### ISSUE TITLE
Can't receive push notifications after a couple of days

### ISSUE THREAD

**Issue by 0x1ad2** [katzer/cordova-plugin-local-notifications#1005]
Hi,

We are using the **cordova-plugin-local-notifications** for sending local push notifications to our users. We recently deployed a stable build where everything was working fine on Android as well as iOS.

After a couple of days testing the app on both platforms the iOS notifications didn't fire anymore we haven't changed our code and tested it on 3 different devices (5s, 6 and 6s).

Does anyone has an idea whats going on?

I read about the scheduling limit https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/WhatAreRemoteNotif.html but we are firing them directly.

Also we tried @ibnbd his solution but that didn't work https://github.com/katzer/cordova-plugin-local-notifications/issues/952

Please help us out!

**Comment by ibnbd** [comment]
Are you using Ionic Framework?
If yes, please go to your project folder and run `ionic platform list`. If your are using cordova only run `cordova platform` and share the output.

Thank You

**Comment by 0x1ad2** [comment]
@ibnbd I'm using Ionic framework this is the output

> Installed platforms: android 4.1.1, ios 3.9.2
> Available platforms: amazon-fireos, blackberry10, browser, firefoxos, webos, windows, windows8, wp8

also this is the plugin output

> com.phonegap.plugins.facebookconnect 1.0.1.1 "Facebook"
> com.unarin.cordova.beacon 3.4.0 "Proximity Beacon Plugin"
> cordova-plugin-app-event 1.1.0 "Application Events"
> cordova-plugin-console 1.0.2 "Console"
> cordova-plugin-device 1.1.1 "Device"
> cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
> cordova-plugin-splashscreen 3.2.0 "Splashscreen"
> cordova-plugin-whitelist 1.2.1 "Whitelist"
> cordova-plugin-x-socialsharing 5.0.10 "SocialSharing"
> de.appplant.cordova.plugin.background-mode 0.6.4 "BackgroundMode"
> de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
> ionic-plugin-keyboard 1.0.8 "Keyboard"
> org.apache.cordova.camera 0.3.6 "Camera"
> org.apache.cordova.file 1.3.3 "File"

**Comment by 0x1ad2** [comment]
I also try to add a simple notification without any dynamic messaging (our app is talking to our API to get the push messages dynamically).

```
console.log('Try to send push notification'); 

cordova.plugins.notification.local.schedule({
    id: 1,
    title: 'Push notification title'
    text: 'Push notification message'
}).then(function () {
    console.log('Push notification send!');
}); 
```

I Xcode logs I only see **Try to send push notification**

Maybe @katzer has an idea?

**Comment by ibnbd** [comment]
Set an unique ID and please update your Cordova iOS `ionic platform update ios`

**Comment by ibnbd** [comment]
It's not push notification, it's local notification. App has to have background mode if you are willing to receive notification in background. And iTunes won't support background mode if it's not a music player. Use push notification plugin http://ngcordova.com/docs/plugins/pushNotifications/

**Comment by 0x1ad2** [comment]
@ibnbd we are creating our ID dynamically using a combination of date, hours, minutes, seconds and milliseconds so it will be unique every time.

Also we've tried to upgrade to iOS cordova 4.1.1 but after that we aren't able to build due to plugin conflicts.

We have background mode enabled.

**Comment by rwillett** [comment]
Is this still an issue? Its not been updated in six months?

**Comment by rwillett** [comment]
No update from original poster so closing.

**Comment by 0x1ad2** [comment]
@rwillett I'm not sure, haven't used this plugin in almost over a year.
