### ISSUE TITLE
Xiaomi Phone

### ISSUE THREAD

**Issue by tusharma12** [katzer/cordova-plugin-local-notifications#1008]
Hello..

Actually the plugin is working fine on all other phones but in case of Xiaomi there is some error.
However if we change the date , all the plugins come instantaneously.

Date = 2016-06-10
Time=20:00:00.0000000
 var schedule_time = new Date((Date  + " " + Time).replace(/-/g, "/")).getTime();
schedule_time = new Date(schedule_time);

  cordova.plugins.notification.local.schedule({
                    id: 1
                    title: reminder,
                    text: remindersasadasd,
                    at: schedule_time
                });

**Comment by snowbreeze** [comment]
How did you fix this? Every xiaomi phone has issue with cordova, with both geolocation and time.
