### ISSUE TITLE
Schedule Repeatedly Not Work

### ISSUE THREAD

**Issue by daniele-sartiano** [katzer/cordova-plugin-local-notifications#1009]
I have a basic schedule:

LocalNotifications.schedule({
          id: 1,
          text: "Single Notification" + new Date(),
          data: { test: 'this_is_a_test' },
          icon: "res://notification/ic_notification",
          every: 'hour'
      });

After 2/3 notifications it stop to notify.
I'm using Ionic 2 and Android. How can I identify the problem?

Thanks in Advance.

**Comment by daniele-sartiano** [comment]
I did another test with "minute" schedule, here the logs of the notifications:

0 Sat Jun 11 2016 20:00:49 GMT+200 ...
1 Sat Jun 11 2016 20:01:59 GMT+200 ...
2 Sat Jun 11 2016 20:02:42 GMT+200 ...
3 Sat Jun 11 2016 20:03:42 GMT+200 ...
4 Sat Jun 11 2016 20:04:42 GMT+200 ...
5 Sat Jun 11 2016 20:05:50 GMT+200 ...
6 Sat Jun 11 2016 20:06:42 GMT+200 ...
7 Sat Jun 11 2016 20:07:59 GMT+200 ...
8 Sat Jun 11 2016 20:08:42 GMT+200 ...
9 Sat Jun 11 2016 20:09:48 GMT+200 ...
10 Sat Jun 11 2016 20:10:50 GMT+200 ...
11 Sat Jun 11 2016 20:12:04 GMT+200 ...
12 Sat Jun 11 2016 20:00:49 GMT+200 ...
0 Sat Jun 11 2016 20:00:49 GMT+200 ...

**Comment by rwillett** [comment]
Is this still an issue? Its over six months old.

**Comment by daniele-sartiano** [comment]
> Is this still an issue? Its over six months old.

Sure. I used a workaround.

**Comment by katzer** [comment]
Please use v0.9-beta. Thanks
