### ISSUE TITLE
notifications show up as "contents hidden" on Android

### ISSUE THREAD

**Issue by ghost** [katzer/cordova-plugin-local-notifications#1012]
All Android notifications seem to show up as "Contents hidden" when the phone is locked.  Is there any way to change that with the plugin - and not a setting on the device?

It looks like the native notification API supports a "visibility" setting based on a fix for a similar issue in phonegap-plugin-push here:

https://github.com/phonegap/phonegap-plugin-push/commit/ceae864264688f9ff17cbdf2e168463dfb397f24

Is it worth adding a similar fix to this plugin?

**Comment by bretanac93** [comment]
Well, I'm brand new using this plugin, but you should check the privacy settings in your phone, cause after Lollipop you have an option to hide the notifications content in the lock screen.

**Comment by josh-m-sharpe** [comment]
Pretty sure the notifications themselves have a privacy setting -- so I think the plugin should allow me to set the notification to "public" or "private" so that it shows up appropriately based on the new phone settings.

**Comment by rwillett** [comment]
Is this still an issue? Its not been updated in six months?

**Comment by rwillett** [comment]
Closed as no response from original poster.
