### ISSUE TITLE
Android crash because of default values + temp fix

### ISSUE THREAD

**Issue by nikoladev** [katzer/cordova-plugin-local-notifications#1013]
On Android the plugin crashes when you send a notification without filling in the values for `every`, `at`, `led`, and/or `color`. It seems that these undefined values get passed to the Java code as `null` and get parsed to ints. However, because they are `null` this doesn't work so well.

For now you can avoid this bug if you make sure to just fill in all the values necessary when calling `schedule()`. Use the default values found [here](https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling#interface) for the values you don't specifically need changed, like so:

``` javascript
cordova.plugins.notification.local.schedule({
        text: 'text',
        title: 'title',
        sound: 'res://platform_default',
        badge: 0,
        id: 0,
        data: null,
        every: '0',
        at: new Date(),
        icon: 'res://icon',
        smallIcon: 'res://ic_popup_reminder',
        ongoing: false,
        autoClear: true,
        led: 'FFFFFF',
        color: '000000'
    }
);
```

And only edit whichever values you need to change.

But a true fix requires defining the default values differently in `local-notification-util.js` in the source code.

**Comment by ben-8409** [comment]
This also happens when I use the color option with a color like this
'#ffddee'. I hope to find the time to be working on a fix soon. Any tips where I should start or find the relevant documentation?

**Comment by nikoladev** [comment]
For fixing the problems with `null` I would just change the default values in `local-notification-util.js` like so:

```javascript
exports._defaults = {
    text:  '',
    title: '',
    sound: 'res://platform_default',
    badge: 0,
    id:    0,
    data:  undefined,
    every: '0', // was undefined
    at:    undefined
};
```

```javascript
defaults.led       = '000000'; // was undefined
defaults.color     = 'FFFFFF';  // was undefined
```

Fixing the default value for `at` will be a bit trickier, as it should default to `new Date()` and that should be done when the notification is created, I figure.

I've switched to using another plugin for notifications, so you might find some ideas in their implementation: https://github.com/ludei/atomic-plugins-notifications

**Comment by rwillett** [comment]
We don't get this with our version of Android on 5 and 6. We don't use the LED's at all and never set them. So is this still an issue? Its nearly six months old.

**Comment by nikoladev** [comment]
I haven't used this plugin for a long time and can't give you an answer. Sorry.
