### ISSUE TITLE
[Question] How to force notification to show on android?

### ISSUE THREAD

**Issue by cescoferraro** [katzer/cordova-plugin-local-notifications#1015]
I got the plugin to work. Its great, but I am not an android user neither have an android to test it with.
With what I got to see from the emulator, notifications do not show when the app is open. It plays a sound and add a bell icon on the status bar. Is this the default behavior? My app wont be scheduling any tasks for the future, it will receive some info via web sockets that I would like to explicitly show to the user. I was expecting something like a ios banner to pop of the screen. Is this possible? I was looking for something better than a Toast

**Comment by rwillett** [comment]
Why not use Toast?

It works very well.

**Comment by rwillett** [comment]
No update from original poster so closing.
