### ISSUE TITLE
Update event callback is passed the original notification, not the updated one

### ISSUE THREAD

**Issue by jim0020** [katzer/cordova-plugin-local-notifications#1016]
On iOS, when a notification is updated using .update(), the registered callback is called but the original notification is passed to the callback, not the new version.  To get the new data for the notification in the update callback I have to call cordova.plugins.notification.local.get( notification.id, callback_to_process_updated_notification ).  Is this the intended behavior?

**Comment by rwillett** [comment]
Is this still an issue? Fill out #1188 with more information. 

As an aside its normally better to kill the old notification and reschedule a new one. Its the same logic but does seem to work.

**Comment by rwillett** [comment]
Closed as no update from original poster.
