### ISSUE TITLE
Odd trigger callback behaviors

### ISSUE THREAD

**Issue by magnars** [katzer/cordova-plugin-local-notifications#1018]
It seems like the `trigger` callback behaves very differently based on the phone's current state. This is on an iPhone6s with iOS 9.3.2.
- If I keep the app open and active, the trigger callback is called, but there is no notification. (expected behavior?)
- If I keep the phone unlocked and active, but background the app, I get the notification, but when tapping the notification, the callback is not triggered.
- If I lock the phone, I get the notification, but when tapping the notification, instead of the callback I see a `TransportError`.

I guess the TransportError is due to some missing white listing of protocols? My config.xml has these allowances:

```
    <allow-navigation href="file:*" />
    <allow-navigation href="*://*.example.com/*" />
    <access origin="*" />
    <access launch-external="yes" origin="mailto:*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
```

Am I missing an intent maybe? I've perused the plugin code, but couldn't find any protocol-ish strings.

As for the second issue, where the callback is never called if the phone is active, why would that be?

Thanks for any help.

**Comment by jim0020** [comment]
Do you get multiple calls on your trigger callback for one notification being triggered?  That's what I'm seeing on iOS.  On android the same code is fine.

**Comment by magnars** [comment]
No, not at all. My problem is that the callback is not triggered (except for in case 1).

**Comment by swamy470** [comment]
I am also facing same issues,couldn't able to find any solution.

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
