### ISSUE TITLE
Android Manifest Permissions Issue

### ISSUE THREAD

**Issue by ashvin777** [katzer/cordova-plugin-local-notifications#1021]
Hi Team,

In the plugin.xml `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` is this really required for this plugin ? I have a security requirement to remove this permission from app.

Please help. I am not using any external storage in my app. Is it ok to just remove it or it is going to impact any functionalities.

**Comment by ecthurlow** [comment]
The plugin does write to the external cache, however starting from 4.4 KitKat no permissions are required to write to the external storage of your own app.

You can use `<uses-permission android:maxSdkVersion="18" android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` instead to only add this permission for versions of android older than KitKat.
https://developer.android.com/guide/topics/data/data-storage.html#AccessingExtFiles
https://developer.android.com/reference/android/content/Context.html#getExternalCacheDir()

**Comment by rwillett** [comment]
Closed as no update from original poster.

**Comment by ashvin777** [comment]
Thanks :)
