### ISSUE TITLE
Unable to receive local notification on ios 10

### ISSUE THREAD

**Issue by sparsh0611** [katzer/cordova-plugin-local-notifications#1024]
The local notifications are working fine on iOS 9 and lower versions. But, in iOS 10 (beta version), no local notification is received. There's no error while scheduling it and 'schedule' method in APPLocalNotification.m runs without error. But, the notification doesn't get fired.

**Comment by gandhiselvarj** [comment]
Can you send me the code for ios 9. I have issue in ios 9.

**Comment by NorthMcCormick** [comment]
I have the same issue. I think it's specifically an iOS 10 beta bug :(

**Comment by NorthMcCormick** [comment]
Beta 2 still has the same issue if anyone is wondering

**Comment by jokiamo** [comment]
Important:UILocalNotification is deprecated in iOS 10. Use UNNotificationRequest instead. A UILocalNotification object specifies a notification that an app can schedule for presentation at a specific date and time.

**Comment by NorthMcCormick** [comment]
Gah I scoured the docs and didn't see that. So basically this plugin is totally useless at this point? Or do the APIs line up pretty well?

Any recommendations for other plugins guys?

**Comment by swamy470** [comment]
#sparsh0611 can you please send me the iOS9 code.

**Comment by sparsh0611** [comment]
@gandhiselvarj @swamy470 Here is my working iOS 9 code. But, it won't work in iOS 10 because of deprecation, as mentioned above .

**Schedule notification:**
`cordova.plugins.notification.local.schedule({
	id: 1,
	title: 'title',
	at: alarmTime,
});`

**On notification receive:** (in app.js)
`$rootScope.$on('$cordovaPush:notificationReceived', function (event, notification) {
        if (notification.alert) {
          navigator.notification.alert(notification.alert);
        }
      });`

**Comment by jokiamo** [comment]
https://github.com/jokiamo/cordova-plugin-local-notifications

**Comment by malloc32** [comment]
For me this update does not work properly, see this post if you hace problems too.
https://github.com/katzer/cordova-plugin-local-notifications/issues/1034?_pjax=%23js-repo-pjax-container

**Comment by tringkishorekumar** [comment]
Deprecation doesn't mean that it wont work, isn't it? I too face the problem. I think the way iOS handled localNotifications have changed that's why it affects UILocalNotifications. #pureAssumptions

**Comment by rwillett** [comment]
Is this still an issue? Its over six months old. It also refers to a Beta of IOS10.

We have IOS10 working.

**Comment by rwillett** [comment]
The code does work in IOS10. Suspect this is an issue with Beta version of IOS10.

Now closed as no update from original poster.
