### ISSUE TITLE
No sound on adroid while notifications are workin as they should

### ISSUE THREAD

**Issue by pawelduszczak** [katzer/cordova-plugin-local-notifications#1029]
I'm ver pleased with Your plugin but i'm having issues with sound option. I'm using newest version of the plugin 0.8.4, cordova 6.2.0
My notificaton call is like below:
`cordova.plugins.notification.local.schedule({
            id: 1,
            title: 'Some test title',
            text:'is this notification with sound?',
            sound: 'file://sounds/sound.mp3',
            icon: 'file://images/icon.png',
            at: new Date()
        });`
Notification is displayed as it suppouse to do, but there is no sound at all. I was trying to set path to file in many ways found on the web but still nothing helps. I've checked path mutiple times so this isn't an issue i thik. Also no errors are thorwn by scripts. All seems to be fine but sound isn't there. Can You provide me some clue what can be the cause?

**Comment by AysadKozanoglu** [comment]
if you are develope for iphone than you have to use .caf files. 

cordova.plugins.notification.local.schedule({
    id: 1,
    text: 'My first notification',
    sound: isAndroid ? 'file://sound.mp3' : 'file://beep.caf',
    every: 'day',
    firstAt: next_monday,
    data: { key:'value' }
})

**Comment by pawelduszczak** [comment]
App is only for android. As far as i was able to find android shouldn't have problems with MP3 or WAV files. At some point i was thinking that maybe my sound is broken, so i downloaded demo app for this plugin and took sounds from that. This however didn't fix my lack of sound issue.

Is it possible that version of cordova or some other installed plugin is the cause?

**Comment by pawelduszczak** [comment]
And issue is solved.

I've figured it out based on some issue not associated with with this plugin at all.

I didn't know that for plaing sound in notifications You also have to have media plugin installed. Suprisingly on docs/wiki is no metion of this dependecy. While installing by cordova command line media plugin isn't istalled automaticly with this plugin. This is worth checking by developers.

**Comment by tucamsam** [comment]
Any thoughts on this? I tried the kitchen sink app and it didn't seem to play any sound either.

**Comment by pawelduszczak** [comment]
If You have installed codova media plugin (as i remember it was native plugin https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-media/) then i have no clue unfortunetly why it's not woking properly. Istalling above plugin solved sound issue for me 100%.

**Comment by rwillett** [comment]
Is this still an issse? If so fill out #1188 with more information.

We just added a custom mp3 sound to an Android 6.0 and it worked fine.

**Comment by rwillett** [comment]
Closed as no update from original poster.
