### ISSUE TITLE
Can we add html tag in text or title ?

### ISSUE THREAD

**Issue by shivam5x** [katzer/cordova-plugin-local-notifications#1030]
Hi,
I am using notification and so i just want to add notification content like - 

"USERNAME", it's time
**row 1** (product 1) PRODUCTNAME
**row 2** (product 2)  PRODUCTNAME

So it is possible to do that.
Is it support bigview ?
Thanks

**Comment by katzer** [comment]
HTML is not possible, but multiple lines or unicode is possible.

**Comment by xeor** [comment]
Is there any api limits? I got some Android notifications that have custom shapes and dynamic content..
