### ISSUE TITLE
Could you provide a type definition for TypeScript?

### ISSUE THREAD

**Issue by glubary** [katzer/cordova-plugin-local-notifications#1033]
That would be great. Thanks.

**Comment by Artfloriani** [comment]
Ionic-Native has implemented this. You can check out at their [repo  ](https://github.com/driftyco/ionic-native/blob/master/src/plugins/localnotifications.ts)or at their [docs ](http://ionicframework.com/docs/v2/native/local-notifications/)

**Comment by rwillett** [comment]
Can this be closed now.

**Comment by kannan8273** [comment]
@Artfloriani The repo URL you have mentioned above is no longer valid. Can you help us to find the type definition file for this plugin?
