### ISSUE TITLE
Uncaught TypeError: Cannot read property 'define' of undefined local-notification.js:1

### ISSUE THREAD

**Issue by claytonseraphin** [katzer/cordova-plugin-local-notifications#1035]
i have this error on console log after adding this
cordova.define("de.appplant.cordova.plugin.local-notification.LocalNotification", function(require, exports, module) {
}); 
And the error is on that line, i mean on the cordova.define..
i dont see how can i resolve this and my cordova version is 5.4.1 please i need help

**Comment by rwillett** [comment]
Is this still an issue?Its over six months old.

**Comment by rwillett** [comment]
Closed as no update from original poster.
