### ISSUE TITLE
Notification.id undefined

### ISSUE THREAD

**Issue by swatislinfy** [katzer/cordova-plugin-local-notifications#1037]
cordova.plugins.notification.local.on("clear", function(notification) {
    alert("cleared: " + notification.id);
});
When I am running this its returning me notification id undefined. I am creating notification by this code:
  $cordovaLocalNotification.schedule({
            id: 1,
            text: 'Its important',
            title: 'Take med',
            icon: "file://img/abc.png",
            sound: "file://audio/abc.mp3",
            headsup: true,
            actions: [{
                    identifier: 'Snoozer',
                    text:'Snoozer',
                    value:0
                },
                {
                   identifier: 'cancel',
                   text: 'cancel',
                   value:1
                }]
        })

**Comment by rwillett** [comment]
Is this still an issue? Its over six months old?

**Comment by rwillett** [comment]
Closed as no update from original poster.
