### ISSUE TITLE
Not working with me on WP8 

### ISSUE THREAD

**Issue by MohamedFekry007** [katzer/cordova-plugin-local-notifications#1039]
please help, local notification not working with me, "listener" almost undefined however event and arguments not null,

file: local-notification-util.js

exports.fireEvent = function (event) {
    var args     = Array.apply(null, arguments).slice(1),
        listener = this._listener[event];

   if (!listener)
      return;
 for (var i = 0; i < listener.length; i++) {
        var fn    = listener[i][0],
            scope = listener[i][1];

```
    fn.apply(scope, args);
}
```

};

**Comment by rwillett** [comment]
Closed as no update from original poster.
