### ISSUE TITLE
After a month localnotificatiion is not working

### ISSUE THREAD

**Issue by Divyaadz** [katzer/cordova-plugin-local-notifications#1040]
Below schedule was working well for a month or so, but suddenly users are not getting notification. Not sure why. Im using build.phonegap. Please let me know your thought.

//Local Notification Scheduler
        cordova.plugins.notification.local.schedule({
                id: 1,
                text: "Test",
                icon: 'res://drawable/icon.png',
                every: 'day',
                at: '07:00 AM',
                led: 'A0FF05',
                data: { secret:'key' }
            }
        );

**Comment by sengmow** [comment]
Hi

This is happening to me and seems like a common issue. Have you found a solution?

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
