### ISSUE TITLE
Localnotification not working after 5 min in background despite backgroundplugin

### ISSUE THREAD

**Issue by polarsbear** [katzer/cordova-plugin-local-notifications#1043]
I have my code scripted that as a certain value changes in firebase, it will launch a notification.
This works till my phone is off for a while, it works when I put it to sleep for 5 min, but after that it just does not work.
When I open the app, I get all the notifications I missed.

Is this an issue or unexpected behavior?

**Comment by mtoo020** [comment]
iOS or Android?

**Comment by loolooii** [comment]
This sounds like iOS and it's exactly the problem that I'm having. Any fix for this?

**Comment by mtoo020** [comment]
iOS puts your app to sleep after 180 seconds if it's in the background. You could use background fetch to gain 30 seconds of execution time every 15 minutes. Would this be frequent enough for you?

https://github.com/transistorsoft/cordova-plugin-background-fetch

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
