### ISSUE TITLE
Are heads-up notifications implemented

### ISSUE THREAD

**Issue by polarsbear** [katzer/cordova-plugin-local-notifications#1044]
Hi, I was wondering if heads-up notifications are implemented?

**Comment by 1337** [comment]
Just tried it. I don't think so.

**Comment by natanraj** [comment]
Any suggestions on how to do heads up notifications?

**Comment by AviShmueli** [comment]
see [1173](ttps://github.com/katzer/cordova-plugin-local-notifications/issues/1173)
