### ISSUE TITLE
Dynamic Text/Title for scheduled messages

### ISSUE THREAD

**Issue by Divyaadz** [katzer/cordova-plugin-local-notifications#1045]
I can display daily scheluded notification but notification text is static. Is there a way to update the  title and text before notification is shown?

 I have tried to use update method inside the trigger function but update function is able to update the title only once and not repetitive

**Comment by philliphicks** [comment]
Hey @Divyaadz, I'd like to implement this functionality too. Did you come up with a solution?

**Comment by hugomosh** [comment]
+1

**Comment by katzer** [comment]
The content is static. You can make use of the update method, however it is not as flexible as you may want.
