### ISSUE TITLE
Local Notifications didn`t working in windows phone universal apps

### ISSUE THREAD

**Issue by MohamedFekry007** [katzer/cordova-plugin-local-notifications#1046]
i`m using IBM worklight to develop windows phone universal app, installed local notification plugin but and when i use, it return undefined.

after debugging, it fails in local-notification-util.js

this._listener[event]; = undefined so it return 

exports.fireEvent = function (event) {
    var args     = Array.apply(null, arguments).slice(1),
        listener = this._listener[event];

```
if (!listener)
    return;

for (var i = 0; i < listener.length; i++) {
    var fn    = listener[i][0],
        scope = listener[i][1];

    fn.apply(scope, args);
}
```

};

**Comment by rwillett** [comment]
Closed as no update from original poster.
