### ISSUE TITLE
pull request to wakeup when notification is triggered

### ISSUE THREAD

**Issue by pierrybos** [katzer/cordova-plugin-local-notifications#1048]
Hi, I do a pull request to 
[https://github.com/vasani-arpit/cordova-plugin-local-notifications](https://github.com/vasani-arpit/cordova-plugin-local-notifications)

using 
[https://github.com/MobileChromeApps/cordova-plugin-background-app](https://github.com/MobileChromeApps/cordova-plugin-background-app)

I can do some tasks on background when a notification is delivered. 

I do tests only on Android, but i believe it can help.

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster,.
