### ISSUE TITLE
How I can get push notification from server in cordova?

### ISSUE THREAD

**Issue by cordova-android** [katzer/cordova-plugin-local-notifications#1050]
In my Cordova app iOS/Android my application will check if there is internet connection it will receive data from server(web service) and use notification

I tried plugin "katzer/cordova-plugin-local-notifications" but it will make notification local from my application not from server or web service or url

I mean when user follow department in my application, he will receive all items and new about this department and newly in notification using response from server

 I need to know how I can do that?

**Comment by MohamedFekry007** [comment]
you need to use this plugin

https://github.com/phonegap-build/PushPlugin

**Comment by rwillett** [comment]
This is what the local notification is supposes to do. You need a different plugin sucg as that suggested by @MohamedFekry007
