### ISSUE TITLE
Android notifications firing more than once. 

### ISSUE THREAD

**Issue by zehni** [katzer/cordova-plugin-local-notifications#1052]
Hey, 

I am building an app that allow people to purchase tickets. 

Case:

When a user purchase 5 tickets, the notification will fire once which is what I want, but on Android it fires 5 times in a row. 

Can someone please advise on what could be the issues. I checked my code more than once, maybe its an issues within the plugin for Android. 

Thank you

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
