### ISSUE TITLE
When notification is clicked app is reloaded and new web view created

### ISSUE THREAD

**Issue by Piranya** [katzer/cordova-plugin-local-notifications#1053]
I have an app where when notification is clicked user is redirected to different pages depending of data. Sometimes it works but most of the times when notification is clicked app is reloaded and new web view created that loads default page (old view triggers associated event (is redirected to proper page) but view is hidden - i can see it in chrome://inspect/#devices module).
Is there any settings I should set on plugin?

**Comment by lysuse** [comment]
I hava some problem

**Comment by netomia** [comment]
Sounds like it could be related to this:

https://github.com/katzer/cordova-plugin-local-notifications/issues/682

Your app might be crashing and reloading when you click the notification because of this.

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
