### ISSUE TITLE
Error: exec proxy not found for :: LocalNotification :: deviceready 

### ISSUE THREAD

**Issue by alexalghisi** [katzer/cordova-plugin-local-notifications#1056]
When I install the plugin and try to run for the browser "cordova run browser" I get this error even tho I didn't add ANY CODE at all :).

**Comment by MrLugh** [comment]
Same issue! is there a workarround?

**Comment by MrLugh** [comment]
Any update on this?

**Comment by ericpennachini** [comment]
Same issue too with browser platform!

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no update from original poster.

**Comment by gingsero** [comment]
Hi, did you clear this problem?? I have a same issue... How to solve that??

**Comment by rwillett** [comment]
I suggest you raise a new issue using the template in #1188. There's far too little information to resolve it here and this thread is closed.
