### ISSUE TITLE
Schedule notification for an event happening in 2 weeks

### ISSUE THREAD

**Issue by veken1199** [katzer/cordova-plugin-local-notifications#1058]
I want to schedule a notification for a notification happening in 2 days from the current date, how can I do this, and is it okey if the the app I killed...should the app be running in the background in order for the notification to be triggered ???

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
