### ISSUE TITLE
Longpolling notification

### ISSUE THREAD

**Issue by dicoy** [katzer/cordova-plugin-local-notifications#1059]
I'd like to run some js, before displaying the notification.
Example:
Every Friday at 8PM my app would run an ajax request to my server to check if there's a notification to show, and if so. the ajax request would respond with the text and all the details about the notification it's supposed to show.

Would that be possible with this plugin?

**Comment by Tawpie** [comment]
I don’t think so. When the notification fires, it’s initially handled by the OS (your app may be backgrounded or killed) and the OS will put up a notification that has the text you scheduled—then the OS will signal your app that a notification has fired. When your app is finally running you can do what you need, but the original notification in the notification tray will have had the text you specified when you scheduled it. In other words, the OS will post the scheduled text as a clue to the user that they may want to interact with your app, but this plugin isn’t intended to be a cron job. On Android you could possibly do that with a service running in the background, but to my knowledge iOS prohibits that kind of thing.

**Comment by dicoy** [comment]
well you could reference the notification id and run an update on it right?
If that's possible, that would be enough for me

**Comment by Tawpie** [comment]
Sure… but your app has to know what time it is so it knows to make the AJAX call doesn’t it? When it’s not actively running, that’s rather a challenge.

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188 otherwise please close it.

**Comment by rwillett** [comment]
Closed as no response from original poster.
