### ISSUE TITLE
[Android] can not remove notification from notification drawer

### ISSUE THREAD

**Issue by wewess92** [katzer/cordova-plugin-local-notifications#1060]
I have 4 notifications, all of them are working fine, but I can't remove first notification (id : 1) from notification drawer. 

Here is how I schedule the notifications (triggered with click action on button).

> ```
>          var defaultOptions = {
>                 maximumAge: 75000,
>                 timeout: 10000,
>                 showErrors: true
>             };
>             navigator.geolocation.getCurrentPosition(function(position) {
>                 var current_lat = position.coords.latitude;
>                 var current_long = position.coords.longitude;
>                 $.get(action, function(data) {
>                     var explode = data.split(';');
>                     if (explode[0] == "success") {
>                         var now = new Date().getTime(),
>                             schedule1 = new Date(now + 1 * 1000 * 30),
>                             schedule2 = new Date(now + 1 * 1000 * 60),
>                             schedule3 = new Date(now + 1 * 1000 * 90),
>                             schedule4 = new Date(now + 1 * 1000 * 120);
>                         cordova.plugins.notification.local.schedule([{
>                             id: 1,
>                             title: 'Reminder',
>                             text: ' Test (30 sec)',
>                             at: schedule1,
>                             icon: "res://icon.png",
>                             ongoing: false
>                         },
>                         {
>                             id: 2,
>                             title: 'Reminder',
>                             text: 'Test (60 sec)',
>                             at: schedule2,
>                             icon: "res://icon.png",
>                             ongoing: false
>                         },
>                         {
>                             id: 3,
>                             title: 'Reminder',
>                             text: 'Test (90 sec)',
>                             at: schedule3,
>                             icon: "res://icon.png",
>                             ongoing: false
>                         },
>                         {
>                             id: 4,
>                             title: 'Reminder',
>                             text: 'Test (120 sec)',
>                             at: schedule4,
>                             icon: "res://icon.png",
>                             ongoing: false
>                         }]);                            
>                         $('#overlay2').remove();
>                     } else if (explode[0] == "fail") {
>                         $('#overlay2').remove();
>                         return false;
>                     } else {
>                         cordova.plugins.notification.local.cancel([1, 2, 3, 4]);
>                         $('#overlay2').remove();
>                         return false;
>                     }                        
>                 });
>             }, function(error) {
>                 handleLocationError(true, infoWindow, map.getCenter());
>             }, defaultOptions);
> ```

There's no error in console.

Thanks

Can I use this plugin together with background geolocation (https://github.com/mauron85/cordova-plugin-background-geolocation) ?

**Comment by rwillett** [comment]
Is this still an issue? Its over six months old?

**Comment by rwillett** [comment]
Closed as no update from original poster.
