### ISSUE TITLE
getAllScheduled returns empty object every time

### ISSUE THREAD

**Issue by theblindprophet** [katzer/cordova-plugin-local-notifications#1065]
I have successfully created the notifications in my Ionic2 app. When I enter the page and call the statement:

`this.allReminders = LocalNotifications.getAllScheduled();`

which always returns the object:

`{"_zone_symbol_state":null, "_zone_symbol_value":[]}`

No matter how many notifications are currently scheduled, that object is always returned.

```
import { Component } from "@angular/core";
import { NavController, Alert } from 'ionic-angular';
import { LocalNotifications } from 'ionic-native';

@Component({
    templateUrl: 'build/pages/reminders/reminders.html'
})
export class RemindersPage {

    getReminders() {
        this.allReminders = LocalNotifications.getAllScheduled();
    }
    ngOnInit() {
        this.getReminders();
    }

}
```

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
