### ISSUE TITLE
Alarm event without notification

### ISSUE THREAD

**Issue by Kobzol** [katzer/cordova-plugin-local-notifications#1066]
Is it possible to schedule an alarm without actually popping the notification and just executing the trigger callback?
I know that there is a dedicated plugin for that (https://github.com/wnyc/cordova-plugin-wakeuptimer), but it doesn't support Windows Phone.
I tried canceling the notification in it's trigger event, but it doesn't work reliably.

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
