### ISSUE TITLE
Example of polling request to the server while in background.

### ISSUE THREAD

**Issue by Natanael1234** [katzer/cordova-plugin-local-notifications#1068]
The documentation says:

> # Examples of Notification Usage
> 
> Local notifications are ideally suited for applications with time-based behaviors, such as calendar and to-do list applications. Applications that run in the background for the limited period allowed by iOS might also find local notifications useful.
> For example, **applications that depend on servers for messages or data can poll their servers for incoming items while running in the background; if a message is ready to view or an update is ready to download, they can then present a local notification immediately to inform their users**.

[Source](https://github.com/katzer/cordova-plugin-local-notifications#how-they-appear-to-the-user).

I need to get data from the server to devide if I will show or not a message to the user in the notifications. Perhaps I would just download data in background periodically.

The problem is, when I close, by pressing back key or via side menu, the notification icon appears in notification area but data is not immediately delivered and processed to my app, so I cannot to decide if I will show or not the notification until the user clicks on it.

When the app is just minimized, by pressing home key, the notification is delivered directly to the app.

Could someone show me a example on this?

**Comment by rwillett** [comment]
You  cannot poll the server whilst an IOS app is in the background. Your JavaScript HTTP connection will not work, neither will timers.

If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
