### ISSUE TITLE
Error: Failed to fetch plugin https://github.com/katzer/cordova-plugin-local-notification via git.

### ISSUE THREAD

**Issue by FrancescoMussi** [katzer/cordova-plugin-local-notifications#1069]
I have tried to install the plugin in the following ways:

```
cordova plugin add https://github.com/katzer/cordova-plugin-local-notification
cordova plugin add de.applant.cordova.plugin.local-notification
cordova plugin add de.appplant.cordova.plugin.local-notification@0.8.1
```

None of this worked for me.
I get the following error:

```
Error: Failed to fetch plugin https://github.com/katzer/cordova-plugin-local-notification via git.
Either there is a connection problems, or plugin spec is incorrect:
    Error: git: Command failed with exit code 128 Error output:
Cloning into '/tmp/git/1470829120089'...
remote: Repository not found.
fatal: repository 'https://github.com/katzer/cordova-plugin-local-notification/' not found
```

Trying to fix i have done the following:
- update cordova to 6.3.0
- install git globally

Same error.

I have seen there are similar issues already closed but none of them helped me.

Can you please tell me why is not installing the plugin properly?

Thank you!

**Comment by Tawpie** [comment]
try adding an 's' to the end of the plugin name
`cordova plugin add de.applant.cordova.plugin.local-notifications`

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
