### ISSUE TITLE
Group multiple notification

### ISSUE THREAD

**Issue by renanbs** [katzer/cordova-plugin-local-notifications#1073]
How can I group multiple notification in a larger one?
Just like it is done in WhatsApp when there is more than one person/group chatting at the same time.

**Comment by ravindranpandu** [comment]
Hi i have the same issue, no matter how many notification i get i should only have one notification icon in the status bar, right now say if i have 10 notification it shows 10 icons in the status bar, is there a way to achieve it?

**Comment by ravindranpandu** [comment]
@renanbs did you got a solution for this?

**Comment by renanbs** [comment]
Nope

**Comment by rwillett** [comment]
This can't be done at present.
