### ISSUE TITLE
Is there a way to track triggered local notification when app is in background on ios?

### ISSUE THREAD

**Issue by methukumalli** [katzer/cordova-plugin-local-notifications#1077]
I'm trying to integrate mixpanel into ios app.

I would like to track each triggered local notification. When the app is in foreground, I was able to get this to work if I add mixpanel tracking code in didReceiveLocalNotif‌​ication method.

But, when the app is in the background, is there a way to track the triggered notification event?

Any help is appreciated.

Thanks,
Lakshmi.

**Comment by sajangurung2015** [comment]
hi,
did u get it 2 work ? i am looking exactly for the same

**Comment by estvmachine** [comment]
+1. Is seems are various tickets for this: #1108 , #1167  , #628

**Comment by katzer** [comment]
No, not with official APIs - see the background-mode plugin. There are some background modes to keep your app awake in background. However that doesn't mean necessarily that the scheduler will call the delegates in background.
