### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by tverilytt** [katzer/cordova-plugin-local-notifications#1079]
Hi!

I commented out the WRITE_EXTERNAL_STORAGE permission in the plugin.xml. Things still seems to work nice. Is the permission required in any particular situation?

cheers
-jo

```
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

**Comment by kasp1** [comment]
My question as well. This is one of the permissions people seem to be sensitive about. It's slowed down my installs growth when I added this permission requirement to one of my apps. It would be better to leave it out if it's not necessary of the plugin itself.

**Comment by wioux** [comment]
#1021 says the permission is only required on androids older than 4.4 KitKat.

**Comment by red-led** [comment]
If it's true, [android:maxSdkVersion="18"](https://developer.android.com/guide/topics/manifest/uses-permission-element.html) in [plugin.xml](https://github.com/katzer/cordova-plugin-local-notifications/blob/master/plugin.xml#L131) should solve problem.

**Comment by katzer** [comment]
I see - I will remove the permission.
