### ISSUE TITLE
Notification while app is in foreground

### ISSUE THREAD

**Issue by Kageyo** [katzer/cordova-plugin-local-notifications#1081]
Hello,
Is it possible to display notification while the application is in foreground ?

It works great on Android but on iOS, there is no display of the notification, the notification only show up if the app is in background.

I've tried this :

cordova.plugins.notification.local.on("trigger", function (notification, state) {
  var message = 'Notification with ID is triggered: ' + notification.id + ' state: ' + state;

  navigator.notification.alert(message, function() {
    cordova.plugins.notification.local.clear(notification.id, function() {
      navigator.notification.alert("Notification cleared from notification center");
    }, 'Notification triggered', 'Close');
  });
});

Found at http://plugins.telerik.com/cordova/plugin/localnotification
Which works but it's an alert, I want the native notification while the app is in foreground.

Is it possible ?

Thanks in advance

**Comment by uareurapid** [comment]
that´s just how IOS notifications work, not plugin related

**Comment by ben-8409** [comment]
So we cannot expect local notifications to be working when the app is in foreground?

**Comment by uareurapid** [comment]
exactly, and imo it doesn´t make much sense in other way.. usually they´re like reminders or they are used to trigger some action inside the app, but you´re already using the app anyway, a notification will only disturb the user

**Comment by gianpaj** [comment]
@Kageyo how did you make a foreground notification appear on Android?
Using the example in the readme file the notification center is hidden or collapsed (you only see the bell icon).

I would like the full notification to appear in the foreground. Thanks

**Comment by rwillett** [comment]
Closing this as this is expected IOS behaviour
