### ISSUE TITLE
How I make to use various icons in multiple screen sizes

### ISSUE THREAD

**Issue by LeandroFranciscato** [katzer/cordova-plugin-local-notifications#1083]
I can't adding the project's icon, only web icons????

**Comment by LeandroFranciscato** [comment]
It works. As below:
`icon: "/platforms/android/res/drawable-mdpi/icon.png"`

But have a question, how I make to use various icons in multiple screen sizes?

**Comment by rwillett** [comment]
What has this to do with local notifications?

If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
