### ISSUE TITLE
iOS local notification no sound or display an alert when app is foreground

### ISSUE THREAD

**Issue by fenglu09** [katzer/cordova-plugin-local-notifications#1084]
There is no sound or  display an alert when my app is foreground。 
my code：

```
 cordova.plugins.notification.local.schedule({
                id: id,
                title: title,
                text: content,
                data: data
                badge: 1
            });
```
by the way， the `badge` property not work in android too.

cordova : 6.1.1 
ios: 9.3.5
cordova-ios: 4.1.1

**Comment by uareurapid** [comment]
that´s iOS specific, not related with the plugin, notifications are not shown when the app is in foreground

**Comment by fenglu09** [comment]
is there any ways to show the notifications when the app is in foreground? I don't know much about Object-C

**Comment by uareurapid** [comment]
@fenglu09 No there isn´t . That´s the way they work on IOS. The system doesn´t deliver notifications while the app is in foreground

**Comment by fenglu09** [comment]
All right. Thanks anyway.

**Comment by kulinsj** [comment]
Starting in iOS 10, you can now actually display the notification when the app is in the foreground by using the appropriate arguments in the completion handler in the  UNUserNotificationCenterDelegate

https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc

**Comment by uareurapid** [comment]
@kulinsj indeed, now on iOS 10 it is possible, since the notification is delivered to the app, while before it was delivered to the OS
