### ISSUE TITLE
Clear all notifications when app close

### ISSUE THREAD

**Issue by szado** [katzer/cordova-plugin-local-notifications#1086]
I want to clear all notifications when you close the application but without using "pause" event (pause =/= close, it's matter in my case). How to do it?

**Comment by ammichael** [comment]
There should be a way as a native app, but I don't think it's possible using hybrid ways.

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
