### ISSUE TITLE
Issue with Click / Trigger / autoClear iOS

### ISSUE THREAD

**Issue by plantastika** [katzer/cordova-plugin-local-notifications#1087]
i try on my App on iOS 9 but the click/Trigger and the autoclear option does not work

example:

cordova.plugins.notification.local.schedule({
id: 123,
text: 'This is my notification',
autoClear: true,
sound: sound,
badge: 1
});

---

cordova.plugins.notification.local.on("click", function (notification) {
alert("user clicked on notification");
});

i try this too but does not work either....

cordova.plugins.notification.local.on("click", function (notification) {
if (notification.id == 123) {
alert("user clicked on notification");
}
});

---

somebody???

**Comment by NateOwen** [comment]
Same

**Comment by inyourhands** [comment]
Hi~ I found the trick to this problem.
Put below code after cordova.js import script tag.

ex)

```
<script type="text/javascript" src="cordova.js"></script>

<script type="text/javascript">
if (window.cordova) {
    window.g_event_interval = setInterval(function() {
        if (cordova.plugins && cordova.plugins.notification && cordova.plugins.notification.local) {
            clearInterval(window.g_event_interval);
            window.g_event_interval = null;

            cordova.plugins.notification.local.on('click', function (notification) {
                console.log('notification clicked');
            }, this);
        }
    }, 10);
}
</script>
```

It will be fire after notification click when app terminated.

But, this trick is't perfect solution.
Just use refer.

Hope this helps.

I'm sorry to have enough English.

**Comment by katzer** [comment]
Please try again with 0.9-beta. Please reopen if its still a topic. Thanks
