### ISSUE TITLE
Check if notification has been missed

### ISSUE THREAD

**Issue by keithpickering** [katzer/cordova-plugin-local-notifications#1088]
Is there a way for me to determine if a notification remains unread X minutes after it appears?

**Comment by chmac** [comment]
@keithpickering I'd guess from the docs (haven't used this plugin myself yet) that you could do this by keeping track of what time you scheduled the notification for, and then watching for the `click` event when the notification is opened. Between that and knowing the current time, you can answer the question.

**Comment by rwillett** [comment]
Is this still an question? Its been nearly six months,

**Comment by rwillett** [comment]
No update from original poster so closing.
