### ISSUE TITLE
Notification not getting triggered when the app is being terminated in Android

### ISSUE THREAD

**Issue by rajesh-iosdev** [katzer/cordova-plugin-local-notifications#1089]
I've scheduled a notification after 5 mins, and then if i kill the app from the multitasking window. The scheduled notification is not getting added to the notification drawer in Android, but it happens in iOS

**Comment by LeandroFranciscato** [comment]
Hello @rajesh-iosdev. I got the same issue.
I recommend you to use the [Cordova-plugin-background-mode](https://github.com/katzer/cordova-plugin-background-mode) to keep your app awake, even in the silence mode.

**Comment by sengmow** [comment]
Hi
I have same issues. In addition, repeating notifications don't seem to work "consistently" after running for some time. I tested by scheduling multiple notifications that repeat every hour. The inconsistency happened even if I left the app running - I think Android (did not test on iOS) will just push it to the background anyway.

I haven't tried running app with the background mode plugin. Does the app get killed if you clear all apps using the hard button? Also, I am just being mindful there is a message on the background mode download page that says "The plugin focuses on enterprise-only distribution and may not compliant with all public store vendors." 

Thanks.

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.

**Comment by sengmow** [comment]
Hi Rob

I am retesting this scenario - leaving the scheduled notification 1 day, 1
week and 1 month. This time without the "every" i.e. scheduled the
notification only once. Hope the problem was due to the repeating (every)
notification schedule. Will let you know.

Thanks.

**Comment by sengmow** [comment]
Hi

I ran the app on Samsung S5 and Mi4. It does not work on Mi4 - after I
exited the app.

On Samsung S5, the notifications were fired after 1, 2 and 7 days as
scheduled. The last notification scheduled is end of month. So far, seems
to be ok if "every" is not used in the notification schedule.
