### ISSUE TITLE
More complex recurrent scheduling

### ISSUE THREAD

**Issue by berardo** [katzer/cordova-plugin-local-notifications#1090]
Hi,

I'm going to implement a calendar solution with recurrent events.
That will allow users to schedule events in a more complex timetable e.g. repeat every week, but just on Mondays and Wednesdays excluding particular dates or every last Wednesdays of the month.
I'm not storing event occurrences but their matrices with rrules to generate events when they're needed.
I was wondering if there is a chance to schedule a notification per matrix and have them happening based on each calculated event. Otherwise I'll have to face a kind of bulk scheduling when an event is created, store all notification ids to cancel in case of having it redefined, which doesn't make sense to me.

Any thoughts will be very appreciated.

Thanks

**Comment by rwillett** [comment]
You would have to write this yourself. There is nothing in the plugin that does this.

**Comment by katzer** [comment]
@berardo Such things are possible since 0.9-beta

> repeat every week, but just on Mondays

```js
trigger: { hour: 9, minute: 0, weekday: 1 }
```

> every last Wednesdays of the month

```js
trigger: { hour: 9, minute: 0, weekday: 3, weekdayOrdinal: 4 } // 4th Wednesday of the month
```
