### ISSUE TITLE
iOS Notification Only Works Once

### ISSUE THREAD

**Issue by mishawagon** [katzer/cordova-plugin-local-notifications#1091]
Dear Katzer,

Thank you for your fantastic work on this plugin. I am encountering a small problem where iOS notification only happens after a fresh app reinstall, but not after that. Here is how I am scheduling. Any thoughts would be greatly appreciated. FYI I am trying to keep the id unique also.

```
 cordova.plugins.notification.local.schedule({
                      id: notification_id,
                      text: "Incoming!",
                      at: noti_date,
                  });
```

**Comment by NateOwen** [comment]
If you're using the same notification_id it may be just updating the old notification instead of creating a new one.

**Comment by mishawagon** [comment]
Yes indeed. Thanks!
