### ISSUE TITLE
Phonegap Build error (Android)

### ISSUE THREAD

**Issue by reijmer** [katzer/cordova-plugin-local-notifications#1094]
When trying to build with Phonegap Build, the following error appears.

`Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: LocalNotification.java`

**Comment by NateOwen** [comment]
I'm using this one and it builds:

<plugin name="de.appplant.cordova.plugin.local-notification" spec="0.8.4" />

**Comment by reijmer** [comment]
I was using the same. I tried creating a new app on Phonegap build. No success.

**Comment by rwillett** [comment]
If this is still a problem, please update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no response from original poster.
