### ISSUE TITLE
Past Date notification not getting triggered

### ISSUE THREAD

**Issue by sahildaga95** [katzer/cordova-plugin-local-notifications#1097]
Hi,
I am using your plugin in IONIC 2.
When i call the schedule notification function at 2 pm and the time of notification to be displayed is 10 am of the same day. The notification should automatically get triggered but that is not the case it gets triggered after some random time.
But if i call the schedule notification function at suppose 9:55 am then the notification of time 10 am gets displayed easily.
Moreover it works how it should be one out of five times.

**Comment by rwillett** [comment]
If this is still a problem, please update using the template in #1188

**Comment by rwillett** [comment]
Closed as moo response from original poster.
