### ISSUE TITLE
Multiple notifications coming up in IOS for single schedule, works fine in android.

### ISSUE THREAD

**Issue by vishnurs** [katzer/cordova-plugin-local-notifications#1099]
Notification scheduled once is triggered thrice or four times in IOS. At first shot it comes thrice and second times it is triggered four times. Works fine in android.

**Comment by rupalpatel0008** [comment]
I am also having this issue.

**Comment by BoBoRepo** [comment]
I am also having this issue on iOS. I guess it occurs after app update or maybe the plugin doesn't update notifications with an existing id. any ideas to solve this bug ? Our users are upset about this spam issue

**Comment by rwillett** [comment]
Is this still a problem?

**Comment by rwillett** [comment]
Closed as no response from original poster.
