### ISSUE TITLE
how can I play a sound from the cordova.file.dataDirectory?

### ISSUE THREAD

**Issue by hounsellal** [katzer/cordova-plugin-local-notifications#1100]
It looks like it will only read files from within the www folder which is readonly.

I want to download a file dynamically and then schedule a notification for that sound file to be played.

Is this possible?

**Comment by rwillett** [comment]
If this is still an issue update with the template in #1188

**Comment by rwillett** [comment]
Closed as no update from original poster.

**Comment by ShakeelBeyondvision** [comment]
Please reopen and give any working example of this issue. I am also facing this issue in my app and want to solve this problem for ios. In android it works perfectly with cordova.file.externalDataDirectory. But in ios it plays default notification sound
