### ISSUE TITLE
iOS 10 badge number not updating

### ISSUE THREAD

**Issue by craig-at-rsg** [katzer/cordova-plugin-local-notifications#1101]
Updating badges isn't working for me for iOS 10, but it works in previous iOS versions. Is this a known issue? A bug with iOS 10? Anyone have any advice or workarounds? I'm surprised I wasn't able to find a report for this issue already.

**Comment by sKuD51** [comment]
on iOS 10 I can't have a notification display. You have it ?

**Comment by sKuD51** [comment]
I testing badge and it'works form me on iOS10 : example : cordova.plugins.notification.badge.set(10);
I'have the cordova-plugin-badge installed

**Comment by craig-at-rsg** [comment]
Does this plugin (katzer/cordova-plugin-local-notifications) support badge numbering in iOS 10? It works in previous iOS versions without an additional plugin.

**Comment by katzer** [comment]
Please use 0.9-beta - Thanks
