### ISSUE TITLE
Trigger loop when clearing from trigger event on iOS

### ISSUE THREAD

**Issue by Chuckytuh** [katzer/cordova-plugin-local-notifications#1102]
``` javascript
cordova.plugins.notification.local.on("trigger", function(notification) {
    console.log("triggered");
    cordova.plugins.notification.local.clear(notification.id);
});
```

**This affects only repeating notifications.**

The example code above results on a lot of `triggered` console log outputs and the reason for it is that, clearing on iOS is a result of canceling a notification and rescheduling it. The problem with this is that, by doing so like on the snippet above, what happens is:
1. User schedules a repeating notification
2. The notification is triggered on `didReceiveLocalNotification` that fires the trigger event into JS side
3. On the JS side, the trigger callback executes the clear action
4. On the native side the clear action cancels the notification but, because it is a repeating notification, re-schedules it with the same fireDate. Since the fireDate of the newly scheduled notification is exactly equal as the time of the execution of the fireevent from 2. then it retriggers the notification, hence the loop!

**Comment by rwillett** [comment]
Closed as no update from OP.
