### ISSUE TITLE
capture click event without redirect to app.

### ISSUE THREAD

**Issue by Souras** [katzer/cordova-plugin-local-notifications#1106]
Hi,

Great Plugin!!!. I want to capture notification click event without redirecting to app it should stay on notification tray after clicking. App state must be foreground or background. Just like music app do in next, play and pause event.

Thanks,

**Comment by rwillett** [comment]
I don't think that you can do this with this plugin. You will need to code this directly.

**Comment by rwillett** [comment]
Closed as no update from original poster.
