### ISSUE TITLE
trigger event is not firing anything when app is in background but fires in foreground

### ISSUE THREAD

**Issue by sajangurung2015** [katzer/cordova-plugin-local-notifications#1108]
the trigger event is not firing anything when the app is in background but fires in foreground .. is trigger event not supposed to work in background ?

**Comment by pan100** [comment]
+1

**Comment by Manikandan85** [comment]
+1

**Comment by Manikandan85** [comment]
@sajangurung2015 Can you able to solve this issue?

**Comment by sajangurung2015** [comment]
@Manikandan85 No, I have not been able to solve it .. I tried to make it happen using cordova background plugins too.. But everything runs in background  not the TRIGGER event callback .... Some more researching led me to find out that it uses didRecieveLocalNotifications ios delegate which runs in foreground only not in background ... so just want to know if the plugin author have some solution for this...

**Comment by Manikandan85** [comment]
Hi @sajangurung2015 ,

Thanks for the update. I too hope that there will be a solution for this. I will update here if I can able to fix this.

**Comment by sajangurung2015** [comment]
my app  strictly requires local notification .. so i am desperately searching for workaround for this ... but if ur app requirement is not as strict as mine , u can use remote push notification which allows provides you with handlers to perform background fetch upon recieving the remote notifications .... so far i see no way to do so with local one ..

**Comment by estvmachine** [comment]
+1

**Comment by tadabanri** [comment]
+1

**Comment by MeggSan** [comment]
@sajangurung2015 Have you solved this issue now?

**Comment by katzer** [comment]
@sajangurung2015 @MeggSan 
The `trigger` event only works when app is running in foreground.
