### ISSUE TITLE
'deviceready' not firing with this plugin

### ISSUE THREAD

**Issue by zoxerus** [katzer/cordova-plugin-local-notifications#1109]
when I use this plugin in my ionic app the 'deviceready' event is never fired and I get a message on the console 'deviceready' has not fired after 5 seconds

**Comment by milamber112** [comment]
I have the same problem here and the plugin doesn't work without that working. Could you guys get a fix going, or a workaround or something?

**Comment by rwillett** [comment]
deviceready is a necessary part of every cordova app. This plugin does not interfere with it. 

Your problem is elsewhere.
