### ISSUE TITLE
Local Notification not working in iOS 10.0.2 

### ISSUE THREAD

**Issue by shivam5x** [katzer/cordova-plugin-local-notifications#1110]
Hi katzer,
   It is great to use your plugin , i know we all facing situation around ios 10 , but i do believe you and your team will be able find solution. 
I am following   cordova plugin add https://github.com/acianti/cordova-plugin-local-notifications but getting notification when app is only in background mode.
I hope , i will get solution.

Thanks
Shivam

**Comment by artursbraucs** [comment]
Hi! For me also not working on iOS 10. Before iOS update there was no problems.

**Comment by Leomhl** [comment]
I have the same problem

**Comment by ciossi** [comment]
I have the same problem. On iOS 10.0.1 notification fired with sound. On iOS 10.0.2 notification fired without sound.
I use these paths: sound: isAndroid ? 'file://sound.mp3' : 'file://beep.caf',

Thanks

**Comment by rickywong-arbaholdings** [comment]
not working :( on iOS 10.2

**Comment by JLNNN** [comment]
See here: #1096

**Comment by rejhgadellaabsl** [comment]
+1

**Comment by grahamj** [comment]
+1

**Comment by grahamj** [comment]
Fix here https://github.com/katzer/cordova-plugin-local-notifications/pull/1107

**Comment by rwillett** [comment]
Is this still a problem. If so update with #1188.

**Comment by rwillett** [comment]
Closed as no update from original poster.
