### ISSUE TITLE
How do i set two hours?

### ISSUE THREAD

**Issue by viniciusgcweb** [katzer/cordova-plugin-local-notifications#1111]
Please, I need help to set two hours or more in my project.

The variable "every" not work when I set in seconds, exemple: every: 120, // 2hours.

Code:
cordova.plugins.notification.local.schedule({
                id: id,
                title: title,
                text: message,
                firstAt: schedule_time,
                every: 120,
                icon: 'res://ic_stat_remedio.png',
                color: '00AD9B'
            });

**Comment by katzer** [comment]
With 0.9-beta

```js
cordova.plugins.notification.local.schedule({
id: id,
title: title,
text: message,
trigger: { every: 2, unit 'hour' },
icon: 'res://ic_stat_remedio.png',
color: '00AD9B'
});
