### ISSUE TITLE
Question - Image on local notifications

### ISSUE THREAD

**Issue by natanraj** [katzer/cordova-plugin-local-notifications#1113]
can you please help how i can show a background image on a notification? in some thread I saw mentioned about attaching a banner on 'trigger' event . How to do it? And can the banner point to non-assets like /image folder or src like http ? Please kindly help.

This is a big decision for my client to use this plugin on something else to look for.

**Comment by tsukasa1989** [comment]
As far as I can read there are some options to define an URI, by http, path or res. See the link below:
https://github.com/katzer/cordova-plugin-local-notifications/wiki/10.-URIs

**Comment by natanraj** [comment]
@tsukasa1989 ...I tried. it doesn't work in my tabris.js based Development.  Were you successful ever ?

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no update from original poster.
