### ISSUE TITLE
Notification not showing on notificaion bar on ios 10 

### ISSUE THREAD

**Issue by ajaysaini95700** [katzer/cordova-plugin-local-notifications#1115]
if app is in background then notification show on notification bar but if it is in foreground then notification is triggered successfully but notification does not show on notification bar on ios 10.
it is working fine on ios 9.

**Comment by neetuagw** [comment]
I am having the same issue in iOS 10

**Comment by rejhgadellaabsl** [comment]
I think I'm seeing this too (or the guy who tests our app on iOS 10 is). He doesn't see the notifications in the notif area. It works fine on iOS9

**Comment by rwillett** [comment]
This is the way IOS 10 works, its different to IOS 9.

**Comment by rwillett** [comment]
Closing as working as designed.
