### ISSUE TITLE
Delay for one time notification

### ISSUE THREAD

**Issue by al922001** [katzer/cordova-plugin-local-notifications#1116]
Hi there, is there a reason I have a delay for one time notifications. The notification appears something like 5 seconds after the command sent. Thanks

**Comment by zocheyado** [comment]
I too would like this, there seems to be almost no documentation on the proper format in setting a notification besides every week which is pointless.

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no update from original poster.

**Comment by leorajdsouza** [comment]
works fine in android version below 6.0. But in 6.0 there is delay around 4 -5 seconds

**Comment by MisterDev** [comment]
I've the same problem. 4-5 seconds

**Comment by rwillett** [comment]
There is no guarantee of a specific time delivery in Android with this version of the code. A delay of 4-5 secs is normal. 

There is an option for more exact time delivery in later versions of Android but this package does not have this option.

**Comment by MisterDev** [comment]
Nice to know! If you have any tip on what to look at to fix this in my app I would appreciate. I may also make a PR

**Comment by rwillett** [comment]
I'm not the author so not sure what to change. Other threads have commented on this, there may be fixes in their threads. 

Also your code fragment of 

```
at: new Date().getTime()
```

should be a few seconds in the future.  

What is your use case that requires accuracy of a less than 5 secs? Whilst it may be nice to have it this accurate, unless you are into timing events, its a little difficult to imagine why a delay of 5-6 secs is that big a deal. If it is that big a deal, then use a different plugin and use a notification like Toast.

**Comment by MisterDev** [comment]
A native app can show notifications immediately, whilst this is not necessary it would be nice. Why should I make do with this if there's a (probably easy) way to fix it?

You're right about adding a short delay.
