### ISSUE TITLE
Notification delay after closing an app

### ISSUE THREAD

**Issue by Kradre** [katzer/cordova-plugin-local-notifications#1117]
When im trying to call instant notification on android 5.0.1 and lower, it works perfectly fine.
But when im trying to call in on 5.1 and higher versions, notification showing up after 4-5 minutes or instantly after closing an app.

**Comment by rwillett** [comment]
Is this still an issue? If so fill out #1188

**Comment by rwillett** [comment]
Closed as no response from original poster.
