### ISSUE TITLE
ios9 sound cannot play

### ISSUE THREAD

**Issue by jason5149** [katzer/cordova-plugin-local-notifications#1118]
version: 0.8.4
cordova: 6.3.1

I using this plugin to play notify sound.
Now I have an issue, below is the key code:

////////////////////////////////////////////////////////////////////////////

```
var id = isIOS ? event.order_id : event.extras.order_id;
var alert = isIOS ? event.aps.alert : event.alert;
var sound = isIOS ? 'file://sound.aac' : 'file://sound.mp3';

cordova.plugins.notification.local.schedule({
    id: id,
    text: alert,
    sound: sound
});
```

///////////////////////////////////////////////////////////////////////////

This can play sound on most android device and ios10, but not ios9...
How can I fix it?
ps: I tried format of '.caf' '.ogg', and only ios9 cannot play...

**Comment by rafaelmb** [comment]
I've triend on the iOS 10 branch and did not work either.

**Comment by katzer** [comment]
With 0.9-beta playing a sound on iOS does work.
