### ISSUE TITLE
Customize look and feel of local notification

### ISSUE THREAD

**Issue by Hephze** [katzer/cordova-plugin-local-notifications#1120]
How can we change the color, style, icon background color etc of local notification?. which is the file need to be changed?

**Comment by pavankumarkatakam** [comment]
Im also looking for this enhancements. Please checkout the issue in Remote notifications plugin https://github.com/phonegap/phonegap-plugin-push/issues/1517

**Comment by katzer** [comment]
Please see the README - v0.9-beta supports the different pre-defined styles.
