### ISSUE TITLE
Having troubles on IOS 10

### ISSUE THREAD

**Issue by teamherois** [katzer/cordova-plugin-local-notifications#1124]
I have installed the latest version and all is running great on android but when I test on my ios device I dont receive the notification. Any help on what may be wrong would be a lifesaver!

Thanks

**Comment by emanfu** [comment]
Same here. The local notification is not working at all on iOS 10. It is working fine on iOS 9.3. My app has been beta testing for quite a while and approaching release. It's too bad we just found the local notification is not working on iOS 10. Any help will be greatly appreciated! Thanks!

**Comment by artkoenig** [comment]
+1

**Comment by teamherois** [comment]
I actually have local notification's working now, coming in 3 hours late but they are working. Im guessing thats an issue with my time in the scheduling. Here's the updated plugin I used, make sure to follow follow this exactly! [Update Plugin](http://plugins.telerik.com/cordova/plugin/localnotification) and make sure to delete the old version of your plugin. I also found this [#1107](https://github.com/katzer/cordova-plugin-local-notifications/pull/1107) to be helpful too.

**Comment by WilliamALiang** [comment]
@teamherois，Which version you are using.is0.8.5-dev？

**Comment by emanfu** [comment]
I manually apply the fix in #1107 and it works fine to me. I will use this solution for now until a new version supporting new API comes out.

**Comment by WilliamALiang** [comment]
@emanfu How do you solve?

**Comment by emanfu** [comment]
@WilliamALiang 
I forked the project, clone the forked project into my disk, then manually make the change proposed by #1107. Then I install the plugin by "cordova plugin add path/to/my_plugin". The trouble of doing this is that you have to merge the changes in the upstream project yourself periodically.

**Comment by katzer** [comment]
Please use v0.9-beta, it fully supports iOS 10 or newer. Thanks
