### ISSUE TITLE
plugin not working with Phonegap Push Plugin

### ISSUE THREAD

**Issue by SiddiquiImran** [katzer/cordova-plugin-local-notifications#1126]
Hi @katzer ,

some people have posted an issue regarding that 
https://github.com/katzer/cordova-plugin-local-notifications/issues/663
is there any update in this area.

**Comment by FredeHo** [comment]
+

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no update from original poster.
