### ISSUE TITLE
The problem on the ios10

### ISSUE THREAD

**Issue by WilliamALiang** [katzer/cordova-plugin-local-notifications#1127]
Currently using the plug-in on ios10 can push notifications?Who can reply, thanks.

**Comment by Tawpie** [comment]
No. This plugin is for local notifications only—push notifications require a different plugin.

**Comment by edencorbin** [comment]
Regarding local notifications, is the best branch master or the ios10 branch? They stopped working after the update and I'm looking to restore basic functionality.

**Comment by argie9999** [comment]
+1

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no update from original poster.
