### ISSUE TITLE
Badge not showing in Android 6

### ISSUE THREAD

**Issue by Siva-93** [katzer/cordova-plugin-local-notifications#1131]
Hi, 
I'm developing an android application which has local-notification features. My functionality is very simple. I need to show the badge whenever the notification arises in the app. However, this is nicely working in android 4.4 and 5. But the weird thing is the same code is not working in Android 6. 

(Problem: Scheduled a notification, I can able to get the notification but the badge is not showing (only occurs in android 6)).

What might be the cause? Is android OS suspends all the running process in background?. Else do I need to enable any permission for the app? Kindly help me to get out from this problem.

Plugin details:
cordova = 6.4
katzer/local-notification = 0.8.4
katzer/badge = 0.7.2

**Comment by souly1** [comment]
Hi @Siva-93 , If you're talking about the icon, i had a similar issue that was solved by changing the images used for small and regular sizes to better fit their preferred sizes: 570x570 48x48.
hope this is what you meant in badges and this helps.
Good luck!

**Comment by Siva-93** [comment]
Thanks for the reply @souly1 , I'm not indicating the app icon. I'm saying about the message count indicator on the event of notification trigger.

**Comment by moisesnarvaez** [comment]
+1

**Comment by rwillett** [comment]
Is this still an issue? We used the setBadge plugin to set the badge number.

**Comment by rwillett** [comment]
Closed as no update from original poster.

**Comment by digaus** [comment]
@rwillett 
Badge is working on Windows for me but not on Android 7? Yes I know there is a Badge Plugin but this Plugin provides it aswell so it should also work but it does not.
