### ISSUE TITLE
Documentation about sound

### ISSUE THREAD

**Issue by epetre** [katzer/cordova-plugin-local-notifications#1133]
I am simply trying to change the default sound. It currently uses the reminder sound but I would like to use the default notification sound (Like push notifications).
Maybe I am misunderstanding how the whole thing works but it seems really hard for no reason.

All the examples I have seen use custom sounds that are stored in the app. I would prefer using the default android and ios notifications sounds for push notifications. I tried the following with no success:

  `file://sounds/message.mp3`
  `file://message.mp3`
  `file://sounds/notification.mp3`
 ` file://notification.mp3`

**Comment by dedamico** [comment]
Hi Epetre - the documentation mentions using the res://  URL specifier for local resources:

https://github.com/katzer/cordova-plugin-local-notifications/wiki/Upgrade-Guide

I would be very interested if you get this to work.  I am currently trying to use a different notification icon and having problems with that.  If you got that to work, let me know!

**Comment by epetre** [comment]
I saw in the code that the default sound ends up bing :  `res://platform_default`
For your icon:
If you want to use your app icon, I do it like this `smallIcon: 'res://icon.png'` and I use a user's profile ficture like so `icon: data.image` where data.image is a remote url. I mention that there is a limitation and remote urls only work on android though.

**Comment by dedamico** [comment]
Thanks Epetre - have you ever used a file:// resource for any of your icons?  I'm having issues doing that right now.  I have my icon file in the www folder and am using file://icon.png.

**Comment by dedamico** [comment]
@epetre I got the res://icon.png to work, which is great - thanks!.  I would like to get the file://othericon.png to work, but having an issue with that. But at least I can override the Android default with the app icon.
