### ISSUE TITLE
Plugin Local Notification not working in android

### ISSUE THREAD

**Issue by williamsilvaec** [katzer/cordova-plugin-local-notifications#1136]
the plugin: "de.appplant.cordova.plugin.local-notification" not working in ionic 2

Error: cmd: Command failed with exit code 1 Error output: 
FAILURE: Build failed with an exception.

What went wrong: 
A problem occurred configuring root project 'android'.

Could not resolve all dependencies for configuration ':_debugCompile'. 
Could not find any matches for com.android.support:support-v4:+ as no versions of com.android
.support:support-v4 are available. 
Searched in the following locations: 
https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml 
https://repo1.maven.org/maven2/com/android/support/support-v4/ 
https://jcenter.bintray.com/com/android/support/support-v4/maven-metadata.xml 
https://jcenter.bintray.com/com/android/support/support-v4/ 
Required by: 
:android:unspecified
Try: 
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more
log output.

**Comment by RylandCai** [comment]
+1

**Comment by borismu** [comment]
I have the same issue in Ionic project. Once I've add plugin to my app, android version fails to build.

* What went wrong:
A problem occurred configuring root project 'android'.

> > Could not resolve all dependencies for configuration ':_debugCompile'.
> 
>    > Could not find any version that matches com.android.support:support-v4:+.
> 
>      Searched in the following locations:
> 
>          https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
> 
>          https://repo1.maven.org/maven2/com/android/support/support-v4/
> 
>      Required by:
> 
>          :android:unspecified
>

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by NeveriaSmart** [comment]
v0.8.4 is OK since it requires cordova-plugin-app-event instead of android-support-v4.
