### ISSUE TITLE
Local notifications does not work if no SD card

### ISSUE THREAD

**Issue by cherngho** [katzer/cordova-plugin-local-notifications#1137]
No local notifications are sent if the Android phone does not contain an SD card. The cause is because of the AssetUtil.getTmpFile(String) line 411 (https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/android/notification/AssetUtil.java#L411). Changing it to 

File dir = context.getCacheDir();

fixes the problem.

**Comment by katzer** [comment]
@cherngho I've added a fallback to the normal cache dir. Thanks!
