### ISSUE TITLE
Notifications created for some time in the past fire when a present notification is fired.

### ISSUE THREAD

**Issue by zocheyado** [katzer/cordova-plugin-local-notifications#1140]
So for example I have 2 notifications, one in the morning and one in the evening both set to repeat every day. If I set the one for the morning all by itself I do not receive any notifications until the next morning (correct) However if I set one for the past and one for the future (say I set in the middle of the day)  when the evening event fires it will also fire the morning event. Then both will repeat correctly after this. Is there a workaround to this or some sort of fix? Happening on ios and android

**Comment by ivanov84** [comment]
Perhaps you use incorrect device time set. Check time on device and check the time zone.

**Comment by rwillett** [comment]
Closed as no response from original poster in four months.
