### ISSUE TITLE
Is there any function Heads-up Notification?

### ISSUE THREAD

**Issue by yoohoogun114** [katzer/cordova-plugin-local-notifications#1141]
Is there any function like this?

I can't find it in documentation or wiki

i found same issue but i can't handle it.

![head](http://www.brevitysoftware.com/blog/wp-content/uploads/2015/10/android_headup_blog.jpg)

How Can I Use Heads-up Notification?

**Comment by yoohoogun114** [comment]
I Found It. 
```
cordova.plugins.notification.local.schedule({
            id: 1,
            title: "Wellness",
            text: "Please Input the text",
            every: "minute",
            icon: "assets/icons/dashboard/icon.png",
            data: { meetingId:"123#fg8" },
            priority: 1
        });
```

priority: 1 
options enable heads-up notification.
but I don't know is there any choice like screen shot.

**Comment by haha8x** [comment]
dosent work with priority: 1
