### ISSUE TITLE
Push notification with image

### ISSUE THREAD

**Issue by smgjreinieren** [katzer/cordova-plugin-local-notifications#1144]
First of all the question is it possible to push an image within the notification? Second how do I push a local notification with an image in it?

**Comment by ivanov84** [comment]
This plugin uses default pics from ipa build

**Comment by smgjreinieren** [comment]
this does not make anything clear for me sorry. So is it possible to send an notification like they do here: https://blog.pusher.com/how-to-send-ios-10-notifications-using-the-push-notifications-api/

**Comment by katzer** [comment]
@smgjreinieren See the README, there's a sample.
