### ISSUE TITLE
Xcode warnings with CDVLocalNotification

### ISSUE THREAD

**Issue by MrLugh** [katzer/cordova-plugin-local-notifications#1145]
I'm trying to build a ionic app on xcode to upload app store for testing.
There are some warnings after build:

Warning 1

/Users/gelordi/code/kpi/kpi_ionic/platforms/ios/CordovaLib/Classes/Public/CDVPlugin.h:51:25: 'CDVLocalNotification' has been explicitly marked deprecated here

void swizzled_pluginInitialize(id self, SEL _cmd) 

...

    [self addObserver:NSSelectorFromString(@"didFinishLaunchingWithOptions:")

                 name:UIApplicationDidFinishLaunchingNotification

               object:NULL];

...

Warning 2

/Users/gelordi/code/kpi/kpi_ionic/platforms/ios/KPI/Plugins/cordova-plugin-app-event/AppDelegate+APPAppEvent.m:79:32: 'CDVLocalNotification' is deprecated: Deprecated in Cordova 4.0. Functionality removed in 4.0, constant will be removed in 5.0

(void)   swizzled_application:(UIApplication*)application

    didReceiveLocalNotification:(UILocalNotification*)notification

{

    // re-post (broadcast)

    [self postNotificationName:CDVLocalNotification object:notification];

    // This actually calls the original method over in AppDelegate

    [self swizzled_application:application didReceiveLocalNotification:notification];

}

Warning 3

/Users/gelordi/code/kpi/kpi_ionic/platforms/ios/KPI/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m:607:47: 'CDVLocalNotification' is deprecated: Deprecated in Cordova 4.0. Functionality removed in 4.0, constant will be removed in 5.0

(void) didFinishLaunchingWithOptions:(NSNotification*)notification

{

    NSDictionary* launchOptions = [notification userInfo];

    UILocalNotification* localNotification;

    localNotification = [launchOptions objectForKey:

                         UIApplicationLaunchOptionsLocalNotificationKey];

    if (localNotification) {

        [self didReceiveLocalNotification:

         [NSNotification notificationWithName:CDVLocalNotification

                                       object:localNotification]];

    }

}

Can yo guys help me?

**Comment by rwillett** [comment]
Ignore them. They are just warnings. They have been there for a long time.

**Comment by MrLugh** [comment]
I can't archive the app on xcode because of those warnings...

Anyway, solution was to update all node stack

**Comment by rwillett** [comment]
Odd, doesn't stop me archiving.

Rob
