### ISSUE TITLE
how to stop repeating schedule notification 

### ISSUE THREAD

**Issue by ajaysaini95700** [katzer/cordova-plugin-local-notifications#1147]
i schedule notification every day . and i am getting notification every day. but now i want to stop repeating notification every day.
so how to stop it ?
i use code for schedule notification:
cordova.plugins.notification.local.schedule({
        id         : 1,
        title      : 'I will bother you every day',
        text       : '.. until you cancel all notifications',
        sound      : null,
        every      : 'day',
        autoClear  : false,
        at         : new Date(new Date().getTime() + 10*1000)
      });

**Comment by rwillett** [comment]
You need to cancel and clear the notifications. 

1. Do a query to get the list of notifications. 

2. Work out which ones to cancel and clear. Use the notification.id to select.

3. Pass an array of integer id's to cancel and clearl. Don't forget to use the callback function. We have found that using timeOuts also helps

```
    function ClearAndCancelLocalNotificationsAndThenExecute (toClearArray:number[] , ExecFunction = null , arg1 = null) {
        var debugClearAndCancelLocalNotificationsAndThenExecute = debugTrue;

        setTimeout(function () {
            if (debugClearAndCancelLocalNotificationsAndThenExecute)
                ConsoleLog("ClearAndCancelLocalNotificationsAndThenExecute: toClearArray = " + JSON.stringify(toClearArray));

            cordova.plugins.notification.local.clear(toClearArray , function() {
                if (debugClearAndCancelLocalNotificationsAndThenExecute)
                {
                    ConsoleLog("ClearAndCancelLocalNotificationsAndThenExecute: Clear function success");

                    ShowNotificationQueue();
                }

                setTimeout(function () {
                    cordova.plugins.notification.local.cancel(toClearArray , function() {
                        if (debugClearAndCancelLocalNotificationsAndThenExecute)
                        {
                            ConsoleLog("ClearAndCancelLocalNotificationsAndThenExecute: Cancel function success");

                            ShowNotificationQueue();
                        }

                        if (ExecFunction)
                            ExecFunction(arg1);
                    });
                } , 1000);
            });
        } , 1000);
    }
```

The above is a working example of clearing out a load of notifications and then executing a function afterwards. We use it for rescheduling notifications.

Rob

**Comment by rwillett** [comment]
Is this now working. If so I'll close this.

**Comment by rwillett** [comment]
closed as no response from original poster.
