### ISSUE TITLE
duplicate symbol _UIApplicationRegisterUserNotificationSettings 

### ISSUE THREAD

**Issue by AlaeddineMessadi** [katzer/cordova-plugin-local-notifications#1149]
I have `de.appplant.cordova.plugin.local-notification 0.8.4` and `cordova-plugin-badge 0.7.3 "Badges"` installed and when I run`ionic build ios` and try build and run the app in **Xcode** I get this error.

```
duplicate symbol _UIApplicationRegisterUserNotificationSettings in:
    /Users/alaeddine/Library/Developer/Xcode/DerivedData/MyApp-bhobcxdkrkswqgafqtdqrmquufpx/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/AppDelegate+APPAppEvent.o
    /Users/alaeddine/Library/Developer/Xcode/DerivedData/MyApp-bhobcxdkrkswqgafqtdqrmquufpx/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/AppDelegate+APPRegisterUserNotificationSettings.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

any suggestions please? Thanks!

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by katche70** [comment]
same problem to me? how to solve it

**Comment by rwillett** [comment]
We use cordova-plugin-badge 0.7.2 with no problems.

**Comment by katche70** [comment]
I did Not use Badge Plugin but have this error with local push Plugin

**Comment by rwillett** [comment]
Then you don't have the same problem. Raise a new issue using the template in #1188.

**Comment by souly1** [comment]
Hi @katche70 , just to mention i had the same issue and listing my plugins found:
'de.appplant.cordova.common.registerusernotificationsettings' which i see you have as well.
uninstalling it and removing from android.json & ios.json under plugins folder solved the issue for me. 
Haven't checked it worked yet, I'll report back if it broke things, but we do have 'cordova-plugin-app-event' installed which should be enough according to the documentation.

Update if you try it out.
Good  luck!

**Comment by rwillett** [comment]
Closed as no update from original poster
