### ISSUE TITLE
Improve the documentation about how to schedule notification

### ISSUE THREAD

**Issue by padupuy** [katzer/cordova-plugin-local-notifications#1153]
Hello,

I found an excellent article about the plugin documentation : https://www.sitepoint.com/integrating-local-notifications-in-cordova-apps/
I wonder if you could update the Sample section on [the main readme file](https://github.com/katzer/cordova-plugin-local-notifications#sample) and in particular the ` firstAt` and `every` parameters

It will save time to a lot of developers :)

**Comment by katzer** [comment]
@padupuy Some samples have been added to the README already. I am looking for further content and also hope for PR's as I am busy enough writing the code ;) - Thanks!
