### ISSUE TITLE
More flexible intervall for repeatable notifications in iOS

### ISSUE THREAD

**Issue by dz020** [katzer/cordova-plugin-local-notifications#1154]
please provide the same functionality for iOS, so that it s possible to give an integer value to "every" parameter in iOS. we need a more flexible interval for our product!

**Comment by Fayozjon** [comment]
Hi there looking answer for this question.
Right now i used to create reminder app which have to REMIND user to do something for example every 2 hours from 8 a.m. 3 times at day. For example take some medicine.

**Comment by katzer** [comment]
Please see the README for 0.9-beta

```js
schedule({
  trigger: { every: 2, unit: 'hour', count: 3 }
});
```

However `count` is only supported yet on Android and Windows.
