### ISSUE TITLE
Implementation plugin for IOS 10 and later 

### ISSUE THREAD

**Issue by eros2187** [katzer/cordova-plugin-local-notifications#1158]
The current plug-in does not work with version 10 of iOS as I can Solve?
there some new plugin branch that does this?

**Comment by novas1r1** [comment]
https://github.com/Telerik-Verified-Plugins/LocalNotification

This one works for us!

**Comment by liuxinqiong** [comment]
@novas1r1 ，I make a demo to test notification by using the plugin that you introduced,But it don't work  at all. Can you tell me the version of your ios? 10.0 or 10.1?  and can you give me a link of your demo? thanks!

**Comment by eros2187** [comment]
by ios 10 and changed everything meanwhile is more can not see the notification when and in the foreground.
In fact now the notifications can be displayed only when the app and in the background.
here is an example of code that can be used to display the notiifca in all it is two cases.

http://www.techotopia.com/index.php/An_iOS_10_Local_Notification_Tutorial#Receiving_Notifications_in_the_Foreground

We should integrate this code in order to implement the plugin I can not do it but I can assure you that the code works we tested.

unaltro problem instead and to be able to somehow leave always on the scheduler so rivecere notification app also fully closed

does anyone know how you can do this? you can deploy the plugin to be able to initiate a call that also functions to app closed in order to have a complete notification.

look your greetings tips giuseppe

**Comment by sgentile** [comment]
how does one add this to a project - ie. ionic - can you add a plugin by branch ?

**Comment by rwillett** [comment]
Is this still a problem?

**Comment by rwillett** [comment]
Closed as no update from original poster.
