### ISSUE TITLE
ios10 Branch - Notification are fired later 

### ISSUE THREAD

**Issue by hiroaka** [katzer/cordova-plugin-local-notifications#1159]
Hey guys, i am experiencing a strange behavior. Some of my notifications are coming in the wrong time. In my app i have a lot of individual notifications, that have to come in customs interval during the day. For this i schedule one notification for each interval. But some of my notification are fired later. 

Can anyone knows why this behavior occurs?

**Comment by rwillett** [comment]
Odd, we have no issues with this at all on IOS10. One of our test cases is how fast we can create local notifications by starting and stopping the app. Each time we start the app up, we need to reschedule local notifications. We might do this 20-30 times to see if we can break the local notifications and so far, we haven't managed to. The local notifications keep appearing at the right time. We can see that the notification.id is incremented by our code and can hit 200 which means we have rescheduled around 200 notifications. 

This test case also works for IOS8, 9 and Android 5. We're just testing it for Android 6 now :) We assume it will work but we'll test for Android 6 anyway.

Rob

**Comment by rwillett** [comment]
Closed as no updated from OP.
