### ISSUE TITLE
Notifications not clearing from app in Android

### ISSUE THREAD

**Issue by rupalpatel0008** [katzer/cordova-plugin-local-notifications#1160]
In android, I need notifications with every="day" property. When any notification is triggered and app is open I need to show a popup with notifications text. On click event of that alert i need to clear the notification from notification tray. I have put code to clear it when alert is clicked. The on("clear") is fired but its not getting cleared from notification tray. Notification is cleared only when its clicked from notification tray.

Clear code when notification is triggered:
**Inside app.js** when platform is ready:
var mealonePopup2;
cordova.plugins.notification.local.on("trigger", function (notification) {
      console.log('notification',notification);
      mealonePopup2 = $ionicPopup.alert({
        template: notification.text,
        title: notification.title,
        cssClass: 'custom-popup2'
      });
      mealonePopup2.then(function () {
        mealonePopup2.close();
        clearNotificationid = notification.id;
        cordova.plugins.notification.local.clear(clearNotificationid, function() {
          
        });
      });
    });
cordova.plugins.notification.local.on("clear", function(notification) {
      console.log('cleared', notification.id);
    });

**In ios its getting cleared from app when following above scenario.**

**Comment by hoongoon86** [comment]
I'm having the same issue, 
Instead of 'update', I'm using 'clear notification' then 'create notification'. 
In iOS, it works good, but in Android, notification is not cleared and when the time has come, all 'not cleared' notifications are coming all together.

**Comment by rwillett** [comment]
We put a lot of these calls in setTimeout functions to get them called later. We also create notifications a few seconds in the future (5 by default). We also make sure we call them in the callback function to really make sure.

Rob

**Comment by rwillett** [comment]
Closed as no update in eight weeks.
