### ISSUE TITLE
How to tell the difference between clear and "close"

### ISSUE THREAD

**Issue by petewall** [katzer/cordova-plugin-local-notifications#1161]
I am using local notifications to notify the user when my app is in background mode (it's a BLE central app, so it runs in the background).
When I schedule a notification, I set a short timeout (~20 seconds), and if the user does not interact with the notification within that timeout, I clear it.  When the notification pops up, there are three actions the user can take:

1. Tap "OK" which opens the app and triggers the "click" event.
2. Tap "Close", which dismisses the notification
3. Do nothing.  The timeout is triggered and the app `clear`'s the notification.

The problem I'm having is that I can't differentiate between 2 and 3.  When the user taps "Close", no event is triggered in the app, and `isPresent()` always returns "`true`".  When the timeout function calls `clear()`, it doesn't cause an error.

Is there any way for me to know that the user dismissed the notification?

Here's a snippet of code:
```
var timeoutHandle;
$rootScope.$on('$cordovaLocalNotification:click', function (event, notification) {
    $timeout.cancel(timeoutHandle);
    // Handle action #1
}); 

$rootScope.$on('$cordovaLocalNotification:clear', function (event, notification) {
    // This is only called when the timeout clears the notification
)};

$cordovaLocalNotification.schedule({
    id: notificationId,
    title: 'Hello',
    text: 'This message will self-destruct in 20 seconds'
});
timeoutHandle = $timeout(function () {
    $cordovaLocalNotification.clear(notificationId);
    // Handle action #3
}, 20 * 1000);
```

**Comment by rwillett** [comment]
@petewall 

We're tearing our hair out with the same issue. We can get the click if a user clicks on an event, your case 1. We cannot find any method of detecting any event when the user clicks cancel in the notification drawer.

#1162 goes through this in more detail, we've been looking for weeks for this and have a process workaround for our use case, which won't work for your use case. 

Our use case is alerting the user to pay a traffic congestion charge bill, so we send them reminders through the day. We also send other local notifications as well, e.g traffic updates which are very transient, i.e. who wants to know about a traffic jam that cleared  four hours ago, but you do want to keep the reminder about paying a bill. 

The problem for us is that we can these different types of local notifications PLUS the notifications that come into our app that are pushed when our app is terminated, so we now have four types of notifications which have different expiry dates.

1. Local repeating notifications for the London congestion charge.

2. Local repeating notifications for the Dartford Bridge crossing charge.

3. Local non repeating notifications for London traffic jams

4. Ordinary non-local notifications generated through Apple Push or Google Push servers. 

We can can selectively clear use cases 1-3 but there is no mechanism to selectively clear out case 4 (that we can find). This means at times we have to clear ALL notifications and then put back in place the ones we want the user to keep seeing cases 1 and 2 and sometimes 3. 

This means that we keep putting back cases 1 and 2 even though the user may have specifically cleared them using "clear" or "x" in the notification drawer as we have no way of detecting this. 

Querying the local notifications using ```getAll``` **doesn't** show notifications that have been "user cleared" from the drawer.

So we're stuck like you. We have read anything in the issues that has clear in, indeed we have contributed to some of the answers but we cannot get a clear (excuse the pun) answer on this. Some people appear to have got this to work, but so many people do not write up what they have done or exactly how they have solved their issue.

We'd be very interested if you have any information or any solution at all to this. Happy to collaborate further if if works for you.

Rob

**Comment by rwillett** [comment]
Two questions:

1. Whats BLE?

2. You appear to be using the ng-corodova version of the plugin. Is this the case?

Rob

**Comment by petewall** [comment]
Thanks for sharing your experiences, Rob.  I'd be happy to share anything that I discover here.

1. BLE - Bluetooth Low Energy.  iOS only allows certain reasons for an app to run in the background, and collecting data from a Bluetooth Low Energy device is one of them.
2. Yeah, I am using the ngCordova version.

**Comment by petewall** [comment]
Thanks for sharing your experiences, Rob.  I'd be happy to share anything that I discover here.

1. BLE - Bluetooth Low Energy.  iOS only allows certain reasons for an app to run in the background, and collecting data from a Bluetooth Low Energy device is one of them.
2. Yeah, I am using the ngCordova version.

**Comment by rwillett** [comment]
Ah, I thought I'd seen BLE before somewhere.

Suspect that the ngCordova version has exactly the same issues as this version. 

We looked at isPresent() and couldn't see that helping. As far as we can see there is no event actually triggered by the user deleting a notification from the drawer and there is no way to query the current view of notifications in the drawer. 

I'd be delighted if we are wrong.

Rob

**Comment by katzer** [comment]
@petewall @rwillett Since 0.9-beta the plugin does fire the clear event if the user clears the notification from outside (notification center).
