### ISSUE TITLE
Not firing the cordova.plugins.notification.local.on("click", function (notification) event

### ISSUE THREAD

**Issue by RikdeVos** [katzer/cordova-plugin-local-notifications#1163]
I'm trying to fire a function when the notification is clicked, but the on click event does not seem to fire. I've tried registering this event handler when the notification is sent, and when the app is opened, but in both cases it's not firing the function. Is this a bug? I'm using iOS 10.1.1

**Comment by rwillett** [comment]
Click does work on IOS 10.1.1.

```
        cordova.plugins.notification.local.on("click", function(notification , state) {
            if (debugSetUpLocalNotificationHandlers)
                ConsoleLog("SetUpLocalNotificationHandlers: 'click' " + notification.id + "state = " + JSON.stringify(state));
        });
```

produces 

```
2016-12-03 20:32:11.623903 Jambuster[228:5833] SetUpLocalNotificationHandlers: 'click' 28state = "background"
```

on our machine. Just tested to confirm,

**Comment by mvitalia** [comment]
I read your comments. How did you configure the plugin with iOS 10.1.1?
Please help me, thanks

**Comment by RikdeVos** [comment]
I ended up deleting the iOS platform, and re-adding it again using the latest version of Cordova iOS. I believe that did the trick.
