### ISSUE TITLE
multiple buttons on notification and action

### ISSUE THREAD

**Issue by pareta2** [katzer/cordova-plugin-local-notifications#1164]
Can a notification button have customization buttons and action on it as Gmail, hotmail, skype have,

**Comment by rwillett** [comment]
Not at the moment. A few forks were done sometime ago for this but it never got merged back.

https://github.com/DavidBriglio/cordova-plugin-local-notifications

and

https://github.com/katzer/cordova-plugin-local-notifications/pull/774

Rob

**Comment by pareta2** [comment]
Great thank you i will look into it....could you also tell me if those button works on locked screen. I want a functionality by which i can see buttons during screen lock and when i click the button it performs the action. Thanks again for you help.

**Comment by rwillett** [comment]
No idea, never installed them. 

I also am unsure if they are supported so I would check this before you do anything.

Rob

**Comment by ventr1x** [comment]
This is actually a feature I'd need in my next app.
Why does this plugin skip half of the api implementation in the first place?
Especially one that is officially used and supported by frameworks like ionic?
Gotta love the javascript ecosystem, huh?

**Comment by rwillett** [comment]
The source is open and free, if you don't like something, fork it and adapt it to what you need. Thats the beauty of it.

@katzer has put a lot of effort into this plugin, you are welcome to carry on working in it to improve it. I expect @katzer would be grateful for any help.

Rob

**Comment by ventr1x** [comment]
Without getting into the argument that you could do that if it's a hobby project, but can't necessarily sell your company the need to cobble together multiple plugins before start working:

A solution exists for over a year, but it never made it to any production branch.
So the question would be: what's the roadmap for 0.9?
As long as this is unclear, any contribution could be wasted time.
The last commit to that branch is also over a year ago.

**Comment by katzer** [comment]
Please use 0.9.beta
