### ISSUE TITLE
Event 'trigger' not fired while app is in background 

### ISSUE THREAD

**Issue by estvmachine** [katzer/cordova-plugin-local-notifications#1167]
I got  the same problema like #628. I'm ussing the latest version of this plugin: 0.8.4. Im ussing ionic with iOs with my app in background mode. The trigger event only works when i got the app in firstground.

In background i try with the cordova.plugins.notification.local.on('trigger', function (notification){}) and $rootScope.$on('$cordovaLocalNotification:trigger', function (event, notification, state) {}). Both not works. Can i do for make this works? i really needed it, thanks.

**Comment by porridj** [comment]
I'm having a struggle with this too. I need the data from the notification to redirect user to a different page, current'y it just doesn't seem to hit the trigger.

Using the ios10 branch. I'll keep looking over the next couple of days, but thought I'd subscribe to this thread just incase :)

**Comment by estvmachine** [comment]
I read a lot about this and appears is a long shot problem (+2 years)

**Comment by katzer** [comment]
@estvmachine @porridj The `trigger` event only works if the app is running (and in foreground). Especially for iOS!

**Comment by Lenndev** [comment]
@katzer is there a different event that does work on iOS?
I need a trigger-like event to work for the app being in background

**Comment by rwillett** [comment]
If the IOS app is in the background you cannot use it. You can use the click on the notification to pull it to the foreground. Thats the way IOS works.
