### ISSUE TITLE
Problem plugin with iOS 10.1.1

### ISSUE THREAD

**Issue by mvitalia** [katzer/cordova-plugin-local-notifications#1168]
Hi, i have a problem with this plugin. I installed the plugin through PhoneGap Build (cli-6.3.0).
The notification permission is correctly set in application load, but the plugin don' t work in iOS 10.1.1.
The problem is iOS 10 or my plugin configuration?
Ps: In Android device the plugin work correctly...

**Comment by Leomhl** [comment]
You can try execute the plugin using the branch IOS10.

**Comment by rwillett** [comment]
Is this working now?

**Comment by rwillett** [comment]
Closed as no response.
