### ISSUE TITLE
Repeating Notification Is Removed After It Fires On iOS Devices

### ISSUE THREAD

**Issue by billycomic** [katzer/cordova-plugin-local-notifications#1169]
I have this built into a few apps on Android and iOS. It is the exact same JS code that handles both, but on iOS the notification is deleted after the first time it is fired. The notification STILL fires the next day, but does not return when calling getAllScheduled(). On android they return and then fire the next day as designed, but iOS shows NO notifications scheduled, but they still fire next day.

I'm completely stumped as to how this is happening. Anyone else experiencing this?

**Comment by John-Henrique** [comment]
You need put your code, we don't know what you do...

**Comment by rwillett** [comment]
Closed as no update.
