### ISSUE TITLE
IOS UIBackgroundModes key

### ISSUE THREAD

**Issue by fluqueval** [katzer/cordova-plugin-local-notifications#1170]
In Xcode 8.1 I have marked compatibilities and Works correctly:

- Remote Locations
- Audio Background

But apple rejects the app and tells me to uncomment "Audio Background"
If I uncheck "Audio Background" notifications do not arrive

Is there any solution?

**Comment by rwillett** [comment]
Are you using a well known hack with Background Audio to trigger background processing? If so that's guaranteed to get a rejection from Apple. 

If not provide more information about the problem. 

Rob

**Comment by fluqueval** [comment]
Hello
Notifications work correctly. In IOS 10 they arrive when the app is in the background. But for it to work I have to check the background compatibility "Airplays aduio ..." in Xcode

I have tested on my Iphone.

If you do not set the option "Airplays aduio ...", the notifications do not arrive.

The problem is that if I set that option in Xcode 8.1, I'm being rejected from Apple's app. I've been talking to them.

This is my code:
This audio file is in: Www / img / appbeep.wav

I am using version 0.8.4 of katzer / cordova-plugin-local-notifications

And it is used by our plugin in:
$ CordovaLocalNotification.schedule {
Id: $ rootScope.phone,
Message: result.text,
Title: "Notification:" + redParmNot,
Icon: 'file: //img/icon.png',
Sound: 'file: //img/appbeep.wav'
}).

We can not remove the UIBackgroundModes audio check because then the notifications do not reach the device.

Can anybody help me please?

**Comment by rwillett** [comment]
1. You are using an old version of the plugin that does not work well on ios 10. 

2. Scheduled Local Notifications do arrive on ios 10 without audio background processing with the app in the foreground, the background, suspended and terminated. We do not play sounds so that might (or might not) be an issue. 

3. You have no at: definition in your schedule. No idea what will happen without that. At the at: for five seconds on the future. 

4. There is a callback on success. You are not using it. Add it into check what's happening. 

5. Put the scheduling object inside an array. 

Under what circumstances do they arrive and under what circumstances do they not arrive. You need to provide a lot more information as local notifications do work on ios 10 without Background Audio.

**Comment by fluqueval** [comment]
Hello
Thank you very much for the prompt response.

1.-
Where can I download the latest version? I have been able to see that the last Release is from Jan 4 0.8.4 which is the one I am using

2.- I will try to delete the audio

3.- I will also act to put the at with a time poseteior

4.- Porbaré the success, to know if the notification is sent

5.- I do not understand this point

$ CordovaLocalNotification.schedule {
 At: tomorrow_at_8_45_am,
Id: $ rootScope.phone,
Message: result.text,
Title: "Notification:" + redParmNot,
Icon: 'file: //img/icon.png',
Sound: 'file: //img/appbeep.wav'
})

Thank you. When I do these tests I will answer you.

**Comment by rwillett** [comment]
1. You need to download the ios10 branch from this github.

2. OK

3. You need to specify a time in the future for a scheduled local notification. The docs are very clear on how to do this.

4. Not clear what you mean.

5. You need to put {
```
At: tomorrow_at_8_45_am, // <-- THIS NEEDS TO DEFINED USING A DATA OBJECT
Id: $ rootScope.phone,
Message: result.text,
Title: "Notification:" + redParmNot,
Icon: 'file: //img/icon.png',
Sound: 'file: //img/appbeep.wav'
} 
```
in 
```
[ // NOTE THE USE OF THE ARRAY
 {
At: tomorrow_at_8_45_am,
Id: $ rootScope.phone,
Message: result.text,
Title: "Notification:" + redParmNot,
Icon: 'file: //img/icon.png',
Sound: 'file: //img/appbeep.wav'
}
 ] // NOTE THE USE OF THE ARRAY
```

Strip the code back to basics but before anything get the right version of the code and read the docs.

Rob

**Comment by fluqueval** [comment]
OK

I will update to the IO10 branch
Https://github.com/katzer/cordova-plugin-local-notifications/tree/ios10

And I will perform all the tests you tell me.

When I have rehearsed it, I will throw the results here, so that the other companions will have a record.

Greetings and again thank you very much

**Comment by eliataylor** [comment]
rwillet, you say 'We do not play sound', so what is the Sound property for? Isn't that sounded off when the notification arrives in the background? 

(I have not yet started using your plugin at all, but am reviewing some issues to see if it might work for me)

(thank you very much for your time in doing this for the community!)

**Comment by Tawpie** [comment]
@rwillett I'm betting you meant to say "THIS NEEDS TO DEFINED USING A **_DATE_** OBJECT", right? Meaning: a javascript date object like you get from `new Date()`

**Comment by rwillett** [comment]
@eliataylor 

We set the sound to be an empty string to make sure that we don't play anything. We make no assumptions what will happen if the sound: field is not present.

This is not my plugin. I cannot take any credit for the work @katzer has put in. We use the local notifications plugin a lot and so we am keen to keep it going. If this takes some work off @katzer thats fine by us.

@Tawpie, You are correct the ```at:``` field most be an object like ```new Date()``` . I've updated my post.

Rob

**Comment by fluqueval** [comment]
@rwillett  
Hello
How can i install command line version ios10

Cordova plugin add de.appplant.cordova.plugin.local-notification@0.8.5-dev
Cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.8.5-dev

Both fail
Thank you

**Comment by rwillett** [comment]
@fluqueval 

Missed this comment. 

cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#ios10

Will work,

I suggest you download and of that works, close this issue down.

Rob

**Comment by ckpr18** [comment]
Hi, @rwillett, your app passed the review in apple? I have the seem problem, Apple reject my app with cordova-plugin-local-notification, but additionally I should put information to the server in local notification and that is why I use another plugin: https://github.com/katzer/cordova-plugin-background-mode. I don't know what is the plugin that apple reject. Anybody have idea?

**Comment by rwillett** [comment]
No issues at all with my app in review process.

Your app is rejected due to the background mode plugin. The plugin states very clearly that 

```
‼️ Store Compliance ‼️

The plugin focuses on enterprise-only distribution and may not compliant with all public store vendors.
```

Pretty obvious

Rob

**Comment by ckpr18** [comment]
Hi, @rwillett, thank for answer, do  you know another background mode plugin, that apple not reject?.

**Comment by rwillett** [comment]
Search for background fetch or Chris Scott. Christocracy from memory. 

On mobile so no access to office at moment

**Comment by rwillett** [comment]
The question I would ask is why do you think you need it?

**Comment by ckpr18** [comment]
well, I need get information from server and I get it through ajax with a setInterval every 15 second. This change some information in the app and occasionally send local notification.

**Comment by rwillett** [comment]
If you are receiving information every 15 secs your app will kill the battery. We were struggling with battery consumption with doing data syncs every five minutes. You are doing 20x more work.

**Comment by ckpr18** [comment]
Well, the same app its working in production for android, and the live of battery is normal, inclusive android consider this app as a low-power battery. Do you know how Whatsapp send and recive notification?. This app keep working background and its battery consumption is low

**Comment by rwillett** [comment]
We moved to web sockets to get the power consumption down. I *think* thats how most apps do this. 

I have no idea how you use the wifi every 15 seconds and do not kill the battery. Creating a connection, sending data and tearing it down consumes power. 

Are you actually doing any wifi connections?

**Comment by ckpr18** [comment]
Yes, I do. I connect to server through wifi connection or 4G net.  Show a code.
setInterval(function(){
var p={

}
$$.ajax({          
              type: 'POST',
              contentType: 'application/json',   
              data: JSON.stringify(p),
              cache:false,
              timeout:5000,
              url: name of recurse in server,
              success: function(){                   
                  
              },
              error: function(XMLHttpRequest, textStatus, errorThrown) {
                    
                }             
            });
},15000);

**Comment by ckpr18** [comment]
when you use web sockets, its keep working in background mode?

**Comment by rwillett** [comment]
No idea why your battery isn't dead. Perhaps android does something special.

Websockets keeps the connection open using a very long running transaction. This avoids the setup and rear down of http connections.

**Comment by rwillett** [comment]
Also that settimer won't work on ios as it suspends the javascript and javascript  http connections.

**Comment by rwillett** [comment]
Closed as no updated from original poster for three months,
