### ISSUE TITLE
How to show a downloading progress in android by this plugin

### ISSUE THREAD

**Issue by andyhuang15** [katzer/cordova-plugin-local-notifications#1172]
Hi ,
  I need to show the progress of downloading file in local notification. I use this function local.update() to update the notice text, but i find if i call this function very quickly when the progress is changing, this notification don't update immediately. Is there a good way to update the content of notification quickly ? Another problem is that the content of notification  is only string , could i add progress animation in it? Any answer will be appreciated!

**Comment by rwillett** [comment]
This plugin will not do that. 

Repeatedly sending update notifications to try and simulate a file downloading progress bar is not a good use of local notifications.

You are far better off trying to do this with a dedicated JavaScript plugin. Or put a animated GIF up and then hide it. This is actually quite tricky to do. 

We got around this by putting up a Toast notification which we then clear on completion.

https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin

Rob

**Comment by andyhuang15** [comment]
thanks for your suggestion, i will try it.

**Comment by rwillett** [comment]
If this is finished suggest you close the thread down.

Rob

**Comment by vasani-arpit** [comment]
I know thread is closed but this might help someone.
I have created a plugin which downloads file using download manager and shows progress bar along the way

https://github.com/vasani-arpit/cordova-plugin-downloadmanager

I hope it helps.
