### ISSUE TITLE
Show notification as heads-up banner

### ISSUE THREAD

**Issue by Woutwo** [katzer/cordova-plugin-local-notifications#1173]
Hello,

I use this plugin in my ionic app and it works great.  I do have one question: is it possible to make the notification show as "heads up banner" (at the top of your screen for a few seconds) in ANDROID. Currently, the notification will add an icon in the notification center; but I want the user to notice it and click it to return to the app after a payment. Is this possible with this plugin?

This works in iOS but not in Android.

Kind regards,
Wouter

**Comment by justfathi** [comment]
+1

**Comment by AviShmueli** [comment]
use this fork:
https://github.com/DavidBriglio/cordova-plugin-local-notifications

**Comment by Woutwo** [comment]
Thanks

**Comment by rwillett** [comment]
If this is finished suggest you close the thread down.

Rob

**Comment by KishanIos007** [comment]
@AviShmueli  I tried to add this plugin but can't able to add it. any other suggestion ?
Here is what i get when i tried to add the plugin 
```
> cordova plugin add cordova-plugin-local-notifications --save
Installing "de.appplant.cordova.plugin.local-notification" for android

Failed to install 'de.appplant.cordova.plugin.local-notification': CordovaError: Failed to fetch plugin org.apache.cordova.device via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "org.apache.cordova.device" "--production" "--save"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not found : org.apache.cordova.device
npm ERR! 404
npm ERR! 404  'org.apache.cordova.device' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```
