### ISSUE TITLE
Control notification vibration option in iOS devices

### ISSUE THREAD

**Issue by rchowdhe** [katzer/cordova-plugin-local-notifications#1174]
I am using - forked plugin https://github.com/shaoner/cordova-plugin-local-notifications/commit/27091795e2ca845ab9ac6a21e2d478d596162fce to control device vibration for application notifications, But this feature os forked only for Android.

Can we get same vibration control options for iOS also.

**Comment by katzer** [comment]
@rchowdhe With 0.9-beta its possible to do on Android, but there's no API for iOS. If that may come then I will support that.
