### ISSUE TITLE
It suddenly doesn't work on my ios app

### ISSUE THREAD

**Issue by ip192** [katzer/cordova-plugin-local-notifications#1175]
I use the plugin as the document says.
cordova.plugins.notification.local.schedule({
                id: 244,
                title: 'title',
                text: 'text',
                at: new Date(),
                sound: null,
                data: { data: 'data' }
            });
At first, it can make a notification. But a few hours ago, it didn't react any more.
Anyone who can help me.

**Comment by zefrench** [comment]
Hi,
Get the same problem too, I'll come back if I can found a way to fix it.

**Comment by ip192** [comment]
Waiting for you.

**Comment by rwillett** [comment]
1. Your date is technically in the background when fired, even by just a few milliseconds. Add a second or two to the the date and see what happens. We add five seconds to every notification we want to schedule now.

2. Make the object an single object in an array. People have reported issues with not passing the object in an array

3. Add a success function so you can check whats happening.

4. There are lots of versions of this plugin, which one are you using?

5. What version of IOS or Android? You haven't provided any context whatsoever for your issue. 

6. What have you changed?

7. I wouldn't expect anything from @katzer at the moment as he doesn't seem to be around. Bumping your thread adds nothing.

**Comment by kaplanmaxe** [comment]
+1

**Comment by skotturi** [comment]
I used to schedule a number of notifications on iOS at once, the soonest one with a 500ms offset but this is not working on iOS anymore. 

I am able to get repeated notifications every minute on iOS using: 

```
  var now = new Date().getTime(),
                    future = new Date(now + 10000);
  var notification = {
            title: "Test",
            at: future,
            every: 'minute',
            id: 990
};

cordova.plugins.notification.local.schedule(notification);
```

However, when I try and schedule a set of single-use notifications at one second intervals, even with a 5 second offset, none of them trigger: 


```
 var foo = new Date().getTime();
                var now = new Date(foo + 5000).getTime();
                var one = new Date(now + 1000),
                    two = new Date(now + 2000),
                    three = new Date(now + 3000),
                    four = new Date(now + 4000),
                    five = new Date(now + 5000),
                    six = new Date(now + 6000),
                    seven = new Date(now + 7000),
                    eight = new Date(now + 8000),
                    nine = new Date(now + 9000),
                    ten = new Date(now + 10000)
                    ;
                var notifications = [
                    {
                        title: "One",
                        at: one,
                        id: 991
                    },
                    {
                        title: "Two",
                        at: two,
                        id: 992
                    },
                    {
                        title: "Three",
                        at: three,
                        id: 993
                    },
                    {
                        title: "Four",
                        at: four,
                        id: 994
                    },
                    {
                        title: "Five",
                        at: five,
                        id: 995
                    },
                    {
                        title: "Six",
                        at: six,
                        id: 996
                    },
                    {
                        title: "Seven",
                        at: seven,
                        id: 997
                    },
                    {
                        title: "Eight",
                        at: eight,
                        id: 998
                    }, {
                        title: "Nine",
                        at: nine,
                        id: 999
                    },
                    {
                        title: "Ten",
                        at: ten,
                        id: 990
                    }
                ];

                console.log('test notifications', notifications);

                cordova.plugins.notification.local.schedule(notifications);


```

I've tried tinkering with the offset, increasing it to one minute and spacing the notifications apart by 10-30 seconds, no luck. 

using plugin:
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"

using platforms:
cordova-android@6.1.0
cordova-ios@4.3.1

system:
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v4.6.2
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by skotturi** [comment]
I got it working by installing the ios10 branch of this repo:

```
$ cordova plugin rm de.appplant.cordova.plugin.local-notification
$ cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#ios10
```

IMPORTANT: the code in my comment above does not work because you need a `text` field as well. Without it I was getting notification sounds but no notification. 

these work: 
```
 var notifications = [
                    {
                        title: "One",
                        text: "Text",
                        at: one,
                        id: 991
                    },
                    {
                        title: "Two",
                        text: "Text",
                        at: two,
                        id: 992
                    },
                    {
                        title: "Three",
                        text: "Text",
                        at: three,
                        id: 993
                    },
... 
```

**Comment by rwillett** [comment]
You are using an old version of the local notifications plugin. The version you have doesn't work well with ios 10. You need the ios10 branch. 

Download that version and try again

Rob

**Comment by rwillett** [comment]
@skotturi 

Messages crossed in the post. You're using the latest version now.

**Comment by zefrench** [comment]
With ionic2 and with ios10 branch version of the plugin, the local notification is not shown.

**Comment by rwillett** [comment]
@zefrench 

I can't comment on Ionic 2 as we use Ionic 1. I'd be a little surprised it doesn't work but since we don't use Ionic 2 and are waiting for Ionic 2 to become stable, we can't check. 

Rob

**Comment by rwillett** [comment]
Can this issue be closed now?

Rob

**Comment by zefrench** [comment]
Yes it seems it works.
