### ISSUE TITLE
Android 5, 6 & 7 - Notifications are not showing in status bar notifications when app is in background

### ISSUE THREAD

**Issue by YannickGagnon** [katzer/cordova-plugin-local-notifications#1177]
Setting and showing notifications works flawlessly from Android 4 to 4.4.4, whether the app is in background or completely shutdown. For versions 5, 6 & 7, It works as expected when the application is shutdown, but nothing shows in the status bar if the app is in background (tapping the home button after creating a notifications for example)

Does Android handle notifications differently since Android 5?

Thanks,

**Info**
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
└── cordova-android@3.7.2
Cordova CLI: 4.3.1
OS: macOS Sierra
Node Version: v4.6.2

**Comment by skotturi** [comment]
What code are you using to schedule the notification?

**Comment by skotturi** [comment]
cordova-android is on v6.1.0, I'd try updating your platform from 3.7.2

$npm install -g cordova-android

**Comment by Tawpie** [comment]
@YannickGagnon another reason to update the android platform is that versions lower than (by memory...) 4.something have a cross scripting vulnerability that is flagged by Google Play. You really do need to update!

**Comment by YannickGagnon** [comment]
I did install the latest version of cordova-android using "cordova platform update android@6.1.0" and still experiencing the same issue.

Any other ideas?

**Comment by YannickGagnon** [comment]
Found the issue, it appears that my notifications gets cleared before they actually make it to the notification panel.

I had **onNotificationTriggered** callback clear all notifications and recreating the remaining, this works around the maximum number of notifications that can be created at one time.
