### ISSUE TITLE
this sample android not working...

### ISSUE THREAD

**Issue by ironelder** [katzer/cordova-plugin-local-notifications#1179]
Error code

12-30 10:36:32.293: I/ViewRootImpl(16310): ViewRoot's Touch Event : Touch Down
12-30 10:36:32.353: I/ViewRootImpl(16310): ViewRoot's Touch Event : Touch UP
12-30 10:36:32.403: D/SystemWebChromeClient(16310): file:///android_asset/www/index.html: Line 188 : Uncaught TypeError: Cannot read property 'notification' of undefined
12-30 10:36:32.403: I/chromium(16310): [INFO:CONSOLE(188)] "Uncaught TypeError: Cannot read property 'notification' of undefined", source: file:///android_asset/www/index.html (188)

I need help! Thank you!

**Comment by rwillett** [comment]
Show the code from index.html around line 188. 

Trying to guess the error with no code is difficult.

**Comment by rwillett** [comment]
I suspect you are not waiting for device ready so nothing is defined.

**Comment by ironelder** [comment]
@rwillett 
hi rwillett !

This error code url
https://github.com/katzer/cordova-plugin-local-notifications/wiki/11.-Samples

I find index.html notification  and I find 
cordova.plugins.notification <--- what's problem,, I'm not understand TT

**Comment by rwillett** [comment]
As already stated, show me your code.

I have no idea what you are doing. Asking me to look at a page and then saying

```
I find index.html notification and I find
cordova.plugins.notification <--- what's problem,, I'm not understand TT
```

provides zero information. What is TT?

Also I am NOT the author of this plugin, I did NOT write the docs. I am trying to help. If you want help, then provide your code. Specifically around the area where the error is. 

Have you checked that the device ready event has been fired. 

I have enough work already, do not expect me to do your work for you.

Rob

**Comment by ironelder** [comment]
Thanks you for kind anwser!

TT is Emoticon... It does not mean much.


I'm download this sample project
sample project = https://github.com/katzer/cordova-plugin-local-notifications/wiki/11.-Samples

and move sample project folder, input command.
ionic platform remove android
ionic platform add android
ionic build android
ionic run android

But Sample Project Not working. ^^;;

my device
LG-F340

ErrorLog
01-02 18:58:38.657: I/ViewRootImpl(32156): ViewRoot's Touch Event : Touch Down
01-02 18:58:38.657: D/PowerManagerService(992): updateUserActivitySummaryLocked: mWakefulness=Awake, mUserActivitySummary=0x1, nextTimeout=242558912 (in 292996 ms)
01-02 18:58:38.727: I/ViewRootImpl(32156): ViewRoot's Touch Event : Touch UP
01-02 18:58:38.777: I/Vold(270): [LGE][VOLD][NetlinkHandler.cpp][onEvent()] subsys:cpu, action:0
01-02 18:58:38.777: D/SystemWebChromeClient(32156): file:///android_asset/www/index.html: Line 188 : Uncaught TypeError: Cannot read property 'notification' of undefined
01-02 18:58:38.777: I/chromium(32156): [INFO:CONSOLE(188)] "Uncaught TypeError: Cannot read property 'notification' of undefined", source: file:///android_asset/www/index.html (188)
01-02 18:58:38.777: I/Vold(270): [LGE][VOLD][NetlinkHandler.cpp][onEvent()] subsys:cpu, action:0
01-02 18:58:39.027: I/Vold(270): [LGE][VOLD][NetlinkHandler.cpp][onEvent()] subsys:cpu, action:0




Thank you!

**Comment by rwillett** [comment]
Have you added the notification plugin? Your lines 
```
cordova platform remove android
cordova platform add android
cordova build android
cordova run android
```
do not show
 
```
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
```

**Comment by ironelder** [comment]
yeap.........um.....
Probably SAMPLE PROJECT seems old.
I try again. create new project.
Thank you!

**Comment by ironelder** [comment]
Thank you! rwillett!!
Android perfectly working!

but This time it does not work on IOS. ... ;;;;

Error Code:
Jan  2 19:51:38 hellojjui-MacBook-Pro SpringBoard[18254]: [DataStore] Could not load data at /Users/hellojj/Library/Developer/CoreSimulator/Devices/4EBB98F2-097A-4C23-84E7-D341CD22A246/data/Library/SpringBoard/PushStore/com.ionicframework.IonicLocalNotificationDemo837499.pushstore


Source Code:
[app.zip](https://github.com/katzer/cordova-plugin-local-notifications/files/680660/app.zip)


Have you seen any of these errors?

**Comment by katzer** [comment]
@ironelder 
> TypeError: Cannot read property 'notification' of undefined

Indicates that the plugin wasn't loaded. Either you're trying to access it to early or its not properly installed or other reasons.

Try `cordova build android` to fix project issues.

If you're using my sample app, sometimes I push the code while having the plugin installed with the `--link` flag. As you can see [here](https://github.com/katzer/cordova-plugin-local-notifications/blob/example/plugins/de.appplant.cordova.plugin.local-notification). Just remove the plugin and add it again.

**Comment by ironelder** [comment]
@katzer 
Hello katzer!
Thank you ! your notification Plugin!

I'm solve android LocalNotification

source Code : app.js
[app.zip](https://github.com/katzer/cordova-plugin-local-notifications/files/680668/app.zip)


but This Code iOS emulator is not working.

I do not know what's wrong. this Code.
Thanks you!

**Comment by katzer** [comment]
Just do the same steps for iOS platform and in case of you're using iOS 10, use the ios10 branch!
```sh
cordova platform remove ios
cordova platform add ios
cordova build ios
```

**Comment by ironelder** [comment]
@katzer 
Thanks you for anwser! 
I'm try again

CLI
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications/tree/ios10

right? ^_^

**Comment by katzer** [comment]
```
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#ios10
```

**Comment by ironelder** [comment]
@katzer 
Hello katzer !
very very Thank you !! your advice!!

iOS Perfectly working now!!

your genius!!  ^_^!!!

**Comment by rwillett** [comment]
If this works, please close the thread. 

Thanks

Rob

**Comment by ironelder** [comment]
@rwillett 
Hello rwillett :) !

this Issue closed this 3 days ago

thank you!
