### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by femioxantos** [katzer/cordova-plugin-local-notifications#1180]
Hi, i start a notification at 8:00 pm and repeat every minute, it works perfectly  in ios, but in Android, in some devices, it does not work correctly; with android jellybean shows notifications perhaps every 15 minutes aprox and with kitkat never starts.

this is my code:

function notificar() {
    var sonido = device.platform == 'Android' ? 'file://sound.mp3' : 'file://beep.caf';
    var fecha = new Date();
    fecha.setHours(20);
    fecha.setMinutes(20);
    fecha.setSeconds(0);

    cordova.plugins.notification.local.schedule({
        id: 1,
        title: "Recordatorio Monee",
        message: "No olvides introducir los datos del día en Monee!",
        firstAt: fecha,
        every: "minute", //"day"
        sound: sonido,
        icon: "http://domain.com/icon.png"
    });

    mostrarToast("Notificación iniciada");

}

Please help, thank you!

**Comment by rwillett** [comment]
Is this working now?

**Comment by katzer** [comment]
Please try with 0.9-beta
