### ISSUE TITLE
Without 'every', push doesn't fire with iOS 10

### ISSUE THREAD

**Issue by yesman99** [katzer/cordova-plugin-local-notifications#1183]
Hi Katzer/Team,

I am running: 
Monaca platform
Cordova 6.2.0
iOS 10.1.1 and 10.2
Android 5.1

As the code below, without every option the push1 doesn't fire with iOS 10(as far as I tried, 10.1.1 and 10.2).
Both pushes works fine with Android.

>cordova.plugins.notification.local.schedule([{
            id: 1,
            title: "push1",
            text: 'text1',
            at: new Date(now + 20000),
          }]);

>cordova.plugins.notification.local.schedule([{
            id: 2,
            title: "push2",
            text: 'text2',
            every: 'year',
            at: new Date(now + 20000),
          }]);

About background, I made an app at March, 2016. At that time the version of iOS was 9.2 and I had no problem with this plugin so I guessed the trigger is iOS 10.

For now I use "every: 'year'" instead and cancel them after fired.

Thanks

**Comment by rwillett** [comment]
I use the plugin without ```never:``` and it fires notifications fine for IOS 8,9 and 10 (10.1 & 10.2)

Which version of the plugin are you using?

**Comment by yesman99** [comment]
Thank you for your reply, rwillett.
I use v0.8.4 which is in master branch at this moment.

**Comment by rwillett** [comment]
Move to the ios10 branch for IOS10.

Rob

**Comment by yesman99** [comment]
Hello Rob,

In my case, with ios10 branch occurs this error.
`Error: undefined is not an object (evaluating 'cordova.plugins.notification.local'`

There is no error with master branch though.

**Comment by rwillett** [comment]
Than you've done something wrong, you're either calling cordova.plugins.notification.local before ```deviceready``` or you haven't installed the plugin correctly.

**Comment by fedepasi** [comment]
i have the same problem. Any Solution?

**Comment by stevengunneweg** [comment]
when setting the `every` parameter to `0` (the default value) manually I also see a warning in the console saying a string is expected for this parameter and I should use something like 'minute', 'hour', etc. Seems to be related.

**Comment by rwillett** [comment]
Since the OP has not come back, I'd suggest this thread is closed and a new one started using the template in #1188.

Thanks,

Rob
