### ISSUE TITLE
Notifications repeating randomly

### ISSUE THREAD

**Issue by nmarti** [katzer/cordova-plugin-local-notifications#1184]
I have an app that insert some yearly notification to remind about the birthday of the contacts.

Everything works fine, but we have reports that in 2 android devices the notifications are re-triggered randomly. This is an example:

28/12 - Tomorrow is the birthday of X
29/12 - Today is the birthday of X

02/01 - Tomorrow is the birthday of Y
03/01 - Today is the birthday of Y

05/01 - Tomorrow is the birthday of Z
06/01 - Today is the birthday of Z

08/01 (without any notification scheduled for this day) - Tomorrow is the birthday of X, Today is the birthday of X, Tomorrow is the birthday of Y, Today is the birthday of Y, Tomorrow is the birthday of Z, Today is the birthday of Z (all the past notifications are launched, but not re-inserted in the app code).

Any idea?

**Comment by Tawpie** [comment]
@nmarti There was a time (search issues) when restarting an Android would cause all notifications to fire. That was supposedly solved but it would be fruitful to review the issue and its resolution just to be sure you haven’t found something new.

**Comment by nmarti** [comment]
@Tawpie I saw the issue, but this is happening without restarting the devices, and only happening in 2 devices.

One device is a samsung galaxy S6, we have 2 galaxy S6 here and the issue not happens, only in this particular device. Is very very strange...

**Comment by Tawpie** [comment]
very frustrating when it seems isolated to a very small number of devices. And I’m not much help without the offending device in my hands… good luck!

**Comment by nmarti** [comment]
Ok so... I managed to solve it removing the "year" repeat, without any repeat all the notifications works fine for the moment.
