### ISSUE TITLE
Schedule Repeatedly on iOS

### ISSUE THREAD

**Issue by JustPepper** [katzer/cordova-plugin-local-notifications#1185]
Ok, im working on an app that requires local notifications every for example 8 hours, but as far as i know this wont work on iOS, i was trying to update de 'at' field when the notification triggers but this is currently not working on background just works when the app is open in foreground.. well right now im disabling notifications on iOS, but i just want to know if there is a way to handle this on iOS.

is an app to notify when u should take your pill. Like every 2 hours, i know i can make this work on Android with the every field.

**Comment by rwillett** [comment]
You have a limit of 64 notifications under IOS so you may well reach your limit using the ```every:``` flag. 

What I do is schedule them, for a specific time and then when the user starts the app up, schedule the next batch directly. 

The plugin does work in the background on IOS 8, 9 and 10 as we use it to schedule notification when the app is suspended.

**Comment by rwillett** [comment]
Closed as no update in six weeks.
