### ISSUE TITLE
Notification not triggered on ios10 when using every

### ISSUE THREAD

**Issue by fanals** [katzer/cordova-plugin-local-notifications#1191]
# Environment

Plugin version: ios10 branch
Platform: iOS
OS version: 10.2
Device manufacturer / model: 5S
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls): ios 4.3.1

# Expected Behavior

Should fire a notification every minute

# Actual Behavior

When using "every" the notification is not fired

# Steps to Reproduce

This is working :
`cordova.plugins.notification.local.schedule({text: 'Test', at: new Date()});`

This is not :
`cordova.plugins.notification.local.schedule({text: 'Test', at: new Date(), every: "minute"});`

**Comment by rwillett** [comment]
(```at:``` OR ```firstAt:```) AND ```every:``` do not work together on IOS 10 and it is unlikely they ever will as Apple appears to have changed their underlying framework. 

```every:``` *should* work OK but at the moment the IOS 10 code is buggy.

You will need to change your logic in your code.

Rob

**Comment by taigeair** [comment]
@rwillett so you think `every:` should work later on with future iOS updates? I'm trying it on 10.2.1 and it doesn't work yet. 

This is my code:
 $cordovaLocalNotification.schedule({
          id: 3,
          title: 'Every Minute',
          text: 'Text',
          every: 'minute'
        })

**Comment by rwillett** [comment]
Thats what I was told. I don't use every so can't state for certain.

**Comment by gogo217** [comment]
Hi @rwillett , I am also facing this issue, still don't have any solution yet?
I should use  both `at` and `every` in my project, could't find another ways.
Thanks.

**Comment by rwillett** [comment]
We do masses of scheduling and never use every or firstAt. 

We code around the problem  it was no big deal.

**Comment by Rukshar** [comment]
@rwillett how do you code around this? In my case, I scheduled the notifications at once for the upcoming 15 days, however, that is only possible if you already know how many days you want to push the notifications. I am kind of curious how you work around scheduling every day at a specific time. Because, on iOS, I am now seeing that after a few days everything I had scheduled, is gone.

**Comment by rwillett** [comment]
We have push notifications that send out notifications, these are only sent if the user hasn't logged on. if the user has logged on we use local scheduling as we get a chance to reschedule everything.

**Comment by Rukshar** [comment]
Thank you @rwillett

**Comment by katzer** [comment]
Please switch to 0.9-beta
