### ISSUE TITLE
Is it possible to set notification every specific number of days

### ISSUE THREAD

**Issue by zuna003** [katzer/cordova-plugin-local-notifications#1193]
**Your Environment**

Plugin version: _"0.8.4"_
Platform: _["ios", "android"]_
Cordova version (cordova -v): _6.4.0_
Cordova platform version :  _[android 6.0.0, ios 4.3.1]_

**Expected Behavior**
Set notification in every specific number of days.
Example it will notify every 3 days.

**Comment by rwillett** [comment]
There is an issue template that you should fill out properly. This helps us without us having to ask what you are doing. See #1188. We have no idea what your version of IOS or Android is.

However you cannot specify a repeating interval of three days, you will need to program it specifically.

Rob

**Comment by rwillett** [comment]
Closed as no update in four weeks.
