### ISSUE TITLE
Example of successful repeating callbacks

### ISSUE THREAD

**Issue by jashachik** [katzer/cordova-plugin-local-notifications#1195]
Good evening,

It looks like the callback functionality isn't working as expected.

My code:

```
window.cordova.plugins.notification.local.schedule({
      id: 1,
      title: "Message Title",
      text: "Message Text",
      at: date,
      every: 'minute',
      ongoing: true
    }, submitCallBack);
```

Please advise on how to get this working

**Comment by rwillett** [comment]
There is an issue template that you should fill in. This helps us without us having to ask what you are doing. See #1188.

However assuming you are using IOS 10, (```at:``` OR ```firstAt:```) AND ```every:``` do not work together on IOS 10 and it is unlikely they ever will as Apple appears to have changed their underlying framework. You will need to change your logic in your code.

Rob

**Comment by steveracine** [comment]
I have to say, I've seen this posted in just about every thread regarding repeating events, but I'm not seeing that behavior.  On my iPhone (iOS 10.2.1) I have a notification using firstAt and every together and it works perfectly.

**Comment by Tawpie** [comment]
Steve: FINALLY someone that has success… would you mind posting detail? Which *exact* plugin version (maybe your ‘cordova plugin add xxxxx’), how you setup your firstAt and every? That kind of stuff. A map for the rest of us!

TIA

**Comment by steveracine** [comment]
Sure.

I'm not using vanilla Cordova, but I'm building my project using PhoneGap, Cloud Builder, using the most recent version of the plugin.  In my config.xml I don't define a version number, so it will pull whatever the master version is.

To schedule the events I use the following settings:

```
{
	id: i+1,
	title: "STRING",
	text: "STRING",
	firstAt: firstNotification,
	every: "day",
	data: {JSON}
}
```

Then after I build an array of notifications to register, I call:

```
cordova.plugins.notification.local.schedule(reminders, function(){
	console.log('notifications scheduled');
	app.loadHUB();
});
```

There IS a warning that says "Unknown property: firstAt", but the notification will be delivered whether the app is running, in the background, or if the app is closed.

However, I should note that my app has multiple notifications and I'm only receiving a notification alert (for lack of better term) for the ones that were created FIRST.  I register 2 notifications at a different spot of my app and I never get the banner on my lockscreen, even though they are triggered as they come up when querying for "triggered" notifications.  Same code, but they don't come to the notification tray or lock screen.

Hope that's clear.  I'm still trying to debug the second issue, was going to make a new thread, but I'm at a loss as to why it wouldn't work.

**Comment by Tawpie** [comment]
Thanks Steve.

I’m always scared to death of JS unknown property warnings. Depending on the JS engine, things may or may not crap out when the engine encounters that error. I’ve found that iOS tends to stop interpreting the balance of the file once it encounters an error whereas Chrome desktop and Android ‘may’ carry on. Regardless, any time I have any kind of error/warning in JS I always eliminate it because once it occurs I don’t trust the interpreter anymore.

A separate issue is indeed in order, perhaps a third for the “unknown property: firstAt”—although they may be related if the lack of a firstAt property is causing the JS engine (or the native code) to stop interpreting the file.

**Comment by steveracine** [comment]
Very possible.  I'll try swapping out the "firstAt" and replace it with "at" to see if the notifications are still successful.  Something to note though, the only notification that actually arrives is the one that I schedule with "firstAt".  The others I use "at", but they are only 1 time events so I'm not using "every".

Will update after with results.

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no update from OP
