### ISSUE TITLE
Some events not firing, notably 0600 hours and 1200 hours

### ISSUE THREAD

**Issue by avanrossum** [katzer/cordova-plugin-local-notifications#1198]
# Initial Information

Plugin Version: de.appplant.cordova-plugin-local-notifications 0.8.4, fork: cordova-plugin-local-notifications-mm  1.0.5
_I switched to this fork at one point as an attempt to see if the issue was resolved.  It's the same in both_
Platform: PG/apple
OS version: 10.1, 10.2
Device manufacturer / model: iPhone 7+, iPhone 6S
Cordova version (cordova -v):  6.3.1/PG: 6.4.2
Cordova platform version (cordova platform ls): iOS 4.1.1
Plugin config: via NPM, no modifications.

# Expected Behaviour

Notifications should fire at the requested times, in this case, notably ~0600 and at 1200

# Actual Behaviour

All notifications fire consistently, other than the ones mentioned above.

# Reproduction/Situation

I'm going to include images with my app's own internal dev log from the process here as well.

Basically, what happens is this:

1. My JS code processes entries from an SQLite database, queueing up notifications in an array.  This works
2. After all notifications are queued, the application cycles through the array, and sends notification requests through the plugin
`cordova.plugins.notification.local.schedule({
                text: NotifyTextArray[counter],
                firstAt: NotifyTimeArray[counter],
                every: "day", }, NotifySetConfirm);'`
3. This process also logs to my internal dev console
![iphone image on 2017-01-23 at 10-10-21](https://cloud.githubusercontent.com/assets/25301314/22209421/68148b3e-e154-11e6-99e3-66a8e7ce5cc0.png)
and the call back verifies:
![iphone image on 2017-01-23 at 10-10-29](https://cloud.githubusercontent.com/assets/25301314/22209432/72d17f82-e154-11e6-9cbc-b850be3c5ece.png)
_Please note that the 'duplicate' entries are ok - I was frustrated with the last build and entered the name twice for each entry in the app - they aren't duplicated, the name of the person is duplicated._
4. The number of callbacks matches the number of requests.
5. Wait until the expected time _or_ advance time on device to 0600 or 1200
6. Notification doesn't fire
7. Wait/Advance to any other expected time
8. Notifications fire.

I'm not developing this on my Mac at the moment, so I don't have xCode dev logs.

Any assistance with this would be greatly appreciated.  Since the other notifications fire, I see no reason that this would be code error, but I'm not ruling it out.

Thank you!

**Comment by avanrossum** [comment]
Ok - so an update.  It's not as consistent as I had thought - even though these entries are firing the callbacks, it's not firing consistently.

**Comment by Tawpie** [comment]
@avanrossum Personally, I’m leery of the ‘every’ construct for scheduling notifications so I figure out the date/time for each notification individually and schedule them in bulk via an array. My concern about ‘every’ is the fact that iOS has a hard limit on the number of local notifications that can be scheduled, 64 is my recollection. I don’t know “for sure” how ‘every’ works, and while it would be nicest if an ‘every’ counted as 1 local notification to iOS I don’t know for certain that’s how it really works. Fortunately for me, my app doesn’t require me to find out.

We’ve been successfully using this plugin for a couple of years now by:
	— rescheduling notifications on every app launch/resume
		— computing fire date and times for each individual notification, 64 max (although our limit is lower ‘just in case!')
		— cancelling ALL notifications and in the cancel callback schedule the next batch—ALWAYS schedule using an array, never schedule via individual calls (arrays should be a rule for this plugin!)
	— we never update notifications, we always cancel them all and reschedule all of them

It is true that the user will run out of notifications if they receive all 64 notifications and still don’t open the app. At least with our app, when this occurs it’s pretty clear the user isn’t interested anymore so we’ve almost certainly already lost them. My guess is that the folks at Apple have a similar thought process with their limit of 64.

It’s really brute force (basic, simple and not clever at all) but unless you’re also targeting Windows Phone (which is horrifically slow scheduling with this plugin), it’s plenty quick enough.

**Comment by avanrossum** [comment]
@tawpie thank you for your response!

Definitely using arrays for this - learned that the hard way!

Like you suggest, we're definitely cancelling all notifications before requesting new ones, and don't do updates at all. Initially I tried to use the cancel callback to fire the new alerts, but it simply... wouldn't execute the new alerts. I will definitely try it again - could have been a bug in the code, because I am seeing the callback fire in my logs. 

I was not aware of the 64 notification limit - that's good to know. However, this particular issue appears immediately after scheduling new notifications (and after cancelling the old ones) so I don't think that it's related to 64 notifications stacking - unless you think it's 64 total scheduled notifications per app?

What I will do is attempt to schedule notifications "manually" and see if that works, as well as prompt the user to reopen the app for the 63rd notification. Due to the nature of this application, it's entirely feasible for the user to not actually open the app for up to two weeks (and in one case more) as once it's set, it doesn't need to be reviewed until the schedule needs changing (and that prompt is one notification that NEVER fails for some reason, also the first one scheduled). 

Would be nice if "every" didn't cause that issue...

Trouble is, we're averaging 6-8 notifications a day (if I combine(which is planned) two notifications that occur at the same time), so we're looking at 10 days max before they have to "reup"

I guess that's not a _huge_ deal. 

Again thank you for your suggestions - I will try them and see!

**Comment by rwillett** [comment]
There are issues with every: and at: when they combined. Its not clear if this is happening here.

To repeat what @Tawpie has said we do exactly the same (and I mean exactly the same) logic as they do.

I would agree that if the user doesn't come back in 64 notifications to your app, you've lost your user :)

Rob

**Comment by Tawpie** [comment]
Looking at this a little more—for clarity though, the 64 local notification per app limit was a characteristic of the now deprecated UILocalNotificiation method (which also treated recurring notifications as a single notification if the plugin implemented it correctly) https://developer.apple.com/reference/uikit/uilocalnotification. 

I haven’t followed the status of the iOS 10 updates to know if the plugin has been updated to use UNNotificationRequest, but if it has UNNotificationRequest’s API Reference https://developer.apple.com/reference/usernotifications/unnotificationrequest doesn’t mention a limit. That doesn’t guarantee there is no limit, but it does allow you to grouse if there is in fact some limit that isn’t mentioned in the doc.

It’s easy to miss details in prose, so here’s our code (my boss likes hungarian notation—it’s not as terrible as you’d think in JS though!)

// and finally schedule the reminders
if (gaMultiRemindersForKatzerLNPlugin.length) {
    cordova.plugins.notification.local.cancelAll(function scheduleAllRemindersViaKatzer() {
        cordova.plugins.notification.local.schedule(gaMultiRemindersForKatzerLNPlugin);
    });
} else {
    console.warn("  there were no reminders in gaMultiRemindersForKatzerLNPlugin to schedule");
}

**Comment by rwillett** [comment]
I can't comment on the IOS 10 updates and whether UNNotificationRequest is used. I do know it is being worked on and that the IOS 10 framework is different.

We'll wait and see what comes out.

Rob

**Comment by rwillett** [comment]
Is this still an issue or should it be closed?

**Comment by rwillett** [comment]
Since no update from OP am closing.
