### ISSUE TITLE
How to repeat x times from recurrence type.

### ISSUE THREAD

**Issue by bameff** [katzer/cordova-plugin-local-notifications#1199]
Hi, I have some question.
how to repeat x times from recurrence type.
example : I want to repeat every 30 hours 4 times in background (when dismiss app)

**Comment by rwillett** [comment]
You can't setup an repeating interval on 30 hours. You can do it on other intervals but not 30 hours.

You would have to schedule them directly e.g. work out each notification and then schedule it directly. 

Read the docs to see what you can do.

Rob

**Comment by bameff** [comment]
Thank you
