### ISSUE TITLE
Android SDK targeting > 23 with custom sound does not work

### ISSUE THREAD

**Issue by bolivir** [katzer/cordova-plugin-local-notifications#1202]
Hi,

At the moment if the target SDK > 23 the custom sound does not work with this plugin.
This issue is because > 23 file:// access is not allowed anymore and you should use the fileprovider to access the file.

Does someone have a implementation of this?, i already looked at the source and changed it to the fileprovider but i still get an exception (Permission denial) and dont know how to solve this at the moment.

**Comment by RobinVerheijen** [comment]
Facing the same problem, also trying to use res://. Not working indeed...

Please help!

**Comment by chevarria** [comment]
same problem here

**Comment by katzer** [comment]
that has been fixed
