### ISSUE TITLE
Remove large icon on Nougat

### ISSUE THREAD

**Issue by jamesl1001** [katzer/cordova-plugin-local-notifications#1203]
Is it possible to remove the large icon in Nougat notifications?

EDIT: My goal is to remove the large icon to allow more space for the text.

![](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0Bzhp5Z4wHba3azVPZUZQWkFyeUE/notifications_guidelines_11_large_icon_dont.png)

**Comment by John-Henrique** [comment]
You can try choose your own icon (tranparent perhaps)

**Comment by jamesl1001** [comment]
I have tried a 1px transparent image which does successfully hide the large icon, however it still takes up space in the notification.

The reason I want to remove the large icon completely is so that there is more space for the text.

If it is not already possible, considering that the large icon is meant to be optional, I'd like to suggest this as a feature for this plugin.

**Comment by katzer** [comment]
Please use 0.9-beta and only set `smallIcon`
