### ISSUE TITLE
Notification Repeats

### ISSUE THREAD

**Issue by mailparikshit** [katzer/cordova-plugin-local-notifications#1204]
i have scheduled a Notification thrice a minute
Example:
Schedule 1: 2017-02-02 14:23:12 
Schedule 2: 2017-02-02 14:23:32
Schedule 3: 2017-02-02 14:23:52

i get  3x3 Triggers 
For 4 Schedule in a minute provides 4x4 triggers (i.e. 4 trigger for 1st schedule,4 for 2nd,  and ...)

Schedule Code:

```
cordova.plugins.notification.local.schedule({
            id: notifyid, /* Unique id for all schedule */
            title: status,
            text: 'sch send',
            at:new Date(notifytime),  /* date Time */
            data: { key:'my schedule' },
            every: 0
        })

```

Trigger Code:

```
cordova.plugins.notification.local.on('trigger', function (notifications) {
          console.log(notifications.id); // printing Notification id's which shows 4 times,3 times repeat for  
                                                         //same id.
            
       
        }, this);
```

**Comment by rwillett** [comment]
Use the template in #1188 and provide more information please.

You'll need to provide more code as well. Such as how you calculate notifyid and notifytime.
