### ISSUE TITLE
Local notification fired multiple times on Windows 10 UWP

### ISSUE THREAD

**Issue by stevesum** [katzer/cordova-plugin-local-notifications#1208]
Plugin version: 0.8.5-dev
Platform: Windows
OS version: 10
Device manufacturer / model: Nokia Lumia 950
Cordova version (cordova -v): 6.5.0
Cordova platform version (cordova platform ls): windows 4.4.3
Plugin config: default

Expected Behavior:
I scheduled 10 notifications in same time, and there is a listener registered in the application on 'triggered' where I log the triggered notifications' data.
After a trigger, I re-registered the notifications, after I cancel the old ones.

Actual Behavior
The registered listener called back two times after the first schedule. After the cancel the old notifications and register the new ones, the listener will fired 3 times next time, and 5 times after that, etc.

Here is my registered notifications fist time:
`[{
         at: 1486459800,
         badge: 1,
          data: "{"DATO":"2017-02-07T09:30:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 1,
          sound: "res://platform_default",
          text: "Påminnelse!",
          title: ""
} {
         at: 1486460100,
          badge: 1,
          data: "{"DATO":"2017-02-07T09:35:00.000Z","USERS":{"0":1}}",
          every: undefined,
          id: 2,
          sound: "res://platform_default",
         text: "Påminnelse!",
          title: ""
}, {
         at: 1486460400,
         badge: 1,
         data: "{"DATO":"2017-02-07T09:40:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 3,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}, {
         at: 1486546200,
         badge: 1,
         data: "{"DATO":"2017-02-08T09:30:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 4,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}, {
         at: 1486546560,
         badge: 1,
         data: "{"DATO":"2017-02-08T09:35:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 5,
         sound: "res://platform_default",
         text: "Du har oversett varsler fra Min Felleskatalog. Vennligst åpne appen for å aktivere fremtidige varsler.",
         title: ""
}, {
         at: 1486546500,
         badge: 1,
         data: "{"DATO":"2017-02-08T09:35:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 6,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}, {
         at: 1486546860,
         badge: 1,
         data: "{"DATO":"2017-02-08T09:40:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 7,
         sound: "res://platform_default",
         text: "Du har oversett varsler fra Min Felleskatalog. Vennligst åpne appen for å aktivere fremtidige varsler.",
         title: ""
}, {
         at: 1486546800,
         badge: 1,
         data: "{"DATO":"2017-02-08T09:40:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 8,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}, {
         at: 1486632660,
         badge: 1,
         data: "{"DATO":"2017-02-09T09:30:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 9,
         sound: "res://platform_default",
         text: "Dette er siste påminnelse! Du har oversett varsler fra Min Felleskatalog. Vennligst åpne appen for å aktivere fremtidige varsler.",
         title: ""
}, {
         at: 1486632600,
         badge: 1,
         data: "{"DATO":"2017-02-09T09:30:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 10,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}]`

Here is my notifications registered second time:
`[{
         at: 1486460100,
         badge: 1,
         data: "{"DATO":"2017-02-07T09:35:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 1,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}, {
         at: 1486460400,
         badge: 1,
         data: "{"DATO":"2017-02-07T09:40:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 2,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}, {
         at: 1486546200,
         badge: 1,
         data: "{"DATO":"2017-02-08T09:30:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 3,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}, {
         at: 1486546500,
         badge: 1,
         data: "{"DATO":"2017-02-08T09:35:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 4,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}, {
         at: 1486546860,
         badge: 1,
         data: "{"DATO":"2017-02-08T09:40:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 5,
         sound: "res://platform_default",
         text: "Du har oversett varsler fra Min Felleskatalog. Vennligst åpne appen for å aktivere fremtidige varsler.",
         title: ""
}, {
         at: 1486546800,
         badge: 1,
         data: "{"DATO":"2017-02-08T09:40:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 6,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}, {
         at: 1486632660,
         badge: 1,
         data: "{"DATO":"2017-02-09T09:30:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 7,
         sound: "res://platform_default",
         text: "Du har oversett varsler fra Min Felleskatalog. Vennligst åpne appen for å aktivere fremtidige varsler.",
         title: ""
}, {
         at: 1486632600,
         badge: 1,
         data: "{"DATO":"2017-02-09T09:30:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 8,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}, {
         at: 1486632960,
         badge: 1,
         data: "{"DATO":"2017-02-09T09:35:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 9,
         sound: "res://platform_default",
         text: "Dette er siste påminnelse! Du har oversett varsler fra Min Felleskatalog. Vennligst åpne appen for å aktivere fremtidige varsler.",
         title: ""
}, {
         at: 1486632900,
         badge: 1,
         data: "{"DATO":"2017-02-09T09:35:00.000Z","USERS":{"0":1}}",
         every: undefined,
         id: 10,
         sound: "res://platform_default",
         text: "Påminnelse!",
         title: ""
}]`

Here is my function what register the new notifications:
`setNewSystemAlerts: function(alerts, callback) {
        var _this = this;
        cordova.plugins.notification.local.getAllIds(function(ids) {
            if (!!ids && ids.length > 0) {
                cordova.plugins.notification.local.cancelAll(function() {
                    _this.scheduleNewAlerts(alerts, callback);
                });
            } else {
                _this.scheduleNewAlerts(alerts, callback);
            }
        });
}`

What is your idea? May the cancel don't clear the old notifications, or the id should be unique for the re-registration also? But then why fired the trigger twice on first time?

The problem is happens only on the Windows platform, we use same code for iOS and android and on the other two platform works fine.

**Comment by stevesum** [comment]
Hmm... nobody found this error? Or this project is totally dead?

**Comment by stevesum** [comment]
I'm still waiting for any idea for this problem.

**Comment by rwillett** [comment]
I suspect nobody is using this plugin in Windows. 

We looked at Windows as a platform and found almost 0% market share in the UK. 

I wouldn't hold your breath for any help.

**Comment by stevesum** [comment]
Thanks. Unfortunatelly we have to release our app on windows platform because of a contract. So I'll try bugfix that part of the plugin. I'll send a patch if finished.

**Comment by rwillett** [comment]
My sympathies

**Comment by Tawpie** [comment]
Istvan:

Likewise my sympathies for having to support Windows… we used to support it (and paid Katzer to add it) but thankfully don’t have to do that anymore.

The main thing from when we did supoort windows: doing anything at all takes forever. Literally a second or two per notification. Be very aware of this fact and don’t start a new plugin action before all previous actions are completed!

So the thing I’d suggest is to pull out the getAllIds and just do the cancelAll with rescheduling in the cancelAll callback. This removes one (unnecessary) layer from the call stack. A simple cancelAll+reschedule worked for us back in the day.

Keep in mind that because windows phone is so slow, you are at risk of having the app force-quit while the plugin is grinding through getting things scheduled. But there’s not much that you can do about that.

**Comment by stevesum** [comment]
Hi Tawpie,
Thank your advices. Yes, I followed same rules in all application, and the
rescheduling of the notifications starts from the callback of the cancelAll
callback (if the getAllIds not empty).
The weird for me that the notifications fired twice on first schedule
already, what can't be a problem with the previously scheduled ones... and
on a second schedule they will fired 3 times, etc...
I realized the speed of the windows also... on the other platforms I
scheduled 60 notifications, on windows I had to limit that on 10.
I have few weeks before they ask me about the windows version of the app,
but I'll try to figure out what happens there.

2017-02-27 18:57 GMT+01:00 Tawpie <notifications@github.com>:

**Comment by stevesum** [comment]
I debugged this problem a little more, and I realized only the 'triggered' event is fired multiple times. So I made an simple javascript workaround and delay the execution of the listener callback for 1 sec, and clear the the previous one if a new arrived in 1 second.

**Comment by katzer** [comment]
The code for Windows is a full rewrite. Please test with 0.9-beta
