### ISSUE TITLE
Notification doesn't raise in notification bar

### ISSUE THREAD

**Issue by Siva-93** [katzer/cordova-plugin-local-notifications#1210]
Hi Katzer,

I'm using your Cordova-local-notification plugin in my Cordova app. 

In my project I used
1) https://github.com/katzer/cordova-plugin-local-notifications#ios10
2) Cordova 6.4
3) ios 4.3.1

So, this my problem. I can get the notification on the time, the trigger is working good. What the weird thing is happened means, the notification doesn't show in the notification bar in ios 10.1. But the same code working good on android.

var new_schedule = {
        id: 1,
        text: notificationTitle,
        at: timeStamp,
        badge: 1,
  };
cordova.plugins.notification.local.schedule(new_schedule, function() {
      console.log('notification scheduled');
    });
cordova.plugins.notification.local.schedule(new_schedule, function() {
      console.log('notification scheduled'); // it gives true
});

This is the code I used in my project. I even checked for permission also but it gives true for me. What would be the issue. Please help me.

**Comment by rwillett** [comment]
Use the template in #1188 to provide the right information.

When you update this, add in more about what you expect to see and when, e.g. is the app in the foreground or background? What are your notification settings in the control panel.

We get notifications appear at the top of the screen when we set them.

**Comment by Siva-93** [comment]
My environment: 
1) https://github.com/katzer/cordova-plugin-local-notifications#ios10
2) Cordova 6.4
3) ios 4.3.1
4) ios 10.1 device

Expected Behaviour: 
Notification should show in the notification bar when expected time is reached.

Actual Behaviour:
When notification time is reached, the notification badge is set, the trigger event is happening, the only thing it is not showing in the Notification bar either app is running in background or foreground. I have given enough permission for the app to get the notification in the notification bar. Tested in IOS 10.1 device.

Steps to reproduce:
Just install this plugin https://github.com/katzer/cordova-plugin-local-notifications#ios10 and set the notification.

**Comment by rwillett** [comment]
We use this specific plugin on IOS 10 and we do get notifications shown in the bar. See #1176.

**Comment by Siva-93** [comment]
Still I'm not getting it.

**Comment by rwillett** [comment]
You need to start to look into your code and configuration.

We have it working with that plugin version. 

I'd create a dummy app and start from there.

**Comment by rwillett** [comment]
Closed as no update from original poster
