### ISSUE TITLE
UTF-8 erro ?

### ISSUE THREAD

**Issue by ran-j** [katzer/cordova-plugin-local-notifications#1214]
I have a issue with this plugin , when the notification rise I got this :

[Pic](http://i.imgur.com/RASw35s.png)

Im using android 7.1

**Comment by rwillett** [comment]
Please use the template ini #1188 to provide more information.

**Comment by ran-j** [comment]
Plugin version:
Platform:0.8.4"
OS version:Android 7.1
Device manufacturer / model:LG G3 Titanium
Cordova version (cordova -v):6.4.0
Cordova platform version (cordova platform ls):Android 


My code:
`function shownotification(){
	
	cordova.plugins.notification.local.schedule({
		id: 1,
		title: message,
		text: 'ônibos chegando',
		sound: 'SYSTEM_DEFAULT',
		icon: 'res://notification.png',
		data: { key:'value' }
	})

	cordova.plugins.notification.local.on('click', function (notification) {
		alert('clicked: ' + notification.id);
	}, this);
		
}
`
I got caracter erros

**Comment by katzer** [comment]
OK, I will test that.

**Comment by katzer** [comment]
@ran-j I tried your sample and others and never had any issues with UTF-8 - cant reproduce.

**Comment by hasanreza** [comment]
@katzer I have the same problem
I tried to change the java code like this
`private Notification makeNotification(JSONObject settings) {
        String title =  new String(settings.getString("title").getBytes("ISO-8859-1"), "UTF-8");
...`
but it did'nt solve the problem.
[picture](https://ibb.co/g5x80H)

**Comment by claudvanbarret** [comment]
I solved this by inserting the code below into index.html.

`<meta charset="utf-8" />`
