### ISSUE TITLE
how to repeat sound and endless vibration ?

### ISSUE THREAD

**Issue by jfitzner** [katzer/cordova-plugin-local-notifications#1217]
when the notification is fired, the sound is playing one time and the phone vibrates for 30seconds. how can i change this? 
i want the phone to vibrate and repeating the sound endless..till the notification is confirmed by pressing on it. I have no clue how to do that.

**Comment by rwillett** [comment]
You need to use the template in #1188

**Comment by rwillett** [comment]
No update from original poster so closing.
