### ISSUE TITLE
Require support for Base64/image file url support (like in banner)

### ISSUE THREAD

**Issue by nbaua** [katzer/cordova-plugin-local-notifications#1218]
Hi,

Need local notification to show a banner using base64 data and/or file data url.
Please see the image below;

![preview](https://cloud.githubusercontent.com/assets/17998763/23099598/270e2684-f691-11e6-974a-ef82cedbb97f.png)

**Comment by rwillett** [comment]
Please use the template in #1188.

**Comment by nbaua** [comment]
Your Environment

Plugin version: Latest release
Platform: Android
OS version:  Android 5 (Lollipop) and Above
Device manufacturer / model: Standard Android Devices (Generic)
Cordova version (cordova -v): 5 and above
Cordova platform version (cordova platform ls): 4.3.0 onwards
Plugin config   

Using config.xml configured in a hybrid mobile app.
<plugin spec="https://github.com/katzer/cordova-plugin-local-notifications.git" source="git"/>

Expected Behavior

Require the notification to provide support for image banner (Base64 and/or file url).
![preview](https://cloud.githubusercontent.com/assets/17998763/23101584/f1a6c3a8-f6bc-11e6-9b27-daae810f471c.png)


Actual Behavior

Provided plug-in works fine, however do not know how to include the base64 image data and stretch the notification to the banner size

<img width="391" alt="happing" src="https://cloud.githubusercontent.com/assets/17998763/23101599/3e859ff0-f6bd-11e6-9a11-4f851eb86ecb.png">

Steps to Reproduce

_Not applicable_

Context

What were you trying to do?

_Not applicable_

**Comment by rwillett** [comment]
I don't think that this is possible but have left it as an enhancement.

**Comment by nbaua** [comment]
Oh, 
Thanks for considering the requirement as an enhancement. I am not sure how tight your schedule is, however I am hoping it is coming soon because I think this will be a big plus on the feature set currently we have.

Thanks anyways for developing such a nice plug-in, I am totally loving it. 👍 

NBaua

**Comment by rwillett** [comment]
I'm not the developer, I'm just helping out :)

I also don't think this is easily possible and would require significant coding, but thats for @katzer to answer.

**Comment by nbaua** [comment]
Hi rwillett,
Can you assign this issue to @katzer?

I would be nice, if this feature is implemented, I don't have clear idea of implementing this in the existing code base. 

I know my dish, How I want it to be prepared for me, however I ain't a good chef myself. :)

**Comment by rwillett** [comment]
I've left it as en enhancement. I think this is quite difficult to do though as I *think* the underlying Apple/Android frameworks don't support it. You would need custom coding and that might undermine the local notifications.

**Comment by nbaua** [comment]
Okey rwillett,
I've got your intent. I can understand its not that easy to alter the native code. It might tamper what is working best till date. Thanks for your prompt reply, You guys rock.

FYI,
Currently, I am leading the user to a custom view where the entire screen is presented with the banner content. I guess this works for now, however please keep me posted, if you guys play with your magic wend some time soon.

Thanks.

**Comment by katzer** [comment]
Please see the README. An example is mentioned there. Works for all platforms.
