### ISSUE TITLE
Q: Is there a way to keep playing the notification until user clicked on it?

### ISSUE THREAD

**Issue by kerryf88** [katzer/cordova-plugin-local-notifications#1220]
**Your Environment**
Plugin version: 0.8.4
Platform: iOS 9.3.4
OS version: Mac 10.11
Device manufacturer / model: iPad Air
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls): iOS 3.9.2

**Expected Behavior**
Repeat notification until user clicked on it

**Tell us what should happen**
When the scheduled notification time is up, the notification fired up, and is repeated at a set interval time (say every 5 minutes) until the user clicked open the notification.

**Actual Behaviour**
Not repeating notification

**Tell us what happens instead**
The notification only sound once for 30 seconds at scheduled time.

**Steps to Reproduce**
**Reproduce this issue; include code to reproduce, if relevant**

```
function onDeviceReady() {
var testAlert = new Date ("February 22, 2017 09:30:00");
cordova.plugins.notification.local.schedule([{
       id: 1,
       title: "Time to go to gym!",
      text: "It's now time for you to go to the gym!",
       sound: "file://sounds/amazing_ringtone.mp3",
      at: testAlert,
}]);
}
```

**Comment by Tawpie** [comment]
That would be plenty annoying! There’s no reason you can’t schedule a series of notifications 5 minutes apart, then when your app is launched cancel them all. Unfortunately for the user, they’ll get a separate notification in the notification tray/pulldown each time the notification went off but by clearing everything when your app is running they’ll disappear (sort of—iOS doesn’t automatically clean the notification pulldown of notifications that weren’t clicked on). Their (android) menu bar will be stuffed with your app logo until they act though. Keep in mind that the ‘every’ method of scheduling has been known to misbehave and that both platforms either do or could have limits on how many discrete notifications can be scheduled at any given time.

**Comment by kerryf88** [comment]
Is there a simpler way of doing it? Like instead of scheduling multiple notifications 5 minutes apart without using the "every", if the user didn't open the app in say two hours, I'd have to set 24 different notifications? 
As there will be other notifications time being scheduled as well, so by doing it this way I'd go over the 64 notification limit pretty quickly. 

Or is there a way to keep the current notification sound continue ringing until user open the notification? At the moment it only goes for 30 sec.

**Comment by rwillett** [comment]
I have to agree with @Tawpie, this would be so annoying. I also think that Apple would reject your app for this.

As far as I know there is no way of doing this with this plugin.

You could easily do it with Push Notifications though as you can keep sending notifications to the device. However we know from our own app that users hate having too many notifications and after a while they just ignore them or delete the app. We monitor the number of full push notifications we send and throttle back after 15 mins.

**Comment by kerryf88** [comment]
I had thought about push notification, but that require internet connection, but my app needs to work without internet connection. I forgot to mention I'm not planning to publish the app, the app is built for the purpose of conducting trials for my research project. 

I found a forked version of this plugin that loop the notification sound until user clicks it but then that's for android and not possible with iOS due to the 30 sec limit.

**Comment by rwillett** [comment]
I think you will have to write your own code to do this then.

**Comment by kerryf88** [comment]
I'm not asking anyone to write the code for me. I wrote the whole app by myself, but was just asking if there is a way to loop through the notification sound until user clicked on it. If there isn't any as stated above, then I'll try and work my way around it. Thanks for the help anyways.

**Comment by rwillett** [comment]
Don't think there is a way round this at the application level. You could look at the Background fetch plugin as that gives a you a little background processing time but IOS is very, very restrictive on what you can do. Its designed that way, Apple is even more restrictive.

**Comment by WiNNiep00h** [comment]
i think you can repeat the notification with 'every'. and in the click callback you can cancel all notifications.

**Comment by WiNNiep00h** [comment]
> Or is there a way to keep the current notification sound continue ringing until user open the notification? At the moment it only goes for 30 sec.

I'm searching exactly for this. i want my app to ring and vibrate till the user pressed the notification. if anybody has a solution for that, please help me :)
At the moment the sound is just played once, and the vibration stops after around 30 seconds. i was just able to repeat the notification each minute, but its not realy what i wanted.

**Comment by rwillett** [comment]
This can't be done using this plugin. You will need to find another way of doing this.

**Comment by rudreshsp** [comment]
Hello sir you can try with type alarm.. here it will play sound until u drag down the notification screen..
code is very simple

Uri uri= RingtoneManager.getDefaultUri(RingtoneManager.TYPE_ALARM);
  nBuilder.setSound(uri);

working for me

**Comment by yasanapriya** [comment]
Please use FLAG_INSISTENT:this will make continous sound until the user drag the notification(status bar).
