### ISSUE TITLE
Support for providing sound from res://

### ISSUE THREAD

**Issue by sunny061** [katzer/cordova-plugin-local-notifications#1221]
**Your Environment**

Plugin version: 0.8.4
Platform: android
OS version: Android OS 6.0.1
Device manufacturer / model: Samsung Galaxy A5 (2014)
Cordova version (cordova -v): 6.5.0
Cordova platform version (cordova platform ls): android 6.1.2
Plugin config: default

**Expected Behavior**

It should play the custom sound when a notification is created.

**Actual Behavior**

It doesn't play sound from Android "res://". It does work when using "file://" but I want to use res just like the URI for icon.

**Steps to Reproduce**

cordova.plugins.notification.local.schedule({
    id: 1,
    title: "Production Jour fixe",
    text: "Duration 1h",
    icon: "res://icon.png",
    sound: "res://raw/sound.mp3",
    data: { "test": "test" }
});

**Context**

Trying to play custom sound for local notification using sound placed in Android res

**Debug logs**

02-21 15:22:09.475 28925-29874/com.*****.******* E/Asset: File not found: raw/s03.mp3
02-21 15:22:10.635 2425-30658/? W/RingtonePlayer: error loading sound for 
                                                  java.io.IOException: setDataSource failed.
                                                      at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1256)
                                                      at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1164)
                                                      at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1101)
                                                      at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1082)
                                                      at com.android.systemui.media.NotificationPlayer$CreationAndCompletionThread.run(NotificationPlayer.java:93)

**Comment by rwillett** [comment]
Please use the template in #1188 and update the issue.

**Comment by sunny061** [comment]
@rwillett Sorry, I've updated the issue now.

**Comment by rwillett** [comment]
1. Saying the latest version of the plugin is wrong. If a new version of the plugin comes out, this issue is incorrect.

2. Why can't you use ```res:```?

**Comment by sunny061** [comment]
@rwillett My bad again. I've updated the post with the exact version. And I don't know why I can't use res:. I can use it to set the icon but it does not work for the sound. I checked the logcat and it is unable to find the file. My sound is kept in....platforms/android/res/raw/sound.mp3. I also have a copy of the sound in the www folder which I can use with file: but I want to use res:. I also dont see an example in the docs where they show how to use a custom sound kept in the res: of android.

**Comment by rwillett** [comment]
Do you need to copy the mp3 over from the right directory?

We have to copy over the notification icon from $root/res/..... to the platforms folder for each android build. We use a hook to do this.

**Comment by sunny061** [comment]
Yes, I do have a cordova hook to perform that action. And I can confirm that the mp3 is in the correct directory. The push plugin is already using the sound kept in res/raw. But this plugin cannot find the file.

**Comment by rwillett** [comment]
This sounds like a bug then.

**Comment by katzer** [comment]
With 0.9-beta just use `sound: "res://sound.mp3"` if its located under the raw folder. I will also add support for Androids native "content://" scheme before 0.9 comes out.
