### ISSUE TITLE
Android 6.0: notification icon does not change

### ISSUE THREAD

**Issue by tschuppi** [katzer/cordova-plugin-local-notifications#1222]
Hi,

### My Environment

Plugin version: Latest
Platform: Android
OS version: 6.0+
Device manufacturer / model: Nexus 5
Cordova version (cordova -v): 6.3.1
Cordova platform version (cordova platform ls): 5.2.2

### Plugin config

                    'icon = "file://images/" + icon;
                    cordova.plugins.notification.local.schedule({
                        id: data.msgType,
                        title: title,
                        text: data.message,
                        icon: icon,
                        data: {
                            sender: data.sender,
                            msgType: data.msgType
                        }
                    });'

I simply want to assign a custom image that will be displayed instead of "icon" and "smallIcon".

### Expected Behavior

The standard 'bell icon' with grey background should be replaced by my image file.

### Actual Behavior

The 'bell icon' with grey background is still displayed.

### Context

I tried different file paths, but there was no change. When i placed my favorable image in "res"-folder and changed the icon parameter to 'icon' it displayed a white rectangle, but thats not what i wanted.
Before Android 6.0 everything worked fine with the code snippet above.

**Comment by rwillett** [comment]
You have the notification png in the wrong place. You need to use a hook to move the icon to the right place in the android platforms. Google for "cordovas hook android notidfication icon".

**Comment by tschuppi** [comment]
Thanks! That was the correct impulse for me.
Solved the problem with the following knowledge:

https://cordova.apache.org/docs/en/6.x/guide/appdev/hooks/index.html
https://gist.github.com/dpogue/a382e9f048b09d490d4e
https://github.com/katzer/cordova-plugin-local-notifications/wiki/10.-URIs

Next problem is:  I am able to change the white icon in the center, but how can i change the background color?

**Comment by tschuppi** [comment]
Found the solution:

https://github.com/katzer/cordova-plugin-local-notifications/issues/874
