### ISSUE TITLE
Notification Banner Not Appearing for Some Notifications

### ISSUE THREAD

**Issue by steveracine** [katzer/cordova-plugin-local-notifications#1223]
**Your Environment**

Plugin version: 0.8.4 (npm)
Platform: PhoneGap cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3)
OS version: iOS 10.2.1
Device manufacturer / model: iPhone 6
Cordova version (cordova -v):
Cordova platform version (cordova platform ls):

**Plugin config**
Expected Behavior
I schedule notifications at two places in my project.  One of them will schedule 1 or 2 recurring reminders that are invoked daily.  The other location schedules 2, one-time reminders.

Tell us what should happen
User should receive notifications (banner, notification tray) at specified scheduled times.

Actual Behavior
One set of notifications work as expected.  The banners and notifications come to the lock screen.  The second set that are one-time events will register the "trigger" event, but they are not delivered to the lock screen, banner, or notification tray.  When querying for triggered events, the notifications will come through as "triggered", but never display.

**Tell us what happens instead**

Steps to Reproduce

Reproduce this issue; include code to reproduce, if relevant

Working code, in a loop creating an array of notifications:
```
reminders[i] = {
	id: i+1,
	title: "Medication Reminder",
	text: "It's time to take your " + controllerInfo,
	at: firstNotification,
every: "day",
	data: {type: "medication", medID: profileSettings.controllerID, time: profileSettings.controllerReminders[i]}
}
```
outside the loop, I call the schedule method with the array:

```
cordova.plugins.notification.local.schedule(reminders, function(){
	console.log('notifications scheduled');
	app.loadHUB();
});
```

This is the second area that I am creating reminders.  These do not get delivered to the lock screen, but the "trigger" event is triggered:

```
var notificationTime = new Date(reminderTime.getTime()-259200000);
var notificationTimeFinal = new Date(reminderTime.getTime()-3600000);
var reminders = [
			{
				id: 3,
				title: "Appointment Reminder",
				text: notificationText,
				at: notificationTime,
				every: "0",
				data: {
					type: "appointment"
				}
			},
			{
				id: 4,
				title: "Appointment Reminder",
				text: notificationText,
				at: notificationTimeFinal,
				every: "0",
				data: {
					type: "appointment"
				}
			}
		];

		console.log("reminders = %o", reminders);

		cordova.plugins.notification.local.schedule(reminders, function(){
			console.log('notifications scheduled');
			executeDB();
		});
```

Context

What were you trying to do?

Debug logs

Logs from when the non-working notifications were created and scheduled
```
[Log] ------ saveEditAppointment ------ (console-via-logger.js, line 173)
[Log] appt date= 2017-02-25 (console-via-logger.js, line 173)
[Log] appt time = 22:05 (console-via-logger.js, line 173)
[Log] reminderTimeParts = 22,05 (console-via-logger.js, line 173)
[Log] remdinerDateParts = 2017,02,25 (console-via-logger.js, line 173)
[Log] notificationText = You have an appointment on Saturday, February 25, 2017 at 10:05 PM (console-via-logger.js, line 173)
[Log] notificationTime = Wed Feb 22 2017 22:05:00 GMT-0500 (EST) (console-via-logger.js, line 173)
[Log] notificationTimeFinal = Sat Feb 25 2017 21:05:00 GMT-0500 (EST) (console-via-logger.js, line 173)
[Log] reminders =  (console-via-logger.js, line 173)
Array (2)
0 Object

at: 1487819100

badge: 0

data: "{\"type\":\"appointment\"}"

every: "0"

id: 3

sound: "res://platform_default"

text: "You have an appointment on Saturday, February 25, 2017 at 10:05 PM"

title: "Appointment Reminder"

Object Prototype
1 Object

at: 1488074700

badge: 0

data: "{\"type\":\"appointment\"}"

every: "0"

id: 4

sound: "res://platform_default"

text: "You have an appointment on Saturday, February 25, 2017 at 10:05 PM"

title: "Appointment Reminder"

Object Prototype

Array Prototype

[Log] notifications scheduled (console-via-logger.js, line 173)
```

Logs of resuming the app after events were scheduled
```
[Log] there were 2 notifications triggered since app was last started... (console-via-logger.js, line 173)
[Log] Array (2) (console-via-logger.js, line 173)

// notification that worked
0 Object

at: 1487818800

badge: 0

data: "{\"type\":\"medication\",\"medID\":\"20\",\"time\":\"22:00\"}"

every: "day"

id: 1

sound: "res://platform_default"

text: "It's time to take your Pulmicort (Budesonide) - 0.25mg"

title: "Medication Reminder"

Object Prototype

// notification not delivered to lock screen
1 Object

at: 1487819100

badge: 0

data: "{\"type\":\"appointment\"}"

every: "0"

id: 3

sound: "res://platform_default"

text: "You have an appointment on Saturday, February 25, 2017 at 10:05 PM"

title: "Appointment Reminder"

Object Prototype

Array Prototype

```

Any help is appreciated.  I'm at a bit of a loss, as it seems that the scheduling is the same in both instances.

Just a side note, the recurring notifications repeat correctly and are always delivered at the scheduled times.

Thanks!

**Comment by rwillett** [comment]
A decent write up for once :)

Thoughts:

1. You are using an older version of the plugin. There are issues with that plugin and ios10.

2. Have you checked the date and times are what you expect. I can see ```var notificationTime = new Date(reminderTime.getTime()-259200000);```. I'd very carefully check these dates expressions do what you expect. Its very easy to lose a couple of digits and find the times are nowhere near what you think you have done. We do two debugging checks, we convert to an ISO date AND we use http://www.epochconverter.com/ to make sure. 

3. I'd remove the ```every:``` from your second test case and see if that works. 

4. Check the Id's you are using are not being overwritten. We use a Angular service to provide unique ID's across our app "just-in-case". 

We use multiple scheduling in different places in our app but not repeating notifications. We manage that ourselves. 

As a note, Apple changed the underlying functionality of IOS10 for local notifications and its very, very likely that every: and first: will not be supported together. I'm not the author of this plugin, but @katzer occasionally keeps me up to date.

**Comment by steveracine** [comment]
Thanks for your response, your feedback is definitely appreciated.

A few bits of feedback based on your questions:

1.  I'm fairly new to using npm and this is my first PhoneGap project, so please bear with me.  How can I specify that the ios10 branch be used from npm?  Maybe I was reading it wrong, but when I looked at the ios10 branch it said that it was behind master by several commits.  

2. Here are the variable outputs from the reminders that are not coming to the lock screen, see below.  Just as a side note, the "trigger" events for these reminders is executed at the correct time.  The problem is that the system notification is never received.  So, the app sees that the reminder was "triggered" but I never receive a notification.

```
// Date/time stored in db
[Log] appt date= 2017-02-25 (console-via-logger.js, line 173)
[Log] appt time = 22:05 (console-via-logger.js, line 173)

// Date/time split into arrays to build new date objects
[Log] reminderTimeParts = 22,05 (console-via-logger.js, line 173)
[Log] remdinerDateParts = 2017,02,25 (console-via-logger.js, line 173)
[Log] notificationText = You have an appointment on Saturday, February 25, 2017 at 10:05 PM (console-via-logger.js, line 173)

// Date object for one notification (appointment time - 3 days)
[Log] notificationTime = Wed Feb 22 2017 22:05:00 GMT-0500 (EST) (console-via-logger.js, line 173)

// Date object for second notification (appointment time - 1 hour
[Log] notificationTimeFinal = Sat Feb 25 2017 21:05:00 GMT-0500 (EST) (console-via-logger.js, line 173)
```

3.  I actually didn't have every: in it originally, but what I noticed is that the default value of "0" was not being set in the reminder object.  When I output the reminder in the trigger event, every: was coming through as "undefined".  So, I'm not sure if that's a bug or expected behavior, as the wiki indicates the default value is "0" for a one-time event.

4.  I use defined reminder ID's for each one.  I know that I will never have more than 4 events scheduled, so the appointment reminders are hardcoded at 3 and 4.  The only time that they will be overwritten is when I schedule new appointment reminders.

It's a really bizarre issue because the "trigger" event is being fired correctly, but the system notification never comes through.  I'm sure that I am being a little ambiguous with my description, but I'm at quite a loss for how to explain it.

Thanks again for your feedback!

**Comment by rwillett** [comment]
1. cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#ios10

2. OK

3, You don't need ```every:```. We don't use it at all.

4. Have you looked at the output using Safari debug mode as opposed to Xcode?

Try with the IOS10 branch and see what happens.

**Comment by rwillett** [comment]
Closed as no update from user after four weeks.
