### ISSUE TITLE
How do you ask for permission again after user initially denies permission?

### ISSUE THREAD

**Issue by BenLorantfy** [katzer/cordova-plugin-local-notifications#1224]
A second call to `cordova.plugins.notification.local.registerPermission` after the user already taps "Don't Allow" doesn't show another popup but instead just calls the callback with granted = false.

**Comment by jkhax0r** [comment]
Don't take this as fact, but I want to say I read somewhere that it will only prompt once and if the user denies then they have to go manually change the setting.

**Comment by rwillett** [comment]
You would have to put an alert up telling the user what to do.

**Comment by katzer** [comment]
Its an limitation by the OS. The dialog will popup only the first time.
