### ISSUE TITLE
crash app because outofmemory 

### ISSUE THREAD

**Issue by elji23** [katzer/cordova-plugin-local-notifications#1226]
Hello guys, I devellop an app for android phone and I have a big issue when i get too many notifications from my user account, my app is slow or may stopped because the notications come very fast on app loading in my homepage and apparently the garbage collector don't have the time to do his job which causing a fattal error because my device have an `OutOfMemoryError`!

I tried to setTimeOut to my `notification.local.schedule` to delay my notications from the other task but it doesn't look to change anything.

I also tried to setInterval to my `notification.local.schedule` to delay my notications incoming frequency but it doesn't look to change anything neither.

I didn't see any example to handle a lot of notifications so if you hanve any idea, that's will be really great.

I share my log here.

Thanks,
[outofmemory_console-log.txt](https://github.com/katzer/cordova-plugin-local-notifications/files/803801/outofmemory_console-log.txt)

**Comment by rwillett** [comment]
Why not throttle the number of notifications being sent? Send them every five seconds rather than using a timeout function. 

If there as so many notifications coming in, then surely your user will ignore them as they simply become a blur.

**Comment by elji23** [comment]
@rwillett thx for your answer.
I was afraid to be misunterdand, I try to explain ... if my user reconnect to his account I get all the notifications remain for his treatment (think of 3 pills at least, 3 times by days for 60 days ) for the 
remaining time and the notifications will come (schedule) in time when it's planned to be taken (it's a reminder) so my user don't have many notifications in a same time.
So, when I get my notifications I have a lot to get and I don't know how I can optimize this...
I don't know where it's save but for the moment It's in the RAM I think, is it the way?

**Comment by rwillett** [comment]
Mmmm....

If you are sending 3 x 3 x 60 notifications to somebody to take pills, thats 540 notifications. If they need reminders to take their pills, sending 540 notifications and expecting them to work through each one, deleting the notification individually sounds like a bad user experience. 

I still don't think I understand the problem though. Are you getting local notifications popping up when the app starts? Why? Notifications should appear when scheduled. Not when the app starts.

There is no problem with the Android app being closed and scheduled notifications being sent out. So why do you get hundreds of notifications?

**Comment by elji23** [comment]
You are understand :) The notifications don't come out when the app start but when scheduled. for example, "this morning you need to take this two pills" so it's ok for the user expérience.
My issue is when my user start the app and log in ( because he install the app in a new phone for example ) I get all the data as you can see in the log I post

**Comment by rwillett** [comment]
Then you have to query the app when it starts up, cancel all the outstanding notifications, and reschedule them slowly over a period of a few minutes so you throttle the number of notifications that way.

Its not difficult to do.

**Comment by elji23** [comment]
I understand, I don't know how I can reschedule them slowly?
I think it's not my only issue because I get my notification every time I go to the home! I will try to optimize my code to ask them only when I need to and I come back to tell you if it works better :)

just to be sure, `notification.local.cancel` delete the notification schedule?

**Comment by rwillett** [comment]
You reschedule them slowly by setting up the time at which they are displayed over a longer period of time.

Is this still an issue otherwise I will close it.
