### ISSUE TITLE
Schedule delay on Android

### ISSUE THREAD

**Issue by a00s** [katzer/cordova-plugin-local-notifications#1229]
Following the new documentation for android I think would be necessary to change the line to have the schedule on the right time.
https://developer.android.com/reference/android/app/AlarmManager.html

I beleave on notifiction.java
line 182
getAlarmMgr().set(AlarmManager.RTC_WAKEUP, triggerTime, pi);
should became
getAlarmMgr().setExact(AlarmManager.RTC_WAKEUP, triggerTime, pi);

I tested this changed and I have a working schedule

**Comment by ernofi** [comment]
I agree. This solved my problem when notifications came 1 to 30 seconds late.

**Comment by dellagustin** [comment]
I had the same problem and the solution from @a00s worked for me.

**Comment by dellagustin** [comment]
It would be interesting ot add a parameter to the schedule interface like "exact" to decide wether you need to use set or setExact.

**Comment by katzer** [comment]
See https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/android/notification/Notification.java#L200

**Comment by woegjiub** [comment]
setExact was added in API level 19, meaning this is only available for KitKat or later.

Would it be possible to add the old code back in for < 19?

**Comment by katzer** [comment]
@woegjiub Only Android 6+ is supported.

**Comment by woegjiub** [comment]
That's very alarming news, it leaves almost 50% of devices out in the cold.

Might be worth noting in the readme. I'll have to look for an alternative.

**Comment by katzer** [comment]
For Android 5 or older you can use v0.8.x

**Comment by katzer** [comment]
Possibly that I will decrease to Android 5+, however full support only for Android 6+.

The main reason for Android 6+ is [NotificationManager.getActiveNotifications](https://developer.android.com/reference/android/app/NotificationManager.html#getActiveNotifications()).
