### ISSUE TITLE
Single Schedule Error on iOS

### ISSUE THREAD

**Issue by samukt** [katzer/cordova-plugin-local-notifications#1230]
Hello friends.
I'm using the plugin but found some bugs (I think).

When I'm trying to compile this:

	cordova.plugins.notification.local.schedule({
	       id: 198123712737123721,
	       title: "Production Jour fixe",
	       text: "Duration 1h",
	       firstAt: _5_sec_from_now,
	       //every: 0,
	       data: { meetingId:"123#fg8" }
	});

A error is showed in XCode:

       2017-03-01 08:24:20.325918 Henry[3056:558841] WARN: Unknown property: firstAt

And the notification don't open.

**But if I use THE SAME CODE with "every" option filled it runs perfectly.**

            cordova.plugins.notification.local.schedule({
                id: 198123712737123721,
                title: "Production Jour fixe",
                text: "Duration 1h",
                firstAt: _5_sec_from_now,
                every: 'minute',
                data: { meetingId:"123#fg8" }
            });

How can do I a single notification?

I also have tried:

    cordova.plugins.notification.local.schedule({
        id: 1,
        text: "Single Notification",
        sound: isAndroid ? 'file://sound.mp3' : 'file://beep.caf',
        data: { secret:key }
    });

And didn't work too.

I tried:
every: 0 --> Error.
Don't pass firstAt and every options ---> Error.
Use at in place of firstAt and don't pass every ---> Error.

I think it's about firstAt and every.

**Comment by rwillett** [comment]
Fill in the template at #1188. 

There are issues with ```firstAt``` and ```every:```.

If you want to send a single notification ```at:``` works fine.

**Comment by rwillett** [comment]
Closed as no response from original poster.
