### ISSUE TITLE
Update always vibrates?

### ISSUE THREAD

**Issue by Rlopez** [katzer/cordova-plugin-local-notifications#1231]
The use case I have in mind is to keep some data (on an external device that's monitored through Bluetooth) as a notification entry. From time to time (the device gets disconnected, or its data changes) I am trying to update the contents of the notification, e.g.:
```
cordova.plugins.notification.local.update({
	id: 0,
	title: "Solog is monitoring",
	text: "Battery level: " + batteryPercent + " %  " + (power > 0?"Charging":"Discharging") + ": " + power.toFixed(2) + " w/h"});
```
What happens is that, about six seconds after that code is executed, the phone vibrates. If that code is commented the vibration is gone, so I am assuming it has to be this.
Is there any way to keep a notification up and update its value without triggering a vibration?

thanks!

**Comment by rwillett** [comment]
Closed as no update from original poster.

**Comment by Rlopez** [comment]
Apologies I never got any request for more information.
The issue still happens to me and it is trivial to repro, is there anything you'd want me to check to confirm this issue?
thanks!

**Comment by rwillett** [comment]
AFAIK there is no way to disable the Android vibration. There should be, but there doesn't appear to be. I would prefer it to be off and to add in a separate vibration.

There is a patch to do this #1001 but I'm never tried it.

**Comment by Rlopez** [comment]
Oh, that's a good tip! I'll try that and will report back!
thanks!

**Comment by rwillett** [comment]
Did the patch work?

**Comment by Rlopez** [comment]
I haven't tried it yet :|!
Sorry for that, got into putting-off-fires mode for the last few weeks..
and I won't be using it in the project (for a while at least). But!! it
doesn't cost me much to give it a shot and report back if that's of any use
to you :)

**Comment by katzer** [comment]
Please reopen if its still an issue.
