### ISSUE TITLE
Android 6.0 there is delay around 4 -5 seconds

### ISSUE THREAD

**Issue by leorajdsouza** [katzer/cordova-plugin-local-notifications#1232]
Plugin works fine in android version below 6.0. But in 6.0 there is delay around 4 -5 seconds

**Comment by rwillett** [comment]
This is a known issue on some versions of Android. Android does not guarantee immediate delivery.

**Comment by madhavhambar** [comment]
facing the same problem

**Comment by rwillett** [comment]
This is (sadly) known behaviour with Android. Not a lot can be done AFAIK.

**Comment by dariusvelavicius** [comment]
Are you sure? https://developer.android.com/reference/android/app/AlarmManager.html

> Note: Beginning with API 19 (KITKAT) alarm delivery is inexact: the OS will shift alarms in order to minimize wakeups and battery use. There are new APIs to support applications which need strict delivery guarantees; see setWindow(int, long, long, PendingIntent) and setExact(int, long, PendingIntent). Applications whose targetSdkVersion is earlier than API 19 will continue to see the previous behavior in which all alarms are delivered exactly when requested.

wouldn't using setExact help?

**Comment by rwillett** [comment]
Its not clear that this plugin uses that code. I suspect not. I don't think you can guarantee that sort of accuracy with this plugin.
