### ISSUE TITLE
getTriggeredIds not working on Windows Phone 10 UWP

### ISSUE THREAD

**Issue by diesalro** [katzer/cordova-plugin-local-notifications#1234]
## Your Environment
- Plugin version: 0.8.4
- Platform: windows
- OS version: 10.0.14393.693
- Device manufacturer / model: Microsoft Lumia 650 Dual SIM
- Cordova version (cordova -v): 6.1.1
- Cordova platform version (cordova platform ls): 4.3.2
- Plugin config: `<plugin name="de.appplant.cordova.plugin.local-notification" version="0.8.4" />`
## Expected Behavior
The plugin retrieves an array of triggered Ids.
## Actual Behavior
The plugin is always returning an empty array.
## Steps to Reproduce
1. Schedule a local notification
2. Close the application
3. Once you receive the notification, don't click on it
4. Open the application by clicking on the app icon
5. getTriggeredIds is returning an empty array instead of the ID from the recently triggered notification
## Context
I'm trying to retrieve the data from the received notification to display a counter of received notifications which the user hasn't read.
I'm binding the event like this:
```
cordova.plugins.notification.local.getTriggeredIds( function (ids) {
	// My code goes here
}, cordova.plugins );
```

**Comment by katzer** [comment]
Please try with 0.9-beta - the code for windows is a full rewrite in C#
