### ISSUE TITLE
Enhamcement Required - 'Big picture'

### ISSUE THREAD

**Issue by nbaua** [katzer/cordova-plugin-local-notifications#1235]
Hi,

Looking forward to implement this feature:

Please visit:  https://material.io/guidelines/patterns/notifications.html#notifications-templates
Look for: 'Big picture'
Big picture template for collapsed and expanded notifications

Thanks.

**Comment by adi928** [comment]
+1 to this!

**Comment by rwillett** [comment]
I've flagged this as en enhancement. I can't comment if it will be done.

**Comment by nbaua** [comment]
Thanks rwillett,

For considering this as an enhancement. I can understand if its going to take a while it sure does.
However I am hoping to have this soon. Thanks. You guys are awesome.

Regards,
NBaua

**Comment by adi928** [comment]
Hi @nbaua ,
I was trying to implement the asked functionality. 

![image](https://cloud.githubusercontent.com/assets/2073268/24014525/512d8de6-0aab-11e7-84d9-e088c5fd2304.png)

But having custom image is still in progress. So this was done using a hard-coded image. Let me know your thoughts.

**Comment by nbaua** [comment]
Hi Aditya Nath,
Your implementation looks great, However I am not sure why the 'CLEAR ALL' button hangs in air, may be you have the 'Overflow' issue on container control.
For dynamic image purpose I guess we can have the control read some JSON (either from service or config). OR the better way is keep a variable/property which takes input as BASE64 string and application view can set/change it at run-time. than you just need to update your image control with the said BASE64 string and its done.

Regards,
N. Baua

**Comment by adi928** [comment]
This kind of Clear button is a by default kind of implementation in Nexus devices. I tried adding an extra value to JSON and currently trying to retrieve that. But having an image in native android is a real struggle here.
Glad you liked it!

**Comment by nbaua** [comment]
I assume you use Native c (or per say Java) for your development which in-turn would be great for reading JSON (even there are many libraries which help)- Though I am not a native c/J developer either I can help you out, if you share your thoughts.

I used this post as reference for changing the code here: (failed though being having limited native os knowledge)
http://www.androidbegin.com/tutorial/android-json-parse-images-and-texts-tutorial/

Do let me know, your thoughts.

Regards,
N. Baua

**Comment by adi928** [comment]
Reading from JSON is not a problem, having the image resource path from JSON to bringing it natively is a challenging thing. I'll take my own sweet time looking into it.

**Comment by nbaua** [comment]
Sure,
Do it at your leisure,

Just consider embedding BASE64 string in JSON instead of resource path, may be I am over-emphasizing it, however I think its the right way.

Sweet time till then.

Regards,
N. Baua

**Comment by Mihir7** [comment]
Hi @adi928 

Can you share the code for showing image in notification. I don't mind loading hard coded image. It works for me..

Thanks..

**Comment by adi928** [comment]
@Mihir7 Sorry man. Changed machine and lost the code and all.

**Comment by Mihir7** [comment]
@adi928  ok. Thanks for replying..

**Comment by shivanipatel-8710** [comment]
Hii...@adi928 ,
I'm trying to display an image in notification using $cordovaLocalNotification..my coding is below...I tried with that but result is zero...plz help me for that

$cordovaLocalNotification.schedule({
                id: $scope.data.notificationid,
                title: $scope.data.title,
                text: $scope.data.message,
                icon: 'res://icon',
                smallIcon: 'res://icon',
                image: $scope.data.image
                
            }).then(function (result) {
                console.log('Notification 1 triggered');
            });

**Comment by katzer** [comment]
Thats supported now!
