### ISSUE TITLE
ionic local notification

### ISSUE THREAD

**Issue by lakshmiprasanna44** [katzer/cordova-plugin-local-notifications#1237]
I have start and end dates, i want use repeat action with in start and end dates.Is it possible in ionic local notification

**Comment by adi928** [comment]
You must have the frequency the notification should come. Then run a loop from start date to end date and keep calling the schedule function in the local notification plugin from within the loop.

**Comment by lakshmiprasanna44** [comment]
I don't want looping for repeat why because if i my start date is 15-03-2017 and my end date is 15-03-2027,and i scheduled daily notification than looping to these dates are increases loading on application.
Is there any alternate way for this.

**Comment by adi928** [comment]
I don't think looping is implemented in this plugin. And even if it was implemented, then it will be using the same looping logic, and registering the notifications.

**Comment by lakshmiprasanna44** [comment]
okay, thanks for your response

**Comment by lakshmiprasanna44** [comment]
can i use "every" and at options for  ionic local notification, is it work in ios

**Comment by adi928** [comment]
It seems there is a way but without a end date time. I believe this can be used (from the wiki of this plugin):
```

cordova.plugins.notification.local.schedule({
    id: 1,
    title: "Production Jour fixe",
    text: "Duration 1h",
    firstAt: monday_9_am,
    every: "week",
    sound: "file://sounds/reminder.mp3",
    icon: "http://icons.com/?cal_id=1",
    data: { meetingId:"123#fg8" }
});
```

**Comment by lakshmiprasanna44** [comment]
is this sound option working in both android and iphone, its not working for me, i have on and off options in my app, how can i do this

**Comment by adi928** [comment]
I guess you are better off logging a different issue for this.

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by adi928** [comment]
Not an issue. More like an enhancement. Your call.
