### ISSUE TITLE
Estimated timeline for official iOS 10 release?

### ISSUE THREAD

**Issue by RyanTully** [katzer/cordova-plugin-local-notifications#1238]
Hello Sebastián,

Thank you for writing this plugin, it's of great use!

I just have a query regarding the release of the official iOS 10 version so haven't used the template for tech requests.

Can you estimate when the official iOS 10 release will be ready? Is it likely it could be the end of March/early April or much later than this?

Thank you

Ryan

**Comment by keithdmoore** [comment]
Until an official iOS 10 release, I am using the patch as defined here:  https://github.com/katzer/cordova-plugin-local-notifications/pull/1107

**Comment by rwillett** [comment]
I can say that the IOS10 branch is being worked on, but there is no release date available at the moment.

Rob

**Comment by katzer** [comment]
@RyanTully 

> Is it likely to be the end of March/early April or much later than this?

(Much) later! There will be a release based on the ios10 branch and then I am looking for to work on a new major version targeting only the newest platform versions. However that will take time as it needs to be done for all platforms.

Sebastián
