### ISSUE TITLE
Feature request: id as a string instead of only integers

### ISSUE THREAD

**Issue by eikooc** [katzer/cordova-plugin-local-notifications#1239]
# Your Environment

Not relevant

# Plugin config

Not relevant

# Expected Behavior

Allow id's of the notification to be a string? A typical scenario would be a _room id_ in a chat application with a unique hashkey that I would like the notifications _id_ to be equal to

# Actual Behavior

errors with `Id is not a number:`

# Steps to Reproduce

Set the id of a notification to some string e.g. "awkopa2002"

# Context

Trying to set the notification id to be a string

# Debug logs

Not relevant

# Include iOS / Android logs

Not relevant

**Comment by eikooc** [comment]
I don't think it is trivial to make a mapping from strings to a list of integers. If I have an arbitrary and dynamic list of "chat rooms" that I want to be subscribed to or whatever. It would reduce a lot of complexity if it could just be a string

**Comment by rwillett** [comment]
How difficult is:

array_name[<chatroomNameAsString>] = UniqueInteger.

Adding and deleting chatrooms is slightly more complex but not enormously difficult.

**Comment by eikooc** [comment]
To generate that _UniqueInteger_ that would require another function like a hash function.

I don't see why it is something that is of interest. Is it difficult to implement or what is the problem? :-)

**Comment by rwillett** [comment]
The point is that the plugin is being wholly rewritten for IOS10. That is a considerable undertaking. 

Adding in functionality that isn't really necessary and that is trivial to implement in a simple JavaScript wrapper, is not a good use of peoples time. 

We manage dozens of notifications being set, changed, queried, reset, rescheduled every day all through a simple service which keeps everything unique and allows us to refer to notifications by name. I wrote it, so I know that its not difficult to do. We put it together in a morning from memory. In the grand scheme of 'hard things' to do, keeping track of notifications by a unique user defined name, isn't difficult.

**Comment by katzer** [comment]
@eikooc The reason is simply that Android expects integers.

**Comment by eikooc** [comment]
@rwillett that is a valid point that you are coming with regarding that it is being rewritten and it is a considerable undertaking, but I don't understand why you keep saying it is trivial. Just creating a hash function is a non-trivial task

@katzer Okay I understand. Makes sense that it is done in this way then.

**Comment by rwillett** [comment]
Why are you creating a hash function? There are masses of libraries that do this for nothing which are cryptographically correct. Most people (myself included) do not have the skills to write hashes that work properly.

But why do you need a hash function anyway? You have a unique name, a chat room, so why do you have to make it difficult by making a cryptographic hash (or non cryptographic hash).

You only have 64 local notifications to use anyway on IOS, writing a hash function for 64 local notifications is a little overkill.

We use a simple integer increment for all local notifications. We have a service that all the local notifications call that gets the next available unique integer. We query the local notifications when we start up, make sure that if we have any local notifications, the unique integer is greater than the greatest number from the query. This guarantees uniqueness, we then use a simple JavaScript associative array to link names to unique integers. 

Thats simple, it's easy, it works, there is no cryptographic hash needed. 

Why are you making it difficult for yourself?
