### ISSUE TITLE
notifications every 2 weeks

### ISSUE THREAD

**Issue by zazics** [katzer/cordova-plugin-local-notifications#1240]
Hello,
is it possible to schedule a notification every 2 (or more) weeks  (instead of every week) ?

**Comment by adi928** [comment]
There doesn't seem to be a way to have every two weeks as interval. 

` private void parseInterval() {
        String every = options.optString("every").toLowerCase();

        if (every.isEmpty()) {
            interval = 0;
        } else
        if (every.equals("second")) {
            interval = 1000;
        } else
        if (every.equals("minute")) {
            interval = AlarmManager.INTERVAL_FIFTEEN_MINUTES / 15;
        } else
        if (every.equals("hour")) {
            interval = AlarmManager.INTERVAL_HOUR;
        } else
        if (every.equals("day")) {
            interval = AlarmManager.INTERVAL_DAY;
        } else
        if (every.equals("week")) {
            interval = AlarmManager.INTERVAL_DAY * 7;
        } else
        if (every.equals("month")) {
            interval = AlarmManager.INTERVAL_DAY * 31;
        } else
        if (every.equals("quarter")) {
            interval = AlarmManager.INTERVAL_HOUR * 2190;
        } else
        if (every.equals("year")) {
            interval = AlarmManager.INTERVAL_DAY * 365;
        } else {
            try {
                interval = Integer.parseInt(every) * 60000;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
}`

The code is hard coded for generic intervals. However if you give the number of minutes in the value of "every" it will take that. So I'm guessing, for 2 weeks it should be 20160 minutes. Hope this helps!

**Comment by zazics** [comment]
Yes, stupid am I.  Even "every 14 days" should be a solution. Thanks for your advice.
