### ISSUE TITLE
Preventing a Triggered notification from showing

### ISSUE THREAD

**Issue by gotters** [katzer/cordova-plugin-local-notifications#1242]
Not sure if this is already supported.

I have setup task reminders via local notification. The user requests when they want these reminders. However I dont want the reminder to show up if the user has already completed the task (by checking it off in the task list).

I could cancel the upcoming notification when they check off the task, but the problem is its a daily notification and will need it for the next day.

What I thought was that I could use the trigger event listener and when the notification was triggered I could check if the task was completed (using my own logic in the callback) and if so I could call some function that would prevent the notification from displaying.
Is there any way to do this?

**Comment by gotters** [comment]
I realized the above works....I can just call the clear method from within the trigger event.

It causes a flicker on the notifications as it appears and then disappears right away, but probably good enough.

**Comment by Mathe13** [comment]
can you show how you did that? i passing for the same problem
