### ISSUE TITLE
Dear Sir,  I need to send local notifications to the user on each day at 9 am, can you please provide the which parameters to set.  Thank you in advance.

### ISSUE THREAD

**Issue by akashchavan4691** [katzer/cordova-plugin-local-notifications#1245]
Dear Sir,

I need to send local notifications to the user on each day at 9 am, can you please provide the which parameters to set.

Thank you in advance.

**Comment by rwillett** [comment]
Fill out the template in #1188 

Tell us what you have tried and what you need to do.

Try reading the docs.

**Comment by stevesum** [comment]
Here is the documentation:
https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling

otherwise that easy:

cordova.plugins.notification.local.schedule({
    text: "Delayed Notification",
    firstAt: monday,
    every: "day",
    icon: "file://img/logo.png"
}, callback);


of course the 'firstAt' is a Date()

2017-03-19 18:11 GMT+01:00 akashchavan4691 <notifications@github.com>:

**Comment by akashchavan4691** [comment]
Thnak you  stevesum. 

But how to trigger at 9 AM? 
Where to mention time ? 

cordova.plugins.notification.local.schedule({
    text: "Delayed Notification",
    firstAt: monday,
    every: "day",
    icon: "file://img/logo.png"
}, callback);

**Comment by stevesum** [comment]
This is base javascript. I sugges to learning some from the w3schools.com
about javascript first. But here is the full example:

cordova.plugins.notification.local.schedule({
   text: "Delayed Notification",
   firstAt: new Date(''2017-03-23T09:00:00Z),
   every: "day"
});

the firstAt have to contains a javascript Date object. Of course may you
have to handle time zones, or Daylight Saving, if you won't use your
browser default.
Please see these pages:
https://www.w3schools.com/jsref/jsref_obj_date.asp
https://www.w3schools.com/js/js_date_formats.asp

2017-03-21 19:06 GMT+01:00 akashchavan4691 <notifications@github.com>:

**Comment by skotturi** [comment]
I believe "every" has stopped working on iOS 10. It still works on Android.

**Comment by rwillett** [comment]
Closed
