### ISSUE TITLE
multiline notification

### ISSUE THREAD

**Issue by Damzou** [katzer/cordova-plugin-local-notifications#1249]
Hello,

I want to do notification with multiline text but i don't find this in your guide.
Can you help me please ?

THX.

**Comment by rwillett** [comment]
Fill out the template in #1188 so we can see what you have tried and what you are trying to do.

Its helpful to provide more information such as Android or IOS as notifications work differently.

**Comment by Damzou** [comment]
Sorry for missing template.

Plugin version: de.appplant.cordova.plugin.local-notification 0.8.5-dev "LocalNotification"
Platform: ionic 2 (ios and android)
OS version: 
Device manufacturer / model: 
Cordova version (cordova -v): 6.5.0
Cordova platform version (cordova platform ls): 
  Installed platforms:
    android 6.0.0
    ios 4.3.0

Here my method to build notification :

> static schedule_notification(id: number, date: Date, title: string, text: string, action: string = null): void {
--LocalNotifications.hasPermission().then(function(permission){
----if(permission) {
------LocalNotifications.schedule({
--------id: id,
--------title: title,
--------text: text,
--------at: date,
--------smallIcon: "res://icon",
--------icon: "res://icon",
--------badge: 1,
--------data: action
------});
----}
--});        
});
>

I want to do notification with multiline text but i don't find this in your guide.
Can you help me please ?

**Comment by rwillett** [comment]
On IOS you automatically get multi line notifications.

Here's one from this morning.

![screenshot 2017 03 23 09 54 41](https://cloud.githubusercontent.com/assets/668923/24242135/bebd3f34-0fae-11e7-83ec-d154934b8f9a.png)

Here's exactly the same notification on Android. You only get one line with this plugin. A PR #819 was made but never merged.
![screenshot_20170323-095649](https://cloud.githubusercontent.com/assets/668923/24242361/71a69f78-0faf-11e7-851a-0b8c13a28552.png)

At this moment single line Android notifications is all you can do (AFAIK).

Rob

**Comment by eros2187** [comment]
prejudice centra little with this topic I be able to help?

regardless of there a few blogs where to ask for help?

I created a plugin with cordova to install it because it is not uploaded to git
how can I do from the console?

and you can install the plugin directly from my machine that I need to use commands in the usual console to install the plugin which is on use git:

cordova plugin + url EXAMPLE:

cordova plugin add https://github.com/apache/cordova-plugin-device.git

Seeing that I um I plugin how can I do? thank you

**Comment by rwillett** [comment]
Don't hijack other threads.

Open a new issue. Read the docs. They are pretty clear.

**Comment by Damzou** [comment]
Thx rwillett i resolve my problem with you.

Have a nice day.

**Comment by dvdpzzt** [comment]
Hi guys,
i just got the same problem and I solved it by myself by adding this couple of lines of code

`builder.setStyle(new NotificationCompat.BigTextStyle()
                    .bigText(options.getText()));`

at line #148 in file src/android/notification/Builder.java, just after the 

`if(smallIcon == 0) {
...
}
else {
...
}`

Bye

**Comment by Riyaz0001** [comment]
thanks @dvdpzzt
