### ISSUE TITLE
"Error: exec proxy not found for :: SpeechRecognition :: isRecognitionAvailable"

### ISSUE THREAD

**Issue by gingsero** [katzer/cordova-plugin-local-notifications#1250]
Your Environment

Plugin version: <plugin name="cordova-plugin-speechrecognition" spec="~1.1.2" >

Platform: browser(chrome), android

OS version: 
{
    "browser": "4.1.0",
    "android": "6.0.0"
}

Device manufacturer / model:
Samsung galaxy S5/ Samsung galaxy note 4 

Cordova version (cordova -v): 6.4.6

Cordova platform version (cordova platform ls):
Installed platforms:
  android 6.0.0
  browser 4.1.0
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  firefoxos ~3.6.3
  webos ~3.7.0
  windows ~4.4.0
  wp8 ~3.8.2 (deprecated)

Plugin config:
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.systran.eztalky" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0">
    <name>test</name>
    <description>
        A blank PhoneGap app.
    </description>
    <author email="test" href="test">
        test
    </author>
    <content src="index.html" />
    <access origin="*" />
    <preference name="phonegap-version" value="cli-6.0.0" />
    <preference name="orientation" value="landscape" />
    <preference name="fullscreen" value="true" />
    <preference name="target-device" value="universal" />
    <preference name="prerendered-icon" value="true" />
    <preference name="detect-data-types" value="true" />
    <preference name="exit-on-suspend" value="true" />
    <preference name="deployment-target" value="7.0" />
    <preference name="android-build-tool" value="ant|gradle" />
    <preference name="android-minSdkVersion" value="10" />
    <preference name="android-maxSdkVersion" value="15" />
    <preference name="android-targetSdkVersion" value="12" />
    <preference name="android-installLocation" value="auto" />
    <preference name="android-windowSoftInputMode" value="stateVisible|adjustResize" />
    <plugin name="org.apache.cordova.device" />
    <plugin name="org.apache.cordova.camera" />
    <plugin name="org.apache.cordova.media-capture" />
    <plugin name="org.apache.cordova.file" />
    <plugin name="org.apache.cordova.file-transfer" />
    <plugin name="org.apache.cordova.splashscreen" />
    <plugin name="org.apache.cordova.contacts" />
    <plugin name="org.apache.cordova.geolocation" />
    <plugin name="org.apache.cordova.inappbrowser" />
    <plugin name="org.apache.cordova.dialogs" />
    <plugin name="org.apache.cordova.vibration" />
    <plugin name="org.apache.cordova.network-information" />
    <plugin name="com.phonegap.plugins.pushplugin" />
    <plugin name="com.phonegap.plugin.statusbar" version="1.1.0" />
    <plugin name="cordova-plugin-speechrecognition" spec="~1.1.2" />
      
</widget>

Expected Behavior:
https://github.com/poiuytrez/SpeechRecognizer
I'm following this project. But it is not working...
When I just call speechRecognization method, I want to operate callback method(success callback).
But, executed error callback method ...

Tell us what should happen:
executed error callback method ...

Actual Behavior
not working

Tell us what happens instead

Steps to Reproduce

Reproduce this issue; include code to reproduce, if relevant

...
...
...
...
Context

What were you trying to do?
reinstall plugin
modify config.xml , plugin.xml, cordova_plugin.xml..
modify speechRecognization.js file
modify android manifest file. etc...

Debug logs

Include iOS / Android logs

ios XCode logs
Android: $ adb logcat

**Comment by rwillett** [comment]
What has this got to do with local notifications?

You aren't even loading thus plugin.

**Comment by gingsero** [comment]
https://github.com/poiuytrez/SpeechRecognizer
Link is project I'm developing... 
No, it has noting to do with local notifications.
loading? what is loading?? Are you meaning "build"?

**Comment by rwillett** [comment]
If it has nothing to do with local notifications why are you posting this issue here? This is the issues section for local notifications. It has nothing to do with https://github.com/poiuytrez/SpeechRecognizer

Rob

**Comment by gingsero** [comment]
Actually I saw a similar error "Error: exec proxy not found for~~". So, I think that you did solve this error.. 
If possible, you can help me..?

**Comment by rwillett** [comment]
This is nothing to do with local notifications. You need to get help from the people at

https://github.com/poiuytrez/SpeechRecognizer

**Comment by rwillett** [comment]
Closed as nothing to do with local notifications.
