### ISSUE TITLE
add to my plugin cordova ? 

### ISSUE THREAD

**Issue by eros2187** [katzer/cordova-plugin-local-notifications#1251]
I created a plugin with cordova to install it because it is not uploaded to git
how can I do from the console?

and you can install the plugin directly from my machine that I need to use commands in the usual console to install the plugin which is on use git:

cordova plugin + url EXAMPLE:

cordova plugin add https://github.com/apache/cordova-plugin-device.git

Seeing that I um I plugin how can I do? thank you

**Comment by rwillett** [comment]
What is this to do with local notifications?

Fill out the template in #1188 so we have some idea what you are trying to do.

**Comment by eros2187** [comment]
I created my own plugin local notification is wanted to know how you can aggingerlo my driven project cordova potetere help me thank you !!

**Comment by rwillett** [comment]
Sorry, you need to explain more.

If this is a request for help in designing a Cordova plugin, there are proper groups to help with this. This is not the place.

Rob

**Comment by rwillett** [comment]
Closed as no update from original poster.
