### ISSUE TITLE
Seek help！ Custom sound is interrupted!

### ISSUE THREAD

**Issue by longyuehua** [katzer/cordova-plugin-local-notifications#1253]
Set the custom sound, after the pop-up notification, when the notification message back online, the sound of the broadcast stopped. How should I solve this problem? Thank you

**Comment by rwillett** [comment]
Fill out the template in #1188 as that provides important information.

**Comment by longyuehua** [comment]
I'm sorry！ The first question does not understand 
Plugin version:0.8.4
Platform:ios
OS version:10.2.1 (14D27)
Device manufacturer / model:iPhone 6s
Expected Behavior:
Want to receive a notification when playing a custom sound for 8 seconds, if you open the notice to stop playing. 
Actual Behavior:
In fact, when you do not open the notification, the notification bar automatically disappears, it automatically stops playing

**Comment by rwillett** [comment]
1. You are using an old version of the plugin for IOS 10. 

2. Its still not clear what you are trying to do.

**Comment by rwillett** [comment]
Closed as no update from original poster.
