### ISSUE TITLE
A heads up - Xcode 8.2.1 (8C1002) doesn't recognise IOS 10.3

### ISSUE THREAD

**Issue by rwillett** [katzer/cordova-plugin-local-notifications#1255]
A quick heads up to warn people that the latest version of XCode 8.2.1 (8C1002) doesn't support IOS 10.3 out of the box. It gives a warning that it cannot find the correct device files and therefore you can't download your latest and greatest code to your iPhone.

This has happened before and is normally solved by putting symbolic links in the right place in the Xcode directory system. Whilst many people are happy with doing this, some people aren't. If not I would suggest you hold off upgrading your iDevice until Xcode is upgraded/patched or you happy to do the links.

Whilst this is not an issue with this plugin, we thought it worth mentioning as it might save somebody some time. We're off to work out which directories to link :)

Rob

**Comment by Tawpie** [comment]
Xcode 8.3 (8E162) does work (for me!), you might be able to save time by upgrading Xcode as well.

**Comment by rwillett** [comment]
Its not coming down as an explicit upgrade for us. We've been checking all day for it. 

We've just checked again and no upgrade listed, but if we go to the Xcode application, it then says we can upgrade. Very annoying.

**Comment by Tawpie** [comment]
You can get 8.3 directly from https://developer.apple.com/download/more/

**Comment by rwillett** [comment]
We're downloading now, but previous upgrades were more easily available in the App store. We've had to go looking for this one.

**Comment by skotturi** [comment]
8.3 showed up in the App Store for me yesterday.  ¯\_(ツ)_/¯

**Comment by rwillett** [comment]
Its still not showing for us at all in the App Store so we're downloading directly.
