### ISSUE TITLE
Scheduled and Triggered event info request

### ISSUE THREAD

**Issue by garygriswold** [katzer/cordova-plugin-local-notifications#1256]
Currently, the "scheduled" event will fire whenever the schedule command is executed, even if the scheduling failed, such as if the notification has already been scheduled and triggered.  So, it appears that if one wants to be certain the event is scheduled, one would also need to search for it using getScheduled(id).  Is this correct?

Similarly, I have never seen the "triggered" event fire, and I am not clear on when it does fire.  I can't imagine that it is intended to fire when the App is in background.  So, does it fire when the next time that the App is in the foreground?  Or, is the triggered event lost?

This is not a bug report or a feature request, but just a sentence or two more about these events is needed in the documentation.

My current thinking is that I will not be able to depend upon either of these events, but will use the getScheduled() and getTriggered() functions instead.

**Comment by katzer** [comment]
Hello @garygriswold I believe that the doc has always space for improvements. However it takes a lot of time and I appreciate every PR to improve the documentation. Especially many things are clear to me but not for everyone else. The repo has a new README which is far from complete. I will also do by myself from time to time. Just at the moment I am busy enough to write the code.

**Comment by katzer** [comment]
> So, does it fire when the next time that the App is in the foreground? Or, is the triggered event lost?

Then its lost - the system wont call the handler because no process is running (in foreground)
