### ISSUE TITLE
Phonegap application not working

### ISSUE THREAD

**Issue by umkka** [katzer/cordova-plugin-local-notifications#1260]
Using this code to show notifications once per day in phonegap app. Testing on Android 6 and Android 5.1

cordova.plugins.notification.local.schedule({
    text: "Delayed Notification",
    firstAt: monday,
    every: "day",
    icon: "file://img/logo.png"
}, callback);

But it does not work. What am i doing wrong?

**Comment by rwillett** [comment]
Use the template in #1188. Not enough information.

**Comment by rwillett** [comment]
Closed as no updated from original poster.
