### ISSUE TITLE
local notification 

### ISSUE THREAD

**Issue by lakshmiprasanna44** [katzer/cordova-plugin-local-notifications#1262]
i get notifications if internet connected or disconnected.I want notifications only if internet is connected, how can i get this scenario

**Comment by Tawpie** [comment]
Delivery of local notifications (this plugin schedules local notifications) are under control of the device operating system and at this time there isn’t a way for you to tell the operating system to stop delivery of local notifications when the internet is available. What you’re trying to do isn’t possible with this or any other plugin that I know of.

**Comment by guirip** [comment]
In real time you can use `navigator.onLine` ([mdn doc](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine)) to know if the browser has an internet connection, then decide to show or not the notification.
Of course this is not compatible with delayed notifications.

**Comment by rwillett** [comment]
Closed as question answered.
