### ISSUE TITLE
Why not error handling

### ISSUE THREAD

**Issue by garygriswold** [katzer/cordova-plugin-local-notifications#1263]
On occasion I see notifications fail to schedule, but no error is produced to help me know that it happened or why.  The only way I see this is to query scheduledIds.  Right now, I am not seeing scheduled notifications fire, although I have in the past, but again there is no error information of any kind to help identify the cause of the problem.

I realize that I am dealing with problems in my own code, but error handling in the plugin would have helped a lot.  Right now I am wondering if it would be easier to write my own plugin with error handling.  All anyone really needs is 1) schedule a notification, 2) update a notification, 3) clear a notification, 4) see a list of all notifications, 5) fire an event when a notification is clicked.  All of the other functionality in this plugin is just syntactic sugar.

**Comment by rwillett** [comment]
Never seem that happen on Android or IOS. Be happy to see code that reproduces that problem. 

I think you grossly underestimate the amount of work needed to make this work. My suggestion would be to fork this notification so you have a working basis and see how it goes. 

Please keep this group updated with your progress. If you have a similar calling interface that would as helpful as we can shim between the systems. 

Let us know it goes. I'm very interested in your progres.

**Comment by garygriswold** [comment]
Rob,

The attached is the beginnings of the ios side of a LocalNotification plugin.  It has been only unit tested, and needs some work with background threads, but it will give you an idea of what I had in mind.  There is error handling around the schedule method and the request method.  Unfortunately, I must put this down for at least a couple weeks in order to make progress on something else.

Gary

**Comment by garygriswold** [comment]
The attached is the ios side of a LocalNotification plugin with some error handling.  It has been only unit tested, and needs some work with background threads, but it will give you an idea of what I had in mind.  There is error handling around the schedule method and the request method.  Unfortunately, I must put this down for at least a couple weeks in order to make progress on something else.

[LocalNotification.zip](https://github.com/katzer/cordova-plugin-local-notifications/files/907243/LocalNotification.zip)
