### ISSUE TITLE
lastAt feature?

### ISSUE THREAD

**Issue by jester6san** [katzer/cordova-plugin-local-notifications#1264]
For scheduled notification, it would be useful to have something like notification every 1 hour and 30 min from 7:00 AM to 10:00 PM

**Comment by rwillett** [comment]
It's not difficult to program.

Also everybody wants something thats a specific repeating schedule that suits them. There would dozens of versions, whereas you can program this very simply and have it do exactly what you want.

**Comment by katzer** [comment]
Please see the trigger section on the readme. Thats possible for android and windows.

```js
schedule({
  trigger: { every: 1.5 unit: 'hour', count: 3 }
});
```
