### ISSUE TITLE
Custom icon for notification.

### ISSUE THREAD

**Issue by salunkhenilesh** [katzer/cordova-plugin-local-notifications#1266]
use all solution to change notification icon, but its not change. below is code.

 document.addEventListener('deviceready',function(){
         var notify = new Date();
    notify.setHours(11,29,00,00);

    cordova.plugins.notification.local.schedule({
        id:      1,
        icon : "file://img/logoicon.png",
        smallIcon : "file://img/logoicon.png",
        title:   'Driving School',
        message: 'Your training batch timing is 6am to 7am, please reach 15 mins before. ',
        repeat:  'daily',
        date:    notify,
        autoCancel: true, 
        ongoing: true, 
        
    });
    window.plugins.toast.showShortBottom("alarm set");
});

**Comment by rwillett** [comment]
Fill out #1188.

Its not clear what your problem is.

**Comment by salunkhenilesh** [comment]
in notification icon get bell_icon. need change that with my app icon

**Comment by rwillett** [comment]
Did you bother even searching the local notification issues for this?

#1075 
#890 
#1222 
#1051 
#1209 
#810 
#966 
#488 

all cover this topic.

**Comment by salunkhenilesh** [comment]
Notification icon is set now. New issues is in android 5.0 and above its show white circle not see icon.

**Comment by Tawpie** [comment]
You absolutely *must* make the icons according to the documentation for the OS you are using, if your icons are the wrong sizes (and that is plural because you need an icon for each screen density!) your icons will not be used and the bell will be substituted. This is something enforced by the OS, not by the plugin.

**Comment by salunkhenilesh** [comment]
@Tawpie fix notification icon issues. now new issues is white icon show on android 6.0 and other one is big text display in notification. As per above show first image on android 6.0, that not show the icon.

**Comment by rwillett** [comment]
You still have the wrong colour combination. From memory, you need to have a white icon as thats how it works. I *think* you can then add in colour but get it working with a white material background.

You need to read about Android icons as @tawpie has already suggested.

**Comment by rwillett** [comment]
Closed as not updated in five days from original poster.
