### ISSUE TITLE
Cancelling notifications by 2 apps

### ISSUE THREAD

**Issue by daQuark** [katzer/cordova-plugin-local-notifications#1267]
Hi,

First of all thanks for this cool feature, I am going to use it in an app for users to be able to set medication intake alarms. I could use multilines in the device notifications message though (I will keep watching this repository for added features, unfortunately I am not able to contribute yet).

I was wondering, what if there are multiple apps on the same device running that use LocalNotifications; will the cancelAll() and/or clearAll() completely wipe the device clean, or are the cancelled/cleared notifications only restricted to the ones that were created by the specific app?

Kind Regards,
Mark

**Comment by rwillett** [comment]
Local notifications only apply to the app they were created for. So if you have two apps using local notifications, they are independent of each other.

Think about it, it has to work this way otherwise I could hijack other peoples notifications.
