### ISSUE TITLE
Notification without sound still vibrates when volume is muted on Android

### ISSUE THREAD

**Issue by kamleshpra995** [katzer/cordova-plugin-local-notifications#1268]
cordova.plugins.notification.local.registerPermission(function (str) {
					cordova.plugins.notification.local.schedule({
						id: 1,
						sound: null,
						title: message
					});
				});

This still vibrates when muted.

This is happening on Android 4.4

**Comment by rwillett** [comment]
Fill out #1888 with more information.

**Comment by rwillett** [comment]
Closed as no update from original poster.
