### ISSUE TITLE
When lock screen, local push notification not work

### ISSUE THREAD

**Issue by gkaradagan** [katzer/cordova-plugin-local-notifications#127]
i need to push notification when user lock screen, how can i do that ?

**Comment by iRajul** [comment]
@mpedersen15 Did you find any solution?

**Comment by mpedersen15** [comment]
@iRajul, I haven't been working on the project that required this plugin for a while, so I have not found a solution. Best of luck!

**Comment by salilsethi** [comment]
+1 I have the same issue and wondering if there is a work around or any way to alert the user, with local notifications, when the phone is locked.

**Comment by gkaradagan** [comment]
you have to implement wakefullintentservice

**Comment by salilsethi** [comment]
Thanks for the reply. I should have mentioned I am having trouble with iOS. Actually at this moment, local notifications are not shown if the app is in the background. I am "monitoring" beacons and if the phone enters a monitored region the notification should be shown to the user. However, in background no message is shown. Any help would be greatly appreciated.
