### ISSUE TITLE
Notifications are not created while app is running in background. 

### ISSUE THREAD

**Issue by inferno1005** [katzer/cordova-plugin-local-notifications#1273]
## Your Environment

Plugin version: **0.8.5-dev**
Platform: **iOS**
OS version: **10.3**
Device manufacturer / model: **iPhone SE Simulator**
Cordova version (cordova -v): **6.5.0**
Cordova platform version (cordova platform ls): **ios 4.3.1**
Plugin config : **default**

## Expected Behavior
The app should create a notification while running in the background by calling
 ```
window.cordova.plugins.notification.local.schedule({
   text:"test"
})
``` 
from javascript.  

## Actual Behavior
The native ```schedule``` function is not run while in the background, instead it gets called as soon as the app is launched manually.  This results in the notification not showing up until the app is launched. 

## Steps to Reproduce
Have the app running in the background. 
I am doing this by a geofence that triggers my javascript. 
Create a notification with : 
```
window.cordova.plugins.notification.local.schedule({
   text:"test"
})
```
There will be no notification. 
Launch the app manually. 
The  native ```schedule``` function is called and now the notification is created.

**Comment by rwillett** [comment]
You haven't set a time to execute the notification. You need to set the time, preferably a few seconds in the future and it'll appear. 

Also you need to put your JSON in an array, even if there is only one element.

**Comment by inferno1005** [comment]
Alright, made those modifications to the js code. 
```
window.cordova.plugins.notification.local.schedule([{
   text:"test",
   at: new Date(new Date().getTime() + 5*1000)
}])
```
Same exact behavior as before. The notification is still not showing up until I manually launch the app.

**Comment by rwillett** [comment]
You are doing something wrong elsewhere. Theres not enough information here, but this is simple stuff and works. 

Here is verbatim code pulled out of a production app. We use this for generating a dummy notification to test that this exact situation works. You can read it as pseudo code but this has been working for months. In fact I just tested it on a iPhone 6 running IOS 10.3.1 and it works fine.

```
  function SendDummyNotification() {
        var debugSendDummyNotification = debugFalse;
        var whatAmI = WhatAmI("SetupCongestionNotificationReminders");
	var d          = new Date();
        var now        = d.getTime();
        var year       = d.getFullYear();
	var month      = d.getMonth();
	var day        = d.getDate();
	var reminder0  = new Date(now + 10 * 1000);

        var notifications = [ { id: GetNotificationIdAndIncrement() ,
                                sound: "" , // Turn the sound off
				at: reminder0 ,
                                data: { type: "CongestionChargeNotification" , original_schedule_time: reminder0.getTime()/1000 ,
                                        reminder_type: "reminder0_congestion_charge" , order: 1} ,
                                text: "[A102] Blackwall Tunnel Southern Approach (N/B) - The carriageway is blocked northbound. Collision between two\
 cars. Carriageway blocked. Police on scene are removing vehicles. Expect long delays."
                              }];

        if (whatAmI === "android_app" || whatAmI === "android_simulator")
        {
            for (var i = 0 ; i < notifications.length ; i++)
            {
             	notifications[i]["icon"] = "file://pw_notification.png";
            }
	}

        if (debugSendDummyNotification)
            ConsoleLog("SendDummyNotification: " + JSON.stringify(notifications));

	cordova.plugins.notification.local.schedule(notifications , function () {
            if (debugSendDummyNotification)
		ConsoleLog("SendDummyNotification: schedule callback OK");
	});

    }
```

**Comment by rwillett** [comment]
Note that we have a callback to check what is happening. You need to check EVERYTHING from plugin initiation onwards.

**Comment by inferno1005** [comment]
So I have figured out what was happening. I had initially written this app over a year ago and since then cordova and ios have gone through some major updates. The problem was not in the native or js code but in the html. 

It seems like they added some extra things to the 'Content-security-Policy' in the index.html.

Comparing my index vs a newly generated app showed that there was a new policy for ```gap:``` which was blocking some things from working because cordova would try to run ```gap://ready``` and it would fail. 

Adding this option to the content-security-policy has fixed the issue.  
Closing issue, thanks for the help rwillett!

**Comment by flagman5** [comment]
What is the option you added?

**Comment by inferno1005** [comment]
My content security policy now looks like this.

```
  <meta http-equiv="Content-Security-Policy"  content="default-src * gap: data: &apos;self&apos;;  style-src &apos;self&apos; &apos;unsafe-inline&apos;; script-src &apos;self&apos; &apos;unsafe-inline&apos; &apos;unsafe-eval&apos; * localhost *;	">
```

**Comment by rwillett** [comment]
That looks like an incredibly unsafe CSP. Difficult to say because of the formatting, but I *think* you have turned all security off.

**Comment by inferno1005** [comment]
No worries, this is for development purposes only. The real version has a good white list. But it is probably good to note that you should not use the one I posted in production.

**Comment by rwillett** [comment]
Ok, lets close this down. If there are any more questions, please raise a new issue.

**Comment by flagman5** [comment]
Thank you both. I am having the same issue so I thought to ask quickly if CSP options can help. I will raise a new ticket if I cannot solve it.
