### ISSUE TITLE
click event parameters are returning empty

### ISSUE THREAD

**Issue by lgDeve** [katzer/cordova-plugin-local-notifications#1274]
Plugin version: 0.8.4
Platform: Android
OS version: 6.0.1
Device manufacturer / model: Samsung note4
Cordova version (cordova -v): 6.2.0
Cordova platform version (cordova platform ls): 6.2.0
Plugin config

# Expected Behavior

when a user clicks on the notification the app would load and launch the click event for the notification. Part of the notification the app would save information into data parameter of the notification. Once the click event has been triggered the app would read the information into the data parameter and manage the information

# Actual Behavior

the scheduled notification is triggered and the click event will run, but when I try to read the parameters notification and state they return empty. could be because I'm testing on past dates and time?

```
cordova.plugins.notification.local.on("click", function (notification, state) {

        if (notification.data == null || notification.data == undefined) { }
        else if (notification.data.localeCompare('') == 0) {
        } else {


        }
    }, this);
```

# Steps to Reproduce

schedule a notification (with past date and time)
run the click event 
check if the parameters aren't empty

# Context

# Debug logs

no logs

**Comment by rwillett** [comment]
Use the template in #1188 as not enough information here.

**Comment by rwillett** [comment]
This works for us (or I think it does). 

```
	                // Use click for when the user selects a notification in the drawer. Use 'trigger' for the little popdown
			// in the notification drawer
                        cordova.plugins.notification.local.on("click", function (notification , state) {
                            if (debugProcessNotificationEvent)
                                ConsoleLog("ProcessNotificationEvent: Adding to execution queue");

                            AddToExecutionQueue("NotificationClick" , ExecuteNotificationEvent , { notification: notification ,
	                                                                                           state: state ,
                                                                                                   name: "NotificationClick"});
```

If you put JSON.stringify(notification) what do you get?

**Comment by rwillett** [comment]
Closed as no update from original poster.
