### ISSUE TITLE
local-notifications is not working  on android when the screen is locked even The background mode is used 

### ISSUE THREAD

**Issue by efnan34** [katzer/cordova-plugin-local-notifications#1275]
Everthing is almost fine except it s not working on locked black screen .When the screen is waken up it gives notification 

Thank you in Advance

**Comment by rwillett** [comment]
Not enough information. Fill out #1188.

**Comment by efnan34** [comment]
**My Environment**
*The lasted version of Plugin
*Platform Android
*OS :Windows 10
*Lenova A6020a41 Android version 5.1
*Cordova version 6.5
*Installed platforms: android 6.1.2
*Plugin config :
      
```
Schelude ()
{
let time2=new Date();
              time2.setHours(11);
              time2.setMinutes(5);
              time2.setSeconds(0);

           this.localNotifications.schedule({
            id:1,
            title: "test",
            text: "Tester?",
            at: time2,
            sound: "file://assets/sound/speed_camera.mp3",
            every: "hour",
        },
}
```
**Expected Behavior:**

Normaly it should pop out when it s scheduled.

**Actual Behavior:**

It doesnt not pop out when the screen is locked .

Any information you need please let me know thank you in Advance

**Comment by rwillett** [comment]
Not enough information. 

Putting latest version doesn't mean anything. 

You have no callback in your schedule function. 

You need to put the object in an array.

Pull out the sound.

Pull out ```every:```

Schedule the notification for about 60 secs from now.

Test to see if it actually works with the app in place.

test to see if it works with the app in the background

Test to see if it works with the App behind a locked screen.

**Comment by efnan34** [comment]
Ok
This is the version of Plugin:"@ionic-native/local-notifications": "^3.5.0",

This is an example from wiki of local notification Plugin

`cordova.plugins.notification.local.schedule({
    id: 1,
    text: "Single Notification",
    sound: isAndroid ? 'file://sound.mp3' : 'file://beep.caf',
    data: { secret:key }
});`

 There is no an array for a single schelude and no callback function.

I ll try what you suggest and give a feedback

Thanks for patient and attention

**Comment by rwillett** [comment]
Ah! 

Then you are using a modified version of this plugin from Ionic.  Thats why its important to fill the template in.

No idea what Ionic have done to this plugin. Suggest you raise this on their forum.

Or dump it and use this plugin.

**Comment by efnan34** [comment]
Thank you
