### ISSUE TITLE
Problems with iOS - works on simulator but not on physical phone

### ISSUE THREAD

**Issue by tvalentino** [katzer/cordova-plugin-local-notifications#1277]
Your Environment
•	Plugin version: 0.8.5
•	Platform: iOS
•	OS version: 10.3.1 (14E304)
•	Device manufacturer / model: Apple iPhone 5S
•	Cordova version (cordova -v): 3.6.8
•	Cordova platform version (cordova platform ls): ios
•	Plugin config

Expected Behavior
With the app in the background, I send data from a server indicating whether a device is inside or outside of a geofence.  I then issue a local notification alerting the user to the device state (inside or outside).  I never go back into the app.  The trigger is set for 30 seconds after receipt of data.

Actual Behavior
This works perfectly on the emulator (X-Code 8 with iOS 10 emulator).  But when I run it on the deivce, I do not get the notification.  I must put the app into the foreground and then return it to the background in order for the notification to show up 30 seconds later.

Steps to Reproduce
Reproduce this issue; include code to reproduce, if relevant
1.	On the physical device - Open the app and then place it into the background
2.	Send data from the server – inside or outside the geofence
3.	The app does trigger after 30 seconds for this initial notification (because I started the app in the foreground)
4.	With the app in the background, send a new data set from the server – inside or outside the geofence
5.	This time there is no notification.
6.	After several minutes (to make sure the data is being received by the app) I put the app into the foreground and then immediately put it into the background.  After 30 seconds the notification shows up.
In the simulator – everything works as expected.

Here is my scheduling code:

function schedule(){
    
    var message = window.localStorage["geoMessage"];
    var d          = new Date();
    var now        = d.getTime();
    var now_plus_30 = new Date(now  + 1000*30);
    var now_plus_15 = new Date(now + 1000*15);
    var now_plus_20 = new Date(now + 1000*20);
    
   
    cordova.plugins.notification.local.schedule({
                                                id: 1,
                                                title: "GeoFence Alert",
                                                text: message,
                                              //  sound: 'file://sounds/sms-received1.caf',
                                                at: now_plus_30
                                                
                                                });
    
}

Context
I am trying to send a local notification based on the value of some server data with the app in the background.

Debug logs
•	None, because this works on the simulator.

**Comment by rwillett** [comment]
This is expected and the right behaviour on the simulator, the 'real' app and the plugin. (sorry).

Your 'real' app gets suspended by IOS, the time taken to be suspended is not in your control. On IOS 10, the OS is very aggressive in suspending your app. Once your app is suspended then all the JavaScript stops as its in the background. You cannot receive notifications in the background and process them, well you can but not easily with JavaScript.

The simulator works differently, so things like JavaScript timeouts carry on working. This is why it works on the simulator and not on the 'real' app. We ran into this as well.

This is a pain but its NOT the plugin but the way apps work and the simulator works. 

As a matter of interest, how do you send a remote notification to the simulator. I didn't think Apple push notifications worked on the simulator and we'd love to be wrong. 

Rob

**Comment by tvalentino** [comment]
Well that's a bummer.  What is interesting is that if I do multiple changes -- say geo in then a few minutes later geo out, then a few minutes later geo in again.  The notifications seem to get stacked up.  i can go into the app 3 times and get the individual notifications.  That is what led me to believe they were at least being scheduled and maybe not triggered.   

We don't send a remote notification to the server from the app.  There is an external device that provides data to the server.  I manipulate the device to put it into different geofence states (which I can see on server logs).  The device then sends that data to the server which then sends it to the APP.

**Comment by tvalentino** [comment]
Sorry - i meant we don't send remote notification to the simulator.

**Comment by rwillett** [comment]
I suspect your package for doing the geofencing is written in Swift, C, Objective-C which can work in the background. Its possibly your geofencing package queuing up and when your app starts, it reads off the queue.

Ok, would love to send remote notifications to the heap of crap that is the IOS simulator. That and a proper GPS emulation system. It would also be nice if the simulator actually simulated things, like the app being suspended properly rather than just lying about it.

**Comment by tvalentino** [comment]
Actually the geofencing is not done in the app.  It just receives the results of the geofencing algorithm which is performed elsewhere outside the app.  The app just basically reads the status message sent by the server.  The app is cordova/phonegap type app so all done with html, javascript and cordova plugins.

Yes, it would be very helpful to even have a pulldown where you could suspend the app in the simulator.  Would solve a great many headaches.

**Comment by rwillett** [comment]
I assumed you had a package that was doing this as a plugin, 

e.g. https://github.com/transistorsoft/cordova-background-geolocation

There are some things you can do in the background but I'm pretty certain you can't schedule local notifications. 

We get round this by using an external push notification server as the main data source and using local notifications when the app is in the foreground, if the app is in the background then the remote push notification is displayed. Since we format them identically it looks great. Your use case may be wholly different.

**Comment by tvalentino** [comment]
We presently use SMS for the remote notification.  Works pretty good, but it can get costly.  The SMS that gets sent by the remote device gets charged (not in the user's phone plan but in the plan we provide - the carriers don't cut us much of a break) so that is why we looked at the Local Notification package.  We investigated doing something with Push notifications, but it looks like that requires some server side modification (which on this particular tracking server is not too easy to do).  I'll have to go back to investigating that I guess.

**Comment by rwillett** [comment]
We have tried a number of push notification providers:

- Amazon
- OpenShift
- Urban Airship
- OneSIgnal
- PushWoosh
- Home built
- and probably one or two others. 

We settled on PushWoosh, but OneSignal is free and very good.

**Comment by tvalentino** [comment]
Thanks.  I'll check out a couple of these.

**Comment by rwillett** [comment]
We got OneSignal working in a few hours. Their documentation is very good. The biggest hassle is the Apple certificates but thats the same for all of them.

We went with PushWoosh as we had a very complex edge condition that OneSignal couldn't handle but we liked them, their company and their support.

**Comment by rwillett** [comment]
Closed as plugin and IOS working correctly, though not the way the OP wants :)
