### ISSUE TITLE
If the time is longer than a few hours, the notification will not appear

### ISSUE THREAD

**Issue by anatoliyB** [katzer/cordova-plugin-local-notifications#1278]
**My Environment**

Plugin version: de.appplant.cordova.plugin.local-notification 0.8.5-dev
Platform: iOS/Android
OS version: iOS 10.3.1 and Android 6.0.1
Device manufacturer / model: iPhone 5s and Xiaomi Redmi 4 pro
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls): android 6.0.0, ios 4.3.1
Plugin config

**Expected Behavior**
    Notifications appear independent to the time elapsed since they were scheduled.
**Actual Behavior**
    If the time is longer than a few hours, the notification will not appear. If the time elapsed from scheduling of notification is less then few hours then notifications appear as they should.
    
**Steps to Reproduce**
I have this code below

prop.articleIndex.forEach(function (element, index, array) {
      if(element.dates && element.dates.length>0){
          art_ids.push(element._id);
          element.dates.forEach(function (el, ind, arr) {
            c_i=getCurrentID(notifications,element._id, new Date(el.getTime()+ (7 * 3600000)),cur_id)
            push_obj={};
            push_obj={
                id: c_i,
                text: $translate.instant('TODAY')+' '+element.title,
                at: new Date(el.getTime()+ (7 * 3600000)),
                data: { propertyId:prop._id, articleId:element._id }
            }
              cur_id.push(c_i);
            push_arr.push(push_obj);
          });
      }

    });
     cordova.plugins.notification.local.schedule(push_arr);

after scheduling if i use this code

cordova.plugins.notification.local.getAll(function (notifications) {
    console.log(notifications);
});

    I can see objects like that: 
     
{
    at:1493031600,
    autoClear:true,
    badge:0,
    data:{"propertyId":"KWmjw7ZJ4oLrqv3qF","articleId":"uYrNMtnFb3dcfebLq"},
    icon:"res://ic_popup_reminder",
    iconUri:"file:///storage/emulated/0/Android/data/com.yourstayapp.app/cache/localnotification/5addfcf0-62b4-4c8e-a775-92ab868224f2",
    id:1,
    ongoing:false,
    sound:"res://platform_default",
    soundUri:"content://settings/system/notification_sound",
    text:"Today Home",
    title:""
}

**Comment by rwillett** [comment]
We schedule for up to 36 hours in advance with no problems on IOS and Android. We explicitly test for it.

You have too much baggage in your code to test this properly. Dump all the code to create the array and create a simple array with one JSON object in with a date a few hours in the future. You only need the```at:``` field, the ```id:``` field and the ```text:``` field. 

Check that you can create the future notification and then add stuff back in, once you have it working.

**Comment by rwillett** [comment]
Closed as no update from original poster.

**Comment by anatoliyB** [comment]
i have used this code:
cordova.plugins.notification.local.schedule([{
    id: 3,
	at:new Date(new Date().getTime() + 2*60*60*1000),
    text: "Single Notification1",
    data: { propertyId:'tttttt', articleId:'ppppp' }
},{
    id: 4,
	at:new Date(new Date().getTime() + 4*60*60*1000),
    text: "Single Notification2",
    data: { propertyId:'tttttt', articleId:'ppppp' }
},{
    id: 5,
	at:new Date(new Date().getTime() + 6*60*60*1000),
    text: "Single Notification3",
    data: { propertyId:'tttttt', articleId:'ppppp' }
},{
    id: 6,
	at:new Date(new Date().getTime() + 15*60*60*1000),
    text: "Single Notification4",
    data: { propertyId:'tttttt', articleId:'ppppp' }
}]);

In result i received all notifications in IOS and only first 2 in android.
In android in logcat i can see this messages:

04-25 13:48:24.851  27436-27436/? D/CordovaActivity﹕ CordovaActivity.onDestroy()
04-25 13:48:24.851  27436-27436/? D/GeolocationPlugin﹕ onDestroy
04-25 13:48:24.851  27436-27436/? D/GeolocationPlugin﹕ Stopping geolocation
04-25 13:48:24.851  27436-27436/? D/GeolocationPlugin﹕ Attempting to shutdown cordova threadpool
04-25 13:48:24.851    1399-2300/? I/ActivityManager﹕ Killing 27436:my.app.com/u0a144 (adj 9): remove task
04-25 13:48:24.854    1399-2226/? I/ActivityManager﹕ Force stopping my.app.com appid=10144 user=0: from pid 2133

Obviously i don't  receive notifications after app is getting force closed...
Is this expected behaviour or normally the plugin should deliver notifications even if the app is closed?
Is there any workaround to fix this?

**Comment by rwillett** [comment]
Android notifications are delivered after force closing the app. It works on our Android Nexus 5 and 6 phones. 

Perhaps Xiaomi are modifying Android. Vendors do 'update' Android with their own fixes and screw things up. The fact you get two of the notifications and no more means its working some of the time.

How much time do you *think* you are adding to the date()? I reckon that you won't see any notification for at least three days at all. Just add in 10,000, 20,000 and 30,000 to check it works.

**Comment by anatoliyB** [comment]
I'm not sure i understood you right 10,000, 20,000 and 30,000 is very short period of time.
I just tried this code:
cordova.plugins.notification.local.schedule([{
    id: 3,
	at:new Date(new Date().getTime() + 10000),
    text: "Single Notification1",
    data: { propertyId:'tttttt', articleId:'ppppp' }
},{
    id: 4,
	at:new Date(new Date().getTime() + 20000),
    text: "Single Notification2",
    data: { propertyId:'tttttt', articleId:'ppppp' }
},{
    id: 5,
	at:new Date(new Date().getTime() + 30000),
    text: "Single Notification3",
    data: { propertyId:'tttttt', articleId:'ppppp' }
}]);

And received all 3 notifications, but i don't receive notifications if i add more then 6 hours (21600000) then notifications don't fire.

**Comment by rwillett** [comment]
The code you originally posted has very different times

```
i have used this code:
cordova.plugins.notification.local.schedule([{
id: 3,
at:new Date(new Date().getTime() + 260601000),
text: "Single Notification1",
data: { propertyId:'tttttt', articleId:'ppppp' }
},{
id: 4,
at:new Date(new Date().getTime() + 460601000),
text: "Single Notification2",
data: { propertyId:'tttttt', articleId:'ppppp' }
},{
id: 5,
at:new Date(new Date().getTime() + 660601000),
text: "Single Notification3",
data: { propertyId:'tttttt', articleId:'ppppp' }
},{
id: 6,
at:new Date(new Date().getTime() + 1560601000),
text: "Single Notification4",
data: { propertyId:'tttttt', articleId:'ppppp' }
}]);
```

The code you **now** post has short times.

We post code on Android more than six hours ahead and it works, but I'll have to check that again tomorrow.

**Comment by anatoliyB** [comment]
Hi, have you checked it are there any news?

**Comment by rwillett** [comment]
We checked and it works for us.

**Comment by rwillett** [comment]
Closed as no update from user.
