### ISSUE TITLE
Does cordova-plugin-local-notifications work with meteor ?YES

### ISSUE THREAD

**Issue by hanene2030** [katzer/cordova-plugin-local-notifications#1280]
Hi, 

Does cordova-plugin-local-notifications work with meteor ?

I tried to use it and didnt succed to unstall it ':)
I used meteor add instead of cordova add

Thanks a lot per advance for your help 🥇

**Comment by rwillett** [comment]
I'd keep trying it and seeing the results, you may well be the first. 

Are you doing this on a mobile or a desktop device? Suspect the desktop would not work at all.

**Comment by hanene2030** [comment]
Thanks for your help  👍 

In mobile 

I used it with cordova only and it does work , now i want to use it in meteor mobile app 

but i didnt succed to make it work

**Comment by rwillett** [comment]
Sorry, no idea. We don't use Meteor.

**Comment by hanene2030** [comment]
thanks for your help
:)  

Have Great day 🥇

**Comment by hanene2030** [comment]
Just in case someone is using meteor :)

This plugin work with meteor ;p 
clone the project localy and use meteor add cordova:<repository@version>  command to add it to your project

**Comment by rwillett** [comment]
Ok, good to know. I'll close this issue.

**Comment by MastaBaba** [comment]
I got the plugin up and running in my Meteor project, but I'm unable to generate any local notifications.

In startup:

```
if (Meteor.isCordova) {
    cordova.plugins.notification.local.hasPermission(function (granted) {
        if (!granted) {
            cordova.plugins.notification.local.registerPermission(function (granted) {
            });
        }
    }); 
}
```

This requests the user to grant permission. So, this works.

Then:

```
if (Meteor.isCordova) {
        cordova.plugins.notification.local.hasPermission(function (granted) {
            if (granted) {
                var date = new Date();                  

                cordova.plugins.notification.local.schedule({
                    id: 1,
                    title: "Message Title",
                    message: "Message Text",
                    at: date,
                    icon: "/icon.png"
                });

            }
        });
    }
```

This doesn't do anything. No error message, nothing.

How to get this to work?
