### ISSUE TITLE
ios-deploy was not found. 

### ISSUE THREAD

**Issue by Alkashi** [katzer/cordova-plugin-local-notifications#1282]
Hi,

Plugin version: #ios10
Platform: iOS
OS version: 10.3
Device manufacturer / model: iPhone SE
Cordova version (cordova -v): 6.5.0
Cordova platform version (cordova platform ls): ios 4.3.1

**Expected Behavior**
Schedule a push notification

**Actual Behavior**
When I install the #ios10 with [_cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#ios10_], I am not able to build with cordova and get this error when I launch a cordova build ios : 
_Error: ios-deploy was not found. Please download, build and install version 1.9.0 or greater from https://github.com/phonegap/ios-deploy into your path, or do 'npm install -g ios-deploy'_

When I remove the plugin and install the master version, the build works but no notification is scheduled.

Thanks for your help

EDIT : of course I tried to launch npm install -g ios-deploy but didn't work

**Comment by rwillett** [comment]
Try installing with 

cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#ios10

**Comment by Alkashi** [comment]
@rwillett it is what I did (Plugin version: #ios10)

**Comment by rwillett** [comment]
You said:

"When I install the #ios10 with npm, I am not able to build with cordova and get this error when I launch a cordova build ios "

That indicates you installed with npm. 

You need to provide a lot more information as I don't think this is anything to do with the plugin based on what you have said. The lack of ios-deploy is a Cordova issue not a local notification issue.

**Comment by Alkashi** [comment]
I have the  ios-deploy only after adding the #ios10 version with _cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#ios10_

When I add the master version with _cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications_ the build works correctly.

So I think the issue has a link with the #ios10 version of the plugin

(I made a misktake when I talked about npm I edit the first msg)

**Comment by rwillett** [comment]
We have the #ios10 branch and have no issues (and have never have had) with ios-deploy when doing cordova build ios. We sometimes do 100's of these builds a day. 

You have something else wrong, perhaps you've screwed something else up. Uninstall everything and start again, shouldn't take long.

**Comment by Alkashi** [comment]
Hi,

OK I finally managed to update ios-deploy with this command : npm install -g ios-deploy --unsafe-perm=true (see the [this issue](https://github.com/phonegap/ios-deploy/issues/283))
After that, I added the plugin with cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#ios10.

Everything works fine now.

The strange think is that the ios-deploy issue appeared only with the #ios10 branch.

**Comment by rwillett** [comment]
Please this is solved but still don't think this is an issue with this plugin.

**Comment by Alkashi** [comment]
It's your opinion. I clearly think it is an issue. If not how to explain that a downgrade of the plugin allow to build without error.

**Comment by rwillett** [comment]
Because we didn't have the issue through any of the previous versions of this plugin and versions of xcode going back for the last 18 months. I've lost count of the number of versions of cordova, the ios platform plugin, this plugin and xcode we gave used.
