### ISSUE TITLE
The local notification comes to late

### ISSUE THREAD

**Issue by linusanderas** [katzer/cordova-plugin-local-notifications#1284]
If you have more then one notification it sometimes comes up to five minutes to late.

I have just tried it on an Android so far. Anyone else with the same problem?

**Comment by rwillett** [comment]
Fill in #1188 as there's too little information.

**Comment by Tawpie** [comment]
@Linus — (you should take the time to create a ‘traditional’ bug report, it does help those that want to assist) But in spite of the lack of detail, know that Google does not promise that Android will deliver a local notification “on time”, it may be several minutes late. It’s an Android thing that the plugin does not attempt to address, so seeing your messages delivered several minutes late is expected and normal. Even if it’s not necessarily desired.

**Comment by rwillett** [comment]
Closed as no update from original poster.
