### ISSUE TITLE
Error running example (Couldn't follow symbolic link)

### ISSUE THREAD

**Issue by juniavp** [katzer/cordova-plugin-local-notifications#1289]
Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.8.4
* Platform: Android
* OS version: -
* Device manufacturer / model: -
* Cordova version (```cordova -v```): 7.0.0
* Cordova platform version (```cordova platform ls```): Installed platforms:
  android 6.2.3
  ios 4.1.1
  windows 4.2.0
Available platforms: 
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0

* Plugin config

## Expected Behavior

Example is ran in Android device.

## Actual Behavior

When I run:
`$ cordova run android `

I get this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not list contents of '/home/CIT/Downloads/cordova-plugin-local-notifications-example/platforms/android/src/de/appplant/cordova/plugin/localnotification/ClickActivity.java'. Couldn't follow symbolic link.
```

## Steps to Reproduce

`$ cordova run android `

## Context

Run the example app.

**Comment by rwillett** [comment]
It looks as if you've installed something wrong. How did you install the plugin and which plugin did you install?

**Comment by rwillett** [comment]
No update from OP so closed,
