### ISSUE TITLE
Notification fires every day when we set the properties every 'day' when we remove it it does not work in ios.

### ISSUE THREAD

**Issue by grishchaudhary** [katzer/cordova-plugin-local-notifications#1294]
Hi All, 
I am facing issue regarding local notification every properties does not care the specific date it only cares the time it fires every day at that time but not the specific date but if i dont give every properties it does not work in IOs. are you guys facing this issue?Thank you.

**Comment by rwillett** [comment]
You removed the issue template that you were asked to fill in. Why?

**Comment by grishchaudhary** [comment]
sorry it was mistaken, I will keep the code with template.
