### ISSUE TITLE
【Android】hasPermission return true even if the permission is disabled

### ISSUE THREAD

**Issue by yesman99** [katzer/cordova-plugin-local-notifications#1295]
## Your Environment

* Plugin version: 0.8.4
* Platform: Android
* OS version: 5.1
* Device manufacturer / model: BV2000s
* Cordova version (```cordova -v```): 6.2.0
* Cordova platform version (```cordova platform ls```):5.1.1
* Plugin config

## Expected Behavior

hasPermission returns false when I disable push notification in device's config.

## Actual Behavior

hasPermission returns true even if the permission is disabled

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ... Set disable the app's push notification in device's config.
  2. ... Launch the app and alert hasPermission's granted.

Is this because of the Android's OS version is too old?

Cheers

**Comment by rwillett** [comment]
Works for me on Android 5, 6 and Android 7.

**Comment by lbelvale42** [comment]
Same problem for me

**Comment by rwillett** [comment]
I suspect this is due to different manufacturers. We've tested this on a 'pure' Android Nexus 5 and Genymotion and it works for us.

**Comment by lbelvale42** [comment]
I have test on my real android device, reproduce the steps describe by yesman99 and it's not working.

**Comment by rwillett** [comment]
As I have already said, we tested on Nexus 5 with Android 5 and Android 6 and Genymotion with Android 7 and it works for us.

I suspect that some manufacturers change things around and this is what the problem is.

**Comment by AlexanderKoehn** [comment]
Take a look at
https://github.com/katzer/cordova-plugin-local-notifications/blob/master/www/local-notification-core.js#L422
Only ios is implemented atm.

**Comment by katzer** [comment]
Has been implemented for Android based on the PR
