### ISSUE TITLE
Solution for the deprecated in Cordova version 5.0 

### ISSUE THREAD

**Issue by Brhernann** [katzer/cordova-plugin-local-notifications#1296]
Hi, i have a 6.5.0 Cordova version and i need use this plugins in my IOS 

do your have some solution for IOS? other library?

on my android project it works perfect! 

Thanks!.

**Comment by rwillett** [comment]
@Brhernann 

This plugin works in cordova 6.5. We use it. 

If you need help, fill out the issues template that you were supposed to fill out when you raised this one. The whole point of the template is to ask for information that you need to provide. I have zero idea what your problem is.

**Comment by rwillett** [comment]
Closed as no update from original poster.
