### ISSUE TITLE
Custom sound not working on IOS 10

### ISSUE THREAD

**Issue by abidvf** [katzer/cordova-plugin-local-notifications#1297]
Provide a general summary of the issue.

**## Your Environment**

Plugin version:
Platform: IOS
OS version: 10.2
Device manufacturer / model: iPhone 6 Plus
Cordova version (cordova -v): 6.5.0
Cordova platform version (cordova platform ls): IOS 4.3.1
Plugin config

**## Expected Behavior**
I am trying to set the custom sound option for notification and it should sound like what I try to set the custom sound to it.

**_Tell us what happens instead_**

It doesn't trigger any sound that I am trying to set it for IOS. Here is my code below.

reminderArray.push({
                    id: 8,
                    text: "Its Isha Time",
                    at: _5_sec_from_now,
                    icon: 'file://img/logo.png',
                    sound: settings[8] ? 'res://platform_default' : (isAndroid ? 'file://audio/azan.wav' : 'file://audio/azan.caf'),
                    every: "day"
                  });

 A quick response will highly be appreciated.

Cheers

**Comment by zannet** [comment]
all notifications not working on ios 10 using 0.8.5

**Comment by rwillett** [comment]
@abidvf

I don't think custom sounds work on IOS, they do on Android. If I get chance this week, I might see if they work for me.

@zannet 

Do not hijack other peoples issues with your own. Raise a new issue. Your statement also says nothing.

**Comment by katzer** [comment]
@abidvf The iOS-10 code isn't perfect yet. As far as I can remember the sound was working, at least with 10.0.x However I had to make sure manually that the app had the right permissions to play notification sounds.

**Comment by abidvf** [comment]
@katzer I have tried with different file formats for IOS but no success.

**Comment by egdbear** [comment]
Be sure that your audio directory is inside www.
Also check if sound notifications volume are turned on in Settings > Sounds > Ringer and Alert (scroller).

**Comment by katzer** [comment]
With a .caf sound file located under www folder for example it works pretty well.
