### ISSUE TITLE
Failed to install 'cordova-plugin-notification'

### ISSUE THREAD

**Issue by anrip** [katzer/cordova-plugin-local-notifications#1299]
Failed to install 'cordova-plugin-notification': CordovaError: Failed to fetch plugin cordova-plugin-app-event@>=1.2.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.

**Comment by rwillett** [comment]
You haven't filled the template in. The template is put there for a reason as it asks you to provide useful information about what you were doing, what the error is. 

Note the first line of the template, 

**WARNING: If you ignore this template, we'll ignore your issue.**

**Comment by anrip** [comment]
when put the cordova-plugin-notification into package.json, run cordova prepare, get the error.

**Comment by rwillett** [comment]
No template or update so closed.
