### ISSUE TITLE
iOS 10 Background localnotification ionic-2 

### ISSUE THREAD

**Issue by jd0048** [katzer/cordova-plugin-local-notifications#1301]
* Plugin version: 0.8.5
* Platform: IOS
* OS version: 10.XX
* Device manufacturer / model: Iphone 
* Cordova version (```cordova -v```): 6.5.0
* Cordova platform version (```cordova platform ls```):  ios 4.1.1
* Plugin config

## Expected Behavior
When i am in background local notification is not displaying 

## Actual Behavior

it must be fired local notification when user application is in background mode also

## Steps to Reproduce
put this code in the place when your application gone in background
```
this.localNotifications.schedule({
						id: 1,
						text: 'notification fired',
						sound: 'file://beep.caf'
					
					});
```

**Comment by rwillett** [comment]
When do you think your notification will be scheduled?

You have no date for it. 

You must put an ```at:``` field in. You also need to schedule the date at least a few seconds in the future. You cannot schedule a notification for now.

There are also other issues, you should make your object call to schedule an object inside an array even if there is only one element.

You have no callback success function.

We have no idea if ```this``` is correct.

**Comment by jd0048** [comment]
we don't need to schedule notification we need instance notification when anything happen in application and its working fine when my application is in foreground so code is perfect just issue with the background mode

**Comment by jd0048** [comment]
@rwillett its ionic-2 code

**Comment by rwillett** [comment]
How are you scheduling notifications in the background? Are you trying to schedule a local notification whilst your app is in the background?

The moment IOS puts an app in the background it is possible that it gets suspended immediately. This means that you cannot schedule anything whilst in the background. Under IOS 8 and 9 it *may* take up to 15 mins for your app to be suspended, under IOS 10 it *may* only take seconds as Apple is more aggressive about suspending your app. 

This is nothing to do with your app, it is a product of Apple and JavaScript and there is very little you can do about it.

**Comment by jd0048** [comment]
@rwillett  i had already all this description in other thread but it will log the console.log data in terminal when anything happen in application 
just issue is it will not fired in background :(

**Comment by jd0048** [comment]
`document.addEventListener('pause', () => {
			console.log('application pause--------->')
		this.localNotifications.schedule({
						id: 1,
						text: 'app in background',
						sound: 'file://beep.caf'
					
					});
		});`

check this code its working fine also in simulator but in actually device it will not fired local notification

**Comment by rwillett** [comment]
If you are not scheduling the notification for the future, then your app MUST be in the foreground when you are scheduling it. How else can you schedule it? 

This plugin will generate a notification for IOS10 when the app is in the background or even killed, if and only if you schedule it in advance. i.e. when the app is in the foreground. We know this works as we explicitly use it and have a test case that checks it, it also works on IOS8 & 9, Android 5, 6 and 7 on Ionic 1. 

So put an at: field in, schedule a notification for 30 secs in the future and see what happens.

I have no idea about Ionic 2 as you didn't mention that at the beginning so it never occurred to me.  We also do not use Ionic 2.

**Comment by rwillett** [comment]
The simulator does NOT work correctly when apps are put in the background. The Xcode simulator keeps apps running and other stuff such as HTTP connections. It does not work the same way as a real device, hence you are managing to execute code in the background.

**Comment by jd0048** [comment]
`at: new Date(new Date().getTime() + 5*1000)`

@rwillett never mind i had try with at and 5 second but its not working

now what should i do?

**Comment by rwillett** [comment]
So are you running this with the app in the foreground, creating a local notification for five seconds in the future, and then putting the app into the background within five seconds on a real device? 

If it works whilst leaving the app in the foreground on a real IOS device, then it looks as if there is a bug in either Ionic 2 or this plugin. 

You cannot use Xcode IOS simulator for doing stuff background stuff as its different, things like setTimeout will not suspend in the simulator and will suspend on a real device.

**Comment by jd0048** [comment]
yes in foreground its working fine it will fire after 5 second but i have schedule another notification that it will fire when application gone in background but that notification is not fired?

have you got my issue? what problem i am facing in real device?

**Comment by rwillett** [comment]
Which plugin are you using and how did you install it?

**Comment by jd0048** [comment]
`cordova plugin add de.appplant.cordova.plugin.local-notification`

**Comment by rwillett** [comment]
Try the ios10 plugin

cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#ios10

**Comment by jd0048** [comment]
Not works

**Comment by rwillett** [comment]
It works fine for us on Ionic 1. 

Suggest you raise this with the Ionic team.

**Comment by jd0048** [comment]
if you are not supporting in ionic 2 then why ionic 2 suggest as to use this plugin for local notifications

**Comment by rwillett** [comment]
I am not supporting the plugin as I didn't write the plugin, I am helping out people as we use the plugin all the time and it works for us. I have no connection with @katzer other than as a user (and as an administrator here), we are trying to free some time up for him to revise the plugin just to help out.

I cannot speak for why Ionic recommends this plugin. I know it works fine under Ionic 1 as we use it all the time and it works.

**Comment by jd0048** [comment]
thank you for your time @rwillett lets wait for @katzer what he/she said about this issue

**Comment by rwillett** [comment]
You could generate a simple Ionic 1 project, just add your code to this and run it. Shouldn't take more than 20 mins. If it works under there, you know its Ionic 2. If it doesn't work, you know its your code.

**Comment by katzer** [comment]
> lets wait for @katzer what he/she said about this issue

he 👍

**Comment by katzer** [comment]
At the moment I cant tell much things about Ionic. Their current wrapper does not work with 0.9-beta. Because many are using the plugin+ionic I will contribute to the ionic-native wrapper in future.

But for now I am closing all ionic related tickets because they point to old code and/or Ionic.
