### ISSUE TITLE
Document the content of the .at and .firstAt element of a notification object

### ISSUE THREAD

**Issue by acutetech** [katzer/cordova-plugin-local-notifications#1302]
**WARNING: If you ignore this template, we'll ignore your issue.**

Provide a general summary of the issue.

Suggested enhancement to documentation: I find that the value of the at (and I guess the atFirst) elements of a notification is unix timestamp (seconds since 1/1/1970. ) Can convert to a javascript Date object by this:
var date = new Date(notification.at * 1000);

## Your Environment

* Plugin version:
* Platform:
* OS version:
* Device manufacturer / model:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Plugin config

## Expected Behavior

_Tell us what should happen_

## Actual Behavior

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment]
Do the test update and we'll merge the PR.
