### ISSUE TITLE
this is year in week repeat use by cordova .

### ISSUE THREAD

**Issue by kaushikkalariya** [katzer/cordova-plugin-local-notifications#1304]
**WARNING: If you ignore this template, we'll ignore your issue.**

Provide a general summary of the issue.

## Your Environment

* Plugin version:
* Platform:
* OS version:
* Device manufacturer / model:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Plugin config

## Expected Behavior

_Tell us what should happen_

## Actual Behavior

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment]
Not a clue what you are trying to do.

All you have done is put a title in and ignored the template.

**Comment by rwillett** [comment]
Closed as no update from user.
