### ISSUE TITLE
Unknown property: icon

### ISSUE THREAD

**Issue by salunkhenilesh** [katzer/cordova-plugin-local-notifications#1307]
Hi Team,
             I am getting notification. but for set icon getting this one issues is Unknown property: icon.

**Comment by rwillett** [comment]
Please fill out the template.

**Comment by salunkhenilesh** [comment]
var notify = new Date();
        notify.setHours(05);
        notify.setMinutes(58);
        cordova.plugins.notification.local.schedule({
            id: 100,
            title: "Beauty Parlor",
            text: "Happy Birthday",
            every: "month",
            icon:"res://icon",
            at: notify,



        });

**Comment by salunkhenilesh** [comment]
![iconerror](https://cloud.githubusercontent.com/assets/18122372/26633162/19009164-4630-11e7-80ff-2bdac4be0c1c.PNG)

**Comment by salunkhenilesh** [comment]
Cordova version (cordova -v): 6.5.0
Cordova platform version (cordova platform ls): android 6.1.2
 in my project i am implement notification to user.
var notify = new Date();
notify.setHours(05);
notify.setMinutes(58);
cordova.plugins.notification.local.schedule({
id: 100,
title: "Beauty Parlor",
text: "Happy Birthday",
every: "month",
icon:"res://icon",
at: notify,

    });
Above code for local notification.

not able change icon bell_icon to my app icon. when i Add icon property into code getting unknown property for icon;

**Comment by rwillett** [comment]
Since you are incapable for following simple instructions and filling the template in, despite being asked twice, I'm closing this thread.
