### ISSUE TITLE
Unable to cancel scheduled notifications for IOS 10

### ISSUE THREAD

**Issue by abidvf** [katzer/cordova-plugin-local-notifications#1309]
## Your Environment

Plugin version:
Platform: IOS
OS version: 10.2
Device manufacturer / model: iPhone 6 Plus
Cordova version (cordova -v): 6.5.0
Cordova platform version (Cordova platform ls): IOS 4.3.1
Plugin config
## Expected Behavior
If there are scheduled notifications then they should be canceled.
**Tell us what should happen**
I am trying to pass an array of IDs to cancel some of my scheduled local notifications for IOS 10 devices and unfortunately it dosent work for me.
**Tell us what happens instead**
It should cancel the notifications whose ids are inside an array that we pass to cancel method of local notification.
My code is: 
cordova.plugins.notification.local.cancel([4,5,6,7,8], function() {
          console.log("removed all  notifications for ios");
        });

Thanks

**Comment by rwillett** [comment]
You haven't said which version of the plugin you are using. The template is there for a reason, use it.

This works for us on IOS10. We do a clear and then a cancel. We clear, then cancel then execute something to make sure it happens in the right order. This is taken from working production code and works on IOS10.

```
function ClearAndCancelLocalNotificationsAndThenExecute (toClearArray:number[] , ExecFunction = null , arg1 = null) {
        var debugClearAndCancelLocalNotificationsAndThenExecute = debugFalse;

        if (debugClearAndCancelLocalNotificationsAndThenExecute)
            ConsoleLog("ClearAndCancelLocalNotificationsAndThenExecute: toClearArray = " + JSON.stringify(toClearArray));

        cordova.plugins.notification.local.clear(toClearArray , function() {
            if (debugClearAndCancelLocalNotificationsAndThenExecute)
            {
                ConsoleLog("ClearAndCancelLocalNotificationsAndThenExecute: Clear function success");

                ShowNotificationQueue();
            }

            cordova.plugins.notification.local.cancel(toClearArray , function() {
                if (debugClearAndCancelLocalNotificationsAndThenExecute)
                {
                    ConsoleLog("ClearAndCancelLocalNotificationsAndThenExecute: Cancel function success");

                    ShowNotificationQueue();
                }

                if (ExecFunction)
                    ExecFunction(arg1);
            });
        });
    }
```

**Comment by abidvf** [comment]
@rwillett  you mean to say first I have to call clear function and then cancel function to remove all of the notifications which have their IDS inside an array?

**Comment by rwillett** [comment]
Thats the way we wrote it and it works for us. YMMV.

**Comment by rwillett** [comment]
Did this work?

**Comment by marcovtwout** [comment]
See https://github.com/katzer/cordova-plugin-local-notifications/wiki/06.-Clear and https://github.com/katzer/cordova-plugin-local-notifications/wiki/07.-Cancelation when deciding if you need to clear() or cancel()

**Comment by katzer** [comment]
Should work fine with 0.9-beta. If not the reopen the ticket.
