### ISSUE TITLE
Does not receive notifications when app is exist

### ISSUE THREAD

**Issue by anivaisu** [katzer/cordova-plugin-local-notifications#1310]
I am using ionic 2 with cordova localnotifications

Here is my code

import { LocalNotifications } from '@ionic-native/local-notifications';

constructor(private localNotifications: LocalNotifications) { }

// Schedule a single notification
this.localNotifications.schedule({
  id: 1,
  text: 'Single ILocalNotification',
  sound: isAndroid? 'file://sound.mp3': 'file://beep.caf',
  data: { secret: key }
});

It's work only when app is resumed or running.I force to closing app.doesn't receive any notifications.
How can i able to do this?

KIndly advice me,

Thanks

**Comment by rwillett** [comment]
No template.

**Comment by rwillett** [comment]
Closed as no update from OP.
