### ISSUE TITLE
"every" property results in no notifications in iOS

### ISSUE THREAD

**Issue by klick-barakgall** [katzer/cordova-plugin-local-notifications#1313]
## Summary
On iOS, I can't get the "every" property to work at all.

An unrelated note: I get a warning whenever I try to use "firstAt" instead of "at", despite this being a documented property.

If I include the "every" property in the call a notification is NEVER triggered.

* Plugin version: 0.8.5
* Platform: iOS
* OS version: iOS 10.3.2
* Device manufacturer / model: iPhone 6+ (I don't know who manufactures them)
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): ios 4.4.0
* Plugin config: None

I expect a first notification to be triggered at the designated "at" date, and then the "every" property continually trigger further notifications (currently set to minute).

However, instead my notification is never triggered unless I remove the "every" property from the options.

This issue occurs every time for me with this code:
```javascript
		cordova.plugins.notification.local.schedule({
			id:1,
			title: 'test',
			text: 'test!',
			at: new Date(new Date().getTime() + (5*1000)),
			every: 'minute'
		});
```
Just to be extra safe I'm also now trying with this code instead (with the same results):
```javascript
		cordova.plugins.notification.local.cancelAll(function(){
			cordova.plugins.notification.local.schedule({
				id:2,
				title: 'test2',
				text: 'test2!',
				at: new Date(new Date().getTime() + (5*1000)),
				every: 'minute'
			});
		});
```

I am trying to test a solution where the plugin will regularly trigger a piece of javascript code. For testing I set "every" to "minute" but ultimately it will be changed to "day". Additionally I will be adding an event handler on trigger to determine actual course of action. The notification here is just used for it's scheduling capabilities. Currently a notification also triggers a sound but I'm hoping to find a way to suppress that. I'm open to alternative methods of achieving this same functionality.

I just tried for the last 20 minutes, and I can't figure out how to get the device logs. I found some logs but they were outdated. I found an SO that recommended I delete the SQLite device log files, and let it restore it, however now the device logs are empty even after I try rebuilding and redeploying the app. Can you give some instructions on how I can provide relevant device logs? Otherwise if you're just looking for XCode output this is what I have (I had to replace my application name with Foo Bar):

```
2017-06-06 10:30:54.157219-0400 Foo Bar[367:20314] Apache Cordova native platform version 4.4.0 is starting.
2017-06-06 10:30:54.158217-0400 Foo Bar[367:20314] Multi-tasking -> Device: YES, App: YES
2017-06-06 10:30:54.167535-0400 Foo Bar[367:20314] 

Started backup to iCloud! Please be careful.
Your application might be rejected by Apple if you store too much data.
For more information please read "iOS Data Storage Guidelines" at:
https://developer.apple.com/icloud/documentation/data-storage/
To disable web storage backup to iCloud, set the BackupWebStorage preference to "local" in the Cordova config.xml file
2017-06-06 10:30:54.252572-0400 Foo Bar[367:20314] Using UIWebView
2017-06-06 10:30:54.254858-0400 Foo Bar[367:20314] [CDVTimer][handleopenurl] 0.124037ms
2017-06-06 10:30:54.257389-0400 Foo Bar[367:20314] [CDVTimer][intentandnavigationfilter] 2.429008ms
2017-06-06 10:30:54.257609-0400 Foo Bar[367:20314] [CDVTimer][gesturehandler] 0.136018ms
2017-06-06 10:30:54.282769-0400 Foo Bar[367:20314] [CDVTimer][file] 24.946988ms
2017-06-06 10:30:54.287976-0400 Foo Bar[367:20314] [CDVTimer][localnotification] 5.075037ms
2017-06-06 10:30:54.288075-0400 Foo Bar[367:20314] [CDVTimer][localnotification] 0.014007ms
2017-06-06 10:30:54.288114-0400 Foo Bar[367:20314] [CDVTimer][TotalPluginStartup] 33.424020ms
2017-06-06 10:30:54.353275-0400 Foo Bar[367:20352] libMobileGestalt MobileGestaltSupport.m:153: pid 367 (Foo Bar) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled
2017-06-06 10:30:54.353362-0400 Foo Bar[367:20352] libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)
2017-06-06 10:30:54.692221-0400 Foo Bar[367:20314] Resetting plugins due to page load.
2017-06-06 10:30:54.890898-0400 Foo Bar[367:20314] Finished load of: file:///var/containers/Bundle/Application/CC444C4A-DE71-466F-8B5D-0D0F4FE00DDB/Foo%20Bar.app/www/index.html
```

EDIT: Fixed updated code snippet to include "every" instead of having it commented out.

**Comment by rwillett** [comment]
```at:``` and ```every:``` do not work together on IOS10.

Apparently Apple have changed the way the underlying notifications framework is implemented on IOS10 from IOS9 and breaks this. As I understand it, the ```every:``` option will not be supported going forward in any new release of this plugin. I do not have a timetable for the next release.

**Comment by rwillett** [comment]
Whilst this is a pain, we coded around it quite easily.

**Comment by klick-barakgall** [comment]
Thanks for the fast response @rwillett !

When you say you coded around this, do you mean that you trigger the event once and then use the trigger event to schedule a new event? I was thinking of doing this instead. Do you know if that will still work if the device is off during the appointed trigger time? (will it delay until the device is on again?)

**Comment by rwillett** [comment]
That won't work, the triggering of the notification doesn't allow you to run Javascript AFAWK, so you can't schedule a new notification this way.

We schedule a few events in advance and then as the user uses the app we work out whats gone and reschedule new ones again. This means that you have to have the user open your app periodically so that you can cancel and re-schedule. 

If you have a use case where you simply need to schedule a notification every day for the next year but the user never opens the app, then this is not the right approach. It might be best to use a calendar them, our use cases mean the user had to open the app periodically so it's not an issue for us. Other people have more of a problem.  

Rob

**Comment by klick-barakgall** [comment]
Hey Rob, I thought that was the intention of the `cordova.plugins.notification.local.on("trigger", ...)` event. Is that not the case?

**Comment by rwillett** [comment]
I don't think it works, we certainly never got it to.

**Comment by klick-barakgall** [comment]
I see, I guess this issue should be closed then? It seems like it's a known issue and the recommended action is to work around it until the behaviour is deprecated and removed?

**Comment by rwillett** [comment]
Thats correct,
