### ISSUE TITLE
ionic 2 :  local notification not running after restart device

### ISSUE THREAD

**Issue by holu15795** [katzer/cordova-plugin-local-notifications#1314]
WARNING: If you ignore this template, we'll ignore your issue.

Provide a general summary of the issue.

Your Environment

Platform: android

Expected Behavior

When restart phone notification appear

Actual Behavior

Notification not fired

Context

I am doing alarm clock app. When the time is done, there is a notice when the appointment, I have done. But when I set the time to restart the phone, so far no notice. Any ideas what help me?

**Comment by rwillett** [comment]
No idea what the problem is here. Thats why the template is there,
