### ISSUE TITLE
ionic 2: after restart phone notifications not show

### ISSUE THREAD

**Issue by holu15795** [katzer/cordova-plugin-local-notifications#1315]
**WARNING: If you ignore this template, we'll ignore your issue.**

Provide a general summary of the issue.

## Your Environment

* Plugin version:
* Platform: Android
* OS version:
* Device manufacturer / model:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Plugin config

## Expected Behavior

I am doing alarm clock app. When the time is done, there is a notice when the appointment, I have done. But when I set the time to restart the phone, so far no notice. Any ideas what help me?

## Actual Behavior

notification not show

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

i trying show notification after restart phone

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rafaellop** [comment]
I can confirm that notifications set before a device restart are not triggered when the phone is restarted. My environment is:

Plugin version: 0.8.4
Platform: Android
OS version: 5.1
Device manufacturer / model: Xiaomi Redmi Note 2
Cordova version (cordova -v): 7.0.1
Cordova platform version (cordova platform ls): android 6.2.3

I have to restart the app to reschedule the notifications.

**Comment by rwillett** [comment]
It works fine on Android  5 and 6 on Nexus 5 phones as well as Android 7 on Genymotion. There might well be issues on Xiomi phones. 

And to the OP, the template was not filled out correctly. No idea on versions, code whatever. Pointless.

**Comment by rwillett** [comment]
Closed as no update from OP.
