### ISSUE TITLE
How can I clear notification counter on custom launchers?

### ISSUE THREAD

**Issue by thpoiani** [katzer/cordova-plugin-local-notifications#1316]
On some devices, the notifications counter is displayed over the application icon.
However, the counter not reset even when I run the `clearAll` method.

## Your Environment

* Plugin version: `de.appplant.cordova.plugin.local-notification 0.8.4`
* Platform: `Android`
* OS version: `5.0.1`
* Device manufacturer / model: `SAMSUNG GT-I9505`
* Cordova version (```cordova -v```): `6.4.0`
* Cordova platform version (```cordova platform ls```): `android 6.0.0`

## Expected Behavior

Reset notification counter on application icon.

## Actual Behavior

`window.cordova.plugins.notification.local.clearAll();` don't clean this app badge number.

![image](https://user-images.githubusercontent.com/1860289/26977476-6c54728e-4cfe-11e7-8ffc-e9ef015eadb5.png)

## Steps to Reproduce

  1. Try it on a device with custom launcher
  2. Send a local notification

```js
window.cordova.plugins.notification.local.schedule({
  id: new Date(),
  icon: 'res://ic_stat_onesignal_default.png',
  color: '78053E',
  title: 'TITLE',
  text: 'TEXT',
  sound: ionic.Platform.isAndroid() ? 'file://audio/sound.mp3' : 'file://audio/sound.caf'
});
```
  3. Clear it

```js
window.cordova.plugins.notification.local.clearAll();
```

  4. Check the app icon on applications screen

**Comment by rwillett** [comment]
We had masses of problems with this and with other plugins such as PushWoosh. There were masses of conflicts and we struggled to make this work, so we gave up.

**Comment by katzer** [comment]
Badge icons like you have shown isn't supported by Android, only through 3rd party extensions. The local-notification plugin does use cordova-plugin-badge now to set the badge.

Using different solutions may conflict each other.
