### ISSUE TITLE
Heads-up notification android 

### ISSUE THREAD

**Issue by philipgriffin** [katzer/cordova-plugin-local-notifications#1317]
## Your Environment

* Plugin version: "^0.8.5"
* Platform: android
* OS version: Samsung Galaxy S5
* Device manufacturer / model:
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): android 6.2.3
* Plugin config

## Expected Behavior

I am using IONIC 2.
I should see a heads-up notification when the notification is triggered.

## Actual Behavior

The bell icon appears in the status bar and the notification sound plays but it does not popdown.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Schedule a notification
  2. Close the application
  3. Wait for the notification to trigger

**Comment by philipgriffin** [comment]
I solved this by using this fork https://github.com/DavidBriglio/cordova-plugin-local-notifications

**Comment by kirajhpang** [comment]
@philipgriffin good suggestion..!! it works for me also.

**Comment by philipgriffin** [comment]
@kirajhpang no problem, but since creating this, the new way (that should work using the [ionic-native plugin](https://ionicframework.com/docs/native/local-notifications/)) is to set the priority to 1. See the priority option [here](https://ionicframework.com/docs/native/local-notifications/#ILocalNotification).

**Comment by kirajhpang** [comment]
@philipgriffin hi, thanks for inform, but When I set `priority: 1`, it doesn't seem to work. 
debug console show error: `unknown property: priority`

**Comment by katzer** [comment]
Thats possible now with 0.9-beta with `priority:`
