### ISSUE TITLE
Device locked - Notification not showing

### ISSUE THREAD

**Issue by philipgriffin** [katzer/cordova-plugin-local-notifications#1318]
## Your Environment

* Plugin version: "^0.8.5"
* Platform: android
* OS version: 
* Device manufacturer / model: Samsung Galaxy S5
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): android 6.2.3
* Plugin config

## Expected Behavior

I am using IONIC 2 and have the background mode plugin activated and working.
I should get a notification when the device is locked.

## Actual Behavior

The notification is not triggered and will randomly trigger when the device is back on.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Schedule a notification
  2. Close the application
  3. Lock the device
  4. Make sure the screen is dim

I have included a gif of the issue showing it works when the screen is not dimmed and also that it doesn't work when the screen is dimmed.
<img src="http://i.imgur.com/LRNeftF.gif"/>

**Comment by philipgriffin** [comment]
I solved this by using this fork https://github.com/DavidBriglio/cordova-plugin-local-notifications

**Comment by katzer** [comment]
Please reopen if its still a topic with 0.9-beta
