### ISSUE TITLE
Ionic 2: change icon notification

### ISSUE THREAD

**Issue by holu15795** [katzer/cordova-plugin-local-notifications#1321]
* Plugin version:"^0.8.5"
* Platform:android
* OS version: Samsung s6
* Device manufacturer / model:
* Cordova version (```cordova -v```): 6.5.0
* Cordova platform version (```cordova platform ls```):android 6.1.2
* Plugin config
* Ionic Version (if using Ionic) 2

## Expected Behavior

i want change icon notification

## Actual Behavior

notification show icon default

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/22868108/27163285-8a6b3580-51b0-11e7-9083-798bbed23d3f.png)

let notifi = {
      id: this.i++,
      title: "Notifi !!!",
      text: "yayays !!!",
      at: new Date(new Date().getTime() + time),
      icon: 'file://img/clock1.png'
    };
    LocalNotifications.schedule(notifi);

**Comment by pcsantana** [comment]
This helped me:
https://github.com/katzer/cordova-plugin-local-notifications/issues/1308#issuecomment-305680542

**Comment by marcovtwout** [comment]
Also see https://github.com/katzer/cordova-plugin-local-notifications/issues/1398

**Comment by katzer** [comment]
Please keep in mind that your icon should follow some design rules: monochrom and transparent background instead of white...

**Comment by joesleiman** [comment]
@katzer i make an icon transparent and put it in the correct positions and correct name , it works fine, but as the icon is white and transparent background it doesn't look nice, how can i change the background if the icon (big-icon)?
