### ISSUE TITLE
Cannot received notification if the app is killed

### ISSUE THREAD

**Issue by felixliu226** [katzer/cordova-plugin-local-notifications#1323]
* Plugin version: 0.8.5
* Platform: android
* OS version: 7.1.1
* Device manufacturer / model: Samsung Galaxy Tab A6
* Cordova version (```cordova -v```):7.0.1
* Cordova platform version (```cordova platform ls```): android 6.2.3
* Plugin config
* Ionic Version (if using Ionic) 2

## Expected Behavior

I scheduled a delayed notification and the time will be 30 seconds later. A notification should be expected to be sent.

## Actual Behavior

If I keep the app running in background, the notification works as expected. However, after I kill the app (swipe the app from recently used apps), there will be no notifications.

## Steps to Reproduce

Just use the sample, set up a delayed notification and then swipe the app from recently used apps

## Context

I'm trying to make a reminder for user at scheduled time.

## Debug logs

Not available.

So I would like to ask is this the expected behavior of the local notification plugin? From my understanding, I suppose it could work whether the app is running in background or not. 

If it is the expected behavior, could you please suggest is there any other way to achieve what I want to do? Thanks in advance.

**Comment by rwillett** [comment]
This is not the expected behaviour. 

This appears to be a problem with Ionic 2 as it works fine in Ionic 1. It could be your code but other people seem to have similar issues with Ionic 2.

**Comment by gigeos** [comment]
Work on Ionic 3 with my app

**Comment by rwillett** [comment]
Ah, thats interesting. We don't use Ionic 3 (or Ionic 2) but it works fine for us across IOS (all versions) and Android (all version but not tested on Android O). 

Could you post simple code that shows this working?

Rob

**Comment by gigeos** [comment]
@rwillett I did it:

```
initScheduleNotifications() {
    const notificationId = 42;
    const scheduleTime = 60 * 1000 * 5;
    this.localNotifications.isScheduled(notificationId).then(
      isScheduled => {
        if (isScheduled ) {
          this.localNotifications.update({
            id: notificationId,
            at: new Date(new Date().getTime() + scheduleTime)
          });
        } else {
          this.localNotifications.schedule({
            id: notificationId,
            text: 'Come back !',
            at: new Date(new Date().getTime() + scheduleTime)
          });
        }
      });
  }
```

I can kill app or reboot phone, I receive my notification 5 min after launch. No problem.

```
$ ionic -v
3.4.0

$ cordova -v
7.0.1

```

**Comment by mzealey** [comment]
I too get this issue with the killed events not working on Android M with ionic 3.4 and cordova 7 (ie latest of everything)

**Comment by d3w201** [comment]
sorry guys i dont use any version of ionic.. use just cordova 7.0.1 and Node v6.10.2

**Comment by d3w201** [comment]
aniway i cannot understan how it works? there'is some kind of service still working 
though the app was killed? and what about this service, i have search in plugin source code but i dont found it? maybe  the service is defined in another plugin class?

**Comment by katzer** [comment]
The native OS is responsible for triggering the notification at the right time. There's no service inside the app.

I can schedule notifications and they come up even the app isn't running. I assume its an issue with the ionic wrapper/code

**Comment by mntdragon** [comment]
you may need the background service to keep the app not sleep
