### ISSUE TITLE
Setting native  ringtone file Url as sound, does not play

### ISSUE THREAD

**Issue by bimal72** [katzer/cordova-plugin-local-notifications#1324]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
I want to set native system ringtone as sound of notification
## Your Environment

* Plugin version: 0.8.5
* Platform: android
* OS version: 7.0
* Device manufacturer / model: Samsung S6 edge+
* Cordova version (```cordova -v```): 
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic) 3.4.0

## Expected Behavior
Hello, Using ringtone native plugin, I am selecting ringtone and setting its Url as sound attribute of the notification.

```
sound: 'content://media/internal/audio/media/26', 
```
_Tell us what should happen_

Assuming this should play the above sound while getting notification

## Actual Behavior

_Tell us what happens instead_

It does not play any sound

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by DylanStandridge** [comment]
Did you ever find an answer to this?

**Comment by aryanpatel** [comment]
Any updates?

**Comment by aryanpatel** [comment]
@bimal72 @DylanStandridge If it helps, I was able to solve this with `cordova-plugin-filepath`
It converted Path from native ringtone plugin to native path (e.g. content:// to file://) and set that converted path to `sound` option

**Comment by DylanStandridge** [comment]
@aryanpatel Thanks, There are problems with sound on the later android versions so I had to scratch sound all together. Though the Plugin is still super handy.

**Comment by katzer** [comment]
@DylanStandridge @bimal72 @aryanpatel Sound on Android works with 0.9-beta, also on later Android Versions (>= 7).

**Comment by katzer** [comment]
The plugin also supports `content://` scheme since 0.9-beta.
