### ISSUE TITLE
Unable to install 0.8.5 for ios

### ISSUE THREAD

**Issue by githubjiangang** [katzer/cordova-plugin-local-notifications#1326]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:0.8.5
* Platform:mac
* OS version:10.12
* Device manufacturer / model:Apple
* Cordova version (```cordova -v```):7.0.1
* Cordova platform version (```cordova platform ls```):ios 4.4.0
* Plugin config  cordova-plugin-device 1.1.6
* Ionic Version (if using Ionic)

## Expected Behavior

_Tell us what should happen_
exec install 
      cordova plugin install ./cordova-plugin-local-notifications-0.8.5 (which download from your release)
or 
      cordova plugin add git+https://github.com/katzer/cordova-plugin-local-notifications.git#ios10
## Actual Behavior

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment]
So what actually happens when you type the commands in.

**Comment by rohitkawale** [comment]
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications 
doing this gives not able to fetch plugin on ios

**Comment by rwillett** [comment]
That's not the error message. That's your view of what's happening.

**Comment by csantosdev** [comment]
$ cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
```
Error: Failed to fetch plugin https://github.com/katzer/cordova-plugin-local-notifications via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

**Comment by sampohaavisto** [comment]
I was able to install the plugin manually. This is an Ionic v1 project so your config may differ.

```
$ cd project/plugins/
$ git clone git@github.com:katzer/cordova-plugin-local-notifications.git
$ git clone git@github.com:katzer/cordova-plugin-app-event.git # dependency for notifications
```
Then in `project/config.xml` add this:

```
...
<plugin name="de.appplant.cordova.plugin.local-notification" spec="^0.8.5" />
...
```

More tips here: 
https://github.com/katzer/cordova-plugin-local-notifications/wiki/03.-Installation

**Comment by mzealey** [comment]
I think this is an issue with cordova 7 which has switched to using npm to install the modules. I am getting a similar issue but I can't diagnose why it is doing this. It is clearly not a connection error even though it says it is, and manual installs also don't work. npm is creating some random symbolic links that go to the wrong place etc etc

**Comment by rwillett** [comment]
I don't use cordova 7. Mmm.... Good reason to stay with cordova 6 for us.

**Comment by rohitkawale** [comment]
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications@version_no 
this is working for me where put required version instead of version_no in the command like
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications@0.8.5

**Comment by mzealey** [comment]
For some reason my npm can only see 0.8.4 not 0.8.5 i have no idea why this is... Cordova install still fails

**Comment by mzealey** [comment]
Confirm this is a cordova 7 issue with your module, perhaps because of the .s in the package name (???)

In some circumstances, this module will not install under cordova 7 with a very cryptic error message like:

```
$ cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#53262c8
Error: Failed to fetch plugin https://github.com/katzer/cordova-plugin-local-notifications#53262c8 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

This was on ubuntu 16.04 with latest npm (5.0.4)/cordova (7.0.1) installed. On a mac with the same versions installed however it worked ok with the same command.

A work-around is to use the old method like:

```
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#53262c8 --nofetch
```

**Comment by sampohaavisto** [comment]
Got cordova 7 running this smoothly now from the official repository.

In Ionic v1 we made a fresh install by 

1. Remove every cordova plugin reference from `config.xml` and `package.json`
2. `rm -Rf plugins/`
3. `rm -Rf node_modules/`
4. `npm install` note: Node >= 6 works with ionic / cordova 7, but npm 5 will cause horrors
5. Add all plugins one by one with `cordova plugin add cordova-my-plugin`
6. Finally add the platform with `cordova platform add ios`.

**Comment by rwillett** [comment]
Thanks for this. Useful information.

**Comment by rwillett** [comment]
Since the original poster hasn't bothered to come back AND @sampohaavisto has kindly posted a fix, I'm closing this.

**Comment by scottbcovert** [comment]
I know this issue has already been closed but just wanted to say thanks to @sampohaavisto for coming up with a solution.

**"note: Node >= 6 works with ionic / cordova 7, but npm 5 will cause horrors"**
^ Thank you for making this very important note!

I had Node 8 with npm 5 and that was the main cause of several days worth of headaches. I had uninstalled and reinstalled plugins, node modules, and the ios platform dozens of times without success but after downgrading to Node 7 with npm 4 it worked as expected.

**Comment by sampohaavisto** [comment]
@scottbcovert you're welcome!

Consider using [nvm](https://github.com/creationix/nvm) or [nodenv](https://github.com/nodenv/nodenv) for multiple node versions on same system. `npm` is package, so I'm not sure if you can hotswap that so easily.

You should be good with Node 6 for a while:

![nodelts](https://user-images.githubusercontent.com/5328394/31806397-2a7429c4-b570-11e7-9c2e-24c022140a6f.png)

**Comment by scottbcovert** [comment]
@sampohaavisto Yup, I used nvm and that worked very nicely-thanks again!
