### ISSUE TITLE
is there a way to open a force close app from background?

### ISSUE THREAD

**Issue by kennrll18** [katzer/cordova-plugin-local-notifications#1327]
is there a way to open a force close app from background? 
I'm using cordova-plugin-background-mode and cordova-plugin-local-notifications. 

Basically i listened to the background event and then add a listener for the local notification.
Inside call back for the local notification I would like to open the app from force close.

**Comment by Tawpie** [comment]
When your user taps the notification in the notification shade the OS will launch your app even when it was force quit.

(spelling and grammer powered by autocorrupt)

**Comment by kennrll18** [comment]
Yea i get that part, but I'd like to open the app when the notification is triggered.   Basically, i want to use cordova.plugins.backgroundMode.unlock() even when it's force quit.

**Comment by rwillett** [comment]
You can't force quite the app by clicking on the notification when the app is in the background. 

You could theoretically click on the app, that will open it, and then quit it.
