### ISSUE TITLE
Why do badges clear every time you schedule new notification

### ISSUE THREAD

**Issue by snakeman21** [katzer/cordova-plugin-local-notifications#1328]
It seems odd that by default all badges are cleared when you schedule a new one. At the very least, I think there should be an option to not clear all badges every time a new one is scheduled/

## Your Environment

* Plugin version: 0.8.5
* Platform: iOS
* OS version: 10.3.2
* Device manufacturer / model: iPhone 6
* Cordova version (```cordova -v```): 6.5.0
* Cordova platform version (```cordova platform ls```): Cordova-iOS 4.3.1

## Expected Behavior
I expect the plugin to either not clear all badges when scheduling a notification or to at least have an option to specify you don't want to. 

## Actual Behavior
It clears all badges every time a new notification is scheduled.

**Comment by katzer** [comment]
That has been fixed.
