### ISSUE TITLE
ELOOP: too many symbolic links encountered

### ISSUE THREAD

**Issue by marcelodeandrade** [katzer/cordova-plugin-local-notifications#1329]
## Your Environment

* Plugin version: 0.8.5
* Platform: Android
* OS version: Linux 4.4 ( Ubuntu 16.04 )
* Device manufacturer / model: Genymotion / ADV emulator
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): android 6.2.3
* Plugin config
* Ionic Version (if using Ionic) : 3.4.0

## Expected Behavior

Should be installed the plugin sucessfully

## Actual Behavior

Throws npm error:

> npm ERR! path /home/marcelo/Documents/ionic/newblank/node_modules/cordova-plugin-app-event/package.json
> npm ERR! code ELOOP
> npm ERR! errno -40
> npm ERR! syscall open
> npm ERR! ELOOP: too many symbolic links encountered, open '/home/marcelo/Documents/ionic/newblank/node_modules/cordova-plugin-app-event/package.json'
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/marcelo/.npm/_logs/2017-06-19T14_09_29_521Z-debug.log
> 

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

1. ionic start newBlank blank
2. ionic cordova plugin add de.appplant.cordova.plugin.local-notification
3. npm install --save @ ionic-native/local-notifications

## Context

Start a new and clean ionic project with local notifications

## Debug logs

> 
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'install',
> 1 verbose cli   '--save',
> 1 verbose cli   '@ionic-native/local-notifications' ]
> 2 info using npm@5.0.3
> 3 info using node@v7.8.0
> 4 verbose npm-session 16e292c3ded2cd7c
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 http fetch GET 304 https://registry.npmjs.org/@ionic-native%2flocal-notifications 1285ms (from cache)
> 8 silly pacote tag manifest for @ionic-native/local-notifications@latest fetched in 1322ms
> 9 silly install loadIdealTree
> 10 silly install cloneCurrentTreeToIdealTree
> 11 silly install loadShrinkwrap
> 12 silly fetchPackageMetaData error for cordova-plugin-app-event@file:node_modules/cordova-plugin-app-event ELOOP: too many symbolic links encountered, open '/home/marcelo/Documents/ionic/newblank/node_modules/cordova-plugin-app-event/package.json'
> 13 verbose stack Error: ELOOP: too many symbolic links encountered, open '/home/marcelo/Documents/ionic/newblank/node_modules/cordova-plugin-app-event/package.json'
> 14 verbose cwd /home/marcelo/Documents/ionic/newblank
> 15 verbose Linux 4.4.0-79-generic
> 16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "@ionic-native/local-notifications"
> 17 verbose node v7.8.0
> 18 verbose npm  v5.0.3
> 19 error path /home/marcelo/Documents/ionic/newblank/node_modules/cordova-plugin-app-event/package.json
> 20 error code ELOOP
> 21 error errno -40
> 22 error syscall open
> 23 error ELOOP: too many symbolic links encountered, open '/home/marcelo/Documents/ionic/newblank/node_modules/cordova-plugin-app-event/package.json'
> 24 verbose exit [ -40, true ]

**Comment by marcelodeandrade** [comment]
Ok, let's go! I changed the `node` and `npm` versions using [`n`](https://github.com/tj/n) and downgraded to:


```
System:

    Node       : v7.8.0
    npm        : 4.2.0
```
 
Again, rerunning the same commands and same step by step:

> 1) ionic start newBlank blank


Log:


```
marcelo@marcelo-X555LF:~/Documents/ionic$ ionic start teste blank
✔ Creating directory ./teste - done!
[INFO] Fetching app base
       (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template blank
       (https://github.com/ionic-team/ionic2-starter-blank/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✔ Running command - done!
> npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest
✔ Running command - done!
> git init
✔ Running command - done!
> git add -A
✔ Running command - done!
> git commit -m "Initial commit" --no-gpg-sign
✔ Running command - done!

♬ ♫ ♬ ♫  Your Ionic app is ready to go! ♬ ♫ ♬ ♫

Run your app in the browser (great for initial development):
  ionic serve

Run on a device or simulator:
  ionic cordova run ios

Test and share your app on a device with the Ionic View app:
  http://view.ionic.io
  
? Link this app to your Ionic Dashboard to use tools like Ionic View? No

Go to your newly created project: cd ./teste
```



> 2) ionic cordova plugin add de.appplant.cordova.plugin.local-notification

Log:

```

marcelo@marcelo-X555LF:~/Documents/ionic/teste$ ionic cordova plugin add de.appplant.cordova.plugin.local-notification
> cordova plugin add de.appplant.cordova.plugin.local-notification --save
✔ Running command - done!
Installing "de.appplant.cordova.plugin.local-notification" for android
Plugin dependency "cordova-plugin-device@1.1.4" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on android.
Installing "cordova-plugin-app-event" for android
ANDROID_HOME=/opt/android-sdk/
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_dz89hvvt6lwni0ughmk25dddr.run(/home/marcelo/Documents/ionic/teste/platforms/android/build.gradle:137)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:clean
:CordovaLib:clean

BUILD SUCCESSFUL

Total time: 1.414 secs
Subproject Path: CordovaLib
Adding de.appplant.cordova.plugin.local-notification to package.json
Saved plugin info for "de.appplant.cordova.plugin.local-notification" to config.xml
```

> 3) npm install --save @ionic-native/local-notifications

Log:

```

marcelo@marcelo-X555LF:~/Documents/ionic/teste$ npm install --save @ionic-native/local-notifications
teste@0.0.1 /home/marcelo/Documents/ionic/teste
└── @ionic-native/local-notifications@3.12.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/home/marcelo/Documents/ionic/teste/node_modules/etc/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/marcelo/Documents/ionic/teste/node_modules/node_modules/package.json'
```

And finally, without errors:  

> 4) ionic cordova build android

```

marcelo@marcelo-X555LF:~/Documents/ionic/teste$ ionic cordova build androidRunning app-scripts build: --iscordovaserve --externalIpRequired --nobrowser

[20:20:45]  build dev started ... 
[20:20:46]  clean started ... 
[20:20:46]  clean finished in 3 ms 
[20:20:46]  copy started ... 
[20:20:46]  transpile started ... 
[20:20:48]  transpile finished in 2.21 s 
[20:20:48]  preprocess started ... 
[20:20:48]  deeplinks started ... 
[20:20:48]  deeplinks finished in 11 ms 
[20:20:48]  preprocess finished in 13 ms 
[20:20:48]  webpack started ... 
[20:20:48]  copy finished in 2.36 s 
[20:20:55]  webpack finished in 7.21 s 
[20:20:55]  sass started ... 
[20:20:56]  sass finished in 1.12 s 
[20:20:56]  postprocess started ... 
[20:20:56]  postprocess finished in 4 ms 
[20:20:56]  lint started ... 
[20:20:56]  build dev finished in 10.61 s 
> cordova build android
⠇ Running command [20:20:58]  lint finished in 1.98 s 
✔ Running command - done!
ANDROID_HOME=/opt/android-sdk/
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_dz89hvvt6lwni0ughmk25dddr.run(/home/marcelo/Documents/ionic/teste/platforms/android/build.gradle:137)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportCompat2600Alpha1Library
:prepareComAndroidSupportSupportCoreUi2600Alpha1Library
:prepareComAndroidSupportSupportCoreUtils2600Alpha1Library
:prepareComAndroidSupportSupportFragment2600Alpha1Library
:prepareComAndroidSupportSupportMediaCompat2600Alpha1Library
:prepareComAndroidSupportSupportV42600Alpha1Library
:prepareOrgApacheCordovaCordovaLib623DebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:transformClassesWithDexForDebug
:mergeDebugJniLibFolders
:transformNative_libsWithMergeJniLibsForDebug
:processDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug
:validateSigningDebug
:packageDebug
:assembleDebug
:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 14.947 secs
Built the following apk(s): 
	/home/marcelo/Documents/ionic/teste/platforms/android/build/outputs/apk/android-debug.apk
```

**Comment by ben-8409** [comment]
So the workaround is to downgrade npm?

**Comment by marioleed** [comment]
For me it was enough to downgrade npm to `npm i -g npm@4.6.1`. Still using node v8.1.4.

Then i reinstalled everything:

```
ionic cordova platform rm ios android
rm -rf node_modules platforms plugins package-lock.json
ionic cordova platform add ios
ionic cordova platform add android
```

**Comment by marcelodeandrade** [comment]
@ben-8409 @marioleed 

Yep! As @toddmedema in that [issue](https://github.com/ionic-team/ionic-cli/issues/2412). The problem is the old repo whitout the `package.json` file and new versions of `NPM` not know how to solve the pending...

**Comment by marioleed** [comment]
npm@5 has only been trouble since the start, no matter what minor or patch version. Also, `npm -g outdated` did not show outdated global packages (except until 5.2.0). The `package-lock.json`is another source of trouble and I'm not entirely convinced that the self-healing cache is doing good things.

Anyway, for me the problem was with cordova-plugin-dialogs... and then the same with the cordova-plugin-geolocation.

At least it works now =)

**Comment by d3w201** [comment]
that's my output when i try to add this plugin ..

`C:\Users\ISED-4038\workspace\cfportal\src\web\mobile>cordova plugin add --save de.appplant.cordova.plugin.local-notif
ication --verbose
No scripts found for hook "before_plugin_add".
No version specified for de.appplant.cordova.plugin.local-notification, retrieving version from package.json
Calling plugman.fetch on plugin "de.appplant.cordova.plugin.local-notification@^0.8.5"
saving
Running command: cmd "/s /c ""C:\Program Files\nodejs\npm.cmd" install de.appplant.cordova.plugin.local-notification@
^0.8.5 --save""
Command finished with error code 0: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" install de.appplant.cordova.plugin.l
ocal-notification@^0.8.5 --save"
Copying plugin "C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\node_modules\de.appplant.cordova.plugin.local-no
tification" => "C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\plugins\de.appplant.cordova.plugin.local-notific
ation"
Calling plugman.install on plugin "C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\plugins\de.appplant.cordova.p
lugin.local-notification" for platform "android
Installing "de.appplant.cordova.plugin.local-notification" for android
Running command: cmd "/s /c "C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\platforms\android\cordova\version.b
at""
Command finished with error code 0: cmd /s /c "C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\platforms\android
\cordova\version.bat"
Dependencies detected, iterating through them...
Requesting plugin "cordova-plugin-device".
Plugin dependency "cordova-plugin-device" not fetched, retrieving then installing.
saving
Running command: cmd "/s /c ""C:\Program Files\nodejs\npm.cmd" install cordova-plugin-device --save""
Command finished with error code 4294963238: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" install cordova-plugin-devi
ce --save"
Failed to install 'de.appplant.cordova.plugin.local-notification': CordovaError: Failed to fetch plugin cordova-plugi
n-device via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963238 Error output:
npm ERR! addLocal Could not install C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\node_modules\node_modules\co
rdova-plugin-device
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "
install" "cordova-plugin-device" "--save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\node_modules\node_modules\cordova-plugin-device
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\node_mo
dules\node_modules\cordova-plugin-device'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\node_mo
dules\node_modules\cordova-plugin-device'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\node_modules\npm-debug.log
    at C:\Users\ISED-4038\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:205:
33
    at _rejected (C:\Users\ISED-4038\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules
\q\q.js:864:24)
    at C:\Users\ISED-4038\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:890
:30
    at Promise.when (C:\Users\ISED-4038\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modu
les\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\ISED-4038\AppData\Roaming\npm\node_modules\cordova\node_modules\cord
ova-fetch\node_modules\q\q.js:808:41)
    at C:\Users\ISED-4038\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:624
:44
    at runSingle (C:\Users\ISED-4038\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules
\q\q.js:137:13)
    at flush (C:\Users\ISED-4038\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q
.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Error: Failed to fetch plugin cordova-plugin-device via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963238 Error output:
npm ERR! addLocal Could not install C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\node_modules\node_modules\co
rdova-plugin-device
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "
install" "cordova-plugin-device" "--save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\node_modules\node_modules\cordova-plugin-device
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\node_mo
dules\node_modules\cordova-plugin-device'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\node_mo
dules\node_modules\cordova-plugin-device'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ISED-4038\workspace\cfportal\src\web\mobile\node_modules\npm-debug.log`

**Comment by pkitatta** [comment]
Hi, 
Do these solutions work on windows?
I am on windows and this problem has persisted despite trying to downgrade my npm._

**Comment by d3w201** [comment]
ies of course , it work for me in windows 10! i try to downgrade or upgrade but problem was persist until i move the entire folder from my apple machine to my windows ...

**Comment by Saravanan-Duraisamy** [comment]
Hi guys,

I faced the same issue today. My node and update versions were Node: v6.11.0 & NPM: 5.0.4

I updated both Node (downloaded the stable release) and NPM (command:  npm install npm@latest -g).
Now the plugin has been installed successfully using the commands. 

ionic cordova plugin add de.appplant.cordova.plugin.local-notification

npm install --save @ionic-native/local-notifications

After update the versions are

Node: 6.11.1

npm: 5.3.0

I use a Windows 10 machine and I am building a ionic2 app. 

Thought this might help

Cheers,
SD.

**Comment by d3w201** [comment]
have you install cordova-plugin-device?

**Comment by pkitatta** [comment]
For me the solution was between; adding "C:\Windows\System32" to my path variables, deleting the .cordova folder, and deleting android and ionic from the npm. Then I did a fresh installation of ionic-cordova, then 'cordova platform add android'. Everything was fine!

Using windows 7

**Comment by leemiller** [comment]
I had this issue with another NPM package after upgrading to npm 5.3.0 
In my case, the problem was that the package-lock.json file that was created by npm used the existing node_modules folder for the information for the lock file.  
The solution was to delete the package-lock.json, delete node_modules, then reinstall npm modules.

**Comment by sxagan** [comment]
I looked into node_modules and there is a file/symlink of the plugin i wanted to install. once i removed that, i have no problem installing the plugin.

**Comment by swlilike** [comment]
I just used 
`pm2 install pm2-logrotate`
it's OK！
