### ISSUE TITLE
Can sound on local notification be desabled ?

### ISSUE THREAD

**Issue by RizkaOMG** [katzer/cordova-plugin-local-notifications#1330]
## Your Environment

* Plugin version: 0.8.4
* Platform: Android
* OS version: Kitkat
* Device manufacturer / model: Redmi 2
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):6.2.3
* Plugin config
* Ionic Version (if using Ionic) : 1

## Expected Behavior

I'm using ionic1 i want make notification but sound and vivration be disabled

## Actual Behavior
Notification sound and vibration  cannot be disabled

## Steps to Reproduce

i make sound be null

## Context

I'm trying disabled sound and vibration but in my case  if notification show sound and vribation still enable

## Debug logs

Not available.

**Comment by RizkaOMG** [comment]
please ignore the template because I don't have technical issue.

**Comment by katzer** [comment]
@RizkaOMG If it's not a technical issue then you wanna talk with a lawyer or football player instead about your issue? ;)

For example the answer may depend on the plugin version, the OS, the OS version, the cordova version, ...

**Comment by RizkaOMG** [comment]
I already change @katzer , what the problem in  my issue

**Comment by katzer** [comment]
@RizkaOMG The sound is possible to disable, vibration not (yet). I am currently working on the next major release. Maybe that will be able to do at least for Android.

for both iOS and Android you can disable the sound via

```js
cordova.plugins.notification.local.schedule({ sound: null, ... });
```

**Comment by hannut91** [comment]
You have to correct java code.

in builder.java

fix like this

if (sound != null) {
 builder.setSound(sound);
}

=>

if (sound != null) {
            if(!sound.toString().equals(new String(""))){
                builder.setSound(sound);
            }
        }

**Comment by katzer** [comment]
Since v0.9-beta you can do:

```js
cordova.plugins.notification.local.schedule({ sound: false, vibrate: false });
```

**Comment by btxtiger** [comment]
`sound: null` works for me in ionic 3

**Comment by hanibhat** [comment]
I tried both `sound: false` and `sound: null` and neither seems to be working. 
Any advice?

**Comment by templatetuners** [comment]
same here, using cordova 8.1.2 with android and can't make it stop. tried `null`, `false`, nothing works.

**Comment by pedropamn** [comment]
Same here... Someone got the solution?

**Comment by RAbuBaker** [comment]
Same here.. not working with:
    "@angular/cdk": "^9.2.1"
    "@ionic-native/core": "^5.23.0"
    "@ionic/angular": "^5.0.7"
    "cordova-android": "8.1.0"
    "cordova-plugin-local-notification": "^0.9.0-beta.2",

**Comment by fpavlic** [comment]
Any update on this?

**Comment by cryptic-jsdev** [comment]
any updates?

**Comment by kotrakrishna** [comment]
This is not working. Any update please ?

**Comment by Sitronik** [comment]
> This is not working. Any update please ?

You can use my [fork](https://github.com/Sitronik/cordova-plugin-local-notifications2)

Example how to disable default sound of notification: 
cordova.plugins.notification.local.schedule({ sound: false, ... });

**Comment by gvorster** [comment]
> > This is not working. Any update please ?
> 
> You can use my [fork](https://github.com/Sitronik/cordova-plugin-local-notifications2)
> 
> Example how to disable default sound of notification: npm -i cordova-plugin-local-notification2
> 
> cordova.plugins.notification.local.schedule({ sound: false, ... });

I tried this fork and {sound: false} still produces a sound on my Samsung A41, Android 11.

**Comment by pafiore** [comment]
> > > This is not working. Any update please ?
> > 
> > 
> > You can use my [fork](https://github.com/Sitronik/cordova-plugin-local-notifications2)
> > Example how to disable default sound of notification: npm -i cordova-plugin-local-notification2
> > cordova.plugins.notification.local.schedule({ sound: false, ... });
> 
> I tried this fork and {sound: false} still produces a sound on my Samsung A41, Android 11.

Could you resolve this bug in Android 11 or 12?. Thanks.
