### ISSUE TITLE
Not working on iOS9 and iOS10

### ISSUE THREAD

**Issue by jfscoertzen** [katzer/cordova-plugin-local-notifications#1334]
Development environment: macOS Sierra, Xcode 8.3.3
iPhone 6 (Physical Device) iOS 10.3
iPhone 5 (Emulator) iOS 9.3

* Plugin version: 0.8.5
* Platform: iOS
* OS version: 10.3 / 9.3
* Device manufacturer / model: Apple iPhone 6 & 5
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): 
Installed platforms:
  android 6.0.0
  ios 4.3.1
* Plugin config: 
* Ionic Version (if using Ionic): not using

Just some 10cents worth here:
I've been trying to use the notification in iOS for over a day. I've been struggling installing and uninstalling the plugin with different version including the iOS branch, as suggested. I just could not get the notifications to show on iOS.

In the end what I had to do was to install the cordova-plugin-badge and set the badge value using that plugin for the notifications to actually work. About 12 hours of struggling I stumbled on the solution. So just my 10cents worth. Not really an issue but definitely something to note.

**Comment by sampohaavisto** [comment]
Maybe this will help with installation:

https://github.com/katzer/cordova-plugin-local-notifications/issues/1326

I also struggled and it finally seems to work though a little different from what the docs suggest.

```
// When app is installed the first time you must prompt for allowing notifications.
// If denied, this won't prompt anymore and you'll have to show an alert to the user
// for this to be allowed manually allowed through iOS general settings.
// If you run emulator, you can build again from scratch by focusing in the emulator window,
// then from the toolbar select **"iOS Simulator" > "Reset Content and Settings"**

cordova.plugins.notification.local.registerPermission();


// Now prompt if the permissions were denied the first time

cordova.plugins.notification.local.hasPermission(function(isAllowed){
  if (!isAllowed) {
    cordovaDialogs.alert(
      'Please enable notifications in your phone settings!',
      'Permission for notifications is required',
      'I got it'
    );
  }
});

// Scheduling a local notification doesn't seem to work with documented
// .schedule(newNotification) function, .add(newNotification) still works
// but gives depr. notice in the logs

cordova.plugins.notification.local.add({
  id: 1234567890,
  text: "My Notification",
  date: (new Date().getTime()) + 5000 // 5 secs
  data: { someData:"that can be used in the event" }
});


// The events are now in form of

cordova.plugins.notification.local.on('trigger', function(obj, state) {
  console.log(obj); // Get the notification info and data from the object
});
```
Hope this helps, good luck!

**Comment by jfscoertzen** [comment]
Thanks. The only thing is I can't seem to get the app to do the default sounds on iOS. If I open the app's permission settings then it only shows 'Badge' and not 'sound and alert'

**Comment by rwillett** [comment]
We've never got these to work either and have given up.

**Comment by jfscoertzen** [comment]
I fixed it by doing this:

I modified the cordova-plugins-badge (0.8.1) iOS code in my project:

from:
`/**
 * Request permission to show badges.
 */
- (void) request:(CDVInvokedUrlCommand *)command
{
    [self.commandDelegate runInBackground:^{
        UNUserNotificationCenter *center =
        UNUserNotificationCenter.currentNotificationCenter;

        **UNAuthorizationOptions options = UNAuthorizationOptionBadge;**

        [center requestAuthorizationWithOptions:options
                              completionHandler:^(BOOL granted, NSError* e) {
                                  [self sendPluginResult:CDVCommandStatus_OK
                                           messageAsBool:granted
                                              callbackId:command.callbackId];
        }];
    }];
}
`

to
`/**
 * Request permission to show badges.
 */
- (void) request:(CDVInvokedUrlCommand *)command
{
    [self.commandDelegate runInBackground:^{
        UNUserNotificationCenter *center =
        UNUserNotificationCenter.currentNotificationCenter;

        **UNAuthorizationOptions options = UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge;**

        [center requestAuthorizationWithOptions:options
                              completionHandler:^(BOOL granted, NSError* e) {
                                  [self sendPluginResult:CDVCommandStatus_OK
                                           messageAsBool:granted
                                              callbackId:command.callbackId];
        }];
    }];
}
`

thus the badges plugin essentially requests for the notifications permissions.

**Comment by rwillett** [comment]
Just to go back to the original poster.

I finally upgraded my personal phone to iOS 10 today. For various reasons to do with two factor authentication and other apps, I kept it at IOS 8. Whilst we test at IOS 10, I personally have not had our own apps running on my personal iphone directly at IOS10.

Our apps work very well on IOS 10 with local notifications being presented as expected in real world situations. Which is not unexpected but is nice.

We have never used badges as we never got badges to work correctly when we tried to get remote push notifications AND local notifications synchronised. Our systems are difficult and complex and there are good reasons why the badge numbers never worked for us.

We have never got sounds to work on IOS though we never really tried that hard and we don't care. 

We also use Cordova 6 and Ionic 1. I suspect that Ionic 2 has issues and I also suspect that Cordova 7 has issues with this plugin. I do not know and we are not prepared to put the time in to try and work this out. We have a workflow with Cordova 6/Ionic 1 which we are happy with and will stay with that.

We also have IOS10 working just like IOS 8 & 9. We had to write separate functions to handle our local notifications for IOS 8/9 and for IOS 10. This makes our services_notifications.js file the largest file in our system at 3,500 lines.

**Comment by S-unya** [comment]
We have a production app running. Our usecase is that a user can set a regular interval (time of day + repetition) for a notification and the app will also send a reminder notification 1 day after the scheduled notification..

I switched to the iOS10 branch a while back because all notifications broke on iOS10. We have a fairly stable behaviour on our test phones where iOS10 phones activate the scheduled notification but not the reminder notification and most Android phones are activating all notifications (some none). 

That notwithstanding, some of our users are getting completely doolaly notifications, offset by -3.5 hours or days, etc...

So there are definitely some observable, though rarer cases where notifications are:

1. either not being set or not being activated - in the cases where no notifications are recieved or reminder notifications are not recieved
2. Notifications times are going crazy - not sure if this is related to this pull request: [#1306] https://github.com/katzer/cordova-plugin-local-notifications/pull/1306

**Comment by jfscoertzen** [comment]
@S-unya I've noticed that the background processing in iOS is on and off at time. Sometimes it runs when you re-open the App that you have suspended in the background and sometimes it runs by itself. It looks like iOS tries to prioritize the the background processing according to the user's activities and battery monitoring. This is basically the only time any of your javascript can run to do notification logic. This is my case.

**Comment by rwillett** [comment]
IOS10 is super aggressive about suspending your app once it goes into the background. We have seen IOS 8,9 where our app ran for many mins in the background. In IOS10 we assume the moment it is in the background it is really suspended. This means we have nothing that runs in the background in JavaScript, though we do have things that are run as part of GPS background processing. 

However we have not seen any issues with notifications not turning up when they are expected (to within a few seconds).

**Comment by jfscoertzen** [comment]
@rwillett It depends on what your app is doing. I think if you handle notifications separate from other data. In my case I can't do that because I load other entities with the notifications (The extra loading will cause unnecessary overhead).  I'll have to look at push notifications, but I have other priorities.

**Comment by S-unya** [comment]
@jfscoertzen and @rwillett,
Thanks for the replies. We've definitely tried to avoid relying on JavaScript running. When the user sets their preferences, we schedule the notifications. At that point the scheduling is delegated to the notification plugin.

I'm hoping that means that this shouldn't be an issue. Is that a foolish optimism?

**Comment by rwillett** [comment]
@jfscoertzen 

IOS is very limited in what you can do with JavaScript once you are in the background. We use a paid for GPS plugin which allows us to do some very limited processing. IOS 10 is far more aggressive than IOS 8 and 9. Apple is also very strict about this. We also use PushWoosh to handle notifications that come from our backend servers.

@S-unya 

Your model for creating notifications is the right way to do it. Let the app schedule them in the foreground and leave them to run. We schedule notifications all the time and manage the timing ourselves, we only ever use ```at:``` and it works for us.

**Comment by jfscoertzen** [comment]
I got the notifications to fully work without push notifications with the cordova-plugin-background-fetch plugin. Doing background fetches seems to be happening every 15 minutes.
