### ISSUE TITLE
ongoing does not work, still. 

### ISSUE THREAD

**Issue by iamola** [katzer/cordova-plugin-local-notifications#1337]
ongoing attribute does not work. The notification clears when it is tapped rather than staying there.

window.plugin.notification.local.schedule({
ongoing: true,
autoClear: false,
title: "Now Playing:",
text: title,
});

**Comment by iamola** [comment]
Please see, https://github.com/katzer/cordova-plugin-local-notifications/issues/946#issuecomment-213483783 for a suggested fix.

**Comment by rwillett** [comment]
No update for 25 days, no template.

**Comment by iamola** [comment]
Why close it? The developer hasnt done any work on this. This is not standard QE procedure.
