### ISSUE TITLE
Can sound and vibration be disabled ?

### ISSUE THREAD

**Issue by RizkaOMG** [katzer/cordova-plugin-local-notifications#1339]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.8.4
* Platform: Android
* OS version: Kitkat
* Device manufacturer / model: Redmi 2
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):6.2.3
* Plugin config
* Ionic Version (if using Ionic) : 1

## Expected Behavior

I'm using ionic1 i want make notification but sound and vivration be disabled

## Actual Behavior
Notification sound and vibration  cannot be disabled

## Steps to Reproduce

i make sound be null

## Context

I'm trying disabled sound and vibration but in my case  if notification show sound and vribation still enable

## Debug logs

Not available.

**Comment by hannut91** [comment]
You have to correct java code.

in builder.java

fix like this

if (sound != null) {
 builder.setSound(sound);
}
=>

if (sound != null) {
            if(!sound.toString().equals(new String(""))){
                builder.setSound(sound);
            }
        }

**Comment by katzer** [comment]
Yes, with 0.9-beta:

```js
schedule({ sound: false, vibrate: false });
```

**Comment by pedropamn** [comment]
> Yes, with 0.9-beta:
> 
> ```js
> schedule({ sound: false, vibrate: false });
> ```

Not working on Android 8.0...
