### ISSUE TITLE
custom notification layout and control sound open close

### ISSUE THREAD

**Issue by humorfish** [katzer/cordova-plugin-local-notifications#1343]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment
ionic

## Expected Behavior
custom notification layout and control sound open close

## Actual Behavior
can only send text, not Complex layout
sounds can't be closed

**Comment by humorfish** [comment]
notification layout need be custom, it can be used in many situations, thanks for your great job

**Comment by rwillett** [comment]
The notification layout doesn't NEED to be custom, you would like it to be custom, subtle difference :)

**Comment by katzer** [comment]
Custom layout isn't possible yet, but different built-in styles are supported.
