### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by Kale-gz** [katzer/cordova-plugin-local-notifications#1344]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.8.5
* Platform: Windows
* OS version: 10
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): android 6.2.3 ios 4.4.0
* Ionic Version (if using Ionic)  3.4.0

## Actual Behavior

Error during installation.
After sending into command line the command:
`ionic cordova plugin add de.appplant.cordova.plugin.local-notification`

i see in the terminal the following error
`Error: Failed to fetch plugin de.appplant.cordova.plugin.local-notification@^0.8.5 via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! code ENOLOCAL
        npm ERR! Could not install from "cordova-plugin-app-event" as it does not contain a package.json file.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-07-07T12_17_21_054Z-debug.log`

**Comment by albe-rosado** [comment]
same over here!

**Comment by luberlu** [comment]
Hello!

I resolve it by doing that : 

cd node_modules
rm -R cordova-plugin-app-event

next you have to go to package.json and remove cordova-plugin-app-event lines.
Same thing in package-lock.json

Finally you have to delete platforms and re-add : 
- ionic cordova platform rm ios
- ionic cordova platform add ios

**Comment by Kale-gz** [comment]
With the following environment
global packages:

@ionic/cli-utils : 1.4.0
Cordova CLI      : 7.0.1
Ionic CLI        : 3.4.0
local packages:

@ionic/app-scripts              : 1.3.8
@ionic/cli-plugin-cordova       : 1.4.0
@ionic/cli-plugin-ionic-angular : 1.3.1
Cordova Platforms               : android 5.1.1
Ionic Framework                 : ionic-angular 3.4.2
System:

Node       : v6.11.0
OS         : Windows 10
Xcode      : not installed
ios-deploy : not installed
ios-sim    : not installed
npm        : 5.0.4`

I've solved the problem downloading the folder of the plugin cordova-plugin-app-event from [here](https://github.com/katzer/cordova-plugin-app-event) and pasting the folder (renaming to remove the '-master') into node_modules and into plugins. After an:
`npm install --save cordova-plugin-app-event`
The commands for the installation of local-notification, and the plugin itselft, worked like a charm
