### ISSUE TITLE
Event on "click" catch Push Notification click event

### ISSUE THREAD

**Issue by edyrkaj** [katzer/cordova-plugin-local-notifications#1346]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.8.5
* Platform: iOS
* OS version: 10.3.2
* Device manufacturer / model: iPhone / 5s
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): 4.4.0
* Plugin config
* Ionic Version (if using Ionic)  CLI 3.5.0 "ionic-angular": "3.5.0",

## Expected Behavior
Click event should be triggered from Push.on('notification') event callback but it is catched by Local Notification on('click')

## Actual Behavior
On receive of Push Notification is called callback function of Local Notification on click event.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Install Push Plugin for Ionic
  2. Install Local Notification
  3. Add callback function on Push .on('notification', () => {alert('Hello from Push Notification');});
  4. Register Local Notification and put on event .on('click', () => {alert('Hello from Local Notification');});

## Context

I will search for a solution by myself

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment]
The click events dont seem to work. We have never got them to work anyway.

**Comment by andr3medeiros** [comment]
I didn't check why, but it seems that the listeners are not been registered sometimes. My workaround was to unregister and register again before schedule:
```typescript
private registerClickListener() {
    let handler = notification => {
      console.log(notification)

      if(notification.data) {
        let data = JSON.parse(notification.data)

        if(data.type !== 'ITEM_CANCELLED') {
          return
        }

        let params: NavigationExtras = {
          queryParams: {
            date: data.date
          }
        }

        let loading = this.utils.loading('Carregando...')
        this.router.navigate([`admin/calendar/${data.saloonId}`], params)
        .then(() => loading.dismiss())
      }
    }

    this.localNotifications.un('click', handler)
    this.localNotifications.on('click', handler)
  }
```

**Comment by katzer** [comment]
With the newest update master the plugin will not handle delegates triggered by push notifications. That should also fix any interferences with PushNotification Plugins.

**Comment by jimtonique** [comment]
Hi, it seems that, with this latest master version (0.9.0 beta 1) of local notification, Events on push notification are not triggered anymore at all on iOS only. It seems that there are still interferences with Push Plugin.
Thanks by advance.
