### ISSUE TITLE
No notification in iOS10

### ISSUE THREAD

**Issue by remcoNL** [katzer/cordova-plugin-local-notifications#1352]
First of all, this is a great plugin, so thanks for all your work. And it works fine on Android. However, I cannot get it to work on IOS 10 the way I want to. 

I learned from the other threads:
- it will only work as the app is in the background (this is perfect for me)
- it needs an 'at: ' moment
- it needs to be scheduled a few seconds in the future

So here are the details:

* Plugin version:0.8.5
* Platform:iOS
* OS version:10.3.3
* Device manufacturer / model: 6s
* Cordova version : 6.2.0
* Cordova platform version : i develop it with the Monaca platform (Onsen)
* Plugin config: 
* Ionic Version (if using Ionic) NO

## Expected Behavior

Just as on Android it should schedule and display a notification.

## Actual Behavior

Nothing happens

## Steps to Reproduce

var now             = new Date().getTime(),
_2_sec_from_now     = new Date(now + 2*1000);

var pushtext        = obj.get('User')+GlobText[GlobLang]['PushNew'];

cordova.plugins.notification.local.schedule({
id: 10,
title: "Paranta",
text: pushtext,
at: _2_sec_from_now

});  

## Context

The app is a chat app. It should display a notification when other users post and you are are not in the app. This works fine in Android. Also the new messages come in from the database to the iPhone as expected. 

From #1334  I get the impression that iOS10 does not allow to schedule notifications when in the background. Is that correct? (if so, this it is not possible to solve this problem).

## Debug logs

iOS does not display an error, it just ignores the notification schedule.

Tx

**Comment by rwillett** [comment]
1.  You are using an old version of the plugin. There is a specific one for IOS10.

2. You cannot schedule a notification in the background using this plugin. You can receive a notification in the background, but the app has to be in the foreground to schedule it. There is a slight possibility that you might get a few seconds of processing time once you suspend the app to allow scheduling. 

3. IOS10 is very aggressive about suspending your app once it hits the background. Nothing this plugin can do about it. 

4. There are other plugins that *may* or may not allow you some background processing. Its very, very unlikely you will pass Apples guidelines for the App Store (I'd go so far as to say impossible).

**Comment by remcoNL** [comment]
Thanks! So it is impossible then. I'll have to try 'real' push notifications but those seem much harder. Anyway, thanks again.

**Comment by rwillett** [comment]
If you are wanting notifications to appear when the app is in the background based on events that occur when the app is in the background, its tricky but not impossible. 

We use a paid for plugin that does all the GPS work for us. That has a mode that allows us to schedule a notification when the app is in the background AND it confirms to Apples guidelines. However its not cheap, though it is excellent and significantly better than the free GPS plugins you find around.

We also use Push Notifications, we use PushWoosh and find them pretty easy to use and pretty responsive to help requests. We have also tried Amazon (junk), Urban Airship (odd interface), AeroGear (not quite right for us), free ones and one or two others before settling on PushWoosh. YMMV.

**Comment by remcoNL** [comment]
haha, good info. Thanks. I work in Parse SDK  so i'll look into the combination.
