### ISSUE TITLE
UI API called on a background thread: -[UIApplication applicationState]

### ISSUE THREAD

**Issue by craig-at-rsg** [katzer/cordova-plugin-local-notifications#1353]
## Summary

XCode 9 checks if certain code that can't be called for background threads is called from background threads, and this plugin has some of that. 

## Your Environment

* Plugin version: 0.8.5
* Platform: iOS
* OS version: 11 preview
* Device manufacturer / model: Apple
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): ios 4.4.0
* Plugin config ??
* Ionic Version (if using Ionic) 1.1.1

## Expected Behavior
No error message

## Actual Behavior
XCode 9 Beta reports the issue:
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 416, TID: 29847, Thread name: (none), Queue name: com.apple.NSXPCConnection.m-user.com.apple.usernotifications.usernotificationservice, QoS: 0

It looks like this is coming from the [Main Thread Checker](https://developer.apple.com/documentation/code_diagnostics/main_thread_checker), and the solution is to wrap the code in 

```
dispatch_async(dispatch_get_main_queue(), ^{
 // add UI related changes here
    });
```

## Steps to Reproduce
Idk how to run on a bg thread, but calling schedule() from a bg thread causes this issue.
## Context
Schedule  a notification
## Debug logs

Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 416, TID: 29847, Thread name: (none), Queue name: com.apple.NSXPCConnection.m-user.com.apple.usernotifications.usernotificationservice, QoS: 0
Backtrace:
4   rMove                               0x0000000102052c90 -[APPLocalNotification applicationState] + 60
5   rMove                               0x0000000102052f54 -[APPLocalNotification fireEvent:notification:] + 108
6   rMove                               0x0000000102052284 __45-[APPLocalNotification scheduleNotification:]_block_invoke + 148
7   UserNotifications                   0x000000018b6b1dc8 <redacted> + 256
8   CoreFoundation                      0x0000000181ce66d0 <redacted> + 144
9   CoreFoundation                      0x0000000181bc7f18 <redacted> + 292
10  Foundation                          0x00000001827e0690 <redacted> + 20
11  Foundation                          0x00000001827e03bc <redacted> + 768
12  Foundation                          0x00000001827e47ec <redacted> + 520
13  libxpc.dylib                        0x0000000181946b0c <redacted> + 60
14  libxpc.dylib                        0x0000000181946a48 <redacted> + 88
15  libdispatch.dylib                   0x0000000103b620c4 _dispatch_client_callout3 + 16
16  libdispatch.dylib                   0x0000000103b7bf38 _dispatch_mach_msg_async_reply_invoke + 348
17  libdispatch.dylib                   0x0000000103b701a0 _dispatch_queue_serial_drain + 212
18  libdispatch.dylib                   0x0000000103b64e30 _dispatch_queue_invoke + 332
19  libdispatch.dylib                   0x0000000103b7135c _dispatch_root_queue_drain_deferred_wlh + 424
20  libdispatch.dylib                   0x0000000103b78298 _dispatch_workloop_worker_thread + 652
21  libsystem_pthread.dylib             0x000000018190c24c _pthread_wqthread + 932
22  libsystem_pthread.dylib             0x000000018190be9c start_wqthread + 4

**Comment by joewoodhouse** [comment]
@katzer any update on this? Plugin seems totally broken to me.

**Comment by t2wu** [comment]
@joewoodhouse I cannot get this branch to work. But instead of the master branch, I switched to the branch named "x" which support iOS 11.

**Comment by joewoodhouse** [comment]
@t2wu Yep switching to branch X worked for me too, though I had to apply a few fixes (like my PR)

**Comment by katzer** [comment]
That has been fixed. Its in master now.
