### ISSUE TITLE
persistent notifications not working, option `ongoing` has no effect

### ISSUE THREAD

**Issue by znegva** [katzer/cordova-plugin-local-notifications#1354]
## Your Environment

* Plugin version: 0.8.5
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: Motorola Moto G2
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):  android 6.2.3
* Plugin config
```
		//ionic-native style
		this.localNotifications.schedule({
			id: 666,
			text: 'Single notification using ionic native',
			ongoing: true
		});

		//testing cordova directly, since the @ionic-native interface does not know about 'autoCancel'
		cordova.plugins.notification.local.schedule({
			id: 667,
			text: 'Single notification using cordova directly',
			ongoing: true,
			autoCancel: false
		});
```
* Ionic Version (if using Ionic): 3.4.0

## Expected Behavior
a persistent notification which stays even if tapped on

## Actual Behavior
the notification disappears when tapped on

## Steps to Reproduce
nothing special, just install and setup plugin, build for android and run

## Context
I expected a persistent notification which stays even if tapped on - I hope this is what the `ongoing` option was created for :-) 
Patching the file `de\appplant\cordova\plugin\notification\ClickActivity.java`
by adding `if (notification.getOptions().isOngoing()) return;` right after `launchApp();` as described [here](https://github.com/katzer/cordova-plugin-local-notifications/issues/946#issuecomment-213483783) fixes the issue (can be done for testing inside of `platforms/android/src` to make cordova use it)
But it would be nice to have it working in the official release ;-)
And since I am uncertain of any possible sideeffects I dont want to fill a pull request, someone with more insight in the whole thing should have a look first.

## Debug logs
no special logs were created

**Comment by olastor** [comment]
+1 Having similar issue

**Comment by katzer** [comment]
Please use with the latest master (0.9-beta) and re-open if its still an issue.

P.S. `ongoing` has been renamed to `sticky`.
