### ISSUE TITLE
Plugin Is not working on IOS

### ISSUE THREAD

**Issue by shibins** [katzer/cordova-plugin-local-notifications#1355]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:0.8.5
* Platform:IOS
* OS version:10.12.4
* Device manufacturer / model:Apple/ipHone
* Cordova version (```cordova -v```):6.5.0
* Cordova platform version (```cordova platform ls```):ios 4.3.1
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

I was trying to run Local Notification  on IOS 10. and should get a notification 
 
## Actual Behavior
  Local Notification  is not getting launched

_Tell us what happens instead_

No Local Notification 

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1.Create APP
  2. Add Local Notification Plugin 
  3. Add Code
        
        cordova.plugins.notification.local.schedule({
             id: 1,
             text: 'Scheduled every minute',
             every: 'minute',
             icon: 'res://icon',
             smallIcon: 'res://ic_popup_sync'
         });
  4. ....

## Context

_What were you trying to do?_

Just schedule Local Notification 

## Debug logs

_Include iOS / Android logs_

017-07-30 22:52:16.054183-0400 XXXX[39256:7609035] This app has attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSLocationWhenInUseUsageDescription key with a string value explaining to the user how the app uses this data
2017-07-30 22:52:16.300424-0400 XXXX[39256:7609035] CDVPlugin class APPLocalNotification (pluginName: LocalNotification) does not exist.
2017-07-30 22:52:16.300589-0400 XXXX[39256:7609035] ERROR: Plugin 'LocalNotification' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2017-07-30 22:52:16.300701-0400 XXXX[39256:7609035] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["INVALID","LocalNotification","deviceready",[]]
2017-07-30 22:52:16.351416-0400 XXXX[39256:7609035] CDVPlugin class APPLocalNotification (pluginName: LocalNotification) does not exist.
2017-07-30 22:52:16.351461-0400 XXXX[39256:7609035] ERROR: Plugin 'LocalNotification' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2017-07-30 22:52:16.351484-0400 XXXX[39256:7609035] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["LocalNotification32903438","LocalNotification","registerPermission",[]]

**Comment by rwillett** [comment]
It doesn't look like you installed the plugin correctly. How did you install it?

Also you are using the wrong plugin, use the IOS10 version.

Your code is incorrect, you need an ```at:``` in it, the plugin doesn't support ```at:``` and ```every:``` anyway. 

Your icon statement is also wrong, don't use res:

You have lots of issues, but the first one is how you installed the plugin.

**Comment by shibins** [comment]
cordova plugin add de.appplant.cordova.plugin.local-notification
Fetching plugin "de.appplant.cordova.plugin.local-notification" via npm
Installing "de.appplant.cordova.plugin.local-notification" for browser
Dependent plugin "cordova-plugin-device" already installed on browser.
Fetching plugin "cordova-plugin-app-event" via npm
Installing "cordova-plugin-app-event" for browser
Installing "de.appplant.cordova.plugin.local-notification" for ios
Dependent plugin "cordova-plugin-device" already installed on ios.
Installing "cordova-plugin-app-event" for ios

This is the command I used 


Also changed code to

        
        cordova.plugins.notification.local.schedule({
             id: 1,
             text: 'Scheduled every minute',
             every: 'minute'
         });

        cordova.plugins.notification.local.on('trigger', function (notification) {
            alert('triggered: ' + notification.id);
        }, this);

        cordova.plugins.notification.local.on('click', function (notification) {
            alert('clicked: ' + notification.id);
        }, this);

**Comment by rwillett** [comment]
1. You need the ```at:```. Dump the ```every:```.

2. Put the object in .schedule in an array e.g.

```
[{
         id: 1,
         text: 'Scheduled every minute',
         every: 'minute' <--- Remove this and replace with an at: in the future
     }]
```

3. Trigger events don't work

4. Do you still get an error in your logs.

5. Have you installed the right version of the plugin?

**Comment by shibins** [comment]
4. Yes nothing has changed my prior install
5.How do I check if I have correct version of the plugin because  I run "cordova plugin add de.appplant.cordova.plugin.local-notification" which should bring me latest version . Should I be installing the correct version

**Comment by rwillett** [comment]
You need the IOS10 branch.

**Comment by shibins** [comment]
Sorry Any pointer  for how to use iOS10 Branch 

Also "Trigger events don't work"  is it a plugin issue or IOS issue

**Comment by shibins** [comment]
In was able to get the notification plugin working  by installing from the local branch .

**Comment by shibins** [comment]
The trigger is also working if the app is foreground . but not getting the events if its background

**Comment by shibins** [comment]
I see unusernotificationcenterdelegate https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate
 has two events willPresent  & didReceive these both are called when the application is in foreground or background 

But is there a way I can capture the Local   Notification event delivery even if the app is not running

**Comment by katzer** [comment]
Please use the latest master branch as it not serves 0.9-beta with proper support for iOS10-11
