### ISSUE TITLE
Failed to install 'de.appplant.cordova.plugin.local-notification'

### ISSUE THREAD

**Issue by noman0911** [katzer/cordova-plugin-local-notifications#1357]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue. Failed to install 'de.appplant.cordova.plugin.local-notification'- my internet connection is working fine and nothing is wrong in plugin spec

## Your Environment

* Plugin version: latest
* Platform: ionic
* OS version: Windows 10
* Device manufacturer / model: 
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)
1
## Expected Behavior

_Tell us what should happen_

## Actual Behavior

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by Elevista** [comment]
@katzer I have this problem too

> Elevista-ui-MacBook-Pro:intra-app elevista$ cordova plugin add cordova-plugin-local-notifications
Installing "de.appplant.cordova.plugin.local-notification" for android
Failed to install 'de.appplant.cordova.plugin.local-notification': CordovaError: Failed to fetch plugin org.apache.cordova.device via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found: org.apache.cordova.device@latest
...
Error: Failed to fetch plugin org.apache.cordova.device via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.

**Comment by skylarmt** [comment]
+1

**Comment by rwillett** [comment]
@skylarmt 

If you have a problem, raise a new issue. Simply saying +1 says nothing about what your problem is.

**Comment by Seraph1322** [comment]
+1
