### ISSUE TITLE
Update in local notifications not working. It is throwing an issue "'getAll' is undefined" in LocalNotificationCore.js 

### ISSUE THREAD

**Issue by BhargavaNandan** [katzer/cordova-plugin-local-notifications#1358]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: v 0.8.4
* Platform: windows
* OS version: Windows 10 
* Device manufacturer / model: 
* Cordova version (```cordova -v```):  version 6.1.1
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

_Tell us what should happen_

it shluld update the notification based on the given id

_Tell us what happens instead_

it is throwing an error getAll of undefined in LocalNotificationCore.js 

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment]
Fill the template in correctly. We have no idea if this is Android or IOS, which version of them etc etc. There's no code examples either.

**Comment by BhargavaNandan** [comment]
im trying for windows devices. and below is the code 
 cordova.plugins.notification.local.update({
                id: 10910,
                text: "Updated Notification 1",
            });
 i've created a notification 
cordova.plugins.notification.local.schedule({
                id: 10910,
                title: "Hybrid App 1",
                text: "Test Data 1",
                firstAt: date,
                repeat: "minutely",
                json: {
                    url: "John",
                    age: 30,
                    cars: ["Ford", "BMW", "Fiat","Suzuki"]
                }
            });
Now i'm updating the text of that notification but it is throwing in exception in LocalNotificationCore.js file and below the function where it is throwing an exception like getAll() is undefined.
update: function (notifications) {
        for (var i = 0; i < notifications.length; i++) {
            var updates = notifications[i],
                options = getAll(updates.id || '0')[0];

            this.updateLocalNotification(options, updates);
            this.fireEvent('update', options);
        }
    },
