### ISSUE TITLE
Example Doesn't Work in Phonegap

### ISSUE THREAD

**Issue by TomAshley303** [katzer/cordova-plugin-local-notifications#1359]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
Nothing in example works.

## Your Environment

* Plugin version:

1.1.0 (Example app)

* Platform: Android
* OS version: 5.0
* Device manufacturer / model: Samsung Galaxy S5
* Cordova version (```cordova -v```): Phonegap 6.5.2
* Cordova platform version (```cordova platform ls```):

trioxin@Extremis:~/code/phonegap/cordova-plugin-local-notifications-example$ phonegap platform ls
Installed platforms:
  android 5.1.1
  browser 4.1.0
  ios 4.1.1
  windows 4.2.0
Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  firefoxos ~3.6.3
  ubuntu ~4.3.4
  webos ~3.7.0

* Plugin config

example app

* Ionic Version (if using Ionic)
NO
## Expected Behavior
Expected example app to do something or anything
_Tell us what should happen_
anything
## Actual Behavior
nothing
_Tell us what happens instead_
nothing
## Steps to Reproduce
run example app using: phonegap serve
_Reproduce this issue; include code to reproduce, if relevant_
example app

## Context
what?
_What were you trying to do?_
use the example app.
## Debug logs

```
phonegap serve
[phonegap] starting app server...
[phonegap] listening on 192.168.1.70:3000
[phonegap] listening on 10.4.2.185:3000
[phonegap] 
[phonegap] ctrl-c to stop the server
[phonegap] 
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=Lsrqo1x
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=Lsrqo2q&sid=3W1QJgad2BHCc1bRAAAA
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=Lsrqo3C&sid=3W1QJgad2BHCc1bRAAAA
[phonegap] [console.warn] Content Security Policy has been added: <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;img-src * 'self' data: content:;style-src 'self' 'unsafe-inline' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
[phonegap] 200 /__api__/appzip
[phonegap] [console.warn] Content Security Policy has been added: <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;img-src * 'self' data: content:;style-src 'self' 'unsafe-inline' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
[phonegap] 200 /__api__/appzip
[phonegap] 200 /socket.io/socket.io.js
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=LsrqqiK
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=Lsrqqje&sid=9kMF6nzCVNvfM7d5AAAB
[phonegap] [console.log] Received Event: deviceready
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=Lsrqqkz&sid=9kMF6nzCVNvfM7d5AAAB
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=Lsrqqkh&sid=9kMF6nzCVNvfM7d5AAAB
_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

```

**Comment by jruizsulime** [comment]
Installing demo in mobile, doen't work in iOS 10, except the 5 seconds delayed or the instant unique alert.

**Comment by katzer** [comment]
Please use 0.9-beta (master branch now)
