### ISSUE TITLE
Notification not working in ios 

### ISSUE THREAD

**Issue by ReemaBegum** [katzer/cordova-plugin-local-notifications#1361]
Notification are not getting in ios cordova below is my code. Any suggestion plz ?
cordova.plugins.notification.local.schedule({
                                                        id: 1,
                                                        title: 'Silent 911 Notication',
                                                        message: 'Police have arrived',
                                                        sound: "file://beep.wav"
                                                    });

**Comment by ReemaBegum** [comment]
Any suggestion plz I have project release .

**Comment by Tawpie** [comment]
(filling out the template is step 1…)

but you need to schedule a time for the notification using the ‘at’ property.

**Comment by ReemaBegum** [comment]
Is "cordova.plugins.notification" will work if app is in foreground or locked ?
