### ISSUE TITLE
Unknown property: icon

### ISSUE THREAD

**Issue by anatoliyB** [katzer/cordova-plugin-local-notifications#1363]
## My Environment

* Plugin version: 0.8.5-dev
* Platform: Mac OS 
* OS version: 10.12.4
* Device manufacturer / model: iPhone 5s
* Cordova version (```cordova -v```): 6.4.0
* Cordova platform version (```cordova platform ls```):   android 6.0.0  ios 4.3.1
* Plugin config
* Ionic Version (if using Ionic): 1.2.4

## Expected Behavior

Set custom icon for local notification and see it in notification when notification pops up.

## Actual Behavior

When icon property is set in notification object it provides error Unknown property: icon and notification pops up with an app standard icon instead of custom icon specified in the code.

## Steps to Reproduce

execute this code:
cordova.plugins.notification.local.schedule([{
    id: 1,
    title: "Local Notification Example",
    text: "Multi Notification 1",
    icon: "http://sciactive.com/pnotify/includes/github-icon.png"
}]);

**Comment by anatoliyB** [comment]
Hello support, it's been 7 days since i've created this issue.
Are there any news?

**Comment by Tawpie** [comment]
anatolyB: you can’t get an icon image from the web, it has to be included in your app bundle. Search here for issues about where to put the image and exactly how to prepare the icon image—Android in particular has exacting requirements.

**Comment by Deimian666** [comment]
We use a local resource and it worked like a charm.
icon: "res://notification_icon"

**Comment by MiguelSyll** [comment]
It does not work for me in IOS. In Android it works. I tried using:

icon: 'http://3.bp.blogspot.com/-Qdsy-GpempY/UU_BN9LTqSI/AAAAAAAAAMA/LkwLW2yNBJ4/s1600/supersu.png',
            smallIcon: 'res://cordova',

I tried with icon: "res://notification_icon" with .png also. But it does not work

Is there a solution?

Thank you!

**Comment by katzer** [comment]
The `icon` property is Android+Windows specific. iOS does not support that.
