### ISSUE TITLE
Unable to install a plugin without downgrading npm to version 4.6.1 ( had 5.3.0 )

### ISSUE THREAD

**Issue by vhb56** [katzer/cordova-plugin-local-notifications#1364]
Sorry, no time for template, already described & filled but for ionic, they said to open issue here instead.

plugin version: 0.8.5

device doesn't matter, error occurs while installing plugin.

https://github.com/ionic-team/ionic/issues/12662

**Comment by marwarn** [comment]
the same issue with npm version:5.3.0

**Comment by katzer** [comment]
Try to add the plugin with the `--nofetch` flag.
