### ISSUE TITLE
iOS notifications 45 minutes too late, Android on time

### ISSUE THREAD

**Issue by Ejam1986** [katzer/cordova-plugin-local-notifications#1365]
Hi,

I'm using this plugin to set a local notification, which gives a message a couple of times a day to fill in a questionnaire. The notification on an Android device is always on time, when using an iPad or iPhone it is always 48 minutes too late. The notification is set for 9.30 a.m. and on all the iOS devices it is shown on 10.18 a.m. How is this possible?

My version the plugin is 0.8.4, the platform is Android and iOS.
The app uses cordova 6.4.0, angular and no ionic.

We tested the app on:
- Sony Xperia Z3 compact / Android 6.0
- Huawei P10 / Android 7.0
- multiple iPad's
- iPhone 5 / iOS 10

This is the code we are using for the plugin:

```
var scheduleDefintions  = [];
        _.each(alarms, function(notification) {
          scheduleDefintions.push({
              id: notification.id,
              every: "day",
              title: notification.title,
              text: notification.text,
              icon: 'icon_notification.png',
              smallIcon: 'icon_notification.png',
              at: new Date(parseInt(notification.time) * 1000),
          });
        });
```

```
 if (window.cordova && window.cordova.plugins.notification) {
          window.cordova.plugins.notification.local.cancelAll();
          window.cordova.plugins.notification.local.schedule(scheduleDefintions);
        }

```
The notification.time is a Unix TimeStamp from the server converted to the local time zone (UTC/GMT) and set in milliseconds for use in JavaScript.

Hopefully somebody can help.
If you need other information then listed above, please let me know.

**Comment by Tawpie** [comment]
That’s pretty odd… the only think I can guess is that there’s an OS timing collision happening between the cancelAll and schedule calls. I put the schedule function call as a callback from cancelAll, that way the OS is done with the cancel before it is asked to reschedule new notifications.

`if (window.cordova && window.cordova.plugins.notification) {
	window.cordova.plugins.notification.local.cancelAll(function thenReschedule() {
		window.cordova.plugins.notification.local.schedule(scheduleDefinitions);
	});
}`

**Comment by rwillett** [comment]
@tawpie, oddly enough we do exactly the same. Perhaps thats the secret.

**Comment by Tawpie** [comment]
Putting the schedule function in the callback of cancelAll was necessary because Windows Phone took literally 5-10 _seconds_ to cancel notifications and we definitely got into trouble. In retrospect, it's generically unwise to rapid fire commands to the OS—the OS may handle them gracefully but it's an unnecessary risk.

**Comment by rwillett** [comment]
Closed as no updated from origonal poster in three weeks
