### ISSUE TITLE
Instalation error 

### ISSUE THREAD

**Issue by junivillegas** [katzer/cordova-plugin-local-notifications#1367]
When try to install the plugin with 
 - cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
 - cordova plugin add de.appplant.cordova.plugin.local-notification@0.8.1
 - cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.8.1
(all) i have this error 
Error: Failed to fetch plugin https://github.com/katzer/cordova-plugin-local-notifications via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

## Your Environment

* Plugin version: 0.8
* Platform: Android / OIS
* OS version: Last
* Device manufacturer / model: N/A
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Error to install 
Error: Failed to fetch plugin https://github.com/katzer/cordova-plugin-local-notifications via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

**Comment by fizdalf** [comment]
I have a similar problem but it's caused by the dependency on cordova-plugin-app-event

**Comment by crlang44** [comment]
I have this same issue, I will update if I resolve it.

**Comment by rejhgadellaabsl** [comment]
It looks like the Katzer solved the issue for cordova-plugin-app-event but I'm still getting the error for local-notifications. I guess it's still referencing the old version in its dependencies?

**Comment by LtotheWT** [comment]
i got the same issue too.

**Comment by marwarn** [comment]
the same error, npm version:5.3.0

**Comment by katzer** [comment]
OK, I will update the package.json here as well

**Comment by candyapplab** [comment]
Same problem cordova 7 npm 5.3.0 mac

**Comment by katzer** [comment]
Its best to add the plugin with the `--nofetch` flag.
