### ISSUE TITLE
No popup notification displayed (Notification is hidden in status bar)

### ISSUE THREAD

**Issue by d1mroberge** [katzer/cordova-plugin-local-notifications#1368]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 4.1.0
* Platform: Android
* OS version: Android 7.0
* Device manufacturer / model: Samsung s7 / Moto g 
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): Android 6.2.3
* Plugin config ionic? 
* Ionic Version (if using Ionic) 3.6.0 

## Expected Behavior

_Tell us what should happen_
When app is in the background, an alert banner appears (like a popup notification) that when selected takes you to the app. 

## Actual Behavior

_Tell us what happens instead_
When app is in the background, we receive an alert, but all that appears is an icon in the status bar, and no visible notification alert. 

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ... close app 
  2. ... set off the scheduled notification 
  3. ... receive badge icon and no banner alert 
  4. ....

## Context

_What were you trying to do?_ 
alert users that something has happened 

## Debug logs 

_Include iOS / Android logs_

N/A 

  * ios XCode logs
  * Android: $ adb logcat

**Comment by stevesum** [comment]
Same happens for us. The system notification is not shown, but the trigger event is fired in the application while it runs in the background.
I tried to use the background-mode-plugin also it that solve this problem, but with enabled background mode is no difference.

**Comment by stevesum** [comment]
I discovered that for us the problem was because on the 'trigger' event we recalculate/re-schedule the notifications and clear the 'old' ones because we have to keep always the next 50 notifications keep alive.

But on android the 'trigger' event is fired in the application while the app is in background mode, what caused the actually triggered notification was cleared by the recalculate of the notifications. Therefore in the notification center it showed, but it was removed also in same time.

After I modified our 'trigger' listener to watch the status also, it works fine for us.

**Comment by jaimeyu** [comment]
@stevesum Thanks for the feedback, I'm going to try this soon and hopefully this solves our problem.

**Comment by katzer** [comment]
Please use latest master branch and set priority to greater than zero.

```js
schedule({ ..., priority: 1 })
```

**Comment by jaimeyu** [comment]
Just FYI for future readers, the fix looks to be in commits: [d85f6af16b41b29d3501b3bfb1c5729a2a795222](https://github.com/katzer/cordova-plugin-local-notifications/commit/d85f6af16b41b29d3501b3bfb1c5729a2a795222) & [d9bb523c6d5e7dca851adf93d873254e1854f317](https://github.com/katzer/cordova-plugin-local-notifications/commit/d9bb523c6d5e7dca851adf93d873254e1854f317)

**Comment by prateekchitransh1907** [comment]
Still facing the same issue for beta 3. only getting the icon in notification tray but no banner.
