### ISSUE TITLE
does "every" key works on IOS10??

### ISSUE THREAD

**Issue by fizdalf** [katzer/cordova-plugin-local-notifications#1369]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
I'm not trying to report an issue, I'm just trying to know if I can schedule notifications in IOS10 with the "every" key to make it re-schedule itself. 

The documentation isn't clear about it.

I've downloaded the sample app, changed the plugin to use cordova-plugin-local-notifications-ios10, and it works for all of the other except for the one that says "Every Min"

**Comment by awstudio-paris** [comment]
Hello, 
We need the same information :), is that a way to have the same feature ? Is the "Every" coming back in the next version ?

Thanks

**Comment by katzer** [comment]
Please see the README. The interface looks different now with 0.9-beta
