### ISSUE TITLE
Notifications scheduled but not fired on iOS 11 beta 7?

### ISSUE THREAD

**Issue by SatguruSharanamMam** [katzer/cordova-plugin-local-notifications#1370]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
Notifications are not fired on iOS 11's latest beta (beta 7 at this time.)

## Your Environment

* Plugin version: 0.8.4
* Platform: iOS 11 beta 7 
* OS version: Mac OS Sierra 10.12.6
* Device manufacturer / model: iOS 11 beta simulator
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): cordova ios 4.3.1
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior
Scheduled notification should be fired on iOS 11 beta  as well.

## Actual Behavior
While notifications are successfully scheduled (when the app is in foreground of course), they don't seem to be fired at the scheduled time.

## Steps to Reproduce
Simply schedule a notification using any sample while running on the latest iOS 11 beta. Same code works fine on iOS 10, iOS 9 and iOS 8.

## Context
Schedule notifications to remind for specific calendar dates and times.
## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by micrdy** [comment]
Happens to me as well

**Comment by raoul14** [comment]
Can anyone confirm this issue ? I'm still using this plugin in ios 10

**Comment by shlomnissan** [comment]
Local notifications seem to work fine on iOS11 _beta 10_

**Comment by katzer** [comment]
@SatguruSharanamMam The `x` branch (0.9-beta) does support iOS10 and iOS11. However its under development and the docs aren't up-to-date.

**Comment by hessius** [comment]
@katzer has the api changed in such a way that it is not backwards compatible?

**Comment by hessius** [comment]
Reading the code it would seem that the "at" property should be moved inside an object "trigger". i.e. using the example in the brief overview

`cordova.plugins.notification.local.schedule({
        id: 110,
        title: "Meeting in 15 minutes!",
        text: "Jour fixe Produktionsbesprechung",
        trigger: {at: tomorrow_at_8_45_am},
        data: { meetingId:"#123FG8" }
    });`

**Comment by katzer** [comment]
@hessius There's the new `trigger` property as you have notices already, however the "old" way is still supported.

I haven't tested what will happened if a notification scheduled with v0.8 triggers when using v0.9

**Comment by hessius** [comment]
@Katzer Using the trigger property with x branch of the plugin on iOS 11 GM I'm still getting scheduled but not fired notifications?

**Comment by hessius** [comment]
Sorry! Not complete bug above; Also seeing instant triggering of a bunch of notifications (both items that should've passed and should be scheduled in the future)

**Comment by hessius** [comment]
For anyone else experiencing this, while not a fix I've found a plugin that provides the basic functionality of this plugin (but doesn't cover everything) https://github.com/DavidBriglio/cordova-ios10-simple-notification which I'm using in the meantime :)

**Comment by katzer** [comment]
@hessius Please post code snippets to demonstrate reproducible issues.

**Comment by KristjanHjartarson** [comment]
@katzer How is 0.9 coming along? Any news?

@hessius I am curious to know if you are still able to use the DavidBriglio plug in as a temporary substitute.

**Comment by hessius** [comment]
Sorry @katzer I missed your comment. I’ll see if I can get a usable snippet, I’m storing a db of notifications in an array and fetching them one by one, thus my code wouldn’t be instantly testable without some work. But the code samples in the repo showed the same errors for me. 

@kristjanhjartarson

**Comment by KristjanHjartarson** [comment]
@hessius 
Still wondering. Have you been able to solve the instant triggering of notifications issue?

Cheers, 
Kristján

**Comment by hessius** [comment]
Still using the other plugin

**Comment by katzer** [comment]
Please use the latest master branch and see the README. It should work fine, otherwise re-open the ticket please.

**Comment by SatguruSharanamMam** [comment]
Thanks. Will give it a shot. What should be the minimum version of iOS and Android for using the latest plugin? Is iOS 8 supported or only iOS 10+?

**Comment by uandme72** [comment]
Since iOS 11, Apple has disabled scheduled fetch and notifications for favorited folders and sub folders for non-push IMAP mail accounts in the native mail app of iOS.
This fetch used to happen in iOS 10.3.3 without any problem.

**Comment by katzer** [comment]
@SatguruSharanamMam 

> Is iOS 8 supported or only iOS 10+?

iOS 10+

**Comment by katzer** [comment]
@uandme72 Sorry, but I don't get what you mean. Is that related to this issue?

**Comment by uandme72** [comment]
May not be directly related. Just wanted to flag it. 
		
		

		Get Outlook for iOS
	




On Tue, Nov 14, 2017 at 4:30 PM +0530, "Sebastián Katzer" <notifications@github.com> wrote:












@uandme72 Sorry, but I don't get what you mean. Is that related to this issue?

**Comment by mkn20** [comment]
It is a great plugin. Thank you very much! With 0.9 beta it looks like only iOS 10 and above is supported. Since the latest cordova ios supports iOS 9 and above, can iOS 9 be supported too? Also, with the beta, what should be the minimum version of Android? Thanks again!

**Comment by katzer** [comment]
iOS9 is not supported and wont. iOS10+ got a new user-notification framework.
For Android you need SDK 26+ to compile the app and Android 6+ is the runtime minimum.

**Comment by katzer** [comment]
Possibly that I will decrease to Android 5+, however full support only for Android 6+

**Comment by mkn20** [comment]
Does latest master support Android 5.x.x now? Also, is it correct rescheduling a notification (for specific date and time in future) with the same ID will overwrite the earlier scheduled notification for **that** ID?

**Comment by katzer** [comment]
@mkn20 The master supports Android 4.4+

Some query methods might return wrong results on Android 4-5 but scheduling notifications however should work as expected.

---

> Also, is it correct rescheduling a notification (for specific date and time in future) with the same ID will overwrite the earlier scheduled notification for that ID?

Yes
