### ISSUE TITLE
foreground notifications

### ISSUE THREAD

**Issue by ThomasKientz** [katzer/cordova-plugin-local-notifications#1371]
I was previously using the plugin, and notifications was showing up when app was in foreground. 

I had to reinstalled all my plugins, and now notifications don't show up anymore when app is in foreground (only in background).

Am I missing something ?

## Your Environment

* Plugin version: 0.8.5 
* Platform: iOS 
* OS version: 10.3.2
* Device manufacturer / model: iPhoneSE, real physical device
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): ios 4.4.0
* Plugin config
* Ionic Version (if using Ionic) : 3.6.0

## Expected Behavior

Notifications show up when app is in foreground with iOS 

## Actual Behavior

Notifications only showed up when app is in background with iOS

**Comment by tattivitorino** [comment]
Thomas, as far as i Know, according to my own implementations, Local Notifications do not show up when app is in the foreground! you need to present a Toast, or alert or a dialog in the trigger handler!

**Comment by ThomasKientz** [comment]
@tattivitorino thanks for the reply. Weird ! From the docs, you are totally right, its the standard behavior, but I've review my code and redownload an older build on testflight, notifications are showing up in foreground ! Don't know how its possible, I guess it may be my APNs certificates or something related to the config of pushs. Its the only I worked on since ! 

So there is no way to show a native notification in foreground ? We have to use toast or whatever ?

**Comment by ThomasKientz** [comment]
Foregrounds notifications are back.

Notifications were not showing up cause of https://github.com/katzer/cordova-plugin-local-notifications/issues/1373

**Comment by katzer** [comment]
Please use the master branch now. It supports foreground notifications. For Android, you need to set the priority to greater than zero.

**Comment by lebaphi** [comment]
I'm using the local-notification version `0.9.0-beta.3` but it seems does not show the notification when the app is in the foreground. I'm using the `"cordova-plugin-firebasex": "^12.1.0"`.
