### ISSUE TITLE
Not possible to install the plugin

### ISSUE THREAD

**Issue by candyapplab** [katzer/cordova-plugin-local-notifications#1374]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:0.8.5
* Platform: mac npm 5.3.0
* OS version: Mac os el capitan
* Device manufacturer / model: Apple mac book pro
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior
Installation

_Tell us what should happen_
Be installed
## Actual Behavior
Impossible to install

_Tell us what happens instead_
```
Error: Failed to fetch plugin https://github.com/katzer/cordova-plugin-local-notifications via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 194 Error output:
npm WARN checkPermissions Missing write access to /Users/xxx/Desktop/Cordova Proyectos/notifications/node_modules/cordova-plugin-app-event
npm WARN com.example.hello@1.0.0 No repository field.
```

npm ERR! path /Users/xxx/Desktop/Cordova Proyectos/notifications/node_modules/cordova-plugin-app-event
npm ERR! code ELOOP
npm ERR! errno -62
npm ERR! syscall access
npm ERR! ELOOP: too many symbolic links encountered, access '/Users/xxx/Desktop/Cordova Proyectos/notifications/node_modules/cordova-plugin-app-event'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2017-09-03T17_37_46_289Z-debug.log

## Steps to Reproduce
Create a new empty project
Install with cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...Create new project
  2. ...cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
  3. ...
  4. ....

## Context

_What were you trying to do?_
Install the plugin
## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by LtotheWT** [comment]
downgrade to npm 4

**Comment by jruizsulime** [comment]
This help me: cordova plugin add XXX **--nofetch**

**Comment by De-Lac** [comment]
I tried to remove `node_modules`, then `npm install`, then `ionic cordova plugin add XXX --nofetch`.
It installs great, but in the application the plugin is not recognized.
If I do ionic cordova plugin list, `de.appplant.cordova.plugin.local-notification` is in.

**Comment by tomilofano** [comment]
Try this:

```
$ ionic cordova plugin rm de.appplant.cordova.plugin.local-notification
$ ionic cordova plugin add de.appplant.cordova.plugin.local-notification
$ npm install --save @ionic-native/local-notifications
```
This help me
