### ISSUE TITLE
Custom sound not working in IOS 10 

### ISSUE THREAD

**Issue by LtotheWT** [katzer/cordova-plugin-local-notifications#1375]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-sim : 6.0.0 
    Node    : v8.1.2
    npm     : 4.6.1 
    OS      : macOS Sierra
    Xcode   : Xcode 8.3.3 Build version 8E3004b 

* Plugin version: 0.8.5
* Platform: IOS
* OS version: macOS Sierra
* Device manufacturer / model: IOS simulator iphone SE
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): ios 4.4.0
* Plugin config 
* Ionic Version (if using Ionic)  3.9.2

## Expected Behavior

The notification should play the desire sound 

## Actual Behavior

the notification does not play the desire sound, no sound at all

## Steps to Reproduce

 the song.wav is in www/audio
```
let options = {
        id: this.info.id,
        title: this.info.title,
        text: this.info.message,
        at: new Date(this.info.enddate),
        sound: 'file://audio/song.wav',
    };
this.localNotifications.schedule(options);
```

## Context

make the notification to play the desire sound 

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by katzer** [comment]
If the permission has been granted, than its working. I can try out with success.

**Comment by Lenndev** [comment]
Oke... if the app is in foreground, the custom sound IS played. but if the app is in background the default sound is played on iOS. Any idea why this is happening?
