### ISSUE TITLE
Unable to Handle Local Notification when app has been terminated

### ISSUE THREAD

**Issue by fvukovic** [katzer/cordova-plugin-local-notifications#1376]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: v0.8.4
* Platform: ANDROID
* OS version: 25
* Device manufacturer / model:
* Cordova version (```cordova -v```):7
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic) 1

## Expected Behavior
i use this code
```
  cordova.plugins.notification.local.on("click", function(notification) {
    alert("click: " + notification.id);
});
```
If app is shuted down and i clicked on my received notification, the app will open, but i will not get this alert, this kind a event works only if the app is working, is there a event which will save all notifications that are received when the app is shuted down and show us on the app opening or similar?

**Comment by Tawpie** [comment]
When you create the notifications, save them in local storage. When the notification system wakes you up, check the saved copy!

**Comment by aitoraznar** [comment]
@Tawpie Without the reference of the clicked notification you can't know which of the saved notifications you have to choose.

Or what is your solutions??

thx

**Comment by katzer** [comment]
Please use the latest master. That works across all platforms now. There's also the new `launchDetails` if the app was launched by clicking on a notification.
