### ISSUE TITLE
Not working in background

### ISSUE THREAD

**Issue by Lucius0909** [katzer/cordova-plugin-local-notifications#1377]
## Your Environment

* Plugin version: 0.8.5
* Platform: ANDROID
* OS version: 6.0
* Device manufacturer / model: LENOVO A7010
* Cordova version (```cordova -v```): 6.5.0
* Cordova platform version (```cordova platform ls```):  Installed platforms: android 6.2.2
* Plugin config 
* Ionic Version (if using Ionic) 2.2.1

## Expected Behavior

When you leave the application, leaving it in the background, a scheduled notification should be shown at the time it was scheduled.

## Actual Behavior

As soon as you leave the APP, the notification is called, before the scheduled time arrives

## Steps to Reproduce

Below "<script src="build/main.js"></script>" in index.html, i put this code:

```
<script>
  function notificationEventsHandler() {
    cordova.plugins.notification.local.on("click", function (notification) {
    });
}
function newNotification() {
    var nexthr = new Date();
    nexthr.setHours(nexthr.getHours()+1);   // set to an hour later
var d = new Date(nexthr.getYear() + 1900, nexthr.getMonth(),
nexthr.getDate(), nexthr.getHours(), 0, 0, 0);
    cordova.plugins.notification.local.schedule({
            id: 1,
            title: "On the hour. Every hour.",
            text: "Test",
            at: d,
            every: "hour",
            led: "0000FF"
        }, function () {
    });
    d.setMinutes(15);
    cordova.plugins.notification.local.schedule({
            id: 2,
            title: "Every quarter past.",
            text: "Test",
            at: d,
            every: "hour",
            led: "0000FF"
        }, function () {
    });
    d.setMinutes(30);
    cordova.plugins.notification.local.schedule({
            id: 3,
            title: "Every half hour.",
            text: "Test",
            at: d,
            every: "hour",
            led: "0000FF"
        }, function () {
    });
    d.setMinutes(45);
    cordova.plugins.notification.local.schedule({
            id: 4,
            title: "Every quarter to.",
            text: "Test",
            at: d,
            every: "hour",
            led: "0000FF"
        }, function () {
    });
}
newNotification();
  </script>
```

## Context

Only schedule a notification so that it is called with the application open or not.

## Additional Infos

`ionic info`

Your system information:

 ordova CLI: 7.0.1
Ionic Framework Version: 3.6.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 2.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.11.3
Xcode version: Not installed

**Comment by katzer** [comment]
If you need to schedule multiple notifications at once, please do that in a single `schedule([{}, {}, ...])` call and do not use the same date instance for all messages.

Please use the latest master branch. Triggering has been changed a bit- see the README.

**Comment by juniordnts** [comment]
Same here
