### ISSUE TITLE
Local notifications not working consistently on Ionic 1

### ISSUE THREAD

**Issue by vijayb** [katzer/cordova-plugin-local-notifications#1378]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
* Platform:Mac
* OS version:Yosemite
* Device manufacturer / model: Android/Axon 7
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):android 6.2.3
* Plugin config
* Ionic Version (if using Ionic)

Cordova CLI: 7.0.1 
Ionic CLI Version: 2.1.15
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.1 
ios-sim version: 6.0.0 
OS: OS X Yosemite
Node Version: v6.4.0
Xcode version: Xcode 7.1 Build version 7B91b

## Expected Behavior

I'm trying to schedule a simple test notification for a few seconds in the future after my Ionic 1 app loads and the notification sometimes appears and sometimes doesn't, but when it appears it's essentially a random amount of time later. Sometimes 20-30 seconds, sometimes several minutes

_Tell us what should happen_

The notification shows up consistently and deterministically

## Actual Behavior

The notifications sometimes show up and sometimes don't and they're not consistent about when they show up

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

One thing I"m confused about is when I dependency inject local notifications into my Ionic 1 controller, $cordovaLocalNotification (singular) doesn't work but $cordovaLocalNotifications (plural) does work. All the examples I have seen use the singular version but someone on the Ionic slack suggested I use the plural because it wouldn't work otherwise. Furthermore, the schedule(...).then(...) syntax fails with an error saying the function doesn't exist. If I skip then .then(...) it does seem to schedule a notification, but as I wrote above, erratically. 

Here's my bower.json:

  "devDependencies": {
    "platform.js": "platform#^1.3.3"
  },
  "dependencies": {
    "jquery": "^3.1.1",
    "angular": "^1.5.3",
    "angular-resource": "1.5.8",
    "ionic": "^1.3.2",
    "lodash": "^4.15.0",
    "moment": "^2.14.1",
    "moment-timezone": "^0.5.5",
    "angular-ui-router": "^0.2.13",
    "jquery.cookie": "^1.4.1",
    "Ionicons": "ionicons#^2.0.1",
    "material-design-icons": "^3.0.1",
    "pubnub": "^4.2.5",
    "pubnub-angular": "^4.0.2",
    "ngCordova": "^0.1.27-alpha"
  },
  "resolutions": {
    "angular": "1.5.3"
  }

And my package.json:

{
    "name": "PeachDelivery",
    "version": "1.0.8",
    "author": "Peach Inc <software@peachd.com>",
    "description": "",
    "devDependencies": {
        "babel-preset-es2015": "^6.13.2",
        "beepbeep": "^1.2.0",
        "connect": "^3.4.1",
        "connect-livereload": "^0.5.4",
        "del": "^2.2.0",
        "express": "^4.11.1",
        "glob": "^4.3.5",
        "gulp": "^3.9.1",
        "gulp-angular-templatecache": "^2.0.0",
        "gulp-autoprefixer": "^3.1.1",
        "gulp-babel": "^6.1.2",
        "gulp-cached": "^1.1.0",
        "gulp-changed": "^1.3.0",
        "gulp-concat": "^2.6.0",
        "gulp-iconfont": "^5.0.1",
        "gulp-iconfont-css": "2.0.0",
        "gulp-if": "^2.0.0",
        "gulp-inject": "^3.0.0",
        "gulp-jshint": "^2.0.0",
        "gulp-json-editor": "^2.2.1",
        "gulp-livereload": "^3.8.1",
        "gulp-load-plugins": "^1.1.0",
        "gulp-ng-annotate": "^1.1.0",
        "gulp-ng-config": "^1.3.1",
        "gulp-order": "^1.1.1",
        "gulp-plumber": "^1.1.0",
        "gulp-remember": "^0.3.0",
        "gulp-rename": "^1.2.2",
        "gulp-rev": "^6.0.0",
        "gulp-sass": "^2.3.2",
        "gulp-shell": "^0.5.1",
        "gulp-sourcemaps": "^1.6.0",
        "gulp-strip-css-comments": "^1.2.0",
        "gulp-strip-debug": "^1.1.0",
        "gulp-uglify": "^2.0.0",
        "http-proxy-middleware": "^0.17.1",
        "jshint": "2.9.3",
        "jshint-stylish": "^2.1.0",
        "json-file": "^0.1.0",
        "lodash": "^4.15.0",
        "lodash._basecopy": "latest",
        "merge-stream": "^1.0.0",
        "node-notifier": "^4.6.0",
        "node-sass": "^3.8.0",
        "open": "0.0.5",
        "proxy-middleware": "^0.15.0",
        "ripple-emulator": "^0.9.32",
        "run-sequence": "^1.1.5",
        "shelljs": "^0.5.3",
        "stream-series": "^0.1.1",
        "streamqueue": "^1.1.1",
        "wiredep": "^3.0.0",
        "yargs": "^3.31.0"
    },
    "scripts": {
        "gulp": "./node_modules/.bin/gulp"
    },
    "cordovaPlugins": [
        "cordova-plugin-device",
        "cordova-plugin-console",
        "cordova-plugin-whitelist",
        "cordova-plugin-statusbar",
        "cordova-plugin-splashscreen",
        "cordova-plugin-dialogs",
        "cordova-plugin-background-fetch",
        "ionic-plugin-deploy",
        "cordova-plugin-device@~1.1.2",
        "cordova-plugin-whitelist@~1.2.2",
        "cordova-plugin-splashscreen@~3.2.2",
        "cordova-plugin-console@~1.0.3",
        "cordova-plugin-background-fetch@~4.0.0",
        "ionic-plugin-deploy@~0.6.4",
        "uk.co.workingedge.phonegap.plugin.launchnavigator",
        "de.appplant.cordova.plugin.local-notification@0.8.5"
    ],
    "cordovaPlatforms": [
        "ios",
        "android"
    ],
    "dependencies": {
        "@ionic-native/deeplinks": "^4.2.1",
        "@ionic/cloud": "^0.9.0",
        "cordova-android": "^6.2.3",
        "cordova-background-geolocation": "https://github.com/transistorsoft/cordova-background-geolocation.git#2.6.0",
        "cordova-plugin-app-event": "^1.2.1",
        "cordova-plugin-background-fetch": "~4.0.0",
        "cordova-plugin-console": "~1.0.3",
        "cordova-plugin-device": "~1.1.2",
        "cordova-plugin-dialogs": "~1.3.3",
        "cordova-plugin-local-notifications": "git+https://github.com/katzer/cordova-plugin-local-notifications.git",
        "cordova-plugin-splashscreen": "~3.2.2",
        "cordova-plugin-statusbar": "^2.2.3",
        "cordova-plugin-whitelist": "~1.2.2",
        "ionic-native": "^2.2.12",
        "ionic-plugin-deploy": "~0.6.4",
        "pubnub": "^4.2.5",
        "pubnub-angular": "^4.0.2",
        "uk.co.workingedge.phonegap.plugin.launchnavigator": "^4.0.2",
        "de.appplant.cordova.plugin.local-notification": "~0.8.4"
    },
    "cordova": {
        "plugins": {
            "uk.co.workingedge.phonegap.plugin.launchnavigator": {},
            "cordova-background-geolocation": {
                "LICENSE": ""
            },
            "cordova-plugin-background-fetch": {},
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-deploy": {},
            "cordova-plugin-dialogs": {},
            "cordova-plugin-statusbar": {},
            "de.appplant.cordova.plugin.local-notification": {}
        },
        "platforms": [
            "android"
        ]
    }
}

## Context

_What were you trying to do?_

Just schedule some very simple local notifications

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by vijayb** [comment]
Also I was basing my code on these examples: http://ngcordova.com/docs/plugins/localNotification/

**Comment by katzer** [comment]
Please try out with the latest master branch (0.9-beta) - wont be compatible as of now with the ionic wrapper.

```js
cordova.plugins.notification.local.schedule({
  title: 'Test',
  trigger: { in: 10, unit: 'second' }
})
```
