### ISSUE TITLE
Implementation Question about BADGE when local-notification and remote push notification is used together

### ISSUE THREAD

**Issue by buymybm100** [katzer/cordova-plugin-local-notifications#1380]
I have a question about how people are handling the Badge count when they have to use both the local and push notification plugins. 

Currently,   I keep track of the badge count on the Server side and send the 'badge' in the remote notification.

I now have to use local-notification to send reminders. At the point of scheduling the local-notification, I can't anticipate what the badge number will be - as when the reminder triggers, more remote notifications may have arrived and changed the badge count.

An example scenario is -
(1) Send remote-notification with badge 1
(2) Send another with badge 2
(3) Schedule a local notification ( can't set a badge number here... )
(4) Send remote-notification with badge 3
(5) At this point...the scheduled reminder triggers.... and I get the local notification. In theory, the badge should be incremented to 4. But, in step (3), I wont know what the badge number would be in advance.

I have tried to use an event-listener for the 'trigger' event so that I can get the Badge count and increment it (via cordova badge). But, the 'trigger' event doesn't trigger when the App is in the background. 

Has anyone found a way to keep the badge count consistent ?

Best regards,
Beemer

**Comment by katzer** [comment]
iOS allows to set a fixed badge number. The OS does not increment the number for you. If you schedule a notification with a badge number, then the number will stay untouched.
