### ISSUE TITLE
No UIApplication+APPLocalNotification.m file

### ISSUE THREAD

**Issue by DeeCann** [katzer/cordova-plugin-local-notifications#1381]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.8.5
* Platform: mac
* OS version: el captain
* Device manufacturer / model: -
* Cordova version (```cordova -v```): 7.0.0
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Build project for cordova iOS emulator

## Actual Behavior

Build fails:
clang: error: no such file or directory: '/Users/xxx/Work/Company/Project/cordova/platforms/ios/Homefitting/Plugins/de.appplant.cordova.plugin.local-notification/UIApplication+APPLocalNotification.m'
clang: error: no input files

There is UIApplication+APPLocalNotification.ios9.m file instead

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ... create ne project
  2. ...  cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#ios10 --nofetch
  3. ...
  4. ....

## Context

Buil iOS project for emulator

**Comment by katzer** [comment]
Please use the latest master
