### ISSUE TITLE
In Android, set "trigger" event callbacks are not invoked if the application is not running

### ISSUE THREAD

**Issue by mohaseeb** [katzer/cordova-plugin-local-notifications#1382]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

**In Android, set "trigger" event callback is not invoked when an scheduled notification is triggered, if the application is not running in the background (i.e. destroyed).**

## Your Environment

* Plugin version: **0.8.5**
* Platform: **Android**
* OS version: **5.1.1**
* Device manufacturer / model: **Samsung Galaxy Tab A (2016)**
* Cordova version (```cordova -v```): **7.0.1**
* Cordova platform version (```cordova platform ls```): 
**Installed platforms:
  android 6.2.3
Available platforms: 
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0**
* Plugin config **default config**
* Ionic Version (if using Ionic) **3.10.3**

## Expected Behavior

When an scheduled event is triggered, the set "trigger" callback is invoked even when the application is not running.
(I am expecting the application to be started, if it is not, to execute the callback!).

## Actual Behavior

When an scheduled event is triggered, the set "trigger" callback is not invoked when the application was not running.

## Steps to Reproduce

  1. Create an ionic app with cordova support, install and configure the local-notification plugin. (Code for reproducing the issue is accessible at: https://bitbucket.org/7aseeb/corodva_local_notification_test/src)
  2. Set a "trigger" event callback
  3. Schedule a delayed notification
  4. Deploy the app to an Android device
  5. Kill the app (e.g. by removing it from the list of recent applications)
  6. When the scheduled notification is triggered, the callback is not invoked.

## Context

I want to execute a logic whenever a scheduled event is triggered, regardless of whether the app is started, paused or not running.

## Debug logs
[trigger_callback_nok.txt](https://github.com/katzer/cordova-plugin-local-notifications/files/1316049/trigger_callback_nok.txt)
Last ~10 lines are the interesting ones:
(09-19 23:40:27.730) -> shows a notification is scheduled 
(09-19 23:41:09.661) -> shows the app (activity) being stopped 
(09-19 23:43:37.635) -> this (and the following lines) are logged when the notification is triggered, **(I am expecting to see lines printed by my callback)**

Line (09-19 23:33:12.795) of below file shows the callback logged lines when it is invoked (in this case the notification was triggered while the application was still running.)
[trigger_callback_ok.txt](https://github.com/katzer/cordova-plugin-local-notifications/files/1316072/trigger_callback_ok.txt)

**Comment by katzer** [comment]
@mohaseeb If the app is not running, it cannot execute a function that will be created at runtime.

**Comment by snow-drop** [comment]
Good day. Is there any workaround for this? I'm thinking that you really need to run the app on the background using this? [https://github.com/katzer/cordova-plugin-background-mode](url)
