### ISSUE TITLE
Actions not working on  x and example-x branch

### ISSUE THREAD

**Issue by buymybm100** [katzer/cordova-plugin-local-notifications#1383]
**Provide a general summary of the issue.**
- Testing the "Actions" feature on branch x and example-x.  The notification banner displays but there are no Action buttons.

$ git clone https://github.com/katzer/cordova-plugin-local-notifications
$ git fetch && git checkout x
$ git fetch && git checkout example-x
$ ./run --emulator --target="iPhone-5"

## Your Environment

* Plugin version:  x and example-x
* Platform: IOS
* OS version: 10.3
* Device manufacturer / model: Iphone 5 simulator
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):

- Installed platforms:
-   ios 4.4.0
-   windows 5.0.0
- Available platforms: 
-   android ~6.2.2
-   blackberry10 ~3.8.0 (deprecated)
-   browser ~4.1.0
-   osx ~4.0.1
-   webos ~3.7.0

* Plugin config  : using branch x and example-x

* Ionic Version (if using Ionic) :  using branch x and example-x

## Expected Behavior
_Tell us what should happen_

expected to see 3 action possibilities - Like, dislike and feedback

## Actual Behavior
_Tell us what happens instead_

The notification is displayed. Actions not shown as buttons or input. 

## Steps to Reproduce
_Reproduce this issue; include code to reproduce, if relevant_

$ git clone https://github.com/katzer/cordova-plugin-local-notifications
$ git fetch && git checkout x
$ git fetch && git checkout example-x## Context

_What were you trying to do?_
run examples in example-x

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

Thank you,
Beemer

**Comment by katzer** [comment]
@buymybm100 You need to expand the notification banner. This is how its works on iOS.

**Comment by buymybm100** [comment]
Got it ! You are right, Thanks Katzer !  

If anyone else is not familiar with Actions in IOS -- the notification appears with a little bar at the bottom. Just drag the bar and the Action buttons will appear.

Thanks again,Katzer.
