### ISSUE TITLE
Call an external function on Click event 

### ISSUE THREAD

**Issue by ruben82** [katzer/cordova-plugin-local-notifications#1390]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## My Environment

* Plugin version:  x branch latest
* Platform: Android 
* OS version: 8.0.0
* Device manufacturer / model: Nexus 5X
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): cordova platform ls
* Plugin config
* Ionic Version (if using Ionic): 3.12.0

## Expected Behavior

When I receive local notification and I click on it, **on('click'** function will be triggered and in that function I need to call external function and change external variable 

## Actual Behavior

When I receive local notification and I click on it, **on('click'** function will be triggered and in that function I cannot handle any external function or variables 

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Create a Ionic Page and import plugin
  2. In this page, schedule a notification
  3. In this page set **this.localNotifications.on('click', handler);**
  4. In this page create a public method called **setTrueSMSArrived**
  5. In the Handler function try to call the public method which change a variable that must  be used at the start of the page to choose if I have to go to the NEXT_PAGE

```js
import { LocalNotifications } from 'ionic-native/local-notifications'
@IonicPage()
@Component({
  selector: 'page-home-first',
  templateUrl: 'home-first.html',
})
export class HomeFirstPage {
  public smsArrived: boolean = false;
  constructor(private navCtrl: NavController
    , private localNotifications: LocalNotifications) {
      startup();
  }
  ionViewDidEnter() {
    if (this.smsArrived) {
      this.smsArrived = false;
      this.navCtrl.push('NEXTPAGE');
    } 
  }
startup() {
    this.platform.ready().then((readySource) => {
        this.localNotifications.schedule({
          title: 'My Notification titile'
          , text: 'My Notification text'
        });
        this.localNotifications.on('click', function(notification){
          this.setTrueSMSArrived();
        });
      });
  }
  public setTrueSMSArrived(){
    this.smsArrived = true;
  }
```
## Context

Understand the Handler scope to handle my variable

## Debug logs

ERROR:
TypeError: this.setTrueSMSArrived is not a function

**Comment by katzer** [comment]
@ruben82 You need to specify the scope in which the callback will the executed. In your case it seems to be `this`.

```js
this.localNotifications.on('click', function(notification){
    this.setTrueSMSArrived();
}, this);
```

**Comment by jruizsulime** [comment]
For a Phonegap app, the scope will be "Cordova"? Example:

`cordova.plugins.notification.local.on("click", function (notification) {
                alert(notification.text);
            }, cordova);`

**Comment by katzer** [comment]
The default scope is _window_.

**Comment by Davidcorral94** [comment]
Hi @katzer, when I put this into my code:

 ```
this.localNotifications.on('click', function(notification){
        this.someFunction();
}, this);
```

I got underlined as a fail by the editor (IntelliJ) as you can see in the figure. The TypeScript error is: 
**TS2346: Supplied parameters do not match any signature of call target.**

![IntelliJ error figure](https://i.gyazo.com/026aff3b2e9a0e3fc4e6c1d0facee89d.png)

Also it doesn't compiles with `ionic cordova run android`.

What can be wrong?

Thanks!

**Comment by ruben82** [comment]
@katzer 
Method 'on' do not permit signature with three parameters according with @Davidcorral94 . So We cannot put the scope... Can we?

**Comment by Davidcorral94** [comment]
Any updates? This is crucial into the app that I'm coding.

**Comment by katzer** [comment]
@ruben82 @Davidcorral94 That looks like the Ionic native wrapper for the plugin does not support this. Setting the scope makes it easier for you, however you can call an external function even the ionic wrapper does not allow to set the scope.

```js
var me = this;

this.localNotifications.on('click', function(notification){
       me.someFunction();
});
```
