### ISSUE TITLE
'Failed to post notification on channel "null"'

### ISSUE THREAD

**Issue by Ladeiras** [katzer/cordova-plugin-local-notifications#1392]
I'm now testing my app on API 26 and can't receive notifications. It was working fine on previous Android versions.

## Your Environment

* Plugin version: 4.3.0
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: 
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): 6.3.0
* Plugin config
* Ionic Version (if using Ionic): 3.12.0

## Expected Behavior
Should receive a notification

## Actual Behavior
Error toast

![error](https://user-images.githubusercontent.com/5716992/31081555-24d56928-a784-11e7-8297-611b876c65ee.png)

## Steps to Reproduce
Use API 26 emulator

## Context
Just begun to use the new emulator

**Comment by katzer** [comment]
That has been fixed, however support for Android 8 is still limited.

**Comment by adidamty** [comment]
Hi katzer,

i encounter the same issue.
i am using  "@ionic-native/push": "^4.5.2".
whrer this was fixed ?

thank you,

**Comment by adidamty** [comment]
Hi katzer,

i encounter the same issue.
i am using @ionic-native/push version 4.5.2.
whrer this was fixed ?

thank you,

**Comment by katzer** [comment]
The latest version of the plugin is v0.9-beta.1. Not sure what plugin with version 4.5.2 you're using

**Comment by kwilliams-curago** [comment]
I just ran into this using 8.5 (ionic-native wrapper). I assume it's related to this:

> On Android 8.0 (API level 26) and higher, a valid notification channel ID, set by setChannelId() or provided in the NotificationCompat.Builder constructor when creating a channel. 
https://developer.android.com/guide/topics/ui/notifiers/notifications.html
