### ISSUE TITLE
Notification Message in Windows

### ISSUE THREAD

**Issue by vincebanzon** [katzer/cordova-plugin-local-notifications#1394]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
Message set for notification is not displayed, instead a text "New notification" is shown
## Your Environment

* Plugin version: 0.8.5
* Platform: Windows
* OS version: 10
* Device manufacturer / model:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

_Tell us what should happen_

## Actual Behavior

_Tell us what happens instead_
It should display the correct message set in local notification property
## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by katzer** [comment]
Please re-open and fill out the template if its still an issue.
