### ISSUE TITLE
Setting the smallIcon forces a large icon to be shown as well

### ISSUE THREAD

**Issue by marcovtwout** [katzer/cordova-plugin-local-notifications#1395]
This is about weird default behavior in the options 'smallIcon' and 'icon'.

## Your Environment

* Plugin version: master
* Platform: Android
* OS version: 7
* Cordova version (```cordova -v```): 7

## Expected Behavior

Default behavior when no options are specified: 'smallIcon' will be set to the default bell icon. There is no large 'icon'

When you supply a custom smallIcon, there should still be no large 'icon'.

## Actual Behavior

When you supply a custom smallIcon, the large 'icon' will now also be set and shows the default bell icon.

This behavior is defined in this piece of code: https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/android/notification/Builder.java#L146

I can't find any workaround (like setting icon: null) to prevent this behavior.

## Steps to Reproduce

```
let notification = <ILocalNotification> {
        id: 1
        title: 'test',
        text: 'test',
        smallIcon: 'res://ic_popup_reminder',
};
```

**Comment by katzer** [comment]
That has been fixed with 0.9.beta
