### ISSUE TITLE
The trigger callback method does not work on iOS 10

### ISSUE THREAD

**Issue by tuzhiye123** [katzer/cordova-plugin-local-notifications#1396]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
By using the latest plugin, when the application is running in the foreground, I want to receive the response from the trigger method. But it doesn't work on iOS10, and it's perfect on iOS9

## Your Environment

* Plugin version:0.8.5
* Platform:iOS
* OS version:10.3.3
* Device manufacturer / model:iPhone6s
* Cordova version (```cordova -v```):6.0.0
* Cordova platform version (```cordova platform ls```):ios 4.0.1
* Plugin config
```
cordova-plugin-app-event
cordova-plugin-camera
cordova-plugin-device
ionic-plugin-keyboard
cordova-plugin-statusbar
cordova-plugin-whitelist
de.appplant.cordova.plugin.local-notification
```
* Ionic Version (if using Ionic)

## Expected Behavior
The trigger callback method work on iOS 10.

## Actual Behavior
The trigger callback method does not work on iOS 10 ,but the schedule callback method works ,and through getTriggeredIds method I can get ID that has been triggered.
All methods are perfect on iOS 9.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Create APP
  2. Add Local Notification Plugin
  3. Add Code
```
var notiDate = new Date();
cordova.plugins.notification.local.schedule({
                    id:1,
                    title: "test",
                    text: "",
                    sound:"",
                    at: notiDate
                });

cordova.plugins.notification.local.on("trigger", function (notification) {
                        setTimeout(function(){
                            alert("--trigger---" + notification.title);
                        },100);
                    });
cordova.plugins.notification.local.on("click", function (notification) {
                        setTimeout(function(){
                            alert("--click---" + notification.title);
                        },100);
                    });
cordova.plugins.notification.local.on("schedule", function (notification) {
                        setTimeout(function(){
                            alert("--schedule---" + notification.title);
                        },100);
                    });

```
Note:
1> Even if I change my schedule to an array object, I get the same result.
2> I install the plugin through the following command line:
```
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
```
3> This plugin is the latest version with contains the code from ios10 branch.

## Context

_What were you trying to do?_
The trigger callback method work on iOS 10.

## Debug logs
No logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by katzer** [comment]
Please use v0.9-beta (master branch now)
