### ISSUE TITLE
after cordova.plugins.notification.local.update trigger event is not fired

### ISSUE THREAD

**Issue by vovikdrg** [katzer/cordova-plugin-local-notifications#1399]
Provide a general summary of the issue.

## Your Environment

* Plugin version: "0.8.5"
* Platform:  Android ,
* OS version: Android
* Device manufacturer / model: Samsung  S7
* Cordova version (```cordova -v```): cordova -v`
* Cordova platform version (```cordova platform ls```):
Installed platforms:
  android 6.3.0
  ios 4.4.0
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~5.0.0
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0
* Plugin config
* Ionic Version (if using Ionic)
3.7.1
## Expected Behavior
If I am using update method then on trigger is not called but notification will be shown.

I am checking if notification is present and i wanted to call update if schedule changed for that id. And then on trigger is not called. 
this.localNotifications.isPresent(ID).then

if i cancel and schedule again it works as expected
this.localNotifications.cancel(category.Id)
        .then(() => {
          this.localNotifications.schedule(scheduleItem);
        })

My notification is shown, i can hear sound but in my trigger even i have logic which turn on vibration for user. 

## Context

I have an app which has updated schedule on push notification. Each notification has id, so i am checking if previous and new notification has different time i want to reschedule. So I found method update which i suppose is kind of the same cancel and schedule. 

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by katzer** [comment]
@vovikdrg The update method does not fire the trigger event if the notification has been triggered already. There's an update event instead.
