### ISSUE TITLE
Asks for permission, never shows example notification

### ISSUE THREAD

**Issue by bgando** [katzer/cordova-plugin-local-notifications#1400]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: ~0.0.0
* Platform: ios 
* OS version: 11.0
* Device manufacturer / model: simulator, various (tried: 5S, 7, X, SE)
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```):
Installed platforms:
  ios 4.5.1
  windows 5.0.0
* Plugin config unsure
* Ionic Version (if using Ionic) N/A

## Expected Behavior
A notification to pop up

## Actual Behavior
It asks for permissions but never shows a notification. I get an error, see below.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_
1. trigger this code to execute:
```
cordova.plugins.notification.local.schedule({
      title: "New Message",
      message: "Hi, are you ready? We are waiting."
    });
```
2. Accept permissions to show notification
3. trigger the code above again, nothing happens

## Context

I am trying to get an example notification to run for the first time.

## Debug logs

```
Main Thread Checker: UI API called on a background thread: -[UIApplication currentUserNotificationSettings]
PID: 38687, TID: 1053046, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   app name                      0x000000010b2cb858 -[UIApplication(APPLocalNotification) registerPermissionToScheduleLocalNotifications] + 168
5   app name                     0x000000010b2c9631 __43-[APPLocalNotification registerPermission:]_block_invoke + 65
6   libdispatch.dylib                   0x00000001129293f7 _dispatch_call_block_and_release + 12
7   libdispatch.dylib                   0x000000011292a43c _dispatch_client_callout + 8
8   libdispatch.dylib                   0x000000011292f352 _dispatch_queue_override_invoke + 1458
9   libdispatch.dylib                   0x00000001129361f9 _dispatch_root_queue_drain + 772
10  libdispatch.dylib                   0x0000000112935e97 _dispatch_worker_thread3 + 132
11  libsystem_pthread.dylib             0x0000000112de85a2 _pthread_wqthread + 1299
12  libsystem_pthread.dylib             0x0000000112de807d start_wqthread + 13
```

  * ios XCode logs
  * Android: $ adb logcat

**Comment by aitoraznar** [comment]
Is not working on IOS. Lots of issues regarding IOS since so much time.

There is no Pull request merging, is this plugin abandoned?

**Comment by steedems** [comment]
same here, any info/news?

**Comment by bgando** [comment]
I fixed my problem by making sure I was installing the latest release of the plugin, not 0.8.1:

`cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.8.5`

**Comment by aitoraznar** [comment]
> cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.8.5

Was the trick, thank you

**Comment by kyle9292** [comment]
I've got the same issue but I'm using an Ionic3 app deployed to iOS11. 
Updated to 0.8.5 and get the same result. 
I can see it scheduled but never triggered. No errors from the plugin.

**Comment by wootwoot1234** [comment]
@kyle9292 did you figure this out?  Having the same issue.

**Comment by kyle9292** [comment]
@wootwoot1234 No I haven't. Sorry. Just kind of waiting for the plugin to be updated.

**Comment by katzer** [comment]
Please use the latest code - you can use the master branch now. That issue with iOS11 and UI thread has been solved already.

**Comment by bgando** [comment]
Thanks @katzer! I appreciate all your hard work to get out this fix.

**Comment by wootwoot1234** [comment]
@katzer thanks!

**Comment by SanjanaTailor** [comment]
@katzer : currently I am using local Notification plugin **cordova-plugin-local-notification 0.9.0-beta.2**. 
For iOS version 9.3.2 no notification permission dialog shows to allow and display the badge count. While for iOS version 12 it's asking notification persmission dialog to allow to display. so that badge doesn't show. Android working fine badge and notification
