### ISSUE TITLE
not showing the notification after changing the device date/time manually in iOS

### ISSUE THREAD

**Issue by amjadm61** [katzer/cordova-plugin-local-notifications#1402]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**
After scheduling the notification, it is working perfectly if I didn't change the device date/time manually. But If I change the time/date of the device, the notification for the future date is not working. It is working perfectly on android and the issue is in iOS.

For example, there is 2 notification. first notification is on 24/10/2017 at 5.00PM and second notification is on 27/10/2017 at 5.00PM. we scheduled both of these notification on 24/10/2017 at 4.58PM and waited for 2 minutes, then we will get the first notification. For testing the second notification we changed the device date to 27/10/2017 4.58PM and waited for 2 minutes, 1 hour, 10 hour, etc. but there is not notification for the second one.

Here you can find my sample code: https://gitlab.com/snippets/1680705

## Your Environment

* Plugin version: ^0.8.5
* Platform: iOS
* OS version: 11.0
* Device manufacturer / model: 7
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): ios 4.5.2
* Plugin config: Unsure
* Ionic Version (if using Ionic): 3.13.2

## Expected Behavior

notification should work if the date/time changed manually also.

## Actual Behavior

notification not working when date/time changed manually

## Steps to Reproduce

code snippet: https://gitlab.com/snippets/1680705

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by Tawpie** [comment]
Amjad. For iOS, notifications are only presented when the time on the devices progresses *through* the notification’s fire time. So set the time to just before your fire time, then set the date. Android will fire notifications that are ‘in the past’ when the date changes but iOS will  not. Keeps you from getting that blast of notifications if you cross an international date line.

**Comment by MatehElismar** [comment]
2019, i have the same problem...
