### ISSUE TITLE
Plugin is not working for long terms and scheduling is not working properly

### ISSUE THREAD

**Issue by Soumyajit250890** [katzer/cordova-plugin-local-notifications#1404]
Thank you for the awesome plugin. In my project, I am trying to schedule notification every 30 minutes. The plugin is working fine for first couple of times but in the long run it is not showing up any notification.

## Phonegap

* Plugin version:  Current
* Platform: Android
* OS version: 6.0 and above
* Device manufacturer / model: Mi Note4, onePlus 3, honor 8
* Cordova version (```cordova -v```): 6.5.0
* Cordova platform version (```cordova platform ls```): Android 6.1.2
* Plugin config
* Ionic Version (if using Ionic): NA

## Expected Behavior
I am trying to schedule the notification every 30 minutes.

## Actual Behavior

For couple of times its working fine. But in the long run, its not working and the scheduling is running every 1 hour and often its failing. Besides after the device is being restarted, the plugin is not resumed. The problem is more reproducible in android 7.0 where the notification comes very rarely.
.
## Steps to Reproduce

cordova.plugins.notification.local.isScheduled($localStorage.checkInId, function (successCallBck) {
            if(!successCallBck){
                var defaultCheckInTime = new Date(2017-10-27 11:30:00");
                $localStorage.checkInId = defaultCheckInTime.getTime()+9999;
                cordova.plugins.notification.local.schedule({
                    id: $localStorage.checkInId,
                    title: "Check IN",
                    firstAt: defaultCheckInTime,
                    text: "There is a meeting in next 30 minutes",
                    every: 30 // "minute", "hour", "week", "month", "year"
                });
            }
        });

## Context

I am trying to schedule notification every 30 minutes.

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by Soumyajit250890** [comment]
@katzer Please look into this issue. I really need your help

**Comment by katzer** [comment]
@Soumyajit250890 Please use v0.9-beta

```js
cordova.plugins.notification.local.schedule({
  ...
  trigger: { every: 30, unit: 'minute', count: 2 }
});
```
