### ISSUE TITLE
Issue on Browser platform

### ISSUE THREAD

**Issue by ThorvaldAagaard** [katzer/cordova-plugin-local-notifications#1406]
I am using this Plugin on 3 different platforms, as PWA is getting more and more popular, one of the platforms is the browser

## Your Environment
Windows 10
* Plugin version: 0.8.5
* Platform: Windows
* OS version: 10
* Device manufacturer / model:
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```):
```
Installed platforms:
  android 6.2.3
  browser 5.0.1
  ios 4.5.2
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0
```
* Plugin config
* Ionic Version (if using Ionic)
```
cli packages: (C:\Users\thorv\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3 browser 5.0.1 ios 4.5.2
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.1
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : D:\Dokumenter\Android\sdk

Misc:

    backend : legacy
```

## Expected Behavior

LocalNotification is not supported on browsers, and that is OK, but like a lot of other plugins without browsersupport I expect it to be inactive on the browserplatform

## Actual Behavior

When starting my application I get this error: 

Error: exec proxy not found for :: LocalNotification :: deviceready

## Steps to Reproduce

Take any project, add the browser platform, and try to run it

## Context

Just running my application

## Debug logs

None provided

## Further details

It seems the problem is that the plugin adds a hook like this

```
/*********
 * HOOKS *
 *********/

// Called after 'deviceready' event
channel.deviceready.subscribe(function () {
    // Device is ready now, the listeners are registered
    // and all queued events can be executed.
    exec(null, null, 'LocalNotification', 'deviceready', []);
});
```
 in local-notification-util.js

That should only happen on supported platforms

but even this simple fix would be appriciated
```
    if (device.platform != 'browser') {
        exec(null, null, 'LocalNotification', 'deviceready', []);
    }
```

**Comment by katzer** [comment]
OK, got what you mean...
