### ISSUE TITLE
0.9 android build issue

### ISSUE THREAD

**Issue by msolovyov** [katzer/cordova-plugin-local-notifications#1409]
phonegap android build fails on 0.9 master branch. Works fine on 0.8.x version. 

## Your Environment

* Plugin version: 0.9.0
* Platform: Android 
* OS version: 7.1.1
* Device manufacturer / model: 
* Cordova version (```cordova -v```): phonegap 7.1.1
* Cordova platform version (```cordova platform ls```): 6.3.0
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Should build and run the app on device

## Actual Behavior

Build failed with errors

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. phonegap plugin add https://github.com/katzer/cordova-plugin-local-notifications.git
  2. phonegap run android --device

## Context

Tried to build the app and run it on android device. Checked and made sure android support repository was already install in android studio.

## Debug logs

ANDROID_HOME=/Users/michaelsolovyov/Library/Android/sdk

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home

Subproject Path: CordovaLib

The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

	at build_dd7omkp7g7egpypjihk2naw3d.run(/Users/michaelsolovyov/dev/phonegap-apps/mk1/platforms/android/build.gradle:145)

The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.

Incremental java compilation is an incubating feature.

The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.

:preBuild
 UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild
 UP-TO-DATE

:CordovaLib:checkDebugManifest

:CordovaLib:prepareDebugDependencies

:CordovaLib:compileDebugAidl

:CordovaLib:compileDebugNdk

UP-TO-DATE
:CordovaLib:compileLint

:CordovaLib:copyDebugLint
 UP-TO-DATE

:CordovaLib:mergeDebugShaders

:CordovaLib:compileDebugShaders

:CordovaLib:generateDebugAssets

:CordovaLib:mergeDebugAssets

:CordovaLib:mergeDebugProguardFiles

UP-TO-DATE

:CordovaLib:packageDebugRenderscript
 UP-TO-DATE

:CordovaLib:compileDebugRenderscript

:CordovaLib:generateDebugResValues

:CordovaLib:generateDebugResources

:CordovaLib:packageDebugResources

:CordovaLib:processDebugManifest

:CordovaLib:generateDebugBuildConfig

:CordovaLib:processDebugResources

:CordovaLib:generateDebugSources

:CordovaLib:incrementalDebugJavaCompilationSafeguard

:CordovaLib:compileDebugJavaWithJavac

:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes

UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug

:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug

:CordovaLib:mergeDebugJniLibFolders

:CordovaLib:transformNative_libsWithMergeJniLibsForDebug

:CordovaLib:transformNative_libsWithSyncJniLibsForDebug

:CordovaLib:bundleDebug

:CordovaLib:preReleaseBuild
 UP-TO-DATE

:CordovaLib:checkReleaseManifest

:CordovaLib:prepareReleaseDependencies

:CordovaLib:compileReleaseAidl

:CordovaLib:compileReleaseNdk

UP-TO-DATE

:CordovaLib:copyReleaseLint

UP-TO-DATE

:CordovaLib:mergeReleaseShaders

:CordovaLib:compileReleaseShaders

:CordovaLib:generateReleaseAssets

:CordovaLib:mergeReleaseAssets

:CordovaLib:mergeReleaseProguardFiles

UP-TO-DATE
:CordovaLib:packageReleaseRenderscript

UP-TO-DATE
:CordovaLib:compileReleaseRenderscript

:CordovaLib:generateReleaseResValues

:CordovaLib:generateReleaseResources

:CordovaLib:packageReleaseResources

:CordovaLib:processReleaseManifest

:CordovaLib:generateReleaseBuildConfig

:CordovaLib:processReleaseResources

:CordovaLib:generateReleaseSources

:CordovaLib:incrementalReleaseJavaCompilationSafeguard

:CordovaLib:compileReleaseJavaWithJavac

:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes

UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease

:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease

:CordovaLib:mergeReleaseJniLibFolders

:CordovaLib:transformNative_libsWithMergeJniLibsForRelease

:CordovaLib:transformNative_libsWithSyncJniLibsForRelease

:CordovaLib:bundleRelease

:prepareComAndroidSupportAnimatedVectorDrawable2540Library

:prepareComAndroidSupportAppcompatV72540Library

:prepareComAndroidSupportRecyclerviewV72540Library

:prepareComAndroidSupportSupportCompat2540Library

:prepareComAndroidSupportSupportCoreUi2540Library

:prepareComAndroidSupportSupportCoreUtils2540Library

:prepareComAndroidSupportSupportFragment2540Library

:prepareComAndroidSupportSupportMediaCompat2540Library

:prepareComAndroidSupportSupportV42540Library

:prepareComAndroidSupportSupportVectorDrawable2540Library

:prepareComFacebookAndroidAudienceNetworkSdk4261Library

:prepareComGoogleAdsMediationFacebook42600Library

:prepareComGoogleAndroidExoplayerExoplayerR203Library

:prepareComGoogleAndroidGmsPlayServicesAds1142Library

:prepareComGoogleAndroidGmsPlayServicesAdsLicense1142Library

:prepareComGoogleAndroidGmsPlayServicesAdsLite1142Library

:prepareComGoogleAndroidGmsPlayServicesAdsLiteLicense1142Library

:prepareComGoogleAndroidGmsPlayServicesBasement1142Library

:prepareComGoogleAndroidGmsPlayServicesBasementLicense1142Library

:prepareComGoogleAndroidGmsPlayServicesGass1142Library

:prepareComGoogleAndroidGmsPlayServicesGassLicense1142Library

:prepareMeLeolinShortcutBadger1119Library

:prepareOrgApacheCordovaCordovaLib630DebugLibrary

:prepareDebugDependencies

:compileDebugAidl

:compileDebugRenderscript

:generateDebugBuildConfig

:generateDebugResValues

:generateDebugResources

:mergeDebugResources

:processDebugManifest

:processDebugResources

:generateDebugSources

:incrementalDebugJavaCompilationSafeguard

:compileDebugJavaWithJavac

:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

/Users/michaelsolovyov/dev/phonegap-apps/mk1/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:32: error: package android.support.v4.media.app.NotificationCompat does not exist

import android.support.v4.media.app.NotificationCompat.MediaStyle;
                                                      ^

/Users/michaelsolovyov/dev/phonegap-apps/mk1/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:125: error: constructor Builder in class Builder cannot be applied to given types;
        builder = new NotificationCompat.Builder(context, Manager.CHANNEL_ID)
                  ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length
/Users/michaelsolovyov/dev/phonegap-apps/mk1/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:292: error: cannot find symbol

        MediaStyle style;
        ^
  symbol:   class MediaStyle
  location: class Builder

/Users/michaelsolovyov/dev/phonegap-apps/mk1/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:294: error: cannot find symbol
        style = new MediaStyle(builder)

                    ^
  symbol:   class MediaStyle

  location: class Builder

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
4 errors

:compileDebugJavaWithJavac
FAILED

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace
 option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.097 secs

Error: /Users/michaelsolovyov/dev/phonegap-apps/mk1/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/michaelsolovyov/dev/phonegap-apps/mk1/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:32: error: package android.support.v4.media.app.NotificationCompat does not exist
import android.support.v4.media.app.NotificationCompat.MediaStyle;
                                                      ^
/Users/michaelsolovyov/dev/phonegap-apps/mk1/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:125: error: constructor Builder in class Builder cannot be applied to given types;
        builder = new NotificationCompat.Builder(context, Manager.CHANNEL_ID)
                  ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length
/Users/michaelsolovyov/dev/phonegap-apps/mk1/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:292: error: cannot find symbol
        MediaStyle style;
        ^
  symbol:   class MediaStyle
  location: class Builder
/Users/michaelsolovyov/dev/phonegap-apps/mk1/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:294: error: cannot find symbol
        style = new MediaStyle(builder)
                    ^
  symbol:   class MediaStyle
  location: class Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by michaeltangcn** [comment]
Your issue looks same with mine of #1408

**Comment by katzer** [comment]
Closing as its a duplicate
