### ISSUE TITLE
[iOS] Removing badge count once notification is clicked

### ISSUE THREAD

**Issue by kallebornemark** [katzer/cordova-plugin-local-notifications#1411]
I have a question regarding the iOS badge count, as this doesn't seem very well documented at the moment.

I currently have a setup where a weekly notification is scheduled once the app is initially started. As so:

```js
cordova.plugins.notification.local.schedule({
  id: 1,
  title: 'My app',
  text: 'Message',
  foreground: true,
  every: 'week',
  badge: 1,
})
```

**Question**: How do you remove the icon badge number after you've entered the app by clicking the notification?

**Comment by katzer** [comment]
@kallebornemark The plugin itself doesn't clear the badge count except you clear or cancel all notifications.

If I remember correct then iOS did that automatically before iOS 10 came out. If you use `cordova-plugin-badge` then this plugin may do it if you have configured it.

**Comment by katzer** [comment]
Btw. if you use v0.9-beta, then the code looks this:

```js
cordova.plugins.notification.local.schedule({
  id: 1,
  title: 'My app',
  text: 'Message',
  foreground: true,
  trigger: { every: 'week' } // <--
  badge: 1,
});
```

**Comment by kallebornemark** [comment]
@katzer Thanks for the info. Btw, is the `firstAt` attribute removed? How do I specify when the first notification out of weekly repeating notifications should appear?

**Comment by katzer** [comment]
> is the firstAt attribute removed?

Yes...

A notification can trigger (and repeat) from now or by date matching components.

```js
trigger: { at: date }
```

```js
trigger: { in: 2, unit: 'month' } // in 2 months from now
```

```js
trigger: { every: 2, unit: 'month' } // every 2 months from now
```

```js
trigger: { every: { day: 1, year: 2018 } } // every first day of the month in 2018
```

**Comment by kallebornemark** [comment]
@katzer Can `in` and `every` be combined? I would like to say that "Beginning in three days, start sending notifications once a week".

**Comment by katzer** [comment]
No, it cannot - would be the same like `firstAt`

> "Starting in three days, send notifications once a week"

From the 04.11, do every week, e.g. every Sunday:

```js
trigger: { hour: 9, minute: 0, weekday: 7 }
```

__Note:__ _weekday_ is interpreted in the context of the calendar with which it is used. In the Gregorian calendar, Sunday is represented by 1.

**Comment by katzer** [comment]
Not all matching components are fully supported across each platform. With v0.9-beta.0, `weekday`, `weekdayOrdinal` and `weekOfMonth` only work on iOS.

**Comment by kallebornemark** [comment]
Sorry for continuing this very off-topic discussion, but it doesn't seem all too necessary to start a new issue.

Hmm, OK. So there's is reliable way to define "starting in `x` days, send notifications once a `y`" for both iOS and Android? In my case, the `x` must be set programmatically, and the solution is required to work on Android (thinking of `weekday`).

**Comment by katzer** [comment]
There are the ways as described. iOS dropped support to schedule notifications like "firstAt and then every ...".

`weekday` and the other will also come to Android. iOS supports that by native and for Android/Windows it has been implemented by me.

**Comment by kallebornemark** [comment]
Alright, guess I'll have to do what I can with it. Thank for the support!

**Comment by kallebornemark** [comment]
@katzer One last question. Is it possible to programatically set the `text` for each week? (i.e. "You're now in week `<current week>`!")

**Comment by katzer** [comment]
Only possible to update the notification - App need to be running therefore.

**Comment by kallebornemark** [comment]
@katzer You wrote:

> From the 04.11, do every week, e.g. every Sunday:
> `trigger: { hour: 9, minute: 0, weekday: 7 }`

Is that correct, even though you did not use the `every` keyword?

I feel like the docs for repeating notifications could be a bit more extensive.

**Comment by katzer** [comment]
```js
trigger: { every: { hour: 9, minute: 0, weekday: 7 } }
```
