### ISSUE TITLE
[Question] Repeating notification starting in X hours then repeating every Y hours.

### ISSUE THREAD

**Issue by joewoodhouse** [katzer/cordova-plugin-local-notifications#1412]
Question on repeating triggers

## Your Environment

* Plugin version: latest from github, master branch, 
* Platform: iOS
* OS version: 11
* Device manufacturer / model: iOS
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): 4.5.3
* Plugin config
* Ionic Version (if using Ionic) 3.8.0

## Expected Behavior

I'm trying to schedule a notification that starts in 2 hours and then from their repeats every 2 hours. Is this possible? I know from previous versions of the plugin there was this `firstAt` parameter, but from looking at the source now I don't think this is used any more. 

## Actual Behavior

N/A

## Steps to Reproduce

N/A

## Context

Trying to schedule a notification to start in X hours and then repeat every Y hours.

## Debug logs

N/A

**Comment by katzer** [comment]
@joewoodhouse Correct, there's no support for it anymore. Some platforms do not support that anymore.

> I'm trying to schedule a notification that starts in 2 hours and then from their repeats every 2 hours.

How about this way:

```js
trigger: { every: 2, unit: 'hour' }
```

**Comment by joewoodhouse** [comment]
Your suggestion of `trigger: { every: 2, unit: 'hour' }` sounds good. What exactly will that do, will it trigger immediately or in 2 hours time? And then from then on every 2 hours?

**Comment by jlchereau** [comment]
@katzer, I have the same issue:

`trigger: { every: 2, unit: 'hour' }` triggers now + every 2 hours thereafter.

Ideally we also need:

`trigger: { in 2, every: 2, unit: 'hour' }` to trigger in 2 hours + every 2 hours thereafter.

**Comment by katzer** [comment]
@joewoodhouse @jlchereau 

`trigger: { every: 2, unit: 'hour' }`Usually it should not trigger immediately. Then I need to fix that (if possible).

---

I will add something like `firstAt` or `notBefore`, however that will only be supported for Android & Windows.

**Comment by jlchereau** [comment]
I can confirm that it triggers immediately on iPhone SE with iOS 11.1. and Nexus 7 with Android 5.1.1.

**Comment by katzer** [comment]
@jlchereau I haven't tested with Android, but on iOS, it doesn't trigger immediatly...

Thats my code:

```js
cordova.plugins.notification.local.schedule({
    text: 'Scheduled every minute',
    trigger: { every: 1, unit: 'minute' },
    foreground: true,
    sound: true
});
```

I've also tested with `trigger: { every: 2, unit: 'hour' }` and it behaves the same way.

**Comment by joewoodhouse** [comment]
@katzer could you explain what `foreground` does in your example? There is no documentation on this.

**Comment by katzer** [comment]
`foreground:true` means to show the notification even the app is in foreground. Otherwise there will be only a `trigger` callback.

**Comment by katzer** [comment]
@jlchereau 

> I can confirm that it triggers immediately on iPhone SE + iPad Pro with iOS 11.1. and Nexus 7 with Android 5.1.1 with plugin v0.8.5.

You have to use v0.9-beta to use the new triggers!

**Comment by katzer** [comment]
@joewoodhouse You can now use it like that:

```js
trigger: { every: 2, unit: 'hour', firstAt: new Date(2018, 1, 1), count: 10 }
```

**Comment by joewoodhouse** [comment]
Amazing thanks! And if you leave off `count` does it just continue forever?

Back on the `foreground`, does that work on Android and iOS? And how does this interact with `silent` (which I asked another question about https://github.com/katzer/cordova-plugin-local-notifications/issues/1413)

**Comment by joewoodhouse** [comment]
Oh and does `firstAt` work on iOS? I see the commit only mentions Android.

**Comment by katzer** [comment]
> Oh and does firstAt work on iOS? I see the commit only mentions Android.

`firstAt` doesn't and wont work on iOS.

> Amazing thanks! And if you leave off count does it just continue forever?

No, the default value is 5. For iOS it continues forever (`count` isn't supported on iOS)

> Back on the foreground, does that work on Android and iOS?

Yes

> And how does this interact with silent?

`silent` has higher prio than `foreground`. However on iOS the plugin can only suppress silent notifications if the app is running (in foreground). Means for iOS `silent:true` and `foreground:false` are equal.

**Comment by joewoodhouse** [comment]
Thanks for the info @katzer. I'm sure you have this as a todo, but it would be great if all these options were documented, especially which ones do an don't work on iOS/Android.

**Comment by jlchereau** [comment]
I have found the reason for recurring notifications to trigger immediately: the api has changed between v0.8.5 and v0.9.0-beta and README.md only documents the latest.

I recommend that you add a disclaimer at the top of README.md redirecting new users of the last stable version of your plugin to https://github.com/katzer/cordova-plugin-local-notifications/blob/64a6e557fd10dcd66a13b22b6aa0ed50163bcd91/README.md as the most recent README only applies to the pending beta.
