### ISSUE TITLE
[Question] Silent Notifications: iOS vs Android

### ISSUE THREAD

**Issue by joewoodhouse** [katzer/cordova-plugin-local-notifications#1413]
I have a question about the behaviour of silent notifications, which seems to differ between iOS and Android.

In iOS, when a notification is set to silent then it seems to behave depending on whether the app is in the foreground or the background. If it's in the background, the notification will fire as normal. However if the app is in the foreground, the notification won't be displayed but the  "trigger" event will fire. I think this is great - it means when the user is looking at the app and a trigger fires, you can do something within the app, but when they aren't they see the notification.

However Android doesn't seem to behave like this. If a notification is set to silent, the actual notification never appears to be displayed, whether the app is foreground or background. The "trigger" event does fire though.

Could I just check a) is this the expected behaviour and if so b) is there any way to get the iOS behaviour in Android? 

## Your Environment

* Plugin version: latest master from github
* Platform: Android + iOS
* OS version: 8/11
* Device manufacturer / model: N/A
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): 6.3.0/4.5.3
* Plugin config
* Ionic Version (if using Ionic) 3.8.0

## Expected Behavior

N/A

## Actual Behavior

N/A

## Steps to Reproduce

N/A

## Context

N/A

## Debug logs

N/A

**Comment by katzer** [comment]
@joewoodhouse Possible that the behaviour of `silent` notifications may change, however its unlikely that it will behave the same across all platforms.

iOS and Windows __should__ behave like Android. However when the app isn't running anymore, the OS takes over control and will present the notification.

**Comment by katzer** [comment]
@rwillett Here we need to differ between Local & Push Notifications. Local Notifications aren't silent nor do they have such flag. And if the app isn't running then the system will present the notification as specified under app settings.
