### ISSUE TITLE
custom sound audio mp3  is not playing 

### ISSUE THREAD

**Issue by lsajjan** [katzer/cordova-plugin-local-notifications#1414]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment
IBM Mobilefirst 7.1 version Hybrid apps Framework (runs top of cordova )

* Plugin version: "0.8.5"
* Platform: android and ios
* OS version: 8/11
* Device manufacturer / model: Android and Iphone device 
* Cordova version (```cordova -v```):3.6.4
* Cordova platform version (```cordova platform ls```):3.6.4
* Plugin config: manually configure into IBM mobilefirst framwork
* Ionic Version (if using Ionic):1.5.2

## Expected Behavior
when we set the sound property in schedule method with custom audio mp3 it should play but its not playing audio mp3 ,in silent mood notification appears 

## Actual Behavior
when schedule  triggers  on specified time notification message display with custom audio mp3
_Tell us what happens instead_
when schedule triggers on specified time notification message displayed but custom audio mp3 not played ,in silent mood notification appears 
## Steps to Reproduce
localnotification.schedule({
        id: 11,
        text: "Wake up!",
        sound: "file://audio.mp3",
        title: "Meeting in 3 minutes!",
        at: _5_sec_from_now,
        every: "day"
    });

_Reproduce this issue; include code to reproduce, if relevant_

  1.copied the audio file in the android asset folder 
  2.created the common sounds folder copied the audio mp3 
  3.Tried to access the following paths for playing the audio file
 1)sound:"file://audio.mp3",
2)sound:"android.resource://com.Alarm/raw/audio.mp3"
3)sound:"file://android_res/raw/audio.mp3"
4)sound:"file://sounds/audio.mp3"
5)sound:"file://android_asset/www/default/sounds/audio.mp3"

## Context

_What were you trying to do?_

we are using the IBM Mobilefirst framework for Hybrid apps development it built top of cordova
## Debug logs
NA

_Include iOS / Android logs_
NA
  * ios XCode logs
  * Android: $ adb logcat

**Comment by katzer** [comment]
@lsajjan Please try to upgrade to v0.9-beta

**Comment by katzer** [comment]
mp3 files might not work on iOS!
