### ISSUE TITLE
Notifications are cancelled when go on the home or the task manager of Android

### ISSUE THREAD

**Issue by rondey** [katzer/cordova-plugin-local-notifications#1415]
If I have some notifications not yet read, and if i go on the home or task manger with their buttons, every notifications will be automatically deleted/cleared. Is this a normal behavior? [UPDATE] The problem occurs only if I execute the initialization of PushNotification (the pugin is phonegap-plugin-push)

## Environment

* Plugin version: 0.9.0-beta
* Platform: Android
* OS version: Oreo - Nougat 7.0
* Device manufacturer / model: emulator API 26x86 - Huawei P9 lite
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): android 6.3.0

## Expected Behavior

Notifications not yet read still remains in the notification center or trigger some "on" event like clear all/cancel all

## Actual Behavior

Every notifications is deleted

## Steps to Reproduce
Use the index.js -> [index.zip](https://github.com/katzer/cordova-plugin-local-notifications/files/1443848/index.zip). Removing `var push = PushNotification.init({
		android: {
		}
	});`
removes the problem

The issue is similar to this: #953

**Comment by rondey** [comment]
The issue is similar to this: #953

**Comment by rondey** [comment]
I have finally understand what is the issue: phonegap-plugin-push by default clear all pending notifications when the app go in pause. To fix this behavior, just set the clearNotifications to "false":

`var push = PushNotification.init({
    			android: {
            clearNotifications:"false"
    			}
    		});`

**Comment by Elevista** [comment]
@rondey Thank you! you saved me
