### ISSUE TITLE
iOS 9.3.5 further development

### ISSUE THREAD

**Issue by marcoramires** [katzer/cordova-plugin-local-notifications#1416]
## Your Environment

* Plugin version: 0.9.0-beta.0
* Platform: iOS
* OS version: 9.3.5
* Device manufacturer / model: iPhone 5 and iPad Air
* Cordova version (```cordova -v```): 7.0
* Cordova platform version (```cordova platform ls```): 5.3.2
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Local notification in iOS 9.3.5

## Actual Behavior

Plugin not identified

## Steps to Reproduce
  1. Install latest plugin branch (master)
  2. Emulate App in iPhone 5 (9.3.5)

## Context

Plugin no longer working on iOS 9.3.5 in particular. Our app still supports iPhone 4, 5s and iPad Air with iOS 9 installed.

Would you be able to confirm if there will be further support to older version of iOS?

We are currently using the branch 0.8 and hopefully be able to upgrade to the master branch is confirmed. Also, How long are you keeping the 0.8 branch in this repo? 

## Debug logs

  * None

**Comment by katzer** [comment]
@marcoramires The support for iOS 9 or older versions has been dropped because iOS has introduced a new API with iOS 10.

The 0.8 branch wont be removed, however no future development will happen on this branch.

**Comment by marcoramires** [comment]
@katzer thanks. We might have to drop support to iOS 9 users as well. We even thought about running two versions of the plugin but it would be too much dev involved.

Thanks a lot for the great work.
