### ISSUE TITLE
not  Install

### ISSUE THREAD

**Issue by GGwujun** [katzer/cordova-plugin-local-notifications#1418]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:
* Platform:
* OS version:
* Device manufacturer / model:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

_Tell us what should happen_

## Actual Behavior

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by katzer** [comment]
@GGwujun You need to fill the template with content.

**Comment by gehirnmitei** [comment]
I guess he tried to say that using "cordova plugin add cordova-plugin-local-notifications" gives following Error: 
"Error: Failed to fetch plugin org.apache.cordova.device via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found: org.apache.cordova.device@latest"

This command "cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git" is working though

**Comment by katzer** [comment]
OK, the README is a bit ahead of time because I haven't yet published 0.9-beta with it's new plugin id on npm.

**Comment by GGwujun** [comment]
Error: cmd: Command failed with exit code 1 Error output:
C:\Users\gwj12\Desktop\MyApp\platforms\android\src\de\appplant\cordova\plugin\no                                                                                                                                  tification\Manager.java:24: ����: �Ҳ�������
import android.app.NotificationChannel;
                  ^
  ����:   �� NotificationChannel
  λ��: ������ android.app
C:\Users\gwj12\Desktop\MyApp\platforms\android\src\de\appplant\cordova\plugin\no                                                                                                                                  tification\Manager.java:41: ����: �Ҳ�������
import static android.os.Build.VERSION_CODES.O;
^
  ����:   ��̬ O
  λ��: ��
C:\Users\gwj12\Desktop\MyApp\platforms\android\src\de\appplant\cordova\plugin\no                                                                                                                                  tification\Manager.java:109: ����: �Ҳ�������
        if (SDK_INT < O)
                      ^
  ����:   ���� O
  λ��: �� Manager
C:\Users\gwj12\Desktop\MyApp\platforms\android\src\de\appplant\cordova\plugin\no                                                                                                                                  tification\Manager.java:112: ����: �Ҳ�������
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
        ^
  ����:   �� NotificationChannel
  λ��: �� Manager
C:\Users\gwj12\Desktop\MyApp\platforms\android\src\de\appplant\cordova\plugin\no                                                                                                                                  tification\Manager.java:112: ����: �Ҳ�������
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
                                         ^
  ����:   ���� getNotificationChannel(String)
  λ��: ����ΪNotificationManager�ı��� mgr
C:\Users\gwj12\Desktop\MyApp\platforms\android\src\de\appplant\cordova\plugin\no                                                                                                                                  tification\Manager.java:117: ����: �Ҳ�������
        channel = new NotificationChannel(
                      ^
  ����:   �� NotificationChannel
  λ��: �� Manager
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ����δ�������򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
6 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace

**Comment by GGwujun** [comment]
This command "cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git" is working though

is can  working  though

but  when  i  command "cordova  build  android"  not  through

**Comment by katzer** [comment]
@GGwujun See #1408

**Comment by GGwujun** [comment]
not  work

**Comment by GGwujun** [comment]
Your latest commit:

Build Date: 2017-11-01 11:48:06 +0000
Configuration on demand is an incubating feature.
:wrapper

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareAndroidArchLifecycleRuntime100Library
:prepareComAndroidSupportCustomtabs2320Library
:prepareComAndroidSupportSupportCompat2610Library
:prepareComAndroidSupportSupportCoreUi2610Library
:prepareComAndroidSupportSupportCoreUtils2610Library
:prepareComAndroidSupportSupportFragment2610Library
:prepareComAndroidSupportSupportMediaCompat2610Library
:prepareComAndroidSupportSupportV42610Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics1142Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl1142Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImplLicense1142Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsLicense1142Library
:prepareComGoogleAndroidGmsPlayServicesBase1142Library
:prepareComGoogleAndroidGmsPlayServicesBaseLicense1142Library
:prepareComGoogleAndroidGmsPlayServicesBasement1142Library
:prepareComGoogleAndroidGmsPlayServicesBasementLicense1142Library
:prepareComGoogleAndroidGmsPlayServicesTagmanagerV4Impl1142Library
:prepareComGoogleAndroidGmsPlayServicesTagmanagerV4ImplLicense1142Library
:prepareComGoogleAndroidGmsPlayServicesTasks1142Library
:prepareComGoogleAndroidGmsPlayServicesTasksLicense1142Library
:prepareMeLeolinShortcutBadger1119Library
:prepareOrgApacheCordovaCordovaLib623ReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:incrementalReleaseJavaCompilationSafeguard
:compileReleaseJavaWithJavac
:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/project/src/de/appplant/cordova/plugin/notification/Manager.java:24: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
/project/src/de/appplant/cordova/plugin/notification/Manager.java:41: error: cannot find symbol
import static android.os.Build.VERSION_CODES.O;
^
  symbol:   static O
  location: class
/project/src/de/appplant/cordova/plugin/notification/Manager.java:109: error: cannot find symbol
        if (SDK_INT < O)
                      ^
  symbol:   variable O
  location: class Manager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
        ^
  symbol:   class NotificationChannel
  location: class Manager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
                                         ^
  symbol:   method getNotificationChannel(String)
  location: variable mgr of type NotificationManager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:117: error: cannot find symbol
        channel = new NotificationChannel(
                      ^
  symbol:   class NotificationChannel
  location: class Manager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors
:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.813 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/project/src/de/appplant/cordova/plugin/notification/Manager.java:24: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
/project/src/de/appplant/cordova/plugin/notification/Manager.java:41: error: cannot find symbol
import static android.os.Build.VERSION_CODES.O;
^
  symbol:   static O
  location: class
/project/src/de/appplant/cordova/plugin/notification/Manager.java:109: error: cannot find symbol
        if (SDK_INT < O)
                      ^
  symbol:   variable O
  location: class Manager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
        ^
  symbol:   class NotificationChannel
  location: class Manager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
                                         ^
  symbol:   method getNotificationChannel(String)
  location: variable mgr of type NotificationManager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:117: error: cannot find symbol
        channel = new NotificationChannel(
                      ^
  symbol:   class NotificationChannel
  location: class Manager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by katzer** [comment]
@GGwujun See #1408 !!! You need to update your SDK, thats the reason.
