### ISSUE TITLE
Ionic build not creating when installing cordova-plugin-local-notifications plugin

### ISSUE THREAD

**Issue by rohitwebethics** [katzer/cordova-plugin-local-notifications#1419]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: latest master from github
* Platform: android
* OS version: 6.3.0
* Device manufacturer / model: N/A
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): 6.3.0/4.4.0
* Plugin config
* Ionic Version (if using Ionic): 3.17.0

## Expected Behavior
N/A

## Actual Behavior 
N/A
 
_What were you trying to do?_

I was trying to use 'cordova-plugin-local-notifications' plugin and its working using ionic's mobile view app(IonicDevApp). But I tried to create android build then build is not working and giving following error:

**Error:** 

_BUILD SUCCESSFUL

Total time: 0.752 secs
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_1sjzl8sv2qyexz3oui2ibg9jg.run(/home/package/workspace/apps-a806c3da-183/cordova/platforms/android/build.gradle:144)
Checking the license for package Android SDK Platform 26 in /opt/android-sdk/licenses
Warning: License for package Android SDK Platform 26 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 26].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.405 secs
Error: /home/package/workspace/apps-a806c3da-183/cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 26].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output._

**Comment by hamzox** [comment]
Same error!

**Comment by katzer** [comment]
See #1408

**Comment by katzer** [comment]
The stack trace already suggest the solution: Please install SDK 26 first.

**Comment by rohitwebethics** [comment]
but how can I add SDK 26 in ionic1.
