### ISSUE TITLE
iOS crash on using notification when app is closed

### ISSUE THREAD

**Issue by futuraprime** [katzer/cordova-plugin-local-notifications#142]
I've got an app with notifications working great, until one triggers when the app has closed down and gone to sleep or left memory. When you click a notification and it has to spin up the app, the `onclick` event never fires; more importantly, the app crashes after about five seconds (whether or not I have an `onclick` function defined).

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).
