### ISSUE TITLE
Unable to get Local Notification Example Buttons to Respond "Out of the Box"

### ISSUE THREAD

**Issue by GeneralUSA** [katzer/cordova-plugin-local-notifications#1421]
##  Environment

* Plugin version:    $ cordova plugin --list
                              cordova-plugin-device 1.1.0 "Device"
                              cordova-plugin-x-toast 2.3.1 "Toast"

* Platform:      Android
* OS version:       Windows 10 (computer)  
* Device manufacturer / model:    Alcatel One Touch Fierce 4.2.2
* Cordova version (```cordova -v```):   7.1.0
* Cordova platform version (```cordova platform ls```):   $ cordova platform ls
                             Installed platforms:
                               android 6.3.0
                               ios 4.1.1
                               windows 4.2.0
                             Available platforms:
                               blackberry10 ~3.8.0 (deprecated)
                               browser ~5.0.0
                               osx ~4.0.1
                               ubuntu ~4.3.4 (deprecated)
                               webos ~3.7.0
                               www ^3.12.0

* Plugin config           not sure how to determine this
* Ionic Version (if using Ionic)       not using

## Expected Behavior

_Tell us what should happen_
Should be able to see Katzer's de.appplant.cordova.plugin.local-notification EXAMPLE working right out of the box, so-to-speak, without any changes, as shown at[ URL](https://github.com/katzer/cordova-plugin-local-notifications/tree/example#instructions)

## Actual Behavior

_Tell us what happens instead_
Able to build successfully from Git BASH CLI onto the device. However, when I click any green button, nothing happens. The "Device Is Ready" is blinking.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...  Downloaded Zip from [URL](https://github.com/katzer/cordova-plugin-local-notifications/tree/example#instructions)
  2. ...  Unzipped cordova-plugin-local-notifications-example.zip
[cordova-plugin-local-notifications-example.zip](https://github.com/katzer/cordova-plugin-local-notifications/files/1457626/cordova-plugin-local-notifications-example.zip)

  3. ... Opened GIT BASH and navigated to the folder location. Ran commands (not necessarily in below order -- trial and error before finally got the EXAMPLE onto the device, which is plugged into the computer)
          $ cordova build android
                        ...
                                :packageDebug UP-TO-DATE
                                :assembleDebug UP-TO-DATE
                                :cdvBuildDebug UP-TO-DATE
                                BUILD SUCCESSFUL
        $ cordova run android
        $ cordova platform remove android
       $ cordova platform add android
                Creating Cordova project for the Android platform:
                        Path: platforms\android
                        Package: de.appplant.localnotification.example
                        Name: NotificationExample
                        Activity: MainActivity
                        Android target: android-26
                Subproject Path: CordovaLib
                Android project created with cordova-android@6.3.0
                Installing "cordova-plugin-device" for android
                Installing "cordova-plugin-x-toast" for android
                --save flag or autosave detected
                Saving android@~6.3.0 into config.xml file ... 

## Context

_What were you trying to do?_
Simply see the EXAMPLE in action and trying to learn how to eventually install/copy into a first-time app I've nearly completed. Very new and every turn is a new experience.

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

I ran the "adb logcat" command, which resulted in a pretty long output in Git Bash. Considering I've not changed anything, not sure if Debug log is needed. If so, I can copy paste into a text file and include.

Thanks for any insight on how to see the Android device in action. Perhaps the device is too old; hopefully not; if so, then I'd like a backward compatible solution, if possible. I have not yet tested on iOS (access only to 9 and 10, though I do also have access via Visual Studios to virtual devices: Android, Windows, & iPhone).

Thanks again.

**Comment by katzer** [comment]
@GeneralUSA So whats your question and what code you try to execute?

**Comment by GeneralUSA** [comment]
Hi @Katzer. Right now just simply trying to see the Schedule "In 5 sec" run on the device. I haven't done anything with your code. Just pulled it down and installed it on the device. When I click any of the [GREEN buttons](https://github.com/katzer/cordova-plugin-local-notifications/tree/example#instructions) as shown on your example under "Instructions" -- when I click the installed Local-Notification Example app, nothing happens.

**Comment by katzer** [comment]
@GeneralUSA The sample app isn't yet up-to-date. The code isn't compatible with v0.9-beta.

There's the `example-x` branch you should better use.

**Comment by GeneralUSA** [comment]
Okay. Thank you. I will look for it.

**Comment by joe-mutti** [comment]
@generalUsa how did you solved the issue? I am still unable to get it working

**Comment by GeneralUSA** [comment]
Issue is still not solved for me. I installed the "cordova-plugin-local-notifications-example-x" per @katzer suggestion, but nothing triggers. I see the app on my device, but it does nothing, no popup question regarding allow notification, cannot schedule anything either. As for tutorials, as a complete newbie, unsure which folder to use to do a [Single Schedule based on instructions](https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling#schedule-single).

**Comment by katzer** [comment]
@GeneralUSA

> Device manufacturer / model: Alcatel One Touch Fierce 4.2.2

Android 4.2 is not supported, min. Android 5.
