### ISSUE TITLE
[Question] Is there an issue when cancel is called right after schedule?

### ISSUE THREAD

**Issue by andrelanka** [katzer/cordova-plugin-local-notifications#1423]
## Your Environment

* Plugin version: 0.8.5
* Platform: Android
* OS version: multiple
* Device manufacturer / model: multiple
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): android 6.3.0
* Plugin config none (not sure what to write here)
* Ionic Version (if using Ionic)

## Expected Behavior

Notifications are displayed.

## Actual Behavior

On many devices we're using, we miss notifications. On the other hand we tested devices where it works flawlessly. 

## Steps to Reproduce

Unfortunately, it's hard to reproduce...

## Context

Our setup is that a server determines the actual notifications dates and sends it regularly to the app. After receiving, the app schedules the new dates and right after that it cancels all notifications that are obsolete now (may include upcoming notifications). Is there an issue with that? Do we need to cancel the notifications in the callback of the schedule (to avoid concurrency issues)? Any hint is highly appreciated as the app is the crucial part of a research project (University of Potsdam) and there is not much time left to fix the issue.

## Debug logs

No problems visible from the log.

**Comment by katzer** [comment]
Servus, 

> Do we need to cancel the notifications in the callback of the schedule (to avoid concurrency issues)?

Genau!

**Comment by andrelanka** [comment]
Great to hear! Thanks a lot for your fast reply.
