### ISSUE TITLE
Notification is sometimes not removed

### ISSUE THREAD

**Issue by ThorvaldAagaard** [katzer/cordova-plugin-local-notifications#1424]
Only on Android it happens that, when clicking on the notification and opening the application, the notification will still be there

## Your Environment
Windows 10 for development

* Plugin version:
```
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
```
* Ionic Version (if using Ionic)
```
cli packages: (C:\Users\thorv\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.2.3 browser 5.0.1 ios 4.5.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.1
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : D:\Dokumenter\Android\sdk

Misc:

    backend : legacy
```
## Expected Behavior

In most situation the notification is removed and all is working fine

## Actual Behavior

Sometimes it stays there and I can try to click on it (and thus open the app) as many times as I like, it will first go away when the application is terminated

## Steps to Reproduce

I am not able to recreate this problem, but would appriciate any help to debug the problem

## Context

Getting notifictions while app is running in the background

## Debug logs
None

**Comment by katzer** [comment]
Any code how to reproduce?

**Comment by ThorvaldAagaard** [comment]
That is a problem as it is part of a large app, and I haven't been able to isolate and consistent reproduce it. So currently I am more looking for help to debug the problem. It could be some logs in the plugin, so I could document it is executed but not closed

**Comment by ThorvaldAagaard** [comment]
Unfortunately I can't switch to the new version yet as the @ionic-native haven't been updated yet. But if you add some log features it would be ok to focus only on the new version

**Comment by katzer** [comment]
@ThorvaldAagaard Are you able to debug the code by adding breakpoints?

Here is where you should start:
https://github.com/katzer/cordova-plugin-local-notifications/blob/0.8.5/src/android/notification/ClickActivity.java#L41

**Comment by ThorvaldAagaard** [comment]
My IDE is Visual Code and combined with Android Studio I haven't been that successful in debugging, but have managed to make a code changes on the java-side :-)

But looking at the suggested place in the code it could look like the problem could be

isRepeating()

In the Ionic wrapper there is no functionality that allows repeating, and my code looks like this:
```
            // Send notification
            self.notification.schedule([{
                id: self.notificationId++,
                title: geme.name,
                text: geme.content,
                icon: "res://screen.png",
                sound: self.platform.is('android') ? 'file://sound.mp3' : 'file://beep.caf',
                data: { secret: geme.id },
                at: new Date(new Date().getTime() + 1000)
            }]);
```

So maybe the boolean behind isRepeating can be uninitialized, and thus explaing the random behavior

**Comment by ThorvaldAagaard** [comment]
Update: It seems I have an option every?:string that should default to 0 (which means that the system triggers the local notification once)

**Comment by katzer** [comment]
Since you use 0.8.5 - which is the latest (stable) version however does not support the latest iOS. If you have some code to reproduce (with v0.9 preferable) then I can investigate where's the issue. Other then that I could not reproduce the issue.
