### ISSUE TITLE
Update changelog for 0.9

### ISSUE THREAD

**Issue by marcovtwout** [katzer/cordova-plugin-local-notifications#1426]
@katzer Recently merged changes from the 0.9 branch into master. The first beta's have also been released. But I'm not sure what changed exactly.

Changes and upgrade instructions are expected to appear in CHANGELOG.md or UPGRADE.md. Can they be added? I'm not sure how many overlaps with the wiki page https://github.com/katzer/cordova-plugin-local-notifications/wiki/Upgrade-Guide as it seems to be mostly about 0.8

**Comment by Mumumurilo** [comment]
I'd love to see that too. There are several new properties in the 0.9 release that I'd like to understand what they exactly do.

**Comment by marcovtwout** [comment]
@katzer Could you at least take a first shot at this? :) It would really help to encourage people to use and test the beta version!

**Comment by katzer** [comment]
I know... Just need to find the time for it.
