### ISSUE TITLE
Ionic Native Actions Property Support

### ISSUE THREAD

**Issue by mino922** [katzer/cordova-plugin-local-notifications#1428]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

Does the ionic native plugin support the actions property?

## Your Environment

* Plugin version: 
* Platform: iOS
* OS version: 11
* Device manufacturer / model: iPhone 8
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): ios 4.4.0
* Plugin config
* Ionic Version (if using Ionic) 3.18.0

## Expected Behavior

I am unable to use the actions property. 

## Actual Behavior

I would like the user to be able to respond yes or no when they view a notification. 

## Steps to Reproduce

N/A

## Context

Issue a notification and have the user answer yes or no.

## Debug logs

N/A

**Comment by katzer** [comment]
@mino922 I know about. Therefore it is necessary to update the ionic-native wrapper to be compatible with v0.9. But they nor myself have found the time yet.

**Comment by mino922** [comment]
@katzer thank you for the update. Do you have an estimated time frame to deliver this feature?

**Comment by katzer** [comment]
@mino922 Actually I have enough to do with my plugins itself. The Ionic code does not come from myself. However many using it and I will will try to support their code with PR's. For now I need to release the plugin first. So there is no time frame...
