### ISSUE TITLE
showing trigger is unknown property

### ISSUE THREAD

**Issue by rrahul14** [katzer/cordova-plugin-local-notifications#1429]
## Your Environment

* Plugin version:0.8.4
* Platform: android
* OS version:4.4.4
* Device manufacturer / model: xiomi redmi 2
* Cordova version (```cordova -v```):6.5.0
* Cordova platform version (```cordova platform ls```):

## Expected Behavior
It should schedule notification after one hrs
## Actual Behavior
It was immediately showing local notification

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_
1) 
  cordova.plugins.notification.local.schedule({
    title: 'Design team meeting',
    text: '3:00 - 4:00 PM',
    trigger: { in: 1, unit: 'hour' }
});
2) 
cordova.plugins.notification.local.schedule({
    title: 'Design team meeting',
    text: '3:00 - 4:00 PM',
    trigger: { in: 5, unit: 'minute' }
});
## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by katzer** [comment]
@rrahul14 Your code is not compatible with `v0.8.x`. Use the tagged README/wiki for your version or upgrade to `v0.9-beta`

**Comment by rrahul14** [comment]
Hi,
Thanks for reply. I will check it by installing other version plugin.
Thanks again.

**Comment by rrahul14** [comment]
I tried to install and after that i was getting error  for installation with v0.9-beta 

Error: Failed to fetch plugin cordova-plugin-local-notification@v0.9-beta via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: No compatible version found: cordova-plugin-local-notification@'v0.9-beta'
Valid install targets:
["0.8.4","0.9.0-beta.1"]

then i installed 0.9.0-beta.1 and plugin get installed but i got following error for making build

 Note: /home/tnex/Documents/QrLocal/cordova/platforms/android/src/de/appplant/cordova/plugin/localnotification/TriggerReceiver.java uses or overrides a deprecated API.
[INF] [shellscript] Note: Recompile with -Xlint:deprecation for details.
[INF] [shellscript] 6 errors
[INF] [shellscript] 
[INF] [shellscript] FAILURE: Build failed with an exception.
[INF] [shellscript] 
[INF] [shellscript] * What went wrong:
[INF] [shellscript] Execution failed for task ''':compileDebugJavaWithJavac'''.
[INF] [shellscript] > Compilation failed; see the compiler error output for details.
[INF] [shellscript] 
[INF] [shellscript] * Try:
[INF] [shellscript] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[INF] [shellscript] Error: /home/tnex/Documents/QrLocal/cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
[INF] [shellscript] Note: Some input files use or override a deprecated API.
[INF] [shellscript] Note: Recompile with -Xlint:deprecation for details.
[INF] [shellscript] Note: Some input files use or override a deprecated API.
[INF] [shellscript] Note: Recompile with -Xlint:deprecation for details.
[INF] [shellscript] /home/tnex/Documents/QrLocal/cordova/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:24: error: cannot find symbol
[INF] [shellscript] import android.app.NotificationChannel;
[INF] [shellscript]                   ^
[INF] [shellscript]   symbol:   class NotificationChannel
[INF] [shellscript]   location: package android.app
[INF] [shellscript] /home/tnex/Documents/QrLocal/cordova/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:41: error: cannot find symbol
[INF] [shellscript] import static android.os.Build.VERSION_CODES.O;
[INF] [shellscript] ^
[INF] [shellscript]   symbol:   static O
[INF] [shellscript]   location: class
[INF] [shellscript] /home/tnex/Documents/QrLocal/cordova/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:109: error: cannot find symbol
[INF] [shellscript]         if (SDK_INT < O)
[INF] [shellscript]                       ^
[INF] [shellscript]   symbol:   variable O
[INF] [shellscript]   location: class Manager
[INF] [shellscript] /home/tnex/Documents/QrLocal/cordova/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
[INF] [shellscript]         NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
[INF] [shellscript]         ^
[INF] [shellscript]   symbol:   class NotificationChannel
[INF] [shellscript]   location: class Manager
[INF] [shellscript] /home/tnex/Documents/QrLocal/cordova/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
[INF] [shellscript]         NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
[INF] [shellscript]                                          ^
[INF] [shellscript]   symbol:   method getNotificationChannel(String)
[INF] [shellscript]   location: variable mgr of type NotificationManager
[INF] [shellscript] /home/tnex/Documents/QrLocal/cordova/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:117: error: cannot find symbol
[INF] [shellscript]         channel = new NotificationChannel(
[INF] [shellscript]                       ^
[INF] [shellscript]   symbol:   class NotificationChannel
[INF] [shellscript]   location: class Manager
[INF] [shellscript] Note: /home/tnex/Documents/QrLocal/cordova/platforms/android/src/de/appplant/cordova/plugin/localnotification/TriggerReceiver.java uses or overrides a deprecated API.
[INF] [shellscript] Note: Recompile with -Xlint:deprecation for details.
[INF] [shellscript] 6 errors
[INF] [shellscript] 
[INF] [shellscript] FAILURE: Build failed with an exception.
[INF] [shellscript] 
[INF] [shellscript] * What went wrong:
[INF] [shellscript] Execution failed for task ''':compileDebugJavaWithJavac'''.
[INF] [shellscript] > Compilation failed; see the compiler error output for details.

**Comment by katzer** [comment]
You have to compile with the latest Android SDK.
