### ISSUE TITLE
Events not registered on iOS11

### ISSUE THREAD

**Issue by jonasbieler** [katzer/cordova-plugin-local-notifications#1430]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.1
* Platform: iOS
* OS version: iOS 11.2
* Device manufacturer / model: iPhone 6 Plus
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): 4.5.3
* Plugin config:
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-badge 0.8.5 "Badge"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-local-notification 0.9.0-beta.1 "LocalNotification"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4 "Cordova WKWebView Engine"
phonegap-plugin-barcodescanner 7.0.0 "BarcodeScanner"

## Expected Behavior

Expecting .on('click', ...) to work.

## Actual Behavior

None of the events gets triggered.

## Steps to Reproduce

  my script:
```js
document.addEventListener('deviceready', function () {
                          cordova.plugins.notification.local.schedule({
                                                                      id: 1,
                                                                      title: 'test',
                                                                      text: 'lorem',
                                                                      trigger: { in: 10, unit: 'second' }
                                                                      });
                        
                          cordova.plugins.notification.local.on('click', function (notification) {
                                                                alert(notification.text);
                                                                });
                
                          }, false);
```
## Context

Was trying to alert something on notification click. Scheduling of events works perfectly.
Please let me know if I have to provide further information as I am new to cordova.

**Comment by katzer** [comment]
Can't reproduce...

**Comment by jonasbieler** [comment]
Alright, the problem occured because of my index.js looking for an element with the id "deviceready" which simply didn't existed.
Plugin works perfectly, sorry to bother you. Was a mistake on my side because I'm new to Cordova.
