### ISSUE TITLE
Angular 4 routing doesn't work inside click handler

### ISSUE THREAD

**Issue by Pichardito** [katzer/cordova-plugin-local-notifications#1431]
Plugin version: 0.9.0-beta.1
Platform: iOS
OS version: iOS 11.2
Device manufacturer / model: iPhone 6 Plus
Cordova version (cordova -v): 6.5.0
Cordova platform version (cordova platform ls): 4.3.1
Plugin config:
cordova-plugin-badge 0.8.5 "Badge"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-local-notification 0.9.0-beta.1 "LocalNotification"
cordova-plugin-whitelist 1.3.3 "Whitelist"

Expected behavior:  When clicking on notification user is routed to specific view of the app.
Actual behavior:  User is routed to home page but home page view appears split with un-styled markup on the upper half of the screen and the home page at the bottom.

My code looks like this:

```
cordova.plugins.notification.local.on("click", function (notification) {    
            this.router.navigate(["view", viewId, "site", siteId]);
        });
```

**Comment by znegva** [comment]
Hi,

you also have to provide the scope (`this`).
Try out:
```js
cordova.plugins.notification.local.on(
   "click",
   function (notification) {    
            this.router.navigate(["view", viewId, "site", siteId]);
   },
   this
);
```
