### ISSUE TITLE
Failed on phonegap online-build

### ISSUE THREAD

**Issue by abomokhahmed** [katzer/cordova-plugin-local-notifications#1434]
## Your Environment

* Plugin version: don't know, I think last update
* Platform: phonegap
* OS version: both android and ios
* Device manufacturer / model: mine is samsung note 4
* Cordova version (```cordova -v```): don't know (online-build)
PhoneGap (iOS / Android / Windows)
cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3)
* Cordova platform version (```cordova platform ls```): don't know (online-build)
* Plugin config: I will paste my config.xml at the end
* Ionic Version (if using Ionic) using onsen 1

I am using phonegap online-build, so I don't have all information you need, but I can provide you the config.xml file

## Expected Behavior

Phonegap would accept my www files and return back an apk file to submit to google play.

## Actual Behavior

I get this error:
"Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: Manager.java - You can fix this here"

## Context

install "cordova-plugin-local-notifications" on my app

## Debug logs

Here my config.xml:
...
<preference name="orientation" value="default" />
	<preference name="android-build-tool" value="gradle" />
	<preference name="permissions" value="none"/>
	<preference name="launchMode" value="singleTask"/>

	<gap:plugin name="cordova-plugin-whitelist" source="npm" />
    <gap:plugin name="phonegap-plugin-push" source="npm" spec="1.5.3" />
    <gap:plugin name="cordova-plugin-device" source="npm" />		
	<gap:plugin name="cordova-plugin-inappbrowser" source="npm" />		
	<gap:plugin name="cordova-plugin-splashscreen" source="npm" />	
	<gap:plugin name="cordova-plugin-geolocation" source="npm" />
	<gap:plugin name="cordova-plugin-network-information" source="npm" />
<gap:plugin name="https://github.com/katzer/cordova-plugin-local-notifications" source="npm" />

	<gap:splash src="splash.png" />
	<preference name="AutoHideSplashScreen" value="false" />  	
    <preference name="SplashScreenDelay" value="10000" />  
	
    <access origin="*" />
    <access origin="tel:*" launch-external="yes" />
    
    <gap:config-file platform="android" parent="/manifest">
        <supports-screens android:xlargeScreens="true" android:largeScreens="true" android:smallScreens="true" />
        <application android:theme="@android:style/Theme.NoTitleBar" >            
        </application>
    </gap:config-file>
...

This error happens only on android.
Do you have any idea how to fix it because I searched all over the web with no result.
the error again is:
"Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: Manager.java - You can fix this here"

Thanks a lot

**Comment by abomokhahmed** [comment]
Hii
After some search I found this link:
http://phonegap-plugins.com/plugins/katzer/cordova-plugin-local-notifications

They suggested the following to build online:

Add the following xml to your config.xml to always use the latest version of this plugin:

<gap:plugin name="de.appplant.cordova.plugin.local-notification" />
or to use an specific version:
<gap:plugin name="de.appplant.cordova.plugin.local-notification" version="0.7.5" />

But even using their instructions gets this notice on phongap:
    "plugin unsupported: de.appplant.cordova.plugin.local-notification @ 0.8.5"
And this error:
    "Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: Manager.java - You can fix this here"

**Comment by daksamedia** [comment]
Hi all!

Have you guys test this on the config.xml ?

>  <gap:plugin name="de.appplant.cordova.plugin.local-notification" source="npm" />
> <gap:plugin name="cordova-plugin-local-notifications-npm" version="0.7.5" />

**Comment by katzer** [comment]
Please use `cordova-plugin-local-notification`. The ownership on npm has been transferred to me now.

```xml
<gap:plugin name="cordova-plugin-local-notification" source="npm" />
```

**Comment by abomokhahmed** [comment]
@katzer Thanks for responding.
I get the following error when uploading my version with 
<gap:plugin name="cordova-plugin-local-notification" source="npm" />
on my config.xml and may help you resolve this issue:

**BUILD FAILED**

Total time: 4.839 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/project/src/de/appplant/cordova/plugin/notification/Manager.java:24: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
/project/src/de/appplant/cordova/plugin/notification/Manager.java:41: error: cannot find symbol
import static android.os.Build.VERSION_CODES.O;
^
  symbol:   static O
  location: class
/project/src/de/appplant/cordova/plugin/notification/Manager.java:109: error: cannot find symbol
        if (SDK_INT < O)
                      ^
  symbol:   variable O
  location: class Manager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
        ^
  symbol:   class NotificationChannel
  location: class Manager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
                                         ^
  symbol:   method getNotificationChannel(String)
  location: variable mgr of type NotificationManager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:117: error: cannot find symbol
        channel = new NotificationChannel(
                      ^
  symbol:   class NotificationChannel
  location: class Manager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by katzer** [comment]
Please see #1408
