### ISSUE TITLE
App crashes when it tries to set alarm

### ISSUE THREAD

**Issue by ivanov84** [katzer/cordova-plugin-local-notifications#1437]
## Your Environment

* Plugin version: 0.9.0-beta.1 from 21 november
* Platform: Android
* OS version: 4.3
* Device manufacturer / model: Galaxy S3
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): 6.3.0
* Plugin config
"cordova-plugin-splashscreen": "4.1.0",
  "cordova-plugin-google-analytics": "1.8.2",
  "cordova-plugin-localization-strings": "1.0.1",
  "phonegap-plugin-push": "1.10.5",
  "cordova-plugin-app-event": "1.2.1",
  "cordova-plugin-app-version": "0.1.9",
  "cordova-plugin-extension": "1.5.3",
  "cordova-plugin-dialogs": "1.3.4",
  "cordova-plugin-globalization": "1.0.8",
  "cordova-plugin-inappbrowser": "1.7.2",
  "cordova-plugin-whitelist": "1.3.3",
  "cordova-plugin-camera": "3.0.0",
  "cordova-plugin-admobpro": "2.29.29",
  "cordova-plugin-crosswalk-webview": "2.2.0",
  "cordova-plugin-apprate": "1.3.0",
  "cordova-plugin-market": "1.2.0",
  "cordova-plugin-x-socialsharing": "5.1.6",
  "cordova-plugin-inapppurchase": "1.1.0",
  "cordova-plugin-device": "1.1.7",
  "cordova-plugin-badge": "0.8.5",
  "cordova-plugin-local-notification": "0.9.0-beta.1" 
* Ionic Version (if using Ionic) 3.18.0

## Expected Behavior

Show notification in 10 seconds

## Actual Behavior

App crushes.

logcat:
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
java.lang.NoSuchMethodError: android.app.AlarmManager.setExact
at de.appplant.cordova.plugin.notification.Notification.schedule(Notification.java:215)
at de.appplant.cordova.plugin.notification.Manager.schedule(Manager.java:100)
at de.appplant.cordova.plugin.localnotification.LocalNotification.schedule(LocalNotification.java:272)
at de.appplant.cordova.plugin.localnotification.LocalNotification.access$400(LocalNotification.java:59)
at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:144)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:841)

## Steps to Reproduce

Code:
cordova.plugins.notification.local.schedule({
  title: "tra la la",
  text: "Oba Oba obana",
  trigger: { in: 10, unit: 'second' }
});

## Context

Tryed:
cordova.plugins.notification.local.schedule({
  title: "tra la la",
  text: "Oba Oba obana"
});
It worked immediately.

**Comment by katzer** [comment]
Android 4.3 is not supported. Android 4.4+

**Comment by ivanov84** [comment]
@katzer Thank you for yout reply.

I'm very grateful to you for such a cool plugin. Could you tell me how to make older devices so that the application does not crash when the plugin is called?

**Comment by ivanov84** [comment]
@katzer Updated the plugin today and the application does not crash. Thank you! 😄
