### ISSUE TITLE
Error when using addActionGroup

### ISSUE THREAD

**Issue by AustinFelipe** [katzer/cordova-plugin-local-notifications#1438]
Hey guys, I'm trying to follow the instruction presented in the README file but I'm facing a problema when using ```cordova.plugins.notification.local.addActionGroup```. As follows:

``` javascript
Uncaught (in promise) TypeError: this.core.registerActionGroup is not a function
    at Object.exports.addActionGroup (local-notification.js:270)
    at Object.sendNotification (index.js:54)
    at cordova.plugins.notification.local.hasPermission.granted (index.js:40)
    at local-notification-util.js:321
    at Object.callbackFromNative (cordova.js:294)
    at processMessage (cordova.js:1120)
    at processMessages (cordova.js:1143)
    at <anonymous>
```

## Your Environment

* Plugin version: **lastest master branch**
* Platform: **Android**
* OS version: **Windows 10**
* Device manufacturer / model: **Samsung S6**
* Cordova version (```cordova -v```): **7.1.0**
* Cordova platform version (```cordova platform ls```): **android 6.3.0**

## Expected Behavior

It should create a default action group

## Actual Behavior

Giving me an error message

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. New project
  2. Include android
  3. Include cordova-plugin-local-notification from master branch
  4. Run

## Context

Doing tests following instructions

**Comment by AustinFelipe** [comment]
Changing style

**Comment by katzer** [comment]
Thanks!
