### ISSUE TITLE
Open/Launch App on action button click

### ISSUE THREAD

**Issue by kashifsulaiman** [katzer/cordova-plugin-local-notifications#1439]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

When i click on title/text area on push notification, it launches the app if it was suspended, but it doesn't launch on any action button. I've tried adding 
```
$rootScope.$on('$cordovaLocalNotification:<action-name>',
        function (event, notification, state) {

        });
```
I get the response when i launch app manually.

## Your Environment

* Plugin version: 0.9.0-beta.1
* Platform: Android
* OS version: Android-26
* Device manufacturer / model: Motorola XT-1060
* Cordova version (```cordova -v```): 6.5.0
* Cordova platform version (```cordova platform ls```): android 6.1.2
* Plugin config ?
* Ionic Version (if using Ionic) 1.7.14

## Expected Behavior

Open/Launch App on action button click

## Actual Behavior

Not Opening/Launching App on action button click

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Push a notification with action buttons
  2. Suspend or close the app
  3. Click on any action button
  4. It won't open the app

## Context

Trying to open the app on clicking the action buttons

**Comment by katzer** [comment]
Actions have their own `launch` property:
https://github.com/katzer/cordova-plugin-local-notifications#properties-1

**Comment by kashifsulaiman** [comment]
@katzer Sorry and Thanks.

**Comment by Syirrus** [comment]
Can you open a Url when clicking on a notification while the app is closed?

**Comment by usmanshaikh404** [comment]
@Syirrus 
Do you find any solution?
how to open page on clicking on notification when app is closed not even running in the background

**Comment by ghonche-yqr** [comment]
> Can you open a Url when clicking on a notification while the app is closed?

I have the same problem. I need to open a page when the notification or a button in notification is clicked. I can get the action when app is in foreground or background. But no event is triggered when app is closed. any solution?
