### ISSUE TITLE
How do I specify res icon on Android?

### ISSUE THREAD

**Issue by t2wu** [katzer/cordova-plugin-local-notifications#1440]
On LG Stylus I currently have a square icon. I do have icons made just for notifications. How do I specify it while sending the notification?
I have the following:
```
  cordova.plugins.notification.local.schedule({
    id: 10,
    title: notif.title,
    text: notif.text,
    //trigger: { at: null}, data: {}
    icon: 'res://notification_icon.png',
    trigger: {}, data: {}, actions: undefined
  });
```

The icons are located such as under platform/android/res/drawable-land-xhdpi/notification_icon.png. And it still show up as a white square.

## Your Environment

* Plugin version: 0.9.0-beta.1
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: LG Stylus 3
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): android 6.3.0
* Plugin config (what config?)
* Ionic Version (if using Ionic) (Not using Ionic)

## Expected Behavior

Should have a white bitmap showing an app icon.

## Actual Behavior

Just a white square.

## Steps to Reproduce

1. Put icon under all the drawable-land-* drawable-port-* and the minimap-* directories such as platform/android/res/drawable-land-xhdpi/notification_icon.png.

2. Notify by
```
  cordova.plugins.notification.local.schedule({
    id: 10,
    title: notif.title,
    text: notif.text,
    //trigger: { at: null}, data: {}
    icon: 'res://notification_icon.png',
    trigger: {}, data: {}, actions: undefined
  });
```

## Context

Send a local notification.

## Debug logs

I guess not relevant? There is no log.

**Comment by djasil** [comment]
Remove the .png extension and see if it works:
`icon: 'res://notification_icon',`

**Comment by katzer** [comment]
Depends on what icon - a small icon resource is required on Android

```js
{ smallIcon: 'res://notification_icon' }
```
