### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by wuilmerj24** [katzer/cordova-plugin-local-notifications#1443]
in this version the progress bar will be updatable?

**Comment by katzer** [comment]
Yes it is. Think the README shows a sample.

**Comment by wuilmerj24** [comment]
@katzer  If I add the following:
var valueProgess
cordova.plugins.notification.local.schedule ({
  Title: 'Synchronization in progress',
  text: 'Copied 2 of 10 files', 
  progressBar: {value: valueProgess}
});
and with just updating the value of said variable is updated?

**Comment by katzer** [comment]
Yes, like here for example: #1459
