### ISSUE TITLE
Documentation for repeating notification is misleading

### ISSUE THREAD

**Issue by RicardoDMelo** [katzer/cordova-plugin-local-notifications#1445]
## Your Environment

* Plugin version: 0.9.0-beta.1
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: Motorola Moto X Play
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): 6.3.0
* Plugin config: default
* Ionic Version (if using Ionic): 3.19.0

## Expected Behavior

A notification should appear every 3 minutes. 

## Actual Behavior

A notification appear after 3 minutes, I manually remove it from the notification bar, and no other notification appear after more 3 minutes.

## Steps to Reproduce

1. Schedule a notification with this code:
`      cordova.plugins.notification.local.schedule({
        id: 10,
        icon: 'file://assets/imgs/logo.png',
        title: 'Test Title',
        text:  'Test description',
        trigger: {
          unit: 'minute',
          every: 3
        }
      });`
2. Wait 3 minutes
3. Remove notification manually
4. Wait another 3 minutes
5. Nothing happens

## Context

I was trying to make some kind of an alarm, customized by the user. I think my problem is the repeat structute on the options object. Documentation is misleading.
Here (https://github.com/katzer/cordova-plugin-local-notifications#properties-2) it says to use "every" and "count" inside a "trigger" property. I don't know what count does, too.
Here (https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling#interface) it says to use every, without trigger object.
In a closed issue I found this "trigger: { any: 'minute', every: 3 }" and thought it was right, but looks like it doesn't work too.

What is the correct way to repeat an notification?
Documentation should be consistent.

## Debug logs

Couldn't filter logs.

**Comment by brunnohofmann** [comment]
Did you solve the problem?

**Comment by RicardoDMelo** [comment]
I'm afraid not. I'm trying to read the plugin code for android, but there's so many layers that I'm a bit lost, maybe tomorrow I'll figure out, if help don't come.

**Comment by brunnohofmann** [comment]
I couldnt wait. I used the background mode to run forever a function setInterval with a time there I needed. Sometimes it doesnt work... but in the major of time yes!

**Comment by RicardoDMelo** [comment]
Do you mind to share the code?

**Comment by brunnohofmann** [comment]
Check the Background Mode plugin (from Katzer too). Then mix with the Local Notification plugin.

`this.repeticaoAgua = setInterval(function(){
     this.localNotifications.schedule({
      id: 1,
      icon: 'res/iconred.png',
      title: 'Hora de tomar água!'
    });
}.bind(this), (60000));`

I putted the interval on a var to cancel it if when I want

`cancelAguaNotification(){
    clearInterval(this.repeticaoAgua);
  }`

**Comment by RicardoDMelo** [comment]
Great, I'll give it a try!

**Comment by katzer** [comment]
I tried with master using Android Emulator and Samsung and it worked as expected. Even I clear the notification it pops-up again after.

The relevant entry point in the code is here:
https://github.com/katzer/cordova-plugin-local-notifications/blob/0.9.0-beta.1/src/android/ClearReceiver.java#L49
