### ISSUE TITLE
Plugin does not work with wkvwebview engine

### ISSUE THREAD

**Issue by pitAlex** [katzer/cordova-plugin-local-notifications#1448]
Hi,
With the wkwebview engine, the javascript part of the plugin does not work as inside it "this" is window. Thus it throws errors like:

Undefined is not an object evaluating : this.core.requestPermission
I made a little hack like this and it fixed it:

```
var _this = this;
.......
setTimeout(function(){
    if(_this instanceof Window || !_this) _this = cordova.require('cordova-plugin-local-notification.LocalNotification');
})
```

But a proper fix should be implemented

**Comment by katzer** [comment]
@pitAlex What plugin version?

**Comment by pitAlex** [comment]
The latest version

**Comment by katzer** [comment]
Cant reproduce

**Comment by katzer** [comment]
Please provide a code snippet.

**Comment by pitAlex** [comment]
I agree, it stopped happening for me too. Perhaps I just had some miss configuration. Also, I couldn't reproduce in a sample app so if its some scripts conflict it will be hard to find.
