### ISSUE TITLE
Error build after install

### ISSUE THREAD

**Issue by BeachNight31** [katzer/cordova-plugin-local-notifications#1450]
## MyEnvironment

* Plugin version : 0.9.0-beta.1
* Platform : android
* Cordova version : 7.0.1
* Ionic Version: 3.19.0

## Context

After installing the plugin I can not build my application because of the Manager.java. screenshot in link.

## Images

![capture](https://user-images.githubusercontent.com/6816374/33550259-8b6724f2-d8ed-11e7-8d49-ce0a5cb6370d.JPG)

**Comment by OctoberCat** [comment]
For this moment plugin version 0.9.* incompatible with Ionic. Try to use 0.8.5.

**Comment by fowlerjg90** [comment]
+1

**Comment by katzer** [comment]
You have to compile with the latest Android SDK even your runtime version is lower than Android 8
