### ISSUE TITLE
Unable to use in Ionic for iOS platform 

### ISSUE THREAD

**Issue by davidkuek** [katzer/cordova-plugin-local-notifications#1452]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9
* Platform: ios
* OS version: mac0s sierra 10
* Device manufacturer / model: iPhone 6s
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): iOS 4.5.1
* Plugin config
* Ionic Version (if using Ionic) 3

## Expected Behavior

_Tell us what should happen_
Wanted to use local notification for iOS 

## Actual Behavior

_Tell us what happens instead_
Ionic platform add iOS got a message of
Installing "cordova-plugin-local-notification" for ios
Plugin doesn't support this project's apple-ios version. apple-ios: 9.3.0, failed version requirement: >=10.0.0
Skipping 'cordova-plugin-local-notification' for ios
## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by davidkuek** [comment]
For android platform it went well, only for iOS i am having issues

**Comment by MeggSan** [comment]
@davidkuek Hello! Did you use the plugin version 0.9.0 with ionic in android platform?

**Comment by davidkuek** [comment]
Hi @MeggSan. I got it fixed by changing the engine version for apple-ios in plugin.xml (originally was version 10)
```html
<engines>
    <engine name="apple-ios" version=">=9.3.0" />
```
Not sure why though but hope to contribute to you guys for the solutions.

**Comment by katzer** [comment]
v0.9 does not run on iOS 9, only iOS 10+
