### ISSUE TITLE
every not working trigger once only

### ISSUE THREAD

**Issue by ayadarwesh** [katzer/cordova-plugin-local-notifications#1453]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:0.9.0-beta.1
* Platform:
* OS version:Android 6.0.1
* Device manufacturer / model: OPPO A57-CPH1701
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```):
* Plugin config 0.9.0-beta.1
* Ionic Version (if using Ionic)3.18.0

## Expected Behavior

trigger local notification every minute

## Actual Behavior

trigger once only

## Steps to Reproduce
 cordova.plugins.notification.local.schedule({
             id: 1,
             title: "title",
             text: "text",
             trigger:{ firstAt: new Date(new Date().getTime()+2*1000),every:'minute'},
             sound: sound,
         });
## Context
I'm going to downgrade to 0.8.5

**Comment by katzer** [comment]
Infinite trigger came into master after the beta.1 - you also have to specify the `count`.

```js
trigger: { every: 'minute', count: 5 }
```
