### ISSUE TITLE
Stuck between a rock and a hard place

### ISSUE THREAD

**Issue by shi11** [katzer/cordova-plugin-local-notifications#1456]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment
macOS Sierra

* Plugin version: 
Android: 0.8.5, iOS: 0.9.0-beta.1
* Platform: 
Android and iOS
* OS version: 
Android 8.0.0, iOS 11
* Device manufacturer / model: 
nexus & apple
* Cordova version (```cordova -v```): 
7.1.9
* Cordova platform version (```cordova platform ls```):
android 6.3.0
ios 4.3.1
* Plugin config

* Ionic Version (if using Ionic)
Ionic v1

## Expected Behavior
notifications should appear on both platforms

## Actual Behavior
iOS works but only on the 0.9.0-beta.1 branch. 
iOS11 doesn't receive notifications on the 0.8.5 branch.

Android only works on 0.8.5 release.
Android using branch 0.9.0-beta.1 fails with error: android.support.v4.media.app.NotificationCompat does not exist

## Steps to Reproduce
build 0.9.0-beta.1 branch on Android

  1. ...
  2. ...
  3. ...
  4. ....

## Context
As I'm sure you are too, I'm trying to get this plugin to work on both platforms with the same branch

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by shi11** [comment]
tried fixing the issue by following this tutorial, https://medium.com/google-developers/migrating-mediastyle-notifications-to-support-android-o-29c7edeca9b7 ...no luck so far.

**Comment by katzer** [comment]
@shi11 The master branch works for both IOS and Android.

**Comment by katzer** [comment]
> error: android.support.v4.media.app.NotificationCompat does not exist

Then you have to upgrade the compat lib

**Comment by shi11** [comment]
thank you @katzer
