### ISSUE TITLE
Js Error, because browser not support for of syntax

### ISSUE THREAD

**Issue by lywzx** [katzer/cordova-plugin-local-notifications#1457]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0
* Platform: android
* OS version: android 5
* Device manufacturer / model:
* Cordova version (```cordova -v```):7.1.0
* Cordova platform version (```cordova platform ls```):android
* Plugin config "cordova-plugin-local-notification": "^0.9.0-beta.1",

## Expected Behavior

when load plugin files, syntax error

## Actual Behavior

cordova cannot down

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. local-notification-util.js file at line 176, please use for in instead of for of
  2. local-notification-util.js file at line 334, please use for in instead of for of
  3. local-notification-util.js file at line 352, please use for in instead of for of
  4. local-notification-core.js file at line 71, please use for in instead of for of
  5. local-notification-core.js file at line 345, please use for in instead of for of
  6. local-notification-core.js file at line 105, please use for in instead of for of
  7. local-notification-core.js file at line 345, please use for in instead of for of

## Context

_What were you trying to do?_

## Debug logs
![image](https://user-images.githubusercontent.com/8436383/33749910-91f3b3aa-dc0b-11e7-9d75-e1dde61469c0.png)

  * ios XCode logs
  * Android: $ adb logcat

**Comment by h3nr1ke** [comment]
Same here... all Android phones running 4.4.2 are broken...

**Comment by scott1991** [comment]
For those old android devices.
There are three things that can't run before Android 5.1
1. for...of
2.Object.assign()
3.Array.from()

1. you may manually change them to for...in and
ex:
from
```        
for (var toast of toasts) {  
  this.mergeWithDefaults(toast);  
  this.convertProperties(toast);  
}  
```
to
```        
for (var i of toasts) {  
  this.mergeWithDefaults(toasts[i]);  
  this.convertProperties(toasts[i]);  
}  
```

2. and 3.
use Polyfill to solve them, MDN has these code.
[Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)
[Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)
put them on the top of 
local-notification-core.js and local-notification-util.js
or , if you use cordova/ionic... u can also put them in app.js

**Comment by katzer** [comment]
WTF

**Comment by katzer** [comment]
Has been fixed on master
