### ISSUE TITLE
Trigger : {at} method doesn't work

### ISSUE THREAD

**Issue by AdobeWordPress** [katzer/cordova-plugin-local-notifications#1458]
Provide a general summary of the issue.

## Your Environment

* Plugin version:
* Platform: IOS
* OS version:9.0
* Device manufacturer / model: simulator
* Cordova version 7.1.0
* Plugin config
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-device-motion 1.2.5 "Device Motion"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-globalization 1.0.8 "Globalization"
cordova-plugin-ios-longpress-fix 1.1.0 "iOS LongPress Fix"
cordova-plugin-local-notifications 0.0.0 "LocalNotification"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"

## Expected Behavior

I just want to send a push notification one time at fixed date. 

## Actual Behavior

I use one of your sample code but it sends notification every time when i click the button even in not date i set (2017-10-27, 15:00). 

$('button').click(function(){
    cordova.plugins.notification.local.schedule({
        title: 'Design team meeting',
        text: '3:00 - 4:00 PM',
        trigger: { at: new Date(2017, 10, 27, 15) }
    });
});

**Comment by schtailmuel** [comment]
try this:

$('button').click(function(){
cordova.plugins.notification.local.schedule({
title: 'Design team meeting',
text: '3:00 - 4:00 PM',
at: new Date(2017, 10, 27, 15)
});
});

**Comment by katzer** [comment]
Cant reproduce - From your plugin config I can see that you might still use branch x and not master.
