### ISSUE TITLE
Using local notification in android 2.x

### ISSUE THREAD

**Issue by rodolphorosa** [katzer/cordova-plugin-local-notifications#146]
I've tried to use this plugin in an application that I'm developing and I found it very simple and useful even for me who's a newbie, thanks, and it worked fine in my 4.3 device. But, I have a question: the application I'm developing is intented to be used in any android version between 2.3 and 4.4, but I've seen that this plugin is only supported by versions equal or greater then 3.0. Is there any modification that I can do so that I can use it in 2.x?

ps.: sorry for my bad english :)

**Comment by zmandel** [comment]
thanks for the great plugin!
android 2.x seems like its not working, however in your docs it says sdk>=7, should say sdk>=11 which is android 3.0.
cheers!

**Comment by zmandel** [comment]
(see https://github.com/katzer/cordova-plugin-local-notifications#supported-platforms)

**Comment by zmandel** [comment]
this other issue that says it does work on 2.1, however only when using version 0.8. On 0.8 seems like window.plugin.notification.local.onclick is not working, but does on the stable 0.7x
