### ISSUE TITLE
[iOS, v0.8.5] clear event doesn't trigger callback

### ISSUE THREAD

**Issue by OctoberCat** [katzer/cordova-plugin-local-notifications#1462]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

Clear events is not fired nor in foreground neither in background.  Repeating mechanism works on Android only. Repeating mechanism on iOS works by strange pattern - in some case it won't work, in other - previous notification showed right after triggering new one 

## Your Environment
* Plugin version: 0.8.5
* Platform: iOS 
* OS version: 11.1.2, 11.2 
* Device manufacturer / model: iPhone 6 SE 
* Cordova version (cordova -v```): 7.1.0 
* Cordova platform version (cordova platform ls```): ios 4.4.0 
* Plugin config Notification options init: 
```
 let notificationOpt: ILocalNotification = {
      id: moment().unix() + Math.floor(Math.random() * 100) + 1,
      title: event.type,
      text: event.data,
      sound: null,

      data: event,
      every: this.isIOS ? 'minute' : '1' //could raise problems on iOS
    };
```

`sound` and `title` are modified based on received data.

*plugin callback registration:

      this.localNotifications.on('click', (notification, state) => {
        this.logEvent('click', notification);
        this.onClickTest(notification, state);
      });

      this.localNotifications.on('schedule', (notification) => {
        this.logEvent('schedule', notification);
      });

      this.localNotifications.on('trigger', (notification) => {
        this.logEvent('trigger', notification);
        this.onTriggered(notification);
      });

      this.localNotifications.on('cancel', (notification) => {
        this.logEvent('cancel', notification);
        this.onCanceled(notification);
      });

      this.localNotifications.on('clear', (notification, state) => {
        this.logEvent('clear', notification);
        this.onClear(notification, state);
      });

All callbacks works except 'clear'
* Ionic Version (if using Ionic)
`ionic info`

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 1.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 2.1.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    Node       : v6.9.0
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

## Expected Behavior

Notifications should be repeated every minute until cancelled( via special toast in app or clear event callback),notification cancellation should clear it( it works like this in Android, and I'm not sure about iOS)

## Actual Behavior

Clear events is not fired nor in foreground neither in background.  Repeating mechanism works on Android only. Repeating mechanism on iOS works by strange pattern - in some case it won't work, in other - previous notification showed right after triggering new one. After cancellation notification is not cleared.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

In my case I receive events via socket connection. Background geolocation plugin provides background work. If this related, badge plugin doesn't work on iOS too for some reason
## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat
## Additional environment info
`npm  ls  --depth=0`
├── @angular/common@2.2.1
├── @angular/compiler@2.2.1
├── @angular/compiler-cli@2.2.1
├── @angular/core@2.2.1
├── @angular/forms@2.2.1
├── @angular/http@2.2.1
├── @angular/platform-browser@2.2.1
├── @angular/platform-browser-dynamic@2.2.1
├── @angular/platform-server@2.2.1
├── @ionic-native/app-availability@3.14.0
├── @ionic-native/app-version@3.14.0
├── @ionic-native/background-geolocation@3.12.1
├── @ionic-native/badge@3.12.1
├── @ionic-native/core@3.6.0
├── @ionic-native/date-picker@3.12.1
├── @ionic-native/insomnia@3.14.0
├── @ionic-native/launch-navigator@3.14.0
├── @ionic-native/local-notifications@3.14.0
├── @ionic-native/native-audio@3.14.0
├── @ionic-native/vibration@3.14.0
├── UNMET PEER DEPENDENCY @ionic/app-scripts@1.1.3
├── @ionic/cli-plugin-cordova@1.4.0
├── @ionic/cli-plugin-ionic-angular@1.3.1
├── @ionic/cloud-angular@0.12.0
├── @ionic/storage@1.1.9
├── angular2-signaturepad@2.6.1
├── angularfire2@2.0.0-beta.7-pre
├── com.lampa.startapp@0.1.4
├── cordova-android@6.4.0
├── cordova-ios@4.4.0
├── cordova-plugin-actionsheet@2.3.3
├── cordova-plugin-app-event@1.2.1
├── cordova-plugin-app-version@0.1.9
├── cordova-plugin-appavailability@0.4.2
├── cordova-plugin-badge@0.8.5
├── cordova-plugin-compat@1.2.0
├── cordova-plugin-console@1.1.0
├── cordova-plugin-datepicker@0.9.3
├── cordova-plugin-device@1.1.7
├── cordova-plugin-geolocation@2.4.3
├── UNMET DEPENDENCY cordova-plugin-globalbroadcaster@git+https://github.com/OctoberCat/GlobalBroadcasterPlugin.git
├── cordova-plugin-insomnia@4.3.0
├── cordova-plugin-mauron85-background-geolocation@2.3.3
├── cordova-plugin-nativeaudio@3.0.9
├── cordova-plugin-network-information@1.3.4
├── cordova-plugin-splashscreen@4.1.0
├── cordova-plugin-statusbar@2.3.0
├── cordova-plugin-vibration@2.1.6
├── cordova-plugin-whitelist@1.3.3
├── cordova-sqlite-storage@2.1.3
├── cordova.plugins.diagnostic@3.7.2
├── de.appplant.cordova.plugin.local-notification@0.8.5
├── firebase@3.9.0
├── GlobalBroadcaster@0.0.1 (git+https://github.com/OctoberCat/GlobalBroadcasterPlugin.git#fe1712dd1e746646a0d090f7199b93d0ef4998a2)
├── ionic-angular@2.1.0
├── ionic-native@2.4.1
├── ionic-plugin-deploy@0.6.7
├── ionic-plugin-keyboard@2.2.1
├── ionicons@3.0.0
├── moment@2.19.4
├── phonegap-plugin-local-notification@1.0.1
├── UNMET PEER DEPENDENCY rxjs@5.4.0
├── socket.io-client@1.7.4
├── sw-toolbox@3.4.0
├── typescript@2.0.9
├── uk.co.workingedge.phonegap.plugin.launchnavigator@3.2.2
└── zone.js@0.6.26

`cordova plugin ls`:

com.lampa.startapp 0.1.4 "startApp"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-badge 0.8.5 "Badge"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-mauron85-background-geolocation 2.3.3 "CDVBackgroundGeolocation"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-vibration 2.1.6 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.1.3 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.7.2 "Diagnostic"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-deploy 0.6.7 "IonicDeploy"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-local-notification 1.0.1 "phonegap-plugin-local-notification"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.2 "Launch Navigator"

**Comment by katzer** [comment]
@OctoberCat I know v0.8.x is the latest stable version, however only v0.9.beta.x supports iOS 10+
