### ISSUE TITLE
missing foreground attribute on ILocalNotification type 

### ISSUE THREAD

**Issue by Hanzofm** [katzer/cordova-plugin-local-notifications#1464]
The foreground:true|false attribute is missing on Ionic Native/0.8.5 plugin version

## Your Environment

* Plugin version: 0.8.5
* Platform: Ionic v3.9.2
* OS version: Android/IOS
* Device manufacturer / model:
* Cordova version: 7.0.1
* Cordova platform version (```cordova platform ls```):android 6.3.0 ios 4.5.4
* Plugin config
* Ionic Version (if using Ionic) Ionic v3.9.2

## Expected Behavior

The attribute foreground should be available for schedule local notifications

## Actual Behavior

When try to schedule a local notifications it logs:

`[12:45:59]  console.warn: Unknown property: foreground `

## Context

Send a foreground notification on IOS

**Comment by katzer** [comment]
Please always see the tagged README for the version you are using.

The `foreground` property requires v0.9.x

**Comment by himalayaahuja** [comment]
using this version     "cordova-plugin-local-notification": "^0.9.0-beta.2",
this should support foreground property right.. but it isn't supporting..

**Comment by chrisg86** [comment]
I'm using `0.9.0-beta.3` and it's still not supported.
