### ISSUE TITLE
cancelAll() doesn't cancel all notifications.

### ISSUE THREAD

**Issue by cheesepencil** [katzer/cordova-plugin-local-notifications#147]
I'm building an android app with ionic/angular and I'm using CPLN in a service.

The service waits for cordova to ready with $ionicPlatform.ready() and assigns window.plugin.notification.local to `CPLN` to save some typing.

The service has a `set` and a `get` function.

`set` creates a new, recurring notification a minute in the future, repeating every minute:

    set: function () {
      // clear all existing notifications
      CPLN.cancelAll();

      // set up the new ones
      CPLN.add({
        id: lastID,
        date: new Date( new Date().getTime() + ( 60 * 1000 ) ),
        message: 'ID: '+ lastID,
        repeat: 1
      });
      lastID++;
    }

As far as I can tell, the notifications are always scheduled, but aren't always cancelled. Calling this function multiple times will register multiple scheduled notifications, and a minute later I will get them all at the same time. Not all of them, but some of them (as many as five or six).

Strangely, getScheduledIds() always calls back with a single item array with the most recent lastID in it, even if I'm getting a half dozen notifications every minute!

    get: function (callback) {
      // return array of notification IDs
      CPLN.getScheduledIds(function (scheduledIds) {
        callback.call( this, scheduledIds );
      });
    }

Are the add() and cancelAll() methods not synchronous? I didn't see a callback argument for those methods in the readme so I assumed they were.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).
