### ISSUE TITLE
Custom notification sound cannot be displayed on Android 8.0.0

### ISSUE THREAD

**Issue by felixliu226** [katzer/cordova-plugin-local-notifications#1471]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.1
* Platform: Android
* OS version: Android 8.0.0
* Device manufacturer / model: One Plus 5 (running with Native Android)
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): Android 6.3.0
* Plugin config: Default
* Ionic Version (if using Ionic): 3.19.0

## Expected Behavior

The custom notification sound should be played when the notification is triggered. 

## Actual Behavior

When the notification is triggered, it displayed the default notification.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. create a empty ionic project and install the local notification plugin 
  2. schedule a local notification with custom sound
`sound: 'file://assets/sound/alarm.wav'`
  3. Put the sound file in `/www/assets/sound/alarm.wav`
  4. run the app on android device, set the notification

## Context

I'm not sure whether the notification sound feature is included in the "limited support for Android 8.0.0", if yes, then please suggest possible solution. Thanks in advance.

## Debug logs

_Include iOS / Android logs_: N.A.

  * Android: $ adb logcat

**Comment by katzer** [comment]
Android 8 support is still limited - thats why its still beta version ;)

**Comment by felixliu226** [comment]
@katzer Thanks for your reply. I tried to modified the manager.java file and change the setting of default notification channel, it works as expected.

But there is another issue on the Android 8.0.0, which is that the notifications are not triggered at correct time. My app is designed to schedule a set of notifications in the following several days. When the notifications are scheduled, the log indicates that `unknown property: at`, but I can still received the first several notifications. However, if the notification is scheduled several hours later (or on the next day), then the trigger time will be delayed. For example, two notifications were scheduled on 9:14 and 10:08, but the two notifications were triggered at the same time on 10:42.

I'm wondering do you have any suggestion about this issue? Thanks in advance.

**Comment by katzer** [comment]
Whats your code?

**Comment by felixliu226** [comment]
FYI, I'm using ionic.

```
// variable time ('yyyy/mm/dd HH:MM:SS') is the output of random generate process, it data type is string. 
this.alarms.push(time);
let notificationArr = [];
this.alarms.forEach((time, index)=>{
    let notification = {
        id: index,
        text: "xxxx",
        at: new Date(time)
    };
    notificationArr.push(notification);
});
this.localNotifications.schedule(notificationArr);
```

**Comment by katzer** [comment]
@felixliu226 Please use the new `trigger` API. See the README for master branch.

Also its not wise to schedule all notifications one by one. Its better to schedule them in a bulk.

**Comment by katzer** [comment]
> For example, two notifications were scheduled on 9:14 and 10:08, but the two notifications were triggered at the same time on 10:42.

Android takes care of invoking the callback. Its possible that the OS decides to invoke them at a later time for reason a, b, c. If time is critical you can try to specify the `priority` flag. That values can be [-2, -1, 0, 1, 2].

Hope that helps.

**Comment by sachinGAcharya** [comment]
same problem here. Anyone found the solution for this?Please help me.
