### ISSUE TITLE
Notification does not show on Android when app is killed

### ISSUE THREAD

**Issue by devfelipereis** [katzer/cordova-plugin-local-notifications#1473]
Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.8.5
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Asus Zenfone 3
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): android 6.1.2
* Plugin config
* Ionic Version (if using Ionic): 1.3.2

## Expected Behavior

Should show a notification after five minutes. I kill the app after the notification has been created.

## Actual Behavior

Nothing is shown.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

```
var now = new Date().getTime(),
    _5_min_from_now = new Date(now + 60 * 1000 * 1 * 5); // 5min for testing

    cordova.plugins.notification.local.schedule({
        title: "Test",
        text: "Test",
        at: _5_min_from_now
    });
```

## Context

I just need to show a notification in the future.
If I do not pass "at", the notification appears(the app is open).
If I pass "at" but do not kill the app, the notification appears.
If I pass "at" and kill the app, the notification doesn't appear.

## Debug logs
My logs do not have errors.

**EDIT 1**
Works as expected on Android 7.1.2

**Comment by elmismopancho** [comment]
+1
Device Huawei Ascend G7
Android 6.0.1

**Comment by elmismopancho** [comment]
It seems that is a problem with the device. My phone has a very unpredictable behaviour when it comes to dealing with local or push notifications. I tried the same code on a Samsung Tablet and it worked without issues.

**Comment by devfelipereis** [comment]
Update: I updated my env and now I'm using the latest version of this plugin.
It still do not work in the 7.0 device.
But it works in the a device 7.1.2 and 6.0.

**Comment by katzer** [comment]
I've Samsung and Android emulator - it works there. Everything other is hard to debug as I cannot reproduce the issue.

**Comment by kirillgroshkov** [comment]
Also doesn't work for us on Google Pixel2, but works on some old Android with version 6.
