### ISSUE TITLE
Notifications have been suddenly broken on Samsung  Galaxy smartphones 

### ISSUE THREAD

**Issue by Lorec-limsky** [katzer/cordova-plugin-local-notifications#1478]
Since last week I found that notifications doesn't work as expected on Android. First thought was that it is related with environment updates, but then I checked version  from Play Store and got the same results. The odd thing in this case that this bug related with Samsung(Galaxy probably)  

Test devices with broken notification: 
Samsung Galaxy J5 (2016) J510H/DS(7..), Samsung Galaxy J7 J700H/DS (6.1.1) , Samsung Galaxy S8 plus((6.1.1)).
Test devices with broken notification: 
Samsung Galaxy J5 (2016) J510H/DS(7..), Samsung Galaxy J7 J700H/DS (6.1.1) , Samsung Galaxy S8 plus((6.1.1)).
Test devices without issues: 
xiaomi redmi 4 s pro/prime(6.1.1), Sony Z 5 premium  (7.1.1)
## Expected Behavior

Notification fires immediately after scheduling and repeats every minute. Everything was just fine until last week.

## Actual Behavior

Notification fires after 4-7 minutes and can be triggered only once,

I checked this bug with 0.8.4 and 0.8.5 version of the plugin and Ionic 2.2. If someone has the same problem please reply.

**Comment by Agimovel** [comment]
Did you solved? Same here.

**Comment by katzer** [comment]
Has this been fixed by itself?
