### ISSUE TITLE
BUG: push notification sound is played on iOS when in foreground

### ISSUE THREAD

**Issue by saoron** [katzer/cordova-plugin-local-notifications#1479]
Plugin make a sound when a notification is fired on foreground

## Your Environment

* Plugin version: 0.9.0-beta.1
* Platform: iOS
* OS version: 11.1
* Device manufacturer / model: iPhone 7 plus
* Cordova version (```cordova -v```):  7.1.0
* Cordova platform version (```cordova platform ls```): ios 4.5.4
* Plugin config 
* Ionic Version (if using Ionic) 3.9.2

## Expected Behavior

On foreground no push notification or sound should be fired 
## Actual Behavior

A push notification is fired even if the foreground: false flag is set

**Comment by katzer** [comment]
Please also provide some code how you schedule the notification. You're talking about push notifications. I guess you mean local notifications.

**Comment by saoron** [comment]
Yes, Im talking about local notification, Sorry, The code is: 


                          if (this.platform.is('cordova')){
					const options = {
						title: 'Sign-in is required',
						tag: "conncted",
						texr: "Click here to sign-in to Dride..",
						icon: "assets/icon/favicon.ico"
					};
					cordova.plugins.notification.local.schedule(options)
				}

**Comment by katzer** [comment]
OK, as you dont specify a sound, the system sound will be played.

For no sound do this:

```js
cordova.plugins.notification.local.schedule({
  ...
  sound: false
});
```

**Comment by saoron** [comment]
Thanks,
Will the sound be played on background?

**Comment by katzer** [comment]
> Will the sound be played on background?

No

**Comment by saoron** [comment]
So that's the point of this issue, When in foreground there is a notification sound, it shouldn't be there..

**Comment by rwillett** [comment]
Passing ```sound: false``` turns off sounds. Unclear what the problem is here?

**Comment by saoron** [comment]
The local notification should not fire when app is in foreground. [Updated initial post]

**Comment by rwillett** [comment]
I think the notification **should** fire when the app is in the foreground but perhaps it should not be presented to the application. Isn't that the correct behaviour?

We want the notification to be displayed regardless of whether the app is in the foreground or background, so we have never used that flag.  We may get chance to try it later on the week.

**Comment by saoron** [comment]
Looks like the guideline is clear about that..


> With local notifications, your app configures the notification details locally and passes those details to the system, which then handles the delivery of the notification when your app is not in the foreground. 

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/

**Comment by rwillett** [comment]
We like have the notification appear on the top of the app even when its in the foreground. It reinforces the notification. YMMV.

**Comment by katzer** [comment]
@saoron Can this be closed? Set `sound` to false if you dont want to have a sound.

**Comment by saoron** [comment]
But I dont want the notification to show on foreground as well :)

**Comment by katzer** [comment]
Have you tried this already?

```js
cordova.plugins.notification.local.schedule({
  ...
  foreground: false,
  sound: false
});
```

**Comment by jimmyblantanojr** [comment]
I think what he want is when the app is open he don't want the app sound to be fired just the system sound but not totally turning off the sound, in my case that's what i want to be too ( if possible :) ) . Coz when the app is open two sound is playing, is there a way to play only one sound when the app is open?

**Comment by jimmyblantanojr** [comment]
Thank You. :)

**Comment by katzer** [comment]
@jimmyblantanojr Is that also the case for beta.3? Usually the plugin now ignores system callbacks triggered by push notifications.

**Comment by jimmyblantanojr** [comment]
@katzer it's on v0.8.5, is it possible on this version?

**Comment by jimmyblantanojr** [comment]
@katzer, do i need to create a new discussion or is it ok here?coz mine seems off the version that's been tackled here.

Thank You. :)

**Comment by katzer** [comment]
@jimmyblantanojr Thats likely possible

**Comment by jimmyblantanojr** [comment]
@katzer ok, thank you for your response. :)
