### ISSUE TITLE
Local Notifications only triggered when running in foreground

### ISSUE THREAD

**Issue by schtailmuel** [katzer/cordova-plugin-local-notifications#1483]
The local notifications scheduled in future are not triggered when app is closed

## Environment

* Plugin version:  0.8.5
* Platform: android
* OS version: 6.0.1
* Device manufacturer / model: Samsung Galaxy S5 mini
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): android 6.3.0
* Ionic Version: 3.19.0

## Expected Behavior

Notification should be triggered at specified datetime

## Actual Behavior

Nothing happens, on android the notification is triggered when opening the app

**Comment by katzer** [comment]
Sounds like you're talking about the trigger callback. If the app isn't running, then there's also no runtime callback to be invoked at runtime. The same might be when the app is running in background in suspended mode.
