### ISSUE TITLE
Method schedule with param trigger: {at: ''} is scheduling wrong month

### ISSUE THREAD

**Issue by John-Henrique** [katzer/cordova-plugin-local-notifications#1485]
When using method schedule with param trigger at result in a schedule wrong month. Every time, the month is plus by one, Jan stay Feb...

## Your Environment

* Plugin version: 0.9-beta
* Platform: Android
* OS version: 6
* Device manufacturer / model: Leagoo M5
* Cordova version (PhoneGap): 7.1.1 
* Plugin config
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-badge 0.8.5 "Badge"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-firebase 0.1.24 "Google Firebase Plugin"
cordova-plugin-local-notification 0.9.0-beta.1 "LocalNotification"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"

## Expected Behavior

When schedule by use 
```
cordova.plugins.notification.local.schedule({
	title: 'Design team meeting',
	text: 'My text',
	at: new Date(2018, 01, 02, 18, 21)
});
```
expected receive notification on 2018-01-02 at 18:21

## Actual Behavior

Notifications are received only in 2018-02-02 at 18:21. No other problems aparently.

## Steps to Reproduce

  1. Schedule any notification using param trigger at and run in console of navigator 

```
cordova.plugins.notification.local.getAll(function (notifications) {
    console.log(notifications);
});

```
  2. You will get some notifications, navigate in nodes of objects until find '{at: [HERE], type: "calendar"}'

  3. If you convert this timestamp to human readable, the month will be Feb

## Context

Schedule multiple notifcations, using the example code.

**Comment by katzer** [comment]
@John-Henrique 

- January: `new Date(2018, 0, 2, 18, 21)`
- February: `new Date(2018, 1, 2, 18, 21)`
