### ISSUE TITLE
Last Stable Version is 0.9.0-beta.1

### ISSUE THREAD

**Issue by mburger81** [katzer/cordova-plugin-local-notifications#1487]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Is that wanted, that the last stable release on **npm** is `0.9.0-beta.1`? Is this really beta or did your forgot to pin the new version number?

![image](https://user-images.githubusercontent.com/3778892/34513960-2d46f6aa-f06b-11e7-8f0b-99cc6024c507.png)

## Your Environment

* Plugin version: 0..9.0-beta.1
* Platform:
* OS version: 
* Device manufacturer / model:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Last stable release should not be a beta release.

## Actual Behavior

Last stable release is a beta release.

## Steps to Reproduce

`npm info cordova-plugin-local-notification`

**Comment by katzer** [comment]
It's beta!

**Comment by mburger81** [comment]
Okay good to know, but IMO you should release this in NPM as beta release and not in stable release. Because anyone which will have automatic upgrade for your plugin will upgrade to your beta release

thx a lot for your hard work!
