### ISSUE TITLE
Repeat everyday at scheduled wrong

### ISSUE THREAD

**Issue by Jatapiaro** [katzer/cordova-plugin-local-notifications#1488]
Im simply scheduling a notification. I use moment js to start the scheduling tomorrow at an hour specified by the user.

So i just simply: let date = moment(date).add(1, 'days').toDate() do this to get the next day.
 Then i just 
`

     //We set the new date to the next notifications
     let notification = { 
           title: "Welcome",
           text: "Lets start with your first reflection", 
           at: new Date(), 
           every: '"day"
     };
     notification.at = date;
     this.localNotifications.schedule(notification);
`

To be sure I print the notification.at, and I've got the tomorrow at some hour correctly. But the device don't care about the at. It just takes the hour. Example, if I right now are the 20:00, and I scheduled something for tomorrow 20:02, the notification is fired in two minutes.

**Comment by ammichael** [comment]
Hi there,

What version of the plugin are you using? If you are at the latest (and you should be), the syntax is a little bit different.

Try this:
```
let notification = { 
       title: "Welcome",
       text: "Lets start with your first reflection", 
       trigger: {
            every: "day",
            firstAt: date
        }
 };
 this.localNotifications.schedule(notification);
```

**Comment by Jatapiaro** [comment]
@ammichael Yeah, I'm using the last version on Ionic 3. Also I'm wondering if the firstAt property works on ios

**Comment by ammichael** [comment]
@Jatapiaro Actually, yes, I'm also having problems with firstAt. I found out that this works:

```
trigger: {
   every: {
       hour: date.getHours(),
       minute: date.getMinutes()
    }
}
```

The problem is that sometimes I need that the notification trigger at the specified hour/minute, but not in the same day I'm scheduling it.. that is where the 'firstAt' would be handy, but it doesn't seem to work on iOS at least.

@katzer any chance my code (below) is wrong? Maybe I'm getting it wrong?

```
trigger: {
   every: {
       hour: date.getHours(),
       minute: date.getMinutes(),
       firstAt: date
    }
}
```

**Comment by katzer** [comment]
@ammichael Please see here:
https://github.com/katzer/cordova-plugin-local-notifications#properties-2

For matching triggers there's no `firstAt` but `after`. However thats only supported on Android and Windows.
