### ISSUE TITLE
Local notification doesn't work on android using ionic 3 with android version 7 and below

### ISSUE THREAD

**Issue by normanaranez** [katzer/cordova-plugin-local-notifications#1489]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: "cordova-plugin-local-notification": "^0.9.0-beta.1"
* Platform: ionic 3
* OS version: android 7 and below( only works on android 8.0)
* Device manufacturer / model:
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): android 6.3.0
* Plugin config
* Ionic Version (if using Ionic):  ionic-angular 3.7.1

## Expected Behavior

_Tell us what should happen_

## Actual Behavior

_Tell us what happens instead_

Notification works fine with me using the genymotion emulator having and android version of 8.0 but when the version is lower the notification will not work anymore.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. in android 4.4 (kitkat) after installing local notification without declaring the code in my project file, some of my code will not work using an emulator by genymotion.
  2. In android 7 my code works fine but the notification not. event just adding the sample notification to see if notification will not
  3. ...
  4. ....

## Context

_What were you trying to do?_

just trying to test the notification if will work no further changes with the code

## Debug logs

_Include iOS / Android logs_

no log shows

  * ios XCode logs
  * Android: $ adb logcat

**Comment by katzer** [comment]
The Ionic wrapper isn't compatible with v0.9-beta. And the support for Android 4.4-5 came in after the release of 0.9-beta.1

**Comment by katzer** [comment]
Without Ionic or Angular the plugin works fine when testing with Android 6 or 7. Without any error log I cannot reproduce the issue.

**Comment by normanaranez** [comment]
you need to test this using ionic 3 if you really want to know what happen. there is no error display but the plugin doesn't work. when i test it on google pixel 3 having android version 8 it works fine when below of the android 8 version it will not work but not returning error.

**Comment by kirillgroshkov** [comment]
Doesn't work for us with Ionic3, 0.8.5 version of the plugin and Google Pixel2 with Android 8

**Comment by ghulamakbar14** [comment]
Local notification is not working on Android 6 (Marshmallow).
It is working on higher versions Android 7, 8 & 9.

Further specifications are as follows:
Ionic: 4.12.0
Cordova: 9.0.0

"@ionic-native/local-notifications": "^5.3.0"
"cordova-plugin-local-notification": "0.9.0-beta.3"
