### ISSUE TITLE
Local notification doesn't work on android using ionic 3 with android version 7 and below #1489

### ISSUE THREAD

**Issue by normanaranez** [katzer/cordova-plugin-local-notifications#1491]
WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!

Provide a general summary of the issue.

Your Environment
Plugin version: ^0.9.0-beta.1
Platform: ionic 3
OS version: android 7 and below( only works on android 8.0)
Device manufacturer / model:
Cordova version (cordova -v): 7.1.0
Cordova platform version (cordova platform ls): android 6.3.0
Plugin config
Ionic Version (if using Ionic): ionic-angular 3.7.1
Expected Behavior
Tell us what should happen

Actual Behavior
Tell us what happens instead

Notification works fine with me using the genymotion emulator having and android version of 8.0 but when the version is lower the notification will not work anymore.

Steps to Reproduce
Reproduce this issue; include code to reproduce, if relevant

in android 4.4 (kitkat) after installing local notification without declaring the code in my project file, some of my code will not work using an emulator by genymotion.
In android 7 my code works fine but the notification not. event just adding the sample notification to see if notification will not
...
....
Context
What were you trying to do?

just trying to test the notification if will work no further changes with the code

Debug logs
Include iOS / Android logs

no log shows but not working

ios XCode logs
Android: $ adb logcat

**Comment by katzer** [comment]
Please keep in mind that v0.9-beta doesn't work with ionic-native. The plugin itself runs on Android 6 and Android 7.

**Comment by julianshak** [comment]
@katzer Hello Sebastián, I am currently looking to use Ionic 3 to develop a hybrid mobile application for my undergraduate capstone project and I came across this native plugin that I was hoping to use for local notifications. Do you have an estimated time on when this plugin will be compatible with Ionic-Native? Or do you have any suggested alternatives? Any help is very greatly appreciated.

Thank you.

**Comment by katzer** [comment]
@julianshak The easiest workaround is to use the plugin directly without any Ionic wrapper. For the rest I have no time estimate but I want to release the plugin first.

**Comment by anilgr** [comment]
If the plugin isn't compatible with ionic native how come I'm able to get notifications in the emulator?.
plugin version : 0.9.0-beta.3
