### ISSUE TITLE
v0.9-beta notifications work in Android 8.1.0 but not in Android 6.0.1

### ISSUE THREAD

**Issue by davedgd** [katzer/cordova-plugin-local-notifications#1496]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

v0.9-beta (latest git) seems to have broken notifications in Android 6.0.1, although they work on 8.1.0.

## Your Environment

* Plugin version: v0.9-beta
* Platform: Android
* OS version: 6.0.1 and 8.1.0
* Device manufacturer / model: Nexus 5 and Pixel 2
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): android 7.0.0
* Plugin config
* Ionic Version (if using Ionic): v1

## Expected Behavior

Receive notifications (using basic examples) on both Android 6.0.1 and Android 8.1.0.

## Actual Behavior

On v0.9-beta, notifications only appear on 8.1.0 but not on 6.0.1. However, reverting to version 0.8.5 results in notifications that only appear on 6.0.1 and not on 8.1.0 (unsurprising given 0.8.5 does not have Oreo support).

**The important point here is that v0.9-beta seems to have broken notifications in 6.0.1...**

## Steps to Reproduce

Run a blank Ionic v1 cordova template and add the local-notifications plugin and a basic notification. On v0.9-beta this will only work on 8.1.0 but not on 6.0.1.

## Context

Test app deployment to a newer and older phone.

**Comment by katzer** [comment]
I am developing with an device running Android 6.0.1 - so I can confirm that it works (at least without Ionic v1).

**Comment by davedgd** [comment]
@katzer: thank you for clarifying that you're using 6.0.1 yourself. It's possible there is some sort of interaction with ionic, so I will try to do some testing without it to see if I can narrow down the problem.

**Comment by rwillett** [comment]
We have just tested with v0.9-beta-1 on Android Oreo (Pixel) and Android 6.0 (Nexus 5). 

We use Ionic 1 and it works fine with the above (and IOS 10). 

We do not use the Ionic wrapper (what ever that is) so I'd suggest you dump it and use the plugin directly. Not sure what the advantage of the wrapper is to be honest.
