### ISSUE TITLE
Not working without internet access

### ISSUE THREAD

**Issue by t2wu** [katzer/cordova-plugin-local-notifications#1497]
Provide a general summary of the issue.

## Your Environment

* Plugin version: cordova-plugin-local-notification
* Platform: iOS
* OS version: 9.3.4
* Device manufacturer / model: iPod Touch MKH02TA/A
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): ios 4.4.0
* Plugin config Not particularly configured.
* Ionic Version (if using Ionic) Not using Ionic

## Expected Behavior

Notification is send immediately regardless of internet access.

## Actual Behavior

When WiFi is not connected (and without cellular access, no sim card), notification doesn't get send.

## Steps to Reproduce

  1. Forget all network
  2. Send a simple notification without trigger

## Context

Just send a simple notification with title and text like the following:

```
  cordova.plugins.notification.local.schedule({
    title: notif.title,
    text: notif.text,
    smallIcon: 'res://notification_icon',
    trigger: {}, data: {}, actions: undefined
  });
```

And nothing pop up on the iPod Touch if not connected to WiFi. (WiFi is on, just not connected to anything).

## Debug logs

Nothing particular is in the log.

**Comment by katzer** [comment]
The plugin does not depend on internet connection. Your code snippet indicates that you're using v0.9. However this version does not support iOS-9 anymore.

**Comment by t2wu** [comment]
Let me see if this can be replicated on an device with iOS 10. It just so happens that we have a device with iOS 9 and without a sim card. The situation is pretty weird, because as soon as I hook on the Internet it runs fine. (And the code did appear to run because code after that runs fine too.)

**Comment by t2wu** [comment]
Interesting enough iOS 10 on iPhone 5 does not experience the same issue. Until further discovery, I guess this issue can be closed.
