### ISSUE TITLE
Error in success callbackid

### ISSUE THREAD

**Issue by jabelcs** [katzer/cordova-plugin-local-notifications#1499]
Developping an app with Visual Studio 2017 and Cordova. The plugin simply won't work...

## Your Environment

* Plugin version: 0.9.0-beta.1
* Platform: Android, windows, iOS
* OS version: Android 5.1 and 7.1.1, windows 10, iOS 11.2.2
* Device manufacturer / model: DOOGEE X5 Pro and Samsung Galaxy Tab, Asus, Iphone 6S 
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): Android 6.3.0, Windows 5.0.0 and ios 4.5.4
* Plugin config
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-badge 0.8.6 "Badge"
cordova-plugin-device 2.0.0 "Device"
cordova-plugin-dialogs 2.0.0 "Notification"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-local-notification 0.9.0-beta.1 "LocalNotification"
cordova-plugin-network-information 2.0.0 "Network Information"
cordova-plugin-screen-orientation 3.0.0 "Screen Orientation"
cordova-plugin-vibration 3.0.0 "Vibration"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-sqlite-storage 2.1.5 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"

## Expected Behavior
Schedule and display local notifications

## Actual Behavior
Returns error:
Error in Success callbackId: LocalNotification35982477 : TypeError: undefined is not a function
cordova.js (313,47)

## Steps to Reproduce

Using the following code to schedule a notification:
cordova.plugins.notification.local.schedule({
        id: 1,
        title: 'Scheduled with delay',
        foreground: true,
        trigger: { at: new Date() }
});

  1. Wait for 'deviceready'
  2. On 'deviceready' schedule a notification

## Context
Schedule and display a notification

**Comment by rwillett** [comment]
Not enough information. 

The plugin does work as we use it on IOS and Android. We schedule, re-schedule, query, remove and update local notifications all the time. 

Schedule your notification 10 secs in the future as well, your title is incorrect as there is no delay which might be your problem.

**Comment by templatetuners** [comment]
Getting same error in iOS. I know that `new Date()` is different in iOS so changed to   

```
var date = new Date();
date = date.replace(' ', 'T');
```

but stil having same error.
