### ISSUE TITLE
Preventing local notification to popup if its has active notification with a same ID

### ISSUE THREAD

**Issue by TreceDoseGoma** [katzer/cordova-plugin-local-notifications#1501]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.8.5
* Platform: Android
* OS version: none
* Device manufacturer / model: Nexus 5
* Cordova version (```cordova -v```):
* Cordova platform version (```6.1.1```):
* Plugin config
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.1 "Splash Screen"
cordova-plugin-statusbar 2.4.1 "Status Bar"
cordova-plugin-vibration 3.0.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.2.0 "cordova sqlite storage plugin"
de.applant.cordova.plugin.local-notification 0.8.5 "Local Notification"

## Expected Behavior

Notify everytime if the quantity is lessthan in quantitylevel  

## Actual Behavior

the notification is working properly but the problem is its re-show up again

## Steps to Reproduce

function noti() {
    $(document).ready(function () {
        var url = "http://###.###.###.###:####/ServiceProduct.svc/findall";
        $.getJSON(url, function (result) {
            console.log(result);
            $.each(result, function (i, field) {
                var Id = field.Id;
                var Item = field.Item;
                var Quantity = field.Quantity;
                var QuantityLevel = field.QuantityLevel;
                if (Quantity < QuantityLevel) {
                    cordova.plugins.notification.local.schedule({
                        id: Id,
                        title: "Warning",
                    }); // notification
                };//if 
            }); // for each
        }); // getJSON
    }); // ready function
    setTimeout(arguments.callee, 5000);
}; // noti function

**# Trying to do**

Preventing the notification to repopup if the notification with the same ID is already has active notification

**Comment by rwillett** [comment]
Two solutions.

1. Keep a log of what notifications you have already sent as a JSON somewhere and check it before creating a new one.

2. You need to query the local notifications and check what is currently running. Use cordova.plugins.notification.local.getAll()
https://github.com/katzer/cordova-plugin-local-notifications/wiki/08.-Querying

It's a bad idea to use the same id: each time as well. We always create new Id's for each new notification. Also make your schedule object an array, even if there is only one object. Also you have no at: time in your object to schedule. Set one in the future, even if it's only five seconds away.

**Comment by rwillett** [comment]
Closed as no update.
