### ISSUE TITLE
JavaScript runtime error: 'LocalNotificationProxy' is not defined on Windows

### ISSUE THREAD

**Issue by dannevesdantas** [katzer/cordova-plugin-local-notifications#1502]
After installing the cordova-plugin-local-notifications on a Windows platform Cordova project the following error message starts to be displayed by Visual Studio when trying to running the app:

> Unhandled exception at line 23, column 1 in ms-appx-web://com.example.hello/www/plugins/cordova-plugin-local-notification/src/windows/LocalNotificationProxy.js
> 0x800a1391 - JavaScript runtime error: 'LocalNotificationProxy' is not defined

![localnotificationproxy-is-not-defined-2](https://user-images.githubusercontent.com/5115895/34857616-dee4e1ce-f732-11e7-87f9-3fd696eb9561.PNG)

The Exception causes the app to crash on the splash screen and terminates prematurely :( 

## Steps to Reproduce

At the Command Prompt, create a new Cordova project and add the cordova-plugin-local-notifications plug-in:

```
cordova create hello com.example.hello HelloWorld
cd hello
cordova platform add windows
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
```
In Visual Studio 2015 Update 3, open the \hello\platforms\windows\CordovaApp.sln solution and run the Windows Universal app. The application will throw the following exception:

> Unhandled exception at line 23, column 1 in ms-appx-web://com.example.hello/www/plugins/cordova-plugin-local-notification/src/windows/LocalNotificationProxy.js
> 0x800a1391 - JavaScript runtime error: 'LocalNotificationProxy' is not defined

## Environment

* Plugin version: v0.9.0-beta.2
* Platform: Windows 10
* OS version: build 1709
* Visual Studio Version: Microsoft Visual Studio Community 2015 Update 3
* Cordova version: 8.0.0
* Cordova platform version: windows 5.0.0

Any ideas why it happens?
Thanks so much!

**Comment by katzer** [comment]
Does it also happen with beta.1 ? My project runs without an error msg.

**Comment by dannevesdantas** [comment]
Yep, the same Exception has been throwing here after installing the 0.9.0-beta.1 :( But I noticed it doesn't happen with the 0.8.5 realease.

**Comment by katzer** [comment]
The Windows port is a complete rewrite with v0.9

**Comment by rwillett** [comment]
Closed as no update in 27 days.
