### ISSUE TITLE
[Question] Recurring schedule every X days at 10:00h

### ISSUE THREAD

**Issue by AbsDeveloper** [katzer/cordova-plugin-local-notifications#1503]
Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.1
* Platform: IOS
* OS version: 11.2.X
* Device manufacturer / model: Iphone 6s Plus
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):
Installed platforms:
  android 6.4.0
  ios 4.4.0
* Ionic Version (if using Ionic) : 3.19.0

## Expected Behavior

It's just a question. I would like to schedule an alarm for example every 3 days at 10:00h.
Is this posible?  

Thank you!!!

**Comment by katzer** [comment]
> I would like to schedule an alarm for example every 3 days at 10:00h.

```js
trigger: { every: 3, unit: 'day', firstAt: datetime }
```

However there's no `firstAt` support on iOS. There it would trigger every 3rd day from now.

Another options is to specify the weekday (Monday is first day of the week). If you want to trigger something 2 times a week you have to schedule 2 notifications.

```js
trigger: { every: { weekday: 1, hour: 10, minute: 0 } }
```

**Comment by AbsDeveloper** [comment]
Thank you @katzer !

**Comment by GrindingOgre** [comment]
> trigger: { every: 3, unit: 'day', firstAt: datetime }

This won't work (at least on Ionic with their plugin), because trigger expects a ILocalNotificationTrigger, and if we look at that interface, **every** and **unit** can't be either a number or a string.

```
export interface ILocalNotificationTrigger {

...
    unit?: ELocalNotificationTriggerUnit;

...
    every?: ELocalNotificationTriggerUnit | ILocalNotificationEvery;

...

}
```

It would be really simple to manage the repeat configuration as a cron
Like this: `0 9 */2 * *` (_at 09:00 on every 2nd day-of-month_)
