### ISSUE TITLE
Notification or sound Not running

### ISSUE THREAD

**Issue by irontamoor** [katzer/cordova-plugin-local-notifications#1504]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: cordova-plugin-local-notification 0.9.0-beta.1 "LocalNotification"
* Platform: android 
* OS version: 5.1.1 also 6
* Device manufacturer / model: lg k4
* Cordova version (```cordova -v```):8.0.0
* Cordova platform version (```cordova platform ls```): android 7.0.0 browser 5.0.3
* Plugin config ?
* Ionic Version (if using Ionic) n/a

## Expected Behavior

_Tell us what should happen_

id:2 - every friday bring up notifcation 
id:100 etc- every time written bring notifcation and sound file

## Actual Behavior

_Tell us what happens instead_

id:2 - nothing
id:100 etc- nothing
tried changing time and dates result nothing  

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

code in js file which is linked in script  pointing to index.html
index.html
<script type="text/javascript" src="scripts/js/index_extra.js"></script>
would like to host online once working also would like to use firbase with code once working.

cordova.plugins.notification.local.schedule([{
    id:2,
    text: 'Jumma Mubrak!',
    firstAt: friday,
    trigger: { every: { hour: 07, minute: 00 } }

}]);

cordova.plugins.notification.local.schedule({
    id:100,
    text: 'Fajr Prayer Time',
    trigger: { every: { hour: 7, minute: 00 } },
    sound: 'file://sound/athan.mp3'

}, callback);

cordova.plugins.notification.local.schedule({
    id:101,
    text: 'Sunrise Stop Praying',
    trigger: { every: { hour: 8, minute: 00 } },
    sound: 'file://sound/athan.mp3'

}, callback);

cordova.plugins.notification.local.schedule({
    id:102,
    text: 'Zuhur Prayer Time',
    trigger: { every: { hour: 13, minute: 00 } },
    sound: 'file://sound/athan.mp3'

}, callback);

cordova.plugins.notification.local.schedule({
    id:103,
    text: 'Asr Prayer Time',
    trigger: { every: { hour: 15, minute: 00 } },
    sound: 'file://sound/athan.mp3'

}, callback);

cordova.plugins.notification.local.schedule({
    id:104,
    text: 'Magrib Prayer Time',
    trigger: { every: { hour: 18, minute: 00 } },
    sound: 'file://sound/athan.mp3'

}, callback);

cordova.plugins.notification.local.schedule({
    id:105,
    text: 'Isha Prayer Time',
    trigger: { every: { hour: 20, minute: 00 } },
    sound: 'file://sound/athan.mp3'

}, callback);

## Context

_What were you trying to do?_

id:2 - every friday bring up notifcation 
id:100 etc- every time written bring notifcation and sound file

tried changing time and dates result nothing  

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs n/a
  * Android: $ adb logcat nothing in logs

**Comment by katzer** [comment]
@irontamoor Do you see the same JS error as described in #1502 ?

**Comment by irontamoor** [comment]
No, I get no error message all installs fines the apk is built a notification which shows text works fine but not the above ones

**Comment by katzer** [comment]
apk? You mentioned `win10 x64`as the OS. What's your Android version, etc.?

**Comment by irontamoor** [comment]
I'm using the 5.1.1 also 6

**Comment by katzer** [comment]
Cannot reproduce...

**Comment by Agimovel** [comment]
Same error here. Android 6, Phonegap downgraded to 6 to use the cordova-plugin-local-notifications#0.8.5 and nothing...
