### ISSUE TITLE
 build fails for android in newest version.

### ISSUE THREAD

**Issue by MeyerSurix** [katzer/cordova-plugin-local-notifications#1506]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

build fails for android in newest version.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: cordova-android@-7.0.0
* OS version: windows10
* Device manufacturer / model: none
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): cordova-android@-7.0.0
* Plugin config: default
* Ionic Version (if using Ionic): no

## Expected Behavior

build should succeed after install and build

## Actual Behavior

when installing plugin, I get these warnings: 
android-sdk version check failed, installing anyways
apple-ios version check failed, installing anyways

when building android plaftorm, it fails:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.4.0) from [com.android.support:exifinterface:25.4.0] AndroidManifest.xml:25:13-35
        is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:23:9-25:38 to override.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. cordova plugin add cordova-plugin-local-notification@0.9.0-beta.2
  2. cordova build android

## Context

installing and building

## Debug logs
n.a.

**Comment by joewoodhouse** [comment]
Also fails for me on cordova-android 6.4.0

**Comment by rwillett** [comment]
Have you got the right version of the Android SDK loaded?

**Comment by katzer** [comment]
Except the fact, that I have to manually delete the `localnotification_provider_paths.xml` file with `cordova-android 7.0.0` every works fine even with cordova CLI 8.0

**Comment by warmsocks** [comment]
This is still broken for me, but I was able to work around it by using the cordova-android-support-gradle-release plugin, available here:

https://github.com/dpa99c/cordova-android-support-gradle-release

**Comment by snakone** [comment]
find any reference to "com.android.support:exifinterface" in your project.

Change the old version 25.4.0 to match com.android.support:support-v4:26.1.0

**26.+** should work. 

I had this issue before, solved by doing this ^^

**Comment by sriharimanepally** [comment]
i have tried above things not worked for me

iam getting below warning

android-sdk version check failed ("platforms\android\cordova\android_sdk_version"), continuing anyways.

**Comment by ishaiavrahami** [comment]
did anyone find a solution ?
