### ISSUE TITLE
iOS ( Ionic 3 ) - Notification fired every day without set trigger. 

### ISSUE THREAD

**Issue by renatogslopes** [katzer/cordova-plugin-local-notifications#1507]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

We scheduled a notification to take place two days later. After these two days we want the notification to be repeated every day at the same time. So to do this we added the attribute (every: 'day') in the notification constructor. 

IMPORTANT: On Android, this issue never happens with the same source code. 

## Your Environment

* Plugin version: 0.8.5
* Platform: iOS
* OS version: 11
* Device manufacturer / model: iPhone
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): iOS 4.3.1
* Ionic Version (if using Ionic) 3.19.0

## Expected Behavior
The expected result would be to receive the notification for the first time within two days, and thereafter receive the same notification daily. What really happens is that we received the notification in the next day and after that we received the notification every day. If we remove the attribute (every: 'day'), everything will run with expected. We received the notification within two days. 

## Actual Behavior

Scheduled Notifications are triggered within two days but the notifications are fired the next day. 

## Steps to Reproduce

  1. Scheduled Notifications on Friday to next Monday. 
this.localNotifications.cancelAll().then(() => {
      this.localNotifications.schedule({
        title: 'Test - Reminder',
        at: this.getNextMonday() //return date of next monday,
        text: "Hi guys", 
        every: 'day'
      });
    });
  2. Next day: Saturday the notification is fired
  3. Next day: Sunday the notification is fired
 
## Context

If we remove "every: 'day'" of the notification constructor, the notification are trigger to Monday and it is fired. At Saturday and Sunday (weekend) the notification pass and never fired. 

## Debug logs

nothing.

**Comment by katzer** [comment]
Thats not working with iOS10 anymore - There's no `firstAt` then every x anymore. That has been removed by Apple in favour of others. Please see the README. Therefore you have to upgrade to v0.9-beta.

To trigger every monday at 10 am:

```js
cordova.plugins.notification.local.schedule({ ..., trigger: { every: { weekday: 1, hour: 10, minute: 0 } } });
