### ISSUE TITLE
Installation faild: Error: Unexpected token } in JSON at position 2898

### ISSUE THREAD

**Issue by peratik** [katzer/cordova-plugin-local-notifications#1508]
Hello

Plugin install command not working:
```
cordova plugin add cordova-plugin-local-notification
Fetching plugin "cordova-plugin-local-notification" via npm
Error: Unexpected token } in JSON at position 2898
```

## My Environment

* Plugin version: Lates
* Platform: Android
* OS version: 7
* Device manufacturer / model: Samsung
* Cordova version: 6.5.0
* Cordova platform version: android 6.3.0
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior
Plugin installation complete without any errors. 

## Actual Behavior
Throws error.

## Steps to Reproduce
just a line command: cordova plugin add cordova-plugin-local-notification

## Context
Install the plugin.

## Debug logs
`Error: Unexpected token } in JSON at position 2898`

**Comment by rwillett** [comment]
Try again, worked for me 10 mins ago.

**Comment by katzer** [comment]
Please reopen if its not solved. Looks more like a temporary issue by NPM
