### ISSUE TITLE
Error: exec proxy not found for :: LocalNotification :: check

### ISSUE THREAD

**Issue by ThorvaldAagaard** [katzer/cordova-plugin-local-notifications#1509]
LocalNotification is missing a proxy for the Browser platform

## Your Environment

* Plugin version:
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
* Platform:
Browser
* OS version:
Windows 10
* Device manufacturer / model:
* Cordova version (```cordova -v```):
8.0.0
* Cordova platform version (```cordova platform ls```):
```
Installed platforms:
  android 6.3.0
  browser 5.0.1
Available platforms:
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```
* Plugin config
* Ionic Version (if using Ionic)
```
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.3.0 browser 5.0.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.3
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : D:\Documents\Android\Sdk

Misc:

    backend : pro
```

## Expected Behavior

I expect to PLugin to load a proxy on the Browser platform

## Actual Behavior
I get this message in the log: Error: exec proxy not found for :: LocalNotification :: check

## Steps to Reproduce
Build an app and deploy it on the Browser platform

## Context

Deploying my app to the browser platform

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by katzer** [comment]
Sorry but there's no support for the browser platform yet. Feel free to submit a PR 👍

**Comment by ThorvaldAagaard** [comment]
How and where ?

**Comment by leocharrua** [comment]
Hello. I have the same issue with the last version of the plugin (0.9.0-beta.2).
Still not working in browser in Windows 10?
I'm building a PWA in Ionic 4 with angular.
If not works ... Can you point me to another solution to get local notifications in browsers of Windows, Android (iOs 
I already lost hope)?
Thanks
