### ISSUE TITLE
Android crashing when trigger is not set

### ISSUE THREAD

**Issue by fmbuthia** [katzer/cordova-plugin-local-notifications#1510]
Samsung is crashing when trigger is not set.

## Your Environment

* Plugin version: lastest dev
* Platform: Android 
* OS version: 4.4 and 6.0
* Device manufacturer / model: samsung
* Cordova version (```cordova -v```): 7
* Cordova platform version (```cordova platform ls```): Android 
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

_Tell us what should happen_

## Actual Behavior

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment]
No code, no example, no logs.

**Comment by fmbuthia** [comment]
I am sorry this may have been a problem with my project, please close.
