### ISSUE TITLE
Trigger event is not working inside background mode on ios

### ISSUE THREAD

**Issue by ideagit-srikanth** [katzer/cordova-plugin-local-notifications#1511]
Hi, 
I have tested with android device notification trigger event works fine inside background mode plugin. But in ios 10 and above it's not capturing the event inside background mode. I have also tested with 0.9.beta.*.
Here is my code...
initializeBackground() {
    this.background.setDefaults(
      {
        title: 'Sync in progress',
        text: 'I\'am working in background',
        silent: true
      }
    );
    this.background.on('activate').subscribe(() => {
      this.database.createTable('test_table');
      this.notification.schedule({
        id: 1,
        title: 'Local ILocalNotification Example',
        text: 'Delayed ILocalNotification',
        firstAt: new Date(new Date().getTime() + 5000),
        every: 'minute',
        sound: null,
        data: { secret: 'key' }
      });
      this.notification.on('trigger', (notification) => {
        console.log(notification);
      });
    });
    this.background.on('deactivate').subscribe(() => {
      console.log('background deactivated');
      this.notification.cancelAll().then(notification => console.log('cancel', notification));
    });
    this.background.enable();
  }

**Comment by rwillett** [comment]
The plugin doesn't appear to generate the events if in background mode on IOS10. 

Not sure what you could do with the event anyway since you app is suspended if it is in the background.

**Comment by katzer** [comment]
Background execution is not an topic for this plugin. It also does not contain any code to prevent the app from being suspended on iOS. Because then nobody could submit the app into the store anymore. The thing that callbacks dont work anymore in background is system behaviour. The plugin itself does not optimise or take care of if the app is in foreground or background.

**Comment by ideagit-srikanth** [comment]
Thanks for the reply...
Yeah, I came to know that IOS wouldn't allows us to do background job only
push notification service has the ablity to do that for background sync.
Once again thanks for the plugin and your response.

---

Thanks & Regards

Srikanth M

Ideas2IT Technologies Services Pvt Ltd



DISCLAIMER:

This e-mail and any files transmitted with it are for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If you are not the intended recipient(s), please reply to
the sender and destroy all copies of the original message. Any review,
use, disclosure, dissemination, forwarding, printing or copying of
this email, and/or any action taken in reliance on the contents of
this e-mail is strictly prohibited and may be unlawful. Opinions,
conclusions and other information in this message that do not related
to official business of the company shall be understood to be neither
given nor endorsed byIdeas2IT Technologies. Any information contained
in this email, when addressed to Clients is subject to the terms and
conditions in governing the client contract.
