### ISSUE TITLE
It seems that PGB can't clone the repository

### ISSUE THREAD

**Issue by luissanchez0305** [katzer/cordova-plugin-local-notifications#1512]
## Your Environment

* Plugin version: 0.9 Beta 2
* Platform: Android and iOS
* OS version: 
* Device manufacturer / model:
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```):   android 6.3.0 ios 4.5.4
* Plugin config 
* Ionic Version (if using Ionic) 3.19.1

## Expected Behavior

When I run PGB it suppose to build and generate both packages APK and IPA

## Actual Behavior

I get an error on PGB "Error - Plugin (or a specific branch or tag) cannot be cloned from the repository: git+https://github.com/katzer/cordova-plugin-local-notifications.git"

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Normal installation of plugin "cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git"
  2. Normal push to my repository
  3. Normal build on PG

## Context

schedule a notification

## Debug logs

IOS Debug log on build
Build Date: 2018-01-21 22:47:31 -0800
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "ionic-plugin-keyboard@^2.2.1" via npm
Installing "ionic-plugin-keyboard" at "2.2.1" for ios
Fetching plugin "cordova-plugin-whitelist@^1.3.1" via npm
Installing "cordova-plugin-whitelist" at "1.3.3" for ios
Fetching plugin "cordova-plugin-device@^1.1.4" via npm
Installing "cordova-plugin-device" at "1.1.7" for ios
Fetching plugin "cordova-plugin-splashscreen@^4.0.3" via npm
Installing "cordova-plugin-splashscreen" at "4.1.0" for ios
Fetching plugin "cordova-plugin-ionic-webview@^1.1.16" via npm
Installing "cordova-plugin-ionic-webview" at "1.1.16" for ios
Fetching plugin "cordova-plugin-network-information@^2.0.1" via npm
Installing "cordova-plugin-network-information" at "2.0.1" for ios
Fetching plugin "cordova-plugin-networkinterface@^1.2.0" via npm
Installing "cordova-plugin-networkinterface" at "1.2.0" for ios
"plugman-151 install --platform ios --project /project --plugin git+https://github.com/katzer/cordova-plugin-local-notifications.git": Fetching plugin "git+https://github.com/katzer/cordova-plugin-local-notifications.git" via git clone
Cloning full repository
Failed to fetch plugin git+https://github.com/katzer/cordova-plugin-local-notifications.git via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: git: Command failed with exit code 128 Error output:
Cloning into '/var/folders/cj/hhlzcb3x7js3ls6gmqfplhhm0000gn/T/git/1516603650963'...
fatal: Unable to find remote helper for 'git+https'

Android debug log on Build
Build Date: 2018-01-22 06:47:23 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "ionic-plugin-keyboard@^2.2.1" via npm
Installing "ionic-plugin-keyboard" at "2.2.1" for android
Fetching plugin "cordova-plugin-whitelist@^1.3.1" via npm
Installing "cordova-plugin-whitelist" at "1.3.3" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-device@^1.1.4" via npm
Installing "cordova-plugin-device" at "1.1.7" for android
Fetching plugin "cordova-plugin-splashscreen@^4.0.3" via npm
Installing "cordova-plugin-splashscreen" at "4.1.0" for android
Fetching plugin "cordova-plugin-ionic-webview@^1.1.16" via npm
Installing "cordova-plugin-ionic-webview" at "1.1.16" for android
Fetching plugin "cordova-plugin-network-information@^2.0.1" via npm
Installing "cordova-plugin-network-information" at "2.0.1" for android
Fetching plugin "cordova-plugin-networkinterface@^1.2.0" via npm
Installing "cordova-plugin-networkinterface" at "1.2.0" for android
"plugman-151 install --platform android --project /project --plugin git+https://github.com/katzer/cordova-plugin-local-notifications.git": Fetching plugin "git+https://github.com/katzer/cordova-plugin-local-notifications.git" via git clone
Cloning full repository
Failed to fetch plugin git+https://github.com/katzer/cordova-plugin-local-notifications.git via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: git: Command failed with exit code 128 Error output:
Cloning into '/tmp/git/1516603643146'...
fatal: Unable to find remote helper for 'git+https'

**Comment by luissanchez0305** [comment]
I reinstall the plugin and now PGB says as follow:
Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: Manager.java - You can fix this here
Only on Android. I tried updating the android-minSdkVersion to 26, but the package won't run on my device, which has Android 7.0
The build log is:
Build Date: 2018-01-23 06:53:25 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "ionic-plugin-keyboard@^2.2.1" via npm
Installing "ionic-plugin-keyboard" at "2.2.1" for android
Fetching plugin "cordova-plugin-whitelist@^1.3.1" via npm
Installing "cordova-plugin-whitelist" at "1.3.3" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-device@^1.1.4" via npm
Installing "cordova-plugin-device" at "1.1.7" for android
Fetching plugin "cordova-plugin-splashscreen@^4.0.3" via npm
Installing "cordova-plugin-splashscreen" at "4.1.0" for android
Fetching plugin "cordova-plugin-ionic-webview@^1.1.16" via npm
Installing "cordova-plugin-ionic-webview" at "1.1.16" for android
Fetching plugin "cordova-plugin-network-information@^2.0.1" via npm
Installing "cordova-plugin-network-information" at "2.0.1" for android
Fetching plugin "cordova-plugin-networkinterface@^1.2.0" via npm
Installing "cordova-plugin-networkinterface" at "1.2.0" for android
Fetching plugin "cordova-plugin-local-notification@^0.9.0-beta.2" via npm
Installing "cordova-plugin-local-notification" at "0.9.0-beta.2" for android
Plugin dependency "cordova-plugin-device@1.1.7" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on android.
Fetching plugin "cordova-plugin-badge@>=0.8.5" via npm
Installing "cordova-plugin-badge" at "0.8.6" for android
Subproject Path: CordovaLib
Subproject Path: CordovaLib
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Subproject Path: CordovaLib
Configuration on demand is an incubating feature.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_6v3i16c4kxhjg4txvkvxl0h7z.run(/project/build.gradle:139)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareAndroidArchLifecycleRuntime100Library
:prepareComAndroidSupportSupportCompat2610Library
:prepareComAndroidSupportSupportCoreUi2610Library
:prepareComAndroidSupportSupportCoreUtils2610Library
:prepareComAndroidSupportSupportFragment2610Library
:prepareComAndroidSupportSupportMediaCompat2610Library
:prepareComAndroidSupportSupportV42610Library
:prepareMeLeolinShortcutBadger1119Library
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/project/src/de/appplant/cordova/plugin/notification/Manager.java:25: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
/project/src/de/appplant/cordova/plugin/notification/Manager.java:43: error: cannot find symbol
import static android.os.Build.VERSION_CODES.O;
^
  symbol:   static O
  location: class
/project/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
        if (SDK_INT < O)
                      ^
  symbol:   variable O
  location: class Manager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:115: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
        ^
  symbol:   class NotificationChannel
  location: class Manager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:115: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
                                         ^
  symbol:   method getNotificationChannel(String)
  location: variable mgr of type NotificationManager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:120: error: cannot find symbol
        channel = new NotificationChannel(
                      ^
  symbol:   class NotificationChannel
  location: class Manager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.499 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/project/src/de/appplant/cordova/plugin/notification/Manager.java:25: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
/project/src/de/appplant/cordova/plugin/notification/Manager.java:43: error: cannot find symbol
import static android.os.Build.VERSION_CODES.O;
^
  symbol:   static O
  location: class
/project/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
        if (SDK_INT < O)
                      ^
  symbol:   variable O
  location: class Manager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:115: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
        ^
  symbol:   class NotificationChannel
  location: class Manager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:115: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
                                         ^
  symbol:   method getNotificationChannel(String)
  location: variable mgr of type NotificationManager
/project/src/de/appplant/cordova/plugin/notification/Manager.java:120: error: cannot find symbol
        channel = new NotificationChannel(
                      ^
  symbol:   class NotificationChannel
  location: class Manager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by katzer** [comment]
From your above log I can imagine that `https://github.com/katzer/cordova-plugin-local-notifications.git` instead of `git+https://github.com/katzer/cordova-plugin-local-notifications.git` could help you.
