### ISSUE TITLE
Tabris Js integration

### ISSUE THREAD

**Issue by ishigo1987** [katzer/cordova-plugin-local-notifications#1513]
Hello i use this plugin(latest version) into a tabrisJs app and everything works fine i want to know something with this snippet
cordova.plugins.notification.local.on(event, callback, scope);
with tabris Js what mean scope?
when i'm click on the notification how to open my page on my app

**Comment by katzer** [comment]
The scope specifies the context in wich the callback will be invoked (`this`).

```js
cordova.plugins.notification.local.on(event, function () {
  // this === obj
}, obj);
```
