### ISSUE TITLE
Module "UserNotifications " are not found  using Xcode 7.3 with SDK 10

### ISSUE THREAD

**Issue by Ykeng** [katzer/cordova-plugin-local-notifications#1515]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.8.2dev
* Platform: ios 
* OS version: 10.11.1
* Device manufacturer / model:  
* Cordova version (```cordova -v```): 6.5.0
* Cordova platform version (```cordova platform ls```): 4.1.1 
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

my project can compiled succesed  when  using xcode7.3 with ios SDK 10  

## Actual Behavior

got an error about "module UserNotifications are not found "

**Comment by rwillett** [comment]
Not enough information.

Also Xcode 7.3 can't be used to target IOS 10 development unless you are compiling for a very old version of IOS and trying to run it on IOS10 which is not what you said.

Xcode is free so upgrade to the latest version so you can target IOS11 properly.

**Comment by Ykeng** [comment]
##### Thank you for your reply!!! 

my problem have been solved by upgrade both for Mac OS and Xcode to higher  version. But i forgot what  versions are. 
Sorry about  that. 

##### Thank you very much
