### ISSUE TITLE
Feature request: iOS download attachments prior to scheduling a notification

### ISSUE THREAD

**Issue by rapoell** [katzer/cordova-plugin-local-notifications#1516]
According the specifications in [UNNotificationAttachment](https://developer.apple.com/documentation/usernotifications/unnotificationattachment) iOS will only display locally stored images in the attachments property of a notification.

It would be a very welcome feature if the plugin could handle downloading the files in the attachments if they are remote urls and replace these original urls with the local urls of the downloaded files.

**Comment by katzer** [comment]
Even the plugin would support this, the download need to be done at schedule time, not at trigger time. That means at trigger time the temporary download might not be available anymore...
