### ISSUE TITLE
local notification doesn't work after upgrading the latest version (npm update)

### ISSUE THREAD

**Issue by nidhi1612** [katzer/cordova-plugin-local-notifications#1518]
Local notification give an error while ionic cordova build android after npm update. all the angular dependencies are upgraded to 5.*.* versions.

cli packages: 
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:
    cordova (Cordova CLI) : 7.0.1

local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 26.1.1
    Node              : v6.9.5
    npm               : 3.10.10
    OS                : Windows 10

* Plugin version: @ionic-native/local-notifications": "^4.5.3"
* Platform: android
* OS version: android 26 api level (oreo)

* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): android 6.2.3
* Plugin config: <plugin name="de.appplant.cordova.plugin.local-notification" spec="^0.8.5" />
<plugin name="cordova-plugin-local-notification" spec="^0.9.0-beta.2" />

* Ionic Version (if using Ionic): 3.19.1

ionic cordova build android should be successful, since it works well with older versions of dependencies.

```
 "@angular/common": "4.1.2", 
    "@angular/compiler": "4.1.2", 
    "@angular/compiler-cli": "4.1.2", 
    "@angular/core": "4.1.2", 
    "@angular/forms": "4.1.2", 
    "@angular/http": "4.1.2", 
    "@angular/platform-browser": "4.1.2", 
    "@angular/platform-browser-dynamic": "4.1.2", 
    "@ionic-native/core": "3.10.2", 
    "@ionic-native/local-notifications": "^4.3.0", 
     "app-scripts": "0.0.0", 
    "cordova-android": "^6.2.3", 
    "cordova-ios": "^4.5.0", 
    "cordova-plugin-app-event": "^1.2.1", 
     "cordova-plugin-compat": "^1.2.0", 
    "cordova-plugin-console": "^1.1.0", 
    "cordova-plugin-device": "^1.1.6", 
     "cordova-plugin-splashscreen": "^4.0.3", 
     "cordova.plugins.diagnostic": "^3.7.1", 
     "cors": "^2.8.4", 
     "de.appplant.cordova.plugin.local-notification": "^0.8.5", 
     "es6-promise-plugin": "^4.1.0", 
     "ionic-angular": "3.5.3", 
     "ionicons": "3.0.0", 
     "rxjs": "5.1.1", 
    "sw-toolbox": "3.6.0", 
    "zone.js": "0.8.11" 
```

after npm update dependencies versions are as below, 

```
"dependencies": {
        "@angular/common": "5.0.3",
        "@angular/compiler": "5.0.3",
        "@angular/compiler-cli": "5.0.3",
        "@angular/core": "5.0.3",
        "@angular/forms": "5.0.3",
        "@angular/http": "5.0.3",
        "@angular/platform-browser": "5.0.3",
        "@angular/platform-browser-dynamic": "5.0.3",
        "@ionic-native/core": "4.4.0",
        "@ionic-native/local-notifications": "^4.5.3",
        "@ionic-native/splash-screen": "4.4.0",
        "@ionic-native/status-bar": "4.4.0",
        "@ionic/storage": "2.1.3",
        "cordova-android": "^6.2.3",
        "cordova-plugin-badge": "^0.8.7",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-ionic-webview": "^1.1.11",
        "cordova-plugin-local-notification": "^0.9.0-beta.2",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-whitelist": "^1.3.1",
        "ionic-angular": "3.9.2",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.5.2",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.18"
    },

```

and when ionic cordova build android command is run, it throws below error.
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not resolve me.leolin:ShortcutBadger:1.1.21.
     Required by:
         project :
      > Could not resolve me.leolin:ShortcutBadger:1.1.21.
         > Could not get resource 'https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.21/ShortcutBadger-1.1.21.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.21/ShortcutBadger-1.1.21.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve me.leolin:ShortcutBadger:1.1.21.
         > Could not get resource 'https://jcenter.bintray.com/me/leolin/ShortcutBadger/1.1.21/ShortcutBadger-1.1.21.pom'.
            > Could not GET 'https://jcenter.bintray.com/me/leolin/ShortcutBadger/1.1.21/ShortcutBadger-1.1.21.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  

I notice that, after the update, when local notification plugin is added, it adds a plugin named "cordova-plugin-badge": "^0.8.7" and this plugin is causing the error.

## Steps to Reproduce:
1. create new ionic project.
2. install cordova-plugin-local-notifications
3. try building project for android - it throws the above error.

**Comment by katzer** [comment]
Try again... The version exist:
http://search.maven.org/#artifactdetails%7Cme.leolin%7CShortcutBadger%7C1.1.21%7C

You can also specify another version... See the README for cordova-plugin-badge.

**Comment by nidhi1612** [comment]
@katzer I am not able to understand. I am receiving error right after creating a new ionic project, (when i install the plugin) and try to do "ionic cordova build android". How should i try again. What settings should i change, in order to resolve error.

**Comment by katzer** [comment]
@nidhi1612 The error says that I cannot download the lib, however the lib+version does exist. My standard cordova-android gradle project can find and download the lib. So I guess it must be on your side or maybe maven was down at the time you tried.

**Comment by scorring** [comment]
Same problem. It seems it appears when I am working behind a proxy.
