### ISSUE TITLE
release 0.8.5, Android 8 - notifications do not appear in the notification center

### ISSUE THREAD

**Issue by wrenr** [katzer/cordova-plugin-local-notifications#1520]
Android 8 notifications do not appear in the notification center, but otherwise appear to function as expected.

While there are newer versions of the plugin, this issue has been created for the following reason:

- Reverting to 0.8.5 has been suggested as a workaround for #1449, but that may not an option for users that require Android 8 support. This would become a greater concern as Android 8 adoption rate increases.

## Your Environment

* Plugin version: 0.8.5
* Platform: Android
* OS version: Build Environment - Mac OS X; Device - Android 8.1.0
* Device manufacturer / model: Huawei Nexus 6P
* Cordova version (cordova -v): 8.0.0
* Cordova platform version (cordova platform ls): Android 7.0.0
* Plugin config: None (default)
* Ionic Version (if using Ionic): None (bare Cordova app)

## Expected Behavior

Notification appears in the notification center. The query method `.getAll()` returns the expected result. An event handler wired to the `trigger` event fires as expected.

## Actual Behavior

Notification _does not_ appear in the notification center. The query method `.getAll()` returns the expected result. An event handler wired to the `trigger` event fires as expected.

## Steps to Reproduce

  1. Start with an empty Cordova app.
  2. On deviceReady, schedule a notification 3 minutes into the future using `.schedule()`.
  3. (diagnostic) Create a `trigger` event with basic `console.log` output.
  4. (diagnostic) Run `getAll()` query.

## Context

This appears to be a silent failure. Aside from the notification not appearing in the notification center, some functionality appears to behave as expected.

This issue could quickly be marked as `resolved` because it is fixed as of the 0.9.0-beta-1 release. However, the primary purpose of this issue is to document potential 0.8.5 incompatibility with Android 8. If this issue can be confirmed on other Android 8 devices it would help paint a better picture of version 0.8.5's Android OS coverage.

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by katzer** [comment]
@wrenr v0.8.x does not support Android 8 - Android 8 has introduced a new API for notifications.

**Comment by wrenr** [comment]
Thank you for your response. Per the original Context, OS compatibility is documented and this issue can be closed.
