### ISSUE TITLE
Too Much Battery Consumption 

### ISSUE THREAD

**Issue by Deepankerchaudhary** [katzer/cordova-plugin-local-notifications#1521]
My battery is draining around more than 25% in 24 hours for iOS & Android both.
I am not able to find out any alternative. There is another plugin background-fetch but that is also not working.

**Comment by katzer** [comment]
@Deepankerchaudhary Does the issue belong to this repo?

**Comment by rwillett** [comment]
Why do you think this plugin is causing this? 

We haven't seen anything specific battery issues.

Rob
