### ISSUE TITLE
getAll() ,getAllScheduled() undefined 

### ISSUE THREAD

**Issue by bhumin3i** [katzer/cordova-plugin-local-notifications#1522]
i am getting error : 

```
setTimeout(function() {
              this.localNotifications.getAll(function (notifications) {
                console.log("getAll notifications: ");
                console.log(notifications);
              });
            }, 5000);
```

ON CONSOLE 

ERROR TypeError: Cannot read property 'getAll' of undefined
    at 5.js:458
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:5284)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask (polyfills.js:3)
    at i.isUsingGlobalCallback.invoke (polyfills.js:3)
    at n (polyfills.js:3)

:(

**Comment by rwillett** [comment]
No template, not enough information, no plugin version, no OS version. 

The template is there for a reason, I suspect that you have 'this' wrong but no idea really. .getAll() works as we use it.

**Comment by katzer** [comment]
Usually indicates that the plugin isn't installed or not loaded/available.
