### ISSUE TITLE
0.9.0-beta.2 fails to compile for android

### ISSUE THREAD

**Issue by dherbe** [katzer/cordova-plugin-local-notifications#1523]
Hi there and thanks for any help you might provide.
I've been using Local Notification plugin successfully up until version 0.8.5.
Today I've updated the plugin to the latest version of the master branch and fails to compile on Android. Compiles perfectly without errors for iOS.

## Environment
* Plugin version: Master branch (0.9.0-beta.2)
* Platform: Android only 
* Cordova version: 6.4.0

## Expected Behavior
Able to compile for android

## Actual Behavior
Fails to compile for android

## Debug logs
 Warning: Cannot include the following item(s) in your application: Plugins\cordova-plugin-background-mode-master\.travis.yml;Plugins\cordova-plugin-googlemaps-master\.cordova;Plugins\cordova-plugin-googlemaps-master\.github\ISSUE_TEMPLATE.md;Plugins\cordova-plugin-googlemaps-master\.gitignore;Plugins\cordova-plugin-image-resizer-master\.gitignore;Plugins\cordova-plugin-request-location-accuracy-master\.gitignore;Plugins\cordova-plugin-sim-master\.editorconfig;Plugins\cordova-plugin-sim-master\.gitattributes;Plugins\cordova-plugin-sim-master\.github\ISSUE_TEMPLATE.md;Plugins\cordova-plugin-sim-master\.gitignore;Plugins\CordovaCallNumberPlugin-master\.npmignore;Plugins\Insomnia-PhoneGap-Plugin-master\.gitignore. The build system treats items with a leading dot as hidden files or directories and does not process them. If you want to include these items in your application package, rename them and rebuild your app.
 android Build Tooling revision 2017.12.28.1r
 Build Tooling Hostname 7bda6465913f
 Warning: Note: Some input files use or override a deprecated API.
 Warning: Note: Recompile with -Xlint:deprecation for details.
 Warning: Note: Some input files use or override a deprecated API.
 Warning: Note: Recompile with -Xlint:deprecation for details.
 Warning: ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle
 Warning: ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight
 Warning: FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':processDebugResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt * Try:
 Warning: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 Warning: Error: /mnt/storage/builds/W2EguMVrdBcJUgGZlV/app/gradlew: Command failed with exit code 1 Error output: Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':processDebugResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. at ChildProcess.whenDone (/mnt/storage/builds/W2EguMVrdBcJUgGZlV/app/cordova/node_modules/cordova-common/src/superspawn.js:169:23) at emitTwo (events.js:106:13) at ChildProcess.emit (events.js:191:7) at maybeClose (internal/child_process.js:852:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
 Error: Build failed during execution
 Error: 'Build failed with error code 2'

Thanks for looking into this and for your time.

**Comment by rwillett** [comment]
This doesn't look an error with the plugin but rather with your build process.

You can test this by removing the local notification plugin and see if it compiles then. It may not run but at least you know it compiles. If it does compile, then add the plugin back in and see what happens then.

What other plugins have you got? What version of Android SDK?

**Comment by dherbe** [comment]
Thanks for your response,

If I remove the plugin, the build completes.
If I install this plugin but version 0.8.5, build works (it's actually what I'm using in production)
If I install this plugin latest version compiles great and works fine on iOS.

I also think it might be related to the building process on android, maybe some kind of dependencies (or Fonts related?) on the host server that are missing or not up to date?

Would appreciate plugin developers feedback and expertise on what might be causing this so I could properly address the issue with Telerik since app building processes are done in their hosts.

Thanks again.

**Comment by rwillett** [comment]
So how do you install the plugin?

I just did this and it worked fine. 

What other plugins do you have? What build of Android SDK are you using.

**Comment by dherbe** [comment]
Well one of the reasons the company went with Telerik Platform at the time (which will be discontinued in May), was because we had experienced people in coding but not familiar with Cordova and it's building process at all. Although since then we also opted for solutions like Xamarin we still have a couple of hybrid apps built this way.

So In Telerik Platform most config is done in their UI.
We can edit Manifests and Config.XML and such:
![image](https://user-images.githubusercontent.com/308554/35769845-77237ac6-0909-11e8-864d-aa287c7cddbf.png)

Regarding platform specific things, they are pretty simple and straightforward, for example:
in iOS (which is not being a problem)
![image](https://user-images.githubusercontent.com/308554/35769868-c383b264-0909-11e8-8dbd-b13c32e7346f.png)

on Android:
![image](https://user-images.githubusercontent.com/308554/35769874-e34fecf2-0909-11e8-93ae-1fe73d838f13.png)

And in general:
![image](https://user-images.githubusercontent.com/308554/35769883-fdc2f700-0909-11e8-9100-f6e7062c0332.png)

So this workflow have been working properly for a couple of years, a lot of plugins were installed and used over time without problems, but I agree with you, this error kind of sounds related with the building process for Android.

I will need to get in touch with Telerik, but I came here first in order to try to get more info, especially because, this plugin using the flow I've described above it's working properly for iOS and not for Android and I thought when I get in touch with them I could provide more specific details about this error.

Once again
thanks

**Comment by rwillett** [comment]
We just the command line and a normal editor, emacs, for the build process. Its not particularly difficult but I do recall that Telerik often build their own plugins. This may (or may not) be the issue.

I've uninstalled and reinstalled the plugin about 5-6 times today (for other reasons) and it works fine with our environment, but we're simple folk :)

I have never used Telerik so cannot comment.

**Comment by dherbe** [comment]
:) Right

thanks for your feedback @rwillett ended with node and cordova cli and you're right, it's really that easy.

Cheers
