### ISSUE TITLE
Question: How to schedule more than 64 notifications on iOS

### ISSUE THREAD

**Issue by mkn20** [katzer/cordova-plugin-local-notifications#1525]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.2 beta
* Platform: iOS
* OS version: iOS 10+
* Device manufacturer / model: Apple 
* Cordova version (```cordova -v```): 7.1
* Cordova platform version (```cordova platform ls```): iOS 4.3.1
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Should be able to schedule more than 64 notifications on iOS.

## Actual Behavior
Only soonest 64 notifications are scheduled. 

## Steps to Reproduce

Just simply schedule 64+ notifications for specific dates and times future and one can verify that only the soonest 64 are actually fired.

## Context

Scheduling more than 64 notifications for specific dates and times for iOS. It is more a question. Has anybody run into this and, if so, how has one solved it (if at all)? Apparently no notification can be scheduled when a scheduled notification is triggered. Any and all advice and strategies appreciated. If not, I guess further notifications can be scheduled on the next App launch.

 For Android however it looks like 170+ future notifications are not a problem. Is there a such a notification limit for Android? Don't seem to find an answer. Thanks in advance!

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment]
The IOS limit is just that, an IOS limit. 

There are two ways around this (that I can think of).

1. Require your user to start the app before the 64 notification limit runs out.
2. Move your notifications to a push server, e.g. OneSignal, PushWoosh, Urban Airship, Firebase etc etc

**Comment by mkn20** [comment]
Thank you very much for the reply. Could #1 be handled automatically by the plugin or be treated possibly as an enhancement request?

How about Android? Is there a practical limit there as well anybody has run into?

Thanks again and regards

**Comment by rwillett** [comment]
It is unlikely that you could do the extra scheduling by the plugin in the background. However I'm not the author. I do know that Apple is very, very strict on what you can do in the background for battery reasons and strongly suspect you can't.

I know Android has a bigger limit (if indeed there is one).

Moving to a PushServer is the quickest and easiest way to do this if you need lots of notifications OR they need to be created when the app is not running. OneSignal is free so costs nothing. The API to use it is easy, we had a service up and running in a couple of hours. You need a server to generate the notifications but there are loads of things around to help.

**Comment by Jacky9425** [comment]
Hi am trying to schedule a series notifications. The case would be:
on app starts, 64 notifications is scheduled for noon, 64 notifications is scheduled for night and 64 notifications is scheduled to the next morning.
Will all the notifications fire as expected or will it fires only on the next morning?

**Comment by Jacky9425** [comment]
also, does the 64 notifications limit only apply to the whole ios system or just one app at a time

eg.
if one app queued 64 notifications, the next incoming notifications from another app will discard the older notifications from the first app.

**Comment by schoendiener** [comment]
> also, does the 64 notifications limit only apply to the whole ios system or just one app at a time
> 
> eg. if one app queued 64 notifications, the next incoming notifications from another app will discard the older notifications from the first app.

Did you find an answer to this question?
