### ISSUE TITLE
Windows 10 Notification not working using the VS 2017 Cordova project template

### ISSUE THREAD

**Issue by maxxxxxxxim** [katzer/cordova-plugin-local-notifications#1526]
I'm trying to get local notification working for Windows 10. I've installed the plugin and I can see the reference has been added correctly! I've put the sample code to schedule a notification in deviceready and am getting this error:

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Toolkit.Uwp.Notifications, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified

## Your Environment

* Plugin version: 0.9-beta
* Platform: Windows
* OS version: 10
* Device manufacturer / model: N/A
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```):
* Plugin config 
* Ionic Version (if using Ionic)

## Expected Behavior

Expecting a notification to be displayed in Windows 10

## Actual Behavior

Getting this error: 
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Toolkit.Uwp.Notifications, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified

## Steps to Reproduce

_Reproduce this issue_ 

  1. Create a new Cordova project in VS 2017
  2. Add the local notification plugin to the project
  3. Put the sample schedule code in deviceready inside index.js
  4. Debug and observe the error

## Context

As above.

**Comment by rwillett** [comment]
AFAIK this plugin doesn't work with Windows 10. Some versions work with WIndows mobile. It defintely works with IOS and Android. I don't recall it working with Windows 10 at all.

**Comment by katzer** [comment]
@rwillett It is intended to work well for Windows 10. Because I have another project setup I got not this error but I can reproduce by fresh install.

**Comment by rwillett** [comment]
Apologies, I'll delete my comment.
