### ISSUE TITLE
after not working

### ISSUE THREAD

**Issue by craig-at-rsg** [katzer/cordova-plugin-local-notifications#1528]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
Repeating notification delays don't seem to work in iOS

## Your Environment

* Plugin version: 0.9.0-beta.1
* Platform: iOS
* OS version: 11
* Device manufacturer / model: tested on Apple iPhone 5, 5s, and 6
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):
Installed platforms:
  android 6.4.0
  ios 4.4.0

* Plugin config
localNotifications.setDefaults({ autoCancel: true, led: 'FFA500' });

* Ionic Version (if using Ionic): 1.1.1

## Expected Behavior

The Match every notifications should start "after" the specified date. 

## Actual Behavior

The repeated notifications start 

## Steps to Reproduce

firstStudyDayEndDate = new Date(firstStudyDayEndSecs * 1000);
localNotifications.schedule({
			id: 1,
			text: $translate.instant('BACKENDS.IOS.SURVEY_MAYBE_READY'),
			trigger: {
				every: {hour: 7, minute: 0}
			},
                        after: firstStudyDayEndDate,
			vibrate: true,
                        sound: null
		});

## Context
Trying to delay the notifications. Also tried {every: 'day', firstAt: secondDayAt7AMDate}, which didn't work either.

**Comment by rwillett** [comment]
Are you using the Ionic local notification or the one in this repository?

**Comment by craig-at-rsg** [comment]
We're using the ones with this plugin; here's the current URL we're using to pull the plugin: https://github.com/katzer/cordova-plugin-local-notifications#0.9.0-beta.1

**Comment by rwillett** [comment]
1. Strip the code down to the basics for the local notification.  Just schedule a simple notification 10 secs in the future, not just 1 sec. 

2. Comment out localNotifications.setDefaults. 

3. Where is localNotifications set? 

4. Are you waiting for device ready?

Post more code.

**Comment by craig-at-rsg** [comment]
Thanks for getting back to me, here are some responses.

1. I'm trying to start repeated notifications at a specific time, sometimes days in the future; I assume by suggesting 10s vs 1s there's a timing issue you're trying to avoid? I don't think that's the issue here. 

2. Ok, but this was my entire setDefaults:
localNotifications.setDefaults({ autoCancel: true, led: 'FFA500' });

3. It's just a reference to the plugin, called when my service is instantiated:
localNotifications = cordova.plugins.notification.local

4. Sort of - I'm using
ionic.Platform.ready(function () { ... })
around my entire app


> Post more code.
What else would you like to see?

**Comment by katzer** [comment]
@craig-at-rsg I think the README is wrong here. There's no support for `after` on iOS in combination with date matching components. I will fix the docs.

**Comment by craig-at-rsg** [comment]
Thanks @katzer.

Would this be the way to get a notification at roughly 7AM each day? I wasn't sure how subsequent notifications would be scheduled after the first one at "firstAt":

                    localNotifications.schedule({
						id: 1,
						text: $translate.instant('BACKENDS.IOS.SURVEY_MAYBE_READY'),
						trigger: {
						    every: 'day'
						},
						firstAt: sevenAmDay2
					});

**Comment by katzer** [comment]
```js
schedule({ id: 1, ..., trigger: { every: { hour: 7, minute: 0 } } })
```

**Comment by craig-at-rsg** [comment]
@katzer Thanks, but I only want it at 7 AM after a certain date - is there a way to say this with firstAt because after isn't supported on iOS? 

And, in your example, does "hour: 7" cause it to be triggered at 7 AM and 7 PM? We had a tester reporting they got a notification at 7 PM, but I would expect that to be "hour: 19". However this works, it might be a good note for the README.

**Comment by katzer** [comment]
> is there a way to say this with firstAt because after isn't supported on iOS?

You can also specify the fix date first and based on the action you may provide to the user the app can schedule another repeating notification. This is how Apple want to see it.

> does "hour: 7" cause it to be triggered at 7 AM and 7 PM?

7 AM!
