### ISSUE TITLE
Katzer Example-X not Working on Weekly Schedule

### ISSUE THREAD

**Issue by GeneralUSA** [katzer/cordova-plugin-local-notifications#1529]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:   initially the plugin that came with Example-X.  Updated this to ... 0.9.0-beta.2
* Platform:            iOS Simulator --  iPhone SE - iOS 10.2 (14C89)
* OS version:        OS X El Capitan 10.11.6
* Device manufacturer / model:   Mac Mini
* Cordova version (```cordova -v```):  8.0.0
* Cordova platform version (```cordova platform ls```):
    Installed platforms:
       ios 4.5.1
      windows 5.0.0
   Available platforms: 
      android ~7.0.0
      browser ~5.0.1
     osx ~4.0.1
     www ^3.12.0
* Plugin config
* Ionic Version (if using Ionic)      none

## Expected Behavior

_Tell us what should happen_
**Schedule weekly Notification to show every Monday at 10 AM local time**

## Actual Behavior

_Tell us what happens instead_
Scheduled under the INTERVAL button but never Triggered
All other buttons work correctly. But the Button under "Schedule" for "Interval" did not work

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...  at https://github.com/katzer/cordova-plug-local-notifications/tree/example-x
          made sure Branch said example-x
          download via green "clone or download" button
  2. ...  opened Terminal and typed "cordova run iOS" per the instructions at "...tree/example-x"
           tested the functions "as is" -- scheduled Interval. It worked every minute as expected
           opened index.js and changed
                            trigger: { every: {'minute'} },
                                         to
                            **trigger: { every: { weekday: 1, hour: 10, minute: 0 } },**
                                         also tried
                            trigger: { every: { weekday: 1, hour: 10, minute: 59 } },
  3. ...  in Terminal again ran the command
                  cordova run iOS
            Checked Permissions -- "Request" permission           
            tested other Scheduling buttons and they worked immediately
            Clicked "Interval" under "Schedule" category
            Changed internal clock to various Monday's at 10 AM
  4. ....  repeated step 3 but this time first running "cordova build iOS" then "cordova run iOS"
            also repeated step 3 using "cordova build" then "cordova run"
  5. ....  finally checked to see if the INTERVAL notification was present.
              clicked under "Presence" "Scheduled?" : "yes" pops up
                                                          "Triggered?"  : "no"                    // never triggered 
                                                          "Present?"  :    "yes"
                                                          "Type?"  :  "scheduled"
## Context

_What were you trying to do?_
Schedule repeat local notification for every Monday at 10:00 am local time, based on @katzer answers in other issues, including https://github.com/katzer/cordova-plugin-local-notifications/issues/1503

Changed system date to various Mondays and selecting system time anywhere between 9:55 am to 9:58 am. Tried with Katzer App Example-X opened and closed.

Checked PRESENCE: if still Scheduled and it was. Checked if Trigger was still present and it was. 

Only changes made to katzer index.js are in "text" and "trigger" below:
` 
   // Schedule a repeating notification
    scheduleInterval: function () {
        var sound = device.platform != 'iOS' ? 'file://sound.mp3' : 'file://beep.caf';

        cordova.plugins.notification.local.schedule({
            id: 1,
            text: 'Scheduled every Monday',
            trigger: { every: { weekday: 1, hour: 10, minute: 0 } },
            sound: sound,
            icon: 'res://icon',
            smallIcon: 'res://ic_popup_sync'
        });
    },
`

## Debug logs

_Include iOS / Android logs_

  * ios Xcode logs
Feb 12 09:58:25 mac logd[23780]: Time changed, updating file headers
Feb 12 09:58:25 mac syslogd[23771]: ASL Sender Statistics
Feb 12 09:58:25 mac logd[23780]: metadata shared cached uuid is null (using logd's shared cache info) IMAutomaticHist (23873)
Feb 12 09:58:25 mac logd[23780]: Failed to harvest strings for pathless uuid '00000000-0000-0000-0000-000000000000'
Feb 12 09:58:35 mac NotificationExample[23861]: [{"smallIcon":"res://ic_popup_sync","category":"DEFAULT_GROUP","id":1,"title":"","progressBar":{"enabled":false},"text":"Scheduled every Monday","sound":"file://beep.caf","trigger":{"every":{"weekday":1,"minute":0,"hour":10},"type":"calendar","at":1517842429},"attachments":[],"icon":"res://icon","actions":[]}]
Feb 12 09:58:38 mac SpringBoard[23786]: [DataStore] No data found at /Users/mac/Library/Developer/CoreSimulator/Devices/04D2F217-xxxx-xxxx-xxxx-0707FA609D455/data/Library/SpringBoard/PushStore/de.appplant.localnotification.example.pushstore
Feb 12 09:58:38 mac NotificationExample[23861]: []
Feb 12 09:58:43 mac SpringBoard[23786]: [DataStore] No data found at /Users/mac/Library/Developer/CoreSimulator/Devices/04D2F217-xxxx-xxxx-xxxx-0707FA609D455/data/Library/SpringBoard/PushStore/de.appplant.localnotification.example.pushstore
Feb 12 09:59:16 --- last message repeated 3 times ---
Feb 12 10:00:20 mac routined[23775]: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
 

Feb 18 09:58:50 mac logd[23780]: Time changed, updating file headers
Feb 18 09:58:50 mac syslogd[23771]: ASL Sender Statistics
Feb 18 09:58:51 mac logd[23780]: metadata shared cached uuid is null (using logd's shared cache info) IMAutomaticHist (23886)
Feb 18 09:58:51 mac logd[23780]: Failed to harvest strings for pathless uuid '00000000-0000-0000-0000-000000000000'
Feb 18 09:58:52 mac com.apple.CoreSimulator.SimDevice.04D2F217-xxxx-xxxx-xxxx-0707FA609D455.launchd_sim[23769] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Feb 18 09:58:52 mac com.apple.CoreSimulator.SimDevice.04D2F217-xxxx-xxxx-xxxx-0707FA609D455.launchd_sim[23769] (com.apple.imtranscoding.IMTranscoderAgent): Unknown key for integer: _DirtyJetsamPriority
Feb 18 09:58:52 mac com.apple.CoreSimulator.SimDevice.04D2F217-xxxx-xxxx-xxxx-0707FA609D455.launchd_sim[23769] (com.apple.imtranscoding.IMTranscoderAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Feb 18 09:58:52 mac com.apple.CoreSimulator.SimDevice.04D2F217-xxxx-xxxx-xxxx-0707FA609D455.launchd_sim[23769] (com.apple.imdmessageservices.IMDMessageServicesAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Feb 18 09:58:52 mac IMAutomaticHistoryDeletionAgent[23886]: [Warning] IMSharedHelperDeleteOrphanedStickerMMCSDownloadTokens error reading contents of directory at path /var/mobile/Library/SMS/transferInfo fileError Error Domain=NSCocoaErrorDomain Code=260 "The folder “transferInfo” doesn’t exist." UserInfo={NSFilePath=/var/mobile/Library/SMS/transferInfo, NSUserStringVariant=(
	    Folder
	), NSUnderlyingError=0x7f96f0d0a440 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Feb 18 09:58:52 mac IMAutomaticHistoryDeletionAgent[23886]: [Warning] Attachments. Error getting contents of directory /var/mobile/Library/SMS/StickerCache error Error Domain=NSCocoaErrorDomain Code=260 "The folder “StickerCache” doesn’t exist." UserInfo={NSFilePath=/var/mobile/Library/SMS/StickerCache, NSUserStringVariant=(
	    Folder
	), NSUnderlyingError=0x7f96f0d0fd90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Feb 18 09:58:52 mac IMAutomaticHistoryDeletionAgent[23886]: [Warning] Attachments. Could not delete browser snapshot cache at path /var/mobile/Library/Caches/com.apple.MobileSMS/BrowserSnapshots/
 
  * Android: $ adb logcat

**Comment by GeneralUSA** [comment]
UPDATE: part of issue was needing to install latest version of the plugin:
     ` cordova plugin rm cordova-plugin-local-notifications 0.0.0 "LocalNotification" `
Above is what I ran, but I suspect you only need to type 
   cordova plugin rm cordova-plugin-local-notifications

I then ran
     `  cordova plugin add cordova-plugin-local-notification@0.9.0-beta.2  `

 Despite this new update, the INTERVALs only showed the word "trigger" indicator once while the app was opened.
When I closed the app, it shows the notification Badge but no notification in the pull down Notification Window. The Interval Notification never triggered again as I manipulated date and time in System settings to match the expected interval.

**Comment by Tawpie** [comment]
One testing note for iOS: when you set the date and time, set it a little earlier than the time you expect the notification to be triggered. iOS has to have the system time pass _through_ the trigger time—the OS won’t trigger a notification whose time has already passed. I don’t know it it’ll change anything, but when you are moving the phone’s time around it’s an important detail.

**Comment by GeneralUSA** [comment]
Thank you, @Tawpie. I will move it to about 5 minutes before I expect the notification.

**Comment by katzer** [comment]
I tried with master and cannot see an issue. The next trigger date was calculated correctly. I also just made a commit to log the next trigger date in debug mode. That makes it easy to follow when the system will trigger the notification.

**Comment by GeneralUSA** [comment]
Simulator never really worked well for me on "Scheduled Interval", whether I ran it via the Terminal CLI or via Xcode directly. But for the actual device -- perhaps it was an environment settings thing. Not sure. Got it to work on the actual iPhone 5 by installing iOS-deploy (which I had previously gotten sidetracked from doing) and also Signing the Example-X app inside of Xcode.

If anyone cares to read all the below--which is written for the most part as I tried to troubleshoot-- have at it. 

@katzer and @Tawpie thank you both. I also had come to understand more about waiting past the 10 AM marker as Tawpie suggested. 

At the very bottom of this comment are deprecation warning messages, if you are interested, Katzer.

Thank you both.

////////// my steps and frustrations for anyone still having issues and looking for solutions  /////

This still is not working for me @katzer. Yes, to clarify: Monday, 1; Tuesday, 2; Wednesday, 3...

I noticed earlier on that the Example-X comes with cordova-plugin-local-notifications 0.0.0 "LocalNotification" .  I've removed this plugin a few times with the **cordova plugin rm cordoba-plugin-local-**notification**s**; and I removed this manually from config.xml and package.json files. I then added cordoba-plugin-local-notification (singular notification w/o s). It still has not worked.
I'm not strong on debug so tried to research before responding. And I discovered that I could open my cordova project directly in Xcode via the folder: platform>ios>[fileName].xcodeproj. (A positive that I'm sure experienced programmers know about). 

`->$ cordova plugin rm cordova-plugin-local-notifications
Uninstalling cordova-plugin-local-notifications from ios
Uninstalling cordova-plugin-local-notifications from windows
Removing "cordova-plugin-local-notifications"
(node:3025) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError
(node:3025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

`->$ cordova plugin add cordova-plugin-local-notification
Installing "cordova-plugin-local-notification" for ios
Plugin dependency "cordova-plugin-device@1.1.6" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on ios.
Installing "cordova-plugin-badge" for ios
Installing "cordova-plugin-local-notification" for windows
Plugin dependency "cordova-plugin-device@1.1.6" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on windows.
Plugin dependency "cordova-plugin-badge@0.8.7" already fetched, using that version.
Installing "cordova-plugin-badge" for windows
Adding cordova-plugin-local-notification to package.json
Saved plugin info for "cordova-plugin-local-notification" to config.xml

/cordova-plugin-local-notifications-example-x
->$ cordova plugin --list
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-x-toast 2.6.0 "Toast"`

The X-Code "debugger output" window never showed anything.

After I installed 0.9.0-beta.2 the Single Schedule just showed "Triggered: 1" in lower part of view screen, but no local notification notice ever showed in foreground or in notification pull down window. The badge count "1" did show though. And later it showed a count of "12". But nothing in notification window.

On a recent cordova build, it said I needed to also install iso-deploy
     `npm install -g iso-deploy`
I now remember trying to install this once before but stuff was going wrong and it never got done.
Also, during the process of discovering I could open my cordova project in Xcode, I also had to play around with Provisioning Stuff.

So the attached iPhone 5 ran well once the iso-deploy was installed and Provisioning/Signing keys in place. Big tip for me & others new like me: Change the time first, then the date. I think I might have been rolling through stuff. Not really sure, but I noticed that this held true on actual phone. And I built this version via the Terminal, not via Xcode directly. Not sure if that matters.

As for Simulator built via Xcode, it triggered at right time only once, and it never showed message. Even when I restarted the Simulator ... and when I "Reset Content & Settings" under "Simulator" (top left) of window for those of you new to Mac, like I am.


////////   **Warnings found in Termina**l (and look similar to Xcode warnings) that may or may not be useful to the Katzer project:

`
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:60:9: warning: 
      'ALAssetsLibraryAssetForURLResultBlock' is deprecated: first deprecated in iOS
      9.0 - Use fetchAssetsWithLocalIdentifiers:options: on PHAsset to fetch assets by
      local identifier (or to lookup PHAssets by a previously known
      ALAssetPropertyAssetURL use fetchAssetsWithALAssetURLs:options:) from the Photos
      framework instead [-Wdeprecated-declarations]
        ALAssetsLibraryAssetForURLResultBlock resultBlock = ^(ALAsset* asset) {
        ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetsLibrary.h:64:16: note: 
      'ALAssetsLibraryAssetForURLResultBlock' has been explicitly marked deprecated
      here
typedef void (^ALAssetsLibraryAssetForURLResultBlock)(ALAsset *asset) NS_DEPREC...
               ^
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:63:69: warning: 
      'defaultRepresentation' is deprecated: first deprecated in iOS 9.0 - Use
      PHImageRequestOptions with the PHImageManager from the Photos framework instead
      [-Wdeprecated-declarations]
                ALAssetRepresentation* assetRepresentation = [asset defaultRepr...
                                                                    ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAsset.h:51:1: note: 
      'defaultRepresentation' has been explicitly marked deprecated here
- (ALAssetRepresentation *)defaultRepresentation NS_DEPRECATED_IOS(4_0, 9_0, "U...
^
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:64:142: warning: 
      'UTI' is deprecated: first deprecated in iOS 9.0 - Use
      requestImageDataForAsset:options:resultHandler: on PHImageManager for a PHAsset
      to request image data from the Photos framework and check the dataUTI passed to
      your result handler instead [-Wdeprecated-declarations]
  ...CFStringRef)[assetRepresentation UTI], kUTTagClassMIMEType);
                                      ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetRepresentation.h:28:1: note: 
      'UTI' has been explicitly marked deprecated here
- (NSString *)UTI NS_DEPRECATED_IOS(4_0, 9_0, "Use requestImageDataForAsset:opt...
^
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:65:82: warning: 
      'size' is deprecated: first deprecated in iOS 9.0 - Use
      requestImageDataForAsset:options:resultHandler: on PHImageManager to request
      image data for a PHAsset from the Photos framework instead
      [-Wdeprecated-declarations]
  ...Byte* buffer = (Byte*)malloc((unsigned long)[assetRepresentation size]);
                                                                      ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetRepresentation.h:34:1: note: 
      'size' has been explicitly marked deprecated here
- (long long)size NS_DEPRECATED_IOS(4_0, 9_0, "Use requestImageDataForAsset:opt...
^
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:66:133: warning: 
      'size' is deprecated: first deprecated in iOS 9.0 - Use
      requestImageDataForAsset:options:resultHandler: on PHImageManager to request
      image data for a PHAsset from the Photos framework instead
      [-Wdeprecated-declarations]
  ...getBytes:buffer fromOffset:0.0 length:(NSUInteger)[assetRepresentation size] er...
                                                                            ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetRepresentation.h:34:1: note: 
      'size' has been explicitly marked deprecated here
- (long long)size NS_DEPRECATED_IOS(4_0, 9_0, "Use requestImageDataForAsset:opt...
^
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:66:62: warning: 
      'getBytes:fromOffset:length:error:' is deprecated: first deprecated in iOS 9.0 -
      Use requestImageDataForAsset:options:resultHandler: on PHImageManager to request
      image data for a PHAsset from the Photos framework instead
      [-Wdeprecated-declarations]
                NSUInteger bufferSize = [assetRepresentation getBytes:buffer fr...
                                                             ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetRepresentation.h:40:1: note: 
      'getBytes:fromOffset:length:error:' has been explicitly marked deprecated here
- (NSUInteger)getBytes:(uint8_t *)buffer fromOffset:(long long)offset length:(N...
^
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:60:63: warning: 
      'ALAsset' is deprecated: first deprecated in iOS 9.0 - Use PHAsset from the
      Photos framework instead [-Wdeprecated-declarations]
        ALAssetsLibraryAssetForURLResultBlock resultBlock = ^(ALAsset* asset) {
                                                              ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAsset.h:42:12: note: 
      'ALAsset' has been explicitly marked deprecated here
@interface ALAsset : NSObject {
           ^
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:63:17: warning: 
      'ALAssetRepresentation' is deprecated: first deprecated in iOS 9.0 - Use
      PHImageRequestOptions with the PHImageManager from the Photos framework instead
      [-Wdeprecated-declarations]
                ALAssetRepresentation* assetRepresentation = [asset defaultRepr...
                ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetRepresentation.h:22:12: note: 
      'ALAssetRepresentation' has been explicitly marked deprecated here
@interface ALAssetRepresentation : NSObject {
           ^
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:74:9: warning: 
      'ALAssetsLibraryAccessFailureBlock' is deprecated: first deprecated in iOS 9.0 -
      Use the Photos framework instead [-Wdeprecated-declarations]
        ALAssetsLibraryAccessFailureBlock failureBlock = ^(NSError* error) {
        ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetsLibrary.h:71:16: note: 
      'ALAssetsLibraryAccessFailureBlock' has been explicitly marked deprecated here
typedef void (^ALAssetsLibraryAccessFailureBlock)(NSError *error) NS_DEPRECATED...
               ^
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:79:9: warning: 
      'ALAssetsLibrary' is deprecated: first deprecated in iOS 9.0 - Use PHPhotoLibrary
      from the Photos framework instead [-Wdeprecated-declarations]
        ALAssetsLibrary* assetsLibrary = [[ALAssetsLibrary alloc] init];
        ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetsLibrary.h:80:12: note: 
      'ALAssetsLibrary' has been explicitly marked deprecated here
@interface ALAssetsLibrary : NSObject {
           ^
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:79:60: warning: 
      'ALAssetsLibrary' is deprecated: first deprecated in iOS 9.0 - Use PHPhotoLibrary
      from the Photos framework instead [-Wdeprecated-declarations]
        ALAssetsLibrary* assetsLibrary = [[ALAssetsLibrary alloc] init];
                                                           ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetsLibrary.h:80:12: note: 
      'ALAssetsLibrary' has been explicitly marked deprecated here
@interface ALAssetsLibrary : NSObject {
           ^
/Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:80:24: warning: 
      'assetForURL:resultBlock:failureBlock:' is deprecated: first deprecated in iOS
      9.0 - Use fetchAssetsWithLocalIdentifiers:options: on PHAsset to fetch assets by
      local identifier (or to lookup PHAssets by a previously known
      ALAssetPropertyAssetURL use fetchAssetsWithALAssetURLs:options:) from the Photos
      framework instead [-Wdeprecated-declarations]
        [assetsLibrary assetForURL:url resultBlock:resultBlock failureBlock:fai...
                       ^
In module 'AssetsLibrary' imported from /Users/mac/Documents/cordova-plugin-local-notifications-example-x/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetsLibrary.h:95:1: note: 
      'assetForURL:resultBlock:failureBlock:' has been explicitly marked deprecated
      here
- (void)assetForURL:(NSURL *)assetURL resultBlock:(ALAssetsLibraryAssetForURLRe...
^
12 warnings generated.
`

**Comment by katzer** [comment]
@GeneralUSA You need to install beta.3 or use the master branch.

**Comment by GeneralUSA** [comment]
Oh, okay. Got beta2 working thanks to you @katzer and @Tawpie, but I'll install beta.3.
One extra question, how do I make the popup happen to let user know when s/he clicks on the "Schedule Interval"? It feels so "quiet" without a confirmation popup, like for "Cancel All." Tried to duplicate the same format but without success.

**Comment by katzer** [comment]
@GeneralUSA What do you mean with

> when s/he clicks on the "Schedule Interval"?

**Comment by GeneralUSA** [comment]
Hi @katzer, yes ... in testing, I click "are notifications allowed?" and popup text is "index.html ... Yes". Also works on cancel Notifications, "index.html ... Notifications cancelled". But when I click the Schedule Interval Notification, no popup to indicate that the notification has been set (and I know this is an issue with my lack of experience, so still working it out) -- but the notification interval is set and does work perfectly on iOS 10 system. Below is the code I've been messing around with trying to figure ... For all intensive purposes though ... you are busy and my initial issue is resolved.

`
/*
 * Licensed to ...
 * under the License.
 */

var app = {
    // Application Constructor
    initialize: function () {
        this.bindEvents();
    },
    // Bind Event Listeners
    //
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function () {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    //
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicitly call 'app.receivedEvent(...);'
    onDeviceReady: function () {
        app.receivedEvent('deviceready');
        app.pluginInitialize();
        app.bindNotificationEvents();
    },
    // Update DOM on a Received Event
    receivedEvent: function (id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    },
    // Initialize plugin
    pluginInitialize: function () {
        document.getElementById('granted').onclick         = app.hasPermission;
        document.getElementById('request').onclick         = app.askPermission;
        document.getElementById('sched_interval').onclick  = app.scheduleInterval;
        document.getElementById('schedule?').onclick       = app.isScheduled;
        document.getElementById('cancel_all').onclick      = app.cancelAll;

        var details = cordova.plugins.notification.local.launchDetails;

        if (details) {
            alert('Launched by notification with ID ' + details.id);
        }
    },
    // Check permissions to read accounts
    hasPermission: function () {
        cordova.plugins.notification.local.hasPermission(function (granted) {
            showToast(granted ? 'Yes allowed' : 'Not yet allowed');
        });
    },
    // Request permissions to read accounts
    askPermission: function () {
        cordova.plugins.notification.local.requestPermission(function (granted) {
            showToast(granted ? 'Yes' : 'No');
        });
    },
    
    
    // Schedule a repeating notification
    scheduleInterval: function () {
        var sound = device.platform !== 'iOS' ? 'file://sound.mp3' : 'file://beep.caf';

        cordova.plugins.notification.local.schedule({
            id: 1,
            title: 'Weekly',
            text: 'Open app reminder.',
            trigger: { every:  {weekday: 1, hour: 10, minute: 0} },
            sound: sound,
            icon: 'res://icon'
        });
    },

    // Cancel all notifications
    cancelAll: function () {
        cordova.plugins.notification.local.cancelAll(app.ids);
    },
    
        // Get a single notification
    notification: function () {
        cordova.plugins.notification.local.get(1, function (obj) {
            console.log(obj);
            showToast(obj ? obj.toString() : '- none -');
        });
    },
    // Get a single notification ...gu
/*    isScheduled: function () {
        cordova.plugins.notification.local.get(1, function (obj) {
            console.log(obj);
            showToast(obj ? obj.toString() : 'toast');  // - none -
        });
    },*/
    
    // Get all notifications ... gu
/*    notification: function() {
        cordova.plugins.notification.local.getAll(function(nots) {
            console.log(nots);
            showToast(nots.length === 0 ? '- none -' : nots.join(' ,'));
        });
    },
    */
    // Listen for events
    bindNotificationEvents: function () {
        cordova.plugins.notification.local.on('schedule', function (obj) {
            console.log('schedule', arguments);
            showToast('scheduled: ' + obj.id);   // this toast was commented out ... gu
        });
        cordova.plugins.notification.local.on('trigger', function (obj) {
            console.log('trigger', arguments);
            showToast('triggered: ' + obj.id);
        });
        cordova.plugins.notification.local.on('click', function (obj) {
            console.log('click', arguments);
            showToast('clicked: ' + obj.id);
        });
        cordova.plugins.notification.local.on('cancelall', function () {
            console.log('cancelall', arguments);
            showToast('Notifications cancelled');   // this was commented out ... gu
        });
        
        // gu ... schInt test...
/*         cordova.plugins.notification.local.on('scheduleInterval', function () {
            console.log('scheduleInterval', arguments);
            showToast('Notifications scheduled');   
        });*/
        
            // If the notification is scheduled ...gu
/*    isScheduled: function () {
        cordova.plugins.notification.local.isScheduled(1, function(scheduled?) {
            showToast(scheduled ? 'Yes 10 AM, Mondays' : 'No');
        });
    }, */   

   // gu... 
/*    scheduleInterval: function () {
        cordova.plugins.notification.local.scheduleInterval(function(sched_interval) {
            showToast(scheduled ? 'Yes 10 AM' : 'Nope');
        });
    },  */        
        
        
    }
};

var dialog;

showToast = function (text) {
    var isMac = navigator.userAgent.toLowerCase().includes('macintosh');

    setTimeout(function () {
        if (window.Windows !== undefined) {
            showWinDialog(text);
        } else
        if (!isMac && window.plugins && window.plugins.toast) {
            window.plugins.toast.showShortBottom(String(text));
        }
        else {
            alert(text);
        }
    }, 500);
};

showWinDialog = function (text) {
    if (dialog) {
        dialog.content = text;
        return;
    }

    dialog = new Windows.UI.Popups.MessageDialog(text);

    dialog.showAsync().done(function () {
        dialog = null;
    });
};

if (window.hasOwnProperty('Windows')) {
    alert = showWinDialog;
}

app.initialize();
`

**Comment by GeneralUSA** [comment]
HTML code
`
             <div id="katzer">
                    <div>
                        <p>&nbsp;</p>
                    </div>
                    <div class="app">
                        <h1></h1>
                        <div id="deviceready" class="blink">
                            <p class="event listening"></p>
                            <p class="event received"></p>
                        </div>
                    </div>
                    <h1 class="section">Permissions</h1>

                    <p class="container">
                    <a id="request"></a>
                    </p>
                    <p class="container">
                    <a id="granted"  class="button blue">Are notifications allowed?</a>
                    </p>

                    <p class="container">
                    <a id="sched_interval"  class="button alt">Schedule Mondays 10 AM</a>
                    </p>
                    <p class="container">
                    <a id="scheduled?"  class="button blue">Did I schedule?</a>
                    </p>                    
                    <p class="container">
                    <a id="cancel_all"     class="button alt"> Cancel notifications</a>
                    </p>
                    
                    
                    
                    <div><p>&nbsp;</p></div>
                </div>
`
