### ISSUE TITLE
Notification action data not delivered on app startup (IOS)

### ISSUE THREAD

**Issue by AlecMRogers** [katzer/cordova-plugin-local-notifications#1530]
I'm trying to get information about what action the user selected for a notification that has elapsed while the app was closed.

Though Im not familiar with the IOS code enough to make changes, is it possible that "didReceiveNotificationResponse" method needs to provide the "data" argument to the startup callback?

Also, thanks for this wonderful plugin.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: IOS
* OS version: 11.2.5
* Device manufacturer / model: 5 plus
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): ios 4.5.4
* Plugin config ?
* Ionic Version (if using Ionic) N/A

## Expected Behavior

Using the following code:
            cordova.plugins.notification.local.addActionGroup('mindful', [
                { id: 'yes', title: 'Mindful' },
                { id: 'no',  title: 'Not Mindful'}
            ], this.survey, this);
            cordova.plugins.notification.local.on('yes', this.surveyResponse.bind(this, true));
            cordova.plugins.notification.local.on('no', this.surveyResponse.bind(this, false));

callbacks to surveyResponse() work when the app is open.
There is a callback to this.survey() at app startup, I expect dat to be passed to the this.survey() method

## Actual Behavior

no arguments are passed to the this.survey() method on startup 

## Steps to Reproduce

1. Schedule a notification that elapses when the app is closed.
2. Try to get information about what action the user selected when the app starts up again.

## Context

Trying to get information about what action the user selected when the app starts up again.

## Debug logs

N/A

**Comment by AlecMRogers** [comment]
Is it possible that I am not registering the following callbacks before they are called by the plugin?

cordova.plugins.notification.local.on('yes', this.surveyResponse.bind(this, true));
cordova.plugins.notification.local.on('no', this.surveyResponse.bind(this, false));

**Comment by katzer** [comment]
@AlecMRogers I think you should install from master because you need [these](https://github.com/katzer/cordova-plugin-local-notifications/commit/689f47b9a6373c3bdc1fa3e41be8be3a019096d7) commit. I noticed that It was bad idea to remove the flag after the release of beta.2

**Comment by AlecMRogers** [comment]
Great! Works with the latest changes (I also used fireQueuedEvents() to defer initialization, in case that was the issue), OK to close this.  Thanks again.
