### ISSUE TITLE
Android dose not play sound !

### ISSUE THREAD

**Issue by klochko7** [katzer/cordova-plugin-local-notifications#1531]
Good day ! I am using cordova-plugin-local-notification version 0.9.0-beta.2 but on Android dose not play sound. Help please !

```
        win.cordova.plugins.notification.local.schedule({
          id: Math.floor(Math.random()),
          title: 'Mobile',
          text: 'Updating Complete!',
          trigger: { in: 1, unit: 'second' },
          sound:  'res://platform_default',
          icon: 'file://assets/icon/download.png',
          smallIcon: 'file://assets/icon/download.png'
        });
```

**Comment by rwillett** [comment]
1. Do not cross post. 

2. The template is there for a reason. Use it.

**Comment by katzer** [comment]
@klochko7 Because you do not specify a sound file: `'res://platform_default'` does not exist anymore.

Either you use `sound:true` for the default sound or you specify a path to a valid sound file.
