### ISSUE TITLE
keep notification shade open upon clicking action button?

### ISSUE THREAD

**Issue by m52go** [katzer/cordova-plugin-local-notifications#1534]
notification clicked --> notification shade closes and app opens --> good.
action button clicked --> notification shade closes --> not always good?

especially if the action results in the related notification still showing.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: android
* OS version: 7.1.1
* Device manufacturer / model: nexus 6
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): android 6.3.0
* Ionic Version (if using Ionic): 3.19.1
* Plugin config

```
this.localNotifications.on( 'switch-book', function( note, event ) {
    that.localNotifications.update({
        id: note.id,
        title: "Loading next book.",
        text: "Just a second...",
        ongoing: true,
        priority: -2,
        sound: null,
        color: null,
        led: null,
        smallIcon: 'res://ic_stat_notify.png',
        icon: null
    });
});
```

## Expected Behavior

notification drawer should stay open if action does not result in clearing its notification.

## Actual Behavior

notification drawer is closed no matter what: on notification click, action click, etc.

## Steps to Reproduce

create new notification with action button. have action button do anything (or nothing), and notification shade will close every time whenever an action button is clicked.

## Context

one of my action buttons updates the notification it's attached to. it's confusing for the user if the 'update' action button results in the whole notification shade closing, when they were just looking for the notification to update.

example: android's default sms app ('messages') provides a 'mark as read' action for new text messages. upon clicking that action, the message is marked as read, and the notification shade remains open.

**Comment by katzer** [comment]
I cannot reproduce - also please use `sticky:true`. `ongoing` is deprecated.

**Comment by m52go** [comment]
hi @katzer, thanks for quick turnaround & your ongoing work on this plugin.

were you getting this behavior? i recorded a [quick screen grab](https://youtu.be/vb3mrsGyzPo).

notification closes every time notification is tapped, no matter what:
- when notification body is clicked & launch is true (i.e., app opens) --> expected, preferred
- when notification body is clicked & launch is false (i.e., app doesn't open) --> indifferent/whatever
- when action button with no assigned function --> not preferred
- when action button WITH assigned function --> not preferred

if that behavior seems odd to you, i started a [brand-new project with code](https://github.com/m52go/cordova-localnotes-shadecollapse). it's literally just a blank project with the plugin added. it uses ionic but i'm not sure that matters.

for what it's worth, i went through as much of the plugin code as i could to try determining where the notification shade collapse action could be, but i didn't see anything of the sort.

**Comment by m52go** [comment]
for the record, it looks like this happens because `getActivity` is designed to close the notification shade whereas `getService` and `getBroadcast` aren't ([source](https://stackoverflow.com/questions/18261969/clicking-android-notification-actions-does-not-close-notification-drawer)). indeed, i tested, and the shade doesn't close when `getactivity` is changed to `getBroadcast` in `getPendingIntentForAction`. 

but of course that screws up the receivers so the events themselves never fire :)

so i'll close this for now. but if this is ever an issue in the future...maybe this helps.

**Comment by katzer** [comment]
@m52go See c008cc6

**Comment by m52go** [comment]
omg it's perfect! you made my WEEK sir!! sending you an email at contact at appplant.

**Comment by m52go** [comment]
@katzer omg it's perfect! you made my WEEK sir!! sending you an email at contact at appplant.
