### ISSUE TITLE
Icon, smallIcon & attachments

### ISSUE THREAD

**Issue by jabelcs** [katzer/cordova-plugin-local-notifications#1536]
## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version: 7.0 & 5.1
* Device manufacturer / model: Samsung Galaxy Tab A & Doogee X5pro
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): 6.3.0
* Plugin config

## Expected Behavior

Show notification icon;
show smallIcon & attachment using downloaded images;

## Actual Behavior

None of the images is showing

## Steps to Reproduce

  1. Create a new cordova project in Visual Studio 2017
  2. Added the necessary plugins
  3. On device ready:
cordova.plugins.notification.local.schedule({
            id: '999',
            title: 'Sample',
            text: 'teste',
            attachments: ['file://data/data/pt.dietmed.dietapura/files/imagens/img_666.jpg'],
            smallIcon: 'res://icon',
            icon: 'file://data/data/pt.dietmed.dietapura/files/imagens/img_666.jpg',
            color: 'a92b27',
            trigger: { every: 'minute', count: 5 }
 });

in config.xml:

\<platform name="android">
        ...
        \<resource-file src="www/images/icon_xxxhdpi.png" target="res/drawable/icon.png" />
        \<resource-file src="www/images/icon_ldpi.png" target="res/drawable-ldpi/icon.png" />
        \<resource-file src="www/images/icon_mdpi.png" target="res/drawable-mdpi/icon.png" />
        \<resource-file src="www/images/icon_hdpi.png" target="res/drawable-hdpi/icon.png" />
        \<resource-file src="www/images/icon_xhdpi.png" target="res/drawable-xhdpi/icon.png" />
        \<resource-file src="www/images/icon_xxhdpi.png" target="res/drawable-xxhdpi/icon.png" />
        \<resource-file src="www/images/icon_xxxhdpi.png" target="res/drawable-xxxhdpi/icon.png" />
\</platform>

## Context

- SmallIcon never shows up;
- Icon and attachments shows when using internet url (Ex.: http://www.something.com/image.png) or images compiled with the app (file://images/image.png).
- What I would really need is the notification to use downloaded images because the app needs to be accessible offline.
- In Doogee with android 5.1 the image is downloaded to  "file:///data/data/pt.dietmed.dietapura/files/imagens/img_666.jpg"
- In Samsung with android 7.0 the image is downloaded to "file:///data/user/0/pt.dietmed.dietapura/files/imagens/img_666.jpg"

Any help on this would be very appreciated.

Thanks in advance.

**Comment by katzer** [comment]
@jabelcs `file://` points to your asset folder within the app, where also your app.js, index.html, ... is located. If you use a file outside of your app than you have to provide the absolute path `file:///` and of course the app needs to have the permission to read the file.

**Comment by jabelcs** [comment]
@katzer Many thanks for your response.

Already tried file:/// but with no luck, maybe read permissions as you said?

How can I give the app read permissions?

Thanks in advance.

**Comment by katzer** [comment]
@jabelcs I tried with the `cordova-plugin-camera` and these options:

```js
var options = {
    destinationType: Camera.DestinationType.FILE_URI,
    sourceType: Camera.PictureSourceType.PHOTOLIBRARY
};
```

Then `navigator.camera.getPicture()` will return the file uri that you can pass 1:1 to the plugin:

```js
navigator.camera.getPicture(function(uri) {
    cordova.plugins.notification.local.schedule({
        title: 'Notification with external icon',
        text: uri,
        attachments: [uri]
    });
}, null, options);
```

`icon:uri` works as well. Only `smallIcon` has to point to a resource.
