### ISSUE TITLE
Remove Notification on app removed

### ISSUE THREAD

**Issue by shrijan** [katzer/cordova-plugin-local-notifications#1539]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:0.9.3 beta
* Platform:ios
* OS version:11.2.1
* Device manufacturer / model:iphone 6
* Cordova version (```cordova -v```):8.0.0
* Cordova platform version (```cordova platform ls```):ios 4.5.4
* Plugin config
* Ionic Version (if using Ionic)ionic v1

## Expected Behavior

_Tell us what should happen_
when uninstalling notification schedule should be removed.

## Actual Behavior
when uninstalling app and again installing back it just remembers the previous setting for local notification. I have to manual go to setting page of the app and disable notification
_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment]
I'm unclear what the problem is here, is is that a scheduled notification is not removed when the app is removed OR that the previous setting of the notifications in the control panel are not put back?

**Comment by katzer** [comment]
@shrijan If you dont like Android then switch to something else, haha. But what you're describing is how Android works. It has nothing to do with the app or any plugin.
