### ISSUE TITLE
Question: Not endlessly repeating Notification in iOS

### ISSUE THREAD

**Issue by GitToTheHub** [katzer/cordova-plugin-local-notifications#1542]
Hi, I only wanted to ask, if i can make a notification, which should be triggered once in a week and only for 3 weeks long. In Android, i have the count-Property, but not under iOS. Is it possible, to create a repeating notification under iOS, which will stop after 3 weeks?

**Comment by Tawpie** [comment]
For that I’d schedule three individual notifications (non repeating) with each one’s “at” trigger set appropriately. Be sure to schedule by putting the three notification objects in an array.

**Comment by GitToTheHub** [comment]
Ok sorry, i should had explain, what i wanted to do.
My app should schedule notifications for waste appointments for one year.
If i schedule all notifications for one year, there will be about 110 notifications, but that will exceed the ios notification limit of 64 notifications. So my idea is, to combine 3 individual notifications (e.g. first notification is on monday 1.1.18, second on monday 8.1.18, third on monday 15.1.18) to one notification. The notifiction should repeat 3 times, every week on monday. But after that, it should stop, because the next pickup day for the waste is tuesday (23.1.18). On Android i would do that, with the count-property, but what can i do on iOS?
Thanks anyway for your last answer on my question :)

**Comment by rwillett** [comment]
A simple solution is to use a simple and free remote push service. OneSignal is free, takes about an hour of coding on your app and a day of coding to get a server API setup.

**Comment by GitToTheHub** [comment]
@rwillett 
Thanks for your reply. I thought about push notifications, but thought also, that i maybe can do it with local notifications. But big thanks for the tip with OneSignal. Maybe i will use it, if we want use push notifications.
Ok big thanks guys. My question is answered :)
