### ISSUE TITLE
Issue with notifications in iOS in foreground mode

### ISSUE THREAD

**Issue by mrvipinkashyap** [katzer/cordova-plugin-local-notifications#1543]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment
Ionic info output:
```
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v6.11.1
    npm               : 3.10.10
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b
```

## Expected Behavior
Notification should show up in foreground mode. Even though I can hear notification sound but don't see actual notification in notfication tray.

## Actual Behavior
I don't see notification in case of foreground mode in iOS

## Steps to Reproduce
I thought it better to simply create a new sample project to shocase this issue, so please see this repo:
https://github.com/mrvipinkashyap/Local-notifications-demo
Code to schedule notification:
https://github.com/mrvipinkashyap/Local-notifications-demo/blob/master/src/pages/home/home.ts#L29-L37
Code for event listener
https://github.com/mrvipinkashyap/Local-notifications-demo/blob/master/src/app/app.component.ts#L20-L40

**Comment by mrvipinkashyap** [comment]
@katzer I realise my mistake as not setting `foreground:true` and that was indeed the issue in this case. My apologies for not adding links to relevant code section. I have updated my query with links to relevant code section for future reference. 
Also updated repo with a working example.

**Comment by mrvipinkashyap** [comment]
Just to follow up on this for future reference, setting foreground:true fixed the issue on demo app but not on original app. In that case I realised this same issue of notification not showing on iOS in foreground was related to OneSignal plugin and removing that plugin fixed the issue.

**Comment by rwillett** [comment]
OneSignal has loads of options about how to display and not to display notifications. We've used it in the past and its worked well. You may have misconfigured something.
