### ISSUE TITLE
Confusion around cordova-plugin-local-notifications and cordova-plugin-local-notification

### ISSUE THREAD

**Issue by HugoHeneault** [katzer/cordova-plugin-local-notifications#1544]
There is a confusion between de.applant.cordova-plugin-local-notification*s* and cordova-plugin-local-notification

## Your Environment

* Plugin version: 1.0.0 or 0.9-beta2
* Platform: ios
* OS version: 11
* Device manufacturer / model: iPhone SE
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): ios 4.5.4
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

There should be ne confusion between cordova-plugin-local-notification*s* and cordova-plugin-local-notification...

## Actual Behavior

I wanted to install your plugin, so I ran `cordova plugin add cordova-plugin-local-notifications`, but it installing a version 1.0.0 of https://www.npmjs.com/package/de.appplant.cordova.plugin.local-notification instead of the 0.9 beta of this repo... Weird?

**Comment by rwillett** [comment]
That is weird. 


Run 
```
cordova plugins 
cordova plugin rm cordova-plugin-local-notifications
cordova plugins 
cordova plugin add cordova-plugin-local-notifications
cordova plugins 
```
and provide the output.

**Comment by katzer** [comment]
@HugoHeneault 

Plugin-ID __before__ v0.9.x
```
de.applant.cordova-plugin-local-notifications
```

Plugin-ID __since__ v0.9.x
```
cordova-plugin-local-notification
```

Any other ID refers to a fork. The one you are installing is [this](https://www.npmjs.com/package/cordova-plugin-local-notifications) one.

**Comment by HugoHeneault** [comment]
Ok thanks for making it clear. 
It might be worth renaming the repo or adding an warning about the possible confusion as I'm probably not the only one having this kind of issues. 🤔
