### ISSUE TITLE
Trigger "at" not working on iOS 11

### ISSUE THREAD

**Issue by Paddy78de** [katzer/cordova-plugin-local-notifications#1547]
* Plugin version: 0.9.0-beta.3
* Platform: iOS
* OS version: 11.2
* Device manufacturer / model:  Apple iPhone 6s Plus and iOS Simulator
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): ios 4.5.4
* Plugin config  cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-globalization 1.0.8 "Globalization"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-ext 0.10.6 "Cordova sqlite storage plugin with extra features"
* Ionic Version (if using Ionic) -

## Expected Behavior

Notification should appear ath the given date, when using the "at" trigger

## Actual Behavior

Notifcation doesn't appear, it works with the "in" trigger though.

The plugin worked in version 0.8 in the same app (Not with trigger: { at: .....} but with at: ....

## Steps to Reproduce

Sample code in my test app:

cordova.plugins.notification.local.schedule({
    title: 'Test',
    text: 'Test notification',
    trigger: { at: new Date(2018, 1, 26, 12,26) }
});
	
	cordova.plugins.notification.local.schedule({
  title: 'Test with in',
    text: 'Test notification with in',
       trigger: { in: 1, unit: 'minute' }
});

The first notification should have been displayed at 12:26 on Feb 26th 2018 but it did not. Localization settings on the device and the simulator are correct (Tested with new Date() )
The second notification showed up after a minute.

## Context

Trying to show a notification at a specific date.

## Debug logs

-

**Comment by katzer** [comment]
@Paddy78de Cannot reproduce. The notification comes up at the specified date. You can also see the calculated trigger date in the logs.

**Comment by Paddy78de** [comment]
Okay, thank you. Strange.. it worked with iOS up to 11.1
How can I access this log or debug? I haven't seen any information in my XCode-logs.

**Comment by rwillett** [comment]
We don't use ```in:``` at all, but we do use ```at:```. 

Just tested on IOS11.1.1, we have a simple test builtin to test local notifications, and its working fine for us. 

It's important to schedule the at: in the future, even if it's only a few seconds.  See thread #1524 for one of my comments with full production working code.

**Comment by Paddy78de** [comment]
Thank you rwillett, it worked on 11.1, since 11.2 only "in" works, not "at".
I think I will make an clean app with this plugin only for more testing.

**Comment by rwillett** [comment]
Ok, let me see if we have anything with 11.2.

**Comment by Paddy78de** [comment]
Hello,

The problem is solved and it's not a bug.
I stumbled over the iOS notification limit. Only 64 notifications can be stored.
Thanks for the support and the plugin, keep up the good work :)
