### ISSUE TITLE
FirstAt and every parameter not working in IOS & Android

### ISSUE THREAD

**Issue by sudattadesai72** [katzer/cordova-plugin-local-notifications#1548]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:0.9.0-beta.3
* Platform:iOS & Android
* OS version: IOS: 10^  Android : 4.4^
* Device manufacturer / model:Apple iPhone 6s Plus and iOS Simulator
* Cordova version (```cordova -v```):7.1.0
* Cordova platform version (```cordova platform ls```):ios 4.5.4
* Plugin config:  cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-globalization 1.0.8 "Globalization"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-ext 0.10.6 "Cordova sqlite"
* Ionic Version (if using Ionic): 3.19.0

## Expected Behavior
Notification should appear every day at specific time.

## Actual Behavior

Ios: every parameter not working and notification are not getting triggered.
Android : Notification get triggered but not at specific time. 

## Steps to Reproduce

 let momentOfFirstAt = moment(currentDateTime);
 let firstAt = new Date(momentOfFirstAt.toString());
      cordova.plugins.notification.local.schedule({
        title: "Daily Reminder",
        trigger:{ 
          at: firstAt,
          every: "day"
         },
        foreground:true
    });

## Context
Trying to show a notification everyday at a specific date.

## Debug logs
-

**Comment by MZanggl** [comment]
```
let momentOfFirstAt = moment(currentDateTime);
let firstAt = new Date(momentOfFirstAt.toString());
```
Aren't you just getting the current date like that, therefore triggering it immediately? Maybe you should add one day to it. That's what I am doing, but it is still not working for me.

I am using the same version. For me, the notification just never triggers. (just tested on Android).

```
    let d = new Date() 
    d.setDate(d.getDate()+1)
    d.setHours(9)
    d.setMinutes(0)
    d.setSeconds(0)

    cordova.plugins.notification.local.schedule({
      id: 1,
      text: "Time for your daily dose!",
      trigger: {
        firstAt: d,
        every: "day"
      }
    })

```

This should create a notification every day at 9AM starting the next day, but I do not receive it. If I leave out ` every: "day"` it works fine btw.

**Comment by gecsbernat** [comment]
same problem. By the way 'trigger' does not exist in type 'ILocalNotification
![screen shot 2018-03-14 at 11 06 01 2](https://user-images.githubusercontent.com/9141914/37396048-15505318-2778-11e8-8e17-ed4ec1bf77f6.png)

**Comment by gecsbernat** [comment]
![screen shot 2018-03-14 at 11 20 29](https://user-images.githubusercontent.com/9141914/37396716-f724b26a-2779-11e8-8d52-fd889e4c4e61.png)
![screen shot 2018-03-14 at 11 20 43](https://user-images.githubusercontent.com/9141914/37396717-f73d0d1a-2779-11e8-8cef-77ec382f7b12.png)

**Comment by mabuonomo** [comment]
same problem

firstAt (or at:) and every not work togheter

I need create a notification every day at same time

**Comment by mabuonomo** [comment]
this examples works

`var now = new Date().getTime(),
                _5_sec_from_now = new Date(now + 5 * 1000);

            cordova.plugins.notification.local.schedule({
                text: "Delayed Notification",
                at: _5_sec_from_now,
                every: "minute",
                led: "FF0000",
                sound: null
            });`

With every "minute", the first notification start not at 5 seconds from now but at 1' and 5'', without "minute" start after 5 seconds

**Comment by gecsbernat** [comment]
I solved it.
First create a notification object, then pass that object to the schedule method.

```
let notification = {
 id: 1,
 title: 'TITLE',
 text: 'TEXT',
 trigger: { every: { hour: 10, minute: 0 } }
};

this.localNotifications.schedule(notification);
```

This will trigger notification every day at 10:00.
Tested on IONIC3 IOS 11+
:)

**Comment by katche70** [comment]
@mabuonomo  your syntax is for version under 0.9 und should not be valid. 
@gecsbernat code is not working on android :(

**Comment by mabuonomo** [comment]
@katche70 in my case the @gecsbernat's code work fine on android (7/8)

**Comment by sudattadesai72** [comment]
@gecsbernat code is working fine on android with Plugin version: 0.9.0-beta.3 👍 Thank you so much!!!
Can we customize notification on days and off days for same ??

Thanks in advance.

**Comment by chakri3130** [comment]
I am scheduling a notification on particular dates on month. But it is repeating everyday with same title.
Same code is working on android. But it is not working on iOS version 11.4.Is it possible to trigger a notification without "every" keyword. Please help me.
Thanks in adavnce.

**Comment by this-is-saudkhan** [comment]
> The notification keeps coming until after the time the time has expired.

Yeah it keeps beeping until the time has expired
