### ISSUE TITLE
Notifications appear to late

### ISSUE THREAD

**Issue by cbonnemayer** [katzer/cordova-plugin-local-notifications#1551]
We try to schedule 10 notifications in a row, every 10 seconds. Some notifications appear to late and on the same moment other notifications appear. This happens on Android device and emulator, not on iOS11+ device.

## Your Environment

* Plugin version: 0.8.5
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Samsung Galaxy Tab 2 SM-&813
* Cordova version (```cordova -v```): 8.0.0.
* Cordova platform version (```cordova platform ls```): android 7.0.0
* Plugin config

cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-splashscreen 5.0.1 "Splashscreen"
cordova-plugin-vibration 3.0.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"

* Ionic Version (if using Ionic) none

## Expected Behavior

Notifications should appear at t=10, 20, 30, 40, 50, 60, 70, 80, 90, 100.

## Actual Behavior

Notification 1 appears at t=10
Notification 2 and 3 appear at t = 30
Notification 4, 5 and 6 appear at t = 60
Notification 7, 8, 9 and 10 appear at t = 100

This is reproducible. It happens every time in the same fashion

## Steps to Reproduce

        var now = new Date().getTime(); 
	var immediate = new Date(now+10000);
	var interval1 = immediate.getTime();
	var interval2 = interval1 + 10000;
	var interval3 = interval2 + 10000;
	var interval4 = interval3 + 10000;
	var interval5 = interval4 + 10000;
	var interval6 = interval5 + 10000;
	var interval7 = interval6 + 10000;
	var interval8 = interval7 + 10000;
	var interval9 = interval8 + 10000;
	var interval10 = interval9 + 10000;

        var date1 = new Date(interval1);
	var date2 = new Date(interval2);
	var date3 = new Date(interval3);
	var date4 = new Date(interval4);
	var date5 = new Date(interval5);
	var date6 = new Date(interval6);
	var date7 = new Date(interval7);
	var date8 = new Date(interval8);
	var date9 = new Date(interval9);
	var date10 = new Date(interval10);

       cordova.plugins.notification.local.schedule([
	       {id: 1, at: date1, text: 'Notification 1', title: 'Notification'}, 
	       {id: 2, at: date2, text: 'Notification 2', title: 'Notification'}, 
	        {id: 3, at: date3, text: 'Notification 3', title: 'Notification'}, 
        	{id: 4, at: date4, text: 'Notification 4', title: 'Notification'}, 
		{id: 5, at: date5, text: 'Notification 5', title: 'Notification'}, 
		{id: 6, at: date6, text: 'Notification 6', title: 'Notification'}, 
		{id: 7, at: date7, text: 'Notification 7', title: 'Notification'}, 
		{id: 8, at: date8, text: 'Notification 8', title: 'Notification'}, 
		{id: 9, at: date9, text: 'Notification 9', title: 'Notification'}, 
		{id: 10, at: date10, text: 'Notification 10', title: 'Notification'}]);

## Context

We would like to schedule notifications on random intervals, twice a day, 5 days in a row. This 10 secs schedule is for testing purposes.

**Comment by i-mediasolutions** [comment]
Same problem here on Huawei P8 Lite running Android 6; even some notifications come earlier (couple of minutes) then scheduled. It looks like they are collected or batched at given intervals, could it be some background app/process/task is responsible for this (like some doze mode)?

**Comment by onelifemedia** [comment]
It looks like I'm having a similar issue. Seems as though the trigger always happens on the hour. If you trigger at 8 minutes, the notification will trigger immediately. If you trigger at 55 minutes, the notification will trigger on the hour.

Are you experiencing similar behavior?

**Comment by guyromb** [comment]
Same here, notifications arrive in delay one 0.9.beta3
