### ISSUE TITLE
Default notification sound plays on Android no matter what

### ISSUE THREAD

**Issue by wodim** [katzer/cordova-plugin-local-notifications#1553]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: git
* Platform: Android
* OS version: 8 (but my app targets Nougat)
* Device manufacturer / model: emulator
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): 6.3.0

## Expected Behavior

Whatever sound I choose to play should play, or none at all if I choose `sound: null` or something like that

## Actual Behavior

I always get the default notification sound from Android

## Steps to Reproduce

            cordova.plugins.notification.local.schedule({
                id:         1337,
                title:      "xxx",
                text:       "xxx",
                sticky:     true,
                autoClear:  false,
                sound:      "file://empty.mp3",
                vibrate:    false,
            });

Or...

            cordova.plugins.notification.local.schedule({
                id:         1337,
                title:      "xxx",
                text:       "xxx",
                sticky:     true,
                autoClear:  false,
                sound:      null,
                vibrate:    false,
            });

**Comment by wodim** [comment]
This only seems to happen when you run the app on Oreo. I just tested it on Nougat and no sound plays, as expected. Didn't try a custom sound, though.

**Comment by MInesGomes** [comment]
I have the same problem.
[https://github.com/ionic-team/ionic/issues/19696](url)

and it seems missing the "channel" as described here
https://distriqt.github.io/ANE-PushNotifications/m.FCM-GCM%20Payload

> Sounds on individual notifications were deprecated in Android O (API 26). You now have to set them on a channel.

@wodim  did you found a solution?

**Comment by wodim** [comment]
I don't remember what I did about this but if you know what the problem is that the "channel" is missing then you could edit the Java code of the plugin.

**Comment by MInesGomes** [comment]
@wodim Thanks for the reply ... I don't know the java code to implement the channel ...
I just now is necessary a different channel every time I launch a localNotification with a different sound ....  If you find a solution I would be 😃
