### ISSUE TITLE
Ionic: Permanent sticky local notification

### ISSUE THREAD

**Issue by admirableghost** [katzer/cordova-plugin-local-notifications#1555]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
I am trying to create a local notification that tells the user when his location is being tracked in my ionic app. For the entire duration, I want the user to always know when I track his location. I was able to create a simple sticky notification that can't be swiped out. But when the user clicks on the notification, the app opens and notification goes away. I want the notification to stay until the user turns off location tracking in the app. Any existing solutions or workarounds for this? Is there a permanent sticky local notification?

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version: Android N
* Device manufacturer / model: Moto G5 S Plus
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): 6.3.0
* Plugin config: N/A
* Ionic Version (if using Ionic): 4.4.0

## Expected Behavior

Sticky notification that doesn't go from the notification tray on  click

## Actual Behavior

Sticky notification that goes from the notification tray on click

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1.    
```
import { LocalNotifications } from '@ionic-native/local-notifications';
constructor(public http: HttpClient, public localNotifications: LocalNotifications, public kipenziUtilsProvider: KipenziUtilsProvider) {}
 let notification:any = {
      id: 1,
      title: "Tracking is on.",
      text: "Location tracking in progress...",
      ongoing: true
    };
    if (notification && notification.id) {
      notification.id = this.generateId(notification.id);
      this.localNotifications.schedule(notification);
      alert("Notification added.");
    }
```
  2. ...
  3. ...
  4. ....

## Context

Explained in the summary.

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by thatsmekaustubh** [comment]
Nice use case, will really like to know the solution.

**Comment by rwillett** [comment]
We track the notification using the notification unique ID, whenever the user opens the app, we always cancel all the notifications and then recreate them. This means they aren't permanently sticky, but they keep appearing as needed. So the user can delete them, but we can keep redisplaying them (depending on the business logic).

**Comment by rwillett** [comment]
Closed as no update
