### ISSUE TITLE
Problem on add pluggin for android plataform

### ISSUE THREAD

**Issue by mariomarquesinf** [katzer/cordova-plugin-local-notifications#1561]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: latest
* Platform: ionic
* OS version: Windows 10 Home 64bits
* Device manufacturer / model:
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):6.2.3
* Plugin config
* Ionic Version (if using Ionic): 3.20.0

## Actual Behavior

Installing "cordova-plugin-local-notification" for android

Plugin doesn't support this project's android-sdk version. android-sdk: 23.0.0, failed version requirement: >=26

Skipping 'cordova-plugin-local-notification' for android

**Comment by rwillett** [comment]
So what's the problem?  What are you expecting to see?

**Comment by mariomarquesinf** [comment]
I don't know why this particular pluggin fails to install on android. That's my problem.

**Comment by AhmedHamedTN** [comment]
Any updates on this ? Same issue here

**Comment by SaiVikas0801** [comment]
Getting the error "Plugin doesn't support this project's apple-ios version. apple-ios: 9.2.0, failed version requirement: >=10.0.0" when I try to create a new cordova project and add the plugin.

Cordova version used(cordova -v):- 8.0.0

Please help on how to resolve this.

**Comment by rwillett** [comment]
@mariomarquesinf Android SDK level is wrong, install the right version

@SaiVikas0801 Don't pollute other threads. Your issue is nothing to do with this thread. Your issue is that the plugin only works on IOS 10. As the error message says IOS version requirement >= 10.0.0. Use the older plugin or upgrade IOS to 10.

**Comment by xudongcamsys** [comment]
@mariomarquesinf any luck?
I have installed all sdk versions in Android Studio.

**Comment by rwillett** [comment]
We have the same versions and it all works. 

I'd post a picture of your android studio and show whats installed.

**Comment by xudongcamsys** [comment]
Not sure if this is exactly related. but I updated Cordova Android to 7.1.0. and re-installed the plugin via Ionic. At least for now, it does schedule the notification on my testing Nexus 5 phone.

**Comment by Tawpie** [comment]
Thx... I'm not able to get the build to happen (still, the error messages imply that I'm not building with the correct android sdk, and the correct sdk is installed), but that's really being covered in another issue so I won't hijack this.

**Comment by madhavansu** [comment]
Same issue here, any solution to fix this.

**Comment by nagthgr8** [comment]
Its been six months since this thread is open & not fixed yet ?

**Comment by nagthgr8** [comment]
> I have no idea if it matters, but what versions of node and npm are you using?
> 
> `node --version`
> `npm --version`
> 
> Nevermind. I have another system that will install the plugin and it's on the same node and npm versions (8.11.1 and 6.0.0) so this isn't it.
> 
> Trying to track this down as well, my android sdk is 27 according to android studio. The plugin wants android-sdk >= 26 so in theory the dependency is met. But in practice...

I guess its not the same sdk versions both are using what happens if you build apk from the studio instead?

**Comment by nagthgr8** [comment]
I kept this thread open in my shell that I come back & answer to this post pending since 6 months. This is what I did to fix the issue. In my case some how there are 2 versions of android sdk folders and the ANDROID_HOME is pointing to old version. First I uninstalled from Android Studio all the SDK which was installed, then  I deleted these 2 sdk folders from C:\Users\<UserName>\Local\AppData\Android 
Then from Android Studio -> Tools -> SDK Manager I installed Android 8.1.1 which is having API 27
Then executed below 
> cordova platform rm android
> cordova platform add android
that s it, it did gave some warnings but this time able to install local notification without any issue.
please also install Android Build Tools

**Comment by IgorBrussolo** [comment]
I get this error today,
I'm not sure if this helps but I removed the Android Q Preview and it worked for me.

**Comment by dpa99c** [comment]
I hit this error today - seems to be caused the [this line](https://github.com/katzer/cordova-plugin-local-notifications/blob/master/plugin.xml#L47) in the `plugin.xml`:

    <engine name="android-sdk"     version=">=26" />

Quick and dirty workaround:  edit `plugins/cordova-plugin-local-notifications/plugin.xml` and comment out that line:

    

Then force install the plugin again:

    cordova plugin add cordova-plugin-local-notifications --force

**Comment by Entrecampos** [comment]
Thanks @dpa99c !
I was having
> Failed to install 'cordova-plugin-local-notification': TypeError: Invalid Version: android-Q

I removed the Android Q Preview and it worked for me too :-)
