### ISSUE TITLE
plugin crashes on iOS 11.2.6

### ISSUE THREAD

**Issue by mardugas** [katzer/cordova-plugin-local-notifications#1562]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:0.9.0-beta.3
* Platform: iOS
* OS version: 11.2.6
* Device manufacturer / model: iPad Air
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): iOS 4.5.4
* Plugin config
* Ionic Version (if using Ionic)

## Expected behavior
app should not crash when plugin notification is applied

## Actual Behavior
app crashes as soon as functions from plugin notification are called

## Steps to Reproduce

install plugin on iOS

code example:
cordova.plugins.notification.local.registerPermission();

cordova run ios

app crashes when above code is executed

## Debug logs

no error message in the console log, the app freezes

**Comment by gurix** [comment]
I had also issues using the plugin on ios 11.3. In my case it turned out, that `window.cordova` is no longer accessible on iOS. I had to use `cordova` alone.
