### ISSUE TITLE
Trigger Callback

### ISSUE THREAD

**Issue by shivang-cnc** [katzer/cordova-plugin-local-notifications#1563]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:0.9.0-beta.3
* Platform: iOS
* OS version:11.2.6
* Device manufacturer / model:iPhone6
* Cordova version (```cordova -v```):8.0.0
* Cordova platform version (```cordova platform ls```):IOS 4.4.0
* Plugin config
* Ionic Version (if using Ionic):3.19.1

## Expected Behavior

If app in foreground need to response callback of trigger in ios

## Actual Behavior

It's happening nothing  
Need to show an alert if app in foreground 

## Steps to Reproduce

1.. schedule notification  
2.. Don't put device on sleep/Background
3.. Notification Trigger but not responding callback of trigger

**Comment by pandeeswaran** [comment]
I face same issue. Need to show an alert if app in forground
