### ISSUE TITLE
Repeating Triggers

### ISSUE THREAD

**Issue by cconnell12345** [katzer/cordova-plugin-local-notifications#1564]
I need the following triggers to work on Android and IOS.  After reading the issues and the documentation I am not sure that I have the correct/working syntax.  In particular does firstAt work?  If no what is the work around?

1) I want the notification triggered every day for 5 days at 10:30AM.  Here is what I have:
trigger: { every: {hour: 10, minute: 30}, count: 5 }
2) I want the notification every Friday at 10:30AM for the next 2 Fridays.  Here is what I have:
trigger: {every: 'week', firstAt: {month:3, day:30, hour:10, minute:30}, count: 2}
3) I want the notification every other day at 10:30AM for the next 14 days.  I am not sure this is possible, if not I am assuming I have to add each one manually.  What is the limit on the number of notifications that can be added?

Thanks in advance for your help.

* Plugin version: latest
* Platform: Cordova
* Cordova version (```cordova -v```): 8.0.0

**Comment by JiiB** [comment]
I downgraded cordova to version `7.1.0` (from 8.0.0) now my code works on iOS and Android

**Comment by lfwells** [comment]
I am also having this "infinite loop" problem on a device. I constantly get notifications for the whole minute (constantly vibrating)

**Comment by Simpler1** [comment]
To avoid the repeating notifications every second:
https://github.com/katzer/cordova-plugin-local-notifications/issues/1533#issuecomment-419107565
