### ISSUE TITLE
Trigger by location / date on Android

### ISSUE THREAD

**Issue by scrakcho** [katzer/cordova-plugin-local-notifications#1566]
* Plugin version: 0.9.0-beta.3
* Platform: Android
* OS version: 6.3.0
* Device manufacturer / model: Xiaomi - Galaxy Tab 4 - Samsung S8
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): 6.3.0

## Expected Behavior

Notifications are managed by location, date or both

## Actual Behavior

Only work setting by date... location seems not work. Futhermore, there arent any example about set a notification that must be launched between two dates and if you are inside an area

## Context

`trigger = {type: 'location', center: [notificacion.lat, notificacion.lng], radius: 10, notifyOnEntry: false};`

`cordova.plugins.notification.local.schedule({`
`                            id: notificacion.id,`
`                            title: notificacion.title,`
`                            text: notificacion.message,`
`                            foreground: true,`
`                            led: { color: '#ccff00', on: 500, off: 500 },`
`                            vibrate: false,`
`                            data: { item_id: notificacion.item_id },`
`                            trigger: trigger`
`});`

**Comment by Fever905** [comment]
Location trigger is not supported on Android.
