### ISSUE TITLE
Actually am going to schedule the three daily notifications at three diffrent time but notification fire only once in a day. all of them are fired at a time.

### ISSUE THREAD

**Issue by akshay19710** [katzer/cordova-plugin-local-notifications#1570]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform:Android
* OS version: linux
* Device manufacturer / model:
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): 8.0.0
* Plugin config
* Ionic Version (if using Ionic) 3.19

## Expected Behavior

_Tell us what should happen_

Actually am going to schedule the three daily notifications at three diffrent time but notification fire only once in a day. all of them are fired at a time. 

cordova.plugins.notification.local.schedule([
      {
        id: 1,
        title: 'Reminder',
        foreground: true,
        text: 'First',
        data: { mydata: 'Upload food images' },
        trigger: { every: 'day', hour: 10 },
      },
      {
        id: 2,
        title: 'Reminder',
        foreground: true,
        text: 'Second',
        data: { mydata: 'Upload food images' },
        trigger: { every: 'day', hour: 12 },

      },
      {
        id: 3,
        title: 'Reminder',
        foreground: true,
        text: 'Third',
        data: { mydata: 'Upload food images' },
        trigger: { every: 'day', hour: 16 },

      }
    ]);

**Comment by Tawpie** [comment]
I would try removing the 'day' and doing the trigger as trigger: `{ every: 'hour': 16 },` because that'll do the same thing as including the day since there's only one sixteenth hour each day.

Also, not having 'hour' as a string in your current code might be something to look at since the property definition is looking for a string. But it might not care either!

**Comment by akshay19710** [comment]
If I remove the day and put the hour the it will work ? Because i need to a 3 local notifications daily with three different time.

**Comment by rwillett** [comment]
Why not try it and see?

**Comment by akshay19710** [comment]
trigger: { every: 'hour': 16 } 


it gives me compile time error ' , ' expcepted.

**Comment by akshay19710** [comment]
trigger: { every: 'hour', hour: 16 }  it works but all three notifications fired all three time in a day
