### ISSUE TITLE
Customize layout for notification

### ISSUE THREAD

**Issue by hoabuiduy** [katzer/cordova-plugin-local-notifications#1571]
Hi guys,
I would like to make custom layout on Notifications. How can i do it on the plugin.

Example: i would like to make same with below photo

![chartpricenotification 1](https://user-images.githubusercontent.com/5258180/38453338-60efeb58-3a7e-11e8-9739-fa85293633ae.jpg)

Charts is images

Thanks

**Comment by rwillett** [comment]
Suggest you add more information.
