### ISSUE TITLE
v0.9.b-2 blocks fechanique/cordova-plugin-fcm work on iOS11

### ISSUE THREAD

**Issue by Reactor13** [katzer/cordova-plugin-local-notifications#1572]
Provide a general summary of the issue.
On iOS when installed fechanique/cordova-plugin-fcm (latest) plugin and katzer/cordova-plugin-local-notifications@0.9.0-beta.2 FCM plugin can't receive any notifications event, onNotification event not fired ever.

Maybe problem with FCM plugin, but:
- on Android the same plugins forks fine
- on iOS cordova-plugin-local-notifications@0.8.5 with FCM plugin also works fine.
- without cordova-plugin-local-notifications FCMplugin also works fine.

## Your Environment

* Plugin version:
cordova-plugin-fcm ^2.1.2
git+https://github.com/katzer/cordova-plugin-local-notifications.git#0.9.0-beta.2

* Platform:
iOS
* OS version:
11.3
* Device manufacturer / model:
any
* Cordova version (```cordova -v```):
7.1.0
* Cordova platform version (```cordova platform ls```):
android 6.3.0
ios 4.5.2
* Plugin config
default
* Ionic Version (if using Ionic)
3.9.2

## Expected Behavior

cordova-plugin-local-notifications don't block fcm plugin events

## Actual Behavior

cordova-plugin-local-notifications block fcm plugin events

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_
1. Create simple ios project
2. Install cordova-plugin-local-notifications. Just install - no code needed.
3. Install https://github.com/fechanique/cordova-plugin-fcm and configure (of course)

// This event will fire
FCMPlugin.getToken(function(token){
    alert(token);
})

// This event will not fire ever even by tap on received notification (push). FCM messages will receiving by devices, bot not fired by FCMPlugin
FCMPlugin.onNotification(function(data){
    if(data.wasTapped){
      //Notification was received on device tray and tapped by the user.
      alert( JSON.stringify(data) );
    }else{
      //Notification was received in foreground. Maybe the user needs to be notified.
      alert( JSON.stringify(data) );
    }
});

**Comment by Reactor13** [comment]
I hope that i have found solution to solve this issue.
I hope, that it can be helpful for other cordova users.

I have install plugin from "https://github.com/katzer/cordova-plugin-local-notifications.git#0.9.0-beta.3"

Now local notifications and fcm works fine on iOS and Android

**Comment by ddralves** [comment]
Please see: https://github.com/katzer/cordova-plugin-local-notifications/issues/1626

**Comment by joesleiman** [comment]
"cordova-plugin-local-notification": "^0.9.0-beta.3",
    "@ionic-native/local-notifications": "^4.18.0",
local notification not working on ios ?
any idea?

**Comment by ddralves** [comment]
@joesleiman see #1626

**Comment by JuanCarlosSC** [comment]
> "cordova-plugin-local-notification": "^0.9.0-beta.2", "@ionic-native/local-notifications": "^4.18.0",

"cordova-plugin-local-notification": "0.8.5",
"@ionic-native/local-notifications": "4.20.0",

works
