### ISSUE TITLE
registerPermission not working on iOS 11.3

### ISSUE THREAD

**Issue by mardugas** [katzer/cordova-plugin-local-notifications#1575]
Provide a general summary of the issue.
registerPermission not working on iOS 11.3 @katzer 

* Plugin version: 0.9.0-beta.3
* Platform: iOS
* OS version: 11.3
* Device manufacturer / model: iPad Air 2
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): ios 4.5.4
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior
cordova.plugins.notification.local.registerPermission
should produce a permission dialog;
app should be listed under settings/notifications of iPad

## Actual Behavior
app stops after calling cordova.plugins.notification.local.registerPermission
no error message on XCode console
app is not listed under settings/notifications of iPad

## Steps to Reproduce
demo code:

      cordova.plugins.notification.local.registerPermission(function (gr) { 
         if (!gr){ alert('No permission'); }
         else { 
            console.log('Permission granted');

            cordova.plugins.notification.local.hasPermission(function (granted) {
               if (granted == true) {
                  cordova.plugins.notification.local.getIds(function (ids) {
                     console.log("ids="+ids);
                     if (ids.length > 0) {
                        for (i = 0; i < ids.length; i++) { 
                           get_not_info(ids[i], i == ids.length-1);
                        }
                     }
                     else {
                        cordova.plugins.notification.local.schedule({
                           id: 8, 
                           title: 'Test notification',
                           text: 'It works!',
                           foreground: true
                        });
                        alert("notification scheduled");
                     }
                  });
               }
               else {
                  alert ("permission granted:"+granted);
               }
            });

         }
     });

## Context
generate a local notification on an iPad

## Debug logs
no error message on Xcode logs

related to #1562

**Comment by katzer** [comment]
@mardugas The name of the method is `requestPermission()`

**Comment by mardugas** [comment]
Thank you - it's working now
