### ISSUE TITLE
Unable to play custom sound on Android

### ISSUE THREAD

**Issue by shivalipawar** [katzer/cordova-plugin-local-notifications#1580]
Provide a general summary of the issue.

## Your Environment

* Plugin version:
* Platform: Android
* OS version: 7
* Device manufacturer / model: Samsung J7
* Cordova version (```cordova -v```):  7.0.1
* Plugin config
* Ionic Version (if using Ionic) : 3.19.1

## Expected Behavior

Android Notification should play custom sound eg: bell.mp3

## Actual Behavior

It doesn't play any sound when we try to play bell.mp3

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

      var date = new Date();
            var timestamp = toTimestamp(date);
            var localNotificationSetting = {
                id: timestamp,
                icon: "icon",
                title: 'ABC',
                text: 'hello',
                ongoing: false,
                autoClear: false,
                data: { clientToken: "sjhbsbd" }
            };
            var applicationStorageDirectory = cordova.file.applicationDirectory;
            var soundFilePath = applicationStorageDirectory + 'www/res/raw/Android/bell.mp3';
             var soundFilePath = 'file://www/res/raw/Android/bell.mp3';
             var soundFilePath = 'file://res/raw/' + 'bell.mp3';
             var soundFilePath = 'res://raw/' + 'bell.mp3';
            var soundFilePath = 'android.resource://com.eaton.ionSecurityConnectPanel/raw/bell';

            localNotificationSetting.sound = soundFilePath;
            cordova.plugins.notification.local.schedule(localNotificationSetting);

This is the piece of code used to play the sound files kept in platforms/android/res/raw/bell.mp3 
But it doesn't seem to play.

What should be the soundFilePath for the above code snippet i'm working on. Asi have tried all possible file paths to access sound file from various paths i.e. platforms and even from www folder.

**Comment by rhclayto** [comment]
This is what I used to get it working:

```js
sound: 'file://assets/custom/sound/file-sounds-924-long-chime-sound.mp3',
```

The ```file://``` path seems to be relative to the project root level ```www``` directory. So put the sound file somewhere inside the ```www``` directoy, & reference it from there.
