### ISSUE TITLE
'launchDetails' are undefined when tapping on notification while app is in background

### ISSUE THREAD

**Issue by GilbyJazz** [katzer/cordova-plugin-local-notifications#1581]
When i tap on a notification to open the corresponding app while the app is closed, i can retrieve _launchDetails_ to get information how the app was launched.

If i do the same while the app is open but in the background, _launchDetails_ is undefined.

## Your Environment

* Plugin version: 0.9.0.beta.3
* Platform: iOS, Android
* OS version: iOS - 10.3.3, Android - 7.0
* Device manufacturer / model: iPhone 5, Samsung Galaxy S6
* Cordova version: 8.0.0
* Cordova platform version: iOS - 4.5.4, Android - 7.0.0
* Ionic Version: 3.19.1

## Expected Behavior

I would expect that _launchDetails_ is filled with data since the app got back to foreground through a notification tap.

## Actual Behavior

_launchDetails_ is undefined and i can't react to the user action (notification tap).

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

Executing this code when the app got launched and when the app resumes back to foreground:

	cordova.plugins.notification.local.fireQueuedEvents();

	// the timeout is just to make sure the events had time to trigger
	setTimeout(() => {
		let details = cordova.plugins.notification.local.launchDetails;

		if (details && details.action == 'click') {
			// do something
		}
		else {
			// do something else
		}
	}, 200);

## Context

I try to show the user a specific screen if the app got opened/back to foreground through a notification tap.

## Debug logs

I am not sure if this is a bug or just a missing feature/feature request, so there are no logs.

**Comment by GilbyJazz** [comment]
I found a solution for my specific requirement. It is by no means a perfect solution, but in case someone else is looking for the same functionality - here are two screenshots that display the changes i made to get the functionality described in the first post to work on Droid and iOS.


For copy-paste _(keep the plugin version in mind when looking for the lines)_:

**iOS**
Class: _APPLocalNotification.m_
Line: 570
Code:

```
else if ([event isEqualToString:@"click"]) {
    _launchDetails = @[toast.options.id, event];
    NSString* launchJs = @"cordova.plugins.notification.local._setLaunchDetails()";
    [self.commandDelegate evalJs:launchJs];
}
```

**Droid**
Class: _LocalNotification.java_
Line: 545
Code:

```
else if (launchDetails == null && toast != null && event.equals("click")) {
    launchDetails = new Pair<Integer, String>(toast.getId(), event);
    String launchJs = "cordova.plugins.notification.local._setLaunchDetails()";
    sendJavascript(launchJs);
}

```
![bildschirmfoto 2018-04-27 um 09 13 57](https://user-images.githubusercontent.com/2064651/39349907-e38acb5e-49fc-11e8-95e6-9eccb68f83ef.png)
![bildschirmfoto 2018-04-27 um 09 15 04](https://user-images.githubusercontent.com/2064651/39349908-e3a5161c-49fc-11e8-8a94-5e8fba42904d.png)

**Comment by Limoli** [comment]
Same problem, is it possible that this is an official library of Ionic?
Creation of push notification works, but what is the purpose of that if I can't handle an event?

**Comment by yeahlo** [comment]
roller coaster coding, "it fits my needs!" click "oh no"
any update ?
