### ISSUE TITLE
Failed to install local notification : TYPESCRIPT ERROR :In ambient enum declarations member initializer must be constant expression:

### ISSUE THREAD

**Issue by ashavyshakh** [katzer/cordova-plugin-local-notifications#1583]
Getting typescript error when trying to install local notification pluggin

##  Environment

* Plugin version:0.9-beta.1
* Platform: Browser plat form
* Cordova version ):6.5.0
* Ionic Version (if using Ionic):3.20.0

## Expected Behavior

I wish to install this pluggin in my ionic v3 app

## Actual Behavior

ERROR:"In ambient enum declarations member initializer must be constant expression. In local-notifications/index.d.ts file"

## Steps to Reproduce
Just followed the package installation steps;

**Comment by Suptzs** [comment]
I had the same problem today and managed to resolve it by updating my typescript version:
$ npm install typescript@next --save

Of course this broke some generics in another stupid plugin which was then resolved with
$ npm install rxjs --save

**Comment by CliffyMk** [comment]
Refer this.
https://github.com/katzer/cordova-plugin-local-notifications/issues/1576
