### ISSUE TITLE
Location trigger not working on android

### ISSUE THREAD

**Issue by ahnurbd65** [katzer/cordova-plugin-local-notifications#1587]
* Plugin version: 0.9.0-beta.2
* Platform: android 
* OS version: 7.1.2
* Device manufacturer / model: Xiaomi Redmi 4x
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): 7.0.0

## Expected Behavior

Set notification should trigger when the trigger conditions are met

## Actual Behavior

Location-based scheduled notification triggers as soon as they are set even when the trigger conditions are not met.

## Context

I was trying to schedule a notification to trigger on the entry in a specific area specified by center and radius.

```
$("#setnotification").click(function (){
            var x = $("#xcor").val();
            var y = $("#ycor").val();
            alert('x: '+x+' y: '+y);
            var tig = { type: 'location', center: [x , y], radius: 25, notifyOnEntry: true };            
            cordova.plugins.notification.local.schedule({
                title: 'Welcome to' + x + ' ' + y,
                trigger: { 
                    type: 'location', 
                    center: [x , y], 
                    radius: 25, 
                    notifyOnEntry: true 
                }
            });
        });
```

## Debug logs

```
sorry, learning :P
[debug.txt](https://github.com/katzer/cordova-plugin-local-notifications/files/1956004/debug.txt)

```

**Comment by matulkum** [comment]
I observed exactly the same behaviour. Any solution (or tipp where to look for fixing) this yet?

**Comment by matulkum** [comment]
Actually I just checked the feature matrix of the Readme, and realised location triggers for android are not supported by this plugin :(

**Comment by Fever905** [comment]
So close the issue?

**Comment by BerkiAttila** [comment]
Any update on this issue? Is there a plan to support it on Android?
