### ISSUE TITLE
Tip for fellow developers

### ISSUE THREAD

**Issue by MichelReij** [katzer/cordova-plugin-local-notifications#159]
Make sure that you _do_ _not_ _reuse_ notification id's, as reusing id's causes the notifications to not appear, at least not in iOS.

As you can imagine, I spent an unreasonable amount of time trying to debug my notifications not showing up :-(

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
