### ISSUE TITLE
Troubles on Oreo

### ISSUE THREAD

**Issue by agoldenberg** [katzer/cordova-plugin-local-notifications#1591]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Samsung Galaxy S9+
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): android 7.0.0
* Plugin config N/A
* Ionic Version (if using Ionic) N/A

## Expected Behavior

I should see a notification.

## Actual Behavior

Uncaught TypeError: Cannot read property 'notification' of undefined
    at deviceIsReady (index.html:19)
    at index.html:60

## Steps to Reproduce
Here's my code
in the head
<pre>
<script type="text/javascript">
        function deviceIsReady() {
            cordova.plugins.notification.local.schedule({
                title: 'My first notification',
                text: 'Thats pretty easy...',
                foreground: true
            });
        }
    </script>
</pre>

in the bottom

<pre>
<script type="text/javascript">
    $(function () {
        setTimeout(getNumber, 500);
    });
    document.addEventListener("deviceready", deviceIsReady(), true);
</script>
</pre>

## Context

I was trying to trigger a test notification.

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment]
Suspect you haven't loaded the plugin properly, this plugin works fine on Android 8.0.

**Comment by agoldenberg** [comment]
Here's what I have plugin wise

<pre>
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-whitelist 1.3.3 "Whitelist"
</pre>

**Comment by rwillett** [comment]
I have no idea, but since notifications isn't being found, I'm struggling to find a better answer. It might be that your code is wrong and that the deviceready event isn't being fired or something like that. Not enough information to go on.

I can tell you that it works on Android 8, Android 7, Android 6 using Ionic 1.

**Comment by agoldenberg** [comment]
@rwillett Well I installed it and deviceready is fired as that top function doesn't get called until deviceready is fired. So I'm not quite sure what I'm missing. Any chance you could hit me on skype? andrew at goldenberg.me

**Comment by agoldenberg** [comment]
@rwillett So it turns out I had the order of execution wrong. My fault entirely.
