### ISSUE TITLE
Question: Android 8 Supported?

### ISSUE THREAD

**Issue by GitToTheHub** [katzer/cordova-plugin-local-notifications#1594]
Hi, i only wanted to ask, if notifications works generally under Android 8.

I ask this, because i often read in the issues here, that there are often problems with notifications and Android 8.

I tested the notifications with a Samsung S8 and Android 8, and the notifications worked without errors. So there are no problems with Android 8 and the notifications, right?

**Comment by rwillett** [comment]
The plugin works under Android 8 on a Google Pixel XL phone.

Since many manufacturers seem to like to tinker with Android, some versions may not work as expected. This observation is based on older versions of android though, so could be wrong.  

All you can say is that it works on the phones and OS's you have tested. You cannot say there are no problems unless you can test on all phones. Welcome to the fragmented world of Android.

**Comment by afolarin** [comment]
Has anyone had any success testing if cordova notifications plugin works on Samsung  Galaxy S8 Android 8? We believe we have encountered some issues specific to Samsung Android.

**Comment by afolarin** [comment]
thanks @GitToTheHub that's useful to know. We are encountering a situation where notification scheduling works on MotoG5 Android 7 but not Samsung S8 Android 8.

**Comment by GitToTheHub** [comment]
Hmm i don't know, maybe its an issue which is mentioned here: #1541
You must append the plugin with a fix which is mentioned later in the discussion.

**Comment by dragonStandard123** [comment]
On vivo Y83A(Android 8.1), it doesn't work!
Any suggestion?

**Comment by velval** [comment]
For me the trigger at wasn't working on Android 8, however after long troubleshooting find out that by default the cordova android build was using android-27 api to compile. I then added a gradle.properties file with cdvCompileSdkVersion=android-28 and notifications started working. Hope it helps someone.

**Comment by Tawpie** [comment]
@velval try adding

 `   <preference name="android-targetSdkVersion" value="28" />`

to config.xml.

**Comment by velval** [comment]
Thanks @Tawpie that also seems to work fine and I guess is cleaner as it specified in the config as usually the platforms/ folder is ignored.

**Comment by GitToTheHub** [comment]
Hi, i'm wondering why this should fix problems with Android 8, because the Android API Level 27 represents Android 8.1 ([see wiki](https://en.m.wikipedia.org/wiki/Android_version_history)) and the API Level 28 is Android 9.
This shouldn't effect any Android 8 issues.
