### ISSUE TITLE
the on event is just expected 1 args in LocalNotification class. It just one args or two 2 args

### ISSUE THREAD

**Issue by alxaln** [katzer/cordova-plugin-local-notifications#1598]
## Your Environment

* Plugin version: ^0.9.0-beta.2
* Platform: Ubuntu Gnome
* OS version: 17.04 64-bit
* Device manufacturer / model: DELL
* Cordova version: 8.0.0
* Cordova platform version: android 7.0.0
* Plugin config
* Ionic Version: Ionic 3.20.0

## Expected Behavior

the on event is just expected 1 args in LocalNotification class. It just one args or two 2 args

## Actual Behavior

IMAGE [CODE:](https://imgur.com/a/zSLVYQy)

## Steps to Reproduce

``` javascript
this.localNotif.on('click'); // and now???
```

**Comment by cedrickbae** [comment]
```
this.localNotif.on('click').subscribe(
(data : any) => {
 console.log(data)
})
```

**Comment by alxaln** [comment]
Thanks!
