### ISSUE TITLE
How do I set up a notification with special date and repeat it every 2 days or 2 weeks

### ISSUE THREAD

**Issue by lytieunuong1** [katzer/cordova-plugin-local-notifications#1599]
Hi,

I'm so sorry when I ignored your template but I just want to ask how to show notification on specific time like 2018-05-09 10:00 AM  and repeat it every 2 days?

Thank you so much!

**Comment by zazics** [comment]
I would like to do the same (see my issue https://github.com/katzer/cordova-plugin-local-notifications/issues/1593). I use "every,unit,firstAt" but "firstAt" is not supported on IOS and I need Android and IOS support.
So, same question for me...

**Comment by ShaneMosley** [comment]
No answer on this in 2 years?......
