### ISSUE TITLE
Better error reporting?

### ISSUE THREAD

**Issue by atuttle** [katzer/cordova-plugin-local-notifications#160]
It would be nice if the plugin would throw some JS errors if things aren't right. For example, I was accidentally attempting to create a notification referencing an undefined variable for the notification title value, causing the notification not to display, and because no error occurred it took me almost an entire day to figure out what was wrong.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
