### ISSUE TITLE
ES5 Compliance

### ISSUE THREAD

**Issue by aleygues** [katzer/cordova-plugin-local-notifications#1601]
Hi,

Thanks for your plugin! Great job!

I'm currently using the latest beta version in my app and doing some tests on old Android webviews (Android 5.0). It seems this webview does not support ES6 features. I had some problems with your plugin in JS files because you are using `for(... of ...)` which is an ES6 feature (so, not supported). I had to switch them to `for(... in ...)`.

There are only 3 occurences (core and utils), if you can quickly fix this in the next release, could be perfect!

Aurélien.

**Comment by rwillett** [comment]
Why not generate a PR for the work?
