### ISSUE TITLE
iOS - Notification Sound Is Being Made But No Notification is Scheduled and Notification Array is Empty

### ISSUE THREAD

**Issue by mino922** [katzer/cordova-plugin-local-notifications#1603]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

I successfully schedule a notification (id 1) and it is displayed to the user. The notification array is now empty. I then go to schedule another notification using the same id and I hear the notification sound but no notification is present and the result of getIds() is []

It appears to be working fine on Android.

## Your Environment

* Plugin version: cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
* Platform: iOS
* OS version: 11.3
* Device manufacturer / model: Apple (All)
* Cordova version (```cordova -v```): 6.4.0
* Cordova platform version (```cordova platform ls```):
```
 Installed platforms:
  android 6.3.0
  ios 4.5.4
```
* Plugin config
* Ionic Version (if using Ionic)

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v8.9.4
    npm        : 5.6.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3.1 Build version 9E501

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

## Expected Behavior

I should be able to schedule a notification with the same id and it should be displayed to the user.

## Actual Behavior

The notification sound is being made but no notification is being displayed and the result of getIDs() is [].

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

            this.localNotification.getIds().then(id => {
              console.log ("All the Notification IDs " + JSON.stringify(id));
            })

            this.localNotification.isTriggered(1).then(value => {
              console.log("Notification is Present " + JSON.stringify(value));
              if (value === false) {
                console.log("Notification is not Scheduled");
                
                  this.localNotification.schedule({
                    id: 1,
                    title: 'Test!',
                    text: "Test"
                  });

              }
            }).catch(err => {
              console.log("Having trouble checking for the notification");
            })
          }
        }

## Context

The above code is inside of a loop. I only want to schedule the notification once. I am using the isPresent to detect if id 1 is present. If not, then schedule it. This works fine on Android, but not on iOS

**Comment by mvierssen** [comment]
Did you try adding `foreground: true`?

**Comment by mino922** [comment]
I'm using the Ionic wrapper with this and it doesn't recognize `foreground` as an option. I'm not sure what to do.

**Comment by lsgd** [comment]
For me it happens from time to time on iOS that I schedule a notification 3 seconds ahead and the phone vibrates after 3 seconds but there is no notification shown. But so far, I could not figure out why this happens. After a restart of the app it works fine again...

@mino992: For 0.9 beta and ionic-native there is no _foreground_, but _launch_:
`this.localNotification.schedule({
  id: 1,
  title: 'Test!',
  text: "Test",
  launch: true
});`
