### ISSUE TITLE
Ionic Local Notification 0.9.0_beta.1 not working 

### ISSUE THREAD

**Issue by Ankitkumar7** [katzer/cordova-plugin-local-notifications#1608]
I have upgraded local notification from 0.8.5 to 0.9.0_beta.1 but when i run command ionic cordova run android error occurs:
Expected 1 arguments, but got 2.
      L92:  this.localNotifications.on("click", (notification, state) => {          
## Your Environment

* Plugin version: 0.9.0_beta.1
* Platform: android
* OS version: 8.0.0
* Device manufacturer / model: Mi A1
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): android 6.3.0

* Ionic Version (if using Ionic)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

**Comment by vivlong** [comment]
u need use below instead:
this.localNotif.on('click').subscribe(
(data : any) => {
 console.log(data)
})
