### ISSUE TITLE
Ionic3 Local Notification 0.8.5 Not Working 

### ISSUE THREAD

**Issue by Ankitkumar7** [katzer/cordova-plugin-local-notifications#1613]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
I am using ionic3 local notification 0.8.5. I am setting notification for multiple ids but after setting up time and setting notification, its clearing and cancelling out all alarm id after schedule not before and also how to get all notification ids which is cancelled 

## Your Environment

* Plugin version: 0.8.5
* Platform: android
* OS version: 8.0.0 ( oreo )
* Device manufacturer / model: MI A1 
* Cordova version (```cordova -v```):  7.1.0
* Cordova platform version (```cordova platform ls```): 

Installed platforms:
  --> android 6.3.0
* Available platforms:
  --> blackberry10 ~3.8.0 (deprecated)
  --> browser ~5.0.0
  --> ios ~4.5.1
  --> osx ~4.0.1
  --> ubuntu ~4.3.4 (deprecated)
  --> webos ~3.7.0
  --> windows ~5.0.0
  --> www ^3.12.0
* Plugin config: 
  --> com-badrit-base64 0.2.0 "Base64"
  --> cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
  --> cordova-base64-to-gallery 4.1.3 "base64ToGallery"
  --> cordova-plugin-android-permissions 1.0.0 "Permissions"
  --> cordova-plugin-app-event 1.2.1 "Application Events"
  --> cordova-plugin-calendar 5.0.0 "Calendar"
  --> cordova-plugin-camera 4.0.4-dev "Camera"
  --> cordova-plugin-device 1.1.4 "Device"
  --> cordova-plugin-facebook4 1.9.1 "Facebook Connect"
  --> cordova-plugin-file 5.0.0 "File"
  --> cordova-plugin-file-transfer 1.7.0 "File Transfer"
  --> cordova-plugin-firebase 1.0.0 "Google Firebase Plugin"
  --> cordova-plugin-geolocation 4.0.1 "Geolocation"
  --> cordova-plugin-googleplus 5.1.1 "Google SignIn"
  --> cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
  --> cordova-plugin-sim 1.3.3 "SIM"
  --> cordova-plugin-speechrecognition 1.1.2 "Speech Recognition"
  --> cordova-plugin-splashscreen 4.0.3 "Splashscreen"
  --> cordova-plugin-whitelist 1.3.1 "Whitelist"
  --> cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
  --> cordova-plugin-youtube-video-player 1.0.6 "CordovaYoutubeVideoPlayer"
  --> cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
  --> cordova-sqlite-storage 2.1.2 "Cordova sqlite storage plugin"
  --> cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
  --> de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
  --> es6-promise-plugin 4.1.0 "Promise"
  --> ionic-plugin-keyboard 2.2.1 "Keyboard"
  --> phonegap-plugin-barcodescanner 7.0.2 "BarcodeScanner"
* Ionic Version (if using Ionic)
*cli packages:
    --> @ionic/cli-utils  : 1.19.0
    --> ionic (Ionic CLI) : 3.19.0

*global packages:

    --> cordova (Cordova CLI) : 7.1.0

*local packages:

    --> @ionic/app-scripts : 3.1.4
    --> Cordova Platforms  : none
    --> Ionic Framework    : ionic-angular 3.9.2

*System:

    --> Android SDK Tools : 26.0.2
    --> Node              : v8.9.1
    --> npm               : 5.5.1
    --> OS                : Windows 10

* Environment Variables:
    --> ANDROID_HOME : G:\ANDROID_SDK_HOME
*Misc:

    --> backend : pro

## Expected Behavior
Setting up multiple notification but schedule() is executing before cancel() function.
_Tell us what should happen_

## Actual Behavior

N/A

_Tell us what happens instead_
N/A
## Steps to Reproduce
N/A
_Reproduce this issue; include code to reproduce, if relevant_
N/A
  1. N/A
  2. N/A
  3. N/A
  4. N/A

## Context
N/A
_What were you trying to do?_
Trying to schedule multiple notification.
## Debug logs
N/A
_Include iOS / Android logs_

  * ios XCode logs N/A
  * Android: $ adb logcat N/A

**Comment by Tawpie** [comment]
The scheduling and clearing methods run asynchronously so their order of execution is unknown. It's best to run the clear method and put your call to the scheduling method inside the callback for clear. This ensures that scheduling doesn't happen until the clear is completed.

**Comment by Ankitkumar7** [comment]
@Tawpie : Thanks, its working now .
