### ISSUE TITLE
The notification is not displayed on the lock screen and the LED-indicator does not turn on.

### ISSUE THREAD

**Issue by EvPut** [katzer/cordova-plugin-local-notifications#1614]
## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version:  6.0 MRA58K
* Device manufacturer / model: Xiaomi Redmi Note 4
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): android 7.0.0
* Plugin config:
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

* Ionic Version (if using Ionic): 3.20.0

Notification received, but is not displayed on the lockscreen (only on top) and the LED-indicator does not turn on.
**Added: After installing the application on the device, Settings -> Notifications and status bar -> Application notification -> My application - the lock screen and the light indicator are disabled.
After enabled, it works. How to make the default, after the installation they have been enabled?**

Me code:
```
cordova.plugins.notification.local.schedule({
	id: 1,
	title: 'TheBestDay',
	text: 'Test message',
	trigger: {at: my_date},
	led: { color: '#FF00FF', on: 500, off: 500 },
	lockscreen: true,
	vibrate: true,
	priority: 2,
	foreground: true
});
```

```
this.localNotifications.schedule({
	id: 1,
	title: 'TheBestDay',
	text: 'Test message',
	trigger: {at: my_date},
	led: { color: '#FF00FF', on: 500, off: 500 },
	lockscreen: true,
	vibrate: true
});
```

Thankful in advance for the help.

**Comment by Ankitkumar7** [comment]
@EvPut - Try this
``cordova.plugins.notification.local.setDefaults({
    led: { color: '#FF00FF', on: 500, off: 500 },
    vibrate: false
});

**Comment by EvPut** [comment]
Does not help, we are talking about this:
![ag1ug](https://user-images.githubusercontent.com/31080162/40577467-d528c8bc-610e-11e8-83eb-71bfe44a6050.png)
