### ISSUE TITLE
Android notification not working in OS 8.0 (oreo) AND ios (10.2)

### ISSUE THREAD

**Issue by Gamerakki** [katzer/cordova-plugin-local-notifications#1616]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

I have install installed the plugin for local notification of version 0.8. The plugin is not throwing any error but no notification is display as such in android 8.0 also ios 10.2

## Your Environment

* Plugin version:0.8
* Platform:Android/ios
* OS version:8.0/10.2
* Device manufacturer / model:Xiaomi Mi A1 
* Cordova version (```cordova -v```):8.0.0
* Cordova platform version (```cordova platform ls```):6.4.0/ios:4.5.4
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior
The notification should appear on the android screen and ios 10.2
_Tell us what should happen_
The notification should appear on the android screen and ios 10.2
## Actual Behavior
No notificaion is getting displayed in notification bar of android and ios 10.2
_Tell us what happens instead_
No notificaion is getting displayed in notification bar of android and ios 10.2
## Steps to Reproduce
Install the plugin 0.8 and run the app in any android 8.0 os devices and ios 10.2
_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

I have install installed the plugin for local notification of version 0.8. The plugin is not throwing any error but no notification is display as such in android 8.0 and ios 10.2

_What were you trying to do?_
Wanna display notification to user about file upload
## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by ConPor** [comment]
Try the [0.9.0-beta.3 ](https://github.com/katzer/cordova-plugin-local-notifications/releases/tag/0.9.0-beta.3) , be aware of i[ssue 1605](https://github.com/katzer/cordova-plugin-local-notifications/issues/1605)

**Comment by Gamerakki** [comment]
Hi @ConPor 
The latest plugin is not working properly when building the app for  android getting some sort of import error when i am trying to build. if u can help in that would be helpful

**Comment by zyyuer** [comment]
I have the same issue, it do well on my android 5. but android 8 not working.who can resolve the problem? Thanks in advance.

**Comment by churu88** [comment]
Hi Team, I have the same issue since yesterday. PhoneGap Builder is failing with this plugin. do you have any updates?

**Comment by pagano** [comment]
Not working on Android 8.0
Logcat: 06-04 12:38:54.035 4990-4990/net.cloudycrm W/Notification: Use of stream types is deprecated for operations other than volume control
    See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case

**Comment by ankurarora** [comment]
I have this from logs it seems to be appearing in status bar but not appearing as a dialog.

```loadUrl(javascript:cordova.plugins.notification.local.fireEvent("trigger",{"title":"Event Reminder","text":"Notification test","trigger":{"at":1541843280000,"type":"calendar"},"foreground":true,"actions":[],"attachments":[],"autoClear":true,"clock":true,"defaults":0,"groupSummary":false,"id":0,"launch":true,"led":true,"lockscreen":true,"number":0,"priority":1,"progressBar":{"enabled":false,"value":0,"maxValue":100,"indeterminate":false},"silent":false,"smallIcon":"res:\/\/icon","sound":true,"timeoutAfter":false,"vibrate":false,"wakeup":true,"meta":{"plugin":"cordova-plugin-local-notification","version":"0.9-beta.3"}},{"event":"trigger","foreground":true,"queued":false,"notification":0}))```

**Comment by velval** [comment]
For me the trigger at wasn't working on Android 8, however after long troubleshooting find out that by default the cordova android build was using android-27 api to compile. I then added a gradle.properties file with cdvCompileSdkVersion=android-28 and notifications started working. Hope it helps someone.

**Comment by FranklinAGK** [comment]
I basically just updated everything to get it working.

- Update Android studio and its SDK-tools.

- Update npm ( npm install -g npm ).

- Use smallIcon as recommended.

- Remove android platform and add it again( i haven't tried ios yet, it should work just fine ).
