### ISSUE TITLE
Android REPEAT notification not working in OS 8.x (oreo) 

### ISSUE THREAD

**Issue by va1bhav** [katzer/cordova-plugin-local-notifications#1617]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:0.9.0-beta.2
* Platform: Android
* OS version: 8.0+
* Device manufacturer / model: Samsung S8, Oneplus 6
* Cordova version (```cordova -v```): 7.0.0
* Cordova platform version (```cordova platform ls```): android 7.0.0
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Repeating notification(every 2 minutes) should be scheduled with below trigger:
trigger: { firstAt: Date, every : 2, unit : minute, count: 100 },

## Actual Behavior

For OS 8.0 and 8.0+ on android, only first notification is getting triggered and then it is getting deleted from scheduled notifications.

This functionality is working as expected for devices with OS 7.x

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Schedule a notification with below code:
cordova.plugins.notification.local.schedule([
                            {
                                id: 110232,
                                title: title,
                                text: description,
                                foreground: true,
                                progressBar: {
                                    enabled : false, value : timeStamp
                                },
                                actions: [
                                    { id: 'SNOOZE', title: 'SNOOZE', identifier: 'SNOOZE' }
                                ],
                               trigger: { firstAt: Date, every : 2, unit : minute, count: 100 },
                                badge : 1
                            }], succesCallback);
  2. Repeating notification is scheduled
  3. Only first notification is fired
  4. Notification is not visible in getScheduled notifications function and notification never repeats.

## Context

Trying to schedule a repeating notification for android also using firstAt property.

**Comment by va1bhav** [comment]
@katzer Could you please share if there is any timeline planned for this fix in future?

**Comment by Simpler1** [comment]
Try:

    cordova.plugins.notification.local.schedule({
      id: 110232,
      title: title,
      text: description,
      trigger: {
        firstAt: new Date(),
        every: 'minute',
        count: 100,
      },
    });

**Comment by h3nr1ke** [comment]
I'm also facing this issue =( does anybody knows a workaround for it? i need to schedule notifications like @va1bhav, for instance, every 5 minutes, every 8 hours.

I trying to figure it out, keep you guys posted... =(

**Comment by va1bhav** [comment]
@h3nr1ke @Simpler1   I was able to fix this by modifying the Plugin version:0.9.0-beta.2 with code in below commit.
https://github.com/katzer/cordova-plugin-local-notifications/commit/9a7bdb4b22738d3d03e1790b95f04003fc3a9bfa

After making these changes, the usual code will work for Android Oreo too. **The issue was - Android Oreo requires added option to provide params to create notification channel.**
