### ISSUE TITLE
Question: Is this plugin dead?

### ISSUE THREAD

**Issue by GitToTheHub** [katzer/cordova-plugin-local-notifications#1618]
The last commit was pushed before 4 months and there are a lots of issues regarding Android 8. I only wanted to know if the developer will maintain this plugin in the future or if he will let it die. (I see his main focus belongs to mruby)

**Comment by rwillett** [comment]
Not as far as I know,

The Android version has some issues with some of the more complex timing schedules, but we still use it and  we understand that work is still going on in the background.

Not every application is updated daily.

**Comment by GitToTheHub** [comment]
I know, that not every application is updated daily, but the last commit is 4 months old, that's not daily :)
No problem, i hope that there will be updates in the future. Anyway im very happy that this plugin exists :)

**Comment by Screeze** [comment]
Looks a bit like its almost dead :( But its the only local notification plugin I could found which seems at least partly up to date. But as far as I understood: v0.8 has issues with newer android/ios versions and v0.9-beta is also having issues. So currently there is no cordova plugin we can rely on for local notifications, am I right?

**Comment by GitToTheHub** [comment]
It's right. That's the only functioning Plugin you can use for local notifications. When you want to use it, then you should try the latest beta. For me it's now working, but you have to use the Android 8 Fix, which you can find in another Issue-Report.
I often saw problems in issue reports with repeating notifications. Maybe you have here issues too. With single Notifications there are no issues.
