### ISSUE TITLE
Notification not working on iOS 11.4. Shows notification 'Schedule with delay' instead every minute.

### ISSUE THREAD

**Issue by puneethshetty12** [katzer/cordova-plugin-local-notifications#1620]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

iOS display a notification with title 'Schedule with delay' with text 'Test Message 1'. But android shows the intended notification. 

i.e.,     cordova.plugins.notification.local.schedule({
            id: 1,
            title: 'Mitteilung',
            text: 'Trink '+$scope.waterml+'ml wasser!',
            icon: 'res://icon',
            trigger: { at: new Date() }, 
            smallIcon: 'res://icon_status'
        }); 

## Your Environment

* Plugin version: **0.9.0-beta.2 "LocalNotification"**
* Platform: **iOS**
* OS version: **11.4**
* Device manufacturer / model: **iPhone 6s**
* Cordova version (```cordova -v```): **8.0.0**
* Cordova platform version (```cordova platform ls```): **ios 4.5.4, android 7.0.0**
* Plugin config: 
* Ionic Version (if using Ionic)

## Expected Behavior
 Should display notification at a given time. This should happen multiple times based on the time stored in an array. This works fine on Android and browser (browser doesn't show notifications since this plugin doesn't support browsers. However, console logs prove that the code works just fine)

## Actual Behavior

-Notifications work as expected on Android. Tested on device running Android 6.0.1.
 -Notifications don't work on iOS. Instead, shows a notification with title 'Schedule with delay' and text 'Test Message 1'. I have not added these anywhere in the project.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

I am trying to display notifications at specific times in a give time interval. Notification fires when the time stored in the array matches the current time.

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment]
You are scheduling the notification in the past. It may only be a few milliseconds in the past, but it is in the past. Add a few seconds to the time.

**Comment by puneethshetty12** [comment]
@rwillett Thank you for the response.  By adding a few seconds, do you mean something like _**trigger: { in: 3 unit: seconds }**_ ?

I will try it out and will let you know if it works.

**Comment by cerw** [comment]
I get black screen of dead on IOS 11.4 :(

**Comment by puneethshetty12** [comment]
Hello @rwillett , I tried your solution. The issue persists. I am at my wit's end thinking what else to do. Just this issue. It works on Android but I keep getting a notification with title 'Schedule with delay' every minute. (probably because the setInterval runs every minute)
