### ISSUE TITLE
Possibility to play sound during ios notification up to 30 seconds

### ISSUE THREAD

**Issue by EugeneSnihovsky** [katzer/cordova-plugin-local-notifications#1621]
Hello!

I trying to use notification with sound indication like this
```
cordova.plugins..notification.local.schedule({
            foreground: true,
            id: 11,
            sound: 'file://assets/sound/incoming-call-long.caf',
            text: 'Text',
            title: 'Title'
        });
```
Where `incoming-call-long.caf` is 28 seconds sound file.

All works, notification shows and sound plays, but only during time when notification displayed on device screen. When notification hides (after approximately 7-8 seconds) - sound also stop playing. Notification not deleted by `clear` method, it just moved to notification bar automatically.

According to [stackowerflow and docs](https://stackoverflow.com/a/14437399/4357871) notification sound length can be up to 30 seconds.

Is there a way to play 30 seconds sounds with this plugin?

## Your Environment

* Plugin version: `installed from git master branch today (14 june 2018)`
* Platform: `ios`
* OS version: `10.3.3`
* Device manufacturer / model: `iPad air 2`
* Cordova version (```cordova -v```): `8.0.0`
* Cordova platform version (```cordova platform ls```): `cordova-ios: 4.5.4`
* Plugin config
```
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-cocoapod-support 1.5.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-music-controls 2.1.4 "MusicControls"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-twilio-video-ios 0.7.0 "TwilioVideoIOS"
cordova-plugin-vibration 3.1.0 "Vibration"
cordova-plugin-websocket 0.12.2 "WebSocket for Android"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.2 "Cordova sqlite storage plugin"
in.lucasdup.bringtofront 0.0.1 "Bring to Front"
phonegap-plugin-push 2.2.2 "PushPlugin"
```
* Ionic Version (if using Ionic)
```
ionic-cli: 3.20.0
ionic-angular: 3.9.2
```

**Comment by moaazhomaid** [comment]
I am interesting
i have this issue too, when the notification goes up then the sound play's and stop's after approximately 7 seconds, i am working with an app that must playing long sound up to 30 sec.
hope to get some help

i think there is no solution for it yet!

**Comment by Novecento88** [comment]
I am interested too. I just would like to add that this "problem" happens when the device is unlocked. When the device is locked audio plays entirely (correct me if I'm wrong).
