### ISSUE TITLE
Title and text are ignored in Windows when the UWP app is compiled in Release mode

### ISSUE THREAD

**Issue by qmatteoq** [katzer/cordova-plugin-local-notifications#1628]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0 beta 3
* Platform: Windows PC
* OS version: Windows 10
* Device manufacturer / model: Any Windows 10 computer
* Cordova version (```cordova -v```): 6.3.0
* Cordova platform version (```cordova platform ls```): 4.4.2
* Plugin config
* Ionic Version (if using Ionic): N/A

## Expected Behavior

I've declared a simple function to send a notification as soon as en event happens (in my sample app, the click of a button):

`function sendNotification() {
    cordova.plugins.notification.local.schedule({
        title: 'My first notification',
        text: 'Thats pretty easy...',
        foreground: true
    });`

The expected behavior is to see, regardless of the way the Windows version is compiled, the notification appearing with the title and text I've set.

## Actual Behavior

If the Windows version is compiled in debug mode, the notification looks good. If it's compiled, instead, in Release mode (for Store distribution), the custom title and text are ignored. The displayed notification uses, at title, the name of the app and, as text, the generic message "New notification".

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Add some code to create a new notification
  2. Add the Windows platform and launch the application compiled in Debug mode: notice the text of the notification is correct
  3. Now compile in Release mode and launch again the application: notice the wrong text of the notification

## Context

N/A

## Debug logs

N/A

**Comment by qmatteoq** [comment]
Hello and thanks for the reply!
Actually, I'm the author of the blog post you have linked :-) My bad that I forgot to update this issue with my findings!

**Comment by rwillett** [comment]
Now thats funny :)

**Comment by savithass** [comment]
:) Oops, I didn't notice it. Anyways thanks a lot, your blog saved my long time struggle.
