### ISSUE TITLE
Android 7.0: Notifications appearing only after opening the app

### ISSUE THREAD

**Issue by GitToTheHub** [katzer/cordova-plugin-local-notifications#1629]
Notifications did not appear under Android 7.0. But after opening the app, the notifications will appear. Have somebody the similar issue?

## Your Environment

* Plugin version: Latest, 0.9.0-beta.3
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Samsung S7 Edge
* Phonegap version : cli-7.1.0

## Expected Behavior
The Notifications should appear, without the need to open the app.

## Actual Behavior
The Notifications only appear, if you open the app.

## Steps to Reproduce
Normal sheduling of a notification. In other Android Versions it works.

**Comment by SidMorad** [comment]
My tested environment is close to yours but works for me.

 - Plugin version: 0.9.0-beta.3
 - Platform: Android
 - OS version: 7.0
 - Device manufacturer / model: Samsung Galaxy J7 Pro 
 - Cordova version: 8.0.0 cordova-android: 7.1.0

Here is my tested trigger syntax:
`trigger: { every: { hour: 10, minute: 0} }`

Thanks.

**Comment by GitToTheHub** [comment]
Hi, thank you for your respond!
I'm scheduling 50 single Notfications with no repeat (every 2 or 3 days a notification should appear).
You have an app where the notifications normally appear with Android 7, without the need to open the app?

**Comment by SidMorad** [comment]
@GitToTheHub Yes, I do confirm that I receive notification with Android 7 while the app is not open.

**Comment by GitToTheHub** [comment]
Thanks for your big reply :)
Ok, than there's no problem with Android 7, but maybe with the user who is using the app.
Thanks. I will check again, why the user only gets the notification, when he open the app.
I think, there is no problem with the Support-Library, but thanks for your deep search in your code changes :)
