### ISSUE TITLE
Conflict with cordova-plugin-firebase

### ISSUE THREAD

**Issue by dmeij** [katzer/cordova-plugin-local-notifications#1630]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

How do I fix the conflict with the cordova-plugin-firebase?

## Your Environment

* Plugin version: 
* Platform: iOS
* OS version: 11.3
* Device manufacturer / model: iPhone 6s
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): 4.5.4
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

OnNotificationOpen for cordova-plugin-firebase should receive messages when App is in the foreground.

## Actual Behavior

It doesn't

**Comment by rwillett** [comment]
No plugin information, no code, no information, no nothing. 

Difficult to comment really.

**Comment by flfruitios** [comment]
I am facing the same issue. It works for android, Firebase is able to call onNotification function.
But in iOS after some time, if message comes from Firebase, it is not calling onNotification function.

**Comment by MiguelSyll** [comment]
I have the same problem, I mean only with iOS. When I send a Notification when die App is in foreground, the Notification not appears. I uninstalled Local Notifications Plugin and I can trap the Notification and show it in the App. In Android I do not have Problems. Can you adapt your plugin to overcome this problem? Please. 

I hope to have news about this problem.

**Comment by shikelong** [comment]
+1

**Comment by shikelong** [comment]
how to fix it?

**Comment by rnovaski** [comment]
Anybody managed to fix this?
