### ISSUE TITLE
launch details does not work as the documentation specifies

### ISSUE THREAD

**Issue by iliran11** [katzer/cordova-plugin-local-notifications#1631]
## My Environment

* Plugin version: 0.9.0-beta.2
* Platform: android
* OS version: Android 5.1.1
* Device manufacturer / model: Samsung
* Cordova version cordova 7.1.0
* Cordova platform version android 6.3.0
* Plugin config - no special configuration
* Ionic Version (if using Ionic) - using onsen instead of ionic.

## Expected Behavior

following this documentation:
[Luanch Details](https://github.com/katzer/cordova-plugin-local-notifications#launch-details)

Expecting to have information object on:
`cordova.plugins.notification.local.launchDetails`

Expecting to have function to launch on:
`cordova.plugins.notification.local.fireQueuedEvents`

## Actual Behavior

`cordova.plugins.notification.local.launchDetails` is `undefined`

`cordova.plugins.notification.local.fireQueuedEvents` is `undefined`

The plugin itself is defined. I get the object on `cordova.plugins.notification.local`

**Comment by bjornicus** [comment]
I'm seeing the same behavior of `cordova.plugins.notification.local.launchDetails` being undefined in my app when launched via a notification, however, when I built the example app (https://github.com/katzer/cordova-plugin-local-notifications/blob/example-x/www/js/index.js) it does work.  Haven't tracked down what's different between the two and don't have time right now, but this may help someone track down what breaks it.
