### ISSUE TITLE
Local-notification 0.8.x in ios not working properly

### ISSUE THREAD

**Issue by Ankitkumar7** [katzer/cordova-plugin-local-notifications#1634]
Need help 

I am using local notification 0.8.x in ios 10+ , I am developing a module where user will give start time and end time and interval time but after setting up both time,all interval notification comes at end of time at once.

Please if you have any solution , help me.

Sorry for not following template.

**Comment by rwillett** [comment]
You are using the wrong plugin. You are using an old plugin. Read the first page and download the right plugin.

Also this issue has been raised by many, many times. A simple search of the issues would have found it.

Your boss is right to be concerned about your development ability.
