### ISSUE TITLE
Repeat Notification In IOS

### ISSUE THREAD

**Issue by BunnyUmar** [katzer/cordova-plugin-local-notifications#1635]
**Environment**

cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

Problem 
I want to schedule a notification for every x minute set by the user in ios.
as Repeat Count parameter is not available in ios.
also, I tried to reschedule notification in on trigger event but this event is only working if the app is running.

**Comment by rwillett** [comment]
1. No template so no idea what you are doing.
2. You cannot repeat automatcially, you need to set a repeat up manually, e.g. setup 30-40 local notifications.
