### ISSUE TITLE
Scheduled notifications don't fire on Android Pie

### ISSUE THREAD

**Issue by mkn20** [katzer/cordova-plugin-local-notifications#1638]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.beta.3
* Platform: Android P Preview Beta 3
* OS version: Mac
* Device manufacturer / model: Android Pixel 2 emulator
* Cordova version (```cordova -v```): 7.0.0
* Cordova platform version (```cordova platform ls```): Cordova Android 7.1.0
* Plugin config 
* Ionic Version (if using Ionic) 

## Expected Behavior
_Tell us what should happen_

Scheduled notification for specific date and time should fire.
## Actual Behavior
_Tell us what happens instead_
Only the first notification, 5 seconds from current time, fires successfully but any later ones for specific date and time in future does not fire though are scheduled without any error. All works fine in Android 8+.

## Steps to Reproduce
_Reproduce this issue; include code to reproduce, if relevant_
Just schedule notification for specific date and time in future.

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by sudattadesai72** [comment]
Hello I am facing same issue in Android Pie and IOS 12 beta. Can anybody fixed this??

**Comment by Tawpie** [comment]
If you could post the code you're using to schedule the notification, it will help. Otherwise it's not really possible for others to assist you.

**Comment by mkn20** [comment]
Code is same as in the example.

cordova.plugins.notification.local.schedule({
    title: 'Design team meeting',
    text: '3:00 - 4:00 PM',
    trigger: { at: new Date(2017, 10, 27, 15) }
});

Fires on Android 8.x but not on Pie.

**Comment by helixx2dbl** [comment]
@rushabhmakwana to fix this you need to use setExactAndAllowWhileIdle on android pie.  In the Notification class (/java/de.appplant.cordova.plugin/notification/Notification.java) change line 226 ish in the try/catch to this:
`try {
                switch (options.getPrio()) {
                    case IMPORTANCE_MIN:
                        if (SDK_INT >= M) {
                            mgr.setExactAndAllowWhileIdle(RTC_WAKEUP, time, pi);
                        } else {
                            mgr.setExact(RTC, time, pi);
                        }
                        break;
                    case IMPORTANCE_MAX:
                        if (SDK_INT >= M) {
                            mgr.setExactAndAllowWhileIdle(RTC_WAKEUP, time, pi);
                        } else {
                            mgr.setExact(RTC, time, pi);
                        }
                        break;
                    default:
                        if (SDK_INT >= M) {
                            mgr.setExactAndAllowWhileIdle(RTC_WAKEUP, time, pi);
                        } else {
                            mgr.setExact(RTC, time, pi);
                        }
                        break;
                }
            } catch (Exception ignore) {
                // Samsung devices have a known bug where a 500 alarms limit
                // can crash the app
            }`
