### ISSUE TITLE
v0.8.x TODO List

### ISSUE THREAD

**Issue by katzer** [katzer/cordova-plugin-local-notifications#164]
Things to be done for v0.8.x

## Changes
| Description | Platform | State | References |
| ---- | --------- | -------- | ------ |
| Rename `add` method to `schedule` | all | intended |
| Rename `onadd` event to `onschedule`| all | intended |
| Rename `date:` property to `at:` or `firstAt:` | all | intended |

## Enhancements
| Description | Platform | State | References |
| ---- | --------- | -------- | ------ |
| Schedule multiple notifications at once | all | maybe |
| Cancel multiple notifications at once | all | maybe |
| Clear multiple notifications at once | all | maybe |
| ✓ Callbacks for `add`, `cancel` & `cancelAll` | all | [done][callbacks] | #147 |
| `isScheduled` & `getScheduledIds` | WP8 | intended | #153 |
| ✓ Scopes for `isScheduled` and `getScheduledIds`| all | [done][callback_scopes] |
| ✓ Blank small icon | Android | done | #144 |
| ✓ Remote images | Android | [done][remote_images] | #76 |
| ✓ Android 2.x support | Android | [done][android2] | #154 |

## Features
| Description | Platform | State | References |
| ---- | --------- | -------- | ------ |
| ✓ LED support | Android | [done][led] |
| `clear` & `clearAll` methods | all | intended | #110, #115 |
| `onclear` event | all | intended |
| ✓ `isTriggered` & `getTriggeredIds` methods | all | [done][trigger_functions] | #155 |
| `onmiss` event | all | maybe | #156 |
| Better WP8 support | WP8 | intended | #101 |
| WP8.1 support | WP8 | maybe |
| Modal dialogs when in foreground | all | intended | #111 |
| Custom Notification Actions | iOS8 & Android | intended |
| Ability to change repeating notifications | all | intended |

## Deprecations
None yet.

## Release date
Some days after Germany won the World Cup ;)

[android2]: 626329dee077596e19957454ac738769843fb0c2
[callback_scopes]: 7fc01db0ac392d2c575e26100967637d523055d4
[callbacks]: cbf00120f246c0877c34af5506c6d9b65ea47fba
[remote_images]: 3649f4bc69e5e7014984458d2491e8fea8664180
[led]: 215a6597b12820ad9d6ca2a2431cdc2042268b34
[trigger_functions]: 50d81b5679ca3c2b4a3f06f341e708deb05bb6b2

**Comment by zmandel** [comment]
I see that "add" now has been renamed to "Schedule" on 0.8rc. Doesnt seem to be documented anywhere except here. Has onclick been renamed too? doesnt work anymore on 0.8x

**Comment by katzer** [comment]
hello @zmandel, please take a look into the wiki. Its not yet complete but I am working on it. There are various changes which are/will be documented there.

For example to listen for click event, please see this [page](https://github.com/katzer/cordova-plugin-local-notifications/wiki/09.-Events).
```javascript
cordova.plugins.notification.local.on("click", function (notification) {
    alert(notification.text);
});
```

**Comment by iamola** [comment]
How do we use the blank Blank small icon as mentioned above?
