### ISSUE TITLE
notifications in background it doesn't work for ios 11.4

### ISSUE THREAD

**Issue by cmaturana** [katzer/cordova-plugin-local-notifications#1642]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

The notifications stopped arriving when the application is in the background with the version of iOS 11.4, but they keep coming when it is open. If I try the plugin with version iOS 11.0 it works without problems.

Does anyone else have this problem with the update? Have they been able to solve it?
## Code 
cordova.plugins.notification.local.schedule({
                      title: ' ',
                      text: ' ',
                      foreground: true
        });

## Your Environment

* Plugin version: ~0.9.0-beta.3
* Platform: Cordova 8.0.0
* OS version: 11.4.1

**Comment by Tawpie** [comment]
Try 0.9.0 beta 3 (with fix for Android, search issues to find it or look in the pull requests)

**Comment by cmaturana** [comment]
I tried and still doesn't send notifications in the background

**Comment by Tawpie** [comment]
@cmaturana I'd suggest you fill out the template including the code you're using to schedule the notifications—otherwise it's pretty much impossible for anyone to understand what isn't right with your implementation.

**Comment by cmaturana** [comment]
I added the call to the notification method
