### ISSUE TITLE
not able to fetch the data object from notification using on.click method in iOS 11.4?

### ISSUE THREAD

**Issue by saty932** [katzer/cordova-plugin-local-notifications#1646]
`

    cordova.plugins.notification.local.requestPermission(function(data){
      console.log(data);
    });
    console.log(cordova.plugins.notification.local.launchDetails);

    cordova.plugins.notification.local.on("click", function (data) {
      console.log(JSON.parse(data));
      alert(JSON.parse(data.data.saty));
    });

    cordova.plugins.notification.local.schedule({
      id: 1,
      title:"xvg",
      text:"New offes Found",
      launch:true,
      data:{"saty":"br"},
      foreground:true
    });

  });

`
Above code when I use it for android I am able to get notification data but in iOS I am not  getting data object when I use click method.Any one is able to get the notification data when the notification clicked in iOS 11?please help me with this if anything goes wrong?

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.11.3
    npm        : 5.6.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

plugin I am using now
   `<plugin name="cordova-plugin-local-notification" spec="^0.9.0-beta.2" />`
iOS mobile version 11.4

**Comment by Tawpie** [comment]
This is what I use—I haven't looked specifically at iOS 11.4 AND I'm using beta-3 but it's been successful in the past

```
      // for when users click on a notification in the tray
      cordova.plugins.notification.local.on("click", function (notification) {
        an_handleKatzerLocalNotificationClickEvent(notification);  // do something
        console.log(
          "i.on.click id:" + notification.id + " " +
          new Date(notification.trigger.at) + " " +
          notification.data  // this is JSON
        );
```

**Comment by saty932** [comment]
@Tawpie 
Thanks for your reply I am also using the same code but I am not able to get the data.
`
cordova.plugins.notification.local.on("click", function (data) {
  console.log(JSON.parse(data));
  alert(JSON.parse(data.data.saty));
});


cordova.plugins.notification.local.schedule({
  id: 1,
  title:"xvg",
  text:"New offes Found",
  launch:true,
  data:{"saty":"br"},
  foreground:true
});
`
can you share how you are scheduling notification too??

**Comment by Tawpie** [comment]
sure... we're pretty complex (we have code to include action buttons but don't use it anymore) but here's the gist.

```
// when would we like this to go off?
    let dFireAt = getScheduledFiringForMessage(aAllMessages[i_anMessageIndex]);

    // build a json metadata string for use during unpacking
    let sMetaData =
      '{"rcls":"' +
      (sModule + "Reminders") +
      '","nid":"' +
      aAllMessages[i_anMessageIndex].id +
      '"}';

    // don't add it to the scheduling array unless the 'at' date is not more than a jiff from now
    /* a wad of code to determine whether or not to actually schedule */

      // build a basic reminder
      let oKatzerLNPluginReminder = {
        id: i + 1,
        trigger: { at: new Date(dFireAt) }, // MUST be a date object
        text: aAllMessages[i_anMessageIndex].displaytext,
        title: aAllMessages[i_anMessageIndex].headline
      };

      // android can show the smallIcon in the actionbar
      if (gsRunningOnPlatform.toLowerCase() === kPlatformandroid) {
        oKatzerLNPluginReminder.smallIcon = "res://" + gsANAndroidPushIcon;
      }

    // attach the metadata
      if (typeof sMetaData !== "undefined") {
        oKatzerLNPluginReminder.data = sMetaData; // Data to be passed through the notification
      }

      // add reminder object to the array for Katzer multiple scheduling
      gaMultiRemindersForKatzerLNPlugin.push(oKatzerLNPluginReminder);

******* we schedule a bunch of reminders at once so we do so using the array technique

cordova.plugins.notification.local.cancelAll(
            function scheduleAllRemindersViaKatzer() {
              console.log(
                "ANSLMH.anRLR - cancellation completed. Elapsed: " +
                  (new Date().getTime() - iStartTime) / 1000 +
                  " secs"
              );
              console.log(
                " ANSLMH.anRLR - scheduling >" +
                  gaMultiRemindersForKatzerLNPlugin.length +
                  "< local reminders"
              );
              cordova.plugins.notification.local.schedule(
                gaMultiRemindersForKatzerLNPlugin
              );
            }
          );
```
