### ISSUE TITLE
Location base notification iOS 10 stop working

### ISSUE THREAD

**Issue by mnievessoto** [katzer/cordova-plugin-local-notifications#1648]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
If I do a schedule notification by date notification shows but if I create a notification based on location not working.
## Your Environment
Mac high sierra with xcode 9.4.1 (9F2000)
* Plugin version: 0.9.0-beta.3
* Platform: iOS
* OS version: 11.3.1
* Device manufacturer / model: iPhone 6
* Cordova version (```cordova -v```): 8
* Cordova platform version (```cordova platform ls```): "ios": "4.5.4"
* Plugin config:  <plugin name="cordova-plugin-local-notification" spec="^0.9.0-beta.3" />
* Ionic Version (if using Ionic)

## Expected Behavior
Set 12 local notifications base on given location at a radius of 2 at application ready.
if user gets to any of the location radius will fire a notification depending on the location.
It was working after a few days ago i updated from 0.9.0-beta.2 to beta.3 and stopped working.
I install the previous version again and still not working.
_Tell us what should happen_

## Actual Behavior
if I trigger the notification using date it shows but if I use location not working.
_Tell us what happens instead_

## Steps to Reproduce
just schedule a notification at ready and get inside the radius location.
it wont show any notification.
_Reproduce this issue; include code to reproduce, if relevant_
 onDeviceReady: function () {
 cordova.plugins.notification.local.schedule({
        id:1,
        title: 'my City',
        text:'welcome message',
        foreground: true,
        trigger: {
            type: 'location',
            center: [Lat,Long],
            radius: 1,
            notifyOnEntry: true,
            notifyOnExit:true
        }
    });
}
## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs: logs don't have any error or warnings 
  * Android: $ adb logcat

**Comment by k05h** [comment]
I'm having the same problem. Any updates on this?

**Comment by Fever905** [comment]
Have you tried specifying the beta2 version?

**Comment by k05h** [comment]
I've tried all the versions up to beta3 with no luck.

**Comment by Fever905** [comment]
Me also.  I've found this that is a different way of doing it:
https://stackoverflow.com/questions/36036429/gps-coordinates-in-background-in-cordova-app
