### ISSUE TITLE
Is it possible to get local notifications on specific dates with different title?

### ISSUE THREAD

**Issue by chakri3130** [katzer/cordova-plugin-local-notifications#1649]
Provide a general summary of the issue.

## Your Environment

* Plugin version:v0.8.5
* Platform:iOS & MAC
* OS version:iOS 11.4
* Device manufacturer / model:Apple
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):cordova-ios@4.5.0
* Plugin config :cordova-plugin-local-notifications, supports:iOS>=10
* Ionic Version (if using Ionic):ionic v1

## Expected Behavior
I am expecting a notification only on schedule date with different title.
_Tell us what should happen_

## Actual Behavior
Getting a same notification with same title on daily basis even not scheduled dates also. 
_Tell us what happens instead_
Getting a same notification with same title on daily basis even not scheduled dates also. 

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_
var d = new Date();
d.setHours(20,0,0,0);
if(currenttime == scheduledtime)
{
  1. ...cordova.plugins.notification.local.schedule([{
                                                                                              id: 2,
                                                                                              title: "Title",
                                                                                              text: Title,
                                                                                              at: d,
                                                                                              every: "day",
                                                                                              icon: 'file://platforms/android/res/drawable-ldpi/icon.png',
                                                                                              sound: 'res://platform_default'
                                                                                              },
                                                                                              ]);
                                                 }
                                                 else
                                                 {
                                                 cordova.plugins.notification.local.cancel(2, function () {
                                                                                           Logger.debug("Event Notification has been canceled!!!!");
                                                                                           });
                                                 }

**Comment by rwillett** [comment]
Can't be done.

**Comment by rwillett** [comment]
You need to schedule them individually.
