### ISSUE TITLE
Need option to set a particular time of the notification visible

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [katzer/cordova-plugin-local-notifications#1650]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:
* Platform: Ionic 3
* OS version: Android and iOS
* Device manufacturer / model:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Need option to set a particular time for the notification to visible. Like visible just for 2 minutes or 5 minutes. And also need option to remove the particular notification if it is visible.

## Context

Need option to set a particular time for the notification to visible. Like visible just for 2 minutes or 5 minutes. And also need option to remove the particular notification if it is visible.

**Comment by rwillett** [comment]
AFAIK you cannot set a notification to be visible for a specific length of time. The underlying frameworks do not allow it.
