### ISSUE TITLE
Azure notification with IONIC V1

### ISSUE THREAD

**Issue by brwa88** [katzer/cordova-plugin-local-notifications#1653]
hello i have a mobile app with ionic v1 and i use azure notification 
with the bellow plugin
https://www.npmjs.com/package/cordova-azure-notification-hubs

i do receive notifications and its shown on notification area on android 7 and bellow
but on android 8 i receive the notification but its not shown on notification area

is there anyway to solve it thank you

**Comment by rwillett** [comment]
The template is there for a reason. Use it.
