### ISSUE TITLE
CordovaError: Failed to fetch plugin cordova-plugin-local-notifications via registry.

### ISSUE THREAD

**Issue by salouri** [katzer/cordova-plugin-local-notifications#1655]
* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version: Ubuntu 18.04.1 LTS 
* Device manufacturer / model: N/A
* Cordova version (```cordova -v```): 8.0
* Cordova platform version (```cordova platform ls```): Android 6.3.0
* Plugin config: 
* Ionic Version (if using Ionic): N/A (Cordova)

## Expected Behavior
Cordova plugin add cordova-plugin-local-notifications , should get the plugin and dependencies installed!

## Actual Behavior
Instead, I get: "CordovaError: Failed to fetch plugin https://github.com/katzer/cordova-plugin-local-notifications via registry"

## Steps to Reproduce

  1. just run:  Cordova plugin add cordova-plugin-local-notifications

## Context
For the past week, I have been trying to workaround the issue with the plugin on Android Oreo but even installing it "almost" never works! (worked once or twice).

## Debug logs

N/A as the problem is not on the Device.

**Comment by salouri** [comment]
BTW, I am 100% sure I am connected to the internet and I am able to install, re-install other plugins at the same time I wasn't able to do so with this plugin.

**Comment by rwillett** [comment]
Try cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git for the latest version.

**Comment by ankurarora** [comment]
I got this same error just now. Is that something to do with plugin or what?

**Comment by fmbuthia** [comment]
I am getting the same problem.

**Comment by fmbuthia** [comment]
Work around download plugin and do cordova plugin add /PATH_TO_PLUGIN_ON_COMPUTER

**Comment by Hosni** [comment]
I am getting the same problem.

**Comment by glebmachine** [comment]
same

**Comment by Loschcode** [comment]
Same problem here. Why isn't this addressed since 2018?
