### ISSUE TITLE
Local notification

### ISSUE THREAD

**Issue by divyangpatel0778** [katzer/cordova-plugin-local-notifications#1656]
Hello sir,

i phase some issue i need the every minute notification. and when i click on notification that time redirect in regarding page i have implemented in angular (cordova) . it was working in emulator but not working in mobile . how to solve it. please help me

**Comment by rwillett** [comment]
Use the template. Thats what its there for. 

You have posted nothing to help resolve the issue.

**Comment by rwillett** [comment]
Closed as no update
