### ISSUE TITLE
Terminating app due to uncaught exception - index 0 beyond bounds for empty array

### ISSUE THREAD

**Issue by terminaltor** [katzer/cordova-plugin-local-notifications#1657]
All methods returns same error, iOS only:
2018-08-06 10:14:57.086475+0300 *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'

Ionic, iOS - android is fine!

* Plugin version: 0.9.0-beta.3
* Platform: iOS
* OS version: 11.4
* Device manufacturer / model: Apple iPhone X
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): android 7.0.0,  ios 4.5.4
* Plugin config
* Ionic Version (if using Ionic): 3.20.0

## Expected Behavior
The getAll & schedule methods should work :)

## Actual Behavior
Getting this error:
'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array

## Steps to Reproduce
  1. Make a new project
  2. Install the plugin
  3. Use getAll or schedule method
  4. Debug with XCode

## Context
Schedule multiple local notifications for my users

## Debug logs
2018-08-06 10:14:57.086475+0300 HebCal [14732:1838811] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'

**Comment by rwillett** [comment]
Whats the code?

**Comment by mdgs** [comment]
Found the problem at below code `local-notification.js`:

`exports._exec = function (action, args, callback, scope) {
    var fn     = this._createCallbackFn(callback, scope),
        params = [];

    if (Array.isArray(args)) {
        params = args;
    } else if (args) {
        params.push(args);
    }

    exec(fn, null, 'LocalNotification', action, params);
};`

`getAll` with send args `0`, not array, and evaluated as false, hence params is empty

**Comment by marioshtika** [comment]
I have the same problem.
