### ISSUE TITLE
The notification can not handle the event when the app in background(ios)

### ISSUE THREAD

**Issue by coderjinhui** [katzer/cordova-plugin-local-notifications#1659]
First, sorry for my english, hope you can understand what I am talking about.

As the title, I try to add the trigger handler when the notification triggered.
It works well if the app doesn't in background.
But when my app is in background, the notification can triggered,but it doesn't call event handler

## Environment

* Plugin version: ```"cordova-plugin-local-notification": "^0.9.0-beta.2"```
* Platform: ```ios```
* OS version: ```ios 11.4```
* Cordova version (```cordova -v```): ```8.0.0```
* Cordova platform version (```cordova platform ls```): ```ios 4.5.5```
* Plugin config: ```<plugin name="cordova-plugin-local-notification" spec="^0.9.0-beta.2" />```
* Ionic Version (if using Ionic): ```3.20.0```

## Expected Behavior

If the notification is triggered, the on trigger function will be called.

## Actual Behavior

If the app doesn't in background, the on trigger function will be called.
But, when the app is in background, the notification still can triggered, but the on trigger function doesn't work

## Steps to Reproduce

The code is really simple:
### In html
```
<button ion-button (click)="setEvent()">setEvent</button>
<button ion-button (click)="callNotification()">callNotification</button>
```
### In setEvent function
```
this.localNotifications.on('trigger').subscribe(() => {
        console.log('triggered!!!!!!!!!!!!!!');
});
```
### In callNotification function
```
this.localNotifications.schedule({
      id: 2,
      text: 'Delayed ILocalNotification',
      trigger: { at: new Date(new Date().getTime() + 10000) },
      sound:null,
      priority: 2,
      launch: true
});
```

## Context

I think: Whether the app is in the foreground or in the background, the on trigger function still work.

## Debug logs

No error message and wornings, I just write a really simple demo include local-notification plugin and try the on trigger function.

**Comment by coderjinhui** [comment]
Is it not possible to call the on trigger function in ios 11? Maybe this is the ios's fault...

**Comment by cmaturana** [comment]
I have the same problem, when iOS update to 11.4 the notification doesn't work. I showed the problem here a few time ago but i haven't solution. Please, if you found the solution to this problem please share it!

**Comment by coderjinhui** [comment]
I still have no idea about it... I'll try to update the system to ios12, maybe it will be ok
