### ISSUE TITLE
Cant install with Latest cordova 8.0.0 version 

### ISSUE THREAD

**Issue by thelaunchengine** [katzer/cordova-plugin-local-notifications#1660]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Plugin installation not working with Latest Cordova and Android Platform
https://www.screencast.com/t/4Qe4uUeUeLe

## Your Environment

* Plugin version:  0.9.0-beta.3
* Platform: Android
* OS version: Windows
* Device manufacturer / model:
* Cordova version (```cordova -v```):  8.0.0 
* Cordova platform version (```cordova platform ls```):  Android 7.0.0
* Plugin config : - 
* Ionic Version (if using Ionic) : No IONIC

## Expected Behavior

Not getting installed

## Actual Behavior

It has suppose to be install successfully

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

Added it using following cmd
$ cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git

**Comment by rwillett** [comment]
Works for me on Cordova 8 WITH Ionic.

**Comment by dantenol** [comment]
Don't know if you still needs it, but for me it worked with `cordova plugin add cordova-plugin-local-notification`. It installs the 0.9.0 beta 2 on the packages.json and config files.
