### ISSUE TITLE
the "latest" tag on npm still points to 0.9.0-beta.2

### ISSUE THREAD

**Issue by shesek** [katzer/cordova-plugin-local-notifications#1663]
Should be changed to `0.9.0-beta.3`. See https://www.npmjs.com/package/cordova-plugin-local-notification?activeTab=versions.

**Comment by marcovtwout** [comment]
@katzer Please push the latest version to npm.

**Comment by marcovtwout** [comment]
Just to be precise: beta.3 is listed at npm, just not as "latest".

**Comment by hordesalik** [comment]
+
