### ISSUE TITLE
Could not find support-v4.aar (com.android.support:support-v4:26.1.0)

### ISSUE THREAD

**Issue by albertocanca** [katzer/cordova-plugin-local-notifications#1665]
Error when the build the app with plugin installed. 

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Android
* Cordova version: 8.0.0
* Cordova platform version: 7.0.0
* Ionic Version: 3.20.0

## Expected Behavior

The app builds successfully.

## Actual Behavior

When I build my ionic app, this errors appears

> Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find support-v4.aar (com.android.support:support-v4:26.1.0).
>   Searched in the following locations:
>       https://jcenter.bintray.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.aar

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Install plugin.
  2. Add android platform
  3. Build android version

**Comment by rwillett** [comment]
This is not a local notifications issue.
