### ISSUE TITLE
I fixed the issue about android 8+ not work led and vibrate

### ISSUE THREAD

**Issue by jevian-ma** [katzer/cordova-plugin-local-notifications#1668]
at the android 8+, NotificationChannel need to set enableLights and enableVibration.
I make a patch to fixed it as follow:
<pre>
diff --git a/src/android/TriggerReceiver.java b/src/android/TriggerReceiver.java
index 19c4eea..cc5915b 100644
--- a/src/android/TriggerReceiver.java
+++ b/src/android/TriggerReceiver.java
@@ -67,6 +67,8 @@ public class TriggerReceiver extends AbstractTriggerReceiver {
             wakeUp(context);
         }
 
+        manager.createDefaultChannel(options.getDict().optBoolean("led", true), options.getDict().optBoolean("vibrate", true));
+
         notification.show();
 
         if (options.isInfiniteTrigger()) {
diff --git a/src/android/notification/Manager.java b/src/android/notification/Manager.java
index c456597..769ef07 100644
--- a/src/android/notification/Manager.java
+++ b/src/android/notification/Manager.java
@@ -68,7 +68,6 @@ public final class Manager {
      */
     private Manager(Context context) {
         this.context = context;
-        createDefaultChannel();
     }
 
     /**
@@ -106,7 +105,7 @@ public final class Manager {
      * TODO: temporary
      */
     @SuppressLint("WrongConstant")
-    private void createDefaultChannel() {
+    public void createDefaultChannel(Boolean enablelights, Boolean enablevibration) {
         NotificationManager mgr = getNotMgr();
 
         if (SDK_INT < O)
@@ -119,6 +118,8 @@ public final class Manager {
 
         channel = new NotificationChannel(
                 CHANNEL_ID, CHANNEL_NAME, IMPORTANCE_DEFAULT);
+        channel.enableLights(enablelights);
+        channel.enableVibration(enablevibration);
 
         mgr.createNotificationChannel(channel);
     }
</pre>
please to commit it, thank you.

**Comment by phiamo** [comment]
+1

**Comment by angel1st** [comment]
+1

**Comment by Wobow** [comment]
+1

**Comment by HartzDev** [comment]
Hi, @jevian-ma ,
Do this plugin work on your android 8.0?
i make some notifs. and its not working in android 8.0.
no notification called , no sound, infact the plugin set the notif.

**Comment by shahkeyur** [comment]
> 
> 
> Hi, @jevian-ma ,
> Do this plugin work on your android 8.0?
> i make some notifs. and its not working in android 8.0.
> no notification called , no sound, infact the plugin set the notif.

Yes it works. I have tested it on multiple 8.0 devices

**Comment by HartzDev** [comment]
thx @shahkeyur ,
i will try. :D

**Comment by HartzDev** [comment]
@shahkeyur , i have try ur code, notif i shown, but no custom sound . 
do i have to use Ringtone class for Oreo smartphone? thx in advanced.
