### ISSUE TITLE
trigger match repeats

### ISSUE THREAD

**Issue by Guiladg** [katzer/cordova-plugin-local-notifications#1669]
When I set a schedule on a specific time, for example { every: { hour: 10, minute: 30 } }, notifications pop every second until 10:31. I just want it to pop once, every day at 10:30. Thanks

**Comment by rwillett** [comment]
Then write a specific piece of code to do it. I recall you have 64 triggers on IOS, if your user doesn't log on to your app in 64 days for you to refresh the code, then your use case is wrong.

**Comment by h3nr1ke** [comment]
What about add in the config 

{ every: { hour: 10, minute: 30 }, count : 1 }

but I'm not sure if this will count the entire cycle of the notification or just in the minute that it matches...

**Comment by Guiladg** [comment]
"Count: 1" is ok for the repeating issue but then it doesn't show a notification the next time it's supoused to. I need a notification every day at the same time besides the user open or not the app.

**Comment by Simpler1** [comment]
Set "count" to some high number like 365.  Then you will only get one notification per day for a year.

**Comment by jb-72** [comment]
Anyone solved this? I have exactly the same issue. Instead of firing once when hour and minute first match current time it fires continuously while they match.

Needs to repeat every day at the same time whether app has been opened or not and only fire once at that time.

**Comment by pjhartin** [comment]
Following up on this too, experiencing the same thing

**Comment by raghav14** [comment]
Guys any updates on this issue? Are we able to resolve it somehow?

**Comment by SamChangi** [comment]
this works for me, thanks a lot! https://github.com/katzer/cordova-plugin-local-notifications/issues/1533#issuecomment-463625420
