### ISSUE TITLE
'clock' property not implemented properly

### ISSUE THREAD

**Issue by InventivetalentDev** [katzer/cordova-plugin-local-notifications#1671]
It seems like the `clock` property is not properly implemented, as the android documentation states there should be a [`when`](https://developer.android.com/reference/android/app/Notification#when) property for the timestamp the event will occur.  
The android source also only calls the [#setShowWhen](https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/android/notification/Builder.java#L139) method but never calls anything to specify the actual timestamp.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version: Win 10
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): android 7.0.0
* Ionic Version (if using Ionic): 4.1.1

## Expected Behavior

There should be a property to specify the `when` timestamp.

## Actual Behavior

You're only able to choose between showing the `when` date or not, but you're unable to specify that date. (There also doesn't seem to be any property of a different name that would set the date, as the android code never calls the required method)

## Context

Trying to make a notification that counts down to a specific date.

**Comment by Steffaan** [comment]
Added, see [here](https://github.com/Steffaan/cordova-plugin-local-notifications)
