### ISSUE TITLE
Missing properties on default values

### ISSUE THREAD

**Issue by tlacaelelrl** [katzer/cordova-plugin-local-notifications#1672]
## Summary:
line 93 of local-notification-util.js:93 Unknown property: xxx

These properties from _defaults are missing and causing warnings on the console
meta,
ongoing

* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version: Windows 10
* Device manufacturer / model: Motorola G4
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior
No warning should be thrown 

## Actual Behavior

Warning is thrown 

## Steps to Reproduce

  1. run code cordova.plugins.notification.local.schedule({
		text: "sample",
		ongoing: false
	});

**Comment by jcunhafonte** [comment]
+1
