### ISSUE TITLE
 function in baground local notification

### ISSUE THREAD

**Issue by eros2187** [katzer/cordova-plugin-local-notifications#1674]
hi I wanted to know if someone who used this plugin somehow managed to start a notification without using the schedule.
is it possible to run a function with a completely closed app that can synchronize data in order to download data?
I currently use local push but if I do not open the app to download the data, the notifications do not start using the schedule.
someone to find some solution using this plugin?
I know that the most obvious solution is to burn firebase but I was looking for a proprietary solution.
thank you

**Comment by rwillett** [comment]
1. Unsure how you can create a local notification without using the schedule and why you would want to.  What's the use case?

2. You are looking to run stuff in the background and do background processing. Apple will not let you do this. There are a number of ways that people have tried to bypass this using audio plugins. Apple catches them and bans the app. The battery life on mobile devices is limited and once your app is in the background, it will get suspended and you cannot do this.  There are agreed exceptions to this, audio playback and sat nav functionality are some of them. We use background processing for GPS management. However you are severely limited by Apple as to what you can and cannot do in the background.  

You need to show your use case for this. If you app is in the background why do you need to download data? What is the app going to do with the data when it's in the background and is suspended?

**Comment by eros2187** [comment]
I was trying to develop a calendar that allows you to remember when to perform an event, I did not want to download everything in memory but use the data little by little. in fact I create a schedule for the notification every x hour.

I imagined that the problem was ios unfortunately the only solution at the moment and push natives with firebase.

so you have tried to use audio and gps plugins with ios but without positive results because of how or understood ios blocks everything. quite right?

thank you.

**Comment by rwillett** [comment]
So where is the calendar app running? if its running the device, then you have 64 local notifications under IOS you can schedule in advance. That number might change. If people aren't using your app to check things and then allow you to download more data and schedule more calender events what use is the app on the device?

We use PushWoosh but we are converting to use OneSignal as a notification provider. OneSignal is free and has a good SDK. 

We have never used audio plugins for background downloading. We use a GPS plugin, but we use it in accordance with Apples rules so we have no issues. We also download lots of data as we manage traffic updates, so we could send 40K of data every 5 minutes to a device. We only send this data when the app is in the foreground as its pointless in the background. We process the traffic updates on a server and send notifications from a server. We also use the GPS background tracking (as we are allowed to do this by Apple) to schedule and send local notifications when the app is in the background. We do NOT download data in the background.
