### ISSUE TITLE
error compile cordova 

### ISSUE THREAD

**Issue by eros2187** [katzer/cordova-plugin-local-notifications#1675]
when I fill it out with me it returns this error:
cordova version 8.00
compile using node js in local no android studio:
**error report:
(node:3204) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle
in your path, or install Android Studio**
what would be the problem?

**Comment by rwillett** [comment]
Closed as no update from OP
