### ISSUE TITLE
[Solved] How to cancel a scheduled notification?

### ISSUE THREAD

**Issue by Kyleeeez** [katzer/cordova-plugin-local-notifications#1676]
As above.
How do I cancel a scheduled repeating notification?

**Comment by Steffaan** [comment]
Use `cordova.plugins.notification.local.cancelAll();`

If you want to cancel some notifications specific by their ID use the  `cordova.plugins.notification.local.cancel([ids]);` method

**Comment by Kyleeeez** [comment]
Thank you @Steffaan !!!
Solved
