### ISSUE TITLE
0.8.4 not displaying notifications on iOS

### ISSUE THREAD

**Issue by mfrna** [katzer/cordova-plugin-local-notifications#1677]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Scheduling a notification on iOS doesn't work, I have verified that the schedule method executes successfully and the plugin actually recognizes the added notifications by adding schedule method callback and on("schedule") event callback

## Your Environment

* Plugin version: 0.8.4
* Platform: iOS
* OS version: 11
* Device manufacturer / model: iPhone 6, iPhone 6/6s/X emulators
* Cordova version (```cordova -v```):8.0.0
* Cordova platform version (```cordova platform ls```): ios 4.1.1
* Plugin config: <plugin name="cordova-plugin-local-notification" spec="~0.8.4" />
* Ionic Version (if using Ionic): 4.0.6

## Expected Behavior

A notification appears

## Actual Behavior

Schedule callback is executed, and on schedule event executes but the notification never appears

## Steps to Reproduce
`
cordova.plugins.notification.local.schedule({
                                id: "1",
                                at: new Date((new Date()).getTime() + 5000),
                                text: "Please click here to view the report.",
                                title: "Visit Ended",
                                foreground: true,
                                // autoCancel: false,
                                // icon: "img/icon.png",
                            },function(){console.log('Schedule callback called!');});
`

## Context

display a notification :)

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication cancelLocalNotification:]
PID: 25684, TID: 1459225, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   AppName                           0x000000010fe83307 -[APPLocalNotification cancelForerunnerLocalNotification:] + 279
5   AppName                           0x000000010fe82ece -[APPLocalNotification scheduleLocalNotification:] + 62
6   AppName                           0x000000010fe7fb22 __33-[APPLocalNotification schedule:]_block_invoke + 466
7   libdispatch.dylib                   0x00000001179cf7ab _dispatch_call_block_and_release + 12
8   libdispatch.dylib                   0x00000001179d07ec _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00000001179d5619 _dispatch_queue_override_invoke + 1451
10  libdispatch.dylib                   0x00000001179dc36c _dispatch_root_queue_drain + 664
11  libdispatch.dylib                   0x00000001179dc076 _dispatch_worker_thread3 + 132
12  libsystem_pthread.dylib             0x0000000117efb169 _pthread_wqthread + 1387
13  libsystem_pthread.dylib             0x0000000117efabe9 start_wqthread + 13
2018-09-09 17:34:45.812904+0200 AppName[25684:1459225] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication cancelLocalNotification:]
PID: 25684, TID: 1459225, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   AppName                           0x000000010fe83307 -[APPLocalNotification cancelForerunnerLocalNotification:] + 279
5   AppName                           0x000000010fe82ece -[APPLocalNotification scheduleLocalNotification:] + 62
6   AppName                           0x000000010fe7fb22 __33-[APPLocalNotification schedule:]_block_invoke + 466
7   libdispatch.dylib                   0x00000001179cf7ab _dispatch_call_block_and_release + 12
8   libdispatch.dylib                   0x00000001179d07ec _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00000001179d5619 _dispatch_queue_override_invoke + 1451
10  libdispatch.dylib                   0x00000001179dc36c _dispatch_root_queue_drain + 664
11  libdispatch.dylib                   0x00000001179dc076 _dispatch_worker_thread3 + 132
12  libsystem_pthread.dylib             0x0000000117efb169 _pthread_wqthread + 1387
13  libsystem_pthread.dylib             0x0000000117efabe9 start_wqthread + 13

**Comment by rwillett** [comment]
The documentation is clear, don't use V0.8.4 on IOS > 9. Use the latest version.
