### ISSUE TITLE
trigger: incompatible type problem

### ISSUE THREAD

**Issue by rotsix** [katzer/cordova-plugin-local-notifications#1678]
VSCode and Ionic are crying and displaying some errors when using this code:

```javascript
this.localNotif.schedule({
  id: 1,
  title: "Title",
  text: "Say Hello",
  launch: true,
  trigger: {
    every: {
      hour: hour,
      minute: minute,
    },
    count: 365,
  },
  actions: [
    { id: "go", title: "Go!" }
  ],
  foreground: true,
});
```
(with `hour` and `minute` numbers)

## Your Environment

* Plugin version:
> "@ionic-native/local-notifications": "4.12.2",
> "cordova-plugin-local-notification": "^0.9.0-beta.2",
* Platform: archlinux
* OS version: up-to-date
* Device manufacturer / model: Lenovo E540
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```):
```
Available platforms: 
  android ~7.0.0
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```
* Plugin config: none?
* Ionic Version (if using Ionic): 3.20.0

## Actual Behavior

both ionic and vscode are crying, incompatible type. And they shouldn't be

## Debug logs

```
Type
'{
  id: number;
  title: string;
  text: string;
  launch: true;
  trigger: {
    every: {
      hour: number;
      minute: n...'
is not assignable to type 'ILocalNotification[]'
```

Thanks!

**Comment by presidentnickson** [comment]
Did you get this sorted ? Having the same issue

**Comment by rotsix** [comment]
Hi, sadly, I couldn't get it working.
I gave up and used push notifications instead.
