### ISSUE TITLE
If I clicked in the notification this doesn't open the view that it's coded

### ISSUE THREAD

**Issue by ginirocha45** [katzer/cordova-plugin-local-notifications#1679]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: Android
* OS version:
* Device manufacturer / model: Samsung Galaxy S5 new edition
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): Android 7.0.0
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

If I click on the notification, it will get me to the view that I have already coded

## Actual Behavior

When the notification arrive and I clicked, this take to the last view of the app that it was open

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

I want that when the notification arrives and clicks on it, it takes me to the view that I need it to open.
For example, if I get a notification from Facebook notifying me that someone mentioned me in a photo and I click on it, it takes me to the photo where I was mentioned.

## Context

I have tried this, but it only works if the view where it was coded is open

cordova.plugins.notification.local.on('click', function (notification) {
                    console.log('onclick', arguments);
                    showToast('clicked: ' + notification.id);
                    $(location).attr('href','prueba.html');
                });

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment]
Closed as a coding issue and no response from OP.
