### ISSUE TITLE
Cannot add Actions

### ISSUE THREAD

**Issue by KostasGeor** [katzer/cordova-plugin-local-notifications#1680]
I am working at Ionic 3 to make a simple app which will trigger repeated notifications every day. I also want the notification to be able to be answered by "yes" or "no". However, when I am trying to add two actions, with title and id "yes" and "no", just like the documentation, it throws an error message saying "cordova.plugins.notification.local.addActions is not a function". Has anyone come across this problem or knows a solution??

**Comment by ybouhouch** [comment]
try this : 

  this.localNotifications.schedule({
     title: 'Title',
     text: 'Text',
     actions: [
                 { id: '0', title: 'Yes' },
                 { id: '1',  title: 'No' }
              ]
     });
