### ISSUE TITLE
Possible to pause/cancel by id and un-pause/activate by same id?

### ISSUE THREAD

**Issue by dayaki** [katzer/cordova-plugin-local-notifications#1687]
** Not using the template as this is no bug in itself **

Am wondering if this is possible or any way to "hack" this to work? I want users to be able to disabled a particular notification and enable it later.

What am thinking is cancelling the notification by id when user disabled and recreate same notification afresh using same id of the cancelled notification.

Any other ways to achieve this?

**Comment by rwillett** [comment]
Your logic is the way we do it. AFAIK you cannot pause a notification, its pretty simple to kill it and recreate it,

**Comment by dayaki** [comment]
Thanks @rwillett
