### ISSUE TITLE
How to set up a daily notification?

### ISSUE THREAD

**Issue by santoshjoseph99** [katzer/cordova-plugin-local-notifications#1689]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

Just seeing a compile time error trying to setup the following:
```
      const input = {
        title: 'daily notification',
        trigger: { every: 'day', at: {hour: 8, minute: 0} }
      };
      this.localNotifications.schedule(input);
```
I get the following error:
```
[ts]
Argument of type '{ trigger: { every: string; at: { hour: number; minute: number; }; }; }' is not assignable to parameter of type 'ILocalNotification | ILocalNotification[]'.
  Type '{ trigger: { every: string; at: { hour: number; minute: number; }; }; }' is not assignable to type 'ILocalNotification[]'.
    Property 'length' is missing in type '{ trigger: { every: string; at: { hour: number; minute: number; }; }; }'.
```

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version: 8.0
* Device manufacturer / model: emulator
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```):
```
Installed platforms:
  android 7.0.0
  ios 4.5.5
Available platforms:
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```
* Plugin config
* Ionic Version (if using Ionic): `4.1.2`

## Expected Behavior

How to set up a trigger to a daily notification at a hour/minute.

## Steps to Reproduce

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by elchory96** [comment]
Hi, if you look at me I have the same error, when you are using the code:

`trigger: { every: 'day', at: {hour: 8, minute: 0} }`

with the trigger every, the attribute is automatically canceled (at: {}) so you must use the convention

```
trigger: {
 every: {
 weekday: day.dayCode,
 hour: firstNotificationTime.getHours(),
 minute: firstNotificationTime.getMinutes(),
 second: firstNotificationTime.getSeconds()
 },
 count:1
},
```
What you should do is create a notification for each day of the week that you are going to show the notification, where you must change it is in "weekday", the days are from 0 to 6, where 0 is Sunday and 6 is Saturday.

Then just put the hour, minutes and seconds in which the notification will be displayed on the day.

PD: What I realized is that the packete @ ionic-native / local-notifications is not updated to the same parameters of this repository. What you should do is use the code directly:

`cordova.plugins.notification.local.schedule();`

For example.

**Comment by santoshjoseph99** [comment]
I understand.  I can use that line directly in ionic.  thanks!

**Comment by santoshjoseph99** [comment]
@elchory96 just curious, if I use this: `trigger: { every: { hour: 8, minute: 0 } },`, shouldn't that be sufficient? 
also a side note...can I cancel or clear a notification before it shows? I think I should handle the `trigger` event, but then I don't want to cancel all of the repeating notifications...just that particular one if I choose.

**Comment by avais88786** [comment]
Hi @santoshjoseph99 were you able to fix this?

**Comment by santoshjoseph99** [comment]
@avais88786 I did the following: `trigger: { every: 'day', count: 365 },`, but that doesn't seem to work every day (actually worked for like 2 weeks and now no notifications)/.

**Comment by Simpler1** [comment]
I haven't been able to successfully get a daily notification to work either.  It seems to work sometimes, but not others.  If you look at the scheduled notifications, they show that they are set, but they don't trigger.
