### ISSUE TITLE
Notification not Fired in iOS 10.2

### ISSUE THREAD

**Issue by mahesh-vi** [katzer/cordova-plugin-local-notifications#1691]
* Plugin version:0.8.5
* Platform:iOS
* OS version:10.2

- Local Notification fired but Banner of local notification not display in Notification center.
- Notification sound and vibration come but banner not come.
- It work fine in iOS 11.4 

var now = new Date().getTime();
var mDate = new Date(now + 2 * 1000);
 var option = {
                        id: "1",
                        title: "Title",
                       at: mDate,
                                           };

**Comment by lloydmurray** [comment]
same on iOS 12.0.1  @mahesh-vi - did you mean 12.0 os version?

**Comment by mahesh-vi** [comment]
@lloydmurray 
Please use https://github.com/EddyVerbruggen/cordova-plugin-local-notifications/tree/master 
this plugin if you want to use 0.8.5 version.

**Comment by lloydmurray** [comment]
@mahesh-vi  - Does the EddyV version work on ios12?  I'm still seeing the same issue.  thanks.

**Comment by mahesh-vi** [comment]
Yes it's working for me.
Version : 0.8.4
