### ISSUE TITLE
Daily notifications

### ISSUE THREAD

**Issue by dayaki** [katzer/cordova-plugin-local-notifications#1693]
** This is not really an issue, so am ignoring the template**

Please can anyone help, am trying to set up a daily notification, say a notification everyday at 16:30. Code I tried didn't trigger at all:

`const today = new Date().setHours(16, 30);
    const info = {
      id: 1,
      text: "reminder",
      trigger: { every: 'day', at: new Date(today), count: 5 }
    }
    cordova.plugins.notification.local.schedule(info)`

**Comment by joegarb** [comment]
Using version 0.9.0-beta.3 of the plugin, here's the format of `trigger` that I use successfully for a daily notification, so give this a try:

```
trigger: {
    every: {
        hour: 16,
        minute: 30
    }
}
```

If nothing's still happening, I'd suggest testing it out on iOS if you haven't already, because I've found that for Android my AndroidManifest.xml was getting messed up by the ionic build command, due to I guess conflicts between other cordova plugins that I'm using. (To fix that, I eventually made a working manifest file and saved a copy of it that I use for now)

**Comment by dayaki** [comment]
Thanks, I have seen and use this code before but it doesn't repeat on the next day, only triggers for the first day....I will try it out on iOS though

**Comment by dayaki** [comment]
@joegarb can you please share the working manifest and how to make it work on Android please.

**Comment by dayaki** [comment]
Here is my manifest file

`<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="1" android:versionName="0.0.1" package="com.mosque.mobile" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:screenOrientation="portrait" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="de.appplant.cordova.plugin.notification.util.AssetProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/localnotification_provider_paths" />
        </provider>
        <receiver android:exported="false" android:name="de.appplant.cordova.plugin.localnotification.TriggerReceiver" />
        <receiver android:exported="false" android:name="de.appplant.cordova.plugin.localnotification.ClearReceiver" />
        <activity android:exported="false" android:launchMode="singleInstance" android:name="de.appplant.cordova.plugin.localnotification.ClickReceiver" android:theme="@android:style/Theme.Translucent" />
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/fb_app_id" />
        <meta-data android:name="com.facebook.sdk.ApplicationName" android:value="@string/fb_app_name" />
        <activity android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="@string/fb_app_name" android:name="com.facebook.FacebookActivity" />
        <service android:enabled="true" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementService" />
        <service android:name="org.apache.cordova.firebase.FirebasePluginMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="org.apache.cordova.firebase.FirebasePluginInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
        <receiver android:name="org.apache.cordova.firebase.OnNotificationOpenReceiver" />
        <meta-data android:name="io.fabric.ApiKey" android:value="e90891bfa20df0c7bb74edf18de4bbb5ed10626d" />
        <activity android:label="TimelineListActivity" android:name="com.manifestwebdesign.twitterconnect.TimelineListActivity" android:theme="@android:style/Theme.NoTitleBar" />
    </application>
    <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="26" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.USE_CREDENTIALS" />
</manifest>
`

**Comment by joegarb** [comment]
The only relevant difference between ours seems to be that I have this:
```
        <receiver android:directBootAware="true" android:exported="false" android:name="de.appplant.cordova.plugin.localnotification.RestoreReceiver">
            <intent-filter>
                <action android:name="android.intent.action.LOCKED_BOOT_COMPLETED" />
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
```
and boot permission:
`<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />`
So that might not be the issue for you unless you were rebooting unfortunately.
