### ISSUE TITLE
Exclude from repeatable/match

### ISSUE THREAD

**Issue by VadimSemenuk** [katzer/cordova-plugin-local-notifications#1694]
Is it possible to exclude some dates from repeatable notifications.
For example I have such configuration (repeat note every day):
`...,
trigger = { 
          every: 
          { 
                  hour: note.startTime.hour(), 
                  minute: note.startTime.minute()
           },
 count: 999
},
...`

And for example i need the note not to notificate on 20 october 2018.
Is it possible to achieve this behaviour using this plugin?

**Comment by echonox** [comment]
@katzer is it possible to achieve this?
