### ISSUE TITLE
Cancel notification when app is killed (not paused)

### ISSUE THREAD

**Issue by ThibertT** [katzer/cordova-plugin-local-notifications#1697]
/!\ NOT AN ISSUE WITH THE PLUGIN ITSELF /!\

## Environment

* Plugin version: 4.14.0
* Platform: Android/iOS
* Cordova version : 8.0.0
* Cordova platform version : android 7.1.1 / ios 4.5.0
* Ionic Version : 3.20.0

## Expected Behavior

Cancel all scheduled notifications when app is killed (not paused)

## Context

- My app is scheduling notifications **when it's entering in background mode** (catching this.platform.pause) to **tell user that app is in background**.

- I need to cancel notifications when user kill the app. Yeah because app is not still in background so no need to send notifications to user that tell him app is in background...

- It is not possible to catch a killing app event with ionic. I mean I didn't find one... Did you ?

- How could I configure notifications to cancel when app is killed ?

- I begin to consider that it's something not possible... One workaround was using setInterval with notifications (not scheduled notifications) but after a big time in background (hours) setInterval is not triggered... 

Thanks for your help :)

**Comment by rwillett** [comment]
You can't detect that an app is killed in the background. 

Even if an event was triggered to say that an application was killed, you wouldn't be given any time to start the app up to process the fact the application was killed.

AFAIK you cannot do what you are trying to do.

**Comment by ThibertT** [comment]
Yeah that's my opinion too... Thank for your answer
