### ISSUE TITLE
Crosswalk compatibility?

### ISSUE THREAD

**Issue by CoenWarmer** [katzer/cordova-plugin-local-notifications#170]
I was wondering if this plugin is compatible with the Android Crosswalk project?

https://crosswalk-project.org/#wiki/Plugins-List-@-3.3.0-Supported-by-Crosswalk-Cordova-Android

**Comment by DayBr3ak** [comment]
well no, it is not compatible

**Comment by DayBr3ak** [comment]
Still not compatible with crosswalk
:compileArmv7DebugJava/home/daybreak/evd/ion/anype/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:473: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
/home/daybreak/evd/ion/anype/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:470: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED
