### ISSUE TITLE
Unknown property: firstAt

### ISSUE THREAD

**Issue by rushabhmakwana** [katzer/cordova-plugin-local-notifications#1705]
$cordovaLocalNotification.schedule([{id: 1, title: "Daily Training Reminder", at: Mon Oct 22 2018 08:00:00 GMT+0530 (India Standard Time), every: "day", firstAt: Mon Oct 22 2018 14:00:00 GMT+0530 (India Standard Time)},{id: 2, title: "Daily Training Reminder", at: Mon Oct 22 2018 09:00:00 GMT+0530 (India Standard Time), every: "day", firstAt: Mon Oct 22 2018 14:00:00 GMT+0530 (India Standard Time)},{id: 3, title: "Daily Training Reminder", at: Mon Oct 22 2018 10:00:00 GMT+0530 (India Standard Time), every: "day", firstAt: Mon Oct 22 2018 14:00:00 GMT+0530 (India Standard Time)}]).then(function (result) {
        // ...
      });

**Comment by marcovtwout** [comment]
Version 0.8 is not maintained anymore, you should update to 0.9 and close this issue.

(hint: see the latest documentation on where to set "firstAt": https://github.com/katzer/cordova-plugin-local-notifications#properties-2)
