### ISSUE TITLE
"weekday" notification not working with version "0.8.4"

### ISSUE THREAD

**Issue by rushabhmakwana-multidots** [katzer/cordova-plugin-local-notifications#1706]
I am developing an application in which I need to send a local notification to the user for reminding the daily training at 3 PM on the weekdays only. For that my demo code to schedule a notification is below.
   var date = new Date();
   date.setDate(date.getDate());
   date.setHours(15);
   date.setMinutes(0);
   date.setSeconds(0);

   $cordovaLocalNotification.schedule({
        id: 1,
        title: 'Daily Training Reminder',
        at: date,
        every: 'weekday'
      }).then(function (result) {
        // ...
      });

But it is not working. Please help.
Thanks in advance.

**Comment by rwillett** [comment]
The template is there for a reason. We have no idea what you are doing, what OS you are running, how you havwe set anything up. Use the template

**Comment by rushabhmakwana** [comment]
@rwillett Thanks for your reply. I am using this plugin version(0.8.4) in my ionic(ionic1) project for sending a reminder notification to the user. 
For the sending notification on every day, I have schedule notification like below:

    var date = new Date();
    date.setDate(date.getDate());
    date.setHours(15);
    date.setMinutes(0);
    date.setSeconds(0);

   $cordovaLocalNotification.schedule({
     id: 1,
    title: 'Daily Training Reminder',
    at: date,
    every: 'day'
   }).then(function (result) {
   });

The above lines working fine with daily notification. But now I want to send a notification to user that reminds user only on 'weekday' and for that, I have set notification like below:

   var date = new Date();
   date.setDate(date.getDate());
   date.setHours(15);
   date.setMinutes(0);
   date.setSeconds(0);

   $cordovaLocalNotification.schedule({
     id: 1,
     title: 'Daily Training Reminder',
     at: date,
     every: 'weekday'
   }).then(function (result) {
   });
 
But it is not working for weekday. Below is an output of "ionic info" command:
------------------------------------------------------------------------------------
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : android 6.3.0 ios 4.5.5
    Ionic Framework   : ionic1 1.3.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 5.0.13 
    Node              : v7.3.0
    npm               : 3.10.10 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145 

Hope you will get some idea from this.

**Comment by rwillett** [comment]
The template is there to provide useful information. 

For example we still have if you are using IOS or Android, could be either. They have different systems and different bugs. We have no idea what else you have tried. e.g. Why are you using 0.8.4 if you are using IOS, or even Android. 

Where did you get that plugin from?  That looks like its come from the Ionic people or similar. It doesn't appear to have come from here. 

What else works? Can you send a single notification? How have you initiated the plugin?  Have you waited for device ready? It may well be that the code combination is wrong. the use of ```every:``` is very, very flaky and normally doesn't work. We do not use it.

Suggest you go back, read your code, look at what other issues look like yours, write a tiny app that does work so you know the code is installed correctly on whatever target OS you use and then come back and complete the template properly.

Rob

**Comment by rushabhmakwana** [comment]
@rwillett Could you please tell me that how can I set the repeated local notification for every weekday(Monday, Tuesday, Wednesday Thursday, Friday) at a specific time using this plugin?

**Comment by rushabhmakwana** [comment]
@rwillett Could you please tell me that how can I set the repeated local notification for every weekday(Monday, Tuesday, Wednesday Thursday, Friday) at a specific time using this plugin?

**Comment by marcovtwout** [comment]
Version 0.8 is not maintained anymore, you should update to 0.9 and close this issue.

**Comment by marcovtwout** [comment]
@Gami-404 See https://github.com/katzer/cordova-plugin-local-notifications#properties-2 property "match"
