### ISSUE TITLE
notifications clear when app close (android)

### ISSUE THREAD

**Issue by AhmedRaafat13** [katzer/cordova-plugin-local-notifications#1710]
notifications clear when app close

Plugin version: 0.9.0-beta.3
Platform: Android
OS version: 5.0.2
Device manufacturer / model: tecno
Cordova version (cordova -v): 7.1.0
Cordova platform version (cordova platform ls): 6.3.0* Plugin config
Expected Behavior
LocalNotification should be not be cleared when app closed or killed

Tell us what happens instead

Loacl notification works when app open or in background
but i close it all my app Loacl notifications is cleared

**Comment by AhmedRaafat13** [comment]
please answer me

**Comment by lokkeshjaya** [comment]
This behavior might be seen when you use local notification plugin in combination with phonegap-push plugin. phonegap-plugin-push by default clear all pending notifications when the app go in pause. To fix this behavior, just set the clearNotifications to "false":

`var push = PushNotification.init({ android: { clearNotifications:"false" } });`
