### ISSUE TITLE
Daily Reminder is not working after update

### ISSUE THREAD

**Issue by hypesol** [katzer/cordova-plugin-local-notifications#1712]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version:
* Device manufacturer / model:
* Cordova version (```cordova -v```): 8.1.2
* Cordova platform version (```cordova platform ls```): 7.1.1

bn = new Date(cd.getFullYear(), cd.getMonth(), date, time.getHours(), time.getMinutes());
			cordova.plugins.notification.local.schedule({
				id: 2,
				title: "Test Title",
				text: "This is a reminder to use the app...",
				at: bn,
				every: every // "minute", "hour", "day", "week", "month", "year"
			});
This is my code which was working fine and notification was prompting daily on the given time.

now I am trying after update this code

trigger: { every: "day",  at: new Date(cd.getFullYear(), cd.getMonth(), date, time.getHours(), time.getMinutes()) }

but this works same day only not repeating every day.

can you please help me what I am doing wrong. why this is not repeating on daily bases. Even i have tried firstAt and also tried trigger with different values.

Thanks

**Comment by avais88786** [comment]
Hi, were you able to fix this?
