### ISSUE TITLE
Cannot set local notification due to "Unknown property: at"

### ISSUE THREAD

**Issue by hnguyen48206** [katzer/cordova-plugin-local-notifications#1717]
Hi, I'm facing an error when trying to set up local notifications in my ionic app. The problem's been described below, any help would be so much appreciated. 

Plugin version: 0.9.0-beta.2
Platform: android
OS version: 7
Device manufacturer / model: Android emulator
Cordova version (cordova -v): 8.0.0
Cordova platform version (cordova platform ls): none
 ionic (Ionic CLI)  : 4.1.0 (C:\Users\HoangN\AppData\Roaming\npm\node_modules\ionic)
 Ionic Framework    : ionic-angular 3.9.2
 @ionic/app-scripts : 3.1.8

Expected Behavior
Set local notification at a specific time by adding "at:" and a Date object

Tell us what happens instead
When running, it failed at "Unknown property: at", I have tried firstAt and the result was still the same. However, when looking at the interface ILocalNotification, I can see both 'at' and 'firstat' has been defined in the file.

**Comment by davec21** [comment]
use:

trigger: {
at: [value]
}

**Comment by hnguyen48206** [comment]
Thanks for your timely response, but have tried 'trigger' too and the keyword wasn't even defined in ILocalNotification, so it can not even pass the build time.
