### ISSUE TITLE
Build Error when using latest Version

### ISSUE THREAD

**Issue by Maj0rrush** [katzer/cordova-plugin-local-notifications#1718]
When i add latest Version i get ShortcutBadger Error

## Your Environment

* Plugin version: @latest
* Platform: Win32 / Cordova / Android build
* OS version: Android 7+
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```):  Android 7.0.0

## Actual Behavior

When i run "cordova run android" i get following build error -> see "debug output @bottom"

I can download the https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom file via browser but not in build process

## Steps to Reproduce

cordova plugin add cordova-plugin-local-notification

cordova run android 

ERROR

## Debug logs

Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve me.leolin:ShortcutBadger:1.1.22.
  Required by:
      project :app
   > Could not resolve me.leolin:ShortcutBadger:1.1.22.
      > Could not get resource 'https://jcenter.bintray.com/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
         > Could not GET 'https://jcenter.bintray.com/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve me.leolin:ShortcutBadger:1.1.22.
      > Could not get resource 'https://maven.google.com/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
         > Could not GET 'https://maven.google.com/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve me.leolin:ShortcutBadger:1.1.22.
      > Could not get resource 'https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve me.leolin:ShortcutBadger:1.1.22.
      > Could not get resource 'https://jcenter.bintray.com/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
         > Could not GET 'https://jcenter.bintray.com/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve me.leolin:ShortcutBadger:1.1.22.
      > Could not get resource 'https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve me.leolin:ShortcutBadger:1.1.22.
      > Could not get resource 'https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve me.leolin:ShortcutBadger:1.1.22.
      > Could not get resource 'https://jcenter.bintray.com/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
         > Could not GET 'https://jcenter.bintray.com/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve me.leolin:ShortcutBadger:1.1.22.
      > Could not get resource 'https://maven.google.com/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
         > Could not GET 'https://maven.google.com/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by scorring** [comment]
Same problem here
