### ISSUE TITLE
Notification not peeking onto the current screen

### ISSUE THREAD

**Issue by lsxBread** [katzer/cordova-plugin-local-notifications#1720]
## The Environment

I am using React + Cordova for developing. After building the production code into 'www' folder, I run 'cordova build ios' for iOS platform. 

* Plugin version: 0.9.0-beta.2
* Platform: Cordova / iOS build
* OS version: iOS 10 / 11 / 12
* Device manufacturer / model: 
* Cordova version : 8.1.2
* Cordova platform version: iOS4.5.5

## Actual Behavior

After installing the App in real device or simulator first time, I click one button to active the local notification, the code is:
```javascript
cordova.plugins.notification.local.schedule({
      id: 1,
      title: 'Testing',
      text: 'Hello world',
      sound: 'file://media/beep.caf'
    })
```
After giving permission, the sound of notification is played, but the notification does not peek onto the current screen or show up in notification center.

However, if I quit the App and clear the cache, and then restart the App,  the notification works well every time I click the button

**Comment by DonsWayo** [comment]
I have the same, when you open the first time, the notifications not work, when you close the app and reopen works always... Any ideas?

**Comment by lsxBread** [comment]
> I have the same, when you open the first time, the notifications not work, when you close the app and reopen works always... Any ideas?

I found a solution that you can set 'foreground: true':
```javascript
cordova.plugins.notification.local.schedule({
      id: 1,
      title: 'Testing',
      text: 'Hello world',
      foreground: true,
      sound: 'file://media/beep.caf'
    })
```
It works well in iOS11+. But for iOS10, the same issue happens

**Comment by DonsWayo** [comment]
> > I have the same, when you open the first time, the notifications not work, when you close the app and reopen works always... Any ideas?
> 
> I found a solution that you can set 'foreground: true':
> 
> ```js
> cordova.plugins.notification.local.schedule({
>       id: 1,
>       title: 'Testing',
>       text: 'Hello world',
>       foreground: true,
>       sound: 'file://media/beep.caf'
>     })
> ```
> 
> It works well in iOS11+. But for iOS10, the same issue happens

For me works well with foreground to true on all iOS versions.

**Comment by lsxBread** [comment]
> > > I have the same, when you open the first time, the notifications not work, when you close the app and reopen works always... Any ideas?
> > 
> > 
> > I found a solution that you can set 'foreground: true':
> > ```js
> > cordova.plugins.notification.local.schedule({
> >       id: 1,
> >       title: 'Testing',
> >       text: 'Hello world',
> >       foreground: true,
> >       sound: 'file://media/beep.caf'
> >     })
> > ```
> > 
> > 
> > It works well in iOS11+. But for iOS10, the same issue happens
> 
> For me works well with foreground to true on all iOS versions.

It's weird. Do you use webpack + babel to compile the code? I am not sure if it is the cause
