### ISSUE TITLE
Handling Inline Reply Value

### ISSUE THREAD

**Issue by kenlie321** [katzer/cordova-plugin-local-notifications#1723]
Hello there. I'm trying to get the value from the inline reply field from the notification. If i do a console log on the event that was fired it only returned the normal Properties of the notification without the reply value. Any insight will be helpful! Thanks

## Your Environment

* Plugin version:0.9
* Platform:Android
* OS version:7
* Device manufacturer / model: Xiaomi 4s
* Cordova version (```cordova -v```):6.4
* Cordova platform version (```cordova platform ls```):6.4
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

The console log should reveal the reply value.

## Actual Behavior

console log only shows properties of the notification without the value

## Context

Obtain reply value of the inline reply.

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by WilliWespe** [comment]
I have the same problem, did you solve it?
