### ISSUE TITLE
Question: Is it possible to play sound that is not inside app bundle on IOS?

### ISSUE THREAD

**Issue by SergeyBazhanov** [katzer/cordova-plugin-local-notifications#1724]
Is it possible to play sound that is not inside app bundle on IOS?

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Mac OS
* OS version: 10.14
* Device manufacturer / model: All apple devices
* Cordova version: 8.1.2
* Cordova platform version: android 7.1.2, ios 4.5.5
* Plugin config
* Ionic Version (if using Ionic): 3

## Expected Behavior

If i set sound to file inside <my_app_container>/Library/Sounds/ folder - sound have to be played

## Actual Behavior

Default notification sound is played

## Context

Thank you for this great plugin. I want to play notification sounds that were previously downloaded from external storage. In the documentation for native UNNotificationSound:soundNamed method it says:

> The name of a sound file to be played for the notification. The sound file must be contained in the app’s bundle or in the Library/Sounds folder of the app’s data container. If files exist in both locations then the file in the app’s data container will be preferred.

Is there any way to make it work with this plugin?
Thanks

**Comment by edento** [comment]
Yes, I have done this the following:
```
   const options = {
      // more options here
      sound: 'file://assets/sound/siren.mp3',
   };
   this.nativeNotification.local.schedule(options);
```

When `siren.mp3` is located at `src/assets/sound`.

Tested on iOS 12.3.1 and the sound is working.
