### ISSUE TITLE
How to change Default channel name?

### ISSUE THREAD

**Issue by BobSadan** [katzer/cordova-plugin-local-notifications#1725]
Hi, I find a issue that is 'Default channel' name for Android when I use this plugin, i want to try it to be myself define name, but don't search  the methods or param settings about notification channel. Anyone know this issue? please help me ,Thanks!

**Comment by Steffaan** [comment]
Use my [fork](https://github.com/Steffaan/cordova-plugin-local-notifications) and declare a property called `channelDescription` along with the `channel` property (optional).

**Comment by BobLisa** [comment]
Hi, Stefan:
Thanks very much! i will try to your branch plugin.
****************************************
Bob Liu
ShangHai China







Use my fork and declare a property called channelDescription along with the channel property (optional).
