### ISSUE TITLE
Plugin still maintained?

### ISSUE THREAD

**Issue by JiiB** [katzer/cordova-plugin-local-notifications#1728]
Is this plugin still maintained or is there a maintained fork of it? Since the last commit was made in february 2018

**Comment by Simpler1** [comment]
This hasn't been maintained for a long time.  It's a shame since it used to work well, but with the latest Android versions there is no reliable way to create daily notifications.

**Comment by Steffaan** [comment]
@JiiB 

Since the plugin isn't updated anymore I forked it [here](https://github.com/Steffaan/cordova-plugin-local-notifications)

Feel free to use my fork and let me know if there are any issues / bugs.

**Comment by JiiB** [comment]
@Steffaan Thanks, I'll try it out as soon as I find time. 👍

**Comment by katzer** [comment]
I'll work on it in the near term. Even it might look unsupported from time to time, but its not...

**Comment by katzer** [comment]
@Steffaan I am open to add maintainers who can take care of the repo next to me.

**Comment by akash-joshi** [comment]
@katzer I can help. I am using this extension extensively and have built lots of stuff on JS

**Comment by Steffaan** [comment]
> @Steffaan I am open to add maintainers who can take care of the repo next to me.

That's good news 👍 I'm in..

**Comment by SveinErik** [comment]
This sounds promising. I just switched to @Steffaan fork, and it's working good so far in my testing. But will you now abandom your fork, and implement all the changes into @katzer's main repository?

**Comment by Steffaan** [comment]
@SveinErik 

I won't for now.. so feel free to use it and let me know if there are any issues.

**Comment by SveinErik** [comment]
@Steffaan 
Thanks for the feedback, good to know :) 
And thank you very much for the time and effort on maintaining this plugin!
