### ISSUE TITLE
Local notification sound not playing when iPhone muted

### ISSUE THREAD

**Issue by dmoczydlowski** [katzer/cordova-plugin-local-notifications#1733]
General summary of the issue:
When notification with sound is triggered while iphone is muted, it's not playing.  

* Plugin version: Newest
* Platform: iOS
* OS version: 12
* Ionic Version (if using Ionic): 3.19

## Expected Behavior

Sound should be played. 

## Actual Behavior

Sound is not played.

## Steps to Reproduce
1. Schedule notification with sound
2. Mute iPhone
3. Notification sound is not played.

**Comment by rocco** [comment]
why should a sound play when phone is on mute? i would expect it to stay silent.

**Comment by dmoczydlowski** [comment]
Because I’m using it for alarm clock app - it’s the only way to do that.

**Comment by rocco** [comment]
you didn't mention if the app has gone into background or if phone is on standby at the time of the alarm. in both cases i'm certain apple won't approve playing a sound when silent mode is active - only the internal alarm clock can do that.

**Comment by dmoczydlowski** [comment]
I saw few apps like with such functionality available on the App Store,
like “bedr radio” so I guess it’s possible
