### ISSUE TITLE
Ionic Local Notification Sunday

### ISSUE THREAD

**Issue by evripidesk** [katzer/cordova-plugin-local-notifications#1735]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: iOS
* OS version: 12
* Device manufacturer / model: iphone xs max
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)3.20.0

## Expected Behavior

I am trying to schedule weekly notification from datepicker, everything work fine except if user choose Sunday as the day to schedule notification, the Sunday is the 0 day and I get that schedule at null

## Actual Behavior

when the weekday is 0, just I get trigger at null

        `let today = new Date(this.data.date);
          let hour = today.getUTCHours();
          let minutes = today.getMinutes();
          this.weekly = today.getDay();

          this.id = res.insertId;
          db.executeSql("UPDATE payments SET reminder = ? WHERE rowid = ?",[this.id,this.rowid])

          this.localNotifications.schedule({
            id: this.id,
            text: 'Weekly Reminder for '+ this.data.description+ ' '+ 'Amount: €' + this.data.amount,
            every: {  count: 1,  weekday: this.weekly, hour: hour, minute: minutes, second: 1  },
            data: {"id":  this.id, "name": "Mr.A"},
            foreground: true,  

         });`

**Comment by evripidesk** [comment]
also how can I schedule a notification for daily base and start from a specific date>? Itry the firstAt but now working

**Comment by evripidesk** [comment]
if the today.getDay(); is Sunday then I get for Sunday 0, so 0 Sunday, 1 Monday.....6 Saturday, the plugin doesnt understand the 0 so I have to convert the 0 to 7

**Comment by tigran88** [comment]
thank you, but for me 7 not working too
