### ISSUE TITLE
Crash on iPhone 5s

### ISSUE THREAD

**Issue by pta03996** [katzer/cordova-plugin-local-notifications#174]
I'm using the latest plugin version on my project.
It works fine on iPhone Retina(64 bit) emulator and the others but it crashes when i'm trying to trigger the notification on iPhone 5s.
The device stop and Xcode highlight on 
"- (void) add:(CDVInvokedUrlCommand*)command"
in APPLocalNotification.m

i use phonegap version 3.4.0-0.19.7, Xcode 5.1

**Comment by sgentile** [comment]
Crashes on iphone5 only - to close because you don't have an iphone5 ???  All my iphone5 users are reporting crashing.

**Comment by sgentile** [comment]
I've confirmed it on iPhone 5/5s running ios7
