### ISSUE TITLE
Disabling Vibration (Android) not working

### ISSUE THREAD

**Issue by Sh1n1x** [katzer/cordova-plugin-local-notifications#1741]
Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: Android
* OS version: Tested on 9.0 and 8.1
* Device manufacturer / model: HUAWEI P20, MI A2 Lite
* Cordova version (```cordova -v```): 8.1.2
* Cordova platform version (```cordova platform ls```): android 7.1.4
* Plugin config
* Ionic Version (if using Ionic) CLI 4.7.1

## Expected Behavior

`vibrate: false` param not working on Android.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. I've created an app with Ionic 4 (beta)
  2. I've added a timer
  3. This timer update a notification every seconds

## Context

```
this.localNotifications.schedule({
	id: 1,
	title: 'Cuisson en cours',
	vibrate: false,
	sound: null,
	progressBar: {value: 0},
	lockscreen: true,
	wakeup: false,
	priority: -2,
	foreground: true
});
this.x = setInterval(() =>{
	this.localNotifications.update({
		id: 1,
		title: 'Il reste encore '+minutes+':'+seconds+' de cuisson.',
		progressBar: {value: percent },
	});
}, 1000);
```

**Comment by matteobombardi** [comment]
same here

**Comment by maikal-qitplus** [comment]
Same issue with my S8 plus and 0.9.0 - beta 2

**Comment by mfsoftworks** [comment]
Also happening with LG G6, plugin 0.9.0-beta2, notification config:
```json
{
        id: id,
        smallIcon: "res://img/logo.png",
        title: filename,
        text: `Downloading`,
        progressBar: {value: 0},
        actions: [
            {id: 'cancel', title: 'Cancel'}
        ],
        foreground: true,
        color: "black",
        vibrate: false,
        sound: false,
        sticky: true
    }
```

**Comment by Steffaan** [comment]
Try this version: https://github.com/Steffaan/cordova-plugin-local-notifications

**Comment by pedropamn** [comment]
Same here....

**Comment by pedropamn** [comment]
@Steffaan , I try your fork with `vibrate: false` and still vibrating... (Android 8.0)
