### ISSUE TITLE
Send notification with action when app is killed not working

### ISSUE THREAD

**Issue by Missile71** [katzer/cordova-plugin-local-notifications#1744]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: Android
* OS version: 6
* Device manufacturer / model: Nexus 5
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): android 7.0.0
* Plugin config
* Ionic Version (if using Ionic) ionic 3.9.2 CLI 4.7.1

## Expected Behavior

If App is killed the local notification with action has to be shown wth action buttons

## Actual Behavior

If App is killed the local notification has been shown, but with no action

## Steps to Reproduce

simply create a notification with action and kill the app

## Context

send a notification with action where the app is killed, when the app is foregroung works fine

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by moshi100** [comment]
+1

**Comment by ghonche-yqr** [comment]
any solution on this? @Missile71
