### ISSUE TITLE
Not all notifications are added (Android, maybe iOS)

### ISSUE THREAD

**Issue by Istenes** [katzer/cordova-plugin-local-notifications#175]
Hello,
We have a loop where we add 20 local notifications, but when looking in the preferences file on Android there seems like its always a random number of notifications scheduled.

Is the add method asynchronous? Making another add method just after another break the schedule?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
