### ISSUE TITLE
Can i not trigger a notification on a fixed date, hour minute and second?

### ISSUE THREAD

**Issue by CreativeArtDesign** [katzer/cordova-plugin-local-notifications#1750]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Can i not trigger a notification on a fixed date and hour min and second?

## Your Environment

* Plugin version: Ionic 4 and standars installation not beta.
* Platform: Android / IOS
* OS version: OSX Mojave
* Device manufacturer / model: emulator / Nokia 6 plus
* Cordova version (```cordova -v```): latest
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)
IONIC v4
## Expected Behavior

_Tell us what should happen_
A trigger when i set a date and time like example this:
5 februari 14:00:05
Will trigger like an alarm set.

## Actual Behavior
NO TRIGGER, not trigged on exactly second

## Steps to Reproduce

Example: februari 11 at 04:04:00 will trigger the alarm)
trigger: {at: month:2, day:11, hour:4, minute:4, second:0 },

## Context

Trigger a alarm on exactly that date and time, time in second.
 februari 11 at 04:04:00 will trigger the alarm

## Debug logs

?

  * ios XCode logs
  * Android: $ adb logcat

**Comment by CreativeArtDesign** [comment]
Other: I have some problem to get the click to work if i press Yes or No action....

**Comment by Tawpie** [comment]
Keep in mind that Android will not trigger the notification "on the second", or even on the minute. Expect at least several seconds delay—it's the operating system that causes this. There is supposed to be a way to force Android to trigger a notification accurately but this plugin doesn't use that technique.

Nevertheless I would try

```
var myDate = new Date(2019, 1,11, 4, 4, 0);  // create a date object fo the 'trigger' 'at'
var arrayOfNotifications = [{
        id: 1,
        trigger: { at: myDate }, // MUST be a date object
        text: The body text of the message,
        title: The title text of the message
      }];
cordova.plugins.notification.local.schedule(arrayOfNotifications);
```

Why use an array? Scheduling a notification is an asynchronous action performed by the OS and if you're trying to schedule more than 1 notification at a time using the array form allows the OS to complete each individual scheduling action before the next one starts.

**Comment by CreativeArtDesign** [comment]
Tried this but did not activate any notification?
import { Component } from '@angular/core';import { LocalNotifications } from '@ionic-native/local-notifications/ngx';import { Storage } from '@ionic/storage';import { NavController, AlertController, Platform } from '@ionic/angular';import { ToastController } from '@ionic/angular';
@Component({  selector: 'app-home',  templateUrl: 'home.page.html',  styleUrls: ['home.page.scss'],})
export class HomePage {  constructor(    public navController: NavController,    public navCtrl: NavController,    private plt: Platform,    private localNotifications: LocalNotifications,    private alertController: AlertController,    private toastController: ToastController) {


      this.localNotifications.on('trigger').subscribe(notification => {          this.presentToast();      });      this.localNotifications.on('yes').subscribe(notification => {          this.presentAlert(notification.data.meetingId);      });      this.localNotifications.on('no').subscribe(notification => {          this.presentAlert(notification.data.meetingId);      });    }

// TRIGGER  async presentToast() {    const toast = await this.toastController.create({      message: 'Athan spelas upp!',      duration: 2000    });    toast.present();  }

  async presentAlert(test) {    const alert = await this.alertController.create({      header: 'Alert',      subHeader: 'Subtitle',      message: test,      buttons: ['OK']    });
    await alert.present();  }


// On load or every check!  scheduleNotification() {
    var myDate = new Date(2019,2,12,8,35,0);  // create a date object fo the 'trigger' 'at'    var arrayOfNotifications = [{        id: 1,        trigger: { at: myDate }, // MUST be a date object        text: 'Abdelbaset Athan spela upp.',        title: 'Spela upp Athan',        data: { meetingId:"Athan - 1" },        foreground: true,        sound: 'content://assets/sms.mp3',        actions: [          { id: 'yes', title: 'Ok, fortsätt lyssna!' },          { id: 'no',  title: 'Stopa Athan' }        ]      }];      this.localNotifications.schedule(arrayOfNotifications);
    // this.localNotifications.schedule({    //       id: 1,    //       led: { color: '#FF00FF', on: 500, off: 500 },    //       title: 'Spela upp Athan - 1',    //       foreground: true,    //       text: 'Abdelbaset Athan spela upp.',    //       trigger: {at: new Date(new Date().getTime() + 3000)},    //       data: { meetingId:"Athan - 1" },    //       sound: 'content://assets/sms.mp3',    //       actions: [    //         { id: 'yes', title: 'Ok, fortsätt lyssna!' },    //         { id: 'no',  title: 'Stopa Athan' }    //       ]    //   });  }

}


    Den måndag 11 februari 2019 18:52:20 EET, Tawpie <notifications@github.com> skrev:  
 
 
Keep in mind that Android will not trigger the notification "on the second", or even on the minute. Expect at least several seconds delay—it's the operating system that causes this. There is supposed to be a way to force Android to trigger a notification accurately but this plugin doesn't use that technique.

Nevertheless I would try
var myDate = new Date(2019, 1,11, 4, 4, 0);  // create a date object fo the 'trigger' 'at'
var arrayOfNotifications = [{
        id: 1,
        trigger: { at: myDate }, // MUST be a date object
        text: The body text of the message,
        title: The title text of the message
      }];
cordova.plugins.notification.local.schedule(arrayOfNotifications);

Why use an array? Scheduling a notification is an asynchronous action performed by the OS and if you're trying to schedule more than 1 notification at a time using the array form allows the OS to complete each individual scheduling action before the next one starts.

**Comment by CreativeArtDesign** [comment]
Hi, when i remove the code for action buttons in my scheduler and put it outside as you told me the foreground get to work. But the action buttons does not work no buttons.
Seems there is a issue here.?


// On load or every check!  scheduleNotification() {    this.localNotifications.addActions('yes-no', [        { id: 'yes', title: 'Yes' },        { id: 'no',  title: 'No'  }    ]);
    var myDate = new Date(2019,2,12,8,35,0);  // create a date object fo the 'trigger' 'at'    var arrayOfNotifications = [{        id: 1,        foreground: true,        trigger: { at: new Date(new Date().getTime() + 3000) }, // MUST be a date object        text: 'Abdelbaset Athan spela upp.',        title: 'Spela upp Athan',        data: { meetingId:"Athan - 1" },        sound: 'content://assets/sms.mp3',        actions: 'yes-no'      }];      this.localNotifications.schedule(arrayOfNotifications);
    // this.localNotifications.schedule({    //       id: 1,    //       led: { color: '#FF00FF', on: 500, off: 500 },    //       title: 'Spela upp Athan - 1',    //       foreground: true,    //       text: 'Abdelbaset Athan spela upp.',    //       trigger: {at: new Date(new Date().getTime() + 3000)},    //       data: { meetingId:"Athan - 1" },    //       sound: 'content://assets/sms.mp3',    //       actions: [    //         { id: 'yes', title: 'Ok, fortsätt lyssna!' },    //         { id: 'no',  title: 'Stopa Athan' }    //       ]    //   });  }


    Den måndag 11 februari 2019 18:52:20 EET, Tawpie <notifications@github.com> skrev:  
 
 
Keep in mind that Android will not trigger the notification "on the second", or even on the minute. Expect at least several seconds delay—it's the operating system that causes this. There is supposed to be a way to force Android to trigger a notification accurately but this plugin doesn't use that technique.

Nevertheless I would try
var myDate = new Date(2019, 1,11, 4, 4, 0);  // create a date object fo the 'trigger' 'at'
var arrayOfNotifications = [{
        id: 1,
        trigger: { at: myDate }, // MUST be a date object
        text: The body text of the message,
        title: The title text of the message
      }];
cordova.plugins.notification.local.schedule(arrayOfNotifications);

Why use an array? Scheduling a notification is an asynchronous action performed by the OS and if you're trying to schedule more than 1 notification at a time using the array form allows the OS to complete each individual scheduling action before the next one starts.

**Comment by CreativeArtDesign** [comment]
Hi again i found the problem with the date, it is working i missunderstand the month it begin with january as 0 not 1.

So this is clear now and working but still i have 
Sound and Button problem addAction does not work for me this is my latest code:
import { Component } from '@angular/core';import { LocalNotifications } from '@ionic-native/local-notifications/ngx';import { Storage } from '@ionic/storage';import { NavController, AlertController, Platform } from '@ionic/angular';import { ToastController } from '@ionic/angular';
@Component({  selector: 'app-home',  templateUrl: 'home.page.html',  styleUrls: ['home.page.scss'],})
export class HomePage {  constructor(    public navController: NavController,    public navCtrl: NavController,    private platform: Platform,    private localNotifications: LocalNotifications,    private alertController: AlertController,    private toastController: ToastController) {


      this.localNotifications.on('trigger').subscribe(notification => {          this.presentToast();      });      this.localNotifications.on('yes').subscribe(notification => {          this.presentAlert(notification.data.meetingId);      });      this.localNotifications.on('no').subscribe(notification => {          this.presentAlert(notification.data.meetingId);      });    }

// TRIGGER  async presentToast() {    const toast = await this.toastController.create({      message: 'Athan spelas upp!',      duration: 2000    });    toast.present();  }
  async presentAlert(test) {    const alert = await this.alertController.create({      header: 'Alert',      subHeader: 'Subtitle',      message: test,      buttons: ['OK']    });
    await alert.present();  }


// On load or every check!  scheduleNotification() {    var myDate = new Date(2019, 1, 12, 9, 4, 5, 0);  // create a date object fo the 'trigger' 'at'    var arrayOfNotifications = [{        id: 1,        foreground: true,        trigger: { at: myDate }, // MUST be a date object        text: 'Abdelbaset Athan spela upp.',        title: 'Spela upp Athan',        data: { meetingId:"Athan - 1" },        sound: 'file://assets/sms.mp3',      }];      this.localNotifications.schedule(arrayOfNotifications);
  }

}



THIS IS WITHOUT BUTTONS... but foreground works but would like to have thees buttons to work because it the notification come up i would like to stop the alarm, snooze or turn it off. Thats why i need the trigger on yes or no or other. 

cordova.plugins.notification.local.addActions('yes-no', [
    { id: 'yes', title: 'Yes' },
    { id: 'no',  title: 'No'  }
]);I tried to put it in scheduleNotification() method but no buttons or sound are working.

Any ide?    Den måndag 11 februari 2019 18:52:20 EET, Tawpie <notifications@github.com> skrev:  
 
 
Keep in mind that Android will not trigger the notification "on the second", or even on the minute. Expect at least several seconds delay—it's the operating system that causes this. There is supposed to be a way to force Android to trigger a notification accurately but this plugin doesn't use that technique.

Nevertheless I would try
var myDate = new Date(2019, 1,11, 4, 4, 0);  // create a date object fo the 'trigger' 'at'
var arrayOfNotifications = [{
        id: 1,
        trigger: { at: myDate }, // MUST be a date object
        text: The body text of the message,
        title: The title text of the message
      }];
cordova.plugins.notification.local.schedule(arrayOfNotifications);

Why use an array? Scheduling a notification is an asynchronous action performed by the OS and if you're trying to schedule more than 1 notification at a time using the array form allows the OS to complete each individual scheduling action before the next one starts.

**Comment by CreativeArtDesign** [comment]
Hi again i found the problem with the date, it is working i missunderstand the month it begin with january as 0 not 1.

So this is clear now and working but still i have 
Sound and Button problem addAction does not work for me this is my latest code:
```
import { Component } from '@angular/core';
import { LocalNotifications } from '@ionic-native/local-notifications/ngx';
import { Storage } from '@ionic/storage';
import { NavController, AlertController, Platform } from '@ionic/angular';
import { ToastController } from '@ionic/angular';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})

export class HomePage {
  constructor(
    public navController: NavController,
    public navCtrl: NavController,
    private platform: Platform,
    private localNotifications: LocalNotifications,
    private alertController: AlertController,
    private toastController: ToastController) {



      this.localNotifications.on('trigger').subscribe(notification => {
          this.presentToast();
      });
      this.localNotifications.on('yes').subscribe(notification => {
          this.presentAlert(notification.data.meetingId);
      });
      this.localNotifications.on('no').subscribe(notification => {
          this.presentAlert(notification.data.meetingId);
      });
    }


// TRIGGER
  async presentToast() {
    const toast = await this.toastController.create({
      message: 'Athan spelas upp!',
      duration: 2000
    });
    toast.present();
  }

  async presentAlert(test) {
    const alert = await this.alertController.create({
      header: 'Alert',
      subHeader: 'Subtitle',
      message: test,
      buttons: ['OK']
    });

    await alert.present();
  }



// On load or every check!
  scheduleNotification() {
    var myDate = new Date(2019, 1, 12, 9, 4, 5, 0);  // create a date object fo the 'trigger' 'at'
    var arrayOfNotifications = [{
        id: 1,
        foreground: true,
        trigger: { at: myDate }, // MUST be a date object
        text: 'Abdelbaset Athan spela upp.',
        title: 'Spela upp Athan',
        data: { meetingId:"Athan - 1" },
        sound: 'file://assets/sms.mp3',
      }];
      this.localNotifications.schedule(arrayOfNotifications);

  }


}


```
THIS IS WITHOUT BUTTONS... but foreground works but would like to have thees buttons to work because it the notification come up i would like to stop the alarm, snooze or turn it off. Thats why i need the trigger on yes or no or other. 

```
this.localNotifications.addActions('yes-no', [
    { id: 'yes', title: 'Yes' },
    { id: 'no',  title: 'No'  }
]);I tried to put it in scheduleNotification() method but no buttons or sound are working.

```

And put the actions in scheduler: 

`actions: 'yes-no',`

Any ide?    Den måndag 11 februari 2019 18:52:20 EET, Tawpie <notifications@github.com> skrev:  
 
 
Keep in mind that Android will not trigger the notification "on the second", or even on the minute. Expect at least several seconds delay—it's the operating system that causes this. There is supposed to be a way to force Android to trigger a notification accurately but this plugin doesn't use that technique.

Nevertheless I would try
var myDate = new Date(2019, 1,11, 4, 4, 0);  // create a date object fo the 'trigger' 'at'
var arrayOfNotifications = [{
        id: 1,
        trigger: { at: myDate }, // MUST be a date object
        text: The body text of the message,
        title: The title text of the message
      }];
cordova.plugins.notification.local.schedule(arrayOfNotifications);

Why use an array? Scheduling a notification is an asynchronous action performed by the OS and if you're trying to schedule more than 1 notification at a time using the array form allows the OS to complete each individual scheduling action before the next one starts.

**Comment by CreativeArtDesign** [comment]
Update code.

```
import { Component } from '@angular/core';
import { LocalNotifications } from '@ionic-native/local-notifications/ngx';
import { Storage } from '@ionic/storage';
import { NavController, AlertController, Platform } from '@ionic/angular';
import { ToastController } from '@ionic/angular';


@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})

export class HomePage {
  constructor(
    public navController: NavController,
    public navCtrl: NavController,
    private platform: Platform,
    private localNotifications: LocalNotifications,
    private alertController: AlertController,
    private toastController: ToastController) {


    this.platform.ready().then(() => {
      console.log("PLATFORM READY IN PROVIDER")
        this.localNotifications.on('trigger').subscribe(notification => {
            this.presentToast();
        });
        this.localNotifications.on('yes').subscribe(notification => {
            this.presentAlert(notification.data.meetingId);
        });
        this.localNotifications.on('no').subscribe(notification => {
            this.presentAlert(notification.data.meetingId);
        });
    })

}


// TRIGGER
  async presentToast() {
    const toast = await this.toastController.create({
      message: 'Athan spelas upp!',
      duration: 2000
    });
    toast.present();
  }

  async presentAlert(test) {
    const alert = await this.alertController.create({
      header: 'Alert',
      subHeader: 'Subtitle',
      message: test,
      buttons: ['OK']
    });

    await alert.present();
  }



// On load or every check!
  scheduleNotification() {

    this.platform.ready().then(() => {

    this.localNotifications.addActions('click', [
        { id: 'yes', title: 'Yes' },
        { id: 'no',  title: 'No'  }
    ]);

    // var myDate = new Date(2019, 1, 12, 9, 31, 15, 0);  // create a date object fo the 'trigger' 'at'
    var myDate = new Date(new Date().getTime() + 3000);  // create a date object fo the 'trigger' 'at'
    var arrayOfNotifications = [{
        id: 1,
        foreground: true,
        trigger: { at: myDate }, // MUST be a date object
        text: 'Abdelbaset Athan spela upp.',
        title: 'Spela upp Athan',
        data: { meetingId:"Athan utförd" },
        sound: 'file://assets/tone_nokia.mp3',
        actions: 'click',
      }];
    this.localNotifications.schedule(arrayOfNotifications);
    })
  }


}
```
