### ISSUE TITLE
automatic app launch

### ISSUE THREAD

**Issue by suhail339** [katzer/cordova-plugin-local-notifications#1755]
can i launch application from background as soon as i receive notification?

**Comment by Tawpie** [comment]
Your app cannot make itself the foreground app on iOS, and likewise probably cannot become foreground on Android either. I am pretty certain the OS vendors believe it would be a bad user experience if another app launched while the user was doing something else. Imagine you're composing an amazing Insta and another app took over your screen... or if your phone woke itself up from sleep with a random app running.

On Android your app can do things in the _background_ when it receives a notification.

**Comment by suhail339** [comment]
I have used this plugin instead of developing one for my own, taken https://github.com/markeeftb/cordova-bring-to-front

**Comment by eeerrrttty** [comment]
How is it possible to use cordova bring to front with this plugin to bring app to front when receiving a notification ???
