### ISSUE TITLE
Tapping on notification when the ios app is closed has no parameters

### ISSUE THREAD

**Issue by CesarBalzer** [katzer/cordova-plugin-local-notifications#1756]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: IOS
* OS version: 9.3.5
* Device manufacturer / model: Iphone 4/ IPad 2 -Real device
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): Android 7.1.4 / IOS 4.5.5
* Plugin config 
* Ionic Version (if using Ionic) - no

## Expected Behavior

Get the parameters of the "data" field sent by Firebase when the application is not running (user closed application) when the user touches the notification

## Actual Behavior

when you tap the notification, the console has no action on the parameter, it only opens the application.

## Steps to Reproduce

Create a new cordova application, and install the plugin with the firebase configuration files, run app and closed application after.

## Context

When the app is closed, I get the notification, when I tap the notification, the application opens, but the parameters I sent from the "data" field do not exist, I can not understand the problem if apple does not allow the application to open from notification with parameters, or something is wrong. When the application is open, whether in the background or in the foreground, everything works perfectly.

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by CesarBalzer** [comment]
I did not understand obj c, but following the logic of some sections above in the AppDelegate + FCMPlugin.m file I decided to put the json return `lastPush = jsonData,` now when I click on the notification with the application off (dead), I can get the parameters.

**Comment by ghonche-yqr** [comment]
> I did not understand obj c, but following the logic of some sections above in the AppDelegate + FCMPlugin.m file I decided to put the json return `lastPush = jsonData,` now when I click on the notification with the application off (dead), I can get the parameters.

Can you explain more? where do you define `lastPush` ?
