### ISSUE TITLE
What is the path to where to put the files? (THIS IS A BUG!!!)

### ISSUE THREAD

**Issue by CreativeArtDesign** [katzer/cordova-plugin-local-notifications#1757]
What is the path for the root sound path?
There are no documentation where to put the file?
Please tell us where we should put our mp3 files.

Provide a general summary of the issue.

## Your Environment

* Plugin version: beta 093
* Platform:
* OS version:
* Device manufacturer / model:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Find the path?

## Actual Behavior

Dont find the path

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

file://???

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by CesarBalzer** [comment]
Follow this example, I put the print of the structure and where is the file bell.mp3
   ```
    cordova.plugins.notification.local.schedule({
    title: 'The Big Meeting',
    text: '4:15 - 5:15 PM\nBig Conference Room',
    smallIcon: 'res://mipmap-mdpi/icon.png',
    icon: 'file://img/apple-icon.png',
	sound:'file://sounds/bell.mp3'
});

![captura de tela 2019-02-19 as 23 04 50](https://user-images.githubusercontent.com/13343041/53061013-34af7500-349b-11e9-8d51-611735fc7424.png)

**Comment by CreativeArtDesign** [comment]
Hi, Thank you for your answers but it does not work even the path is right.1. Compiled and signeed the packed and tested it on my phone.2. Path does not work see my path below.3. Does it not allows assets folder? even if it is in right place?

As i mentioned this is my code and paths is following:
var arrayOfNotifications = [{            id: id,            sound: 'file://assets/audio/sms.mp3',            trigger: { at: myDate }, // MUST be a date object            text: type,            title: information,            data: { mydata: 'My hidden message this is' },            actions: [                { id: 'yes', title: 'Yes' },                { id: 'no',  title: 'No' }            ],            foreground: true          }];          this.localNotifications.schedule(arrayOfNotifications);        }



In my project i have following path.
My app---platform
 ---plugins ---resources
 ---scr
 ------app
 ------assets
 ---------audio
----------> sms.mp3
 ---------css
 ---------fonts
 ---------icon
 ---------img
 ---------xml
------environments
------theme---www ------assets
 ---------audio----------> sms.mp3 ---------css
 ---------fonts
 ---------icon
 ---------img
 ---------xml
 ------cordova-js-src
 ------plugins
 ------svg



Are there issues in the path i can not see it..this is beta 093 and ionic 4
    Den onsdag 20 februari 2019 04:09:26 EET, Cesar E. Balzer <notifications@github.com> skrev:  
 
 
Follow this example, I put the print of the structure and where is the file bell.mp3
 cordova.plugins.notification.local.schedule({
 title: 'The Big Meeting',
 text: '4:15 - 5:15 PM\nBig Conference Room',
 smallIcon: 'res://mipmap-mdpi/icon.png',
 icon: 'file://img/apple-icon.png',
 sound:'file://sounds/bell.mp3'
});

![captura de tela 2019-02-19 as 23 04 50](https://user-images.githubusercontent.com/13343041/53061013-34af7500-349b-11e9-8d51-611735fc7424.png)

**Comment by CreativeArtDesign** [comment]
Hi, Thank you for your answers but it does not work even the path is right.1. Compiled and signeed the packed and tested it on my phone.2. Path does not work see my path below.3. Does it not allows assets folder? even if it is in right place?

**As i mentioned this is my code and paths is following:**
```
        var arrayOfNotifications = [{
            id: id,
            sound: 'file://assets/audio/sms.mp3',
            trigger: { at: myDate }, // MUST be a date object
            text: type,
            title: information,
            data: { mydata: 'My hidden message this is' },
            actions: [
                { id: 'yes', title: 'Yes' },
                { id: 'no',  title: 'No' }
            ],
            foreground: true
          }];
          this.localNotifications.schedule(arrayOfNotifications);
        }
```



**In my project i have following path.**
My app
---platform
 ---plugins
---resources
 ---scr
 ------app
 ------assets
 ---------audio
----------> sms.mp3
 ---------css
 ---------fonts
 ---------icon
 ---------img
 ---------xml
------environments
------theme
---www
------assets
---------audio
----------> sms.mp3 
---------css
 ---------fonts
 ---------icon
 ---------img
 ---------xml
 ------cordova-js-src
 ------plugins
 ------svg

**Comment by CreativeArtDesign** [comment]
Hi, If you really want to help me to find the bug as i assure it is, you can download my sample text file it is only a button that trigger a notification.

www.aishacenter.se/noti.zip

This is my Ionic 4 with local notification and audio files.

Best regards

**Comment by CreativeArtDesign** [comment]
Or if you have a working example please send me the sample file so i can test my self. and see what the differences is between my code and your code. Please

**Comment by CreativeArtDesign** [comment]
This is really a BUG, i have tested this code with waves and the path is right what i have used before.

this is the same path and i have test both only the picture working sound not same path.

```
       icon: 'file://assets/icon/favicon.png',
    sound: 'file://assets/icon/sms2.wav'
```

I have put both files in same folder and oly the favicon.png working the sound does not.

So this is 100% a bug in beta 0.9.0 beta 3.

I have tested everything now and are stuck with this BUGG!!

**Comment by CreativeArtDesign** [comment]
Can you please fix this bug???

PLEASE PLEASE PLEASE!!
Or tell me where in the code i should look so i can fix it in my application and give you feedback about it.???

**Comment by blondie63** [comment]
I'm using this code that working fine with beta3:

`setSound() {
    if (this.platform.is('android')) {
      return 'file://assets/sounds/1110.mp3';
    } else {
      return 'file://assets/sounds/1110.caf';
    }
  }

  scheduleNotification() {
    this.localNotifications.schedule({
      id: 1,
      title: 'Attention',
      text: 'Notification after 5 seconds',
      vibrate: true,

      smallIcon: 'res://calendar', // Solo Android ??
      led: { color: '#FF00FF', on: 500, off: 500 }, // Solo Android ??
      data: { mydata: 'My hidden message this is' },
      trigger: { in: 5, unit: ELocalNotificationTriggerUnit.SECOND },
      foreground: false // True = Show the notification while app is open
    });
  }`

**Comment by im-me** [comment]
So is anyone going to fix this or not??

**Comment by blondie63** [comment]
i think this plugin prj is dead :(

**Comment by im-me** [comment]
not good... any other solution how to use custom notification sounds?

**Comment by Tawpie** [comment]
peek at the pull request 1696 that adds channels to Android. Note the comment at the bottom of this particular post https://github.com/katzer/cordova-plugin-local-notifications/pull/1696#issuecomment-434475267 as there appears to be some magic android hand waving that has to be done when you alter the configuration. My guess is: completely delete your app and reinstall.

CAVEAT: I don't use custom sounds so am neither informed or qualified to comment!

**Comment by prabhashibuddhima** [comment]
hi, have you find a solution? I'm facing same
