### ISSUE TITLE
Trigger notification when event time matches with current time

### ISSUE THREAD

**Issue by mohiniMoger** [katzer/cordova-plugin-local-notifications#1758]
I have a set of events in local storage. I want to trigger a notification when current time matches with the event time. could you please help me on it.

EX- I have 10 events in localstorage with date and time. I need to trigger notification when each event matches with current time.

**Comment by Tawpie** [comment]
This is a straightforward task: you'll want to create an array with a notification object for each of your events and then use the .schedule() method to schedule the entire array. Don't schedule them one at a time, that doesn't work.

**Comment by Raagu1993** [comment]
Hi, Thanks,

Controller code - 

$scope.notification = function(){
  cordova.plugins.notification.local.schedule(
     $localStorage.localNotification
);
}

  $localStorage.localNotification is an array which keeps updating. $scope.notification function will execute only when I call from the view and trigger only one notification.

for example : two events 3: AM and 4 :AM in the array. If I call $scope.notification function, notification will generate exactly at 3: AM. Notification will not generate at 4:AM. 
If I want notification at 4: AM I should call $scope.notification finction once again.

Is there any way that notification should generate with respect to time in the array

**Comment by Raagu1993** [comment]
@Tawpie 
could you please help me on this

**Comment by Tawpie** [comment]
This reply is just my experience—I've successfully used the plugin "this way", there are likely other ways!

1) I use the `trigger: { at: dateObject }` technique for scheduling a specific time (not firstAt) although you must be aware that Android does not guarantee that the notification will trigger at the exact time. On Android the notification can arrive late by several seconds. This does limit the number of notifications you can schedule, so firstAt may be a better way for you although I read that people have a difficult time getting firstAt to work properly. Take care with the syntax of firstAt, I don't use it myself but I also don't think your sample code is correct.

2) you will want to have logic that will determine whether to schedule the 3: AM notification or the 4: AM notification—only one can be in the array of objects to be scheduled. You cannot have both in the array of objects to be scheduled, if you do have both in the array, they will both get scheduled

3) when I schedule notifications, I've found it simpler to cancel all notifications and then schedule all notifications again. The plugin has an update capability but I don't use it.

-- so. Make two notification objects, one for 3 and another for 4 AM. You must specify the date as well, so if you want these at 3AM or 4AM every day you have to make an object for each day

```
      // create an array to hold reminder objects that we want to schedule
      let aScheduleTheseReminders = [];

      // build a basic Katzer reminder, one object for each reminder you want to schedule
      let oKatzerLNPluginReminder3AM = {
        id: i + 1,  // an integer
        trigger: { at: $scope.response[i].startTime) }, // MUST be a date object
        text: $scope.response[i]..displaytext,
        title: $scope.response[i]..headline
      };

      // your logic for choosing 3AM or 4AM
      if (I want the 3AM) {
        aScheduleTheseReminders.push(oKatzerLNPluginReminder3AM);
      } else {
        aScheduleTheseReminders.push(oKatzerLNPluginReminder4AM);
      }

      // cancel existing reminders and schedule the reminder array via the callback
      cordova.plugins.notification.local.cancelAll(
        function scheduleAllRemindersViaKatzer() {
              cordova.plugins.notification.local.schedule(aScheduleTheseReminders)
        });
```
