### ISSUE TITLE
Conflict with cordova-plugin-fcm-with-dependecy-updated

### ISSUE THREAD

**Issue by Shashank2406** [katzer/cordova-plugin-local-notifications#1759]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

cordova-plugin-local-notifications conflicts with cordova-plugin-fcm-with-dependecy-updated if i remove local notification FCM plugin seems to work fine. Can anyone come up with the solution so that both plugins can work together

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: iOS
* OS version: iOS 12
* Device manufacturer / model: Apple 
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic) 3 

## Expected Behavior

In the foreground, no push is received and no FCM on event is fired 

## Actual Behavior

FCM event should be fired so, I can generate a local notification. 

## Steps to Reproduce

Install this plugin and cordova-plugin-fcm-with-dependecy-updated

## Context

Implement push notification

**Comment by jiseungjun** [comment]
ionic cordova plugin rm cordova-plugin-fcm-with-dependecy-updated
ionic cordova plugin rm cordova-plugin-local-notifications

ionic cordova plugin add cordova-plugin-fcm-with-dependency-updated-apns
ionic cordova plugin add cordova-plugin-local-notifications@0.9.0-beta.3

**Comment by fsalazarsch** [comment]
> ionic cordova plugin rm cordova-plugin-fcm-with-dependecy-updated
> ionic cordova plugin rm cordova-plugin-local-notification
> 
> ionic cordova plugin add cordova-plugin-fcm-with-dependency-updated-apns
> ionic cordova plugin add cordova-plugin-local-notification@0.9.0-beta.3

you deserve a six pack of beer

**Comment by devexpert1** [comment]
Thanks a lot @jiseungjun , You saved my 2 days

**Comment by ProximaHaiz** [comment]
@jiseungjun Thanks! You are awesome!

**Comment by martinriviere** [comment]
Hi @jiseungjun, thanks for your solution!
I have implemented it, but still have an issue: since then and only on iOS, when I click on the local notification, it triggers the FCM plugin onNotification method resulting in a bad behavior?
Any idea why and how to fix this?
