### ISSUE TITLE
Can you explain `count`?

### ISSUE THREAD

**Issue by ash-auctionvilla** [katzer/cordova-plugin-local-notifications#1760]
The `count` parameter is quite ambiguous. There seems to be no documentation on it so far. Can anyone explain is simple words how it works? 

Apparently, I would like to schedule a single message notification each hour. 

`      cordova.plugins.notification.local.schedule({
        title: "title",
        text: 'Text!',
        attachments: '',
        trigger: { every: 'hour', count: 1 }
     });
`

Will it work?

**Comment by Simpler1** [comment]
count is a bit odd... If you want multiple notifications, then you need to
enter a number higher than 1 and then you will receive that many
notifications.

That is my understanding, but I'd be happy to be corrected. :)

It would be nicer if count were not needed and the notifications would just
continue recurring until canceled, but that's not how it's currently
implemented.

**Comment by Ashik72** [comment]
[Simpler1](/Simpler1) thanks for your insight. I thought if I schedule a notification each hour and make count X, at least once within X time(s) user need to enter the app for rescheduling.  I experimented little bit with each minute and count 3, I cancelled first notification and none was fired after then.
