### ISSUE TITLE
cordova.plugins.notification.local.schedule works first time, crashes every other time

### ISSUE THREAD

**Issue by salem0426** [katzer/cordova-plugin-local-notifications#1764]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## iOS

* Plugin version: cordova-plugin-local-notification 0.9.2
* Platform: iOS
* OS version: 12.0.1
* Device manufacturer / model: iPhone 7 (MNAJ2LL/A)
* Cordova version (```cordova -v```): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (```cordova platform ls```): 8.1.2 (cordova-lib@8.1.1)
* Plugin config cordova-plugin-local-notification 0.9.2 "LocalNotification"
* Ionic Version (if using Ionic)

## Expected Behavior
Notification pop-ups work every time

## Actual Behavior

First notification is successful. Every other notification crashes the app in UNUserNotificationCenter(APPLocalNotification) getNotificationWithID Line 131

## Steps to Reproduce

Happens consistently

## Context

Code snippet:
    	cordova.plugins.notification.local.schedule({
    	    title: 'PEARL Alert',
    	    text:inText,
    	    smallIcon: 'res://noti-logo.png',
    	    icon: 'file://img/noti-logo.jpg',   	   
    	    vibrate:true,
    	    lockscreen:true,
            foreground: true,
    	    actions: [ 
              acts
    	      function(data){
    		console.log("Notification callback: ",data);    		
    	      }
             ]
});

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
2019-03-03 15:26:27.735880-0500 PEARL[2178:698268] 15:26:27:730  Scheduling notification  is moving for item Aircraft
2019-03-03 15:26:27.753769-0500 PEARL[2178:698819] -[NSNull stringValue]: unrecognized selector sent to instance 0x23fc659a0
2019-03-03 15:41:49.352519-0500 PEARL[2178:698819] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull stringValue]: unrecognized selector sent to instance 0x23fc659a0'
*** First throw call stack:
(0x20f793ef8 0x20e961a40 0x20f6ab154 0x20f799810 0x20f79b4bc 0x1003b6904 0x1003abdd0 0x100bdb840 0x100bdcde4 0x100bdfcac 0x100bee1f8 0x100beebe4 0x20f3ae190 0x20f3b0d00)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by salem0426** [comment]
Additional information:
Plugin List:

cordova-plugin-aws-user-pool 1.1.0 "Aws UserPool sdk"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-ble-central 1.2.2 "BLE"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-dbcopy 2.1.2 "sqlDB"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-local-notification 0.9.2 "LocalNotification"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"

The iPhone 

Receives a one time only pop-up asking to allow Notifications for iOS Application. After "Allow" is clicked, Notification pop-up is observed.

![image1-12](https://user-images.githubusercontent.com/48187496/53727937-777c3000-3e3f-11e9-863b-c4eede88a89d.jpeg)

**Comment by salem0426** [comment]
Neglected to indicate that this issue is with iOS devices only. Notifications for this App on Android phones works just fine.

**Comment by Tawpie** [comment]
have you tried included including a unique integer id property with each notification? I also recommend when you're scheduling to always schedule using the array technique (build notification objects, put them in an array and then schedule).

**Comment by salem0426** [comment]
Updated Notification code per Tawpie's recommendation as follows:

    scheduleNotification:function (inText,inActions){
    	if(!inActions){
    		// don't clear notifications if actions are available
    		cordova.plugins.notification.local.clear();
    	}    	
    	var acts = (inActions ? inActions : []);
    	if(this.ntfObj == null){
    		
    		this.ntfObj = {
    				id:1,
    				title: 'PEARL Alert',    	    	    
    	    	    smallIcon: 'res://noti-logo.png',/* Must exist in res directory on both platforms */
    	    	    icon: 'file://img/noti-logo.jpg',   	   
    	    	    vibrate:true,
    	    	    lockscreen:true,   	    	    
    		};
    	}
    	this.ntfObj.text = inText;
    	this.ntfObj.actions = acts;
    	
    	cordova.plugins.notification.local.schedule(this.ntfObj,function(data){
    		console.log("Notification callback: ",data);    		
    	});    	
    } 

Crashed in 0_pthread_kill, line 4 “signal SIGABRT” after the first successful Notification. Xcode console log: 

2019-03-04 23:30:36.415232-0500 PEARL[1254:803939] 23:30:36:409  Scheduling notification  is moving for item Aircraft
2019-03-04 23:30:36.439309-0500 PEARL[1254:804502] -[NSNull stringValue]: unrecognized selector sent to instance 0x1bf94d9d0
2019-03-04 23:30:36.442377-0500 PEARL[1254:804502] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull stringValue]: unrecognized selector sent to instance 0x1bf94d9d0'
*** First throw call stack:
(0x18f889ea4 0x18ea59a50 0x18f7a2b14 0x18f88f7bc 0x18f89146c 0x10117925c 0x10116f350 0x101cff824 0x101d00dc8 0x101d03c90 0x101d121dc 0x101d12bc8 0x18f4a517c 0x18f4a7cec)
2019-03-04 23:30:36.442424-0500 PEARL[1254:803939] WARN: Unknown property: meta
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by salem0426** [comment]
Updated code "works" via audio notification but do not see a pop-up.

    scheduleNotification:function (inText,inActions){
        if(!inActions){
                // don't clear notifications if actions are available
                cordova.plugins.notification.local.clear();
        }
        var acts = (inActions ? inActions : []);
        if(this.ntfObj == null){

                this.ntfObj = {
                                id:0,
                                title: 'PEARL Alert',
                    smallIcon: 'res://noti-logo.png',/* Must exist in res directory on both platforms */
                    icon: 'file://img/noti-logo.jpg',
                    vibrate:true,
                    lockscreen:true,
                };
        }
        this.ntfObj.id +=1;
        this.ntfObj.text = inText;
        this.ntfObj.actions = acts;

        cordova.plugins.notification.local.schedule(this.ntfObj,function(data){
                console.log("Notification callback: " + data);
        });    
    }
----------------------------------
When I added "foreground: true," it reverted back to working for the first time (Notification audio and pop-up) but crashing every other time.

**Comment by salem0426** [comment]
One additional piece of information that may be relevant:
Tried several different iterations of updates including iPhone Notification option changes and updated cordova-plugin-local-notification version to 0.9.2 

These changes resulted in providing audio Notifications but no pop-up every time.

So the issue appears to be related to pop-up displaying for the first time only and crashing every other time.

I will attempt to narrow down which individual change caused this change in behavior. 

Any advice/tips that anyone can provide would be greatly appreciated!

**Comment by rnovaski** [comment]
@salem0426 Did you find a solution? I'm having crashes on my Android app, as well.

**Comment by Tawpie** [comment]
I'm on beta 3 with a fix for android issue 1541 (wouldn't work after device restart)... I believe the Android fix got rolled into master a few months ago. Next suggestion is to make sure you're using the real latest—npm seems to be fixated on a downrev version. And look at the pull requests as they may fix a number of other problems.

**Comment by rnovaski** [comment]
@Tawpie I have the master version and, following you suggestion, I adjusted some code based on pull requests #1792 and #1772 , but the crash when notification is going to show, persists. Thank you, anyway.

**Comment by Tawpie** [comment]
@rnovaski could you post the code you're using to schedule your notifications? Perhaps there's a clue in there.

**Comment by rnovaski** [comment]
@Tawpie I'm using Ionic, so:
this.localNotifications.schedule({
      title: 'My first notification',
      text: 'Thats pretty easy...',
      foreground: true,
      trigger: {at: new Date(new Date().getTime() + 3000)}
  });

This is an example I got from the docs here.

**Comment by rnovaski** [comment]
I removed and added the Android platform again and it's working right now. Thanks!

**Comment by Tawpie** [comment]
I'd add a id, in case you want to deal individually with the notification later or want to schedule another one (with a different id). But glad it was as simple as a remove/reinstall!
