### ISSUE TITLE
Open a specific screen through Ionic local notifications when the app is closed

### ISSUE THREAD

**Issue by uvindu9412** [katzer/cordova-plugin-local-notifications#1767]
## Your Environment

* Plugin version:^0.9.0-beta.2
* Platform:Android
* OS version:
* Device manufacturer / model:
* Cordova version (```cordova -v```): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (```cordova platform ls```):
Installed platforms:
  android 7.0.0
  ios 4.5.5
Available platforms: 
  browser ~5.0.1
  osx ~4.0.1
  windows ~6.0.0
* Plugin config
* Ionic Version (if using Ionic) 3.9.4

## Expected Behavior

To open a a specific screen through a notification when the app is not running in the background

## Actual Behavior

I am trying to open a specific screen of my app when a local notification is clicked the code given below works when app is running in the background. But when the app is fully closed not running in the background this doesn't work. Is there a specific way to do this.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

```
this.localNotification.on('click', (notification, event) => {
      localStorage.setItem('isNotification','1');
      if(localStorage.getItem('isNotification')=='1'){
          this.appCtrl.getRootNav().push(SalePage, 
          {'field':notification.data.sale,'field':notification.data.field1,'pn':notification.data.pn});
    }
});
```

## Context

Open a specific screen in android through local notifications

**Comment by adamalexander** [comment]
@uvindu9412 Have you got this to work?
