### ISSUE TITLE
Local notifications dont find firebasecore.h file

### ISSUE THREAD

**Issue by veronesecoms** [katzer/cordova-plugin-local-notifications#1770]
* Plugin version:

cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"

* Platform:

IOS

* ionic version
4.1.2

* Installed platforms:
  ios 4.5.5

## Expected Behavior

Build an ios application in iOS

Im trying to make a build an ios app but when i try to build in xcode i receive:

`#import <FirebaseCore/FirebaseCore.h> ` 

FirebaseCore.h not found

in the archive **Firebase.h**

I dont know what i have to do...
I have to install an specific dependency on pod?

My actually pod:

```
# DO NOT MODIFY -- auto-generated by Apache Cordova
platform :ios, '8.0'
target 'JControle App' do
	project 'JControle App.xcodeproj'
end

```

Im not using push notifications, just local notifications as you can see:

cordova plugin ls
```
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.4.0 "Cordova sqlite storage plugin"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
phonegap-plugin-multidex 1.0.0 "Multidex"
```

i really need this firebase plugin? please help me

**Comment by tripflex** [comment]
Not for this plugin, no.  You can clearly see that it's added under your cordova plugins:
```
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
```
