### ISSUE TITLE
Notification is not getting triggered at expected time

### ISSUE THREAD

**Issue by smadapat** [katzer/cordova-plugin-local-notifications#1773]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

I am getting the notification but delayed by 1 minute when I use firstAt and every

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version: Android 6.0 "Marshmallow"
* Device manufacturer / model: Lenovo Vibe k4
* Cordova version (```cordova -v```): 8.1.2
* Cordova platform version (```cordova platform ls```):
Installed platforms:
  android 7.1.4
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~6.0.0

* Plugin config
* Ionic Version (if using Ionic) 3.20.1

## Expected Behavior

If I am using the below code I expect notification to come at Apr 4, 2019, 12:15AM but it is delayed by a minute
```
cordova.plugins.notification.local.schedule({
      id: "id",
      title: "title",
      text: "text",
      trigger: {
        firstAt: new Date(2019, 3, 4, 0, 15),
        every: "minute",
        count: 2
      }
    });
```

## Actual Behavior

I am getting the notification at Apr 4, 2019, 12:16AM

```
cordova.plugins.notification.local.schedule({
      id: "id",
      title: "title",
      text: "text",
      trigger: {
        firstAt: new Date(2019, 3, 4, 0, 15),
        every: "minute",
        count: 2
      }
    });
```

## Context

Trying to display repeated notification starting with a particular date & time.

## Debug logs
NA

**Comment by aidanas** [comment]
I seem to be getting notifications always delayed by 2 minutes.
