### ISSUE TITLE
schedule event not firing on ios

### ISSUE THREAD

**Issue by angjelkom** [katzer/cordova-plugin-local-notifications#1774]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
On ios when scheduling an event the on('schedule') event is not fired

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: iOS
* OS version: 12.1
* Device manufacturer / model: Iphone Simulator
* Cordova version 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version ios 5.0.0
* Plugin config
* Ionic Version (if using Ionic) NO

## Expected Behavior

Setting a schedule event:

```
cordova.plugins.notification.local.on("schedule", function(notification) {
    alert("scheduled: " + notification.id);
});

```
and scheduling a notification with:

```
cordova.plugins.notification.local.schedule({
    text: "Delayed Notification",
    at: new Date(Date.now() + 5000),
});
```

it should trigger the schedule event, but it doesn't

## Actual Behavior

Schedule event isn't fired

## Steps to Reproduce

1. On Device ready set the schedule event first:

```
cordova.plugins.notification.local.on("schedule", function(notification) {
    alert("scheduled: " + notification.id);
});
```

2. Schedule a notification to fire 5s from now:

```
cordova.plugins.notification.local.schedule({
    text: "Delayed Notification",
    at: new Date(Date.now() + 5000),
});
```

3. Schedule event doesn't fire

## Context

To receive info when event gets successfully scheduled

## Debug logs

> 2019-04-04 12:43:32.763365+0200 HelloCordova[54115:280582] Apache Cordova native platform version 5.0.0 is starting.
> 2019-04-04 12:43:32.763710+0200 HelloCordova[54115:280582] Multi-tasking -> Device: YES, App: YES
> 2019-04-04 12:43:32.766578+0200 HelloCordova[54115:280582] 
> 
> Started backup to iCloud! Please be careful.
> Your application might be rejected by Apple if you store too much data.
> For more information please read "iOS Data Storage Guidelines" at:
> https://developer.apple.com/icloud/documentation/data-storage/
> To disable web storage backup to iCloud, set the BackupWebStorage preference to "local" in the Cordova config.xml file
> 2019-04-04 12:43:32.782206+0200 HelloCordova[54115:280582] Using UIWebView
> 2019-04-04 12:43:32.782987+0200 HelloCordova[54115:280582] [CDVTimer][console] 0.033975ms
> 2019-04-04 12:43:32.783097+0200 HelloCordova[54115:280582] [CDVTimer][handleopenurl] 0.038028ms
> 2019-04-04 12:43:32.783921+0200 HelloCordova[54115:280582] [CDVTimer][intentandnavigationfilter] 0.751972ms
> 2019-04-04 12:43:32.784015+0200 HelloCordova[54115:280582] [CDVTimer][gesturehandler] 0.031948ms
> 2019-04-04 12:43:32.784076+0200 HelloCordova[54115:280582] [CDVTimer][TotalPluginStartup] 1.141071ms
> 2019-04-04 12:43:32.977928+0200 HelloCordova[54115:280582] Resetting plugins due to page load.
> 2019-04-04 12:43:32.998695+0200 HelloCordova[54115:280582] Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.)
> 2019-04-04 12:43:32.999783+0200 HelloCordova[54115:280582] Resetting plugins due to page load.
> 2019-04-04 12:43:33.207536+0200 HelloCordova[54115:280582] Finished load of: file:///Users/jack/Library/Developer/CoreSimulator/Devices/6A5C232E-5284-410F-87D6-FE88E7ED09AC/data/Containers/Bundle/Application/5C3AAF74-23B3-4BAB-BA37-8F85EBB669C9/HelloCordova.app/www/index.html
> 2019-04-04 12:43:33.232169+0200 HelloCordova[54115:280582] Received Event: deviceready
> 2019-04-04 12:43:43.234284+0200 HelloCordova[54115:280582] scheduled
> 2019-04-04 12:43:43.241948+0200 HelloCordova[54115:280582] WARN: Unknown property: at
>

**Comment by Tawpie** [comment]
Try preparing the notification object as shown below:

```
// build the reminder, start with a basic no-action reminder
    let oKatzerLNPluginReminder = {
      id: new Date().getTime(),
      trigger: { at: new Date(dFireAt) }, // MUST be a date object
      text: "This is a test message scheduled to fire at " + dFireAt.toString(),
      title: "TESTING!"
    };
```

especially note that the trigger property is an object with a property at whose value is the date object defining when you want the notification to fire. You really need an is—it keeps the various notifications from colliding with each other

Then schedule that object using the array method (I know you're only scheduling 1 so it's not really necessary, but trust me, you'll be happier down the road)

```
    cordova.plugins.notification.local.schedule(
      [oKatzerLNPluginReminder]
    );
```
