### ISSUE TITLE
Cannot change smallIcon

### ISSUE THREAD

**Issue by netomia** [katzer/cordova-plugin-local-notifications#178]
window.plugin.notification.local.add({
	id:         1,
	title:		'MyTitle',
	sound:		null,
	smallIcon:	'file://images/another_icon.png'
});

This does not change the small icon - the small icon is _always_ the local res icon.

I am testing on Android 2.3 and 4.2.2.

**Comment by mikegetlottoapp** [comment]
Any update on this? I'm only getting the Bell :)

**Comment by mrmaiko** [comment]
You simply put the name of the small icon without the extension like so :    smallIcon: 'small',     Then place small.png in your res/drawable directory, just like the icons.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by DonLiborio** [comment]
The smallIcon setup wasn't working for me at all, no matter what image I used. BUT, I figured out that the default ic_popup_reminder was an android system icon (it's not in the resources folder), so I went to http://androiddrawables.com and found an appropriate icon for my app, entered its name and, voilá!, it worked.
