### ISSUE TITLE
Local Notification not working in Android 6

### ISSUE THREAD

**Issue by ghulamakbar14** [katzer/cordova-plugin-local-notifications#1785]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

Local notification is not working on Android 6 (Marshmallow).
It is working on higher versions Android 7, 8 & 9.

Further specifications are as follows:
Ionic : 4.12.0
Cordova : 9.0.0

"@ionic-native/local-notifications": "^5.3.0"
"cordova-plugin-local-notification": "0.9.0-beta.3"

**Comment by EmilienRamos** [comment]
I'm testing on a Samsung J6 (Android 8) and, as you said, localNotification doesn't appear.
Howerver, on ANdroid 6, it's working.
There will be a fix ?
