### ISSUE TITLE
requestPermission Dialog only shows for iOS platform

### ISSUE THREAD

**Issue by SanjanaTailor** [katzer/cordova-plugin-local-notifications#1787]
* Plugin version: "cordova-plugin-local-notification": "0.9.0-beta.2",
* Platform: Android
* OS version: 
* Device manufacturer / model: Samsung Tablet
* Cordova version (```cordova -v```) :9.0.0 
* Cordova platform version (```cordova platform ls```): android 6.3.0
* Plugin config
* Ionic Version (if using Ionic)   Ionic Framework    : ionic-angular 3.8.0
   @ionic/app-scripts : 3.0.1

## Expected Behavior
In Android using below code doesn't show permission dialog itself when for iOS platform it shows
` this.localNotifications.requestPermission().then((permission) => {
      //permission
    });`

## Actual Behavior

_Tell us what happens instead_

It display local notification dialog for android behaviour for both iOS and android will be similar

**Comment by haschu** [comment]
Same issue here. @SanjanaTailor did you find any solution/workaround so far?

**Comment by haschu** [comment]
Haha ok, that was an easy one  😄

Turns out, that under android there is no need to request the users permission for displaying notifications. I guess this issue can be closed.

**Comment by SanjanaTailor** [comment]
@haschu : right, For android there is no need to request to show permission dialogue for displaying local notification. As I understand end user might request to show same behaviour for both android and iOS right. can you share where is it mentioned in document as well ?
