### ISSUE TITLE
iOS 9  Local notification and badge not working

### ISSUE THREAD

**Issue by SanjanaTailor** [katzer/cordova-plugin-local-notifications#1788]
ionic info
Ionic:

ionic (Ionic CLI) : 4.1.2 Ionic Framework : ionic-angular 3.8.0 @ionic/app-scripts : 3.0.1

Cordova:

cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1) Cordova Platforms : android 6.3.0 Cordova Plugins : no whitelisted plugins (14 plugins total)

System:

Android SDK Tools : 26.1.1 ( NodeJS : v8.11.2 npm : 6.9.0 OS : Windows 10

"dependencies": {
    "@ionic-native/badge": "^4.20.0",
    "@ionic-native/local-notifications": "^4.20.0",
    "cordova-plugin-badge": "0.8.8",
    "cordova-plugin-local-notification": "0.9.0-beta.2",
  },

**Comment by SanjanaTailor** [comment]
Thank you @timbru31. Confirmed now it supports for iOS 10+ as per documentation

**Comment by timbru31** [comment]
Awesome! Could you close your issue since it's resolved now? :)

**Comment by SanjanaTailor** [comment]
yes, please close it
