### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by f5cs** [katzer/cordova-plugin-local-notifications#1789]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Android

* Plugin version:0.9.0-beta.2
* Platform:Android
* OS version:Windows
* Device manufacturer / model:
* Cordova version (```cordova -v```):9.0.0
* Cordova platform version (```cordova platform ls```):android 8.0.0
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

_Tell us what should happen_

## Actual Behavior

when execute cordova build android,the exception happen:
> Task :app:transformClassesWithDexBuilderForDebug FAILED
    FAILURE: Build failed with an exception.
    * What went wrong:
    Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 38 path $[0].name
Command failed with exit code 1 Error output:
cordova\platforms\android\app\src\main\java\de\appplant\cordova\plugin\localnotification\TriggerReceiver.java

when insall the plugin,i have install other plugins before:
cordova plugin add cordova-plugin-android-permissions
cordova plugin add cordova-plugin-fullscreen
cordova plugin add cordova-plugin-statusbar
cordova plugin add cordova-plugin-backbutton
cordova plugin add cordova-plugin-background-mode

cordova plugin add cordova-plugin-inappbrowser
cordova plugin add cordova-plugin-geolocation
cordova plugin add cordova-plugin-sim
cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-file
cordova plugin add cordova-plugin-vibration
cordova plugin add cordova-plugin-splashscreen
cordova plugin add cordova-plugin-screen-orientation
cordova plugin add cordova-plugin-media
cordova plugin add cordova-plugin-camera
cordova plugin add cordova-plugin-crop

**Comment by luca-itro** [comment]
Please post your js code
