### ISSUE TITLE
Sound still plays on Android

### ISSUE THREAD

**Issue by netomia** [katzer/cordova-plugin-local-notifications#179]
window.plugin.notification.local.add({
	id:         1,
	title:		'MyTitle',
	sound:		null,
	smallIcon:	'file://images/another_icon.png'
});

I still hear a beep whenever this is called.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
