### ISSUE TITLE
UIKit: -[UIConcreteLocalNotification setUserInfo:] + 420 on push open

### ISSUE THREAD

**Issue by Morathil** [katzer/cordova-plugin-local-notifications#1794]
We recently updated this plugin from `#a75c097` to `#fbcc2e5`. Since then we are receiving a lot of crashes on iOS < 12 when Users try to open the app via the received push notification. Crash: `UIKit: -[UIConcreteLocalNotification setUserInfo:] + 420`.

I was able to reproduce it in the xCode simulator (see below).
Crashed did not happen on the old version `#a75c097`.

Maybe someone could help me with this one?

Cheers,
Christoph

## Your Environment

* Plugin version: `#fbcc2e5`
* Platform: `iOS`
* OS version: `iOS 10 + 11`
* Device manufacturer / model: `Apple`
* Cordova version (```cordova -v```): `8.0.0`
* Cordova platform version (```cordova platform ls```): cordova-ios: `4.5.4`
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

When the app is closed and I click on a local push the app should start.

## Actual Behavior

When the app is closed and I click on a local push the app crashes.
But the app does not crash if the app runs in background.

## Steps to Reproduce

  1. Schedule a notification on iOS 11.4
  2. Complete close the app
  3. Receive a notification
  4. Click on the notification
  5. Crash

## Context

Open a local notification on iOS < 12 on any device.

## Debug logs

_Include iOS / Android logs_

![Screen Shot 2019-05-09 at 11 30 47](https://user-images.githubusercontent.com/3746974/57525727-c35dc080-732b-11e9-9091-0cbd56326921.png)

**Comment by amWhitelabel** [comment]
Was there any fix found for this? Or any workaround suggestions?

**Comment by amWhitelabel** [comment]
Just in case anyone is still facing this issue:
The crash is due to 'timeoutAfter' key in notifications userInfo being null. This parameter is not used for iOS and is there only for Android.

Simple fix for iOS, before creating APPNotificationContent, check for null value for any key in options dictionary, and remove the same.

- (void) schedule:(CDVInvokedUrlCommand*)command
{
    NSArray* notifications = command.arguments;

    [self.commandDelegate runInBackground:^{
        for (NSDictionary* options in notifications) {
            APPNotificationContent* notification;
            // Null value in options causing crash
            // 'timeoutAfter' is used only in Android
            NSMutableDictionary* optionsCopy = [options mutableCopy];
            for (NSString* key in options.allKeys) {
                if ([[optionsCopy valueForKey:key] isKindOfClass:[NSNull class]]) {
                    NSLog(@"Found %@ to be Null, would result in crash. Removing %@ from options", key, key);
                    [optionsCopy removeObjectForKey:key];
                }
            }
            notification = [[APPNotificationContent alloc]
                            initWithOptions:optionsCopy];
            [self scheduleNotification:notification];
        }
        [self check:command];
    }];
