### ISSUE TITLE
Notification not firing after re-start 

### ISSUE THREAD

**Issue by s-khan-net** [katzer/cordova-plugin-local-notifications#1799]
1 Notifications **not** firing after restarting the device
2 small icon is not appearing in color

Phonegap build repo here: [https://github.com/s-khan-net/notify](https://github.com/s-khan-net/notify)

* Plugin version: 0.9.0-beta.2
* Platform: Phonegap build (cli-8.0.0)
* OS version: Android 8 & 9
* Device manufacturer / model: Samsung & motorola

## Expected Behavior
*The notification must fire after device is restarted
*The small icon is always in white, ie, even though Ive put a transparent color png, it still appears in grey

## Actual Behavior
notification not firing
the color of the icon is always greyed

## Steps to Reproduce
Ive made a demo pgb project here:
https://github.com/s-khan-net/notify

**Comment by s-khan-net** [comment]
Ive tried to build using beta 1 as well, but same issues exist

![image](https://user-images.githubusercontent.com/16497901/58148818-deaac300-7c7d-11e9-877f-e81213cc3e32.png)
The small icon issue,
Im using the transparent png file same as in twitter

**Comment by luoenzhen** [comment]
From your code "at: new Date(now + 1000)" which should be "trigger: { at: new Date(now + 1000) }".

**Comment by s-khan-net** [comment]
I changed at to trigger, the immediate notification works fine, but the scheduled notification does not fire after device restart.

**Comment by luoenzhen** [comment]
I have the similar issue, the immediate notification works but not the scheduled ones.

**Comment by s-khan-net** [comment]
hey... I think it worked
 with this cordova-plugin-local-notification-fixed
include this in the config instead of the cordova-plugin-local-notification
Ill update code in the repo.

**Comment by luoenzhen** [comment]
I will let you if it works on my side. Thanks.

**Comment by luoenzhen** [comment]
Update: I installed the https://github.com/kitolog/cordova-plugin-background-mode-fixed, it still doesn't work for the scheduled ones.
