### ISSUE TITLE
Banner not appearing on local notification

### ISSUE THREAD

**Issue by neilkyoung** [katzer/cordova-plugin-local-notifications#180]
This may be a stupid question and maybe I am missing something but the application now does in fact fire the notification and it appears in the notification center but it does not appear as a banner at the top of the screen. Is this something silly that I am missing or a bug with the plugin?

**Comment by zeeshanjan82** [comment]
I am not able to understand how to display a banner using this plugin. I am able to display a notification when my app is in background. I am using the following code:

            var now = new Date().getTime(),
                _5_sec_from_now = new Date(now + 60 * 1000);
            var sound = device.platform == 'Android' ? 'file://sound.mp3' : 'file://beep.caf';
            cordova.plugins.notification.local.schedule({
                id: 1,
                title: 'Scheduled with delay',
                text: 'Test Message 1',
                at: _5_sec_from_now,
                sound: sound,
                badge: 12
            });

**Comment by revaret** [comment]
same issue here

**Comment by revaret** [comment]
@JavierAbrego  Did you found a work around ?

**Comment by jgillard** [comment]
I'm trying to achieve the same, any more wisdom gained yet?

**Comment by revaret** [comment]
I implemented a work around by using [noty](http://ned.im/noty/#/about) in the push call back

**Comment by fathiabdoon** [comment]
The is now happening in Android not IOS. When the app is not in view, you get the local notification only the bell icon shows up, not the message (in form of toaster).
