### ISSUE TITLE
reply in notification : actions input

### ISSUE THREAD

**Issue by alarbcoin** [katzer/cordova-plugin-local-notifications#1801]
**Issue**: The issue is Reply to messages that are in the form of a notification .

**Issue description** : You've added notifications well but the problem is responding to messages in the android platform
Is there a patching solution for the command or just wait for an update for this plugin.

I need the property very much for anyone who has a solution or a patching solution for example
That is when adding the value must be sent to the database .

**actions input**

Thank you in advance

## Your Environment

* Plugin version: 0.10.6
* Platform: android
* OS version: 4.4 or Height
* Cordova version : last

**Comment by millerf** [comment]
+1

**Comment by ikennaUkwueze** [comment]
@alarbcoin Have you found solution to this yet?

**Comment by moshi100** [comment]
+1

**Comment by fasthostinc** [comment]
any solution yet?
