### ISSUE TITLE
Clear notification on app close

### ISSUE THREAD

**Issue by jessica88888** [katzer/cordova-plugin-local-notifications#1802]
## Your Environment

* Plugin version: Latest version from Git using PhonegapBuild
* Platform: Android
* Cordova version (```cordova -v```): Using PhonegapBuild

## Expected Behavior

Hi, first of all, I would like to thanks for this great plugin. I'm using this plugin together with phonegap-plugin-push. By default, phonegap-plugin-push will clear all notification on pause, so I added this line of code: android: { clearNotifications:"false" }

I do not want the notifications to be cleared on pause (minimize), but I couldn't find a way to clear all notification on app close/killed.

May I know is there any possibility to clear all notification / clear particular id on app close?

Thank you.

Best regards,
Jessica

**Comment by pedropamn** [comment]
Did you find a solution to this?
