### ISSUE TITLE
Android 9 doesn't show notification at top of screen

### ISSUE THREAD

**Issue by sts-ryan-holton** [katzer/cordova-plugin-local-notifications#1807]
Android 9 only appears to show notifications when sliding down the notifications box, and doesn't seem to show notifications on lock screen

**Comment by LeoSaucedo** [comment]
Having the same issue. Can't edit notification settings from app either. The plugin is old and says there's no Oreo support, so perhaps this is related.

**Comment by Kraloz** [comment]
I have the same issue, any solution?
