### ISSUE TITLE
It keeps rining whole minutes...

### ISSUE THREAD

**Issue by kotran88** [katzer/cordova-plugin-local-notifications#1818]
let notification2:any = {
      title: 'Happy Birthday!!!',
    trigger: { every: {  hour: 3, minute: 2,second:0 } }
    }
    this.notification.schedule(notification2);

I'm using ionic v3
eventhough I set second to 0 , 
it gives me alarm for whole time of 3:2am even if I quit it. 
and when it become 3:3am, alarm quit. 
I can I set alarm only once at 3:2am. 
I want to get notification for every day only one time at 3:2am.

**Comment by jmeyers91** [comment]
It looks like this plugin doesn't accept a `second` option. I was running into the same issue and fixed it in #1813, but I thought my issue was related to the `weekday` option, so I'm not 100% sure it will fix your use-case.

**Comment by katzer** [comment]
@kotran88 @jmeyers91 I cannot reproduce that

**Comment by webteambel** [comment]
@katzer I tested on Android 10 / plugin v9 beta2

```
 this.localNotifications.schedule({
      id: 100,
      title: 'Mood',
      text: 'Please let us know how you are feeling today!',
      trigger: { every: { hour: hr, minute: min } },
      foreground: true,
      led: 'FF0000',
      vibrate: true,
      sound: null
    });
```
It keeps rining whole minute on my android device and works fine on iOS
