### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by jmeyers91** [katzer/cordova-plugin-local-notifications#1819]
It appears most of the issues and PRs submitted over the past few months haven't been addressed by any maintainers. Is this project still actively being maintained?

**Comment by blondie63** [comment]
:( i think no..

**Comment by sts-ryan-holton** [comment]
Does anyone know of any other plugins for notifications

**Comment by nicolashenry** [comment]
Ping @katzer

**Comment by katzer** [comment]
Hi, its maintained from time to time because I dont use it by myself anymore. It's not a perfect situation, I know.

**Comment by blondie63** [comment]
> Hi, its maintained from time to time because I dont use it by myself anymore. It's not a perfect situation, I know.

are you using another plugin ?

**Comment by katzer** [comment]
I dont use cordova

**Comment by blondie63** [comment]
> I dont use cordova

i'm curious... so what platform are you using now ?

**Comment by katzer** [comment]
> i'm curious... so what platform are you using now ?

Either its native mobile development or pure web apps.

I used cordova in a project when I initially created all of my cordova plugins. Since that time I only develop & maintain them :´(

**Comment by ivaneidel** [comment]
Hi @blondie63 !

Just as a suggestion, if you are looking for a cross platform mobile development framework, i'd really encourage you to try [Flutter](https://flutter.dev/), if you haven't already. I've been using it for work and personal projects for a while now, and i can tell you, if you put in a few hours, you'll find it's super simple and extremely powerful.

Anyway, hope you find what you're looking for ;)
