### ISSUE TITLE
iOS plugin works first time in foreground, crashes every other time

### ISSUE THREAD

**Issue by salem0426** [katzer/cordova-plugin-local-notifications#1821]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

cordova-plugin-local-notifications on iOS works great with initial test of having the app in background. But when I attempted to change the behavior to have it work in the foreground, it only works the first time.

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: iOS
* OS version: 12.3.1
* Device manufacturer / model: iPhone
* Cordova version (```cordova -v```): 4.5.5
* Cordova platform version (```cordova platform ls```): iOS 4.5.5
* Plugin config Cordova
* Ionic Version (if using Ionic) N/A

I have also tried Plugin versions
cordova-plugin-local-notification 0.9.3
cordova-plugin-local-notification 0.9.0-beta.2 

## Expected Behavior

Every time my app calls this function, I would like a notification to appear. 

## Actual Behavior

Only works the first time and crashes every other time.

## Steps to Reproduce

I have a function call that passes as an argument the text string that needs to be displayed. To keep the test simple, I’m disabling the text string passing and using a hard coded text string.

## Context

ntfObj = { actions: [
            {id:'0',
             title: 'PEARL Alert',
             text: 'hardcoded text'}
             ],
             foreground: true};

First time, I get the notification. 
cordova.plugins.notification.local.schedule(ntfObj);

When I call it a second time:
cordova.plugins.notification.local.update('0');

The app crashes

I have also tried cordova.plugins.notification.local.on for the second call, same result.

## Debug logs

Error message when the app crashes:
2019-07-31 06:07:46.247162-0400 PEARL[643:292777] -[NSTaggedPointerString objectForKey:]: unrecognized selector sent to instance 0xedf4d5aa222822f6
2019-07-31 06:07:46.251461-0400 PEARL[643:292777] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString objectForKey:]: unrecognized selector sent to instance 0xedf4d5aa222822f6'
*** First throw call stack:
(0x1c087127c 0x1bfa4b9f8 0x1c078dab8 0x1c0876ac4 0x1c087875c 0x100da14c0 0x101cff6f0 0x101d00c74 0x101d03ad4 0x101d11dc8 0x101d127ac 0x1c04911b4 0x1c0493cd4)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Tawpie** [comment]
Have you tried using an int for the id properly? I don't update my notifications (I cancel them and reschedule anew) but have not had problems using integers for id.

**Comment by salem0426** [comment]
Tawpie: Thank you for your suggestion. I changed the id to be an integer and there was no change in behavior. My app still crashed a second time.

**Comment by mukeshgupta** [comment]
Try to give different id value every time your code run
