### ISSUE TITLE
Click events not firing on iOS from cold start

### ISSUE THREAD

**Issue by adamalexander** [katzer/cordova-plugin-local-notifications#1826]
## My Environment

* Plugin version: 0.9.0-beta.2
* Platform: iOS
* OS version: iOS 12.4
* Device manufacturer / model: iPhone 7 Plus
* Cordova version: 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version:  ios 4.5.2
* Plugin config:
```
 cordova.plugins.notification.local.schedule({
id: 0, 
 title: 'Title',
 text: 'Test', 
foreground: true
});
```
## Expected Behavior
When clicking a notification when the app is terminated, the click event should still fire after the onDeviceReady event.

## Actual Behavior
When clicking the notification, while the app is terminated, nothing happens. the event is lost. I tried upgrading to beta.3 but when I did that the click event never worked. Not even with the app resuming from the background

## Steps to Reproduce
  1. ... Register an on click event listener within the device-ready event
  2. ... Send your push notification
  3. ... Terminate the app
  4. .... Click the notification in the drawer and see that the click event didn't register

**Comment by adamalexander** [comment]
@katzer It seems as though this works fine on version 0.5.8, but not on the latest version. In fact, on the latest beta, the click event never fires on iOS. If you have any tips as to how we can get aorund this would be great.

**Comment by katzer** [comment]
@adamalexander I tried it and it works...

**Comment by florian-diatelic** [comment]
Hi @katzer and @adamalexander ,
I've the same problem. I've created a sample application on [my repository](https://github.com/florian-diatelic/local-notification-test). 

- I click on "Trigger notification in 3 seconds", 
- I accept the app to send notification
- I quit the app (Home button)
- After notification appears, I kill the app
- In notification center I open notification
- Nothing is added in my result list and I think that in iOS, didReceiveNotificationResponse is not called

It works fine on Android, app killed or not and it works on iOS when we don't kill the app.
