### ISSUE TITLE
Sound not working in android

### ISSUE THREAD

**Issue by sahiltuteja09** [katzer/cordova-plugin-local-notifications#1828]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 5.12.0
* Platform: Android
* OS version: Win 10
* Device manufacturer / model: mi
* Cordova version (```cordova -v```):9.0.0
* Cordova platform version (```cordova platform ls```):
android 8.0.0
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
* Plugin config
* Ionic Version (if using Ionic) : 5.0.2

## Expected Behavior

_Tell us what should happen_ : Notification Sound not working

## Actual Behavior 

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ... 
{
          id: new Date().getTime(),
          title: 'Test',
          text: 'Hey! Have you check today reports ?',
          trigger: {count: 1, at: new Date(new Date().getTime() + 10000)},
          foreground: true,
            launch: true,
            badge: 1,
            vibrate: true,
            sound: 'file://assets/chat/notification.mp3',
            attachments: ['file://assets/chat/chat1.jpg'],
        }
  2. ... Build android app
  3. ... and check the notification sound is not working
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by danemco** [comment]
I could be wrong, but don't sound files need to be included in the app's `res` folder first, and you reference it from there?
