### ISSUE TITLE
Adding local notifications blocks the UI on Android

### ISSUE THREAD

**Issue by hypermurea** [katzer/cordova-plugin-local-notifications#183]
I'm noticing that setting up multiple notifications seems to block the UI completely, on Android 2.3.3 I get log as below. This means the notification plugin methods should be set to use threads?

W/PluginManager(  335): THREAD WARNING: exec() call to LocalNotification.add blocked the main thread for 23ms. Plugin should use CordovaInterface.getThreadPool().
W/webview (  335): Miss a drag as we are waiting for WebCore's response for touch down.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
