### ISSUE TITLE
Documentation: What physical unit is "location -> radius"?

### ISSUE THREAD

**Issue by klaus31** [katzer/cordova-plugin-local-notifications#1830]
I just miss the Information about the physical unit of `radius`. Is it in metres or inches or what is it?  
Surely everybody knows it but me ... 

PS: Since I only miss a tiny point in your `README.md`, I did not fill out your template ...

**Comment by adamalexander** [comment]
Hey @klaus31  It's definitely in Meters.

**Comment by katzer** [comment]
center gives the coordinates of center of the region, while radius gives the distance in meters between the center and the region's boundary.

**Comment by andrews3** [comment]
@katzer Is location trigger supported in Android?
