### ISSUE TITLE
Android 8+ : Local notification and badge not working

### ISSUE THREAD

**Issue by ELIDJEAKA** [katzer/cordova-plugin-local-notifications#1831]
##Ionic 
ionic (Ionic CLI) : 4.10.2 Ionic Framework : ionic-angular 3.9.2 @ionic/app-scripts : 3.2.4 
Cordova 
cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1) Cordova Platforms android 8.1.0
System : 
( NodeJS : v10.13.0 npm : 6.9.0 OS : Windows 10)
"dependencies": {
"@ionic-native/badge": "^4.20.0",
"@ionic-native/local-notifications": "^4.20.0",
"cordova-plugin-badge": "0.8.8",
"cordova-plugin-local-notification": "git+https://github.com/katzer/cordova-plugin-local-notifications.git#ios10",
},

Local and badge notifications not working on android 8,9

**Comment by kolbasa** [comment]
How is that still not fixed? Android 8 was released on August 21, 2017.

**Comment by shanthan25** [comment]
need to create notification channel

**Comment by alborrajo** [comment]
How would I create a notification channel with this plugin?
