### ISSUE TITLE
Notification Sound not Working

### ISSUE THREAD

**Issue by Rickk137** [katzer/cordova-plugin-local-notifications#1832]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**
I'm working on a react project ,and want to use my own sound for the notification.
i imported the sound and put it in the set Default object.
 cordova.plugins.notification.local.setDefaults({
      sound: notifSound
    });
## Your Environment

* Plugin version:0.9.0
* Platform:android
* OS version:9
* Device manufacturer / model: xiami mi 8
* Cordova version (```9.0.0```):
* Cordova platform version (``android 8.0.0```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior
use the imported sound instead of default sound for notification.

_Tell us what should happen_

## Actual Behavior

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by emilycestmoi** [comment]
I have the same issue. Same code works fine on iOS but the default notification sound is played on Android.

**Comment by timkellypa** [comment]
I know this is old, but the reason for this is that the custom sound is not being added to the notification channel for Android 8, 9, 10.

I have it working in this fork (and I think there are some other forks that addressed this as well):
https://github.com/timkellypa/cordova-plugin-local-notifications
