### ISSUE TITLE
launchDetails is coming when Open app by App Icon.

### ISSUE THREAD

**Issue by maniveltvl** [katzer/cordova-plugin-local-notifications#1833]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

I have schedule the notification and notification fired. But I cleared the notification and click app icon. But I am getting the launchDetails on OnDeviceReady event by the give code.
'cordova.plugins.notification.local.launchDetails'.

## Your Environment
Android and iOS
* Plugin version: 0.9.0-beta.0
* Platform: Android and iOS
* OS version: 
* Device manufacturer / model: Samsung
* Cordova version (```cordova -v```): 8.1.0
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior
When notification triggered and I click on app icon, launch details should be undefined then app should open home screen. If I click on notification app launch and based on notification id app will redirect to other page instead home page.

_Tell us what should happen_

## Actual Behavior
Now notification triggered and if i click app icon instead notification, app is getting launchDetails

_Tell us what happens instead_

Now notification triggered and if i click app icon instead notification, app should not get launchDetails

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. trigger one notification by the time app should not run(app should killed).
  2. don't click push notification. If you want keep notification or you can clear the all notifications
  3. Now click on App icon
  4. On Device ready event, we are getting the launchDetails values using 'cordova.plugins.notification.local.launchDetails'

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by katzer** [comment]
Could you test with `beta.3` first. I cannot reproduce that.

**Comment by maniveltvl** [comment]
Thanks for your reply. Let me try with beta.3 version.

Thanks
Mani
