### ISSUE TITLE
IOS13 support

### ISSUE THREAD

**Issue by KristjanHjartarson** [katzer/cordova-plugin-local-notifications#1834]
Since this plug in seems to be non-functional at the moment does anyone know of a fork that currently/soon has support for IOS13?

**Comment by katzer** [comment]
I agree with the general problem with Cordova. Despite that I just tried out basic things on iOS 13 with the plugin and it seems to work.

**Comment by KristjanHjartarson** [comment]
I can confirm that it works with ios13 out of the box, at least when utilizing schedule arrays defined beforehand.

**Comment by nielsjakob** [comment]
Everything works fine for me iOS 13 and below as well as Android

**Comment by leasonliu** [comment]
same problem here. Does anyone know when it will be fixed??

**Comment by LuanNg** [comment]
it work ios 13 and android 9 now, i used this way to repeating notifications.
let notification = {
                        id: 1,
                        data: {},
                        launch: true,
                        title: "Test",
                        text: "Test...",
                        silent: false,
                        trigger: { every: { hour: 0, minute: 0 } },
                        foreground: true,
                        wakeup: true
                    };

and please careful with conflict plugins such as cordova-plugin-fcm, cordova-plugin-background-geolocation, ... just remove them and try to test

**Comment by webteambel** [comment]
Hello, 
It's not working for me, is there any solution? ( test with iOS 12 working , test with iOS 13 not working)

Ionic : 3.9.2
Plugin version: 4.20.0

`this.localNotifications.schedule({
              id: idSession,
              title: name,
              text: description,
              foreground: true,
              trigger: { at: date },
              led: 'FF0000',
              vibrate: true,
              sound: null
            });`
