### ISSUE TITLE
App crash when notification is launched

### ISSUE THREAD

**Issue by felipegonzalez1994** [katzer/cordova-plugin-local-notifications#1838]
install the plugin and try to launch a notification with a button, but the application closes, I have installed the geolocation-background plugin , it will be a problem of compatibility of plugins?

apparently it is an ionic update error, create a blank project and install and configure the plugin and re-crashe the app.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: android
* OS version:
* Device manufacturer / model: Samsung galaxy j7 prime
* Cordova version (```cordova -v```): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (```cordova platform ls```): android 8.0.0
* Plugin config: default
* Ionic Version (if using Ionic): 5.2.7

## Expected Behavior

App send notification when button is activated

## Actual Behavior

when button is activated app is closed(crashed).

## Steps to Reproduce
-in appmodule.ts
import { LocalNotifications } from '@ionic-native/local-notifications/ngx';
...
providers: [
    BackgroundGeolocation,
    LocalNotifications
...
  ]

-in home.ts
import { LocalNotifications } from '@ionic-native/local-notifications/ngx';
...
 constructor(private backgroundGeolocation: BackgroundGeolocation, public plt: Platform, private localNotifications: LocalNotifications)
...
notificationTest(){
    this.localNotifications.schedule({
      id: 1,
      text: 'Notificacion',
      data: { secret: 'secret' }
    });
  }

**Comment by matamune94** [comment]
me too, someone can help ?

**Comment by matamune94** [comment]
it worked with this 
```
      cordova.plugins.notification.local.schedule({
        text: 'Delayed ILocalNotification',
        led: 'FF0000',
        smallIcon: 'res://mipmap-ldpi/ic_launcher.png'
      })
```

**Comment by Wolfman13** [comment]
What is the android version of the device you tested on?

**Comment by matamune94** [comment]
> What is the android version of the device you tested on?

7 > 9.0

**Comment by Wolfman13** [comment]
> > What is the android version of the device you tested on?
> 
> 7 > 9.0

There is a known issue with the cordova local notifications package that causes the app to crash if you don't implicitly stipulate smallIcon

**Comment by chengda** [comment]
config.xml
`
<config-file target="AndroidManifest.xml" parent="/manifest">
            <uses-permission android:name="android.permission.WAKE_LOCK"/>
</config-file>
`

**Comment by hp0101** [comment]
> it worked with this
> 
> ```
>       cordova.plugins.notification.local.schedule({
>         text: 'Delayed ILocalNotification',
>         led: 'FF0000',
>         smallIcon: 'res://mipmap-ldpi/ic_launcher.png'
>       })
> ```

Thank you. You save my life

**Comment by seunexplicit** [comment]
Thanks to this thread, it helps after so many month of experiencing the same issue
