### ISSUE TITLE
[android] Notification isn't displayed in foreground, only in statusbar

### ISSUE THREAD

**Issue by devjoks** [katzer/cordova-plugin-local-notifications#1843]
I installed firebase plugin (cordova-plugin-firebasex) and install this plugin. In iOS I don't have problems with the notification in foreground, but in android the notification only appears in the statusbar.

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: android
* OS version: 9
* Device manufacturer / model: Samsung Galaxy S9
* Cordova version: 9.0.0
* Cordova platform version: android 8.0.0
* Plugin config: default
* Ionic Version: 4.10.2

## Expected Behavior

Show push notification by firebase when the app is in foreground.

## Actual Behavior

Push notification only appears in the statusbar and isn't showing in foreground.

## Context

I trying to display the notification when the app is in foreground and background with the same behavior.

**Comment by aaabidunique** [comment]
As I understand in foreground fcm will call the callback function and not show the notification.
In Background fcm will show notification and on click it will call the call back function.
It will be helpful if you post some sample regarding what exactly you are doing.

**Comment by devjoks** [comment]
> As I understand in foreground fcm will call the callback function and not show the notification.
> In Background fcm will show notification and on click it will call the call back function.
> It will be helpful if you post some sample regarding what exactly you are doing.

I'm using the code below
```
  public onMessageReceived() {
    const _self = this;
    this.firebase.onMessageReceived().subscribe((data) => {
      if (data.messageType === 'notification') {
        if (_self.platform.is('ios')) {
          _self.notificationMessage = {
            'message': data.aps.alert.body,
            'title': data.aps.alert.title,
          };
        } else if (_self.platform.is('android')) {
          _self.notificationMessage = {
            'message': data.body,
            'title': data.title,
          };
        }
        _self.localNotifications.schedule({
          title: _self.notificationMessage.title,
          text: _self.notificationMessage.message,
          foreground: true,
          id: 1,
          priority: 2,
          silent: false,
        });
      }
    });
  }
```

**Comment by aaabidunique** [comment]
> > As I understand in foreground fcm will call the callback function and not show the notification.
> > In Background fcm will show notification and on click it will call the call back function.
> > It will be helpful if you post some sample regarding what exactly you are doing.
> 
> I'm using the code below
> 
> ```
>   public onMessageReceived() {
>     const _self = this;
>     this.firebase.onMessageReceived().subscribe((data) => {
>       if (data.messageType === 'notification') {
>         if (_self.platform.is('ios')) {
>           _self.notificationMessage = {
>             'message': data.aps.alert.body,
>             'title': data.aps.alert.title,
>           };
>         } else if (_self.platform.is('android')) {
>           _self.notificationMessage = {
>             'message': data.body,
>             'title': data.title,
>           };
>         }
>         _self.localNotifications.schedule({
>           title: _self.notificationMessage.title,
>           text: _self.notificationMessage.message,
>           foreground: true,
>           id: 1,
>           priority: 2,
>           silent: false,
>         });
>       }
>     });
>   }
> ```
From the code you provided, I can't conclude anything.
So can you provide a sample project (a repo) with this issue, it will help me fast track it.

**Comment by gwynjudd** [comment]
Probably related to the fix in this PR

https://github.com/katzer/cordova-plugin-local-notifications/pull/1696
