### ISSUE TITLE
Why can't I install a plugin with a low version number with this command: "$cordova plugin add cordova-plugin-local-notification@VERSION"

### ISSUE THREAD

**Issue by Wjiana** [katzer/cordova-plugin-local-notifications#1850]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

I can't use the latest version of the plugin due to system version issues, I want to try to install an earlier version of the plugin, but I can't install it.

## Your Environment

* Plugin version:0.7.2
* Platform:android
* OS version:
* Device manufacturer / model: Samsung Galaxy S9
* Cordova version : 8.0.0
* Cordova platform version: android 6.2.3
* Plugin config
* Ionic Version (if using Ionic): 3.20.0

## Expected Behavior

I hope to install a lower version of the plugin in my project to run properly.

## Actual Behavior

I can't install the plugin with the specified version number with this command.
"$cordova plugin add cordova-plugin-local-notification@VERSION"

## Context

Try installing a low-level plugin

## Debug logs

(node:32184) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin cordova-plugin-local-notification@0.7.2 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cordova-plugin-local-notification@0.7.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by lorenzyannick** [comment]
Because it was renamed.
Before : https://www.npmjs.com/package/de.appplant.cordova.plugin.local-notification
Maybe try cordova plugin add de.appplant.cordova.plugin.local-notification@0.7.2

**Comment by Wjiana** [comment]
> Because it was renamed.
> Before : https://www.npmjs.com/package/de.appplant.cordova.plugin.local-notification
> Maybe try cordova plugin add de.appplant.cordova.plugin.local-notification@0.7.2

Thanks,but it still doesn't work,reporting the same error!

**Comment by hoangDung096** [comment]
You can change the version in the package.json then build the project
