### ISSUE TITLE
Android scheduling repeating notifications not working

### ISSUE THREAD

**Issue by Sithdasss** [katzer/cordova-plugin-local-notifications#1857]
Scheduling a repeating notification is not working. When using at and every, nothing shows. I am not sure what changed but they used to work together.  I am trying to get a date and set a weekly repeating notification that will trigger the same day of week and hour. 

## Your Environment

* Plugin version: 0.9.0-beta.2 & 0.9.0-beta.3 & Master
* Platform: android
* OS version:  Windows 10
* Device manufacturer / model: samsung galaxy s6
* Cordova version (```cordova -v```): 7.0.0 and 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (```cordova platform ls```):  android 8.1.0
* Plugin config
* Ionic Version (if using Ionic) not using Ionic

## Expected Behavior
```
var date = new Date(Date.now() + 30 * 1000);
cordova.plugins.notification.local.schedule({ 
                            id: id,
                            title: title,
                            text: text,  
                            at:  date,
                            every: 'week',     
                        }));
```
_Tell us what should happen_

Notification should trigger in thirty seconds and will repeat at the same time next week.
## Actual Behavior
``` 
var date = new Date(Date.now() + 30 * 1000);
cordova.plugins.notification.local.schedule({
                            id: id,
                            title: title,
                            text: text,  
                            at:  date, // will trigger if there is no every option
                            every: 'week', // if at and every options are there, no notification happens
 //trigger: { every: { month: date.getMonth(), day: date.getDay(), hour: date.getHours(), }, count: 20 } // doesnt work
 //trigger: { every: 'week', at: date } // doesnt work
 //trigger: { every: 'week', firstAt: date } // doesnt work
 //firstAt: date// doesnt work
 //trigger: { every: 'week', at: date } // doesnt work
 }));
```
_Tell us what happens instead_

All the commented out options are ones I have tried in the above code and will not trigger the notifications, I have tried all three current plugins but can't get any to work.

**Comment by Sithdasss** [comment]
```
trigger: { 
every: { weekday: date.getDay(),  
hour: date.getHours() ,
date : nextUpcomingCutoffDateNotificationDate.getMinutes()  } },
```
android 8.1.0
9.0.0 (cordova-lib@9.0.1)
0.9.0-beta.3

It seems to be working. Tested on an emulator, notification triggered in 30 seconds. I then set emulator date to the same day of the week, hour and minute but a week ahead and it triggered as expected.

**Comment by naffets77** [comment]
Thanks for posting your solution, it almost seems to be working, but the notification isn't dismissible. Did you run into that issue, or are you using one of the other branches (https://github.com/timkellypa/cordova-plugin-local-notifications) that might work a little better?
