### ISSUE TITLE
How to Install this plugin into ionic 

### ISSUE THREAD

**Issue by Hussainmohamed** [katzer/cordova-plugin-local-notifications#1871]
when i am installing this plugin but it says some error 
Error: EPERM: operation not permitted, rename 'C:\Users\sp\.config\configstore\cordova-config.json.347950191' -> 'C:\Users\spidy\.config\configstore\cordova-config.json'

**Comment by StefanRein** [comment]
To install it on ionic you would run:

`ionic cordova plugin add cordova-plugin-local-notifications`

or this to get the latest one from this repository:

`ionic cordova plugin add git+https://github.com/katzer/cordova-plugin-local-notifications.git`

I am not sure if the `git+` is necessary here

You have a permission issue. Make sure your user has the permissions to modify files in this directory.
