### ISSUE TITLE
Stop scheduling and sending notification after 10-12 days. Strange behaviour 

### ISSUE THREAD

**Issue by prashant18-code** [katzer/cordova-plugin-local-notifications#1872]
Can someone please help me out to be able to understand what might have gone wrong. I'm using this plugin " katzer/cordova-plugin-local-notifications " and scheduling the notification for a certain timeline only when user logs in for the first time. Notification works fine for 10-12 days and then suddenly stops. Any solution would be appreciated .

**Comment by simongroenewolt** [comment]
This could be related to the maximum number of notifications on iOS. (64 as far as I know)

**Comment by prashant18-code** [comment]
Thanks for responding.
It should still work for atleast 30-40 days as we send notifications roughly twice a day. Also, the issue occurs on Android devices as well, not only on iOS. IS there any limit of notfication count on Android as well ??
