### ISSUE TITLE
Vibrating for a whole minute and crashing

### ISSUE THREAD

**Issue by AbayIbrayev** [katzer/cordova-plugin-local-notifications#1877]
The phone vibrates for a whole minute and either crashes or continues to work after the minute when trying to trigger the everyday notification.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version: MIUI 11.0.4
* Device manufacturer / model: Xiomi Redmi Note 8
* Cordova version (```cordova -v```): 9.0.0
* Cordova platform version (```cordova platform ls```): 8.1.0
* Plugin config "cordova-plugin-local-notification": {}
* Ionic Version (if using Ionic) 5.4.15

## Expected Behavior
receive notification 1 time when using trigger {every:  {hour: 12, minute: 0}}
## Actual Behavior
the phone vibrates for a whole minute and either crashes or continues to work after the minute passed eventually
## Steps to Reproduce
using trigger {every:  {hour: 12, minute: 0}} or any other minute (when I used every: ELocalNotificationTriggerUnit.MINUTE everything was alright, however, I really need that 12:00 notification)

  1. 
```
this.localNotifications.schedule({
        id: 1,
        title: "Hey, check this out!",
        text: `Don't forget to check out our daily deals & offers on our ${this.randomChosenCategory} products!`,
        trigger: { every: { hour: 10, minute: 30 } }
      });
```

## Context
Want to receive a scheduled notification every day at 12:00
## Debug logs
build is successful so there are not any error logs, however, it vibrates for a whole minute for some reason even though the notification appears in a normal way.

**Comment by NilLlisterri** [comment]
We are having the same issue. The app vibrates and receives endless notifications for a whole minute. In some devices it crashes after a few seconds with a StackOverflowError.

**Comment by AbayIbrayev** [comment]
@NilLlisterri unfortunately, they never responded to me, I actually already finished the app I was working on while they were responding. What I can suggest, as it is definitely their bug, you can just set it to send the notification daily and this issue will disappear, however it is sad that you cannot control the time when you receive it. If you find the solution send it to me pls.

**Comment by alphagamer7** [comment]
Facing same issue

**Comment by rahmadid** [comment]
Hi all, perhaps you can try this fork, it is more recent and still
maintained (to my knowledge):
https://github.com/timkellypa/cordova-plugin-local-notifications

Note:
-The fork also includes updates for Android 10.
-It uses androidx, so you might need cordova-plugin-androidx and/or
cordova-plugin-androidx-adapter plugins.

Hope it helps. Thanks.
