### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by jhgeluk** [katzer/cordova-plugin-local-notifications#1880]
Hi,

Is this repository still maintained? Or is there a fork that has updates?

This is full of issues and bugs!

**Comment by sts-ryan-holton** [comment]
@SaltyPotato I'm wondering exactly the same 👍

**Comment by SimonBrazell** [comment]
It hasn't had a new release in 2 years, try [this fork](https://github.com/Steffaan/cordova-plugin-local-notifications) instead.

**Comment by tomaz-dugii** [comment]
I want to know this to ?
