### ISSUE TITLE
onNotificationOpen() handler of cordova-plugin-firebase not triggered if this plugin is also installed

### ISSUE THREAD

**Issue by delwynpinto** [katzer/cordova-plugin-local-notifications#1882]
Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: MacOS
* OS version: 10.15.3
* Device manufacturer / model: Xiaomi Poco F1
* Cordova version (```cordova -v```): 8.0.1
* Cordova platform version (```cordova platform ls```): cordova-ios 5.0.1
* Plugin config 
* Ionic Version (if using Ionic): 3.9.2

## Expected Behavior
When a notification present in the notification tray of the device is clicked, the handler should be triggered.

## Actual Behavior
The handler is not triggered when the notification is clicked.

## Steps to Reproduce

  1. Install this plugin & cordova-plugin-firebase
  2. Send a push notification to the device
  3. Uninstall this plugin and try again

**Comment by Maqsyo** [comment]
Do you have the same problems with https://github.com/dpa99c/cordova-plugin-firebasex ?
cordova-plugin-firebase is known as buggy, so there is this new plugin which seems to work completely fine

**Comment by HansKrywaa** [comment]
Upgrade to `0.9.0-beta.3` worked for me

**Comment by delwynpinto** [comment]
@Maqsyo cordova-plugin-firebasex also has the same [issue](https://github.com/dpa99c/cordova-plugin-firebasex/issues/230)
