### ISSUE TITLE
weekday not working in Android

### ISSUE THREAD

**Issue by jonasmedeiros** [katzer/cordova-plugin-local-notifications#1884]
When I try to use weekday: 1 (any number until number 7) is not working

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: Android
* OS version: Android 6.0.1
* Device manufacturer / model: Samsung Galaxy J2, SM-G532MT
* Cordova version (```cordova -v```): 8.1.2
* Cordova platform version (```cordova platform ls```):  android 7.1.4
* Plugin config
* Ionic Version: 5.4.16

## Expected Behavior

Should Trigger the notification of week day

## Actual Behavior

Is not triggering at the week I add

## Steps to Reproduce

  1. Build a debug version using local notifications plugin
  2. Open debug console log at Chrome
  3. Add code bellow (you can choose date more close to you)
   ```
     cordova.plugins.notification.local.schedule({
        text: 'Testing',
        trigger: { every: { weekday: 2, hour: 9, minute: 12, second: 1}}
    });
```
  4. If you remove weekday: 2 will work fine, I tested adding weekdays for all days of the week does not work

Image of console on my testing.

![Screen Shot 2020-03-03 at 11 06 58](https://user-images.githubusercontent.com/13767309/75783322-272ffa80-5d3f-11ea-8f4f-9dd1224e9cce.png)

As you can see in the image when I use weekday is not adding to the list of schedule

**Comment by jonasmedeiros** [comment]
I had to get this working so I made the fix, I will open PR when I have more time.

https://github.com/jonasmedeiros/cordova-plugin-local-notifications/commit/a6cd9306946d65a5fa04db18a7a090801458b059

**Comment by webteambel** [comment]
Hi, I have the same problem on iOS too .. :(
