### ISSUE TITLE
IOS: Actions button not working

### ISSUE THREAD

**Issue by ksabariraj** [katzer/cordova-plugin-local-notifications#1885]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.3 
* Platform: IOS
* OS version: 13.3.1
* Device manufacturer / model: Iphone 6s
* Cordova version (```cordova -v```): 9.0.0
* Cordova platform version (```cordova platform ls```): 5.1.1
* Plugin config
* Ionic Version (if using Ionic) : 5.4.15

## Expected Behavior

Action button should visible

## Actual Behavior

Action button not visible

## Steps to Reproduce

I used the example code:

`(<any>window).cordova.plugins.notification.local.schedule({
            title: 'Local Notification Plugin',
            text: 'Made by appPlant from Leipzig/Germany',
            icon: 'file://img/icon.png?crop=cirlce',
            attachments: ['file://img/icon.png'],
            actionGroupId: 'like-dislike',
            trigger: {
                in: 10, unit: ELocalNotificationTriggerUnit.SECOND
            },
            actions: [{
                id: 'like',
                type: 'button',
                title: 'Like',
                launch: true
            },{
                id: 'dislike',
                type: 'button',
                title: 'Dislike',
                ui: 'decline'
            },{
                id: 'feedback',
                type: 'input',
                emptyText: 'Enter feedback',
                submitTitle: 'Send'
            }]
        });`

**Comment by rkjamvi** [comment]
Hi,
I am facing the same issue on iOS.

**Comment by thomasLS64** [comment]
Same problem here but little strange
I have defined 3 action group : 
```js
window.cordova.plugins.notification.local.addActionGroup('action-treatment', [
  { id: Constants.Notification.Events.Treatments.Taken, title: 'Prendre mon traitement' },
  { id: Constants.Notification.Events.Treatments.Reminder, title: 'Rappeler' },
  { id: Constants.Notification.Events.Treatments.Cancel, title: 'Pas besoin' }
])

window.cordova.plugins.notification.local.addActionGroup('action-risk', [
  { id: Constants.Notification.Events.Treatments.NewRisk, title: 'Oui, je continue la PrEP' },
  { id: Constants.Notification.Events.Treatments.Cancel, title: 'Je n\'ai pas pris de risque' }
])

window.cordova.plugins.notification.local.addActionGroup('action-reminder', [
  { id: Constants.Notification.Events.Reminders.Ok, title: 'Ok, j\'en ai pris connaissance' }
])
```

On Android all work fine
On iOS the first and third (`action-treatment` and `action-reminder`) definition not show buttons but the second (`action-risk`) show them

If someone have solution, I'm in 😸

**Comment by tommymetz** [comment]
Same problem here. Action buttons don't show up on iOS but fine on Android.

**Comment by AleksandarTokarev** [comment]
Any solution to this?

**Comment by bjdose** [comment]
Someone could resolve this issue? I've been trying to deal with it

**Comment by terryjiang2020** [comment]
Any update for this issue?

**Comment by ferd2009** [comment]
any resolution on this?
