### ISSUE TITLE
ionic localnotifications triggering problem on some devices 

### ISSUE THREAD

**Issue by julianlecalvez** [katzer/cordova-plugin-local-notifications#1887]
Hi !
I'm using this plugin since 2017 in one of my ionic application. Since my last upgrade in december, some users (more than usual) talked about notifications problem. They don't have any of my local notification. 
I checked the code a lot, with various hypotheses but notifications works on my test devices. 
Then, I started to suspect the battery optimizer system, and indeed, when I manually put the app in the battery optimizer system I don't receive the notifications. 
Is it a common problem that some of you have ? 

Also, in this last version, I increased significantly the number of programmed notifications. 
I had a maximum of 20 notifications before, and now it's more around 50 - 60. Could it be the problem ? 

## Your Environment

* Plugin version: 0.9.0-beta.3 
* Platform: mostly android (and some users on ios) 
* OS version: i asked and there's not a specific version 
* Device manufacturer / model: i asked and there's not a specific model 
* Cordova version (```cordova -v```): 9.0.0 
* Cordova platform version (```cordova platform ls```): android 8.0.0 // ios 4.5.5
* Plugin config
* Ionic Info (if using Ionic)
```
Ionic:
   ionic (Ionic CLI)  : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:
   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0, ios 4.5.5
   Cordova Plugins       : no whitelisted plugins (16 plugins total)

System:
   Android SDK Tools : 26.1.1 (/Users/julianlecalvez/Library/Android/sdk/)
   ios-deploy        : 1.9.1
   NodeJS            : v10.16.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS High Sierra
```

## Expected Behavior

Notifications should be triggered each time, on all devices.

## Actual Behavior

Some users don't have any notifications at all. 

## Steps to Reproduce

I wish I could find a way to reproduce it each time.

**Comment by ferryjagers** [comment]
I am experiencing the exact same thing.
The app I developed is used project based:

Last project, ran until the end of Januari 2020, with 400+ users:

- No reported notification issues with iOS at all.
- Quite some reported issues with Android, in almost all cases solved by instructing the user to disable the 'Battery Optimizer' for the app.

Current project with, started two weeks ago, 750+ (and counting) users:

- Already quite some notification issues with iOS reported.
- Not much reported notification issues with Android since I included the 'Battery Optimizer' suggestion in the FAQ.

I suspect that the iOS problems have something to do with the release of iOS 13.3.1/13.4 but I'm still not able to reproduce is on my own (simulated) devices. Notifications are scheduled on affected devices but randomly (some days they do, other days they dont) seem not to be triggered for some users.. Did you gain any insights since your post @julianlecalvez ?

```
Ionic:

   Ionic CLI          : 6.5.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : no whitelisted plugins (11 plugins total)

Utility:

   cordova-res	: 0.11.0
   native-run	: 0.3.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.14.1 (/usr/local/bin/node)
   npm        : 6.14.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.4 Build version 11E146
```

**Comment by julianlecalvez** [comment]
Hi @ferryjagers , 

Thanks for sharing your experience. It really helps ! I don't have more insights than you. 
I keep trying on different devices, and on android, I'm pretty sure the battery optimizer is the problem.

But on iOS, I didn't have any user reported issues about it in several weeks...

**Comment by julianlecalvez** [comment]
Hi again @ferryjagers !
I have a question for you. 
Do you use the "priority" and "foreground" setting when you schedule your notifications ? I didn't use it and I will activate them in the next release to see if it can have an impact.  

Also, I found this plugin : https://github.com/thomas550i/cordova-plugin-doze-Optimize to help detecting android users that are not ignoring the battery optimisation system, and take them to the correct device setting. 
But be careful because using this strategy is a recommendation only if the app matches the acceptable use cases for that : https://developer.android.com/training/monitoring-device-state/doze-standby#support_for_other_use_cases 

Cheers,

**Comment by julianlecalvez** [comment]
Hi everyone, 

I found where my problem come from. It's the way the notification system works in Android. 
There's a counter for each application with the number of notifications scheduled by this application.
If you schedule 1 notification, you'll have the counter at 1.
If you schedule 10, you'll have the counter at 10. But if you cancel the 10 notifications, and then reschedule 10 notifications, the counter will be at 20. 

My strategy was to schedule and cancel all the notification I planned at regular frequency AND each time the user changes a setting related to the notifications. 

My problem was that I reach the manufacturer limitation of the counter of scheduled notifications. 
For example, on my samsung S7 Edge and my Huawei p30 pro, the limit is 500 notifications, which means that when the number of 500 notifications scheduled is reach, no more notifications can be scheduled.

Even when you cancel some notifications, the counter doesn't decrease. It only decrease when the notification is triggered OR when the notification was supposed to trigger (if you canceled it). 
So with my strategy of canceling/rescheduling in mass, I planned some notifications 3 months in advance, and I would have to wait 3 months before the cancelation actually decrease the counter. 

Hope this is clear :) 

The command line `adb shell dumpsys alarm` allow to see notifications actually scheduled in the android system.

Cheers,
Julian
