### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException'

### ISSUE THREAD

**Issue by juanpasolano** [katzer/cordova-plugin-local-notifications#189]
I keep getting this error every time i try to create a new notification. I ma on iOS and don't know much Objective C

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
```

**Comment by clawish** [comment]
having the same error... Just using

    window.plugin.notification.local.add({ message: 'hello'});

after the `deviceready` event
