### ISSUE TITLE
iOS crash

### ISSUE THREAD

**Issue by theavijitsarkar** [katzer/cordova-plugin-local-notifications#1902]
I am getting the following crash reports from firebase crashlytics. Not sure what is causing them Attaching the dumps and my code.

## Your Environment

* Plugin version:0.9.0-beta.2 
* Platform: iOS
* OS version: 12., 13
* Device manufacturer / model: Apple
* Cordova version (```cordova -v```): 9.0.0
* Cordova platform version (```cordova platform ls```): android 8.1.0  ios 5.1.1
* Plugin config
```
 cordova.plugins.notification.local.schedule({
              title: 'Schedule Task',
              text: `${payload.task}`,
              trigger: { at: self.$moment(payload.date).toDate() }
            });
```

* Ionic Version (if using Ionic)

## Expected Behavior

Should not crash

## Actual Behavior

Crashing

## Steps to Reproduce

Unknown

## Context

This is a report from Crashlytics

## Debug logs
 
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1c0de7180 __exceptionPreprocess
1  libobjc.A.dylib                0x1bffbf9f8 objc_exception_throw
2  CoreFoundation                 0x1c0d039bc -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x1c0dec9c8 ___forwarding___
4  CoreFoundation                 0x1c0dee65c _CF_forwarding_prep_0
5  GoDial                         0x10058cefc -[APPNotificationOptions triggerDate] + 342 (APPNotificationOptions.m:342)
6  GoDial                         0x10058d2e8 -[APPNotificationOptions triggerWithDateMatchingComponents:] + 429 (APPNotificationOptions.m:429)
7  GoDial                         0x10058d050 -[APPNotificationOptions nonRepeatingTrigger] + 375 (APPNotificationOptions.m:375)
8  GoDial                         0x10058cd88 -[APPNotificationOptions trigger] + 306 (APPNotificationOptions.m:306)
9  GoDial                         0x10058bfc4 -[APPNotificationContent request] + 104 (APPNotificationContent.m:104)
10 GoDial                         0x10058abcc -[APPLocalNotification scheduleNotification:] + 464 (APPLocalNotification.m:464)
11 GoDial                         0x1005894e4 __33-[APPLocalNotification schedule:]_block_invoke + 102 (APPLocalNotification.m:102)
12 libdispatch.dylib              0x1c0824a38 _dispatch_call_block_and_release
13 libdispatch.dylib              0x1c08257d4 _dispatch_client_callout
14 libdispatch.dylib              0x1c07c9c80 _dispatch_queue_override_invoke
15 libdispatch.dylib              0x1c07d6030 _dispatch_root_queue_drain
16 libdispatch.dylib              0x1c07d68d4 _dispatch_worker_thread2
17 libsystem_pthread.dylib        0x1c0a061b4 _pthread_wqthread
18 libsystem_pthread.dylib        0x1c0a08cd4 start_wqthread

**Comment by moshi100** [comment]
I am facing the same issue, any suggestions?
