### ISSUE TITLE
Problem with version 0.9.0-beta 3 on android and ios using ionic

### ISSUE THREAD

**Issue by pitis** [katzer/cordova-plugin-local-notifications#1904]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9-beta3
* Platform: android and ios
* OS version: 10.15.4
* Device manufacturer / model: Macbook pro 
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic) 5.1

## Expected Behavior

On Android I cant even build the project because of deprecated functions.

On iOS i receive the notification if I'm in app, but if the app is inactive, I receive no notifications.
## Actual Behavior

_Tell us what happens instead_

I should be able to receive notifications even if I'm not in the app and should be able to use in android.

_Reproduce this issue; include code to reproduce, if relevant_

localNotifs.schedule({
          id: idNotif,
          title: `New message from ${data.message.chatData.sender.name}`,
          text: data.message.message,
          icon: data.message.chatData.sender.profileImg,
          foreground: true,
        })

## Context

Im trying to receive a notification when app is not active.

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: android\capacitor-cordova-android-plugins\src\main\java\de\appplant\cordova\plugin\notification\Notification.java:33: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat

**Comment by marcelo-ansaldi-baltazar** [comment]
I'm having the same problem when building on android :( did you find a solution or alternative? 

![image](https://user-images.githubusercontent.com/26723811/81871995-e75b6f80-9546-11ea-8d76-e6829cbb0570.png)

**Comment by pitis** [comment]
> I'm having the same problem when building on android :( did you find a solution or alternative?
> 
> ![image](https://user-images.githubusercontent.com/26723811/81871995-e75b6f80-9546-11ea-8d76-e6829cbb0570.png)

Yes, I found a solution on the Capacitor docs. You have to install jetifier. You can find more info here:

https://capacitor.ionicframework.com/docs/android/updating

Basically you need to update the project to AndroidX

**Comment by marcelo-ansaldi-baltazar** [comment]
u were right, thanks a lot !

**Comment by AmineAML** [comment]
Thanks for the solution!

**Comment by mrunwal** [comment]
Thanks worked
