### ISSUE TITLE
Encode HTML in text property does not work

### ISSUE THREAD

**Issue by rohankoliyal** [katzer/cordova-plugin-local-notifications#1907]
I need to have html encoded text as in to bold and underline the given text in Localnotification Payload "text" property

## Your Environment

* Plugin version:^0.9.0-beta.2
* Platform:android
* OS version:Windows 10
* Device manufacturer / model:Issue occurs in all device
* Cordova version (```cordova -v```):^8.1.0
* Cordova platform version (```cordova platform ls```):android 8.0.0
* Plugin config
* Ionic Version (if using Ionic)5.4.6

## Expected Behavior

The notficiation text as assigned in encode HTML

## Actual Behavior

The notficiation text shows html tags

this.localNotifications.schedule({
      // id: 1,
      foreground: true,
      title: "titleMessage",
      text: <b> asasassa </b>
});

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

I wanted to underline and bold text property of the payload

**Comment by juank525** [comment]
I have the same problem only when the app is in the foreground, but when the notification arrives and the app is in the background or closed it interprets the HTML correctly.

**Comment by Mickey-A-Mouse** [comment]
Recently I faced the same behavior. Any updates on this issue?
