### ISSUE TITLE
Set vibrate is false, but it has been vibrating at every update progress time

### ISSUE THREAD

**Issue by lei-xiaoming** [katzer/cordova-plugin-local-notifications#1908]
Set vibrate is false on the update progress bar,but it has been vibrating at every update progress time.

## Environment
* Plugin version:cordova-plugin-local-notification": "^0.9.0-beta.2"
* Platform:android
* OS version:10
* Device manufacturer / model:x5-LG
* Cordova version (```cordova -v```):9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (```cordova platform ls```):android 8.1.0
* Plugin config
    "cordova-plugin-badge": "^0.8.8",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-local-notification": "^0.9.0-beta.2",

## Expected Behavior
Should not vibrate when create schedule or update progress.

## Actual Behavior
It has been vibrating at every progress update progress time.

## Steps to Reproduce
  1. default set
```
      cordova.plugins.notification.local.setDefaults({
        id:1,
        sound:false,
        vibrate:false,
        title: 'title',
        text: "0%",
        progressBar: { value: 0}
      });
```

  2. create schedule
```
        cordova.plugins.notification.local.schedule({
          id:1,
          text: "0%",
          progressBar: { value: 0}
        });
 ```

  3. update progress
```
        cordova.plugins.notification.local.update({
          id:1,
          text: "50%",
          progressBar: { value: 50 }
        });
 ```
          
## Context
It has been vibrating when create schedule or update progress.

## Debug logs
[log.txt](https://github.com/katzer/cordova-plugin-local-notifications/files/4762133/log.txt)

**Comment by Zagrios** [comment]
Hi, I'm struggling with this issue too, has anyone found a solution? 
I'd like to clarify that first, the notification vibrates with every update, and secondly, I can't lock my smartphone because the notification also unlocks my screen with every update :/
