### ISSUE TITLE
Not Receiving attachment in background. Only receiving it when app is running in background.

### ISSUE THREAD

**Issue by codehack26** [katzer/cordova-plugin-local-notifications#1910]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: ^0.9.0-beta.2
* Platform: Android
* OS version: Android 10
* Device manufacturer / model: oneplus 5T
* Cordova version (```cordova -v```): 9.0.0
* Ionic Version (if using Ionic):4.12.0

## Expected Behavior
Not Receiving attachment in background. Only receiving it when the app is running in the background

## Actual Behavior
Should able to receive the attachment in the background when the app is closed.

## Code

  showNotificationWithImage(title:string,text:string,image:string){
    this.notification.schedule({
       id:1,
       title:title,
       text:text,
       attachments: ["https://cdn.craftbeer.com/wp-content/uploads/coffee2_hero.jpg"]
       vibrate:true,
       foreground: true,
       color:'#064ea2',
       smallIcon:'res://notification_icon',
    });
  }

**Comment by Fever905** [comment]
I noticed on iOS the attachment image does not come through..  I haven't tried it when the app is running in background.   The GPS function does work to trigger it, but no image is showing up.
