### ISSUE TITLE
Issues integrating this plugin in Ionic Cordova Windows UWP app

### ISSUE THREAD

**Issue by srinidhirao** [katzer/cordova-plugin-local-notifications#1911]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Local Notification does not integrate with a Windows 10 Cordova app using Ionic 5

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Windows 10
* OS version: Windows 10 Pro (Version 1903) OS Build 18362.900 
* Device manufacturer / model: Lenovo
* Cordova version (```cordova -v```):  9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (```cordova platform ls```): windows 7.0.1
* Plugin config
* Ionic Version (if using Ionic): @ionic/angular 5.2.2

## Expected Behavior

Since the plugin supports Windows platform, local Notification integrate and work

## Actual Behavior

Using the plugin fails with an exception

## Steps to Reproduce

Checkout the sample project at:
https://github.com/srinidhirao/windows10-local-notification-sample
The readme file has setup instructions.

1. Run the project in debug mode.
2. Click on 'Schedule Local Notification' button
3. The debugger displays the following error message:
```
Exception calling native with command :: LocalNotification :: schedule ::exception=WinRTError: The system cannot find the file specified.

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Toolkit.Uwp.Notifications, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at LocalNotificationProxy.LocalNotification.Builder.Build()
   at LocalNotificationProxy.LocalNotification.Manager.Schedule(Options[] notifications)
cordova.js (1051,13)
```

## Context

Adding Windows Platform to an existing ionic cordova app. 

## Debug logs

APPHOST9603: Can’t load the ActiveX plug-in that has the class ID '{D27CDB6E-AE6D-11CF-96B8-444553540000}'.  Apps can't load ActiveX controls.
index.html
The method Windows.UI.ApplicationSettings.SettingsPane.getForCurrentView has been deprecated. SettingsPane is deprecated and might not work on all platforms. For more info, see MSDN.
eval code (3) (1,7)
The event Windows.UI.ApplicationSettings.SettingsPane.add_CommandsRequested has been deprecated. SettingsPane is deprecated and might not work on all platforms. For more info, see MSDN.
eval code (4) (1,7)
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
vendor-es2015.js (72286,9)
adding proxy for StatusBar
cordova.js (1072,9)
adding proxy for Device
cordova.js (1072,9)
adding proxy for SplashScreen
cordova.js (1072,9)
adding proxy for Badge
cordova.js (1072,9)
adding proxy for LocalNotification
cordova.js (1072,9)
Ionic Native: deviceready event fired after 1926 ms
vendor-es2015.js (100707,13)
Exception calling native with command :: SplashScreen :: hide ::exception=TypeError: Unable to get property 'classList' of undefined or null reference
cordova.js (1051,13)
Test Notification Button Clicked
tab1-tab1-module-es2015.js (136,13)
Exception calling native with command :: LocalNotification :: schedule ::exception=WinRTError: The system cannot find the file specified.

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Toolkit.Uwp.Notifications, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at LocalNotificationProxy.LocalNotification.Builder.Build()
   at LocalNotificationProxy.LocalNotification.Manager.Schedule(Options[] notifications)
cordova.js (1051,13)

**Comment by MarcMenghin** [comment]
Same problem with our App, still on Ionic 3. 

As a workaround, I modified the plugin.xml to directly include the project (`LocalNotificationProxy`) and add the missing reference (`Microsoft.Toolkit.Uwp.Notifications`).
