### ISSUE TITLE
Unable to build with cordova-plugin-firebase-messaging

### ISSUE THREAD

**Issue by jringbox** [katzer/cordova-plugin-local-notifications#1913]
## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: android
* OS version: API 29
* Device manufacturer / model: N/A
* Cordova version (```cordova -v```): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (```cordova platform ls```):  android 8.1.0
* Plugin config: N/A
* Ionic Version (if using Ionic): N/A

## Expected Behavior

Build without error.

## Actual Behavior

When I performed a "cordova build android", I got the following error.

```
D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver
```

## Steps to Reproduce

Create a cordova project with android platform and add the following plugins.

```
cordova plugin add cordova-support-google-services
cordova plugin add cordova-plugin-firebase-messaging
cordova plugin add cordova-plugin-local-notifications
cordova build android
```

## Context

Build my android application with cordova command.

## Debug logs

N/A

**Comment by feronimus** [comment]
I have exacly the same problem!

**Comment by jringbox** [comment]
Awesome.  That fixed it!
