### ISSUE TITLE
How to Set Trigger to Repeat Every 5 Minutes 

### ISSUE THREAD

**Issue by GitFr33** [katzer/cordova-plugin-local-notifications#1916]
Is there any way to make this plugin repeat every time a user-defined number of minutes has elapsed.

I have not figured out how (or if) it's possible to set the trigger object to accomplish this. 
At first I thought that the `count` element was all I needed but experimenting showed that this is the number of _times_ to repeat, not the number of _units_ between repeats.

I tried to combine the `every` and `in` elements in various ways (`{ every: { in: 5, unit: 'minute' }, count: -1 }`) but I haven't found a solution.

**Comment by GitFr33** [comment]
I discovered that this possible, though the correct syntax is not covered in the README 
`trigger = { every: parseInt(5),  unit: 'MINUTE' };` works, at least on Android.

What was causing the problem for me was partially that a numeric value of `every` must be of the type int for the trigger to work.

I hope this helps someone else.

**Comment by hnguyen48206** [comment]
May you explain more about the count here, does it mean the total number of notifications that will be fired, in this case 500 messages for 500 minutes, one for every minute? Thank you.

**Comment by GitFr33** [comment]
It seems that it means (on Android) the total number of notifications that will be fired. 
So in this case 500 notifications. One every 5 minutes. (for a total of 2500 Minutes.)
