### ISSUE TITLE
Trouble with sounds on iOS and Android

### ISSUE THREAD

**Issue by jondspa** [katzer/cordova-plugin-local-notifications#1917]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

It's a great plugin, been using for years!  Thanks!  But having trouble with custom sounds.  Just get standard device notification sounds instead of my custom sounds.

Any help would be most appreciated!
  - Jon

## Your Environment

* Plugin version: Steffaan version 0.9.3
* Platform: Android and iOS
* OS version: iOS 13, Android 6, 7, 8, 9
* Device manufacturer / model: iPhone and several models on Android
* Cordova version (```cordova -v```): 9.0.0 for both iOS and Android
* Cordova platform version (```cordova platform ls```): android 8.0.1 and iOS 4.2.1
* Plugin config
* Ionic Version (if using Ionic) N/A
## Expected Behavior

Notifications would play a custom sound and not the standard phone notification sound
## Actual Behavior

Plays standard phone notification sound
## Steps to Reproduce

 Android
    soundFile: `file://assets/ding.mp3'
      also tried 'res://ding.mp3'
      also tried 'file:///android_asset/www/assets/ding.mp3'

 iOS
        soundFile = "assets/ding.mp3",

          singleObj = {
                    channel: "channel1",
                    id: 100 + m,
                    text: String(reminders[n][0]),
                    priority: 2,
                    foreground: true,
                    sound: soundFile,
                    
                    trigger: {
                        every: {
                            weekday: Number(reminders[n][1][n1]) + 1, // days 1-7
                            hour: Number(reminders[n][2][0]),
                            minute: Number(reminders[n][2][1])
                        },
                        count: 1
                    }
                }

**Comment by GitFr33** [comment]
I was having a similar problem on newer versions of android. I resolved it by switching to timkellypa's version #1891
