### ISSUE TITLE
App crashes with URL icon or attachment

### ISSUE THREAD

**Issue by jabelcs** [katzer/cordova-plugin-local-notifications#1919]
Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Android and iOs
* OS version: Android 8.1.0, iOs 13.6
* Device manufacturer / model: Android tablet Lenovo TB-8504F, iphone XR
* Cordova version (```cordova -v```): 10.0.0
* Cordova platform version (```cordova platform ls```): Android 9.0.0, iOs 6.1.0
* Plugin config

## Expected Behavior
Show notification with icon and attachment from URL.

## Actual Behavior

I'm using visual studio code to develop the app.

On Android:
Using URL on icon and attachment crashes app.
If I uninstall and reinstall the plugin the notification works and shows the icon and attachment from URL then if I debug the app one second time the app crashes.

On iOs:
Always showing "file not found" when I know the file exists on the server.

## Steps to Reproduce

Code used:
cordova.plugins.notification.local.schedule({
	title: 'Olá!',
	text: 'Bem vindo(a) à sua aplicação de acompanhamento nutricional.',
	vibrate: true,
	smallIcon: 'res://notification_icon',
	icon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzfXKe6Yfjr6rCtR6cMPJB8CqMAYWECDtDqH-eMnerHHuXv9egrw',
	attachments: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzfXKe6Yfjr6rCtR6cMPJB8CqMAYWECDtDqH-eMnerHHuXv9egrw'],
	foreground: true
});

  1. Uninstall plugin
  2. Reinstall plugin
  3. Debug the app - all goes well
  4. Stop debugging
  5. Start debugging
  6. App crashes on android
  7. on iOs always saying "File not found: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzfXKe6Yfjr6rCtR6cMPJB8CqMAYWECDtDqH-eMnerHHuXv9egrw"

## Context

_What were you trying to do?_

## Debug logs

Android logs:
08-20 00:48:14.045 12502 12599 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-3
08-20 00:48:14.045 12502 12599 E AndroidRuntime: Process: pt.gooddiet.app, PID: 12502
08-20 00:48:14.045 12502 12599 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:584)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:558)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.notification.util.AssetUtil.getUriFromFile(AssetUtil.java:365)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.notification.util.AssetUtil.getUriFromRemote(AssetUtil.java:214)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.notification.util.AssetUtil.parse(AssetUtil.java:93)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.notification.Options.getLargeIcon(Options.java:355)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.notification.Builder.build(Builder.java:159)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.localnotification.TriggerReceiver.buildNotification(TriggerReceiver.java:120)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.notification.receiver.AbstractTriggerReceiver.onReceive(AbstractTriggerReceiver.java:60)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.notification.Notification.trigger(Notification.java:254)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.notification.Notification.schedule(Notification.java:206)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.notification.Manager.schedule(Manager.java:100)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.localnotification.LocalNotification.schedule(LocalNotification.java:273)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.localnotification.LocalNotification.access$400(LocalNotification.java:60)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:145)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-20 00:48:14.045 12502 12599 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
08-20 00:48:14.064   969  3515 W ActivityManager:   Force finishing activity pt.gooddiet.app/.MainActivity
08-20 00:48:14.066   969  3515 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
08-20 00:48:14.067 12502 12502 D CordovaActivity: Paused the activity.
08-20 00:48:14.079   969  1976 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{8136da0 com.lenovo.launcher} is now in focus and seems to be in full-screen mode
08-20 00:48:14.079   969  1976 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.lenovo.launcher/com.android.launcher3.Launcher/3000010
08-20 00:48:14.086  1995  2223 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
08-20 00:48:14.087  1995  2223 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
08-20 00:48:14.097   969   984 W AppErrorDialog: blockSize=4096,,availableBlocks=842301
08-20 00:48:14.097   969   984 W AppErrorDialog: memory=3450064896
08-20 00:48:14.097   969   984 I ActivityManager: Showing crash dialog for package pt.gooddiet.app u0
08-20 00:48:14.100  1995  1995 V Launcher: Launcher.onResume()
08-20 00:48:14.100  1995  2063 D NotificationListener: handleMessage->3
08-20 00:48:14.102  1995  1995 D Launcher: Deferring update until onResume
08-20 00:48:14.104   969   983 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
08-20 00:48:14.106  1995  1995 D Launcher: Time spent processing callbacks in onResume: 1
08-20 00:48:14.106  1995  1995 D Launcher: Time spent in onResume: 6
08-20 00:48:14.106   969  1529 D CompatibilityInfo: mCompatibilityFlags - 4
08-20 00:48:14.107   969  1529 D CompatibilityInfo: applicationDensity - 213
08-20 00:48:14.107   969  1529 D CompatibilityInfo: applicationScale - 1.0
08-20 00:48:14.107  1995  1995 D AllAppsContainerView: NavBarBg:16,200
08-20 00:48:14.107  1995  2063 D NotificationListener: filterNotifications->6
08-20 00:48:14.108   969   983 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
08-20 00:48:14.118  1995  2223 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
08-20 00:48:14.122  1995  2223 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
08-20 00:48:14.125  1349  1349 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3162 
08-20 00:48:14.126  1349  1349 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1831 
08-20 00:48:14.130   969  1529 D CompatibilityInfo: mCompatibilityFlags - 4
08-20 00:48:14.130   969  1529 D CompatibilityInfo: applicationDensity - 213
08-20 00:48:14.130   969  1529 D CompatibilityInfo: applicationScale - 1.0
08-20 00:48:14.133   969  1529 D CompatibilityInfo: mCompatibilityFlags - 4
08-20 00:48:14.133   969  1529 D CompatibilityInfo: applicationDensity - 213
08-20 00:48:14.133   969  1529 D CompatibilityInfo: applicationScale - 1.0
08-20 00:48:14.150   969  4765 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 08/23/18, 26560a1, I77d3059488
08-20 00:48:14.150   969  4765 I zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
08-20 00:48:14.151   969  4765 I OpenGLRenderer: Initialized EGL, version 1.4
08-20 00:48:14.151   969  4765 D OpenGLRenderer: Swap behavior 2
08-20 00:48:14.156   969  4765 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
08-20 00:48:14.158   969  4765 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
08-20 00:48:14.160   969  4765 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
08-20 00:48:14.170 12502 12566 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
08-20 00:48:14.479 12502 12566 I chatty  : uid=10208(pt.gooddiet.app) RenderThread identical 2 lines
08-20 00:48:14.481 12502 12566 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
08-20 00:48:14.481 12502 12502 D CordovaActivity: Stopped the activity.
08-20 00:48:14.483 12502 12502 D CordovaActivity: CordovaActivity.onDestroy()

iOs logs:
2020-08-20 00:44:55.324270+0100 GoodDiet[39263:3895591] File not found: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzfXKe6Yfjr6rCtR6cMPJB8CqMAYWECDtDqH-eMnerHHuXv9egrw

**Comment by Risi1997** [comment]
hii @jabelcs are you able to solve it?

**Comment by rahmadid** [comment]
@jabelcs that fork uses androidx, perhaps the error related to it?
