### ISSUE TITLE
Not able to capture the trigger event

### ISSUE THREAD

**Issue by GitFr33** [katzer/cordova-plugin-local-notifications#1920]
I am not able to capture the `trigger` event. I am using the following code but the console does not output `notification trigger` when a notification is triggered.

```
function onNotificationTrigger(){
  console.log('notification trigger');
}
cordova.plugins.notification.local.on('trigger',onNotificationTrigger);
```
The callback runs when I execute `cordova.plugins.notification.local.fireEvent('trigger', {});`

## Your Environment

* Plugin version: 0.9-beta.4 (https://github.com/timkellypa/cordova-plugin-local-notifications.git) #1891
* Platform: Android
* OS version: Android 7.1.1
* Device manufacturer / model: Alcatel tablet model 9024W
* Cordova version: 10.0.0
* Cordova platform version: android 9.0.0
* Plugin config:
```actions: Array(2)
0: {id: "pause", title: "Pause"}
1: {id: "reset", title: "Reset"}
alarmVolume: -1
attachments: []
autoClear: false
autoLaunch: false
channel: "remindful"
clock: true
defaults: 0
foreground: false
fullScreenIntent: false
groupSummary: false
id: 1
launch: true
led: true
lockscreen: true
meta: {plugin: "cordova-plugin-local-notification", version: "0.9-beta.4"}
number: 0
priority: 0
progressBar: {enabled: false, value: 0, maxValue: 100, indeterminate: false}
resetDelay: 5
silent: false
smallIcon: "res://mipmap-xxxhdpi/ic_launcher.png"
sound: "file://audio/large-bell-short.mp3"
text: "Set for 1 minutes, on repeat."
timeoutAfter: null
title: "Remindful Bell"
trigger: {in: 1, unit: "MINUTE", type: "calendar"}
triggerInApp: false
vibrate: false
wakeup: true
```
* Ionic Version (if using Ionic) not using ionic

## Expected Behavior

console should log 'notification trigger' when a notification is triggered. 

## Actual Behavior

_Tell us what happens instead_

## Steps to Reproduce

define 
`function onNotificationTrigger(){
  console.log('notification trigger');
}`

on device ready add
`cordova.plugins.notification.local.on('trigger',onNotificationTrigger);`

schedule a notification with a trigger.

**Comment by abeledovictor** [comment]
Could reproduce on iPhone 8 only when phone is blocked or app not active

**Comment by abeledovictor** [comment]
@katzer any ideas on why it isn't working? I think it's not a bug specific to android
