### ISSUE TITLE
Android 9 app crash - Attempt to invoke virtual method android.content.res.XmlResourceParser

### ISSUE THREAD

**Issue by sts-ryan-holton** [katzer/cordova-plugin-local-notifications#1922]
On Android 9, when trying to trigger a notification the app crashes and logs the following:

```
Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
```

This is with the latest version of this plugin!

**Comment by rahmadid** [comment]
hi all, perhaps you can try this fork, it is more recent and still maintained:
https://github.com/timkellypa/cordova-plugin-local-notifications

hope it helps. thanks.

**Comment by sts-ryan-holton** [comment]
I'll give it a go, but the plugin seemingly worked up until recently, so I'm lost as to why it would suddenly stop working

**Comment by sts-ryan-holton** [comment]
@rahmadid Just tried that fork, get: `Execution failed for task ':app:compileDebugJavaWithJavac'.` error when trying to build for Android.

**Comment by rahmadid** [comment]
@sts-ryan-holton that fork uses androidx, perhaps the error related to it? or maybe you could ask/open an issue in that repo.

**Comment by sts-ryan-holton** [comment]
@rahmadid I resolved this error by using that fork and enabling Android X.
