### ISSUE TITLE
How to cancel a schedule notification

### ISSUE THREAD

**Issue by aavelyn** [katzer/cordova-plugin-local-notifications#1923]
I couldn't find anything in the docs so is there a way to **cancel already scheduled** notifications?

My use case is simple. I want to show a local notification after 7 days if user hasn't opened the app since.
So everytime the app is closed or goes into the background I want to schedule that notification and every time the app opens I want to remove that notification.

Thanks for the help

**Comment by ferreria23** [comment]
What about `cordova.plugins.notification.local.cancel(notificationId)`?

**Comment by aavelyn** [comment]
Ah thanks!
