### ISSUE TITLE
Plugin is breaking `on('notification')` event of phonegap-plugin-push

### ISSUE THREAD

**Issue by anujraghuvanshi** [katzer/cordova-plugin-local-notifications#1924]
## My Environment

* Plugin version:  0.9.0-beta.2
* Platform: iOS
* OS version: iOS 14
* Device manufacturer / model: iPhone XR
* Cordova version (```cordova -v```): v10.0.0
* Cordova platform version (```cordova platform ls```): ios 6.0.0
* Ionic Version (if using Ionic): 5.4.16

## Expected Behavior

It should let `on('notification')` work so that I can schedule local notification.

## Actual Behavior

It should handle its own responsibility, After adding latest version of this plugin which I've mention above, It stops trigerring `on('notification')` event of `phonegap-plugin-push`

## Steps to Reproduce

  1. Install latest versions of both plugins
  2. Give try catching `on('notification')` event 
  3. It will not work.

## Context

- Want  to schedule local notification once notification is catched from `phonegap-plugin-push`

## Related thread 
- https://github.com/phonegap/phonegap-plugin-push/issues/2724

**Comment by incapsulatesshamala** [comment]
Any update in this fix?

**Comment by Anuj-Raghuvanshi** [comment]
Hi @incapsulatesshamala - Give a try by installing plugin by this url 
- https://github.com/katzer/cordova-plugin-local-notifications.git#0.9.0-beta.0

Hope it will work for you too as I have managed by this.

**Comment by incapsulatesshamala** [comment]
@Anuj-Raghuvanshi Thanks for the response. 

It is not working for me, May be because i am using ionic3

**Comment by Anuj-Raghuvanshi** [comment]
Have you checked the version of installed plugin ? Is it `0.9.0-beta.0` ? I think it should work if this version is installed.
