### ISSUE TITLE
Notifications not received

### ISSUE THREAD

**Issue by AleksandraMikic** [katzer/cordova-plugin-local-notifications#1931]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Samsung, SM-A510F
* Cordova version (```cordova -v```): 10.0.0
* Cordova platform version (```cordova platform ls```): Android 8.1.0
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Hi, users of the app should receive 7 notifications per day.

## Actual Behavior

Notifications are normally scheduled, but they do not appear according to plan (e.g. only 2 out of 7 are received), or they do not appear at all. This happens on few smart devices, on others they come normally. 

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. cordova.plugins.notification.local.schedule([
                {icon: 'ic_launcher', id: a, text: 'Es ist Zeit für die nächste Befragung!', title: 'IPU-Umfrage 1', trigger: {at: new Date(epoch1)} }, 
                {icon: 'ic_launcher', id: b, text: 'Es ist Zeit für die nächste Befragung!', title: 'IPU-Umfrage 2', trigger: {at: new Date(epoch2)} }, 
                {icon: 'ic_launcher', id: c, text: 'Es ist Zeit für die nächste Befragung!', title: 'IPU-Umfrage 3', trigger: {at: new Date(epoch3)} }, 
                {icon: 'ic_launcher', id: d, text: 'Es ist Zeit für die nächste Befragung!', title: 'IPU-Umfrage 4', trigger: {at: new Date(epoch4)} }, 
                {icon: 'ic_launcher', id: e, text: 'Es ist Zeit für die nächste Befragung!', title: 'IPU-Umfrage 5', trigger: {at: new Date(epoch5)} }, 
                {icon: 'ic_launcher', id: f, text: 'Es ist Zeit für die nächste Befragung!', title: 'IPU-Umfrage 6', trigger: {at: new Date(epoch6)} },
                {icon: 'ic_launcher', id: g, text: 'Es ist Zeit für die nächste Befragung!', title: 'IPU-Umfrage 7', trigger: {at: new Date(epoch7)} }
                
            ]);
            console.log("Day:");
            console.log("i="+i);
  2. ...
  3. ...
  4. ....

## Context

It functioned pretty well, then the code for notifications was changed in order to adapt randomisation, and now it doesn´t.

## Debug lo

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by HafizAhmedMoon** [comment]
@AleksandraMikic have you found anything to solve this issue?

**Comment by AleksandraMikic** [comment]
We changed the reverse domain-style identifier, the app and the notifications names and now notifications are received normally.

**Comment by HafizAhmedMoon** [comment]
@AleksandraMikic can you provide more info, what you changed in the package id of the app and the notification?
