### ISSUE TITLE
open current notification content, no next

### ISSUE THREAD

**Issue by iecxiv** [katzer/cordova-plugin-local-notifications#1933]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: Version 0.8.5 (22.05.2017)
* Platform: Cordova Android Application
* OS version: Android
* Device manufacturer / model:
* Cordova version (```cordova -v```): 10.0.0
* Cordova platform version (```cordova platform ls```): android 9.0.0  
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

i schedule a notification inmediately, then scheduled (updated) same notify every 6 second. every notification has a content stored on a variable seted with Math.floor(Math.random() *. Then on clicking notification notify text is appended to a bodys paragraph >> $('.quote').empty().append(notesaved); 

_Tell us what should happen_

i need to click on notification and set paragraph content of CURRENT notification.

## Actual Behavior

when i click notification paragraphs content setted to NEXT notification content.

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

CODE: 
``var app = {
    // Application Constructor
    initialize: function () {
        this.bindEvents();
    },
    // Bind Event Listeners
    //
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function () {
        document.addEventListener('deviceready', this.onDeviceReady, false);
        document.addEventListener("backbutton", this.onBackKeyDown, false);
    },
    // deviceready Event Handler
    //
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicitly call 'app.receivedEvent(...);'
    onDeviceReady: function () {
            app.addListeners();
            app.randomGenerate();
        // continue application initialization
        app.receivedEvent('deviceready');
    },
    // Update DOM on a Received Event
    receivedEvent: function (id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    },
    // Displays an alert dialog containing a message. 
    onBackKeyDown: function (e) {
        //if (confirm("¿Desea salir de la aplicación?") == true){
        //    navigator.app.exitApp();
        //}
        var lastTimeBackPress=0;
        var timePeriodToExit=2000;
        e.preventDefault();
        e.stopPropagation();
        if(new Date().getTime() - lastTimeBackPress < timePeriodToExit){
            navigator.app.exitApp();
        }else{
            demo.notify("Pulsa atrás dos veces para salir.");
            lastTimeBackPress=new Date().getTime();
        }
    },
    addListeners: function () {
        //document.querySelector("#add-btn").addEventListener("click", app.addNote);
        checkbox = document.getElementById('customCheck1');
        checkbox.addEventListener('change', e => {
            if(e.target.checked){
                app.addNote();
                //navigator.notification.alert("scheduled");
            }else{
                cordova.plugins.notification.local.cancelAll();
                //navigator.notification.alert("canceled");
            }
        });
        cordova.plugins.notification.local.on("click", function (notification) {
            //navigator.notification.alert("clicked: " + notification.id);
            console.log(notification.data);
            //$('.quote').empty().append(ramQuoteNoty);
            var notesaved = localStorage.getItem('note');
            $('.quote').empty().append(notesaved);
            if (notification.id == 11) {
            //    $('.quote').empty().append(ramQuoteNoty);
                //navigator.notification.alert("clicked: " + notification.id);
            }
        });
        cordova.plugins.notification.local.on("trigger", function (notification) {
            //navigator.notification.alert("triggered: " + notification.id);    
            let noteOptions = {
                id: 11,
                title: "Buenos días",
                text: ramQuoteNoty,
                //at: inOneMin,
                trigger: { every: 6, unit: 'second' },
                badge: 1,
                icon: 'file://img/icon.png',
                data: {
                    prop: "prop value",
                    num: 42
                }
            };
            localStorage.setItem('note', ramQuoteNoty);
            cordova.plugins.notification.local.schedule(noteOptions, function(note){
                var randomQuoteNoty;
                $.getJSON('data.json',function(quotes){
                    randomQuoteNoty = quotes.quotes[Math.floor(Math.random() * quotes.quotes.length)];      
                    ramQuoteNoty = randomQuoteNoty.quote;  
                });
                //localStorage.setItem('note', ramQuoteNoty);
                //$('.quote').empty().append(ramQuoteNoty);
            });        
        });
    },
    randomGenerate: function (){
        var randomQuoteNoty;
        $.getJSON('data.json',function(quotes){
            randomQuoteNoty = quotes.quotes[Math.floor(Math.random() * quotes.quotes.length)];      
            ramQuoteNoty = randomQuoteNoty.quote;  
        });
        localStorage.setItem('note', ramQuoteNoty);
        //$('.quote').empty().append(ramQuoteNoty);
    },
    addNote: function (ev) {
        let props = cordova.plugins.notification.local.getDefaults();
        //let inOneMin = new Date();
        //inOneMin.setMinutes(inOneMin.getMinutes() + 1);
        //let id = new Date().getMilliseconds();
        let noteOptions = {
            id: 11,
            title: "Buenos días",
            text: ramQuoteNoty,
            //at: inOneMin,
            //trigger: { every: 6, unit: 'second' },
            badge: 1,
            icon: 'file://img/icon.png',
            data: {
                prop: "prop value",
                num: 42
            }
        };
        localStorage.setItem('note', ramQuoteNoty);
        cordova.plugins.notification.local.schedule(noteOptions, function(note){
            var randomQuoteNoty;
            $.getJSON('data.json',function(quotes){
                randomQuoteNoty = quotes.quotes[Math.floor(Math.random() * quotes.quotes.length)];      
                ramQuoteNoty = randomQuoteNoty.quote; 
            });
            //localStorage.setItem('note', ramQuoteNoty);
            //$('.quote').empty().append(ramQuoteNoty);
        });
    
        //navigator.notification.alert("Added notification id " + id);
        //navigator.notification.alert("ram " + ramQuote);
    
        cordova.plugins.notification.local.cancel(id, function () {
        });
        cordova.plugins.notification.local.clear(id, function () {
        });
        cordova.plugins.notification.local.isPresent(id, function (present) {
        });
    
      }
};

app.initialize();``

_What were you trying to do?_

im trying implementing localstorage to show notification on paragraph (notesaved) instead of ramQuoteNoty variable, but same with and without localstorage.

**Comment by iecxiv** [comment]
https://tetsiapp.com/vid/currentNEXT.mp4  <<-- Here what happens!

**Comment by iecxiv** [comment]
solved removing var notesaved = localStorage.getItem('note'); from click trigger.
and adding notesaved = localStorage.getItem('note'); to trigger.

**Comment by iecxiv** [comment]
now when i uncheck checkbox and check again shows only first notification, not others...

**Comment by iecxiv** [comment]
code: https://controlc.com/7ee35ba1
password controlc paste >>   12345678

**Comment by manel00** [comment]
> https://tetsiapp.com/vid/currentNEXT.mp4 <<-- Here what happens!

Hola colega! como has conseguido que funcione las local notifications en iOS? Gracias ;)

**Comment by iecxiv** [comment]
it is android men!

**Comment by manel00** [comment]
I know, I meant if you achieved it on iOS, eskerrik asko!

**Comment by iecxiv** [comment]
no, i dont achieved it on iOS. nahi baduzu frogatu iOSen pasatuko dizut kodea edo kompilatu dezaket iOS paquetea froga dezazun. nola ematen dizut kodea?

**Comment by manel00** [comment]
No gracias! y disculpa solo se decir eso en euskera y alguna cosa mas! ;)

**Comment by iecxiv** [comment]
if you need the code of the example, say here. is for cordova framework and is very simple

**Comment by manel00** [comment]
Ok to be honest... okey can you post your example on the code? just to know how you call it, thank you.

Mine is:

**APPCOMPONENT.TS**
```
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();

      this.fcm.getToken().then(token => {
        this.myToken = token
      });

      this.fcm.onNotification().subscribe(data => {
        this.utils.requestLocalNotif(data)
      });
...
```

UTILS.TS

```
requestLocalNotif(data) {
    this.enableBGMode()

    this.localNotifications.requestPermission().then(() => {
      this.showLocalNotification(data)
    })

  }

  showLocalNotification(data) {
    this.localNotifications.schedule({
      id: 1,
      title: data.title,
      text: data.body,
      vibrate: true,
      attachments:'',
      led: { color: '#FF00FF', on: 500, off: 500 },
      foreground: true
    });
  }
```

**Comment by iecxiv** [comment]
you can take a look here: https://github.com/iecxiv/frase-notificaciones
is unfinished app
is cordova based

**Comment by manel00** [comment]
Thank you sir, I am sorry but it is not what I am looking for! So kind ;)
