### ISSUE TITLE
resource xml/localnotification_provider_paths not found on build Android

### ISSUE THREAD

**Issue by Houdhey** [katzer/cordova-plugin-local-notifications#1936]
* Plugin version: @ionic-native/local-notifications": "^5.30.0
* Platform: Android
* OS version: Android 7, Android 10, All Android globally
* Device manufacturer / model: Non necessary for this problem, android build
* Cordova version (```cordova -v```): Capacitor 2.2.0   cordova 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (```cordova platform ls```):  
* android ^8.0.0
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0

* Plugin config
* Ionic Version (if using Ionic) : 5.4.16

## Expected Behavior

When doing build command  gradlew assembleRelease to build an APK, it should finish with a "Successful"

## Actual Behavior

The build process is interrupted with this error : 

```
_* What went wrong:
Execution failed for task ':capacitor-cordova-android-plugins:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     C:\Users\\Desktop\app-dev\android\capacitor-cordova-android-plugins\src\main\AndroidManifest
.xml:7:3-112: AAPT: error: resource xml/localnotification_provider_paths (aka capacitor.android.plugins:xml/localnotific
ation_provider_paths) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13s
117 actionable tasks: 2 executed, 115 up-to-date_
```

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ionic build
  2. npx cap copy android
  3. npx cap open android
  4. in Terminal, cd android, gradlew assembleRelease

## Context

Build an APK for Android.

**Comment by Houdhey** [comment]
I don't know why but the file was missing here : 

![image](https://user-images.githubusercontent.com/44744194/102495684-b01de580-4076-11eb-9a20-30ce143653ca.png)

We shouldn't have this kind of bugs...
For anyone meeting this problem (and you'll definitely meet it some day), I just added (or created) this file in the xml repository inside the capacitor-cordova-android-plugins  folder.
The file appears in the android/res/xml  but not in the capacitor cordova android plugins folder.

**Comment by dm185353** [comment]
.

**Comment by smahdis** [comment]
@Houdhey What should put as their content?

**Comment by Houdhey** [comment]
> @Houdhey What should put as their content?

Nothing, I think it was empty, it's just has to be same name as asked by the plugin
