### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by zoranmil** [katzer/cordova-plugin-local-notifications#1940]
replace complie to implementation
localnotification.gradle for android

**Comment by wimZ** [comment]
Please fix, 
How long will 'compile' be just a warning before it is no longer supported?,

**Comment by alimdi** [comment]
Any news on fixing this?

**Comment by acommend** [comment]
This plugin will not work with Gradle v7+ since 'compile' was removed in v7: https://docs.gradle.org/current/userguide/upgrading_version_6.html
