### ISSUE TITLE
Is it possible to get more information from launch details after notification click?

### ISSUE THREAD

**Issue by Smokolisz** [katzer/cordova-plugin-local-notifications#1944]
Is it possible to get more information about notification on click?

cordova + framework7

* Plugin version: cordova 10.0.0
* Platform: cordova 10.0.0
* OS version: Android 9
* Device manufacturer / model: LG v30
* Cordova version (```cordova -v```): 10.0.0
* Cordova platform version (```cordova platform ls```): android 9.0.0

## Expected Behavior

Add more information to notification object, get the information on app start

## Actual Behavior

After notification click and app start the object has only id and event name

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

`          
        //create notif (how to add more info which i can get on app start after notification click?
        cordova.plugins.notification.local.schedule({
        title: 'Za 10 minut rozpoczyna się zaplanowana jazda',
        text: time[0]+':'+time[1] + ' - ' + time[2]+':'+time[3],
        actions: [{ id: 'ride_start', title: 'Rozpocznij' }],
        trigger: { at: dateStart }
        });

         //on app start get the data (now it only contains id and event name)
        console.log("LAUNCH DETAILS", cordova.plugins.notification.local.launchDetails, cordova.plugins.notification.local);
`

## Context

I want to get more information about notification at app start after notification click

**Comment by leuphana** [comment]
I am doing it like this:

```
{
  id: 19,
  title: "X",
  text: "Y",
  trigger: {at: dt19},
  icon: "res://icon",
  smallIcon: "res://icon",
  data: {i:19, heading: 'My heading', subheading: 'My subheading', displayedtext: 'Foo Bar, XXX!'}
}

cordova.plugins.notification.local.on("click", function (notification) {
  var objects = notification.data;
  // My data is now available in objects.heading, objects.subheading and so on.
  console.log(objects.displayedtext);
});
`

**Comment by Smokolisz** [comment]
Thank you very much @leuphana !! You saved me!

**Comment by ghonche-yqr** [comment]
> I am doing it like this:
> 
> ```
> {
>   id: 19,
>   title: "X",
>   text: "Y",
>   trigger: {at: dt19},
>   icon: "res://icon",
>   smallIcon: "res://icon",
>   data: {i:19, heading: 'My heading', subheading: 'My subheading', displayedtext: 'Foo Bar, XXX!'}
> }
> 
> cordova.plugins.notification.local.on("click", function (notification) {
>   var objects = notification.data;
>   // My data is now available in objects.heading, objects.subheading and so on.
>   console.log(objects.displayedtext);
> });
> `
> ```

Does this work when the app is closed?
