### ISSUE TITLE
Notification not triggered in iOS when app in background

### ISSUE THREAD

**Issue by iliyaST** [katzer/cordova-plugin-local-notifications#1945]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

Plugin version: 0.9.0-beta.2
Platform: iOS
OS version: 11.2
Device manufacturer / model: iphone 8
Cordova version (cordova -v): 10.0.0
Cordova platform version (cordova platform ls): iOS 10+
## Expected Behavior

_Tell us what should happen_
Notification triggered when app is in background.

## Actual Behavior

_Tell us what happens instead_
No notification shows up.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1.  When i receive a notification from the server (push notification) i trigget the local notification plugin
  2.  
  cordova.plugins.notification.local.clearAll([1]);
   cordova.plugins.notification.local.schedule({
           id: 1,
           title: 'New notification!',
});
  3. ...
  4. ....

## Context

_What were you trying to do?_
Notify the user that they have a notification.

**Comment by manel00** [comment]
Hello I am facing the issue of NON NOTIFICATIONS POP UP on iOS, Did you solve it? Thank you

**Comment by iliyaST** [comment]
Yes

На чт, 11.03.2021 г. в 11:19 ч. Manel M ***@***.***> написа:

**Comment by manel00** [comment]
Can you post it here пожалуйста?

**Comment by iliyaST** [comment]
What i did was to put the background mode on in xcode. Before archiving.

На пн, 15.03.2021 г. в 11:56 ч. Manel M ***@***.***> написа:

**Comment by manel00** [comment]
Background fetch or background processing? пожалуйста, If you say some information, please be clear as much as possible... We cannot guess it

**Comment by manel00** [comment]
it is not working still...

**Comment by iliyaST** [comment]
Turn all background services on the archive in XCode.
[image: image.png]

**Comment by manel00** [comment]
Cannot see the image...

**Comment by manel00** [comment]
IT IS NOT WORKING, I TRIED ONCE MORE TODAY

**Comment by iliyaST** [comment]
Try installing background pplugin as well

**Comment by manel00** [comment]
Can you say at least how please? for me and for the rest of the people who dont know... thank you

**Comment by iliyaST** [comment]
https://github.com/katzer/cordova-plugin-background-mode i used this
plugin + background fetch and remote notifications checked in XCode when
building the project.


На вт, 23.03.2021 г. в 17:49 ч. Manel M ***@***.***> написа:

**Comment by manel00** [comment]
Sorry but still not working... what else you did?
