### ISSUE TITLE
Is This Project Still Being Worked On? Fix About The Repeating Notification Issue?

### ISSUE THREAD

**Issue by AlvinStefanus** [katzer/cordova-plugin-local-notifications#1948]
The problem with repeating notification that keeps looping until the phone becomes unresponsive, how is this? From [#1564](https://github.com/katzer/cordova-plugin-local-notifications/issues/1564) it is said that the current master branch is already fixed the issue. It was from 2 or 3 years ago. Is there a workaround for this?

**Comment by codewise-nicolas** [comment]
If you are having the repeat notification for one minute on android issue, here is the fix that did it for me. It was "fixing" the MatchTrigger.java  file.
https://stackoverflow.com/questions/55379397/local-notification-trigger-continuously-for-one-minute-in-android-device
