### ISSUE TITLE
IOS 14.5 Notification is not showing in status bar when app in foreground

### ISSUE THREAD

**Issue by bhandaribhuminpfizer** [katzer/cordova-plugin-local-notifications#1950]
Notification works on background but in foreground got only notification `BEEP` sound.

**Comment by Eslley** [comment]
Could you post your code? 

My code is like that:
`this.localNotifications.schedule({
      id: 1,
      text: 'Your message!',
      trigger: { at: new Date(new Date().getTime() + 10000) },
      smallIcon: 'res://ic_stat_onesignal_default.png',
      //icon: 'res://icon.png',
      data: { partyId: this.partyData.id },
      color: '632a89',
      foreground: true,
      launch: true
    });`

And for subscribe the events:
`this.localNotifications.on('click').subscribe(res => {

          console.log("click" + JSON.stringify(res))

        });`

**Comment by bhandaribhuminpfizer** [comment]
Here is my code 
```
 const scheduledDateObject = scheduledDateWithTime.toDate();
        const body = {
          id: scheduledDateWithTime.valueOf(),
          icon: 'res://ic_popup_reminder',
          title: notificationTitle,
          // text: `at ${scheduledDateObject.toLocaleTimeString()} `,
          trigger: { at: scheduledDateObject },
          foreground: true,
          priority: 2,
          channel: 'Med',
          channelDescription: 'Med',
        };
```

**Comment by rahmadid** [comment]
Hi all, perhaps you can try this fork, it is more recent and still maintained (to my knowledge):
https://github.com/timkellypa/cordova-plugin-local-notifications

Hope it helps. Thanks.
