### ISSUE TITLE
All schedule notifications coming at 5:30 AM for india and 7:30 for singapore

### ISSUE THREAD

**Issue by Lalitnegi12** [katzer/cordova-plugin-local-notifications#1959]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: IOS 
* OS version: 
* Device manufacturer / model: 
* Cordova version (```cordova -v```): 10.0.0
* Cordova platform version (```cordova platform ls```): 5.1.1
* Plugin config
* Ionic Version (if using Ionic) : 5.4.16

## Expected Behavior
Every day notification should display on scheduled time  
_Tell us what should happen_

## Actual Behavior
Every day scheduled notifications showing on 5:30 AM on next day when its scheduled
_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Creating every day notification
  2. Working ok for same day 
  3. .But next day showing on 5:30 AM for india and 7:30 AM for singapore and varying for other countries

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by lsstavares** [comment]
I was having very similar behavior on iOS (but on the other side of the World). 

After some hours studying the iOS plugin, just figured out that when scheduling a repeating event, you should provide the next time on Unix timestamp to make it work,  for example:  (trigger:{at: "timestamp", every: "day"}. You also need to make sure you send a future timestamp. 

Unfortunately, I didn't check the Android plugin yet...

Hope it helps.
