### ISSUE TITLE
Getting a build error after migrating our Ionic 5 app from Cordova 10 to Cordova 11

### ISSUE THREAD

**Issue by jeanteke** [katzer/cordova-plugin-local-notifications#1983]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Windows
* OS version: 10
* Device manufacturer / model:
* Cordova version (```cordova -v```): 11
* Cordova platform version (```cordova platform ls```): 11
* Plugin config
* Ionic Version (if using Ionic): 5

## Debug logs

![image](https://user-images.githubusercontent.com/87687185/188997050-bf29cae4-9b3b-4b14-8808-8f611b0ee334.png)

  * Android: $ adb logcat

**Comment by hussain-github** [comment]
Any update on this?

**Comment by jeanteke** [comment]
> ¿Algún avance en esto?

add this other plugin https://github.com/rgarciadelongoria/cordova-plugin-local-notifications.git 

lets build the app, but when launching local notifications the app closes

**Comment by jeanteke** [comment]
> Any update on this?

You can already solve, with this other:

ionic cordova plugin add cordova-plugin-local-notification-12

**Comment by alanmilinovic** [comment]
> > Any update on this?
> 
> You can already solve, with this other:
> 
> ionic cordova plugin add cordova-plugin-local-notification-12

This plugin is trowing error during the installation.

```
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done
```

**Comment by alanmilinovic** [comment]
> > Any update on this?
> 
> You can already solve, with this other:
> 
> ionic cordova plugin add cordova-plugin-local-notification-12

I can confirm, version from that repo is working.

**Comment by hussain-github** [comment]
> > Any update on this?
> 
> You can already solve, with this other:
> 
> ionic cordova plugin add cordova-plugin-local-notification-12

It is building successfully. Thank you.

**Comment by bevinGithub** [comment]
> > > Any update on this?
> > 
> > 
> > You can already solve, with this other:
> > ionic cordova plugin add cordova-plugin-local-notification-12
> 
> It is building successfully. Thank you.

Hi guys there is a bug on the plugin.

I have tested the plugin [katzer](https://github.com/katzer) /
[cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications) it doesn't work on the events onTrigger

onDeviceReady() {
this.localNotifications.on('trigger').subscribe((test: any) => {
console.log('Trigger' + JSON.stringify(test));
});
}

Its not logging the subscription out as l need to process data from the data: { test: 'Test Data }.

Anyoe able to catch the event Trigger?

**Comment by bevinGithub** [comment]
There is a bug on the local notifications on  catching triggers, its not outputting the subscription from the trigger events. 

I have tested the plugin [katzer](https://github.com/katzer) /
[cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications) it doesnt work on the events onTrigger

onDeviceReady() {
this.localNotifications.on('trigger').subscribe((test: any) => {
console.log('Trigger' + JSON.stringify(test));
});
}

Its not logging the subscription out as l need to process data from the data: { test: 'Test Data }.

**Comment by fragfeaster777** [comment]
There seems to be another bug when tapping on a notification for Android SDK 31: The app doesn't open. It works with Android 29. 

Here is the output of adb logcat when tapping the notification (package name obfuscated with ######)

> 10-17 18:38:13.288   533  2413 E NotificationService: Indirect notification activity start (trampoline) from #####..app blocked
> 

It seems others are having similar issues, for example: https://github.com/aws-amplify/amplify-js/issues/10118
