### ISSUE TITLE
Local notification play only the sound

### ISSUE THREAD

**Issue by batphil** [katzer/cordova-plugin-local-notifications#199]
Hello :)

I made a local notification like that :

/* local notification */
document.addEventListener('deviceready', function () {
    window.plugin.notification.local.add({
        id: 1,
        message: "test",
        title: "Hello !",
        icon: 'file://img/logo/true.png',
        sound: 'TYPE_NOTIFICATION'
    });
}, false);

But there is a problem : the sound it's the only event played...

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
