### ISSUE TITLE
bug: Gradle 7 compatibility

### ISSUE THREAD

**Issue by ghonche** [katzer/cordova-plugin-local-notifications#1991]
## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version: 12
* Device manufacturer / model: Samsung Galaxy A72
* Cordova version (```cordova -v```): 10.0.0 (cordova-lib@10.1.0)
* Cordova platform version (```cordova platform ls```): Using Capacitor 4, no Cordova platform
* Ionic Version: 6.0.4

## Actual Behavior
I just upgraded to Gradle 7 , and I get following error:

> Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method compile() for arguments [me.leolin:ShortcutBadger:1.1.22@aar] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

## Steps to Reproduce

  1. Create a new ionic project
  2. npm i @capacitor/core
  3. npm i -D @capacitor/cli
  4. npx cap init
  5. npm i @capacitor/android
  6. npm i @capacitor/android
  7. npm i cordova-plugin-local-notification
  8. npx cap sync
  9. Open android project in Android Studio
  10. Set Android Gradle Plugin Version: 7.2.2
  11. Set Gradle Version: 7.4.2
  12. Use Java 11
  13. Try to sync project with gradle 
  14. error appears.

## Related issue
https://github.com/ionic-team/capacitor/issues/6027

**Comment by ghonche** [comment]
> is it possible to update compile with implementation for gradle compatibility please ?

Already updated.

**Comment by midomario** [comment]
For me i did this :
step 1 : disable capacitor 
step 2 : uninstall all  deps (packages) + remove node modules + package lock file
step 3 : use cordova 
step 4 : reinstall deps (cordova version)
step 5 : npm i jetifier
step 6 : cordova plugin add cordova-plugin-androidx-adapter
step 7 : npx jetifier
step 8 : build with cordova

**Comment by Tejas-ChandraShekarRaju** [comment]
Hi @ghonche, Where did you make the changes to implementation from compile? Because I see that their source code is upgraded with implementation but whatever is published is still has compile.

**Comment by ShaneJohnsonCC** [comment]
@ghonche Same as what @Tejas-ChandraShekarRaju said. You made this change a long time ago but never published it. Trying to use cordova to install this package and it says beta.4 does not exist.

**Comment by felixphase** [comment]
I have resolved this by installing the plugin as below:

`ionic cordova plugins add https://github.com/katzer/cordova-plugin-local-notifications.git`

And this way it installs beta.4 version and resolve the issue.

I hope this helps who are facing the issue.
