### ISSUE TITLE
Notification redirect to the certain action

### ISSUE THREAD

**Issue by EnchanterIO** [katzer/cordova-plugin-local-notifications#20]
Hi, first of all... thank you a lot for this plugin... this is exactly what i was looking for!

But i have a question... i am new to phonegap and android apps and i would like to do a certain action when the user opens the app by clicking on the notification ... is that possible please?

+

i would like to attach a vibration signal to the notification but i dont know how.

"navigator.notification.vibrate(2000);" i can put this code next to the "window.plugin.notification.local.add" but this will not work when the notification is set up to the specific time... it would be great if there would be some callback function or something like: "foreground: 'app.foreground' " but : "active": 'some_function' or something. 

Thx

**Comment by jomarocas** [comment]
ok i can make a alarm notification, the sound still no working, only if you use default sound, working

```
document.addEventListener('deviceready', function () {

    var now = new Date().getTime(),
    from_now = new Date(now + 5*1000);
    window.cordova.plugins.notification.local.schedule({
        firstAt:from_now,
        title: 'title',
        text: 'description',
        every: 2,
    },success);

    window.cordova.plugins.notification.local.on("trigger", function (notification) {
            vibrate();
    });
}, false);

    function success(){
        alert('alert create');
    }

    function vibrate() {
        //for this you need to add plugin vibrate from cordova **https://github.com/apache/cordova-plugin-vibration**
        navigator.vibrate(2000);
    } 
```

and this working with default sound and vibration
