### ISSUE TITLE
Play custom audio files on Ionic Cordova Local Notifications IOS

### ISSUE THREAD

**Issue by bevinGithub** [katzer/cordova-plugin-local-notifications#2003]
Is a a workaround to play custom audio files or device ringing tones on ionic Cordova local notifications IOS. I want to play audios recorded on my app on Local notifications trigger  

Your Environment
Device OS is IOS 16.1.2 Ionic:

Ionic CLI : 5.4.5 (/usr/local/lib/node_modules/ionic) Ionic Framework : @ionic/angular 5.9.4 @angular-devkit/build-angular : 12.1.4

Cordova:

Cordova CLI : 11.0.0 Cordova Platforms : ios 6.2.0 Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 14 other plugins)

Utility:

cordova-res : 0.15.4 native-run : 1.6.0 (update available: 1.7.1)

System:

ios-deploy : 1.10.0 ios-sim

**Comment by GitFr33** [comment]
I haven't tested on iOS but the workaround that I'm using which seems to work on Android (using this fork: https://github.com/powowbox/cordova-plugin-local-notification-12)  is to set different values for sound along with matching unique channelId and channelName values using the setDefaults method before scheduling a notification.

For example:
```
cordova.plugins.notification.local.setDefaults({
    sound:bell_uri,
    channelName:bell_info[1],
    channelId:bell_info[0]
});
```
