### ISSUE TITLE
Apps Now Having Problems Adding Plugin

### ISSUE THREAD

**Issue by Andalusio** [katzer/cordova-plugin-local-notifications#2006]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.4
* Platform: Android
* OS version: Android 12
* Device manufacturer / model: Nokia 6.2 Plus
* Cordova version (```cordova -v```): 11.1.0
* Cordova platform version (```cordova platform ls```):
* Plugin config: <plugin name="https://github.com/katzer/cordova-plugin-local-notifications.git" spec="https://github.com/katzer/cordova-plugin-local-notifications.git" />
* Ionic Version (if using Ionic)

## Expected Behavior

Plugin should have been added. It worked last week.

## Actual Behavior

Plugin 'https://github.com/katzer/cordova-plugin-local-notifications.git' found in config.xml... Migrating it to package.json
Discovered plugin "cordova-plugin-local-notification". Adding it to the project
Failed to restore plugin "cordova-plugin-local-notification". You might need to try adding it again. Error: CordovaError: Failed to fetch plugin cordova-plugin-local-notification@~0.9.0-beta.4 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cordova-plugin-local-notification@~0.9.0-beta.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Omar\AppData\Roaming\npm-cache\_logs\2023-05-24T18_18_50_116Z-debug.log

## Steps to Reproduce

Just add the plugin. Half the times, it's stuck at "Discovered plugin "https://github.com/katzer/cordova-plugin-local-notifications.git". Adding it to the project".

## Context

Add the plugin.

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by GitToTheHub** [comment]
There was never a version "0.9.0-beta.4", maybe this was the problem.
