### ISSUE TITLE
Gradle 9.0 Compatibility - Deprecated Gradle features were used in this build

### ISSUE THREAD

**Issue by Owen7000** [katzer/cordova-plugin-local-notifications#2029]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

I have created a blank cordova project, and installed the plugin with the command `cordova plugins add https://github.com/katzer/cordova-plugin-local-notifications.git`. I go to run `cordova build android` and get told that the plugin uses deprecated features.

## Your Environment

* Plugin version: 0.9.0-beta.3
* Platform: Android 
* Cordova version: 12.0.0
* Cordova platform version: android 13.0.0

## Expected Behavior

App should build successfully

## Actual Behavior
Build fails with the following output.

> Checking Java JDK and Android SDK versions
> ANDROID_HOME=undefined (recommended setting)
> ANDROID_SDK_ROOT=undefined (DEPRECATED)
> Using Android SDK: C:\Users\OPlim\AppData\Local\Android\Sdk
> 
> BUILD SUCCESSFUL in 15s
> 1 actionable task: 1 up-to-date
> Subproject Path: CordovaLib                                            
> Subproject Path: app                                                   
> 
> > Task :CordovaLib:compileDebugJavaWithJavac
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 
> > Task :app:compileDebugJavaWithJavac
> C:\Users\OPlim\Desktop\Projects\Cordova Projects\notifications\platforms\android\app\src\main\java\de\appplant\cordova\plugin\localnotification\ClickReceiver.java:25: error: cannot find symbol
> import android.support.v4.app.RemoteInput;
>                              ^
>   symbol:   class RemoteInput
>   location: package android.support.v4.app
> C:\Users\OPlim\Desktop\Projects\Cordova Projects\notifications\platforms\android\app\src\main\java\de\appplant\cordova\plugin\localnotification\ClickReceiver.java:76: error: cannot find symbol
>         Bundle input = RemoteInput.getResultsFromIntent(getIntent());
>                        ^
>   symbol:   variable RemoteInput
>   location: class ClickReceiver
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 2 errors
> 
> > Task :app:compileDebugJavaWithJavac FAILED
> 
> > Run with --info option to get more log output.
> > Run with --scan to get full insights.
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.  
> 
> For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
> 
> BUILD FAILED in 1m 24s
> 46 actionable tasks: 46 executed
> Command failed with exit code 1: C:\Users\OPlim\Desktop\Projects\Cordova Projects\notifications\platforms\android\tools\gradlew.bat cdvBuildDebug
> 

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. `cordova create`
  2. Add Android platform
  3. `cordova plugins add https://github.com/katzer/cordova-plugin-local-notifications.git`
  4. `cordova build android`

## Context

Install the plugin as I've been trying to implement notifications of any sort into any app for the past few days, and I'm way out of my depth in all honesty! But I can't find a single plugin that works out of the box, so any help whatsoever would be greatly appreciated!

## Debug logs

N/A

**Comment by GitToTheHub** [comment]
You can use the master-version to fix this.

**Comment by Owen7000** [comment]
Great, thank you! I had tried using the master version at the time but still had issues. I'll try with the new release when I'm home! Thanks for your help!

**Comment by GitToTheHub** [comment]
No problem 🙂

**Comment by Owen7000** [comment]
Just wanted to say thank you for fixing the issues! Everything works as expected now!

**Comment by GitToTheHub** [comment]
Thank you, I‘m happy it works now for you 🙂
