### ISSUE TITLE
scheduale multiple notafications

### ISSUE THREAD

**Issue by josefcarlsson** [katzer/cordova-plugin-local-notifications#203]
im trying to set up multible notafications but I only set the first one,

var now = new Date().getTime(),
_60_seconds_from_now = new Date(now + 30*1000);
 _120_seconds_from_now = new Date(_60_seconds_from_now.getTime() + 60*1000),
            window.plugin.notification.local.add({
                                   id:      28,
                                   title:   'Reminder',
                                   message: 'Dont forget to buy some ds.',
                                   repeat:  'minutely',
                                   date:    _60_seconds_from_now
                });
              window.plugin.notification.local.add({
                                    id:      27,
                                    title:   'Reminder',
                                    message: 'Dont forget to buy some dsfsdafsdafsdaf.',
                                    repeat:  'minutely',
                                    date:    _120_seconds_from_now
                });

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
