### ISSUE TITLE
notification actions are not working.

### ISSUE THREAD

**Issue by balya7777** [katzer/cordova-plugin-local-notifications#2031]
CordovaLocalNotifications.schedule({
id: new Date().getTime(),
title: notification.data.title,
text: notification.data.body,
progressBar: { value: parseInt(notification.data.body!.slice(0, -1)), maxValue: 100 },
actions: [
{ id: 'yes', title: 'Yes' },
{ id: 'no', title: 'No' }
],
});

CordovaLocalNotifications.on('yes').subscribe((notification: any) => {
console.log('Notification clicked:', notification);
alert(JSON.stringify(notification));
});
CordovaLocalNotifications.on('no').subscribe((notification: any) => {
console.log('Notification clicked:', notification);
alert(JSON.stringify(notification));
});

the app doesn't show alert

**Comment by GitToTheHub** [comment]
Please test this in a vanilla cordova app, this is not cordova.

**Comment by balya7777** [comment]
Yes, I am using Ionic/React/Capacitor.
Can't I use this plugin for it?

**Comment by GitToTheHub** [comment]
I don't know, i saw some people using this plugin in Ionic, but this plugin is primarily developed for Cordova. I don't have experience with Ionic/React/Capacitor.

**Comment by balya7777** [comment]
how to receive the actions button click event in Cordova?

**Comment by GitToTheHub** [comment]
This is a simple example:

```
  cordova.plugins.notification.local.schedule({
      title: 'Do you want to go see a movie tonight?',
      actions: [{ id: 'yes', title: 'Yes' }]
  });

  cordova.plugins.notification.local.on('yes', function (notification, eopts) {
      alert("Yes clicked");
  });
```

I tested it in Android and it works.
