### ISSUE TITLE
Adding the Cordova plugin local notification plugin through Cordova resulted in the Ionic project reporting 'compile not found' when generated through build

### ISSUE THREAD

**Issue by 2550536224** [katzer/cordova-plugin-local-notifications#2034]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta.2
* Platform:Android
* OS version：Android14
* Device manufacturer / model:
* Cordova version (```cordova -v```):12.0.0 (cordova-lib@12.0.1)
* Cordova platform version (```cordova platform ls```):android 13.0.0
* Android SDK：34
* Java JDK：17
* gradle：8.7
* node：18.19.0
* Plugin config <platform name="android">
        <framework src="com.android.support:support-v4:26.+" />
        <framework src="src/android/build/localnotification.gradle" custom="true" type="gradleReference"/>

        <config-file target="res/xml/config.xml" parent="/*">
            <feature name="LocalNotification">
                <param name="android-package" value="de.appplant.cordova.plugin.localnotification.LocalNotification"/>
            </feature>
        </config-file>

        <config-file target="AndroidManifest.xml" parent="/manifest/application">
            <provider
                android:name="de.appplant.cordova.plugin.notification.util.AssetProvider"
                android:authorities="${applicationId}.provider"
                android:exported="false"
                android:grantUriPermissions="true" >
                <meta-data
                    android:name="android.support.FILE_PROVIDER_PATHS"
                    android:resource="@xml/localnotification_provider_paths"/>
            </provider>

            <receiver
                android:name="de.appplant.cordova.plugin.localnotification.TriggerReceiver"
                android:exported="false" />

            <receiver
                android:name="de.appplant.cordova.plugin.localnotification.ClearReceiver"
                android:exported="false" />

            <activity
                android:name="de.appplant.cordova.plugin.localnotification.ClickReceiver"
                android:launchMode="singleInstance"
                android:theme="@android:style/Theme.Translucent"
                android:exported="false" />
        </config-file>
* Ionic Version (if using Ionic) 5.4.16

## Expected Behavior
After installing Cordova plugin local notification, execute ionic Cordova build Android and package it as an app normally

## Actual Behavior

After installing the local plugin through ionic cordova plugin add cordova plugin local notification, execute ionic cordova build Android with an error message：
1: Task failed with an exception.
-----------
* Where:
Script 'ionicProject\platforms\android\cordova-plugin-local-notification\starter-localnotification.gradle' line: 31

* What went wrong:
A problem occurred evaluating script.
> Could not find method compile() for arguments [me.leolin:ShortcutBadger:1.1.22@aar] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

## Context

After installing Cordova plugin local notification, executing Ionic Cordova build Android can package it into an app and achieve local notification functionality

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by GitToTheHub** [comment]
You have to use the master-branch to make it work.
