### ISSUE TITLE
how to handle notification action button with icon not text

### ISSUE THREAD

**Issue by balya7777** [katzer/cordova-plugin-local-notifications#2036]
icon assets are in drawable folder
android/app/src/main/res/drawable-mdpi/ic_action_previous.png
android/app/src/main/res/drawable-hdpi/ic_action_previous.png
android/app/src/main/res/drawable-xhdpi/ic_action_previous.png
android/app/src/main/res/drawable-xxhdpi/ic_action_previous.png
android/app/src/main/res/drawable-xxxhdpi/ic_action_previous.png

actions: [
  { id: 'no', title: 'No', icon: 'ic_action_previous' },
  { id: 'yes', title: 'Yes', icon: 'ic_action_next' }
],

**Comment by GitToTheHub** [comment]
Hi, since Android 7, Icons are not displayed on action buttons anymore, see https://developer.android.com/reference/android/app/Notification.Action.Builder#Builder(int,%20java.lang.CharSequence,%20android.app.PendingIntent)

**Comment by balya7777** [comment]
Thank you.

**Comment by GitToTheHub** [comment]
I don‘t know if it‘s possible in general, but it’s currently not supported by this plugin.
