### ISSUE TITLE
Can I avoid restarting the app when click the notification action button?

### ISSUE THREAD

**Issue by balya7777** [katzer/cordova-plugin-local-notifications#2037]
When click the notification action button, the app restarts certainly.
Can I avoid it?

**Comment by GitToTheHub** [comment]
Which platform do you talk?

**Comment by GitToTheHub** [comment]
Does the app restart, when you click a notification without action buttons?

**Comment by balya7777** [comment]
With action buttons, normal notification click doesn't work

**Comment by GitToTheHub** [comment]
I will try to see if i can reproduce this

**Comment by balya7777** [comment]
Thank you.

**Comment by GitToTheHub** [comment]
Sorry, i couldn't find time to test this. The app should not restart, when you click a action button.
