### ISSUE TITLE
Vibrate setting has no effect (Android)

### ISSUE THREAD

**Issue by GitFr33** [katzer/cordova-plugin-local-notifications#2039]
Setting `vibrate` to `true` or `false` seems to have no effect the and vibration simply follows the devices default vibration setting.

##  Environment

* Plugin version: 0.10.1 https://github.com/fquirin/cordova-plugin-local-notifications/tree/pr-katzer (also tried several other versions and forks)
* Platform: Android
* OS version: 12 and 13 
* Device manufacturer / model: Samsung S10 and  FairPhone FP4
* Cordova version: 12.0.0 (cordova-lib@12.0.1)
* Cordova platform version: android 12.0.0
* Plugin config
* Ionic: Not using ionic

## Expected Behavior
Ability to customize weather or not the device vibrates when the notification is shown using one of the following:
`cordova.plugins.notification.local.setDefaults({ vibrate: true})`
`cordova.plugins.notification.local.setDefaults({ vibrate: false})`
or
`cordova.plugins.notification.local.schedule({ vibrate: true})`
`cordova.plugins.notification.local.schedule({ vibrate: false})`
 
## Actual Behavior

The vibrate setting has no effect.

## Steps to Reproduce
```
cordova.plugins.notification.local.schedule({
    title: 'My first notification',
    text: 'Thats pretty easy...',
    vibrate: true
});
```

**Comment by GitToTheHub** [comment]
Hi, the vibration property is currently not supported by this plugin. The creation of channels must be implemented first to support this property again.

**Comment by GitFr33** [comment]
Okay. Thanks for your prompt response!
Is the channels implementation part of https://github.com/katzer/cordova-plugin-local-notifications/pull/2000 ?

**Comment by GitToTheHub** [comment]
Not really, this has to be done in a new PR. The PR #2000 is is too messy and must be cleaned up.

**Comment by GitToTheHub** [comment]
This will be fixed, when the notifications channels are configurable.
