### ISSUE TITLE
Android & Events...?

### ISSUE THREAD

**Issue by FabioKB** [katzer/cordova-plugin-local-notifications#204]
Hi there,

First up - great plugin, API seems very clean.

I managed to install the plugin and am able to get notifications to appear with the add() method. However none of the events seem to be working... (on Android here).

I'm trying namely:
window.plugin.notification.local.ontrigger = function (id, state, json) {
alert('test');
};
window.plugin.notification.local.onclick = function (id, state, json) {
alert('test');
};

And cannot seem to ever get it to fire my alert call on the respective event.

Am I missing something?

Thanks in advance!

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
