### ISSUE TITLE
Chanel creation

### ISSUE THREAD

**Issue by iamAdamGoodman** [katzer/cordova-plugin-local-notifications#2048]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: v1.0.0
* Platform:Android
* OS version:13
* Device manufacturer / model:
* Cordova version (```cordova -13```):
* Cordova platform version (```cordova platform ls` Android``):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Thanks to Katzer for adding the future of creating channel .
I have question :
I dont get it what the Success_callback function should do when you create chanel ;
If you please can provide the full code to create channel with an example for the success_back i will be thankful.

_Tell us what should happen_
 Im using the exact code provided in the documentation 
cordova.plugins.notification.local.createChannel({
    channelId:'my_ch_id', // string - To separate something in the id, use "_" instead of "-"
    channelName:'My Channel Name', // string 
    description:"Description of channel", // string (optional)
    sound: 'file://audio/ring.mp3', // string (optional) 
    vibrate: true, // bool (optional), default is false
    importance: 3, // int (optional) 0 to 4, default is IMPORTANCE_DEFAULT (3)
    soundUsage: 5, // int (optional), default is USAGE_NOTIFICATION
  }, success_callback, this)

## Actual Behavior

_Tell us what happens instead_

Using the code im able to get success alert but the channel still not created;

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by GitToTheHub** [comment]
Hi, the channel creation is currently only possible in the master "1.0.1-dev". It's not integrated in the currently released version 1.0.0.

**Comment by iamAdamGoodman** [comment]
Thank you :)
