### ISSUE TITLE
Erros no build: Error: Missing PendingIntent mutability flag [UnspecifiedImmutableFlag]

### ISSUE THREAD

**Issue by g1lvan** [katzer/cordova-plugin-local-notifications#2049]
BUILDEI UM PROJETO HJ E APARECEU OS SEGUINTES ERROS, DEVO PREOCUPAR? A DOIS DIAS ATRÁS EU BUILDEI E NÃO DEU ERRO
C:\Users\gl665\pessoal\newApp>cordova build android --release --buildConfig=build.json

Checking Java JDK and Android SDK versions
ANDROID_HOME=C:\Users\user\AppData\Local\Android\Sdk (recommended setting)
ANDROID_SDK_ROOT=undefined (DEPRECATED)
Using Android SDK: C:\Users\user\AppData\Local\Android\Sdk
Reading build config file: C:\Users\user\pessoal\newApp\build.json
Reading the keystore from: C:\Users\user\pessoal\newApp\key.keystore

BUILD SUCCESSFUL in 14s
1 actionable task: 1 up-to-date
Subproject Path: CordovaLib
Subproject Path: app

> Task :CordovaLib:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :app:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :app:lintVitalRelease
C:\Users\gl665\pessoal\newApp\platforms\android\app\src\main\java\de\appplant\cordova\plugin\notification\Notification.java:228: Error: Missing PendingIntent mutability flag [UnspecifiedImmutableFlag]
                        context, 0, intent, FLAG_CANCEL_CURRENT);
                                            ~~~~~~~~~~~~~~~~~~~
C:\Users\gl665\pessoal\newApp\platforms\android\app\src\main\java\de\appplant\cordova\plugin\notification\Notification.java:355: Error: Missing PendingIntent mutability flag [UnspecifiedImmutableFlag]
                    context, 0, intent, 0);
                                        ~

   Explanation for issues of type "UnspecifiedImmutableFlag":
   Apps targeting Android 12 and higher must specify either FLAG_IMMUTABLE or
   FLAG_MUTABLE when constructing a PendingIntent.

   FLAG_IMMUTABLE is available since target SDK 23, and is almost always the
   best choice. See
   https://developer.android.com/guide/components/intents-filters#CreateImmuta
   blePendingIntents for a list of common exceptions to this rule.

   https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability
   https://goo.gle/UnspecifiedImmutableFlag

2 errors, 0 warnings


Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 3m 1s
78 actionable tasks: 73 executed, 5 up-to-date
Built the following apk(s):
        C:\Users\user\pessoal\newApp\platforms\android\app\build\outputs\apk\release\app-release.apk


* Plugin version: 1.0.0
* Platform: Android
* OS version: 13
* Cordova version (```cordova -v```): lasted
* Cordova platform version (```cordova platform ls```): 13.0.0

**Comment by GitToTheHub** [comment]
Hi,

your build is successful. Your Gradle task `:app:lintVitalRelease` tells you, that there is code, which is not compatible to Android 12, but the incompatible is only be executed on Android 11 and older, as you can see here: https://github.com/katzer/cordova-plugin-local-notifications/blob/5d7cd40292cba8a3fa4143d31064f735d94bfdef/src/android/notification/Notification.java#L222-L229.
So you can ignore this.

**Comment by g1lvan** [comment]
Ok, mas qual o comportamento esperado para versões anteriores a o android 12? A que nível isso pode afetar o app?

**Comment by GitToTheHub** [comment]
Hi good you wrote again this. I didn't saw that `FLAG_IMMUTABLE` is supported since Android 6, so I think, we can always use this.

**Comment by GitToTheHub** [comment]
Hi,
I made an update to the master branch. `FLAG_IMMUTABLE` is now always be used on every Android version.
Regards
