### ISSUE TITLE
Notification for dynamic data from ajax web service 

### ISSUE THREAD

**Issue by senthilmurugan-tag** [katzer/cordova-plugin-local-notifications#205]
But I need to implement this notification as dynamically. Based on dynamic data from server i need to show the notification.
    
    Before the notification showing each time, it should call the web service and get the notification content (like title, message, etc..). Based on the content, it will decide whether to display the notification or not. How i do it?

for example 
  if(notification_show== true) {
            //Show notification for a particular time
            window.plugin.notification.local.add({
		 	    id:      1,
		 	    title:   'dynamicTitle',
		 	    message: 'dynamicMessage',
		 	    repeat:  'minutely',
		 	    date:    _20_seconds_from_now,
		 	    sound: 'TYPE_ALARM',
		 	    //icon: 'file://img/logo.png',
		 	    led: 'A0FF05',
	 	});
 }else{
           //Notification in turned OFF
 }
    
notification_show, dynamicTitle, dynamicMessage ---> response from ajax web service

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by Divyaadz** [comment]
How to implement dynamic title using local notification? Dynamic text will be received from rest service.
