### ISSUE TITLE
Local Notification not working on iOS Simulator & Real Devices in Foreground mode

### ISSUE THREAD

**Issue by Akash-Tapadia-DFT** [katzer/cordova-plugin-local-notifications#2051]
## Your Environment

* Plugin version: master version
* Platform: iOS
* OS version: iOS 18
* Device manufacturer / model: iPhone 16 pro
* Cordova version (```cordova -v```): 10
* Cordova platform version (```cordova platform ls```): 7.1.1
* Plugin config
* Ionic Version (if using Ionic) : 6.4.0

## Expected Behavior

Local Notification should be received on iOS simulators

## Actual Behavior

Could not receive any notifications on iOS simulators

## Steps to Reproduce

Call schedule method from the local Notification plugin

## Context

I am trying to call the schedule method from the local Notification plugin as shown below
this.localNotifications.schedule({
      id : 1,
      title: 'New Statement Available',
      text: 'Click to view your statement.',
      foreground: true,
      sound: 'default'
    });

## Debug logs

iOS XCODE Logs

ERROR: Unhandled Promise rejection: undefined is not an object (evaluating 'm.aps.alert') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: undefined is not an object (evaluating 'm.aps.alert')

**Comment by Akash-Tapadia-DFT** [comment]
I am getting error when I initiate the notification call. Same issue on Real Device as well.

**Comment by GitToTheHub** [comment]
Hi,

your issue must be somewhere else. I tested it in iOS 18.1 with an iPhone 16 Pro Max Simulator and everything was running fine:

<img src="https://github.com/user-attachments/assets/d330874f-36d7-459a-b430-b0ed1c352ff0" width="320">

Please try a clean Project:

```bash
cordova create notification-test
cordova platform add ios
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
```

Also please use cordova 12 instead of 10

Regards

**Comment by GitToTheHub** [comment]
I released a new version, try if the issue persists.

Regards
