### ISSUE TITLE
Sound file for IOS

### ISSUE THREAD

**Issue by iamAdamGoodman** [katzer/cordova-plugin-local-notifications#2052]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Hi . 
I dont get where exactly the notification sound file should be placed for ios.
Im using it as sound: 'file://audio/ring.mp3', 
so the file ring.mp3 is in www/audio/. .. but it is not working .
Any ideas ?

## Your Environment

* Plugin version:
* Platform:
* OS version:
* Device manufacturer / model:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

_Tell us what should happen_

## Actual Behavior

_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ...
  2. ...
  3. ...
  4. ....

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by iamAdamGoodman** [comment]
fixed .

**Comment by GitToTheHub** [comment]
Good 🙂
