### ISSUE TITLE
Failed to locate callback for id : LocalNotification1035745259 

### ISSUE THREAD

**Issue by 1337-5P34Ker** [katzer/cordova-plugin-local-notifications#206]
I'm trying to reset and set Notifications on my WP8 and get an Error like:
Failed to locate callback for id : LocalNotification1035745259
Der Thread 0xec8 hat mit Code 259 (0x103) geendet.
??
And if I append a list of notifications with different IDs on tile always appears the last added 
 
window.plugin.notification.local.add(
                   {
                       id: guid,  //  -> I create a new Guid here each time
                       date: reminderDateTime,    // This expects a date object
                       message: message,  // The message that is displayed
                       title: 'Erinnerung',  // The title of the message
                       autoCancel: true, // Setting this flag and the notification is automatically canceled when the user clicks it
                       smallIcon: 'ic_action_reminder',
                       icon: 'ic_list_reminder'
                   });

Is it a bug or what must I do to see different tiles? If I click on the tile to open the app, I hoped the notification is canceled - but it's not.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
