### ISSUE TITLE
Specific date

### ISSUE THREAD

**Issue by alezala** [katzer/cordova-plugin-local-notifications#208]
Hello, I am using the plugin you created for phonegap. How can I start a specific notification date?. Example : 07/19/2014. Thanks you!

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
