### ISSUE TITLE
Android Wear support

### ISSUE THREAD

**Issue by mollyfud** [katzer/cordova-plugin-local-notifications#209]
Hi, 
Sorry if this isn't the right place for this sort of question but wondering if you looked at the Android Wear SDK/stuff and if, apart from the default support for notification, there is anything that can be done in this project to support Android Wear features?

TIA and love your work
Molly

**Comment by katzer** [comment]
A bit quite old... v0.9-beta supports Apple Watch and Android Wear out of the box.
