### ISSUE TITLE
How many notifications can be set at once?

### ISSUE THREAD

**Issue by AtanuCSE** [katzer/cordova-plugin-local-notifications#211]
Suppose I want to set 60 notifications at once with different ids and different dates. Is it possible? What is the maximum number of notification that I can set at once? Is it possible to add multiple notifications at once with different ids, or do I need to add multiple ids to set multiple alarm.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
