### ISSUE TITLE
Encountering error: device is not defined 

### ISSUE THREAD

**Issue by mrhwangmiyoung** [katzer/cordova-plugin-local-notifications#214]
Hi, I am running the app with the plugin, and it pops an error in the logcat that the device is not defined.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
