### ISSUE TITLE
Add multiple notifications crashes iPad

### ISSUE THREAD

**Issue by 1337-5P34Ker** [katzer/cordova-plugin-local-notifications#215]
I try to add some notifications:

for (var task in tasks) {
	window.plugin.notification.local.add({
		id: CreateGuid(), // creates a unique guid
		date: reminderDateTime,
		message: 'remember the milk',
		title: 'Reminder',
		autoCancel: true,
	});
}
but the iPad crashes if I do not delay the function. What can I do to add multiple notifications at once? On Android everything works fine.

**Comment by stefanmdt** [comment]
I had similar problems. Looks like the async call of adding a notification must be finished before adding the next one. One solution/workaround could be to wait for the callback and use it for adding the next notification. Works in my case ...

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
