### ISSUE TITLE
Disabling Vibration (Android)

### ISSUE THREAD

**Issue by andersdn** [katzer/cordova-plugin-local-notifications#216]
Is there an acceptable way to disable (android) vibrations within the plugin, I have tested overwriting the default notification as part of creating the notification object service using 
`notification.defaults |= Notification.DEFAULT_VIBRATE;`.

I also tried adding the vibrate permission to android manifest and setting the vibrate property on the notification to `(long[] 0,0)` to force a nothing vibrate, but neither has helped in disabling the vibrations.

**Comment by trueicecold** [comment]
Thanks andersdn, that did it for me :+1:
