### ISSUE TITLE
Not working on ios

### ISSUE THREAD

**Issue by scadger** [katzer/cordova-plugin-local-notifications#217]
Not working on ios (does not issue any notification). Using phonegap 3.4.0

Works fine on android but doesn't appear to do anything on ios (tested on iphone 3s with ios 6.1.6 and iphone 4 with ios 7.1.2). Checked the Notification settings in ios and tried either Banners and Alerts but still nothing). Tried using with scheduled date/time and without. Still nothing. Android works exactly as required.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by Ketan108ideaspace** [comment]
Thanks katzer,

it's properly working.
