### ISSUE TITLE
Phonegap local notification not playing sound or appearing on screen if phone is locked

### ISSUE THREAD

**Issue by adyking** [katzer/cordova-plugin-local-notifications#218]
Hi there, 

Please help, I'm trying to play a sound on my iphone for the local notification but it won't work, plus if phone is locked notification won't display until I open the app again.

any ideas?

thank you

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by zeeshanjan82** [comment]
I am facing the issue on android where the local notification does not wake up the phone and is not displayed over the lock screen. Any help?

**Comment by maxHus** [comment]
Hi,
I am not receiving the notification , i have scheduled it for every 10 mins, but it doesn't come up ..

is it necessary to use this plugin with the Background Mode plugin.. ?
