### ISSUE TITLE
How to make localnotification work when app is in background

### ISSUE THREAD

**Issue by mrhwangmiyoung** [katzer/cordova-plugin-local-notifications#219]
Hi katzer,

I have successfully implemented the Plugin. I used the notification to notify me if the user is near a marker. However, is it possible that when I open the app, then I go back to home, the notification I set in the Google Map will still appear? Thanks.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
