### ISSUE TITLE
Is it possible to execute javascript code when local notification is fired in background (not on onclick).

### ISSUE THREAD

**Issue by rivf** [katzer/cordova-plugin-local-notifications#220]
Hello! I have a problem. I am trying to make app which changes state after notification is fired. I need to run simple "variable = 1" (example) code after notification is fired. Ontrigger doesn't work when app is an background. The code in ontrigger simply doesn't execute (and as far as I can understand from other issues here, and I read every related, it's normal for background, ontrigger only executes when app is in foreground). Of course there is still onclick, but for example I almost never click on the notification, I simply launch app.
Is there any way at all to execute simple code after notification was fired in background? 
I coded a lot and now the core concept of the app is impossible.
I also heard about background plugin, but I don't understand how to use it to solve the issue.

Here is my code with background plugin. I think I don't get how to use it right.
```javascript
            window.localStorage.setItem("after_plan", $scope.afterPlanText);
            window.plugin.backgroundMode.enable();
            //1 line notification
            window.plugin.notification.local.add({
                id:      51,
                title:   'Reminder',
                message: "5_1 1 minute before train time",
                date:    train1before
            });
            window.plugin.notification.local.ontrigger = function (id, state, json) {
                $scope.stateNotif = 1;
                window.localStorage.setItem("state_notif", $scope.stateNotif);
                navigator.notification.alert('OnTrigger 5_1');
                window.plugin.backgroundMode.disable();
            };
```

Also I need to say that local notifications work. Ontrigger works when app is in foreground. Onlick also works. I'm using ios 7.1.1, latest cordova, plugin from master branch. I'm new to javascript and else, so I appreciate any suggestions! Sorry for possibly stupid question.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
