### ISSUE TITLE
Phone Restart - Notification Fails

### ISSUE THREAD

**Issue by basitj** [katzer/cordova-plugin-local-notifications#221]
Notifications are gone once the phone is restarted. Is that by design? I believe the scheduled notification should be fired even after restart.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
