### ISSUE TITLE
Notification on Wifi Reachable

### ISSUE THREAD

**Issue by marvinosswald** [katzer/cordova-plugin-local-notifications#222]
Hey Guys,

Trying to schedule a Notification which should execute as soon as a Wifi Network is available..
Until now I found tonnymillion's [Reachability](https://github.com/tonymillion/Reachability) but I need a Idee, right know I don't have any Idea how to perform this..

Any Ideas ? 

Cheers Marvin :)

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
