### ISSUE TITLE
How to get the intent extras in the main activity (Question) - Android

### ISSUE THREAD

**Issue by jjdltc** [katzer/cordova-plugin-local-notifications#223]
I'm working with the plugin and until now is great but I need to do some custom actions after the notification is activated, I saw in the ReceiverActivity.java the data (call it "options"), but when I try to access that in my main launch activity I got null, how should I get the information of the notification in my main activity (the one that is launch from ReceiverActivity) ¿?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
