### ISSUE TITLE
Badge number is always 1.

### ISSUE THREAD

**Issue by Nedvedyy** [katzer/cordova-plugin-local-notifications#225]
Hi ,

I have scheduled a repeated notification at 08:30. The badge number is always displayed as 1, even after I uninstall and re-install the app or comment out the window.plugin.notification.local.add({}). Checking on the notification board,both 'all' and 'missing' are empty. Could u advise?

Regards
Ned

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
