### ISSUE TITLE
iOS - Notification works, but doesn't notify

### ISSUE THREAD

**Issue by oliverholmberg** [katzer/cordova-plugin-local-notifications#226]
I am having an issue on iOS 7 - The notification is working, and shows up in notification center, but nothing visible happens in the UI, no sound, popup or other indication that the notification has happened.

When viewed in notification center, it appears as it should.

I checked in notification center, and the app has all notifications enabled.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by oliverholmberg** [comment]
Will do.  Thanks!

**Comment by katzer** [comment]
You may also see here: https://github.com/katzer/cordova-plugin-local-notifications#i-would-like-to-propose-new-features
