### ISSUE TITLE
Windows Phone - Compilation error

### ISSUE THREAD

**Issue by bperel** [katzer/cordova-plugin-local-notifications#227]
Hi,

I get 2 similar compilation errors when trying to compile the project with the Windows Phone SDK 8.0 from Visual Studio 2013 : 

```
'De.APPPlant.Cordova.Plugin.LocalNotification.Options' does not contain a definition for 'Foreground' and no extension method 'Foreground' accepting a first argument of type 'De.APPPlant.Cordova.Plugin.LocalNotification.Options' could be found (are you missing a using directive or an assembly reference?)	C:\myproject-phonegap\platforms\wp8\Plugins\de.appplant.cordova.plugin.local-notification\LocalNotification.cs
```

It occurs lines 60 and 62 of LocalNotification.cs which correspond to the following fragment : 

```
if (!string.IsNullOrEmpty(options.Foreground))
                {
                    string arguments = String.Format("{0}({1})", options.Foreground, options.ID);
```

If I look at the Options class definition, I indeed confirm that there is no Foreground field.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
