### ISSUE TITLE
Issue with Notification badge on load

### ISSUE THREAD

**Issue by ghe0106** [katzer/cordova-plugin-local-notifications#228]
Hey - I am relatively new to this and have adopted a project using this plugin - with Cordova 3.0, and Angular, - the issue is that when the project loads it has a notification badge with number 1 showing on the icon - when i check the notifications on the device there isn't any, Otherwise the notifications are being set - and everythng is behaving normally .....

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
