### ISSUE TITLE
Problem with remote sounds

### ISSUE THREAD

**Issue by javizarza** [katzer/cordova-plugin-local-notifications#229]
Hi there.

I'm using your plugin (tried both, stable and current) with cordova 3.5.0. Problem happens on Android 4.4 in a Nexus 4. I didn't try other platforms.

After creating a new project with "cordova create", adding platform and plugin, and running the test app with "cordova run android", everything works nice, but when I try to get a remote sound, it just doesn't sound. So I was wondering what could be wrong and I checked remote webserver logfile, and it didn't even try to retrieve the file.

I'm trying with this code:

        var now = new Date().getTime();
        var luego = new Date(now+10*1000);
        
        window.plugin.notification.local.add({
        	id:1,
        	title:'Alarma',
        	message:'Levanta',
        	date:luego,
        	sound:'http://realworkinghosthere/beep.mp3'
        });

And also just

window.plugin.notification.local.add({ sound: 'http://realworkinghosthere/beep.mp3' });

Am I missing something?

Thanks!

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
