### ISSUE TITLE
Notification icon

### ISSUE THREAD

**Issue by maciekmp** [katzer/cordova-plugin-local-notifications#230]
When notification appears and content of the message is in Android Status Bar the icon before the content is too big and it is cropped. How to set it properly, is it posible?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
