### ISSUE TITLE
App stops notifying after approximately 3 repeats

### ISSUE THREAD

**Issue by ximxim** [katzer/cordova-plugin-local-notifications#231]
The application works fine for a while. However, eventually I run into one notification that, if clicked it crashes unexpectedly. No further notifications come through from that point onward. Even relaunching the application several times, doesn't work. Only thing that works is re installing the application.

Please help. This error is the only thing standing between the launch of my application. Thanks in advance.

**UPDATE JULY 24 2014

After debugging some more I found a pattern. After third day when my daily notification shows, the notifications stop coming through.

I wonder if there is a limit of how many notifications repeat itself. Please me know. @katzer

**Comment by josmarycarrero** [comment]
Hi @ximxim I'm having the same problem :S Did you resolve this unexpected problem?

**Comment by ximxim** [comment]
I didn't resolve it. However, the developer released an update fixing the
issue. Check out the following link. I hope this helps.

https://build.phonegap.com/plugins/1356

On Wed, Feb 11, 2015 at 4:52 PM, Josmary Carrero <notifications@github.com>
wrote:

> Hi @ximxim <https://github.com/ximxim> I'm having the same problem :S Did
> you resolve this unexpected problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/katzer/cordova-plugin-local-notifications/issues/231#issuecomment-73972650>
> .
>



-- 
Regards,

Azim Ahmed

   -
      - ca.linkedin.com/in/ahmedaz/

**Comment by josmarycarrero** [comment]
Thank you so much, It really helps :)

**Comment by ximxim** [comment]
Glad I can help. :)

On Wed, Feb 11, 2015 at 4:59 PM, Josmary Carrero <notifications@github.com>
wrote:

> Thank you so much, It really helps :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/katzer/cordova-plugin-local-notifications/issues/231#issuecomment-73973845>
> .
>



-- 
Regards,

Azim Ahmed

   -
      - ca.linkedin.com/in/ahmedaz/

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
