### ISSUE TITLE
Feature request: notify but do not show the notification on the status bar

### ISSUE THREAD

**Issue by zwz** [katzer/cordova-plugin-local-notifications#233]
In some case, I would like to notify the user with led light (for a few second) or sound, but I do not want to distract the user by adding/showing the notification in the status bar.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
