### ISSUE TITLE
Events not fired on iOS

### ISSUE THREAD

**Issue by stevesum** [katzer/cordova-plugin-local-notifications#234]
The onadd, ontrigger, onclick, etc events never fired on iOS (7.1.2).
I tested tested it on every possible way. (running in background, foreground, with or without the background-mode plugin)
It works well on android, but I can't force it to works on iOS plattform.
As I see, the event is fired on the native side of the plugin, but the event is not delegated on the cordova side or not delegated back to the webview. I used the cordova v3.5.0-0-2.6.
Any idea?

**Comment by dortzur** [comment]
+1

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by ByGreez** [comment]
I still reproduce this problem:

```SpringBoard[43] <Warning>: UILocalNotification: could not calculate next fire date - previous = 2015-07-30 18:52:51 +0000 : next = 2015-07-30 18:52:51 +0000 : repeatInterval = 2```

**Comment by FlawaCLV** [comment]
Same for me:

Sep  1 17:47:41 MBP-de-Hugo SpringBoard[14114]: UILocalNotification: could not calculate next fire date - previous = 2015-09-01 15:44:56 +0000 : next = 2015-09-01 15:44:56 +0000 : repeatInterval = 2

**Comment by FilippoBenassutiCDM** [comment]
This happen to me too when the app is in background.
When app is active the call back works.

**Comment by FlawaCLV** [comment]
I'm simply scheduling a local notification on device ready. Not working...

document.addEventListener("deviceready", function() {
            window.plugin.notification.local.schedule({
                id: parseInt(new Date().getTime()),
                message: "Notification",
                date: new Date()
            });
});
