### ISSUE TITLE
build.phonegap `singleInstance` android app spawns new instance when notification is tapped...

### ISSUE THREAD

**Issue by AubreyHewes** [katzer/cordova-plugin-local-notifications#235]
This seems to have been a solved problem.. but it "seems" to still be failing (for me); An android  `singleInstance` build.phonegap application will spawn a new instance when opened via the katzer-notification...

**build platform:** build.phonegap.com (via API)
**config.xml katzer-notification version:** latest/*
````
	<gap:plugin name="de.appplant.cordova.plugin.local-notification" />
````
**config.xml `singleInstance` config:**
````
	<gap:config-file platform="android" parent="/manifest/application">
		<activity android:launchMode="singleInstance" />
	</gap:config-file>
````

Application does the following:
* Opens audio to play
* Sets non-closable/ongoing notification of playing audio title (the idea is that the user can listen to audio and do other stuff and then tap the notification to get back to the app).

User does the following:
* opens app
* plays audio (which opens non-closable/ongoing notification; android)
* closes app (ongoing notification stays alive; single-instance?)
* clicks ongoing notification

Result:
 * click on ongoing notification spawns **new** application instance.

Expected:
* click on ongoing notification (re)spawns **running** application instance.

Generated android manifest:

The BPG generated android manifest contains two (2) `singleInstance` activities. One for the application and one for the katzer-notification (could this be the problem, should the plugin activity define itself as a `singleInstance` activity?). 
(Removing the application's config.xml own `singleInstance` definition results in the same behaviour.)

````
<?xml version="1.0" encoding="utf-8"?>
<manifest android:versionCode="X" android:versionName="X" android:windowSoftInputMode="adjustPan" android:installLocation="auto" package="X"
  xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:resizeable="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <application android:label="@string/app_name" android:icon="@drawable/icon" android:debuggable="true" android:hardwareAccelerated="true">
        <activity android:label="@string/app_name" android:name=".X" android:launchMode="singleInstance" android:screenOrientation="unspecified" android:configChanges="locale|keyboard|keyboardHidden|orientation|screenSize" android:windowSoftInputMode="stateUnspecified|adjustUnspecified">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:label="@string/app_name" android:name="com.phonegap.DroidGap">
            <intent-filter />
        </activity>
        <receiver android:name="de.appplant.cordova.plugin.localnotification.Receiver" />
        <receiver android:name="de.appplant.cordova.plugin.localnotification.Restore">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <activity android:name="de.appplant.cordova.plugin.localnotification.ReceiverActivity" android:launchMode="singleInstance" />
    </application>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
</manifest>
````

I am a little stumped... :-S 

Thanks, Aubrey

_p.s. I do not want to unpack/custom-edit/repackage/resign the generated package; defies the use of a build service._

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by T1mobil3** [comment]
I have a similar app setup and this issue still exists for me with version 0.8.x
