### ISSUE TITLE
Ios7.2 - Badge works well, but no banner or alert shown

### ISSUE THREAD

**Issue by cedriclombardot** [katzer/cordova-plugin-local-notifications#237]
Hi,

I don't understand why the banner is not shown, when i do getTriggeredIds i see that the event was triggered any idea on how to fix it

Cedric

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
