### ISSUE TITLE
Error after installing and trying to build app

### ISSUE THREAD

**Issue by adpande** [katzer/cordova-plugin-local-notifications#238]
Cordova Version: 3.5.0. Using ionic framework

After installing the app i ran ionic build ios... and got these errors!!

clang: error: no such file or directory: '/Users/abhishek/aaprojects/myApp/platforms/ios/myApp/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

2014-08-12 00:42:17.070 xcodebuild[90806:4403]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-5069/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:76
Details:  Failed to load dependencies output contents from ``/Users/abhishek/aaprojects/myApp/platforms/ios/build/myApp.build/Debug-iphonesimulator/myApp.build/Objects-normal/i386/APPLocalNotification.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “APPLocalNotification.d” couldn’t be opened because there is no such file." UserInfo=0x7f84a53c4cc0 {NSFilePath=/Users/abhishek/aaprojects/myApp/platforms/ios/build/myApp.build/Debug-iphonesimulator/myApp.build/Objects-normal/i386/APPLocalNotification.d, NSUnderlyingError=0x7f84a53c04a0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/abhishek/aaprojects/myApp/platforms/ios/build/myApp.build/Debug-iphonesimulator/myApp.build/Objects-normal/i386/APPLocalNotification.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f84a53c4d00>{name = (null), num = 7}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **

The following build commands failed:
	CompileC build/myApp.build/Debug-iphonesimulator/myApp.build/Objects-normal/i386/APPLocalNotification.o myApp/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: /Users/abhishek/aaprojects/myApp/platforms/ios/cordova/run: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)

**Comment by jamesdef** [comment]
Experiencing the same problem, although the .h and .m files are present in the appropriate directory.
   ```
** BUILD FAILED **


The following build commands failed:
	CpResource tesou/Resources/CDVNotification.bundle build/emulator/tesou.app/CDVNotification.bundle
(1 failure)
Error: /Users/James/development/rendezVous/rendezVous-Ionic-App/platforms/ios/cordova/build: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

Dide someone come up with sth?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
