### ISSUE TITLE
ontrigger not firing, ios or android

### ISSUE THREAD

**Issue by andyryan** [katzer/cordova-plugin-local-notifications#239]
I have local notification seemingly working. I am even getting the notification when the app is in the abckground or the device is asleep.

The one problem I'm having now is ontrigger not firing at all

    window.plugin.notification.local.ontrigger = function (id, state, json) { alert("notfication received"); };

This isn't fireing on ios or android, whether or not the app is in foreground or background.

This is in a simple hello world app that makes a notification for 10 seconds time on button press.

I have tried putting the function both inside and outside the app object. I have tried moving the event binding above into onDeviceReady() and still nothing. 

What am I missing?

**Comment by dorijrs** [comment]
Any updates?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
