### ISSUE TITLE
android: local sound file is not played

### ISSUE THREAD

**Issue by amunters** [katzer/cordova-plugin-local-notifications#24]
Thanks for this great plugin! However, I encountered one issue with Android: When I specify a custom notification sound, it works OK when I specify a sound file on a remote location, i.e. sound: 'http://example.com/sound.mp3'
But when I specify a local sound file it doesn't work. No sound, no error messages either. My sound file is located in the top www directory. I tried many ways to specify the location, but nothing works:
sound: 'sound.mp3'
sound: '/sound.mp3'
sound: 'www/sound.mp3'
sound: '/www/sound.mp3'
sound: 'android_asset/www/sound.mp3'
sound: '/android_asset/www/sound.mp3'
sound: 'file://sound.mp3'
sound: 'file:///sound.mp3'
sound: 'file://www/sound.mp3'
sound: file:///www/sound.mp3'
sound: 'file://android_asset/www/sound.mp3'
sound: 'file:///android_asset/www/sound.mp3'

I this a bug, or am I doing something wrong? Please advise
- thanks, Allard

**Comment by Riyaz0001** [comment]
hey guys, same sound not played in my real android device version 4.4.2
my code is: 
```
cordova.plugins.notification.local.schedule({
                    id: 1,
                    text: 'Scheduled every minute',
                    every: 'minute',
                    sound: "android.resource://com.test.notificationapp/raw/sound",
                    icon: 'res://icon',
                    smallIcon: 'res://ic_popup_sync'
                });
```
how to solve this problem? anyone help please, Thanks.

**Comment by rwillett** [comment]
Don't hijack closed threads that are over three years. Raise a new issue with the template in #1188.
