### ISSUE TITLE
Notification not firing when app is open.

### ISSUE THREAD

**Issue by sjvisschers** [katzer/cordova-plugin-local-notifications#240]
The plugin is working perfect for notification when the app is in the background or not running, but when the app is in the foreground the notifications are not firing?

I use de.appplant.cordova.plugin.local-notification 0.7.4 "LocalNotification"
& Cordova 3.5.0-0.2.4

Issues is showing both in iOS as in Android

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
