### ISSUE TITLE
isTriggered and getTriggeredIds not in build

### ISSUE THREAD

**Issue by nickfedoroff** [katzer/cordova-plugin-local-notifications#241]
After installing the plugin, I couldn't get `isTriggered` to work. A quick search of local-notification.js revealed that the method wasn't in the source. Is this feature released or not?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
