### ISSUE TITLE
Poll server notifications

### ISSUE THREAD

**Issue by AidasK** [katzer/cordova-plugin-local-notifications#242]
Hi,

How do I poll notifications from the server?
For example: send ajax request to a server every 5 minutes and ask if it has some messages.

Or should I use google native push notification service? Like this one:
https://github.com/phonegap-build/PushPlugin/tree/93067b9303252d5ed7394819bf220db56d99d22c

From readme:
https://github.com/katzer/cordova-plugin-local-notifications#examples-of-notification-usage
```
For example, applications that depend on servers for messages or data can poll their servers for incoming items while running in the background; if a message is ready to view or an update is ready to download, they can then present a local notification immediately to inform their users.
```
But I can't see the example. All examples depends on scheduled events.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by wfsm** [comment]
@AidasK Can you do this after 0.8 release?
