### ISSUE TITLE
Crash on iOS 7.1 background mode 

### ISSUE THREAD

**Issue by jaumard** [katzer/cordova-plugin-local-notifications#244]
Hi,

I try to use this plugin to fire notification on background mode. I use this one to enable background mode (https://github.com/katzer/cordova-plugin-background-mode).
It works great on iOS 6 and 7.0 but on iOS 7.1 app crash when fire notification.

Here is the crash log : 
2014-08-19 21:55:30.351 Plasstik[21479:1303] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xa41a7c0
2014-08-19 21:55:30.352 Plasstik[21479:1303] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xa41a7c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000d61e4 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x01d0c8e5 objc_exception_throw + 44
	2   CoreFoundation                      0x00173243 -[NSObject(NSObject) doesNotRecognizeSelector:] + 275
	3   CoreFoundation                      0x000c650b ___forwarding___ + 1019
	4   CoreFoundation                      0x000c60ee _CF_forwarding_prep_0 + 14
	5   Plasstik                            0x00026ba9 -[APPLocalNotification notificationWithId:] + 521
	6   Plasstik                            0x00026926 -[APPLocalNotification isNotificationScheduledWithId:] + 86
	7   Plasstik                            0x00023788 __28-[APPLocalNotification add:]_block_invoke + 200
	8   libdispatch.dylib                   0x022ca7b8 _dispatch_call_block_and_release + 15
	9   libdispatch.dylib                   0x022df4d0 _dispatch_client_callout + 14
	10  libdispatch.dylib                   0x022cdeb7 _dispatch_root_queue_drain + 291
	11  libdispatch.dylib                   0x022ce127 _dispatch_worker_thread2 + 39
	12  libsystem_pthread.dylib             0x0260edab _pthread_wqthread + 336
	13  libsystem_pthread.dylib             0x02612cce start_wqthread + 30
)
libc++abi.dylib: terminating with uncaught exception of type NSException

And my JS code is simple : 
window.plugin.notification.local.add({
					id      : 1,
					title   : 'Alert ',
					message : 'Dont forget to buy some flowers.'
				});

This plugin support iOS 7.1 ? Anyone have same problem or a solution for me please

Thanks

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by mifkys** [comment]
This issue still exists in 0.8 release. Please, fix this problem.
