### ISSUE TITLE
Notification disappear when app is paused

### ISSUE THREAD

**Issue by oalifdal** [katzer/cordova-plugin-local-notifications#245]
Hi,

I am trying to have my notification persist as a way to indicate that an action is currently occuring in the  app. Unfortunately, the notification disappear when I click on it or if I switch to another app. It must be disappearing when the app is paused...

I set the ongoing flag but no luck, it it still disappearing. Autocancel is set to false.

Is there a way to make the notification permanent ? Have I missed something ?

Thanks !

**Comment by rafaellop** [comment]
Same problem here.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
