### ISSUE TITLE
How can I have a notification show in the top Android notification bar, even after the application has been pushed to the background and it sleeps after 30 minutes?

### ISSUE THREAD

**Issue by aklare** [katzer/cordova-plugin-local-notifications#246]
How can I have a notification show and sound in the top Android notification bar, even after the application has been pushed to the background? We are having trouble triggering a notification after the phone has gone into sleep mode after 30 minutes. Is there a way to have the application stay awake.  I am new to Android developement.  We are using Telerik AppBuilder which I believe uses PhoneGap / Cordova plugins. We have played with localNotification and PowerManagement but can't get a notification after 30 minutes. We don't want to use cloud notification due to possible delay in notification. We are also currently using SignalR to trigger a client alert from the server. We just need the client to stay running longer than 30 minutes..

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
