### ISSUE TITLE
display a progress bar in the notification

### ISSUE THREAD

**Issue by hananeglit** [katzer/cordova-plugin-local-notifications#248]
hi,
i use the plugin to implement local notification when downloading a file. i don't find how to display a progress bar in the notification like in native one http://javatechig.com/wp-content/uploads/2014/05/Displaying-Progress-Notification-in-Android-Example.png
can you help?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by dheerajkhokhar** [comment]
@hananeglit got any answer?

**Comment by vasani-arpit** [comment]
I have created a plugin which downloads file using download manager and shows progress bar along the way

https://github.com/vasani-arpit/cordova-plugin-downloadmanager

```
//after device is ready
var fail = function (message) {    
   alert(message)
}
var success = function (data) {
   console.log("succes");
}
cordova.plugins.DownloadManager.download("Your URL to download", success, fail);
```
I hope it helps.

**Comment by amitinnotical** [comment]
i have same issue i need to show downloading progress on notification bar.

**Comment by vasani-arpit** [comment]
@amitinnotical 
If you are downloading a file and want to show it's progress then you can use my plugin
https://github.com/vasani-arpit/cordova-plugin-downloadmanager

if you want to show progress bar for other purposes you need to fork this repo and make changes on your own.
Do an PR so that others can use that feature too.

**Comment by amitinnotical** [comment]
Thanks for this. And I used this plugin in my project and obviously I did
modifications in your Java file..
Nice plug-in and helpful too.

**Comment by katzer** [comment]
@amitinnotical v0.9.beta supports progress bar:
https://github.com/katzer/cordova-plugin-local-notifications#progress

**Comment by DaltonHarvey** [comment]
> @amitinnotical v0.9.beta supports progress bar:
> https://github.com/katzer/cordova-plugin-local-notifications#progress

did u try do use it?
