### ISSUE TITLE
New API for Notifications in iOS 8

### ISSUE THREAD

**Issue by joseandrespg** [katzer/cordova-plugin-local-notifications#250]
Hi!

Testing this plugin in iOS 8 crashes, then I make some searches and found the problems: 
- iOS 8 use a new API to push notifications
- iOS 8 need grant user permissions to display different types of notifications

iOS 8 changelog: https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewIniOS/Articles/iOS8.html

A quote from deprecated list:

    The UIApplication methods and properties for registering notifications. Use the new API instead

Will support this plugin this new API?

Thanks in advance!

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
