### ISSUE TITLE
notification scope and callback

### ISSUE THREAD

**Issue by voidbrain** [katzer/cordova-plugin-local-notifications#252]
I have this loop in my code, it shows the final callback "done" but i never see "notification id: "
why?
var data = ["2014-09-10","2014-09-10","2014-09-10"];
for (var i in data) {	
	var d = new Date(data[i]);
	d.setDate(d.getDate() - 1);
	d.setHours("18");
	d.setMinutes("00");
	d.setSeconds("00");
	window.plugin.notification.local.add({
		autoCancel: true,
		id:      i+"_"+d,
		title:   'Calendario svuotamenti',
		message: "Tomorrow: "+data[i],
		date:    d 
	},function(){
		console.log("notification id: "+i+"_"+d);
	},i);
}
console.log("done");

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
