### ISSUE TITLE
cancel all callback

### ISSUE THREAD

**Issue by voidbrain** [katzer/cordova-plugin-local-notifications#253]
window.plugin.notification.local.cancelAll( function(){console.log("done")} )
never returns a callback, why?

**Comment by tomchambers2** [comment]
I'm experiencing the same issue #389

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
