### ISSUE TITLE
iOS 6 crash with loop 

### ISSUE THREAD

**Issue by voidbrain** [katzer/cordova-plugin-local-notifications#254]
this code works fine with ios7 and android, but on ios6 it sets notifications but after that, if i move inside the app, it crashes. Maybe a memory leak?

var data = ["2014-09-10","2014-09-10","2014-09-10"];
for (var i in data) {
      var d = new Date(data[i]);
      d.setDate(d.getDate() - 1);
      d.setHours("18");
      d.setMinutes("00");
      d.setSeconds("00");
      window.plugin.notification.local.add({
            autoCancel: true,
           id: i+""+d,
            title: 'Calendario svuotamenti',
            message: "Tomorrow: "+data[i],
            date: d 
      },function(){
            console.log("notification id: "+i+""+d);
      },i);
}
console.log("done");

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
