### ISSUE TITLE
Notification not showing on Android 4.4.4

### ISSUE THREAD

**Issue by aminecmi** [katzer/cordova-plugin-local-notifications#255]
Hi,

I'm trying to use this plugin with steroids, but I'm facing an issue.
The notification is added, then triggered, but never appears in the notification bar.
However, the led of the phone is glowing.
I'm using a Nexus 5 with the last stock Android (4.4.4).
I'm also using Angular.

Here is my sample code.
```
$window.document.addEventListener("deviceready", function() {
  window.plugin.notification.local.add({ message: 'Great app!', led: '66CD00' });
  window.plugin.notification.local.onadd = function (id, state, json) {
    $window.alert('here');
  };
  window.plugin.notification.local.ontrigger = function (id, state, json) {
    $window.alert("here too")
  };
}, false);
```

In addition, to use the plugin with steroids, I had to fork, and remove this line:
```
<lib-file src="libs/android/android-support-v4.jar" />
``` 

Is this a known issue?
Thanks for your help.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
