### ISSUE TITLE
big view

### ISSUE THREAD

**Issue by ikawka** [katzer/cordova-plugin-local-notifications#256]
is big view possible?

**Comment by kozuch** [comment]
The docs do not mention "big view" at all so I assume the plugin can not do it. However, this would really be a nice feature for Android to have! :)

**Comment by katzer** [comment]
@ikawka,

please can you specify a bit more what you mean and want. The plugin auto use big-view style on Android.

**Comment by kozuch** [comment]
@katzer: you say the plugin already uses big-view style notification automatically? If so, how can a big notification be triggered?

**Comment by katzer** [comment]
https://github.com/katzer/cordova-plugin-local-notifications#i-would-like-to-propose-new-features
