### ISSUE TITLE
iOS 8: App requests push notification permissions immediately on first launch

### ISSUE THREAD

**Issue by brianglick** [katzer/cordova-plugin-local-notifications#258]
My Cordova app (version 3.5.0-0.2.7), in iOS 7, requests push permissions from the user when I try to register the device.

Now, in iOS 8 (beta 5, with Xcode beta 7), it requests push permissions the moment the app is opened for the first time. This is not good, since users will often deny permission if the request isn't given some context.

From what I can tell, iOS 8 now lumps remote push notifications and local notifications together into the same permission request, whereas previously, local notifications weren't separately requested. (Source: http://forums.coronalabs.com/topic/50722-ios-8-corona-apps-ask-for-push-notification-approval/) Is it possible that this plugin is requesting local notification permissions behind the scenes at launch, and now, in iOS 8, that's getting surfaced to the user?

The only Cordova plugin I have that seems related is PushPlugin. (Not using any local notification plugins.)

Thanks for any help!

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
