### ISSUE TITLE
Run notification on specific days

### ISSUE THREAD

**Issue by sharjeelz** [katzer/cordova-plugin-local-notifications#259]
I am using jquery mobile, i am creating notifications on as many dates as i like to, but can i do something to activate my notification on specific day? e. g. user selected monday,wednesdy at 4:00 PM , so the notification run on    "EVERY COMING"   monday and wednesday at 4:00 PM?
I hope u understand my point.
thanks

**Comment by g105b** [comment]
The date parameter of the configuration object is simply a JavaScript `Date` object. You can construct it however you want. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
