### ISSUE TITLE
When i restart my phone i get "unfortunately myapp has stopped working"

### ISSUE THREAD

**Issue by Mac956** [katzer/cordova-plugin-local-notifications#26]
Hi, like the title says: When i restart my phone i get "unfortunately myapp has stopped working", if i uninstall your plugin i don't get that error. Thanks in advance again.
Btw is there a way i can make a donation, i'm asking for a lot of changes. Thanks again

**Comment by alan0xd7** [comment]
I just encountered this problem with the latest version of the plugin. When the phone is restarted there's a message saying the app has stopped. Currently tested on Android 4.4.4 and 5.0.0 (Genymotion).

My app only needs the notifications displayed right away, so as a workaround I've removed the boot intent filters and permission from AndroidManifest.xml.

Please let me know if you need any details to help fix this, thanks.
