### ISSUE TITLE
perpetual crash after notification

### ISSUE THREAD

**Issue by frigon** [katzer/cordova-plugin-local-notifications#263]
Testing the localnotification on ios8 on an ipad and have noticed that if notification fires AND the app has be killed (not running in the background) the app can no longer launch EVER which renders the app dead.  I'm using the sample app provided in the source code.

Steps to reproduce:
1. launch demo app
2. fire notification
3. exit app
4. kill app (double click home and kill the app via swipe)
5. wait for notification
6. click on app
= crashing app from thereafter

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
