### ISSUE TITLE
Non-repeating notifications that have triggered aren't handled correctly

### ISSUE THREAD

**Issue by msscully** [katzer/cordova-plugin-local-notifications#265]
If a notification with a null repeat value triggers it will correctly appear in the notification center. However it will not be listed in getTriggeredIds or getScheduledIds and you won't be able to cancel it programmatically, meaning a user has to click on it for it to go away.

Steps to reproduce:
1. Create a notification for now that does not repeat.
2. After the notification has triggered, check that its id does not appear in the output of window.plugin.notification.local.getScheduledIds or window.plugin.notification.local.getTriggeredIds.
3. Call window.plugin.notification.local.cancel with the notification Id and it will remain in the notification center.

Expected behavior:
A non-repeating notification should be cancelable even after triggering, and should be included in the list of triggered Ids if it has been triggered but not cleared/canceled. It may also make sense for a non-repeating notification to stay in the list of scheduledIds if it has triggered but its notification hasn't been clicked or canceled.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
