### ISSUE TITLE
handling localnotification after app is closed

### ISSUE THREAD

**Issue by josmarycarrero** [katzer/cordova-plugin-local-notifications#266]
Hi, i'm using this 2 events:  notification.local.ontrigger, notification.local.onclick.
I understand that only works in either background or foreground state. But there is a way that once the app is closed, and the notification i'ts triggered after to capture that event 
somehow?

**Comment by quelo83** [comment]
+1

**Comment by katzer** [comment]
@josmarycarrero, call `getTriggered()` on start and make a diff!

The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
