### ISSUE TITLE
Callback from promptForPermission

### ISSUE THREAD

**Issue by danielsmith-eu** [katzer/cordova-plugin-local-notifications#272]
I'm using the IOS8 version (latest commit from branch 0.7) and it doesn't look like the 'promptForPermission' call allows a callback - is this possible to have?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
