### ISSUE TITLE
hasPermission never calls callback

### ISSUE THREAD

**Issue by danielsmith-eu** [katzer/cordova-plugin-local-notifications#273]
The hasPermission callback is never called - this is on IOS8 in the simulator.

I can get notifications to work, but I'd like to check first.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
