### ISSUE TITLE
"dependency conflict" problem

### ISSUE THREAD

**Issue by bau720123** [katzer/cordova-plugin-local-notifications#274]
hi @katzer 

PGB told me my app have a "dependency conflict" problem
http://www.littlebau.com/de01.jpg

I check your latest plugin，but find that only support device 0.2.8 for now
http://www.littlebau.com/de02.jpg

but the latest device plugin is 0.2.12
http://www.littlebau.com/de03.jpg

maybe you should delete this line your plugin.xml
```
<dependency id="org.apache.cordova.device" url="https://github.com/apache/cordova-plugin-device" />
```

so I have been made a pull request
https://github.com/katzer/cordova-plugin-local-notifications/pull/275

**Comment by bau720123** [comment]
hi @katzer 
I seem found a way to solve it
http://community.phonegap.com/nitobi/topics/-plugins-cordova-io-seem-not-really-work
is my way right ?

**Comment by katzer** [comment]
hi @bau720123, I have resolved it: 954d727d9faed41565ff9bfd3dcbdeaa3a5bcca4

**Comment by bau720123** [comment]
thanks @katzer 
maybe the new version will have a update in 3rd plugin ?
https://build.phonegap.com/plugins/all

or...just update from "plugins.cordova.io" by future ?

**Comment by katzer** [comment]
I want publish all plugin updates within the next (2) weeks
