### ISSUE TITLE
Crash: [__NSCFString stringValue]: unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by orbitaloop** [katzer/cordova-plugin-local-notifications#281]
I have a crash when there is existing LocalNotifications (previously scheduled with a previous version?).

**[__NSCFString stringValue]: unrecognized selector sent to instance (in notificationWithId method) **

I am a newbie in Objective C, but it looks like it's because the method is calling stringValue on an object that is already a string.

So I added this changed in bold: 

 - (UILocalNotification*) notificationWithId:(NSString*)id
 {
     NSArray* notifications = self.scheduledNotifications;
    
     for (UILocalNotification* notification in notifications)
     {

    **NSString* notId = NULL;
    if ([[notification.userInfo objectForKey:@"id"] isKindOfClass:[NSString class]] ) {
      notId = [notification.userInfo objectForKey:@"id"];
     } else {**
        notId = [[notification.userInfo objectForKey:@"id"]  stringValue];
     }**

Is it a good change? Or am I a completely wrong? I am about to release this code to Apple.. Thanks for your feedback

**Comment by romil-choksi** [comment]
I have updated my AppLocalNotification.m to incorporate these changes:
https://github.com/pavoltanuska/cordova-plugin-local-notifications/commit/2e6ab6590c1ea703bd4ced3d0005bf4c7e7a4339

I don't see the [__NSCFString stringValue] error anymore in the console log but I am still not able to generate a local notification. I have set the permission for local notification using promptForPermission and the hasPermission returns true

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
