### ISSUE TITLE
How to clear badge number?

### ISSUE THREAD

**Issue by g105b** [katzer/cordova-plugin-local-notifications#282]
After scheduling a notification like this:

```javascript
window.plugin.notification.local.add({
    /* ... */
    badge:      1,
    /* ... */
});
```

the icon on iOS gets a nice little 1 badge on it. This badge stays there forever, even after uninstalling and reinstalling the app.

Any ideas on how to remove the badge?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
