### ISSUE TITLE
Is there a way to get json data from isScheduled method?

### ISSUE THREAD

**Issue by tomswatermelon** [katzer/cordova-plugin-local-notifications#284]
Hi,

I am trying to get the json data from this method:

```
window.plugin.notification.local.isScheduled(id, function (isScheduled) {
    // console.log('Notification with ID ' + id + ' is scheduled: ' + isScheduled);
});
```

is that possible?

Thanks!

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
