### ISSUE TITLE
Sample app for Background service and local notification

### ISSUE THREAD

**Issue by akhilsinghal** [katzer/cordova-plugin-local-notifications#285]
This is a great plugin. Thanks to the contributors!!

I am new to Cordova and I have one requirement in which there will be one service which will run in background. It will make a call to server once every 24 hours and if it founds any data then it will create a local notification by Displaying an alert on banner, Badging the app’s icon and Playing a sound. otherwise sleeps for next 24 hours. If user taps on banner or app then that notification should go away.

I am not able to find much samples on web. Can you please provide some help links or samples if you have having similar requirements.

**Comment by jbeuckm** [comment]
Subscribe - trying to do the same.

**Comment by tuomaslaa** [comment]
I'am also trying to execute scheduled local notification on silent background remote notification. It won't work, no errors either. In schedule foreground it will work. I'am using this plugin for the remote and silent background notifications  https://github.com/jbeuckm/PushPlugin
