### ISSUE TITLE
iOS sstopped working in cca (Chrome Cordova Apps / MobileChromeApps)

### ISSUE THREAD

**Issue by g105b** [katzer/cordova-plugin-local-notifications#287]
I have been using this plugin within my cca app, and it totally stopped working today. Can't work out the reason behind this.

iOS 8, cca 0.4.1

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
