### ISSUE TITLE
Not asking for permissions to show alerts (iOS 8)

### ISSUE THREAD

**Issue by timbergus** [katzer/cordova-plugin-local-notifications#288]
I am creating an app that check the position of the user in background and then notify him when reaching a place. The problem is that the alerts never show because they don't have the user's permission to show. How I need to configure the plugin or the project to force my app asking permission to the user?

The messages I have in Xcode are the following:

    Attempting to schedule a local notification [...] with an alert but haven't received permission from the user to display alerts
    Attempting to schedule a local notification [...] with a sound but haven't received permission from the user to play sounds

Could you please help me?

Thanks in advance,

Gustavo

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by MikeBBarreiro** [comment]
build.phonegap.com does not support de.appplant.cordova.plugin.local-notification to be built.

![image](https://user-images.githubusercontent.com/7136454/38834775-08eba330-418f-11e8-84ab-0367ef979ee0.png)
