### ISSUE TITLE
I realize the title says Cordova 3.x.x, but will this support Cordova 4?

### ISSUE THREAD

**Issue by devinle** [katzer/cordova-plugin-local-notifications#291]
I'm curious, because after following the install steps, and verifying that the plugin is listed in the cordova_plugins.js file within the ios build, it still won't fire anything. It comes up as undefined in the console.

Thanks for you help on this.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
