### ISSUE TITLE
getTriggeredIds issue

### ISSUE THREAD

**Issue by meiriko** [katzer/cordova-plugin-local-notifications#292]
I found a bug in getTriggeredIds, I have a workaround code but it is quite messy, sorry for not contributing a PR.

The bug is when calling:

    arguments = (JSONObject)alarms.get(id)

alarms.get(id) returns a string which is actually a JSONArray. I don't know the code well enough to understand why this happens but the work around is along the lines of:

    JSONArray ja = new JSONArray(alarms.get(id).toString());
    arguments = ja.getJSONObject(0);

This seems to work for me

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
