### ISSUE TITLE
isTriggered either not working properly or lacks a clear definitions

### ISSUE THREAD

**Issue by meiriko** [katzer/cordova-plugin-local-notifications#293]
I am trying to use the isTriggered function. I am not sure what it should do, there are 2 options:

1. Return value ONLY for repeating notifications - in this case it is not clear from the documentations.
2. Return true for all notifications (including NON repeating ones) - in this case it is not working properly. For example, if I add a handler for the ontrigger and inside it query isTriggered with the same id, I get false (though the notification is open). This is because the method starts with:

`boolean isScheduled = alarms.containsKey(id);`

and the following logic block is entered only if:

    if(isScheduled){
      ...
      ...
    }

but once a non repeating alert is displayed, its schedule is removed and the content of the block will never be evaluated.

Thx again for a great plugin

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
