### ISSUE TITLE
Crash: iOS8, crashes in notificationWithId when adding a new notification

### ISSUE THREAD

**Issue by bogdanripa** [katzer/cordova-plugin-local-notifications#294]
XCode crash at:
```
        NSString* notId = [[notification.userInfo objectForKey:@"id"]
                           stringValue];
```
(AppLocalNotification.m)

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString stringValue]: unrecognized selector sent to instance 0x17803fee0'

When:
```
window.plugin.notification.local.add({
	    title:   'Lots of new photos!',
	    message: 'Come back and check it out.',
	    repeat:  'daily',
	    date:    new Date(now + 10*1000)
	});
```

**Comment by asecondwill** [comment]
I tried this fix in /plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m  however running the app on my phone via xcode gets the same error with the line unchanged in the debugger.   Any hints on how to apply this change?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
