### ISSUE TITLE
cannot read property 'local' of Undefined

### ISSUE THREAD

**Issue by daxeshS** [katzer/cordova-plugin-local-notifications#295]
I want my cordova android application to show local notifications.
when application starts it will make messeges and will show in notification area.
for that i am using local notification plugin.below it is:
https://github.com/katzer/cordova-plugin-local-notifications/
i have implemented it step by step.always geeting error likke : "cannot read property local of Undefined".
do i misiing something?
need help.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by roysG** [comment]
same issue for me

**Comment by roysG** [comment]
also happen to me.

**Comment by Trylar** [comment]
issue still happen to me.

**Comment by Viterbo** [comment]
maybe you didn't install the plugin propertly.
Run this in command line:

`cordova plugin add de.appplant.cordova.plugin.local-notification`
