### ISSUE TITLE
Cordova 4

### ISSUE THREAD

**Issue by voidbrain** [katzer/cordova-plugin-local-notifications#296]
App crashes with cordova 4 (iOS 8.1) 
i'm inside a loop with scoped var, i've a success feedback after setting notifications and then it crashes. 
error is on 
AooLocalNotification.m
 * Retrieves the local notification by its ID.
 NSString* notId = [[notification.userInfo objectForKey:@"id"]

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
