### ISSUE TITLE
Does anyone has a working example?

### ISSUE THREAD

**Issue by philecom** [katzer/cordova-plugin-local-notifications#297]
I seems not to get my hand on it, I dont know where to start. I will be glad if anyone can share a sample of their code for people like me to learn from it.. Thank you

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
