### ISSUE TITLE
Notification Properties Clarification

### ISSUE THREAD

**Issue by philecom** [katzer/cordova-plugin-local-notifications#298]
Please can someone explain the use of the following properties of the notification object.
BADGE and JSON. Thank you
window.plugin.notification.local.add({
    badge:      Number,  // Displays number badge to notification
    json:       String,  // Data to be passed through the notification
}, callback, scope);

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by katzer** [comment]
https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling
