### ISSUE TITLE
iOS 8 Error

### ISSUE THREAD

**Issue by garyns** [katzer/cordova-plugin-local-notifications#299]
The call window.plugin.notification.local.add({ message: 'Great app!' }); is the following the following error below for me in iOS8.0.2. Or the app just crashes. Working fine in Android. I've tried using Cordova 4 (also tried a 3)

(Using Weinre, window.plugin.notification.local.hasPermission(function (granted) { console.log(granted) }) echos true)

(lldb) 2014-10-23 15:21:06.359 mybizapp[1294:615092] -[__NSCFString stringValue]: unrecognized selector sent to instance 0x17521af0
(lldb) 2014-10-23 15:21:06.360 mybizapp[1294:615092] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString stringValue]: unrecognized selector sent to instance 0x17521af0'
*** First throw call stack:
(0x293ade3f 0x36a5bc8b 0x293b3189 0x293b10a7 0x292e3208 0x128d87 0x128bb7 0x125b5f 0x36fbb8cb 0x36fc4da3 0x36fc5cd7 0x3711ce31 0x3711cb84)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) Process 1294 stopped
* thread #10: tid = 0x962b4, 0x370a1dfc libsystem_kernel.dylib`__pthread_kill + 8, queue = 'com.apple.root.default-qos', stop reason = signal SIGABRT
    frame #0: 0x370a1dfc libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill + 8:
-> 0x370a1dfc:  blo    0x370a1e14                ; __pthread_kill + 32
   0x370a1e00:  ldr    r12, [pc, #4]             ; __pthread_kill + 24
   0x370a1e04:  ldr    r12, [pc, r12]
   0x370a1e08:  b      0x370a1e10                ; __pthread_kill + 28
(lldb)

**Comment by pinkfire** [comment]
@zeroshadow, work for me also...

**Comment by tamilp** [comment]
Working for me also @zeroshadow thank you...

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
