### ISSUE TITLE
Crash: IOS8 (Background Fetch)

### ISSUE THREAD

**Issue by apollon0815** [katzer/cordova-plugin-local-notifications#300]
Hello,

I use the plugin to send notifications over the background fetch. first time everthing works well. at the second fetch I get this error:

2014-10-23 12:05:37.349 DemoApp[4218:33624] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString stringValue]: unrecognized selector sent to instance 0x7f87b166b5c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010addaf35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010d605bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010ade204d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010ad3a27c ___forwarding___ + 988
	4   CoreFoundation                      0x000000010ad39e18 _CF_forwarding_prep_0 + 120
	5   DemoApp                             0x000000010abb6ae6 -[APPLocalNotification notificationWithId:] + 470
	6   DemoApp                             0x000000010abb68ae -[APPLocalNotification isNotificationScheduledWithId:] + 62
	7   DemoApp                             0x000000010abb3422 __28-[APPLocalNotification add:]_block_invoke + 178
	8   libdispatch.dylib                   0x000000010dd26ba6 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x000000010dd447f4 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010dd2f15d _dispatch_root_queue_drain + 1097
	11  libdispatch.dylib                   0x000000010dd30612 _dispatch_worker_thread2 + 52
	12  libsystem_pthread.dylib             0x000000010e0dcef8 _pthread_wqthread + 314
	13  libsystem_pthread.dylib             0x000000010e0dffb9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
