### ISSUE TITLE
IOS 8.1 ontrigger/onclick not firing

### ISSUE THREAD

**Issue by grillorafael** [katzer/cordova-plugin-local-notifications#301]
Hi guys!

My local push gets triggered by a beacon running in background (using background mode plugin). I receive the push notification but I can't handle how they are opened.

Any ideas?

**Comment by lucaele** [comment]
Hi,
i'm interesting in use ibeacon in background. Can u share your code for background mode plugin?
thanks

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
