### ISSUE TITLE
Missing Push Notification

### ISSUE THREAD

**Issue by zeroshadow** [katzer/cordova-plugin-local-notifications#302]
Ciao Katzer, nice to see you again ;)

got email from apple: Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service...

Do I have to enable the push notifications in the App ID section (iOS developer) or not?
If yes, should I do something with the de.appplant.cordova.plugin.local-notification or it is OK like this.

Thanks in advance for your kind as always answer.

**Comment by sparkycrisse** [comment]
I am also experiencing this problem...

**Comment by davidtron** [comment]
I also have this issue.

**Comment by BartReymenants** [comment]
+1

**Comment by katzer** [comment]
if your app has some missing entitlements you can add them via Xcode.
Nevertheless thats a __local__ notification plugin and does not use anything from __remote__ notification API nor it tries to connect the APNR Server!

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by insane210** [comment]
Hello @katzer ,

I still get this warning from Apple with the latest version 0.8.1

> **Missing Push Notification Entitlement** - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

Could you give some info, if this is intended or if it is not intended remove the given API?

Thanks

**Comment by salilsethi** [comment]
+1 I have the same issue. Did anyone figure out how to resolve this

**Comment by ian-katsuno** [comment]
+1 Also having this issue

**Comment by skotturi** [comment]
I am also getting this message from Apple. 

From this apple developer forum post: https://forums.developer.apple.com/thread/15880

> I also guess that it is a (new) bug in Apples checking system. I uploaded an app yesterday and got this > message. This app has been updated at least 30 times without any problems. I didn't add any push >notification code in the last version and I don't use any frameworks like PhoneGap or Cordova that >could cause this message. I have searched the app for push notification code without finding anything. >It doesn't appear under notifications on the device.
 
>I also tried to upload the previous version that was approved in July (and didn't generate an email). This >this time I got the warning email also for this version. So I think that Apple is wrong and I will take my >chances and hope it will be approved despite the warning.
