### ISSUE TITLE
No sound in iOS8 using 0.7 branch

### ISSUE THREAD

**Issue by lewisde** [katzer/cordova-plugin-local-notifications#306]
I've double checked the notification and sound settings. The app is able to set sound and plays the notification sound in iOS 7.1 but not in iOS 8.1. Otherwise, notifications work fine.

Has the reference to default sound changed in iOS 8 SDK?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
