### ISSUE TITLE
Notification won't show up, but otherwise, seems to be installed correctly.

### ISSUE THREAD

**Issue by devinle** [katzer/cordova-plugin-local-notifications#308]
Hi all. 

I've been working with this plugin, but I'm really hitting a snag. I've download from the branch, which includes the necessary ios8 updates (prompt for permission and has permission). And when I run the following code, I can see the correct info sent to the console. But the notification just won't actually display.

After running the emulator a second time. I can see 22 showing up. And my permission shows as true. But the notification just wont show up! Does this not work in XCode's emulator? Do I just have to put it on an actual device to see them?

I've also removed my platform and rebuilt it several times. Still no luck. Please help. Thanks.

window.plugin.notification.local.getScheduledIds(function (scheduledIds) {
             console.log('Scheduled IDs: ' + scheduledIds.join(' ,'));
});

window.plugin.notification.local.hasPermission(function (granted) {
              console.log('Permission has been granted: ' + granted);

              window.plugin.notification.local.add({
                       id:      22,
                       title:   'Reminder',
                       message: 'Dont forget to buy some flowers.',
                       repeat:  'weekly',
                       date:    1000
              });
});

**Comment by Hirbod** [comment]
Hi, thanks for that. But this is just a alert. How does WhatsApp Achieve the native InApp-Banners? Did they implemented something selfmade?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by Hirbod** [comment]
So you're not sure about InApp Notification banners? Is this even possible ?

**Comment by katzer** [comment]
Hi @Hirbod, please make a feature request:
https://github.com/katzer/cordova-plugin-local-notifications#i-would-like-to-propose-new-features
