### ISSUE TITLE
Plug-In causes cordova build to fail

### ISSUE THREAD

**Issue by PeterA1** [katzer/cordova-plugin-local-notifications#310]
Hi,

When I install the plugin, build fails, when I remove the plugin cordova build works. The Error Messages contain the following....

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:62:5: note: 
      'UIRemoteNotificationTypeBadge' declared here
    UIRemoteNotificationTypeBadge   = 1 << 0,
    ^
/Users/web7/Documents/plex/PlexClient/platforms/ios/PlexClient/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m:273:73: error: 
      use of undeclared identifier 'UIUserNotificationTypeSound'; did you mean 'UIRemoteNotificationTypeSound'?
        types = UIUserNotificationTypeAlert|UIUserNotificationTypeBadge|UIUserNotificationTypeSound;

Any advice?

I am using xCode v5, Cordova v3.5.0-0.2.4 and ios 7.

Best Regards
Peter

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
