### ISSUE TITLE
Crashing on all ios

### ISSUE THREAD

**Issue by ghost** [katzer/cordova-plugin-local-notifications#312]
Not entirely sure whats going on at all...
Receiving SIGBRT error.
The output:

```
2014-11-07 12:44:58.505 HelloWorld[12846:4653521] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull doubleValue]: unrecognized selector sent to instance 0x5576b0'
```

The problematic line at Line 425:
`double timestamp = [[options objectForKey:@"date"] doubleValue];`

The javascript thats creating the alarm:

``` javascript
 function set_alarm_notification(savedDate, days){
           //replace dashes with slashes because of weird javascript date bug
            savedDate = savedDate.replace(/-/g,'/');
            var lastDateToDate = new Date(savedDate);
            lastDateToDate.setDate(lastDateToDate.getDate() + (parseInt(days)));
            //make alarm happen at 8am edt
            var lastDateString = (lastDateToDate.getMonth()+1)+" "+(lastDateToDate.getDate())+", "+lastDateToDate.getFullYear()+" 08:00:00 EDT";
            var lastDateTime = new Date(lastDateString);
            //make notification happen 3 days before time
            lastDateTime.setDate(lastDateTime.getDate() - 3);
            window.plugin.notification.local.add({
                id:      1,
                title:   'Reminder',
                date:    lastDateTime,
                message: 'Remember to buy flowers!'
            });
```

Note:
I'm using the bug fix for the notification ID
changing
`NSString* notId = [[notification.userInfo objectForKey:@"id"] stringValue];`
to this
`NSString* notId = [notification.userInfo objectForKey:@"id"];`

**Comment by asecondwill** [comment]
@lbodden  - I'm getting the same error.  Why did you close this? how did you fix it?  Any hints on how to resolve it would be great.  Thanks : )

**Comment by asecondwill** [comment]
I think this is caused when the app hasn't got LN  permissions.

**Comment by lbodden** [comment]
Sorry for late reply... But yes it was because I was not asking for permissions for notifications first. I added the two functions hasPermission and promptForPermission with some pretty standard logic to prevent this from happening.
