### ISSUE TITLE
window.plugin undefined

### ISSUE THREAD

**Issue by daniil967** [katzer/cordova-plugin-local-notifications#313]
I tried installing and re-installing this plugin few times with different examples from issues, no luck. Tried ngCordova guide, also no luck. Fairly baffled on what is going on. I am using Cordova 4

	$scope.submit_ping  = function(){ 
			document.addEventListener("deviceready", onDeviceReady, false);
			console.log(window.plugin)
			function onDeviceReady() {
				// Now safe to use the Cordova API
				console.log("inside")
				 window.plugin.notification.local.add({
							id: 1, //Can be number or string
							message: "Wohoo!"
						}, function () { //Callback
							_alertOnTrigger(); 
						});
			}
		}

`window.plugin` returns undefined, whatever I do
`window` does exist, and `window.Plugin`... but that bears nothing, it seems like different item

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
