### ISSUE TITLE
Local notification is coming randomly

### ISSUE THREAD

**Issue by nirajmchauhan** [katzer/cordova-plugin-local-notifications#314]
I am trying to create a notification on my phonegap app, when I create notification with the below code:

```
localNotification = window.plugin.notification.local;
console.log(localNotification);
var status = localNotification.add({ message: 'Good Morning' });
console.log(status);
```

I am not getting immediate notification and it comes randomly after 5-10 mins, the above status is printing as 0

Here is the screenshot of the debugging:

![screenshot from 2014-11-13 18 17 06](https://cloud.githubusercontent.com/assets/1540451/5028453/56b63902-6b61-11e4-87f0-71188b1c4905.png)

Object is the output of localNotification and 0 is of status. Also I am invoking this code inside onDeviceReady function

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
