### ISSUE TITLE
Sound with repeating notification in Android

### ISSUE THREAD

**Issue by MichelReij** [katzer/cordova-plugin-local-notifications#315]
Hi, I have the notifications working fine in iOS, with the app uploaded for review by Apple today.
But setting a repeating notification in Android, minutely (just for testing), daily or weekly, results in playing the sound only on the first occurrence, not on the next repetitions.

Part of my code:
```JavaScript
window.plugin.notification.local.add({
   'id': 209,
   'title': task.getName(),
   'message': task.getInfo() ? task.getInfo() : " ",   // Make sure there's at least a space in msg
   'sound': task.getSound(),
   'repeat': "minutely",
   'date': task.getFirstOccurrence(),
   'autoCancel'	: false,
   'led': 'CADC05',
   //'ongoing': false
});
```

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
