### ISSUE TITLE
Is there a way to schedule a daily task to set up a Notification?

### ISSUE THREAD

**Issue by wrenzi** [katzer/cordova-plugin-local-notifications#316]
Hi,

First of all, great plugin.

One question: Is there a way to schedule a daily task to set up a Notification? My need is show a default Notification, daily, but it depends if the user inserts something in the local storage or not.

So, the logic would be:

```
daily do
  if (user inserted new words?) do
    notify("some text")
  else
    //nothing
  end
end
```

Thanks,
Renzi

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
