### ISSUE TITLE
Listen to response of permission request

### ISSUE THREAD

**Issue by ripcurlx** [katzer/cordova-plugin-local-notifications#319]
Hi,

the 0.7 branch works great for me, but I need to get the response on the permission dialog, to be able to create the notification or not to create the notification afterwards. I saw in the docu that it should be doable by overwriting the app delegate method [didRegisterUserNotificationSettings](https://developer.apple.com/library/ios/documentation/uikit/reference/uiapplicationdelegate_protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/application:didRegisterUserNotificationSettings:). Unfortunately I'm such an objective-c noob that I didn't find out how to forward this method from the appDelegate property within the phonegap plugin to a custom implementation. If someone could point me in the right direction I'd love to extend the branch with a response functionality.

Best,

Christoph

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
