### ISSUE TITLE
Documentation for successful Apple store submittal is missing

### ISSUE THREAD

**Issue by jgberg** [katzer/cordova-plugin-local-notifications#322]
Many of us are new to the Apple app submission process. In the process of development and using TestFlight we receive warning emails from apple when we submit our app to iTunes Connect. The warning email from apple says that we _seem_ to be using the "Apple Push Notification" service, and we may want to indicate that in our apps' Provisioning Profile.  So does is this local notification plugin require the "Apple Push Notification" service?  And if so, when add that to our provisioning profile do we need to allocate SSL keys and so forth?

Can someone please describe what is needed (if anything) for uses of this plugin to successfully submit their app to iTunes Connect without complaint?  A related issue is #302 

Here is the email from apple.com:
'''
Dear developer,

We have discovered one or more issues with your recent delivery for (YOUR APP NAME). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

Regards,

The App Store team
'''

**Comment by katzer** [comment]
The plugin does not make use of any push notification APIs since its a local notification plugin

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
