### ISSUE TITLE
Perform a function before to send the push

### ISSUE THREAD

**Issue by baloran** [katzer/cordova-plugin-local-notifications#324]
Hello,

I have a question about this plugin. I need to get information in a rest API and after transmit this to this plugin. But i need cron job to execute this task every day at a certain time. 

If you have a solution I'm interested.

Thanks you

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
