### ISSUE TITLE
Cannot play sound from local folder

### ISSUE THREAD

**Issue by philecom** [katzer/cordova-plugin-local-notifications#325]
Hello, Good day.
Please can someone help me out. I have set the notification and everything is working well except playing custom sounds both from the asset folder or the resource folder.

this is the path to my assets folder
sound: '/www/sound/whistle.mp3'

and the path to my resource folder
sound: 'android.resource://' + package_name + '/raw/sound/whistle.mp3'

I will be glad if anyone can help me out especially with a sample code. i am developing for both Android and iOS. Thank you

**Comment by Alkashi** [comment]
Exactly the same issue. Only a remote sound works on my Android app :/
If someone has an idea...

**Comment by MichelReij** [comment]
Alkashi, in my situation it was user error: I had misinterpreted the way the merge folder was copied into the platform folder, so my sound files were ending up in the wrong location. I found out I had to copy the sound files to /platforms/android/res/raw/ manually.
Then you can reference them like you describe above, with the package name being the reverse url identifier that you specified when you created your app through the CLI. And you can omit the file extension, although I'm not sure it's necessary. Example from my app:
```javascript
	switch (device.platform) {
		case "iOS":
			notif.sound = "www/sound/" + notif.sound + ".caf";
			break;
		case "Android":
			notif.sound = 'android.resource://com.benedictime.benedictime/raw/' + notif.sound;
			break;
	}
```

**Comment by Alkashi** [comment]
I did exactly the same and I can't still not here the sound. The notification is fired correctly but without sound. 
I build my app with the cordova build. And try with the app-debug.apk file generated. 
Do you think the package name is change when it run on the debug mode ?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by Alkashi** [comment]
It works perfectly now.
Thanks a lot guys !
