### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by p4ulypops** [katzer/cordova-plugin-local-notifications#326]
Hi,

I'm very new to using Cordova (and iOS development), so please forgive me if this is silly,

I'm getting the following error when deployed to my device
```
Error in Success callbackId: LocalNotification440305403 : TypeError: undefined is not an object (evaluating 'callback.call')
```

And my code is
```javascript
   window.plugin.notification.local.add({
                        id: 1,
                        title: 'Reminder',
                        message: 'Dont forget to buy some flowers.',

                    }, function() {
                        console.log("Added:");

                    }
                );
```

If someone can help me out, that would be apprechated.

**Comment by davidpfahler** [comment]
I have the same problem and the id is a string. The notification is scheduled, but the callback never fires.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
