### ISSUE TITLE
Local Notification fires on add if hour matches

### ISSUE THREAD

**Issue by derpnificent** [katzer/cordova-plugin-local-notifications#327]
Hey!

I have a problem with my notifications and I wonder if you guys can help! I have set the time my notification should fire like this: 
                        var date = new Date(moment().day(3));
                        date.setHours(15,1,0); 
                        $scope.addNotification('v86','Test first notification', date);
It works and I get it on wednesday at 15:01 when I initilize the notification between 15;01 and 15;59 on a wednesday I get it aswell. Anyone knows a fix for this? I run lollipop on my Nexus5.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
