### ISSUE TITLE
How to extend to include RingtoneManager?

### ISSUE THREAD

**Issue by micBaird** [katzer/cordova-plugin-local-notifications#328]
The notifications work and are using the default sound, but I would like to extend this plugin to allow the user to choose the sound they wish to hear for the notification. Any ideas on how to incorporate this feature?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
