### ISSUE TITLE
How to use  cordova-plugin-local-notifications for server based page?

### ISSUE THREAD

**Issue by Chintanpan** [katzer/cordova-plugin-local-notifications#329]
Hello first of all congratulation for this awesome plugin.
ISSUE:
this plugin works fine in local page(assets/www/index.html).when i write your demo code here its work perfectly.but
in my phonegap app local  index.html page called server page(eg. www.website.com/index.php )

i write your code on server like this
i incude cordova js,local-notification.js,device.js on that page

        document.addEventListener('deviceready', function () {
			var now = new Date().getTime(),
			_60_seconds_from_now = new Date(now + 20*1000);

		window.plugin.notification.local.add({
			id:      1,
			title:   'Reminder',
			message: 'Dont forget to buy some flowers.',
			repeat:  'weekly',
			date:    _60_seconds_from_now
});
}, false);
 

but server page returns this error in logcat
Uncaught TypeError: Cannot read property 'notification' of undefined.

how to solved this to server page.
thanks in advance.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
