### ISSUE TITLE
promptForPermission callback

### ISSUE THREAD

**Issue by ojame** [katzer/cordova-plugin-local-notifications#330]
It looks like `promptForPermission` was intended to take a callback, but from what I understand response never gets sent back to the plugin result:

```
/**
 * Ask for permission to show badges.
 *
 * @param callback
 *      The function to be exec as the callback
 */
- (void) promptForPermission:(CDVInvokedUrlCommand *)command
```

I tried copying the ```[self.commandDelegate sendPluginResult:result callbackId:command.callbackId];``` from `hasPermission` and even just send a `true` to invoke the callback, but I've had no luck.

---

Reason this is required: if the user grants permission, you usually have to schedule a notification. Doing a recursive loop is out of the question due to how cordova executes functions.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
