### ISSUE TITLE
Persistent notification

### ISSUE THREAD

**Issue by alexislg2** [katzer/cordova-plugin-local-notifications#331]
Hey,
I would like to have a persistent message in the status bar to indicate that the app is running in background. How can I do that with your plugin?

**Comment by mikegetlottoapp** [comment]
It sounds like you want Ongoing notifications as well: http://developer.android.com/design/patterns/notifications.html#ongoing_notifications

I'm hoping I can get some information on this.

**Comment by mrmaiko** [comment]
It sounds like you want Ongoing notifications as well: http://developer.android.com/design/patterns/notifications.html#ongoing_notifications

I'm hoping I can get some information on this.

**Comment by katzer** [comment]
Just make use of the `ongoing:` property. For more informations see [here](https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling)

```javascript
cordova.plugins.notification.local.schedule({
    text: "Persistent Notification",
    ongoing: true,
    ...
});
```

**Comment by katzer** [comment]
And you can also use of the [background-mode plugin](https://github.com/katzer/cordova-plugin-background-mode).

**Comment by mrmaiko** [comment]
Amazing, thank you Katzer!

**Comment by hanibhat** [comment]
When I use cordova.plugins.notification.local.schedule() I get an error that cordova is undefined. I'm trying to use this directly instead of the wrapper offered by ionic, because that doesn't support the ongoing property. Is there a way to use this plugin directly in my app?

**Comment by Vomyos** [comment]
> Just make use of the `ongoing:` property.
> 
> ```js
> cordova.plugins.notification.local.schedule({
>     text: "Persistent Notification",
>     ongoing: true,
>     ...
> });
> ```
> 
> For more informations see [here](https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling)

How can I make it close when I press a button? Sorry if it's a silly question but it's my first time using this plugin.

**Comment by hanibhat** [comment]
> > Just make use of the `ongoing:` property.
> > ```js
> > cordova.plugins.notification.local.schedule({
> >     text: "Persistent Notification",
> >     ongoing: true,
> >     ...
> > });
> > ```
> > 
> > 
> > For more informations see [here](https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling)
> 
> How can I make it close when I press a button? Sorry if it's a silly question but it's my first time using this plugin.

Simply call cordova.plugins.notification.local.cancel() when the buttom is clicked, and pass it the id of the local notification. Have a look [here](https://link.medium.com/xdneyvspMV) for a full example on the use, or [here](https://gist.github.com/hanibhat/7bedd7e1f2cafb8ab51ceb2587981635#file-tab1-page-ts) in line 22 for the exact function that you need to call. The difference is the button fires an action implemented in the notification itself.
