### ISSUE TITLE
Mach O Linker Error

### ISSUE THREAD

**Issue by mrhwangmiyoung** [katzer/cordova-plugin-local-notifications#332]
Hi Sebastian,

I am encountering an error when archiving my iOS PhoneGap project, Mach O Linker Error. It points out error in the plugins I installed, but it also includes the CDV LocalNotification plugin as one of the errors. Any ideas why it happens?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
