### ISSUE TITLE
Failed to load resource ... ng-cordova_plugins.js after back button pressed

### ISSUE THREAD

**Issue by jecourtney** [katzer/cordova-plugin-local-notifications#334]
Hello,

(This happens in emulators and on actual Android devices!)

I'm having a strange problem.  When the app initially loads, there are no errors and the plugin for local-notification works splendidly!  However, after I press the back button (app is still in memory) and then tap the app again, the app fails to find the plugin.  Looking at the Sources in the debugger, I see the plugins folder is missing and an android2.3-jscompat.js file is added.  Now, when I swipe the app off of running apps (no longer in memory) and click again all is fine once more until the back button is used.  It seems like the WebView is starting up from a different point from when it loads originally (not in memory.)

Does anyone have thoughts?  All of the other sources and index.html, etc remain unchanged... very odd.

I'm trying to fully close the app on the back button, but have not had much luck doing that.

Thanks in advance.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
