### ISSUE TITLE
IOS 8 a sound but haven't received permission from the user to play sounds

### ISSUE THREAD

**Issue by Ketan108ideaspace** [katzer/cordova-plugin-local-notifications#335]
I have already define hasPermission and promptForPermission into existing code. meanwhile i got the "a sound but haven't received permission from the user to play sounds" error issue.

**Comment by lucaele** [comment]
Hi, there is another thread for this issue:
https://github.com/katzer/cordova-plugin-local-notifications/issues/359

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by Ketan108ideaspace** [comment]
It's working properly.

Thanks Lucaele,
