### ISSUE TITLE
WP8 : Play sound on notification

### ISSUE THREAD

**Issue by mogaembo** [katzer/cordova-plugin-local-notifications#337]
Can someone share a sample code to play sound on local notification ?
1. What would be the path to provide filename ? ( /www/sound/file.mp3 ?)
2. How to add notifications in the notification center ? ( Emails / whatsapp messages appear here  when pulled from the top of the screen)

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
