### ISSUE TITLE
notification as heads up notification

### ISSUE THREAD

**Issue by justgeek** [katzer/cordova-plugin-local-notifications#339]
is there away to make a heads up notification , and customize contents ?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by natanraj** [comment]
@katzer : could you please help us, how to get heads-up notifications using this plugn?
