### ISSUE TITLE
Notification causing black screen and exits the app

### ISSUE THREAD

**Issue by razat2013** [katzer/cordova-plugin-local-notifications#340]
Hi,

I am testing local notification plugin on my nexus 4 mobile, Whenever notification gets fired app shows black screen and exit and land to android navigation screen.
I am using the default example of notification plugin. Is anybody else also facing the same issue and if yes is there any fix for this issue?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
