### ISSUE TITLE
iOS app frequently crashes unless I change the code manually

### ISSUE THREAD

**Issue by anildigital** [katzer/cordova-plugin-local-notifications#341]
I have to put

```
NSString* notId = [notification.userInfo objectForKey:@"id"];
```

instead of 

```
NSString* notId = [[notification.userInfo objectForKey:@"id"]
                           stringValue];
```

then app stops crashing.

It's mentioned here http://stackoverflow.com/questions/26450016/local-notification-app-crashes-simulator

Any update in latest stable version of this plugin?

**Comment by asecondwill** [comment]
@anildigital  - do you have to run a build or anything to apply that fix? I have changed the code in APPLocalNotification.m  however i get the same error and the code appears unchanged in the xcode debugger.  Is there a build phase i am missing?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
