### ISSUE TITLE
Set Onclick to Map

### ISSUE THREAD

**Issue by mrhwangmiyoung** [katzer/cordova-plugin-local-notifications#342]
Hi Sebastian,

I would like to ask if I can modify the onclick on the notification? When the notification is clicked, I want the app to open (even when it is already closed) then open my gmap.html(where my map is) and set the center of the map in a specific coordinate. Is this possible? If so, can you give me a short snippet on the approach I need to use. Thanks.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
