### ISSUE TITLE
isScheduled function problem

### ISSUE THREAD

**Issue by byair74** [katzer/cordova-plugin-local-notifications#343]
hi,

1st thanks for the plugin.
After updating my cordova android platform version from 3.4.0 to 3.6.4 I noticed that I have problem in the isScheduled function.

for example the i value in the following code in 3.4.0 version is 0, 1, 2 and so on but in 3.6.4 version is always 49, why?
``` 
for (var i = (diff > 0 ? 0 : Math.floor(diff * -1) + 1) ; i < 49; i++) {
    window.plugin.notification.local.isScheduled(schedulerID(i), function (isScheduled) {
        try {
            if (!isScheduled) {
                //addNotification(schedulerID(i), i);
            }
        }
        catch (ex) {
            alert(ex);
        }
    });
}
```

please help!

thanks,

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
