### ISSUE TITLE
not playing sound

### ISSUE THREAD

**Issue by davoam** [katzer/cordova-plugin-local-notifications#344]
Plugin works great but doesn't play the sound. If add sound field to add object, sound doesn't play. 
window.plugin.notification.local.add({
              id: '1',
              title: title,
              message: message,
              json: JSON.stringify(json),
              autoCancel: true,
              sound: '/www/audio/notification.mp3'
            });
If i comment it, default sound plays. I tried backgroundMode, but it didn't help. I placed my file in app_folder/www/audio/ .What should i do to play my sound?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
