### ISSUE TITLE
a "Dependencies" problem wuth your plugin

### ISSUE THREAD

**Issue by bau720123** [katzer/cordova-plugin-local-notifications#345]
all detail content right here
http://community.phonegap.com/nitobi/topics/-plugins-cordova-io-seem-not-really-work

**Comment by bau720123** [comment]
hi @katzer 
I seem found a way to solve it
http://community.phonegap.com/nitobi/topics/-plugins-cordova-io-seem-not-really-work
is my way right ?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
