### ISSUE TITLE
Custom Layout

### ISSUE THREAD

**Issue by s1037989** [katzer/cordova-plugin-local-notifications#346]
When adding a notification, allow a custom layout as supported by [Android](http://developer.android.com/guide/topics/ui/notifiers/notifications.html).

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by lok0613** [comment]
Is that means I can write a custom layout of the notification item ?
