### ISSUE TITLE
  window.plugin.notification.local.getScheduledIds return only one object although notifications are added before

### ISSUE THREAD

**Issue by qualitybits** [katzer/cordova-plugin-local-notifications#349]
i need to add dynamic add to the notification and for that i am using this technique 
             var abc=1;
             window.plugin.notification.local.getScheduledIds(function(scheduledIds) {
              scheduledIds.sort()
                for (var i = 1; scheduledIds.length > i; i++) {
                  abc=i;
                    }
              });
and in the each loop where  i am generating the notifications:
 for (i=0;i<selectedDays.length;i++){
abc++;
              var notificationObject = {
                  id:abc,
                  title:'Prayer Time',
                  message:'Dont forget to buy some flowers.',
                  repeat:'weekly',
                  date:null,
                 json: JSON.stringify({
                    category: cat,start_time:startTime,end_time:endTime }
                                      )
              };

              var  notificationObjectMonday = jQuery.extend(notificationObject, {
                  date : newactualdate
               });
                window.plugin.notification.local.add(notificationObjectMonday);

             }

and now problem is that on the first time its give me this
["1"]
which is fine and after all plugins added its give me this:
["1","2","3","4","5","6","7","8"]
and when i goto another page and come back its give me this again: 
 ["1"]
it should give me this:
["1","2","3","4","5","6","7","8"]
 i can add more from 9,10,11

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
