### ISSUE TITLE
Uncaught TypeError: Cannot read property 'notification' of undefined

### ISSUE THREAD

**Issue by sgentile** [katzer/cordova-plugin-local-notifications#351]
I've been struggling to get this working - I'm using latest Ionic Framework.

```javascript
.run(function($ionicPlatform, $cordovaLocalNotification) {
  $ionicPlatform.ready(function() {
    
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if(window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
    
    $cordovaLocalNotification.hasPermission(function (granted) {
      alert('Permission has been granted: ' + granted);
    });

    //
    $cordovaLocalNotification.promptForPermission(function () {
      alert('registered Permission');
    });
```

I show this in my ios.json :

```
"de.appplant.cordova.plugin.local-notification"
```

Is there anything that I should install in the Ionic config.xml ?

Thanks

**Comment by chetankhilosiya** [comment]
I am getting same error but which running app on mobile phone. When i do **ionic run android** it gives me this error but if i do **ionic emulate android** it runs fine. Somehow local notification plugin is not initialized on mobile.
The error line is of ng-cordova.js which is 
*$window.plugin.notification.local.oncancel = function (id, state, json) {*
This is first line for local notification plugin.

**Comment by alexlopezit** [comment]
+1

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by Avinash-Raj** [comment]
@katzer document in your repository is totally different from http://ngcordova.com/docs/plugins/localNotification/ . seems ngcordova failed to update their docs.
