### ISSUE TITLE
onclick

### ISSUE THREAD

**Issue by sgentile** [katzer/cordova-plugin-local-notifications#353]
First off, things have been working very well, down to solving one more issue:  

I'm not able to get a 'onclick' to work

In my angular.module...run,  I have the following:

```javascript
$cordovaLocalNotification.onclick = function (id, state, json) {
      if(json) {
        var item = JSON.parse(json);
        if(item && item.teamId) {
          $state.go('tab.team', {teamId: item.teamId});
        }
      }
    };
```
I've put some alerts in to test this, but when I click on a notification , it's not firing this code.   I've tested on Android and iOS 8

**Comment by vir474** [comment]
same here not firing onclick method

**Comment by sannysinghs** [comment]
Same issue . $rootScope.$on("$cordovaLocalNotification:clicked",funciton(){}) , is not being called

**Comment by zmandel** [comment]
Not working for me on 0.8, but does work on stable 0.7x

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
