### ISSUE TITLE
Question on Scope

### ISSUE THREAD

**Issue by sgentile** [katzer/cordova-plugin-local-notifications#354]
Can someone describe how 'scope' works ?

ie. I have a scenario where I'm adding notifications for different 'teams' - and a user can have multiple teams.  When they add a team, I'm tracking the Id's myself so if they remove the team, I can remove notifications just for that team vs. all the teams.

I'm wondering - is scope something where I can store a 'teamId' with a notification so I can then say something like 'remove all notifications where scope is teamId 'x''

Is that how scope works or it is something else entirely ?

Thanks!!!

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
