### ISSUE TITLE
Get Details of Scheduled Notification

### ISSUE THREAD

**Issue by rocklinzc** [katzer/cordova-plugin-local-notifications#355]
Is there a way to get the details of a scheduled notification? I see you can get a list of the IDs but can you  use that ID to get the details?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
