### ISSUE TITLE
cancel callback not fired

### ISSUE THREAD

**Issue by frigon** [katzer/cordova-plugin-local-notifications#357]
i'm finding erratic behavior (on iOS) where the cancel callback never fires:

                        var reminder = options.data;
                        window.plugin.notification.local.cancel(reminder.id, function () {
                            console.log("this never fired");
                            options.success(reminder);
                        });

However the event listener does:

                       window.plugin.notification.local.oncancel = function(){
                           console.log("listentiner does fire");
                           console.log(arguments);
                       };

**Comment by frigon** [comment]
![2014-12-31_16-02-56](https://cloud.githubusercontent.com/assets/5033564/5591272/8809d5c0-9106-11e4-87d3-83b5092fc6e0.png)

attached is verification of the issue... note the callback function does not fire

**Comment by katzer** [comment]
have testet with master and both types of callbacks are fired!

**Comment by frigon** [comment]
I don't know what to tell you but I'm still having the issues on ios so have stopped using it.  The screen shot above should demostrate there is an issue.

**Comment by christophermiles** [comment]
I am having trouble using the cancel() method, it never works. I've tried passing the id of the notification on its own, and as an array, but nothing happens. cancelAll() does seem to work.

**Comment by zmandel** [comment]
For me oncancel also not getting called. Im using stable 0.7x as 0.8dev has issues.

**Comment by christophermiles** [comment]
My issue was related to the IDs of the notifications being created. I had not realised that notification IDs need to be strictly numeric; I was passing in string values so I could identify the 'type' of notification, but the notifications were being stored with an ID of '0'. Therefore the cancel() method was failing when I passed through the string value I thought the notification had been saved with.

**Comment by zmandel** [comment]
I am using numeric values and "cancel" is not getting called in 0.7x. Cant use 0.8dev as onclick is broken there (at least on android 4.4)

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
