### ISSUE TITLE
IOS 8.1 Attempting to schedule a local notification[...]with an alert but haven't received permission from the user to display alerts

### ISSUE THREAD

**Issue by lucaele** [katzer/cordova-plugin-local-notifications#359]
In iOS 8.1 version 0.7.6 don't work, error appear on simple line "window.plugin.notification.local.registerPermission();".
With plugin version 0.8.0 (dev) work partially, in console appear this error:
 with an alert but haven't received permission from the user to display alerts.

In many forum i see "use registerPermission" but i receive same error.
This is my code:

document.addEventListener('deviceready', function () {
   window.plugin.notification.local.registerPermission();
    
    window.plugin.notification.local.add({
        id:         '123456798',
        message:    'messaio',
        title:      'titolo',
        badge:      1,
        autoCancel: true
    });
}, false);

Someone can help me?
Luca

**Comment by lucaele** [comment]
I'm using Sencha + phonegap.

**Comment by katzer** [comment]
Calling `registerPermission` and `add` in sequence does not work because they work asynchron. You should use the callback from registerPermission to add a notification.

And since today you only need to call `add` as usual, because the plugin does handle that internally.
```javascript
window.plugin.notification.local.add({
    ...
});
```
When calling that the first time the user will receive a system dialog. When the user has granted the permission the plugin will add the notification. No need to call `registerPermission` directly.

BTW: iOS prefers short IDs. Sometimes when using long IDs it does not display the notification.

Sencha is a very good choice!

**Comment by lucaele** [comment]
Hi, i've upgraded your plugin master version but some error remains.
With the follow code only badge work fine, dialog for user permission form don't show and "with an alert but haven't received permission from the user to display alerts" remain in console of xCode.

Code in launch app:
document.addEventListener('deviceready', function () {
 window.plugin.notification.local.add({
                id:			'1239',
                title: 		"iBeaconPOC",
                message: 	'ciao',
                badge:		1,
                autoCancel: true
            });
}, false);

ps: Sencha have a fantastic set of tool but recently (Sencha) has deleted account for single developers... 
Minimum 5 licenses is too expensive. This require that single developers make a union of money.

**Comment by lucaele** [comment]
On iPhone i had delete my test app, then on build &run hasPermission return on launch "true" but on add a local notification console return the same info "with an alert but haven't received permission from the user to display alerts".

window.plugin.notification.local.hasPermission(function (granted) {
                    alert(granted);
                }); 

I hope that information can help to solve this problem.      :-)

**Comment by manan13589** [comment]
Hello katzer .. you are doing really great job .


will you please tell me when you done with 

[feature:] New method hasPermission to ask if the user has granted to display local notifications.
[feature:] New method registerPermission to register permission to display local notifications.

Thank you

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
