### ISSUE TITLE
Notification without sound still vibrates when volume is muted (Android)

### ISSUE THREAD

**Issue by T1mobil3** [katzer/cordova-plugin-local-notifications#360]
Currently, when the volume of the phone is muted and a Notification is fired with the option 'sound: null', the phone still vibrates. Is it possible to configure the plugin to have the phone NOT vibrate when the option 'sound: null' is used?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by kamleshpra995** [comment]
I am still having this issue, not on all devices but on Android 4.4.

cordova.plugins.notification.local.registerPermission(function (str) {
					cordova.plugins.notification.local.schedule({
						id: 1,
						sound: null,
						title: message
					});
				});

sound is set to null, but it still vibrates.

**Comment by rwillett** [comment]
Do not hijack two year old closed threads. Raise a new issue using #1888.

**Comment by kamleshpra995** [comment]
Raised a new Issue using ##1268.

Thanks.
