### ISSUE TITLE
Repeating notifications on iOS seem to be auto cancelled on click?

### ISSUE THREAD

**Issue by CyberFerret** [katzer/cordova-plugin-local-notifications#361]
I have an Ionic app which has repeating notifications on both iOS and Android (daily, weekly, monthly) etc.

All seems to work great except on iOS.  It seems that whenever the user taps on a notification to open my app and go to the relevant screen, any follow up notifications are getting automatically cancelled and the user never receives further notices.  If they DON'T tap on the notification when it pops up, then it repeats fine.

My onclick handler just does a 'window.location.href' with some data in the notification to redirect my user.

Problem doesn't happen on Android - it seems that users can tap or not and the repeated notifications keep working.

I have set autoCancel: false in the options, or left it out altogether, or even tried to set it false globally, but to no avail.  Possibly a bug?

**Comment by CyberFerret** [comment]
Perhaps this section in APPLocalNotificationOptions.m ?  It seems to be setting 'autoCancel' to TRUE if iOS version is at least 8?  Should there be a check for [dict objectForKey:@"autoCancel"] in there as well?

- (BOOL) autoCancel
{
    if (IsAtLeastiOSVersion(@"8.0")){
        return YES;
    } else {
        return [[dict objectForKey:@"autoCancel"] boolValue];
    }
}

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
