### ISSUE TITLE
Get Notification Details function?

### ISSUE THREAD

**Issue by frigon** [katzer/cordova-plugin-local-notifications#362]
I know you can get the scheduled IDs from the getScheduledIDs interface... but is there anyway to get the details associated with that notification: the date, the title, repeats, etc?

The only way i can figure it out to to cache that locally via the ID, store it separately and they try to map that via ID, which is a bit clumsy

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
