### ISSUE TITLE
missing functions on ios

### ISSUE THREAD

**Issue by frigon** [katzer/cordova-plugin-local-notifications#364]
Using release 0.7.4 on iOS 8

See the attached screenshot of the notification.local option from webview debugger (via Telerik AppBuilder).  Note this is running on an iphone device, not an emulator.

Notice there are several interfaces/functions not being shown:
notification.local.hasPermission
notification.local.registerPermission
notification.local.isScheduled
notification.local.isTriggered

Also notice the signatures on add, cancel do not possess the callback function as documented.

![2015-01-05_14-39-47](https://cloud.githubusercontent.com/assets/5033564/5621277/de7f427e-94e8-11e4-92da-b9ba4a778a0a.png)

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
