### ISSUE TITLE
iOS 8.1 build fails with linker error 

### ISSUE THREAD

**Issue by smistry-toushay** [katzer/cordova-plugin-local-notifications#365]
Using master 998ea0de83d4765efbc2f7b3a442a83784b33bce

Installed platforms: iOS 3.7.0
Xcode Version 6.1.1 (6A2008a)

```
  "_UIApplicationRegisterUserNotificationSettings", referenced from:
      -[APPLocalNotification pluginInitialize] in APPLocalNotification.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by christophermiles** [comment]
Same here.
Cordova 4.1.2.
de.appplant.cordova.plugin.local-notification 0.8.0dev

**Comment by sherlockat** [comment]
same here
check : Build Phases -> Compile Sources
my case, UIApplication+APPLocalNotification.m file had been left out list

**Comment by dscx** [comment]
Confirming here as well.

Cordova 4.1.2.
de.appplant.cordova.plugin.local-notification 0.8.0dev

**Comment by joshhunt** [comment]
Confirming again.

Is there a last known good commit I can install from?

```
→ cordova --version
    4.1.2
→ xcodebuild -version
    Xcode 6.1.1
    Build version 6A2008a
→ cordova plugins info
    de.appplant.cordova.plugin.local-notification 0.8.0dev "LocalNotification"
    nl.x-services.plugins.actionsheet 1.1.1 "ActionSheet"
    org.apache.cordova.camera 0.3.4 "Camera"
    org.apache.cordova.console 0.2.12 "Console"
    org.apache.cordova.device 0.2.14-dev "Device"
    org.apache.cordova.dialogs 0.2.11 "Notification"
    org.apache.cordova.file 1.3.2 "File"
    org.apache.cordova.file-transfer 0.4.8 "File Transfer"
    org.apache.cordova.inappbrowser 0.5.4 "InAppBrowser
```

**Comment by taenadar** [comment]
Above fix seems to work for me

**Comment by dscx** [comment]
Confirmed madflanderz's fix does indeed work. I did have to re-add the platform, however. Thanks!

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
