### ISSUE TITLE
how to remove displayed notification using cordova

### ISSUE THREAD

**Issue by mfkj** [katzer/cordova-plugin-local-notifications#367]
how can i remove notification which has been displayed(presend on phone bar) but not repspond by the user? using cordova https://github.com/katzer/cordova-plugin-local-notifications/

i check different method but didn't get any property or function of it. although when registering

window.plugin.notification.local.add({
    id:         String,  // A unique id of the notification
    date:       Date,    // This expects a date object
    message:    String,  // The message that is displayed
    title:      String,  // The title of the message
    repeat:     String,  // Either 'secondly', 'minutely', 'hourly', 'daily', 'weekly', 'monthly' or 'yearly'
    badge:      Number,  // Displays number badge to notification
    sound:      String,  // A sound to be played
    json:       String,  // Data to be passed through the notification
    autoCancel: Boolean, // Setting this flag and the notification is automatically cancelled when the user clicks it
    ongoing:    Boolean, // Prevent clearing of notification (Android only)
}, callback, scope);
you have an option of

  autoCancel: Boolean, // Setting this flag and the notification is automatically cancelled when the user clicks it
This is working but how can i removed using coding.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
