### ISSUE TITLE
NSException - value parameter is nil

### ISSUE THREAD

**Issue by dscx** [katzer/cordova-plugin-local-notifications#369]
Hello, 

Here is the error I am getting through Xcode. 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSJSONSerialization dataWithJSONObject:options:error:]: value parameter is nil'

*** First throw call stack:
(0x186c0a59c 0x1973680e4 0x186c0a4dc 0x187b50a34 0x10012107c 0x10012025c 0x10011f9f8 0x186bb0ae4 0x186aef220 0x1879eecc0 0x100119b30 0x18b64f1bc 0x18ee7962c 0x186bc2a28 0x186bc1b30 0x186bbfd30 0x186aed0a4 0x18fc8f5a4 0x18b4223c0 0x100119378 0x1979d6a08)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

I saw a few other fixes form last May for other NSException errors but not for the value parameter being nil.

This error comes up without any notifications, a custom one, or the example: window.plugin.notification.local.add({ message: 'Great app!' });

I'm on the latest dev build.
thanks!

**Comment by dscx** [comment]
I have determined this is due to permission not populating across views, and I do not believe this to be an issue with the plugin but something on my end.

**Comment by devwwb** [comment]
I could fix this disabling notifications from a background service.

In my case with debug: false in the background geolocation plugin solved the problem.
