### ISSUE TITLE
Ionic + Cordova - No notification showed either Android/iOS

### ISSUE THREAD

**Issue by feoche** [katzer/cordova-plugin-local-notifications#370]
Hi all, 

We are currently designing an hybrid app using Ionic, Angular.js and Cordova. 

I just can't show a single notification on either Android or iOS physical devices (and virtual ones using Genymotion)
Here's the code in the app.js :

<pre><code>
angular.module('app', ['ionic', 'app.controllers'])
.run(function($ionicPlatform, $rootScope) {
    $ionicPlatform.ready(function() {
          window.plugin.notification.local.add({
            badge: 1, 
            message: "test", 
            repeat: "secondly", 
            sound: "TYPE_NOTIFICATION", 
            title: "TEST"
         });
    });
});
</code></pre>

I am able to display window.plugin.notification.local, but there's no effect on the device with the add() function, even if the app is running in background or not working at all.

Do you have any ideas of what is going on?

Regards

**Comment by Klapsa2503** [comment]
Have you found any solution to this problem?

**Comment by feoche** [comment]
Hi
I haven't find any solution, I am not able to display any of the notifications which can be displayed with the plugin.
Regards

**Comment by Klapsa2503** [comment]
This solution is working for me (tested on Android 4.+:

```
        .run(function ($ionicPlatform) {
            $ionicPlatform.ready(function () {
                window.plugin.notification.local.hasPermission(function (granted) {
                    if (granted === true) {
                        window.plugin.notification.local.add({message: 'Great app!'});
                    } else {
                        window.plugin.notification.local.registerPermission(function (granted) {

                        });
                    }
                });
            });
        });
```

Using this plugin:
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git && cordova prepare

**Comment by katzer** [comment]
what version, 0.7 or 0.8-dev?

**Comment by Klapsa2503** [comment]
I copied the link from here: https://github.com/katzer/cordova-plugin-local-notifications . The one from master.

**Comment by feoche** [comment]
Hello to both of you, 

Thank you for helping me.

Unfortunately, it doesn't seem to work with Klapsa2503 piece of code.

I did
<pre><code>
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git && cordova prepare
</code></pre>
on CLI, then I put Klapsa2503 snippet in my app.js.
After trying to log with alert(), it seems that it validates the 'granted' variable as true, so it should execute <pre><code>window.plugin.notification.local.add({message: 'Great app!'});</code></pre> but it's not.

So I have several questions :

What do I have to check to make this working ? Can I log notification callbacks effectively ?
Does it need any dependances in my module ?
Why is the registerPermission callback function empty ?
Does the plugin work on virtual devices (through Genymotion for instance) ?

Thanks

**Comment by Klapsa2503** [comment]
Try this way (maybe it will work):
1. start new ionic project (ionic start ....)
2. add android platform   (ionic platform add android)
3. add notification plugin  (ionic plugin add https://github.com/katzer/cordova-plugin-local-notifications.git && cordova prepare)
4. test on real device (I don't know if this works on simulator)

**Comment by feoche** [comment]
Ok, so now I started a new project with the notification plugin, added the snippet from above (4th comment), and it crashes when the app is launched.
After investigating, the plugin is well defined inside app (we can make calls on the defined functions), but when add() function is triggered, it simply crashes the app.

So close to a solution !

**Comment by katzer** [comment]
@feoche, @Klapsa2503,
I can call the following and receive the local notification within the notification center - including all callbacks. You can use real device or simulator, works both.

```javascript
window.plugin.notification.local.add({message: 'Great app!'});
```

There is no need to call `registerPermission` directly since the plug-in will do that behind. But the OS will ask you only one times. You can check the permission in the device settings.

**Comment by feoche** [comment]
Well, I just find out that a file generated by Ionic (a AndroidManifest.xml for Android) distrubs the whole application, including this plugin. Now it works like a charm. Thanks !

**Comment by brunodb3** [comment]
You got it working by changing the AndroidManifest? Wow, i didn't need to go that far really, i just did this:

    $ionicPlatform.ready(function() {
        if (window.cordova) {
            document.addEventListener("deviceready", function() {
                window.plugin.notification.local.onadd = function(id, state, json) {
                    scope.$broadcast('notifAdicionar', id, state, json);
                };
                window.plugin.notification.local.onclick = function(id, state, json) {
                    scope.$broadcast('notifClicar', id, state, json);
                };
                window.plugin.notification.local.oncancel = function(id, state, json) {
                    scope.$broadcast('notifCancelar', id, state, json);
                };
                window.plugin.notification.local.ontrigger = function(id, state, json) {
                    scope.$broadcast('notifGatilho', id, state, json);
                };
            }, false);
        }
    });

And when i need to show a notification i just do the usual

    window.plugin.notification.local.add({
        id: 1,
        title: 'Test Notification'
    });

I did not change anything in the AndroidManifest really...

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
