### ISSUE TITLE
Local notification  not working on IOS

### ISSUE THREAD

**Issue by farrukhm** [katzer/cordova-plugin-local-notifications#371]
I am trying to develop an application that show me a  local notification at specific time and date set by user i m using intel xdk IDE when i build app in Android and install .apk file in my phone it works fine but when i build the same application for ios and install .ipa in iphone then notification does not work .. Any suggestion

**Comment by balichowdry** [comment]
Hy, 

I am facing same issue, did you find anything ?

**Comment by farrukhm** [comment]
i have post solution on this forum (https://forums.html5dev-software.intel.com/viewtopic.php?f=29&t=10437&sid=d79b275b32164c52ef44de0a2c781a75) you can try my code.

**Comment by zmandel** [comment]
farrukhm seems your issue was not related to this plugin, but to an incorrect use of javascript Date?

**Comment by farrukhm** [comment]
@zmandel ,you are right i m making mistake in javascript date object
Thanks for your response

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
