### ISSUE TITLE
How to remove notification after specified time?

### ISSUE THREAD

**Issue by mfkj** [katzer/cordova-plugin-local-notifications#372]
I check documentation of local notification but did n't find the way of local notification removal after specified time.
i want to remove a local notification after some minutes how can i do this? i did this thing with setTimeout and it is worked but the problem is setTimeout will not work if the app is not open.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
