### ISSUE TITLE
Build issue and local notifications not working

### ISSUE THREAD

**Issue by Nolexum** [katzer/cordova-plugin-local-notifications#373]
I´ve been using your plugin for local notifications and it was working much more than fine, but two days ago and without any change in source code, I´ve done a new build ussing netbeans 8.0.2 and cordova 3.5.0 with plugman using master version on -> https://github.com/katzer/cordova-plugin-local-notifications.git;  and now I´m getting a buid failure after some [java] errors during building process, like this 
......appplant\cordova\plugin\localnotification\LocalNotification.java:91: error: cannot find symbol
    [javac]                 		options.setInitDate();

This issue seems to be something related to the plugin because I´ve removed on plugins-properties file the line related to https://github.com/katzer/cordova-plugin-local-notifications.git and now buiding process it´s working back fine again.

The most curious thing is that build it´s failing just sometimes but anyway.. even when the build process it´s finishing properly, the pluging calls does not work anymore.

Any idea about what´s going on?.

Thank you.

**Comment by olivermuc** [comment]
Similar here. The build process however works, no errors there. But none of the calls produce any output, neither a message/alert nor an error msg.
It's just silent.
v.078 still works though!

**Comment by zmandel** [comment]
https://github.com/katzer/cordova-plugin-local-notifications/issues/384

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
