### ISSUE TITLE
Local Notification cannot wake the phone from sleep/standby mode in iOS 8.1.2

### ISSUE THREAD

**Issue by hkcity1111** [katzer/cordova-plugin-local-notifications#374]
Dear all,

I found that the plugin can add message to notification center but cannot wake up the iPhone from sleep/standby mode in iOS 8.1.2 
I try the plugin succesfully to wake up the iPad iOS 8.1 and iOS 8.0.2.
Do anyone know that apple change their notification setting or we need to add some coding to make the phone wake up from sleep/standby mode.
Thank a lot

Regards,
  Kenny

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
