### ISSUE TITLE
Incorrect Installation Instructions for Stable Version

### ISSUE THREAD

**Issue by mkandahar** [katzer/cordova-plugin-local-notifications#375]
Hi,
final *s* is missing in installation instructions in Readme. Correct one is:

**cordova plugin add de.appplant.cordova.plugin.local-notifications**

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
