### ISSUE TITLE
Daily notifications not working

### ISSUE THREAD

**Issue by arlg** [katzer/cordova-plugin-local-notifications#376]
Hi. I can't manage to make daily notifications work on my phone ( iOS 7 ).

I set it to be like 2 minutes after. But the notification doesnt trigger. When i set it to me "minutely", it works fine.

Here is the code, i get the time from an input :  

    var time = $('#time').value,
          date = new Date(),
          hours = time.split(':')[0],
          minutes = time.split(':')[1];

    date.setHours(hours);
    date.setMinutes(minutes);

    window.plugin.notification.local.add({
            id:      0,
            title:   "title",
            message: "message",
            repeat:  "daily",
            date:    date
        });

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
