### ISSUE TITLE
Android deviceready after task killed

### ISSUE THREAD

**Issue by craig-at-rsg** [katzer/cordova-plugin-local-notifications#383]
On Android, if I kill the task for my app, my notification will reopen my app, but I won't get the onclick event in the newly opened app. 

The event does get fired and handled, but for the killed task; chrome://inspect shows the killed one as "detached". I'm trying to navigate to different pages depending on the json in the notification, so I need the onclick in my app's current task. 

The LocalNotification class has a deviceready boolean which gets set to true, and I think if this gets set to false when a WebView task is killed, then the onclick event could get handled by the new WebView when it's available (because LocalNotification will get re-initialized by the new WebView).

**Comment by kristianbenoit** [comment]
If I get that correctly, I have the same problem. The app is in one of 4 states when the notification get clicked.

1. The app is not in "recently opened".
2. The app is on screen
3. The app is running off screen.
4. The app is stopped by pressing the back button, but is still present in the "recently opened".

1, 2 and 3 works fine. For the fourth, clicking on a notification starts the app, going through splashscreen and al, but the click is catch early, most likely, by the version we stopped with the back button. Then the newly started app never receives the click event. Strangely, in 1, 2, 3 the state is 'background' while in 4 the state is 'foreground'.

Looking at this I found it is related to the resume/pause events. Here's my experienced behaviour of the pause/resume. Starting the app does not call pause or resume. Leaving the app by swiping it from "recently opened" or back button does not call pause or resume. Switching to another app or letting the screen turn off calls pause, returning to the app calls resume.

Here's what happen when you click a notif in the different state of the app :

Application state | What happen to pause/resume | local notif state
------------- | -------------|--------------
app not in recently opened (1) | Start the app then call onclick. Does not call resume or pause.| background
app is on screen (2) | It pauses the app, call onclick and resume. | background
app is paused : using another app (3) | It call onclick and resume. | background
app is closed but in recently opened (4) | Call on click then start the app. Does not call resume or pause. | foreground

I made a demo application that make sure you have a notification to click and logs what the application is doing. The app is based on Ionic tab project (Angular), the goal is to switch to the friends tab once clicked.
https://github.com/kristianbenoit/local-notifications-bug

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by hammadjamil** [comment]
After spending lot of time on finding solution of this issue i haven't found any of the suggestion worked for me.
But finially I have find solution and root cause of the issue on my own
The issue is events like click and trigger doesn't work after the app kill because when app is opened after kill events are not bind.
So the solution of this issue is to rebind the events at the start of the app your problem will be solved
like i am working on ionic app i have put below code in app.js for notification click event
`
$ionicPlatform.ready(function () {
cordova.plugins.notification.local.on("click", function (notification) {
                        cordova.plugins.notification.local.cancel(notification.id, function () {
                            // Notification was cancelled
                            console.log('notification is cancelled  : '+ notification.id);
                             
                        }, '');

                    });
 });
`
Now events are bind and work properly even after app kill. i have tested it for android and hopefully work for ios as well
