### ISSUE TITLE
Android build fails 

### ISSUE THREAD

**Issue by sunsus** [katzer/cordova-plugin-local-notifications#384]
Hello 

The dev Version fails to build for android: 
platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:241: error: cannot find symbol
    [javac]     		options.setInitDate();
    [javac]     		       ^
    [javac]   symbol:   method setInitDate()
    [javac]   location: variable options of type Options
platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:242: error: method schedule in class NotificationWrapper cannot be applied to given types;
    [javac]         	nWrapper.schedule(options);
    [javac]         	        ^
    [javac]   required: de.appplant.cordova.plugin.notification.Options
    [javac]   found: de.appplant.cordova.plugin.localnotification.Options
    [javac]   reason: actual argument de.appplant.cordova.plugin.localnotification.Options cannot be converted to de.appplant.cordova.plugin.notification.Options by method invocation conversion
platforms/android/src/de/appplant/cordova/plugin/localnotification/Receiver.java:67: error: constructor NotificationBuilder in class NotificationBuilder cannot be applied to given types;
    [javac]     	NotificationBuilder builder = new NotificationBuilder(options,context,OPTIONS,
    [javac]     	                              ^
    [javac]   required: de.appplant.cordova.plugin.notification.Options,Context,String,Class<?>,Class<?>
    [javac]   found: de.appplant.cordova.plugin.localnotification.Options,Context,String,Class<DeleteIntentReceiver>,Class<ReceiverActivity>
    [javac]   reason: actual argument de.appplant.cordova.plugin.localnotification.Options cannot be converted to de.appplant.cordova.plugin.notification.Options by method invocation conversion

**Comment by PKnittel** [comment]
Try to remove android with:
cordova platform rm android 
and add it again with:
cordova platform add android

That should fix your build error.

**Comment by zmandel** [comment]
if you do a clean build, it works. no need to remove the entire android.

**Comment by sunsus** [comment]
Clean command can be found here: ~/Desktop/work/project/platforms/android/cordova/clean

**Comment by alidavut** [comment]
I had this issue, updated cordova. It works now.
```npm update cordova -g```

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
