### ISSUE TITLE
Alert notification on iOS?

### ISSUE THREAD

**Issue by mmBs** [katzer/cordova-plugin-local-notifications#385]
Hey. Is there any way to show an alert notification instead of banner notifications on iOS? Because in the readme there is mentioned that we can display an alert or banner, but in the notification config there is no option for that:

    window.plugin.notification.local.add({
    id:         String,  // A unique id of the notification
    date:       Date,    // This expects a date object
    message:    String,  // The message that is displayed
    title:      String,  // The title of the message
    repeat:     String,  // Either 'secondly', 'minutely', 'hourly', 'daily', 'weekly', 'monthly' or 'yearly'
    badge:      Number,  // Displays number badge to notification
    sound:      String,  // A sound to be played
    json:       String,  // Data to be passed through the notification
    autoCancel: Boolean, // Setting this flag and the notification is automatically cancelled when the user clicks it
    ongoing:    Boolean, // Prevent clearing of notification (Android only)
    }, callback, scope);

If you give me some feedback, it would be great! Thanks in advance!

**Comment by Hirbod** [comment]
I guess this depends on your notification center settings. You can't override this iirc. @mmBs

**Comment by mmBs** [comment]
@Hirbod thanks for a really quick response. I changed it in the notification center settings and it works like a charm :) However, is there any possibility to force this type of notification (to be a default type of the notification for my application)?

**Comment by Hirbod** [comment]
Hi @mmBs,

If I remember correctly, there is now way to change the notification type by software. It's always users decision - at least on iOS (which is fine imho).

**Comment by mmBs** [comment]
I think you're right. Thanks for replies, you were very helpful :+1:
