### ISSUE TITLE
Provide foreground view

### ISSUE THREAD

**Issue by Hirbod** [katzer/cordova-plugin-local-notifications#386]
Hi,

thanks so much for this great plugin. I hassled a lot to get Push work fine (remote and local) but there is still some feature I'm really missing. I know it is possible to call an alert() or navigator.alert() when the app is in foreground. But this is something disturbing and UI blocking. I'd love to have a second (toast like) view/inappbanner to show local notifications.

http://stackoverflow.com/questions/14872088/get-push-notification-while-app-in-foreground-ios

Here are some workarounds but maybe you could incorporate something (trough an option) "force inapp-banner" in foreground or as an extra option. I know I could trigger @EddyVerbruggen 's Toast-Plugin but I really need something with a click callback. Like WhatsApp. I guess WhatsApp build some own InAppNotification (but it looks so native, even there settings-page).

Is there any way to achieve this?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
