### ISSUE TITLE
Crashing on iOS 7

### ISSUE THREAD

**Issue by craig-at-rsg** [katzer/cordova-plugin-local-notifications#387]
My app is crashing for me on iOS 7 with log lines like:
2015-01-15 15:13:38.709 rMove[155:5003] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication currentUserNotificationSettings]: unrecognized selector sent to instance 0x15524f70'

It looks like this is being caused by code in UIApplication_APPLocalNotification.m:

```
- (BOOL) hasPermissionToScheduleLocalNotifications
{
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 80000
    UIUserNotificationType types;
    UIUserNotificationSettings *settings;

    settings = [[UIApplication sharedApplication]
                currentUserNotificationSettings];

    types = UIUserNotificationTypeAlert|UIUserNotificationTypeBadge|UIUserNotificationTypeSound;

    return (settings.types & types);
#else
    return YES;
#endif
}
```

I think the check should be for the current device version instead of the max allowed version, something like:

```
#define IS_OS_8_OR_LATER ([[[UIDevice currentDevice] systemVersion] floatValue] >= 8.0)
```

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
