### ISSUE TITLE
Failure of cancelAll callback, failure of cancelAll to cancel all reminders, failure of getScheduledIds to get all active reminders

### ISSUE THREAD

**Issue by simongcx** [katzer/cordova-plugin-local-notifications#389]
Using cordova-plugin-local-notifications v 0.7.6 in an Intel XDK app (Cordova 3.5) on Android 4.4.4, I have experienced failure of the cancelAll callback to occur, a falure of the cancelAll function to cancel all reminders (it works sometimes) and a failure of getScheduledIds to get all active reminders.

The cancelAll failing to cancel all notification and the failure of getScheduledIds issues occur in a test case where the use clicks the create notifications button multiple times in quick succession and hence (it is likely) that the simultaneous calling of the cancelAll and add functions is what is creating the problem.

Selected code extracts are as follows, but as you can see it's pretty basic stuff.

If you have Intel XDK, I'm happy to share the source and you can build and test yourself.

    function createreminders() {

        window.plugin.notification.local.cancelAll();

        var datelist = getdatelist();

        for (var i = 0; i < datelist.length; i++) {
            createreminder(datelist[i]);
        }

    }

    function cancelnotifications() {

        window.plugin.notification.local.getScheduledIds(function(scheduledIds) {
            for (var i = 0; scheduledIds.length > i; i++) {
                window.plugin.notification.local.cancel(scheduledIds[i]);
                console.log("Notification cancelled: " + scheduledIds[i]);
            }
        });

    }

    function createreminder() {

        var reminderid = getnewreminderid()

        var notifconfig = {
            id:         reminderid,
            date:       date,    // This expects a date object
            message:    reminderid.toString(),  // The message that is displayed
            title:      "This is notification:",  // The title of the message
        };

        try {
            window.plugin.notification.local.add(notifconfig);
        }
        catch(err) {
            console.log("Notification creation failed: " + date.toISOString() + ", " + reminderid.toString());
        }

    }

    function getdatelist() {

        var datelist = [];

        for (var i = 0; i < 100; i++) {
            var d = new Date();
            d = new Date(d.getTime() + i * 60 * 1000);
            datelist.push(d);
        }

        return datelist;

    }

**Comment by tomchambers2** [comment]
I'm also having a problem with the callback not firing.

```
  $scope.clearReminders = function() {
    console.log('will cancel all');
    $cordovaLocalNotification.cancelAll().then(function () {
      console.log('finished');
      $scope.reminders = [];
    });
  };
```

in ngCordova:

```
      cancelAll: function (scope) {
        var q = $q.defer();
        scope = scope || this;

        $window.plugin.notification.local.cancelAll(function (result) {
          console.log('calling cancel all callback');
          q.resolve(result);
        }, scope);

        return q.promise;
      },
```

The console.logs inside the callbacks are never executed.

**Comment by simongcx** [comment]
Ok, so after reviewing the code, there is no callback set up for cancelAll() or cancel() in version 0.7.6. Still investigating the failures of cancelAll() and getScheduledIds(), but it seems to occur when multiple calls are occurring at once.

**Comment by christophermiles** [comment]
Any update on this? I am unable to get a simple cancel() working correctly.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
