### ISSUE TITLE
v0.80 doesn't work on iOS8.1 (both Simulator & device)

### ISSUE THREAD

**Issue by olivermuc** [katzer/cordova-plugin-local-notifications#391]
It compiles ok, but doesn't work, *except one function*:
```javascript
window.plugin.notification.local.hasPermission(function (granted) {
    console.log('Permission has been granted: ' + granted);
});
```
The above at least prints the log msg, out side of that nothing appears to be working.
This already doesn't work, it just silently sits there:

```javascript
window.plugin.notification.local.registerPermission(function (granted) {
    console.log('Permission has been granted: ' + granted);
});
```
same with this:
```javascript
window.plugin.notification.local.add({ message: 'Great app!' });
```
I then boldly tried this 
```javascript
window.plugin.notification.local.exec('add', { message: 'Great app!' });
```
and at least the app crashed, so it appears to have at least tried...

EDIT:
~~Btw. version v0.78 does work just fine!~~

**Comment by olivermuc** [comment]
Got to take this back, v0.78 works ok in the Simulator, but on an iPhone 4S with iOS 8.1.2, it crashes.

**Comment by olivermuc** [comment]
Go figure as soon as I followed-up here, I had a hunch that it could have to do with the **v.80 testing earlier**, which messed up the app. Changing the app's bundle ID, allowed for a fresh new start and voila, v0.78 works on the actual device now.

 Why v0.80 is the Master now and not just a branch, beats me.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
