### ISSUE TITLE
LED indicator not working on Samsung phone

### ISSUE THREAD

**Issue by alex1423** [katzer/cordova-plugin-local-notifications#392]
There is a LED light on my Samsung Galaxy phone. When I receive a text message, that light starts blinking. Thanks a lot for your wonderful plug in. I got it to work to play a sound. It will be great if you can make it work with the LED notification light. Otherwise users won't know about the notification when they are back with their phone.

**Comment by alex1423** [comment]
It seems that the code doesn't support LED indicator

    notification = new NotificationCompat.Builder(context)
        .setDefaults(0) // Do not inherit any defaults

Should it be:
.setDefaults(Notification.DEFAULT_VIBRATE | Notification.DEFAULT_SOUND | Notification.FLAG_SHOW_LIGHTS)

There seems to be no way to change the defaults:
      	Builder notification = builder.buildNotification();
       	nWrapper.showNotification(notification, options);

Someone said at stackoverflow that the priority needs to be HIGH for the LED indicator to blink. There is no way to set that either. Has anyone managed to get the LED indicator to blink?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
