### ISSUE TITLE
Working on Android, but not on iOS

### ISSUE THREAD

**Issue by jamesdef** [katzer/cordova-plugin-local-notifications#393]
I guess the title says it al: android works like a charm, but ios (simulator and device) don't.
I'm using Ionic, and the code is fired at the platformready event.
Anyone having this problem?

**Comment by condomitti** [comment]
jamesdef, this link might help you: http://stackoverflow.com/questions/24457041/ios-local-notifications-not-working-with-phonegap

Cheers,

**Comment by vir474** [comment]
Any Updates ??

**Comment by farrukhm** [comment]
i m facing the same issue my app does not appear in notifications in IOS but notification work in Android

**Comment by vir474** [comment]
Try scheduling the notification after sometime by adding date to the add method

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
