### ISSUE TITLE
v0.78 : cordova.js error after adding or canceling notifications

### ISSUE THREAD

**Issue by olivermuc** [katzer/cordova-plugin-local-notifications#394]
After adding or canceling notifications, here is what I see in the 
**in the iOS Simulator / Safari Console**:
```javascript
[Error] SyntaxError: Unexpected EOF
	appendChild (index.html, line 1)
	createExecIframe (cordova.js, line 851)
	pokeNativeViaIframe (cordova.js, line 1062)
```
I wonder if this has to do with the 3.7 cordova [iFrame bug](https://issues.apache.org/jira/browse/CB-8002).

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
