### ISSUE TITLE
Creating a notification with the same id creates a new notification on iOS

### ISSUE THREAD

**Issue by huttj** [katzer/cordova-plugin-local-notifications#395]
On Android, scheduling a local notification to be immediately displayed, and then scheduling another one shortly afterwards, with the same ID, causes the first notification to be overwritten.

On iOS (v8), the second one is added to the list, even though the ID is the same.

I want to overwrite the first one, or programmatically clear/remove it. Is that at all possible?

**Comment by jimibi** [comment]
I think what the best thing is to use:

window.plugin.notification.local.cancel(ID, function () {
    // The notification has been cancelled
}, scope);

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
