### ISSUE TITLE
iOS (v8) counter doesn't decrement unless notification is clicked

### ISSUE THREAD

**Issue by huttj** [katzer/cordova-plugin-local-notifications#396]
The home screen icon counter/badge counts up for each notification that is deployed. However, clearing the notifications does not decrement the counter, as would be expected. The only thing that decrements the counter is tapping on the notifications.

Consequentially, the counter can be stuck at a non-zero number if any notifications are dismissed before they are tapped on.

How can I decrement the counter?

**Comment by joshbuckley182** [comment]
I've also noticed this - I think it's a recent thing because I've not seen it before.

**Comment by bayhall-digital** [comment]
I found using the de.appplant.cordova.plugin.badge plugin to manage badges (created by the same developer).

You can wipe all badges easily after deviceready:

cordova.plugins.notification.badge.clear();

Also, works with local-notification permission request (as this request badges, sounds, and banners, you don't need to request badges through the Badges plugin also).

        window.plugin.notification.local.hasPermission(function (blnHasPermissionGranted) {
            if (blnHasPermissionGranted == false) {
                //alert("no notification permissions")                   
                window.plugin.notification.local.promptForPermission();
            } else {
                //alert("notification permissions")
                cordova.plugins.notification.badge.clear();
            }
        });  

You can also manage the icon on an individual bases:

cordova.plugins.notification.badge.set(-1) for example.

**Comment by stefanmdt** [comment]
Which version are you using? In my case the badge is always "1", also if multiple notifications are deployed. As soon as I either click on one of the notifications or open the app via home screen icon, the badge disappears ...

**Comment by huttj** [comment]
I'm using 0.8.0dev.

**Comment by stefanmdt** [comment]
Are you trying to increment / decrement the counter from within the app? As far as I know, the badge number must be kept on server side and be included into the push notification. Till clicking the notification, no app code is executed, so there is no way to increase / decrease badge number on client side at that moment. Also a push notification without badge payload does not increase badge count in my case. Opening the app does clean the badge value, but you could then set a specific value in the app of course ...

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
