### ISSUE TITLE
iOS 7.0.3 notification not displayed

### ISSUE THREAD

**Issue by AndreaBruno** [katzer/cordova-plugin-local-notifications#397]
Hi, 
I'm using an Ipad Mini with iOS 7.0.3.
The function window.plugin.notification.local.hasPermission, return true but I don't see any notification.
To trigger the notification I use "window.plugin.notification.local.add({ message: 'Great app!' });"
I've tried also in the emulator (Iphone 6, iOS 8) and It gave the same problem.

Thank you.

**Comment by jonnywonny** [comment]
Experiencing the same issue with iOS 8.

**Comment by vir474** [comment]
Any Updates on this issue ???

**Comment by jonnywonny** [comment]
I found the issue that I was having. It turns out I didn't have a proper understanding of how the plugin functioned. The plugin ifself doesn't display any notification, all it does is call the plugin.notification.local.ontrigger function. You are responsible for showing the actual notification itself. The strange thing is, none of the display parameters seem to be passed to the ontrigger function, so it seems as though that if you want to display a popup with the correct contents, you have to retrieve them based on the ID from a storage location that you yourself have to manage. Seems a little odd. I applaud the effort that went into creating this plugin, and certainly appreciate it, but I find some of decisions a little poorly thought out, and the documentation could do a much better job making it all clear.

**Comment by vir474** [comment]
So just by writing the plugin.notification.local.add() method it doesnt work on IOS ??

**Comment by jonnywonny** [comment]
Correct. You also have to do something like this: 
```
plugin.notification.local.ontrigger = function(id, state, json) {
    // Display notification here.
}
```

To display a notification, you could use this plugin: https://github.com/apache/cordova-plugin-dialogs/blob/master/doc/index.md

There may be a different way to accomplish all this, but from what I have experienced so far this is how you have to do it.

**Comment by vir474** [comment]
Thanks again but my problem is i don't receive the notification at all on IOS while it works on Android ! 
Still i will try what you suggested ..

**Comment by jonnywonny** [comment]
Ahh, I see. Well, perhaps on other platforms the OS still handles the notification even if the app is open.

**Comment by vir474** [comment]
@jonnywonny  Well i tried what you suggested nothing happens on IOS ! but works on Android

**Comment by jonnywonny** [comment]
Can you confirm that plugin.notification.local.ontrigger is being called?

**Comment by vir474** [comment]
shoot, i put an alert inside the ontrigger method its not called i guess because i dont see the alert

**Comment by jonnywonny** [comment]
Have you checked the error log? Do you know about using Safari to debug UIWebViews?

**Comment by vir474** [comment]
alert("notifying");                    
                    window.plugin.notification.local.add({ message: 'You have been notified by Viral' });
alert("adding listener");                    
                    // Add listener to register and show large notification when the user clicks on local notification 
                    window.plugin.notification.local.onclick = function ( msgid , msgstate, msgjson) {
                        var localnotify = $ionicPopup.alert({
                                                    title: "On click Notification",
                                                    template: "Long message direct input"
                        });
                        localnotify.then(function( result ) {});
                    };
			window.plugin.notification.local.ontrigger = function(id, state, json) {
                        	// Display notification here.
alert("notification triggered");                        
                    	}

------------- 
This is the code is use !! its after ionic platform ready

**Comment by vir474** [comment]
No i dnot know how to do that !

**Comment by jonnywonny** [comment]
With your iPhone plugged in to your Mac, open up Safari. In the top menu bar, there's a menu item labeled "Develop." After revealing the Develop menu, you should see a menu item with the name of your iPhone. The menu item has a submenu, which contains all of the UIWebViews currently present on the iPhone. Clicking them will open up a developer console for that UIWebView (the same one you see in web pages in Safair.) Check the console to see if there are any errors. You might have to reload the web view first, as it won't display any messages from before the console was open (you can reload the web view by pressing ⌘R in the console.)

**Comment by vir474** [comment]
on the console i got two things 


![log](https://cloud.githubusercontent.com/assets/7997646/5876255/d7e27ffe-a2e3-11e4-9e7e-fb93dea34e09.png)

**Comment by jonnywonny** [comment]
Hmm, well neither of those should be halting the execution of your script.

Try running this in the console to make sure that the notifications are actually being added:
`plugin.notification.local.getScheduledIds(function(ids) {console.log(ids);})`

You should see ["0"]

**Comment by vir474** [comment]
@jonnywonny  well i see ["3"] !!

**Comment by jonnywonny** [comment]
Well, then it certainly seems like the notification is being properly added. 

At this point it seems like the only way to move forward would be to either find a different plugin for local notifications, or start looking into the actual iOS source of the plugin to see if you can figure out what's going wrong (that's how I solved my problem.)

**Comment by vir474** [comment]
@jonnywonny ahh ok ! thanks for the help

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
