### ISSUE TITLE
Play sound while app in Background

### ISSUE THREAD

**Issue by Alkashi** [katzer/cordova-plugin-local-notifications#399]
Hi all,

First, thanks for this great plugin it works like a charm !

Question : is there any way to play a sound while the app is in Background. 
I mean : is it possible to call a method when a local notification is fired and the app is in Background ? (screen locked or browsing another app for example)

**Comment by MichelReij** [comment]
I'm not sure what you mean Alkashi: with this plugin you are using the notification mechanism of the device OS to play the sound (along with a message) at the desired time. Then, if the user decides to click the message, your app is launched. Whatever you want to do then is up to you...

**Comment by Alkashi** [comment]
Thanks Michel,

Basically, I want to play a long mp3 when a local notification is Fired. You can consider it like an alarm. When the notification is Fired, I want to play an mp3 file whose duration is > 30 sec.

Is it more clear ?

**Comment by MichelReij** [comment]
Ah yes, it's clear now. But this is not possible without the user clicking the notification first, as far as I know.

**Comment by lylepratt** [comment]
It should play the sound when the UILocalNotification is fired as long as its less than 30 seconds. Unfortunately a UILocalNotification can not play sounds >30 sec.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
