### ISSUE TITLE
Notification sound on iOS

### ISSUE THREAD

**Issue by bayhall-digital** [katzer/cordova-plugin-local-notifications#400]
I understand from the documentation that on iOS you need to get the user to manually change the settings in the Notification Center to allow sounds.

"Note: To play notification sounds, permission needs to be granted in the notification center settings."

I'm using PhoneGap Build and everything is working perfectly on Android (playing sounds) and Apple (no sounds).

Is there a reason this Plugin can't obtain/request for Sound notifications? I need to justify/explain the reasons.

Is there any way that I redirect the user directly from the App to the Notification Center settings for the App? Or is there another plugin I can use to obtain notifications without having to leave the App?

My issue is I don't expect all of the users of this App to know how to find the Notification Center and change their individual settings.

For example, I've previously used PushPlugin which does obtain all permissions (Badges, Banners, and Sounds) - but obviously needs extra certification which I don't want/need to include for this project.

**Comment by MichelReij** [comment]
Hi bayhall-digital, for reasons that are beyond most of the users here, the master branch lacks a vital function that is present in the 0.7 branch:
```javascript
window.plugin.notification.local.promptForPermission();
```
This will prompt the user in his own language to give permission for the notifications.
So my advice if you have customers using iOS8: use the 0.7 branch (currently up to 0.7.8).

**Comment by bayhall-digital** [comment]
Thanks for the reply - currently using 0.7.8.

Should the registerPermission method create an alert to request for permission from the user?

I've done a hard reset on my iOS8 device to reset notifications for the App (delete App, reboot device, change the date into the future, reboot device and install App again), and with a promptForPermission it's now setting up sound? (although I ran registerPermission beforehand, nothing happened with this method - documentation read not available until v0.8?).

Baffled!

**Comment by MichelReij** [comment]
'registerPermission(callback)' is a 0.8 method replacing both the 'promptForPermission' (to launch the system message asking the user for permission) and 'hasPermission(callback)' methods in 0.7.8.

My experience is limited to the 0.7.8. It works there, but due to the lack of a callback on the 'promptForPermission' method, I need quite a bit of code to poll the system until the 'hasPermission' method returns true.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
