### ISSUE TITLE
Is there a way to make notification sound just one time just like others app such as whatsapp and hangouts?

### ISSUE THREAD

**Issue by rodolphorosa** [katzer/cordova-plugin-local-notifications#401]
Currently, the notification sounds forever until the user reads it. How can I make it sound only a single beep, for example, just like whatsapp?

Sorry for my bad english :)

**Comment by MichelReij** [comment]
Hi rodolphorosa, your sound should just play once for each notification. Can it be that you have specified a very small value for the 'repeat' property, causing the notification to fire repeatly with a very short interval?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
