### ISSUE TITLE
schedule notification for some future date & time in IOS

### ISSUE THREAD

**Issue by farrukhm** [katzer/cordova-plugin-local-notifications#403]
i m developing my app in Intel XDk IDE and using local notification in my app and i want to show notification at some specific time and date when any user want to set notifications at some future date & time on that that date & time notification appear, this is my code
 
function reminder(){
var msg = document.getElementById("text").value;
if(msg==''){
msg='Please Take flower..';
}
var date = document.getElementById("date").value;
var time = document.getElementById("time").value;
var now = new Date(date+' '+time).getTime(), _60_seconds_from_now=new Date(now+1*1000);
window.plugin.notification.local.add(
{
id: 1,
title: 'title',
message: msg,
repeat: 'daily',
date: _60_seconds_from_now
});
navigator.notification.alert("Successfully Add Notification ",null," Notification","OK" );
}
input type="date" id="date"
input type="time" id="time"
input type="text" id="text"
 button type="submit"  onclick="reminder()" 
 But when i click button (Reminder) my app crashes in IOS But the same code works in Android.so if you can please provide any help, I'll be really appreciative.

Thanks

**Comment by MichelReij** [comment]
Hi farrukhm, can you give some more detail of the crash? Which version of the plugin do you use? If you're testing on iOS8, you need to handle the permission request for your app to use local notifications, which is different for the 0.8 (master) branch and 0.7.8 branch.

**Comment by farrukhm** [comment]
Hi MichelReij, Thank you for your response, i m testing my app on IOS8 and i don't know how to handle the permission.and i m using this version (https://github.com/katzer/cordova-plugin-local-notifications) branch (master).
Thanks Again

**Comment by luigi37** [comment]
Hi Sebastian,
I'm not exactly sure how to make the app ask for permission in iOS8.
I would expect it to be asked at first run but I can't make the question appear.
Could you please post a very simple example of something that asks permission at the beginning and then keep it forever on (unless changed in phone settings)?

Also, shall we use the dev or main branch to work in iOS8?

Thanks a lot!
Luigi

**Comment by katzer** [comment]
hi @luigi37,
I recommend version 0.8rc (master branch). The documentation is not yet up to date, but you can use the [example branch](https://github.com/katzer/cordova-plugin-local-notifications/tree/example) as a reference.

With v0.8 you just need to schedule a new local notification and the question will appear the first time you use it.Please note that iOS will ask you only one times, even after re-installation. Later you need to change the permissions manually from the system settings.

```javascript
// => Does ask for permission automatically
cordova.plugins.notification.local.schedule({
    text: "Local Notification"
})

**Comment by luigi37** [comment]
Thanks Sebastian actually I used to use "add". Shall I move to "schedule"?

''''
window.plugin.notification.local.add({
                id:         "1234567",  // A unique id of the notifiction
                message:    "ciao",  // The message that is displayed
                title:      "My app"  // The title of the message
            });

Thanks

Luigi

**Comment by katzer** [comment]
I recommend to use `schedule`! Version 0.8rc introduces a set of some changes like renamed methods, attributes or changed method signature.

**Comment by farrukhm** [comment]
@katzer, Thanks for providing this plugin i have used this plugin in my app and it works great.

**Comment by zmandel** [comment]
Do you guys have onclick working on 0.8rc? Schedule works but not onclick
(android 4.4)

**Comment by luigi37** [comment]
@katzer 

> I recommend to use schedule! Version 0.8rc introduces a set of some changes like renamed methods, attributes or changed method signature.

Thanks Sebastian all seems to be fine now!

I reccomend update the readme to replace "add" method with "schedule" (and "message" property with "text")

Thanks!

Luigi

**Comment by katzer** [comment]
I have started with the new wiki, but its far from complete.
https://github.com/katzer/cordova-plugin-local-notifications/wiki/Schedule-Notifications

**Comment by katzer** [comment]
@zmandel, that should work:
```javascript
cordova.plugins.notification.local.on("click", function(notification) {
    alert("clicked: " + notification.id);
});
```

**Comment by luigi37** [comment]
Hi Sebastian
Is the cancel method changed as well? I'm not able to cancel a notification with same old method.. Thanks
luigi

**Comment by luigi37** [comment]
hmmm... interesting... I changed the ID from "123" (string) to 123 (number) and now cancel works properly....

Also what is the difference between "clear" and "cancel" ?
Thanks
Luigi

**Comment by katzer** [comment]
@luigi37, works with string an number - tried it!

`clear` clears the notification from the notification center, but it may schedule (again) in future.

**Comment by MichelReij** [comment]
Hi @katzer in the new wiki you briefly show the "at" and "startAt" parameters. Are these aliases for the same, or should I use "startAt" for repeating notifications and "at" for a single occurrence?

**Comment by katzer** [comment]
@MichelReij, `firstAt` is an alias for `at`.

```javascript
cordova.plugins.notification.local.schedule({
    id: 1,
    text: "Test",
    firstAt: tomorrow
});
```
Aliases like `firstAt` or `date` will be converted to `at`. If you want to retrieve a notification later, the property name will be always `at`.
```javascript
cordova.plugins.notification.local.get(1, function (notification) {
    alert(notification.at);
})
```

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
