### ISSUE TITLE
Missing notifications on Android

### ISSUE THREAD

**Issue by joanlopez** [katzer/cordova-plugin-local-notifications#405]
Hi,

I want to use this plugin to schedule notifications for a large period of time. For example in a week, in a month, in a year... Basically it has to do something like a local calendar:

I add a reminder for next thursday at 9pm, then I expect that on next thursday it will display the notification at 9pm.

I was testing, and there are some notifications that are not displayed (also with notifications scheduled for the same day).

For this, I have a question: 

Does the plugin manage the possible app crashes & auto closing (Android OS closes the apps in background when it needs more memory)?? Does the plugin manage a possible mobile restart? Or I have to manage every of this possible things with some other plugins like background?

If I haven't, why there are some notifications that are never displayed?

(Sorry for my low-level of english)

**Comment by MichelReij** [comment]
Hi joanlopez, I seem to be getting similar issues on Android. It's been working fine for a long time now on iOS, but Android still seems to be flaky. It works fine for the short term, but longer term it's not entirely reliable. I haven't found a pattern yet. I'm using the 0.7.8 version.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
