### ISSUE TITLE
work nice on android , ios 8 , but crashing on iOS 7

### ISSUE THREAD

**Issue by l3th2nh** [katzer/cordova-plugin-local-notifications#407]
Hi all , 
i using xcode 6 with sdk8.1 , cordova 3.6.3  for build app , it wrok nice on android , ios 8 , but crashing and not work on iOS 7  . who can explain to help me or explain to me why ? how to me can fix this? 

one more thing i use verison 0.8.0  . old vesion work nice , but i like feature upgrade for new version 

Thanks

This is log warning : 

Finished load of: file:///var/mobile/Applications/C516BAB0-6F69-42D9-8827-6052B92D3C11/Demo.app/www/index.html
2015-02-04 23:23:53.576 Demo[1982:1803] -[UIApplication registerUserNotificationSettings:]: unrecognized selector sent to instance 0x16629c60
2015-02-04 23:23:53.579 Demo[1982:1803] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication registerUserNotificationSettings:]: unrecognized selector sent to instance 0x16629c60'
*** First throw call stack:
(0x2ef39ecb 0x396d4ce7 0x2ef3d7f7 0x2ef3c0f7 0x2ee8b058 0x33e77 0x31897 0x39bbdd53 0x39bc3689 0x39bc38dd 0x39ceec17 0x39ceeadc)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
