### ISSUE TITLE
Crash iOS7 when adding notification

### ISSUE THREAD

**Issue by sjvisschers** [katzer/cordova-plugin-local-notifications#408]
I'm trying to schedule some repeating notifications in my app.
It all works wonderfull in Android, but in IOS it doesn't work.

I used the last version in the Master and it just crashes.

In the log I see the following:
`Feb  4 20:19:15 iTouchs-iPhone-4 AppName[1895] <Error>: -[UIApplication registerUserNotificationSettings:]: unrecognized selector sent to instance 0x15d20e30`

I tried an fixed suggested by craig-at-rsg in pull-request #388. It stopped the app from crashing,
 but no notifications are scheduled then.

Can anybody help me with this? 

I use IntelXDK to build the app.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
