### ISSUE TITLE
Build Failed - iOS

### ISSUE THREAD

**Issue by parsafatehi** [katzer/cordova-plugin-local-notifications#409]
** BUILD FAILED **
The following build commands failed:
	CompileC build/***.build/Debug-iphonesimulator/***.build/Objects-normal/i386/APPLocalNotification.o ***/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
ERROR building one of the platforms: Error: /Users/parsaf/MobileApps/***/platforms/ios/cordova/build: Command failed with exit code 65
" You may not have the required environment or OS to build this project "

**Comment by guanxun** [comment]
Problem was in plugin files not being copied into `platforms/ios/recordcalories/Plugins/`. I manually copied them over and could build successfully.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
