### ISSUE TITLE
Local image path seem to fail

### ISSUE THREAD

**Issue by tolu360** [katzer/cordova-plugin-local-notifications#412]
Hi All,

Is anybody else having issues with using local image path for custom notification icons? Doing this ```window.plugin.notification.local.add({ icon: 'file://img/icon.png' });``` does not seem to work for me. I had my icon.png in www/img but it doesn't get used for the notification. Any ideas? Thanks

**Comment by zmandel** [comment]
hi tolu360, I have not tried the custom icon feature, however "file://img/icon.png" doesnt look like a valid path. try showing the icon in your webapp and do alert(iconPath) and see what it shows.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
