### ISSUE TITLE
Expired Date Notification Triggering.

### ISSUE THREAD

**Issue by tamilp** [katzer/cordova-plugin-local-notifications#417]
I had a problem in my android 4.4 Past date notification coming, please resolve this problem.

**Comment by tamilp** [comment]
I was tested both master and stable, please check.

**Comment by katzer** [comment]
hi @tamilp, can you please explain a bit more detailed what you mean?

If you schedule a local notification with a date points to the past, the notification will trigger immediately.

**Comment by tamilp** [comment]
Thanks for the quick replay Katzer.

In my DB i have a list of date and time.

for ex...
Fri Feb 16 2015 09:00:00 GMT+0530 (India Standard Time)
Fri Feb 17 2015 09:00:00 GMT+0530 (India Standard Time)
Fri Feb 18 2015 09:00:00 GMT+0530 (India Standard Time)

If I fetch and put the notification by now(Fri Feb 18 2015 10:40:00 GMT+0530 (India Standard Time)), The Notification will trigger immediately.

**Comment by tamilp** [comment]
All the Three

**Comment by tamilp** [comment]
Thanks for the quick replay Katzer.

In my DB i have a list of date and time.

for ex...
Fri Feb 16 2015 09:00:00 GMT+0530 (India Standard Time)
Fri Feb 17 2015 09:00:00 GMT+0530 (India Standard Time)
Fri Feb 18 2015 09:00:00 GMT+0530 (India Standard Time)
Fri Feb 19 2015 09:00:00 GMT+0530 (India Standard Time)

If I fetch and put the notification by now(Fri Feb 18 2015 10:40:00 GMT+0530 (India Standard Time)),
the first three date and time will trigger immediately, the last date and time working correctly.

**Comment by tamilp** [comment]
Thanks for the quick replay Katzer.

In my DB i have a list of date and time.

for ex...
Fri Feb 16 2015 09:00:00 GMT+0530 (India Standard Time)
Fri Feb 17 2015 09:00:00 GMT+0530 (India Standard Time)
Fri Feb 18 2015 09:00:00 GMT+0530 (India Standard Time)
Fri Feb 19 2015 09:00:00 GMT+0530 (India Standard Time)

If I fetch and put the notification by now(Fri Feb 18 2015 10:40:00 GMT+0530 (India Standard Time)),
the first three date and time will trigger immediately, the last date and time working correctly.

**Comment by katzer** [comment]
This is intended.

**Comment by tamilp** [comment]
but in your previous versions like 0.6.3, i m not getting this kind of a problem the current version only i m getting.

**Comment by tamilp** [comment]
but i m not getting this kind of problem with your previous versions(0.6.3), current version only i m getting.

**Comment by katzer** [comment]
You can check if the date was in the past before scheduling it. I hope thats a working solution for you.

**Comment by tamilp** [comment]
but I m using repeat, for future the past before scheduled notification will not trigger ?

**Comment by MichelReij** [comment]
Hi tamilp, when setting a repeating notification you will need to compute the first occasion in the future on which this should fire and specify this in your "add" or "schedule" (v.8.0rc) command.

I found the Moment.js library to be very useful with this: http://momentjs.com

**Comment by tamilp** [comment]
Thanks @MichelReij this might be very useful, will try and give the feedback.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
