### ISSUE TITLE
Prevent notification from showing up

### ISSUE THREAD

**Issue by bmilakovic** [katzer/cordova-plugin-local-notifications#419]
Hi, 
Is it possible to do some checking right before notifiaction is triggered and then to decide should it be displayed or not? Something like:
```javascript
window.plugin.notification.local.ontrigger = function (id, state, json) {
 if (doNotShowNotification) {
    return false;
  }
};
```
Thanks.

**Comment by katzer** [comment]
Not in that way because the system does trigger the notification and the app may or may not run at that moment.
If the app is running you can cancel or update the notification once triggered.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
