### ISSUE TITLE
Notifications are scheduled, but not show up on iOS

### ISSUE THREAD

**Issue by ochakov** [katzer/cordova-plugin-local-notifications#421]
Hi,

Testing the latest 0.8rc
On Android, everything works fine.
For iOS, we compile for iOS 8.1 and apply runtime crash fix for iOS 7

A simple test:

cordova.plugins.notification.local.schedule({
	id: 1, text: "Local Notification", title: "test"
});

Shows nothing for both iOS8.1 and iOS7
The same happens for scheduled notifications

Any ideas?

**Comment by katzer** [comment]
hi @ochakov,

because of the runtime crash:
For iOS8 the app needs to be compiled with iOS8 SDK and for iOS7 you have to switch to iOS7 SDK. Otherwise the plugin will crash on iOS7 when it was compiled with iOS8 SDK.

**Comment by katzer** [comment]
Re: the other issue

It looks like your app does not have the permission to show local notifications. You can use `hasPermission` and `registerPermission` to check that.

Please see https://github.com/katzer/cordova-plugin-local-notifications/tree/example#ios8-permission

**Comment by sjvisschers** [comment]
Hi @katzer,

Are your seriously saying we need to build a different app voor ios8 and for ios7? This will be a problem, because you cannot push two ipa's to the store (as far as I know). I also have the problem it's not working on ios. 

BTW, I really appreciate the work you have done on this plugin, cause I know how difficult local notifications are.

**Comment by ochakov** [comment]
Hi @katzer,

Actually the iOS7 crash was easily fixed with runtime check.
I do have the permissions, I am calling the functions and get the permission before calling the function from the example.

**Comment by clawish** [comment]
Having the same issue. If I apply the crash fix by commenting out the condition:
    // if ([notId isEqualToString:id]) {
        return notification;
    // }
the notifications just don't show up. 

    window.plugin.notification.local.hasPermission(function (granted) {
       console.log('Permission has been granted: ' + granted);
    });
returns `true`.

**Comment by ochakov** [comment]
Something is very strange. I create new cordova project, add ios platform, add local notification plugin 0.8 from git. No changes at all. Add two buttons, one is calling cordova.plugins.notification.local.registerPermission(); the second one is calling cordova.plugins.notification.local.schedule({
	id: 1, text: "Local Notification", title: "test"
});

Run on iOS8 simulator and it's not working. I get permission prompt on the first button, but nothing happens for the second one.
Any ideas?

**Comment by rm-km-it** [comment]
Both the crash and the not showing notification in iOS 7 can be fixed with this change

https://github.com/rm-km-it/cordova-plugin-local-notifications/commit/74cac52de33935a86045b0fd1098a6c12bc2de5f

**Comment by clawish** [comment]
works, but only for iOS 7.1 and along with this fix https://github.com/katzer/cordova-plugin-local-notifications/issues/413 .
However iOS 8.1 still has **no** notification triggered.

**Comment by ochakov** [comment]
Hi again,

I was able to isolate the problem and make the trivial example above work on both iOS7 and iOS8 using the fix provided by @rm-km-it (thanks a lot!)

The original issue on iOS8 happens when creating multiple notifications. It looks like adding many notifications in a loop, only keeps the last one scheduled. That was originally the issue, so now this is the only problem I will have to solve.
BTW, adding setTimeout with some random numbers to schedule multiple notifications works, but obviously this is not the solution for this issue.

Thanks!

**Comment by rm-km-it** [comment]
Ah, right, I've got the #413 fix, too, and it's working in 7.1 and 8

**Comment by katzer** [comment]
@ochakov,
if your app is in foreground when the notification gets triggered then iOS does add it only to the notification center. The user will only get notified if the app is not running (in foreground).

**Comment by ochakov** [comment]
Hi @katzer,
I was able to make everything perfectly working. I had to create a queue of notifications and using the callback, adding them one by one from the queue only after the previous notification has been scheduled. It's an ugly workaround, but it works now. If you will be able to solve adding multiple notifications in a loop on iOS (it works fine on Android), I will be following that and get an update.

Thanks for your great work!

**Comment by katzer** [comment]
I can add multiple at once and it works!

```javascript
cordova.plugins.notification.local.schedule([{
    id:   1,
    text: 'Multi Message 1'
},{
    id:   2,
    text: 'Multi Message 2'
},{
    id:   3,
    text: 'Multi Message 3'
}]);
```

**Comment by ochakov** [comment]
I know, but for be it's a bigger change, as I don't have all of them. It's not a simple loop, but a callback...
I will try to play more later. Thanks!

**Comment by clawish** [comment]
Alright. In the end I was just too incredibly stupid.
Got it working now as you do with https://github.com/rm-km-it/cordova-plugin-local-notifications/commit/74cac52de33935a86045b0fd1098a6c12bc2de5f and https://github.com/katzer/cordova-plugin-local-notifications/issues/413 .
Thank you very much for the hotfixes. I hope they make it to master.

**Part of my problem was**: make sure that you're app does it's local notification via a banner or something that you actually see, when the app is in the background, you can set that in the settings. Also: make sure you understand that the notification scheduling mechanism via a date property in your notification object that you are passing requires a **date**, not a date string or something. To schedule a notification 5 seconds into the future (to test if local notification works when app is in background), you can use 

    window.plugin.notification.local.schedule({
        text: 'bg message',
        date: (new Date((new Date()).getTime()+5000))
    });

This is embarrassing...

**Comment by katzer** [comment]
@sjvisschers, both SDKs are supported now by a single binary. For compilation iOS 8 SDK is required.

**Comment by sjvisschers** [comment]
@katzer, Super!! 

I've tried it and it now works perfectly for me.

Thanks for all the effort you have put in this plugin!!!

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
