### ISSUE TITLE
App getting crashed on iOS 7

### ISSUE THREAD

**Issue by kalyanpkumar** [katzer/cordova-plugin-local-notifications#422]
Hi Team,

I am using this plugin for one of my phonegap app. The plugin is working fine on iOS 8, but on iOS 7 it is crashing. May i know how to fix it. Please find the attached screen shot of the crash issue.

Xcode version - 6.1.1
Base Sdk - iOS 8.1
Deployment target - iOS 7.0 & 7.1

Please do needful and let us know how to fix the issue.

![localnotification](https://cloud.githubusercontent.com/assets/11042372/6290096/77506958-b94a-11e4-835b-f043c6b54925.png)

**Comment by katzer** [comment]
The problem would be solved with iOS7 SDK instead of iOS8 SDK

**Comment by kalyanpkumar** [comment]
Hi Sebastian…

Thanks for the information…

So, i have Xcode 6.1.1 with base sdk iOS 8 and deployment target as iOS 7 on my device…. don’t this work??

So, you say that base sdk should be iOS 7 right??

So, if i build the app with iOS 8 sdk and run on iOS 7 device, does that work?? But the SDK should be supporting iOS 7 too right as it is updated sdk….

So, if possible can we do any fix in the current plugin in such a way that the current plugin should be supporting iOS 7 too….

Please let me know….


Regards
Kalyankumar Parise
Team Lead - iOS Applications Development
M: +91 7396476329 | T: 040 42000654
e-mail : kalyan.p@bravemount.com
skype  : kalyan.parise

**Comment by katzer** [comment]
With the latest [commit](77eec5985b3693208f4bfd21403f3e04b147cb0f) both SDKs and deployment targets should work from a single binary.

**Comment by manuelpaulo** [comment]
Same here. Workaround:

Seems like it only crashes when the first call is an window.plugin.notification.local.add.

Try doing a window.plugin.notification.local.getScheduledIds first and them the add and it will work.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
