### ISSUE TITLE
Cordova is never ready when using local-notifications on IOS

### ISSUE THREAD

**Issue by kristianbenoit** [katzer/cordova-plugin-local-notifications#425]
The cordova-plugin-local-notifications plugin prevent Cordova from issuing deviceready on IOS. When the plugin is loaded I get the following errors which I don't get without the plugin.
```
[Log] deviceready has not fired after 5 seconds. (console-via-logger.js, line 173)
[Log] Channel not fired: onCordovaInfoReady (console-via-logger.js, line 173)
```

**Comment by kristianbenoit** [comment]
Fix this by `cordova platform rm ios` and `cordova platform add ios`.

**Comment by katzer** [comment]
Hi, thats a often seen cordova bug, but you are right.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
