### ISSUE TITLE
Crosswalk compability

### ISSUE THREAD

**Issue by MaZZly** [katzer/cordova-plugin-local-notifications#426]
With crosswalk it doesn't compile if localnotification plugin is used.
```
APP/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:473: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
APP/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:470: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJava'.
```

I can get rid of compilation errors by removing the `sendJavascript` function in `LocalNotification.java:463`
and replacing the 2 calls to it (`:419` & `:454`) with `webView.sendJavascript(js);`

Then it will compile.. Then when calling cancelAll() or scheduledIds() (And maybe others) the app crashes and output is: 
`[ERROR:runtime_javascript_dialog_manager.cc(69)] Not implemented reached in virtual void xwalk::RuntimeJavaScriptDialogManager::WebContentsDestroyed(content::WebContents*)`

Ideas?

**Comment by ggr86** [comment]
I can confirm this issue too.

**Comment by shprink** [comment]
same here!

**Comment by katzer** [comment]
https://github.com/katzer/cordova-plugin-local-notifications#i-would-like-to-propose-new-features

**Comment by marco-broccio** [comment]
Same for me.

Temporarily use this. It works for me.

http://plugins.cordova.io/#/package/jp.wizcorp.phonegap.plugin.localnotificationplugin

**Comment by beliz** [comment]
Same for me.

**Comment by DanailMinchev** [comment]
I'm receiving same error in [Apache Cordova Android 4.0.0](http://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html)

```
/home/danail/git/app/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:495: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
/home/danail/git/app/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:492: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/danail/git/app/platforms/android/src/org/apache/cordova/file/ContentFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
 FAILED
```

According to http://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html, new Android uses first-class support for Crosswalk

**Comment by danielfpedro** [comment]
same here

**Comment by danielfpedro** [comment]
Not sure if the issue is about crosswalk or the new cordova release that is building with Gradle instead Ant

**Comment by katzer** [comment]
local-notification plugin will support Cordova 4 and Crosswalk starting with v0.9

**Comment by danielfpedro** [comment]
Can you say when? I'm not trying to rush you, I'm asking because I have a project that is using crosswalk and I'm wating this release

**Comment by danda1man** [comment]
I'm also running into this, any timeline on 0.9?

**Comment by keenkiran** [comment]
I am also running into this same issue. When do you think 0.9 will be out please ?

**Comment by pnmougel** [comment]
Same problem here, I would like to use this plugin with Crosswalk

**Comment by mirkofisic** [comment]
I have the same problem with cordova 5.0.0

**Comment by TedWei** [comment]
I have the same problem with cordova 5.0.0

**Comment by shuhanxu** [comment]
+1

**Comment by sonnylazuardi** [comment]
+1

**Comment by Krysisx** [comment]
+1, same problema with cordova 5.0.0 and android platform version 4.0.0

**Comment by hafeyang** [comment]
+1

**Comment by mejainankit** [comment]
+1, i also have same issue with cordova 5.0.0 and cordova android platform 4.0.0

**Comment by Durss** [comment]
is it really necessary to say i have the same problem..? :p

**Comment by mansa-dev** [comment]
+1 Crosswalk on Cordova@5.0

**Comment by dwhogg** [comment]
+1

**Comment by martinbrylski** [comment]
+1

**Comment by Gaafar** [comment]
+1

**Comment by Gaafar** [comment]
Having the same issue without crosswalk

**Comment by ag-secret** [comment]
Why this issue was closed?

**Comment by 1wQasdTeedFrsweXcs234saS56Scxs5423** [comment]
I am having similar issue with phonegap 4.

**Comment by 1wQasdTeedFrsweXcs234saS56Scxs5423** [comment]
![screen shot 2015-05-25 at 9 27 29 am](https://cloud.githubusercontent.com/assets/7888138/7791587/5ba96456-02c0-11e5-9db8-8222964511c3.png)


This is the issue I get when I try to compile it.

**Comment by sharifbdp** [comment]
same problem here :(

/cordova/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:495: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
/Users/sharif/Desktop/android-project/cordova/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:492: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)

**Comment by DawnMage** [comment]
+1

**Comment by kentoo** [comment]
same here.
+1

**Comment by EgyptionBoy** [comment]
same

**Comment by 1wQasdTeedFrsweXcs234saS56Scxs5423** [comment]
use webView.getView().eva... this should solve your problem.

**Comment by Santino-Wu** [comment]
+1

**Comment by sharifbdp** [comment]
I got a solution. Hope it works ---

webView.getView().post(new Runnable(){
         public void run(){
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
              webView.sendJavascript(js);
            } else {
              webView.loadUrl("javascript:" + js);
            }
       }
 });


HaPpY CoRdOvIaNs :)

**Comment by MaZZly** [comment]
Well the fix makes the project compile.. But when calling the localnotifications functionality the app crashes so it's not really a solution...

**Comment by holographix** [comment]
+1 same here, no matter what the fix

**Comment by bradmartin** [comment]
+1 crosswalk compat. would be nice

**Comment by wilianto** [comment]
+1
same here

**Comment by abremner** [comment]
+1 Yes please.

**Comment by canda** [comment]
+1

**Comment by dfq** [comment]
+1

**Comment by sebasi** [comment]
I forked one a working versions with crosswalk and removed the events that were crashing the app (basically everything trying to callback to Cordova). Unfortunately I am not into Cordova that much yet so I can implement it correctly. 

You will not be able to hook into events, like cordova.plugins.notification.local.on("click", callback .. ).
It works for what I need. Perhaps it's enough functionality for some of you until it's fully implemented upstream.

https://github.com/sebasi/cordova-plugin-local-notifications

Cheers, Seb

**Comment by Shinji89** [comment]
+1

**Comment by Jeff-Tian** [comment]
+1

**Comment by victoriaSh** [comment]
+1 :(
after updating cordova to 5.0.0 and android sdk to 22

**Comment by victoriaSh** [comment]
The best decision is to save your www directory and list of plugins, then create new project, install all plugins and copy www directory.
Works for me even with crosswalk. Build successful.
P.S Haven't checked emulator yet

**Comment by ivangabriele** [comment]
:+1:

**Comment by mcoeur** [comment]
+1

**Comment by mjanisiewicz** [comment]
+1 - I'm using Cordova 5.0.0.

**Comment by winterwurzel** [comment]
+1

**Comment by murilolobato** [comment]
+1

**Comment by canda** [comment]
I think it is a cordova 5 issue. As stated here https://github.com/katzer/cordova-plugin-local-notifications/issues/535
I solved this way
I changed LocalNotification.java 
both
/plugins/de.appplant.cordova.plugin.local-notification/src/android/LocalNotification.java
/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java
replacing the function in line 554 with

    private static synchronized void sendJavascript(final String js) {

        if (!deviceready) {
            eventQueue.add(js);
            return;
        }
        webView.getView().post(new Runnable(){
          public void run(){
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
              webView.sendJavascript(js);
            } else {
              webView.loadUrl("javascript:" + js);
            }
          }
        });
        // webView.post(new Runnable(){
        //     public void run(){
        //         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
        //             webView.evaluateJavascript(js, null);
        //         } else {
        //             webView.loadUrl("javascript:" + js);
        //         }
        //     }
        // });
    }

**Comment by danda1man** [comment]
Agree with @canda, this is really a Cordova 5/Cordova Android 4 issue, not necessarily crosswalk issue.  His fix does work (no runtime errors I have seen yet), just need to also delete this jar to fix the compilation error: platforms/android/libs/android-support-v4.jar

**Comment by bradmartin** [comment]
Do the notifications work with the fix proposed by @canda ?

**Comment by danda1man** [comment]
@bradmartin yup, just finished checking my app, notifications come in with all of the properties

**Comment by bradmartin** [comment]
@danda1man thanks! I'll use the fix then. Big thanks to @canda  for the code.

**Comment by murilolobato** [comment]
Shouldn't be created a pull request to fix this, and create a new tag in the repository to be used with cordova 5?

**Comment by ObjectiveTruth** [comment]
Thank you @canda! for the code snipped. It all works now. 

This Should really just be updated in a PR

**Comment by kennedymca** [comment]
not working i have a error   cannot resolve method in this line   webView.evaluateJavascript(js, null)

**Comment by behrad** [comment]
+1

**Comment by flavioalves** [comment]
+1

**Comment by aaronprojects** [comment]
+1

**Comment by HNygard** [comment]
+1

**Comment by allan-empalmado** [comment]
@canda fix works :)

**Comment by dolphineor** [comment]
+1

**Comment by marcoocram** [comment]
+1

**Comment by Krysisx** [comment]
+1

**Comment by csvan** [comment]
+1

**Comment by mblecek** [comment]
+ 1

**Comment by hirogasa** [comment]
+1

**Comment by Crashthatch** [comment]
+1

**Comment by moshetet** [comment]
Hi had a compliation error with @canda`s fix due to the method sendJavascript expecting only one argument and not the 2nd null parameter that was still left there.
I've forked it and fixed it. if anyone is intrrested:
https://github.com/moshetet/cordova-plugin-local-notifications

**Comment by nerdfiles** [comment]
@canda's solution +1

**Comment by darchanjo** [comment]
Worked for me: https://github.com/sebasi/cordova-plugin-local-notifications 
on Cordova 5.4.1

**Comment by lobobobo** [comment]
@canda thank you so much your solution worked for me :)
@sharifbdp thank you too for half solution;)

**Comment by donaldinou** [comment]
+1
We need a new release :P

**Comment by swswnt** [comment]
how to end schedule notification after particular time(2 hours)??

**Comment by jQrgen** [comment]
+1

**Comment by degaray** [comment]
+1

**Comment by vancentvan** [comment]
Call native app from a web application and then get this error while tabbing back ....
[ERROR: runtime_javascript_dialog_manager.cc(69) ] Not implemented reached in virtual void xwalk::RuntimeJavaScriptDialogmanager::ResetDialogState(content::WebContents*)

**Comment by felixschul** [comment]
@darchanjo I am not surprised that sebasis's plugin compiles, since the relevant lines are just commented out: https://github.com/sebasi/cordova-plugin-local-notifications/blob/master/src/android/LocalNotification.java#L552
I would be surprised if the actual notifications fire through...
