### ISSUE TITLE
isScheduled crash (both 0.7.8 and 0.8rc)

### ISSUE THREAD

**Issue by joshbuckley182** [katzer/cordova-plugin-local-notifications#428]
In my app I'm testing whether a notification is scheduled, but it's causing a crash. It looks like when the notification is created, it's getting an integer ID, rather than a string. 

Additionally, maybe related, when calling `getScheduledIds`, I'm getting an empty array - even when I know I've created a notification or two. 

Any ideas? Let me know if I can provide any more info to help debug it. 

This screenshot is using 0.8rc, but it's also happening on 0.7.8:
![screen shot 2015-02-24 at 22 07 28](https://cloud.githubusercontent.com/assets/957402/6360451/f1dc5342-bc71-11e4-99ca-cad5e97e7107.png)

**Comment by CoenWarmer** [comment]
Getting the same crash on 0.8rc.

**Comment by katzer** [comment]
Is fixed: 61aa0f067cedaacd8d08b14b17dcb4aab2a4b936

**Comment by CoenWarmer** [comment]
Thanks @katzer !

**Comment by joshbuckley182** [comment]
:+1:

Turns out I had another issue too, but it's kinda unrelated to this plugin - I'd previously used another notifications plugin (https://github.com/simplec-dev/LocalNotification) which had set a notification that didn't have an `options.id` set, thus causing a crash.
