### ISSUE TITLE
Why cancelling notifications older than 5 days?

### ISSUE THREAD

**Issue by MichelReij** [katzer/cordova-plugin-local-notifications#429]
Hi @katzer, I noticed in the iOS code that you cancel on app termination all repeating notifications that are older than 5 days:
```
/**
 * Clears all single repeating notifications which are older then 5 days
 * before the app terminates.
 */
- (void) onAppTerminate
{
    [self cancelAllNotificationsWhichAreOlderThen:432000];
}
```
But why? I have a lot of repeating notifications that repeat 'every': 'week', as they should only fire on Wednesday or Thursday etc. I have a routine in place that reschedules these, but that's a band-aid I would rather get rid of.

**Comment by katzer** [comment]
hi @MichelReij,
there is a reason why that needs to be done. But indeed there is a bug, because the methods cancels all repeating instead of non-repeating notifications.

I will fix that and close the issue.

**Comment by MichelReij** [comment]
Merci Sebastian!
