### ISSUE TITLE
Does local notification work in android 5 ?

### ISSUE THREAD

**Issue by tamilp** [katzer/cordova-plugin-local-notifications#430]
Can any one tell me, local notification work in android 5 ?

**Comment by katzer** [comment]
yes it does

**Comment by tamilp** [comment]
but its not working on 0.7.6 version with my emulator.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by tamilp** [comment]
Will check @katzer
