### ISSUE TITLE
Can the badge value be incremental...

### ISSUE THREAD

**Issue by bayhall-digital** [katzer/cordova-plugin-local-notifications#431]
Is the badge value incremental? If I set it to 1, will this always set the badge value to 1, or should it increment by 1 if the app already has a current badge value? ie, if the current app badge value is displaying 1, another reminder goes off, app badge value changes to 2.

Currently, the app always displays the value 1 regardless of how many local notifications go off, ideally I'd like this to increment - is there a way to make this plugin increment?

**Comment by katzer** [comment]
Thats not possible by the OS because the app may not run at trigger time and therefor a notification has to be scheduled with a fixed badge number.

**Comment by bayhall-digital** [comment]
OK - thanks for the answer.
