### ISSUE TITLE
Notifications works only first minutes after phone is locked (android)

### ISSUE THREAD

**Issue by vcartera81** [katzer/cordova-plugin-local-notifications#432]
Hi, I have a strange behavior with this plugin. It works as expected when application is in both foreground and background. I can push notifications and everything seemed worked fine.

However, when the phone is locked, notifications works for first, lets say, five minutes (i mean, for the next five minutes my application can create local notifications and I can hear notification sounds and see them in notifications area if I unlock the phone). After this time, they doesn't work anymore, until I unlock the phone and bring to front my application. In this case it starts pushing well again.

My piece of code is:

currentParams.notificationsController = {
                                notifyInStatusBar: {
                                    notifyAboutNewEvent: function (ev) {
                                        var la = currentParams.GetLinkedAccountById(ev.UserId);

                                        if (ev != undefined && ev.UserId != user.UserId && currentParams.application.isInBackground) {
                                            var delay = new Date(new Date().getTime() + 1000); //delay one second

                                            window.plugin.notification.local.add({
                                                id: ev.EventId,
                                                title: la.FirstName + " " + la.LastName + " added new event",
                                                message: ev.Title + " (" + ev.Class + ") - " + ev.Amount.toFixed(2) + " " + la.RefCurrency,
                                                autoCancel: true,
                                                date: delay
                                            });
                                        }
                                    },

**Comment by katzer** [comment]
@vcartera81, its because of the app was paused in background - thats normal behavior.

**Comment by vcartera81** [comment]
@katzer , no it's not. I can "ping it" and see it works responding to my requests (of signal-r for example). The application is up and running in the background for sure.

**Comment by katzer** [comment]
Do you use version 0.8?

**Comment by vcartera81** [comment]
0.8.0dev

**Comment by katzer** [comment]
Would you please update to 0.8rc2 first and let me know if it still exists.

You may also take a look [here](https://github.com/katzer/cordova-plugin-local-notifications/wiki/Upgrade-Guide)

**Comment by vcartera81** [comment]
How can I upgrade from Visual Studio (Tools for Apache Cordova CTP3) ?

**Comment by katzer** [comment]
You need to install the plugin from github source via cmd line:

```
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.8.0rc2
```

**Comment by vcartera81** [comment]
Testing right now, I'll let it pass a half of hour and see if it works.. thanks!

**Comment by vcartera81** [comment]
Updated and it doesn't worked. I even installed BackgroundMode plugin, to ensure my application will work as a service (now I have a notification that says "App is running in the background doing heavy tasks"). Anyway, after 5 minutes or so, I can't send any notifications (same behavior).

And, with 0.8rc2 all notifications generated by my application strangely have a bell icon instead of my application icon. This is confusing as with earlier 0.8 it was ok (notifications were decorated with my app logo icons).

**Comment by katzer** [comment]
#### 5 min issue
Let me try it out with my phone.

#### Icon
I have changed the default value for icon from _res://ic_popup_reminder_ to _res://icon_. But as you can imagine its impossible to find valid default values for everyone.

Luckily its possible to change the default values per app.

```javascript
cordova.plugins.notification.local.setDefaults({
    icon: "res://icon",
    smallIcon: "res://ic_popup_reminder"
});
```

**Comment by katzer** [comment]
Tested with LG and have not that issue. Seems to be phone-specific.

**Comment by vcartera81** [comment]
Ok, I'll check this on virtual and other devices. Thanks for assistance!
