### ISSUE TITLE
Race condition when device is ready

### ISSUE THREAD

**Issue by kristianbenoit** [katzer/cordova-plugin-local-notifications#433]
There is a race condition when the device is ready between the plugin calling the callback (`ontrigger`, `onclick`, ...) and the application registering the callbacks.

Here's what is happening.

1. The application register the callback when it receives `deviceready`.
2. The plugin catch the device ready in javascript and pass it to native.
   * which calls `timeout(plugin.onclick(...), 0)`
3. plugin.onclick(...) is called.

1 and 2 works by registering a callback to `'deviceready'` which might be executed in any order. Since native add a timeout, it is normally executed after all device ready are executed so no problem.

When using a framework like ionic, one should normally register the callbacks in `$ionicPlatform.ready(...)` which happens sometime after deviceready.

My solution is to manually send `deviceready` after I register the callbacks. This implies to changes in the behaviour and would break everyones code.

I'm writting this to discuss a solution. Perhaps we can add a configuration in config.xml ?

**Comment by stefanmdt** [comment]
I've spent hours identifying this problem the last days. ;) In my case, it works when registering the callbacks is the first step in $ionicPlatform.ready(...), but that's pure accident of course.

How about a dedicated event or some kind of init() function?

**Comment by katzer** [comment]
OK, is see. The plugin uses the after-deviceready event to fire the events because the listeners should be registered on deviceready  event.

But probably ionic's deviceready gets called after cordova's after-deviceready event. Right?

**Comment by kristianbenoit** [comment]
Seems like it.

Here's how both register for device ready

This plugin
=========

```javascript
channel.deviceready.subscribe(function () {
    // Device is ready now, the listeners are registered
    // and all queued events can be executed.
    exec(null, null, 'LocalNotification', 'deviceready', []);
});
```

Ionic
====

```javascript
document.addEventListener("deviceready", onPlatformReady, false);
```

Which calls all registered functions to ionic.Platform.ready:

```javascript
function onPlatformReady(...) {
  ...
  for (var x = 0; x < readyCallbacks.length; x++) {
      // fire off all the callbacks that were added before the platform was ready
      readyCallbacks[x]();
  }
  ...
}
```

One of these callback is the `$ionicPlatform.ready(...)`:

```javascript
      function(cb) {
          var q = $q.defer();

          ionic.Platform.ready(function() {
            q.resolve();
            cb && cb();
          });

          return q.promise;
        }
```

As far as I can see in Angular code (https://github.com/angular/angular.js/blob/master/src/ng/q.js#L364), q.resolve seems to be synchronous as with the rest of the stack. So the callbacks seems to be registered at the same time as other framework, on `deviceready`.

Is there a difference between  `document.addEventListener("deviceready",...)` and `channel.deviceready.subscribe(...)`

**Comment by kristianbenoit** [comment]
@stefanmdt you can use my repo for now https://github.com/kristianbenoit/cordova-plugin-local-notifications. It's based on 0.7.8 with a few fixes.

**Comment by stefanmdt** [comment]
Thx for the link. Do you know how the problem is handled in the cordova push notification plugin? I use them both in the same project and in case of the push plugin, I register my event handler somewhere deep down in the code and it gets fired anyway.

**Comment by katzer** [comment]
@kristianbenoit

> Is there a difference between document.addEventListener("deviceready",...) and channel.deviceready.subscribe(...)

Yes, listener registered via `channel.deviceready.subscribe()` will be called after _deviceready_ event. It's a after-deviceready event used by cordova-core and plugins.

**Comment by kristianbenoit** [comment]
@stephanmdt. I'm not using it, but it make sens to wait until the app register its first callback then call `deviceready` in a timeout.

That sounds like a nice way to handle this.  Instead of having one queue for all events. There could be one queue per event and release the queue once the application has registered a handler for that particular event. This way there is no change in the api and its guaranteed to deliver the events to the app callbacks.

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by katzer** [comment]
I think the current solution works well because the click event on startup will be called after all deviceready callbacks were fired.

**Comment by jwlyan** [comment]
I don't know why but in my case, it is not being fired after, and the click event is not working. Can you guys please help me how to fix it? Thanks.

**Comment by seekchange** [comment]
same here. have not been able to get .on("trigger") or .on("click") to do anything. i'm guess most people are not having this issue.
