### ISSUE TITLE
Know when the plugin as processed all events that happend prior to deviceready

### ISSUE THREAD

**Issue by kristianbenoit** [katzer/cordova-plugin-local-notifications#434]
The plugin cache the events that happend before device is ready and sends them all when it receive `deviceready`. When a user click on a notification we might want to know if the application is started from a notification or somewhere else. For this we might need to wait until all events has been sent from native to JS and check if we received onclick.

For this we can add an event after all startup events are processed (afterdeviceready).

What do you think ?

**Comment by katzer** [comment]
that special click event will be sent to JS after all deviceready callbacks were fired.
