### ISSUE TITLE
Issue about multiple notification in iOS 8.1 in iPhone 

### ISSUE THREAD

**Issue by hkcity1111** [katzer/cordova-plugin-local-notifications#436]
Hi all

I am new in notification plugin and phonegap development. I find the strange things in multiple notification. 
If I execute the following 6 notifications in iPhone , it will create 3 notification message (which is title 4, title 5, title 6 shown in notification center) instead of  6 notification message shown.
After I click "title 6" in notification center,  other notification message of title 1 , title 2, title 3 are added back into notification center. 
This effect are the same in iPhone 5 real device and iPhone 5 simulator but not in iPad and iPad simulator. 
Is there any constraint in this case?
Thanks a lot!

```
    window.plugin.notification.local.schedule( [
        {
            id:     1, 
            title:   "This is Title 1",
            text: " This is text field 1",
            data: JSON.stringify({
                notificationID: "id-10-122a"
            })
        },
        {
            id:     2, 
            title:   "This is Title 2",
            text: " This is text field 2",
            data: JSON.stringify({
                notificationID: "id-10-122b"
            })
        },
        {
            id:     3, 
            title:   "This is Title 3",
            text: " This is text field 3",
            data: JSON.stringify({
                notificationID: "id-10-122c"
            })
        },
        {
            id:     4, 
            title:   "This is Title 4",
            text: " This is text field 4",
            data: JSON.stringify({
                notificationID: "id-10-122d"
            })
        },
         {
            id:     5, 
            title:   "This is Title 5",
            text: " This is text field 5",
         data: JSON.stringify({
         notificationID: "id-10-122e"
         })
         },
         {
            id:     6, 
            title:   "This is Title 6",
            text: " This is text field 6",
         data: JSON.stringify({
         notificationID: "id-10-122bf"
         })
         }]

    );
```

**Comment by katzer** [comment]
@hkcity1111, the notification center on iOS does not display all notifications. The count is limited. I think the max is 5 per app.

**Comment by hkcity1111** [comment]
@katzer , but I set max is 10 per app but such problem exist.
I think the plugin work perfect and I guess it is iOS issue.
