### ISSUE TITLE
[WP8] Notification is not dismissed after click.

### ISSUE THREAD

**Issue by sjvisschers** [katzer/cordova-plugin-local-notifications#437]
When I click on a notification in iOS or Android, my app opens and the notification is removed from the notification center (not from the queue, just from the center).

But when I try this on WP8 the message stays on the Live Tile. How can I remove a (repeating) notification from the Live Tile, without removing it from the queue?

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!
