### ISSUE TITLE
Notification "click" event crashes the app if app is closed via navigator.app.exitApp()

### ISSUE THREAD

**Issue by gkamenov** [katzer/cordova-plugin-local-notifications#438]
Hi, 
I'm experiencing the following issue with the plugin: When notification is clicked by the user, if app is on foreground or is in background (by pressing "home" button) the "click" event is delivered as expected.
If application is "closed" via navigator.app.exitApp() or by pressing back button (back button event not attached in app), when notification is clicked, the app is started and then crashes into event handler:

                window.plugin.notification.local.on('click', function (id, state, json) {
                    alert('clicked');
               });

If app is manually removed from "recent apps" after being "closed" and prior clicking the notification, then everything works as expected.

It seems the crash is related to cordova's implementation of 'alert' call, and is related to the way how the plugin launches closed activity which is still in "recent app list"

Here is the log:
W/System.err( 3635): android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@b1ff40d8 is not valid; is your activity running?
W/System.err( 3635): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:536)
W/System.err( 3635): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
W/System.err( 3635): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
W/System.err( 3635): 	at android.app.Dialog.show(Dialog.java:286)
W/System.err( 3635): 	at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
W/System.err( 3635): 	at org.apache.cordova.CordovaChromeClient.onJsAlert(CordovaChromeClient.java:126)
W/System.err( 3635): 	at com.android.webview.chromium.WebViewContentsClientAdapter.handleJsAlert(WebViewContentsClientAdapter.java:606)
W/System.err( 3635): 	at com.android.org.chromium.android_webview.AwContentsClientBridge.handleJsAlert(AwContentsClientBridge.java:73)
W/System.err( 3635): 	at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err( 3635): 	at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:27)
W/System.err( 3635): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 3635): 	at android.os.Looper.loop(Looper.java:136)
W/System.err( 3635): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
W/System.err( 3635): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 3635): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 3635): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/System.err( 3635): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/System.err( 3635): 	at dalvik.system.NativeStart.main(Native Method)
F/libc    ( 3635): Fatal signal 6 (SIGABRT) at 0x00000e33 (code=-6), thread 3635 (com.gigs42.orch)
W/WindowManager( 1190): Attempted to add application window with unknown token Token{b2186150 ActivityRecord{b22237a0 u0 com.gigs42.orch/._42Orch t53 f}}.  Aborting.

**Comment by katzer** [comment]
Does this help?
```javascript
window.plugin.notification.local.on('click', function (notification, state) {
    setTimeout("alert('clicked')", 0);
});
```

**Comment by gkamenov** [comment]
No it doesn't help.

**Comment by gkamenov** [comment]
It is works now! I upgraded to cordova from 4.2.0 to 4.3.0 and downgraded org.apache.cordova.device 0.3.1-dev to 0.3.0

**Comment by gkamenov** [comment]
Thanks!
