### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by misabitencourt** [katzer/cordova-plugin-local-notifications#440]
Hi, that error appears when i try to build an android debug apk.

Any ideias to solve it?

______________________________________________________________________________
______________________________________________________________________________

-pre-compile:
     [echo] Set jars path to: D:\nodejs\LocalizaBike\platforms\android\CordovaLib\ant-build\classes.jar;D:\nodejs\LocalizaBike\platforms\android\libs\android-support-v4.jar

-compile:
    [javac] Compiling 22 source files to D:\nodejs\LocalizaBike\platforms\android\bin\classes
    [javac] D:\nodejs\LocalizaBike\platforms\android\src\de\appplant\cordova\plugin\localnotification\LocalNotification.java:64: error: method does not override or implement a method from a
supertype
    [javac]     @Override
    [javac]     ^
    [javac] 1 error

BUILD FAILED
D:\program_files\adt-bundle-windows-x86_64-20140702\sdk\tools\ant\build.xml:720: The following error occurred while executing this line:
D:\program_files\adt-bundle-windows-x86_64-20140702\sdk\tools\ant\build.xml:734: Compile failed; see the compiler error output for details.

______________________________________________________________________________
______________________________________________________________________________

Cordova: 3.5.0-0.2.6

**Comment by katzer** [comment]
OK, the method is first available with Android platform v3.6.0. Will change that incompatibility. If there is no reason you can also upgrade to 3.6.0 or newer.

**Comment by katzer** [comment]
[Fixed](744b513c79216a5565e6f8136b50fe8f2432fe23)
