### ISSUE TITLE
what's wrong with the "winphone" platform

### ISSUE THREAD

**Issue by bau720123** [katzer/cordova-plugin-local-notifications#441]
hi @katzer 
according to these

in 0.7.8 verison
https://build.phonegap.com/plugins/2057
http://plugins.cordova.io/#/package/de.appplant.cordova.plugin.local-notification
them are supported by Android，iOS and winphone

but in 0.8.0 version
https://build.phonegap.com/plugins/2058
http://plugins.cordova.io/#/package/de.appplant.cordova.plugin.local-notification
them seem only supported by Android，iOS

anything change ? winphone not support anymore when start at 0.8.0 ?

**Comment by bau720123** [comment]
hi @katzer 
I saw a new version 0.8.1
https://build.phonegap.com/plugins/2081
http://plugins.cordova.io/#/package/de.appplant.cordova.plugin.local-notification

but still can't see the winphone support
winphone not support anymore when start at 0.8.0 ?

**Comment by katzer** [comment]
hi @bau720123, the windows platform will be added as next and the WP8 platform has been removed.

**Comment by bau720123** [comment]
hi @katzer 
thanks for your reply
how sad that hear WP8 forever removed in the future (any reason or ... ?)

There is a suggestion
Maybe you can do the two versions coexist
I mean is...
[for example]
"de.appplant.cordova.plugin.local-notification" => android, ios, wp8 (old version)
"de.appplant.cordova.plugin.local-notification_new" => android, ios (new version)

anyway...thanks a lot your plugin ~

**Comment by katzer** [comment]
hi @bau720123,
the cordova windows platform includes Windows 8.1 and Windows Phone 8.1. Means v0.8 will add support for WP 8.1. But WP 8.0 has been removed.

**Comment by katzer** [comment]
You may also see here: https://github.com/katzer/cordova-plugin-local-notifications#i-would-like-to-propose-new-features

**Comment by bau720123** [comment]
hi @katzer 
really thanks
fully understand what you mean
WP 8.0 is too old
just removed it....
GOOD JOB !!!

**Comment by katzer** [comment]
@bau720123, if you are interested please vote for that cordova-windows issue!
https://issues.apache.org/jira/browse/CB-8674

**Comment by bau720123** [comment]
hi @katzer 
vote already
