### ISSUE TITLE
A plugin in your app does not support the compulsory arm64 (64-bit support) architecture

### ISSUE THREAD

**Issue by bau720123** [katzer/cordova-plugin-local-notifications#442]
hi @katzer 
when I am using PGB 3.7 and add your plugin "local-notifications" (0.8.0 version，source="plugins.cordova.io")
only ios will build fail and said...

Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture. - You can fix this here

but if I change back to 0.7.8 version，ios build success...

**Comment by katzer** [comment]
hi @bau720123, you can ask their support whats the concrete reason and let me know about their answer.

The plugin only contains source code and I can build and run it with arm64.

**Comment by bau720123** [comment]
hi @katzer 
thanks for your reply
I have been left some message at here
http://community.phonegap.com/nitobi/topics/a-plugin-in-your-app-does-not-support-the-compulsory-arm64-64-bit-support-architecture

waitting for PGB's answer...

**Comment by bau720123** [comment]
hi @katzer 
just send some feedback
I saw a new version 0.8.1
https://build.phonegap.com/plugins/2081
http://plugins.cordova.io/#/package/de.appplant.cordova.plugin.local-notification

but still occur arm64 (64-bit support) problem
Keep tracking

**Comment by bau720123** [comment]
hi @katzer 
I finally know what the problem is !! (discover by myself)

if you use these in PGB ...
```
<gap:plugin name="de.appplant.cordova.plugin.badge" version="0.6.2" source="plugins.cordova.io" />
<gap:plugin name="de.appplant.cordova.plugin.local-notification" version="0.7.8" source="plugins.cordova.io" />
```
OR
```
<gap:plugin name="de.appplant.cordova.plugin.local-notification" version="0.8.1" source="plugins.cordova.io" />
```
the ios will build success !!!

but...if you use these
```
<gap:plugin name="de.appplant.cordova.plugin.badge" version="0.6.2" source="plugins.cordova.io" />
<gap:plugin name="de.appplant.cordova.plugin.local-notification" version="0.8.1" source="plugins.cordova.io" />
```
well..the ios will build fail (64-bit support problem) 

[The Conclusion is]
one of the plugin use the "new method" (I guess is local-notification)
but the old one still use the "old method" (I guess is badge)
and maybe the two plugin have use Some kind of "common function"
so...will cause another have the 64 bit issue

**Comment by katzer** [comment]
hi @bau720123, badge 0.6.2 and local-notification 0.8.x had incompatibilities and could not be used in combination (but has nothing to do with 64-bit...)

Anyway that has been fixed with badge 0.6.3 and local-notification 0.8.2dev

**Comment by bau720123** [comment]
got it
thanks @katzer

**Comment by bau720123** [comment]
hi @katzer 
for now I just (only) use badge 0.6.3 version in PGB 3.7 but build fail in iOS
this is the log information...
you can search the "badge" keyword to find the issue
http://www.littlebau.com/badge_log.txt

**Comment by katzer** [comment]
hi @bau720123,

I am uninstalling/installing the plugin and the app builds fine. Looks more like PGB ignores the hook scripts!

**Comment by bau720123** [comment]
hi @katzer 
I have been made a question to PGB
http://community.phonegap.com/nitobi/topics/-hook-scripts-problem
to see if there is any reply
