### ISSUE TITLE
Question: clearing the badge

### ISSUE THREAD

**Issue by sgentile** [katzer/cordova-plugin-local-notifications#443]
I'm using the latest 080 version and updating my code base with it.

I'm using scheduled notifications.

When the app loads, or when someone clicks on a notification, I want to clear the icon badge.

I'm not clear on what I can call to clear it ?

Thank you!

**Comment by sgentile** [comment]
I found the answer - 'clear' - I recall previously there was a property on the notification to clear when it was selected - now I need to clear it myself (ie. when app loads, or when notification is clicked).   I am seeing that clear by id isn't clearing the badge, but clearAll does.

**Comment by katzer** [comment]
@sgentile, for enhanced badge functions see the [badge plugin](https://github.com/katzer/cordova-plugin-badge).
