### ISSUE TITLE
[iOS 8] sound is not playing when notification is triggered

### ISSUE THREAD

**Issue by milica** [katzer/cordova-plugin-local-notifications#444]
Hi there!

I just upgraded to 0.8, but now have problem with sound. So, the old way was working, I was setting sound to **www/sound/some-sound.caf**, but it just don't want to play it. Am I missing something? I included all my sound files in **Copy Bundle Resources**, but still not working...
Heeelp?

**Comment by milica** [comment]
So, now I put it to be **file://sound/some-sound.caf**, and sometimes it plays and sometimes not, I can't get it why is it random like this? This was also issue with previous version so I updated just to see if it's going to fix this behaviour...

**Comment by katzer** [comment]
iOS will play the sound only if the app is in background or not running - but not in foreground

**Comment by milica** [comment]
Yes, I know that. So, I have couple of sounds that are randomly picked for the notification, and in the end I realised that couple of them are more then 30s or exactly 30s, and it looks like those won't play. Didn't know that, I thought that it would play until 30th second and quit it.
