### ISSUE TITLE
Click event remove all other notifications 

### ISSUE THREAD

**Issue by sannysinghs** [katzer/cordova-plugin-local-notifications#445]
I had followed the code show in example file . But when i try to implement this , i have got some strange error.According to example , i put 3 different notifications with diff ids . The thing is when i click one , it remove other two notifications and show something like this in console 

         [Object, "background"]

Object => contain noti id of the one who has been triggered and other data from server
Pls kindly have a look my gist file https://gist.github.com/sannysinghs/c26dd2500040d15c311f
Thanks

**Comment by scravy** [comment]
Could you please State what the expected behaviour is and what happens instead? The way it is your "issue" does not make any sense to me and should be better raised as a question on stackoverflow.

**Comment by sannysinghs** [comment]
Hi Scravy , it seem like the question was not obvious what i want to state here . I think it would b better if i show you the code . 
below code was inserted in onNotificationGCM

**Comment by katzer** [comment]
What platform? I know that iOS has some issues when scheduling multiple one at same time.
