### ISSUE TITLE
no returned information from querying notifications

### ISSUE THREAD

**Issue by neil-rowe** [katzer/cordova-plugin-local-notifications#447]
i cannot seem to get the "get" function to work. I have tried a lot of variations to no avail.

once i schedule a notification with id of 3 or '3' i try to check it with this

	cordova.plugins.notification.local.get('3', function (notification) {
	  alert(notification.text);
	});
	cordova.plugins.notification.local.get(3, function (notification) {
	  alert(notification.text); 
	});

..using this to fire on a button click. it just returns undefined for both. 
..any ideas? Ultimately I'm trying to just get the date for any scheduled notifications and then update some dom time inputs with the times from the scheduled notifications, but i can't seem to pull any info from the scheduled ones to do so. I've looked at the sample app and this looks to be correct for pulling info from a notification.

**Comment by katzer** [comment]
Hi @neil-rowe, please take a look into the index.html from the kitchen sink sample app. There is an example.

That should work for example:
```javascript
var callback = function () {
    cordova.plugins.notification.local.get(3, function (notification) {
        alert(notification.text); 
    });
}

cordova.plugins.notification.local.schedule({
    id: 3,
    text: '...'
}, callback)
``` 


please note that all methods work asynchron

**Comment by neil-rowe** [comment]
does this have to be run at the time of the scheduling to pass the notification through to the get function?

I am looking for a way to pull information about the currently scheduled notifications long after they have been scheduled but before they are fired.   if i successfully schedule a notification with the id of 1, and then later run 

cordova.plugins.notification.local.get(1, function (notification) {
        alert(notification.text); 
    });

off a click event, i do not get any alert.  also for some reason all of the event listeners have stopped working. this includes the kitchen sink app. i can schedule notifications, but get no fired events from the listeners.. even in the stock kitchen sink app using Xcode deployment target IOs 8.1 on iPhone 6. i wonder if the two are related?

**Comment by neil-rowe** [comment]
running the exact above code to set and then get the notification id  3 in the simulator also returns 'undefined'

**Comment by neil-rowe** [comment]
..also on live phone iOS 8.1.3. returns undefined.

**Comment by neil-rowe** [comment]
..although the event listeners do seem to be working now.. lame cache ;/

**Comment by neil-rowe** [comment]
Ok, so I've debugged a bit and am using the kitchen sink app , and the methods are all working it seems, but I'm still left wondering how to retrieve data from the scheduled notifications using the get method, if i run it as you've listed it returns undefined. but if i just alert the notification it returns [object Object] .. so it seems that there is data being returned. The question is how do we actually  dig into the object to return any given notification data such as the id, date, text?

id like to be able to display for the user what time a notification is scheduled at after the fact.
the kitchen sink app returns ids via the getid methods, but i can't find a working example of returning other data  from the scheduled notification.

**Comment by neil-rowe** [comment]
Ok aftr digging deeper it looks like the "get" method is being passed through the "getall" method which returns and array. thus the object Object being returned. 

so if your doing a "get" on a single scheduled notification you can just grab index 0 of the returned array. This code works to return notification data. 

var callback = function () {
    cordova.plugins.notification.local.get(3, function (notification) {
        alert(notification[0].text);  //<-just accessing the 0 index of the array here was all it took :)
        alert(notification[0].title);
    });
}

cordova.plugins.notification.local.schedule({
    id: 3,
    text: '...'
}, callback)


the example app could possibly be updated to pull some given data such as the text to give better direction maybe?

anyway.. awesome plugin, and thanks again for all your work on it !!

**Comment by katzer** [comment]
hi @neil-rowe, the `get` method should not respond with an array if a single notification was requested - should work in the way as described in the wiki. Will be fixed in next version.
