### ISSUE TITLE
notifications update function has problem.

### ISSUE THREAD

**Issue by tsecheng** [katzer/cordova-plugin-local-notifications#449]
i am using 0.8.1, android kitkat 4.4.2

cordova.plugins.notification.local.schedule({
id:"1",
title:'title...ggg',
text: 'Test Message 1',
at: later,
every:1
});

cordova.plugins.notification.local.on('trigger', function (notification) {
	cordova.plugins.notification.local.update({
	    id: notification.id,
	    title: "New Title..",
	    text:"New Text...",
	    badge:10,
	    ongoing:false
	});
});

if i don't use update function , every this is fine, when i use update function to update notification, sound don't play and notification disappear immediately.

**Comment by ahetawal** [comment]
Were you able to resolve this. I am seeing the same issue. I am using a dynamic function to update the text on trigger. 

cordova.plugins.notification.local.on('trigger', function (notification) {
cordova.plugins.notification.local.update({
id: notification.id,
title: getNewTitile(),
text:"New Text...",

});
});

But the title never gets updated if i use the function, a static string works fine. Any ideas?

**Comment by katzer** [comment]
I tried and could update both title and text.
