### ISSUE TITLE
What will happen to the scheduled local notifications after updating the app from google play store

### ISSUE THREAD

**Issue by sh30** [katzer/cordova-plugin-local-notifications#450]
Let's suppose the current time is 1 PM and we have a local notification scheduled to be executed at 5PM.

If a new version of the app is available in google play store and the phone installed it automatically, (means replaced the receiver java file of the plugin), what will happen to the scheduled local notification in this case? will it be lost?

Will the plugin give order to the operating system to execute the local notification at 5PM and the system is responsible to do it regardless of the plugin presence at 5PM, or maybe the plugin will wait until 5PM to send its order to the operating system? if the last case then this means the local notification will not be executed after the app update, am i right? 

Kindly clarify this point.

Thanks

Update: I've tried to install another apk and the local notification still firing but the thing is after update it is not possible to cancel the existing notifications although maybe the plugin cannot control the ID of notification after updating the app. I'm using version 0.7.8 of the plugin.

**Comment by sh30** [comment]
Update: I've tried to install another apk and the local notification still firing but the thing is after update it is not possible to cancel the existing notifications although maybe the plugin cannot control the ID of notification after updating the app.

**Comment by katzer** [comment]
@sh30, this is a good point what you are describing.
The plugin gives order to the OS to execute the notification. They will not be lost after update!
But I will try out what will happen on Android if broadcast receiver classes from 0.7 do not exist anymore after update to 0.8
