### ISSUE TITLE
what things happen when notification is click

### ISSUE THREAD

**Issue by sannysinghs** [katzer/cordova-plugin-local-notifications#454]
I can not really figure it out what was going on when i click on notification.To my understanding , it should enter to on click listener and remove this notification from status bar .

**Comment by katzer** [comment]
yes, thats exactly the behavior.

**Comment by sannysinghs** [comment]
Thanks for reply . To my surprised , when i click one notification , it remove all older notification . I downloaded the example app and it works fine . But i am using ngCordova push plugin which listen onclick event on $rootScope. I thoguht it might be some problem with that or any idea why it is happening ?

**Comment by katzer** [comment]
All notifications have an unique ID?

**Comment by sannysinghs** [comment]
YES . I've different ID for each notification. I also try with setting static key like "1,2,3" for three notifications.I don't know what's wrong . Please have a look my current code 

             cordova.plugins.notification.local.schedule({
                    id: notification.payload.notId,
                    title: notification.payload.title,
                    text: notification.payload.message,
                    data: { msgtype:notification.payload.msgtype },
                    badge : 1,
                    icon: "file://res/drawable/icon.png",
                    smallIcon : "file://res/drawable/icon.png"
                });

                cordova.plugins.notification.local.on("click", function (notification, state) {
                    var data = JSON.parse(notification.data);
                    console.info(data);
                    $state.go('menu.tab.event-detail',{'id' : notification.id , 'msgtype' : data.msgtype });
                }, this);

**Comment by katzer** [comment]
@sannysinghs, have you found out the reason? Local- and Push-Notifications have other OS callbacks. I think they do not influence each other. From code I cannot see any reason.

BTW if your data is only a string you can simple assign that string directly.
