### ISSUE TITLE
iOS | Error while using number in 'every' property in schedule()

### ISSUE THREAD

**Issue by BerendWeij** [katzer/cordova-plugin-local-notifications#455]
The property 'every' can be uses as a number (interval in minutes) or a string (minute, hour, etc.).
But if I use it as a Number, I am getting an error with function stringIsNullOrEmpty since this function is expecting a string.
How can I solve this issue?

**Comment by katzer** [comment]
hi @BerendWeij, custom number intervals are only supported on Android. Will update the wiki to make that clear.

**Comment by BerendWeij** [comment]
Ok. That's a pity. Thank you for the quick reply.
Cheers.
