### ISSUE TITLE
Notification trigger again after phone restart

### ISSUE THREAD

**Issue by sparkcoding** [katzer/cordova-plugin-local-notifications#457]
Don't know why, but if I click notification (don't pull left) and app starts, then closing app and restart phone, notification shows again. But when I pull notification left its doesn't happens. When app is closed and I click on notification, the event "click" don't fire.

Sorry my english.

**Comment by quelo83** [comment]
Same problem here. When the app is running or in background everything works as expected, but when it's closed the "click" event doesn't fire. I've also experienced the repeated notifications on device reboot.

**Comment by bau720123** [comment]
hi @katzer @sparkcoding @quelo83 
I have the same problem
I am using PGB 3.7 with latest plugin 0.8.1
but it don't need any reboot

[Fist time]
I use the "schedule" method
of course it will trigger the "click" event and "trigger" event that only one time
https://github.com/katzer/cordova-plugin-local-notifications/wiki/11.-Samples

[Second time]
I use the "schedule" method again
but this time it will trigger the "click" event and "trigger" event that twice time

x->1
x->2
x->3
x->...

**Comment by katzer** [comment]
please explain again, when does it happen?
You schedule same notification twice and all callbacks will be called twice?

What OS? Android?

**Comment by bau720123** [comment]
hi @katzer 
yes...in iOS 8.2 and Android 4.4.3 have this situation
first time，it only trigger one time 
second time，it will trigger twice times
....etc

**Comment by katzer** [comment]
@bau720123, I think your code registers a click listener within the click callback!

**Comment by katzer** [comment]
@sparkcoding, @quelo83, cannot reproduce - the click callback gets invoked each time

**Comment by bau720123** [comment]
hi @katzer ，thanks for your help...I really did a big wrong (listener within the click callback)，please forgive me
