### ISSUE TITLE
Error in file 

### ISSUE THREAD

**Issue by montaserfzy** [katzer/cordova-plugin-local-notifications#458]
The plugin not working and the error appearing in the AppLocalNotification.m file 
![screen shot 2015-03-15 at 4 23 05 pm](https://cloud.githubusercontent.com/assets/8565425/6656356/3ff77e22-cb30-11e4-8b0d-60b774ec7fc7.png)

**Comment by katzer** [comment]
Is that gone? Maybe a quick cleanup will help. The error from xcode makes no sense.
