### ISSUE TITLE
Android Studio compliance ?

### ISSUE THREAD

**Issue by alxpereira** [katzer/cordova-plugin-local-notifications#460]
We have some errors with the latest SDK and using Android Studio.

plugin/localnotification/LocalNotification.java:495: error: cannot find symbol
webView.evaluateJavascript(js, null);

plugin/localnotification/LocalNotification.java:492: error: cannot find symbol
webView.post(new Runnable(){

Might be cool to fix that.
Alex

**Comment by katzer** [comment]
what SDK version do you use?

**Comment by ReneMoraales** [comment]
Same here with SDK 21.

**Comment by machei** [comment]
+1 same here

```
    <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="19" />
```

**Comment by machei** [comment]
Another error after untagged function deviceready(here no need callback finish, but every 1s i can check object if is not null): 

```
:preDexX86Debug
:dexX86Debug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/app/NotificationCompat$Action;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)

:dexX86Debug FAILED
```

**Comment by machei** [comment]
Found answer for it:

- remove plugin/localnotification/LocalNotification.java:492
- remove platforms/android/libs/*/android-support-v4.jar

Add build-extras.gradle
```
dependencies {
    compile 'com.android.support:support-v4:21.0.0'
    compile 'com.android.support:appcompat-v7:21.0.0'
}

configurations {
    all*.exclude group: 'com.android.support', module: 'support-v4'
}
```

**Comment by katzer** [comment]
Yes the plugin isn’t crosswalk compatible yet

**Comment by lucaele** [comment]
i've the same problem. 
Which row i will remove in LocalNotification.java?
My row n° 492 is:
webView.post(new Runnable() {...

When will be available this plugin crosswalk?
Thanks,
Luca

**Comment by machei** [comment]
lucaele, u can do it manually.

**Comment by lucaele** [comment]
Sorry Machei, my error have different row number from your.
For ex you have readSortableTypes(DexMerger.java:596) and i have readSortableTypes(DexMerger.java:594).

So, i must delete deviceready/webview.post?

**Comment by machei** [comment]
I think u have wrong configuration with gradle (u are missing library com.android.support-v4)

Just create new file build-extras.gradle and place it to folder platforms/android.

Or if u are still on ANT (not gradle), u have to must convert build system to gradle.

**Comment by miraculixx** [comment]
@machel Thanks for your solution. I was able to get this fixed using a build [hook](https://github.com/apache/cordova-app-hello-world/blob/master/hooks/README.md):

```
#!/bin/bash
# hooks/before_build/fix_android-local-notifications.sh

if [[ ! "$CORDOVA_PLATFORMS" == "android" ]]; then
  # only needed on android builds
  exit 0
fi

GRADLE_EXTRAS="./platforms/android/build-extras.gradle"
FIX_URL="https://github.com/katzer/cordova-plugin-local-notifications/issues/460" 

echo "Applying fix for issue $FIX_URL"

JAR="platforms/android/libs/android-support-v4.jar"
if [ -f "$JAR" ]; then 
	echo "Removing $JAR"
	rm $JAR
fi

echo "creating $GRADLE_EXTRAS"
cat << EOF > $GRADLE_EXTRAS
dependencies {
    compile 'com.android.support:support-v4:21.0.0'
}
configurations {
    all*.exclude group: 'com.android.support', module: 'support-v4'
}
EOF
``` 

versions:

```
phonegap 4.2.0-0.26.0
cordova 4.2.0
platform android@4.0.0
cordova-plugin-local-notification#0.8.1 + PR #532
```

**Comment by dam1** [comment]
Thanks @machei !

**Comment by arbes** [comment]
@machei I applied your fix. Now I have the problem, that as soon as the app reaches the schedule-statement, it crashes. Do you have any idea what the problem could be?

**Comment by katzer** [comment]
That has been fixed already!
