### ISSUE TITLE
schedule() is not working in ionic project for version 0.8.1

### ISSUE THREAD

**Issue by tonychunwei** [katzer/cordova-plugin-local-notifications#462]
I am trying to upgrade to v0.8.1 in an ionic project, and test on real device (Android Nexus 5)  Looks like hasPermission() is working, since I got alert. but I didn't get notification. Don't know if I miss anything :/ Any ideas? Thanks lot!

```javascript
   $ionicPlatform.ready(function() {
      cordova.plugins.notification.local.hasPermission(function (granted) {
        if (granted === true) {
          var alarmTime = new Date();
          alarmTime.setSeconds(alarmTime.getSeconds() + 5);
          alert(alarmTime);
          cordova.plugins.notification.local.schedule({ title:"Hello World", firstAt:alarmTime});
        } 
      });
    });
```

**Comment by devup-sam** [comment]
you could register for the following event to see if it's getting registered, or something about it means it's not getting that far. Perhaps if you use "firstAt", rather than "at" you need a "repeat" value.

cordova.plugins.notification.local.on('schedule', function (notification) { alert(notification.title); });

And if you're only scheduling 5 seconds in the future you might want to put your alert(alarmTime); after the .schedule :)

**Comment by skoschik** [comment]
I'm having the same issue with 0.8.1 but I'm coming from 0.7.  The .on('schedule') event you suggested is getting called but no notification is added/scheduled.  Logcat doesn't seem to reveal any clues.  Any other thoughts on how to debug/resolve?

**Comment by luishomero** [comment]
Hi, I am trying to use the plugin version 0.8.1 I am not able to get any notifications triggered. I also registered schedule event but it is also not triggered.
Here are the lines I am using to test in android phone.

document.addEventListener("deviceready",onDeviceReady,false);
function onDeviceReady () {
 cordova.plugins.notification.local.schedule({
        id:1,
        title:'test',
        text:'message'
       });

cordova.plugins.notification.local.on("schedule", function(notification) {
          alert("scheduled: " + notification.id);
        });  
}

Am I missing something?

**Comment by devup-sam** [comment]
All I can say is that it does work for me, on a number of devices. I use
the Intel XDK to compile my APKs.

I schedule tests, using moment.js, with the date as moment().add(30,
'seconds').toDate(). You run into all sorts of problems if the ID isn't
unique, and a valid Java Integer though.

Perhaps you have a timing issue.  Maybe try postponing the scheduling with
a setTimeout of 5000 or something.

Regards,

Sam.

Dev Up Limited

**Comment by katzer** [comment]
@devup-sam, great to hear that the plugin does work with ionic and intel xdk.

BTW `firstAt` is just an alias for `at`.

**Comment by luishomero** [comment]
Hi, thanks for the reply, actually my issue was that I was using cordova
version 3.5, the build didn't have any error however I think some of the
classes might not get compile, making the plugin to not work. I update to
cordova 4.x and now I am seeing the notifications again.

**Comment by ttariq7** [comment]
$ionicPlatform.ready(function() {

		$timeout(function(){

		cordova.plugins.notification.local.cancelAll(function() {

			cordova.plugins.notification.local.schedule({
			    id: 0,
			    firstAt: new Date(today0),
			    title: "Today 0"
			});
			cordova.plugins.notification.local.schedule({
			    id: 1,
			    at: new Date(today1),
			    title: "Today 1"
			});
			cordova.plugins.notification.local.schedule({
			    id: 2,
			    at: new Date(today2),
			    title: "Today 2"
			});
			cordova.plugins.notification.local.schedule({
			    id: 3,
			    firstAt: new Date(today3),
			    title: "Today 3"
			});
			cordova.plugins.notification.local.schedule({
			    id: 4,
			    at: new Date(today4),
			    title: "Today 4"
			});	

		});

		$timeout(function(){
			cordova.plugins.notification.local.getAll(function (notifications) {
				console.log(notifications)
			});
		},5000)

	},15000)

	})


Even with the timeout this only schedules the last notification with id 4 the other 3 are ignored for some reason. Does anyone know the reason? My notifications were working before on 0.7.8 but I accidentally updated to 0.8.1 and now cannot get them to work again. Is there a way I can download and use version 0.7.8 again?  

Thank you

**Comment by jimibi** [comment]
I haven't test your snippet but if you want return to an old version use this:

cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.7.8

**Comment by Tawpie** [comment]
@ttariq7: put your notifications into an array and then call schedule() one time with the array. That works well.

**Comment by ttariq7** [comment]
@Tawpie  thanks tried but, that doesn't work either. 

@jimibi  Thank you I tried that but getting the following error


'''
$ cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.7.8
Fetching plugin "https://github.com/katzer/cordova-plugin-local-notifications" via git clone
Repository "https://github.com/katzer/cordova-plugin-local-notifications" checked out to git ref "0.7.8".
Installing "de.appplant.cordova.plugin.local-notification" for ios
Fetching plugin "https://github.com/apache/cordova-plugin-device" via git clone
Failed to install 'de.appplant.cordova.plugin.local-notification':Error: Expected fetched plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".
'''

**Comment by karvapallo** [comment]
Yeah I just tried to run the newest version, which didn't compile for iOS and then tried version 0.7.8 and got the same error as @ttariq7
