### ISSUE TITLE
IOS xcode 6 receiving the AppDelegate.h file not found

### ISSUE THREAD

**Issue by arickatz** [katzer/cordova-plugin-local-notifications#464]
I have imported a project based on the phonegap template to xcode
and when I add the new plugin with all of its files I am receiving the:
AppDelegate.h file not found, any ideas why?

**Comment by katzer** [comment]
ok, have you found out? Each iOS App does have a AppDelegate.h file

**Comment by arickatz** [comment]
I kind of realized it, yet I am using the appery.io hybrid mobile platform and imported
my project to xcode. The project compiled and worked with the old plugin (07).
As it seems there is no AppDelegate.h file in that project I tried searching for it in xcode and
directly through the file system but no AppDelegate.h file was found. any ideas why or where can that file be located? is there any way to run with the new plugin without referencing the AppDelegate. h file?

**Comment by arickatz** [comment]
I talked with the appery team and they told me that they renamed the file to ApplicationDelegate.h
I will check it
