### ISSUE TITLE
Plugin dependences Conflict 

### ISSUE THREAD

**Issue by alyeldegwy** [katzer/cordova-plugin-local-notifications#467]
When adding this plugin to my project i found this problem 

[dependency] ------------------
[dependency] Found 2 versions of android-support-v4.jar in the dependency list,

BUILD FAILED[dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
/***************/android-sdk-linux/tools/ant/build.xml:577: Jar mismatch! Fix your dependencies

Total time: 2 seconds
[dependency] All versions of the libraries must be the same at this time.
[dependency] Versions found are:
[dependency] Path: /************************/platforms/android/com.phonegap.plugins.facebookconnect/RehabianzApp-FacebookLib/libs/android-support-v4.jar
[dependency] 	Length: 758727
[dependency] 	SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
[dependency] Path: /*********************/platforms/android/libs/android-support-v4.jar
[dependency] 	Length: 19036
[dependency] 	SHA-1: bc202617b4cfed6673b1e10d87e52c78f7a6de38
Command finished with error code 8: /******************/platforms/android/cordova/run 
ERROR running one or more of the platforms: Error: /******************/platforms/android/cordova/run: Command failed with exit code 8
You may not have the required environment or OS to run this project

this is the plugin that it conflicts with: 
              com.phonegap.plugins.facebookconnect

**Comment by appastair** [comment]
https://github.com/katzer/cordova-plugin-local-notifications/blob/master/plugin.xml#L120

Manually removing `platforms/android/FacebookLib/libs/android-support-v4.jar` worked for me.

```
com.phonegap.plugins.facebookconnect 0.7.0 "Facebook Connect"
de.appplant.cordova.plugin.local-notification 0.8.1 "LocalNotification"
```

**Comment by k-cgomezh** [comment]
This issue happens to us and we can't manually remove any file because we are building with PGB. 
How to fix it ?

**Comment by appastair** [comment]
Don't use PGB
