### ISSUE TITLE
the "sound" attribute seem can't use the remote access

### ISSUE THREAD

**Issue by bau720123** [katzer/cordova-plugin-local-notifications#468]
hi @katzer 
the "sound" attribute seem can't use the remote access anymore (http://somedomain...)
but when in 0.7.8，it is really work

**Comment by bau720123** [comment]
hi @katzer 
anything unclear ?

**Comment by katzer** [comment]
[Fixed](901a844e37016a6f202ab7b8b840c6979c29cf6d)

**Comment by bau720123** [comment]
hi @katzer 
thanks
I will waiting the new version release

**Comment by bau720123** [comment]
hi @katzer 
about the "sound" attribute (a long time ago...)
is there any Plan to update a new version (the latest for now is 0.8.1)

**Comment by bau720123** [comment]
hi @katzer 
how soon will release a new version ?

**Comment by katzer** [comment]
@bau720123, I am busy... it takes time

**Comment by bau720123** [comment]
OKOK
thanks @katzer 
I will waitting
