### ISSUE TITLE
what the "firstAt" attribute true meaning

### ISSUE THREAD

**Issue by bau720123** [katzer/cordova-plugin-local-notifications#469]
according to this about "Schedule Delayed"
https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling
I can't figure out what the sample code true meaning
I guess...
this message will appear at every week's monday
right ?
so the "firstAt" attribute have other value ? (tuesday, wednesday, ....)

**Comment by katzer** [comment]
@bau720123,

>this message will appear at every week's monday

correct

`firstAt` is an alias for `at`. The value is a date object or a number

**Comment by bau720123** [comment]
git it
thanks @katzer

**Comment by bau720123** [comment]
hi @katzer 
if I change the code to...
```
cordova.plugins.notification.local.schedule({
    text: "Delayed Notification",
    firstAt: tuesday,
    every: "day",
    icon: "file://img/logo.png"
}, callback);
```

if it will change to tuesday ? etc ...

**Comment by bau720123** [comment]
hi @katzer 
anything unclear ?

**Comment by katzer** [comment]
yes, schedule daily beginning from Tuesday

**Comment by bau720123** [comment]
hi @katzer 
why this issue become reopen ?
is something wrong with the "firstAt" attribute ?

**Comment by bau720123** [comment]
hi @katzer 
any feedback ?

**Comment by katzer** [comment]
Maybe I pressed the wrong button...

**Comment by bau720123** [comment]
OKOK
thanks @katzer
