### ISSUE TITLE
is the "led" function support from all device ?

### ISSUE THREAD

**Issue by bau720123** [katzer/cordova-plugin-local-notifications#470]
according to this
https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling
just a question
is the "led" function support from all device ?
or...
what device can support the "hardware" function ?

**Comment by katzer** [comment]
led is Android & device specific

**Comment by bau720123** [comment]
git it
thanks @katzer

**Comment by bau720123** [comment]
hi @katzer 
just want to ask...
can you Point out some Android device that support the "led" function ?
