### ISSUE TITLE
Notifications schedule on iOS simulators but not on devices

### ISSUE THREAD

**Issue by runestonestudios** [katzer/cordova-plugin-local-notifications#471]
Hi we are using 0.8.1 version of the pugin. When trying to schedule the notification, they work on the simulator but not on the device. we re using the following code to schedule the notifications.
cordova.plugins.notification.local.schedule({
                    id: id,
                    title: "Title",
                    text: "Text",
                    data: data,
                    at: new Date()
                });

**Comment by frostney** [comment]
I'm having the same issue with the 0.8.1 and 0.8.0 version.

**Comment by runestonestudios** [comment]
@frostney Hey did you schedule it the same way we have as in the sample code above or did you use some other syntax?

**Comment by frostney** [comment]
I've used your example code and I've tried different notifications as well (without `data`, `text` and `id` properties).

I also had a change to test it on different devices and noticed something strange:
- iPad 3 (iOS 8.2) -> Notifications work
- iPad Air 2 (iOS 8.2) -> Once the notifications are shown, the app crashes

**Comment by katzer** [comment]
hi, do you have any error message? Have you checked the notification permissions?

**Comment by runestonestudios** [comment]
hi @katzer i dont get any error message, but when i install the app on the device for the first time, it asks for access to notifications, so it seems theres no problem with the permissions. and also the notifications on device worked with an older version of the plugin but it was delayed and random at times.

**Comment by cupcake0** [comment]
Similar problem here. v8.1 works on iPhone 6 (iOS 8.2) but not on iPhone 4S (iOS 8.4 and 7.1). Using v7.0 "works" on both but comes with another set of issues.

**Comment by katzer** [comment]
Cant reproduce the issue on real device. Please reopen if still and issue with latest version.
