### ISSUE TITLE
Find out wether registerPermission has ever been called?

### ISSUE THREAD

**Issue by deanpi** [katzer/cordova-plugin-local-notifications#472]
Is there a way to find out wether .registerPermission() has ever been called?

If I'm not mistaken .hasPermission() is false from the very beginning until .registerPermission() is called and granted, right? So I don't know wether I don't have the permission because the user has not granted it or because the user has never been asked.

What I want to do is to have a button "activate Notifications" that EITHER prompts for permission by showing the official dialog OR shows instructions on how to grant permission on iOS if he has been asked earlier and denied at that moment. (Something like "got to Settings on your iPhone and then click...")

**Comment by katzer** [comment]
Thats possible. You can make a feature request.
https://github.com/katzer/cordova-plugin-local-notifications#i-would-like-to-propose-new-features
