### ISSUE TITLE
Click on notification in Ionic app

### ISSUE THREAD

**Issue by virix** [katzer/cordova-plugin-local-notifications#474]
In a Ionic app click event on a notification works well (tested with Android 5 on my Nexus 5).
It works well also if i close the app with swipe out from Android recent apps.
On the contrary if I close the app with the call
ionic.Platform.exitApp()
click event does not work anymore.

**Comment by dansanti** [comment]
Well, i test that all notification was canceled on swipe to close app , rebooting works fine, but the problems is with swipe to close or clean on Android recent app manager :/

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
As no update in over a year am closing the issue.
