### ISSUE TITLE
i have a problem in first local-notifications project

### ISSUE THREAD

**Issue by cordova-android** [katzer/cordova-plugin-local-notifications#478]
it don't work till now

1-i download in cmd local-notifications using command
cordova plugin add de.appplant.cordova.plugin.local-notification

2- build cordova

3-in html

head

		  <script type="text/javascript" src="js/jquery.js"></script>
		<script type="text/javascript" charset="utf-8">

function sendNotification() {

	cordova.plugin.notification.local.schedule({ 
	text: 'Good morning!' ,
	every: "minute" 
	});
	alert(2);
				
			}
			

    </script>

    body
 button onclick="sendNotification();"  -->send
    
   
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>

4- nothing added in config.xml or in AndroidManifest.xml

till now it don't work

**Comment by katzer** [comment]
The namespace is cordova.plugin**s**.notification.local ;)

**Comment by cordova-android** [comment]
not understand what you mean

**Comment by katzer** [comment]
The namespace in your code snippet is wrong
