### ISSUE TITLE
Notification not created/scheduled (Android)

### ISSUE THREAD

**Issue by mrgroen** [katzer/cordova-plugin-local-notifications#480]
I am using release 0.8.1 with PhoneGap 3.5.0 and everything seems to run without errors.
However I don't get a notification when calling the "schedule" function.
Als when I retrieve all notifications with the "getIds" it returns "undefined".
I tested this on an Android 4.3 (Galaxy Nexus) and 5.0.2 (HTC One M7) device.

So from my understanding it doesn't create the notification.
I don't know what to do next, any suggestions?

**Comment by akreienbring** [comment]
Hello, i can confirm that it works on Android 4.4.4 (Galaxy Nexus) and 4.4.2 (Samsung S5)
You may post the code here to let us check...

**Comment by mrgroen** [comment]
Config XML addition:
<gap:plugin name="de.appplant.cordova.plugin.local-notification" version="0.8.1" />

Javascript:
            document.addEventListener('deviceready', lang.hitch(this,function () {
                console.log('deviceready');
                
                window.plugin.notification.local.hasPermission(function (granted) {
                   console.log('Permission has been granted: ' + granted);
                });
                
                cordova.plugins.notification.local.schedule({
                    title: 'test title',
                    text: 'test text'
                }, function(){ alert('callback'); });
                
            }), false);


Nothing fancy ;-)

**Comment by akreienbring** [comment]
Hi,
I'm not sure if the id is mandatory. But try this:
```
                cordova.plugins.notification.local.schedule({
                    id: 1,
                    title: 'test title',
                    text: 'test text'
                }, function(){ alert('callback'); });
```

**Comment by luishomero** [comment]
Hi, I was having the same issue, when building with cordova 3.5. I was able to make notification run by upgrading cordova to 4.x and use sdk for android 5.
Thanks

**Comment by kiStephane** [comment]
Hi, I am having the same issue. Here is my code:
```javascript
function ondeviceReady(){
    cordova.plugins.notification.local.schedule({
        id: 10,
        title: "ESSENTIEL radio",
        text: "ESSENTIEL radio, Bien + que de la radio"
    });

    cordova.plugins.notification.local.on("click", function (notification) {
        if (notification.id == 10) {
            console.log("CLICK ! ! !");
        }
    });

    setSongsInfo();
}
```

When printing my avd logcat i get this: 
```shell
E/PluginManager( 1002): Uncaught exception from plugin
E/PluginManager( 1002): java.lang.NullPointerException
E/PluginManager( 1002): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.execute(LocalNotification.java:133)
E/PluginManager( 1002): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:65)
E/PluginManager( 1002): 	at org.apache.cordova.PluginManager.execHelper(PluginManager.java:242)
E/PluginManager( 1002): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:227)
E/PluginManager( 1002): 	at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:53)
E/PluginManager( 1002): 	at org.apache.cordova.CordovaChromeClient.onJsPrompt(CordovaChromeClient.java:227)
E/PluginManager( 1002): 	at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:600)
E/PluginManager( 1002): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/PluginManager( 1002): 	at android.os.Looper.loop(Looper.java:137)
E/PluginManager( 1002): 	at android.app.ActivityThread.main(ActivityThread.java:4340)
E/PluginManager( 1002): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/PluginManager( 1002): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/PluginManager( 1002): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/PluginManager( 1002): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/PluginManager( 1002): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by kiStephane** [comment]
I updated my android platform and now it works. 
```javascript
cordova platform update android
```

**Comment by mrgroen** [comment]
Well this is lame, but it now works for me also.
I used the latest phonegap version to build my application.
So on phonegap 3.5.0 it doesn't work, on 3.7.0 it does...
