### ISSUE TITLE
icon in iOS

### ISSUE THREAD

**Issue by garfield185** [katzer/cordova-plugin-local-notifications#483]
I read in the wiki that we can specify a custom icon for the notification.
In iOS this icon setting does not work and the cordova logo appears instead. The wiki refers that the icon setting is only for Android apps, does it mean that all iOS notifications must show the cordova logo?

**Comment by salvadorhol** [comment]
On iOS by default the notifications match your app's tile icon.

**Comment by garfield185** [comment]
That's what I need. However it happens on Android, not on iOS. I am receiving a Cordova logo. How can I change it?

**Comment by katzer** [comment]
@garfield185, on Android the (small) icon can be specified via `icon` and `smallIcon`. On iOS a single notification has no icon.

**Comment by garfield185** [comment]
I am not using single notifications in iOS, but the regular scheduled ones. The app schedules one notification per day, at the same time. 
Is it possible to avoid showing the cordova logo on that one? I mean, I want to remove the logo in the screenshot and show the logo of my own app
![2015-03-31 10 02 06](https://cloud.githubusercontent.com/assets/9219347/6906830/79eda6f8-d731-11e4-9cd6-4b907f596779.png)

**Comment by katzer** [comment]
No its not possible. The icon and the app label are not part of the notification and places by iOS itself. Otherwise the plugin would also offer these attributes for iOS.

**Comment by katzer** [comment]
iOS will use the icon of your app. The KitchenSink's app icon is just the cordova icon - has nothing to do with the plugin.

**Comment by dpa99c** [comment]
@katzer It would be useful to explicitly state on the [URIs Wiki page](https://github.com/katzer/cordova-plugin-local-notifications/wiki/10.-URIs) that changing the notification icon on iOS is not possible.

The current wording can be mistakenly read to imply that it's possible to set a custom notification icon for both Android and iOS:

>Local resource for native resources relative to the res/drawable/ (Android) or Resources/ (iOS) folder.
>Sample: res://ic_popup_reminder or res://icon.png

**Comment by Tawpie** [comment]
I haven’t tried it, but XCode 9 has slots for “iPhone Notification” and “iPad Notification” in the assets catalog. Cordova doesn’t seem to properly copy everything over there, but if you go into the XCode project directly you’ll find those slots—the implication is that you can have different notification icons. Again, I haven’t tried because I don’t need that feature.
