### ISSUE TITLE
get() returns at property without milliseconds

### ISSUE THREAD

**Issue by sfeldkamp** [katzer/cordova-plugin-local-notifications#484]
context: version 0.8.1 on Android 4.4.4

`schedule()` accepts a Date object, but the milliseconds are stripped from the UTC value (in `convertProperties()`) before it is handed off to the native bridge to schedule with the OS timer.

when `get()` is called the callback receives an array of objects whose `at` property is returned directly from the native OS, that is to say, a UTC value but with the milliseconds removed.

A developer couldn't know that this occurs without looking at the code and if they try to create a Date object from the callback `at` then that Date object will be quite early in 1970.  We should multiply the return value by 1000 so that `at` is a UTC value rounded to the second from what was scheduled.

workaround: Developers should multiply the `at` value from `get()` by 1000 before creating a date object from it.

**Comment by Tawpie** [comment]
+1

**Comment by katzer** [comment]
Yeah usually the at: in callbacks should be a date object

**Comment by jim0020** [comment]
+1

**Comment by comandante3d** [comment]
+1

**Comment by julianohaze** [comment]
+1

**Comment by katzer** [comment]
Will be date object with v0.9
