### ISSUE TITLE
Notification not rescheduled when at/firstAt is in the past

### ISSUE THREAD

**Issue by sfeldkamp** [katzer/cordova-plugin-local-notifications#485]
context: version 0.8.1 on Android 4.4.4

When `schedule()` is called with an `every` option and an `at` option that are in the past, then the notification is not rescheduled.  It exists and is query-able, but the notification does not trigger.

If `every` is not a supplied option and `at` is in the past, then the notification is triggered immediately as described.

If `at` option is supplied and `every` option is not, then the notification is triggered on the schedule.

Also applies to `firstAt`.  Not sure if `update()` also experiences this same behavior.

**Comment by nespapu** [comment]
Context: version 0.8.1 on Android: 4.3 and 4.2 

Yes, it does. The update function is not working properly. It happens the same, the attributes change correctly, but the notification is never triggered. I am using cancel-schedule to mimic update by the moment.

On the other hand, I want to congrats @katzer for this wonderful plugin. it's awesome and very well documented. Thanks!

**Comment by katzer** [comment]
Should be fixed now
