### ISSUE TITLE
trigger is not working when app is in background

### ISSUE THREAD

**Issue by alejandroc2003** [katzer/cordova-plugin-local-notifications#487]

**Comment by alan0xd7** [comment]
If your app is in the background, normally the OS will put it into a suspended state so it cannot continue to run and cannot send any notifications. You need to implement something that will allow your app to run in the background, for example a background service on Android.

**Comment by luishomero** [comment]
Hi, I am testing with android trigger event and, It seems to work while not navigating inside the app.
But on IOS the trigger event doesnt happen when user is not inside the app, also I tried to query a single triggered notification like this

      cordova.plugins.notification.local.schedule({
        id:1,
        title:"Test",
        text:message,
       });

function onResume() {
  cordova.plugins.notification.local.getTriggeredIds(function (ids) {
     var id = parseInt(ids); --> knowing is a single notification, so no comma delimited string
    cordova.plugins.notification.local.get(id, function (notification) {
      alert(notification.id) ---> produces undefined
    });
  });
}
Am I missing something, or is there a way to retrieve a notification object with data in this scenario?
Thanks in advance

**Comment by katzer** [comment]
Yes, thats right. App is paused in background.

**Comment by alejandroc2003** [comment]
If I use this plugin, the notifications will work in background?

https://github.com/katzer/cordova-plugin-background-mode

Regards.

**Comment by katzer** [comment]
yes

**Comment by nickpe** [comment]
It looks like it does not work for iOS. The trigger event is not caught when the app is in background, even though i use cordova-plugin-background-mode plugin.

I have 2 plugins installed: https://github.com/katzer/cordova-plugin-local-notifications and 
https://github.com/katzer/cordova-plugin-background-mode.

Here is the code snippet:
`cordova.plugins.backgroundMode.onactivate = function() {
  cordova.plugins.notification.local.on("trigger", function(notification) {
      LocalNotificationsService.setLocatNotification();// reschedule notification
  });
};`


Please advise.
Thank you.

**Comment by byrneab1** [comment]
@nickpe did you get the trigger event to work using the cordova-plugin-background-mode plugin?

**Comment by estvmachine** [comment]
This works??

**Comment by RCATT123** [comment]
@nickpe can you provide complete code to start and enable background mode. and make it to trigger in background mode
