### ISSUE TITLE
data/json field of the local notification not working

### ISSUE THREAD

**Issue by gespim** [katzer/cordova-plugin-local-notifications#489]
I can set   text, title, badge.. but I cannot pass data: {id:'222'}  or json:{id:'222'}

any idea?

**Comment by luishomero** [comment]
One thing that has worked for me is:
var obj = JSON.parse(notification.data);
then you can access obj.id
hope this helps

**Comment by katzer** [comment]
@gespim, what platform?

**Comment by gespim** [comment]
Ios.

 

I checked the sourcode of the plugin and cannot find the definition of data as notification attribute

**Comment by katzer** [comment]
@gespim, it works exactly in the way @luishomero has described it. Passing an object does work. Any event does return these data.

**Comment by luishomero** [comment]
Other important fact, make sure you are using a valid json string.
before setting it you can always use an online validator. that might do the trick

**Comment by Tawpie** [comment]
@gespim being a bit more specific, your json object `{id:'222'}` should be `{"id":"222"}`. You are missing the quotes around id
