### ISSUE TITLE
Windows: Conflict with de.appplant.cordova.plugin.email-composer 0.8.2?

### ISSUE THREAD

**Issue by Tawpie** [katzer/cordova-plugin-local-notifications#491]
when de.appplant.cordova.plugin.email-composer 0.8.2 and de.appplant.cordova.plugin.local-notification 0.8.2dev are both in the same project, building for windows phone 8.1, VS throws an exception during startup just after receipt of the deviceready event. 

`Exception calling native with command :: LocalNotification :: deviceready ::exception=TypeError: Unable to get property 'deviceready' of undefined or null reference`

If you remove the email-composer plugin, the error goes away. This was experienced with the default cordova project made using `cordova create helloWorld`

**Comment by katzer** [comment]
hi @Tawpie, cannot reproduce even with fresh project and local-notification + email-composer side by side.

Can you please update your project to the newest cordova version and specially windows platform (3.8.0).

**Comment by Tawpie** [comment]
I'm pretty certain I'm at windows platform 3.8.0, but will confirm... #491 is sort of a side issue to #490 though! I was hoping it might be a clue.

**Comment by katzer** [comment]
@Tawpie, I made a [commit](be9826f1ae1380c13eaa07159067a2659941a94b) which I hope solves it.

**Comment by Tawpie** [comment]
commit id 385dabb23c063f284191aa17933358899c0b31cf appears to have resolved this issue. Thank you
