### ISSUE TITLE
ongoing does not work

### ISSUE THREAD

**Issue by iamola** [katzer/cordova-plugin-local-notifications#493]
ongoing attribute does not work. The notification clears when it is tapped rather than staying there. 

window.plugin.notification.local.schedule({
			ongoing: true,
			autoCancel: true,
			title: "Now Playing:",
			text: title,
});

**Comment by iamola** [comment]
Also, can we remove the smallicon? Just have one icon, the main one and not both?

**Comment by katzer** [comment]
`autoCancel` or `autoClear` needs to be set to _false_.

Android does not allow notifications without a small icon.

**Comment by iamola** [comment]
Would setting them to false keep the notification there? Untill i kill it? 
Also, would this keep it there after the restart or is that problem fixed? 

Thank you, and i didn't forget.

**Comment by jiju0nair** [comment]
Setting `autoClear` to false didnt helped.
Solved the issue by :

Add this code 
` if (notification.getOptions().isOngoing())
            return;`

in the file 
de\appplant\cordova\plugin\notification\ClickActivity.java

after the code :
`launchApp();`

Regards,
Jiju Nair

**Comment by iamola** [comment]
@katzer Can @jijunair's fix be added to the new release coming up please. As ongoing is broken even up till now. Thanks.

**Comment by iamola** [comment]
Still not resolved. This is still an issue.
