### ISSUE TITLE
Change id from numeric to string

### ISSUE THREAD

**Issue by andrewedcomp** [katzer/cordova-plugin-local-notifications#494]
Having the id as a string would allow setting notifications and retrieving them / updating them based on different events in the app... e.g.

Set a notification from user A (id:'user7677')   or user B (id:'user98989')   and also set a notification for a reminder (id:'remind343')  so if user A performs something that requires the notification updating e.g. a new post somewhere we simply update notification 'user7677'
This is just an example use.. lots of others too.. - numeric means its hard to keep a track of notifications being attached to different kinds of actions..

Thanks a lot

Andy

**Comment by iamola** [comment]
Yes, id is now numeric.

**Comment by katzer** [comment]
id was always numeric! But with v0.7 on iOS some methods worked with strings while others let the caused a crash.
