### ISSUE TITLE
Previous notifications trigger again on device restart

### ISSUE THREAD

**Issue by quelo83** [katzer/cordova-plugin-local-notifications#495]
It happens on Android devices. If I restart the phones then all previous notifications trigger again although all of them have been clicked previously.
I'm using Phonegap Build 3.7 and the last version of this plugin (0.8.1)
My code is:

cordova.plugins.notification.local.schedule({
      id: notificationId,
      title: 'Test app reminder',
      date: reminderCalculatedDate.toDate(),
      message: post.title,
      ongoing: false,
      data: JSON.stringify({
            type: "reminder",
            id: post.id
      })
});

What am I doing wrong? What should I change?
Thanks in advance!

**Comment by iamola** [comment]
I noticed this also. 
Single notification, Schedule Single.

**Comment by hkcity1111** [comment]
me too using plugin ver 0.8.1. 
All notification show again when restart device in android.
Thanks for further advance!

**Comment by jimibi** [comment]
Same for me, If notifications aren't manually cleared,  they will trigger again when phone start again.
I use V0.8.2dev on Android.
This is not necessarily stupid, if the phone initializes itself. But we should be able to configure it.
Thanks in advance.

**Comment by katzer** [comment]
Hope that helps: 3b159c88554c8090b55d8e3ff440c0f56b1a23f5

**Comment by iamola** [comment]
When would all the new changes be published to Phonegap Build?

**Comment by hkcity1111** [comment]
Thanks katzer.
There is no more additional notification after reboot.

**Comment by jimibi** [comment]
Thank
It's Ok for me

**Comment by quelo83** [comment]
It seems it's been resolved ;)
However I'm waiting for the publication to Phonegap Build.
Thanks in advance!

**Comment by osamamamdouh** [comment]
This modification was not enough for me , the reason was "wasInThePast" function returns false even for previous notifications.
I noticed that the previous notifications takes new current date value after reboot the device.
so I made the following correction:

    public boolean wasInThePast () {
    	
    	Date d = new Date();
    	Date afterAddingFiveMins=new Date(d.getTime() + (5 * 60000));    	
        return afterAddingFiveMins.after(options.getTriggerDate());       	
    	
    }

**Comment by ashishrar** [comment]
@katzer  @osamamamdouh 
Hi this solution is working fine when notification is scheduled for single time.
But when notification is scheduled with repeat options (Like every: day), then notifications are triggering again on device restart.

**Comment by WassiMan** [comment]
Hi. I have version 0.8.2dev installed, and the problem is still there, even with my version containing @katzer 's changes (https://github.com/katzer/cordova-plugin-local-notifications/commit/3b159c88554c8090b55d8e3ff440c0f56b1a23f5)

**Comment by adi3890** [comment]
Hi even i have 0.8.2dev installed, tried all mentioned methods but still all notification appears on device startup. @katzer please help

**Comment by Krysisx** [comment]
same for me

**Comment by Mohammad-Soryani** [comment]
I tried some of the proposed methods by others but It seems that they don't work for me. As my notifications are triggered only once I found the following code helpful for that situation:
```javascript
cordova.plugins.notification.local.on("click", function (notification) {
    cordova.plugins.notification.local.cancel(notification.id, function () {
    });
});
cordova.plugins.notification.local.on("clear", function(notification) {
    cordova.plugins.notification.local.cancel(notification.id, function () {
    });
});
```
It cancels every clicked and cleared notifications so they won't appear again. Not clicked and not cleared notifications though will still be triggered after next startup.

**Comment by M-Summers** [comment]
For one-time notifications, adding unpersist(); at the end of showNotification will solve the problem.
But there are two points about it:
1- before changing the source of the plugin, remove the platform (android in my case). Then Change the source, Add the platform, and build.
2- I'm not sure if this solution does everything that should be done and doesn't have any side effects (If anyone has info about this I'd be grateful).

**Comment by iepathos** [comment]
Having this issue as well still with latest build.

**Comment by cusackd** [comment]
Also having this issue with Android buil

**Comment by ciokan** [comment]
+1 any news on this?

**Comment by gorilla77** [comment]
This is how I solved this issue, for now:

Notification.java:165

    public void schedule() {
        long triggerTime = options.getTriggerTime();
        schedule(new Date(triggerTime));
    }
    public void schedule(Date triggerDate) {
        persist();

        // Intent gets called when the Notification gets fired
        Intent intent = new Intent(context, receiver)
                .setAction(options.getIdStr())
                .putExtra(Options.EXTRA, options.toString());

        PendingIntent pi = PendingIntent.getBroadcast(
                context, 0, intent, PendingIntent.FLAG_CANCEL_CURRENT);

        if (isRepeating()) {
            getAlarmMgr().setRepeating(AlarmManager.RTC_WAKEUP,
                    triggerDate.getTime(), options.getRepeatInterval(), pi);
        } else {
            getAlarmMgr().set(AlarmManager.RTC_WAKEUP, triggerDate.getTime(), pi);
        }
    }

RestoreReceiver.java:46

    public void onRestore (Notification notification) {
        if (notification.isScheduled()) {
            if (notification.wasInThePast()) {
                // Increase trigger time until it's in the future
                Date triggerDate = notification.getOptions().getTriggerDate();
                do {
                    triggerDate = new Date(triggerDate.getTime() + notification.getOptions().getRepeatInterval());
                }
                while (new Date().after(triggerDate));
                notification.schedule(triggerDate);
            }
            else {
                notification.schedule();
            }
        } else {
            notification.cancel();
        }
    }

You may want to persist the newly calculated trigger time.

**Comment by gaurav-chandra** [comment]
Happening still. Is it solved?
