### ISSUE TITLE
Getting many errors on xcode 5.1.1 and ios 7.1.2

### ISSUE THREAD

**Issue by poojasonawane** [katzer/cordova-plugin-local-notifications#499]
/Users/sampada_pingale/Documents/hello/platforms/ios/HelloWorld/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m:413:30: Undeclared selector 'registerUserNotificationSettings:'
/Users/sampada_pingale/Documents/hello/platforms/ios/HelloWorld/Plugins/de.appplant.cordova.plugin.local-notification/UIApplication+APPLocalNotification.m:40:9: Unknown type name 'UIUserNotificationType'; did you mean 'UIRemoteNotificationType'?
/Users/sampada_pingale/Documents/hello/platforms/ios/HelloWorld/Plugins/de.appplant.cordova.plugin.local-notification/UIApplication+APPLocalNotification.m:41:9: Use of undeclared identifier 'UIUserNotificationSettings'
/Users/sampada_pingale/Documents/hello/platforms/ios/HelloWorld/Plugins/de.appplant.cordova.plugin.local-notification/UIApplication+APPLocalNotification.m:41:37: Use of undeclared identifier 'settings'
/Users/sampada_pingale/Documents/hello/platforms/ios/HelloWorld/Plugins/de.appplant.cordova.plugin.local-notification/UIApplication+APPLocalNotification.m:43:9: Use of undeclared identifier 'settings'
/Users/sampada_pingale/Documents/hello/platforms/ios/HelloWorld/Plugins/de.appplant.cordova.plugin.local-notification/UIApplication+APPLocalNotification.m:46:17: Use of undeclared identifier 'UIUserNotificationTypeAlert'; did you mean 'UIRemoteNotificationTypeAlert'?
/Users/sampada_pingale/Documents/hello/platforms/ios/HelloWorld/Plugins/de.appplant.cordova.plugin.local-notification/UIApplication+APPLocalNotification.m:46:17: Use of undeclared identifier 'UIUserNotificationTypeAlert'; did you mean 'UIRemoteNotificationTypeAlert'?
/Users/sampada_pingale/Documents/hello/platforms/ios/HelloWorld/Plugins/de.appplant.cordova.plugin.local-notification/UIApplication+APPLocalNotification.m:65:9: Use of undeclared identifier 'settings'

**Comment by katzer** [comment]
The latest platform SDK is required for compilation.
