### ISSUE TITLE
Click and schedule events triggers multiply for one notification

### ISSUE THREAD

**Issue by alexusdenisov** [katzer/cordova-plugin-local-notifications#501]
1)Click event (notification.local.on("click" ... ) triggers multiply(2 and more, depend how many times you click) when click..
2) Also after click if I try to schedule new notification, notification.local.on("schedule".. will trigger multiply too.
Really only one new notification was scheduled that proved  by this code:
window.plugin.notification.local.getScheduledIds(function (scheduledIds) {
alert('Scheduled IDs: ' + scheduledIds.join(' ,')); //1,2
});
I could see the second problem only with the first.

**Comment by katzer** [comment]
Do you register the click event within the click-callback?

**Comment by alexusdenisov** [comment]
Yes, of course.

**Comment by jimibi** [comment]
It should be added "cordova.plugins.notification.local.on("trigger", function (data)" once, check that your program doesn 't go to this place several times.

**Comment by katzer** [comment]
@alexusdenisov, if you register an event callback within a callback for that event, the next time the event occurs, one more callback will be executed. - Don't register a callback within a callback for same event.

**Comment by alexusdenisov** [comment]
Ok, thank you. It seems in angular controller I should make some check like this if(typeof($window.plugin.notification.local.core._listener['click']) == 'undefined'){
    notification.local.on("click" ... )
}
to register click event once.

**Comment by calsupik** [comment]
I am also having this issue. I am creating multiple notifications in a for loop and then pushing these notifications into an array. I am then calling schedule with the array of notifications. 
inside for loop:
"var notification = {
						id: locations[i].id,
						title: locations[i].name,
						text: locations[i].shortDesc,
						//data: {loc:locations[i]}
			}
					
notifications.push(notification);"

outside for loop:
"cordova.plugins.notification.local.schedule(notifications);"

I have the "notification.local.on("click", function (notification){ alert("Notification ID = " + notification.id);},this);" in another function. The notifications pop up as expected and the alert comes up as expected when clicked, but when the notification is created again, when I click it two alerts pop up. On the third time 3 alerts come up and so on and so forth. What needs to be done so only one alert comes up each time?
