### ISSUE TITLE
iOS 8.0

### ISSUE THREAD

**Issue by lucaele** [katzer/cordova-plugin-local-notifications#502]
Sound not play in background mode in iOS 8.0.
MP3 file is correctly present; i use the same file from button action and it's work.
On same app i use cordova-plugin-background-mode, is this a conflict problem?
Thanks,
Luca
----------------------------------------------------------
window.plugin.notification.local.add({
    id: 1526,
    title: titolo,
    sound: 'cazzarola.mp3',
    text: testo,
    badge: '1'
});

**Comment by katzer** [comment]
You need to convert mp3 files to .caf or .wav. Thats Apple...

**Comment by lucaele** [comment]
Thanks Katzer, in iOS 8.2 audio file .caf works!!!
Now i try the same on Android.
