### ISSUE TITLE
app new version notification  

### ISSUE THREAD

**Issue by 7aduta** [katzer/cordova-plugin-local-notifications#503]
can i use the plugin to notify the user when there is new version released ?

**Comment by katzer** [comment]
sure if you know the release date

**Comment by 7aduta** [comment]
is there an chance to provide me with a sample code for it ... and if i released a new version in the google play store is gone found a new update and will show that in the market app .. i searched for an answer for that and i couldnt found any thing 
ps: sorry  for bad english :)

**Comment by katzer** [comment]
```javascript
cordova.plugins.notification.local.schedule({
    title: "Update"
    text: "Update ready for download"
    at: next_monday // a date object
})
```
