### ISSUE TITLE
The documentation isn't clear on where to put files to be used as a smallIcon resource

### ISSUE THREAD

**Issue by carpiediem** [katzer/cordova-plugin-local-notifications#504]
Closed issues like [230](https://github.com/katzer/cordova-plugin-local-notifications/issues/230) and [398](https://github.com/katzer/cordova-plugin-local-notifications/issues/398) make it clear that the smallIcon must be be placed in the res directory, but I'm having trouble figuring out how to do that in my Ionic project.  It includes a resources/android directory with both icon & splash as sub-directories.  Do I put the PNG file directly in there?  In a new sub-directory?  Somewhere else?  What do I name the file so that I can refer to it in the schedule function?

    cordova.plugins.notification.local.schedule({
      id: 1,
      title: title,
      text: message,
      at: new Date(now + delay * 1000),
      sound: sound,
      smallIcon: 'notification',
      led: 'FBA50A',
      badge: 1
    });

**Comment by wworley** [comment]
I've got the same issue, by default the icon seems to be a alert bell icon which is android default, i've tried to change to file://res/icon/android/small.png and that didn't work, maybe in the latest version the small icon has been removed on accident?

**Comment by katzer** [comment]
See https://github.com/katzer/cordova-plugin-local-notifications/wiki/10.-URIs

`res://icon/android/small.png` (native ressource folder)
`file://res/icon/android/small.png` (www/res/...)

**Comment by wworley** [comment]
Still doesn't seem to work.

        function triggerMessage() {
            var msgNum = Math.floor((Math.random() * 100) + 1);
            window.plugin.notification.local.add({
                id:         msgNum,  // A unique id of the notifiction
                title:      '7:00PM - 8:00PM',  // The title of the message
                message:    'BOGO: Premium drinks at some bar!',  // The message that is displayed
                icon:       'file://icon.png',
                led:        '009900',
                sound:      'file://cricket.mp3',
                smallIcon:  'file://res/icon/android/small.png'
            });
        }

All i see if the main icon.png and where the small icon should be (normally the bell icon on android) there is just a black square, i've confirmed the small icon exists and is in the right location.

![screenshot_2015-04-13-18-18-28](https://cloud.githubusercontent.com/assets/7535181/7126786/4fc9fbae-e20a-11e4-859c-819089997002.png)

**Comment by wworley** [comment]
Not using the smallIcon param results in the below as expected.
![screenshot_2015-04-13-18-38-41](https://cloud.githubusercontent.com/assets/7535181/7127022/9d983eac-e20c-11e4-8ae1-dc4a6d3a8655.png)

**Comment by carpiediem** [comment]
Yeah, this is the same results I've been having.  Perhaps something got broken during the recent rewrite?

**Comment by katzer** [comment]
@wworley, the reason is that on Android `smallIcon` needs to point to a native resource e.q `res://...`. The black square comes from the plugin because it cannot find the resource icon.

**Comment by wworley** [comment]
@katzer In a previous version of the plugin the smallIcon would just show up even when not specified (it pulled the "icon" specified in the config.xml), but if i'm understanding your reply, you are saying that when using the plugin on Android you are not able to specify the smallIcon and you must use the default android "bell" icon instead, is that correct?

If not please help me understand how i can set the smallIcon without altering the default Android platform icon (which would make all other applications on the phone that use that icon use my apps replacement of the native icon).

**Comment by carpiediem** [comment]
@katzer , I think the trouble I'm having might be related to the different file structures used in [your kitchen sink app](https://github.com/katzer/cordova-plugin-local-notifications/tree/example/platforms/android/res)
```
/platforms/android/res/drawable-hdpi/icon.png  (12 other directories for various sizes)
```
and the [Ionic starter app](http://ionicframework.com/docs/guide/installation.html) that my project is based on.
```
/resources/android/icon/drawable-hdpi-icon.png   (5 other icons for various sizes)
```

I've tried various versions of 'res://small' and tried putting my file in every location in the resources folder that I can think of, but I'm still getting a blank icon (strangely, mine is white instead of black).  I can't even duplicate @wworley 's success using the same file:// address for both icon & smallIcon.

Do you have any idea how I refer to a specific resource in Ionic's file system?

I'm also suspicious that the file size might be a factor in the problems I'm having.  I've been testing with a 24x24px PNG image; should I use something else?

**Comment by wworley** [comment]
@carpiediem i think you can rule out the file dimensions and file size as the standard cordova icon is 128X128 and file size of 12KB the small icon i was trying to use was same size and similar in file size.

I should mention i'm using phonegap, phonegap build and obviously on android and have not yet tested on iOS

**Comment by katzer** [comment]
`smallIcon` only works with `res://` uri because Android needs the resource ID for that file and therefor the file has to be placed in a special folder.

`res://icon` refers to _R.drawable.icon_. Not sure about the naming under ionic.

**Comment by tribe84** [comment]
Dropped my icons into the platforms/android/res/drawable folder and pointed to it using file:// and it all works as expected for me.

cordova.plugins.notification.local.schedule({title:"notification",message:"yeah boi", icon: 'file://notification_icon.png',smallIcon: 'file://notification_alert',led: '009900'});

**Comment by wworley** [comment]
@tribe84 please tell me how the small icon is working without the file extension? OR is the file extension no required which is why no one else but you can get it to work?

**Comment by bolonmedia** [comment]
If you are using Meteorjs, all you need to do is go to this link --> https://forums.meteor.com/t/meteor-cordova-www-directory/3851/5 read the comment and later use the solution @tribe84 provides, and everything will work as expected!

![img2](https://cloud.githubusercontent.com/assets/4873608/7799135/82d562cc-02d0-11e5-9209-16b37f012257.jpg)
![img1](https://cloud.githubusercontent.com/assets/4873608/7799136/82d7413c-02d0-11e5-8772-c40a74bda215.jpg)
![img3](https://cloud.githubusercontent.com/assets/4873608/7799198/24e2b6a0-02d1-11e5-9f0a-3b7bf98551dd.jpg)

**Comment by DarrylD** [comment]
Not using meteor but, @bolonmedia works perfectly for me.

Place in res, lowercase and underscores, use extension.

**Comment by souly1** [comment]
A small simple workaround if you fear to change your platform folder manually is to add a Cordova 'after_prepare' hook and copy a file from folder a to platforms/android/res/drawable, this worked for me.

Simple code example for such a hook file:


#!/usr/bin/env node

var filestocopy = [{
  "www/img/notification_icon.png":
  "platforms/android/res/drawable/notification_icon.png"
}];

var fs = require('fs');
var path = require('path');

// no need to configure below
var rootdir = process.argv[2];

filestocopy.forEach(function(obj) {
  Object.keys(obj).forEach(function(key) {
    var val = obj[key];
    var srcfile = path.join(rootdir, key);
    var destfile = path.join(rootdir, val);
    //console.log("copying "+srcfile+" to "+destfile);
    var destdir = path.dirname(destfile);
    if (fs.existsSync(srcfile) && fs.existsSync(destdir)) {
      fs.createReadStream(srcfile).pipe(
          fs.createWriteStream(destfile));
    }
  });
});

**Comment by homen** [comment]
Working @bolonmedia

**Comment by sirius2013** [comment]
This is working now?

**Comment by GK303** [comment]
I use the phonegap for android and want to change the notification icon for the app ,I use your method,but it still not work?would you help me?if in in the android workspace(phonegap),which foolder I should choose to put the icon?

**Comment by heekinho** [comment]
I'm using ionic and I had the same problem as @carpiediem: the icon was entirely white.
That happened because I didn't realized at first that the icon should be flat. So I prepared an icon using only white and transparency and it's ok now.

I also prepared a similar hook like @souly1. 

```
#!/usr/bin/env node

var fs = require('fs-extra');
var path = require('path');

var androidPlatformsDir = path.resolve(__dirname, '../../platforms/android/res'); 
var notificationIconsDir = path.resolve(__dirname, '../../resources/android/notification-icon');
fs.copy(notificationIconsDir, androidPlatformsDir);
```

Also, my configuration looks like this:
```
{
  ...
  icon : 'file://img/icon.png', // This is on the www folder
  smallIcon: 'res://ic_notification.png' // This is on the platform/android/res/drawable-* folders
}

**Comment by iamola** [comment]
@wworley I tried your method that works, does not work for me using Phonegap Build.
`icon: 'file://icon.png',
smallIcon: 'file://icon.png',`

**Comment by flint002** [comment]
I have the same problem #ionic v2

**Comment by rwillett** [comment]
We have it working on Ionic 1, with PushWoosh and local notifications. 

We use a very similar technique to populate the Android folders as @heekinho. The only differences is our start folder locations and we use a shell script and not JavaScript.

We don't use smallIcon though. We do use icon and its identical to @heekinho.

Works fine for us.

**Comment by flint002** [comment]
I solve this by adding smallicon param
![](https://lh3.googleusercontent.com/-V0tp-o6MvGc/WKYLICBItFI/AAAAAAAACEs/4YTc8LWQxe4KBfNpT0WI59JEsmq7htxowCL0B/h328/working.png)


without smallicon param give me blank square on the icon

![](https://lh3.googleusercontent.com/-h2DpstTeQpA/WKYLKU47OZI/AAAAAAAACE4/CteWyF9fuwc5nWsOVp9Pyo5yGrE_Zh-yQCL0B/h288/blank.png)

thank you

**Comment by a578242325** [comment]
@flint002 Thanks, the normal work. However, smallIcon and icon conflict, only one

**Comment by a578242325** [comment]
@flint002 Try it, you can set smallIcon as file: //small.png can be compatible
