### ISSUE TITLE
Clearing all but not the current triggered notification

### ISSUE THREAD

**Issue by akreienbring** [katzer/cordova-plugin-local-notifications#505]
Hello,
my app creates a series of local notifications (Version 0.8.1). I would like to clear all but not the last one that triggered.
The below code should accomplish that, but the clear statement does not clear any notifications.
```
		cordova.plugins.notification.local.on("trigger", function(currentNotification) {
			//a local notification was triggered: clear all others
			try {
				$log.debug("just triggered: " + currentNotification.id);
				cordova.plugins.notification.local.getTriggeredIds(function (triggeredNotifications) {
					$log.debug("found triggered notification before: " + JSON.stringify(triggeredNotifications));
					triggeredNotifications.splice(triggeredNotifications.indexOf(currentNotification.id), 1);
					$log.debug("found triggered notification after: " + JSON.stringify(triggeredNotifications));
					cordova.plugins.notification.local.clear(triggeredNotifications);
				});				
			} catch (err) {
			}
		});
```
I can confirm that after splicing the array contains exactly the notification id's I would like to clear.
BTW clearAll works like expected...
Is this a bug or is there something wrong with my solution?

**Comment by akreienbring** [comment]
Rootcause: This code seems not to work on Android 4.4.2:
```
cordova.plugins.notification.local.getTriggeredIds(function (triggeredNotificationsIds) {
	cordova.plugins.notification.local.clear(triggeredNotificationsIds);
});				
```

**Comment by katzer** [comment]
@akreienbring, can it be that you want to clear scheduled notifications? Better use `getScheduledIds`.

**Comment by mikepsinn** [comment]
I have this issue as well. I have notifications showing, but getTriggeredIds returns an empty array. @akreienbring Did you ever find a solution to this issue?
