### ISSUE TITLE
notifications doesnt schedule/trigger

### ISSUE THREAD

**Issue by stefansc** [katzer/cordova-plugin-local-notifications#506]
Here is my code example:

```javascript
datumUnixType = moment(resultSet.rows.item(i).startDatum,'X').add('hours',window.localStorage.getItem('meineBenachrichtigungszeit')).format('X');
datumDateType  = new Date(datumUnixType*1000);
console.log('##################### My new Date: '+datumDateType + '##### Titel: '+resultSet.rows.item(i).titel + 'id:'+resultSet.rows.item(i).bid  + '#####################');
 cordova.plugins.notification.local.schedule({
  id: resultSet.rows.item(i).bid, 
  title: resultSet.rows.item(i).titel,
  text: "Ein Termin steht an",
  at: datumDateType
 });
```

Tested it with ios sdk 8.2 and 8.3, latest cordova version and latest version of the plugin. All permissions are granted and i didnt receive any error message. console.log gives an output with a correct date to push the event. Previously the plugin and the app works with function window.plugin.notification.local.add and further versions of cordova. Could you please tell me what am i doing wrong?

**Comment by stefansc** [comment]
i've tried it in several ways. the datumUnixType for example is 1428919200 the other dateType is a date object like Mon Apr 13 2015 12:00:00 GMT+0200 (CEST). I have noticed that there is an unknown log at the end of scheduling: WARN: Unknown property: autoClear
Do you know that instance of console output?

Basically the plugin works with the 5sec_from_now example.

**Comment by stefansc** [comment]
So i've tested it with default values. The resultSet contains for example 20 or more items and all of that set will appear at console log, but only 4 or less items will be triggered. I dont receive any error message, only that warning "unknown property: autoClear" at the end....

```javascript
function addNotifications(tx,resultSet){
    cordova.plugins.notification.local.cancelAll(function() {
        alert("done");
    }, this);
    for (var i = 0; i < resultSet.rows.length; i++) {
        console.log('## New Notification: ' + resultSet.rows.item(i).bid + '##');
        var now = new Date().getTime();
        var sec_from_now = new Date(now + 2*i*1000);
        cordova.plugins.notification.local.schedule({
            id: i,
            title: "ID="+resultSet.rows.item(i).bid,
            text: "Ein Termin steht an",
            at: sec_from_now,
            sound: null
        });
    }
}
```

**Comment by katzer** [comment]
@stefansc, I made 2 commits today related to the "unknown..." message and passing number for at:

**Comment by stefansc** [comment]
@katzer, i'm sorry but it doesnt solve the problem, now the message wont be shown but the issue still exist. During the for loop, all the events will be logged, but only randomly selected events will be triggered

**Comment by katzer** [comment]
Try to call schedule on time with an array of notifications

**Comment by stefansc** [comment]
@katzer thanks a lot, this works. Don't know why it doesn't work with a loop but with an array from the resultset there will be no issues.
