### ISSUE TITLE
Schedule repeating notifications

### ISSUE THREAD

**Issue by ihaveaquestion** [katzer/cordova-plugin-local-notifications#509]
Hello sorry if this question is stupid but I am new and I cant find any solution in weeks. 

My question is with this plugin it is possible for Android set in parameter "every" the value 100 to recive a local notification every 100 minutes? I am trying with this code but I only recive the first notification at time1, after that it is not rescheduling. The notification is queried well and show all parameters properly (the id, tittle, text and the schedule first time saved in the var info1) but it is not firing after the first time.

info1=time1.getHours()+":"+time1.getMinutes();
cordova.plugins.notification.local.schedule({
    id: 1,
    title: "Notification!",
    text: message,
    firstAt: time1,
    data: info1,
    every: 100
});

I tried in "every" set the value 5 and then it works better, but after some times it stops notifying too.I am missing something?

Many thanks in advance for answers!

**Comment by jimibi** [comment]
With Android it's possible to specify a time in minutes with an integer, I tested with v8.00 and it works, I have not used with this version.

**Comment by ihaveaquestion** [comment]
Thank you for your answer jimibi, do you know if for you is working with long repeating times?
 I was trying with previous versions but its the same for me. With the 0.8.0 version I tried with this sample code:
    
var now = new Date().getTime(),
    _60_seconds_from_now = new Date(now + 60*1000);
    cordova.plugins.notification.local.schedule({
    id: 1,
    title: "Notification!",
    text: "message",
    firstAt: _60_seconds_from_now,
    every: 100
});


And I only receive the notification after 1 minute, but nothing after 100 minutes. 

But the weird thing is that if I set the "every" parameter to 5 I receive the notification only the 5 or 6 first times, sometimes 5, sometimes 6 times. And its stop notyifing later.

**Comment by ksabariraj** [comment]
HI, 

Me too facing the same issue. I am getting the notification only 5 to 6 times. After that, there is no notification.

**Comment by jimibi** [comment]
I don't have test with so long time ihaveaquestion (max 10minutes).
But you use new interface with 8.00 and I'am not sure it's possible.

**Comment by ksabariraj** [comment]
Hi,
Thanks for the response. Not need to test that much long. I have tested like, I set remainder first at 7.30 pm after that every 2 mins. I got only 6 notifications only. This issue is happening continues for me. Please see the below code and guide me if I did anything wrong.

cordova.plugins.notification.local.schedule({
						id: "12",
						title: "sample",
						text: "Wakeup",
						firstAt: from_now,
						every: 2, //2 Mins
						led: 'A0FF05',
						autoCancel: true,
						data: {}
					});

**Comment by jimibi** [comment]
Hi,

Test with: "autocancel: false"

**Comment by ksabariraj** [comment]
HI,
I have checked with autoCancel: false, But, still not fixed :-( only getting notification 5 times

**Comment by MichelReij** [comment]
Hi ksabariraj, I think I am facing the same issue on some versions of Android. I have two people reporting that repeating notifications don't work for them. One is on Android 4.2.2 and the other is on Android 5.1.

I have tried everything, but still no succes for them. I am on version 0.8.1 of the plugin.

**Comment by ksabariraj** [comment]
Hi Katzer,

Any update on this issue?

Thanks,
Sabari.

**Comment by katzer** [comment]
@ksabariraj That sounds Android/Device specific. Android does not guarantee for exact time in case of repeating alarms. In combination with `ongoing:true` I had no issues and exact times.

**Comment by rupalpatel0008** [comment]
@katzer with ongoing:true notification won't be cleared.

**Comment by imran031387** [comment]
I'm having the same issue and i tried with ongoing:true as well

**Comment by bameff** [comment]
I have some question.
how to repeat x times from recurrence type.
example : I want to repeat every 30 hours 4 times

**Comment by imran031387** [comment]
any update regarding this issue?
