### ISSUE TITLE
Do you have API to work with buttons in a notification?

### ISSUE THREAD

**Issue by VanDalkvist** [katzer/cordova-plugin-local-notifications#519]
So, I've not found any API methods to operate with buttons in a notification. Do you have it?

**Comment by elizabethrego** [comment]
Hey, my fork of this has interactive notifications for iOS, and I'm hoping to have Android done by the end of this week. Talking to Katzer about having the changes merged when complete.

https://github.com/elizabethrego/cordova-plugin-local-notifications

There's documentation on how to use them and everything.

**Comment by katzer** [comment]
:+1:
