### ISSUE TITLE
[iOS] You have to wait for previous scheduling/cancel success callback until you can to make changes again

### ISSUE THREAD

**Issue by jtomaszewski** [katzer/cordova-plugin-local-notifications#520]
This bug happens only on iOS.

For example if we have 10 alerts, and we'll assign them like this:

```js
var ids = [1,2,3,4,5];
for (var i in ids) {
  cordova.plugins.notification.local.schedule({id: ids[i]});
}
```

Then only one of them will actually be assigned, propably because of some race condition.

To solve this, we need to:

```js
// wait with some callback/promise after adding the previous callback:
var ids = [1,2,3,4,5];
var i = 0;
callback(0);

function callback(i) {
  if (i >= ids.length) return;
  cordova.plugins.notification.local.schedule({id: ids[i]}, function(){ callback(i+1) });
}

// OR
// assign them all at once
cordova.plugins.notification.local.schedule(ids.map(function(i){
  return {id: i};
}));
```

But seems like there is no information in docs that we need to do this in this way! We should add info about it.

I was fighting with this bug (which happens only on iOS) for a couple of days, wondering why only some of my notifications are actually being added. (because, f.e. when changing 'alert time' I was canceling and re-adding all the alerts at once).

**Comment by katzer** [comment]
Yes iOS works a bit strange when trying to schedule multiple at once. Thats why its better to call schedule with an array of notifications. Added a hint to the wiki page.
