### ISSUE TITLE
Question about error handling around notifications

### ISSUE THREAD

**Issue by r1c4l** [katzer/cordova-plugin-local-notifications#522]
Firstly, would like to say that this is a great plugin! Thanks for writing this.

I'd like to ask about how to handle error properly when using this plugin. I am not sure, maybe I missed this on the docs somewhere. Say when registering or cancelling notification(s), how to check whether there is any error occurs or the operation is not successful? I know there is a success callback but is there any error callback as well?

Also does each of the operation run synchronously? I mean is it always safe to assume that one operation always complete before another operation, for example, if I have these two operations in sequence:
. . .
cordova.plugins.notification.local.cancel([1,2,3, ... 20], function() {
  // do something . . .
}); 
cordova.plugins.notification.local.get([1,2,3, ... 20], function (notifications) {
  // check if they are really gone . . .
});
. . .
Will the second one always be executed after the first one completed?

Many thanks.

**Comment by katzer** [comment]
> is there any error callback as well?

No, there are no error callbacks. You see a useful need for them?

> does each of the operation run synchronously?

Yes, all methods works asynchron.
