### ISSUE TITLE
Scheduling a notification that triggers once every week at a specific time.

### ISSUE THREAD

**Issue by Whebcraft** [katzer/cordova-plugin-local-notifications#523]
Hello i would like to schedule a notification that triggers once every week (on Sundays) at (5am) 

        scheduleWeekly = function () {
            var date = new Date;
            var hour = date.getHours();
            _at_5_am = hour + 5;
            var sound = device.platform == 'Android' ? 'file://sound.mp3' : 'file://beep.caf';
            cordova.plugins.notification.local.schedule({
                id: 1,
                at: _at_5_am,
                text: 'hello...',
                every: 'week',
                sound: sound
            });
        };

is this a good approach?

**Comment by jimibi** [comment]
No with your snippet, you set: today at hour+5.

Use this for good approach:

    scheduleWeekly = function () {
        var var sound = device.platform == 'Android' ? 'file://sound.mp3' : 'file://beep.caf',
              date = new Date(),
              var day = date.getDays(),
              _sund_5_am = date.setDate(date.getDate+(7-day));
        _sund_5_am = date.setHours(5);
        cordova.plugins.notification.local.schedule({
            id: 1,
            at: _sund_at_5_am,
            text: 'hello...',
            every: 'week',
            sound: sound
        });
    };

**Comment by Whebcraft** [comment]
Thanks.
