### ISSUE TITLE
click event not fired after application restart

### ISSUE THREAD

**Issue by nagajyothy** [katzer/cordova-plugin-local-notifications#524]
when i am click on notification status bar it was not fired.

**Comment by JimGeek** [comment]
+1. Having the same problem. If app is closed and clicked on the notification in status bar then click event is not firing.

**Comment by virix** [comment]
+1. Having the same problem. I described my situation in issue #474.

**Comment by JayLIJS** [comment]
Hey guys, having the same problem too...

It seems like the "click" event was fired before my listener was initiated. 
That's why I can't detect the event. Trying to find a way around it now~

**Comment by spi100** [comment]
I met the same issue.
In the java code, events are correctly queued to be triggered after the device ready event, but it not seems to be enough on android 4.4.

I have changed the code of the "void deviceready" in localNotification.java by wrapping the launch of  queue events in a TimerTask to delay them. Not sure it's the best solution, but it works for me

    private static synchronized void deviceready () {
        isInBackground = false;
        deviceready = true;

        final Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                for( String js : LocalNotification.eventQueue) {
                    LocalNotification.sendJavascript(js);
                }
                LocalNotification.eventQueue.clear();
            }
        }, 2000);
    }
