### ISSUE TITLE
Notifications are not showing

### ISSUE THREAD

**Issue by Ajaxy** [katzer/cordova-plugin-local-notifications#528]
I have strange issue, notification are showing in emulator, but not on real device.

I make a simple call when app is in background:
```javascript
        cordova.plugins.notification.local.schedule({
            title: 'Hello',
            message: 'world'
        });
```

And nothing happens. I tested from Safari console, `registerPermissions` passes `true` in callback, and I have Pushwush plugin ( https://build.phonegap.com/plugins/1297 ) working well with push notifications.

I tested on iPhone 5 iOS 7.1, iPhone 4S iOS 7.0 and iPad 2 iOS 8.1.2

In emulator everything works perfect.

**Comment by Ajaxy** [comment]
I found that my notifications appear in Notifications Center, but not showing as banner or popup. I have correct notifications settings for my app and Pushwoosh push notifications are showing correctly.

**Comment by Ajaxy** [comment]
It works if I schedule delayed notification in foreground at 5 secs from now, then bring app to background. Seems that I can't trigger instant notification from background somehow.

**Comment by katzer** [comment]
Yes usually your app is paused in background

**Comment by Ajaxy** [comment]
@katzer, but I can read in README:

>Applications that run in the background for the **limited period allowed by iOS** might also find local notifications useful.
>For example, applications that depend on servers for messages or data can poll their servers for incoming items **while running in the background**; if a message is ready to view or an update is ready to download, they can then present a local notification immediately to inform their users.

I want to do definitely the same.

**Comment by WassiMan** [comment]
Any news on this issue? Having the same issue on iOS 8.4.1 and plugin v. 0.8.2dev.

**Comment by Ajaxy** [comment]
I ended up using remote push notifications.

**Comment by Krisa** [comment]
I agree, that's quite confusing. When the app is in the background, it's paused, so I can't figure out how it can still do some polling ... But if it's really possible, then I would be happy to see a real working example.
