### ISSUE TITLE
Plugin working when building with cordova CLI, not working when building with PhoneGap Build

### ISSUE THREAD

**Issue by LlamaloX** [katzer/cordova-plugin-local-notifications#529]
I am having a very strange problem that I am not able to solve.

I have an application that uses the plugin and when I build the .apk using the cordova line interface, I install it on my phone and the plugin works perfectly.

But, when I upload the .zip to PhoneGap Build (with only the /www folder and the config.xml), I install the .apk on my phone and it says Error: Uncaught TypeError: Cannot read property 'notification' of undefined url: /android_asset/www/js/shifts.js..... 

Same error each time some of the plugin's methods are called. The config.xml seems to be read correctly since in PhoneGap build the plugins appears as installed on the plugins tab.

What is the problem? I have been days scratching my head and I have not find the solution.

**Comment by Ajaxy** [comment]
Are you waiting for `deviceready` event before using plugin?

**Comment by stevegreatrex** [comment]
+1.  In my case I am definitely waiting for deviceready

**Comment by katzer** [comment]
Looks like PGB does not support hooks

**Comment by Ajaxy** [comment]
@katzer, but I can read in README:

>Applications that run in the background for the **limited period allowed by iOS** might also find local notifications useful.
>For example, applications that depend on servers for messages or data can poll their servers for incoming items **while running in the background**; if a message is ready to view or an update is ready to download, they can then present a local notification immediately to inform their users.

I want to do definitely the same.

**Comment by nespapu** [comment]
@katzer What does it mean PGB does not support hooks? I am definitely waiting for deviceready event. Is there a solution for that? Thanks in advance

**Comment by katzer** [comment]
Hooks aren't required anymore
