### ISSUE TITLE
cordova 5.0 cli "rename" and build fail problem

### ISSUE THREAD

**Issue by bau720123** [katzer/cordova-plugin-local-notifications#530]
hi @katzer  
I am using cordova 5.0 cli
there is a new "rename" problem
all detail at here
http://www.littlebau.com/cli/local_cli.gif
http://cordova.apache.org/

it will build fail too
www.littlebau.com/cli/02local_cli.gif

**Comment by katzer** [comment]
Will rename the dependency to its new id

**Comment by Yamini-Sontakke** [comment]
how the rename can be done for dependency to new id..like if I want to rename my 

org.apache.cordova.* plugin to cordova-plugin-*..??

How this can be done.

**Comment by bau720123** [comment]
hi @katzer 
just feedback something
the 0.8.2dev version still cause android build fail
