### ISSUE TITLE
Showing an image in notification area

### ISSUE THREAD

**Issue by WassiMan** [katzer/cordova-plugin-local-notifications#536]
Hi.

Is there a way to show an image with a notification using this amazing plugin. I've managed to configure a sound alert, showing a title and the app's icon, but I need to show an image instead of a description text under the title. Is it even possible with this plugin ?

**Comment by WassiMan** [comment]
What about the "image" attribute of the upcomming version ?

**Comment by roysG** [comment]
what happens with this ? 
any news ?

**Comment by WassiMan** [comment]
@roysG Nope, I abandoned the feature, it seems that we have to deal with some custom native development (Java) within the plugin itself. Sorry.

**Comment by katzer** [comment]
There are the `icon` and `smallIcon` attributes you can use.
