### ISSUE TITLE
notification.data is passed as string

### ISSUE THREAD

**Issue by hyyan** [katzer/cordova-plugin-local-notifications#538]
Hey , thanks for the great work

I have been trying to pass data to clicked notification , put after some digging I found that the `data` is passed as string . which is really wired .

logging the notification object gave me the following result :

```json
{"icon":"http://mysite.com/photot.jpg","data":"{\"type\":\"post\",\"id\":24}","
at":1430774835,"every":"minute","id":"1","title":"testing","smallIcon":"res://ic_popup_reminder","ongoing":false,"led":"FFFFFF","sou
nd":"res://platform_default","badge":0}
```

And here is a snippet from my code : 

```js
 cordova.plugins.notification.local.schedule({
            id : 1,
            every: "minute", // "minute", "hour", "week", "month", "year"
            title: 'testing',
            icon : 'url'
            data : {
              type: 'post',
              id: ID
            }
});

cordova.plugins.notification.local.on("click", function (notification) {
          if(notification.id != 1){
            return ;
          }
          $log.debug(JSON.stringify(notification));
});
```
Any idea ?  thanks in advance

**Comment by hyyan** [comment]
??

**Comment by hgenru** [comment]
I have same issue on ios 8.3

**Comment by markomarkovic** [comment]
I can confirm that the same issue exists on android, using cordova 5.0.0. Logging shows that the `data` is passed as string: `"data":"{\"schedulerId\":\"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\"}"`.

**Comment by snese** [comment]
Hi All,

I have same issue in this test environment

 - Cordova: 5.4
 - Cordova Platform: android 4.1.1, ios 3.9.1
 - Plugin version: 0.8.1

**Comment by katzer** [comment]
Its because the plugin does not expect JSON format.
