### ISSUE TITLE
Schedule - local-notification-util.js:115 Unknown property: firstAt (Android)

### ISSUE THREAD

**Issue by annemb22** [katzer/cordova-plugin-local-notifications#539]
Hello,

Here is my call to the plugin:

 cordova.plugins.notification.local.schedule({
        id: IdN,
        text: notifText,
        icon: "images/treeheartandeyeicon.png",
        sound: "file://sounds/alert.caf",
        firstAt: currentTime,
        every: formInputFrequecy 
        });     

currentTime is a js date object (in this case the result was: Tue May 05 2015 09:30:00 GMT+0200 (CEST)     )

Obtained with the following code:

       var currentTime = new Date();
        var chour = currentTime.getHours();
        var cminutes = currentTime.getMinutes();
        var month = currentTime.getMonth() + 1;
        var day = currentTime.getDate();
        var year = currentTime.getFullYear();
        var tdayNumber = currentTime.getUTCDay();       // used to calculate firstAt date, if  targetDay is bigger than tdayNumber (targetDay - tdayNumber = number of day to add to date for atFirst)
        if (targetDay != tdayNumber || (targetDay === tdayNumber && targetHour < chour) || (targetDay === tdayNumber && targetHour === chour && targetMinutes < cminutes) )  {
        if(targetDay > tdayNumber)  { var dayOffset = targetDay - tdayNumber;}
        else { dayOffset = 7 - tdayNumber + targetDay; }        
        currentTime.setHours(targetHour);
        currentTime.setMinutes(targetMinutes);
        currentTime.setSeconds(0);
        currentTime.setTime( currentTime.getTime() + dayOffset * 86400000 ); 
        }
        else {
        currentTime.setHours(targetHour);
        currentTime.setMinutes(targetMinutes);
        currentTime.setSeconds(0);
         }

Project Target:   Android 4.4
API level:        19
de.appplant.cordova.plugin.local-notification (0.8.2dev)
App built with Intel xdk
Testing on a Samsung Galaxy 5S

Is the problem me and my code or.... ?

**Comment by dani-inside** [comment]
Same problem here, but with iOS 8.3 on an iPhone 6. Any idea?

**Comment by annemb22** [comment]
I changed it to 'at' and the unknown property message went away but notifications weren't being scheduled. After reading through some of the other issues here I saw that someone had solved a similar issue by changing the Cordova build to 4.1. I was using 3.5, so I tried that and it's working ok now.

**Comment by bigkrp** [comment]
in local-notification-util.js (112) we loop and check in 'defaults' options, but in (33) we have only 'at' property and no 'firstAt'. Maybe this is error?
