### ISSUE TITLE
WP 8.1 unable to get property 'apply' of undefined or null reference

### ISSUE THREAD

**Issue by Tawpie** [katzer/cordova-plugin-local-notifications#540]
Exception calling native with command :: LocalNotification :: deviceready ::exception=TypeError: Unable to get property 'apply' of undefined or null reference

Not certain what's going on here -- but after a force-quit of my app, subsequent relaunches fail. I am not sure if this is the reason, but suspect it. App runs and relaunches after force-quit just fine without the plugin installed!!!

**Comment by katzer** [comment]
That should help: 0ce3fe702cde874c14c7ba8457927ed1f885582d

**Comment by ekambarrao** [comment]
I used this and i found it was broke yesterday which was perfect earlier, not able to reinstall either...in VS Cordova project. What is the reason????

**Comment by katzer** [comment]
@ekambarrao, whats broken? I installed the latest dev version, opened with VS and also could start and use the plugin.

**Comment by ekambarrao** [comment]
Hi Sebastian,
Thanks lot for quick reply.
when I try to install the plugin using https://github.com/katzer/cordova-plugin-local-notifications.git in visual studio, it is not bringing up anything.
If I download and refer the folder and also not able to install. Please find below.
I already installed once and it has been working fine but not able to reinstall it, if disturb the earlier version not able to restore it.
Following is a sample app to where i am trying to include. Can you help me by sharing the installation guide?

Thanks,Ekambar
