### ISSUE TITLE
Unable to install plugin after cordova update

### ISSUE THREAD

**Issue by paweldziura** [katzer/cordova-plugin-local-notifications#541]
Updated cordova to 5.0.0. When installing this plugin I get an error:

Failed to install 'de.appplant.cordova.plugin.local-notification':CordovaError: Plugin doesn't support this project's cordova version. cordova: 3.5.2, failed version requirement: >=3.6.0

EDIT: downgraded cordova and still same issue

EDIT: using:
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications

returns:
remote: Repository not found.
fatal: repository 'https://github.com/katzer/cordova-plugin-local-notification/' not found

**Comment by shybovycha** [comment]
:+1:

**Comment by antsav** [comment]
:+1:

**Comment by katzer** [comment]
Should work now :)
