### ISSUE TITLE
Scheduling multiple notifications crashes app

### ISSUE THREAD

**Issue by filipbiel** [katzer/cordova-plugin-local-notifications#542]
So, for phone gap 3.7.0 and plugin version 0.8.1, when the app tries to register more than one notification the app crashes. (Scheduling the second single notification triggers the crash.) The notifications all have different IDs (and I think correctly formated properties). The crash occurs even after cancelAll() and waiting 4 seconds between scheduling the notifications one by one. I also tried separating them in time with the "at" property. No luck. 

I'm only using phone gap build, is this solvable somehow?

**Comment by appastair** [comment]
Provide a snippet of how you're scheduling these. Of course; it's possible - I can confirm. 😉

**Comment by filipbiel** [comment]
Ok, so I have a for loop where I push all notifications to an array:

                    var notifyAt = new Date(startDate + 86400000*this.minDays + index*10);
                    if (notifyAt > now) {
                        var notification = {
                            id: notificationId,
                            title: data.title,
                            text: this.text,
                            at: notifyAt
                        };
                        notifications.push(notification);
                        notificationId++;
                    }

Then I try to schedule them once:

        cordova.plugins.notification.local.schedule(notifications, function(){
            cordova.plugins.notification.local.getAllIds(function (ids) {
                console.log('Ids[]');
                console.log(ids);
            });
        });

The array looks fine when I log it in weinre; IDs, times and all.
The weird thing is that if I just schedule them one by one instead of adding them in the loop, the app doesn't crash but some notifications aren't scheduled. AAND if I do it one by one but with a really long interval (multiple seconds) it ALSO crashes...

Help please :)

**Comment by appastair** [comment]
As I understand/recall, you pass `schedule()` a single object with the notification's parameters. You're passing it multiple.

I also recall that, if no ID is provided, it'll assign one and return the ID of the notification that was scheduled.



If I'm not wrong about all of that :arrow_up:, you should be scheduling inside your loop and pushing the response/returned ID.

It would be safer to use the function that returns all scheduled notification IDs if/when you need it rather than storing it in another way.

**Comment by filipbiel** [comment]
The second parameter for schedule() is the callback and I think chatter recommends passing them all at once in an array if you're registering multiple.

If I provide no ID it will use 0 as default for all of them which is not good as it overwrites the previous ones, right?

**Comment by katzer** [comment]
Not clear to say whats the reason. Scheduling multiple notifications with same timestamp on iOS is no good idea. At least is does not crash for me.

Please reopen if the issue still exists with latest version.
