### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by mirkofisic** [katzer/cordova-plugin-local-notifications#543]
Here is my error, I use cordova 5.0.0 plugin is installed but when I try build app show me error

C:\ksa2\platforms\android\src\de\appplant\cordova\plugin\localnotification\Local
Notification.java:564: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
C:\ksa2\platforms\android\src\de\appplant\cordova\plugin\localnotification\Local
Notification.java:561: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 15.321 secs

C:\ksa2\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\ksa2\platforms\android\gradle
w cdvBuildDebug -b C:\ksa2\platforms\android\build.gradle -Dorg.gradle.daemon=tr
ue"
ERROR building one of the platforms: Error: C:\ksa2\platforms\android\cordova\bu
ild.bat: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: C:\ksa2\platforms\android\cordova\build.bat: Command failed with exit cod
e 1
    at ChildProcess.whenDone (C:\Users\Administrator\AppData\Roaming\npm\node_mo
dules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)

**Comment by DarianLewin** [comment]
Looks similar to issue #535

In that issue, @nlinksteinar proposed the following quick-fix:

> Quick fix is to modify the block starting at LocalNotification:492 with the following:

webView.getView().post(new Runnable(){
  public void run(){
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
      webView.sendJavascript(js);
    } else {
      webView.loadUrl("javascript:" + js);
    }
  }
});

**Comment by PKnittel** [comment]
This Issue should be fixed with the last commit. 
@DarianLewin: Using your solution would brake compatibility with older cordova-versions than 4.0
