### ISSUE TITLE
I don't know if is a issue ?

### ISSUE THREAD

**Issue by bau720123** [katzer/cordova-plugin-local-notifications#544]
hi @katzer 
I am using PGB

I found a strange situation

if I only install
```
<gap:plugin name="de.appplant.cordova.plugin.local-notification" version="0.8.1" source="plugins.cordova.io" />
```
no problem at all

but !!!
after my detail survey
if you install another plugin that called
```
<gap:plugin name="nickreed.com.phonegap.plugins.facebookconnect" version="0.11.1" source="plugins.cordova.io">
 <param name="APP_ID" value="213142343242" />
 <param name="APP_NAME" value="yourname" />
</gap:plugin>
```

it will let the Android build fail

my conclusion is
if you only install facebookconnect plugin or local-notification，it will all build suucess
if you install the two of them，it will build fail that only in Android...

you can try my above Process，you will know what I mean @_@

PS
if this issue just like the "badge" plugin
already solved in "local-notifications" 0.8.2 dev
https://github.com/katzer/cordova-plugin-badge/issues/25
however, 0.8.2dev is not available in plugins.cordova.io currently ..

**Comment by k-cgomezh** [comment]
We've got the same problem.. We can't use both plugins together because the build process in PGB found 2 versions of android-support-v4.jar in the dependency list.

**Comment by bau720123** [comment]
hi @k-cgomezh 
thanks for your reply
for now I am using "cordova-plugin-local-notifications" from npm
but seem have some conflict with "megaplan-plugin-push" (push plugin)
did you have a solve way or any suggestion ?

**Comment by k-cgomezh** [comment]
hi @bau720123 
we still have the same issue, even with npm and don't know how to solve it.  :(

**Comment by axten** [comment]
same problem here, but not together with facebook connect:

https://github.com/GetVideostream/cordova-chromecast

**Comment by bau720123** [comment]
hi @katzer 
is there any further reply ?

**Comment by bau720123** [comment]
hi all
this plugin
https://www.npmjs.com/package/cordova-plugin-local-notifications-nn
solved the PGB's problem (for me)
