### ISSUE TITLE
Bugreport (App crashes) with cordova-plugin-background-geolocation

### ISSUE THREAD

**Issue by klauswaiss** [katzer/cordova-plugin-local-notifications#545]
Hey,

I found a bug (app crashes) which probably only happens if some other plugin is creating a local notification that your plugin can't handle. 

When using this plugin (https://github.com/christocracy/cordova-plugin-background-geolocation) in debug mode, cordova-plugin-local-notifications crashes the app with following error:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSJSONSerialization dataWithJSONObject:options:error:]: value parameter is nil'

The bug source is from this line in the geolocation plugin (self notify):

- (void) locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status
{
    NSLog(@"- CDVBackgroundGeoLocation didChangeAuthorizationStatus %u", status);
    if (isDebugging) {
        [self notify:[NSString stringWithFormat:@"Authorization status changed %u", status]];
    }
}

After self notify the cordova-plugin-local-notifications is receiving a notification which it obviously can't handle and therefore crashes.

So here is the line where your plugin crashes:

- (void) fireEvent:(NSString*)event notification:(UILocalNotification*)notification
{
    NSString* js;
    NSString* params = [NSString stringWithFormat:
                        @"\"%@\"", self.applicationState];

    if (notification) {
        NSString* args = [notification encodeToJSON];

The last line (notification encodeToJSON) causes the app to crash. Sometimes the line above with self.applicationstate already crashes the app. Seems a little weird :-)

Here is my code:

var bgGeo = window.plugins.backgroundGeoLocation;
		    
		    var counterrss = 0;
		    
		    var callbackFn = function(location){
			    Ext.getCmp('bvTargetTextFd').setValue('received location ok' +  counterrss);
			};
			 
			var failureFn = function(error){
			    alert('Geolocation Error');
			    Ext.getCmp('bvTargetTextFd').setValue('received location error');
			};
			 
			// BackgroundGeoLocation is highly configurable.
		    bgGeo.configure(callbackFn, failureFn, {
		        desiredAccuracy: 10,
		        stationaryRadius: 20,
		        distanceFilter: 30,
		        activityType: 'AutomotiveNavigation',
		        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
		        stopOnTerminate: false // <-- enable this to clear background location settings when the app terminates
		    });
			
			
			
			
			
			// Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
			bgGeo.start();

I will have to fix it, because I have an app to deliver. So if I find a bugfix I will post it here. Maybe it helps.

**Comment by MaliciousMustard** [comment]
Hi klauswaiss,

I'm also trying to use both background-geolocation plugin along with local-notification and I'm getting exactly the same issue. 
Did you manage to find a fix for that?

**Comment by klauswaiss** [comment]
no, but to avoid the bug I guess you can just comment out a line of code that is not necessary anyway: comment out the self notify (see code below) in APPLocalNotification.m 


- (void) locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status
{
    NSLog(@"- CDVBackgroundGeoLocation didChangeAuthorizationStatus %u", status);
    if (isDebugging) {
        [self notify:[NSString stringWithFormat:@"Authorization status changed %u", status]];
    }
}




or setting the debug flag to false (in your javascript coce) should also help probably:

bgGeo.configure(callbackFn, failureFn, {
            desiredAccuracy: 10,
            stationaryRadius: 20,
            distanceFilter: 30,
            activityType: 'AutomotiveNavigation',
            debug: false,

**Comment by MaliciousMustard** [comment]
Yes, I have already commented out the debug flag to make it work, but I need to set it back to true when not in production environment for debugging purposes. 
I'll try commenting out the line in APPLocalNotification.m! 
But ideally, what needs to change is the local-notification plugin, to not assume that all the notifications it receives are with JSON format, or at least to fail silently!

Thank you for your help!

**Comment by ian-katsuno** [comment]
Hi! 

I am having the same issue - a conflict between Katzer's local-notification-plugin and the background-geolocation plugin. 

I tried commenting out the didChangeAuthorizationStatus() definition in CDVLocation.m but it did not help. Still getting the same error.

Any updates on this issue?

**Comment by katzer** [comment]
Would be great to see a PR for it!

**Comment by rwillett** [comment]
I've just run into this problem.

I have the premium background location plugin from 

https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/api.md

The background location plugin is com.transistorsoft.cordova.background-geolocation 1.2.0

and 

the local notification plugin 

de.appplant.cordova.plugin.local-notification 0.8.2 "LocalNotification"

As a temporary fix, I have commented out these lines in AppLocalNotification.m to get things going so other people have a temporary (and not very good fix). This is simply a hack to avoid the interaction issue between the two plugins and stops the local notifications working properly (which I can live with whilst debugging the background geolocation plugin). Clearly it is not a proper fix. However my Objective-C skills are rubbish, so it may take some time to work a fix.

```
/**
 * Fire event for local notification.
 */
- (void) fireEvent:(NSString*)event notification:(UILocalNotification*)notification
{
    /* RBW - REMOVE THESE COMMENTS
     NSString* js;
    NSString* params = [NSString stringWithFormat:
                        @"\"%@\"", self.applicationState];

    if (notification) {
        NSString* args = [notification encodeToJSON];

        params = [NSString stringWithFormat:
                  @"%@,'%@'",
                  args, self.applicationState];
    }

    js = [NSString stringWithFormat:
          @"cordova.plugins.notification.local.core.fireEvent('%@', %@)",
          event, params];

    if (deviceready) {
        [self.commandDelegate evalJs:js];
    } else {
        [self.eventQueue addObject:js];
    }
     */ // RBW REMOVE THESE COMMENTS
}
```

I'll try and see if I can find a fix but any help welcomed. Since other people have the same plugin issue, somebody must have worked it out (he says hopefully). The debugging flag on the background geolocation is pretty useful, not using it is not an option for us.

Rob

**Comment by rwillett** [comment]
I've had a look and can't see how to check whats going on. I suspect bit cannot prove that the background geolocation plugin is NOT filling out all the fields correctly, but its beyond my limited Objective-C skills to debug it. 

Apologies

Rob

**Comment by andersborgabiro** [comment]
I just ran into this problem myself. The question is why the background geolocation plugin is issuing local notifications. A plugin should be UI-less, unless it is a UI itself.

**Comment by rwillett** [comment]
This is because the background geolocation plugin has been configured to send out debug notifications. This issue only arises in debug mode on the geolocation plugin.

**Comment by andersborgabiro** [comment]
But I can't even build the app. Isn't debug mode a run-time configuration?

**Comment by rwillett** [comment]
Then there is a different problem. 

Raise a new issue so as not to pollute this one.

**Comment by andersborgabiro** [comment]
I have. It might be specific to PGB though, as I have to use '-mm'.

**Comment by rwillett** [comment]
I don't use PGB so can't comment.

**Comment by andersborgabiro** [comment]
I sometimes wish I didn't :).
