### ISSUE TITLE
Android: plugin fails to install (expected older nomenclature for device dependency)

### ISSUE THREAD

**Issue by Tawpie** [katzer/cordova-plugin-local-notifications#546]
(!599)-> cordova plugin add ../cordova-plugin-local-notifications
Installing "de.appplant.cordova.plugin.local-notification" for android
Fetching plugin "https://github.com/apache/cordova-plugin-device" via git clone
Failed to install 'de.appplant.cordova.plugin.local-notification':Error: Expected fetched plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".

The fix/workaround is to edit plugin.xml line 21 so that it reads:
`<dependency id="cordova-plugin-device" url="https://github.com/apache/cordova-plugin-device" />`

**Comment by katzer** [comment]
Has been fixed with prior updates.
