### ISSUE TITLE
WP8.1 error and crash when clicking on notification in tray

### ISSUE THREAD

**Issue by Tawpie** [katzer/cordova-plugin-local-notifications#549]
When you click on a fired notification in the windows notification tray, the relaunch of the app generates the following error:

`Exception is about to be caught by JavaScript library code at line 298, column 9 in ms-appx://com.a2morrowinc.hsq1/www/plugins/de.appplant.cordova.plugin.local-notification/src/windows/LocalNotificationUtil.js

0x800a138f - JavaScript runtime error: Unable to get property 'at' of undefined or null reference

If there is a handler for this exception, the program may be safely continued.`

A brute force fix for this specific error is to modify LocalNotificationUtil.js:295 to use new Date() if .at property is undefined. However, the error more serious because if the app has been destroyed by the OS (simulate this by clicking the lifecycle event "suspend and shutdown"), clicking on a notification in the tray causes the app to crash because the .event property of undefind. I suspect that throughout the notification object is undefined and I think that's at the root of the errors.

**Comment by katzer** [comment]
hey @Tawpie, would you post some code snippets please. I cannot reproduce the described error.

**Comment by Tawpie** [comment]
That's not so easy -- our code is long and complex (and yes, we use hungarian notation)! To generate the notifications, we create 17 objects and schedule them in an array. This is the code that builds the array:

`                        if (!bAbort) {
                            // build a json metadata string for use during unpacking
                            var sMetaData = '{"rcls":"' + oReminder.timing + '","nid":"' + oReminder.id + '"}';

                            // create the fire schedule
                            var fDesiredAddedSeconds = 0;
                            if (oReminder.timing === "AM") {
                                fDesiredAddedSeconds = typeof iSecondsFromNow !== 'undefined' ? iSecondsFromNow :
                                +getLS(klssAppSettingsReminderPrefix + "MorningHour") * 24 * kSecondsPerHour;
                            } else if (oReminder.timing === "PM") {
                                fDesiredAddedSeconds = typeof iSecondsFromNow !== 'undefined' ? iSecondsFromNow :
                                +getLS(klssAppSettingsReminderPrefix + "EveningHour") * 24 * kSecondsPerHour;
                            }
                            if (giNextDayHappensIn !== kSecondsPerDay) {    // Scaling day
                                fDesiredAddedSeconds = fDesiredAddedSeconds * gfTestDayRatio;
                            }
                            //console.log("lM.fQLM - dBaseDate:" + dBaseDate + " iSFN:" + iSecondsFromNow + " fDAS:" + fDesiredAddedSeconds);
                            var iReminderDate = dateAdd(dBaseDate, fDesiredAddedSeconds, "second");

                            // for dev, munge the message to indicate source/reason for reminder on the notifications screen
                            // this doesn't show up in-app
                            if (kReleaseMode === kDev_Only) {
                                var dFireDate = new Date(iReminderDate);
                                oReminder.headline = oReminder.id +
                                " " + dFireDate.toLocaleDateString() +
                                oReminder.timing;
                                // stuff before ^ will be the notification title and will be stripped from the body by reminder_plugin.js:alarmNotify
                                oReminder.displaytext = oReminder.prereq1 + "^" + oReminder.messagetype + " " + oReminder.displaytext;
                            }

                            // don't bother if the 'at' date is not more than a minute from now
                            var dCutoffDate = dateAdd((new Date()), 1, "minute");
                            if ((new Date(iReminderDate)) > dCutoffDate) {
                                // build a basic reminder
                                oKatzerLNPluginReminder = {
                                    id: i + 1,
                                    at: (new Date(iReminderDate)),    // MUST be a date object
                                    text: oReminder.displaytext,
                                    title: oReminder.headline
                                    //smallIcon: "res://sm_notif.png"
                                };

                                // add options that require us to think...
                                // lookup to see if sound is enabled, if not, turn it off
                                if (coreData.getReminderMaskSoundEnabled() == 0) {
                                    oKatzerLNPluginReminder.sound = null;
                                }

                                if (typeof sMetaData !== 'undefined') {
                                    oKatzerLNPluginReminder.data = sMetaData; // Data to be passed through the notification
                                }

                                // add reminder object to the array for Katzer multiple scheduling
                                aMultiRemindersForKatzerLNPlugin.push(oKatzerLNPluginReminder);
                                console.log("lM.fQLM - length:" + aMultiRemindersForKatzerLNPlugin.length + " id:" + oKatzerLNPluginReminder.id + " at:" + (new Date(oKatzerLNPluginReminder.at)).toString() + " text:" + oKatzerLNPluginReminder.text);
                            }
                        }
                    }`

When we actually schedule, we do it in a timeout because the cancelAll method takes 4+ seconds to run.

`                       console.log("lM.fQLM - scheduling >" + aMultiRemindersForKatzerLNPlugin.length + "< local reminders");
                        var iStartTime = (new Date()).getTime();    // for debug to check timing
                        gaMultiRemindersForKatzerLNPlugin = aMultiRemindersForKatzerLNPlugin;   // a global for the callback
                        setTimeout(cordova.plugins.notification.local.cancelAll(function scheduleChunkifierQueue() {
                            console.log("lM.fQLM - cancellation completed. Elapsed: " + ((new Date()).getTime() - iStartTime) / 1000 + " secs");
                            cordova.plugins.notification.local.schedule(aMultiRemindersForKatzerLNPlugin);
                        }),1);
`

It's odd, when you request the list of scheduled notifications and count them, it says 34 notifications are scheduled. This actually might have something to do with the problem as half of those are not intended!

`/* ---------------- Katzer local notifications -------------- */
function testGetScheduledLNCount() {
    var aList = [];
    cordova.plugins.notification.local.getScheduled(function (notifications) { aList = notifications });
    return aList.length;
}

function testGetScheduledLNs() {
    var aList = [];
    cordova.plugins.notification.local.getScheduled(function (notifications) { aList = notifications });
    return aList;
}
`

**Comment by katzer** [comment]
See 2383f32e4a9157e319993d5c8e76ab11dc8eb741
