### ISSUE TITLE
unable to use plugin

### ISSUE THREAD

**Issue by ekambarrao** [katzer/cordova-plugin-local-notifications#550]
hi, installed plugin, it was working fine till two days ago, is now obsolete and new installation is not bringing up the plugin in visual studio. Please let me know what could be the issue. thx

**Comment by hdezela** [comment]
Getting these errors with NetBeans after upgrading to cordova 5.0.0:

    D:\WEBDEVEL\FuxionApp\platforms\android\src\de\appplant\cordova\plugin\localnotification\LocalNotification.java:564: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
      symbol:   method evaluateJavascript(String,<null>)
      location: variable webView of type CordovaWebView
    D:\WEBDEVEL\FuxionApp\platforms\android\src\de\appplant\cordova\plugin\localnotification\LocalNotification.java:561: error: cannot find symbol
        webView.post(new Runnable(){
      symbol:   method post(<anonymous Runnable>)
      location: variable webView of type CordovaWebView

**Comment by MayankLogiciel** [comment]
I am getting this error while running cordova ionic project after updating cordova to latest 5.0.0 version.

:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaD:\GitHub\JobProgressPlus\jp_mobile_app_plus\platforms\android\src\de\appplant\cordova\plugin\localnotification\LocalNotification.jav
a:495: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
D:\GitHub\JobProgressPlus\jp_mobile_app_plus\platforms\android\src\de\appplant\cordova\plugin\localnotification\LocalNotification.java:492: error: can
not find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
 FAILED
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.

BUILD FAILED

Total time: 1 mins 5.46 secs
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

D:\GitHub\JobProgressPlus\jp_mobile_app_plus\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "D:\GitHub\JobProgressPlus\jp_mobile_app_plus\platforms\android\gradlew cdvBuildDebug -b D:\GitHub\JobP
rogressPlus\jp_mobile_app_plus\platforms\android\build.gradle -PcdvBuildArch=arm -Dorg.gradle.daemon=true"
ERROR running one or more of the platforms: Error: D:\GitHub\JobProgressPlus\jp_mobile_app_plus\platforms\android\cordova\run.bat: Command failed with
 exit code 8
You may not have the required environment or OS to run this project

**Comment by improvi** [comment]
same here. Looking for a fix at the earliest!

**Comment by hdezela** [comment]
This seems to be the same as https://github.com/katzer/cordova-plugin-local-notifications/issues/535, the fix suggested by nlinksteinar fixed it for me.

As for Visual Studio, you need to download the repository and remove line 23 from plugin.xml, then load it from your local file.

**Comment by MrAntix** [comment]
fyi line 23 is         <engine name="cordova" version="<4.0.0" />

**Comment by katzer** [comment]
That issues have been fixed with previous updates
