### ISSUE TITLE
unable to get() an existing notifications on ios

### ISSUE THREAD

**Issue by smknstd** [katzer/cordova-plugin-local-notifications#551]
I installed latest plugin version (0.8.2dev). Everything works fine on android but my app crashes on ios when I do the following seq (if notification 1 does not exist yet):

ok -> window.plugin.notification.local.get(1)
ok -> window.plugin.notification.local.schedule({
                                id: 1,
                                title: title,
                                text: text,
                                at: timestamp
                            })
ok -> window.plugin.notification.local.update({
                                    id: 1,
                                    title: title,
                                    text: text,
                                    firstAt: timestamp,
                                    every: "day"
                                })
ko -> window.plugin.notification.local.get(1)

to me, it looks close to this : https://github.com/katzer/cordova-plugin-local-notifications/issues/473

Thank you for your help :)

**Comment by smknstd** [comment]
same exception: "Invalid type in JSON write (__NSDate)"

**Comment by mrmwiebe** [comment]
I can second this, I'm getting the same exception as @smknstd.

**Comment by mrmwiebe** [comment]
On further tests and experiments, I was able to use cordova.plugins.notification.local.getScheduled() successfully.  I was getting this exception when using cordova.plugins.notification.local.getAll().  Not ideal, but it works!

**Comment by katzer** [comment]
Please reopen if this issue still exists with latest version.
