### ISSUE TITLE
Uncaught TypeError: Cannot call method 'apply' of undefined at local-notification-util.js:252

### ISSUE THREAD

**Issue by hagaisela** [katzer/cordova-plugin-local-notifications#557]
I am getting this error on  android 4.4 (LG G2). I am not sure when exactly it happens, it may be when I click a notification when the app is not running.

**Comment by appastair** [comment]
Without providing anything other than the error message to attempt reproduction, we can only guess as to the cause. My guesses...:

1. You have not included some necessary JavaScript (or it has not yet been run when you're hitting this error).
1. You have specified a callback function for your notification but failed to define the function.

**Comment by hagaisela** [comment]
My bad, it was 2. The function was defined in the wrong object. Suggestion - check if the function is defined and log it's name as an error message instead of just failing to call it.

**Comment by appastair** [comment]
I don't think that callback-checking would really benefit anyone. The error told you it's undefined. A routine chock to log tyecsame thong seems overkill but adding your own wouldn't be tough. 😛

Extend the function (or callback) with something like `(typeof(callback) !== 'function'){}`. Outside of development/debugging, type-checking every time seems overkill.


Anyway - I'm glad you fixed it!! 🙌

**Comment by katzer** [comment]
Please reopen
