### ISSUE TITLE
Trigger event from coldstart

### ISSUE THREAD

**Issue by nicopmsi** [katzer/cordova-plugin-local-notifications#558]
First, thank you very much for your great work and the improvements of the plugin.
I try to retrieve the notification datas when a user click on it when application is not running (coldstart). The "trigger" event is effectively dispatched and I can retrieve all the datas I need.
But unfortunately this event take long time to be triggered after the application start (around 20s I think), though ondeviceready event was fired immediately after the start.
Is there a way to shorten this delay of "trigger" event fire at the start of application (coldstart)? 

Thank you very much!

**Comment by katzer** [comment]
@nicopmsi The plugin events will get fired after all deviceready events have been called. Otherwise the app could not register for plugin events. If it takes that long time than your app takes long time to start ;)

**Comment by Syirrus** [comment]
> First, thank you very much for your great work and the improvements of the plugin.
> I try to retrieve the notification datas when a user click on it when application is not running (coldstart). The "trigger" event is effectively dispatched and I can retrieve all the datas I need.
> But unfortunately this event take long time to be triggered after the application start (around 20s I think), though ondeviceready event was fired immediately after the start.
> Is there a way to shorten this delay of "trigger" event fire at the start of application (coldstart)?
> 
> Thank you very much!

How are you able to get this to work from a cold start?
