### ISSUE TITLE
Open app by notification

### ISSUE THREAD

**Issue by volodymyrl** [katzer/cordova-plugin-local-notifications#559]
I read the documentation for Local Notifications plugin but didn't find answer for next questions:
1) Is it possible open app by clicking on the notification message?
2) Can I check some condition before run the schedule notification?

Can some one give me answers or advice how I can implement it.
Thanks!

**Comment by appastair** [comment]
1. Have you tried this without success?
1. Whatever the conditions might be that could change between scheduling and triggering a notification, you could easily cancel it. If it's a change that happens  remotely, you should be using GCM/etc., not local notifications.

**Comment by volodymyrl** [comment]
@appastair thanks for you answers! 
1) I resolved it by adding $state.go("mystate");
2) The task is: once per day I need send a request to the server and if I get updates, app must show the notification with results. If not waiting for next day.

**Comment by appastair** [comment]
I'm glad!

I don't know exactly what you're up to but push notifications will save everyone involved a lot of needless requests.

**Comment by katzer** [comment]
@volodymyrl 
> Is it possible open app by clicking on the notification message?

Yes, thats the default behavior

> Can I check some condition before run the schedule notification?

Thats very use case specific. If the app received some data it may schedule a notification or wait longer.
