### ISSUE TITLE
notification data is returned as a JSON string

### ISSUE THREAD

**Issue by nexus-uw** [katzer/cordova-plugin-local-notifications#560]
As documented in the wiki, when I attach an object to a notification's data property, this plugin serializes it as JSON before passing it off to the native notification. But when I get the notification back, (ie. in the ```.on('clear',cb)``` event handler), the data field is a JSON string.

Should the plugin not parse this data string back into an object before it reaches the plugin user's?

Thanks,
Simon

**Comment by bboyairwreck** [comment]
Hey nexus-uw, Thank you for pointing that out. I was having a lot of trouble trying to figure out why i kept getting undefined. just had to do a JSON.parse(notificaiton.data) to fetch my variables out of it.

So yeah they definitely should make this automatically parse to JSON rather than converting the json string ourselves

**Comment by katzer** [comment]
@bboyairwreck The plugin does not convert the data itself since its not expected to be JSON

**Comment by kwvanderlinde** [comment]
@katzer The README suggests otherwise in this sample:

```javascript
cordova.plugins.notification.local.schedule({
    id: 1,
    title: "Production Jour fixe",
    text: "Duration 1h",
    firstAt: monday_9_am,
    every: "week",
    sound: "file://sounds/reminder.mp3",
    icon: "http://icons.com/?cal_id=1",
    data: { meetingId:"123#fg8" }
});

cordova.plugins.notification.local.on("click", function (notification) {
    joinMeeting(notification.data.meetingId);
});
```

This suggests that the 'data' field ought to be automatically deserialized as JSON.
