### ISSUE TITLE
How to use bigview?

### ISSUE THREAD

**Issue by plrthink** [katzer/cordova-plugin-local-notifications#561]
I find a merged PR at #92, but don't find any documents about this feature, is this still alive?

**Comment by plrthink** [comment]
I mean how to add action button to notifications.

**Comment by plrthink** [comment]
like this in [android docs](http://developer.android.com/training/notify-user/expanded.html#)

![android notification with actions](http://developer.android.com/images/training/notifications-bigview.png
)

How can I add action button to notifications?

**Comment by ptbrowne** [comment]
I am also interested in this functionality. I cannot see support for actions in the PR though so I guess that if we want it, we should submit a PR ourselves. It does not seem so hard though. I might do this if I find the time.

**Comment by katzer** [comment]
Action buttons are coming soon. Theres an open issue and PR for it

**Comment by plrthink** [comment]
:+1:
