### ISSUE TITLE
No badge on android 4.4

### ISSUE THREAD

**Issue by hagaisela** [katzer/cordova-plugin-local-notifications#563]
Hi,
I am trying to add a local notification with a badge to android 4.4 (LG G2). the badge works on iphone 4 but not on my LG. I am using cordova android platform 3.7.1. This test reproduces the problem:

https://drive.google.com/file/d/0B91Vmp4A3YOuWDB6OU16NVlKR1k/view?usp=sharing

Thanks.

**Comment by katzer** [comment]
@hagaisela Where do you expect to find the badge? On iOS its on the home screen, for Android its part of the notification. See the badge plugin for some more functionality
