### ISSUE TITLE
__NSCFNumber isEqualToString

### ISSUE THREAD

**Issue by alxgrn** [katzer/cordova-plugin-local-notifications#564]
This issue (#526) still exists in 0.8.1 release.

2015-05-21 17:43:16.775 ComicConRussia[81699:8207247] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xb000000000000003
2015-05-21 17:43:16.777 ComicConRussia[81699:8207247] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xb000000000000003'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e292c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001105f2bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010e29a0ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010e1f013c ___forwarding___ + 988
	4   CoreFoundation                      0x000000010e1efcd8 _CF_forwarding_prep_0 + 120
	5   ComicConRussia                      0x000000010e058b0d -[UIApplication(APPLocalNotification) localNotificationWithId:] + 461
	6   ComicConRussia                      0x000000010e055eaa -[APPLocalNotification cancelForerunnerLocalNotification:] + 170
	7   ComicConRussia                      0x000000010e055ade -[APPLocalNotification scheduleLocalNotification:] + 62
	8   ComicConRussia                      0x000000010e052c67 __33-[APPLocalNotification schedule:]_block_invoke + 471
	9   libdispatch.dylib                   0x0000000110d0d186 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x0000000110d2c614 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x0000000110d16552 _dispatch_root_queue_drain + 1768
	12  libdispatch.dylib                   0x0000000110d17b17 _dispatch_worker_thread3 + 111
	13  libsystem_pthread.dylib             0x0000000111099637 _pthread_wqthread + 729
	14  libsystem_pthread.dylib             0x000000011109740d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

notification code:
    cordova.plugins.notification.local.schedule({
        text: "Hello"
    });

phonegap plugins list
de.appplant.cordova.plugin.local-notification 0.8.1 "LocalNotification"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.inappbrowser 0.6.0 "InAppBrowser"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.apache.cordova.statusbar 0.1.10 "StatusBar"

**Comment by arlg** [comment]
Same here. Is there a fix ?

**Comment by arlg** [comment]
@alxgrn Try to remove and add the plugin with this line, it will use the latest version ( in the wiki : cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications )

**Comment by alxgrn** [comment]
@arlg I use this command:
phonegap plugin add de.appplant.cordova.plugin.local-notification
and it install the version 0.8.1.
As I know 0.8.1 is the latest version, is not it?

**Comment by arlg** [comment]
Apparently there is a 0.8.2 dev version that fixes this issue ( I don't get it and notifications works : )

Here is my cordova plugin list : 

de.appplant.cordova.common.registerusernotificationsettings 1.0.1 "RegisterUserNotificationSettings"
de.appplant.cordova.plugin.local-notification 0.8.2dev "LocalNotification"

**Comment by giriprashaad** [comment]
The issue still exists in 0.8.2 dev version.

2015-09-11 11:57:24.226 astellasBVF[12651:5898042] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x17e342e0
2015-09-11 11:57:24.227 astellasBVF[12651:5898042] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x17e342e0'
*** First throw call stack:
52afef 0x367dac8b 0x28530409 0x2852e327 0x2845de78 0x513bd 0x50ef7 0x5333b 0x531b5 0x4c82d 0x36d452e3 0x36d4f381 0x36d503c3 0x36eacdc1 0x36eacb14)
libc++abi.dylib: terminating with uncaught exception of type NSException
Process 12651 stopped
* thread #8: tid = 0x59ff3a, 0x36e30df0 libsystem_kernel.dylib`__pthread_kill + 8, queue = 'com.apple.root.default-qos', stop reason = signal SIGABRT
    frame #0: 0x36e30df0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x36e30df0 <+8>:  blo    0x36e30e08                ; <+32>
    0x36e30df4 <+12>: ldr    r12, [pc, #0x4]           ; <+24>
    0x36e30df8 <+16>: ldr    r12, [pc, r12]
    0x36e30dfc <+20>: b      0x36e30e04                ; <+28>


Any temporary fix available?

**Comment by GitRubb** [comment]
There's 4 active issues marked with this same bug.

Any fix coming this year?

**Comment by katzer** [comment]
@alxgrn @GitRubb I will add a catch block to prevent the crash. But the real issue is that the notification has an __ID which is not a Number__
