### ISSUE TITLE
ghost application after click in notification

### ISSUE THREAD

**Issue by Distopico** [katzer/cordova-plugin-local-notifications#565]
After click in notification It appears a second app in black and the real app, when I click in app black this trigger the last notificacion although this canceled, in some cases this behavior crash the app

Android 4.4
Tablet 

![app](http://a.pomf.se/qpncvf.png)

**Comment by katzer** [comment]
@Distopico Please reopen if the issue is still existent in latest version.

**Comment by Distopico** [comment]
:+1:
