### ISSUE TITLE
Parse Issue for the parameter passed

### ISSUE THREAD

**Issue by 1wQasdTeedFrsweXcs234saS56Scxs5423** [katzer/cordova-plugin-local-notifications#566]
Hi,

I am getting a parse issue in the following section of the code for UIUserNotificationSettings*

/**
 * Called on otification settings registration is completed.
 */
- (void) didRegisterUserNotificationSettings:(UIUserNotificationSettings*)settings
{
    if (_command)
    {
        [self hasPermission:_command];
        _command = NULL;
    }
}

**Comment by katzer** [comment]
Please reopen if the issue still exists with latest version. Tks!
