### ISSUE TITLE
Ionic join local notifications8.1,ionic build Android failed

### ISSUE THREAD

**Issue by zoucaitou** [katzer/cordova-plugin-local-notifications#567]
:compileDebugJavaD:\hybrid\ionic\platforms\android\src\de\appplant\cordova\plugin\localnotification\LocalNotification.java:495: 
                    webView.evaluateJavascript(js, null);
                           ^
  evaluateJavascript(String,<>)
  ΪCordovaWebView webView
D:\hybrid\ionic\platforms\android\src\de\appplant\cordova\plugin\localnotification\LocalNotification.java:492: 
        webView.post(new Runnable(){
               ^
   post(<Runnable>)
  λΪCordovaWebViewwebView
ע: D:\hybrid\ionic\platforms\android\src\com\ionic\keyboard\IonicKeyboard.java API
ע:  -Xlint:deprecation 
2 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by pavei** [comment]
+1

**Comment by MikeBateman** [comment]
+2

**Comment by rcdilorenzo** [comment]
I'm seeing this issue as well. +1

**Comment by zoucaitou** [comment]
Configure the Android SDK environment variables，if you project add the android, execute 1.ionic  platform remove android,  2. ionic platform add android, 3.ionic build android , done!!!! I don't know why

**Comment by VanDalkvist** [comment]
@zoucaitou - it's not working for me

**Comment by zoucaitou** [comment]
@VanDalkvist  You can try changing local notifications to version 0.7.8

**Comment by zoucaitou** [comment]
@VanDalkvist  You can try changing local notifications to version 0.7.8

**Comment by zoucaitou** [comment]
@VanDalkvist  You can try changing local notifications to version 0.7.8

**Comment by zoucaitou** [comment]
@VanDalkvist  You can try changing local notifications to version 0.7.8

**Comment by Trexology** [comment]
@zoucaitou Downgrading local notification will not work for Cordova cli 5.0

Failed to install 'de.appplant.cordova.plugin.local-notification':Error: Expected plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".

Due to the naming convention of plugin ID as mentioned here: http://stackoverflow.com/questions/29945563/html5video-cordova-android-plugin-wont-install-error-using-cli

Still need a proper solution to this.

**Comment by olieidel** [comment]
+1. Build does not seem to work with Ionic.

**Comment by oscaruiz** [comment]
I also have this problem. If I download the plugin and try to build it I get a faillure and if I remove the plugin it works again.

**Comment by Pierre-Gilles** [comment]
+1 Same issue for me...

**Comment by katzer** [comment]
That shall be no issue anymore, Please reopen if the issue is still existent in latest version.
