### ISSUE TITLE
trigger event is not fired until notification is swiped/clicked/etc.

### ISSUE THREAD

**Issue by Alex-Sessler** [katzer/cordova-plugin-local-notifications#568]
First of all, thanks for this great Plugin... really makes the job easier!

I'm using the Plugin to schedule a notification immediately and am using the 'trigger' listener to set a flag for the notification to not be scheduled again (I'm calling the schedule function in a $interval). The notification is delivered as expected but it is scheduled over and over again, meaning that the block of the trigger event listener is not being executed when the notification appears. After I've clicked or dismissed the notification, everything is fine.

Again, thanks a lot and keep up the great work!

**Comment by katzer** [comment]
Please reopen and post a code snippet if the issue is still existent in latest version

**Comment by NBAMj** [comment]
I'm facing the same issue using 0.9-Beta on Android 8.
You need to click or dismiss the notification in order to be able to add a new notification with the same notification id
