### ISSUE TITLE
iOS: clicking on notification too quickly does not trigger the "on" callbacks

### ISSUE THREAD

**Issue by mysegfault** [katzer/cordova-plugin-local-notifications#570]
Which is quite annoying because you always want to trigger the "on" callback if you set on. After some research, it appeared that this code was the source of this misbehavior:

NSString* event = (timeInterval <= 1 && deviceready) ? @"trigger" : @"click";

=> if I change 1 for 0.1, it always goes to "click" and so trigger the listeners. Why do you need the "trigger" event ? Should you remove it ? At least, 1 sec is too long to way to trigger click.

**Comment by jclardy** [comment]
I saw this also. If I tapped a notification right after it came in my app would open but no callback would be made.

**Comment by katzer** [comment]
@mysegfault I will see if it makes sense to decrease the timeframe

**Comment by katzer** [comment]
@mysegfault I have decreased the time-frame to 200 milli seconds. Clicking that fast on notifications only happens while testing.

**Comment by mysegfault** [comment]
Sounds good. Thanks.
