### ISSUE TITLE
How to schedule for repeat days like Monday 8:40 AM, Tuesday 8:40AM and similar?

### ISSUE THREAD

**Issue by manoj529** [katzer/cordova-plugin-local-notifications#572]
I have a scenario where i need to schedule notifications as 
 
morning 8:30 AM  -monday,tuesday,saturday
evening 7:00 PM - Wed,Thursday,Friday

so how do i set the parameters of schedule, The current documentation is not that clear.

example :
                var alarmTime = new Date();
                alarmTime.setMinutes(alarmTime.getMinutes() + 1);
                $cordovaLocalNotification.schedule({
                    id: 'test12',
                    at : alarmTime,     <--------- or StartAT parameter should i enter day of week
                    every:'day',            <---------where should i set day of week like monday,tues...etc
                    message: "This is a message for the tablet",
                    title: "This is a title",
                    autoCancel: true,
                    sound: null
                }).then(function() {
                    console.log("The notification has been set");
                }); 

Please provide me with proper sample of usage.

**Comment by jimibi** [comment]
Hi manoj529,
In your case it is necessary to have one notifications by day.
And select:
- every: "week",
- firstAt: day and hour of the notification

**Comment by manoj529** [comment]
Thank You for the reply Jimibi,

So according to your procedure i have to first calculate when is monday in future calender from the current date and then set that in firstAt followed by the every:week option as

at, firstAt : Date or Number
The date and time when the system should deliver the local notification. If the specified value is nil or is a date in the past, the local notification is delivered immediately.
- Default: now ~ new Date()

as According to the document it takes date and time not day and time.

**Comment by manoj529** [comment]
Anyhow i have written a custom coding to calculate the next occuring for monday or required day and hard scheduled it
