### ISSUE TITLE
Cannot read property 'notification' of undefined

### ISSUE THREAD

**Issue by EpaXapate** [katzer/cordova-plugin-local-notifications#573]
When I try to execute this function: 

cordova.plugins.notification.local.schedule({
			id: noteId++,
			title: getAlarmTitle,
			text: getAlarmDesc,
			sound: isAndroid ? 'file://sound.mp3' : 'file://beep.caf',
			data: { secret:key }
		});

It always gives me this error ( Cannot read property 'notification' of undefined ). Does anyone know how to fix this?

**Comment by pavei** [comment]
+1

**Comment by EpaXapate** [comment]
Nevermind, it appeared I forgot that nothing is supposed to happen in the browser because this plugin is not browser supported.

**Comment by roysG** [comment]
what do u mean running on broweser?

on mobile console command? or on chrome ?

**Comment by Group-TimTeam** [comment]
For mobile app

If you have properly installed the plugin, maybe the problem is your function call that is situate outside the event "device ready" or, if you are in the event "device ready", your call is too early (before the initialization of the plugin)

To check on your place a setTimeout call.
