### ISSUE TITLE
Small Icon shows in tray, but not in list view

### ISSUE THREAD

**Issue by slikk66** [katzer/cordova-plugin-local-notifications#574]
Here are 2 screenshots of what I'm getting, this is same behavior on Android emulator and my phone, my phone is running Lollipop, and I've gotten same on Android emulator Lollipop as it's the only OS that I believe supports the small icon inside the large icon format on the notification list.

I've set the smallIcon value in my notification schedule.. if I don't, then I get the bell in the top, and I see the full icon + bell in the pulldown,   But when I do set the smallIcon I see it at the top, but if I drag down the notification list, I get a white square.

```window.plugin.notification.local.schedule({ id: 1, title: 'New Alert', message: 'Message', smallIcon:'res://icon', sound: null, led: "FF0000"});```

With this declaration here, this is what I get at top:

![fullicon](https://cloud.githubusercontent.com/assets/633269/7893003/3073014c-060e-11e5-928c-c89329654642.jpg)

But when I pull down from top of screen, this shows up:

![missing](https://cloud.githubusercontent.com/assets/633269/7893007/3dfd8f30-060e-11e5-98e3-1ec05f541015.jpg)

Seems like it's set but not set at the same time!

Any tips?

**Comment by slikk66** [comment]
Ok, found out the small icon has to be transparent. Still working on getting it correct, but here's a page that will help you make some:https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_example

Anyone know the exact path to put the icon in?

**Comment by blakerego** [comment]
I'm also having problems setting icons from images on the device. I'm working on an Ionic app that is targeted towards iOS.  

In the icon parameter, I've used 'file://img/image.png' as well as 'res://image.png', but neither worked.  Are there specific sizes that the images need to be for these to display properly?  I've been using the following code - 

  var alarmTime = new Date();
      alarmTime.setMinutes(alarmTime.getMinutes() + 15);

    $cordovaLocalNotification.schedule({
      id: Math.random().toString(),
      date: alarmTime,
      message: 'Timeout Warning',
      title: 'Return to prevent your session from expiring.',
      autoCancel: false,
      icon: 'file://img/image.png'
    }, $scope);

The notification is working well, but I'm having problems getting the desired icon to show up.  If there is more detailed documentation regarding the image option parameters, please point me towards it.

**Comment by katzer** [comment]
Please reopen if the issue still exists with latest version. Tks!
