### ISSUE TITLE
Notification For Few Days

### ISSUE THREAD

**Issue by myprojects1** [katzer/cordova-plugin-local-notifications#576]
Hi,

Can you please help me about how to set notification for few days only (example from today to next 10 days).

**Comment by dansanti** [comment]
you need to modify the code, making a method that get limit time from ie from js parse in data object data:{fecha_t: "date"}, and make a reader in options.java 
public boolean continue(){
JSONObject data  = new JSONObject(options.optString("data","{}"));
			
			String fecha_t=(String) data.get("fecha_t");

and compare if can continue or not
return true or false
}
 and in  notification.java on method  public boolean isRepeating () {
return (getOptions().getRepeatInterval() > 0 && options.continue());
}

**Comment by katzer** [comment]
Thats not possible without doing some own logic within the callbacks and cancel it manually
