### ISSUE TITLE
download plugin for MAC OS 10.8.5

### ISSUE THREAD

**Issue by cordova-android** [katzer/cordova-plugin-local-notifications#579]
i try to download plugin in terminal using command
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications

my os:MAC OS 10.8.5

before download BUILD SUCCEEDED

but after download plugin i get error 

------------------------------------------- 
error: Command failed: /bin/sh -c git clone "https://github.com/katzer/cordova-plugin-local-notifications" "/var/folders/s0/x_bcn18d51zd33vx03tltwm40000gn/T/git/1433249592654"
dyld: lazy symbol binding failed: Symbol not found: ___strlcpy_chk
  Referenced from: /usr/local/git/bin/git
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___strlcpy_chk
  Referenced from: /usr/local/git/bin/git
  Expected in: /usr/lib/libSystem.B.dylib

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
------------------------------------------- 

so , i need to help to solve this problem

**Comment by mix3d** [comment]
The issue is that the plugin didnt download correctly. Try manually downloading a zip of the plugin, unpacking, then doing `cordova plugin add ../path/to/folder`
