### ISSUE TITLE
Scheduled Notification does not trigger when time is changed manually in phone

### ISSUE THREAD

**Issue by manoj529** [katzer/cordova-plugin-local-notifications#582]
I did a through testing of notifications behavior and found the following bugs or can say this needs improvements.
Example: I scheduled the notifications with the below timings
Monday 8 30 AM 6 30 PM
Every week Repeat
And found the below observations by changing the time of phone manually: 
if i set the time to Monday ---  8 35 AM -- It works fine
if i set immediately to 6 35 PM and test--- It works fine
if i set the time to Next week Monday --- 8 35 AM --- It works fine

But the issue comes when i change the time to past i'e 

if i set the time to Monday 11 PM i'e around 3 hrs post the scheduled time and test -- It wont work
next immediately if i check for next week monday setting it to 8 35 PM -- Again it breaks 
now again if set the time to 6 29PM and test for 6 30 scheduled alarm it works fine.

Problem : The scheduled Notification does not trigger when i change the time manually to the pre scheduled time or do any changes to phone time.

Tested with Android 5.0 genymotion

**Comment by dansanti** [comment]
the logic here it's, you set the alarm and when it's fired schedule next notification interval,  there are a bug if you schedule an alarm in past (need to fire the notification once for shcedule next next notification), that was resolved in current version, but now the problem it's that android fire all alarms on reboots
