### ISSUE TITLE
How to update badge count?

### ISSUE THREAD

**Issue by ahetawal** [katzer/cordova-plugin-local-notifications#583]
Hello,
Trying to use a repeating notification which triggers every day at 10 am. 
I set the badge:1 to display the badge, but I am not sure how to update this badge count with every trigger of this notification each day.
So basically after 3 days of notifications, how do I see number 3 as the badge count on my app icon.
Currently it seems the badge count is static that is once i define it in my config, it always remains the same? 
I might be wrong on this, but this is what I seem to be seeing right now..

Any advise,
Thanks

**Comment by MrAntix** [comment]
there is another plugin you could try here
https://github.com/katzer/cordova-plugin-badge

**Comment by katzer** [comment]
:+1: for the badge plugin
