### ISSUE TITLE
Android Build Failed

### ISSUE THREAD

**Issue by herve1976** [katzer/cordova-plugin-local-notifications#584]
cordova plugins:

android.support.v4 21.0.1 "Android Support v4"
com.danielcwilson.plugins.googleanalytics 0.6.1 "Google Universal Analytics Plugin"
com.ionic.deploy 0.1.5 "IonicDeploy"
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-console 1.0.0 "Console"
cordova-plugin-inappbrowser 1.0.1-dev "InAppBrowser"
cordova-plugin-whitelist 1.0.0 "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.1 "LocalNotification"
nl.x-services.plugins.socialsharing 4.3.18 "SocialSharing"

ionic build android:

/Users/herve76/Desktop/mani/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:495: cannot find symbol
symbol  : method evaluateJavascript(java.lang.String,<nulltype>)
location: interface org.apache.cordova.CordovaWebView
                    webView.evaluateJavascript(js, null);
                           ^
/Users/herve76/Desktop/mani/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:492: cannot find symbol
symbol  : method post(<anonymous java.lang.Runnable>)
location: interface org.apache.cordova.CordovaWebView
        webView.post(new Runnable(){
               ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
100 warnings
 FAILED

Anyone has the same problem ?

**Comment by rgreschner** [comment]
Had the same issue. What solved it was to downgrade to an earlier version 0.7.8 of the plugin as described in issue #567.

**Comment by docherty** [comment]
@rgreschner how did you downgrade? I use the command:
```
$ cordova plugin add de.applant.cordova.plugin.local-notification@0.7.8
```
but I get the error about the package ID:
```
Expected plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".
```
I'm running Cordova CLI: 5.0.0 (+ Ionic CLI 1.5.0)

Any advice would be great. Thanks

**Comment by mjot91** [comment]
Here's how I achieved downgrade:

Download zip version of 0.7.8 (you can find it here: https://github.com/katzer/cordova-plugin-local-notifications/releases). After unzipping, edit plugin.xml file and change "id" argument value to "cordova-plugin-device". Then install plugin with --searchpath option: 
    cordova plugin add de.applant.cordova.plugin.local-notification --searchpath path-to-search-for-your-modified-plugin

**Comment by Trexology** [comment]
@mjot91 thx for the solution! By the way is de.appplant.cordova.plugin.local-notification  NOT de.applant.cordova.plugin.local-notification. You have a missing p in "appplant". Cheers!

**Comment by phearme** [comment]
@mjot91 @Trexology thanks guys, this works for me, I also have this issue with Cordova CLI 5. although I also have to use the old API call instead of the documented one: `cordova.plugins.notification.local`. the old one is something like `window.plugin.notification.local.add`

**Comment by docherty** [comment]
Quick update: As I mentioned above, I used:
```
$ cordova plugin add de.appplant.cordova.plugin.local-notification@0.7.8
```
which failed per the error above.
However, when I do:
```
$ cordova plugin list
```
version 0.7.8 of the plugin is listed as being installed! Without doing anything else I built the app and tried to run it on the device...and it worked! I have no idea why/how and how that relates to the error message but thought this might help someone.

**Comment by phearme** [comment]
@docherty which version of Cordova CLI are you using? The issue I am experiencing is also because I am using CLI 5.0

**Comment by docherty** [comment]
@phearme I'm using 5.1.1

**Comment by phearme** [comment]
@docherty thanks for your feedback. downgrading 0.7.8 is not a good solution anyways. this issue should be fixed.

**Comment by jyy12** [comment]
the same error in 5.1.1

**Comment by Ruudieboy** [comment]
+1

**Comment by Krysisx** [comment]
+1

**Comment by H0rst** [comment]
+1

**Comment by tubaman** [comment]
I've patched 0.7.8 like mjot91 suggested above: https://github.com/tubaman/cordova-plugin-local-notifications/tree/0.7.8_fix-584

You can use it like this: `cordova plugin add https://github.com/tubaman/cordova-plugin-local-notifications#0.7.8_fix-584`

**Comment by phearme** [comment]
@tubaman thanks !

**Comment by H0rst** [comment]
I had already switched to the new API, so the old version don't work for me. But i found the new version working here: 
cordova plugin add https://github.com/Telerik-Verified-Plugins/LocalNotification

**Comment by tubaman** [comment]
@H0rst that totally works!  I had to:
   1. Update from cordova 5.0.0 to 5.1.1
   2. Update android-sdk-linux with the new Android SDK Build Tools and add the Android Support Library

**Comment by PKnittel** [comment]
We fixed the Issue with our last commit. The plugin should also work with cordova 4.0 now.

**Comment by Krysisx** [comment]
Thanks @PKnittel, but when is the new version going to be released? Thanks

**Comment by timokujawa** [comment]
I have the same question @PKnittel When can we use the fix? Thanks in advance.
