### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by tlvince** [katzer/cordova-plugin-local-notifications#586]
The Cordova plugins registry is being removed in favour of npm. Could you publish this on npm accordingly? See: http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by Krysisx** [comment]
+1

**Comment by Dineshrajaa** [comment]
Katzer kindly port all the plugins which you have made so far for Cordova to "npm repository" .

**Comment by csvan** [comment]
Has this been done?

**Comment by DanailMinchev** [comment]
@katzer 

Any updates on this?

Thank you in advance!

**Comment by katzer** [comment]
Has been published some time ago :)
