### ISSUE TITLE
on click close all notifications

### ISSUE THREAD

**Issue by volodymyrl** [katzer/cordova-plugin-local-notifications#587]
I add notifications in the loop with different ids, but when I click on the one - all notification are closed. It doesn't look like right behavior. How it should work bu default and someone know how to fix it?

**Comment by TorpedoCXC** [comment]
You should not add multiple notifications in a loop but instead should schedule multiple notifications by using an array:

```javascript
cordova.plugins.notification.local.schedule([{
            id: 0,
            title: "Welcome",
            text: "Hello!",
            at: dt0,
            data: {i:0, iueb1: 'Welcome', iueb2: 'Hello!', itext: 'Lorem ipsum...'}
          },{
            id: 1,
            title: "Exercise",
            text: "Your next exercise is ready",
            at: dt1,
            data: {i:1, iueb1: 'Exercise', iueb2: 'Next exercise', itext: 'During your next exercise you should try to... and so on...'}
          }]);
```

**Comment by volodymyrl** [comment]
Hi @TorpedoCXC thanks for your answer, but problem wasn't in it. It's conflict between Local Notification plugin and Push notification plugin. If I remove Push notification code
```
$cordovaPush.register(config).then(function(result) {
            // ** NOTE: Android regid result comes back in the pushNotificationReceived, only iOS returned here
            if (ionic.Platform.isIOS()) {
                $rootScope.regId = result;
                scheduleNotifications.storeDeviceToken("ios");
            }
        }, function(err) {
            navigator.notification.alert("Register error " + err);
        });
```
it works ok

I found this issue https://github.com/katzer/cordova-plugin-local-notifications/issues/497 but it didn't help

**Comment by DevRecords** [comment]
Hi Volodymyr

Could you please provide more details about code you commented since I also have faced this kind of issue

Thanks

**Comment by volodymyrl** [comment]
Hi @DevRecords I've just installed both plugins and gotten this issue

**Comment by katzer** [comment]
Thats an issue with iOS. It still happen when scheduling to many notifications at same time.
