### ISSUE TITLE
Local icon path not working for iOS notifications

### ISSUE THREAD

**Issue by blakerego** [katzer/cordova-plugin-local-notifications#589]
The notifications are currently working, but I can't seem to figure out how to set the icon from a local file. My image is currently located in my ionic project repository at path 'www/img/image.png'. I'm trying to schedule the notification using the following code:

    var alarmTime = new Date();
       alarmTime.setMinutes(alarmTime.getMinutes() + 15);

    $cordovaLocalNotification.schedule({
      id: Math.random().toString(),
      date: alarmTime,
      message: 'Timeout Warning',
      title: 'Return to prevent your session from expiring.',
      autoCancel: false,
      icon: 'img/image.png'
    }, $scope);

Again, the notification works, but the desired icon does not appear. In the icon option, I've also tried: 'www/img/image.png', 
'file://img/image.png',
'res://image.png',
'../img/image.png'

Each time, I always see the default cordova robot icon instead of the icon I'm trying to specify.

Other than that, this plugin seems to be working well. Looking forward to hearing from you. Thanks in advance.

**Comment by katzer** [comment]
The `icon` and `smallIcon` properties are Android specifics.
