### ISSUE TITLE
[Android - iOS] - Scheduling a notification triggers it instantly

### ISSUE THREAD

**Issue by arlg** [katzer/cordova-plugin-local-notifications#593]
When I schedule a notification for later ( the user enters the time in an input, then i get that time for schedule ). A notification triggers instantly. Is that common ? Is there something I would have forgotten to do ?

**Comment by PKnittel** [comment]
Normaly it should trigger after the timespan you define in 'firstAt'. Check the example branch for more information about how to shedule notifications.
