### ISSUE TITLE
Plugin dependency

### ISSUE THREAD

**Issue by elacheche-bedis** [katzer/cordova-plugin-local-notifications#596]
Cordova device's plugin "org.apache.cordova.device" has been renamed to "cordova-plugin-device". Same thing for "cordova-plugin-android-support-v4"

**Comment by PKnittel** [comment]
Should be fixed with the last commit.

**Comment by alain-r** [comment]
Please also update dependency in the plugin.xml.
Line 26 needs to be changed to <dependency id="cordova-plugin-device" />
