### ISSUE TITLE
Question about Repeating Events and Windows Support

### ISSUE THREAD

**Issue by surajreddy** [katzer/cordova-plugin-local-notifications#597]
Hi,

I've noticed that windows 8.1 is now supported. Are notifications that repeat daily, weekly, etc. also handled on windows, or is this a limitation?

Thanks,

- Suraj

**Comment by Tawpie** [comment]
8.1 is supported. But you need to clone the repo!

Kim

(grammar and spelling mostly courtesy of mobile autocorrect)

**Comment by surajreddy** [comment]
@Tawpie, just to confirm - are you saying that weekly repeating notifications are supported on 8.1? Why is the cloning necessary?

**Comment by PKnittel** [comment]
Unfortunately, cause of a OS-limitation, it´s only possible to repeat a notification up to 5 times every first till 60th minute.

**Comment by Tawpie** [comment]
@surajreddy The windows foo is in a separate branch and you won't get that by installing the plugin directly so you need a local copy of the repo. I don't need weekly repeating notifications, just 1 time is good enough for me so I don't know if weekly repeating is supported.
