### ISSUE TITLE
Click event listening does not work when cold starting application

### ISSUE THREAD

**Issue by Bitneko** [katzer/cordova-plugin-local-notifications#600]
When I quit the application completely and then click on one of the notification, the click event listener does not get fire at all, although it is able to launch the app just fine. I placed the listener inside the device ready event, and when I place it outside the device ready event, there's a 50 - 50 chance of the listener firing on cold start. I need the click listener to get data in the notification object. Any ideas?

**Comment by syntiux** [comment]
+1

**Comment by PKnittel** [comment]
Check out the examplebranch for more information about how to use the plugin.
