### ISSUE TITLE
scheduled notifications show up as already triggered

### ISSUE THREAD

**Issue by logalleg** [katzer/cordova-plugin-local-notifications#601]
I'm trying to schedule a repeated notification like this:
<pre>
var opts = {
    id: 1,
    title: 'My App',
    text:  'Test Message',
    every: 'day',
    at:    '11:15 AM'
};
cordova.plugins.notification.local.schedule(opts);
</pre>

The notifications are not being triggered, and when I print out the scheduled Ids nothing shows up, but if I print out the triggered Ids then the ID of it is printed.

Any ideas?

**Comment by PKnittel** [comment]
On wich platform have you tried it?
