### ISSUE TITLE
Plugin work only after second app start

### ISSUE THREAD

**Issue by Marix1** [katzer/cordova-plugin-local-notifications#603]
At me the plugin work only after  second app start.

1. install app and start (don't work)
2. close and restart app - then the notifications work!

I tried at my own app and even the demo app the thame.
And compiled via PhonegapBuild for android with phonegap 3.6.3

notice:

after app restart the notifications need about a minute to work immediatly

**Comment by katzer** [comment]
@Marix1 If it should still exist with latest version please reopen
