### ISSUE TITLE
Error after remove and install plugin

### ISSUE THREAD

**Issue by cinek19** [katzer/cordova-plugin-local-notifications#604]
After remove and reinstall the plugin, when i'm trying to build the app, it get this error message:

:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources/home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.0/res/drawable-xhdpi/abc_ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.0/res/drawable-xhdpi/abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.0/res/drawable-hdpi/abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.0/res/drawable-hdpi/abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.0/res/drawable-mdpi/abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.0/res/drawable-hdpi/abc_ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

:processDebugManifest
:processDebugResources/home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/res/debug/xml/config.xml:57: error: Error parsing XML: unbound prefix

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        /home/dorian/Android/Sdk/build-tools/22.0.1/aapt package -f --no-crunch -I /home/dorian/Android/Sdk/platforms/android-22/android.jar -M /home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/res/debug -A /home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/assets/debug -m -J /home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/generated/source/r/debug -F /home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/res/resources-debug.ap_ --debug-mode --custom-package es.dorian.fiestassanrafael2015 -0 apk --output-text-symbols /home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/symbols/debug
  Error Code:
        1
  Output:
        /home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build/intermediates/res/debug/xml/config.xml:57: error: Error parsing XML: unbound prefix
        

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.206 secs

/home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/dorian/Dropbox/Compartides/manco/Festes/fiestasSTRafael/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true

Can anyone help me?

**Comment by katzer** [comment]
Your android platform seems to be corrupted. Simply remove & add the whole platform instead of the plugin.
