### ISSUE TITLE
Trouble on build

### ISSUE THREAD

**Issue by GuimaP** [katzer/cordova-plugin-local-notifications#605]
Hey guys, i'm trying to build an app using plugin, when i just add plugin, my app dont works, don't run and don't build, the exceptions is:
"AILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/home/guima/Android-SDK/android-sdk-linux/build-tools/22.0.1/aapt package -f --no-crunch -I /home/guima/Android-SDK/android-sdk-linux/platforms/android-22/android.jar -M /home/guima/Phonegap Apps/cordova/demo/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /home/guima/Phonegap Apps/cordova/demo/platforms/android/build/intermediates/res/debug -A /home/guima/Phonegap Apps/cordova/demo/platforms/android/build/intermediates/assets/debug -m -J /home/guima/Phonegap Apps/cordova/demo/platforms/android/build/generated/source/r/debug -F /home/guima/Phonegap Apps/cordova/demo/platforms/android/build/intermediates/res/resources-debug.ap_ --debug-mode --custom-package com.guima.teste -0 apk --output-text-symbols /home/guima/Phonegap Apps/cordova/demo/platforms/android/build/intermediates/symbols/debug
  Error Code:
  	1
  Output:
  	/home/guima/Phonegap Apps/cordova/demo/platforms/android/build/intermediates/res/debug/xml/config.xml:30: error: Error parsing XML: unbound prefix
"

I really don't know whats happen.

**Comment by cinek19** [comment]
Same here

**Comment by cinek19** [comment]
I fixed it with by doing this: 

https://github.com/katzer/cordova-plugin-local-notifications/issues/543#issuecomment-100222047

**Comment by katzer** [comment]
Fixed in the meantime
