### ISSUE TITLE
Android IndexOutOfBounds exception

### ISSUE THREAD

**Issue by LukePulverenti** [katzer/cordova-plugin-local-notifications#607]
Happening here:

https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/android/notification/AssetUtil.java#L406-L407

This is happening because you're checking for the existence of a character in one string, but then attempting to use the result to substring a different value. I would submit a pull request but it doesn't appear you're actively merging any in.

**Comment by katzer** [comment]
;) I will try my best

**Comment by katzer** [comment]
Has been fixed. Thanks!
