### ISSUE TITLE
Linking Error after upgrade of plugin

### ISSUE THREAD

**Issue by jvence** [katzer/cordova-plugin-local-notifications#609]
I've upgraded Cordova and all plug-ins including cordova-plugin-local-notifications and I now get a linking error: 

duplicate symbol _UIApplicationRegisterUserNotificationSettings in:
    /Users/qqq/Library/Developer/Xcode/DerivedData/TestMobile-fttpobxheeiarhaqixedifwqwxyq/Build/Intermediates/TestMobile.build/Debug-iphonesimulator/TestMobile.build/Objects-normal/x86_64/AppDelegate.o
    /Users/qqq/Library/Developer/Xcode/DerivedData/TestMobile-fttpobxheeiarhaqixedifwqwxyq/Build/Intermediates/TestMobile.build/Debug-iphonesimulator/TestMobile.build/Objects-normal/x86_64/AppDelegate+APPRegisterUserNotificationSettings.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can anyone explain how to fix this? Thanks

**Comment by jvence** [comment]
Is it possible that there's a conflict with the com.phonegap.plugins.PushPlugin? Was working fine with both plug-ins before upgrade.

**Comment by katzer** [comment]
@jvence Yes there was a conflict. I think its fixed already on their side.
