### ISSUE TITLE
Error building ios app on ionic for local notifications

### ISSUE THREAD

**Issue by nehakansal** [katzer/cordova-plugin-local-notifications#610]
Hi,
I am getting a build error when I try to build ios app with ionic.
Ionic version - 1.5.1
Cordova version - 5.0.0

This is the error
```
..../platforms/ios/helloApp/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m:617:47: error: expected a type
- (void) didRegisterUserNotificationSettings:(UIUserNotificationSettings*)settings
                                              ^
..../platforms/ios/helloApp/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m:467:30: warning: undeclared selector 'registerUserNotificationSettings:' [-Wundeclared-selector]
         respondsToSelector:@selector(registerUserNotificationSettings:)])
                             ^
1 warning and 1 error generated.
```

The stack trace is much bigger but I just copied what seemed to be most relevant. Please let me know if the whole strack trace will help.

I was also getting some errors with Android build, but those got fixed following the solution provided in https://github.com/katzer/cordova-plugin-local-notifications/issues/426

**Comment by nehakansal** [comment]
I did see issue https://github.com/katzer/cordova-plugin-local-notifications/issues/448, and the resolution was to upgrade xcode. My xcode version is 5.1.1. 

Is upgrading xcode the only resolution for this?

**Comment by joosepvaikma** [comment]
Were you able to find a solution? This is driving me crazy. (I have the same errors)

Only option is to upgrade?

**Comment by katzer** [comment]
@joosepvaikma You need to update Xcode
