### ISSUE TITLE
cordova build android fails with some java error

### ISSUE THREAD

**Issue by wblsoftsol** [katzer/cordova-plugin-local-notifications#611]
Hi,

I am creating an ionic app and I added local notification plugin with push plugin. after that when I do cordova build android, I get java error:

console output

:compileArmv7DebugJava/Repositories/OfflineWallet/mobile/OfflineWallet/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:495: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
/Repositories/OfflineWallet/mobile/OfflineWallet/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:492: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

/console output

What could be the problem? When I remove the local notification plugin, it works.

**Comment by tabrindle** [comment]
This is a duplicate of several other issues:

Quick fix is to replace in LocalNotifcation.java
```java
webView.post(new Runnable(){
            public void run(){
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                    webView.evaluateJavascript(js, null);
                } else {
                    webView.loadUrl("javascript:" + js);
                }
            }
        });
```
With:
```java
webView.getView().post(new Runnable(){
  public void run(){
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
      webView.sendJavascript(js);
    } else {
      webView.loadUrl("javascript:" + js);
    }
  }
});
```

See https://github.com/katzer/cordova-plugin-local-notifications/issues/543

**Comment by wblsoftsol** [comment]
Yes, this solves the problem. Thanks. I hope in future this is merged with master branch.
