### ISSUE TITLE
Problem with old notifications

### ISSUE THREAD

**Issue by H0rst** [katzer/cordova-plugin-local-notifications#614]
I have used an older version of the plugin. With this it was possible to use alphanumeric IDs. I have used this. When i set a notification with the old version, the new version crashs when i try to Access the old notifications.
Also clearAll or getAll crashs.

My problem is:
I have a version with the old plugin in the store. When i update it, it crashes for all users which have notifications set with the old version.

Andy idea how to solve it? It would be enough, if i can remove the old notifications.

**Comment by mix3d** [comment]
There is a function for removing all scheduled notifications, but there might be a mismatch in the stored data... worth a shot, however. 

See the docs for the exact syntax

**Comment by H0rst** [comment]
Thanks, but i have already tried. clearAll crashes the app.

**Comment by H0rst** [comment]
I have some log. With the old version i had IDs with alphanumeric values. For example "m188340_0". A cancelAll now throw this error:

07-07 13:24:20.295: E/AndroidRuntime(14609): FATAL EXCEPTION: pool-1-thread-1
07-07 13:24:20.295: E/AndroidRuntime(14609): Process: net.klier.myapp, PID: 14609
07-07 13:24:20.295: E/AndroidRuntime(14609): java.lang.NumberFormatException: Invalid int: "m188340_0"
07-07 13:24:20.295: E/AndroidRuntime(14609): 	at java.lang.Integer.invalidInt(Integer.java:138)
07-07 13:24:20.295: E/AndroidRuntime(14609): 	at java.lang.Integer.parse(Integer.java:410)
07-07 13:24:20.295: E/AndroidRuntime(14609): 	at java.lang.Integer.parseInt(Integer.java:367)
07-07 13:24:20.295: E/AndroidRuntime(14609): 	at java.lang.Integer.parseInt(Integer.java:334)
07-07 13:24:20.295: E/AndroidRuntime(14609): 	at de.appplant.cordova.plugin.notification.Manager.getIds(Manager.java:196)
07-07 13:24:20.295: E/AndroidRuntime(14609): 	at de.appplant.cordova.plugin.notification.Manager.getAll(Manager.java:245)
07-07 13:24:20.295: E/AndroidRuntime(14609): 	at de.appplant.cordova.plugin.notification.Manager.cancelAll(Manager.java:179)
07-07 13:24:20.295: E/AndroidRuntime(14609): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.cancelAll(LocalNotification.java:265)
07-07 13:24:20.295: E/AndroidRuntime(14609): 	at de.appplant.cordova.plugin.localnotification.LocalNotification.access$300(LocalNotification.java:51)
07-07 13:24:20.295: E/AndroidRuntime(14609): 	at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:151)

**Comment by katzer** [comment]
@H0rst Theres no universal migration way. Hope you found a way to manage it.
