### ISSUE TITLE
Plugin not working on android 5

### ISSUE THREAD

**Issue by jamesdef** [katzer/cordova-plugin-local-notifications#615]
I've the following piece  of code

```
 window.cordova.plugins.notification.local.schedule({
            id: 1,
            title: 'title ',
            text: 'text '
          }, function(result) {
            console.log('native callback result:');
            console.log(result);
          });

```

on iOs and Android. the former works like a charm, but on my Nexus 5 running android 5.0.2, nothing happens (not even error message or console).

Anyone having trouble aswell on android 5.0.x?

**Comment by simonbbyrne** [comment]
I am running android 5 here. The notification is added (triggered) to the notification centre but querying isTriggered() returns false. isScheduled() returns true. Strange

**Comment by Alexintosh** [comment]
same problem here

**Comment by Heshyo** [comment]
On Android 5 I do see the notifications (I tried doing a ```schedule```, then ```update```, then ```clear``` and things worked as expected). I haven't tried ```isTriggered``` or ```isScheduled```.

**Comment by katzer** [comment]
Please reopen the ticket if its still a topic with the latest version.
