### ISSUE TITLE
Android are inexactly as of API 19

### ISSUE THREAD

**Issue by dansanti** [katzer/cordova-plugin-local-notifications#617]
Hi!
On android's alarmManager documentation, say:
Note: as of API 19, all repeating alarms are inexact. If your application needs precise delivery times then it must use one-time exact alarms, rescheduling each time as described above. Legacy applications whose targetSdkVersion is earlier than API 19 will continue to have all of their alarms, including repeating alarms, treated as exact.

So, then how we can fix it ?

**Comment by katzer** [comment]
@dansanti The OS doesn't support it anymore!

**Comment by dansanti** [comment]
Android or api 19? BTW tis bugs is for mayor or equal to api 19, only minor than api 19 works fine.
