### ISSUE TITLE
plugin "org.apache.cordova.device" has been renamed to "cordova-plugin-device"

### ISSUE THREAD

**Issue by alain-r** [katzer/cordova-plugin-local-notifications#619]
Cordova device's plugin "org.apache.cordova.device" has been renamed to "cordova-plugin-device". 
Please also update dependency in the plugin.xml.
Line 26 needs to be changed to: dependency id="cordova-plugin-device"

**Comment by mix3d** [comment]
This has already been addressed in recent commits

**Comment by katzer** [comment]
@alain-r Has been fixed in the meantime
