### ISSUE TITLE
Plugin not working with Windows phone 8.1

### ISSUE THREAD

**Issue by Guih44** [katzer/cordova-plugin-local-notifications#620]
Hi

I try to use this plugin on Windows phone 8.1 but it doesn't work.

I try exemple projet but it doesn't work to.

Is there anyone who use this plugin with success ?

Thanks,
Guillaume

**Comment by Clayr** [comment]
I'm also having the same problem.
It does not run in the emulator and not on the device.

**Comment by kaczyk** [comment]
Same problem for me and additionaly I can't install version 0.7.8 of this plugin which was working earlier with windows phone.

**Comment by Tawpie** [comment]
If you clone the repository from github, v8.2 has a windows phone folder that was working in early July. It is UNRELEASED and that means it’s not completely tested so use with caution.
