### ISSUE TITLE
Plugin incompatible with cordova-plugin-badge on iOS  -fix included-

### ISSUE THREAD

**Issue by alain-r** [katzer/cordova-plugin-local-notifications#621]
The plugin is incompatible with cordova-plugin-badge on iOS. When using both at the same time, xCode gives a linker error.
Please apply the following fix:

     *In plugin.xml:
     -Under dependencies, add the following line:
     + <dependency id="de.appplant.cordova.common.RegisterUserNotificationSettings" />
     Under iOS, delete the following block:
     -        <hook
     -            type="after_platform_add"
     -            src="scripts/ios/didRegisterUserNotificationSettings.js" />
     -
     -        <hook
     -            type="after_plugin_install"
     -            src="scripts/ios/didRegisterUserNotificationSettings.js" />

     *Delete the file scripts/ios/didRegisterUserNotificationSettings.js
     
     *in src/ios/APPLocalNotification.m
      remove
      -#import "AppDelegate.h"
      add
      +#import "AppDelegate+APPRegisterUserNotificationSettings.h"

**Comment by toddhalfpenny** [comment]
It looks like the incompatibility was fixed... in v0.8.2 but for some reason that code has gone.

**Comment by alain-r** [comment]
Gone?
Gone due to a revert? Or just disappeared?

**Comment by toddhalfpenny** [comment]
Just removed from this repo. I have found forks of this repo that include later commits that fix this.

**Comment by chrisid** [comment]
this fix would be very welcoming

**Comment by nurfgun** [comment]
Can anyone tell me how to use this plugin with the above fix applied while waiting for this repo to be fixed
or should I abandon the local push notification entirely and go with some other option if there is in the meantime?
I'm an inch away from the completion of an app that I am building and dying to see it fixed.

**Comment by toddhalfpenny** [comment]
Sorry... this is the fork I've been using https://github.com/Salesfloor/cordova-plugin-local-notifications

**Comment by nurfgun** [comment]
@toddhalfpenny it works like a charm! thanks you've saved my day!

**Comment by katzer** [comment]
See 19a212a90ffd85b2f67013f09a9c7f7ebebef9bf.
Sorry I forgot to push some commits.

**Comment by slikk66** [comment]
I don't have the badge plugin installed.. I upgraded cordova device 1.0.2, I have 0.8.2dev of this repo, and I'm still getting the linker error.  When I remove this plugin, it goes away.. reinstall it.. comes back.

When I attempt to edit the files as described by OP the lines aren't there.. it appears I already have this latest commit 19a212a but still getting the error:

```dbi-osx:ios slikk66$ ionic plugin list
android.support.v4 21.0.1 "Android Support v4"
com.google.cordova.admob 2.7.8 "AdMob Plugin Pro"
com.google.playservices 19.0.0 "Google Play Services for Android"
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-device 1.0.2-dev "Device"
cordova-plugin-extension 1.1.4 "Cordova Plugin Extension"
cordova-plugin-iad 2.0.5 "iAd PluginPro"
cordova-plugin-inappbrowser 1.0.1-dev "InAppBrowser"
cordova-plugin-whitelist 1.0.1-dev "Whitelist"
de.appplant.cordova.common.registerusernotificationsettings 1.0.1 "RegisterUserNotificationSettings"
de.appplant.cordova.plugin.local-notification 0.8.2dev "LocalNotification"
nl.x-services.plugins.backgroundaudio 1.0.1 "BackgroundAudio"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.media 0.2.16 "Media"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.jshybugger.cordova 4.5.9 "jsHybugger"
```
---
```
duplicate symbol _UIApplicationRegisterUserNotificationSettings in:
    /Users/slikk66/Development/slikk66/MixHop/mixhop-app/platforms/ios/build/MIXHOP.build/Debug-iphonesimulator/MIXHOP.build/Objects-normal/i386/AppDelegate.o
    /Users/slikk66/Development/slikk66/MixHop/mixhop-app/platforms/ios/build/MIXHOP.build/Debug-iphonesimulator/MIXHOP.build/Objects-normal/i386/AppDelegate+APPRegisterUserNotificationSettings.o
ld: 1 duplicate symbol for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```

**Comment by slikk66** [comment]
I got it to work.. here's what I had to do:

-remove local notification plugin
-remove registerusernotificationsettings plugin
-remove cordova plugin device plugin
-cordova platform rm ios
-cordova platform add ios
-cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications

after that it built.. I guess the version #s need to match precisely and then have to clear it all out and start over

**Comment by stevehanson** [comment]
I was getting a similar error (though not using the Badge plugin). Turns out that installing the plugin using the Github URL didn't install the latest version -- still not sure why. I removed the plugin and then added it back, appending the release number at the end of the git url, and my issue was resolved:

```
> cordova plugin remove de.appplant.cordova.plugin.local-notification
> cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git#0.8.4
```

Note: if you're using Ionic, you can replace `cordova` with `ionic` in the commands, and the plugin info will be saved to `package.json` so `ionic state restore` will work.
