### ISSUE TITLE
NSInvalidArgumentException in XCode with Ionic and Cordova

### ISSUE THREAD

**Issue by ymc-sise** [katzer/cordova-plugin-local-notifications#622]
I am using Ionic with AngularJS and Cordova 5.1.1. I added the plugin by command "cordova plugin add de.appplant.cordova.plugin.local-notification". In Android everything works fine. But if I run my application in XCode 6.4 and use the iOS Simulator for iPhone (8.4) I get following error while start up:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: localnotification)'

**Comment by katzer** [comment]
@ymc-sise Please reopen if its still a topic with latest version
