### ISSUE TITLE
Cannot read property notification of undefined

### ISSUE THREAD

**Issue by nitishrajput01** [katzer/cordova-plugin-local-notifications#624]
I am getting above error while using this plugin i also checked your kitchen sink app it does'nt work out

Here is the code i m using

$cordovaLocalNotification.add({
      id: 212,
      title:   hi there,
      message: this is not working,
});

**Comment by roysG** [comment]
me to on cordova 5.1

**Comment by Group-TimTeam** [comment]
If you have properly installed the plugin, maybe the problem is your function call that is situate outside the event "device ready" or, if you are in the event "device ready", your call is too early (before the initialization of the plugin)

To check on your place a setTimeout call.

**Comment by katzer** [comment]
Please reopen if its still a topic with latest version
