### ISSUE TITLE
Wake Up Phone

### ISSUE THREAD

**Issue by zeeshanjan82** [katzer/cordova-plugin-local-notifications#627]
Does the plugin support  feature which is in skype of any calling app where when the phone is locked or in sleep mode, the user is able to respond to the call. I do not want the app to unlock the phone but show a screen like skype or whatsapp does during calling , I am building a calling app where the user should be able to respond to call even if the screen is locked.

**Comment by katzer** [comment]
@zeeshanjan82 Not yet but Android support would be possible

**Comment by EugeneSnihovsky** [comment]
@katzer Hi. Thanks for great plugin!
Is this issue still exist?
I read docs, but can't figure out:
1. how to show notification, when my android phone is locked? I use background mode with this plugin and notifications shows in device toolbar, but the screen backlight not turn on. I want not unlock device, just wake up it (turn on backlight).
2. how to show notification  not only in device toolbar, but also on the screen itself?

Thanks in advance.

**Comment by katzer** [comment]
@EugeneSnihovsky 

> how to show notification, when my android phone is locked?

I haven't yet added an option for that. You can set sound, vibration, led light and `priority`. Possible that Android turn on the backlight if the notification has high prio (`priority:2`).

> how to show notification not only in device toolbar, but also on the screen itself?

If you want to show the notification even the app is in foreground, then set `foreground: true`
