### ISSUE TITLE
Function not called on event trigger of notification while app is in background

### ISSUE THREAD

**Issue by FilippoBenassutiCDM** [katzer/cordova-plugin-local-notifications#628]
Hi I'm writing an app, for Ios, based on ionic that need to check data on server on scheduled time when the app is active, when the app is open but it is in background and when the app is open but the device is not in use and basically in sleep mode.

For my goal I added to my ionic app this plugin and the cordova-plugin-background-mode too.
At start up i call the background plugin to let my app work in background with:
window.cordova.plugins.backgroundMode.enable();

And when i call the sync manually all works fine.

For scheduling purpose I used to add a local notification scheduled every hour and on trigger I call the sync function, the same sync function I call manually.

My function is called when don't pass so much time after the I leave the ipad with black screen but for example after a long time ( an hour at least), the notification trigger but my function is not called.

Example:

On my controller:

Notification definition:
$rootScope.add = function() {
  var alarmTime = new Date();
  var text_notification = 'Check per sync';
  $cordovaLocalNotification.schedule({
        id: "1234",
        firstAt: alarmTime,
        every: "hour",
        title: 'Notify',
        text: text_notification,
        data: {
          customProperty: 'custom value'
        },
        sound: null
  },$rootScope).then(function (result) {
        console.log("The notification 1234 has been set.Sinc set at ",alarmTime);
  });
}

Function definition:
$rootScope.doscheduled = function(scope,manual){
   console.log("doscheduled called");
   localStorage.setItem("userdatasyncInProgress",true);
});

$rootScope.$on('$cordovaLocalNotification:trigger', function (event, notification, state) {
  if ( notification.id == '1234' ){
      console.log("notification: ",notification);
      var checktoday = new Date();
      console.log("called notification 1234 at ",checktoday);
   }
});

Call for set notification:
$ionicPlatform.ready(function () {
  $rootScope.add();
});
On emulator it is working because emulator don't go on sleepmode.

When I deploy the app into ipad I see the notification appear regularly but on log, when the device is on sleepmode, I noticed that don't show up text of console log that i set on on trigger event for my specified event.

I don't think this is supposed to work like this... What I missing?

**Comment by FilippoBenassutiCDM** [comment]
On log at the time the schedule should call my function there is only this kind of message:
SpringBoard[52] <Warning>: No image found for recordID 2015-07-16 13:43:24 +00000b843c64147ec59ba yet we're being asked for a scale

The time change, depends when the notification was sheduled.

**Comment by katzer** [comment]
@FilippoBenassutiCDM Please reopen if its still a topic with latest version

**Comment by estvmachine** [comment]
Hi, i try the same but happen the same thing when the app is in background dont works the trigger i iOs
