### ISSUE TITLE
iOS: sound doesn't work

### ISSUE THREAD

**Issue by Ionas83** [katzer/cordova-plugin-local-notifications#63]
iOs 7.0 doesn't play a sound when an alert is received. Sound is enabled in the notification center for the specific app. In the docs it writes: "The sound must be located in your project's resources and must be a caf file".

I created a 'beep.caf' file but since I am using phonegap build, there is no resources folder in my project. I tried putting it in the root folder (www) but doesn't work.

So where should i put the caf file so as it can be located by the plugin?

**Comment by nopium** [comment]
I had the same issue. 
Then I put sound file into www/sounds/done.caf
and referred it in js as:
>var snd = new Media("sounds/done.
>snd.play();

Then file was playing fine both in simulator and real device (5s ios 7.0)

**Comment by katzer** [comment]
@nopium,

if your sound file is located under _www/sounds/done.caf_, use the following and your sound will play even the app isn't running*:

```javascript
cordova.plugins.notification.local.schedule({
    text: "...",
    sound: "file://sounds/done.caf"
});
```

*Requires version 0.8

**Comment by greemlin** [comment]
I had the same problems with ios sounds.... nothing whatsoever!
Than I found this post:
http://leifwells.com/post/2016-06-03-local-notifications/ 

-->    sound: 'res://platform_default'

everything WORKED!

**Comment by eamonnalphin** [comment]
1 year too late, I know, but I had the same issue and that fix didn't work for me, but this did:

installed:
cordova-plugin-media
cordova-plugin-file

put my wav file in www/audio

then used:
```
var wavURL
      
if(device.platform == 'iOS') {
   console.log("Using ios file system.")
   wavURL = 'cdvfile://localhost/bundle/www/audio/chimes.wav'
} else {
   console.log("Using android file system.")
   wavURL = 'file:///android_asset/www/sound/chimes.wav'
}
$cordovaMedia.newMedia(wavURL).play();
```
