### ISSUE TITLE
Apple Mach-O Linker Error / linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by zaouifahd** [katzer/cordova-plugin-local-notifications#630]
Hi, thank you for help me. after install plugin local notifications i have always this error on build.
My configuration: 
Xcode 6.4.
Cordova IOS platform: 3.8.0.
LocalNotificationPlugin: 0.8.2dev.

duplicate symbol _UIApplicationRegisterUserNotificationSettings in:
    /Users/Fahed/Library/Developer/Xcode/DerivedData/ConnectYou-gmfhlcyicrqteheazgzdbuyarita/Build/Intermediates/Trice.build/Debug-iphoneos/Trice.build/Objects-normal/arm64/AppDelegate.o
    /Users/Fahed/Library/Developer/Xcode/DerivedData/ConnectYou-gmfhlcyicrqteheazgzdbuyarita/Build/Intermediates/ConnectYou.build/Debug-iphoneos/Trice.build/Objects-normal/arm64/AppDelegate+APPRegisterUserNotificationSettings.o
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help me

**Comment by alain-r** [comment]
https://github.com/katzer/cordova-plugin-local-notifications/issues/621

**Comment by katzer** [comment]
Has been fixed in the meantime
