### ISSUE TITLE
Fix compatibility w/ other plugins due to android-support-v4.jar

### ISSUE THREAD

**Issue by sgrebnov** [katzer/cordova-plugin-local-notifications#632]
In order to work w/ other plugins which uses android-support-v4 as well such as Facebook and Push Notifications it is recommended to replace
```
 <lib-file src="libs/android/android-support-v4.jar" />
```
with
```
<framework src="com.android.support:support-v4:+" />
```
For more details: 
https://github.com/phonegap-build/PushPlugin/issues/492

**Comment by axten** [comment]
+1

**Comment by trajedy** [comment]
+1

**Comment by saurius** [comment]
Hi, just extending @sgrebnov comment, I had the plugin installed and my app was not compiling on android for exactly this problem. The solution was 
1) remove the plugin 
```
ionic plugin rm de.appplant.cordova.plugin.local-notification
```
2) add the plugin again 
```
ionic plugin add https://github.com/katzer/cordova-plugin-local-notifications.git
```
3) Go to ```/project_dir/plugins/de.appplant.cordova.plugin.local-notification/plugin.xml``` line 136 where you should find 
```
<lib-file src="libs/android/android-support-v4.jar" />
```
 and change it for 
```
<framework src="com.android.support:support-v4:+" />
```
4) remove Android platform 
```
ionic platform rm android
```
5) add android again 
```
ionic platform add android
```
6) Build and it should work now

**Comment by sgrebnov** [comment]
Closing as resolved   - PR has been merged to master and will be available in 2.5.0

**Comment by Slavrix** [comment]
+1
This fix should be merged to be added

**Comment by sgrebnov** [comment]
@Slavrix, which plugin added 'android-support-v13.jar' to libs? - we may want to update it as well (adding such jars to libs folder is a wrong way to deal w/ deps and won't scale moving forward)

**Comment by Slavrix** [comment]
com.phonegap.plugins.PushPlugin is where the install came from.

**Comment by sgrebnov** [comment]
Great  - this has been already fixed in master branch (PushPlugin) and will be released as w/ 2.5.0

**Comment by Slavrix** [comment]
awsome

**Comment by anthonyray** [comment]
+1

**Comment by franblas** [comment]
+1 it did the trick for me.

**Comment by manuelpaulo** [comment]
Also 
<dependency id="org.apache.cordova.device" />
should be
 <dependency id="cordova-plugin-device" />

**Comment by gregalton** [comment]
Will this be fixed for the plugin on build.phonegap.com?

**Comment by felipepastor** [comment]
Well, i dont know if i have a newest version of local-notification but in my plugin.xml, line 136 and all file there isnt `<lib-file src="libs/android/android-support-v4.jar" />` or any other ".jar", i think, its because now we have dependency of cordova-plugin-android-support-v4, anyway, to make the build work, i've needed to delete android-support-v4.jar from platforms/android/libs.

Thanks all.

**Comment by katzer** [comment]
Has been fixed in the meantime.

**Comment by paul-shatalov** [comment]
I've just got the same error on this plugins set:

cordova-plugin-device,
cordova-plugin-console,
cordova-plugin-whitelist,
cordova-plugin-splashscreen,
cordova-plugin-statusbar,
ionic-plugin-keyboard,
de.appplant.cordova.plugin.local-notification,
cordova-android-support-v4,
cordova-plugin-app-event

Does anybody know what to do?
After removing local-notification all goes right.
