### ISSUE TITLE
no clear notification to click

### ISSUE THREAD

**Issue by newmesiss** [katzer/cordova-plugin-local-notifications#633]
There is some method that allows me to keep the notification bar once d enotificaciones echo click on it?

**Comment by FilippoBenassutiCDM** [comment]
Have you tried intercept on cancel or clear event to prevent that with event.preventDefault() ???

Assuming that your notification event id is 1 something like:
$rootScope.$on('$cordovaLocalNotification:clear', function (event, notification, state) {
  if ( notification.id == '1' ){
    event.preventDefault();
    //do your things
  }
});

or try on click the same thing:
Assuming that your notification event id is 1 something like:
$rootScope.$on('$cordovaLocalNotification:click', function (event, notification, state) {
  if ( notification.id == '1' ){
    event.preventDefault();
    //do your things
  }
});

**Comment by katzer** [comment]
Since the issue is from July please reopen the ticket if its still a topic with latest version.
