### ISSUE TITLE
Showing Banner

### ISSUE THREAD

**Issue by zeeshanjan82** [katzer/cordova-plugin-local-notifications#635]
I am not able to understand how to display a banner using this plugin. I am able to display a notification when my app is in background. I am using the following code:

                var now = new Date().getTime(),
                    _5_sec_from_now = new Date(now + 60 * 1000);
                var sound = device.platform == 'Android' ? 'file://sound.mp3' : 'file://beep.caf';
                cordova.plugins.notification.local.schedule({
                    id: 1,
                    title: 'Scheduled with delay',
                    text: 'Test Message 1',
                    at: _5_sec_from_now,
                    sound: sound,
                    badge: 12
                });

**Comment by FilippoBenassutiCDM** [comment]
For my experience  notification trigger when they are set up but to show your banner, that must be set on trigger event or click or cancel your application need to be active and device must not be in sleep mode.

For a banner that pop up on trigger of your notification, call a banner when your notification of id:1 is called.

For example:
cordova.plugins.notification.local.on("trigger", function (notification, state) {
      if ( notification.id == '1' ){
        // here call your banner
      }
});

or if you are using cordova with angular
$rootScope.$on('$cordovaLocalNotification:trigger', function (event, notification, state) {
      if ( notification.id == '1' ){
        // here call your banner
      }
});

**Comment by ituhin** [comment]
@FilippoBenassutiCDM how do you call that banner ?

**Comment by FilippoBenassutiCDM** [comment]
With cordova.plugins.notification you set a notification that make a notification on your device at the time you set.
When the notification trigger the event '$cordovaLocalNotification:trigger' is called and you can do what you want... open a banner or what else but the app must be active.

**Comment by ituhin** [comment]
@FilippoBenassutiCDM ... yes but how to call that native banner ? similar to whatsapp/gmail .... i got the $cordovaLocalNotification:trigger part....

**Comment by FilippoBenassutiCDM** [comment]
Are you looking for something like cordova notification that is different from LocalNotification? ... if I understand correctly.
Take a look:  https://cordova.apache.org/docs/en/3.0.0/cordova_notification_notification.md.html#Notification

**Comment by ituhin** [comment]
@FilippoBenassutiCDM isnt it the native dialog box ? I was talking about the one (small bar or banner in ios ?) comes at the top of the screen, like when a sms comes, or in gmail when a mail arrive... what do you call it ?

**Comment by FilippoBenassutiCDM** [comment]
Ok so text for the notification is set with:
cordova.plugins.notification.local.schedule({
                id: 1,
                title: 'Scheduled with delay',
                text: 'Test Message 1',
                at: _5_sec_from_now,
                sound: sound,
                badge: 12
            });

text shown is what you set on "text" 
title is what you set on "title"
at may be a specific time or something else

see specification for detail.

With schedule you set a notification that show up on notification bar of your device with title and text that you set at the time you set.

**Comment by ituhin** [comment]
@FilippoBenassutiCDM ... yes I am aware of all that .... I was getting the notification in the notification screen, when the app is active notification comes silently. and when the app is in background it was not working, then I found out that app stays in pause mode and can not invoke a new notification. I guess I will have to check with background service plugin for that. but anyway notification works as an alert with a sound, if its already set and when the app is in background.

But still that banner thing is not coming, which was my original problem, I wanted to show a message like this (please check the link.)... i am guessing these are called banners ? or I dont know what to call them. 

http://i1-news.softpedia-static.com/images/news2/iOS-8-Issues-Notification-Banners-Won-t-Go-Away-461121-2.jpg

how do I do this in cordova ?

Also wants to point out here, when I called $cordovaLocalNotification.registerPermission() , it got the permission without sound in my iphone 4s/ios8.4, then I had to change it in notification settings.

**Comment by FilippoBenassutiCDM** [comment]
Ok so:
Point 1) Notifications is a thing, when you set one or more they appear on
notification area of your device at the time they are set and when you are
using an other app you see the banner of the notification comes up to
advise you, with sound or what you set up for notification.
Point 2) A pop up into the center of the screen with a button or an ok and
cancel or what you want to show up is all javascript logic that you have to
setup at an event like on trigger or on click of the notification
Point 3) All javascript logic that you set on event like trigger or onclick
of the notification need the app in active mode or simply it must not be in
sleep/pause mode, on ios for my experience, to be executed. If your app is
not active you may see something like:
SpringBoard[43] <Warning>: UILocalNotification: could not calculate next
fire date - previous = 2015-07-30 18:52:51 +0000 : next = 2015-07-30
18:52:51 +0000 : repeatInterval = 2
See issues (
https://github.com/katzer/cordova-plugin-local-notifications/issues/234#issuecomment-136767232
 )
Point 4) If you need something like whatsup message advise, something that
comes from server that woke up your device and your app you probably need a
push notification service to trigger and you have to check push
notification plugin.
Point 5) Notification of permission are asked only the first time that you
install the app. After the first time you have to change them on settings
section.

--
*Filippo Benassuti*


Cidiemme Informatica s.r.l.
Via Ca' Nova Zampieri, 4/E
37057 San Giovanni Lupatoto - VERONA

Tel.045 8753037Fax045 8777002E_mail
filippo.benassuti@cidiemmeinformatica.itSitowww.cidiemmeinformatica.it
Questo documento è indirizzato esclusivamente al destinatario.
Tutte le informazioni ivi contenute, compresi eventuali allegati, sono
soggette a riservatezza secondo i termini del D.Lgs. 196/2003 in materia di
"privacy" e ne è proibita l'utilizzazione da parte di altri soggetti.
Se avete ricevuto per errore questo messaggio, contattate il mittente al
più presto e cancellate immediatamente il messaggio.

2015-09-01 22:42 GMT+02:00 ituhin <notifications@github.com>:

**Comment by ituhin** [comment]
@FilippoBenassutiCDM thanks :) :+1:

**Comment by katzer** [comment]
:+1: 
These foreground notifications may come in future even its not direct related to local notifications.

**Comment by leonardobazico** [comment]
@katzer has any plan to implement foreground notifications with native banner? Apps like whatsapp use native banner, but I don't found a example of use in Apple Developer documentation.

**Comment by justfathi** [comment]
Hey, this issue is still happening. 

http://stackoverflow.com/questions/37947937/how-to-always-show-notification-on-android-using-cordova-plugin-local-notificati/40721963#40721963

**Comment by Pradeepraj** [comment]
@katzer any updates on foreground local notification like WhatsApp? Thank You
