### ISSUE TITLE
App able to schedule and fire more than 64 local notifications

### ISSUE THREAD

**Issue by sparsh0611** [katzer/cordova-plugin-local-notifications#638]
It is mentioned that an app can't schedule more than 64 local notifications and if the number exceeds the limit, then only the soonest firing 64 notifications will fire. But, when I tried to schedule the notifications, I was able to schedule more than 64 notifications and all of them were fired. Here is the code snippet -

```javascript
 $scope.addLocalNotification = function (){
    var alarmTime = new Date();
    var options = [];
    for ( var i = 0; i < 130 ; i++) {
      var id = i;
      var time = alarmTime.setSeconds(alarmTime.getSeconds() + 10);
      var option = {
        id: id,
        at: time,
        text: 'This is a message number ' + i ,
        title: 'This is a title',
        sound: null
      }
      options.push(option);
    }
    $cordovaLocalNotification.schedule(options).then(function (){
      console.log('All notifications are set.');
    });
}
```
What's the reason that more than 64 notifications can be scheduled and fired, when Apple documentation and the plugin wiki both mention that it's not possible?

The app is deployed on iOS 8.3 and the version of the plugin used is 'de.appplant.cordova.plugin.local-notification 0.8.2dev'.

**Comment by katzer** [comment]
@sparsh0611 The source is the Apple Doc. If its working than its fine.
