### ISSUE TITLE
undefined is not a function (evaluating '$cordovaLocalNotification.schedule) on Cordova 4.3

### ISSUE THREAD

**Issue by spivotron** [katzer/cordova-plugin-local-notifications#640]
I'm trying to schedule a notification like so in my Ionic app: 

document.addEventListener("deviceready", function () {

      $cordovaLocalNotification.schedule({
              id: 1,
              title: 'Title',
              text: 'Slide for details.'
            }).then(function(){
              console.log("The notification has been set");
        })
  }, false);  

I'm using the ngCordova library's example but I don't understand why I'm getting this error.

Thank you.

**Comment by ziobudda** [comment]
Hi, have you find a solution ?

**Comment by spivotron** [comment]
Yes. I chose to not use this plugin as it wasn't suitable for my purpose.  

Thanks @ziobudda
