### ISSUE TITLE
All messages pop-up after restarting the device.

### ISSUE THREAD

**Issue by babakarj** [katzer/cordova-plugin-local-notifications#641]
After restarting the device all messages show up no matter if their time has came up or not.
I've checked this on LG L7 and ASUS MeMO Pad 8 ME181C K011.

Am I forgetting something or this is a bug?

**Comment by Krysisx** [comment]
I have the same issue.

**Comment by akreienbring** [comment]
+1 Anybody found a workaround?

**Comment by mrozlukasz** [comment]
Same issue with Nexus 5

**Comment by mix3d** [comment]
There is already a thread for this issue, with some proposed fixes. Please review: https://github.com/katzer/cordova-plugin-local-notifications/issues/571
