### ISSUE TITLE
Problem with creating persistent notification icon

### ISSUE THREAD

**Issue by ivellios1988** [katzer/cordova-plugin-local-notifications#646]
I'd like to add a persistent notification (preferably, an icon) in the status bar in Android and iOS. I've already added this plugin into config.xml: de.appplant.cordova.plugin.local-notification

My code is:

document.addEventListener('deviceready', function () {
window.plugin.notification.local.add({
message: 'Radio Paranormalium', // The message that is displayed
title: 'Radio Paranormalium', // The title of the message
ongoing: true, // Prevent clearing of notification (Android only)
});
}, false);

and it's placed in index.html.

However, I can see no notification when I run my app. Am I doing something wrong?

**Comment by katzer** [comment]
@ivellios1988 Sounds like it wasn't installed properly. Use `cordova plugin add ...`

Since the issue is from August please reopen the ticket if still present with latest version.
