### ISSUE TITLE
"Closed App" notification icon & Notification twice

### ISSUE THREAD

**Issue by Shinzah** [katzer/cordova-plugin-local-notifications#647]
Hi,
My LocalNotification is working fine.
When the app is launched in foreground or background, the icon and the smallIcon are fine.
But when the application is closed, the notification ticket icon is a white square ...
When i pulldown the notification, i can see a grey round with my app icon in middle.

Do you know how to remove this white square ?

![Image of the issue](http://i.imgur.com/M91FBNq.png)

In addition to this problem, when i receive a notification and the application is closed, if i click on it to open the application, i got the same notification again when the application is started..

How to avoid that ?

Thank you

**Comment by Krysisx** [comment]
+1, same for me

**Comment by JoergHolz** [comment]
+1

**Comment by katzer** [comment]
@Shinzah 
> Do you know how to remove this white square ?

I have seen that white square when the icon could not be found or was in wrong size.

Since the issue is from Aug/Sep please reopen the ticket if still present with latest version.

**Comment by SidharthPHariharan** [comment]
Does it still exist, I have the same issue. More over I am getting 

Unknown property: icon
Unknown property: smallIcon

Please help.
