### ISSUE TITLE
Version 0.8.1 won't compile for iOS

### ISSUE THREAD

**Issue by karvapallo** [katzer/cordova-plugin-local-notifications#648]
Hey guys!

I just tried using the latest version of this plugin on an ionic app, and after installing the plugin (either via the cordova or ionic cli) and then trying to build, I get a bunch of errors similar to this:
```
clang: error: no such file or directory: '/Users/aapo.kuuselo/Projects/estimote-sticker-logger/platforms/ios/estimote-sticker-logger/Plugins/org.apache.cordova.device/CDVDevice.m'
clang: error: no input files
```

~~The problem is probably that the folder should be `plugins` instead of `Plugins` with a capital `P`~~

Using OS X Yosemite as the OS.

Thank you!

**Comment by karvapallo** [comment]
Okay this seems to be an issue with trying to have local notifications with the Estimote Cordova Plugin:

https://github.com/evothings/phonegap-estimotebeacons

It seems to rely on `0.3.0` version of the `org.apache.cordova.device` plugin which seems to cause issues with the `cordova-plugin-local-notifications` plugin in questions. Any ideas or advice how to get the two to behave?

**Comment by karvapallo** [comment]
Issue can be solved by just following the XCode errors and putting the files into the correct locations. But there is some underlying issue here. Those with more experience in peculiarities of the Cordova plugin isntallation process would you please take a close look?

**Comment by mix3d** [comment]
I believe there is a version of this plugin that is updated to use the new `cordova-plugin-device` plugin format that Cordova is switching to (https://github.com/apache/cordova-plugin-device), so that it will play nicely with other plugins that have updated to the new formats.

**Comment by katzer** [comment]
Has been fixed with v.0.8.2
