### ISSUE TITLE
Compatibility problem with other plugins that uses android-support-vX.jar

### ISSUE THREAD

**Issue by excendia** [katzer/cordova-plugin-local-notifications#649]
Hi, I noticed there is a problem with plugins that also uses android-support-vX.jar. To fix this, I forked and edited to make this plugin compatible with other plugins such as PushPlugin: https://github.com/excendia/cordova-plugin-local-notifications .
These modifications were made thanks to another issue post in this repository.

**Comment by nikolowry** [comment]
@excendia you are a gentleman and a scholar. resolved all my Android issues!

**Comment by ituhin** [comment]
@excendia Thanks, you are a saviour. It worked.
pushPlugin and local-notifications not working together, build always fails.
I was fighting with this issue for hours, and I was about to report this issue, then I saw this :P 
Thanks alot :) :+1:

**Comment by zyion** [comment]
@excendia that did the trick, thank you! :+1:

**Comment by katzer** [comment]
@excendia tks its integrated now
