### ISSUE TITLE
Cannot read property 'notification' of undefined

### ISSUE THREAD

**Issue by brunocasado** [katzer/cordova-plugin-local-notifications#65]
Guys,

I'm using Phonegap Cordova 3.3. I followed the instructions of the README but my application has not window.plugin.notification. (I  am building using command line)

01-17 11:20:41.382: E/Web Console(5846): Uncaught TypeError: Cannot read property 'notification' of undefined:32

This plugin is compatible with phonegap 3.3 or i'm making anything wrong?

**Comment by lobobobo** [comment]
@katzer you got it right i dont find my plugin inside cordova_plugin.js.Now what i should do ?

Thanks katzer for finding this.
