### ISSUE TITLE
Onscreen notification when app in background

### ISSUE THREAD

**Issue by jgillard** [katzer/cordova-plugin-local-notifications#650]
I'm developing for Android and have everything working perfectly except for a drop-down banner when the phone is unlocked and the app is in the background.

I've read through several closed issues around this topic but nothing useful, does anybody know how to make this happen?

**Comment by WassiMan** [comment]
Same issue here but with iOS!

**Comment by FlossyWeb** [comment]
+1 Same here with iOS

**Comment by jfaigan** [comment]
I am using the willyboy fork and I am correctly receiving the notifications, on Android, even when the application is in the background...I cannot say the same for iOS...anyone know why the notifications are not coming through on iOS when the app is in the background?

**Comment by katzer** [comment]
@jgillard 
> anyone know why the notifications are not coming through on iOS when the app is in the background

Because the app is paused when in background

Since the issue is from August please reopen the ticket if still present with latest version.
