### ISSUE TITLE
Click/Trigger Events Not Firing

### ISSUE THREAD

**Issue by seekchange** [katzer/cordova-plugin-local-notifications#651]
First off, let me say thank you to Katzer. You are the best for providing this great plugin. Those of you reading this, I encourage you support this project via a paypal donation (button on the github readme). 

Anyways, I've been experiencing issues with getting "click" and "trigger" events to fire. I've been using the code provided in the wiki with the latest 0.8.2dev. 

The scheduling works fine with a data property (JSON), and I receive the notifications without any issues. 

The issue comes in that the "click" event never seems to get called. 

However, I think I seem to have pinpointed where the issue is on my end - not sure if it's something other folks are also experiencing. 

**Seeing if this problem is occurring for you**
In Xcode add `NSLog(@"deviceready() called on APPLocalNotification");` into your AppLocalNotification.m file located in your project /Plugins folder. 

This will let you see if the plugin is receiving the onDeviceReady call from cordova. 

When you run this code from simulator or on your phone, you should see this come up in your Xcode console. If it doesn't come up, then there might be an issue with the plugin getting the deviceready call. 

**Why is this a problem?**
If you look at APPLocalNotification.m you will see that if the plugin detects that the device is not ready, it will queue the javascript calls such as event triggers. 

If you scroll all the way down on APPLocalNotification.m you can see in "fireEvent" that there is a check for (deviceready) in which the plugin decides if it will:

`[self.commandDelegate evalJs:js];
//this basically runs the javascript to execute the event trigger`

OR 

`[self.eventQueue addObject:js];
//this adds the code to a queue to be run when deviceready is detected`

In other words, if your deviceready is not passed onto this plugin (as discerned via the trace call above), then the triggers will be queued and not run right away. It will wait to be called from the app when it starts (again assuming the deviceready call on the app will be able to communicate effectively with the plugin). 

**What can I do to fix this?**
I have no real solution to this. 

But what might be happening is that when Cordova runs it might be messing up how it sends the deviceready event call to the plugin via CDVInvokedUrlCommand. 

In other words, you may need to manually make sure the plugin gets its deviceready handler called from your app deviceready function. Something like this might work for you:

     //set the handler to detect the deviceready call within your app
     document.addEventListener('deviceready', function(){

     //manually call the plugin's device ready handler since it may not be happening automatically or there may be a disruption in the communication/handshake
     cordova.exec(
            // Register the callback handler - this is what is called when happens succesfully
            function callback(data) {
                console.log(data);
            },
            // Register the errorHandler - happens when error detected in exec cordova call
            function errorHandler(err) {
                alert('Error');
            },
            // Define what class to route messages to
            'LocalNotification',
            // Execute this method on the above class
            'deviceready',
            // An array if you want to pass data for some reason.
            []
        );
     }, false);```

**This doesn't work for me. I don't know what you are talking about.**
Sorry. I'm not an Objective-C coder, nor consider myself an expert coder in any shape or form. I don't know if this makes sense, but it's something that seems to be working for me at this point, since I've pinpointed the whole deviceready issue on my end. 

May the force be with you.

**Comment by newshorts** [comment]
I'm getting the same behavior, just wondering if anyone has found a fix for this? It's weird, I did an update about a day ago and it was working

**Comment by seekchange** [comment]
Have you tried checking to see if the plugin ondeviceready is being triggered?

**Comment by katzer** [comment]
> You are the best for providing this great plugin

@seekchange Thanks a lot!

#### About your described issue

Your description is correct. If cordova does not fire the `deviceready` event then usually the load process hangs. Maybe due to a syntax bug or an undefined method... Its mostly app related.

Sometimes it also happens that cordova starts to not load the plugins anymore. Then you have to re-add the _corrupt_ platform.

Hope that helps!
