### ISSUE TITLE
examples gets a compile error

### ISSUE THREAD

**Issue by donhill** [katzer/cordova-plugin-local-notifications#652]
I downloaded the example and when I do a cordova run android I get the followoing error. I am running cordova 3.5.0-0.2.7

ls platforms/android/src/de/appplant                                  12:26:00
cordova

cordova run android                                                   12:23:11
Error: ENOENT, no such file or directory '/Users/dhill/Downloads/cordova-plugin-local-notifications-example 2/platforms/android/src/de/appplant/localnotification/example'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at Object.module.exports.update_from_config (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/metadata/android_parser.js:268:29)
    at Object.module.exports.update_project (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/metadata/android_parser.js:332:18)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:116:31

**Comment by davidmann4** [comment]
same problem here +1

**Comment by Rohitnew1974** [comment]
Getting exactly the same error. Any solution. pls advise.

**Comment by trynget** [comment]
Getting the same problem……Have you got any solution?

**Comment by jrbistuer** [comment]
Same problem! Have anyone got the solution?

**Comment by katzer** [comment]
@donhill 

if you encounter such things try to re-add the plugin or as best the whole platform.
