### ISSUE TITLE
"onclick' returning increasing number of alerts each time it is called

### ISSUE THREAD

**Issue by calsupik** [katzer/cordova-plugin-local-notifications#654]
I am creating multiple notifications in a for loop and then pushing these notifications into an array. I am then calling schedule with the array of notifications.
inside for loop:
"var notification = {
id: locations[i].id,
title: locations[i].name,
text: locations[i].shortDesc,
//data: {loc:locations[i]}
}

notifications.push(notification);"

outside for loop:
"cordova.plugins.notification.local.schedule(notifications);"

I have the "notification.local.on("click", function (notification){ alert("Notification ID = " + notification.id);},this);" in another function. The notifications pop up as expected and the alert comes up as expected when clicked, but when the notification is created again, when I click it two alerts pop up. On the third time 3 alerts come up and so on and so forth. What needs to be done so only one alert comes up each time?

**Comment by calsupik** [comment]
Similar to question #501 https://github.com/katzer/cordova-plugin-local-notifications/issues/501

**Comment by calsupik** [comment]
Issue was solved

**Comment by pjhartin** [comment]
@calsupik I know this was some time ago, but I am having the same issue, how did you resolve this? onClick is being called 30+ times (number of elements in array).
