### ISSUE TITLE
Local notification status in android always showing true

### ISSUE THREAD

**Issue by sasikanth513** [katzer/cordova-plugin-local-notifications#656]
I want to send local notifications to user, I want show the status of notification settings in device.

In the following image there is a "show notifications" checkbox,Is there any way to read that status?

![screenshot_2015-08-20-22-15-42](https://cloud.githubusercontent.com/assets/6153816/9389518/3bbb9156-4789-11e5-9792-36589632e2cb.png)

That app has one method to check notification status

    cordova.plugins.notification.local.hasPermission(function (granted) {
        console.log('Permission has been granted: ' + granted);
    });

but it is always giving wheteher user disabled notifications or not in app info page(I suppose it is reading info of permission given while installing app, correct me if I'm wrong)

Is there any other way to know the status of notifications which is in app info page.

**Comment by Bitneko** [comment]
+1

**Comment by katzer** [comment]
@sasikanth513 Android gives no public access to ask/monitor these system settings.
