### ISSUE TITLE
Schedule notification as hidden on Android

### ISSUE THREAD

**Issue by i-mediasolutions** [katzer/cordova-plugin-local-notifications#657]
To schedule a notification when the app is active (to do some housekeeping) I used to set text, title and sound to an empty string to create a 'invisible/silent' notification.

On iOS the notification behaves as expected, doesn't show up in the notification center and triggers the trigger-event when the app is active/open. On Android however, the notification appears on the notification center. Is there a way to make the notification 'invisible/silent' on Android as well?

**Comment by katzer** [comment]
With 0.9-beta, you may use the `silent` or `foreground` property. Thanks!
