### ISSUE TITLE
update doesn't update every interval

### ISSUE THREAD

**Issue by JcDenton86** [katzer/cordova-plugin-local-notifications#658]
Using this plugin I am able to show the initial notification which shows a static title and a text that fetches from an API.  I check for text changes every second and angular updates the text in the DOM. I am trying to update the text at the notification too with no success yet. My code is this:

```
//some code here
//notification schedule
cordova.plugins.notification.local.schedule({
                            id: 1,
                            title: 'TItle',
                            text: $scope.text,
                            icon: 'res://icon',
                            smallIcon:'res://ic_school',
                            sound: null,
                            led:null,
                            ongoing:true
                        });
//notification update
cordova.plugins.notification.local.isTriggered(1, function (present) {
                            cordova.plugins.notification.local.update({
                                id: 1,
                                every:'second',
                                text: $scope.text
                            });
                        });
```
But the update is only called once and not repeating every second. Is this a bug? If not, what is the proper way of updating the notification message every second? I tried to wrap the `update` code inside a `setInterval()` but that keeps hiding and re-showing the notification continuously. 

My setup is: Android 5, Cordova 5, Angular 1.4

Thanks in advance.

**Comment by FilippoBenassutiCDM** [comment]
Try to set your update on "trigger" event instead of "isTrigered".

cordova.plugins.notification.local.on("trigger", function(notification) {
    alert("triggered: " + notification.id);
    // <-- Set your update here
});

**Comment by katzer** [comment]
:+1: for trigger event
