### ISSUE TITLE
Compiling Error on Android & Running Exception with XWalk

### ISSUE THREAD

**Issue by landall** [katzer/cordova-plugin-local-notifications#660]
G:\NerisRevenie\mobileframe\trunk\TestPB>cordova plugins
android.support.v4 21.0.1 "Android Support v4"
cordova-plugin-crosswalk-webview 1.2.0 "Crosswalk WebView Engine"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-media 1.0.1 "Media"
cordova-plugin-screen-orientation 1.4.0 "Screen Orientation"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-urlhandler 0.7.0 "URLHandler"
cordova-plugin-whitelist 1.0.0 "Whitelist"
de.appplant.cordova.common.registerusernotificationsettings 1.0.1 "RegisterUserN
otificationSettings"
de.appplant.cordova.plugin.local-notification 0.8.2dev "LocalNotification"
nl.x-services.plugins.headsetdetection 1.0 "Headset Detection"
org.apache.cordova.device 0.3.0 "Device"

TestPB\platforms\android\src\de\appplant\cordova\plugin\localnotification\LocalNotification.java:564: cannot find symbol org.apache.cordova.CordovaWebView
                    webView.evaluateJavascript(js, null);
                           ^
TestPB\platforms\android\src\de\appplant\cordova\plugin\localnotification\LocalNotification.java:561: cannot find symbol org.apache.cordova.CordovaWebView
        webView.post(new Runnable(){
               ^
FAILURE: Build failed with an exception.

**Comment by landall** [comment]
I use Cordova CLI 5.2.0

**Comment by landall** [comment]
\src\de\appplant\cordova\plugin\localnotification\LocalNotification.java:561

This block is wrong, in Cordova 5.2.0, there is no post&evaluateJavascript definition in the class cordovaWebView.

        webView.post(new Runnable(){
            public void run(){
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                    webView.evaluateJavascript(js, null);
                } else {
                    webView.loadUrl("javascript:" + js);
                }
            }
        });

**Comment by landall** [comment]
Compiling is ok after modify code however Crosswalk throw exceptions...

W/System.err(22672): Caused by: java.lang.Throwable: Warning: A XWalkViewInternal method was called on thread 'pool-1-thread-2'. All XWalkViewInternal methods must be called on the UI thread.

**Comment by imskull** [comment]
same problem, no evaluateJavascript method.

**Comment by katzer** [comment]
Should work since v0.8.2
