### ISSUE TITLE
Lost notifications if added fast and not in array

### ISSUE THREAD

**Issue by malloc32** [katzer/cordova-plugin-local-notifications#661]
Hello, Instead of using an array to schedule notification I schedule one by one (fast) and see that some of them not call then function (promise.resolve()).
Thank you.

**Comment by Tawpie** [comment]
@malloc32 If you have more than one notification to schedule and you need to do it quickly, you *must* schedule using the array method. You could try waiting until you receive the onSchedule event before scheduling your next notification, but this certainly won't be very fast.

**Comment by malloc32** [comment]
Thank you, now I schedule in an array.
