### ISSUE TITLE
Persistent notification overwritten

### ISSUE THREAD

**Issue by jgillard** [katzer/cordova-plugin-local-notifications#662]
I'm using this plugin alongside cordova-plugin-background-geolocation and have just hit a problem.
When starting the background geopositioning, the persistent notification appears in the drawer as expected. The second local notification that fires (I increment the IDs starting from 0) is replacing the original background geolocation one, which is then persistent so I cannot dismiss it. Is this a mix-up of notification IDs or something similar?

**Comment by katzer** [comment]
@jgillard Probably. Have you found the reason?

**Comment by jgillard** [comment]
Never found out the exact reason. Not using that plugin anymore
