### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by idhamperdameian** [katzer/cordova-plugin-local-notifications#665]
I use Ionic, please see my error log:
## ionic plugin add https://github.com/katzer/cordova-plugin-local-notifications
Updated the hooks directory to have execute permissions
Fetching plugin "https://github.com/katzer/cordova-plugin-local-notifications" via git clone
Repository "https://github.com/katzer/cordova-plugin-local-notifications" checked out to git ref "master".
Installing "de.appplant.cordova.plugin.local-notification" for android
Fetching plugin "cordova-plugin-android-support-v4" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-android-support-v4
npm http 304 https://registry.npmjs.org/cordova-plugin-android-support-v4
Installing "cordova-plugin-android-support-v4" for android

        Your support is needed. If you use the local-notification plugin please support us in order to ensure further development.
        https://github.com/katzer/cordova-plugin-local-notifications#supporting

        Thank you!

Installing "de.appplant.cordova.plugin.local-notification" for ios
Fetching plugin "de.appplant.cordova.common.registerusernotificationsettings" via cordova plugins registry
npm http GET http://registry.cordova.io/de.appplant.cordova.common.registerusernotificationsettings
npm http 200 http://registry.cordova.io/de.appplant.cordova.common.registerusernotificationsettings
Installing "de.appplant.cordova.common.registerusernotificationsettings" for ios

        Your support is needed. If you use the local-notification plugin please support us in order to ensure further development.
        https://github.com/katzer/cordova-plugin-local-notifications#supporting

        Thank you!

Saving plugin to package.json file

## ionic build android
Running command: /Users/jarene/Documents/ionic/Liga/hooks/after_prepare/010_add_platform_class.js /Users/jarene/Documents/ionic/Liga
add to body class: platform-android
Running command: /Users/jarene/Documents/ionic/Liga/platforms/android/cordova/build
ANDROID_HOME=/Applications/android-sdk-macosx
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
Running: /Users/jarene/Documents/ionic/Liga/platforms/android/gradlew cdvBuildDebug -b /Users/jarene/Documents/ionic/Liga/platforms/android/build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:compileReleaseJava UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:prepareComAndroidSupportSupportV42300Library UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues UP-TO-DATE
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:preDexDebug
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Applications/android-sdk-macosx/build-tools/23.0.0/dx --dex --no-optimize --output /Users/jarene/Documents/ionic/Liga/platforms/android/build/intermediates/dex/debug --input-list=/Users/jarene/Documents/ionic/Liga/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:

  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 32.256 secs

/Users/jarene/Documents/ionic/Liga/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/jarene/Documents/ionic/Liga/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/jarene/Documents/ionic/Liga/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/jarene/Documents/ionic/Liga/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/jarene/Documents/ionic/Liga/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/Cellar/node/0.12.7/libexec/npm/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

## cordova plugin list
com.ionic.keyboard 1.0.4 "Keyboard"
com.phonegap.plugins.PushPlugin 2.5.0 "PushPlugin"
cordova-plugin-android-support-v4 21.0.1 "Android Support v4"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"
de.appplant.cordova.common.registerusernotificationsettings 1.0.1 "RegisterUserNotificationSettings"
de.appplant.cordova.plugin.local-notification 0.8.2-dev "LocalNotification"

**Comment by akreienbring** [comment]
Those are conflicting:

com.phonegap.plugins.PushPlugin 2.5.0 "PushPlugin"
cordova-plugin-android-support-v4 21.0.1 "Android Support v4"

Because PushPlugin comes with "Android Support v13". You need to get rid of one of the corresponing jars!

**Comment by idhamperdameian** [comment]
Oke thank you, so it mean i need play with android build project?

**Comment by akreienbring** [comment]
Better use a fork:
This one seems to do the trick by using the <framework> Tag in Plugin.xml instead of a dependeny:
https://github.com/excendia/cordova-plugin-local-notification

**Comment by idhamperdameian** [comment]
You give me a broken link

**Comment by felipepastor** [comment]
Any updates? +1

**Comment by idhamperdameian** [comment]
I still can't use the plugin.

**Comment by felipepastor** [comment]
@idhamperdameian look this issue https://github.com/phonegap-build/PushPlugin/issues/492 and this https://github.com/katzer/cordova-plugin-local-notifications/issues/632

I've commented in this two and i could solve my problem.

**Comment by vyarmak** [comment]
Had similar problem with Facebook Connect and LocalNotification

**com.phonegap.plugins.facebookconnect 0.11.0 "Facebook Connect"**
**de.appplant.cordova.plugin.local-notification 0.8.2-dev "LocalNotification"**

Found quite simples solution - https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1017#issuecomment-142811456

@idhamperdameian maybe this will help.

**Comment by idhamperdameian** [comment]
Oke nice, thank you.

**Comment by okobloko** [comment]
I'm not using the push plugin, nor facebook... but sadly at the moment I'm getting : 

Fetching plugin "de.appplant.cordova.common.registerusernotificationsettings" via npm
Fetching plugin "de.appplant.cordova.common.registerusernotificationsettings" via cordova plugins registry

which is then timing out.

This has happened to me several times in the last month. When I checked out exactly what was being called, the file was there (could reach it via a browser at least) but plugman was timing out.  At some point it randomly started working. It's always de.appplant...

**Comment by katzer** [comment]
@okobloko thats strange why it runs into timeout but the `registerusernotificationsettings` plugin has been published on npm now.
