### ISSUE TITLE
Irregular timings of notifications

### ISSUE THREAD

**Issue by srbasraa** [katzer/cordova-plugin-local-notifications#667]
Hello there,
         I have implemented this plugin and i am getting local notifications but they are completely at random times. Sometimes they run on time and other times they run 1-10 minutes later than the prescribed time. This has got me scratching my head for a couple of days, any help will be highly appreciated. Thank you

**Comment by tehmaestro** [comment]
Hi, I'm seeing these issues too. I've went through the code and wiki numerous times, but I cannot figure it out.

**Comment by mlaiken** [comment]
I'm noticing the same problem.  Sometimes it works perfectly and fires at the set time, but then other times it will fire at a time I did not set. Any help would be greatly appreciated.

**Comment by jgillard** [comment]
Same problem here

**Comment by srbasraa** [comment]
Stil facing the same issue, which has held the app launch by the nuts. Any help would be highly appreciated

Thanks!

**Comment by iwakari** [comment]
Hi, along with everyone else, am seeing randomly timed (relative to when they are scheduled for) notifications being posted.

Thanks again for a great plugin!

**Comment by rnachison** [comment]
Hi, just came to echo the same thing as everyone else.

And I agree with iwakari, thanks for the great plugin!

**Comment by dansanti** [comment]
Hi, is a problem with android and repeating alerts? , in android's docs, was mentioned that after api 19 alerts must be inextact..

https://github.com/katzer/cordova-plugin-local-notifications/issues/617

well i fix it detecting buld version if < api 19 user normal repeating, but if > api 19 use onetime alert, adding repeating interval, for next reeating

**Comment by jgillard** [comment]
I now reschedule like the Android docs say

**Comment by tehmaestro** [comment]
Hi. Do you guys reschedule on `trigger` event?

**Comment by jgillard** [comment]
Exactly.

**Comment by srbasraa** [comment]
In my app, the alarms are to be set by end users. Each user can create multiple alarms and due to the dynamic nature of it, what iam doing is this:

- Whenever user saves the alarms, i clear all previous alarms of the user
- and then i create new alarms for the new prescribed time
- I do not use reschedule at all 

I am still stuck with this, anybody got it figured out?

Thanks alot!

**Comment by jgillard** [comment]
What I do is schedule 1 push, and then for any further pushes I add their details to a queue in local storage. When the 1st triggers, I pop the next from the queue and schedule it

**Comment by srbasraa** [comment]
does your 1st push trigger exactly on time? accurate to the second?

**Comment by jgillard** [comment]
Fortunately I only need around minute accuracy, but no it isn't second accurate for me. Just did a test for a 60 second alarm and it went off in 73 seconds.

**Comment by pbrisson** [comment]
Same issue here guys. We got both Nexus 5 and Samsung Galaxy S5 in the office; Nexus 5 works fine, but we're getting random notifications using S5. I even seen seem being triggered more than 40 seconds after the delay expired.

**Comment by katzer** [comment]
![](http://i.kinja-img.com/gawker-media/image/upload/s--mwmBJ7mw--/17mbvzkjzb2yyjpg.jpg)
