### ISSUE TITLE
Ionic app crashes just by including local notification plugins (without even using them)

### ISSUE THREAD

**Issue by MaliciousMustard** [katzer/cordova-plugin-local-notifications#668]
Hi,

I'm building a mobile app using Ionic and I wanted to use the local notification plugin.
So I have the following config:
```xml
    <gap:plugin name="org.apache.cordova.geolocation" />
    <gap:plugin name="com.phonegap.plugins.PushPlugin" version="2.4.0" />
    <gap:plugin name="org.apache.cordova.network-information" />
    <gap:plugin name="org.apache.cordova.statusbar" />
    <gap:plugin name="org.transistorsoft.cordova.background-geolocation"/>
    <gap:plugin name="nl.x-services.plugins.calendar" />
    <gap:plugin name="com.ionic.keyboard" version="1.0.3" />
    <gap:plugin name="de.appplant.cordova.plugin.local-notification" />
    
    <gap:plugin name="com.phonegap.plugins.facebookconnect" version="0.9.0">
        <param name="APP_ID" value="xxxxxx" />
        <param name="APP_NAME" value="xxxxxx" />
    </gap:plugin>
```

But the moment I include the local-notification plugin, the app is crashing!
I'm not even using them at the moment, I just include them in the config.xml.
In particular I'm getting the following error:
```
<Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSJSONSerialization dataWithJSONObject:options:error:]: value parameter is nil'
```

I should note here that I'm using Phonegap Build, I'm using the latest version of the local-notifications (0.8.1 I think) and I also have ng-cordova installed.

Am I doing something wrong? Are there any conflicting dependencies?

Many thanks,
Alex

**Comment by MaliciousMustard** [comment]
After some investigation I found out that the problem occurs when I include the background-geolocation plugin and the local-notification one.
Any idea why this might be happening?

**Comment by ochakov** [comment]
I had similar issues with both plugins installed together.
The problem was with using notifications by the background geolocation plugin in debug mode. If you disable debug option, it should work.
Anyway, I fixed those issues, check my fork of this plugin here: https://github.com/ochakov/cordova-plugin-local-notifications

**Comment by katzer** [comment]
@ochakov, @MaliciousMustard 
some changes from your fork have been added (9ac02bd)
