### ISSUE TITLE
Intel XDK + smallicon configuration

### ISSUE THREAD

**Issue by braglin** [katzer/cordova-plugin-local-notifications#669]
Dears,

I'm trying to use the smallicon to replace the android bell standard icon, how can I use file:// or res:// directory with www folder instead the plataforms/android/res? 

Or

Why the plugin didn't get the app icon by default? I have tried the javamrright cordova-plugin-local-notifications fork and it work without define a smallicon, but the title option are not working (just show "s1") so I came back to the katzer official plugin.

I don't have much experience with this... so any help will be appreciate!

**Comment by matrixreal** [comment]
yes it will be awesome if we find solution about that

**Comment by katzer** [comment]
@braglin 
@matrixreal 

`smallIcon` (e.g. Android) only supports `res://` format. I've updated the wiki.
