### ISSUE TITLE
Intel XDK build problem

### ISSUE THREAD

**Issue by Ash110** [katzer/cordova-plugin-local-notifications#671]
Tried to use the plugin with the Latest Intel XDK. Got the following error while compiling 
Error: Plugin "" failed to install.
Error: Could not retrieve plugin dependencies for local-notification'.
Error: Plugin local-notification failed to install.

Please Advise on the same ASAP

Thanks, 
Ashwin

**Comment by Kyle-Collins** [comment]
Confirming, also having this issue. 

![2wcmxqj](https://cloud.githubusercontent.com/assets/13670709/9893868/8b7e46c4-5bda-11e5-84ff-98699a22be5d.png)

**Comment by Ash110** [comment]
@Kyle-Collins I fixed the problem.
I went into the builds and downloaded version 0.7.6 from here https://github.com/katzer/cordova-plugin-local-notifications/releases/tag/0.7.6
Load it up as a local plugin, and it builds without errors.
Yet, I haven't been able to get the notifications from the app. Try it and tell me if it works for you.
@katzer you need to update, I believe. Can you check my app, if i send the code to you?

**Comment by Kyle-Collins** [comment]
I was also able to build with that version. After some tests, im seeing the following:

(using wiener debugging on compiled apk)

![m2vgxzk](https://cloud.githubusercontent.com/assets/13670709/9894598/9818ef26-5be2-11e5-909e-862ce9c1019e.png)

**Comment by Kyle-Collins** [comment]
I'm gaining some progress on getting the version you specified above to work. 

Currently, in plugin.xml, 
    <js-module src="www/local-notification.js" name="LocalNotification">
        <clobbers target="plugin.notification.local" />
    </js-module>

changing the above to:

    <js-module src="www/local-notification.js" name="LocalNotification">
        <clobbers target="cordova.plugins.LocalNotification" />
        <clobbers target="plugin.LocalNotification" />
    </js-module>

brings the _default class in local-notifications.js to the cordova scope. 

I'll update as I make further progress.

**Comment by Kyle-Collins** [comment]
I've brought version 0.7.6 to functional. Make the following edits:

in plugin.xml:

change the following

<js-module src="www/local-notification.js" name="LocalNotification">
    <clobbers target="plugin.notification.local" />
</js-module>

to 

<js-module src="www/local-notification.js" name="LocalNotification">
    <clobbers target="cordova.plugins.LocalNotification" />
    <clobbers target="plugin.LocalNotification" />
</js-module>

In local-notifications.js, I had to change most of the structure to work direct with exports.*
For some reason, the prototype declaration wasn't functional in the slightest. See http://pastebin.com/raw.php?i=zTK9t7Pu for those full edits. You can replace the contents of the original local-notifications.js to the contents of that paste. 

Usage is different in 0.7.6 than in the current version, however the documentation for 0.7.6 should work correctly. Notice the namespace changes (primarily, call to cordova.plugins.LocalNotification or window.plugin.LocalNotification )

Example:

cordova.plugins.LocalNotification.add({
    id:      1,
    title:   'TEST NOTIFCATION',
    message: 'TEST NOTIFCATION',
    repeat:  'weekly',
    date:    _1_second_from_now
});

Enjoy!

**Comment by Kyle-Collins** [comment]
NOTE::

The above actually has its own issues. The onclick event seems to be having some issues firing anything when using a listener. I'm still on the track of figuring out exactly why, and if I make any progress in that aspect I'll add it here.

**Comment by Kyle-Collins** [comment]
Currently, this fork works without an issue:: https://github.com/Skysurfer0110/LocalNotification

**Comment by Ash110** [comment]
I've been trying , with no luck.
@Kyle-Collins Any progress there?
If yes, could you paste the code you got to work, or if possible, your entire XDK project.

**Comment by nitishrajput01** [comment]
$cordovaLocalNotification inject this dependency into your controller or module it works fine for me in intel xdk 
try{
 var now = new Date().getTime();
      var _10SecondsFromNow = new Date(now + 10 * 1000);

      $cordovaLocalNotification.schedule({
        id: 1,
        title: 'Title here',
        text: 'Text here',
        at: _10SecondsFromNow
      }).then(function (result) {
        // ...
      });
    };

}catch(ex){console.log(ex);}

**Comment by Ash110** [comment]
Thanks @nitishrajput01 
Any chance you can share the project with me so i can take a look at the files that are required

**Comment by katzer** [comment]
If the problem still exists, just reopen the issue.
