### ISSUE TITLE
Example code does not work

### ISSUE THREAD

**Issue by soumendub3** [katzer/cordova-plugin-local-notifications#672]
Hello,

I have been fiddling with this plugin for couple of days now and I tried writing my own code to integrate the plugin and nothing seemed to work. I reverted back to the examples to see what I was doing incorrectly and ran the examples. I have two android devices - 5 and 4.1.2. I am using Phonegap to run my app on both and the example does not work on either - the app starts as shown in the attachment but the buttons do nothing as expected.
![screenshot_2015-09-13-23-58-33](https://cloud.githubusercontent.com/assets/14145517/9842453/da9c7504-5a73-11e5-9caf-1ac1d5c8e366.png)

Is there any quirk that I am missing? Any help will be much appreciated.

Thanks!

**Comment by khalid-hussain** [comment]
Did you try updating the android platform in the project?

**Comment by katzer** [comment]
@soumendub3 The sample app works. Try to re-add the android platform. It sounds like cordova does not load any plugin.
