### ISSUE TITLE
Plugin Breaking in IOS9 

### ISSUE THREAD

**Issue by ajaybeniwal** [katzer/cordova-plugin-local-notifications#674]
I am testing the app with IOS9.1 and the local notifications are breaking if I do not pass any sound name.

**Comment by vasam** [comment]
I'm getting "signal SIGABRT" for line "NSString* path = [dict objectForKey:@"sound"];

**Comment by ajaybeniwal** [comment]
Options dictionary is coming as empty in _init method in UILocalNotification+AppLocalNotification.m 
- (void) __init
{
    APPLocalNotificationOptions* options = self.options;

    self.fireDate = options.fireDate;
    self.timeZone = [NSTimeZone defaultTimeZone];
    self.applicationIconBadgeNumber = options.badgeNumber;
    self.repeatInterval = options.repeatInterval;
    self.alertBody = options.alertBody;
  //  self.soundName = options.soundName;

    if ([self wasInThePast]) {
        self.fireDate = [NSDate date];
    }
}

**Comment by ajaybeniwal** [comment]
Sorry Issue was resolved when i took the latest version of plugin from master branch

**Comment by vasam** [comment]
latest version did not help me. I had to remove ios platform then add it again, then update plugins

**Comment by okobloko** [comment]
I have the same issue with version 0.8.1
