### ISSUE TITLE
Not receiving local notification when user clicks on banner and app is killed

### ISSUE THREAD

**Issue by jim0020** [katzer/cordova-plugin-local-notifications#675]
I launch my iOS app, and the local notifications are created.  Then the app is killed (not in background, not in foreground, that is I swiped up on the app from the double click home button app list). When a local notification is then triggered, and I click on the notification banner, the app launches but neither the "click" event nor the "trigger" event is called.

If the app is in the background it works fine.

What might I be missing?   Anyone else seen this?

I suspect the html document, and thus the local notification plugin, is not ready when the notification is processed.

I haven't tried this yet on Android.

**Comment by Tawpie** [comment]
The same is true on Android. If the app has been killed by any of the many ways to kill an app on Android, the app will be launched but you will not get either trigger or click events. We're currently working around this but would very much appreciate an event.

**Comment by katzer** [comment]
@jim0020 
@Tawpie

I tried extra tried out all possible ways on iOS and Android and each time the `click` callback was fired. If you try it with the Kitchen Sink App, does it work?

The interesting JS code can be found in `local-notification-util.js`. Make sure that you register the callbacks as soon as possible and not within a thread.
```js
// Called after 'deviceready' event
channel.deviceready.subscribe(function () {
    // Device is ready now, the listeners are registered
    // and all queued events can be executed.
    exec(null, null, 'LocalNotification', 'deviceready', []);
});
```

**Comment by jim0020** [comment]
@Tawpie : did you ever get this working?

**Comment by ozexpert** [comment]
how does this work? seems on iOS it's working even the app is killed. 
on android, on.click event is not triggered if the app is killed. It only works in the app is in background (closed).

**Comment by Tawpie** [comment]
@jim0020 sorry, I wasn't paying attention. But no, since I've implemented a workaround I haven't tried to get the plugin to work... the workaround isn't elegant but isn't difficult: keep copy of desired reminder schedule in app local storage, at launch check to see if one "should have fired but didn't". Respond accordingly.

**Comment by ozexpert** [comment]
@Tawpie hey, are you saying when scheduled notification is triggered, save the desired reminder schedule in app local storage?

but people could just dismiss the notification. --> in this case, getting from queue and do some action would be bit awkward for the user.

**Comment by Tawpie** [comment]
@ozexpert What I do is save the array of scheduled reminders when I schedule them. When one is clicked/triggered, I remove it from the saved array... then in onDeviceReady I look through the saved schedule to see if there are any reminders in the saved schedule that are "past due". They shouldn't be in the saved schedule if they've been acted upon by the user. If there is something past due in there, I pretend we launched in response to a click on that reminder. If there is more than one past due I can't tell which one the user might have wanted so I default to the most recent past due reminder. As I mentioned, it's far from elegant and if the above solution from Katzer works by all means go that way!

**Comment by hammadjamil** [comment]
After spending lot of time on finding solution of this issue i haven't found any of the suggestion worked for me.
But finially I have find solution and root cause of the issue on my own
The issue is events like click and trigger doesn't work after the app kill because when app is opened after kill events are not bind.
So the solution of this issue is to rebind the events at the start of the app your problem will be solved
like i am working on ionic app i have put below code in app.js for notification click event
$ionicPlatform.ready(function () {
cordova.plugins.notification.local.on("click", function (notification) {
                        cordova.plugins.notification.local.cancel(notification.id, function () {
                            // Notification was cancelled
                            console.log('notification is cancelled  : '+ notification.id);
                             
                        }, '');

                    });
 });

Now events are bind and work properly even after app kill. i have tested it for android and hopefully work for ios as well

**Comment by vegham** [comment]
I have the subscription in constructor of its respective provider in my Ionic project. It has the addressed issue where it work while app is running and not while killed.

Solution was as hammadjamil suggested. By adding the provider to root-component (MyApp in app.components.ts) its able to fetch the clicked notification.

**Comment by jimtonique** [comment]
Hi,

@vegham could you be me specific about your solution ?
Which code to add and where ?
Thanks by advance.

**Comment by vegham** [comment]
I have a notifier.ts (provider) which uses LocalNotifications. To prevent the crash I simply added the provider to app.component.ts as follows:

```
import { Notifier } from '../providers/notifier';
export class MyApp
{
  constructor(private notifier: Notifier) { }
....
}
```

**Comment by jimtonique** [comment]
@vegham thanks for the response !!
I'm using LocalNotifications same as you in a provider that is included in MyApp constructor for localNotification initialization but the click event is not triggered when app is killed. Could you show me how LocalNotifications is used inside your notifier provider ? Maybe that will help me understand the difference and why it's not working on my case. Also when do you define the local....on('click') event ? 
Thanks by advance.

**Comment by vegham** [comment]
In my provider constructor I have
```
      let parent = this;
      this.platform.ready().then(()=>
      {
        this.localNotifications.on("click", function(notification)
        {
          parent.log.warning("Notifier received notification click");
          parent.clickedNotification = notification;
          parent.events.publish("notification:clicked");
        });
      });
```

**Comment by jimtonique** [comment]
@vegham Thanks a lot for your help !! It's working for me too now.
