### ISSUE TITLE
iOS 9 problem

### ISSUE THREAD

**Issue by stevesum** [katzer/cordova-plugin-local-notifications#679]
For me the plugin throw an exception in UIApplication+APPLocalNotification.m (line 126)
because the UIContrateLocalNotification has no option property defined anymore.

**Comment by stevesum** [comment]
Ok. I see this is reported already on #585

**Comment by luigi37** [comment]
In reality it's  a different issue so maybe good to keep this one open

**Comment by stevesum** [comment]
Ok. I reopened. Hopefully it can be fixed easily, because at the moment I can't do anything with this only comment out the plugin. Every time when I try get the id's of the notifications (scheduled, triggered, etc.), I got an exception because can't get the property id from undefined.

**Comment by stevesum** [comment]
:) Funny, but I will close this ticket again, because this is fixed in the devel version already. Thx.
