### ISSUE TITLE
Phonegap Build Error CLI 5.2.0

### ISSUE THREAD

**Issue by LlamaloX** [katzer/cordova-plugin-local-notifications#683]
Hey,

All of a sudden I can't build my Android app through Phonegap Build since it says:

"Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: LocalNotification.java - You can fix this here"

Any solutions? I know that there is one building it through the cli but I need to build it throught Phonegap Build.

**Comment by LlamaloX** [comment]
Same happens when trying with CLI 5.1.1

**Comment by andreluizmorita** [comment]
I have same problem

**Comment by troywardle** [comment]
Having the same problem also, only started occurring after the latest PhoneGap Build update (5.2.0)

**Comment by troywardle** [comment]
Hi all,

I asked the same question here and got a useful response:

http://community.phonegap.com/nitobi/topics/plugin-broken-in-pgb

In the last week or so Adobe changed the default version from 3.7.0 to 5.2.0 so if you weren't specifying a version, a whole heap of problems could come from that upgrade. You can revert to 3.7.0 by including this in your config.xml:

<preference name="phonegap-version"       value="3.7.0" />

**Comment by andreluizmorita** [comment]
Thank,

Your sugestion working for me. 

preference name="phonegap-version" value="3.7.0"

**Comment by FlossyWeb** [comment]
+1 same here need to build in 3.7.0 for Android because builds with cli-5.1.1 and 5.2.0 fails

**Comment by Medioman92** [comment]
+1 Same issue...will this plugin ever support phonegap-android 4+ ?

**Comment by onuryilmaz** [comment]
+1, with the latest CLI 5.2.0 on Phonegap build.

**Comment by aliexalter** [comment]
Hi,
I just notice if you have phonegap.js in your index.html file the plugin will not work. Replace phonegap.js with cordova.js.

**Comment by katzer** [comment]
Should be any issue anymore

**Comment by kruded** [comment]
Having the same problem also
