### ISSUE TITLE
404 npm registry error on install.

### ISSUE THREAD

**Issue by mikeljames** [katzer/cordova-plugin-local-notifications#684]
Hi,

I'm finding that when I run:
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.8.1
or 
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
or
cordova plugin add de.appplant.cordova.plugin.local-notification

I get the following error:
nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings

Any ideas?

**Comment by tengbretson** [comment]
Any resolution to this issue?

**Comment by SanatShukla** [comment]
Remove plugin, then Add it again.

**Comment by tengbretson** [comment]
This happens to me often from a fresh install. It seems like the host: https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings
is down constantly. Is there a reason for this?

**Comment by kjt1212** [comment]
Any resolution to this yet? I keep facing the same issue.

**Comment by SanatShukla** [comment]
Removing and Add it again work for me. I don't know what is the reason for other.

**Comment by lucbonnin** [comment]
I'm using ionicframework.
I had to do following stuffs as cordova-badge-plugin and de.appplant.cordova.plugin.badge was both installed.

```
ionic platform remove ios
ionic platform remove android
cordova plugin remove de.appplant.cordova.plugin.badge
ionic platform add  ios
ionic platform add android
```

Then 
`cordova plugin list 
`And duplicated plugin are no more there ;)  Only stay the cordova-plugin-badge 0.7.2

I hope it could help

**Comment by hammadjamil** [comment]
@katzer  i am using this plugin for android and ios both, for android it is working very well but for ios i am unable to install this plugin it return errors

Failed to install 'de.appplant.cordova.plugin.local-notification-ios9-fix':CordovaError: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:192:33
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


Error: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings



It seems that above link is broken is their a way around kindly suggest me

Thanks :-)
