### ISSUE TITLE
Click On Notification Is Not Working

### ISSUE THREAD

**Issue by DevSubhashis** [katzer/cordova-plugin-local-notifications#685]
On Latest Version 0.8.1 Click On Notification Is Not Working. It was working at previous version. Need Help. PLZ.

**Comment by mekaercu** [comment]
Have same issue on  
<gap:plugin name="de.appplant.cordova.plugin.local-notification-ios9-fix" version="0.8.2" />

**Comment by katzer** [comment]
@DevSubhashis iOS or Android? When running the KitchenSink App its working!
