### ISSUE TITLE
Error when I'm doing a build

### ISSUE THREAD

**Issue by andreluizmorita** [katzer/cordova-plugin-local-notifications#687]
Command: cordova build android

Error:
LocalNotification.java:561: error: cannot find symbol
webView.post(new Runnable(){

symbol:   method post(<anonymous Runnable>)
location: variable webView of type CordovaWebView

**Comment by Tawpie** [comment]
In general, and only for the CLI (I don’t know about phonegap build), the build errors will go away if you:

— remove the existing plugin
— use the fork at cordova plugins 
		cordova add https://github.com/excendia/cordova-plugin-local-notifications.git

This gives you de.appplant.cordova.plugin.local-notification 0.8.2dev “LocalNotification"

**Comment by katzer** [comment]
Should be any issue anymore
