### ISSUE TITLE
The Sound is not working for IOS

### ISSUE THREAD

**Issue by gamesparati** [katzer/cordova-plugin-local-notifications#689]
The notifications are working, but the sound is never played, the phone doesn't even vibrate when the notification comes, it would be awesome if it worked. Besides that, if you're using IOS 9 with intervals smaller than 15 minutes, the app crashes. Can you solve it please?

**Comment by dansanti** [comment]
soun must be on .caf format, vibration is not implemented, the only way to implement a  vibration, is adding it manually ,

**Comment by katzer** [comment]
@gamesparati - Vibration and sound are controlled by the OS, not the app or plugin (thats different to Android). If these things are activated in settings, the OS will only play sound or vibrate if the app is in background, but never when the app is in foreground.

**Comment by FranciscoG** [comment]
I found [this](https://forums.developer.apple.com/thread/18395?start=120&tstart=0) thread on Apple Developer forums that a lot of people are experiencing the same problem and as of the last page of the thread  it is still not fixed.   I'm going to have to use a cordova plugin as a stub until this is fixed but it looks like this is an OS problem and not a problem with this plugin.   Noti

https://forums.developer.apple.com/thread/18395?start=120&tstart=0
