### ISSUE TITLE
iOS: Not able to schedule local notification

### ISSUE THREAD

**Issue by sparsh0611** [katzer/cordova-plugin-local-notifications#695]
Since I have added the plugin for [push notifications](https://github.com/phonegap/phonegap-plugin-push), I can't schedule a local notifications. Every time when a local notification is scheduled, didRegisterForRemoteNotificationsWithDeviceToken method of PushPlugin.m gets called and returns an error "Invalid callback id received by sendPluginResult" and the local notification is not scheduled.
I have also opened a bug on the push notification plugin [here](https://github.com/phonegap/phonegap-plugin-push/issues/183#issuecomment-144520543).

**Comment by lylepratt** [comment]
I'm having this exact problem. Took me forever to figure out why suddenly local notifications were not working.
