### ISSUE TITLE
Error::Plugin not allowed in config.xml. LocalNotification

### ISSUE THREAD

**Issue by Krysisx** [katzer/cordova-plugin-local-notifications#699]
Hi,

I'm trying to use the plugin on WP8.1 using Visual Studio 2013 and the WP8.1 emulator and when I do:

```javascript
var notification = {
    id:      1,
    title:   "title",
    text: "text",
    at: new Date(),
};
cordova.plugins.notification.local.schedule( notification );
```

it says `Error::Plugin not allowed in config.xml. LocalNotification`
I use `cordova 5.3.3` and the plugin version is `0.8.2dev`.

Any help please?

Thanks
the console in Visual Studio says:

**Comment by Krysisx** [comment]
Any help please?

**Comment by Tawpie** [comment]
@krysisx: try cloning the repo to your local system and using the Windows branch. 

Kim

(grammar and spelling mostly courtesy of mobile autocorrect)

**Comment by Krysisx** [comment]
Thanks for the answer, how can I use the Windows branch?
Thanks

**Comment by Krysisx** [comment]
Thanks for your reply, but it still does not work.
Maybe I have to add something to my `config.xml`?

**Comment by Tawpie** [comment]
@Krysisx… it’s been since the spring that I’ve build for windows phone 8.1, but the essence is:
	— clone the repository to your local windows machine
	— using your git client, switch to the windows branch
	— add the plugin from the local branch: cordova plugin add <path to the local copy of the repo>\cordova-plugin-local-notifications

It is worth noting that adding plugins must be done in the native silverlight directory .\bld\Debug\platforms\windows after you’ve build for the emulator in debug mode.

Beyond that, I’m afraid I’m out of suggestions. The general process for windows was quite long, hairy, and poorly documented. I don’t know how it’s changed since May when I last built.

**Comment by Krysisx** [comment]
ok thanks, and coudl you please try the latest version from master? I see from readme file that they have added support for WP8 and WP8.1 so it should work, even if it does not work for me.

**Comment by Tawpie** [comment]
I would, but sadly windows phone is in my rear view mirror (well, given how much stomach lining it cost—gladly is more accurate)… it’d take a couple hours to get everything set back up and honestly I can’t take that much time. If I get some time I’ll see about launching windows again, going through all the updates, then trying to figure out what VS has been broken between May and today but I would be surprised if I have that much time.

A few things I discovered in the Spring:
	— windows phone is EXCEPTIONALLY slow with the cancelAll command, and likewise horrifically slow scheduling basic one time notifications. It’s nearly unusable for our purposes it’s so slow. 10 full seconds to accomplish what Android and iPhone do in 10s of milliseconds.
	— the hijinks necessary to build and debug are beyond excessive, so we dumbed our app down to avoid complications
	— we have no plans to update. Maybe in early 2016, but there aren’t enough customers for our app on the platform to do much work on it at all

Sorry I’m not much more help.

**Comment by Krysisx** [comment]
ok thanks for your help
