### ISSUE TITLE
CDVPlugin class APPLocalNotification (pluginName: LocalNotification) does not exist.

### ISSUE THREAD

**Issue by sergionader** [katzer/cordova-plugin-local-notifications#704]
Hello. 

Though the plugin is working on iOS 9.02 (after applying the fix mentioned in this page), it throws this error: CDVPlugin class APPLocalNotification (pluginName: LocalNotification) does not exist.

I really don't where and what I should change. Any ideas? 

Thanks in advance, 

Sergio

**Comment by katzer** [comment]
Sounds like a cordova issue or a corrupt project config. If possible re-add the platform.
