### ISSUE TITLE
Arguments to path.resolve must be strings     

### ISSUE THREAD

**Issue by yugalbagul** [katzer/cordova-plugin-local-notifications#706]
Hi,

I am new to the cordova world.
I am trying to get the local notifications up on ionic.Unfortunately i am not able to install using 

cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git

This is the error i am facing -

Fetching plugin "https://github.com/katzer/cordova-plugin-local-notifications.gi
t" via git clone
cp: dest file already exists: G:\Projects\TimeMyTask\Mobile App\TMTapp\plugins\d
e.appplant.cordova.plugin.local-notification\CHANGELOG.md

cp: dest file already exists: G:\Projects\TimeMyTask\Mobile App\TMTapp\plugins\d
e.appplant.cordova.plugin.local-notification\CHANGELOG.md
cp: dest file already exists: G:\Projects\TimeMyTask\Mobile App\TMTapp\plugins\d
e.appplant.cordova.plugin.local-notification\LICENSE

cp: dest file already exists: G:\Projects\TimeMyTask\Mobile App\TMTapp\plugins\d
e.appplant.cordova.plugin.local-notification\CHANGELOG.md
cp: dest file already exists: G:\Projects\TimeMyTask\Mobile App\TMTapp\plugins\d
e.appplant.cordova.plugin.local-notification\LICENSE
cp: dest file already exists: G:\Projects\TimeMyTask\Mobile App\TMTapp\plugins\d
e.appplant.cordova.plugin.local-notification\plugin.xml

cp: dest file already exists: G:\Projects\TimeMyTask\Mobile App\TMTapp\plugins\d
e.appplant.cordova.plugin.local-notification\CHANGELOG.md
cp: dest file already exists: G:\Projects\TimeMyTask\Mobile App\TMTapp\plugins\d
e.appplant.cordova.plugin.local-notification\LICENSE
cp: dest file already exists: G:\Projects\TimeMyTask\Mobile App\TMTapp\plugins\d
e.appplant.cordova.plugin.local-notification\plugin.xml
cp: dest file already exists: G:\Projects\TimeMyTask\Mobile App\TMTapp\plugins\d
e.appplant.cordova.plugin.local-notification\README.md

skipping existing file: broadcastActivateEvent.js
skipping existing file: setToastCapable.js
skipping existing file: ClearReceiver.java
skipping existing file: ClickActivity.java
skipping existing file: LocalNotification.java
skipping existing file: AbstractClearReceiver.java
skipping existing file: AbstractClickActivity.java
skipping existing file: AbstractRestoreReceiver.java
skipping existing file: AbstractTriggerReceiver.java
skipping existing file: AssetUtil.java
skipping existing file: Builder.java
skipping existing file: ClearReceiver.java
skipping existing file: ClickActivity.java
skipping existing file: Manager.java
skipping existing file: Notification.java
skipping existing file: Options.java
skipping existing file: TriggerReceiver.java
skipping existing file: RestoreReceiver.java
skipping existing file: TriggerReceiver.java
skipping existing file: APPLocalNotification.h
skipping existing file: APPLocalNotification.m
skipping existing file: APPLocalNotificationOptions.h
skipping existing file: APPLocalNotificationOptions.m
skipping existing file: UIApplication+APPLocalNotification.h
skipping existing file: UIApplication+APPLocalNotification.m
skipping existing file: UILocalNotification+APPLocalNotification.h
skipping existing file: UILocalNotification+APPLocalNotification.m
skipping existing file: LocalNotificationCore.js
skipping existing file: LocalNotificationProxy.js
skipping existing file: LocalNotificationUtil.js
skipping existing file: local-notification-core.js
skipping existing file: local-notification-util.js
skipping existing file: local-notification.js
Installing "de.appplant.cordova.plugin.local-notification" for android
Error during processing of action! Attempting to revert...
Failed to install 'de.appplant.cordova.plugin.local-notification':TypeError: Uh
oh!
**Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)**
    at module.exports.framework.install (C:\Users\Yugal\AppData\Roaming\npm\node
_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:3
5)
    at Object.ActionStack.process (C:\Users\Yugal\AppData\Roaming\npm\node_modul
es\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:67:25)
    at handleInstall (C:\Users\Yugal\AppData\Roaming\npm\node_modules\cordova\no
de_modules\cordova-lib\src\plugman\install.js:575:20)
    at C:\Users\Yugal\AppData\Roaming\npm\node_modules\cordova\node_modules\cord
ova-lib\src\plugman\install.js:335:28
    at _fulfilled (C:\Users\Yugal\AppData\Roaming\npm\node_modules\cordova\node_
modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Yugal\AppData\Roaming\npm\node_module
s\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Yugal\AppData\Roaming\npm\node_
modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Yugal\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.
js:509:49
    at flush (C:\Users\Yugal\AppData\Roaming\npm\node_modules\cordova\node_modul
es\q\q.js:108:17)
TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at module.exports.framework.install (C:\Users\Yugal\AppData\Roaming\npm\node
_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:3
5)
    at Object.ActionStack.process (C:\Users\Yugal\AppData\Roaming\npm\node_modul
es\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:67:25)
    at handleInstall (C:\Users\Yugal\AppData\Roaming\npm\node_modules\cordova\no
de_modules\cordova-lib\src\plugman\install.js:575:20)
    at C:\Users\Yugal\AppData\Roaming\npm\node_modules\cordova\node_modules\cord
ova-lib\src\plugman\install.js:335:28
    at _fulfilled (C:\Users\Yugal\AppData\Roaming\npm\node_modules\cordova\node_
modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Yugal\AppData\Roaming\npm\node_module
s\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Yugal\AppData\Roaming\npm\node_
modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Yugal\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.
js:509:49
    at flush (C:\Users\Yugal\AppData\Roaming\npm\node_modules\cordova\node_modul
es\q\q.js:108:17)

These are the version information
ionic 1.3.22
cordova 4.3.0

Running it for windows, for android.

I have searched and found similar issues here 
https://github.com/diegonetto/generator-ionic/issues/92 

The solution given there did not work for me.Still getting the same error. 
Please Help.

**Comment by gvandenbosch** [comment]
Having same problem here, did you find any solution?

**Comment by katzer** [comment]
Seems like a prior uninstallation failed. Re-add the platform to fix that.
