### ISSUE TITLE
Samsung+Lollipop crash due to >500 notifications scheduled

### ISSUE THREAD

**Issue by Tawpie** [katzer/cordova-plugin-local-notifications#710]
This is specific to Samsung (specifically encountered on Galaxy S6) running lollipop. Even though notifications are cancelled and no longer fire, they still build up and eventually hit a limit that causes the app to crash.

See http://stackoverflow.com/a/29703161 for details but the essence is a need to alter the plugin to use UPDATE_INTENT instead of CANCEL_INTENT.

UPDATE: making the changes to UPDATE_INTENT in Builder.java and Notification.java has cleared up the problem. I would fork etc., but have never done that before and frankly the instructions are insufficient.

To see what's happening, in a terminal window with adb running run the following:
adb shell dumpsys alarm | grep -c "com.yourApps.widget id from config.xml"

Each time you schedule notifications when using CANCEL_INTENT, the count of pending alarms keeps increasing. When using UPDATE_INTENT, pending alarms don't keep adding to the count.

**Comment by logalleg** [comment]
Those fixes didn't resolve the issue for me
