### ISSUE TITLE
Local Notification + OneSignal - PGB Fails

### ISSUE THREAD

**Issue by murliatdure** [katzer/cordova-plugin-local-notifications#713]
![local-notification](https://cloud.githubusercontent.com/assets/7137859/10483012/519bd60c-729a-11e5-9234-066c563ed8de.PNG)

**Comment by murliatdure** [comment]
https://github.com/one-signal/OneSignal-Cordova-SDK/issues/18

**Comment by katzer** [comment]
Its now available as an npm pkg
