### ISSUE TITLE
Conflict with Push Plugin iOS9?

### ISSUE THREAD

**Issue by graphicgeek** [katzer/cordova-plugin-local-notifications#714]
I seem to have the notifications working on iOS9, but once I install the Push Plugin (https://github.com/phonegap/phonegap-plugin-push) local notifications no longer fire.

I've traced it down to the registerPermission method. In local-notification-core.js the registerPermission method calls the cordova exec function to call the native registerPermission function. But for some reason the native registerPermission never runs. Since it never runs, the registerPermission method in local-notification-core.js never runs it's callback, and the notification never completes.

I don't know enough Objective C to figure out what's going wrong.

**Comment by Mojo90** [comment]
#663
