### ISSUE TITLE
Duplicate notification received (IOS9 only)

### ISSUE THREAD

**Issue by Linerd00** [katzer/cordova-plugin-local-notifications#718]
current version 0.8.2-dev won't cause the app crash any more, but duplicate notifications are received on IOS9, I am using ionic

```javascript
var notifications = [];
for(var i = 0; i < 4; i++){
  var at = new Date(new Date().getTime() + (1000 * (10 + 5 * i)));
  var reminder = {
    id: 600 + i,
    title: '00 test title6-' + i,
    text: '00 test text6-' + i,
    at: at
  };
  notifications.push(reminder);
}
$cordovaLocalNotification.schedule(notifications);
```

(P.S thanks to "t1tlehto", an error is fixed by installing both de.appplant.cordova.plugin.local-notification &  de.appplant.cordova.plugin.badge,
link: https://github.com/katzer/cordova-plugin-badge/issues/23)

**Comment by randdusing** [comment]
I'm noticing something similar, but only when the app is in the background. If it's completely terminated, I get the one notification as expected.

**Comment by Linerd00** [comment]
@randdusing I just check that, the duplicate notifications received no matter the app is terminated or not in IOS9. It works fine in IOS8.
I am wondering why nobody else encounters the same issue, only you and me? 
Still can't find anything I set wrong. Notifications are not scheduled twice.

**Comment by thadeuszlay** [comment]
I got the same issue: iOS9; using ionic.

Get notification twice when:
- app is closed
- and I'm not in the log in home view of the iPhone

However I do not get the notificatin twice when 
- I closed the app
- and I'm in the log in home view of the iPhone.

**Comment by randdusing** [comment]
Just wanted to add I'm using Ionic as well, but I don't think it should make a difference. And I'm on iOS 9.1

**Comment by CookieCookson** [comment]
+1 I have the same issue here, got a double notification when triggering a notification from the lock screen (iBeacon integration) however when on the home screen and triggering I received a single notification.

**Comment by Chuckv01** [comment]
+1

**Comment by JLNNN** [comment]
+1

**Comment by Rusta** [comment]
+1

**Comment by iDurian** [comment]
+1

**Comment by katzer** [comment]
@Linerd00, @Rusta

> it seems to be an issue when multiple schedules are being added that are in the past (so are triggered immediately) if the schedules are in the future then they seem to trigger fine (ie no duplicates)...

I can confirm that behavior. I will try to fix that but iOS behaves very strange (maybe not thread-safe) when scheduling multiple notifications. Its already a "magic thing" that its working at least in the way it does now ;)

**Comment by katzer** [comment]
Its an bug on iOS side. Since there is not reason no spam the user with multiple notifications popping up at the same time its more an edge case.

**Comment by cokron** [comment]
Hello Sebastián,
I am glad I found this thread about notifications showing twice or more at the same time.
I am having the same issue with Version 0.8.4 on iOS. I assumed that when I use the same ID when I create a local notification, the previous one will be overwritten. In my case, I was creating a notifications that alerts every day at 6pm. Some uses complained that this notification is shown twice or more.

Do you have any advice on what to do when I want to have recurrent notifications and need to replace an existing one? Delete all notifications first? Use different IDs with the replacement notification? Set the new one at 6:01pm instead of 6:00pm? 

Any help is greatly appreciated :-)

**Comment by BoBoRepo** [comment]
I am also having this issue on iOS. I guess it occurs after app update or maybe the plugin doesn't update notifications with an existing id. any ideas to solve this bug ? Our users are upset about this spam issue
