### ISSUE TITLE
Stacking local notifications

### ISSUE THREAD

**Issue by pliablepixels** [katzer/cordova-plugin-local-notifications#720]
Hello, the Android HID says if an app needs to issue multiple local notifications of the same type, it should stack notifications and use update.

I am using local notifications to display motion detection alarms for a home security app.
When I call update, the existing notification gets rewritten - there does not seem to be any option to stack unless I use a new ID which is not a good idea because Android considers that bad UI practice (and also results in many icons at the top of the notification bar)

What I am looking at is a mechanism to display a single notification icon at the top and stacked messages. According to Android's guide here http://developer.android.com/guide/topics/ui/notifiers/notifications.html#Managing it should be possible but I don't see it in the plugin.

Any thoughts?

**Comment by polyn0m** [comment]
+1, required feature

**Comment by cdorner** [comment]
This dosen't seem very hard to implement, I thinking in implement when I saw @HabibMAALEM PR https://github.com/katzer/cordova-plugin-local-notifications/pull/828, I ask if he is thinking in add support for this feature on his PR https://github.com/katzer/cordova-plugin-local-notifications/pull/828

**Comment by claudiobadii** [comment]
+1, required feature

**Comment by mix3d** [comment]
Adding my +1 as well

**Comment by ravindranpandu** [comment]
+1 a must required feature

**Comment by katzer** [comment]
Thats possible with 0.9-beta. See the README. Thanks!
