### ISSUE TITLE
querying read fails except by id

### ISSUE THREAD

**Issue by frigon** [katzer/cordova-plugin-local-notifications#724]
See attached image from a debug session attached to a iPhone runnion ios9.

For some reason getAll, getScheduledIds, getTriggeredIds, & getAllIds all return nothing.  However get(id, function) DOES work.
<img width="464" alt="local notification" src="https://cloud.githubusercontent.com/assets/5033564/10595171/d82ecbdc-7689-11e5-8cbb-4a6df06c66e6.png">

**Comment by katzer** [comment]
Have you found out the reason or any hint? When I am trying it out it works.
