### ISSUE TITLE
 Could not find any version that matches com.android.support:support-v4:+.

### ISSUE THREAD

**Issue by Xekz** [katzer/cordova-plugin-local-notifications#726]
Running: /home/work/Документы/Мобильное приложение/cordova-plugin-local-notifications-example/platforms/android/gradlew cdvBuildDebug -b /home/work/Документы/Мобильное приложение/cordova-plugin-local-notifications-example/platforms/android/build.gradle -PcdvBuildArch=arm -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified

**Comment by Giacomololo** [comment]
Install Android Support Library and Android Support Repository from Android SDK Manager

**Comment by Rockam** [comment]
Hi, I get the same error, but I'm working from a docker with cordova and Android SDK, so I need the command line version of the solution you propose.
I've already included the extra-android-support which it's supposed to be the missing thing, but I still get the same error, any ideas?

Thank you!

**Comment by Rockam** [comment]
Hi again, finally the solution is installing "extra-android-support" and "extra" libs in the android sdk.

Thanks anyway :D

**Comment by SidharthPHariharan** [comment]
@Rockam Yes with latest plugin and updated android sdk solved this issue +1 for the solution.
