### ISSUE TITLE
Please add "quarter" intervall to master 

### ISSUE THREAD

**Issue by katche70** [katzer/cordova-plugin-local-notifications#727]
Android: 
Options.java
else
        if (every.equals("quarter")) {
            interval = AlarmManager.INTERVAL_HOUR * 2190;
        }

Ios
APPLocalNotificationOptions.m (
else if ([interval isEqualToString:@"quarter"]) {
        return NSCalendarUnitQuarter;
    }

**Comment by katzer** [comment]
Would you please open an PR, tks!
