### ISSUE TITLE
Local notifications problem with Angularjs

### ISSUE THREAD

**Issue by romanornr** [katzer/cordova-plugin-local-notifications#729]
I have a problem with Android mobile notifications. I am using Angularjs and ionic framework.
I want to work with local notifications and I use this plugin. https://github.com/katzer/cordova-plugin-local-notifications

<addr>
var app = angular.module('Forex', ['ionic', 'ngCordova']) 
app.controller("MainCtrl", function($scope,$http,$interval, $ionicPlatform, $cordovaLocalNotification) {

$ionicPlatform.ready(function () {
    $scope.scheduleSingleNotification = function () {
      $cordovaLocalNotification.schedule({
                    id: 1,
                    text: 'test'
      })
      .then(function (result) {
        console.log(result);
      });
      }

    });

But if I press the button in my html page 
ng-click="notification()"

I get an error 
ReferenceError: $cordova is not defined

**Comment by PatrickDinh** [comment]
Hi romanornr,
I'm using localnotification with AngularJS too.
Try to use
```
$window.plugin.notification.local
```
instead of 
```
$cordovaLocalNotification.schedule
```

**Comment by Linerd00** [comment]
@PatrickDinh $window.plugin.notification.local is not a function.

**Comment by PatrickDinh** [comment]
@Linerd00 sorry, it seems like my app wires notification in a different way. According to the plugin.xml, you should be able to access it by `cordova.plugins.notification.local` or `plugin.notification.local`

**Comment by romanornr** [comment]
@PatrickDinh I get this error 
Uncaught TypeError: Cannot read property 'notification' of undefined

Why is every documentation about this plugin so different. Every website and person says something else.

**Comment by PatrickDinh** [comment]
@romanornr my apologies, I didn't see that you are using Ionic. It could be different to my experience (I'm using AppBuilder). 
I had the same problem with you when I first used the plugin, turned out it was me didn't register it probably.

Good luck

**Comment by dansanti** [comment]
did you load ng-cordova.js on index.html?

**Comment by SidharthPHariharan** [comment]
I am using this plugins with ionic framework. getting error stating Cannot get property 'subscribe' from undefined at local-notification-util.js:293
this is the line

// Called before 'deviceready' event
channel.onCordovaReady.subscribe(function () {
    // Device plugin is ready now
    channel.onCordovaInfoReady.subscribe(function () {
        // Merge platform specifics into defaults
        exports.applyPlatformSpecificOptions();
    });
});

**Comment by SidharthPHariharan** [comment]
![localnotification](https://cloud.githubusercontent.com/assets/9650370/11329682/a90ab4d6-91c5-11e5-91c7-e90298169a2f.png)

**Comment by dansanti** [comment]
@SidharthPHariharan your  issue is diferent, open a new ticket, my be was a compile problem, check if Local Notifications is  compiled correctly, there are a problem if you don't add com.android.support:support-v4

**Comment by SidharthPHariharan** [comment]
@dansanti I had that issue with support library and later resolved that too.. moreover its a build issue but this is runtime issue.. anyway i will open a new ticket but i thought its still related angular ionic.

**Comment by dansanti** [comment]
@SidharthPHariharan i'm using ionic too, try removing and adding again localnotification, sometimes if you update localnotification and then execute "ionic prepare android", this don't update android project

**Comment by katzer** [comment]
Guys I hope and feel that the community can help about `ngCordova` and `Angular` issues and experiences.

**Comment by elizabethrego** [comment]
Hey @romanornr, I'm using Ionic too. Are you positive ngCordova is properly installed/defined? Are you testing on a real device or simulator? Cordova doesn't work using ionic serve.

**Comment by RylandCai** [comment]
I'm using ionic and angular and I get this error 
Uncaught TypeError: Cannot read property 'notification' of undefined

I've seen many documentation and websites about this issue and haven't got a solution yet.

**Comment by Cheng-angular** [comment]
Hi, @guys.
I'm trying to implement this package into Angular8 app.
But not sure how to import it and use correctly.
I will appreciate if anyone guide me to use it.
Thanks.
Cheng
