### ISSUE TITLE
Unable to clear scheduled notifications in iOS 9

### ISSUE THREAD

**Issue by brandoncorbin** [katzer/cordova-plugin-local-notifications#730]
I've tried every possible combination of 

cordova.plugins.notification.local.cancel
cordova.plugins.notification.local.cancelAll
cordova.plugins.notification.local.clear
cordova.plugins.notification.local.clearAll

Even when getIds or getTriggered returns no ID's the notifications remain. 

Cordova 5, iOS 9

**Comment by mekaercu** [comment]
+1

iPhone'umdan gönderildi

26 Eki 2015 tarihinde 00:07 saatinde, Brandon Corbin <notifications@github.com> şunları yazdı:

**Comment by bensinther** [comment]
+1

**Comment by gnazarkin** [comment]
+1

**Comment by katzer** [comment]
@brandoncorbin I cannot reproduce. When I clear a notification its not visible anymore in the notification center.

**Comment by zwacky** [comment]
when i have notifications scheduled and ill install a new version of the app, `cancelAll` doesn't remove the scheduled ones from the first app install.

this might be connected with this issue.

**Comment by GitRubb** [comment]
+1

**Comment by alexymik** [comment]
Having this issue also. Here's the code to reproduce:

```javascript
var now             = new Date().getTime(),
    _5_sec_from_now = new Date(now + 5*1000);

cordova.plugins.notification.local.schedule({
    id: 1,
    text: "Delayed Notification",
    at: _5_sec_from_now,
    sound: null
});

cordova.plugins.notification.local.cancel(1, function() {});
cordova.plugins.notification.local.cancelAll();

cordova.plugins.notification.local.on('trigger', function(notification) {
    if (notification.id == 1) {
        alert('Should not see me');
    }
});
```

**Comment by alexymik** [comment]
Is this working for anyone else or is there a workaround we can implement? Currently I'm not able to stop any scheduled notifications from firing.

**Comment by zwacky** [comment]
seems like the OS is the big problem. #747

**Comment by alexymik** [comment]
It could be the two issues are related, I'm not sure. The difference between the referenced issue and the example I posted above is that in the example the scheduled notification triggers with the app running in the foreground despite being cancelled using both methods.

**Comment by katzer** [comment]
@alexymik Please consider in your code snippet that all methods are working async! Thats big difference. You need to call `cancel` from within the callback of `schedule`.

@brandoncorbin See #747

**Comment by brandoncorbin** [comment]
Hey @katzer: So you'll need to schedule it again, then cancel it via the callback? Could you correct @alexymik example for all of us? I'm sure everyone would be very grateful.  - B

**Comment by alexymik** [comment]
@katzer Thank you for the clarification. I referenced the docs while building the example and it wasn't clear to me whether the function was asynchronous or not. Checking again, I see in [this documentation page]( https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling) that a callback is mentioned.

@brandoncorbin Here's the updated code which successfully cancels the notification:
```javascript
var now             = new Date().getTime(),
    _5_sec_from_now = new Date(now + 5*1000);

cordova.plugins.notification.local.schedule({
    id: 1,
    text: "Delayed Notification",
    at: _5_sec_from_now,
    sound: null
}, function(notification) {

    cordova.plugins.notification.local.cancel(1, function() {});
    cordova.plugins.notification.local.cancelAll();

    cordova.plugins.notification.local.on('trigger', function(notification) {
        if (notification.id == 1) {
            alert('Should not see me');
        }
    });
});
```

Thanks everyone for your help.

**Comment by katzer** [comment]
```js
var now             = new Date().getTime(),
    _5_sec_from_now = new Date(now + 5*1000);

cordova.plugins.notification.local.schedule({
    id: 1,
    text: "Delayed Notification",
    at: _5_sec_from_now,
    sound: null
}, function() {
    cordova.plugins.notification.local.cancel(1);
});

cordova.plugins.notification.local.on('trigger', function(notification) {
    ...
});
```

The methods are all async!

__Note:__ Never register callbacks within callbacks!
