### ISSUE TITLE
unable to serialize user info crashes app on latest version 

### ISSUE THREAD

**Issue by jbalchun** [katzer/cordova-plugin-local-notifications#731]
Calling a notification as follows. This was working fine until i tried to clearAll().    
cordova.plugins.notification.local.schedule({
                        text: "Delayed Notification",
                         id:"1",
                        at: timeUp,
                        led: "FF0000"
                    });

Using the latest version with ionic, getting the following error, app is suspending and crashing. Like i said it was working fine until i tried to cancel notifications. All the fixes I'm seeing are for prior versions, this shouldn't be an issue any more right?
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'unable to serialize userInfo: (null)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010933fc65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010b776bb7 objc_exception_throw + 45
	2   UIKit                               0x0000000109c0d567 -[UIConcreteLocalNotification userInfo] + 0
	3   gainApp                             0x00000001090e3c9f -[UILocalNotification(APPLocalNotification) initWithOptions:] + 127
	4   gainApp                             0x00000001090dc2e6 __33-[APPLocalNotification schedule:]_block_invoke + 374
	5   libdispatch.dylib                   0x000000010be6f186 _dispatch_call_block_and_release + 12
	6   libdispatch.dylib                   0x000000010be8e614 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000010be78552 _dispatch_root_queue_drain + 1768
	8   libdispatch.dylib                   0x000000010be79b17 _dispatch_worker_thread3 + 111
	9   libsystem_pthread.dylib             0x000000010c1fb637 _pthread_wqthread + 729
	10  libsystem_pthread.dylib             0x000000010c1f940d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Tawpie** [comment]
@jbalchun:

Try it with an int for id instead of a string.

**Comment by jbalchun** [comment]
Originally the id tag was excluded and it still did not work, so i don't
expect this is the issue but i will try and get back to you

**Comment by katzer** [comment]
@jbalchun What plugin version do you use?

**Comment by mr-sparks** [comment]
@jbalchun 

I had the exact same problem. Check twice if one of the variables needed for the creation of the notification gets lost on its way. I had it that it worked on the first setup of a notification, but on another request right after that a variable got lost on its way to create the notification. Thats whats resulting in the:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'unable to serialize userInfo: (null)'

Because one of the variable is either empty or invalid..

**Comment by katzer** [comment]
@mr-sparks @jbalchun

Its not that I haven't seen this message before by myself but the OS takes care about `userInfo` and it should not be _null_!

**Comment by katzer** [comment]
Next time I am having such thing I will take a look into it.
