### ISSUE TITLE
Able to schedule (and receive) notifications, unable to call any querying methods.

### ISSUE THREAD

**Issue by lunchbag** [katzer/cordova-plugin-local-notifications#734]
I'm able to call $cordovaLocalNotification.schedule(...) and actually receive the notification on my device, but none of the querying methods seem to work. For example, when I pass in the proper parameters and callback to $cordovaLocalNotification.[isScheduled|getScheduled|hasPermission|getIds], the callback don't get hit. Any ideas why this might be happening?

      notificationArr.push(notificationObj);
      // gets called! and I can receive the notification
      $cordovaLocalNotification.schedule(notificationArr);

      // I hardcoded an id=1 for one of the objects in notificationArr
      $cordovaLocalNotification.isScheduled(1, function(a){
        // don't ever see this console log
        console.log("isScheduled", a);
      });

      $cordovaLocalNotification.getScheduled(1, function(a){
        // don't ever see this console log
        console.log("getScheduled", a);
      });

      $cordovaLocalNotification.hasPermission(function (granted) {
        // don't ever see this console log
        console.log("granted?", granted);
      });

      $cordovaLocalNotification.getIds(function(ids){
        // don't ever see this console log
        console.log("getIds", ids);
      });

**Comment by lunchbag** [comment]
Ah, it's because $cordovaLocalNotification returns promises. My bad!

**Comment by Tawpie** [comment]
@lunchbag -- could you post and example the correct callback? Based on the wiki, I too would have guessed that the code in your original issue writeup would work... Thank you!

**Comment by lunchbag** [comment]
@Tawpie 

It would look something like this:

    $cordovaLocalNotification.isScheduled(1)
    .then(function(response) {
      console.log("is scheduled?", response);
    });

**Comment by Tawpie** [comment]
many thanks. (smacks head and says ‘duh’)

**Comment by pugwonk** [comment]
Man. I'm embarassed to say how long I spent on this before I found this thread. Part of the problem is that $cordovaLocalNotification.isScheduled(blah, function() {}) executes quite happily, but then never calls the callback.
