### ISSUE TITLE
Apple Watch Support?

### ISSUE THREAD

**Issue by cvoisey** [katzer/cordova-plugin-local-notifications#735]
I was wondering if anyone has figured out how to send the notification properly to Apple Watch using this plugin?   More specifically, I know the Notification itself is automatically relayed to the Watch, however it only shows the short message.  I'm looking to add longer details on the Watch if possible.  Can we do this?

**Comment by katzer** [comment]
Apple Watch in general is supported, however the system decides how to display the payload. Actions and events work as expected.
