### ISSUE TITLE
Uncaught TypeError: undefined is not a function - Been struggling with this error for days

### ISSUE THREAD

**Issue by axelpersoon** [katzer/cordova-plugin-local-notifications#736]
Hi guys,

Great work on this plugin, looks like a quality piece of work. Of course I can't really tell until I get it to work..

I have made a simple app to test the local notification plugin, basically comes down to the following setup (simplified a bit): 

A div on homescreen:
`<div onclick="schedule()">Single<br /><span>schedule(1)</span></div>`

With attached script:

            schedule = function () {
                cordova.plugins.notification.local.schedule({
                    id: 1,
                    text: 'Test Message 1',
                    icon: 'http://www.optimizeordie.de/wp-content/plugins/social-media-widget/images/default/64/googleplus.png',
                    sound: null

                });
            };`

When I run the emulator and click on the div, it gives the **'Uncaught TypeError: undefined is not a function'** error, on the 'cordova.plugins.notification.local.schedule' line in my script.

I've included the links to the cordova-plugin.js, local-notification.js, local-notifcation-core.js and local-notification-util.js in the header of the app. Also added the following lines to cordova-plugin.js:

```
"file": "plugins/de.appplant.cordova.plugin.local-notification/www/local-notification.js",
  "id": "de.appplant.cordova.plugin.local-notification.LocalNotification",
  "clobbers": [
   "cordova.plugins.notification.local"
  ]

  "file": "plugins/de.appplant.cordova.plugin.local-notification/www/local-notification-core.js",
    "id": "de.appplant.cordova.plugin.local-notification.LocalNotification.Core",
    "clobbers": [
      "cordova.plugins.notification.local.core"
    ]

   "file": "plugins/de.appplant.cordova.plugin.local-notification/www/local-notification-util.js",
      "id": "de.appplant.cordova.plugin.local-notification.LocalNotification.Util",
      "merges": [
        "cordova.plugins.notification.local.core"
      ]
```

I have been trying all sorts of things, but nothing seems to help. Kinda out of ideas, anyone got a clue what this could be?

**Comment by iamsamwood** [comment]
I'm hitting this as well, it appeared to show up after I upgraded Xcode to support iOS 9.1.

**Comment by katzer** [comment]
Hi, I had the same right now after upgrading cordova iOS platform. I recreated the platform from scratch and then cordova found the plugins.

**Comment by axelpersoon** [comment]
I decided to start with a clean project in the end, which fixed the problem. It seemed that for some reason the deviceready event wasn't firing in my old setup which probably caused the plugin to not be found as well. Not entirely sure what was going on, but its fixed now. Thanks for your replies!
