### ISSUE TITLE
0.8.1 breaking on iOS 9.1

### ISSUE THREAD

**Issue by okobloko** [katzer/cordova-plugin-local-notifications#737]
As in https://github.com/katzer/cordova-plugin-local-notifications/issues/674 the plugin is breaking at : 

`NSString* path = [dict objectForKey:@"sound"];` which seems directly related to the compiler warnings : 

` UILocalNotification+APPLocalNotification.m:44:19: warning: 
      convenience initializer should not invoke an initializer on 'super' [-Wobjc-designated-initializers]
    self = [super init];
                  ^
....de.appplant.cordova.plugin.local-notification/UILocalNotification+APPLocalNotification.m:42:1: warning: 
      convenience initializer missing a 'self' call to another initializer [-Wobjc-designated-initializers]
- (id) initWithOptions:(NSDictionary*)dict
^
2 warnings generated.
`

**Comment by okobloko** [comment]
I've tried using the master branch, but it makes no difference. Still the same error at "path =" (EXC_BAD_ACCESS (code=1, address=.....

**Comment by okobloko** [comment]
The fix here https://github.com/katzer/cordova-plugin-local-notifications/issues/715 seems to help (although for some reason, the app's JS side seems to occasionally freeze when a notification is scheduled).

**Comment by katzer** [comment]
0.8.2-dev supports iOS 9
