### ISSUE TITLE
When I add platform for android,it failed!

### ISSUE THREAD

**Issue by zhujunwei** [katzer/cordova-plugin-local-notifications#738]
Hello katzer.How can i solve the problem ,Error during processing of action! Attempting to revert...
Failed to install 'de.appplant.cordova.plugin.local-notification':Error: Uh oh!
ENOENT, no such file or directory 'C:\Users\Administrator\Desktop\svnItsme360\It
sme_360\platforms\android\local.properties'

**Comment by zhujunwei** [comment]
I found the error .The <framework src="com.android.support:support-v4:+" /> in plugin should be changed to <dependency id="android.support.v4" />.If not ,you will find that you cannot add this to your android platform successfully.

**Comment by gazxm** [comment]
In plugin.xml <dependency id="android.support.v4" /> Replace <framework src="com.android.support:support-v4:+" />  you can add android

**Comment by simar88** [comment]
Hi @zhujunwei can you explain better how did you solve this issue? 
I've also the same more or less and i can't understand what you did to fix it!
Thanks in advance,
Simone

**Comment by katzer** [comment]
@zhujunwei, what do you mean in detail? I recently updated iOS and Android platform to latest cordova versions and got no error.

**Comment by zhujunwei** [comment]
@simar88    <platform name="android"><dependency id="android.support.v4" />  Before the "dependecy" is " framework " ;Take place it  and the plugin will be ok;

**Comment by zhujunwei** [comment]
@simar88  "  platform name="android"    dependency id="android.support.v4"  "

**Comment by katzer** [comment]
@simar88 In general your right that linking it as a dependency is more clean. But to keep compatibility with common plugins like Facebook or push-plugin I cannot use that way.

**Comment by dansanti** [comment]
try with : on android studio, right click on android project and select open module settings (f4)  then select dependencies and add library dependency  com.android.support:support-v4
