### ISSUE TITLE
Trigger event not firing on iOS 9

### ISSUE THREAD

**Issue by fabriziopoggi** [katzer/cordova-plugin-local-notifications#739]
I'm working on Cordova 3.6.3 and version 0.8.1 of the plugin.
Trigger event doesn't work.
Any help?

**Comment by slightlydiff** [comment]
I also have this issue with 0.8.2 on IOS 9.  Any ideas?

**Comment by katzer** [comment]
Works for me with latest version, kitchen sink app and iOS 9.

__Note:__ The callback gets called only when running in foreground!
