### ISSUE TITLE
schedule from background iOS is not popup

### ISSUE THREAD

**Issue by balicekt** [katzer/cordova-plugin-local-notifications#740]
Hello, I have problem with iOS when is notification scheduled from background it doesn't popup. Sometimes I can see it in notification center but I don't see it popup. Android is working just fine. Does anyone could help me? 

Thank you

TB

**Comment by camilacanhete** [comment]
I had the same issue. Probably your app is being killed. See my answer on this topic:

https://github.com/katzer/cordova-plugin-local-notifications/issues/87

**Comment by katzer** [comment]
@balicekt You will only see the pop-up when your app is __not__ in foreground!
