### ISSUE TITLE
Cloned example not working

### ISSUE THREAD

**Issue by ludoanda** [katzer/cordova-plugin-local-notifications#741]
Hello!

I cloned your example, and used `cordova run android --device` to run the app.
Cordova app opens, but keeps saying 'Connecting to device'. Does anyone know what's going wrong?
I'm using a Samsung Galaxy S4

Yours,
L

**Comment by ludoanda** [comment]
Never mind! I created a new cordova project, and followed the INSTALLATION, and got it working now.. hahah

**Comment by katzer** [comment]
Great!
