### ISSUE TITLE
Repeated notifications on iOS 9.1

### ISSUE THREAD

**Issue by dpalou** [katzer/cordova-plugin-local-notifications#743]
Hi!

If I schedule several notifications at once, one of them to be triggered right away and the rest to be triggered later, the notification that has to be triggered right away is triggered several times (as many as notifications scheduled).

An example:

I want to schedule 3 notifications: A, B and C. Notification A has to be triggered right away ('at' property is 1 hour ago), Notification B has to be triggered tomorrow and notification C has to be triggered a week from now. So I call *cordova.plugins.notification.local.schedule* 3 times, with 3 different objects. I verified that the IDs, messages and times of these notifications are the right ones.

I expect that notification A is triggered right away, but not the others. The result, however, is that I end up with notification A triggered 3 times, I can see 3 identical notifications on my notification bar. If I schedule 4 notifications then notification A is triggered 4 times, and so on.

I tested it on an iPad and an iPhone both with iOS 9.1. I'm using the latest version of this plugin (downloaded from GitHub).

Anybody knows how can I fix it?

Thanks!

**Comment by Tawpie** [comment]
@Dani:

use the technique that schedules using an array. It takes “some time” for iOS to process and if you try to schedule them one at a time you will see problems.

**Comment by katzer** [comment]
@dpalou, as @Tawpie correctly mentioned you need to schedule them all in one within an array.
