### ISSUE TITLE
Can't set time by date object

### ISSUE THREAD

**Issue by beamthsa** [katzer/cordova-plugin-local-notifications#745]
Schedule Repeatedly
var now             = new Date().getTime(),
    _5_sec_from_now = new Date(now + 5*1000);
cordova.plugins.notification.local.schedule({
    text: "Delayed Notification",
    at: _5_sec_from_now,
    led: "FF0000",
    sound: null
});
I try according to this code. 
I want to specific time to send notification.
Specific time by date object. ( sethours, setminutes, setdate, setmonth, setfullyear)
 var dateObj = new Date();
dateObj.setFullYear(2015);
dateObj.setMonth(11);
dateObj.setDate(8);
dateObj.setHours(20);
dateObj.setMinutes(26);
cordova.plugins.notification.local.schedule({
                id: 1,
                title: 'App',
                text: 'Desc',
                at: dateObj
});
but this code is not work

**Comment by katzer** [comment]
@beamthsa, the default value for `at` is `new Date()`. Assigning a date object works fine.

If you asking a date pointing to the past the notification will trigger immediately.

**Comment by beamthsa** [comment]
@katzer I don't want to set time in the past I want set time in the future.
But I try many times it's not work T_T

**Comment by katzer** [comment]
@beamthsa Just to make clear `setMonth(11)` points to __December__ and not November!
