### ISSUE TITLE
CancelAll won't remove older scheduled notifications after app update

### ISSUE THREAD

**Issue by zwacky** [katzer/cordova-plugin-local-notifications#747]
scenario:

- user has notifications scheduled in app version A
- user updates to version B without uninstalling
- version B tries to `cancelAll()` notifications, but the scheduled notifications from version A still pop up

this call should remove them though https://github.com/katzer/cordova-plugin-local-notifications/blob/593fe5a8d3fa370f8920eae41f739f66e6889a26/src/ios/APPLocalNotification.m#L158

am i missing something?

**Comment by katzer** [comment]
Don't use _iOS_ ;) To me its a bug of iOS. I aware of it but have to way to fix that if the OS loses the connection between app and notification.
