### ISSUE TITLE
Recurring notification continues to repeat, but no longer appears in scheduledIds

### ISSUE THREAD

**Issue by lunchbag** [katzer/cordova-plugin-local-notifications#748]
Hi there,

I have a repeating notification, let's say, for every minute. Before it fires for the first time, its ID shows up in getScheduledIds. After it fires for the first time, its ID no longer shows up in getScheduledIds, but the notification continues to fire every minute. According to the wiki, recurring notifications should always be 'scheduled'. Any ideas?

Thanks!

**Comment by dansanti** [comment]
if you use android , try with latest commit, because there are some fix with was in past method..

**Comment by katzer** [comment]
Yes that should be fixed with 0.8.2

**Comment by lunchbag** [comment]
@katzer  This doesn't appear to be fixed with 0.8.2! I was on 0.8.2-dev and reproduced the problem after upgrading to 0.8.2. I checked the Obj-C code and it's the same as master. Any ideas?

Specifically, I'm creating a daily recurring notification that doesn't show up anymore in getAllScheduled after its first trigger... but it still triggers daily.
