### ISSUE TITLE
iOS 9.1.0 crash after registerPermission prompt

### ISSUE THREAD

**Issue by sebrojas14** [katzer/cordova-plugin-local-notifications#749]
I'm using ionic (last release), cordova (las release for cordova and iOS cordova lib) and the last release of this plugin (0.8.2). After user accepts or rejects the prompt for permissions, my app crash (freezes)...I had to kill the app and after open it again the prompt doesn't appear and the app works fine.

Please help!

**Comment by randdusing** [comment]
Same thing is happening to me. Only on iOS 9.1 as well.

**Comment by sebrojas14** [comment]
I was using the registerPermission method...I removed and call schedule...it launcs the permission dialog the first time it tryes to schedule a notification

**Comment by randdusing** [comment]
Hmm, I thought it was required to call that in previous versions. I'll try removing it and see what happens. Unfortunately I don't get the error on my device, so I just have to see how the number of crash reports changes...

**Comment by randdusing** [comment]
I think I may have been created some sort of race condition when manually calling registerPermission. After calling hasPermission, I was waiting to call registerPermission, but during that same time I was calling schedule. Calling hasPermission and schedule at almost the same time, may have been causing the issue.

```javascript
window.plugin.notification.local.hasPermission(function(granted) {
	if (!granted) {
		window.plugin.notification.local.registerPermission();
	}
});

cordova.plugins.notification.local.schedule({});
```

**Comment by sebrojas14** [comment]
Schedule make the register, at least using ngCordova. Now I only use schedule, the first time it promts for permissions

**Comment by katzer** [comment]
@sebrojas14 Let me check that with iOS 9.1.

Btw. theres no need to use `registerPermission()` because `schedule()` takes care of that.

**Comment by sebrojas14** [comment]
Yes, i leave ir with only schedule
