### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by matrixreal** [katzer/cordova-plugin-local-notifications#751]
hi
got build fail with new intel xdk and cli 5.1.1
any solution

**Comment by k3nsei** [comment]
Comment this in plugins/de.appplant.cordova.plugin.local-notification/plugin.xml
<framework src="com.android.support:support-v4:+" />

**Comment by matrixreal** [comment]
@k3nsei 
i download this repo
change the line in intel xdk
still build fail

**Comment by matrixreal** [comment]
@k3nsei 
any other solution please ?
it seem that your solution did not work

**Comment by sparkycrisse** [comment]
You should also delete the android-v4.jar lib (platforms/android/libs)

**Comment by dansanti** [comment]
@k3nsei on android studio, right click on android project and select open module settings (f4)  then select dependencies and add library dependency  com.android.support:support-v4

**Comment by Fuv** [comment]
@k3nsei 

Did you change something else too? Because commenting this line gives me compilation error. Happens both on CLI 5.2.2 and 4.1.2

[code]-compile:
    [javac] Compiling 28 source files to .../appanalyzer/platforms/android/bin/classes
    [javac] .../appanalyzer/platforms/android/src/de/appplant/cordova/plugin/notification/Notification.java:34: error: package android.support.v4.app does not exist
    [javac] import android.support.v4.app.NotificationCompat;
    [javac]                              ^
    [javac] .../appanalyzer/platforms/android/src/de/appplant/cordova/plugin/notification/Notification.java:65: error: package NotificationCompat does not exist
    [javac]     private final NotificationCompat.Builder builder;
    [javac]                                     ^
    [javac] .../appanalyzer/platforms/android/src/de/appplant/cordova/plugin/notification/Notification.java:81: error: package NotificationCompat does not exist
    [javac]                     NotificationCompat.Builder builder, Class<?> receiver) {
    [javac]                                       ^
    [javac] .../appanalyzer/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:30: error: package android.support.v4.app does not exist
    [javac] import android.support.v4.app.NotificationCompat;
    [javac]                              ^
    [javac] .../appanalyzer/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:155: error: package NotificationCompat does not exist
    [javac]     private void applyDeleteReceiver(NotificationCompat.Builder builder) {
    [javac]                                                        ^
    [javac] .../appanalyzer/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:177: error: package NotificationCompat does not exist
    [javac]     private void applyContentReceiver(NotificationCompat.Builder builder) {
    [javac]                                                         ^
    [javac] .../appanalyzer/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:119: error: package NotificationCompat does not exist
    [javac]         NotificationCompat.BigTextStyle style;
    [javac]                           ^
    [javac] .../appanalyzer/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:120: error: package NotificationCompat does not exist
    [javac]         NotificationCompat.Builder builder;
    [javac]                           ^
    [javac] .../appanalyzer/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:122: error: package NotificationCompat does not exist
    [javac]         style = new NotificationCompat.BigTextStyle()
    [javac]                                       ^
    [javac] .../appanalyzer/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:125: error: package NotificationCompat does not exist
    [javac]         builder = new NotificationCompat.Builder(context)
    [javac]                                         ^
    [javac] Note: .../appanalyzer/platforms/android/src/com/intel/appx/Notification/xwalk15/AppAnalyzer.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 10 errors

BUILD FAILED
.../android-sdk-linux/tools/ant/build.xml:720: The following error occurred while executing this line:
.../android-sdk-linux/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.[/code]

**Comment by Fuv** [comment]
It seems that I found the problem. I changed that line to the one from previous version (0.8.1), downloaded jar from the Internet and put it in the correct location:
<lib-file src="libs/android/android-support-v4.jar" />

Now it is building, but I don't know why it is not mentioned anywhere.

**Comment by matrixreal** [comment]
use my fork and add the plugin via additions.xml and not the plugin manager

**Comment by katzer** [comment]
See #738
