### ISSUE TITLE
How to handle time zone changes on Android?

### ISSUE THREAD

**Issue by MichelReij** [katzer/cordova-plugin-local-notifications#755]
One of my users went abroad and told me that her Android phone kept delivering her notification in Amsterdam (summer) time (UMT+2), rather than in the time of the US region where she was (UMT+9). 

Also some users complained about their Androids not adjusting to the change in Daylight Saving Time recently.
My iPhone handled this well and neither did I receive any complaints from other iPhone users.

Does anybody know how to make Android take into account the changing of time zones and DST changes?

**Comment by katzer** [comment]
@MichelReij Did you found a way?

**Comment by MichelReij** [comment]
No, I have not yet looked into it. I have 3 more months until the change to Daylight Saving Time... ;-)

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by MichelReij** [comment]
I'm not sure, I have not had any complaints with the last change from daylight saving time to winter time in October. But then again, my app does not have many users anymore... :-(

**Comment by rwillett** [comment]
In that case I'll close it.
