### ISSUE TITLE
Question: Example of getting all notifications into one object array?

### ISSUE THREAD

**Issue by fmiboy** [katzer/cordova-plugin-local-notifications#757]
Hello,
I wonder if someone can show me example of getting all (scheduled, triggered) notifications in one object array?
Thank you! Sorry for putting it here on issues.

**Comment by fmiboy** [comment]
I looks there is an issue with getall method.
If I have 2 scheduled notifications, I will get 1 with repeated.
$cordovaLocalNotification.getAll().then(function(notification) {
                            console.log(JSON.stringify(notification));
                        });
ngcordova just wraps this plugin's getall method. So there is no problem with that, I even tried with plugin method.
cordova.plugins.notification.local.getall(function (notification) {
   //output
})
still same.

**Comment by fmiboy** [comment]
Another issue:
after I got notifications in all of them "at" value is incorrect, when I convert that "at" value new Date(at),
value somewhere around 1970 year...

**Comment by katzer** [comment]
Pls could you provide a code sample how you schedule the notifications.

**Comment by katzer** [comment]
@fmiboy 
> when I convert that "at" value new Date(at), value somewhere around 1970 year

`at` is __seconds__ while `new Date()` expects __milliseconds__
```javascript
new Date(notification.at * 1000);
```

__Note:__ Probably with v0.9 `notification.at` will be already converted to `Date`.

**Comment by katzer** [comment]
> I wonder if someone can show me example of getting all (scheduled, triggered) notifications in one object array?

See the kitchen sink app! The `getAll` method works as expected.
