### ISSUE TITLE
Relying on a deprecated plugin

### ISSUE THREAD

**Issue by andersborgabiro** [katzer/cordova-plugin-local-notifications#758]
Including cordova-plugin-local-notifications makes builds fail on PGB. cordova-plugin-local-notifications-mm at npm works though. Time to merge?

These are the plugins I use in the applicable app:

`<gap:plugin name="cordova-plugin-whitelist" source="npm" />`
`<gap:plugin name="cordova-plugin-device" source="npm" />`
`<gap:plugin name="cordova-plugin-inappbrowser" source="npm" />`
`<gap:plugin name="cordova-plugin-statusbar" source="npm" />`
`<gap:plugin name="cordova-plugin-dialogs" source="npm" />`
`<gap:plugin name="cordova-plugin-appversion" source="npm" />`
`<gap:plugin name="nl.x-services.plugins.toast" />`
`<gap:plugin name="cordova-plugin-vibration" source="npm" />`
`<gap:plugin name="cordova-plugin-local-notifications-mm" source="npm" />`
`<gap:plugin name="cordova-plugin-ibeacon" source="npm" />`

The error message (same for iOS and Android):

Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-local-notifications" via npm Installing "de.appplant.cordova.plugin.local-notification" for ios WARNING: org.apache.cordova.device has been renamed to cordova-plugin-device. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.device` and `cordova plugin add cordova-plugin-device`. Changing plugin to "cordova-plugin-device" Fetching plugin "cordova-plugin-device" via npm Failed to install 'de.appplant.cordova.plugin.local-notification':Error: Expected plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device". at checkID (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/fetch.js:177:15) at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/fetch.js:161:9 at _fulfilled (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13) at /usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:557:44 at flush (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17) at doNTCallback0 (node.js:417:9) at process._tickCallback (node.js:346:13) Expected plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".

Cheers,
Anders

**Comment by katzer** [comment]
@andersborgabiro To check I installed the npm module as follows

```bash
$ npm install de.appplant.cordova.plugin.local-notification
de.appplant.cordova.plugin.local-notification@0.8.2 node_modules/de.appplant.cordova.plugin.local-notification
```

Then I looked into the dependencies

```bash
grep dependency node_modules/de.appplant.cordova.plugin.local-notification/plugin.xml 
    <dependency id="cordova-plugin-device" />
        <dependency id="de.appplant.cordova.common.registerusernotificationsettings" />
```

As you can see the plugin does not rely on `org.apache.cordova.device`. Its using the newer namespace!

**Comment by andersborgabiro** [comment]
Right, but not the cordova-plugin-local-notifications invoked at PhoneGap Build that is 1.0.0.

The plugin list doesn't show a version number for this plugin, but links here where the version is shown:
https://www.npmjs.com/package/cordova-plugin-local-notifications

As far as I understand it, it's simply a different plugin. Confusing all the same.

Yet, if I use de.appplant.cordova.plugin.local-notification instead I actually get the same error.

Confusing.

**Comment by katzer** [comment]
@andersborgabiro PGB allows you to define the source of the package, e.g npm or PGB. Make sure that you are using npm or ask their support whats going on.

**Comment by andersborgabiro** [comment]
I just described what the problem is: a name conflict. Please fix it by changing the name of your plugin or ask the other author to.

**Comment by andersborgabiro** [comment]
To try to summarize:

`<gap:plugin name="de.appplant.cordova.plugin.local-notification" source="npm" />`
Result:
iOS: "Error - The following plugin, plugin version or a dependancy of this plugin is not on npm: de.appplant.cordova.plugin.local-notification"
Android: "Error - One of your plugins required the gradle android build tool to build"
Fair enough.

`<gap:plugin name="cordova-plugin-local-notifications" source="npm" />`
Result: The previously mentioned error for both iOS and Android. Chooses (as far as I understand) https://www.npmjs.com/package/cordova-plugin-local-notifications, not your plugin. One of many forks of this plugin.

In neither case does PGB's list of used plugins show any version, probably because of the error.

`<gap:plugin name="cordova-plugin-local-notifications-mm" source="npm" />`
Result: Both succeed and work. Version 1.0.1

I'm tapped out, and will not do anything more with this unless also "-mm" breaks.

Did you try to build an example with PGB?

Cheers,
Anders

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by andersborgabiro** [comment]
No longer if I use de.appplant.cordova.plugin.local-notification. I've replaced use of other variants everywhere.
