### ISSUE TITLE
Installing Plugin faild

### ISSUE THREAD

**Issue by cSteusloff** [katzer/cordova-plugin-local-notifications#759]
I want to install this plugin in Visual Studio 2015 with cordova. I get this error:

1> Installing "de.appplant.cordova.plugin.local-notification" for android
1>  Running command: D:\VS\Local\App2\App2\platforms\android\cordova\version.bat
1>  Command finished with error code 0: D:\VS\Local\App2\App2\platforms\android\cordova\version.bat
1>  Dependencies detected, iterating through them...
1>  Dependent plugin "cordova-plugin-device" already fetched, using that version.
1>  Dependent plugin "cordova-plugin-device" already installed on android.
1>  Install start for "de.appplant.cordova.plugin.local-notification" on android.
1>  Beginning processing of action stack for android project...
1>  Parsing android project files...
1>  Installing Android library: com.android.support:support-v4:+
1>  Error during processing of action! Attempting to revert...
1>  Failed to install 'de.appplant.cordova.plugin.local-notification':TypeError Uh oh!
1>  Path must be a string. Received undefined
1>      at assertPath (path.js:8:11)
1>      at Object.win32.resolve (path.js:130:5)
1>      at module.exports.framework.install (C:\Users\chris\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
1>      at Object.ActionStack.process (C:\Users\chris\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:67:25)
1>      at handleInstall (C:\Users\chris\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:575:20)
1>      at C:\Users\chris\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:335:28
1>      at _fulfilled (C:\Users\chris\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\q\q.js:787:54)
1>      at self.promiseDispatch.done (C:\Users\chris\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\q\q.js:816:30)
1>      at Promise.promise.promiseDispatch (C:\Users\chris\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\q\q.js:749:13)
1>      at C:\Users\chris\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\q\q.js:509:49
1>  TypeError: Uh oh!
1>  Path must be a string. Received undefined

**Comment by hanschrome** [comment]
I have the same problem running it in console. I couldn't solve it yet
1> Installing Android library: com.android.support:support-v4:+
1> Error during processing of action! Attempting to revert...
![image](https://cloud.githubusercontent.com/assets/6317267/11459721/47bf2096-96dd-11e5-90a8-6cdcd5aa0006.png)

**Comment by cSteusloff** [comment]
Download the android sdk and install the "extras" components.
![29-11-2015 21-41-46](https://cloud.githubusercontent.com/assets/1674741/11459917/1284b562-96e2-11e5-9114-92afef2fde8b.png)
