### ISSUE TITLE
[suggestion]add support of using local or remote image as large icon in android

### ISSUE THREAD

**Issue by gitawego** [katzer/cordova-plugin-local-notifications#76]
as title said. that would be nice. because I wanna show the icon that reflects the current message content.

something like this: http://stackoverflow.com/a/20599257

thanks for your amazing plugin

**Comment by performatric** [comment]
This issue is closed, but does not working for me.

Ionic: 3.4.0
Cordova: 7.0.1

I'm trying to set the notification icon as a remote image https://domain.co/avatar where's image a jpg and should be works like the profile image of Whatsapp.

that's my code:

```
this.localNotification.schedule({
   title: 'Hello World',
   text: 'Lorem ipsum dolor sit amet',
   // sample image
   icon: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Mlg_illuminati.png'
});
```

config.xml

```
<access origin="*" />
<allow-intent href="http://*/*" />
<allow-intent href="https://*/*" />
```

the code works, but the bell icon's is showed.

how do I do? Sorry my english :/

**Comment by Tawpie** [comment]
I haven’t looked at the actual code, but do suspect that the plugin only works with images that are included in the app bundle. This suspicion is based on the fact that for Android at least, it will only show a custom icon if that icon is in platforms/android/res/drawable-ldpi (-mdpi, -hdpi and -xhdpi).

So I wouldn’t think that your scheme of getting the icon from the internet will work. Besides which, depending on the handset, the plugin needs a differently sized icon so your internet source would have to be able to return a different icon depending on the screen size of the handset.

**Comment by performatric** [comment]
Unfortunately in documentation this is not explained, but in readme is written:

```
icon: "http://icons.com/?cal_id=1",
```
