### ISSUE TITLE
Problem with weekly notifications.

### ISSUE THREAD

**Issue by midhunadarvin** [katzer/cordova-plugin-local-notifications#760]
Hi,
I am setting the notification object as shown below. However i am not receiving the weekly notifications correctly. Can anyone verify that the given syntax is valid? 

    var notificationOb = {
      "at":"2015-11-24T02:30:00.693Z",
      "id":"1800",
      "title":"Sample",
      "text":"You can create weekly report of last week",
      "every":"week"
    }

    window.plugin.notification.local.schedule(notificationOb);

**Comment by svludwig** [comment]
The code looks correct to me. You might try to use "firstAt" instead of "at" though, at least that's the way it's done in the samples, don't know if it actually makes a difference.

**Comment by katzer** [comment]
@midhunadarvin You should pass the date as a date or number object and not as a string.
