### ISSUE TITLE
runtime issue with ionic framework

### ISSUE THREAD

**Issue by SidharthPHariharan** [katzer/cordova-plugin-local-notifications#761]
I am using this plugins with ionic framework. getting error stating Cannot get property 'subscribe' from undefined at local-notification-util.js:295
this is the line

    // Called before 'deviceready' event
    channel.onCordovaReady.subscribe(function () { //  <---- this is 295
        // Device plugin is ready now
        channel.onCordovaInfoReady.subscribe(function () {
            // Merge platform specifics into defaults
            exports.applyPlatformSpecificOptions();
         });
    });
![localnotification](https://cloud.githubusercontent.com/assets/9650370/11330635/54ba8be0-91d4-11e5-807c-97a79c4b2b86.png)

**Comment by katzer** [comment]
Whats your Cordova version?
