### ISSUE TITLE
ios bug

### ISSUE THREAD

**Issue by match08** [katzer/cordova-plugin-local-notifications#762]
[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xb000000000000005

**Comment by match08** [comment]
isPresent bug

**Comment by GitRubb** [comment]
Any fix planned for this? when using cancelNotification it's crashing my iOS app.

**Comment by match08** [comment]
I found the reason for the ID type problem , id is not number, ID is string number:'unrecognized selector sent to instance 0xb000000000000005'.  Is my own reason. ID type is number,sorry

**Comment by katzer** [comment]
Yes it needs to be a Number!
