### ISSUE TITLE
Plugin kills whole application

### ISSUE THREAD

**Issue by Sanafan** [katzer/cordova-plugin-local-notifications#763]
Hey guys,
my application crashes everytime i want to play a sound.

` double timestamp = [[dict objectForKey:@"at"]
                        doubleValue];`

Is the part which gets marked by xcode as crash-reason. `Thread 16: EXC_BAD_ACCESS (code=1, address=0x10)`. 

This is my function:

`function playSound(){
	cordova.plugins.notification.local.schedule({
	    id: 1,
	    text: "Bestellung eingegangen!",
	    sound: isAndroid ? 'file://sound.mp3' : 'file://sound.mp3'
	});
}`

**Comment by electronicmax** [comment]
hey @Sanafan  - did this get resolved? i'm having this same problem now with 0.8.2dev and cordova-ios 3.9.2
