### ISSUE TITLE
Interactive notifications with buttons

### ISSUE THREAD

**Issue by svludwig** [katzer/cordova-plugin-local-notifications#765]
Is it possible to make notifications interactive by adding buttons? I couldn't find anything in the Wiki about it, so I guess that function doesn't exist yet?

Here is an example for what I'm talking about:
https://code.exacttarget.com/apis-sdks/journey-builder-for-apps/feature-implementation/implement-interactive-notifications.html#android

I would love to be able to add buttons to my local notifications in cordova.

**Comment by ammichael** [comment]
No answers? Sad :(

I need this too. I'm pretty sure this plugins doesnt do that, but I don't know if it's possible at all, or if it's just not implemented yet.

**Comment by elizabethrego** [comment]
Hey, my fork of this has interactive notifications for iOS, and I'm hoping to have Android done by the end of this week. Talking to Katzer about having the changes merged when complete.

https://github.com/elizabethrego/cordova-plugin-local-notifications

There's documentation on how to use them and everything.

**Comment by ammichael** [comment]
You are a genius!

I will give it a try as soon as possible.

Thank you!

**Comment by elizabethrego** [comment]
Awesome, let me know if you have any issues!

**Comment by svludwig** [comment]
@elizabethrego This is awesome! I need this for Android so I will wait and give it a try as soon as it's available.Thank you!

**Comment by elizabethrego** [comment]
Great, I'll post back as soon as it's done :)

**Comment by katzer** [comment]
:+1:

**Comment by elizabethrego** [comment]
Android actions are done now in my fork! Hopefully they can get merged soon :)

**Comment by maxHus** [comment]
:+1:

**Comment by ishotjr** [comment]
@elizabethrego So glad I found this - thank you!!! :bowtie: :+1:

**Comment by ankitp29** [comment]
I am developing an app in ionic and have installed [this](https://github.com/elizabethrego/cordova-plugin-local-notifications) plugn. However I am getting following errors. 

```
/Volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/inAppCamDentistry/Plugins/de.appplant.cordova.plugin.local-notification-ios9-fix/UIApplication+APPLocalNotification.m:131:72: warning: undeclared selector 'setBehavior:' [-Wundeclared-selector]
                                    if ([newAction respondsToSelector:@selector(setBehavior:)]) {
                                                                       ^
/Volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/inAppCamDentistry/Plugins/de.appplant.cordova.plugin.local-notification-ios9-fix/UIApplication+APPLocalNotification.m:133:47: error: use of undeclared identifier 'UIUserNotificationActionBehaviorTextInput'; did you mean 'UIUserNotificationActionContextDefault'?
                                            ? UIUserNotificationActionBehaviorTextInput : UIUserNotificationActionBehaviorDefault];
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                              UIUserNotificationActionContextDefault
In file included from /Volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/inAppCamDentistry/Plugins/de.appplant.cordova.plugin.local-notification-ios9-fix/UIApplication+APPLocalNotification.m:1:
In file included from /Volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/inAppCamDentistry/inAppCamDentistry-Prefix.pch:25:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:58:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:24:5: note: 'UIUserNotificationActionContextDefault' declared here
    UIUserNotificationActionContextDefault,  // the default context of a notification action
    ^
/Volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/inAppCamDentistry/Plugins/de.appplant.cordova.plugin.local-notification-ios9-fix/UIApplication+APPLocalNotification.m:133:91: error: use of undeclared identifier 'UIUserNotificationActionBehaviorDefault'; did you mean 'UIUserNotificationActionContextDefault'?
                                            ? UIUserNotificationActionBehaviorTextInput : UIUserNotificationActionBehaviorDefault];
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                          UIUserNotificationActionContextDefault
In file included from /Volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/inAppCamDentistry/Plugins/de.appplant.cordova.plugin.local-notification-ios9-fix/UIApplication+APPLocalNotification.m:1:
In file included from /Volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/inAppCamDentistry/inAppCamDentistry-Prefix.pch:25:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:58:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:24:5: note: 'UIUserNotificationActionContextDefault' declared here
    UIUserNotificationActionContextDefault,  // the default context of a notification action
    ^
/Volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/inAppCamDentistry/Plugins/de.appplant.cordova.plugin.local-notification-ios9-fix/UIApplication+APPLocalNotification.m:132:52: error: no visible @interface for 'UIMutableUserNotificationAction' declares the selector 'setBehavior:'
                                        [newAction setBehavior:[[action objectForKey:@"behavior"]  isEqual: @"textInput"]
                                         ~~~~~~~~~ ^~~~~~~~~~~
/Volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/inAppCamDentistry/Plugins/de.appplant.cordova.plugin.local-notification-ios9-fix/UIApplication+APPLocalNotification.m:136:105: error: use of undeclared identifier 'UIUserNotificationTextInputActionButtonTitleKey'
                                                                                                 forKey:UIUserNotificationTextInputActionButtonTitleKey]];
                                                                                                        ^
1 warning and 4 errors generated.

** BUILD FAILED **


The following build commands failed:
	CompileC build/inAppCamDentistry.build/Debug-iphonesimulator/inAppCamDentistry.build/Objects-normal/i386/UIApplication+APPLocalNotification.o inAppCamDentistry/Plugins/de.appplant.cordova.plugin.local-notification-ios9-fix/UIApplication+APPLocalNotification.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/cordova/build-debug.xcconfig,-project,inAppCamDentistry.xcodeproj,ARCHS=i386,-target,inAppCamDentistry,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /volumes/data/inAppCamDentistryWithIntNotification/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```
I am a Angular developer and don't know ios(objective c). Could you please help me in solving this issue.
Thanks in advance.

**Comment by elizabethrego** [comment]
@ankitp29 All of the errors have to do with iOS 9 capabilities. Is there any chance you don't have the iOS 9 SDK downloaded in Xcode?

**Comment by katzer** [comment]
The actions are now available from the 0.9-dev branch

**Comment by ankitp29** [comment]
0.9-dev branch not working and generate same errors as https://github.com/elizabethrego/cordova-plugin-local-notifications plugin

**Comment by elizabethrego** [comment]
Which would make sense for ios 9 sdk not being downloaded, please let me
know because I'd love to fix it if that's not the case.

**Comment by ankitp29** [comment]
i have used 8.3 sdk, can you help me to done with 8.3sdk

**Comment by ankitp29** [comment]
i am not aware from ios native developement so please help me to solve this error

**Comment by elizabethrego** [comment]
If you're using the 8.3 SDK you'll need to remove the offending lines, but I really recommend just downloading the iOS 9 SDK.

**Comment by ejazmafat999** [comment]
but as i told earlier as [ankitp29](https://github.com/ankitp29)  that i am not aware from ios native developement , so how can i identify which lines are offending. sorry in advance , but help me

**Comment by elizabethrego** [comment]
Is there a reason you don't want to download the iOS 9 SDK? Because that would solve your problem pretty quickly and doesn't require any knowledge of iOS native development...

**Comment by rwillett** [comment]
Hi,

Has this fork been merged back into the main branch please or should I go and and look at Elizabeth's fork?

Rob

**Comment by mattsilv** [comment]
+1 for @rwillett 's question.  Has this fork been merged back?

**Comment by rwillett** [comment]
I'll take this as a no :(

**Comment by waleedasif322** [comment]
+1, just donated too

**Comment by BioPhoton** [comment]
Hey when do you merge the branch with the interactive notifications??????

**Comment by jljaker** [comment]
I'm lost and was hoping someone could help out.   I'm trying to use the branch from elizabethrego , but, the most recent one with the ios9 fix. But when do "Cordova plugin add" on her repo I get this plugin installed: de.appplant.cordova.plugin.local-notification-ios9-fix

But for ngCordova to work it needs the original name. How do I go about using her branch??? Am I supposed to manually merge her branch? Copy and replace some files?  

Help!!!!

(As a side note I did try installing v9 of katzer's plugin but it doesn't seem to work at all on ios.)

**Comment by katzer** [comment]
Hello everyone, I've released a new version of the print plugin and the background and local-notification plugin comes next. So please give me a little time for it. Thanks!

**Comment by jljaker** [comment]
Awesome, can't wait for the new notification version!

In the meantime I did resolve elizabethrego's version regarding the issue with the iOS version not working. It's the same solution as the badge plugin that someone posted. In each of the two files, plugin.xlm, and src/ios/APPLocalNotification.m

replace: de.appplant.cordova.common.registerusernotificationsettings
with this: cordova-plugin-app-event

I actually installed plugin cordova-plugin-app-event prior to installing the location notification plugin but not sure if that was necessary.

Hope this helps

**Comment by mubasshir** [comment]
@katzer any idea when @elizabethrego 's commit will be merge? I'm in need of action buttons on Android. Thank you both

**Comment by keithpickering** [comment]
Any update on this? I would use @elizabethrego 's solution but apparently it's outdated now?

**Comment by BioPhoton** [comment]
Hi, I have the fork in betha for some month an  just want to know a rough timeline. Have many Plugins of @katzer in use and would love to push interactive notifications into rc in my projekt.

THX for past development and comming Version of notifications!!

**Comment by rwillett** [comment]
I'm using @katzers notification plugin and would welcome the fork with buttons.

What would be even better would be that the @BioPhoton fork stops being a fork and merges back into the main branch of this plugin. Having too many forks is a problem to us, we would much prefer a well supported main plugin with this functionality.

Thanks for the work,

Rob

**Comment by keithpickering** [comment]
@rwillett There are an incredible number of forks. @katzer 's plugin has been updated most recently, but it's missing features? It really doesn't make any sense. Can someone just let me know which version/fork of this plugin allows actionable notifications and also works on new versions of iOS?

**Comment by Rafff** [comment]
@keithpickering @elizabethrego's fork enables this functionnality.
@katzer 's plugin should merge the @elizabethrego's fork soon, but it's been delayed because of refactorization.

@katzer Any updates on this merge ?

I would love to use this feature too!

**Comment by jljaker** [comment]
BTW folks, even after doing the mods I listed above, it seems to crash on Android Marshmallow 6.0 :(

The action buttons work fine in Lollipop and kater's current version (without the action buttons) works fine in Android 6.0.

So I think this is a moot point for now until @katzer merges in @elizabethrego's changes and fixes the Android 6.0 issues.

I also hope katzer isn't holding up release due to wanting to support Windows :)

**Comment by BioPhoton** [comment]
This is a very important feature for all of us. What do you think about crowd sourcing this one?? :-)
https://www.bountysource.com/issues/28652500-interactive-notifications-with-buttons

**Comment by Artfloriani** [comment]
Hey folks,

I am currently mantaining a fork with actions on both Android and iOS. It is in very very early stages. I got together many PRs from other forks, plus some minimal code from myself in order to have this working. 

I updated with the latested changes from katzer ios10 branch. Unfortunatelly my time is quite limited and I was not able to organize everything or even do it the proper way. I lost a few of the original commits and will fix it as soon as possible. 

I will be updating this fork, until the official repository is updated with actions. 

I should update the docs on how to use soon. 

Any help is appreciated 👍 

Cheers

**Comment by smgjreinieren** [comment]
@Artfloriani Did you allready managed to finish it? If so I would love to use the action buttons on android and ios.

**Comment by hammadjamil** [comment]
@elizabethrego i am using you code, notification pops up successfully in the notification list but when i click on the actions button or any where on the notification my ionic app crashes immediately. currently i am stuck following are my steps to install and use you code.

Install using following cammand : 
cordova plugin add https://github.com/elizabethrego/cordova-plugin-local-notifications

Code : 

**var actions = [ {
            identifier: 'SIGN_IN',
            title: 'Yes',
            icon: 'res://ic_signin',
            activationMode: 'background',
            destructive: false,
            authenticationRequired: true
        },
        {
           identifier: 'MORE_SIGNIN_OPTIONS',
           title: 'More Options',
           icon: 'res://ic_moreoptions',
           activationMode: 'foreground',
           destructive: false,
           authenticationRequired: false
        },
        {
           identifier: 'PROVIDE_INPUT',
           title: 'Provide Input',
           icon: 'ic_input',
           activationMode: 'background',
           destructive: false,
           authenticationRequired: false,
           behavior: 'textInput',
           textInputSendTitle: 'Reply'
        }];

        cordova.plugins.notification.local.schedule({
                id: 1,
                title: "Production Jour fixe",
                text: "Duration 1h",
                actions: [actions[0], actions[1]],
                category: 'SIGN_IN_TO_CLASS'
        });
        
        
        $window.cordova.plugins.notification.local.on('action', function (notification, state, data) {
            alert('hoot');
            $timeout(function () {
                 alert('moot');
              $rootScope.$broadcast('$cordovaLocalNotification:action', notification, state, data);
            });
        });
        
        $rootScope.$on('$cordovaLocalNotification:action', function(event, notification, state, data) {
            // use conditionals to choose actions to take like above, blah blah
            alert('cooool');
        });**



Correct me if i am missing some thing

**Comment by rwillett** [comment]
@hammadjamil I've never had any reply from Elizabeth. I would consider her plugin as abandoned. I'd be delighted to be proven wrong.

**Comment by globules-io** [comment]
Any update on this? Thanks

**Comment by katzer** [comment]
@globules-io See the `x` and `sample-x` branch. However as long as its not yet in the master its not intended to use as of now.

**Comment by globules-io** [comment]
Thanks for the reply, Katzer

**Comment by katzer** [comment]
Thats possible with 0.9-beta. See the README. Thanks!
