### ISSUE TITLE
Scheduling multiple notifications at different times

### ISSUE THREAD

**Issue by khalid-hussain** [katzer/cordova-plugin-local-notifications#768]
Hi there,

I'm having some trouble here and I'm a complete beginner at Javascript. The app gets values from the GPS which is then passed to another javascript function which calculates Muslim prayer times.

I then set up notifications for each of the prayer times using the function below but for some reason I'm only getting the last notification ("This is the TEST!"). Does anyone know why?

```javascript
function add_reminder(list, times) {
        var salahTimes = [];

        for (var i = 0; i < 6; i++) {
            var schedule_time = new Date();
            var strTimeTemp = times[list[i].toLowerCase()].split(':');

            schedule_time.setHours(strTimeTemp[0], strTimeTemp[1]);
            salahTimes[i] = schedule_time;
        }

        console.log("salahTimes: ");
        console.log(salahTimes);
        console.log(list);

        cordova.plugins.notification.local.schedule([{
            title: list[0],
            text: "Time for Fajr in your area",
            at: salahTimes[0],
            every: "day"
        }, {
            title: list[1],
            text: "It is now Sunrise",
            at: salahTimes[1],
            every: "day"
        }, {
            title: list[2],
            text: "Time for Zuhur in your area",
            at: salahTimes[2],
            every: "day"
        }, {
            title: list[3],
            text: "Time for Asr in your area",
            at: salahTimes[3],
            every: "day"
        }, {
            title: list[4],
            text: "Time for Maghrib in your area",
            at: salahTimes[4],
            every: "day"
        }, {
            title: list[5],
            text: "Time for Isha in your area",
            at: salahTimes[5],
            every: "day"
        }, {
            title: "Khalid",
            text: "This is the TEST!"
        }]);        
    }
```

**Comment by katzer** [comment]
@khalid-hussain Except the last one `This is the TEST!` the others are in the future. Thats why they do not appear immediately.

**Comment by khalid-hussain** [comment]
Actually, that is why I came here. I'm sorry I was not clear earlier. The notifications don't appear at all, I've waited for about two days but nothing shows up. If it helps, here is the complete JS code I'm using:

```javascript
function onSuccess(position) {
    var element = document.getElementById('geolocation');
    element.innerHTML = 'Latitude: ' + position.coords.latitude + '<br />' +
        'Longitude: ' + position.coords.longitude + '<br />' +
        'Altitude: ' + position.coords.altitude + '<br />';

    // Get GPS coordinates
    var lat = position.coords.latitude;
    var lang = position.coords.longitude;

    // Prayer Times JS; get prayer times according to GPS coordinates
    prayTimes.setMethod('Makkah');
    var list = ['Fajr', 'Sunrise', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'];
    var date = new Date(); // today
    var times = prayTimes.getTimes(date, [lat, lang]);
    
    console.log("times:");
    console.log(times);

    // Generate table with Prayer Names and Times
    var html = '<table id="timetable">';
    html += '<tr><th colspan="2">' + date.toLocaleDateString() + '</th></tr>';
    for (var i in list) {
        html += '<tr><td>' + list[i] + '</td>';
        html += '<td>' + times[list[i].toLowerCase()] + '</td></tr>';
    }
    html += '</table>';
    document.getElementById('table').innerHTML = html;

    /*===============================
    Local Notifications
    =================================*/
    add_reminder(list, times);    

    function add_reminder(list, times) {
        var salahTimes = [];

        for (var i = 0; i < 6; i++) {
            var schedule_time = new Date();
            var strTimeTemp = times[list[i].toLowerCase()].split(':');

            schedule_time.setHours(strTimeTemp[0], strTimeTemp[1]);
            salahTimes[i] = schedule_time;
        }

        console.log("salahTimes: ");
        console.log(salahTimes);
        console.log(list);

        cordova.plugins.notification.local.schedule([{
            title: list[0],
            text: "Time for Fajr in your area",
            at: salahTimes[0],
            every: "day"
        }, {
            title: list[1],
            text: "It is now Sunrise",
            at: salahTimes[1],
            every: "day"
        }, {
            title: list[2],
            text: "Time for Zuhur in your area",
            at: salahTimes[2],
            every: "day"
        }, {
            title: list[3],
            text: "Time for Asr in your area",
            at: salahTimes[3],
            every: "day"
        }, {
            title: list[4],
            text: "Time for Maghrib in your area",
            at: salahTimes[4],
            every: "day"
        }, {
            title: list[5],
            text: "Time for Isha in your area",
            at: salahTimes[5],
            every: "day"
        }, {
            title: "Khalid",
            text: "This is the TEST!"
        }]);        
    }
    
    /*cordova.plugins.notification.local.hasPermission(function(granted) {
        if (granted == true) {
            schedule(list[i], schedule_time);
        } else {
            cordova.plugins.notification.local.registerPermission(function(granted) {
                if (granted == true) {
                    schedule(list[i], schedule_time);
                } else {
                    navigator.notification.alert("Reminder cannot be added because app doesn't have permission");
                }
            });
        }
    }); // End of the notification block*/
}

function onError(error) {
    alert('code: ' + error.code + '\n' +
        'message: ' + error.message + '\n');
}

navigator.geolocation.getCurrentPosition(onSuccess, onError);
```

Thanks for your time and the help so far.

**Comment by katzer** [comment]
@khalid-hussain What OS? Can you tell me if they appear in the notification center because nothing shows up if the app is in foreground.

**Comment by khalid-hussain** [comment]
This is on Android, and only required to be on Android. It's actually a friend's assignment which he asked to help out with.

The Kitchen sink app throws notifications like I expect, even after restarting the phone, which is awesome but I can't seem to get mine to work. Does it have to do with [callback functions](https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling#schedule-repeatedly)?

If you need the source for debugging, I'm willing to share it.

**Comment by khalid-hussain** [comment]
I think I found the answer. Adding `id` fields to each notification in the array made it work. Maybe you can confirm this and add it to the wiki.

**Comment by katzer** [comment]
@khalid-hussain Thats right, haven't seen the missing `id`. If its not provided the plugin uses the same default ID and cancels the previous one with the same ID.

**Comment by aimanaquiyah** [comment]
i am sorry, i am totally a beginner in this native ionic, may i ask, does the function onSuccess need to be inside export class?

**Comment by iamAdamGoodman** [comment]
> Actually, that is why I came here. I'm sorry I was not clear earlier. The notifications don't appear at all, I've waited for about two days but nothing shows up. If it helps, here is the complete JS code I'm using:
> 
> ```js
> function onSuccess(position) {
>     var element = document.getElementById('geolocation');
>     element.innerHTML = 'Latitude: ' + position.coords.latitude + '<br />' +
>         'Longitude: ' + position.coords.longitude + '<br />' +
>         'Altitude: ' + position.coords.altitude + '<br />';
> 
>     // Get GPS coordinates
>     var lat = position.coords.latitude;
>     var lang = position.coords.longitude;
> 
>     // Prayer Times JS; get prayer times according to GPS coordinates
>     prayTimes.setMethod('Makkah');
>     var list = ['Fajr', 'Sunrise', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'];
>     var date = new Date(); // today
>     var times = prayTimes.getTimes(date, [lat, lang]);
> 
>     console.log("times:");
>     console.log(times);
> 
>     // Generate table with Prayer Names and Times
>     var html = '<table id="timetable">';
>     html += '<tr><th colspan="2">' + date.toLocaleDateString() + '</th></tr>';
>     for (var i in list) {
>         html += '<tr><td>' + list[i] + '</td>';
>         html += '<td>' + times[list[i].toLowerCase()] + '</td></tr>';
>     }
>     html += '</table>';
>     document.getElementById('table').innerHTML = html;
> 
>     /*===============================
>     Local Notifications
>     =================================*/
>     add_reminder(list, times);    
> 
>     function add_reminder(list, times) {
>         var salahTimes = [];
> 
>         for (var i = 0; i < 6; i++) {
>             var schedule_time = new Date();
>             var strTimeTemp = times[list[i].toLowerCase()].split(':');
> 
>             schedule_time.setHours(strTimeTemp[0], strTimeTemp[1]);
>             salahTimes[i] = schedule_time;
>         }
> 
>         console.log("salahTimes: ");
>         console.log(salahTimes);
>         console.log(list);
> 
>         cordova.plugins.notification.local.schedule([{
>             title: list[0],
>             text: "Time for Fajr in your area",
>             at: salahTimes[0],
>             every: "day"
>         }, {
>             title: list[1],
>             text: "It is now Sunrise",
>             at: salahTimes[1],
>             every: "day"
>         }, {
>             title: list[2],
>             text: "Time for Zuhur in your area",
>             at: salahTimes[2],
>             every: "day"
>         }, {
>             title: list[3],
>             text: "Time for Asr in your area",
>             at: salahTimes[3],
>             every: "day"
>         }, {
>             title: list[4],
>             text: "Time for Maghrib in your area",
>             at: salahTimes[4],
>             every: "day"
>         }, {
>             title: list[5],
>             text: "Time for Isha in your area",
>             at: salahTimes[5],
>             every: "day"
>         }, {
>             title: "Khalid",
>             text: "This is the TEST!"
>         }]);        
>     }
> 
>     /*cordova.plugins.notification.local.hasPermission(function(granted) {
>         if (granted == true) {
>             schedule(list[i], schedule_time);
>         } else {
>             cordova.plugins.notification.local.registerPermission(function(granted) {
>                 if (granted == true) {
>                     schedule(list[i], schedule_time);
>                 } else {
>                     navigator.notification.alert("Reminder cannot be added because app doesn't have permission");
>                 }
>             });
>         }
>     }); // End of the notification block*/
> }
> 
> function onError(error) {
>     alert('code: ' + error.code + '\n' +
>         'message: ' + error.message + '\n');
> }
> 
> navigator.geolocation.getCurrentPosition(onSuccess, onError);
> ```
> 
> Thanks for your time and the help so far.

Brother im facing the same issue with local notifications for prayer times on ios .
can u please tell me how did you resolve it ?
