### ISSUE TITLE
Not get notification on device

### ISSUE THREAD

**Issue by webquali** [katzer/cordova-plugin-local-notifications#769]
Hi All,

I use this plugin but don't get notification on device. I success set notification. Maybe someone now were problem?

I use IOS9

Thanks!

**Comment by webquali** [comment]
I works on android and iPad but not working on iPhone. My device iPhone 5s.

Can you help someone please?

**Comment by katzer** [comment]
Maybe your iPhone has some other settings. From code perspective theres no difference between iPad or iPhone.

**Comment by webquali** [comment]
Thanks for answer. Which other settings you mean?

**Comment by katzer** [comment]
@webquali App permissions or notification center settings
