### ISSUE TITLE
onclick is not called?

### ISSUE THREAD

**Issue by Mina-H-Samy** [katzer/cordova-plugin-local-notifications#77]
Thank you very much for the plugin!

I'm having a bit of a problem: My onclick doesn't seem to be getting called

```
        window.plugin.notification.local.add({
            id:          1,
            date:        dateobj,
            message:    'Test Notification',
            title:      'MyApp',
            repeat:     'daily',
            badge:       1,
            autoCancel:  true
        });
        window.plugin.notification.local.onclick = function(id, state, json){
            console.log("SUCCESS");
            alert("success");
        };
```

The notification appears fine and the app loads when I click it, but I don't see anything in console and don't see the alert. Am I correct in assuming the onclick should be fired after user clicks notification and the app loads?

I'm using phonegap build 3.1, plugin 0.7.0, android 4.3. Am I missing anything?

**Comment by vir474** [comment]
does the onclick works now ?? i have the same problem it is not firing when i click on the notification !
