### ISSUE TITLE
What should happen on iOS when initial notification displayed in drawer?

### ISSUE THREAD

**Issue by rwillett** [katzer/cordova-plugin-local-notifications#772]
Hi,

We're trying to work out if this is a bug or a feature. We're not sure and we can't find any docs to tell us. We think we have our app and this plugin working well but for one odd edge case and can't work out if its a problem of not. This is all iOS V8, de.appplant.cordova.plugin.local-notification 0.8.2

If I explain the steps it might be help, just to be clear we're not looking for code or debugging, just some useful insight. We have this stuff working, but its odd for one little bit :)

1. We put our app into the background.  - **All working**

2. We send data to our app via a silent notification using the content-available: 1 flag - **All working**

3. We capture the silent notification in our app - **All working**

4. We go back to our server and download some more data to process - **All working**

5. We process the data we have recovered from the server and generate 2-3 local notifications to display to the user. This simulates the way push notifications work but gives us far, far more control about how we handle and display them, The local-notifications we generate are not scheduled but are simple text messages with a unique piece of data attached so we know how to handle them when the user selects them from the notification drawer. We send the notifications down as an array in one go, rather than as a series of cordova.plugins.notification.local.schedule calls. We read on this site that doing them one after the other is slow. We attach code to show this - **All working**

 ````
                for (var key in notificationQueue)
                {
                    if (debugGetNotificationsFromServerSuccess)
                        ConsoleLog("LocalNotification: " + key + " " + notificationQueue[key].message);

                    switch (whatAmI) {
                        case "ios_app":
                        case "ios_simulator":
                        default:
                            notification = {id: key ,
                                            text: notificationQueue[key].message};
                            break;
		                case "android_app":
                        case "android_simulator":
                            notification = {id: key ,
                                            text: notificationQueue[key].message ,
                                            smallIcon: "file://notification.png"};
                            break;
                    }

                    tmpArray.push(notification);
                }

                cordova.plugins.notification.local.schedule(tmpArray);

                cordova.plugins.notification.local.on("click", function (notification , state) {
                    var debug = 1;

                    if (debug)
                    {
                        ConsoleLog("Local Notifications Click: notification=" + JSON.stringify(notification));
                        ConsoleLog("Local Notifications Click: state=" + JSON.stringify(state));
                    }

                    // Need to remove notification.id from notificationQueue
                    RemoveNotificationFromQueue(notification.id);
                    $rootScope.$broadcast('new_notification' , { Disruption_Id: notification.id });
                }, this)
 ````

6. When we send the local notification two things happen, a small window pops down from the top of the iOS display showing the contents of each notification we have sent using cordova.plugins.notification.local.schedule, so if we send 3 notifications, we get three little windows that display and then hide. These pop down for a few tenths of seconds only **This is the bit that we don't quite understand, see point 8 for more information**

7. The local notification is then displayed in the notification drawer along with all other notifications. We can click on the notification in this drawer and our app starts up and displays the right information. **All Working**

8. if we quickly click on the notification that pops down from the top of the display, we get sent back to our app as we expect, BUT we do not get the click event we get if we had clicked the notification in the main Notification Drawer. We have to be quick as the little pop down only lasts a few tenths of seconds. This means we go back to the main screen in our app and we don't go to the screen we need as the click event hasn't fired. Is there another event we should be looking for JUST when that tiny pull down notification occurs or is the iOS behaviour just to open the app up? We would have thought that clicking on that pop down should be treated as the same way as other notifications. We also thought that it might be a timing issue and that the local-notifications aren't quite ready yet.

Everything else is working well, so we're puzzled by the behaviour here. Any insights on this gratefully received.

Thanks

Rob

**Comment by katzer** [comment]
@rwillett 

> Is there another event we should be looking for JUST when that tiny pull down notification occurs or is the iOS behaviour just to open the app up?

No, the `click` event is the right & only one. Don't click on the banner immediately, instead __wait at least for one second__.

This is because iOS doesn't differ between _trigger_ and _click_ event. Theres only one callback. If there is a delay of at least 1 second between trigger time and iOS callback the plugin fires the `click` callback, otherwise `trigger` callback.

Hope that helps!

**Comment by rwillett** [comment]
Sebastien,

Thanks for the quick and helpful reply.

We can't stop the users clicking on the banner though when it appears even for a small amount of time. Why can't we look for the trigger event? Is that possible?

Thanks,

Rob

**Comment by rwillett** [comment]
Just to add,

We updated our code to catch the trigger 

````
                cordova.plugins.notification.local.on("click", function (notification , state) {
                    var debug = 1;

                    if (debug)
                    {
                        ConsoleLog("Local Notifications Click: notification=" + JSON.stringify(notification));
                        ConsoleLog("Local Notifications Click: state=" + JSON.stringify(state));
                    }

                    // Need to remove notification.id from notificationQueue
                    RemoveNotificationFromQueue(notification.id);
                    $rootScope.$broadcast('new_notification' , { Disruption_Id: notification.id });
                }, this);

                cordova.plugins.notification.local.on("trigger" , function (notification , state) {
                    var debug = 1;

	            if (debug)
                    {
                        ConsoleLog("Local Notifications trigger: notification=" + JSON.stringify(notification));
                        ConsoleLog("Local Notifications trigger: state=" + JSON.stringify(state));
                    }

                    // Need to remove notification.id from notificationQueue
                    RemoveNotificationFromQueue(notification.id);
                    $rootScope.$broadcast('new_notification' , { Disruption_Id: notification.id });
                }, this);
            }
````

just to see what happened. It does appear to work OK. This is based on 10 mins of testing which is not exactly deep and meaningful.

Is there any reason why the trigger event can't be used? 

Thanks

Rob

**Comment by rwillett** [comment]
Mmmm.... things aren't working the way I thought they might. We're still investigating so catching the trigger event *might* not be a good idea.

I'll keep this thread open to report on progress.

Rob

**Comment by Pixelartdev** [comment]
Hey, just to help you to understand how iOS notifications visualisation work: 
The popdown you are talking about is called "banner notification". You as the app developer have no influence on this setting. The user has the ability to select between none (no notification on screen but in the notification center), banner (the one you are seeing), and popup (looks like an alert box). So you cannot control which ways the user selects to show the notification. You can self test this by going to the settings app on the iOS device and scrolling down until you see your app name. There you can select the notification type you want to see. Default is banner by the way.

hope this helps you to understand how the notification visualisation is working.
Regards

**Comment by rwillett** [comment]
Thanks for the explanation. 

We are still experimenting with notifications, some of our use-cases are very tricky, e.g. what happens when the app has gone into suspended mode, rather than just into the background. IOS doesn't make life easy for developers at times :)

Rob

**Comment by Pixelartdev** [comment]
For that case you will need a background plugin (like background fetcher).
But I am actually facing some problems with it on iOS 9.2

**Comment by rwillett** [comment]
@derDeno 

Yes we know. We've implemented Background fetch (https://github.com/christocracy/cordova-plugin-background-fetch) and are exploring what it can (and can't do).

One thing we have found with background fetch is that we cannot get Angular $HTTP Posts and Gets to work from inside the background fetch. We can get raw open's to work but nothing more high level. 

```
           xmlhttp.open("GET" , url , true);

            xmlhttp.onreadystatechange = function() {
		// State 0 is "request not initialized"
                // State 1 is "server connection established"
                // State 2 is "request received"
                // State 3 is "processing request"
                // State 4 is "request finished and response is ready"
```

The background fetch docs talk about jQuery which we are reluctant to use (but may have to). This a pain as we have to rework our existing code if we want to do a background fetch from a server. The upside is that once you have done the background fetch, it *appears* that the app more back to the background from suspended mode for a few minutes more. We still need to confirm this and it may change under different versions of IOS as well.

I'd be interested in what you have done with background fetch to see if you have the same issues.

Rob

**Comment by derDeno** [comment]
My target is to check a JSON api and to see if there is any update available. But I am far away from this, because I am trying to do just some simple notification when background fetch is active to see if it is working. But unfortunately this is not working because I am getting the mysterious error when launching (https://github.com/christocracy/cordova-plugin-background-fetch/issues/10). I will add my code later because I am actually not at my mac :smile: 

Is the background fetcher working for you without getting this error in the console?

**Comment by rwillett** [comment]
Mmmm....We do occasionally get that error, since things seemed to be working, I had ignored it (I know, I know).

I can certainly state that background fetch *appears* to allow us to do a 'low level' call to a server and return data. We've configured a trivial JSON reflector on a server so we can check that we get something back. At the moment we don't care about the contents of the call, just that it works. 

This is still early days for us in getting background fetch working. We have a convoluted test case for 
1. sending notifications AND 
2. clearing them out of the iOS/Android notification drawer when new ones come in AND 
3. when the user is in suspended mode (not just background) BUT the app is started up AND
4. the app suspension is in the last 15 mins or so. 

We'll check more over the weekend and see if we can report back if background-fetch is really working all the time or not. We are using iOS 8.4 for testing so wonder if this is an iOS version issue. We don't use the Xcode simulate fetch at all. I've read through the thread you quote and can see its been out for a long time. I know Chris through his geolocation plugin and have a lot of respect for his code, however I suspect he has abandoned the background fetch plugin. I also worry that Apple will change things yet again in iOS 9.X and really make life difficult.

Rob

**Comment by derDeno** [comment]
Interesting. I have some strange test today. First everything worked perfectly in in the sim. I saw the notifications, the console didn't output anything. Then I decided to move to my real iPhone and BAAM: It stopped working. I was like what the hack is happening (by the way I have a iPhone 5s and iOS 9.2 and used the same for the sim)?! Then I moved back to the sim and for no reason the error happened there too? First it worked and after my device failed the sim also fails. So I don't know if it is code specific or just a random thing breaking it.

I also tried to understand Chris's plugin and the background fetch, because I wanted to know what really is the problem there. After plenty of hours yesterday night and today I still didn't find the bug (if there is one..) in the code. Maybe it is because I am new to Apple stuff because I am a Java / PHP developer :smile: 

If I would be able to locate the problem and if it is code based, I would try to fix it, as the fixes provided in the repo didn't really helped. Are you better in Objective C than me? Because then there would be a way to fix it maybe or rewrite the plugin.

I also wonder that there is no other real background fetcher plugin for cordova out there, as it is a major feature for many tasks.

**Comment by rwillett** [comment]
I suggest we move this discussion over to the background-fetch github area. We are way off topic :)

Rob

**Comment by derDeno** [comment]
Yes your right

**Comment by rwillett** [comment]
Created a new issue at https://github.com/christocracy/cordova-plugin-background-fetch/issues/25 for this discussion.
