### ISSUE TITLE
Not working at all!

### ISSUE THREAD

**Issue by pdcmoreira** [katzer/cordova-plugin-local-notifications#773]
I've been trying to make this work for the past 2 days. I think I've tried everything by now.

So, I'm using PhoneGap CLI and I'm testing with the PhoneGap Dev App on Android and with the command `phonegap serve`.

I've installed the plugin with `phonegap plugin add https://github.com/katzer/cordova-plugin-local-notifications`.

After two days, this is really frustrating, because all tutorials show me the same, which is what I have. Am I missing something?

index.html:
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <meta name="msapplication-tap-highlight" content="no" />
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi" />
    <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; media-src *">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>test</title>
</head>

<body>
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript" src="js/app.js"></script>
</body>

</html>
```

app.js:
```javascript
var app = {
    initialize: function() {
        this.bindEvents();
    },
    
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    
    onDeviceReady: function() {
        cordova.plugins.notification.local.schedule({
            id: 1,
            title: "Production Jour fixe",
            text: 'Second Row Text'
        });
    }
};

app.initialize();
```

**Comment by John-Henrique** [comment]
Plugins not working in navigator, you need use a mobile device conected by 'USB Debug', so you need install in device "PhoneGap" (look for in app store)

**Comment by pdcmoreira** [comment]
I'm not testing in the browser, I'm using the PhoneGap Developer app, downloaded from the Play Store.

**Comment by katzer** [comment]
@pdcmoreira I haven't used the _PhoneGap Developer app_, but from your code snippet I can see that the `cordova_plugins.js` is missing!

**Comment by pdcmoreira** [comment]
What `cordova_plugins.js`? I haven't read about such a thing in any docs.

**Comment by katzer** [comment]
@pdcmoreira 
> What `cordova_plugins.js`?

Its an auto generated file and without no plugin will be loaded. See [here](https://github.com/katzer/cordova-plugin-local-notifications/blob/example/platforms/android/assets/www/cordova_plugins.js) as an example.

**Comment by pdcmoreira** [comment]
I don't think that applies to PhoneGap Build.
