### ISSUE TITLE
unable to serialize userInfo / iOS crashes when 2nd notification is set

### ISSUE THREAD

**Issue by mr-sparks** [katzer/cordova-plugin-local-notifications#775]
Hey there,

I'm using the latest plugin. So far i can set a notification with no problem. When i set another one,
right after i already set one (second one for another date of course) the app crashes. 

**Xcode error on USB-iPhone Mode:**

reason: 'unable to serialize userInfo: Error Domain=NSCocoaErrorDomain Code=3851 "Property list invalid for format: 200 (property lists cannot contain objects of type 'CFNull')" UserInfo={NSDebugDescription=Property list invalid for format: 200 (property lists cannot contain objects of type 'CFNull')}'

**Xcode error on iPhone Simulator Mode:**

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'unable to serialize userInfo: Error Domain=NSCocoaErrorDomain Code=3851 "Property list invalid for format: 200 (property lists cannot contain objects of type 'CFNull')" UserInfo={NSDebugDescription=Property list invalid for format: 200 (property lists cannot contain objects of type 'CFNull')}'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f1b9f45 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000011183bdeb objc_exception_throw + 48
	2   UIKit                               0x000000010fbee9bf -[UIConcreteLocalNotification userInfo] + 0
	3   parkandpay                          0x000000010ef8d11f -[UILocalNotification(APPLocalNotification) initWithOptions:] + 111
	4   parkandpay                          0x000000010ef85806 __33-[APPLocalNotification schedule:]_block_invoke + 374
	5   libdispatch.dylib                   0x0000000112103e5d _dispatch_call_block_and_release + 12
	6   libdispatch.dylib                   0x000000011212449b _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000011210cbef _dispatch_root_queue_drain + 1829
	8   libdispatch.dylib                   0x000000011210c4c5 _dispatch_worker_thread3 + 111
	9   libsystem_pthread.dylib             0x00000001124554f2 _pthread_wqthread + 1129
	10  libsystem_pthread.dylib             0x0000000112453375 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

I thought maybe that means that some kind of variable needed for setting the notification is empty, but all of them are filled correctly.

**I'm using this code:**

function setAblaufReminder(aToken) {

	var sound = device.platform == 'Android' ? 'file://sound.mp3' : 'file://beep.caf';

	cordova.plugins.notification.local.schedule({
		id: timerID,
		text: "Notification",
		at: date,
		sound: sound
	});

	console.log("Reminder set for: "+date);
}

Any ideas on that ? T

Thank you

**Comment by mr-sparks** [comment]
there was in fact a variable empty which was needed for setting the notification. But that was a problem in my code, not in the plugin.

**Comment by mikepsinn** [comment]
@mr-sparks What variable was empty?

**Comment by aborovsky** [comment]
+1 same trouble for me
