### ISSUE TITLE
Do monthly notifications take into account the varying number of days per month?

### ISSUE THREAD

**Issue by jackroscoe** [katzer/cordova-plugin-local-notifications#776]
If I were to schedule a notification using the following code:

    cordova.plugins.notification.local.schedule({
        text: "Test Notification",
        at: _5_sec_from_now,
        every: "month"
    }, callback);

Would the notification repeat every 31 days, or would it consider the varying number of days per month and trigger the notification for example on the same date every month?

As an example, if I scheduled a notification to start on January 31st and repeat monthly, would the next notification trigger on February 29th or March 2nd?

**Comment by katzer** [comment]
@jackroscoe Only iOS!

**Comment by jackroscoe** [comment]
@katzer Thanks for the fast response! Do you mean iOS is the only one that takes into account the length of the month?

**Comment by katzer** [comment]
@jackroscoe Yes, the only one that takes into account the length of the month, quarter and year!

**Comment by jackroscoe** [comment]
@katzer ok, thank you!
