### ISSUE TITLE
getAll function always returns 17 Jan 1970 date.

### ISSUE THREAD

**Issue by brunyan** [katzer/cordova-plugin-local-notifications#777]
We make a schedule with this function
schedule({
   id: task.id,
   title: task.title,
   text: task.msg,
   every: 'daily',
   at: task.time})

where a task.time is date object.

But when we call the function getAll the 'at' in object retuns always the same date and time, 17 Jan 1970!

Why?

**Comment by katzer** [comment]
You need to convert from seconds to milliseconds first.
```js
new Date(notification.at * 1000)
```

Probably with v0.9 `notification.at` will already be converted to `Date`.
