### ISSUE TITLE
No click event on iOS 9.1/9.2

### ISSUE THREAD

**Issue by nwidal** [katzer/cordova-plugin-local-notifications#782]
Hey,
when Notification is due and triggered, clicking on that Notification gives no callback to the cordova.plugins.notification.local.on("click", function (notification) {
...
}
funny though if installed the plugin cordova-plugin-geofence the didReceiveLocalNotification function written in swift is executed for these notifications aswell.
At first I thought it was related that the geofence plugin is responsible for this odd behaviour, but after removing geofence plugin the on-click method still won't get called.

Anyone else with this issue? XCode 7.1, iOS 9.1 / XCode 7.2, iOS 9.2 Sim and Device

**Comment by katzer** [comment]
@nwidal The `click` event works! Wait at least for a second before you click on the notification.
