### ISSUE TITLE
Notification not appearing when I swipe away the app from the recent list

### ISSUE THREAD

**Issue by nursyafiah** [katzer/cordova-plugin-local-notifications#786]
hi @katzer , i installed your cordova-plugin-local-notification to my mobile app. i will only receive notification when i run the app and then lock my phone. i can also receive notification when the app is part of the recent list and then i lock my phone again. however, when i swipe away the app from the recent list, i am unable to receive notification.

do you have an idea as to why this is happening?
thank you so much for taking your time reading and replying to my email. really appreciate it a lot.

**Comment by katzer** [comment]
@nursyafiah I cannot reproduce. I set a date in future and swipe the app away from list. The notification appears.

**Comment by dansanti** [comment]
this is cased by taskKiller, my question is related to this too, becouse when you do swipe, task killer clear all data and notifications https://github.com/katzer/cordova-plugin-local-notifications/issues/785

**Comment by nursyafiah** [comment]
@katzer hi katzer, is it possible for the notification to notify the user on every beacon detection, even when the app is swipe away from the recent list (not force close)?

**Comment by katzer** [comment]
@nursyafiah You can add that here #451

**Comment by dansanti** [comment]
I found a solution  add to activity on AndroidManifest: 

 android:excludeFromRecents="true" 

, and user cant never swipe app from last App..
