### ISSUE TITLE
change the app icon

### ISSUE THREAD

**Issue by nursyafiah** [katzer/cordova-plugin-local-notifications#789]
hi,

when i receive the notification, the image will be the robot, which i think is default.
how do i change the icon?

thanks.

**Comment by katzer** [comment]
You can make use of `icon` and `smallIcon`. Also see the [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling)

**Comment by nursyafiah** [comment]
@katzer Hi, would like to ask you at which java file can I change the icon? This is because I explored the various files and could not locate as to where I can change the information.
