### ISSUE TITLE
Option to hide the smallIcon in drawer

### ISSUE THREAD

**Issue by patcon** [katzer/cordova-plugin-local-notifications#790]
Seems `smallIcon` is always set with android:
https://github.com/katzer/cordova-plugin-local-notifications/blob/da0a1f12f0d3d821f69f4b0adede43c842ec23c3/src/android/notification/Builder.java#L136-L141

Since I have essentially the same icon for both, it seems odd to have the smallIcon in the corner of the large icon when the drawer is pulled down. Any chance you'd be willing to accept a PR for adding an option to hide the smallIcon in this situation (ie. only use it in the top taskbar)

Thanks!

**Comment by katzer** [comment]
@patcon See 4f9f3d0697cdb517c5bb854324a975d5520ac5b2 That will come with the next minor update.

**Comment by patcon** [comment]
Thanks @katzer. Sorry for the noise :)
