### ISSUE TITLE
Allow notification to avoid launching app

### ISSUE THREAD

**Issue by patcon** [katzer/cordova-plugin-local-notifications#791]
Sometimes you just want a notification to run something in the background (download something, etc) without bringing the app to the front.

Any thoughts on adding a `launchApp` key for android that defaults to true, but can also be false in order to skip this line?
https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/android/notification/ClickActivity.java#L42

**Comment by katzer** [comment]
Thats possible with 0.9-beta through the `launch` property. Thanks!
