### ISSUE TITLE
Why the alarm fires before the time set?

### ISSUE THREAD

**Issue by rcurvello** [katzer/cordova-plugin-local-notifications#794]
Why the alarm fires before the time set?
I tried run in Android Kitkat and Android 6.

**Comment by katzer** [comment]
@rcurvello Could you post a sample please. Maybe you have assigned a date that is in the past.

**Comment by aminecmi** [comment]
@katzer is it possible to not schedule, or trigger the past notifications ?

**Comment by rwillett** [comment]
Closed as no update from original poster.
