### ISSUE TITLE
The plugin can't be built with PhoneGap Build (cli-5.2.0)

### ISSUE THREAD

**Issue by andersborgabiro** [katzer/cordova-plugin-local-notifications#795]
This applies to both iOS and Android.

Proof (plugin.xml):
cordova-plugin-local-notifications: `<dependency id="org.apache.cordova.device" />`
cordova-plugin-local-notifications-mm (that works): `<dependency id="cordova-plugin-device" />`
Among other differences. The files under www are identical, but there are also differences in the native code and package.json.

Causing:

Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-local-notifications" via npm Installing "de.appplant.cordova.plugin.local-notification" for android WARNING: org.apache.cordova.device has been renamed to cordova-plugin-device. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.device` and `cordova plugin add cordova-plugin-device`. Changing plugin to "cordova-plugin-device" Fetching plugin "cordova-plugin-device" via npm Failed to install 'de.appplant.cordova.plugin.local-notification':Error: Expected plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device". at checkID (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/fetch.js:177:15) at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/fetch.js:161:9 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13) at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:557:44 at flush (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17) at doNTCallback0 (node.js:417:9) at process._tickCallback (node.js:346:13) Expected plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".

From README.md for -mm: "Temporary Fork of Cordova Local-Notification Plugin to hot-fix PGB build problem for Moodle Mobile application."

Please make it a permanent fix in cordova-plugin-local-notifications.

Regards,
Anders

**Comment by katzer** [comment]
Duplicated with #758
