### ISSUE TITLE
sound: "file://sounds/reminder.mp3" not playing on android one device running Android M 6.0

### ISSUE THREAD

**Issue by appplumbr** [katzer/cordova-plugin-local-notifications#797]
May I please request you to help me understand what am I missing here this custom sound plays fine on MI Note 4G (Running kitkat 4.4.4) and fails to play on Android One device running 6.0. On Android M 6.0 its plays default sound and not custom.

sound: "file://sounds/reminder.mp3"

any help is appreciated!

**Comment by katzer** [comment]
@appplumbr I've tested with Android 6 using simulator and it works. Make sure that the system settings for notifications in general and/or for that app forbid playing sound.
