### ISSUE TITLE
Is it possible to get the date that a clicked notification was triggered

### ISSUE THREAD

**Issue by MrAntix** [katzer/cordova-plugin-local-notifications#800]
I need to identify a clicked notification by the date it was triggered

the notification is a repeater and may have triggered any number of times to the user. 
I would like to know which one the user clicked.

Is this possible?

**Comment by katzer** [comment]
@MrAntix By ID! You can also put some uniq information into the `data` property.

**Comment by MrAntix** [comment]
On a repeated notification the data is the same for all in the repeat
