### ISSUE TITLE
Missing title and buggy smallIcon when in background

### ISSUE THREAD

**Issue by StephJan** [katzer/cordova-plugin-local-notifications#802]
Using local notifications on a Lollipop device in conjunction with cordova-plugin-background-mode, I noticed that when displaying a notification when in background : 
- smallIcon is a white square (seems like the black/white version of the normal icon, even though I specifiy them both to different resources)
- title is empty.

When app is on screen, everything is fine ...

EDIT : removing cordova-plugin-background-mode gets the same result

**Comment by appplumbr** [comment]
@StephJan This worked for me:

a) Remove "target sdk" from platforms/android/AndroidManifest.xml
b) in cordova.plugins.notification.local.schedule() ref the smallicon like this { smallIcon: 'ic_stat_social' } only the file name and not the extension.
c) Generate smallicon from  https://romannurik.github.io/AndroidAssetStudio/icons-notification.html

Note: white box for small icon are displayed only in android lollipop 5.0 and above

**Comment by StephJan** [comment]
@appplumbr : is this fix specifically for small icon issue when in background ? Because otherwise, functionality is ok (plus there is still the issue of the missing title)

**Comment by appplumbr** [comment]
@StephJan Yes, only for is this fix specifically for small icon issue when in background.

**Comment by StephJan** [comment]
Thanks, I'll give it a try. Any clue for the missing title ?

**Comment by appplumbr** [comment]
@StephJan I can get it working for both Title + Small Icon for my app on Android 5/6 please review my app screenshots on play store https://play.google.com/store/apps/details?id=expirybell.appplumbr.com

May be you can try insatll my app and test it.

Also, please confirm if you are using below format, to schedule:
{
    id: 1,
    title: "Production Jour fixe",
    text: "Duration 1h",
    ..................
}

**Comment by StephJan** [comment]
Here is the snippet of the code I use to create local notifications. "push" is actually phonegap-plugin-push 1.5.2, so I basically generate an immediate local notification each time I receive a push notification : 

      push.on('notification', function (data) {
        $cordovaLocalNotification.schedule({
          id: 1,
          title: data.additionalData.originator_name,
          text: data.message,
          icon:"file://img/icon.png",
          smallIcon:"res://logo48.png"
        }).then(function (result) {
         // console.log('Notification triggered');
        });
      });

This code is triggered by a hard-coded notification sent from my server on demand.

I've installed your app and set a bell for later on, so I have time to play with my device and make sure your app goes background, I'll keep you posted.

**Comment by nursyafiah** [comment]
@StephJan @katzer hi there, when I use your local notification, i realized that the notification will look something like this: 
![image](https://cloud.githubusercontent.com/assets/15919618/12108010/292b2e80-b3ad-11e5-85d9-53e8a85f081e.png)

I need to change it & ensure there is a text below the main title, like this: 
![image](https://cloud.githubusercontent.com/assets/15919618/12108017/3fe0ce46-b3ad-11e5-825f-30293fb443df.png)

Can you help me on how i can change it and which java files i need to edit from based on the question i mentioned earlier?

For you info: The notification will appear when the mobile app detects a beacon.

**Comment by StephJan** [comment]
@appplumbr : I confirm that your app is working fine, I have no clue what is wrong with mine.

@nursyafiah : see examples above for proper configuration

**Comment by nursyafiah** [comment]
@StephJan may i know which java files i'll need to edit from so that it appears like the 2nd pic which i posted?

**Comment by appplumbr** [comment]
@StephJan - when we fetch out the notification response from stored notifications as JSON.

push.on('notification', function (data) {
    $cordovaLocalNotification.schedule({
      id: 1,
      title: data.additionalData.originator_name,
      text: data.text, //i changed this line
      icon:"file://img/icon.png",
      smallIcon:"res://logo48.png"
    }).then(function (result) {
     // console.log('Notification triggered');
    });
  });

Important: you need to use text: data.text  and NOT text: data.message, update this and it should work.

**Comment by StephJan** [comment]
@appplumbr : actually the text works ok, only title is defective :)

 ... could it be that I should use data.data.* instead of data.additionalData.* ? Just in case I'll notify the full JSON to see what's going on.

**Comment by appplumbr** [comment]
@StephJan - Please share some code if possible to help

**Comment by StephJan** [comment]
The mobile part is pretty much what I posted above, and the server part is heavily based on https://www.npmjs.com/package/node-pushserver

The funny part is that, upon receiving a notification from Google Cloud Messaging :
- when app is in background, I get the problems described before
- when clicking on notification to bring the app to foreground, I get the local notification a second time, this time well-formed ???

Notifications are so straightforward I can't see what I did wrong :(

**Comment by StephJan** [comment]
@appplumbr : something very strange is going on : to investigate this issue, in the piece of code where I receive the push notification and generate the local notification, I replaced the text of the local notification with <JSON of the received push>.

When the app is in background, the former text is displayed : this means that something is intercepting the push notif, and turns it into a local notif itself ! Only when putting app back to foreground do I get a notif containing JSON as expected.

Could it be an interference with phonegap-plugin-push ? I'll raise the issue on the other side.

**Comment by joneldiablo** [comment]
the first solution proposed, works for me. But there is not possible add the icons using the config.xml? something like this:

	<platform name="android" >
		<ic_stat_social density="" src="res/ic_stat_social.png" />
		...
		<ic_stat_social density="xxxhdpi" src="res/ic_stat_social-xxxhdpi.png" />

		<icon density="" src="res/Icon-a.png" />
		...
		<icon density="xxxhdpi" src="res/Icon-xxxhdpi.png" />

		<splash density="land-ldpi" src="res/splash-landscape-ldpi.png" />
		...
		<splash density="port-xxxhdpi" src="res/splash-portrait-xxxhdpi.png" />

	</platform>

**Comment by rwillett** [comment]
Is this still an issue or can it be closed? No update in a year!
