### ISSUE TITLE
plugin file missing

### ISSUE THREAD

**Issue by bakhtout** [katzer/cordova-plugin-local-notifications#803]
Hi,

I got this error message when trying to run the example app  on ios
Error: ENOENT: no such file or directory, stat '/Users/amine/dev/mobile/notif-sample/plugins/de.appplant.cordova.plugin.local-notification'

when trying to ls the file I found it is a symlink toward another file
lrwxr-xr-x   1 amine  staff    68 Dec 30 13:51 de.appplant.cordova.plugin.local-notification -> /Users/sebastian/Documents/github/cordova-plugin-local-notifications

That's weird can you solve that.

Regards.
Amine.

**Comment by katzer** [comment]
@bakhtout As best you remove the platform and add it again.
