### ISSUE TITLE
Can't clear notification when clicked on with app in backround? Android

### ISSUE THREAD

**Issue by dvulanov** [katzer/cordova-plugin-local-notifications#806]
If I click on a notification when outside of my app, it brings me into the app with the 'click' event.  That's all fine.  But the notification doesn't clear off the tray?  Manually trying to clear it (using clear(), in code) doesn't work either, if I list all notification id's it's not there.  I can only clear it by swiping it, but it still doesn't seem to clear properly.

For me it happens every time, but only when the app is in the background.  If you click on the notification when the app is in the foreground or when the app is not running, everything works fine.

I believe I'm using the latest build

**Comment by appplumbr** [comment]
@dvulanov You may define it inside device ready() or app config if using Ionic or angularjs. 

cordova.plugins.notification.local.on("clear", function(notification) { }); Event Listener will listen to every clear call(); if you have tried all of this; please elaborate your issue with your code.

**Comment by rwillett** [comment]
We have this working fine on Android.

Is this still an issue or can we close this?

**Comment by rwillett** [comment]
No update so closing.
