### ISSUE TITLE
Is It working even the app is closed?

### ISSUE THREAD

**Issue by zuna003** [katzer/cordova-plugin-local-notifications#807]
Hi Good Day,
  I hope someone can give me an idea if this will work even the app is closed.
  For Example I'll set a notification everday at specific time,.

Thank you

**Comment by ihadeed** [comment]
Yes it does work, you basically tell the phone when to display the notification and it will display it even if you close the app.

**Comment by zuna003** [comment]
Thank you for your response.

**Comment by FrancescoMussi** [comment]
Yes is working. You can make a quick test.
Set a notification after one minute and call it through ng-click:

$scope.notification_test = function()
{
	var alarmTime = new Date();
	alarmTime.setMinutes(alarmTime.getMinutes() + 1);

	cordova.plugins.notification.local.schedule(
	{
		id: 1,
		title: 'test 1',
		text: 'This is a test notification message!',
		at: alarmTime
	});
}

Click the button and close the app.
The notification will properly come.

**Comment by zuna003** [comment]
Thank you for that example.I really appreciate it.

**Comment by adi928** [comment]
Alright, the notification is shown even when the app is closed, but when the user clicks on the notification, and the app is already closed (i.e. not in the background), the system just opens the app as new and whatever action we defined for onClick function, will not be executed. Any work around for this?

**Comment by FrancescoMussi** [comment]
check out the localStorage. You can save data there and will be maintained.

**Comment by adi928** [comment]
So, you are suggesting to check for some preference in the localStorage whenever the app is opened?

**Comment by rwillett** [comment]
There are two issues here.

 @adi928 if this is still an issue, raise a new issue with the template in #1188.
