### ISSUE TITLE
With multiple notifications it display only one (bell) icon

### ISSUE THREAD

**Issue by FrancescoMussi** [katzer/cordova-plugin-local-notifications#810]
I really appreciate this plugin! 
I just noticed this thing:

When sending multiple notifications i can see only one bell icon (for the last one).
Here is a screenshot from Genymotion (in android phone have same behavior):

![screen shot 2016-01-05 at 13 24 26](https://cloud.githubusercontent.com/assets/5312907/12114287/4ef1439e-b3b1-11e5-9386-951ba0866848.png)

This is the simple code i am using:

$scope.notification_test = function()
{
            var alarmTime = new Date();
            alarmTime.setMinutes(alarmTime.getMinutes() + 1);
            cordova.plugins.notification.local.schedule(
            {
                id: 1,
                title: 'test 1',
                text: 'This is a test notification message!',
                at: alarmTime,
                icon: "file://img/icon_app.png",
                sound: "file://app_notification.wav",
            });
}

Do you know why this happens?

**Comment by rwillett** [comment]
Is this still an issue or can it be closed? No update in a year!
