### ISSUE TITLE
When use the .on "clearall" event ?

### ISSUE THREAD

**Issue by FrancescoMussi** [katzer/cordova-plugin-local-notifications#811]
Hello guys.
I am testing the notifications in my Ionic app.

In my case I need to know when the user click or clear a notification, in order to not send the same notification twice.
I am using .on "click" and .on "clear" and they are working perfectly.

I am also trying .on "clearall" in the event the user 'clear' all the notification.
But when i do clear all the notifications, in Genymotion or in an android phone, what is triggered is not the "clearall" event but the "clear" event for each notification displayed.

This is the code:

cordova.plugins.notification.local.on("click", function (notification) 
{
        console.log('notification clicked');
        console.log(notification);
});

cordova.plugins.notification.local.on("clear", function (notification) 
{
        console.log('notification cleared');
        console.log(notification);
});

cordova.plugins.notification.local.on("clearall", function (state) 
{
        console.log('notifications all cleared');
        console.log(state);
});

I wanted to ask if that is the proper behavior?
In which case i am supposed to use the "clearall" event?

Thank you very much!

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by FrancescoMussi** [comment]
I don't know honestly. I had it one year ago.
