### ISSUE TITLE
IOS build failed

### ISSUE THREAD

**Issue by myfooddb** [katzer/cordova-plugin-local-notifications#812]
I use the Intell XDK Framework and the local Notifikation Plugin 0.8.4. When i compile the iOS app, than i see following message. The android compile works fine. The problem is the cordova-plugin-app-event.

CompileC build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/AppDelegate+APPAppEvent.o MyFoodDB/Plugins/cordova-plugin-app-event/AppDelegate+APPAppEvent.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd .../mobile2/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Developer/android-sdk-macosx/tools:/usr/local/ant/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=8.0 -iquote .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-generated-files.hmap -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-own-target-headers.hmap -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-all-target-headers.hmap -iquote .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-project-headers.hmap -I.../mobile2/platforms/ios/build/device/include -I.../mobile2/platforms/ios/build/device/usr/local/lib/include -I.../mobile2/platforms/ios/build/UninstalledProducts/include -I.../mobile2/platforms/ios/build/device -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/DerivedSources/armv7 -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/DerivedSources -F.../mobile2/platforms/ios/build/device -include .../mobile2/platforms/ios/build/sharedpch/MyFoodDB-Prefix-adnximjampipriatljpcmowmenem/MyFoodDB-Prefix.pch -MMD -MT dependencies -MF .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/AppDelegate+APPAppEvent.d --serialize-diagnostics .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/AppDelegate+APPAppEvent.dia -c .../mobile2/platforms/ios/MyFoodDB/Plugins/cordova-plugin-app-event/AppDelegate+APPAppEvent.m -o .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/AppDelegate+APPAppEvent.o
.../mobile2/platforms/ios/MyFoodDB/Plugins/cordova-plugin-app-event/AppDelegate+APPAppEvent.m:109:56: error: expected a type
- (void) postNotificationName:(NSString*)aName object:(nullable id)anObject
                                                     ^
  1 error generated.

CompileC build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/CDVDevice.o MyFoodDB/Plugins/cordova-plugin-device/CDVDevice.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd .../mobile2/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Developer/android-sdk-macosx/tools:/usr/local/ant/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=8.0 -iquote .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-generated-files.hmap -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-own-target-headers.hmap -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-all-target-headers.hmap -iquote .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-project-headers.hmap -I.../mobile2/platforms/ios/build/device/include -I.../mobile2/platforms/ios/build/device/usr/local/lib/include -I.../mobile2/platforms/ios/build/UninstalledProducts/include -I.../mobile2/platforms/ios/build/device -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/DerivedSources/armv7 -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/DerivedSources -F.../mobile2/platforms/ios/build/device -include .../mobile2/platforms/ios/build/sharedpch/MyFoodDB-Prefix-adnximjampipriatljpcmowmenem/MyFoodDB-Prefix.pch -MMD -MT dependencies -MF .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/CDVDevice.d --serialize-diagnostics .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/CDVDevice.dia -c .../mobile2/platforms/ios/MyFoodDB/Plugins/cordova-plugin-device/CDVDevice.m -o .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/CDVDevice.o

CompileC build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/CDVPlugin+APPAppEvent.o MyFoodDB/Plugins/cordova-plugin-app-event/CDVPlugin+APPAppEvent.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd .../mobile2/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Developer/android-sdk-macosx/tools:/usr/local/ant/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=8.0 -iquote .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-generated-files.hmap -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-own-target-headers.hmap -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-all-target-headers.hmap -iquote .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/MyFoodDB-project-headers.hmap -I.../mobile2/platforms/ios/build/device/include -I.../mobile2/platforms/ios/build/device/usr/local/lib/include -I.../mobile2/platforms/ios/build/UninstalledProducts/include -I.../mobile2/platforms/ios/build/device -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/DerivedSources/armv7 -I.../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/DerivedSources -F.../mobile2/platforms/ios/build/device -include .../mobile2/platforms/ios/build/sharedpch/MyFoodDB-Prefix-adnximjampipriatljpcmowmenem/MyFoodDB-Prefix.pch -MMD -MT dependencies -MF .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/CDVPlugin+APPAppEvent.d --serialize-diagnostics .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/CDVPlugin+APPAppEvent.dia -c .../mobile2/platforms/ios/MyFoodDB/Plugins/cordova-plugin-app-event/CDVPlugin+APPAppEvent.m -o .../mobile2/platforms/ios/build/MyFoodDB.build/Release-iphoneos/MyFoodDB.build/Objects-normal/armv7/CDVPlugin+APPAppEvent.o
.../mobile2/platforms/ios/MyFoodDB/Plugins/cordova-plugin-app-event/CDVPlugin+APPAppEvent.m:93:23: error: expected a type
                name:(nullable NSString*)event
                      ^
.../mobile2/platforms/ios/MyFoodDB/Plugins/cordova-plugin-app-event/CDVPlugin+APPAppEvent.m:94:23: error: expected a type
              object:(nullable id)object
                      ^
2 errors generated.

**Comment by uzumakinaruto123** [comment]
@myfooddb  same issue !  any solution yet ?

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no update
