### ISSUE TITLE
Repeat Scheduling not working

### ISSUE THREAD

**Issue by joelseneque** [katzer/cordova-plugin-local-notifications#813]
I've tried setting up a repeated schedule in my app with:

```
getTime();
var date = new Date();
date.setHours(reminderHour);
date.setMinutes(reminderMin);
date.setSeconds(00);

cordova.plugins.notification.local.schedule({
    id: 1,
    title: 'Daily',
    text: 'Get your daily reminder',
    sound: null,
    every: 'day',
    firstAt: date,
    badge: 1
});
```

But this won't work for me.
Using the Cordova iOS 3.9.2 on iOS9.2 with the latest version of the plugin

I am getting a "WARN: Unknown property: firstAt" when scheduling also
I'm guessing this is part of the problem

**Comment by jim0020** [comment]
Try changing the key 'firstAt' to just 'at'.  I've had similar problems using 'firstAt'.

**Comment by nursyafiah** [comment]
hi @jim0020 @joelseneque = which files did you edit your codes from?

**Comment by joelseneque** [comment]
I've got it working now.
Thanks @jim0020 - changing it to 'at' works.

But also where the reminder wasn't working was when I would schedule the first 'at' in the past. I changed my code so that when people want to choose a time that has already happened in the day it would schedule the first time for the next day.
