### ISSUE TITLE
Get List of Registered Alarms

### ISSUE THREAD

**Issue by Overseas634** [katzer/cordova-plugin-local-notifications#814]
We have added list of reminder through your plug-in on device ready event 
so when i open an app  each time it registers new reminder.  I want to register reminder once only.
so please guide me how can i check reminder is already set or not

**Comment by rwillett** [comment]
You need to query all the notifications and work it for yourself, 

https://github.com/katzer/cordova-plugin-local-notifications/wiki/08.-Querying

**Comment by rwillett** [comment]
No update so closing
