### ISSUE TITLE
Not working with latest version 5.2 cordova

### ISSUE THREAD

**Issue by anthemi** [katzer/cordova-plugin-local-notifications#817]
I need this urgently, how can I get it work? Anyone has any ideas much appreciated

**Comment by nursyafiah** [comment]
my cordova version is 3.6.3 and the notification is able to work :) maybe you can try to downgrade your cordova version

**Comment by anthemi** [comment]
I want to avoid that because I have a number of plugins going for me, and everything is working except for this one.

**Comment by anthemi** [comment]
Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: LocalNotification.java - You can fix this here

When I try to add to build.phonegap.com I get the above error

**Comment by anthemi** [comment]
APP ID   1852886 

https://build.phonegap.com/apps/1852886/share

Please check and revert

**Comment by AmitAnthem** [comment]
We have changed our phonegap version to 3.7.0 As directed by you , but now "push notification" is not working .
When changing phonegap vesrion again to Cli-5.2.0 then my push notification work but my local notification didn't work it . Because local notification don't supports 
4.1.1(android) , 3.9.1(IOS)


I need to do both of them (i.e. local notifications and push notifications) in one app . Please suggest me way through which i can do so.

**Comment by spottuit** [comment]
Maybe you should look for an alternative for your push notification plugin. What about [pushwoosh](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin)?

**Comment by Zapmobilegames** [comment]
Using Cordova CLI version 5.1.1 the plugin is no more usable. In my Intel XDK interface, the debug module gives an error. Could you please check and fix, as suggested elsewhere? 

"You'll have to ask the authors to update them. Tell them to read: http://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html (the 1st link in that post points to an API change doc that gives them instructions on how to update)"

**Comment by rwillett** [comment]
We have the plugin working with the latest cordova, this is over a year old, can this be closed?

**Comment by rwillett** [comment]
No update so closing.
