### ISSUE TITLE
Notification every 2 second every day

### ISSUE THREAD

**Issue by ghost** [katzer/cordova-plugin-local-notifications#818]
Hi, I want the notification to appear every 3 second, everyday. what kind of properties do I need to make the notification works?

Below is the references i got online:

cordova.plugins.notification.local.schedule({
                id: 1,
                title: Welcome to mall
});

**Comment by spottuit** [comment]
You might want to take a look at [the samples of the plugins wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki/11.-Samples). 
[Here](https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling) is also more info about the **.schedule({});**

My guess is this should do the trick:

```
cordova.plugins.notification.local.schedule({
    id: 1,
    text: 'Welcome to mall',    
    every: 0.05,   //minutes    
})
```

**Comment by phuongtailtranminh** [comment]
Seem like 0.05 just notify me 1 times

**Comment by spottuit** [comment]
Replace **0.05** with **'second'** and it will work.

**Comment by rwillett** [comment]
Is this stlll an issue or can it be closed?

**Comment by rwillett** [comment]
No update so closing.
