### ISSUE TITLE
Cannot find plugin.xml for plugin 'cordova-plugin-app-event' & Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by spottuit** [katzer/cordova-plugin-local-notifications#820]
I can't use the plugin cordova-plugin-local-notifications. I get errors when trying to install the plugin or when I open my app. I searched through this repository's issues and found two issues which had an error close to my error in it. #729 and #761.

The suggested solutions given in #729:
1. register the plugin properly
2. compile Local Notifications correctly, there is a problem if you don't add com.android.support:support-v4
3. try removing and adding again localnotification

The suggested solutions given in #761:
none

I don't know if I missed any suggested solutions, but I have tried suggestion 3 of #729 in different ways. I used [the installation page of this plugins wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki/03.-Installation) and tried all the given options to install the plugin. After trying each option I removed all created files by the command.

**Option 1:**
Command:
```
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
```

Output:
```
Fetching plugin "https://github.com/katzer/cordova-plugin-local-notifications" via git clone
Repository "https://github.com/katzer/cordova-plugin-local-notifications" checked out to git ref "master".
Installing "de.appplant.cordova.plugin.local-notification" for android
Fetching plugin "cordova-plugin-device" via npm
cordova-plugin-device" will not install due to "C:\Users\Username\Documents\Node\app\plugins\org.apache.cordova.device" being installed.
Dependent plugin "org.apache.cordova.device" already installed on android.
Failed to install 'de.appplant.cordova.plugin.local-notification':CordovaError: Cannot find plugin.xml for plugin 'cordova-plugin-app-event'. Please try adding it again.
    at new PluginInfo (C:\Program Files\nodejs\node_modules\cordova\node_modules\cordova-lib\node_modules\cordova-common\src\PluginInfo\PluginInfo.js:338:15)
    at PluginInfoProvider.get (C:\Program Files\nodejs\node_modules\cordova\node_modules\cordova-lib\node_modules\cordova-common\src\PluginInfo\PluginInfoProvider.js:35:32)
    at runInstall (C:\Program Files\nodejs\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:284:43)
    at installDependency (C:\Program Files\nodejs\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:566:16)
    at C:\Program Files\nodejs\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:449:32
    at _fulfilled (C:\Program Files\nodejs\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Program Files\nodejs\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Program Files\nodejs\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Program Files\nodejs\node_modules\cordova\node_modules\q\q.js:810:14
    at flush (C:\Program Files\nodejs\node_modules\cordova\node_modules\q\q.js:108:17)
```

Error:
> Error: Cannot find plugin.xml for plugin 'cordova-plugin-app-event'. Please try adding it again.

I tried adding the plugin again, but I ended up with the same error.

**Option 2:**
Command:
```
cordova plugin add de.appplant.cordova.plugin.local-notification@0.8.1
```

Output:
```
Fetching plugin "de.appplant.cordova.plugin.local-notification@0.8.1" via npm
Fetching plugin "de.appplant.cordova.plugin.local-notification@0.8.1" via cordova plugins registry
Installing "de.appplant.cordova.plugin.local-notification" for android
Notice: org.apache.cordova.device has been automatically converted to cordova-plugin-device and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin "cordova-plugin-device" via npm
cordova-plugin-device" will not install due to "C:\Users\Username\Documents\Node\app\plugins\org.apache.cordova.device" being installed.
Dependent plugin "org.apache.cordova.device" already installed on android.

        Your support is needed. If you use the plugin please support us in order to ensure further development.
        https://github.com/katzer/cordova-plugin-local-notifications/tree/example#how-can-i-support-the-further-development

        Thank you!
    
Installing "de.appplant.cordova.plugin.local-notification" for ios
Notice: org.apache.cordova.device has been automatically converted to cordova-plugin-device and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin "cordova-plugin-device" via npm
cordova-plugin-device" will not install due to "C:\Users\Username\Documents\Node\app\plugins\org.apache.cordova.device" being installed.
Dependent plugin "org.apache.cordova.device" already installed on ios.

        Your support is needed. If you use the plugin please support us in order to ensure further development.
        https://github.com/katzer/cordova-plugin-local-notifications/tree/example#how-can-i-support-the-further-development

        Thank you!
    

```
Error:

>Uncaught TypeError: Cannot read property 'subscribe' of undefined

**The error occurs on:**

file:///android_asset/www/plugins/de.appplant.cordova.plugin.local-notification/www/local-notification.js:751

```javascript
// Called before 'deviceready' event
channel.onCordovaReady.subscribe(function () {
    // Device plugin is ready now
    channel.onCordovaInfoReady.subscribe(function () { //this is line 751
        // Merge platform specifics into defaults
        exports.applyPlatformSpecificOptions();
    });
});
```
The plugin is installed. I get the error above in the console when opening the apk on my android device. I also see **cordova.js:1186 deviceready has not fired after 5 seconds.** in the console after the error.

**Option 3:**
Command:
```
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.8.1
```

Output:
```
Fetching plugin "https://github.com/katzer/cordova-plugin-local-notifications" via git clone
Repository "https://github.com/katzer/cordova-plugin-local-notifications" checked out to git ref "0.8.1".
Installing "de.appplant.cordova.plugin.local-notification" for android
Notice: org.apache.cordova.device has been automatically converted to cordova-plugin-device and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin "cordova-plugin-device" via npm
cordova-plugin-device" will not install due to "C:\Users\Username\Documents\Node\app\plugins\org.apache.cordova.device" being installed.
Dependent plugin "org.apache.cordova.device" already installed on android.

        Your support is needed. If you use the plugin please support us in order to ensure further development.
        https://github.com/katzer/cordova-plugin-local-notifications/tree/example#how-can-i-support-the-further-development

        Thank you!
    
Installing "de.appplant.cordova.plugin.local-notification" for ios
Notice: org.apache.cordova.device has been automatically converted to cordova-plugin-device and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin "cordova-plugin-device" via npm
cordova-plugin-device" will not install due to "C:\Users\Username\Documents\Node\app\plugins\org.apache.cordova.device" being installed.
Dependent plugin "org.apache.cordova.device" already installed on ios.

        Your support is needed. If you use the plugin please support us in order to ensure further development.
        https://github.com/katzer/cordova-plugin-local-notifications/tree/example#how-can-i-support-the-further-development

        Thank you!
    

```
Error:

>Uncaught TypeError: Cannot read property 'subscribe' of undefined

**The error occurs on:**

file:///android_asset/www/plugins/de.appplant.cordova.plugin.local-notification/www/local-notification.js:751

```javascript
// Called before 'deviceready' event
channel.onCordovaReady.subscribe(function () {
    // Device plugin is ready now
    channel.onCordovaInfoReady.subscribe(function () { //this is line 751
        // Merge platform specifics into defaults
        exports.applyPlatformSpecificOptions();
    });
});
```
The plugin is installed. I get the error above in the console when opening the apk on my android device. I also see **cordova.js:1186 deviceready has not fired after 5 seconds.** in the console after the error.

Solution 1 seems to be the same as 3 and I don't know if I compile Local Notifications correctly or how I compile Local Notifications correctly (solution 2). I also wonder if I am responsible for setting property 'subscribe' at the correct value or if it's someting that the plugin should do because I haven't added any code. I only added the plugin.

**Comment by spottuit** [comment]
**UPDATE:**

>Error: Cannot find plugin.xml for plugin 'cordova-plugin-app-event'. Please try adding it again.

I managed to solve the error above. What I did wrong was reinstalling the plugin: **cordova-plugin-local-notifications**, but I actually had to reinstall the plugin: **cordova-plugin-app-event**.

**Comment by spottuit** [comment]
UPDATE:

>Uncaught TypeError: Cannot read property 'subscribe' of undefined

>cordova.js:1186 deviceready has not fired after 5 seconds

I managed to remove the errors above. Apparantly my plugin: **cordova-plugin-device**  or **org.apache.cordova.device** wasn't installed properly. 

I removed both plugins(**cordova-plugin-device** and **org.apache.cordova.device**) from:
- the /plugins folder
- /plugins/android.json
-  /plugins/fetch.json 
- ios.json

I only need one of the plugins (**cordova-plugin-device**). The other plugin(**org.apache.cordova.device**) is from the outdated plugin repository if I am correct. I also noticed there was no device plugin in here: **\platforms\android\platform_www\plugins** (also not in ios platform_www).

I installed **cordova-plugin-device** again, but got the following error:
>Error: Uh oh! "C:\Users\Username\Documents\Node\app\platforms\android\src\org\apache\cordova\device\Device.java" already exists!

So I removed the folder device and installed **cordova-plugin-device** again. Tested my app on a device and the errors were gone. I also managed to get a notification :D. 

Hopefully this issue will help people that have the same problem as I had.

**Comment by renjithvk** [comment]
I **SOLVED** that by add the plugin from GitHub repository: https://github.com/meteor/meteor/issues/8998#issuecomment-353261759

**Comment by WilliWespe** [comment]
Hello, I have the same problem. Could you please publish your code somewhere? It would really help.
Otherwise I will try again what you wrotey thank you anyways :-)
