### ISSUE TITLE
Does schedule contain property message or is the documentation wrong?

### ISSUE THREAD

**Issue by spottuit** [katzer/cordova-plugin-local-notifications#821]
I was looking at [this example in the plugins wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki/11.-Samples#schedule-notifications) and I saw the property 'message'. I couldn't find this property in [the documentation about the .schedule({});](https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling) so I am wondering if this property isn't documented or if it's suppose to be the property 'text' because that makes sense.

**Comment by iamkwan** [comment]
@spottuit 
text = message

**Comment by spottuit** [comment]
Well in that case I hope the owner(s) of this repo will change message to text. It's a little confusing.

**Comment by iamkwan** [comment]
the message is old attribute
it renamed from 'message' to 'text'

**Comment by spottuit** [comment]
'message' isn't an old attribute. The attribute is still usable. I found it inside the [local-notification-util.js](https://github.com/katzer/cordova-plugin-local-notifications/blob/master/www/local-notification-util.js) on **line 91**:

```Javascript
options.text = this.getValueFor(options, 'text', 'message');
```

I also tested if I could use 'message' instead of 'text'. I should have done that in the first place because it worked. So basicly you can set the text of a notification with either 'text' or 'message'.
