### ISSUE TITLE
"UserInfo" error on run at ios (3.9.2)

### ISSUE THREAD

**Issue by ahait** [katzer/cordova-plugin-local-notifications#823]
Getting following error:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'unable to serialize userInfo: Error Domain=NSCocoaErrorDomain Code=3851 "Property list invalid for format: 200 (property lists cannot contain objects of type 'CFNull')" UserInfo={NSDebugDescription=Property list invalid for format: 200 (property lists cannot contain objects of type 'CFNull')}'
## When running following JS:

```
    var tomorrow_at_7_am = new Date('2016-01-10 07:00:00.01');
    cordova.plugins.notification.local.schedule({
        id: 1,
        text: "text comes here",
        firstAt: tomorrow_at_7_am,
        every: "day" // "minute", "hour", "week", "month", "year"
    });
```

---

using phonegap cli 5.4.0

**Comment by ahait** [comment]
After hours and hours of debugging... (first time ever in Xcode)...
I found out that the date doesnt work...
var tomorrow_at_7_am = new Date('2016-01-10 07:00:00.01');

But I am not an obj-c or swift developer, so its just my best shot since "new Date()" works, but the other one does not....

**Comment by modestoartur** [comment]
i'm still in the same problem, help us!

**Comment by padho** [comment]
Hi,
this issue arises from the fact that Safari can't parse your date format. See [this discussion on Stackoverflow](http://stackoverflow.com/questions/4310953/invalid-date-in-safari).

A quick fick would be something like:

`var tomorrow_at_7_am = new Date('2016-01-10 07:00:00.01'.replace(/\s/, 'T'));`

Make sure that the timezone is correct. You could also take a look at [moment.js](http://momentjs.com/) which makes date handling a lot easier.

**Comment by rwillett** [comment]
Is this still an issue otherwise I'll close it.

**Comment by rwillett** [comment]
No update so closing.
