### ISSUE TITLE
Notification every second

### ISSUE THREAD

**Issue by phuongtailtranminh** [katzer/cordova-plugin-local-notifications#824]
Hi,

I'm trying to set local notification to every second with this code:

```
<script type="text/javascript">
    document.addEventListener('deviceready', onDeviceReady, false);

        function onDeviceReady() {

        cordova.plugins.notification.local.schedule({
            text: "Wake up!",
            every: 0.05 // every 3 seconds
        });

        }
</script>
```

But it seem like just notify me 1 times. Is there a bug? [I'm testing with Android]

If I change value of 'every' property to: 1 which means 1 minutes, it works correctly!

**Comment by spottuit** [comment]
Replace 0.05 with 'second' and it will work.

**Comment by phuongtailtranminh** [comment]
Thank for your reply!

So how can I make 3 seconds schedule?

**Comment by Variable2016** [comment]
@phuongtailtranminh  please can you explain how this this really works mine it  not firing notification.Thanks in Advance.

**Comment by rwillett** [comment]
Is this still an issue or can it be closed?

**Comment by WiNNiep00h** [comment]
for me its not working. when i write "second" it is firing every minute

**Comment by rwillett** [comment]
Use the template in #1188 and update it. There does appear to be issues with the ```every:``` flag.

Make sure you put your code in there.

**Comment by rwillett** [comment]
Closed as no response from original poster.
