### ISSUE TITLE
Cancel un-define id schedule

### ISSUE THREAD

**Issue by phuongtailtranminh** [katzer/cordova-plugin-local-notifications#825]
Hi,

I've defined a schedule without ID, now I can't cancel this schedule

                cordova.plugins.notification.local.schedule({
                    text: "Wake up!",
                    sound: "file://sounds/alert.caf",
                    every: 30 // every 30 minutes
                });

I've tried this:

                cordova.plugins.notification.local.cancel(0, function () {
                    alert('Notification has been cancalled');
                }, scope);

But the schedule is still effect!

**Comment by spottuit** [comment]
If you have only one notification or don't mind to cancel all notifications you can try this:

```javascript
cordova.plugins.notification.local.cancelAll(callback);
```

**Comment by phuongtailtranminh** [comment]
Hi,

Thank for your reply!

I've met another trouble, I'm trying to cancel notification with id = 1 with this code

                cordova.plugins.notification.local.cancel(1, function() {
                    alert('OK')
                }, scope);        

But it doesn't work. Do I have to define scope?

**Comment by phuongtailtranminh** [comment]
I've fixed this problem with specific scope for function. Thank for your help!

            cordova.plugins.notification.local.cancel(1, function() {
                alert('OK')
            }, this);
