### ISSUE TITLE
'trigger' event handler only called the first time on Android, then never again.  Same code works fine on iOS.

### ISSUE THREAD

**Issue by jim0020** [katzer/cordova-plugin-local-notifications#829]
I have registered several event handlers, together in the same block.  I have a repeating event, which is set to repeat every minute.  The notification appears, as expected, every minute.  In Android, the 'trigger' event handler is only called the first time. After the first time, it is never called again.  The 'click' event works fine, and is called every time I click on the notification.

In iOS, the 'trigger' event handler works fine, it's called every time the notification appears.  In Android, the event handler is only called the first time the notification appears.

**Comment by jim0020** [comment]
In Android (src/android/TriggerReceiver.java:50), it looks like the 'trigger' event is set to only fire if the event has been updated.  In iOS this is not the case, it is fired every time.  Is this the desired behavior?

**Comment by philliphicks** [comment]
I'm facing this issue too. Did you find a solution @jim0020?

**Comment by jim0020** [comment]
I no longer use repeating notifications.  Every time one is triggered, I cordova.plugins.notification.local.update() the notification to set 'at' for the next due datetime.  I store JSON in the 'data' field which contains the repeat interval value which I convert to msecs and add the the current 'at' value to get the new trigger datetime.  Of course, there are other ways to store this data, but this way I don't have to map notification objects to some datastore.


I did do this for a while in src/android/TriggerReceiver.java:50, but I got rid of it to avoid custom changes to the plugin code...

public class TriggerReceiver extends de.appplant.cordova.plugin.notification.TriggerReceiver {

    /**
     * Called when a local notification was triggered. Does present the local
     * notification, re-schedule the alarm if necessary and fire trigger event.
     *
     * @param notification
     *      Wrapper around the local notification
     * @param updated
     *      If an update has triggered or the original
     */
    @Override
    public void onTrigger (Notification notification, boolean updated) {
        super.onTrigger(notification, updated);

        // if (!updated) {
            LocalNotification.fireEvent("trigger", notification);
       // }
    }

**Comment by philliphicks** [comment]
Great, thanks @jim0020, much appreciated.

**Comment by rwillett** [comment]
Is this still an issue otherwise I'll close it.
