### ISSUE TITLE
isScheduled() returns null on iOS

### ISSUE THREAD

**Issue by catnipapp** [katzer/cordova-plugin-local-notifications#830]
I'm developing an app for iOS9 which is using the latest version of this plugin. It seems that the isScheduled function returns null, regardless of whether a notification has been added or not. 

```
cordova.plugins.notification.local.isScheduled(parseInt(id), function(isScheduled) {
    return isScheduled;
    // Always returns null
});
```

I have confirmed that the notification is created. As expected, it appears within the notification drawer. The notification is even registered and appears when I call getAll(). And yet, I cannot locate it using isScheduled().

I'm not sure how to resolve this, or probe the issue further. Guidance would be appreciated. 

Thank you!

**Comment by rwillett** [comment]
Is this still an issue or can it be closed? No update in a year!
