### ISSUE TITLE
Crash on Android when scheduling a notification

### ISSUE THREAD

**Issue by JiDW** [katzer/cordova-plugin-local-notifications#833]
Hello.

Here is our crash log : 

01-14 16:57:19.209: W/System.err(28403): java.lang.NumberFormatException: Invalid int: "null"
01-14 16:57:19.226: W/System.err(28403):    at java.lang.Integer.invalidInt(Integer.java:138)
01-14 16:57:19.226: W/System.err(28403):    at java.lang.Integer.parse(Integer.java:410)
01-14 16:57:19.226: W/System.err(28403):    at java.lang.Integer.parseInt(Integer.java:367)
01-14 16:57:19.226: W/System.err(28403):    at java.lang.Integer.parseInt(Integer.java:334)
01-14 16:57:19.226: W/System.err(28403):    at de.appplant.cordova.plugin.notification.Options.parseInterval(Options.java:120)
01-14 16:57:19.226: W/System.err(28403):    at de.appplant.cordova.plugin.notification.Options.parse(Options.java:80)
01-14 16:57:19.226: W/System.err(28403):    at de.appplant.cordova.plugin.notification.Manager.schedule(Manager.java:80)
01-14 16:57:19.233: W/System.err(28403):    at de.appplant.cordova.plugin.localnotification.LocalNotification.schedule(LocalNotification.java:216)
01-14 16:57:19.233: W/System.err(28403):    at de.appplant.cordova.plugin.localnotification.LocalNotification.access$000(LocalNotification.java:50)
01-14 16:57:19.233: W/System.err(28403):    at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:138)
01-14 16:57:19.233: W/System.err(28403):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-14 16:57:19.233: W/System.err(28403):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-14 16:57:19.233: W/System.err(28403):    at java.lang.Thread.run(Thread.java:818)

01-14 16:57:19.418: E/AndroidRuntime(28403): FATAL EXCEPTION: pool-1-thread-7
01-14 16:57:19.418: E/AndroidRuntime(28403): Process: com.celsiusonline.celsiusheroes, PID: 28403
01-14 16:57:19.418: E/AndroidRuntime(28403): java.lang.NumberFormatException: Invalid int: "null"
01-14 16:57:19.418: E/AndroidRuntime(28403):    at java.lang.Integer.invalidInt(Integer.java:138)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at java.lang.Integer.parse(Integer.java:410)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at java.lang.Integer.parseInt(Integer.java:367)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at de.appplant.cordova.plugin.notification.Options.getColor(Options.java:265)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at de.appplant.cordova.plugin.notification.Builder.build(Builder.java:122)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at de.appplant.cordova.plugin.notification.Manager.schedule(Manager.java:92)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at de.appplant.cordova.plugin.notification.Manager.schedule(Manager.java:80)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at de.appplant.cordova.plugin.localnotification.LocalNotification.schedule(LocalNotification.java:216)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at de.appplant.cordova.plugin.localnotification.LocalNotification.access$000(LocalNotification.java:50)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:138)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-14 16:57:19.418: E/AndroidRuntime(28403):    at java.lang.Thread.run(Thread.java:818)

And here is our code : 

cordova.plugins.notification.local.schedule({
    id:1,
    title:"Celsius Heroes",
    text: lang.lg("TexteNotificationAPMax"),
    at: ch.gestionAP.dateAPMax,
    led: "FFFFFF",
    sound: null,
    icon:"res://iconandroid.png",
    smallIcon:"res://notifandroid.png"
});

We run this plugin with Cocoon.io.
I do'nt find anything in the wiki related to a "color" parameter.
I tried to set it to "000000" and null but it didn't do anything more.

Can you help us please ?
Regards.

**Comment by catnipapp** [comment]
Remove "sound: null" and try again.

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no update from original poster.
