### ISSUE TITLE
Build failed with iOS: ld: 1 duplicate symbol for architecture i386

### ISSUE THREAD

**Issue by vasam** [katzer/cordova-plugin-local-notifications#834]
Latest version of plugin do not allow to build ios, getting following error:

ld: 1 duplicate symbol for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

No errors without local notification plugin. Please advise.

System information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.3 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.2 Build version 7C68

**Comment by ReavingDev** [comment]
Signing this, i have the exact same error with duplicate symbol for architecture i386.

**Comment by hannes-k** [comment]
I've got the same problem after upgrading to the newest version. 
Removing the old dependency (cordova plugin remove de.appplant.cordova.common.registerusernotificationsettings) fixed this issue.

**Comment by rwillett** [comment]
Is this an issue or can it be closed ? Its now over a year old.
