### ISSUE TITLE
PhoneGap Build error

### ISSUE THREAD

**Issue by fritek373** [katzer/cordova-plugin-local-notifications#835]
I took the "starter" demo for PhoneGap and added the plugin via ```<gap:plugin name="de.appplant.cordova.plugin.local-notification" version="0.8.1" />```, no further changes were made. When I place it in PhoneGap Build, I get this error: *Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: LocalNotification.java - You can fix this here*. When I remove the *<gap:plugin>* code is works fine. I have attaced the src, changed lines 81-83 in config.xml.
[src.zip](https://github.com/katzer/cordova-plugin-local-notifications/files/90920/src.zip)

**Comment by robochris** [comment]
i had the same problem and put this instead and it worked for me.
`<gap:plugin name="de.appplant.cordova.plugin.local-notification" source="npm" version="0.8.4"/>`

**Comment by fritek373** [comment]
That works for me too! Awesome tnx :+1:.

**Comment by MarcBalaban** [comment]
@fritek373 Can you please specify the fix? It seems a bit unclear as I'm still having this issue.  Thanks.

**Comment by fritek373** [comment]
@MarcBalaban Do you use PhoneGap build?
