### ISSUE TITLE
Request: disable vibration on Android

### ISSUE THREAD

**Issue by fritek373** [katzer/cordova-plugin-local-notifications#837]
It would be very helpfull for me to disable the the vibrations on Android. I'm using PhoneGap build, so I can't use this https://github.com/katzer/cordova-plugin-local-notifications/issues/216 fix :(. Would it be hard to add a _no vibration_ function?

**Comment by Arxi** [comment]
+1 for the control over vibration, if it's possible

**Comment by rchowdhe** [comment]
vibrate option still shows as undefined property, please suggest how it will work, i tried with option vibrate:0 and it says vibrate is not default property.

**Comment by edoardoo** [comment]
Is this going to be merged into @katzer repo? If so in which release? Thank you.

**Comment by katzer** [comment]
@edoardoo I've merged the PR into master. The release will be 0.9, however the development for this release happens in the x branch, which is not stable yet.

@rwillett You can also merge PR's into master or ios10 branch as I am working on the x branch.

**Comment by katzer** [comment]
That has been added to 0.9-beta, thanks!
