### ISSUE TITLE
Notification on Lollipop doesn't run with configurated date.

### ISSUE THREAD

**Issue by debe78** [katzer/cordova-plugin-local-notifications#838]
Hi i'm using your plugin (latest version 0.8.4) but with android 5 (lollipop on huawey p8) it does not run, i don't see the notification if i use a configurated date for example between two day, but if i dont't configure the date and use new data() i see the notification immediatly.
If i use Android 4.1.2 (samsung s2) it runs very well for every date i configure.
I'm using cordova 5.3.3.

Is it possible enable a log?

this is my notification event:
var attivationday = [the day and time configurated by user]
cordova.plugins.notification.local.schedule({
        id:         1,
        at:         attivationday,
        text:       'Cambiare lenti!',
        title:      'Timer LAC',
        badge:      1,
        every:      'hour',
        ongoing:    false
      });
    }

**Comment by rwillett** [comment]
Is this an issue or can it be closed ? Its now over a year old.
