### ISSUE TITLE
Reschedule notification if device is not running

### ISSUE THREAD

**Issue by joaojoyce** [katzer/cordova-plugin-local-notifications#839]
I am trying to schedule an event to run at 9am. But in case the device is not running I would like the event to trigger as soon as the device starts.

I have tried this and have been playing with the events but I was unable to do it.
            cordova.plugins.notification.local.schedule({
                id:2000,
                title: "Test",
                text: 'My first notification',
                firstAt:new Date(new Date().getTime() + 2*60000),
            });

**Comment by rwillett** [comment]
You will need to query the notifications on startup and work out what has happened.

Is this an issue or can it be closed ? Its now over a year old.
