### ISSUE TITLE
Breakline on message \r\n

### ISSUE THREAD

**Issue by cdorner** [katzer/cordova-plugin-local-notifications#840]
Hi, I can't find any way to break line on the message. I tried \n, \r\n, but no success.

**Comment by cdorner** [comment]
I just found that it's not possible yet since the plugin doesn't have support for inbox style messages on Android.
On iOS the \r\n works but for android the plugin needs to implement the feature.

**Comment by rvenancior** [comment]
Hello @cdorner!

I know that is not the best way, but add the above code at platforms/android/src/de/appplant/cordova/plugin/notification/Builde.java - line 144 and still use "\r\n".

`		String text = options.getText();
		String[] texts = text.split("\r\n");
		int qtdText = texts.length;
		if(qtdText > 1){
			NotificationCompat.InboxStyle inboxStyle = new NotificationCompat.InboxStyle();
			inboxStyle.setBigContentTitle(options.getTitle());
			for (int i=0; i < qtdText; i++) {
				inboxStyle.addLine(texts[i]);
			}
			builder.setStyle(inboxStyle);
		}`
