### ISSUE TITLE
TypeError: Cannot call method 'indexOf' of undefined

### ISSUE THREAD

**Issue by shallsaur** [katzer/cordova-plugin-local-notifications#841]
I have tried looking around for solutions for a week now but it seems that there is no one facing the same issue as I did. I hope I can get help on this.

I am running Cordova 4.3.1.

If I run the following command to add the plugin into my project:

> cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications

This is the response i would get:

> Fetching plugin "https://github.com/katzer/cordova-plugin-local-notifications" via git clone
> Installing "de.appplant.cordova.plugin.local-notification" for android
> TypeError: Cannot call method 'indexOf' of undefined
>     at C:\Users\shallsaur.DOMAIN\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:232:45
>     at Array.forEach (native)
>     at getEngines (C:\Users\shallsaur.DOMAIN\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:211:13)
>     at runInstall (C:\Users\shallsaur.DOMAIN\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:269:22)
>     at C:\Users\shallsaur.DOMAIN\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:81:16
>     at _fulfilled (C:\Users\shallsaur.DOMAIN\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
>     at self.promiseDispatch.done (C:\Users\shallsaur.DOMAIN\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
>     at Promise.promise.promiseDispatch (C:\Users\shallsaur.DOMAIN\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
>     at C:\Users\shallsaur.DOMAIN\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:810:14
>     at flush (C:\Users\shallsaur.DOMAIN\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)

I have noticed that the src package was not included in my project when it is opened in Eclipse.

I have also been getting the following error when trying to run just a simple schedule() function:

> Uncaught TypeError: Cannot read property 'notification' of undefined

**Comment by shallsaur** [comment]
I have resorted to installing the older 0.8.1 version and it seems to work.
Just a heads up to you guys on this issue while I will use the older version for now.

>
cordova plugin add de.appplant.cordova.plugin.local-notification@0.8.1

**Comment by codingbandit** [comment]
I had the same issue, will try using the older now

**Comment by codingbandit** [comment]
I couldn't get the older version to install. Discovered Visual Studio Tools for Apache Cordova is compatible with Cordova CLI 5.1.1, after updating my version, I was able to install the plugin without issue.

**Comment by rwillett** [comment]
Is this an issue or can it be closed ? Its now over a year old.
