### ISSUE TITLE
All notifications been cleared when click in one of them - Android

### ISSUE THREAD

**Issue by cdorner** [katzer/cordova-plugin-local-notifications#842]
When I have two or more notifications (different id's) if I click in one the others just vanish, without calling clear or clearAll event.
The same occurs if Android pause the app, if I click home button the notifications is been cleared from the notification area.

This is the default behavior of Android or I'm doing sothing wrong?

**Comment by diegoherrera** [comment]
When I have two or more notifications (different id's) if I click in one the others just vanish. you have a solution?

**Comment by cdorner** [comment]
Hey @diegoherrera It's been a while since I work with this plugin, but if I remember correct no I don't find a solution for this problem.

**Comment by rwillett** [comment]
Is this still an issue or can it be closed ? Its nearly a year old.

**Comment by diegoherrera** [comment]
Hi

Close please, this is old

Bye
