### ISSUE TITLE
Android 5.0+ "!@Too many alarms (500) registered from pid XXXX uid YYYYY"

### ISSUE THREAD

**Issue by logalleg** [katzer/cordova-plugin-local-notifications#843]
On Android 5.0+ on Samsung there is an issue with crashing due to "!@Too many alarms (500) registered from pid XXXX uid YYYYY". 

I did a little bit of research and it pointed to possibly using PendingIntent.FLAG_CANCEL_CURRENT vs PendingIntent. FLAG_UPDATE_CURRENT.

Our particular use case we are never scheduling over 500 notifications at once, but over time we can definitely be scheduling over 500 total.

**Comment by phavre** [comment]
I do have the same issue on android. I try to register 995 notification, I can cancelAll also and reregister them if needed. Weirdly it seems to work on some level on some android (Wiko brand lolipop 5.1)

**Comment by phavre** [comment]
I just saw that on January the 3rd, the 0.8.3 version fixed the #710 issue on android Samsung lollipop.
Did you updated the plugin @logalleg?

**Comment by logalleg** [comment]
I just updated to version 0.8.4 an that did not resolve the issue.

**Comment by logalleg** [comment]
Updated to 0.8.4 and the issue still exists (also tried 0.8.3)

**Comment by zenrobin** [comment]
Also updated but issue still exists. Web searches indicate that Google's Firebase messaging has a similar error.  Details [here](http://stackoverflow.com/questions/40212155/firebase-messaging-too-many-alarms-on-samsungs-android-devices/40786050#40786050)

**Comment by zenrobin** [comment]
Stack trace:

java.lang.SecurityException: !@Too many alarms (500) registered from pid 27889 uid 12608

at android.os.Parcel.readException(Parcel.java:1540)
at android.os.Parcel.readException(Parcel.java:1493)
at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:206)
at android.app.AlarmManager.setImpl(AlarmManager.java:428)
at android.app.AlarmManager.set(AlarmManager.java:215)

at de.appplant.cordova.plugin.localnotification.LocalNotification.a(Unknown Source)
at de.appplant.cordova.plugin.localnotification.a.run(Unknown Source)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by zenrobin** [comment]
found this - going to look into it: 
https://github.com/katzer/cordova-plugin-local-notifications/pull/921

**Comment by rwillett** [comment]
Is this still an issue or can it be closed ? Its nearly a year old.

**Comment by zenrobin** [comment]
The fix that I found is to use the try catch referenced in the issue above. This repro's master has a pull request with it (I think) but has not been updated. So technically the issue is still there until that try catch is installed, or another fix is found. 

In LocalNotification.java: 
// referenced from: https://github.com/uareurapid/cordova-plugin-local-notifications/blob/6759116c16965a987c9fcc0a3cbc3024d5cf62cc/src/android/LocalNotification.java

try
{
         AlarmManager am = getAlarmManager();
       PendingIntent pi = PendingIntent.getBroadcast(context, 0, intent, PendingIntent.FLAG_CANCEL_CURRENT);

            if (doFireEvent) {
                fireEvent("add", options.getId(), options.getJSON());
            }

            am.set(AlarmManager.RTC_WAKEUP, triggerTime, pi);
        }
        catch(Exception generic) {
            //silently ignore the exception
            //on some samsung devices there is a known bug where a 500 alarms limit can crash the app
            //http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=280286&listLines=15&startId=zzzzz%7E&searchSubId=0000000001
        }
    }

**Comment by rwillett** [comment]
This appears to be a bug in Android rather than this plugin? This patch catches the Android bug. 

Is that the case? If so I'll leave the issue open and flag it as a bug/enhancement.

**Comment by katzer** [comment]
The patch has been integrated with 0.9-beta. Thanks!
