### ISSUE TITLE
Error for `cordova run ios` 

### ISSUE THREAD

**Issue by calvintan** [katzer/cordova-plugin-local-notifications#844]
Hello there. I've clone the example branch, and when i do `cordova run ios` the following error occurs:
Error: ENOENT: no such file or directory, stat '/Users/calvin/testfolder/cordova-plugin-local-notifications/plugins/de.appplant.cordova.plugin.local-notification'

Is there something I've missed?

**Comment by bodiam** [comment]
No, you didn't miss anything. Just go the /Users/calvin/testfolder/cordova-plugin-local-notifications/plugins/ directory, and do an ls -al. You'll see that someone checked in a symbolic link:

`de.appplant.cordova.plugin.local-notification -> /Users/sebastian/Documents/github/cordova-plugin-local-notifications`

It doesn't matter much, because after that, you'll run into other issues:

```
Running command: /Users/erikp/Downloads/cordova-plugin-local-notifications-example/platforms/ios/cordova/run
module.js:339
    throw err;
    ^

Error: Cannot find module './Api'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/erikp/Downloads/cordova-plugin-local-notifications-example/platforms/ios/cordova/run:24:11)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
```

**Comment by KamChanLiu** [comment]
Removing the symbolic link and re-adding the plugin via registry (`cordova plugin add de.appplant.cordova.plugin.local-notification@0.8.1`) seemed to fix it for me.

**Comment by rwillett** [comment]
Can this be closed now. It looks like its working.

**Comment by DWboutin** [comment]
It doesn't work for me

**Comment by rwillett** [comment]
Use the template in #1188 and raise a new issue. This one is from over a year ago and a lot has changed.

**Comment by oldergod** [comment]
This problem is still relevant.

**Comment by rwillett** [comment]
I just ran ```cordova run ios``` for the very first time. We never use this command and rarely use the simulator expect for small issues as the GPS on the simulator is junk and push notifications don't work.

Works fine for me.

**Comment by oldergod** [comment]
Does this look fine?

https://github.com/katzer/cordova-plugin-local-notifications/blob/example/plugins/cordova-plugin-app-event

**Comment by rwillett** [comment]
No idea. 

I have not done anything to get ```cordova run ios``` to work.

It just works.
