### ISSUE TITLE
Not scheduled on mobile device WP 8.1

### ISSUE THREAD

**Issue by Grumaks** [katzer/cordova-plugin-local-notifications#848]
Hi.
I use Visual Studio and this plugin. I implemented simple schedule notification (not multi, not timer). 
And it doesn't work on WP 8.1 mobile device. This work only when I debug application with VS debugger and register permission when first notification fire. When I deploy application, detached phone and launch application on phone notifications doesn't work, and even not register permission.(upd: I see it in phone setting)

Pls, help.

**Comment by claudiobadii** [comment]
On the output of the debug, do you have a error like "plugin LocalNotification not allowed?"

**Comment by katzer** [comment]
WP 8.1 is not a supported platform. The plugin supports Windows UWP
