### ISSUE TITLE
Could not retrieve plugin dependencies for LocalNotification

### ISSUE THREAD

**Issue by Zapmobilegames** [katzer/cordova-plugin-local-notifications#849]
Passing from the 0.8.2 to the 0.8.4 I'm not able to install the plugin. I already installed: 
- android.support.v4
- org.apache.cordova.device
- cordova-plugin-app-event
- cordova-plugin-registerusernotificationsettings
  I always got: "Could not retrieve plugin dependencies for LocalNotification"
  What else I need?

**Comment by rwillett** [comment]
Is this still an issue or can it be closed ? Its over a year old.

**Comment by timsar2** [comment]
this is an issue
error: cannot find symbol
import android.support.v4.util.ArraySet;

error: cannot find symbol
import android.support.v4.app.NotificationCompat.MessagingStyle.Message;
