### ISSUE TITLE
display a progress bar in the notification

### ISSUE THREAD

**Issue by escolhatecnologia** [katzer/cordova-plugin-local-notifications#850]
how display a progress bar in the notification and  update  every second ?

**Comment by cmgchris** [comment]
Notifications are text only.

**Comment by escolhatecnologia** [comment]
how  update a notification  every second without create  another notification?

**Comment by midhunadarvin** [comment]
Is it possible to add this as a new feature?

**Comment by rwillett** [comment]
Unlikely.

**Comment by RodolfoSilva** [comment]
Displaying Progress in a Notification - https://developer.android.com/training/notify-user/display-progress.html

**Comment by RodolfoSilva** [comment]
PR - #1047

**Comment by katzer** [comment]
Has been added for Android and Windows. See the README. Thanks
