### ISSUE TITLE
When Local notification schedule crashes the app in iOS

### ISSUE THREAD

**Issue by praveenjzerosoft** [katzer/cordova-plugin-local-notifications#853]
When i schedule the notification it crashes the app in iOS. is shows error in

File Name: APPLocalNotification.m

 (id) initWithOptions:(NSDictionary*)dict {

   self = [super init];

   [self setUserInfo:dict];                        Thread 18:signal SIGABRT

   [self __init];

   return self;

}

**Comment by rwillett** [comment]
Is this still an issue or can it be closed ? Its nearly a year old.
