### ISSUE TITLE
questions in ios

### ISSUE THREAD

**Issue by hyitclj** [katzer/cordova-plugin-local-notifications#854]
first one,sound not work in ios.my code:
cordova.plugins.notification.local.schedule({
                id: 11,
                title: "game over",
                text: "",
                sound: 'file://1.caf',
                led: "FF0000",
                at: clocktime
            });
1.caf in cordova's www folder
second,notification don't work when the application is being used

in android,no problem

the version in ios:0.8.2
if use 0.8.4,the application will exit immediately when use it

**Comment by hyitclj** [comment]
in android,no problem

**Comment by hyitclj** [comment]
the version in ios:0.8.2
if use 0.8.4,the application will exit immediately when use it

**Comment by tsvarsha** [comment]
I am facing the same issue. Did anyone find the solution yet?

**Comment by fenglu09** [comment]
I am facing the same issue too.

**Comment by Tawpie** [comment]
Try making the id a string `id: “11”`

**Comment by rwillett** [comment]
Is this still an issue or can it be closed?
