### ISSUE TITLE
Build failed on iOS (using 0.9 dev branch)

### ISSUE THREAD

**Issue by kjt1212** [katzer/cordova-plugin-local-notifications#855]
Hi, this is in continuation to the discussion on https://github.com/katzer/cordova-plugin-local-notifications/pull/799.

Firstly, I must say that the plugin you guys have created is amazing and I have been using it. I currently want to have support for interactive notifications so I checked out the feature branch that you guys are working on - 0.9-dev and am trying to use it. However, when I build my project for iOS it gives me the following error:
*\* BUILD FAILED **

The following build commands failed:
    CompileC build/headUpNotificationsKatzerExtend.build/Debug-iphonesimulator/headUpNotificationsKatzerExtend.build/Objects-normal/i386/APPLocalNotification.o headUpNotificationsKatzerExtend/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Volumes/Data/headUpNotificationsKatzerExtend/platforms/ios/cordova/build-debug.xcconfig,-project,headUpNotificationsKatzerExtend.xcodeproj,ARCHS=i386,-target,headUpNotificationsKatzerExtend,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Volumes/Data/headUpNotificationsKatzerExtend/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Volumes/Data/headUpNotificationsKatzerExtend/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Volumes/Data/headUpNotificationsKatzerExtend/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Volumes/Data/headUpNotificationsKatzerExtend/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

I tried removing and adding the ios platform multiple times, however, nothing helped. Can you help me around this?

**Comment by rwillett** [comment]
Is this still an issue or can it be closed ? Its nearly a year old.
