### ISSUE TITLE
App crashes on startup if I try to schedule a local notification on iOS

### ISSUE THREAD

**Issue by kingalione** [katzer/cordova-plugin-local-notifications#856]
My Application crashes on startup since I've added this plugin and implemented the scheduler. 

If I run it on the device with xcode it stops at CDVPlugin+APPAppEvent.m at 

void swizzled_pluginInitialize(id self, SEL _cmd) 

with the error: EXC_BAD_ACCESS (code=2, address=0x16fc27ff0)

What can I do to run this plugin?

**Comment by zanemcca** [comment]
+1

**Comment by OhKoanGyun** [comment]
+1

**Comment by WilsonFpz** [comment]
+1

**Comment by iadc2005** [comment]
+1

**Comment by hasandogu** [comment]
+1

**Comment by danicastanos** [comment]
+1

**Comment by danicastanos** [comment]
This change seems to work (at least app is inited)
https://github.com/katzer/cordova-plugin-app-event/pull/4/files?diff=split

**Comment by nikkow** [comment]
+1

The fix provided seems to fix the issue. Would be great to merge it in the main package :) Thanks for the fix!

**Comment by erikriverson** [comment]
the PR linked by @danicastanos worked for me, too. thanks.

**Comment by GitRubb** [comment]
+1

**Comment by rwillett** [comment]
Is this still an issue or can it be closed ? Its nearly a year old.
