### ISSUE TITLE
clear badge

### ISSUE THREAD

**Issue by kahunafr** [katzer/cordova-plugin-local-notifications#857]
Hi
After opening the application, the badges will not empty. They always increment.
The badge disappears when opening the application, but when next push the badge appears incremented.
Is there a solution?

**Comment by RangerMauve** [comment]
I'm also having issues with this. So far I've had to make a fake notification with the badge number set to 0. Any plans on adding an API for clearing the badges?

**Comment by Liberateur** [comment]
`cordova.plugins.notification.local.cancelAll(callback);` doesn't work for me...
