### ISSUE TITLE
Multiple dex exception

### ISSUE THREAD

**Issue by paul-shatalov** [katzer/cordova-plugin-local-notifications#858]
I'm working on ionic application and I get exception on this set of plugins:

cordova-android-support-v4 4.0.0 "Android Support v4"
cordova-plugin-app-event 1.1.0 "Application Events"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-statusbar 2.1.0 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-keyboard 1.0.8 "Keyboard"

UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

I've saw same issues closed, and I see all these changes in current version, but it still cause same errors.

Without your plugin all works fine.

**Comment by rwillett** [comment]
You need to defined the multiple dex option in the Android config file. Google for the solution as not at my computer.  I have much the same plugins and it does work with this option.

Rob

**Comment by rwillett** [comment]
Is this still an issue or can it be closed ? Its nearly a year old.
