### ISSUE TITLE
0.9 dev branch crashes the app in iOS

### ISSUE THREAD

**Issue by sanmed** [katzer/cordova-plugin-local-notifications#861]
I pulled in the 0.9 version of the plugin and it causes the app to crash when it's loaded. Is this a known issue?

I'd like to use the interactive push actions with the plugin. Should I go back to a working version (not sure which one that would be) of the plugin and pull in the PR related to the actions?

**Comment by hackfanatic** [comment]
same issue here https://github.com/katzer/cordova-plugin-local-notifications/issues/852

**Comment by rwillett** [comment]
Is this still an issue otherwise I'll close it?
