### ISSUE TITLE
Range of possible ids is different on iOS vs Android

### ISSUE THREAD

**Issue by logalleg** [katzer/cordova-plugin-local-notifications#862]
It would probably make the most sense if ids on each were the same size (preferably 64 bits, but of course if this plugin supports 32-bit architectures then it will have to be 32). It would also make sense if they were both unsigned so people can use database ids.

This creates issues where if you want to register a notification on iOS and Android with the same id, but that number is not supported on Android if the ID is a 64-bit value.

Side note - I'm not sure about the Windows side of the plugin, but regardless that means there isn't a consistent range of numbers that the ids can be across all platforms.

**Comment by rwillett** [comment]
Unclear as to why this is needed. Why would you need to have the same internal ID? if you want consistent ID's add some user data.

**Comment by logalleg** [comment]
Our application has gone pretty far outside of the Cordova scope. We are hoping to rewrite it in native iOS/Android solutions soon. This "issue" can be ignored.
