### ISSUE TITLE
Plugin is not going to install

### ISSUE THREAD

**Issue by shivam5x** [katzer/cordova-plugin-local-notifications#866]
I want to add Local Notification Functionality , but plugin is not going to install and getting same error on every try, please let me know the issue.

Error: Failed to fetch plugin https://github.com/katzer/cordova-plugin-local-notifications
 via git.
Either there is a connection problems, or plugin spec is incorrect:
        Error: "git" command line tool is not installed: make sure it is accessible on you
r PATH.cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#0.8.

Thanks
SHivam

**Comment by iamwolf** [comment]
I think the error message says it all - you don't have git on your machine. Can you try to run ``git --version``? Or alternatively ``which git``.

If you're on Mac, you can install it with Homebrew or Port - ``brew install git``. On Ubuntu with ``sudo apt-get install git``. On Windows http://git-scm.com/downloads

**Comment by Yvro** [comment]
hi!
I could well download the plugin on this link: https://github.com/katzer/cordova-plugin-local-notifications

**Comment by rwillett** [comment]
Is this still an issue otherwise I'll close it?
