### ISSUE TITLE
hasPermission return true even if the permission is disabled in the notification center.

### ISSUE THREAD

**Issue by aminecmi** [katzer/cordova-plugin-local-notifications#867]
Hi,

I'm trying to use hasPermission, but it seems to returning true, even if the notifications are disabled for the app in the notification center.

Is this normal ? (I'm trying to find out if the user has not granted the permission to prompt the permission request if he tries to enable notifications from inside the app.)

Thanks for the help.

**Comment by aminecmi** [comment]
Anyone with the same problem ?

**Comment by aminecmi** [comment]
@katzer is this supposed to happen ?

**Comment by aminecmi** [comment]
can anyone help, please?

**Comment by sashagrunge** [comment]
I got the same problem, hasPermission() always return true.

**Comment by aminecmi** [comment]
Any news on this @katzer ?

**Comment by sashagrunge** [comment]
It happens on android only, always return true
