### ISSUE TITLE
iOS: Handling notifications when application process has been killed

### ISSUE THREAD

**Issue by cdahl** [katzer/cordova-plugin-local-notifications#87]
I'm wondering if anyone has a solution for getting the onclick callback method working for iOS, when the user opens the app via Notification Center after the app process has been killed.

In this case, didFinishLaunchingWithOptions is called with the notification as a launch option (UIApplicationLaunchOptionsLocalNotificationKey). When writing a native application, you could just trigger the didReceiveLocalNotification event at this point; however, it's unlikely that the Cordova application would be ready in this case.

One possible solution would be to call didReceiveLocalNotification after some time interval, but that might risk the Cordova application not being ready yet.

Has anyone else run into this? Thanks!

**Comment by camilacanhete** [comment]
Here is a solution for those who doesn't trust cordova to fire deviceready (in my case, i wanted notifications firing only when user is logged in)

So i manually modified these files inside plugins folder:

local-notification-core.js | add this function
```exports.deviceready = function () {
        this.exec('deviceready', null, null, null);
    };```

local-notification-util.js | remove or comment this function:
    ```channel.deviceready.subscribe(function () {
        // Device is ready now, the listeners are registered
        // and all queued events can be executed.
        exec(null, null, 'LocalNotification', 'deviceready', []);
    });```

update `exec(fn, null, 'LocalNotification', action, params);` to:
```if(action == 'deviceready')
            exec(null, null, 'LocalNotification', 'deviceready', []);
        else
            exec(fn, null, 'LocalNotification', action, params);```

local-notification.js | add this function
```exports.deviceready = function () {
        this.core.deviceready();
    };```

now you can call your deviceready manually, like this: `cordova.plugins.notification.local.deviceready();`
