### ISSUE TITLE
Scope is not defined

### ISSUE THREAD

**Issue by MartineNavara** [katzer/cordova-plugin-local-notifications#870]
When using cordova.plugins.notification.local.un, the following message is shown in the console:
`Uncaught ReferenceError: scope is not defined`

This error is caused by the following code in local-notification.js (line 374):

`exports.un = function (event, callback) {
    this.core.un(event, callback, scope);
};`

**Comment by lennykean** [comment]
I have a pull request pending approval for this.

**Comment by rwillett** [comment]
Is this still an issue? I don't get this.

**Comment by katzer** [comment]
Seems to be fixed already.
