### ISSUE TITLE
Schedule doesn't appear instantly in android 5.1

### ISSUE THREAD

**Issue by Flocez** [katzer/cordova-plugin-local-notifications#872]
Hi all,

Have a little problem but important in my project. I use this plugin in version 0.8.4 and Cordova CLI 6.0.0.

the notifications appear normally in android kitkat, but have too much latence in lollipop (10min).... 

Can you help me ?

Greats regards.

**Comment by jrm0695** [comment]
+1 exactly the same problem, with Android 5.1...

**Comment by kozmanbalint** [comment]
+1 exactly the same problem here with Android 6.0.1 (Nexus 5x)

**Comment by rwillett** [comment]
Is this still an issue otherwise I'll close it?
