### ISSUE TITLE
Trigger Notification more than 5 times in iOS

### ISSUE THREAD

**Issue by shivam5x** [katzer/cordova-plugin-local-notifications#873]
Hi,
   I have setup 8 weeks notification according to the day & night (Time 6 AM & 6 PM), but it trigger more than 5 times of 6 PM any time i logged-in.
I setup that, once logged-in then it will set notifications and there is localstorage that will not to set it again if user kill page ( During session of user).
As i said when i re-login it will throw bunch of notifications & at logout i am calling cancelAll() to cancel if suppose use logout the use will not get notifications in future. To setup Notification he has to login again then it will setup all that thing. 
So main motive is how can i handle the notification which I am getting in bunch of single day of early morning.
Is it possible that hasPermission and registerPermission function do that?

Please let me know if anybody know something around that.

Thanks

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as its now over a year old?
