### ISSUE TITLE
How can we change background color of local notifications

### ISSUE THREAD

**Issue by shivam5x** [katzer/cordova-plugin-local-notifications#874]
Hi,
  I want to change background color of notification , so is there anything in native code to change ?  so that i can get background color like what we want.

Thanks
Shivam

**Comment by dhjw** [comment]
Do it like this in the options: `color:'FFFFFF'
Per https://github.com/katzer/cordova-plugin-local-notifications/issues/816#issuecomment-191974219

**Comment by kamilo81** [comment]
@dhjw it does not works for me.
'
{
                id: last,
                title: obj.title,
                text: obj.body,
                color: 'ed4c0c',
                data: {
                    
                }
            }
`

**Comment by rwillett** [comment]
Is this still an issue or can it be closed? No update in nearly a year!

**Comment by rwillett** [comment]
Closed as no response from original poster
