### ISSUE TITLE
black screen problem

### ISSUE THREAD

**Issue by matrixreal** [katzer/cordova-plugin-local-notifications#876]
Hi,
i got blackscreen when i add the plugin with the new cordova ios 4.0.1
https://cordova.apache.org/announcements/2015/12/18/cordova-ios-4.0.1.html
with the old cordova ios 3.9.2 work good
so maybe the plugin needs update

**Comment by matrixreal** [comment]
any news ?

**Comment by mix3d** [comment]
Might be related to a bug with cordova ios platform. They should be releasing a new version today. There was an issue with a frozen launch screen for me, so it could be related. 

Have you tried removing this plugin and rebuilding? does it work without this plugin?

**Comment by matrixreal** [comment]
@mix3d 
yes when i remove the plugin it work perfect
but when i add it ... i got black screen after the splash screen
where can i try the new version ? any link ?

**Comment by matrixreal** [comment]
@mix3d 
any news about the update?

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as its now over a year old?
