### ISSUE TITLE
Android 4 alerts

### ISSUE THREAD

**Issue by armandsmit** [katzer/cordova-plugin-local-notifications#878]
I am using Version 0.8.4.
On Android 5 all works as expected.
On Android 4.2 I get an alert with an empty array "[]" when trying to clearAll(), 
and I get an alert returning the array of notification I was trying to set when calling schedule()

Please advise

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as its now over a year old?

**Comment by rwillett** [comment]
Closed as no response from original poster
