### ISSUE TITLE
plugin not working in ionic 

### ISSUE THREAD

**Issue by toni783** [katzer/cordova-plugin-local-notifications#881]
hi i am making a app in ionic and when i try to deploy my app in the device and get the following error in the console log. 

file:///android_asset/www/plugins/de.appplant.cordova.plugin.local-notification/www/local-notification.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///android_asset/www/plugins/de.appplant.cordova.plugin.local-notification/www/local-notification-core.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///android_asset/www/plugins/de.appplant.cordova.plugin.local-notification/www/local-notification-util.js Failed to load resource: net::ERR_FILE_NOT_FOUND
cordova.js:1431 Uncaught Error: Module de.appplant.cordova.plugin.local-notification.LocalNotification does not exist.

this is the only plugin that does not work in my app , any ideas of how to fix this? 

thx in advance

**Comment by rwillett** [comment]
It does work in Ionic on Android as we are using it on Android and IOS. 

Check its installed correctly. 

Even if you think its installed correctly, pull it and reinstall it AND the Android platform.

Rob

**Comment by gkimpson** [comment]
I have seen that error before - check the www directory is in the correct place? Have you manually moved www from its default location?

**Comment by fnokeke** [comment]
It does work on in ionic. 

**add plugin to your ionic app**
`cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications
`

**pass in cordova to your controller**
```
.controller('ChatsCtrl', function ($scope, $cordovaLocalNotification) {
    console.log ("do awesome");
});

```
**schedule event after you make sure platform is ready**
```
$ionicPlatform.ready(function () {
          $cordovaLocalNotification.schedule({
            id: 1,
            title: 'Notify Me',
            text: 'Hi, notify time.',
            every: 'day'
          });
});

```

Good to go.
