### ISSUE TITLE
Click event does not work on iOS

### ISSUE THREAD

**Issue by jlamim** [katzer/cordova-plugin-local-notifications#882]
The click event of the plugin does not work on iOS. I need to display a message on an "alert" to the user as soon as they click on the notification and open the application.

One is running on Android.

I'm using iOS 9.2.

```
cordova.plugins.notification.local.on("click", function (notification) {
   alert("Message");
});
```

**Comment by zcfan** [comment]
same here, using with ionic in this way:

```
$cordovaLocalNotification.on("click", function(notification) {
    $scope.hint = 'clicked';
});
```

trying to fix it myself, wish me luck :-)

**Comment by feerglas** [comment]
I use the same method as zcfan. To test it, I use it in a controller of an ionic-angular app. For me, this seems to work most of the time; 5 out of 6 times the click event-handler is called when I tap on the notification. Tested it in the simulator and on real device. Does somebody has a clue what the problem could be?

**Comment by zcfan** [comment]
@feerglas this `$rootScope.$on('$cordovaLocalNotification:click'` one? I don't have problem with that method. 

but the `$cordovaLocalNotification.on("click"` is a mistake, it shouldn't work at all.

**Comment by luco** [comment]
+1 here. Tried everything. None.

**Comment by Jacse** [comment]
Experiencing the same here +1

**Comment by Piranya** [comment]
+1

**Comment by Kalleno** [comment]
Same Problem on iOS10 ... 
+1

**Comment by katzer** [comment]
Please use v0.9-beta, thanks!
