### ISSUE TITLE
Plugin Not Allowed

### ISSUE THREAD

**Issue by claudiobadii** [katzer/cordova-plugin-local-notifications#884]
In platform wp8, when the plugin is called it create an error:

Error:: Plugin not allowed in config.xml. LocalNotification

in the config.xml file the string LocalNotificarion there isn't, but there is:

<feature name="Notification">
 <param name="wp-package" value="Notification" />
</feature>

**Comment by daniele-sartiano** [comment]
Same problem. Any solutions?

**Comment by Tawpie** [comment]
I believe the plugin only works for WP8.1, not 8 or earlier.
  
  
 (grammar and spelling mostly courtesy of autocorrupt)  
  
  

  
  
  
  

  
  
>

**Comment by claudiobadii** [comment]
Ok, but I try the platform wp8 on a WP8.1 device.

**Comment by Tawpie** [comment]
ah. try uninstalling wp8 (cordova platforms rm wp8) and installing platform windows (cordova platforms install windows). I don’t have my windows machine running (and with the required updates it takes hours!), so I can’t confirm for sure that will work, but I would try it.

**Comment by claudiobadii** [comment]
Yes, I confirm it. On the platform windows it works. I have problems with windows platform that show a blank screen when the app is signed. Altough, it works on debug and release version unsigned. So I use the platform wp8. In these days I will try the new versione of the platorm windows.
