### ISSUE TITLE
Can't get the trigger event to work but can schedule trigger

### ISSUE THREAD

**Issue by rwillett** [katzer/cordova-plugin-local-notifications#885]
Hi,

We're been using this plugin for the last few months and its been working fine. We're starting to use it more and can't seem to get the trigger event to 'trigger' (excuse the pun).

We're using IOS 8.4 on a real iPhone with Cordova 5.3.3.

We've been through the code example for trigger and schedule and literally cut and pasted. The schedule event fires off (we're trying to avoid the word trigger). However the trigger event doesn't. The local notification is triggered and we can see it, but the event function doesn't.

We're waiting for deviceready otherwise nothing in our app would work :) We're read through the issues as well can can see various versions of our problem but nothing recent. We can't believe we are the only ones with this problem so we figure it must be us misunderstanding what we need to do.

Here's the code but its taken from the examples on this site
```
        cordova.plugins.notification.local.on("trigger", function(notification) {
            if (debugSetupCongestionNotificationReminders)
                ConsoleLog("SetupCongestionNotificationReminders: triggered: " + notification.id);
        });

	cordova.plugins.notification.local.on("schedule", function(notification) {
           ConsoleLog("SetupCongestionNotificationReminders: scheduled: " + notification.id);
        });
```

We can see the scheduled stuff fine when its scheduled.

We want to use the trigger event to clear notifications from the notification queue once they've been triggered as scheduled notifications seem to hang around once they've been set off. We can't see any other way of doing this.

Just about everything else works on local notifications so we are puzzled by this one area.

Happy to provide any more information as requested.

Rob

**Comment by Tawpie** [comment]
Rob:

I ran into this a while ago and can’t remember all of the details, but I think some of this stems from the Human Interface Guidelines which frown on popping up notifications when the app is actually open. My solution to your underlying problem of clearing the notification queue is very brute force and so ugly as to be a little embarrassing… but it does work.

Before we quit, we clear all reminders and reschedule all the upcoming reminders in the completion callback for the clearing method. Clearing all clears the notification queue, be cautious about scheduling reminders “in the past”. We also clear and reschedule all shortly after launch in case the user quits via a force-quit/powerdown.

FWIW, I keep a copy of the reminder schedule in local storage and consult that onDeviceReady to see if somehow a reminder fired and we never handled it for whatever reason. It takes extra space, but also means I don’t have to regenerate the complete reminder schedule when we’re about to go away.

**Comment by rwillett** [comment]
@Tawpie 

Thanks for the reply. 

We have a solution to clearing the notification queue which is similar to your own, we're also checking carefully for when we schedule notifications.

There's two issues and I'm sure there are good reasons why there are two but we can't work it out.

1. Why isn't the notification cleared after its been 'used'? Whats the point of keeping it in the queue?

2. Why doesn't the 'trigger' event get called? The schedule event does and everything else we do with local notifications work so why not this?

Thanks

Rob

**Comment by rwillett** [comment]
@Tawpie 

Realised I can't answered your reply properly. 

We have no issues with the notifications being sent to the IOS drawer with the app in the foreground or background. It works fine.

Rob

**Comment by rwillett** [comment]
Ok, it now seems to work so we suspect <cough> we had coded incorrectly.

The trigger event is working but we're still not sure why, but I'm 99% sure its us.

Rob
