### ISSUE TITLE
redirect to another page from localnotification click 

### ISSUE THREAD

**Issue by joe2movies** [katzer/cordova-plugin-local-notifications#887]
Hi 

When my app is in the background and i get a local notification and i click on it the redirect works fine. However when i get multiple notification (ie 3) and each say should redirect to different html pages (from the same directory) the 1st one redirects fine (since the app was in the background) however after it's in foreground and i click on the 2nd or 3rd notification it just stays on the same page and doesn't redirect like the first notification. 

Joseph

**Comment by jjrchrds** [comment]
Any luck solving this? Also is this ionic 2?

**Comment by joe2movies** [comment]
Hi

below is the answer to your problem.

http://stackoverflow.com/questions/33511823/local-notification-schedule-and-trigger-methods-are-executing-multiple-times/36672203#36672203

**Comment by rwillett** [comment]
Closed as no response from original poster
