### ISSUE TITLE
Not working with transistorsoft/cordova-background-geolocation on IOS

### ISSUE THREAD

**Issue by markarupert** [katzer/cordova-plugin-local-notifications#888]
I am getting a crash when I try and use this notification with transistorsoft/cordova-background-geolocation. 

It seems like your plugin assumes that every notification received has your JSON schema.  The background geolocator plugin emits its own notifications, as a simple String-of-text, which you receive then attempts to JSON-decode without catching it.

Any chance this could be fixed?

**Comment by netjets-user** [comment]
+1

**Comment by netjets-user** [comment]
A big thank you!  Tried 0.8.4 version with background-geo 1.40 and cordova iOS 4.1.0 today and they work together.

**Comment by markarupert** [comment]
I see that I did not mention that the error occurs when background-geo is set to debug mode. That is when it is emitting notifications.

**Comment by netjets-user** [comment]
I had bggeo debug on and see my application messages mixed in with bggeo messages.

**Comment by markarupert** [comment]
So just to be clear, did you make a change to your code or you aren't experiencing the bug?

**Comment by netjets-user** [comment]
I made no code changes, but had recently updated to Cordova 6 and updated plugins via ionic state reset.  I had taken out local notifications plugin so I could get more diagnostics from bggeo.  Added local notifications back in and viola!

Sent from my iPhone

On Mar 12, 2016, at 10:06 PM, Mark <notifications@github.com<mailto:notifications@github.com>> wrote:


So just to be clear, did you make a change to your code or you aren't experiencing the bug?

—
Reply to this email directly or view it on GitHub<https://github.com/katzer/cordova-plugin-local-notifications/issues/888#issuecomment-195861112>.

*** *** ***
This message contains information which may be confidential and privileged. Unless you are the addressee (or authorized to receive for the addressee), you may not use, copy or disclose to anyone the message or any information contained in the message. If you have received the message in error,  please advise the sender by reply e-mail and delete the message.

**Comment by markarupert** [comment]
Perfect I will give it a go.

Thanks!

**Comment by rwillett** [comment]
This is still an issue as I use both these plugins.

It only is an issue for me with the debug flags set to true in the geolocation plugin though.

**Comment by katzer** [comment]
@rwillett With latest master could you please post here a stack trace. Guess there might be two for triggering and clicking.

**Comment by rwillett** [comment]
@katzer,

I know the problem. I haven't checked it recently as no need to do debugging with the geolocation plugin.

Let me see what I can do to get the information to you.

Rob

**Comment by rwillett** [comment]
Both work well together if debugging is turned off in the transistorsoft plugin.

**Comment by jumamfa** [comment]
That's what I was hoping too after reading other threads - however the crash persists. I have debugging disabled, and I manually schedule notifications from the Geolocation events for when a journey is complete etc.

cordova.plugins.notification.local.schedule({
            id: Math.floor(100000 + Math.random() * 900000),
            text: new Date().toLocaleTimeString() + ': ' + text,
            foreground: true,
            data: {
                type: 'something'
            }
        });

I also notice the crash isn't immediate, it can be several minutes following the notification (or even later), but only happens when I send using this plugin and speaking with the geolocation plugin developer he is saying it's absolutely not on his side.

**Comment by rwillett** [comment]
Chris has rather strong views on life :)

I know that it works fine for me with the latest versions of this plugin. We're behind the curve on the transistorsoft plugin but we've never had an issue until now. However we haven't tested IOS12.

**Comment by jumamfa** [comment]
Thanks for coming back to me - appreciate it. We are using a mix of iOS 12 and iOS 12.1 devices and noticing the issue. Does my crash report info above help at all to identify a cause?

**Comment by rwillett** [comment]
Not to me as I'm not a Objective-C developer, C yes, Objective-C no.

The question I would ask is, does it work OK on IOS11.
