### ISSUE TITLE
Turn on/off Android LED and change flash speed

### ISSUE THREAD

**Issue by djangojack** [katzer/cordova-plugin-local-notifications#889]
1. How do I set the LED on / off for notifications? Right now leaving the led property off the Android notification causes the LED to franticly flash red. 
2. How can I change the speed of the LED? Android has ledOffMs & ledOnMs. Can we hook into this? http://developer.android.com/reference/android/app/Notification.html#ledOffMS

**Comment by kanoblake** [comment]
I also have this issue.  The docs also indicate the default is FFFFFF, as per https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling#interface.

**Comment by Tawpie** [comment]
I'm working on contributing a means to set the on and off times... hopefully I'll have enough time to get it done and tested.

**Comment by StefansArya** [comment]
Will someone work on this? I also have an issue because the led blinking so fast on my android.

**Comment by rwillett** [comment]
The focus on the new work (AFAIK) is IOS10. I wouldn't expect any update in any time period at all.

If it's such a big issue, fork the Android code and update it.

**Comment by katzer** [comment]
With 0.9-beta you can do it like this:

```js
led: { color: '#FF00FF', on: 1000, off: 500 }
```

```js
led: ['#FF00FF', 1000, 500]
```

```js
led: 'FF00FF' // '#' is optional
```

```js
led: true|false
```

All led properties have default values!
