### ISSUE TITLE
Help Request

### ISSUE THREAD

**Issue by mitchellfranklin** [katzer/cordova-plugin-local-notifications#892]
Hi All,
I have looked and read through the doco but I'm either not getting it for some reason or its hitting me right in the face.

Basically I will be setting up my own push with this to get new messages from my server when the user opens up and every lets say 3 days check for new information so I can store the return data into Variables - this I have no issues with

The problem is I cant see how to write or get the code to of this plugin to work (I build out to test since I use Intel XDK).

Is it possible for someone to provide something like the below for me? im more of a see it "thats how it works" then an explanation type person.

**Every 3 days do:**
Call to server (No issues with this so not needed)
**The Code to send/display the notification with.**
- Title
- Message Body

Thanks in advance to anyone who can help out

**Comment by Tawpie** [comment]
Mitchell... You need one of the "push" plugins to have your server send the notification. This plugin schedules notifications locally, without a server. 

(grammar and spelling mostly courtesy of autocucumber)

**Comment by mitchellfranklin** [comment]
Hi Tawpie, thanks for the response,
