### ISSUE TITLE
Add bootstrap's list item to view in local notification 

### ISSUE THREAD

**Issue by almemar87** [katzer/cordova-plugin-local-notifications#894]
Hello there, I'm Ali, 

Is it possible to add a bootstrap's item or list item to be shown in 'messages' of notification? 
I mean something like this 
`
<a class="list-group-item allow-badge widget uib_w_21" data-uib="twitter%20bootstrap/list_item" data-ver="1" data-sm="iRSS" data-sc="multiple" data-rpath=".rss.channel.item[]" ng-repeat="entry in entries" ng-click="select_entry($event, entry)" data-adidx="{{$index}}">
                    <h4 class="list-group-item-heading">{{entry.pubDate}}</h4>
                    <p class="list-group-item-text">{{entry.title}}</p>
                  </a>
`
let's say {{entry title}} will be the message

Many thanks in advance

**Comment by katzer** [comment]
For Android the plugin supports the various system styles. Also showing multiple lines. However custom extensions (like intreated webview) isn't supported.
