### ISSUE TITLE
some like me?  [exception NoClassDefFoundError]

### ISSUE THREAD

**Issue by yaorunlong** [katzer/cordova-plugin-local-notifications#897]
environment:plugin 0.8.3  android 4.0.4 cordova 6.0.0

Thread [<18> pool-1-thread-2] Suspended (exception NoClassDefFoundError)
    <VM does not provide monitor information>
    ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1094
    ThreadPoolExecutor$Worker.run() line: 569
    Thread.run() line: 856

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as it's nearly a year old?
