### ISSUE TITLE
Icon issues when using flavors

### ISSUE THREAD

**Issue by tehmaestro** [katzer/cordova-plugin-local-notifications#900]
Hi, so I'm using flavors to build a bunch of applications ids. Let's say I'm building:
`com.example.a` and `com.example.b` . However, in manifest I have the following main package `com.example.main`.

  This of course means that all my resources are located in `com.example.main.R$drawable`. In order to make this plugin work, I added a function in `AssetUtil`:

```
    private String getMainName () {
        return context.getClass().getPackage().getName();
    }
```

I call this function like this:

```
    int getResIdForDrawable(String resPath) {
        int resId = getResIdForDrawable(getPkgName(), resPath);

        if (resId == 0) {
            resId = getResIdForDrawable(getMainName(), resPath);
        }
   ...
```

 Now, my problem is that the function `getResIdForDrawable` gets called multiple times, an although the first 2 or 3 times, `getMainName` get the correct `com.example.main`, the next time it is called it becomes `android` so I get an `android.R$drawable` class which does not have my icons.

 This happens because the context changes. My question is, why does the context change or why does the function gets called multiple times, thus overriding the found icon with the missing icon in `android.R`. Any ideas? Thanks a lot.

**Comment by rwillett** [comment]
I have no idea if this is an issue at all? If no further explanation provided, I'll close it.

**Comment by rwillett** [comment]
Closed as no response from original poster
