### ISSUE TITLE
UILocalNotification: could not calculate next fire date ---> cordova-plugin-local-notifications Release v0.8.4

### ISSUE THREAD

**Issue by edgardoreyes** [katzer/cordova-plugin-local-notifications#901]
I'm still having issue on iOS 9 about:
UILocalNotification: could not calculate next fire date - previous = 2016-03-10 21:42:47 +0000 : next = 2016-03-10 21:42:47 +0000 : repeatInterval = 2

I am already using the latest version of the API which is Release v0.8.4
I'm just calling a simple test below,

          var now = new Date().getTime(),
          _5_sec_from_now = new Date(now + 5*1000);

          cordova.plugins.notification.local.schedule({
              text: "Delayed Notification",
              at: _5_sec_from_now,
              sound: null
          });

**Comment by hisshash** [comment]
Same
Cordova - 6.0.0
LocalN - 0.8.4

This actually breaks my android build at `:transformClassesWithDexForDebug`
`Execution failed for task ':transformClassesWithDexForDebug'.`

**Comment by edgardoreyes** [comment]
I am closing this issue because after doing some updates on node and cordova, it solved this issue.
My node version is now 5.8.0 and Cordova 6.0.0.
