### ISSUE TITLE
Notification scheduled but not triggered - Ionic 2

### ISSUE THREAD

**Issue by ammichael** [katzer/cordova-plugin-local-notifications#902]
Hello guys!

Well, I know that Ionic 2 right now is a Beta, but I thought it could be useful to report this.

I'm trying to schedule a notification, and I even get the 'on schedule' event confirmation, but no notification is triggered at all. Here is my code:

```
cordova.plugins.notification.local.on("schedule", function (notification, state) {
	console.log(notification);
	console.log("was scheduled");
})
setNotification(lembrete){
	let notificationDate =  new Date(lembrete.dateReminder.date);
	let notification = {
		id: lembrete.id,
		at: notificationDate,
		text: lembrete.desc
	}
	this.scheduleNotification(notification);
}

scheduleNotification(notification){
	cordova.plugins.notification.local.schedule(notification);
}
```

**Comment by NorthMcCormick** [comment]
This is not just an ionic 2 issue, I'm unable to get the trigger event as well. It's very possible it could be related to iOS 9.3

**Comment by koenclaes** [comment]
In android I'm having the same issue. Some more data:
 - Cordova 6.0.0
 - Android 5.1.1

It gets triggered at first, and even once after reboot. However, 2nd time after reboot the trigger does not happen anymore.

FYI, to track this, I created a button to schedule (cordova.plugins.notification.local.schedule), and one to check if it was scheduled (isScheduled).

**Comment by ammichael** [comment]
Well, this is weird, but I've updated to iOS 9.3 from beta to release, and its working now.
