### ISSUE TITLE
Notification isn't triggered until device used.

### ISSUE THREAD

**Issue by finppp** [katzer/cordova-plugin-local-notifications#903]
So I am trying to use the application for an alarm clock style app.
The plugin is great (thanks), however, when set for long periods of time, e.g. overnight (8 hours), the alarm is only triggered when the phone is unlocked.

example: set the notification last night, to be triggered at 9.30 this morning, however I woke up at 10.00 with no alarm. as I checked my phone, the notification was triggered.

The notifications work fine short term, with the app backgrounded of closed still.

Just to check, is there a maximum time you can use? does anything go into a sleep mode?

This is for Android M by the way

Thanks,
Fin

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as it's nearly a year old?

**Comment by rwillett** [comment]
Closed as no response from original poster
