### ISSUE TITLE
Local notification vibrate when android phone is in vibrate mode.

### ISSUE THREAD

**Issue by romanornr** [katzer/cordova-plugin-local-notifications#904]
I have an issue.
Local notification vibrates when android phone is in vibrate mode.

However it doesn't vibrate when the phone sound is turned on or on mute.

Is there a way to disable the vibration when the android phone is in vibrate mode.
Because currently it triggers a short vibration.

**Comment by shawns582** [comment]
I am also trying to figure out how to do this.  Any idea or progress?

**Comment by dhjw** [comment]
yeah, i wish it wouldn't vibrate when sound is set to null too

**Comment by katzer** [comment]
Please use v0.9-beta. Now its possible to turn off vibration. Thanks
