### ISSUE TITLE
firstAt options

### ISSUE THREAD

**Issue by jcguarinpenaranda** [katzer/cordova-plugin-local-notifications#905]
Hello,

I have gone through the documentantion and part of the code, but I have not found yet any reference to the firstAt option that may be passed as an argument when creating a notification.

In the examples it says something like friday_7_pm, but i have no idea if that variable is there or I have to create it. As I am on the browser I don't have the plugin to test it out and I cannot see if it is included or not

**Comment by andreola** [comment]
I think tose are just exmples.
Well, I got it working fine after struggling a bit, by parsing a date string to milliseconds with Date.parse().

**Comment by rwillett** [comment]
Is this still an issue. Please fill out #1188.

**Comment by rwillett** [comment]
Closed as no update from from original poster.
