### ISSUE TITLE
error "Could not find method android.support.v4.app.NotificationCompat$Builder.setContentIntent"

### ISSUE THREAD

**Issue by amunters** [katzer/cordova-plugin-local-notifications#907]
Hi,
I created an Android app using Cordova 6.0.0. Everything works fine except local notifications.
When I try to schedule a notification with "cordova.plugins.notification.local.schedule"
the app crashes (see LogCat messages below).
I've already manually added android-support-v4.jar to the build path, but this doesn't help.
Any idea?

03-16 01:08:49.557: I/dalvikvm(4105): Could not find method android.support.v4.app.NotificationCompat$Builder.setContentIntent, referenced from method de.appplant.cordova.plugin.notification.Builder.applyContentReceiver
03-16 01:08:49.557: W/dalvikvm(4105): VFY: unable to resolve virtual method 193: Landroid/support/v4/app/NotificationCompat$Builder;.setContentIntent (Landroid/app/PendingIntent;)Landroid/support/v4/app/NotificationCompat$Builder;
03-16 01:08:49.557: D/dalvikvm(4105): VFY: replacing opcode 0x6e at 0x0031
03-16 01:08:49.557: I/dalvikvm(4105): Could not find method android.support.v4.app.NotificationCompat$Builder.setDeleteIntent, referenced from method de.appplant.cordova.plugin.notification.Builder.applyDeleteReceiver
03-16 01:08:49.557: W/dalvikvm(4105): VFY: unable to resolve virtual method 197: Landroid/support/v4/app/NotificationCompat$Builder;.setDeleteIntent (Landroid/app/PendingIntent;)Landroid/support/v4/app/NotificationCompat$Builder;
03-16 01:08:49.557: D/dalvikvm(4105): VFY: replacing opcode 0x6e at 0x002d
03-16 01:08:49.557: E/dalvikvm(4105): Could not find class 'android.support.v4.app.NotificationCompat$Builder', referenced from method de.appplant.cordova.plugin.notification.Builder.build
03-16 01:08:49.557: W/dalvikvm(4105): VFY: unable to resolve new-instance 65 (Landroid/support/v4/app/NotificationCompat$Builder;) in Lde/appplant/cordova/plugin/notification/Builder;
03-16 01:08:49.557: D/dalvikvm(4105): VFY: replacing opcode 0x22 at 0x000e
03-16 01:08:49.557: D/dalvikvm(4105): DexOpt: unable to opt direct call 0x00bb at 0x12 in Lde/appplant/cordova/plugin/notification/Builder;.build
03-16 01:08:49.557: W/dalvikvm(4105): threadid=21: thread exiting with uncaught exception (group=0xb3d24b20)
03-16 01:08:49.557: E/AndroidRuntime(4105): FATAL EXCEPTION: pool-1-thread-2
03-16 01:08:49.557: E/AndroidRuntime(4105): Process: net.gooddx.essense, PID: 4105
03-16 01:08:49.557: E/AndroidRuntime(4105): java.lang.NoClassDefFoundError: android.support.v4.app.NotificationCompat$Builder
03-16 01:08:49.557: E/AndroidRuntime(4105):     at de.appplant.cordova.plugin.notification.Builder.build(Builder.java:122)
03-16 01:08:49.557: E/AndroidRuntime(4105):     at de.appplant.cordova.plugin.notification.Manager.schedule(Manager.java:94)
03-16 01:08:49.557: E/AndroidRuntime(4105):     at de.appplant.cordova.plugin.notification.Manager.schedule(Manager.java:80)
03-16 01:08:49.557: E/AndroidRuntime(4105):     at de.appplant.cordova.plugin.localnotification.LocalNotification.schedule(LocalNotification.java:217)
03-16 01:08:49.557: E/AndroidRuntime(4105):     at de.appplant.cordova.plugin.localnotification.LocalNotification.access$0(LocalNotification.java:212)
03-16 01:08:49.557: E/AndroidRuntime(4105):     at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:138)
03-16 01:08:49.557: E/AndroidRuntime(4105):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-16 01:08:49.557: E/AndroidRuntime(4105):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-16 01:08:49.557: E/AndroidRuntime(4105):     at java.lang.Thread.run(Thread.java:841)

**Comment by Danbardo** [comment]
Hey,

I know you've already stated you've done this,

But I had the exact same error, I copy pasted the android-support-v4.jar into the libs folder and eclipse instantly recognized the new library (no more project errors) and I could build the app.

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as it's nearly a year old?

**Comment by rwillett** [comment]
Closed as no response from original poster
