### ISSUE TITLE
Android: Sometimes I see local notifications 2 times in the status bar

### ISSUE THREAD

**Issue by gaurav-chandra** [katzer/cordova-plugin-local-notifications#908]
Android 5.0

I am using local notifications in conjunction with push plugin. When I receive a push notification, and my app is running, I schedule a local notification. In may cases, I see 2 local notifications in the status bar with exact content. This does not happen on every phone but on some phones. Here is my code:

```
if(ionic.Platform.isAndroid()) {
                    cordova.plugins.notification.local.schedule({
                        id: notid,
                        title: payload.title,
                        text: payload.text,
                        icon: 'res://icon',
                        smallIcon: 'res://hb_icon',
                        data: {payload: payload.payload}
                    });
                }
```

**Comment by rwillett** [comment]
Is this still an issue, its nearly a year old.

**Comment by gaurav-chandra** [comment]
No, it is not an issue. Sorry for not replying earlier here.
