### ISSUE TITLE
Issue regarding local notification 

### ISSUE THREAD

**Issue by ashwin4av** [katzer/cordova-plugin-local-notifications#909]
https://github.com/katzer/cordova-plugin-local-notifications.git , I have installed the plugin successfully but could not able to execute in index.js file, I have written below code in device ready function. 

 cordova.plugin.notification.local.schedule({
                id: 1,
                title: 'I will bother you every minute',
                text: '.. until you cancel all notifications',
                sound: null,
                every: 'minute',
                autoClear: false,
                at: new Date(new Date().getTime() + 10 \* 1000)
            });

here i am getting the bellow issue : **## cannot read property local of undefined**  . 

can you please provide a solution for the particular issue. 

While debugging i am unable to find notification plugin in **cordova.plugin.**
**cordova.plugin.notification** is undefined in quick view. 

Please provide a solution. Thanks in advance. @katzer  

![notification](https://cloud.githubusercontent.com/assets/17904195/13846114/d2db4604-ec6a-11e5-8f6f-1f71f60d9cff.PNG)

![notification2](https://cloud.githubusercontent.com/assets/17904195/13846126/eb6d50c2-ec6a-11e5-95bb-ddf167dbdffe.PNG)
![notification3](https://cloud.githubusercontent.com/assets/17904195/13846166/28047614-ec6b-11e5-9be2-5cb5f2607957.PNG)

**Comment by brandoncorbin** [comment]
cordova.plugins.notification
not cordova.plugin.notification

**Comment by ashwin4av** [comment]
Hi @brandoncorbin , Thank you so much for quick response . I have tried  with **cordova.plugins.notification**  but it is not working.. same issue am facing. do i need to update any one of these cordova , npm , os , vs ,node


I am using VS2015 , Win10 , cordova 4.1.3 , npm 2.15.0, Android API 22 (5.1.1) . 

I updated cordova 6,  after update some plugins are not working.

**Comment by ashwin4av** [comment]
sorry... cordova 4.3.1

**Comment by ashwin4av** [comment]
@katzer could you please give a solution for my issue. Thank you in advance.

**Comment by Danbardo** [comment]
Run this command after building the project:
cordova prepare android
It will move the cordova_plugins.js file into your android project along with the plugins.

**Comment by jim0020** [comment]
@Danbardo : did you mean run cordova prepare _before_ building the project?

**Comment by Danbardo** [comment]
Sorry I meant after running:
Cordova platform add android

I haven't been using cordova build but yea if you are using it run cordova prepare beforehand.

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as it's over six months old?

**Comment by rwillett** [comment]
Closed as no response from original poster
