### ISSUE TITLE
Error adding plugin with example app "local-notification-example" in Cordova 6.0.0

### ISSUE THREAD

**Issue by amunters** [katzer/cordova-plugin-local-notifications#911]
Hi,
(I'm using Cordova 6.0.0 and Eclipse Mars.1).
When I run the example app "local-notification-example", notifications are not scheduled. LogCat shows many errors, see below. Does anyone have an idea?

03-17 22:53:51.274: I/System.out(2073): Error adding plugin de.appplant.cordova.plugin.localnotification.LocalNotification.
03-17 22:53:51.274: W/System.err(2073): java.lang.NullPointerException
03-17 22:53:51.274: W/System.err(2073):     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
03-17 22:53:51.274: W/System.err(2073):     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
03-17 22:53:51.274: W/System.err(2073):     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
03-17 22:53:51.274: W/System.err(2073):     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
03-17 22:53:51.274: W/System.err(2073):     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-17 22:53:51.274: W/System.err(2073):     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
03-17 22:53:51.274: W/System.err(2073):     at android.os.Handler.dispatchMessage(Handler.java:102)
03-17 22:53:51.274: W/System.err(2073):     at android.os.Looper.loop(Looper.java:136)
03-17 22:53:51.274: W/System.err(2073):     at android.os.HandlerThread.run(HandlerThread.java:61)
03-17 22:54:02.064: W/System.err(2073): java.lang.ClassNotFoundException: de.appplant.cordova.plugin.localnotification.LocalNotification
03-17 22:54:02.064: W/System.err(2073):     at java.lang.Class.classForName(Native Method)
03-17 22:54:02.064: W/System.err(2073):     at java.lang.Class.forName(Class.java:251)
03-17 22:54:02.064: W/System.err(2073):     at java.lang.Class.forName(Class.java:216)
03-17 22:54:02.064: W/System.err(2073):     at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
03-17 22:54:02.064: W/System.err(2073):     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
03-17 22:54:02.064: W/System.err(2073):     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
03-17 22:54:02.064: W/System.err(2073):     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
03-17 22:54:02.064: W/System.err(2073):     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
03-17 22:54:02.064: W/System.err(2073):     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-17 22:54:02.064: W/System.err(2073):     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
03-17 22:54:02.064: W/System.err(2073):     at android.os.Handler.dispatchMessage(Handler.java:102)
03-17 22:54:02.064: W/System.err(2073):     at android.os.Looper.loop(Looper.java:136)
03-17 22:54:02.064: W/System.err(2073):     at android.os.HandlerThread.run(HandlerThread.java:61)
03-17 22:54:02.064: W/System.err(2073): Caused by: java.lang.NoClassDefFoundError: de/appplant/cordova/plugin/localnotification/LocalNotification
03-17 22:54:02.064: W/System.err(2073):     ... 13 more
03-17 22:54:02.064: W/System.err(2073): Caused by: java.lang.ClassNotFoundException: Didn't find class "de.appplant.cordova.plugin.localnotification.LocalNotification" on path: DexPathList[[zip file "/data/app/de.appplant.localnotification.example-1.apk"],nativeLibraryDirectories=[/data/app-lib/de.appplant.localnotification.example-1, /system/lib]]
03-17 22:54:02.064: W/System.err(2073):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-17 22:54:02.064: W/System.err(2073):     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
03-17 22:54:02.064: W/System.err(2073):     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
03-17 22:54:02.064: W/System.err(2073):     ... 13 more

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as it's nearly a year old?

**Comment by rwillett** [comment]
Closed as no response from original poster.

**Comment by WakeUpMrWest** [comment]
If anyone stumbles across this issue in the future, I found that removing Android platform and then re-adding it resolved the issue:

"cordova platform remove android"

Then: 

"cordova platform add android"
