### ISSUE TITLE
ongoing true no close the notification

### ISSUE THREAD

**Issue by joneldiablo** [katzer/cordova-plugin-local-notifications#912]
I think if we touch the notification, when the flag ongoing is true, the notification should not hide

**Comment by shahidj** [comment]
Yeah, it is not allowing to set value true. It always returns false. Kindly look into this issue.

**Comment by rwillett** [comment]
if this is still an issue please use #1188 to describe the problem.

**Comment by rwillett** [comment]
No update from original poster so closing.
