### ISSUE TITLE
Question: Is it possible to set a notification every 10 minutes?

### ISSUE THREAD

**Issue by tsukasa1989** [katzer/cordova-plugin-local-notifications#914]
Hello,

I can see I can repeat a notification every minute. But is it it possible to run it every 10 minutes for example? I've seen this is possible for Android by giving a number of minutes instead of an string. But for iOS?

Thanks,

Niels

**Comment by technotip** [comment]
<b>@tsukasa1989,</b> hey can you please share your code. I'm not able to get local notification to fire in my device (android) - the scheduling function not firing :-(

**Comment by iAdil** [comment]
@technotip does it work notifications every 10 minutes on ios?

In that case ios just crashes... i want to set every 2 hour notifications, but dont know how.. can anybody  help? Thanks

**Comment by peepsilog** [comment]
What if you add $timeout equivalent to 10 mins?

**Comment by iAdil** [comment]
@peepsilog I tried, app just crashes...

**Comment by peepsilog** [comment]
What version of local notif are you using 8.4?Maybe I can try to recreate it

**Comment by iAdil** [comment]
@peepsilog are u mean "every" property, when say about  $timeout quivalent?

**Comment by iAdil** [comment]
```
            cordova.plugins.notification.local.schedule({
                id: 10,
                title: "title",
                text: "text",
                every: 'minute',
                sound: "file://sounds/water2.mp3",
            });
```

works well but 

```
            cordova.plugins.notification.local.schedule({
                id: 10,
                title: "title",
                text: "text",
                every: 10,
                sound: "file://sounds/water2.mp3",
            });

```
dont work

**Comment by mikepsinn** [comment]
@iAdil Did you ever figure out how to get `every: 10` to work on iOS?

**Comment by viniciusgcweb** [comment]
@mikepsinn not work on IOS
see this Link: https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling
On IOS variable every only string

**Comment by mikepsinn** [comment]
That's unfortunate.  iOS sucks.  I was hoping it might be an oversight in the docs. Thanks, @viniciusgcweb !

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as it's nearly a year old?

**Comment by mikepsinn** [comment]
I'm not sure if it's still a problem.  I switched to push notifications.
