### ISSUE TITLE
Not working in Phonegap CLI or Phonegap 3.0

### ISSUE THREAD

**Issue by Khaleel** [katzer/cordova-plugin-local-notifications#915]
Hey

I want to first say this is a really nice plugin but having some difficulties getting it working.

I am using an Android and Phonegap CLI. I have tried both CLI 5.0 and now Phonegap 3.5.0, this is my config.xml

`<preference name="phonegap-version" value="3.5.0" />`

In my config.xml I have tried all these combinations:

```
<plugin name="de.appplant.cordova.plugin.local-notification"  spec="0.8.1" source="pgb" />
<gap:plugin name="de.appplant.cordova.plugin.local-notification" />
<plugin name="de.appplant.cordova.plugin.local-notification" source="pgb" />
```

However the notifications do not appear - nothing happens. I have also downloaded the KitchenSink App and installed on Phonegap build and my phone and nothing again happens..

This is my code:

```
cordova.plugins.notification.local.registerPermission(function (granted) {
    // console.log('Permission has been granted: ' + granted);
});

cordova.plugins.notification.local.schedule({
    id: 1,
    title: 'Reminder',
    text: 'Dont forget to pray today.',
    every: 'minute',
    icon: 'res://icon',
    smallIcon: 'res://ic_popup_sync'
});

```

I also tried

```

cordova.plugins.notification.local.schedule({
    id: 2,
    text: "Good morning!",
    firstAt: tomorrow_at_8_am,
    every: "day" // "minute", "hour", "week", "month", "year"
});
```

Even the KitchenSink app is not working - nothing happens on the phone??

My Android version is: 5.1.1

Appreciate any feedback

**Comment by Khaleel** [comment]
Hey??

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as it's nearly a year old?
