### ISSUE TITLE
Cordova 6 + local notification working?

### ISSUE THREAD

**Issue by technotip** [katzer/cordova-plugin-local-notifications#916]
I'm using Cordova 6 for my ionic project. Local notification doesn't fire ..can you guys please share your code or let me know how I can go with troubleshooting this.

I'm testing with real device - Nexus 6p - and not in emulator or browser.

This is my code ..

``` javascript
     $cordovaLocalNotification.schedule({
        id: 10,
        title: "Meeting in 15 minutes!",
        text: "Technotip.com",
        every: 1
    }).then(function (result) {
        console.log(JSON.stringify(result)); alert(JSON.stringify(result));
      });
```

.then block isn't getting executed too :-(

<b>Update:</b> It's working. Will update with the details once I play with the code

**Comment by dcanlas** [comment]
@technotip do you mind sharing what the problem was? I am having the same issue, but for me, it is because the 'schedule' function is not exported. So I am getting '$cordovaLocalNotification.schedule is not a function'.

**Comment by smknstd** [comment]
@technotip Are you aware that attribute "every" is meant to make a notification recurrent ? Anyway, you might miss the attribute "at" or "firstAt" to specify when to trigger the notification. Cheers

**Comment by technotip** [comment]
<strong>@dcanlas, </strong>Still have some doubts in my code, trying my best to understand it. Will post the code. 

<strong>@smknstd, </strong>ya I'm aware of it. "at" is working, but "firstAt" doesn't seem to work in the newer version of the plugin.


My code is working only for the first time, the recurring feature is not working, even though I specify value for the key "every". I'm still trying to figure it out. Will get back once things are clear to me. thanks ..

**Comment by smknstd** [comment]
Yes same here, firstAt only works when I update existing notification. I managed to make it work with something like:

```
                     $window.plugin.notification.local.schedule({
                          id: name,
                          title: title,
                          text: text,
                          at: timestamp
                      },function () {
                          $window.plugin.notification.local.update({
                              id: name,
                              firstAt: timestamp,
                              every: "day"
                          });
                      });
```

Good luck !

**Comment by technotip** [comment]
will try that out ..thanks (y)

**Comment by Khaleel** [comment]
What is wrong with my code?

cordova.plugins.notification.local.registerPermission(function (granted) {
    // console.log('Permission has been granted: ' + granted);
});

cordova.plugins.notification.local.schedule({
	id:1,
	title:'Reminder',
	text:'Dont forget to pray Qadha today.',
	every:'minute',
	icon:'res://icon',
	smallIcon:'res://ic_popup_sync'
});
cordova.plugins.notification.local.schedule({
	id:2,
	text:"Good morning!",
	firstAt:tomorrow_at_8_am,
	every:"day"
});

**Comment by technotip** [comment]
@Khaleel What error are you getting?

**Comment by technotip** [comment]
I'm getting the following error message:

>      420594   error    TypeError: Cannot read property 'notification' of undefined

Previously my code was working, but once I updated Cordova to version 6.1.1 LocalNotification started throwing above error message :-(

**Comment by Variable2016** [comment]
Please make this thing more clearer, After inserting this page in an script tag what next??

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as it's nearly a year old?

**Comment by rwillett** [comment]
Closed as no response from original poster
