### ISSUE TITLE
$cordovaLocalNotification.schedule is not a function

### ISSUE THREAD

**Issue by dcanlas** [katzer/cordova-plugin-local-notifications#917]
Hi, 

I installed plugin by doing 'cordova plugin add ...' and it is technically working if I use
`$cordovaLocalNotification.add({ ... })`
but since this function is deprecated, I tried using the new 'schedule' function. However, the schedule function is being returned as not defined. and doing a console log on the $cordovaLocalNotification object, I do see that it is missing. I am using ionic and angular, and below is a screen capture from chrome 'inspect devices' when I connect my android device. Any help is appreciated! 

`$cordovaLocalNotification.schedule({
                id: "1234",
                date: moment().add(30, 's').toDate(),
                text: "hello world",
                title: "notification!"
            }).then(function () {
                console.log("The notification has been set");
            });`

![local-noti-issue-capture](https://cloud.githubusercontent.com/assets/597939/14062665/b1406140-f364-11e5-9183-8e0006fcd018.PNG)

**Comment by ibnbd** [comment]
Include ` $cordovaLocalNotification` on your controller like 

```
.controller('MyController', function ($scope, $state, $cordovaLocalNotification) {
        $cordovaLocalNotification.schedule({
            id: '222',
            text: 'Some text',
            title: 'Some title',
            icon: 'http://sciactive.com/pnotify/includes/github-icon.png'
       }).then(function () {
           console.log('Notification triggered');
      });
})
```

**Comment by technotip** [comment]
not working with Cordova v6.1.1

**Comment by dcanlas** [comment]
@ibnbd Yes, I have it like that and it doesn't work. I am on cordova 6.0.0

**Comment by abdohossam5** [comment]
@dcanlas try using cordova.plugins.notification.local.schedule instead of  $cordovaLocalNotification.schedule

**Comment by rwillett** [comment]
is this still an issue?

**Comment by rwillett** [comment]
No update from original poster so closing.

**Comment by Brhernann** [comment]
hey in the version 6.0 this don't work because was deprecated in the 5.0 version. but, what can use to send local notification?

**Comment by rwillett** [comment]
@Brhernann 

Don't hijack other peoples issues, especially when they are closed. Raise a new issue.

Rob
