### ISSUE TITLE
recurrent notifications not triggered at the exact right time

### ISSUE THREAD

**Issue by smknstd** [katzer/cordova-plugin-local-notifications#919]
Hello !

With plugin 0.8.4 and cordova 5.1.1, I schedule recurrent notifications (daily):

```
                          {
                              id: name,
                              title: title,
                              text: text,
                              firstAt: timestamp,
                              every: "day"
                          }
```

Notifications seems to work fine on some devices with Android 4.3 or >5. But when using a devices with android 4.2.2, notifications are triggered but not exactly at the right time... For example I scheduled 3 notifiactions at 12:12, 12:20 and 13:01 and they respectively were triggered at 12:13, 12:37 and 13:05.

Does someone have any clue ?

Thank you 4 your help :)

**Comment by leouze** [comment]
Same issue on some iOS devices.

**Comment by Danbardo** [comment]
I have the same issue with android, but iOS is working okay for me.

**Comment by hamza-d52** [comment]
I am also facing the same issue

**Comment by rwillett** [comment]
Android does not guarantee specific times for local notification delivery.

**Comment by rwillett** [comment]
No update from original poster so closing.
