### ISSUE TITLE
Get  the next trigger Date.

### ISSUE THREAD

**Issue by oorabi** [katzer/cordova-plugin-local-notifications#929]
I setup a notification to be every 15 minutes like following:
window.cordova.plugins.notification.local.schedule({
                    id: 5,
                    title: 'My Title',
                    text: 'My Text',
                    every: '15',
                });

How can i get the next trigger time. (If the time now is 9:05 AM, the next fire trigger time should be 9:20 AM).

Specially, i found that (in Notification.java), the isTriggered function is indirectly depending on options.getTriggerDate()

So, how can i get the next trigger date from the Javascript.

**Comment by wicktus** [comment]
Something like that ?
var In15Mins = new Date(DateCurrent.getTime() + 15*60000);

**Comment by oorabi** [comment]
Sorry, did you mean DateCurrent the current date?

What about the next scenaroi,
I setup it at 2016-04-10 09:15:00 to be every 2 weeks.
Now, the time is 2016-04-18 18:35:00.
What will the next triger time.?

And please provide the full code.
And i hope to get a built in function to get it..

**Comment by wicktus** [comment]
DateCurrent is the actual date 

For the next scenario, i think one possible solution would be  something like that :
You will need to calculate the remainder of the division (Number of days between 2016-04-10 09:15:00 and 2016-04-18 18:35:00) / 2*7 , if remainder = 0 the local notification should be triggered immediately, if remainder = x days then the notification should be triggered in 14 - x days.
```
  var buyingDate = new Date('2016-04-10 09:15:00');
                        var date2 = new Date(); // Date NOW
                        var date3 = new Date(); // Just a temporary date object 
                        var timeDiff = Math.abs(date2.getTime() - buyingDate.getTime());
                        
                        var diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24));
                        var NumberOfWeeks = 2;
                        var reste = Math.abs (diffDays % (7 * NumberOfWeeks)); //Remainder here
// days left between when your local notification needs to be triggered and the actual date
                        var DaysToRevision = (7 * NumberOfWeeks) - reste; 
                        var CalcScheduledDate = date3.setTime(date2.getTime() + (DaysToRevision * 86400000));
                        var ScheduledDate = new Date(CalcScheduledDate);
```

**Please test thoroughly this code, I did it quickly :).** I don't like the fact that people copy code without understanding the logic behind, so if you don't please tell me.

**Comment by oorabi** [comment]
Thanks wicktus,
But actually suggested to have this function in the plugins.
Something like window.cordova.plugins.notification.local.getNextTime(id,callback).

I think in some where, this value is automatically stored hence the notification can be fired on this time.

But if you resist on your solution, i want to calculate it in the call back function of getScheduled:

window.cordova.plugins.notification.local.Scheduled(5, function(notifications){
  /*TODO: Calculation of next time should go through here.*/
  /*Or to find a property or function in notifications like notification[0].nextFireTime;*/
});

**Comment by wicktus** [comment]
You do not have this function in the plugin, you can repeatedly repeat a notification
with a day, week, month year interval (only those intervals), you cannot do that with a custom interval like 3 weeks, 13 days, i can only be 1, 7, 30 or 360,15 days :).

**Comment by oorabi** [comment]
I think custom repeat can be done like this:
window.cordova.plugins.notification.local.schedule({
id: 5,
title: 'My Title',
text: 'My Text',
every: '15',
});

every :15 /*15 minutes*/
every: 1*60*24 /* 1 day*/
every: 1*60*24*7 /* 1 week.*/

And so on.
please correct me if i'm wrong.

**Comment by wicktus** [comment]
You can specify a custom minute interval only on android, not compatible with Ios...

**Comment by linkchiu** [comment]
meet the same problem. I have already set up repeat schedules. But I need show the next notification date in my app. How can I do it? Is it possible to get the next notification date?

**Comment by wicktus** [comment]
I personnally save the date in a JSON using the cordova file api along with other informations.

But you could also use the querying function to get the notification  along with its notification date, you will need to have its ID for that. 


https://github.com/katzer/cordova-plugin-local-notifications/wiki/08.-Querying

**Comment by oorabi** [comment]
Which property is storing the next date specially with the repeating notification.

**Comment by rwillett** [comment]
You need to query ALL the scheduled functions and work it out.

Is this still an issue, otherwise I'll close it.

**Comment by rwillett** [comment]
No update from original poster so closing.
