### ISSUE TITLE
add to condition to initiate local notification

### ISSUE THREAD

**Issue by gouravsen** [katzer/cordova-plugin-local-notifications#930]
I want that the notification should only trigger , if i close the app.
not when the app is open.
Is it possible to schedule it accordingly

**Comment by Danbardo** [comment]
You can use the window.onunload event. When this event is triggered you can run a function to add the notification.

**Comment by rwillett** [comment]
If this is still an issue, please fill out #1188.

**Comment by rwillett** [comment]
No update from original poster so closing.
