### ISSUE TITLE
Change icon and smallIcon

### ISSUE THREAD

**Issue by YouconnSystem** [katzer/cordova-plugin-local-notifications#931]
Hello guys.
I'm developing an app with the Intel XDK using this plugin.
The local notification work's fine. But, can I change the icon and smallIcon?
I have read and I did everything I saw on the topics. But I could not change the default icon ic_popup_reminder...
PLZ!!!! Help me!!!

**Comment by ibnbd** [comment]
Same problem here, tried all of this :

```
icon: 'http://sciactive.com/pnotify/includes/github-icon.png'
icon: '../img/icon.png'
icon: 'img/icon.png' 
icon: 'res://icon.png' 
```

But result always same :
![screen](https://cloud.githubusercontent.com/assets/2509519/14372270/d397e44c-fd60-11e5-8b36-68d99f7884c9.png)

**Comment by Danbardo** [comment]
How can you see all the possible small icons you can use? e.g. ic_popup_reminder, ic_popup_reminder?

**Comment by ibnbd** [comment]
It's fixed for me and working :+1:

**Comment by almi2001** [comment]
He,
i have same problem, the icon not change.
Tried with this:
icon: 'file://logo.png';

The icon is in the root  -> www/logo.png

Al

**Comment by remcova** [comment]
I also don't get to manage to show my own icon in the notification. Can someone help me?
My icons are in the mipmap folders, does that matter?

**Comment by aamir1995** [comment]
@ibnbd how you made it worked?

**Comment by rwillett** [comment]
See #1222 for how its solved.

**Comment by rwillett** [comment]
Closed as no update from user.
