### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by ibnbd** [katzer/cordova-plugin-local-notifications#932]
Hello there, since yesterday I was trying to fix a problem with missing icon on Android devices (ios works fine). I tried all solutions I found online eg.

```
icon: 'http://sciactive.com/pnotify/includes/github-icon.png'
icon: '../img/icon.png'
icon: 'img/icon.png' 
icon: 'res://icon.png' 
```

no matter how I change the icon property my notification shows as bellow : 

![screen](https://cloud.githubusercontent.com/assets/2509519/14372023/c27345a0-fd5e-11e5-901a-dd4244fe7208.png)

`APPNAME/platforms/android/res`

My android platform files shows as bellow :
![screen2](https://cloud.githubusercontent.com/assets/2509519/14372146/a8ab6b1a-fd5f-11e5-82e9-5c358cb369a5.png)

Code I am using to showing notification :

```
$cordovaLocalNotification.schedule({
  id: email_id,
  text: subject,
  title: sender_name,
  icon: 'http://sciactive.com/pnotify/includes/github-icon.png'
}).then(function () {
  console.log('Notification triggered');
});
```

Any help will be highly appreciated :+1:  :+1:  

Thanks

**Comment by ibnbd** [comment]
Finally made it work thanks to @mix3d
All I had to do is mention which icon to pick.

```
$cordovaLocalNotification.schedule({
  id: email_id,
  text: subject,
  title: sender_name,
  icon: 'icon',
  smallIcon: 'icon'
  }).then(function () {
    console.log('Notification triggered');
});
```


When I mentioned `icon` android system automatically picking icon from drawable folders where I have a file named icon. If you want to use another file, put that file into your drawable folder and point to it.

If your drawable is too many, in my case `drawable-hdpi`, `drawable-land-hdpi` and 18 more folders. You have to place that file inside all those folders. Make sure your file size is exact as android icon file.

**Comment by snowbreeze** [comment]
Will this solution work in IOS?

**Comment by ibnbd** [comment]
iOS automatically use system icon.

**Comment by pure4Sk** [comment]
Nice one, solved my problem. Thanks
