### ISSUE TITLE
app crashes on ios 

### ISSUE THREAD

**Issue by daphnawegner** [katzer/cordova-plugin-local-notifications#933]
as soon as the notification is called the app crashes, happens on both simulator and device

plugin version 0.8.4

**Comment by peepsilog** [comment]
Does you app call cordova.plugins.notification.local.registerPermission? This made the app crash in my case

**Comment by daphnawegner** [comment]
Thanks for the info! but no I don't call that anywhere in the app

**Comment by dolce** [comment]
I am also having the same problem, someone managed to solve?
![captura de tela 2016-04-12 as 10 49 29](https://cloud.githubusercontent.com/assets/2837790/14495729/15b846dc-0167-11e6-96eb-d32d03a615b3.png)

**Comment by kkeeling** [comment]
Yep, crashes after asking for permission (with or without an explicit call to requestPermission).

**Comment by kkeeling** [comment]
Seems like it's crashing in different places for different people. Here's where it's crashing for me...
![screen shot 2016-04-15 at 12 05 27 pm](https://cloud.githubusercontent.com/assets/366274/14567511/630b3d4e-0302-11e6-8852-a552f1fa3d02.png)

**Comment by daphnawegner** [comment]
Good to know, but I need to use the 'every' property, to set up daily notification (every:'day')

Is there a different property for this now?

**Comment by rwillett** [comment]
Is this still an issue? Its nearly a year old?

**Comment by rwillett** [comment]
Closed as no response from original poster.
