### ISSUE TITLE
Doesn't seem to work with latest Cordova

### ISSUE THREAD

**Issue by technotip** [katzer/cordova-plugin-local-notifications#934]
I'm getting this error message:

> 0     137398   error    TypeError: Cannot read property 'notification' of undefined

**I've tried:**
1. cordova.plugins.notification.local.schedule
2. window.cordova.plugins.notification.local.schedule
3. $cordovaLocalNotification.schedule

Both of them fail :-(

**I'm using**
cordova 6.1.1
ionic 1.7.14

**Comment by technotip** [comment]
I've tried a lot of things ..but this plugin doesn't seem to work with Cordova 6.1.1
Please somebody confirm.

**Comment by Danbardo** [comment]
Works for me,

Make sure that your plugins are actually installed properly for your platforms,
For andriod look in the assets folder, look for cordova_plugins.js and the plugins folder.
For iOS look in the Staging folder, same file / folder.
If the files aren't there your application won't activate the plugins correctly.

If this is your problem, the save way to copy these files over is:
cordova prepare ios
cordova prepare android

**Comment by rwillett** [comment]
Is this still an issue or can it be closed?

**Comment by rwillett** [comment]
Closed as no response from original poster.
