### ISSUE TITLE
Don't show past notification

### ISSUE THREAD

**Issue by pawelkryla** [katzer/cordova-plugin-local-notifications#935]
How can I make an app not to show past scheduled notification?

**Comment by Danbardo** [comment]
After the notification has been presented it won't be shown again unless you have set the 'every' condition.

If you have set your notification to run every so often, for example every minute, you can turn it off using the cancel function:

cordova.plugins.notification.local.cancel(id, function() {
    alert("done");
});

where id is the id of the notification you wish to cancel. Once canceled it will no longer show this notification.

**Comment by rwillett** [comment]
Is this still an issue? Its nearly a year old?

**Comment by rwillett** [comment]
Closed as no response from original poster.
