### ISSUE TITLE
Typescript Error when trying to schedule multiple notifications

### ISSUE THREAD

**Issue by jjrchrds** [katzer/cordova-plugin-local-notifications#941]
I see the following when sending an array into schedule with typescript.

`TypeScript error: /Users/joshua.richards/projects/Symbicort30/app/pages/walkthrough/walkthrough.ts(196,32): Error TS2345: Argument of type '{ id: number; title: string; text: string; data: { customProperty: string; }; }[]' is not assignable to parameter of type 'Notification'.
 Types of property 'every' are incompatible.
   Type '(callbackfn: (value: { id: number; title: string; text: string; data: { customProperty: string; }...' is not assignable to type 'string'.`

**Comment by rwillett** [comment]
This is caused by something in your code. You've defined something incorrectly.

**Comment by rwillett** [comment]
No update from original poster so closing.
