### ISSUE TITLE
Scheduled 109 notification but trigger only 64 in iOS

### ISSUE THREAD

**Issue by shivam5x** [katzer/cordova-plugin-local-notifications#942]
Hi,
   I am in the situation where i am not able to find why it is triggered only 64 notification not whole 109. 
  I am using iOS 9 ,please let me kn ow the solution.

Thanks
Shivam

**Comment by Tawpie** [comment]
@Shivam: iOS limits local notifications to 64.

Each app on a device is limited to 64 scheduled local notifications. The system discards scheduled notifications in excess of this limit, keeping only the 64 notifications that will fire the soonest. Recurring notifications are treated as a single notification.
 <>
From: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/WhatAreRemoteNotif.html

**Comment by shivam5x** [comment]
Thanks @Tawpie.
You saved my time.

**Comment by mkn20** [comment]
That is very helpful. Thank you. Is there a local notification scheduling limit for Android too? Thanks in advance and regards.
