### ISSUE TITLE
the every 'quarter' repeat schedule keyword not work

### ISSUE THREAD

**Issue by linkchiu** [katzer/cordova-plugin-local-notifications#943]
I read the iOS source code, found that there is 'quarter' keyword for repeat schedule, but it is not work. And when I change the return value of another keyword(such as 'year') to NSCalendarUnitQuarter. the year keyword is not work as well.  

Is it the issue of iOS NScalendarUnit or the plugin bug?

**Comment by rwillett** [comment]
Is this still an issue? Its not been updated in nearly a year?

**Comment by rwillett** [comment]
Is this still an issue? Its not been updated in nearly a year?

**Comment by rwillett** [comment]
No update from original poster so closing.
