### ISSUE TITLE
Is it possible to get next notification date?

### ISSUE THREAD

**Issue by linkchiu** [katzer/cordova-plugin-local-notifications#944]
I have already set up repeat schedules. But I need show the next notification date in my app. How can I do it? Is it possible to get the next notification date?

**Comment by wicktus** [comment]
I replied to you in another post : 

I personnally save the date in a JSON using the cordova file api along with other informations.

But you could also use the **querying functions** to get the notification along with its notification date, you will need to have its ID for that.

https://github.com/katzer/cordova-plugin-local-notifications/wiki/08.-Querying

it would look like that 

cordova.plugins.notification.local.get(ID, function (notifications) {
    alert(notification.at); or notification.date try both.
});

**Comment by rwillett** [comment]
Closed as no response from original poster.
