### ISSUE TITLE
ongoing : true | autoClear :false | not keeping notification persistant

### ISSUE THREAD

**Issue by jiju0nair** [katzer/cordova-plugin-local-notifications#946]
I tested the plugin for persistent notification and found that the parameter ongoing : true keeps the notification from getting swiped off but when taped it gets cleared.

Sample code used is below :
cordova.plugins.notification.local.schedule({
	id: 999,
	text: "Notification test",
	at: _5_sec_from_now,
	sound: null,
	ongoing: true,
	autoClear:false,
	data: { notify:"yes"}
});

**Comment by jiju0nair** [comment]
Solved the issue :

Add this code 
` if (notification.getOptions().isOngoing())
            return;`

in the file 
de\appplant\cordova\plugin\notification\ClickActivity.java

after the code :
`launchApp();`

Regards,
Jiju Nair

**Comment by iamola** [comment]
Any chance we can get 8.5 with this fix? Or is it available in npm somewhere?

**Comment by iamola** [comment]
This is still not fixed.
