### ISSUE TITLE
iOS Crashes when IDs are Strings

### ISSUE THREAD

**Issue by ClickSimply** [katzer/cordova-plugin-local-notifications#949]
Hey Guys,
Thanks so much for this plugin, it's been super helpful in a project I've been working on.

I've spent the past day struggling with a particular problem.  When I went to schedule a notification on iOS, my whole app would crash instantly.  The strack trace provided very little help so I spent a while debugging through the Safari console and trying to find folks who also had an issue with iOS 9 and the notifications.

Eventually I discovered that the plugin causes the app to crash to the home screen if you attempt to use strings as the push IDs instead of numbers.  Using strings works fine on Android, but not iOS.

It would be helpful if this was documented or if there was a change made to the iOS native code to handle strings as push IDs as well as numbers.

**Comment by rwillett** [comment]
Is this still an issue?

I've used strings and it doesn't cause IOS to crash.

**Comment by rwillett** [comment]
No update from original poster so closing.

**Comment by almoore** [comment]
I still see this issue. I was trying to track down why I was seeing a crash, and this was the problem. 


`
var id = "1";
...
$cordovaLocalNotification.isScheduled(id).then(function(ret) {
                return ret;
})
`
