### ISSUE TITLE
iOS - clearAll & schedule

### ISSUE THREAD

**Issue by jlmaieron** [katzer/cordova-plugin-local-notifications#950]
Hey Guys,
thanks so much for this plugin, it's been super helpful!!
I've spent the past day struggling with a particular problem. When I went to schedule a notification on iOS, When I went to set a notification in IOS, it is not shown. Currently in Android, this works perfectly.

But if I run the method "cordova.plugins.notification.local.clearAll" and then execute the method "cordova.plugins.notification.local.schedule", this works perfectly. 

What it can be happening?

The method cordova.plugins.notification.local.clearAll removes all messages from the notification center and is not useful for me.

Thank so much!!

**Comment by jlmaieron** [comment]
I tested with version 6.1.1 of cordova and update the iOS platform to version 6.1.1.
Continues displaying the message in the notification center only if the app is in foreground. In background does not show notifications.

Even applying cordova.plugins.notification.local.clearAll, the message won't display.

In android, it works correctly.

Please, I need someone to help me with this problem because I do not know the iOS coding.

Thank so much!!

**Comment by katzer** [comment]
Hi @jlmaieron,

> In background does not show notifications.

Please note that when your app is in background its not running anymore. iOS does freeze the app and stopp execution. Once it comes back to foreground it will be resumed. Thats normal behavior on iOS and on Android it may happen after certain time depend on memory, CPU usage, ...

**Comment by jlmaieron** [comment]
Hi **@katzer**,

many thanks for the answer!! But for this test I have coded the console.log for each notification alert. 
And this console.log appear before and after the notification is called in background.

Please, I need your help.

Thanks!!

**Comment by katzer** [comment]
@jlmaieron, I've tested it using the latest versions of cordova, cordova-ios, iOS, simulator and real device and I cannot see a misleading behavior.

Notifications get triggered while in foreground and __in background if they have been scheduled while in foreground__, e.g. trigger in 1 Min. and then move to background or close the app.

Please note that the simulator does not work in same way as a real device. The simulator does not pause apps in background as it's the case in real world - same applies to the windows platform by the way.

**Comment by jlmaieron** [comment]
Hi @katzer,

excuse this confusion!!. I can not understand is how an application such as whatsapp, can receive and display messages when running in background.
In my case, I need to have the same behavior for iOS and Android.

**I find it very rare that the application to crash when in background on iOS, as you mention.**

In my tests, I mentioned before, I still see the trace of console.log every 5 seconds in both foreground and background. But the notification does not appear.

I will continue investigating !! Thank you!!

**Comment by katzer** [comment]
@jlmaieron,

it's best if you take a look into the following links about _Background Execution_ and _App Life Cycle_. iOS and Android are very different systems from inside. By testing the background mode also make sure to see if its still running when not connected to USB or deployed from Xcode.

- [TheAppLifeCycle.html](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/TheAppLifeCycle/TheAppLifeCycle.html)
- [BackgroundExecution.html](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html)

> I find it very rare that the application to crash when in background on iOS, as you mention.

They do not crash, they get suspended! As you mentioned Skype - as a VoiP app it gets resumed periodically while in background.

| State | Description |
| ------- | --------------- |
| Suspended | The app is in the background but is not executing code. The system moves apps to this state automatically and does not notify them before doing so. While suspended, an app remains in memory but does not execute any code.<br/>When a low-memory condition occurs, the system may purge suspended apps without notice to make more space for the foreground app. |

As you see its not so easy for iOS but I hope it does help you.

**Comment by rwillett** [comment]
Is this still an issue? Its not been updated in nearly a year?

**Comment by rwillett** [comment]
No update from original poster so closing.
