### ISSUE TITLE
iOS notification not working.

### ISSUE THREAD

**Issue by ibnbd** [katzer/cordova-plugin-local-notifications#952]
Hey there, I am using this code to schedule notification

```
$cordovaLocalNotification.schedule({
 id: 22,
 text: 'NAME',
 title: 'VALUE'
}).then(function () {
 console.log('WORKIGN');
});
```

It was working perfect on android and iOS weeks ago and nothing been changed. Now only android working, iOS not showing notification at all. But it reach the console "WORKING". Any idea whats going on?

Thank You

**Comment by ibnbd** [comment]
The change I can remember is I have added badges plugin.

**Comment by RevProg** [comment]
Same problem.

**Comment by ibnbd** [comment]
@RevProg updating cordova ios version fixed my problem.
`ionic platform update ios`

Best of luck

**Comment by rwillett** [comment]
Is this still an issue? Its over a year old now?

**Comment by rwillett** [comment]
Closed as no response from original poster.
