### ISSUE TITLE
ongoing:true -> incompatibility with PushPlugin

### ISSUE THREAD

**Issue by vilmar23** [katzer/cordova-plugin-local-notifications#953]
Hi, I'm having a problem mantaining the notifications active when leaving(not closing) the app.

I'm using Cordova version 6.1.1, and only for Android at the moment.

I call the notification like so:

notification = {
          id:1,
          title: 'Title',
          text: 'You are listening to ' + app.song,
          icon: 'res://icon',
          smallIcon: 'res://notification',
          sound: null,
          ongoing: true,
          autoClear: false,
          led: null
 };
 cordova.plugins.notification.local.schedule(notification);

But as soon as the app goes to the background the notification dissapears.

**Comment by vilmar23** [comment]
Looking for conflicts, I am also using the last version of the phonegap-plugin-push@1.6.2

Withuot it, is seems to work fine. But with it, as soon as you leave the app(not closing it) the "persistent" notifications disapears.

Anyone has any idea how to correct it.

**Comment by rwillett** [comment]
Is this still an issue? Its nearly a year old.

**Comment by rwillett** [comment]
Closed as no response from original poster.
