### ISSUE TITLE
No vibrations on android (including temp fix)

### ISSUE THREAD

**Issue by Danbardo** [katzer/cordova-plugin-local-notifications#955]
Hey all,

I noticed that I am not getting any vibrations for push notifications on android,

A rough fix for this problem is to go into:
de.appplant.cordova.plugin.notification.Builder.java

and change:
        builder = new NotificationCompat.Builder(context)
                .setDefaults(0)
                .setContentTitle(options.getTitle())
                .setContentText(options.getText())
                .setNumber(options.getBadgeNumber())
                .setTicker(options.getText())
                .setAutoCancel(options.isAutoClear())
                .setOngoing(options.isOngoing())
                .setColor(options.getColor());

to:
        builder = new NotificationCompat.Builder(context)
                .setDefaults(0)
                .setContentTitle(options.getTitle())
                .setContentText(options.getText())
                .setNumber(options.getBadgeNumber())
                .setTicker(options.getText())
                .setAutoCancel(options.isAutoClear())
                .setOngoing(options.isOngoing())
                .setVibrate(new long[] {  0, 1000,250,1000,250,1000,250,1000,250,1000,250,1000,250})
                .setColor(options.getColor());

Note: all I added was .setVibrate(new long[] { 0, 1000,250,1000,250,1000,250,1000,250,1000,250,1000,250})

This sets a vibration of 1 second, then a 250 ms delay, then a 1 second vibration etc.etc.

**Comment by blattmann** [comment]
Awesome! I was missing that as well and your "upgrade" solved it. Thanks for sharing!
Maybe there might be an option to integrate this in the plugin config as well so we could integrate our own patterns through the JavaScript config?

**Comment by jomarocas** [comment]
Hi @Danbardo how to se in my custom schedule that sound and vibrate, for example i make somthing wrong but still no working good, i add a vibrate in a custom function 

`    if (window.cordova) {
        window.cordova.plugins.notification.local.schedule({
            id: 3,
            firstAt:_5_sec_from_now,
            title: "tomar medicamentos 1",
            text: "tomese el acetaminofen",
            every: 2,
        },vibrate);
    }

    function vibrate() {
        navigator.vibrate(2000);
    } `

i want add vibrate but inside schedule, thanks

**Comment by katzer** [comment]
A `vibrate` property has been added with v0.9-beta.

> i want add vibrate but inside schedule, thanks
If you want to vibrate the phone inside schedule and not trigger, you need to use the cordova-vibrate plugin to do yourself.
