### ISSUE TITLE
Accept 'cron' expressions to define a schedule

### ISSUE THREAD

**Issue by rupertdadey** [katzer/cordova-plugin-local-notifications#958]

**Comment by AysadKozanoglu** [comment]
it is very simple to set a schedule like cron.
you can set the schedule with the parameters "firstAt" and "every". 
A example is the best way to understand and demonstrate.

example:

cordova.plugins.notification.local.schedule({
    id: 1,
    text: "Good morning!",
    firstAt: tomorrow_at_8_am,
    every: "day" // "minute", "hour", "week", "month", "year"
});

more detail and  informations you can find here:
https://github.com/katzer/cordova-plugin-local-notifications/wiki/11.-Samples

have a nice day
Aysad Kozanoglu

**Comment by rupertdadey** [comment]
Yes but I would like to have a schedule definition that allows for example: 10am and 4pm everyday

**Comment by rihdus** [comment]
Not sure if this helps, but you could schedule 2 local notifications, one for 10am on the first Monday and second for 4pm on the same day. 
Since both notification are supposed to happen every Monday, they can be set to repeat every week.

**Comment by rwillett** [comment]
Is this still an issue? Its nearly eight months old.

**Comment by rwillett** [comment]
Closed as no response from original poster,
