### ISSUE TITLE
Can I call a function when a scheduled notification is triggered?

### ISSUE THREAD

**Issue by waleedasif322** [katzer/cordova-plugin-local-notifications#959]
Is it possible to call a function when a scheduled notification is triggered to display? Right now, it looks like the function I specify is called right away after the scheduling code is executed. Anyway to hold it off until the notification actually displays? If not, just close this issue, and I might try to take a stab at making this possible and send a pull request.

```JAVASCRIPT
        var now = new Date();
        var _10SecondsFromNow = new Date(now.getTime() + (30 * 1000));
        $cordovaLocalNotification.schedule({
          id: 1,
          title: 'Title here',
          text: 'Text here',
          at: _10SecondsFromNow
        }, function(){
          console.log('callback') // never called
        })
        .then(function(d){
          console.log(d); // called right away
        });
```

[In the docs](https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling#schedule-repeatedly), I see that we can pass a callback while scheduling notification, however I can't seem to get that callback to execute. 

http://stackoverflow.com/questions/36960727/schedule-a-function-to-run-at-a-future-time-with-cordova-on-android

And while we are on the topic, can I schedule a notification and expect it to be present a few days from now?

**Comment by waleedasif322** [comment]
For anyone else looking for this, you can get the function called on `trigger` event:

```JAVASCRIPT
  $rootScope.$on('$cordovaLocalNotification:trigger', function(event, notification, state) {
    // Your function here
  })
```

**Comment by osarhan** [comment]
Hi @waleedasif322 !

Thanks for your question and follow up answer.  Its helping me work through my own issues. 

Question for you.  Are you aware of triggering a function in the app on notification trigger, without the user to have to click an action button?  I am looking to create a scheduled event, however in background mode, ios is very picky about having these events triggered consistently. 

Was hoping to "hack" the local notification trigger to call a function in its place.  

(side note, this is for an athan app that will cast the athan onto your google speakers at the specified time in the day.)
