### ISSUE TITLE
Unable to clear a repeating notification

### ISSUE THREAD

**Issue by kjt1212** [katzer/cordova-plugin-local-notifications#960]
I am using the plugin to schedule repeating notifications. However, I am unable to clear them.

```
if (triggeredNotification.category === '<some category>') {
cordova.plugins.notification.local.clear(parseInt(triggeredNotification.id), function() {});
}
```

However, the notification does not get cleared. On the other hand if I remove the repeating attribute from these notifications then they get cleared correctly using the above code. How can I clear repeating notifications from the drawer?

**Comment by kjt1212** [comment]
@katzer is it possible to clear a repeating notification?

**Comment by rickvil27** [comment]
function cancelNotification(idNotification){
    cordova.plugins.notification.local.cancel(idNotification, function() {
        console.log("eliminada notificacion: " + idNotification);
    });
}

**Comment by kjt1212** [comment]
@rickvil27 Thanks for the response. Cancelling the notification works, however it cancels all instances of that notification. I do not want to do that. I just want to clear it from the notification drawer.

**Comment by rwillett** [comment]
Is this still an issue? Its nearly a year old.

**Comment by rwillett** [comment]
Closed as no response from original poster.
