### ISSUE TITLE
custom repeat in iOS?

### ISSUE THREAD

**Issue by linkchiu** [katzer/cordova-plugin-local-notifications#962]
I am wondering if there is a way to setting custom repeat notifications in iOS? 
My problem is I need allow to  set up notification for every 1-28 days. 
I know in android, this is not an issue, you can convert to seconds string, but how about iOS?

**Comment by kriskast** [comment]
I am also interested

**Comment by linkchiu** [comment]
@kriskast it seems impossible in iOS as the platform limite. iOS can only process specifical calendar date types such as monthly, yearly and so on. My final solution is just set a one-time notification. And set next new notification when user create an new event(in my case, user allow to set alert frequency and start date). In case user miss the notification, I also set another every day repeat schedule after the notification day to hint user that you have a overdue event.

**Comment by kriskast** [comment]
Thank you for the reply. I understand.

Just one last question, why is it that if I fire a new notification with the same id as a previously scheduled notification it doesn't get replaced on ios?

Are they limiting this as well?

Thanks again.

**Comment by linkchiu** [comment]
@kriskast I think you need cancel the previous schedule first if you want schedule a new one with the same Id.

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no response from original poster.
