### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by gitHubLie** [katzer/cordova-plugin-local-notifications#963]
how fix this?

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/zhengbin/workspace/zzApp/platforms/ios/cordova/build-debug.xcconfig,-project,zzApp.xcodeproj,ARCHS=i386,-target,zzApp,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/zhengbin/workspace/zzApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/zhengbin/workspace/zzApp/platforms/ios/build/sharedpch

**Comment by jackroscoe** [comment]
This doesn't look to be specific to the local notifications plugin.

Did you receive any other details in the build output?

**Comment by julianlecalvez** [comment]
I have the same error when I try to run `cordova build ios`
If I uninstall the cordova-plugin-local-notification, it compiles without errors. 
I tried to uninstall and reinstall ios platform, and then I tried to uninstall/reinstall the plugin. I always got the same error at build time. 

> The following build commands failed:
	CompileC build/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/i386/APPLocalNotification.o MyApp/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler


Thanks !

**Comment by jackroscoe** [comment]
@julianlecalvez do you know which version of [cordova-ios](https://github.com/apache/cordova-ios/releases) you are using?

**Comment by rwillett** [comment]
Is this still an issue? Its over six months old.

**Comment by rwillett** [comment]
No update from original poster so closing.
