### ISSUE TITLE
On Click don´t work when app is closed

### ISSUE THREAD

**Issue by Enso-Sa** [katzer/cordova-plugin-local-notifications#964]
Hi,

I am using the plugin in a project and the notifications are trigged at the correct time.
But i have a problem with onclick. If my app is opened the onclick method is called and i can show the notification id. But if my app is closed, when i click on notification the app is launched but the onclick method isn't called and nothing happened.

To schedule my notification i use the follow code:
var time = new Date();
time.setSeconds(time.getSeconds() + 10);
    
cordova.plugins.notification.local.schedule({
     id: 2,
     title: "My Title",
     text: "My text",
     firstAt: time,
     icon: "icon",
});

To catch the onclick event i use the follow code:
cordova.plugins.notification.local.on("click", function (notification) {
     alert("ID: " + notification.id); 
});

Someone can tell me if i am doing something wrong or what i need to catch the onclick event when my app is closed. 
I need to know the notification id of the notification clicked by the user.

Thanks

**Comment by abdohossam5** [comment]
same problem here

**Comment by AysadKozanoglu** [comment]
cordova.plugins.notification.local.on("click", function (notification, state) {
    alert(notification.id + " was clicked");
}, this)

works fine on a new created project with cordova.
to build a new clean project with cordova use this:

cordova create hello com.example.hello HelloWorld

It helpful to use a new blank new project to eliminate other possible issues !

**Comment by Enso-Sa** [comment]
When the app is launched and method click is called the plugin didn't load yet. 
When I put my code in a EventListener("deviceready") it work perfectly 
Thank you for your help

**Comment by jjrchrds** [comment]
@Enso-Sa is this the same as ionic 2 this.platform.ready()?
