### ISSUE TITLE
Notification triggered by other notifications

### ISSUE THREAD

**Issue by bflopez** [katzer/cordova-plugin-local-notifications#965]
I have functions that trigger a local notification when I receiving bluetooth. I also am using the cordova-geofence-plugin which has built in notifications. For some reason when a geofence notification is triggered so are my local bluetooth notification although they shouldn't be. Is there an incompatibility or maybe an id/indexing error?

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no response from original poster.
