### ISSUE TITLE
icon and smallicon

### ISSUE THREAD

**Issue by vasani-arpit** [katzer/cordova-plugin-local-notifications#966]
I have a issue with icon and small icon

    cordova.plugins.notification.local.schedule({
        id: 1,
        title: "DTH ",
        text: "Don't forget your DTH bill.",
        at: notificationDate,
        icon:'dth_notification',
        smallIcon:'dth_notification'
    });

![screenshot_2016-05-05-15-00-26](https://cloud.githubusercontent.com/assets/6497827/15040936/061b9140-12d6-11e6-8d9b-7c1757261644.png)

now the right sign is app icon. shouldn't that be 'dth_notification' ? (DTH_notification is the dish icon in assets. I've put hdpi,xhdpi,ldpi and mdpi files in all folders)
what I need is the following.
![screenshot_2016-05-05-15-00-26-000](https://cloud.githubusercontent.com/assets/6497827/15040979/50a9323a-12d6-11e6-95b7-8ecc136b0a16.jpg)
 
is that not possible with this plugin ? or this is a bug ?

**Comment by vasani-arpit** [comment]
Sorry.
Forgot "res://" in URI
     
    cordova.plugins.notification.local.schedule({
        id: 1,
        title: "DTH ",
        text: "Don't forget your DTH bill.",
        at: notificationDate,
        icon:'res://dth_notification',
        smallIcon:'res://dth_notification'
    });

**Comment by victorazevedo** [comment]
I´m trying to put image on the push and it´s not working. The sound is ok.

            var event = {
                id: 1,
                title: 'Hello!',
                sound: "file://img/ok.mp3",
                icon: "file://img/good.png",
                text: 'HI'
            };

I´m putting the image in the 'img' folder inside www folder at the project... Is it right?
What is the resolution of image for it?

**Comment by vasani-arpit** [comment]
no Image has to be in drawable folder inside android platform (if you are targeting android)
path is `<project folder>/platforms/Android/res`
find 4 folders named following
    
    drawable-hdpi
    drawable-ldpi
    drawable-mdpi
    drawable-xhdpi

 above folder will have app icon in it. put your notification icon as same size as app icon there. and then use `icon:res://iconNameWithoutExtention`
keep in mind that icon must be transparent PNG.

**Comment by victorazevedo** [comment]
I´m gettin a small icon inside a big circle. Do you know how to solve it ??

**Comment by vasani-arpit** [comment]
Yes,
your icon is not transparent.
it has to be transparent PNG.
[https://developer.android.com/design/patterns/notifications.html](https://developer.android.com/design/patterns/notifications.html)
head over to the section "Make notifications optional"

**Comment by sirius2013** [comment]
what is correct dimensions for icon?

**Comment by vasani-arpit** [comment]
@sirius2013 
depends on the device so you have to put it for all dimensions

    drawable-hdpi
    drawable-ldpi
    drawable-mdpi
    drawable-xhdpi

**Comment by sirius2013** [comment]
![image](https://cloud.githubusercontent.com/assets/5020713/18676396/05737fea-7f88-11e6-9d09-8e7b5b1f23ba.png)

**Comment by sirius2013** [comment]
I am seeing white icon on the status bar.

**Comment by vasani-arpit** [comment]
your logo has to be transparent png to be seen in notification bar.
have a look at [this link](https://blog.clevertap.com/fixing-notification-icon-for-android-lollipop-and-above/)

![blog-copy](https://cloud.githubusercontent.com/assets/6497827/18698702/e462ca60-7fe9-11e6-986d-5fa8f539473a.jpg)

**Comment by sirius2013** [comment]
Thanks 
cordova.plugins.notification.local.schedule({
    id: 1,
    title: "DTH ",
    text: "Don't forget your DTH bill.",
    at: notificationDate,
    icon:'res://dth_notification',
    smallIcon:'res://dth_notification'
});
but you used same image for icon and smallIcon?
how didd you get this result?
https://cloud.githubusercontent.com/assets/6497827/15040979/50a9323a-12d6-11e6-95b7-8ecc136b0a16.jpg

**Comment by sirius2013** [comment]
![icon](https://cloud.githubusercontent.com/assets/5020713/18704735/c4d4a8f6-801d-11e6-8c84-8aa1fb343021.png)
I tried to use this, but no lucky.

**Comment by vasani-arpit** [comment]
@sirius2013 
your file is not transparent.
in my case I had this file app_logo.png
![app_logo](https://cloud.githubusercontent.com/assets/6497827/18706268/f044a0f4-800e-11e6-95db-f8dae6bdd26c.png)
if I use this file it gives round white circle, same as you are having square.
but if I use this file icon_transparent.png
![icon_transparent](https://cloud.githubusercontent.com/assets/6497827/18706316/285d1e9e-800f-11e6-80a5-735beaabf4c7.png)
it gives proper smallicon/icon like 

    cordova.plugins.notification.local.schedule({
        id: item.id,
        title: item.T,
        text: item.n,
        at: momentDate.toDate(),
        icon: 'res://otherBigIcon',
        smallIcon: 'res://icon_transparant',
        every: item.r,
        data: notifData,
        sound: 'file://' + item.s,
        ongoing: true
    }, callback);

 ignore other values than icon,smallIcon
and if res:// is not working for you can use file:// or http://
look [10.URIs](https://github.com/katzer/cordova-plugin-local-notifications/wiki/10.-URIs)

**Comment by shrutigv** [comment]
Hi,
I am getting the blank square blank and I have placed them in drawable folder. My image is a transperant image.
 cordova.plugins.notification.local.schedule({
                id: i,              
                icon: "res://icon.png",
                smallIcon: "res://icon.png",
                at: t
            });


![icon](https://cloud.githubusercontent.com/assets/23708772/26364108/c63d180e-3fa8-11e7-81fa-30ada24c8cde.png)

**Comment by vasani-arpit** [comment]
Hi @shrutigv 

android will convert everything in single color 

basically the white part inside your icon (head and glass) should not be white it should be transparent.

please refer this [link](https://clevertap.com/blog/fixing-notification-icon-for-android-lollipop-and-above/) which I've sent earlier.

I hope this resolves your query.

**Comment by dovk** [comment]
What eventually worked for me was taking the **_drawable-xhdpi-icon_** icon (size **96x96**), renaming it  **icon.png** and placing it in two places:
&nbsp;&nbsp;&nbsp;**/src/assets/_img_**
&nbsp;&nbsp;&nbsp;**/platforms/android/res/_drawable_**
The **_drawable_** folder is a new folder created manually.
In the **local** or **geofence** notification it is reference as follows: 
```
      smallIcon: 'res://icon',
      icon: 'file://assets/img/icon.png'
```

**Comment by lathonez** [comment]
> What eventually worked for me was taking the drawable-xhdpi-icon icon (size 96x96), renaming iticon.png and placing it in two places

This helped me out, thanks. Eventually I had to do **platforms/android/app/src/main/res/drawable**.

Any icon name seems to work in this location. I have an pacakge.json script to patch:

```
    "patch-small-icon": "mkdir -p platforms/android/app/src/main/res/drawable && cp src/assets/imgs/logo.png platforms/android/app/src/main/res/drawable"
```

The two are then referenced like this:

```javascript
      smallIcon: 'res://logo.png',
      icon: 'file://assets/imgs/logo.png'
```

**Comment by joesleiman** [comment]
i made a transparent background image with png extension and with correct name m everything work fine, but i don't need a transparent background as the icon is white so it appears ugly, so how can i change the background color of the icon (big-icon)?

**Comment by Zerokk** [comment]
I've been trying multiple approaches to fix the smallIcon thingy, and none of them have worked this far. I managed to show a normal icon at the right of the notification, which is kinda okay, but I need to either remove or put a decent smallIcon, though I keep getting the "black" square.

I tried the @dovk approach, I followed the @vasani-arpit link of making a full alpha image with the visible parts in white, and everything. But nothing seems to work. Anybody can help me?

This is what I keep seeing, no matter what:

![WhatsApp Image 2019-08-20 at 16 24 33](https://user-images.githubusercontent.com/10697745/63355811-0be33c00-c367-11e9-873d-d3087db70db6.jpeg)

**Comment by dovk** [comment]
I see I didn't go into detail earlier: I added the script below as an **_after_platform_add_** hook. 
Over time I expanded as follows - 
(a) write to folder **mipmap** as well as **drawable**, 
(b) write to path **platforms\android\app\src\main\res** as well as **platforms\android\res**
```
rem create and write to **drawable**
md ...\platforms\android\res\drawable 
copy ...\src\assets\img\icon.png   ...\platforms\android\res\drawable\ 
rem create and write to **mipmap**
md ...\platforms\android\res\mipmap 
copy ...\src\assets\img\icon.png   ...\platforms\android\res\mipmap\ 
rem do the same for path **platforms\android\app\src\main\res** 
md ...\platforms\android\app\src\main\res\drawable 
copy ...\src\assets\img\icon.png   ...\platforms\android\app\src\main\res\drawable\ 
md ...\platforms\android\app\src\main\res\mipmap
copy ...\src\assets\img\icon.png   ...\platforms\android\app\src\main\res\mipmap\ 
```
I hope that might still help

**Comment by vasani-arpit** [comment]
@Zerokk 
Can you share the app logo from android project? These Mi devices are weird in terms of following android standards.

**Comment by dovk** [comment]
No access right but will send tomorrow asap

**Comment by Zerokk** [comment]
@vasani-arpit The icon I currently have, is this:

![DromousLogo_36x36](https://user-images.githubusercontent.com/10697745/63404332-1d6a2980-c3e3-11e9-8148-9ef4b046c131.png)

As a transparent one was needed, I tested these both, none of them working (not even placing them in the drawable and mipmap directories as @dovk said):

![test_transparent_logo](https://user-images.githubusercontent.com/10697745/63404350-2eb33600-c3e3-11e9-91ff-42dadd060d26.png)
![Transparent_logo](https://user-images.githubusercontent.com/10697745/63404352-31ae2680-c3e3-11e9-8580-a8b05bb9e417.png)

(yes, they are simple, test-purpose-only logos, not final logos)

**Comment by vasani-arpit** [comment]
Issue could be different than what I am thinking. Can you share your code or platform/android folder ?

**Comment by Zerokk** [comment]
@vasani-arpit I just fixed it! I just changed the ILocalNotification's smallIcon to the name "transparent_logo", which was the name I had in the mipmap-ldpi folder, and it worked. Thanks everybody for the help!

**Comment by dovk** [comment]
Yes, in about 12 hours

________________________________

**Comment by saifk5297** [comment]
@Zerokk can you please share the code and folder to place image. i am also facing same issues in mi mobile if possible ASAP

**Comment by HanojHanu** [comment]
this my location resources/notificationIcons/IconNotificationDefault-ldpi.png

in code i added

        `smallIcon : 'res://notificationIcons/IconNotificationDefault-ldpi.png',  not worked`


        `smallIcon : 'resources/notificationIcons/IconNotificationDefault-ldpi.png',  not worked`
