### ISSUE TITLE
incompatibility with ongoing:true on cordova-plugin-local-notifications 

### ISSUE THREAD

**Issue by vilmar23** [katzer/cordova-plugin-local-notifications#968]
I'm using both plugins. And I'm getting an incompatibility when I have ongoing local notifications.

The issue is when I send the application to the background the PushPlugin cancels all notifications.

I've fixed it changing the line 119 of PushPlugin.java to:

`editor.putBoolean(CLEAR_NOTIFICATIONS, jo.optBoolean(CLEAR_NOTIFICATIONS, false));`

instead of true.

My question is if by doing so, am I breaking something elsewhere?

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by vilmar23** [comment]
not sure, find it that way, but stopped working on that project a long time ago.
