### ISSUE TITLE
Ionic - trigger function seems not working in background

### ISSUE THREAD

**Issue by AlexTeixeira** [katzer/cordova-plugin-local-notifications#970]
Hello,

I currently developing an app who using this plugins. It is awesome but I'm currently facing a problem on IOS.

here the code I'm using 

```
$rootScope.$on('$cordovaLocalNotification:trigger', function (event, notification, state) {
    if(state === "background"){
            cordova.plugins.notification.local.update({
                id: 1,
                title: "Meeting in 5 minutes!"
            });
        } else {
            alert(state);
        }
)};
```

So the alert shown correctly, but when press home button, the application don't update the title.
The thing is, in my logic I wanna delay the notification (in background) if a certain condition was true.

(I already have tested without the if background, was the same )

Thanks for the help.

**Comment by lync0056** [comment]
Did you end up getting to the bottom of this? I have been pulling my hair out. The trigger will only fire for me when the application is open.

**Comment by AlexTeixeira** [comment]
Hello,

Sorry for the delay I was not available before.

I did not sorry, I'm just waiting for an update of the library which
correct this.



2016-08-11 7:07 GMT+02:00 Cameron Lynch <notifications@github.com>:

**Comment by pan100** [comment]
+1

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
No update from original poster so closing.
