### ISSUE TITLE
Trying to install this plugin 

### ISSUE THREAD

**Issue by byair74** [katzer/cordova-plugin-local-notifications#971]
Hi, trying to install this plugin from the main git repository but after 3 attempt I got some error about timeout. 

> Error: connect ETIMEDOUT
> at errnoException (net.js:904:11)
> at Object.afterConnect [as oncomplete](net.js:895:19)

The following is the command I use:
`Cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications`

Why it happened? There is alternative repository for this plugin? 

I use cordova version @4.0.0 with the latest android version for this cordova. 

Thanks

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no response from original poster.
