### ISSUE TITLE
How to Add a flag in notification 

### ISSUE THREAD

**Issue by vasani-arpit** [katzer/cordova-plugin-local-notifications#976]
First of all great plugin using it in almost all my project.

I want notification to behave like alarms. Until user clicks or swipes the notification it should keep ringing. by looking around in android SDK Docs and other stackoverflow answers I found that it is possible using flags. [reference](http://stackoverflow.com/questions/26631651/android-notification-builder-how-to-setsound-so-that-sound-plays-in-a-looper)

**My Question is how to add notification flag in above plugin ?**

I am not much of a java developer so please provide your answer in details if possible.

Thanks in Advance.

**Comment by sKuD51** [comment]
Hi, you can add the badge propriety in config like this : 
```
cordova.plugins.notification.local
					.schedule({
						id : 1, 
						title : "Title for message",
						text : "Your message",
						badge : 1, //this is the number display on your icon
						data : ""
					});
```
That's all ;-)

**Comment by vasani-arpit** [comment]
Thanks for reply.
I was taking about the flag which android native system provides over the notification object.
anyways I resolved my problem by editing notifiacation.java in plugin.
basically I need notification to behave like alarms.
here,
[https://github.com/vasani-arpit/cordova-plugin-local-notifications](https://github.com/vasani-arpit/cordova-plugin-local-notifications)
in case anyone have this kind of requirement.
