### ISSUE TITLE
Conflict with Facebook Connect 0.12.0 (phonegap-facebook-plugin)

### ISSUE THREAD

**Issue by Enso-Sa** [katzer/cordova-plugin-local-notifications#977]
Hi,

I am using the local-notifications plugin and the phonegap-facebook-plugin and i have the follow error:

/Users/Desktop/workspacePhonegap/hello/platforms/android/src/de/appplant/cordova/plugin/notification/Options.java:262: error: cannot find symbol
            return NotificationCompat.COLOR_DEFAULT;
                                     ^
  symbol:   variable COLOR_DEFAULT
  location: class NotificationCompat
/Users//Desktop/workspacePhonegap/hello/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:130: error: cannot find symbol
                .setColor(options.getColor())
                ^
  symbol:   method setColor(int)
  location: class Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/Desktop/workspacePhonegap/hello/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileDebugJava FAILED

If only use the cordova-plugin-local-notifications or only use phonegap-facebook-plugin i don't have any error, but when i used the two plugins at same time I and this error.

Any help?

**Comment by rwillett** [comment]
is this still an issue?

**Comment by rwillett** [comment]
No update from original poster so closing.
