### ISSUE TITLE
catching triggered event when app not active (question)

### ISSUE THREAD

**Issue by uzumakinaruto123** [katzer/cordova-plugin-local-notifications#978]
I have a use case where i am trying to switch user settings after delayed amount of time.

I tried using trigger event and it worked when app was active. however when app is terminated the notifications are received but the trigger callback is not fired.

Is there a way i can catch triggered event in background ? i just have to switch settings by changing localstorage variable.

Help is appreciated !

**Comment by Yusadolat** [comment]
Paste what you have been trying let review it for you.

**Comment by uzumakinaruto123** [comment]
I tried this for testing :- 
```

   
$scope.schedule=function(){

        cordova.plugins.notification.local.schedule({
          id: 1,
               text: "Single Notification",
               every: "minute"
               });


               cordova.plugins.notification.local.on("trigger", function(notification) {
              
               // this is fired only when app is active/minimized
               $localStorage.notifications = false;
            });


  };

```

I also tried making a http call on triggered event and it worked only when app was active/minimized like this :-1: 
```

            $http({
                method: 'GET',
                url: 'http://xyz.com/testapp/triggertest.php',
                data: FormData,
                headers: {'Content-Type': 'application/json'},
            })
              .success(function (data) {
              })
              .error(function (data) {
              });

```

I do get notification every minute even when app is closed. Thanks for the help

**Comment by amilino** [comment]
This issue is duplicated as #970.

It's a little bit disappointing because trigger event is not fired when application is not active.

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no response from original poster.
