### ISSUE TITLE
schedule end of notifications and vibrations each time

### ISSUE THREAD

**Issue by jomarocas** [katzer/cordova-plugin-local-notifications#979]
hi @katzer  i want personalize notifications with end date something like that, end time to schedule and vibrate each time 20 milliseconds.

```
    var now = new Date().getTime(),
    hour = new Date(now + 5*1000);
    endate =  new Date(now + 500*1000);

        if (window.cordova) {
            window.cordova.plugins.notification.local.schedule({
                firstAt:hour,
                title: "tomar medicamentos 1",
                text: "tomese el acetaminofen",
                every: 2,
                to: enddate,
                vibrate: 20
            });
        }
    }
```

this is possible in documentation no exist nothing like this, thanks

**Comment by rihdus** [comment]
Hi @katzer , I'm also looking for a 'last date' like feature for repeating notifications.
Any help is highly appreciated. Thanks.

**Comment by rwillett** [comment]
Is this still an issue? Its not been updated in nearly a year?

**Comment by rwillett** [comment]
No update from original poster so closing.
