### ISSUE TITLE
Notification icon not showing in android release apk

### ISSUE THREAD

**Issue by shawns582** [katzer/cordova-plugin-local-notifications#980]
the notification image that I am using which is http(s) seems to work on my development apk but not the release apk. Has anyone had this issue, any way to fix it?  Thanks!

**Comment by ronyrun** [comment]
+1

**Comment by avinihal05** [comment]
+1

**Comment by zyf0330** [comment]
Please see Android Monitor.

**Comment by rwillett** [comment]
Is this still an issue? Its not been updated in nearly a year?

**Comment by rwillett** [comment]
No update from original poster so closing.
