### ISSUE TITLE
Getting error in console, "Error: exec proxy not found for :: LocalNotification :: schedule"

### ISSUE THREAD

**Issue by rijine** [katzer/cordova-plugin-local-notifications#983]
Deprecated: use "registerPermission" instead.
cordova.js:989 Error: exec proxy not found for :: LocalNotification :: schedule

**Comment by rijine** [comment]
@katzer 
Cordova app with ngCOrdova + local notificaiton

**Comment by rwillett** [comment]
Is this still an issue? Its not been updated in nearly a year? If so please use template in #1188.

**Comment by rwillett** [comment]
No update from original poster so closing.
