### ISSUE TITLE
Not getting Notification

### ISSUE THREAD

**Issue by Variable2016** [katzer/cordova-plugin-local-notifications#984]
Hello Buddies I'm trying to get this local notification on my android App but not getting notified, This how i implement it.Please take a review 
` function schedule(){
     var now                  = new Date().getTime(),
    _60_seconds_from_now = new Date(now + 60*1000);

cordova.plugin.notification.local.add({
    id:      1,
    title:   'Reminder',
    message: 'Dont forget to fast.',
    repeat:  'minute',
    date:    _60_seconds_from_now
});
        }
        `
i include this in a html page and called the function, Yet not working.Thanks in Advance.

**Comment by vtellez** [comment]
Try to change this lines

`repeat: 'minute',
date: _60_seconds_from_now`

to this:

`every: 'minute',
at: _60_seconds_from_now`

**Comment by Variable2016** [comment]
Thanks @vtellez , Yet it not working. What do you suggest??

**Comment by vtellez** [comment]
Try this basic example from docs:

```
var now = new Date().getTime(),
        _5_sec_from_now = new Date(now + 5*1000);

        cordova.plugins.notification.local.schedule({
            id: 1,
            text: "Delayed Notification",
            at: _5_sec_from_now,
            badge: 1,
        });
```

**Comment by Variable2016** [comment]
Yes i inserted this to a script tag also it doesn't notified me. Can granting access cause  it??. That the only thing i suspect for now. Take a look of my index.html



<!doctype html>
<html>
	<head>
		<title>YES</title>
		
        <script type="text/javascript">
            var id = 1, dialog;

            callback = function () {
                cordova.plugins.notification.local.getIds(function (ids) {
                    showToast('IDs: ' + ids.join(' ,'));
                });
            };

            showToast = function (text) {
                setTimeout(function () {
                    if (device.platform != 'windows') {
                        window.plugins.toast.showShortBottom(text);
                    } else {
                        showDialog(text);
                    }
                }, 100);
            };

            showDialog = function (text) {
                if (dialog) {
                    dialog.content = text;
                    return;
                }

                dialog = new Windows.UI.Popups.MessageDialog(text);

                dialog.showAsync().done(function () {
                    dialog = null;
                });
            };

        </script>
		<script type="text/javascript">
            hasPermission = function () {
                cordova.plugins.notification.local.hasPermission(function (granted) {
                    showToast(granted ? 'Yes' : 'No');
                });
            };

            registerPermission = function () {
                cordova.plugins.notification.local.registerPermission(function (granted) {
                    showToast(granted ? 'Yes' : 'No');
                });
            };
        </script>

		<script type="text/javascript">
    document.addEventListener('deviceready', onDeviceReady, false);

        function onDeviceReady() {

        cordova.plugins.notification.local.schedule({
            text: "Wake up!",
            every: 0.05 // every 3 seconds
        });

        }
</script>
		 
		<script type="text/javascript" charset="utf-8" src="js/init.js"></script>
		<script>
	 if("username" in localStorage){
   // alert('yes');
	window.location = "menu.html";
   } else {
   //alert('no');
   window.location = "login.html";
  }
  schedule();
</script>
	<body>		
	<script type="text/javascript" src="cordova.js"></script>
	</body>
</html>

**Comment by vtellez** [comment]
I think you forgot something here:

```
 cordova.plugins.notification.local.schedule({
        text: "Wake up!",
        every: 0.05 // every 3 seconds
    });
```


You have to define when the first notification has to start, with "at" key 


I recommend you, to create a empty script, just with the very basic example to confirm that the plugin works fine.

**Comment by Variable2016** [comment]
creating empty script?? Do you mean i should only put it in a page ??, Like this.

 <script type="text/javascript">
document.addEventListener('deviceready', onDeviceReady, false);

    function onDeviceReady() {

    cordova.plugins.notification.local.schedule({
        text: "Wake up!",
        every: 0.05 // every 3 seconds
    });

    }
</script>

**Comment by Dineshrajaa** [comment]
I am trying to schedule a local notification which will get repeated at certain time daily but no luck here is the code
`var n_format_time = timeToNowGMT($("#txtTime").val());
    var now = new Date();
    var day = ("0" + now.getDate()).slice(-2);
    var month = ("0" + (now.getMonth() + 1)).slice(-2)
    var dateSplit = now.getFullYear() + '-' + month + '-' + day + 'T' + n_format_time;
    var notificationTime = new Date(dateSplit).toUTCString();
cordova.plugins.notification.local.schedule({
        title: 'Dowells',
        text: "Do you like to update your profile status?",
        every: $("#frequencySelect").val(),
        at:new Date(notificationTime)

    }, function() { console.warn("configured local notification") });`

**Comment by rwillett** [comment]
Is this still an issue? Its not been updated in nine months?

**Comment by rwillett** [comment]
Closed as no response from original poster
