### ISSUE TITLE
Local Notification in iOS is not working when app is in background or iPhone is locked 

### ISSUE THREAD

**Issue by winzuton** [katzer/cordova-plugin-local-notifications#985]
### Overview of the app:
-I use local notification mainly to notify user that there are promos in shops nearby.
-I use location-based trigger to push this local notification.
-I use "Schedule Single" or "Schedule Delayed" style to create the notifications (I do not use "every" component)

### Issue:
-Local Notification in iOS is not working when app is in background or iPhone is locked 

### Note:
-The issue is not happening when using "every" property (for alarms, appointments, etc.).

### Steps to Reproduce:
**Scenario A**
1. Minimize app
2. Trigger notification (location-based in my case)
3. Result: No banner style notification; No notification in the notification tray 
4. Open app
5. Result: Notification appears in the notification tray

**Scenario B**
1. Open app
2. Lock iPhone
3. Trigger notification (location-based in my case)
4. Result: No notification in the lock screen
5. Unlock iPhone
6. Result: No notification in the notification tray
5. Open app
6. Result: Notification appears in the notification tray

### Other data:
Platform: iOS 9.0 
Cordova CLI: 6.1.1
Ionic Framework Version: 1.2.4
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Version 7.3.1 (7D1014)

**Comment by winzuton** [comment]
Anyone having issues in iOS?

**Comment by winzuton** [comment]
I found out that Xcode is not simulating location when application is minimized. I can now receive badge and locked screen notifications after setting delay of local notification by 5 seconds.

**Comment by efnan34** [comment]
I am having the same problem with android. Even the app is on background mode ,The local notification is not working ? Any good solution? 

Thanks in Advance

**Comment by rwillett** [comment]
@efnan34

Do not hijack closed threads from a year ago. Raise a new issue with the template in #1188
