### ISSUE TITLE
Plugin can't be used with PhoneGap Build

### ISSUE THREAD

**Issue by andersborgabiro** [katzer/cordova-plugin-local-notifications#987]
There are build errors for both iOS and Android, even when this is the only plugin included.

I'm using cli-6.1.0 (Cordova iOS 4.1.0 / Android 5.1.1)

cordova-plugin-local-notifications-mm works with PGB, but on the other hand doesn't work with cordova-background-geolocation-lt, as separately posted.

iOS:
## PLUGIN OUTPUT

Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.2.2" for ios
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" at "1.1.2" for ios
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" at "1.4.0" for ios
Fetching plugin "cordova-plugin-statusbar" via npm
Installing "cordova-plugin-statusbar" at "2.1.3" for ios
Fetching plugin "cordova-plugin-dialogs" via npm
Installing "cordova-plugin-dialogs" at "1.2.1" for ios
Fetching plugin "cordova-plugin-appversion" via npm
Installing "cordova-plugin-appversion" at "1.0.0" for ios
Fetching plugin "cordova-plugin-x-toast" via npm
Installing "cordova-plugin-x-toast" at "2.5.1" for ios
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information" at "1.2.1" for ios
Fetching plugin "cordova-plugin-globalization" via npm
Installing "cordova-plugin-globalization" at "1.0.3" for ios
Fetching plugin "cordova-plugin-vibration" via npm
Installing "cordova-plugin-vibration" at "2.1.1" for ios
"plugman install --platform ios --project /project --plugin cordova-plugin-local-notifications": Fetching plugin "cordova-plugin-local-notifications" via npm
Installing "de.appplant.cordova.plugin.local-notification" at "0.8.2dev" for ios
Notice: org.apache.cordova.device has been automatically converted to cordova-plugin-device and fetched from npm. This is due to our old plugins registry shutting down.
Dependent plugin "cordova-plugin-device" already installed on ios.
Fetching plugin "de.appplant.cordova.common.registerusernotificationsettings" via npm
Failed to install 'de.appplant.cordova.plugin.local-notification':CordovaError: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/fetch.js:146:33
    at _rejected (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings

Android:
## PLUGIN OUTPUT

Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.2.2" for android

```
           This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
```

Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" at "1.1.2" for android
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" at "1.4.0" for android
Fetching plugin "cordova-plugin-statusbar" via npm
Installing "cordova-plugin-statusbar" at "2.1.3" for android
Fetching plugin "cordova-plugin-dialogs" via npm
Installing "cordova-plugin-dialogs" at "1.2.1" for android
Fetching plugin "cordova-plugin-appversion" via npm
Installing "cordova-plugin-appversion" at "1.0.0" for android
Fetching plugin "cordova-plugin-x-toast" via npm
Installing "cordova-plugin-x-toast" at "2.5.1" for android
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information" at "1.2.1" for android
Fetching plugin "cordova-plugin-globalization" via npm
Installing "cordova-plugin-globalization" at "1.0.3" for android
Fetching plugin "cordova-plugin-vibration" via npm
Installing "cordova-plugin-vibration" at "2.1.1" for android
Fetching plugin "cordova-plugin-local-notifications" via npm
Installing "de.appplant.cordova.plugin.local-notification" at "0.8.2dev" for android
Notice: org.apache.cordova.device has been automatically converted to cordova-plugin-device and fetched from npm. This is due to our old plugins registry shutting down.
Dependent plugin "cordova-plugin-device" already installed on android.
Notice: android.support.v4 has been automatically converted to cordova-android-support-v4 and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin "cordova-android-support-v4" via npm
Installing "cordova-android-support-v4" at "4.0.0" for android

```
    Your support is needed. If you use the local-notification plugin please support us in order to ensure further development.
    https://github.com/katzer/cordova-plugin-local-notifications#supporting

    Thank you!
```

Fetching plugin "cordova-plugin-autostart" via npm
Installing "cordova-plugin-autostart" at "2.0.1" for android
Fetching plugin "cordova-plugin-ibeacon" via npm
Installing "com.unarin.cordova.beacon" at "3.4.0" for android
Fetching plugin "cordova-plugin-geolocation" via npm
Installing "cordova-plugin-geolocation" at "2.2.0" for android
Fetching plugin "cordova-plugin-compat" via npm
Installing "cordova-plugin-compat" at "1.0.0" for android
Fetching plugin "https://github.com/robertklein/cordova-ios-security" via git clone
Repository "https://github.com/robertklein/cordova-ios-security" checked out to git ref "master" at "a76f927".
Installing "sk.kcorp.cordova.ios-security" at "0.3.0" for android
Fetching plugin "cordova-plugin-background-mode" via npm
Installing "cordova-plugin-background-mode" at "0.6.5" for android
Dependent plugin "cordova-plugin-device" already installed on android.
Fetching plugin "cordova-plugin-barcodescanner" via npm
## COMPILE OUTPUT

:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaWithJavac/project/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:564: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
/project/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:561: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileDebugJavaWithJavac'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 27.007 secs
undefined

**Comment by vtellez** [comment]
I can use this plugin neither in android with PGB 6.1.0 cli.

This is my compile output:

```
Build Date: 2016-05-29 19:49:10 +0000
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV132340Library
:prepareComAndroidSupportSupportV42340Library
:prepareComGoogleAndroidGmsPlayServicesBase840Library
:prepareComGoogleAndroidGmsPlayServicesBasement840Library
:prepareComGoogleAndroidGmsPlayServicesGcm840Library
:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:compileReleaseJavaWithJavac/project/src/com/adobe/phonegap/push/GCMIntentService.java:20: error: cannot find symbol
import android.support.v4.app.NotificationCompat.WearableExtender;
                                                ^
  symbol:   class WearableExtender
  location: class NotificationCompat
/project/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:495: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
/project/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:492: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
/project/src/com/adobe/phonegap/push/GCMIntentService.java:362: error: cannot find symbol
                    new NotificationCompat.Action.Builder(resources.getIdentifier(action.optString(ICON, ""), DRAWABLE, packageName),
                                                 ^
  symbol:   class Builder
  location: class Action
/project/src/com/adobe/phonegap/push/GCMIntentService.java:371: error: cannot find symbol
                mBuilder.extend(new WearableExtender().addActions(wActions));
                                    ^
  symbol:   class WearableExtender
  location: class GCMIntentService
/project/src/com/adobe/phonegap/push/GCMIntentService.java:596: error: cannot find symbol
            mBuilder.setColor(iconColor);
                    ^
  symbol:   method setColor(int)
  location: variable mBuilder of type Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.725 secs
undefined
```

**Comment by andersborgabiro** [comment]
I use cordova-plugin-local-notifications-mm instead, but it's also flawed (some problem with the Android Support library), as it doesn't work together with cordova-background-geolocation-lt.

**Comment by LlamaloX** [comment]
Have you been able to solve it? I have the same issue

**Comment by andersborgabiro** [comment]
As indicated, not even "-mm" worked with cordova-background-location, but I found "-san" that does, so now everything works as it should. This might change any day, which is what makes using Cordova such an exciting adventure, in sometimes a very bad way :/.

Of course this and many other issues should be fixed in the main, but it's not, and might never be, as seemingly no one is working on this plugin. I wish the Cordova core team would adopt this plugin and fix it.

**Comment by LlamaloX** [comment]
Thank you very much!

**Comment by Divyaadz** [comment]
I don't have any issue in using local notification with build.phonegap

**Comment by LlamaloX** [comment]
The issue is when using it along other plugins that use a different android support version I think

**Comment by Divyaadz** [comment]
Possible. I faced issue in phonegap build when using push notification
plugin due to different version of SDK.

**Comment by KishorMi** [comment]
Failed to install 'cordova-plugin-camera':CordovaError: Failed to fetch plugin cordova-plugin-compat via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: connect ECONNREFUSED 151.101.120.162:443
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:196:33
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
Error: Failed to fetch plugin cordova-plugin-compat via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: connect ECONNREFUSED 151.101.120.162:443

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by andersborgabiro** [comment]
Nope. Same as #986. Don't know why I posted twice.
