### ISSUE TITLE
How to display notification only if mobile is connected to Internet?

### ISSUE THREAD

**Issue by Divyaadz** [katzer/cordova-plugin-local-notifications#988]
I like to display the notification only if device is connected to internet, is it possible to do that?

**Comment by snowbreeze** [comment]
This is probably an off topic question. But my requirment is to fire a notification whenever the phone connects to a specific wifi. I have achieved this in android, But it doesnt work in iOS

```
 document.addEventListener("online", onOnline, false);
```


```
function onOnline() {
    // Handle the online event
          WifiWizard.getCurrentSSID(function(network){
                    network = network.replaceAll('"','')
                    //My wrapper over this plugin
                    sendNotification('Wifi Changed '+network,'Regular.li!',2,null,new Date(),null)
                
                        
                }, function(e){
                });
}
```

**Comment by rwillett** [comment]
This is nothing to do with local notifications. You need to code something to recognise the wifi name or the fact its offline/online. There are other plugins to do this sort of thing,.
