### ISSUE TITLE
iOS text probleme with "%" char

### ISSUE THREAD

**Issue by sKuD51** [katzer/cordova-plugin-local-notifications#989]
Hi everyone, 
I discovered a "bug" in this plugin with "%" char in text message like this : 

`cordova.plugins.notification.local
                    .schedule({
                        id : 1,
                        title : "Message title",
                        text : "10 % offer",
                        badge : 1,
                        data : ""
                    });`

This notification works fine on Android, but on iOS, character % isn't displayed. 
Somebody have this problem ? Any solution ?
thank's all !!!

**Comment by sKuD51** [comment]
So I use this simple solution : 

`var m = "10% offer";
				 if(navigator.platform === 'iPad' || navigator.platform === 'iPhone' || navigator.platform === 'iPod'){
					m =  m.replace("%","%%");
				 }
				 cordova.plugins.notification.local
					.schedule({
						id : 1, 
						title : "Message title",
						text : m,
						badge : 1,
						data : ""
					});`
If we send "%%" in notification in iOS, only one "%" will be display but on Android, "%%" is display. So I do replace() only for iOS.
If somebody has an other solution ?

**Comment by rwillett** [comment]
Is this still an issue? Its not been updated in over seven months?

**Comment by vosecek** [comment]
@rwillett Still does not work correctly.

**Comment by rwillett** [comment]
This is probably due to the sprint type handling deep down in IOS. 

I recall that putting %% in sprintf means one % character should be printed. Either way theres a discrepancy. 

I'll flag it as a bug but @sKuD51 has a simple workaround.

**Comment by sKuD51** [comment]
Yes my solution works. I do this : 
`text : ((platform === 'iOS') ? message.replace("%","%%") : message),`
where message is a string var.
