### ISSUE TITLE
Scheduling Multiple Notifications for Android

### ISSUE THREAD

**Issue by CWBlumey** [katzer/cordova-plugin-local-notifications#991]
I am trying to schedule multiple notifications for the near future within a $.each loop. This woks fine on iOS, but unfortunately only seems to create the last notification in Android. Is this a known-situation? If it's helpful, I can post code. Thanks!

**Comment by CWBlumey** [comment]
Here is the current code. It's a little bit contrived for testing, but I am more interested in identifying why the app has this behavior.

```
var i = 10;
$.each(data.Notifications, function(i, notification){ //iterate through the new notification schedule
        i += 5;
		var x = new Date(notification.NotificationTime);
		x.setMinutes(x.getMinutes() + x.getTimezoneOffset());
		var t = new Date();
		t.setSeconds(t.getSeconds() + i);
		cordova.plugins.notification.local.schedule({ //schedule  a new notification for each
			id: notification.Id, 
			title : notification.Title,
			message : JSON.stringify(x), //notification.Message,
			at : t, //convert date to usable format
			icon : notification.icon,
			data : {storeId : notification.RestaurantId}
		});
});
```

**Comment by CWBlumey** [comment]
I found the issue, and it was simply that the id's being sent over were the same, so there was a weird difference in functionality based on the performance of the phones.

**Comment by zocheyado** [comment]
@CWBlumey I am not sure how it works but I have noticed it seems like the "schedule" function actually takes a little bit to run to complete. (probably based on CPU or something else device bound) anyways because of that I have found that it works best to add a timeout function and wrap it in that, not sure why but it fixed this issue when I had it.

**Comment by CWBlumey** [comment]
@zocheyado Thanks, it appears that there was a delay. The solution in the end was to simply agglomerate all of the new notifications in to a list and schedule them at once. I think it could be potentially useful to note the delay in the documentation, as I imagine my scenario is not particularly uncommon. Thanks!

**Comment by zocheyado** [comment]
Np, do you happen to have the code for combining into one list so that one can schedule them all at once? Currently I am using loops all over :p
