### ISSUE TITLE
Notification every X seconds?

### ISSUE THREAD

**Issue by salvatoreleone** [katzer/cordova-plugin-local-notifications#993]
Hi,

is there a way to trigger the notification every X seconds? 

I know that if I supply a number that is the number of minutes. So I was expecting that `every: 0.5` would trigger the notification every 30 seconds... unfortunately this is not the case.

Am I doing it wrong or there no such a feature?

If no, where can I change in the source the default behavior to seconds instead of minutes? I've checked the js but couldn't find anything...

thanks

**Comment by rexx-org** [comment]
You would need to change the native code files. I'd like this feature also. Suggestion would be to add another option: repeatCount (default to 1). For your case you would then specify every: second, repeatCount: 30.
If you always want 30 seconds, you could hack your existing plugin source.
For iOS, change UILocalNotification+APPLocalNotification.m, method repeatIntervalInSeconds(). In default: return 30;
For Android, change notification/Options.java, method parseInterval(). If (every.equals("second")) { interval = 30 * 1000;
Don't know about Windows, don't use it.
BTW I have simply looked at the code, I have not tried these changes myself.

**Comment by rwillett** [comment]
Is this still an issue? Its not been updated in six months?

**Comment by rwillett** [comment]
No update from original poster so closing.
