### ISSUE TITLE
UIBackgroundModes key - unable to play any audible content

### ISSUE THREAD

**Issue by jlmaieron** [katzer/cordova-plugin-local-notifications#996]
Hi @katzer,

I received the following report from Apple:
  _Your app declares support for audio in the **UIBackgroundModes key in your Info.plist**, 
  but we were unable to play any audible content when the application was running in the background._

I had coded next lines and the sound isn't throwed:
`cordova.plugins.notification.local.schedule({
    text: "Wake up!",
    sound: "file://sound/ios/notification.caf"
});`

The sound directory is located into the www directory.
I have reviewed the platforms/ios directory, and the file is not there.

Please, can you help me.

Thanks

**Comment by leifwells** [comment]
Have you heard the sound at all on your device? (Not the emulator)
Can you try different file formats? (.wav, .mp3)
How are you testing this?

**Comment by jlmaieron** [comment]
Hi @leifwells,

- I heard the sound with Quicktime perfect. Not the real iPhone.
- I trying with mp3 and aif file formats with the same result.
- I have tested with above formats and I have changed the location of the directories

I hope some indication please!!

Thanks!!

**Comment by jlmaieron** [comment]
Hi @katzer,

This issue is related with [#63](url https://github.com/katzer/cordova-plugin-local-notifications/issues/63)

I've tried everything said and still doesn't work!!
I'm talking with a Mac developer to review the plugin code and what happens to phonegap.

Please, can you help me.

Thanks

**Comment by fluqueval** [comment]
Hello jlmaieron 

Have you been able to solve this problem?

I currently have the same problem.

In Xcode 8.1 I have marked compatibilities:
- Remote Locations
- Audio Background

But I have rejected the app proque I have marked "Audio Background"
If I uncheck "Audio Background" notifications do not arrive

Is there any solution?

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
Closed as no update from original poster.
