### ISSUE TITLE
Notification triggered date is not captured.

### ISSUE THREAD

**Issue by mahipalz** [katzer/cordova-plugin-local-notifications#997]
Hello,
Thanks. I am able to use this plugin for multiple notifications. However, in my application, I wanted to capture the actual trigger date for each notification. I tried to capture it using "notification.at" property in notification click event. But it shows the actual date when this notification was created. My plugin info:
****_"de.appplant.cordova.plugin.local-notification 0.8.4 "
android 5.1.1, iOS 4.0.1
cordova 6.0.0 ***_****

Is this an existing bug? here is my code for schedule to get notification at 8:30am every day:

document.addEventListener("deviceready", function(){
    var sound = device.platform == 'Android' ? 'file://sound.mp3' : 'file://sound.caf';
        cordova.plugins.notification.local.schedule({
            id: 123,
            title: "test notification",
            text: "my first notification",
            at: new Date(new Date().setHours("08","30","00"));
            every: "day",
            sound:sound
        });

```
});
```

 please help. Thanks, Mahipal

**Comment by leifwells** [comment]
As far as I can tell the notification ```at``` property never changes. It will always be the time it was originally set.

Take a look at the "trigger" event which can be captured if the app is running. Capturing that event will give you the opportunity to get the current time.

**Comment by mahipalz** [comment]
Thanks. I tried that also but everywhere the notification object returns no triggered date. For now, I made changes to the file:  "UILocalNotification+APPLocalNotification.m" to add "fireDate" also in the notification object. Here is the method after modification:
**************************************************************************************************
- (NSString*) encodeToJSON
{
    NSString* json;
    NSData* data;
    NSMutableDictionary* obj = [self.userInfo mutableCopy];
    [obj removeObjectForKey:@"updatedAt"];
    if (obj == NULL || obj.count == 0)
        return json;
     // newly added code - convert  frigate to string and add it to output dict

    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
    [dateFormatter setDateFormat:@"yyyy-MM-dd HH:mm:ss"];
    NSString *stringDate = [dateFormatter stringFromDate:self.fireDate];
    [obj setObject:stringDate forKey:@"fireDate"];

    data = [NSJSONSerialization dataWithJSONObject:obj
                                           options:NSJSONWritingPrettyPrinted
                                             error:NULL];

    json = [[NSString alloc] initWithData:data
                                 encoding:NSUTF8StringEncoding];

    return [json stringByReplacingOccurrencesOfString:@"\n"
                                           withString:@""];
}
**************************************************************************************************
Now access the fireDate as:
document.addEventListener("deviceready", function(){
     cordova.plugins.notification.local.on("click", function (notification) {        
           alert(notification.fireDate);
});
});
**************************************************************************************************
How do I do this on Android classes. Can somebody help it. Thanks

**Comment by mahipalz** [comment]
I fixed this on Android too.

**Comment by mahipalz** [comment]
Actually, "notification.at" and "notification.firedate" both are same. My problem is not resolved yet.

**Comment by mahipalz** [comment]
Actually the problem is not resolved yet. I get the same data for notification.firedate.

**Comment by rwillett** [comment]
This is the expected behaviour. The ```at:``` property doesn't change.

**Comment by rwillett** [comment]
No update from original poster so closing.
